### ISSUE TITLE
iOS LOB apps uses to be able to Roll back to previous versions

### ISSUE THREAD

**Issue by Kurag** [MicrosoftDocs/memdocs#100]
A recent change to the API and GUI disabled the ability to roll back to a previous version of the app. Can we get a "force" option so  we can bypass the “Update this app by selecting a newer line of business app package.” message?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78e4c03c-9e67-a425-2122-94194d5daea9
* Version Independent ID: d27690dc-cd34-32ee-06f5-e77ce8689989
* Content: [Add an iOS line-of-business app to Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/lob-apps-ios#feedback)
* Content Source: [memdocs/intune/apps/lob-apps-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/lob-apps-ios.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@Kurag - Thanks for the feedback. I have passed this request on to the Intune product team.
