### ISSUE TITLE
Latest information

### ISSUE THREAD

**Issue by Sculpin90** [MicrosoftDocs/memdocs#1004]
Edited 08/29/2018, is this page still up to date?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c81aa84-a76d-a24b-d314-9af35b75e4f4
* Version Independent ID: 234466b6-2dff-dcbb-f322-371fcbdb7e78
* Content: [Enroll your organization-provided macOS device in management](https://docs.microsoft.com/en-us/mem/intune/user-help/enroll-company-device-macos)
* Content Source: [memdocs/intune/user-help/enroll-company-device-macos.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/user-help/enroll-company-device-macos.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @Sculpin90, thanks for reaching out to the Intune docs team.  You're right, this article could probably benefit from a refresh. I'm going to work with the product team to verify the steps in this article and other macOS-related how-tos in this doc set. This process might take a while so thanks for your patience.

**Comment by lenewsad** [comment]
The documentation team hasn’t been able to get answers to verify the freshness of this article yet. I opened a work item for our team to track these efforts internally. Should you need any support that's not covered in this article, here are some support channels:

Device users:
* Reach out to the IT support person at your work or school for help. 

IT administrators:  
- Open a support ticket by following the steps here: [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support). 

- Post on [Microsoft Q &A](https://docs.microsoft.com/answers/products/?WT.mc_id=msdnredirect-web-msdn).

- Browse the old [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/home?forum=microsoftintuneprod). The site was recently replaced with Microsoft Q & A but still shows the old posts from our community MVPs who are very experienced, knowledgeable, and helpful.   

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
