### ISSUE TITLE
how many CNAMES are being added? 

### ISSUE THREAD

**Issue by mariajavier1** [MicrosoftDocs/memdocs#1006]
This page specifically the section "Simplify Windows enrollment without Azure AD Premium" is not clear. Am I adding 5 CNAMES altogether or just the 3 CNAMES? 

Type | Host name | Points to | TTL
-- | -- | -- | --
CNAME | EnterpriseEnrollment.company_domain.com | EnterpriseEnrollment-s.manage.microsoft.com | 1 hour
CNAME | EnterpriseRegistration.company_domain.com | EnterpriseRegistration.windows.net | 1 hour

Type | Host name | Points to | TTL
-- | -- | -- | --
CNAME | EnterpriseEnrollment.contoso.com | EnterpriseEnrollment-s.manage.microsoft.com | 1 hour
CNAME | EnterpriseEnrollment.us.contoso.com | EnterpriseEnrollment-s.manage.microsoft.com | 1 hour
CNAME | EnterpriseEnrollment.eu.contoso.com | EnterpriseEnrollment-s.manage.microsoft.com | 1 hour

It states this is for simplification for Windows enrollment. Yet a few lines below that it also has another set of CNAMES stating they are for Windows devices again and also for other devices.
"Azure Active Directory has a different CNAME that it uses for device registration for iOS/iPadOS, Android, and **Windows** devices."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f1e311c-c5ff-1c68-028d-e4fddda23324
* Version Independent ID: 1d2174e5-8984-8d9c-34c5-dfbcc619b410
* Content: [Set up enrollment for Windows devices by using Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/windows-enroll)
* Content Source: [memdocs/intune/enrollment/windows-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/windows-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
9050278

**Comment by ErikjeMS** [comment]
Repinged PM...

**Comment by o-l-a-v** [comment]
You add two CNAMEs per domain you use as domain in you UserPrincipalNames. Usually you only use maindomain.com. But one can add multiple subdomains.maindomain.com. If users with username@subdomain.maindomain.com should be able to enroll, you add two CNAMEs for the subdomain.maindomain.com as well.
