### ISSUE TITLE
IKEv2 settings

### ISSUE THREAD

**Issue by IzumiWakabayashi** [MicrosoftDocs/memdocs#1008]
On MEM (https://endpoint.mictosoft.com/), when IKEv2 settings> Client Authentication Type> Machine Authentication is selected in iOS / IKEv2 profile, the profile that can be specified in [Authentication certificate] is limited to SCEP, and PKCS is Cannot be selected.
Please state that the certificate profile must be a SCEP certificate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a4e2ec1-b0f9-aee4-e7df-eed9ab445091
* Version Independent ID: bff2d59c-7fe4-fca0-60ad-d39438fe8f27
* Content: [Configure VPN settings to iOS/iPadOS devices in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/vpn-settings-ios)
* Content Source: [memdocs/intune/configuration/vpn-settings-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/vpn-settings-ios.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@IzumiWakabayashi Thank you for raising this issue. This behavior will be fixed in a future release (no ETA).
