### ISSUE TITLE
Windows Analytics is not longer available as a free solution, please update this.

### ISSUE THREAD

**Issue by Field5555** [MicrosoftDocs/memdocs#101]
While Windows Analytics was retired on January 31, 2020, support for Update Compliance has continued through the Azure Portal; however, please note the following updates: As of March 31, 2020, The Windows Defender Antivirus reporting feature of Update Compliance is no longer supported and will soon be retired. (https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-monitor)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7024ad8-b24b-598c-8b16-2da8bc15e9e4
* Version Independent ID: 230e96a7-e771-e6dd-d5f4-ac8b514fb4d4
* Content: [Use Update Compliance reports for Windows Updates in Microsoft Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/windows-update-compliance-reports#feedback)
* Content Source: [memdocs/intune/protect/windows-update-compliance-reports.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/windows-update-compliance-reports.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@field5555  Thanks for the feedback. I’ve passed the information to our product team to ensure everyone is on the same page. Content will receive a light revision in line with this change.
