### ISSUE TITLE
Use PKI Certificates when available is required since 2006 HFRU

### ISSUE THREAD

**Issue by Yupiter2005** [MicrosoftDocs/memdocs#1010]
In Prerequisite section we need to make sure the customers have "Use PKI Certificates when available" checkbox set.

We have had the envs using the IBCM without this checkbox (HTTP internally, HTTPS externally), and the it has been working until the change in 2006 HFRU:
https://support.microsoft.com/en-us/help/4578605/update-rollup-for-microsoft-endpoint-configuration-manager-version-200

`Clients incorrectly attempt to use PKI certificates for communication, even if the option Use PKI client certificate (client authentication capability) when available is disabled on the Communication Security tab of Site Properties.
`

Before 2006 HFRU it has been working for years as a bug :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0894e83-ae5e-960f-169c-cb5ea0e85a10
* Version Independent ID: 2a3ad459-44e9-7fe1-f2b9-a6b8ad58afa9
* Content: [Internet-based client management - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/plan-internet-based-client-management)
* Content Source: [memdocs/configmgr/core/clients/manage/plan-internet-based-client-management.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/plan-internet-based-client-management.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Yupiter2005 for the feedback, good catch.
