### ISSUE TITLE
How to renew certificate

### ISSUE THREAD

**Issue by davidstan1234** [MicrosoftDocs/memdocs#1011]
Could you add some documentation or link to documentation that discusses the proper method of renewing this certificate?  Our company policy has a 2year max on certificates and we would like some more details on the proper method for cert renewal.  
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15f70f31-c5d5-562a-d3af-8c52bc20c89a
* Version Independent ID: cf459805-6802-eb92-fc89-14c487c9915a
* Content: [Encrypt recovery data - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/protect/deploy-use/bitlocker/encrypt-recovery-data)
* Content Source: [memdocs/configmgr/protect/deploy-use/bitlocker/encrypt-recovery-data.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/protect/deploy-use/bitlocker/encrypt-recovery-data.md)
* Product: **configuration-manager**
* Technology: **configmgr-protect**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @davidstan1234, good question! Let me check with engineering

**Comment by aczechowski** [comment]
As noted in the [Create certificate](https://docs.microsoft.com/mem/configmgr/protect/deploy-use/bitlocker/encrypt-recovery-data#create-certificate) section:

> The certificate expiration date is not checked or enforced by SQL Server when the certificate is used for database encryption as is the case here.

So you don't _have_ to renew the certificate. If you want to, the process would be to create a new certificate and then rotate it. I'm adding information to this article on how to do that for another reason (SQL Server upgrade), but the steps should still apply for this scenario.
