### ISSUE TITLE
Export-IntunePublicKey : They key PFXEncryptionKey does not exist so there is no public key to export

### ISSUE THREAD

**Issue by MichalKafka** [MicrosoftDocs/memdocs#1014]
Any keyname I am using returns the same "They key XXX does not exist so there is no public key to export". What keyname shall use there?

**Comment by ErikjeMS** [comment]
@MichalKafka Can you provide the URL to the article for this issue?

**Comment by Brenduns** [comment]
@MichalKafka   I've consulted with our engineering team, and while they weren’t sure of the source of the issue, they thought this could be related to the public/private Windows cryptography key that’s created to encrypt the PFX passwords before they’re uploaded to Intune. The keyname is the name of the public/private key pair, which would have the name given to it when created.  

This isn’t something we can troubleshoot via this doc feedback forum. The recommendation is to contact support for deeper  assistance if after reviewing the initial process used to generate and store the public/private key pair (Windows cryptography, a hardware security module, or another type of cryptography), the name given to the key pair then doesn't work for the Export functionality.
