### ISSUE TITLE
iOS supported OS varies by model - how to accommodate?

### ISSUE THREAD

**Issue by rasldasl** [MicrosoftDocs/memdocs#1015]
Apple is still releasing security updates for iOS 12 but only for these models:
iPhone 5s, iPhone 6 and 6 Plus, iPad Air, iPad mini 2 and 3, iPod touch (6th generation)
The other models only receive updates to iOS 14.

Is there any way to set a device as compliant if it has a minimum supported OS but not allow compliance on a device that supports a newer OS? 
example: mark iPhone 6 compliant with 12.4.9 but only mark iPhone 6s compliant with iOS 14

**Comment by ErikjeMS** [comment]
@rasldasl Can you provide the URL to the article for this issue?

**Comment by rasldasl** [comment]
https://docs.microsoft.com/en-us/mem/intune/protect/compliance-policy-create-ios

Sent from my iPhone

On Nov 20, 2020, at 12:00 PM, Erik Kjerland <notifications@github.com> wrote:

﻿

@rasldasl<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frasldasl&data=04%7C01%7C%7Cfd835f512938437cfd9508d88d7e250e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637414920205136223%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Pnt6CbGyHy8WuNt%2B%2BvV1ijR%2FL5JJARYiv2HlCSJaXTk%3D&reserved=0> Can you provide the URL to the article for this issue?

**Comment by Brenduns** [comment]
Investigating.

**Comment by Brenduns** [comment]
@rasldasl   After running down the right contacts in our engineering team, I regret to say this isn’t supported scenario. There isn’t any guidance we can provide to work around this in a supported method, that wouldn’t create other problems best avoided (like duplicate or overlapping policies assigned to the same users or devices).

However, our engineering team has created an internal work item to track feedback and requests for this area. They also recommend that you add this to our UserVoice feedback channel (https://microsoftintune.uservoice.com/forums/291681-ideas). The feedback channel submission would help double down on the need for this, as it’s one of the core paths for community and customer asks to be turned into product changes.

**Comment by rasldasl** [comment]
I have come up with a workaround but it's not very elegant. I'll have to create dynamic device groups for the devices that support a lower minimum OS version and apply a different compliance policy to that group (and exclude the group from the main policy). My example still stands, though, as Apple just released iOS 12.5 this week but only for older devices. 
For Android there is an additional setting for security patch level but it moves around depending on type of management. 
Full managed, dedicated, and corporate owned it's under Device Properties. Personally-owned with work profile (Android Enterprise) and Android Device Administrator it's under System Security. 
I'll look for or submit a user voice but in general what we want to enforce is that a device is getting security updates which usually correlates to an OS update but not always to a minimum OS version. 
Device with iOS 12.5 is up to date and secure, device with 13.x is NOT as any device supporting 13 should be on 14. Android, of course, is heavily fragmented. There are devices on Android 8 with current security updates and devices on 9 that should be updated to 10 (and so on).
