### ISSUE TITLE
Fix step 2

### ISSUE THREAD

**Issue by sf5414** [MicrosoftDocs/memdocs#1018]
Configure the site
In the Configuration Manager console, go to the Administration workspace, expand Site Configuration, and select the Sites node. Select the site and choose Properties in the ribbon.

Switch to the Client Computer Communication tab.

Step 2 on this page should say select the Communication Security tab.  There isn't a Client computer communications tab.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac80195f-d429-0ffd-2a32-fb23e57c6697
* Version Independent ID: c4e06cf7-5c50-8fb4-d8b9-ecce874f118b
* Content: [Enhanced HTTP - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/hierarchy/enhanced-http)
* Content Source: [memdocs/configmgr/core/plan-design/hierarchy/enhanced-http.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/hierarchy/enhanced-http.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @sf5414 for the feedback. That tab was renamed in version 1906, so since 1902 is now out of support, we're good to replace those references. There are several others in the content, so I'll handle them all.

**Comment by aczechowski** [comment]
I put in a fix for this issue with the 2010 current branch content. This issue will auto close when that pull request merges, but the change won't be live until we release 2010.
