### ISSUE TITLE
Please help me out

### ISSUE THREAD

**Issue by Poopooracoocoo** [MicrosoftDocs/memdocs#102]
When I try to install an app  that is for a certain device, it doesn't let me install it. Is it possible to override that on Windows 10? I'm using PowerShell and the it's an eappxbundle file. It's designed for Xbox One but it should work just fine on W10, even if only in fullscreen mode. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 925b5dc0-9a45-5ac2-7132-80f8cc158d66
* Version Independent ID: ceb01ba2-5a90-1fda-ed25-36887099da71
* Content: [Windows 10 app deployment by using Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-windows-10-app-deploy#feedback)
* Content Source: [memdocs/intune/apps/apps-windows-10-app-deploy.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/apps-windows-10-app-deploy.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@Poopooracoocoo - Thanks for sharing this with the Intune documentation team. If you are still running into problems related to this issue, we want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

This question is in our documentation feedback channel and it may be best to handle this question as a support request. For this reason, I'm closing this issue. Please use the above channels if you don't already have a solution.

**Comment by Poopooracoocoo** [comment]
@ErikjeMS I'm not actually using Intune. I just tried searching for help and clicked on the first Microsoft link. I'm trying to use Powershell to install a UWP app that targets Xbox.
