### ISSUE TITLE
Profile Always Fails for System Account

### ISSUE THREAD

**Issue by philjorgensen** [MicrosoftDocs/memdocs#1034]
Following this guide works and the system encrypts using the correct algorithm set in the Profile, however the Profile Assignment status always results in a failure.

Under Device status, the Deployment Status of the user logging into the device shows as "Succeeded" but the System account always shows as "Error", causing the entire Profile Assignment to fail.  How can this be avoided?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ff0284d-e040-ea4a-dd6e-8184914ea702
* Version Independent ID: c756c9fe-f38a-e121-68a3-72489921e0e5
* Content: [Setting the BitLocker encryption algorithm for Autopilot devices](https://docs.microsoft.com/en-us/mem/autopilot/bitlocker)
* Content Source: [memdocs/autopilot/bitlocker.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/bitlocker.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by frankroj** [comment]
Thanks @philjorgensen for taking the time to share this with the Windows documentation team. I apologize for the time it took to get back to you regarding this feedback item. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Microsoft](https://learn.microsoft.com/answers/tags/415/intune). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Windows Autopilot support information](https://support.microsoft.com/windows) to find your available support options.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
