### ISSUE TITLE
Significance of statement "Win32 component to activate Application Guard"

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/memdocs#1040]
In the section **Microsoft Defender Application Guard**, what is the significance of the following statement?

> Application Guard is only available for Windows 10 (64-bit) devices. **Using this profile installs a Win32 component to activate Application Guard.**

What is this "Win32 component" and why is it mentioned here.  It seems unrelated to the fact that Application Guard is only available for 64-bit devices.  But I could be wrong.  In any case, if the statement has no purpose it should be removed.  If it does have a purpose, it should be clear, and it currently is not clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f2a095c-452e-c494-a013-0626b9f3728d
* Version Independent ID: a4787d69-187f-fe55-d071-3a37b9b082e9
* Content: [Protection settings for Windows 10 devices in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/endpoint-protection-windows-10#next-steps)
* Content Source: [memdocs/intune/protect/endpoint-protection-windows-10.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/endpoint-protection-windows-10.md)
* Service: **microsoft-intune**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@JeremyTBradshaw   Thanks for the question. I’ve checked with our engineering team, as this warning you see in docs is the same as what’s presented in the Intune UI when configuring the Endpoint Protection profile. The word is that Application Guard installs a Win32 component on the system as part of activation, which is what the message states. Its been added to the UI, and duplicated in docs as the 32 bit component might not be expected. As to why, Intune engineering wasn't able to provide any insight as Intune is only a method to enable this Windows feature. The warning is meant as a heads up to the administrator.

**Comment by JeremyTBradshaw** [comment]
@Brenduns thanks for info.  I'll close this issue, I have a feeling that if I dealt with Application Guard and Win32 apps in Intune more often, it might make more sense to me/would have more context.  So I'll take it for what it is per them.
