### ISSUE TITLE
Update: Language Support section

### ISSUE THREAD

**Issue by deniraj** [MicrosoftDocs/memdocs#1044]
[Enter feedback here]
Observations on DMC article below screenshot: 
1.	“English” is duplicated
2.	It would be smooth flow for languages to be in A-Z order, looks like it started that way.

Also, for Intune, there are different support times by premier/non-premier and Language support, e.g. PSfP supports English language 24x7 vs EMEA languages are supported business hours. This causes customer dissatisfaction with support.

Thanks!
Niraj 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f32be850-f158-e979-6767-feb9a5c9c32d
* Version Independent ID: a720bcf8-f04d-54a9-1053-d4eb93b699d8
* Content: [Microsoft Intune Service Description](https://docs.microsoft.com/en-us/mem/intune/fundamentals/microsoft-intune-service-description)
* Content Source: [memdocs/intune/fundamentals/microsoft-intune-service-description.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/microsoft-intune-service-description.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @dougeby
* Microsoft Alias: **dougeby**

**Comment by MandiOhlinger** [comment]
@deniraj Good catch. We fixed the list. The changes should be live later today.

As for the support times, it'd be great if you created a pull request with your recommended changes. We also have [How to get support](https://docs.microsoft.com/mem/get-support), which may be a good article for that info.
