### ISSUE TITLE
Broker App for Android

### ISSUE THREAD

**Issue by dschuette01** [MicrosoftDocs/memdocs#1045]
In my environment, I'm seeing on Android that users are being directed to the Microsoft Authenticator app as the broker app, *not* Company Portal. Is the documentation wrong? Is this the expected behavior?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca76fcaf-979f-7b6b-c410-34080685d415
* Version Independent ID: eaceac76-73c4-c586-952c-8dfa90390c6e
* Content: [App-based Conditional Access with Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/app-based-conditional-access-intune)
* Content Source: [memdocs/intune/protect/app-based-conditional-access-intune.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/app-based-conditional-access-intune.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@dschuette01     I’ve gotten word from our engineering team that having the Android based authenticator app act as the broker is fine, and can be expected – but hasn’t been communicated well.  It seems the authenticator app also includes the broker functionality, and whichever app installed first on a device gets the action to serve as broker.  However, we don’t direct the reader to install the authenticator app as Intune mobile application management (MAM) scenarios require the Company Portal app.  To close this content gap, I’m adding a note about this to the article to confirm you might see the authenticator app serve as the broker.
