### ISSUE TITLE
Update Rings and Feature Updates Assignments - User vs Device

### ISSUE THREAD

**Issue by gmarnold25** [MicrosoftDocs/memdocs#1046]
I understand that the Feature Updates (Preview) is stated that only device groups are supported for assignment. Is there a plan to support user groups in the future?

Also I think it may help to get this point across if also mentioned in the [Update Rings](https://docs.microsoft.com/en-)us/mem/intune/protect/windows-update-for-business-configure#windows-10-update-rings) section that it's not recommended to use User Group assignments _**if**_ also using the Feature Updates (Preview) Intune feature.

I can see that my devices receive the normal update ring policies, but when testing the feature updates with the user group assignments and looking at the specific policy in the feature updates node, under **Monitor -->End user update status**, there is no data. Which follows what the docs say in that only device groups are supported. Is there any way to pass this along as a feature request? Either support user group assignments, or prevent using certain groups from the Intune UI (device vs user) in assignments where the type of group isn't applicable. Another instance is **Available apps**; only user groups work for these assignments as you cannot assign device groups.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62bdbb09-8341-1b8b-b0ba-cd5aaa3fa6f3
* Version Independent ID: dcb0a61c-2502-04f1-4744-97777496b57e
* Content: [Configure Windows Update for Business in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/windows-update-for-business-configure)
* Content Source: [memdocs/intune/protect/windows-update-for-business-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/windows-update-for-business-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@gmarnold25   Thanks for this feedback.  I’ve passed your feedback on to our engineering team for consideration.

As a heads up, this content area is about to get a revision (any day now), which will separate out details for update rings and feature updates. In those pending revisions, the detail that feature updates are only supported with device groups is more pronounced.  I’m also adding some detail to the update rings to note that while user or device groups are supported for rings, when used with feature updates you should plan to use device groups, as feature updates are only supported with device groups.  

Also, for feature updates reports, data collection is needed to enable data from the devices, which is passed through Windows Update, not directly from the client to Intune. That hadn't been made clear in existing content, and there is a great more detail on the way for Feature updates to ensure the reports are usable. More than I can share here, so do return back to this article, say on Monday, as we hope the content revisions will be live by then.  The article dates will update when this publishes.
