### ISSUE TITLE
Be sure to complete any tasks....

### ISSUE THREAD

**Issue by bleek00** [MicrosoftDocs/memdocs#1049]
what does "Be sure to complete any tasks or actions to get dedicated devices compliant with your assigned policies." this means? to complete any tasks in what way?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc9c611f-edcb-81fd-b76e-207dd5b3fe04
* Version Independent ID: e5998630-06e9-2051-5d40-1e1509e7fddb
* Content: [Android Enterprise compliance settings in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/compliance-policy-create-android-for-work?source=docs)
* Content Source: [memdocs/intune/protect/compliance-policy-create-android-for-work.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/compliance-policy-create-android-for-work.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@bleek00  Thanks for the question on this note. Its taken some time to unravel, and the original intent and delivery missed the mark, and will update in docs later today. With updated guidance, we're clarifying how to correctly use compliance policy with  Android Enterprise dedicated devices which involves setting up _Azure AD shared device mode_ on the device, and deploying the policy to devices and not users.  For more about Azure AD shared device mode, see [Android Enterprise dedicated device enrollment](https://docs.microsoft.com/mem/intune/enrollment/android-kiosk-enroll) in the Intune docs, and [Overview of shared device mode](https://docs.microsoft.com/azure/active-directory/develop/msal-shared-devices) in the Azure AD documentation.
