### ISSUE TITLE
Missing details for -2016346112

### ISSUE THREAD

**Issue by MatthewSteeples** [MicrosoftDocs/memdocs#1052]
When trying to apply a VPN Configuration to Windows 10 an error is shown that doesn't have a description on this page

![image](https://user-images.githubusercontent.com/255971/99965395-b62ce900-2d8c-11eb-8e8f-e8cd9816ffbe.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef65dde9-9a09-7783-54fd-d2048a7e5c8d
* Version Independent ID: 78f87124-42d7-746a-5a67-11cba073f3e4
* Content: [Error and status codes in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/fundamentals/troubleshoot-company-resource-access-problems)
* Content Source: [memdocs/intune/fundamentals/troubleshoot-company-resource-access-problems.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/troubleshoot-company-resource-access-problems.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@MatthewSteeples Thank you for the feedback. If you're looking for community technical help, be sure to post your issue in the [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). You can also [open a support case](https://docs.microsoft.com/intune/get-support), or contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

As for this article, it's not actively being maintained or updated. But, if you find a resolution, feel free to add some of your findings in a pull request, in case others get that same error. We review every pull request before publishing anything live.

**Comment by MatthewSteeples** [comment]
@MandiOhlinger Thanks for the response. I didn't need any support because a few hours later the issue had resolved itself so whatever it was it seemed transient
