### ISSUE TITLE
With PKCS, a user can have the same certificate provisioned on each device they use.

### ISSUE THREAD

**Issue by DJTomos** [MicrosoftDocs/memdocs#1057]
Hi,

I just wanted to check if this sentence is correct. -> "With PKCS, a user can have the same certificate provisioned on each device they use."  (https://docs.microsoft.com/en-us/mem/intune/protect/certificates-configure)

In my test environment I get a different certificate on each unique device. Also the KB article "(https://docs.microsoft.com/en-us/mem/intune/protect/certificates-s-mime-encryption-sign#encryption-certificates) describes:

"While Intune supports issuing PKCS certificates that support encryption, Intune creates a unique certificate per device. A unique certificate per device isn't ideal for an S/MIME encryption scenario where the encryption certificate should be shared across all the user's devices."

can someone tell me which describes the correct functionality of PKCS?

gr,
Tom

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2320f32-f46c-c4a8-1c22-1a79b44f1075
* Version Independent ID: abd36170-7d28-8708-29d6-45260ef44df5
* Content: [Learn about certificate types and profiles you use with Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/certificates-configure)
* Content Source: [memdocs/intune/protect/certificates-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certificates-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@DJTomos  Thanks for this question. You’ve spotted something that’s gone off the rail in the content, which will be fixed today.  *With PKCS certificates, each device will get a unique certificate.* 

If you need multiple devices to use the same certificate (as for S/MIME encryption scenarios), you would then want to use imported PKCS certificates.

**Comment by DJTomos** [comment]
Thanks for the update!

I think you should also update the table somewhat lower (https://docs.microsoft.com/en-us/mem/intune/protect/certificates-configure#which-certificate-profile-to-use):

> Deploys a template for a certificate request to users and devices. The provisioned certificate is always associated to a user and each of the user’s devices can receive that same certificate.

gr,
Tom

**Comment by Brenduns** [comment]
@DJTomos  Thanks for catching that, as clearly I didn't. I've just submitted the update for the table, which will be live later today.
