### ISSUE TITLE
Add all supported 3rd party MDMs, as some are missing

### ISSUE THREAD

**Issue by g1th4ck3rl3j** [MicrosoftDocs/memdocs#1058]
Document should be updated to reflect all of the available 3rd party MDMs. i.e. Mobileiron Cloud and on-prem products are missing here. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81bcb445-ada9-e2e3-d8a8-a5693a5a3850
* Version Independent ID: 6214bb16-5087-c21c-fd43-d5f0a6f405c1
* Content: [Device compliance partners in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/device-compliance-partners)
* Content Source: [memdocs/intune/protect/device-compliance-partners.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/device-compliance-partners.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@g1th4ck3rl3j   Thanks for this question. The four compliance partner entries that don’t appear in docs are related to compliance partners that aren’t yet in a public preview. For now, we won’t be revising this content. Several partners are moving towards public previews, and when that happens and we have customer ready procedures and guidance to share, they’ll be added to our docs.  

About the partners you’ve noted: To support some partners that are working on their own private previews, Intune enabled those entries in the to assist their efforts. We normally only flight (make visible) private preview details upon a per-tenant basis, by request. But these partners were added to the UI to enable those partners to drive their private previews. 

Our engineering team is aware of the confusion this creates (having something visible in the UI that’s not publicly supported nor available) and are considering their options. This feedback from you is now part of that ongoing consideration.
