### ISSUE TITLE
Can BYOD or Azure AD join process be triggered or automated

### ISSUE THREAD

**Issue by CodeCyclone** [MicrosoftDocs/memdocs#106]
Can either BYOD or Azure AD join be triggered or completely automated via PowerShell? I've been searching for a way to do this. Would need a way to detect if you are already joined too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc53a657-80d3-fa90-4d6c-4565ad0dd567
* Version Independent ID: 6ffc793f-bfab-4cd8-5cc5-1a13c127d88d
* Content: [Enroll Windows 10 device in Intune Company Portal](https://docs.microsoft.com/en-us/mem/intune/user-help/enroll-windows-10-device#feedback)
* Content Source: [memdocs/intune/user-help/enroll-windows-10-device.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/user-help/enroll-windows-10-device.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @CodeCyclone, thanks for your question. You may find this article in our IT pro docset helpful: [Use PowerShell scripts of Windows 10 devices in Intune](https://docs.microsoft.com/en-us/mem/intune/apps/intune-management-extension)
