### ISSUE TITLE
Application Manager Role does not exist

### ISSUE THREAD

**Issue by philrice** [MicrosoftDocs/memdocs#1068]
Unless im going crazy , there is no Application Manager Role available in Azure or 365. The only one I can see is Application Administrator but that seems to be for Enterprise Apps and App Registrations rather than InTune.
Im looking for guidance on which role to assign to allow users to create and configure InTune Apps but without giving them InTune Administrator adn all roads lead back to this page which gives incorrect info

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3eaa886-918b-127e-ad4b-d829e99b0d44
* Version Independent ID: 87240468-dd25-7f45-740b-f078cd5deac7
* Content: [Role-based access control (RBAC) with Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/role-based-access-control)
* Content Source: [memdocs/intune/fundamentals/role-based-access-control.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/role-based-access-control.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@philrice The Application Manager role is an Intune built-in role. You can find it under **Tenant administration** > **Roles** > **All roles**. You can create your own Intune custom roles by following the steps here: https://docs.microsoft.com/en-us/mem/intune/fundamentals/create-custom-role
Let me know if this doesn't unblock you.
