### ISSUE TITLE
Updating the MDT release notes documentation and keeping it current.

### ISSUE THREAD

**Issue by vultureman** [MicrosoftDocs/memdocs#1069]
I would highly suggest posting the current patch to allow 2004/20H2 imaging on this page as well.

https://support.microsoft.com/en-us/help/4564442/windows-10-deployments-fail-with-microsoft-deployment-toolkit

Also, please clarify that all future Win10 versions are supported with MDT until MS says that they aren't supported. Some companies won't use it because the current release notes say only 1809 and lower, despite that patch being created that allows 2004/20H2 installs.

https://www.reddit.com/r/MDT/comments/k1sxwi/windows_10_20h2_mdt_official_support_documentation/

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df86617a-8915-afa6-3bf0-db1f846b4dc5
* Version Independent ID: 1901d959-5e4a-a233-19fc-2f9c48d17d33
* Content: [MDT release notes](https://docs.microsoft.com/en-us/mem/configmgr/mdt/release-notes)
* Content Source: [memdocs/configmgr/mdt/release-notes.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/mdt/release-notes.md)
* Product: **configuration-manager**
* Technology: **configmgr-mdt**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @vultureman for the feedback. I'll add a bit about that KB.

As for the supported OS versions, see the FAQ further down the page: https://docs.microsoft.com/en-us/mem/configmgr/mdt/release-notes#frequently-asked-questions

> ### Is this release only supported with Windows 10, Windows ADK, or Configuration Manager version X?
> We primarily tested this build of MDT with the configuration listed above. Unless there are any explicit known issues, anything outside of the above configuration has a high probability of still working. Your mileage may vary as we haven't explicitly tested other combinations.

I commented the same on the reddit thread.

**Comment by aczechowski** [comment]
That KB/issue is already included in [the known issues](https://docs.microsoft.com/mem/configmgr/mdt/release-notes#windows-10-version-2004). Based on other feedback, I am breaking out the known issues into a separate article, so hopefully that will increase visibility.
