### ISSUE TITLE
Sr. Engineer

### ISSUE THREAD

**Issue by GeorgeChiuTheHartford** [MicrosoftDocs/memdocs#107]
Some mobile apps prompt for password and do not honor the passwordless authentication method form the Microsoft authenticator.   Is this a known issues?  The problem is our organization is using smartcard login only that users do not know their password.   If the mobile app does not honor passwordless authentication, users are not able to use the mobile apps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cde34bc-bab0-d412-5971-cbc1f515a486
* Version Independent ID: ac355bba-5f6f-0168-49f3-67b7a2ddb2d4
* Content: [Create and deploy app protection policies - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policies)
* Content Source: [memdocs/intune/apps/app-protection-policies.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-protection-policies.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@GeorgeChiuTheHartford - Thanks for sharing this with the Intune documentation team. To better understand your issue, you may need to contact support and provide the apps you are using, whether the apps are managed, what platform the apps are on. We want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

This question is in our documentation feedback channel and it may be best to handle this question as a support request. For this reason, I'm closing this issue. Please use the above channels if you don't already have a solution.
