### ISSUE TITLE
Software update points with a network load balancing (NLB) cluster is not supported after 1702

### ISSUE THREAD

**Issue by henrywang08** [MicrosoftDocs/memdocs#1070]
[Enter feedback here]
This feedback is regarding the statement in this article:

"_For failover support with the software update point, use Windows PowerShell to install this role on a Windows network load balancing (NLB) cluster._"
 
According the link below, Software update points with a network load balancing (NLB) cluster is not supported after 1702. 

https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/changes/deprecated/removed-and-deprecated-cmfeatures#unsupported-and-removed-features

"
**Software update points with a network load balancing (NLB) cluster | February 27, 2016 | Version 1702**
"

The current supported high available configuration for Software Update Point is to setup an additional SUP in the same boundary group. The details are stated in the link below:

https://docs.microsoft.com/en-us/mem/configmgr/sum/plan-design/plan-for-software-updates#BKMK_SUPSwitching

Please help to correct the information in this article. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4ea8367-2aff-5024-fa22-e19f1a1297b5
* Version Independent ID: 5fd889f1-cb94-3ceb-f712-11e2845a0219
* Content: [High availability - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/high-availability-options)
* Content Source: [memdocs/configmgr/core/servers/deploy/configure/high-availability-options.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/deploy/configure/high-availability-options.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @henrywang08 for catching that
