### ISSUE TITLE
iOS dependency is incorrectly listed

### ISSUE THREAD

**Issue by BenLeggiero** [MicrosoftDocs/memdocs#1071]
This documentation page lists the following dependencies:

> - Your app must be targeted for iOS 12 or above.

But according to [the Intune release notes](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/tag/14.0.0):

> Updated target OS version to iOS 13. Apps linking against this version of the SDK should target iOS 13 or higher, as that is the minimum supported iOS version for Intune SDK version 14+.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 893c295c-9fa2-954f-4c9c-8b776d43f182
* Version Independent ID: dd4a72fe-ddde-4ed7-c408-c987f18c5d2a
* Content: [Microsoft Intune App SDK for iOS developer guide](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios)
* Content Source: [memdocs/intune/developer/app-sdk-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/developer/app-sdk-ios.md)
* Service: **microsoft-intune**
* Sub-service: **developer**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@BenLeggiero - Thanks for the feedback. It looks like this change has now been updated. Thanks
