### ISSUE TITLE
Two spelling errors

### ISSUE THREAD

**Issue by timpeteren** [MicrosoftDocs/memdocs#1076]
Hi.

Just wanted to point out a couple of spelling errors, to help improve the quality of the document for explaining this interesting new feature:

https://docs.microsoft.com/en-us/mem/intune/protect/derived-credentials#supported-platforms

Fully **Mmanaged** devices (version 7.0 and above)
Corporate-Owned Work **pProfile**

Kind regards,

\-Tim Peter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d241b80-3ec6-debc-4f49-f8e02e86fc81
* Version Independent ID: c0443988-fec8-db83-e2f3-ff06b687a834
* Content: [Use derived credentials for mobile devices in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/derived-credentials)
* Content Source: [memdocs/intune/protect/derived-credentials.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/derived-credentials.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@timpeteren   Thanks for raising this to our attention.  I've submitted a fix that will resolve the typo's later this morning. It appears that an effort to update Android profile references went a bit off track.
