### ISSUE TITLE
Notes in purple in dark mode are hard to see links

### ISSUE THREAD

**Issue by bledMS82** [MicrosoftDocs/memdocs#1079]
Please edit format to allow for ease of visibility , example underline hyperlink . in the example below the hyperlink is on the words "Creating Windows Embedded applications " 

![image](https://user-images.githubusercontent.com/64666203/100895626-65e81200-3483-11eb-894e-d07ae946160c.png)

**Comment by aczechowski** [comment]
Hi @bledMS82 thanks for the feedback. That's a behavior of the fundamental docs.ms platform, not specific to our content. Please file [site feedback](https://aka.ms/sitefeedback) to share with the docs engineering team. (This link is also in the footer of every page on docs.ms.
