### ISSUE TITLE
Incorrect options in steps

### ISSUE THREAD

**Issue by andrewbeaumont** [MicrosoftDocs/memdocs#109]
The steps at https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policies#create-an-iosipados-or-android-app-protection-policy are different when creating a Policy for Windows 10.

Additionally, before creating a new Policy you must click the Create Policy button on the App Protection Policies page and then select the Device Type from a drop down list.

Then the options on the first page of the New Windows 10 Policy wizard are:
- Name:
- Description:
- Enrollment State:

Enrollment state needs clearer explaination about it's use, which are loosely found at https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policies#target-app-protection-policies-based-on-device-management-state but contains Mobile Device specific information. This should be amended to include Windows 10 specific information also. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cde34bc-bab0-d412-5971-cbc1f515a486
* Version Independent ID: ac355bba-5f6f-0168-49f3-67b7a2ddb2d4
* Content: [Create and deploy app protection policies - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policies#target-app-protection-policies-based-on-device-management-state)
* Content Source: [memdocs/intune/apps/app-protection-policies.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-protection-policies.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@andrewbeaumont - Thanks for the feedback. The section you mentioned has been updated to specifically mention 'App protection policies for iOS/iPadOS and Android apps'. Also, I'm adding a link to point to a topic on Windows app protection policies. In that topic, we also point to additional Windows information, including 'Enrollment State'. The link should be published today.
