### ISSUE TITLE
EnforcementState is missing couple of error values

### ISSUE THREAD

**Issue by JoergWu** [MicrosoftDocs/memdocs#1094]
During Error inspection we found for the "EnforcementState" (error) values a couple enforcement states missing.
On the other hands side we did not find any of the shown enforcement states.
These are the values we see currently:

- 1000
- 1001
- 2000
- 2004
- 2009
- 3000

May be the values are somehow combined (e.g. binary/matrix addition, colon addition)?
If this is the case may you enhance the documentation or add the missing values, please?

Thanks a lot!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93173219-d3a7-a318-6033-71fca60fe734
* Version Independent ID: b3a5e2f1-3266-cbb3-79f0-05a0e862a7b0
* Content: [SMS_AppDeploymentAssetDetails Class - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/develop/reference/apps/sms_appdeploymentassetdetails-server-wmi-class)
* Content Source: [memdocs/configmgr/develop/reference/apps/sms_appdeploymentassetdetails-server-wmi-class.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/develop/reference/apps/sms_appdeploymentassetdetails-server-wmi-class.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @JoergWu for the feedback. The ConfigMgr SDK content is an area in which we're not actively investing beyond basic maintenance and some new functionality. If you'd like to submit a change for this issue, see [How to contribute](https://docs.microsoft.com/mem/use-docs#bkmk_contribute).
