### ISSUE TITLE
OSD boot media certificate with CMG - Requirements not clearly

### ISSUE THREAD

**Issue by CCWT** [MicrosoftDocs/memdocs#1095]
> If you use a PKI-based certificate for the boot media, configure it for SHA256 with the Microsoft Enhanced RSA and AES provider.

On [PKI certificates for clients](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/network/pki-certificate-requirements#BKMK_PKIcertificates_for_clients) is listed that the client certificate has the same requirements like the certificate for a server with the dp role. Both doesn't state that the "Microsoft Enhanced RSA and AES provider" is needed.

Does this also mean that CNG v3 certificates aren't supported for boot media?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05a9c57b-3e71-da71-4eda-8b282ecca677
* Version Independent ID: 319575c7-ef4f-dc86-fea6-3448faaf02d0
* Content: [Deploy a task sequence over the internet - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/osd/deploy-use/deploy-task-sequence-over-internet#bootable-media-support-for-cloud-based-content)
* Content Source: [memdocs/configmgr/osd/deploy-use/deploy-task-sequence-over-internet.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/osd/deploy-use/deploy-task-sequence-over-internet.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @CCWT, thanks for the feedback.

The engineering team just took a change for this prerequisite to relax the requirement, so this prerequisite will shortly change to a recommendation. SHA2 cert is preferred, but can fallback to a SHA1 cert if the former isn't available. This change will be available in a few weeks with the global availability of version 2010 (not [early update ring](https://docs.microsoft.com/mem/configmgr/core/servers/manage/checklist-for-installing-update-2010#early-update-ring) as it is right now).

I'm checking on the CNG v3 question, stay tuned.

**Comment by aczechowski** [comment]
CNG certs should work. We already note on that page that OSD scenarios are supported, and should be no difference here. I'm adding an explicit line to this article, though. Thanks again for the feedback.

This issue will auto close when my change merges, and then should publish live later that same day.
