### ISSUE TITLE
MacOS apps not installed, but still discovered in Intune

### ISSUE THREAD

**Issue by TobiasCouturier** [MicrosoftDocs/memdocs#1096]
We see in our Intune Portal apps in the Discoverd apps list which are not even fysical present on the device. There are .app files in the iCloud folder, which are only symbolic links to the content in the cloud, but still in the discovered apps list.

This page says "All apps installed on the device" are being discovered, but what is your definition of installed? Can you please complete the document or change the mechanism. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2f41921-6680-75b6-5b95-55327279861a
* Version Independent ID: a0178c17-b82b-b762-49f6-17e2abcbd775
* Content: [Discovered apps - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-discovered-apps?source=docs)
* Content Source: [memdocs/intune/apps/app-discovered-apps.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-discovered-apps.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
We have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. If you have continue to have questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

Please use the above channels if you don't already have a solution.
