### ISSUE TITLE
Deploy an OS over CMG using bootable media

### ISSUE THREAD

**Issue by Stroell** [MicrosoftDocs/memdocs#1097]
When you try to _deploy an OS over CMG using bootable media_ and the site is in E-HTTP mode and the CMG uses an internal certificate, the deployment will fail as the client does not trust the CMG Cert.

Therefore, you need to manually import the RootCA to your WinPE Boot image.
This is currently not part of the Docu and should be added (including how to add a cert to WinPE)

Cheers,
Stefan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05a9c57b-3e71-da71-4eda-8b282ecca677
* Version Independent ID: 319575c7-ef4f-dc86-fea6-3448faaf02d0
* Content: [Deploy a task sequence over the internet - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/osd/deploy-use/deploy-task-sequence-over-internet#deploy-an-os-over-cmg-using-bootable-media)
* Content Source: [memdocs/configmgr/osd/deploy-use/deploy-task-sequence-over-internet.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/osd/deploy-use/deploy-task-sequence-over-internet.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Stroell for the feedback. I'll make a note.

I also suggest you file [product feedback](https://docs.microsoft.com/mem/configmgr/core/understand/product-feedback). For E-HTTP, I think the site should add the root cert to the boot image.
