### ISSUE TITLE
MEMCM

### ISSUE THREAD

**Issue by pamcdo** [MicrosoftDocs/memdocs#1099]
This page says that the product should be referred to as Microsoft Endpoint Configuration Manager, Configuration Manager, or ConfigMgr. But David James is out there on Twitter using #MEMCM. Where does #MEMCM fit in to this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0847f1f-4207-1380-4c05-0b9b9b4bf6c9
* Version Independent ID: 0dd578d7-5a6d-482d-04d6-cc2b29f5b9ec
* Content: [Microsoft Endpoint Configuration Manager FAQ - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/understand/microsoft-endpoint-manager-faq#how-do-we-refer-to-the-product-now)
* Content Source: [memdocs/configmgr/core/understand/microsoft-endpoint-manager-faq.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/understand/microsoft-endpoint-manager-faq.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @pamcdo, I think that's just how Dave and MVPs are using it on Twitter. Similar to how #SCCM was unofficially used for years.

This page lists the official product brand use.

**Comment by pamcdo** [comment]
But...

![memcm](https://user-images.githubusercontent.com/48225667/101416413-d2b24080-38b7-11eb-9bde-d8a2f0111e55.JPG)

**Comment by aczechowski** [comment]
Hashtags aren't product names. 😉
