### ISSUE TITLE
DEM accounts with Autopilot.

### ISSUE THREAD

**Issue by juelizon** [MicrosoftDocs/memdocs#110]
Are DEM accounts supported with Autopilot? I don't see them listed on the limitations. 
And if supported, are there any know issues while using DEM accounts with Autopilot? 

* ID: 7786d9c0-55b0-9bff-fc0a-f4ee70ee0615
* Version Independent ID: cf0c17a0-fdc7-e0af-db82-913e36d2ec7c
* Content: [Enroll devices using a device enrollment manager account - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-manager-enroll)
* Content Source: [memdocs/intune/enrollment/device-enrollment-manager-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/device-enrollment-manager-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@juelizon Yes, DEM works with Autopilot. There are no known issues. Thanks!
