### ISSUE TITLE
question about SUP internet required URL http://ntservicepack.microsoft.com

### ISSUE THREAD

**Issue by yunwa** [MicrosoftDocs/memdocs#1100]
[Enter feedback here]
One question about the URL http://ntservicepack.microsoft.com on TCP/ICMP connection test. 

Internet access requirements - Configuration Manager | Microsoft Docs
Software updates
Allow the active software update point to access the following endpoints so that WSUS and Automatic Updates can communicate with the Microsoft Update cloud service:
•        http://windowsupdate.microsoft.com
•        http://*.windowsupdate.microsoft.com
•        https://*.windowsupdate.microsoft.com
•        http://*.update.microsoft.com
•        https://*.update.microsoft.com
•        http://*.windowsupdate.com
•        http://download.windowsupdate.com
•        http://download.microsoft.com
•        http://*.download.windowsupdate.com
•        http://ntservicepack.microsoft.com

On machine 1, the TCP test connection is success and reply message from ntservicepack.microsoft.com in netmon trace. 
 
We could see the response from ntservicepark.microsoft.com on port 80 based on network monitor trace. 

On machine 2 , customer found the tcp test connection was failed. We captured the network monitor trace and no any response from ntservicepack.microsoft.com.  

**Note:** Machine 2 has proxy and cx add all the URLs list into the bypass list , and only the ntservicepack.microsoft.com couldn’t pass the tcp test on port 80/443.  Interesting that we can resolve the IP address of ntservicepack.microsoft.com on machine 2. 

I can understand that ping/ICMP may be not allowed by ntservicepack.microsoft.com, but why the TCP port testing couldn’t pass also. 

>>I tested this in my lab without proxy settings, but get the same symptom with customer on machine 2. 
Test-NetConnection ntservicepack.microsoft.com -port 80
WARNING: TCP connect to ntservicepack.microsoft.com:80 failed
WARNING: Ping to ntservicepack.microsoft.com failed -- Status: TimedOut

ComputerName           : ntservicepack.microsoft.com
RemoteAddress          : 207.46.22.245
RemotePort             : 80
InterfaceAlias         : Ethernet 2
SourceAddress          : 192.168.10.18
PingSucceeded          : False
PingReplyDetails (RTT) : 0 ms
TcpTestSucceeded       : False

-NetConnection ntservicepack.microsoft.com -port 443
WARNING: TCP connect to ntservicepack.microsoft.com:443 failed
WARNING: Ping to ntservicepack.microsoft.com failed -- Status: TimedOut

ComputerName           : ntservicepack.microsoft.com
RemoteAddress          : 207.46.22.245
RemotePort             : 443
InterfaceAlias         : Ethernet 2
SourceAddress          : 192.168.10.18
PingSucceeded          : False
PingReplyDetails (RTT) : 0 ms
TcpTestSucceeded       : False

nslookup  ntservicepack.microsoft.com
Server:  ty-win2008r201.tatsuro.com
Address:  192.168.20.1

Non-authoritative answer:
Name:    ntservicepack.microsoft.nsatc.net
Address:  207.46.22.245
Aliases:  ntservicepack.microsoft.com

**Question:**
Does the endpoint ntservicepack.microsoft.com still use for updates ?  If yes, how to verify the TCP connection ? 
If no, can we modify the document to avoid confuse ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a9e88a5-bc7d-4982-4564-ceea80bde0e7
* Version Independent ID: 817824fe-5b44-ebeb-75c4-9eeb2dfa13ce
* Content: [Internet access requirements - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/network/internet-endpoints)
* Content Source: [memdocs/configmgr/core/plan-design/network/internet-endpoints.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/network/internet-endpoints.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @yunwa. We take our list directly from the [WSUS documentation](https://docs.microsoft.com/windows-server/administration/windows-server-update-services/deploy/2-configure-wsus#211-connection-from-the-wsus-server-to-the-internet). So you could try filing feedback on that article. I'm closing this issue as there's nothing actionable for us right now.

**Comment by yunwa** [comment]
Hi ,

I already feedback on WSUS documentation<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fwindows-server%2Fadministration%2Fwindows-server-update-services%2Fdeploy%2F2-configure-wsus%23211-connection-from-the-wsus-server-to-the-internet&data=04%7C01%7Cyunwa%40microsoft.com%7C2d206573e2554864667408d89d7539d0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637432474097574135%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rmvYUAGVjDsZTqmKeRpLFHMawzl%2Bk2jeG1dVV4TCbqY%3D&reserved=0>. But no response till now.

Best Regards,
Yunbo

**Comment by yunwa** [comment]
Yunbo Wang would like to recall the message, "[MicrosoftDocs/memdocs] question about SUP internet required URL http://ntservicepack.microsoft.com (#1100)".
