### ISSUE TITLE
Link 'delete them from the Intune All devices blade' points to incorrect URL

### ISSUE THREAD

**Issue by ivassallo19** [MicrosoftDocs/memdocs#1102]
[Enter feedback here]
Under 'Delete Autopilot devices', point 1, the link for 'delete them from the Intune All devices blade' points to an incorrect link.
The link currently points to:
https://docs.microsoft.com/en-us/mem/intune/remote-actions/devices-wipe#delete-devices-from-the-azure-active-directory-portal
Which is 'Delete devices from the Azure Active Directory portal'.
And instead it should point to:
https://docs.microsoft.com/en-us/mem/intune/remote-actions/devices-wipe#delete-devices-from-the-intune-portal
Which is 'Delete devices from the Intune portal'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97ce79c0-0014-f6f0-95f7-58574bfdefb3
* Version Independent ID: 40b3877e-a094-8d05-c95b-ca842c5ca8ce
* Content: [Enroll devices with Windows Autopilot - Microsoft Intune](https://docs.microsoft.com/en-us/mem/autopilot/enrollment-autopilot)
* Content Source: [memdocs/autopilot/enrollment-autopilot.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/enrollment-autopilot.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@ivassallo19 Thanks! I'll fix this today.
