### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by jegilber** [MicrosoftDocs/memdocs#1104]
Using Desktop Analytics and Configuration Manager to reduce Windows TCO through data-driven insights for management, servicing, and support

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae3a0675-959f-840c-bc51-199cee1d71d5
* Version Independent ID: eb5ed4c2-332f-5816-5d1f-7f2958b8e410
* Content: [Desktop Analytics - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/desktop-analytics/overview)
* Content Source: [memdocs/configmgr/desktop-analytics/overview.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/desktop-analytics/overview.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @jegilber for the feedback! Here's the proper link to the session: https://myignite.microsoft.com/archives/IG19-BRK3085

I've updated this article, as well as two others that had similar issues with the Ignite archives. The changes will publish live tomorrow morning.
