### ISSUE TITLE
Prerequisite .NET Framework

### ISSUE THREAD

**Issue by pilgi3** [MicrosoftDocs/memdocs#1105]
We configured the connected cache on four Server (three 2012 R2 and one 2019 Core).
On two of them we got Error 500 calling the URI http://localhost:53000/summary.
The other two servers (2019 Core and 2012 R2) working as expected.
I found out the installed .NET Framework were different.
The working ones have 4.7.2 installed the faulty ones 4.5.2.
So I updated these two servers and voila the connected cache works!

Could you please mention this in the prerequisite?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f3bc546-10ba-d750-fc0c-a9fa4e3e1e8d
* Version Independent ID: 9a692485-d3fb-d8d4-57d2-611ff9692421
* Content: [Microsoft Connected Cache - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/hierarchy/microsoft-connected-cache)
* Content Source: [memdocs/configmgr/core/plan-design/hierarchy/microsoft-connected-cache.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/hierarchy/microsoft-connected-cache.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks for the feedback. I'm checking with the MCC team to confirm.

**Comment by aczechowski** [comment]
I'm making this change with some other updates to the article. This issue will closely shortly, and the article will update with the 2111 release.

**Comment by pilgi3** [comment]
Thanks for editing this:

![grafik](https://user-images.githubusercontent.com/44865075/155668041-35c7f81e-e31b-45db-86da-93e497d641b4.png)
