### ISSUE TITLE
License requirements?

### ISSUE THREAD

**Issue by kangdu** [MicrosoftDocs/memdocs#1109]
Hi there, what license do we need for those dedicated devices? 

It seems the Device is not associated with an user. How do we allocate license for it?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b915e54-6436-0716-5c8c-e69930499a8f
* Version Independent ID: 99d8b7ca-8e4a-395d-8991-2943b2d3a591
* Content: [Setup Intune enrollment for Android Enterprise dedicated devices - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/android-kiosk-enroll)
* Content Source: [memdocs/intune/enrollment/android-kiosk-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/android-kiosk-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by MandiOhlinger** [comment]
@kangdu Good question. It seems [Assign licenses in Intune](https://docs.microsoft.com/mem/intune/fundamentals/licenses-assign#how-user-and-device-licenses-affect-access-to-services) may answer your question.
