### ISSUE TITLE
Service pack requirements

### ISSUE THREAD

**Issue by MaratMussabekov** [MicrosoftDocs/memdocs#111]
in this page it is stated "Your Exchange version is Exchange 2010 SP1 or later."
in page https://docs.microsoft.com/en-us/mem/intune/protect/exchange-connector-install , mentioned that sp3 is required.
Which information is correct?
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d40a143-767d-ea36-83e3-e5bdab481972
* Version Independent ID: 2fbd64e5-72bb-af91-3277-0bb8e696e1b4
* Content: [Create Exchange Conditional Access policy - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/conditional-access-exchange-create#feedback)
* Content Source: [memdocs/intune/protect/conditional-access-exchange-create.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/conditional-access-exchange-create.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@MaratMussabekov   Thanks for the question.  I believe that SP3 is the requirement and that the SP1 statement wasn't updated to match. However, as the service pack version statements predate my work on this content set, I'm seeking validation form our engineering team, and will reply back again once I have that.

**Comment by Brenduns** [comment]
@MaratMussabekov   The content will update today to reflect Service Pack 3 is the correct version in both articles. Exchange Server 2010 is all but out of [support by Microsoft](https://support.microsoft.com/lifecycle/search?alpha=Exchange%20Server) and only SP3 remains in support at this time, through *extended* support until October of this year, with mainstream support having ended in January 2015. Anyone using Exchange 2010 should investigate an newer version of Exchange that continues to be in support by Microsoft in the future to ensure their Exchange deployment remains secure, and in support should assistance be needed. .
