### ISSUE TITLE
Microsoft Connected Cache requirements

### ISSUE THREAD

**Issue by Stroell** [MicrosoftDocs/memdocs#1110]
The Internet access requirements for the Microsoft Connected Cache Role on Distribution Points are missing.

So far I have found that the following URLs are used, but I´m not sure if that list is complete:

*.do.dsp.mp.microsoft.com.
*.dl.delivery.mp.microsoft.com
*.emdl.ws.microsoft.com
*.windowsupdate.com
*.delivery.mp.microsoft.com
*.update.microsoft.com
tsfe.trafficshaping.dsp.mp.microsoft.com
officecdn.microsoft.com
officecdn.microsoft.com.edgesuite.net
*.manage.microsoft.com
*.delivery.mp.microsoft.com
assets1.xboxlive.com.nsatc.net
assets1.xboxlive.com
assets2.xboxlive.com.nsatc.net
assets2.xboxlive.com
xvcf1.xboxlive.com
xvcf2.xboxlive.com
xvcb1.xboxlive.com
xvcb2.xboxlive.com

*.manage-beta.microsoft.com
*.manage-selfhost.microsoft.com
*.manage-dogfood.microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a9e88a5-bc7d-4982-4564-ceea80bde0e7
* Version Independent ID: 817824fe-5b44-ebeb-75c4-9eeb2dfa13ce
* Content: [Internet access requirements - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/network/internet-endpoints)
* Content Source: [memdocs/configmgr/core/plan-design/network/internet-endpoints.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/network/internet-endpoints.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @Stroell 
There's a mention of it under the [section for DO](https://docs.microsoft.com/mem/configmgr/core/plan-design/network/internet-endpoints#delivery-optimization)

> Distribution points that support Microsoft Connected Cache also require these endpoints.

And the [MCC article](https://docs.microsoft.com/mem/configmgr/core/plan-design/hierarchy/microsoft-connected-cache#prerequisites-and-limitations) notes this prerequisite:

> The distribution point requires internet access to the Microsoft cloud. The specific URLs can vary depending upon the specific cloud-enabled content. Make sure to also allow the endpoints for delivery optimization.

So I'm reluctant to start such a lengthy list of endpoints for MCC that will vary depending upon the content that a customer is using.
