### ISSUE TITLE
.local domains

### ISSUE THREAD

**Issue by stuart7777** [MicrosoftDocs/memdocs#1113]
I have set up MS Tunnel and have a test website called demo.mstunnel.local and there is a internal DNS record for this. If I use a device wide VPN I can access the website using the VPN. If I change the configuration to use per-app VPN and then configure Edge as the browser to be used for per-app VPN, when I launch Edge the VPN starts and connects. However, I cannot access the site. If I add a DNS for an internal domain that has part of the URL as Internet routable, such as infra.mstunnel.info, where infra is only available internally then I can connect. So in this example I have a DNS records in my internal DNS for demo.infra.mstunnel.info. I can also connect using the IP address. Is there a know issue with .local DNS suffixes with per-app VPN?

**Comment by Brenduns** [comment]
@stuart7777   After review by our product team, their feedback is that this this shouldn’t need to be internet routable but must be a valid domain format. While not aware of any DNS issues, there is thought that what you describe could be related to this aged Apple developer forum post (which doesn’t look to have received a solution): https://developer.apple.com/forums/thread/82705 (DNS resolution  in Per-App VPN configurations).  One of our team member also found the following article from Citrix for their gateway clients that describe similar results based on this Apple behavior. https://docs.citrix.com/en-us/citrix-gateway/citrix-gateway-clients/set-up-sso-for-ios-users.html.  It seems there are some issues for per-app VPNs that need a deeper look and possible guidance or solutions. 

Our engineering team is looking to schedule some additional testing in this area, which is might start in the weeks ahead. Any relevant results would drive a content update.
