### ISSUE TITLE
Edge and per-app VPN

### ISSUE THREAD

**Issue by stuart7777** [MicrosoftDocs/memdocs#1114]
I have configured MS Tunnel to use per-app VPN and then configured Edge for iOS to use this VPN. When I launch Edge the MS Tunnel VPN connects as expected. I have App Protection Policies applied to Edge to apply DLP, such as restricting copy and paste. However, if I am logged into Edge with my work account this restricts these action, but if I sign out of Edge I can still use the MS Tunnel VPN via Edge and the App Protection Policies do not apply so data leakage can occur. Is there a way or any plans to only allow the VPN to be used via a work account?

**Comment by Brenduns** [comment]
@stuart7777  The engineering team has no current plans to differentiate VPN cone activity by identity or account within an application. However, that might be something to ask for via the Intune Feedback forum (User Voice channel) @ https://microsoftintune.uservoice.com/forums/291681-ideas. 

The User Voice channel is the best path to get a product ask or enhancement on our engineering team radar, for future work.  We encourage you to submit your product asks, and to vote on the submissions by others that you’d also like to see.
