### ISSUE TITLE
access denied to the tool used to get help with access denied.

### ISSUE THREAD

**Issue by ksaur** [MicrosoftDocs/memdocs#1116]
[Enter feedback here]
I get access denied for the link in "For contact information, check the Company Portal website."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08300405-c9e4-b981-6151-a4309e6d11c7
* Version Independent ID: 8b5f54f1-07b3-dce5-4046-9ccf8798d3d0
* Content: [Enroll your Mac with Intune Company Portal](https://docs.microsoft.com/en-us/mem/intune/user-help/enroll-your-device-in-intune-macos-cp)
* Content Source: [memdocs/intune/user-help/enroll-your-device-in-intune-macos-cp.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/user-help/enroll-your-device-in-intune-macos-cp.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @ksaur, thanks for sharing your experience. If you're getting an access denied message, that means that you don't have permission to sign in to the website (maybe your organization has yet to set up your account in Intune yet or you're behind a firewall, for example).  Definitely reach out to your IT support person for help.

**Comment by ksaur** [comment]
I'm a Microsoft employee with a machine long past registered with InTune.  So I'm not quite sure what the issue is. :)
