### ISSUE TITLE
Step 4 in "To create a custom role" needs to be revised

### ISSUE THREAD

**Issue by Peha1906** [MicrosoftDocs/memdocs#112]
I did some testing with custom roles in Intune and determined that action under Step 4 in "To create a custom role" is actually just tagging the role with the tag - not giving the permissions to "see" devices tagged with particular tag. Part which is handling on which tagged devices you'll have the permissions is when you create a "Role assignment" in the next step.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee559326-3f31-4a98-7399-21d571a42d9d
* Version Independent ID: 11eb7dee-44e1-d6bd-76c1-a6327199964d
* Content: [Create a custom role in Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/create-custom-role#feedback)
* Content Source: [memdocs/intune/fundamentals/create-custom-role.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/create-custom-role.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@Peha1906 Thanks! I'll improve the wording today.
