### ISSUE TITLE
IP endpoint list possibly outdated

### ISSUE THREAD

**Issue by GiggaWatson** [MicrosoftDocs/memdocs#1121]
Good Day , 
Please can someone update the list of Intune Endpoints as this list seems to be outdated.

I was able to identify two additional endpoints (so far) that are not in this list .
**13.69.67.228 
13.69.231.132** 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c9c3475-56d4-026b-349f-f9cbc258537c
* Version Independent ID: 9c6476ed-8a47-bcb4-dfbf-25ba305c3b24
* Content: [Network endpoints for Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/intune-endpoints)
* Content Source: [memdocs/intune/fundamentals/intune-endpoints.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/intune-endpoints.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@GiggaWatson Those two IP addresses you noted are included under the entry for *.manage.microsoft.com as (using CIDR notation):
13.69.231.128/28
13.69.67.224/28

**Comment by ErikjeMS** [comment]
(PM thread 9050183)
