### ISSUE TITLE
MEM Tunnel

### ISSUE THREAD

**Issue by zlDev** [MicrosoftDocs/memdocs#1124]
Why is it still called Intune tunnel? Should it be called MEM Tunnel instead?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ebaa15c-1e00-c075-eff2-79d4c10ba6af
* Version Independent ID: c9dfee71-1c01-4318-725c-b4bb97052efb
* Content: [Use the Microsoft Tunnel VPN solution for Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/microsoft-tunnel-overview)
* Content Source: [memdocs/intune/protect/microsoft-tunnel-overview.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/microsoft-tunnel-overview.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@zlDev    Thanks for the question.  While you use the Microsoft Endpoint Manager console to configure the Microsoft Tunnel, it is part of the Intune service.
