### ISSUE TITLE
Conditional Access

### ISSUE THREAD

**Issue by Coopem16** [MicrosoftDocs/memdocs#1127]
It would be nice if this page displayed the Conditional Access policies supported by the Partner Apps. We spent too many hours, vetting Tableau for intune, only to learn it did not support either, "Require App Protection" or "Required App". 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02165898-ec07-86e1-adc5-18f60bec9689
* Version Independent ID: 7b6c64c4-3304-42b0-079a-7dee609c5e4f
* Content: [Supported Microsoft Intune apps](https://docs.microsoft.com/en-us/mem/intune/apps/apps-supported-intune-apps)
* Content Source: [memdocs/intune/apps/apps-supported-intune-apps.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/apps-supported-intune-apps.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
Thanks for the feedback. I'm adding an additional note to help call out that the app vendor should be contacted for more app information.
