### ISSUE TITLE
Is wipe also available with hybrid AAD joined devices

### ISSUE THREAD

**Issue by pedrr** [MicrosoftDocs/memdocs#113]
Is wipe also available with hybrid AAD joined devices?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cdcc7fd-5bd9-1645-abf4-a73d3ea7adaa
* Version Independent ID: 5022b2ba-5fb0-18ce-9079-1b65ad0b2e17
* Content: [Retire or wipe devices using Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/remote-actions/devices-wipe)
* Content Source: [memdocs/intune/remote-actions/devices-wipe.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/remote-actions/devices-wipe.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
(7024113)

**Comment by pjsyeah** [comment]
The 'Wipe' option is available for me in Hybrid AAD Joined devices. Trying that out now.

**Comment by ErikjeMS** [comment]
Repinged PM....

**Comment by ErikjeMS** [comment]
The documentation team hasn’t been able to find an answer for this issue. If this is still an issue for you can try any of the following: 
- Open a support ticket by following the steps here: [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support). 
- Post on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.   
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.   
 I'm closing this issue as there's nothing actionable for docs at this time.
