### ISSUE TITLE
Available for Device

### ISSUE THREAD

**Issue by tobiasabele** [MicrosoftDocs/memdocs#1138]
Maybe the article should make clear, that available can only be assigned to user Groups, and not to Devices. At least that shows the testing on Windows 10 .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7ad786b-eac9-7979-9509-25e05673b35a
* Version Independent ID: 42d279ce-086f-be9f-821f-53d7100fa838
* Content: [Assign apps to groups in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-deploy)
* Content Source: [memdocs/intune/apps/apps-deploy.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/apps-deploy.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
Thanks for the feedback. I'm making updates to the topic based on your suggestion now. Thanks
