### ISSUE TITLE
Defender for Endpoint and 365 Business Premium

### ISSUE THREAD

**Issue by flcev** [MicrosoftDocs/memdocs#1139]
This page states that: 

"To use Microsoft Defender ATP with Intune, be sure you have the following configured, and ready for use:
Licensed tenant for Enterprise Mobility + Security E3 and Windows E5 (or Microsoft 365 Business Premium)"

However as I see it:
Microsoft 365 Business Premium does not include Microsoft Defender for Endpoint and
Enterprise Mobility + Security E3  does not include Microsoft Defender for Endpoint

Am I correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d129246-93fe-04ec-0e49-8e9ac1c910a8
* Version Independent ID: 66d3e475-e2b9-1974-f04a-2ae8b31f96bd
* Content: [Use Microsoft Defender for Endpoint in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/advanced-threat-protection?WT.mc_id=Portal-Microsoft_Intune_DeviceSettings)
* Content Source: [memdocs/intune/protect/advanced-threat-protection.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/advanced-threat-protection.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@flcev    You are correct.  Neither of those products includes Microsoft Defender ATP.  Would it help if the third bullet point of the prerequisite list was moved to be first, and reworked slightly as follows? 

- A Microsoft Defender ATP subscription, which also provides access to the Microsoft Defender Security Center (ATP portal).

**Comment by flcev** [comment]
Yes I think so. The current information is misleading.

**Comment by Brenduns** [comment]
@flcev  Thanks for confirming. I've submitted that change which should be live in the published article later today.
