### ISSUE TITLE
misspelling of Corporate

### ISSUE THREAD

**Issue by dchomas** [MicrosoftDocs/memdocs#114]
Replacing or revoking a token/QR code won't have any effect on devices that are already enrolled.

Sign in to the Microsoft Endpoint Manager admin center and choose Devices &gt; Android &gt; Android enrollment &gt; Coporate-owned dedicated devices.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b915e54-6436-0716-5c8c-e69930499a8f
* Version Independent ID: 99d8b7ca-8e4a-395d-8991-2943b2d3a591
* Content: [Setup Intune enrollment for Android Enterprise dedicated devices - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/android-kiosk-enroll?source=docs#feedback)
* Content Source: [memdocs/intune/enrollment/android-kiosk-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/android-kiosk-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@dchomas Thanks! I'll fix it today.
