### ISSUE TITLE
Site server in passive mode fails to update to version 2010

### ISSUE THREAD

**Issue by Shibaruraya** [MicrosoftDocs/memdocs#1140]
Site server in passive mode fails to update to version 2010
THis issue is also in CM2006

https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/install/release-notes#site-server-in-passive-mode-fails-to-update-to-version-2010

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bea18363-d497-9f92-2c82-e907bf385f36
* Version Independent ID: 2d62fd48-3825-1ed2-c4e4-e42ff2621b29
* Content: [Release notes - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/install/release-notes)
* Content Source: [memdocs/configmgr/core/servers/deploy/install/release-notes.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/deploy/install/release-notes.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @Shibaruraya for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://docs.microsoft.com/answers/products/mem). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time. Our engineering team only recently found this issue with version 2010.
