### ISSUE TITLE
The wording seems impossible on hybrid Autopilot known issue with ESP

### ISSUE THREAD

**Issue by dbaldwin32** [MicrosoftDocs/memdocs#1142]
We are seeing this known issue documented above with a client but the wording makes it sound like no matter what you set the ESP to it will take 40 minutes longer than that timeout?? Or do you just need to set it to longer than 40 minutes?

_'Hybrid Azure AD Autopilot deployment with ESP takes longer than the timeout duration defined in the ESP profile. On Hybrid Azure AD Autopilot deployments, the ESP will take 40 minutes longer than the value set in the ESP profile. This delay gives time for the on-prem AD connector to create the new device record to Azure AD.'_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92ba0166-1d3c-40ca-a2f3-2954dcfe4411
* Version Independent ID: e07d50e2-7a95-868d-5800-ea548c84e884
* Content: [Set up the Enrollment Status Page - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/windows-enrollment-status)
* Content Source: [memdocs/intune/enrollment/windows-enrollment-status.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/windows-enrollment-status.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by MandiOhlinger** [comment]
@dbaldwin32 Good question. It will take will take 40 minutes longer than that timeout: Timeout value + 40 minutes. We updated the article to make that more clear. Thank you.

If you're still seeing issues, and want some help, [How to get support](https://docs.microsoft.com/mem/get-support) has more information.

**Comment by dbaldwin32** [comment]
Thank you, Mandi for the update. I do have a further question then. If it
will always take 40min longer than should the toggle always be selected not
to wait? Otherwise, the hybrid join will never complete during Autopilot
according to this, right??

Thanks much!

**Comment by MandiOhlinger** [comment]
@dbaldwin32 That sounds logical. But, I suggest posting this question to the [Autopilot Q&A](https://docs.microsoft.com/en-us/answers/products/). It'd be good to find out what others are doing, and what's worked for them. As always, you can get support guidance from the Microsoft support teams.
