### ISSUE TITLE
licensing requirements should be added to the page

### ISSUE THREAD

**Issue by luriep** [MicrosoftDocs/memdocs#1144]
This page is missing a link to the Windows Autopilot licensing requirements.  It should probably live under: 
https://docs.microsoft.com/en-us/mem/autopilot/self-deploying#requirements

And refer to licensing requirements for Windows Autopilot at https://docs.microsoft.com/en-us/mem/autopilot/licensing-requirements  

Thanks!
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25e8c073-c36b-180e-a841-ed57ac32dc83
* Version Independent ID: 739ddac5-64f1-161f-b047-50cb737c58da
* Content: [Windows Autopilot Self-Deploying mode](https://docs.microsoft.com/en-us/mem/autopilot/self-deploying)
* Content Source: [memdocs/autopilot/self-deploying.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/self-deploying.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by frankroj** [comment]
Thank you for the feedback @luriep. I apologize for the time it took to get back to you regarding this feedback item. There shouldn't be a need to list the licensing requirements on ever page of the Autopilot docs or for every Autopilot scenario when there is already a whole page dedicated to the subject. You can always refer to the licensing link you mentioned for the licensing requirements:

https://learn.microsoft.com/mem/autopilot/licensing-requirements
