### ISSUE TITLE
Document all possible tokens

### ISSUE THREAD

**Issue by trevonmckay** [MicrosoftDocs/memdocs#1146]
> The {{ and }} characters are used by token types only and must not be used for other purposes.

Are all of the possible tokens documented in this article or can this be found somewhere else. If the content exists it would be helpful to provide a link to the content from this article otherwise the full list of available tokens should be documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee33d638-3024-87d5-1b02-c4568478d1ce
* Version Independent ID: fe0f2aa3-b2dc-486a-4883-9c25ee361fe8
* Content: [Add app configuration policies for managed iOS/iPadOS devices - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-configuration-policies-use-ios)
* Content Source: [memdocs/intune/apps/app-configuration-policies-use-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-configuration-policies-use-ios.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by lenewsad** [comment]
Hi @trevonmckay, thanks for your question. I'm working on finding out this answer for you.

**Comment by lenewsad** [comment]
Hi @trevonmckay, I confirmed that there are no other articles that list tokens so you're in the right place. At the moment, the tokens in this article are the ones we've confirmed to work with Intune.  I created a work item for our team to investigate other tokens. If we confirm that additional ones work, we'll add them to the doc. Hope that helps and thanks again for your curiosity.

**Comment by trevonmckay** [comment]
Thank you @lenewsad
