### ISSUE TITLE
Incomplete description

### ISSUE THREAD

**Issue by infamousdanno** [MicrosoftDocs/memdocs#1147]
[Enter feedback here]
In the "Max pin attempts" section, reset pin only indicates "The user must reset their PIN."  Some users in our group interpreted that to mean someone can just reset the pin and then get in.  Obviously that is not the case, but the documentation (and corresponding Android documentation) could be updated to indicate the user must reset their pin after successfully re-logging into the account and completing an MFA challenge (if required).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c81b9a99-a379-a3b6-0dde-8781da62d16a
* Version Independent ID: 33b4409f-9687-feb7-07ab-7d6bc0d8b9f5
* Content: [iOS/iPadOS app protection policy settings - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policy-settings-ios)
* Content Source: [memdocs/intune/apps/app-protection-policy-settings-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-protection-policy-settings-ios.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@infamousdanno - Thanks for the feedback. I agree. I'm updating the text for both of these articles now. Thanks
