### ISSUE TITLE
References are to iOS not MacOS

### ISSUE THREAD

**Issue by mberry1212** [MicrosoftDocs/memdocs#1149]
This document is supposed to be about MacOS but is clearly referring to iOS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fcba7b2-dcfe-7b92-31d4-68c0463a9cf2
* Version Independent ID: fdc1b2cb-7f5b-7de8-c529-8f6a2b395b38
* Content: [Installing the Company Portal app for macOS](https://docs.microsoft.com/en-us/mem/intune/user-help/what-happens-if-you-install-the-company-portal-app-and-enroll-your-device-in-intune-macos)
* Content Source: [memdocs/intune/user-help/what-happens-if-you-install-the-Company-Portal-app-and-enroll-your-device-in-intune-macos.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/user-help/what-happens-if-you-install-the-Company-Portal-app-and-enroll-your-device-in-intune-macos.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @mberry1212, thanks for your feedback. I see that this article hasn't been updated in a few years so it's definitely time! I did some quick pencil edits to clean up the first section of the article until we can do a much more thorough revision (or removal if this content is redundant). I created an internal work item to track these efforts so I'm going to close this issue. 

Thank you again!
