### ISSUE TITLE
Is DEM enrollment for Android Enterprise COPE device supported?

### ISSUE THREAD

**Issue by nicolonsky** [MicrosoftDocs/memdocs#1150]
As indicated by the docs DEM enrollment for Android corporate-owned devices with work profiles should be supported with a maximum limit of 10 devices. Is this accurate or is an adjustment of the docs required? During testing, with an account that was a member of the device enrollment manager role, I was unable to enroll the device:

![image](https://user-images.githubusercontent.com/32899754/102694355-bb147980-4220-11eb-95b9-2b4f538d90da.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7786d9c0-55b0-9bff-fc0a-f4ee70ee0615
* Version Independent ID: cf0c17a0-fdc7-e0af-db82-913e36d2ec7c
* Content: [Enroll devices using a device enrollment manager account - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-manager-enroll)
* Content Source: [memdocs/intune/enrollment/device-enrollment-manager-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/device-enrollment-manager-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by MandiOhlinger** [comment]
@nicolonsky Good question. Using a DEM account isn't available to enroll COPE devices. We fixed the article. The changes should be live later today. Thanks for bringing this to our attention.
