### ISSUE TITLE
Documentation for updating already-added apps

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/memdocs#1151]
Hello, I'm having trouble finding any information on the process of updating apps.  I'm specifically thinking about Win32 apps for Windows 10.  Is there anything covered for this topic?  If so, can you please help me find those pages?

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a125bda-493d-8beb-e67f-09ff821e8fe4
* Version Independent ID: 39473e48-5fbd-a50c-6732-d86bcd1f7290
* Content: [What is app management in Microsoft Intune?](https://docs.microsoft.com/en-us/mem/intune/apps/app-management)
* Content Source: [memdocs/intune/apps/app-management.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-management.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@JeremyTBradshaw - Win32 apps are essential LOB apps. You can find more info in this section of the Windows LOB apps topic: [Update a line-of-business app](https://docs.microsoft.com/mem/intune/apps/lob-apps-windows#update-a-line-of-business-app).

If you have additional questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

**Comment by JeremyTBradshaw** [comment]
Thanks @Erikre .
