### ISSUE TITLE
Is there a working plist example for Microsoft edge?

### ISSUE THREAD

**Issue by BigIve** [MicrosoftDocs/memdocs#1152]
Hi I'd like to know if there is a working plist example file for Microsoft Edge.  I've tried the version that can be downloaded from the Microsoft Edge page.
But no matter how it is formatted (e.g. removing the list and dict flags as per this page) Intune WILL NOT deploy it as it says it couldn't validate the file.
This is extremely frustrating and is currently doing my head in.  Please advise how the list file is to be 'correctly formatted' for deployment via Intune.

**Comment by MandiOhlinger** [comment]
@BigIve What article are you referring? Please include the link. Thanks!

**Comment by MandiOhlinger** [comment]
@BigIve If you still need some help, you have some options:

- Post your issue on [Microsoft Q&A](https://docs.microsoft.com/answers/products/enterprise-mobility-security). These are moderated by our community MVPs, who are very experienced, knowledgeable, and helpful. 
- Use [get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a support case.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager. 

If you got this working, and you think others would benefit with a documentation update, please create a pull request in the article you're referring. If you're not sure how to update an article, then the steps are at [https://github.com/MicrosoftDocs/memdocs](https://github.com/MicrosoftDocs/memdocs). Just scroll past the folder view.
