### ISSUE TITLE
Confused with Minimum Appraiser Version 

### ISSUE THREAD

**Issue by Navneet-Singh-Ghura** [MicrosoftDocs/memdocs#1154]
In this doc its mentioned minimum Appraiser Version is 1001**776**3. But if I go on the client machine and check in WMI. 
It says minimum appraiser version should be 1001**767**3. So i think there is a typo in this document, as I believe WMI should be correct. I can share further WMI details if required. 

- [ ] 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 819ede64-7469-d780-6420-bc785f459a1e
* Version Independent ID: d80b24c8-02d3-8958-79cb-10db3a6c8785
* Content: [Monitor connection health - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/desktop-analytics/monitor-connection-health)
* Content Source: [memdocs/configmgr/desktop-analytics/monitor-connection-health.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/desktop-analytics/monitor-connection-health.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @Navneet-Singh-Ghura, good catch, does look to be a typo, transposing those two numbers. I confirmed by checking the [Win7 KB](https://support.microsoft.com/help/2952664/compatibility-update-for-keeping-windows-up-to-date-in-windows-7) that updates appraiser.dll to version 10.0.17673.
