### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by dedimitrov** [MicrosoftDocs/memdocs#1155]
This document states that Azure AD Premium and Intune licensing is required, but at Ignite it was confirmed that no additional licensing is required for Co-management if the customer has the end devices covered by Config Manager. Can the article be updated with the correct information please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b813a55b-0679-f80c-983f-782b394c748c
* Version Independent ID: ea738339-f10c-10f2-91ab-a2b87b342b12
* Content: [Tutorial: Enable co-management for existing clients - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/comanage/tutorial-co-manage-clients)
* Content Source: [memdocs/configmgr/comanage/tutorial-co-manage-clients.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/comanage/tutorial-co-manage-clients.md)
* Product: **configuration-manager**
* Technology: **configmgr-comanage**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @dedimitrov, there's a link from the [main co-management prerequisites](https://docs.microsoft.com/mem/configmgr/comanage/overview#prerequisites) to this FAQ which answers your question: [What changes with licensing for co-management in Microsoft Endpoint Manager?](https://docs.microsoft.com/mem/configmgr/core/understand/product-and-licensing-faq#bkmk_mem)
