### ISSUE TITLE
Links are directing to the wrong page

### ISSUE THREAD

**Issue by ibawwad** [MicrosoftDocs/memdocs#1157]
This link in the page referring to see Set up iOS/iPadOS device access to your company resources is actually referring to a MacOS page (https://docs.microsoft.com/en-us/mem/intune/user-help/enroll-your-device-in-intune-macos-cp), not an iPhone/iPadOS page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59482bb2-51be-0adf-0452-ad2381233577
* Version Independent ID: 82fe5d21-4a76-dd37-db40-84eeaf6f6294
* Content: [Enroll iOS/iPadOS devices - User Enrollment - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/ios-user-enrollment?WT.mc_id=Portal-Microsoft_Intune_Enrollment)
* Content Source: [memdocs/intune/enrollment/ios-user-enrollment.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/ios-user-enrollment.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by MandiOhlinger** [comment]
@ibawwad Thank you! In the future, it'd be great if you created a pull request (PR) with changes like this. We certainly want and appreciate the help. I fixed the link. Changes should be live sometime tomorrow.
