### ISSUE TITLE
instructions do not match!

### ISSUE THREAD

**Issue by JeroenVBH** [MicrosoftDocs/memdocs#116]
Turn on Real-time Protection step3 tells me to "Open Computer Configuration &gt; Administrative Templates &gt; Windows Components &gt; Windows Defender Security Center &gt; Virus and threat protection." but Windows Defender Security Center  is not in there?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76b07dd3-8f84-c715-76f5-c22c2a98b5f3
* Version Independent ID: b212305e-9b54-f6cd-81bd-f23254f6891a
* Content: [Turn on Windows Defender](https://docs.microsoft.com/en-us/mem/intune/user-help/turn-on-defender-windows#feedback)
* Content Source: [memdocs/intune/user-help/turn-on-defender-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/user-help/turn-on-defender-windows.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by dr-raypc** [comment]
I am also experiencing the same issue.
Microsoft, can you please update your own documentation to reflect what is current for managing Windows Defender via Group Policy?

**Comment by lenewsad** [comment]
Hi @JeroenVBH and @dr-raypc, thanks for sharing you experience. I've opened a case here on our side to update this article with the accurate labels. I'll close this issue after the article has been updated. Thank you for your patience!
