### ISSUE TITLE
Where can I find specification of v3 third-party update catalog format

### ISSUE THREAD

**Issue by guliteb** [MicrosoftDocs/memdocs#1161]
Where can I find specification of v3 third-party update catalog format?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4297c3f-8555-19d1-97bd-2b80de947f78
* Version Independent ID: ce761853-8fb2-9324-ca6d-4a4233d289f8
* Content: [Enable third party updates - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/sum/deploy-use/third-party-software-updates?source=docs#update-the-schedule-per-catalog)
* Content Source: [memdocs/configmgr/sum/deploy-use/third-party-software-updates.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/sum/deploy-use/third-party-software-updates.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
I don't think there's a documented specification for the update catalog, I know we don't publish anything. The Windows Update documentation might have something.

[System Center Updates Publisher](https://docs.microsoft.com/mem/configmgr/sum/tools/updates-publisher) is the tool to create and manage custom update catalogs.
