### ISSUE TITLE
Why is this token type revocable, when Fully Managed's token is not?

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/memdocs#1162]
I'm unclear on why there's attention to the ability to revoke the COPE profile token but not the Fully Managed token.  If we're needing devices' IMEI or serial numbers to be added to Corporate Identifiers in order to be pre-deemed as 'Corporate-Owned', what is the risk of this token being 'accidentally' shared?  Worded another way in case this helps clarify what I'm asking - is there some risk with this token that is different and/or more severe than the risk associated with the Fully Managed token?

Thanks in advance.

PS.  The same question applies to the Dedicated profile tokens as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54658e86-7300-d033-4a54-8375e251c894
* Version Independent ID: 3c2c1763-5c7f-fd65-aced-b5670196598e
* Content: [Setup Intune enrollment for Android Enterprise corporate-owned devices with corporate-owned work profile - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/android-corporate-owned-work-profile-enroll)
* Content Source: [memdocs/intune/enrollment/android-corporate-owned-work-profile-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/android-corporate-owned-work-profile-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
9050110

**Comment by ErikjeMS** [comment]
@JeremyTBradshaw Here's the PM's response: "For fully managed we do not support creating token profiles the way we do for COPE or dedicated, so revoking the token doesn't have the same implications. This capability is tied to the ability to create multiple tokens for their org - and revoking a token is part of the token management workflow. For Fully managed device, we have a single tenant wide QR code so 'revoking' this token would be the same as disabling Fully managed enrollments. There is no security differences between COPE and COBO that is driving this."
If this doesn't answer your question, let me know and I'll reopen this issue.

**Comment by JeremyTBradshaw** [comment]
Hi @ErikjeMS , it actually doesn't answer the question of why, it just is a summary of how things are designed today, but still with no reason why we have the different approach for Fully Managed vs the other methods.

**Comment by ErikjeMS** [comment]
@JeremyTBradshaw I'll ask them again.
