### ISSUE TITLE
microsoft 360

### ISSUE THREAD

**Issue by thienhap** [MicrosoftDocs/memdocs#1165]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebb41d4f-a321-d272-ba76-1e8b7e13ce22
* Version Independent ID: a00debf0-79da-be24-a689-d559883937a5
* Content: [Collections introduction - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/collections/introduction-to-collections)
* Content Source: [memdocs/configmgr/core/clients/manage/collections/introduction-to-collections.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/collections/introduction-to-collections.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
I'm assuming this is a test or accident, so am closing it. If you have feedback on this article, please reopen it and provide further information. For more information on filing doc feedback, see [How to use the docs](https://docs.microsoft.com/mem/use-docs).
