### ISSUE TITLE
Wrong PowerShell variable

### ISSUE THREAD

**Issue by nclinch** [MicrosoftDocs/memdocs#1166]
change:
# Write a message to a log file
Write-Output "Hello world!" | Out-File -FilePath "$_SMSTSLogPath\mylog.log" -Encoding "Default" -Append

to:
# Write a message to a log file
Write-Output "Hello world!" | Out-File -FilePath "$LogPath\mylog.log" -Encoding "Default" -Append

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b601ce41-e08d-b2ab-bfca-dcab191b6950
* Version Independent ID: 6d67cf1a-fb3e-7f38-8bde-ec89c839765b
* Content: [How to use task sequence variables - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/osd/understand/using-task-sequence-variables)
* Content Source: [memdocs/configmgr/osd/understand/using-task-sequence-variables.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/osd/understand/using-task-sequence-variables.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @nclinch for the feedback. You're right, that makes it a more functional example with less modification. I'll change it shortly.

In the future, I encourage you to submit the change yourself! 😉 For more information, see [How to use the docs](https://docs.microsoft.com/mem/use-docs#contribute).
