### ISSUE TITLE
typo - NSIT / NIST

### ISSUE THREAD

**Issue by J-Fedor** [MicrosoftDocs/memdocs#1167]
[Enter feedback here]
Middle of the page there's a heading with NSIT, but believe it should be NIST.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c553157-31cf-faf9-0b4c-00f1a56f0545
* Version Independent ID: c91b6b7b-3264-f0f7-688e-baac0ce3a718
* Content: [Learn about security baselines in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/security-baselines)
* Content Source: [memdocs/intune/protect/security-baselines.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/security-baselines.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@J-Fedor  Yep, that's a typo, and a fix will go live later today.  Thanks for brining this to our attention.
