### ISSUE TITLE
Here's one for UserVoice, which I'll report here too

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/memdocs#1173]
I have a lot to whine about as it relates to the Android Enterprise Fully Managed Device Restrictions setting below.  I'm quoting the article here:

> **Allow access to all apps in Google Play store**: When set to Allow, users get access to all apps in Google Play store. They don't get access to the apps the administrator _**blocks**_ in [Client Apps](https://docs.microsoft.com/en-us/mem/intune/apps/apps-add-android-for-work).
> 
> When set to Not configured (default), Intune doesn't change or update this setting. By default, the OS might:
> 
> * Force users to only access the apps the administrator makes available in the Google Play store, or apps required in [Client Apps](https://docs.microsoft.com/en-us/mem/intune/apps/apps-add-android-for-work).
> * Automatically uninstall any apps that are detected as being installed by users outside of the Google Play store.
> If you want to enable side-loading, set the Allow installation from unknown sources and Allow access to all apps in Google Play store settings to Allow.

Let me begin.  First, there is no such thing as "Block", nor a single mention of that word in the linked "Client Apps" page.  Second, what good is this?:

> When set to Not configured (default), Intune doesn't change or update this setting. By default, the OS might:
> * Force users to only access the apps the administrator makes available in the Google Play store, or apps required in [Client Apps](https://docs.microsoft.com/en-us/mem/intune/apps/apps-add-android-for-work).
> * Automatically uninstall any apps that are detected as being installed by users outside of the Google Play store.

The behavior in my testing is most certainly that **Not Configured** translates to **only approved apps from the managed Play Store show up**.  But I'm curious why this article is written this way, and who thinks that would be OK?  What would the point of the Managed Play Store be, if you couldn't have any control over what apps are available through it?  It would be 100% pointless.  I'm 99% sure that this problem only exists in the writing on this page.  It should say:

> When set to Not configured (default), only apps that have been approved in the managed Play Store will show up in the Play Store app.

Third, and now this might be a dig on Google, or maybe both them and Microsoft (hard to say for sure), if you turn this setting to **Allow** and the user doesn't add their own Google account (either because it's not allowed, or because they just didn't bother), the user can tap on the hamburger icon in the Play Store app, then go to **My apps & games** and review the list of apps that anyone (in the entire organization with an enrolled device) has installed.  They can also remove apps from that list.  They are essentially acting as the generic/service account (01*****@android-for-work.gserviceaccount.com).  This is not that big of a deal, but certainly is not great either.

(admin edit: adding article metadata for proper linking and tracking)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 900e72be-d42b-49ba-f304-602df23cbb04
* Version Independent ID: 2ce5c45d-15be-d316-1c57-92bea37358e0
* Content: [Android Enterprise device settings in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-android-for-work#applications)
* Content Source: [memdocs/intune/configuration/device-restrictions-android-for-work.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/device-restrictions-android-for-work.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@JeremyTBradshaw Thank you for your feedback. Our docs are in a public GitHub repository, and are open to community contributions. When you see descriptions that could be more clear, we encourage you and want to you to help make them better. 

That being said. The "blocks" is confusing. As you've said, you can't block apps. The wording is fixed. 

Also, we can't remove the **Intune doesn't change or update this setting** text. For the first bullet, what you wrote is better. Thank you.

Changes should be live later today.
