### ISSUE TITLE
Wrong portal name and link

### ISSUE THREAD

**Issue by jaymichaud** [MicrosoftDocs/memdocs#1175]
This article is about using the Azure portal, and all of the screen illustrations depict the Azure portal as expected, but the text of the article instructs readers to instead use the _Intune portal_ in each numbered item under the heading, _Tour Microsoft Intune_. I believe this is an error. This can be corrected by updating every link of "Intune portal" and "Intune" to "Azure portal" with the link [https://portal.azure.com/](https://portal.azure.com/).

Also, the content source Markdown filename and the URL both include "intune-portal" rather than "azure-portal".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 873ed0fb-9b09-fba1-ed4b-0a2a305634fc
* Version Independent ID: 2ead72fc-1bd7-7fd6-1632-7119815377d8
* Content: [Tutorial - Walkthrough Intune in the Azure portal - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/tutorial-walkthrough-intune-portal#tour-microsoft-intune)
* Content Source: [memdocs/intune/fundamentals/tutorial-walkthrough-intune-portal.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/tutorial-walkthrough-intune-portal.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by jaymichaud** [comment]
After submitting this issue, I continued with the tutorial and found that the Azure portal no longer has the functionality described in the article; it just redirects users to the new Microsoft Endpoint Manager admin center. Maybe the whole article should be deleted instead of edited, since the functionality it describes seems no longer to exist.

<img width="693" alt="Azure-portal-Microsoft-Intune-has-moved" src="https://user-images.githubusercontent.com/16993344/103462382-d8524900-4cf2-11eb-9fdd-c94ae86640ba.png">

**Comment by Erikre** [comment]
@jaymichaud - Thanks for the feedback. I'm doing an initial update of this topic now. It should be published later today. Thanks again.
