### ISSUE TITLE
please update documentation

### ISSUE THREAD

**Issue by HenryvanderHeide** [MicrosoftDocs/memdocs#1177]
The quote on this page isn't correct (anymore) "Passcode reset isn't available for devices running Android 7.0 and later. If you forget your passcode on one of these devices, you must reset it to factory settings." 

a Android 10.0 device does have the option to reset the passcode from the management interface.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3135437-2b7c-da11-38f1-eda3d07de967
* Version Independent ID: eecdb690-105c-7d4e-27bc-bfec129c25b4
* Content: [How to reset your passcode from the Company Portal website](https://docs.microsoft.com/en-us/mem/intune/user-help/reset-your-passcode-cpwebsite)
* Content Source: [memdocs/intune/user-help/reset-your-passcode-cpwebsite.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/user-help/reset-your-passcode-cpwebsite.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @HenryvanderHeide, thanks for reaching out to Docs. To clarify, this article is for people using the web version of Intune Company Portal to reset their passcode. I tested it on an Android 11 and there was no option to reset it in Company Portal. So I think what you mean is to change this part to say that their IT admin could reset it for them from Intune (the admin interface)--is that right? Let me know if I'm understanding correctly. In the meantime, I'll verify this with the product team. It might take a while to confirm so thanks for your continued patience!

**Comment by lenewsad** [comment]
Hi @HenryvanderHeide, you're right that the reset option is available on more devices now. I just updated the article and you can expect to see the changes by the end of the week. Thanks again for your contribution to docs!
