### ISSUE TITLE
Possible conflict or changing feature?

### ISSUE THREAD

**Issue by toanyonebutyou** [MicrosoftDocs/memdocs#118]
In the above it states that like of sight too a domain controller is required and vpn is not supported at this time. 

According to this though, around the 8 minute mark, vpn is supported with 1909. 

https://techcommunity.microsoft.com/t5/business-continuity-and-disaster/provision-windows-devices-from-anywhere-to-support-a-mobile/m-p/1289174#

Any clarification here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a94c428-95df-632b-46e8-4386ad551a03
* Version Independent ID: f23998f0-52ff-1203-1a0c-ff5c25b08c1c
* Content: [Enrollment for hybrid Azure AD-joined devices - Windows Autopilot](https://docs.microsoft.com/en-us/mem/intune/enrollment/windows-autopilot-hybrid#feedback)
* Content Source: [memdocs/intune/enrollment/windows-autopilot-hybrid.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/windows-autopilot-hybrid.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
(7054807)

**Comment by ErikjeMS** [comment]
@toanyonebutyou The client-side support for this was in December. However, the server-side support that has not been released. So, the sentence in the article is still accurate. Keep watch on the [In-Development](https://docs.microsoft.com/en-us/mem/intune/fundamentals/in-development) and [What's New](https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new) pages for information on when server-side support will be released.
