### ISSUE TITLE
The log file is schedule.log, not scheduler.log (Prepare the install job)

### ISSUE THREAD

**Issue by PanuSaukko** [MicrosoftDocs/memdocs#1180]
The flowchart refers to a wrong log file in "Prepare the install job" phase. The correct log file name is schedule.log, not scheduler.log.

Panu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4466280-5fdf-18e9-7d15-ce6259ec641b
* Version Independent ID: ea742435-b7e9-de0b-647e-a31881b8e34c
* Content: [Set up site server in passive mode - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/passive-site-server-flowchart)
* Content Source: [memdocs/configmgr/core/servers/deploy/configure/passive-site-server-flowchart.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/deploy/configure/passive-site-server-flowchart.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @PanuSaukko, good catch. scheduler.log is the client log.

**Comment by aczechowski** [comment]
Thanks to @ChrisKibble for submitting a change for this issue!
