### ISSUE TITLE
These steps take you in a loop.

### ISSUE THREAD

**Issue by AdamGrossTX** [MicrosoftDocs/memdocs#1181]
The Before you begin section has a link to Create a device profile. That takes you to https://docs.microsoft.com/en-us/mem/intune/configuration/wi-fi-settings-configure#create-the-profile. Under step 7, you can click on the platform you want. If I click Windows 8.1 and newer, it takes me right back to this doc.  

The issue I found was that I was trying to import Wi-Fi settings but I was choosing the Windows 10 and new Platform and not seeing the Import Wi-Fi option. I didn't realize I was on the Windows 8.1 docs since the Applies To section says Windows 10, but in the table of contents on the left, I noticed I was under Windows 8.1.

Basically, the Before you Begin section makes it seem like you need to fully create a Wi-Fi profile, before continuing, when in reality you only want to follow the first 7 steps then proceed by selecting Wi-Fi Import next.

![image](https://user-images.githubusercontent.com/20917262/103678744-89522100-4f49-11eb-9603-f3449094ed0a.png)

![image](https://user-images.githubusercontent.com/20917262/103678753-8c4d1180-4f49-11eb-9095-377ea932c736.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e46e8fe-9289-4d25-9959-3ac871c7a5a5
* Version Independent ID: fa0d6f1a-dd8e-4ac1-1ee3-a2fe567cf365
* Content: [Import Wi-Fi settings for Windows devices in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/wi-fi-settings-import-windows-8-1#feedback)
* Content Source: [memdocs/intune/configuration/wi-fi-settings-import-windows-8-1.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/wi-fi-settings-import-windows-8-1.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@AdamGrossTX I see your point. We need to call out the Wi-Fi import feature, instead of it being hidden under Windows 8.1. I'm on it from a docs perspective. Changes should be live later today/tomorrow sometime. 

Thanks for this issue. It's a good one.
