### ISSUE TITLE
No information about Derived Credentials

### ISSUE THREAD

**Issue by AdamGrossTX** [MicrosoftDocs/memdocs#1182]
When creating a Wi-Fi profile, there's an option for Derived Credential when you select certain EAP options but the docs don't mention Derived Credential or in which cases it should be used. Perhaps add a link to https://docs.microsoft.com/en-us/mem/intune/protect/derived-credentials#derived-credentials-for-windows for more info.

![image](https://user-images.githubusercontent.com/20917262/103680478-d7682400-4f4b-11eb-8a26-b4b14075719e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2c27850-c79f-dbd0-4f43-0448fa0aeca7
* Version Independent ID: f3540fb3-ec93-0b0e-0d24-00a2e93fd8b8
* Content: [Wi-Fi settings for Windows 10 devices in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/wi-fi-settings-windows)
* Content Source: [memdocs/intune/configuration/wi-fi-settings-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/wi-fi-settings-windows.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@AdamGrossTX You are correct. Thank you for letting us know. The doc changes should be live sometime tomorrow.
