### ISSUE TITLE
Instructions are outdated. There is no ...More button

### ISSUE THREAD

**Issue by Kenshinryu** [MicrosoftDocs/memdocs#1186]
On step 3 of locating a lost iPad or iOS device there is no ...More button. 

Step: From the list of devices you manage, choose an iOS/iPadOS device, and choose ...More. Then choose the Locate device remote action.

So I'm unable to complete the next step in locating the device. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf0d4fa4-c4a0-6a69-3d86-5b34ccf8cbad
* Version Independent ID: 112c8b86-6df1-6fb8-4b7c-9bc2b5d15c2a
* Content: [Find lost iOS/iPadOS devices with Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/remote-actions/device-locate)
* Content Source: [memdocs/intune/remote-actions/device-locate.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/remote-actions/device-locate.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@Kenshinryu You're correct. It now just shows "...". I'll update the doc today. Thanks!
