### ISSUE TITLE
Screenshot for Registry Detection Rule shows incorrect syntax

### ISSUE THREAD

**Issue by asjimene** [MicrosoftDocs/memdocs#1188]
For Registry Detection rules, the docs state:

- Registry: Verify based on value, string, integer, or version.
  - Key path: The full path of the registry entry that contains the value to detect. A valid syntax is HKEY_LOCAL_MACHINE\Software\WinRAR or HKLM\Software\WinRAR.

However, the screenshots posted below show the registry key in the form of: "Computer\HKEY_LOCAL_MACHINE..."

The text in the document contradicts what is shown in the screenshot, which can be very confusing.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca840cce-3b99-3009-c8fa-d5fab6ae37d0
* Version Independent ID: 928b9e37-626a-8d50-c6a1-ac0b5cad4be4
* Content: [Add and assign Win32 apps to Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-win32-add)
* Content Source: [memdocs/intune/apps/apps-win32-add.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/apps-win32-add.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
Thanks for the feedback. I'm publishing the update today.
