### ISSUE TITLE
Can the wording be changed here and still be correct and true?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/memdocs#1189]
> Your company support can't manage the personal data on your device.

Being able to manage something or not is not the necessary words to see here.  It leaves open far too many possibilities. Something like this would be what we would expect to see...

> Your company support can't view or access any of the non-work profile data on your device.

Unambiguous as to what they can and cannot see.

The Play store page for this all says it needs permission to read the contents of shared storage. That tells me that the company can view data that is not theirs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50b13370-965f-0a72-9226-f119229ba68a
* Version Independent ID: 089ce4b0-bf8d-3936-82a9-e29029fc7df1
* Content: [Enroll Android work profile with Intune Company Portal](https://docs.microsoft.com/en-us/mem/intune/user-help/enroll-device-android-work-profile)
* Content Source: [memdocs/intune/user-help/enroll-device-android-work-profile.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/user-help/enroll-device-android-work-profile.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @StingyJack, thanks for your question and I do like your edit. I'll check with the product team and see if it still keeps the doc honest. It might take a while to confirm so thanks for your patience.

**Comment by lenewsad** [comment]
Hi @StingyJack, just wanted to let you know that we're updating the language to make it clearer, so you should see those changes go live on 2/5/2021. Thanks again for reaching out to the docs team with that suggestion.
