### ISSUE TITLE
Lots of questions people might have are not covered here...

### ISSUE THREAD

**Issue by ambanmba** [MicrosoftDocs/memdocs#119]
1. Where are the scripts stored on the local machine (or are they not?)
2. Running /Library/Intune/Microsoft\ Intune\ Agent.app/Contents/MacOS/IntuneMdmDaemon 
 in Terminal seems to produce output - what does it mean? Are there any command line parameters?
3. Will it run on macOS devices enrolled with Device Affinity

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44b04772-bcf6-51f9-8328-20714583e2a6
* Version Independent ID: f50b96e7-b17e-ab68-2b85-051b590f2f51
* Content: [Use shell scripts on macOS devices in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/macos-shell-scripts#known-issues)
* Content Source: [memdocs/intune/apps/macos-shell-scripts.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/macos-shell-scripts.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
We have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. If you have continue to have questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

Please use the above channels if you don't already have a solution.
