### ISSUE TITLE
Update configuration names

### ISSUE THREAD

**Issue by afield1235** [MicrosoftDocs/memdocs#1191]
Why are these so cryptic? For example, a yes to “ Touch ID and Face ID unlock” actually does the opposite, it doesn’t allow Touch ID. Why doesn’t it say “Block Touch ID and Face ID unlock:“ instead like the other options? Someone should review and adjust all of these that are not clear and consistent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88932dd8-abce-bf23-9624-1df5f60a946d
* Version Independent ID: ab2d932f-e375-2485-a6e5-e02daf7a27c4
* Content: [iOS/iPadOS device settings in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-ios)
* Content Source: [memdocs/intune/configuration/device-restrictions-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/device-restrictions-ios.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@afield1235 I hear ya. There's been some recent improvements to update the UI settings with a beginning action word, like "block", "allow", "require", etc. Not sure why this setting doesn't have it. Either way, I shared your feedback with the PM.
