### ISSUE TITLE
Use Update Compliance section needs update

### ISSUE THREAD

**Issue by jandreacola** [MicrosoftDocs/memdocs#1192]
Example Setting name and description refers to Windows Analytics - this does not exist and should be updated to reflect better example.

Value setting is also outdated.  There is no OMS workspace (now log analytics) and there is no Windows Telemetry tab.  Need correct directions on getting Commercial ID

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7024ad8-b24b-598c-8b16-2da8bc15e9e4
* Version Independent ID: 230e96a7-e771-e6dd-d5f4-ac8b514fb4d4
* Content: [Use Update Compliance reports for Windows Updates in Microsoft Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/windows-update-compliance-reports#use-update-compliance)
* Content Source: [memdocs/intune/protect/windows-update-compliance-reports.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/windows-update-compliance-reports.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@jandreacola  Thanks for bringing this outdated example to our attention.  After a bit of investigation, I’ve submitted an edit to fix the example which will be live later today. In place of Windows Analytics, use Update Compliance. 

I'll note that this pending update is a stop gap, as some additional work to bring this content up to date, and provide more clear guidance on setting up Update Compliance for use with Intune is still pending. That work will be published in the days or weeks ahead after some deeper review.
