### ISSUE TITLE
Administrative Template profile - Windows 10

### ISSUE THREAD

**Issue by harikrishnahn** [MicrosoftDocs/memdocs#120]
Hi Team,

when i am checking the One-Drive Administrative template profile setting for windows 10 , There is no setting, before one drive setting is available but i can find the one drive folder inside the folder no setting is available. please check this and add on this as high priority.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d16c28db-1e8e-31fa-6127-3050a2940422
* Version Independent ID: 4cf9a244-1ae5-1637-48f7-3f503d400da6
* Content: [What's new in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new#feedback)
* Content Source: [memdocs/intune/fundamentals/whats-new.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/whats-new.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by harikrishnahn** [comment]
Please provide some solution on this 🙏

**Comment by ErikjeMS** [comment]
@harikrishnahn Thanks for taking the time to share this with the Intune documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a few options available to provide the fastest level of support for this:   
- Post on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.   
- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.   
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.   
I'm closing this issue as there's nothing actionable for docs at this time.
