### ISSUE TITLE
process for obtaining SCCM key is incorrect

### ISSUE THREAD

**Issue by bertsawicki** [MicrosoftDocs/memdocs#1201]
I called into support and they say the process for obtaining an SCCM key outlined in Internal article 4033838 has changed and partners need to submit a Partner Center support request.  please update the documentation.
Paragraph below that needs correction
"Yes, you have rights to use Configuration Manager to manage clients covered by the EMS license. First download and install the evaluation software. Then contact Microsoft Support to obtain the license key. When you talk with Microsoft Support, ask them to reference the internal article ID 4033838."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f3023a8-ab6c-1d77-0111-77cc7583347c
* Version Independent ID: 26debf60-c3c1-caa6-7f78-a04a8b8e73af
* Content: [Product and licensing FAQ - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/understand/product-and-licensing-faq)
* Content Source: [memdocs/configmgr/core/understand/product-and-licensing-faq.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/understand/product-and-licensing-faq.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hmm...I'm not sure that's correct, but I'll followup. This process has unfortunately been fraught with difficulty, but outside of our control. I'll keep this open as I check into it. Thanks for letting me know, and sorry for the trouble.

**Comment by bertsawicki** [comment]
I’ve spent a couple of hours on the phone with support who gave me this information.  If you have access to the internal document, that should be where it states the new process.



Bert Sawicki      See my Availability<https://outlook.office365.com/owa/calendar/BertsCalendar@connection.com/bookings/>
Microsoft Solutions Associate
Microsoft Center of Excellence
bert.sawicki@connection.com<mailto:bert.sawicki@connection.com>
Phone: 800-800-0014 x76262     Mobile: 603-583-0978
www.connection.com<http://www.connection.com/>​
CSP SUPPORT 24/7
cloud.support@connection.com<mailto:cloud.support@connection.com>
800-793-2222, option 1 to reach technical support.

[cid:image001.png@01D6E5DE.2DB7A9C0]
LINKEDIN<https://www.linkedin.com/company/connection-it/>  l  TWITTER<https://twitter.com/ConnectionIT>  l  FACEBOOK<https://www.facebook.com/Connection4IT/>  l  INSTAGRAM<https://www.instagram.com/ConnectionIT/>  l  YOUTUBE<https://www.youtube.com/c/ConnectionIT>  l  BLOG<https://www.connection.com/social-blog>
[Image result for azure az 900 badge]  [cid:image005.png@01D6E5DE.7EEBEEA0]

**Comment by aczechowski** [comment]
FYI, when replying via email, your signature gets added to this public post on GitHub... I updated your post to remove your personal information 😄 

I do have access to the KB, and it doesn't mention a new process or really much that I can see about requiring a Partner Center support request. The last revision to the article was on November 25, 2019. I'm checking with a couple different folks that should know more about it.

**Comment by aczechowski** [comment]
I got confirmation from others that the process hasn't changed, so unfortunately this was probably just a case of a support person not properly reading the article or misunderstanding it. Sorry for the challenge.
I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by bertsawicki** [comment]
Thanks for looking into this...if only you could connect me with a support person who knew the correct path!!
