### ISSUE TITLE
Request for Plist Example

### ISSUE THREAD

**Issue by BigIve** [MicrosoftDocs/memdocs#1203]
Hi @MandiOhlinger, 
I posted a question regarding wanting an example of a working plist example for MS Edge.  It was issue 1152.  I missed the replies as I was away and didn't have reliable access to the internet.  The article I was referring to is: 
https://docs.microsoft.com/en-us/mem/intune/configuration/preference-file-settings-macos
I downloaded the files for Edge Chromium and tried to use the list example that came with it.  Intune wouldn't allow me to upload it saying the file wasn't in the correct formatting.  Even when I formatted it as per the article above.
The only way I could get it to work was to follow a different set of instructions and 'wrap' the file using an apple deployment tool.  I'd really like to be able to make use of the 'native' MS capability in Intune if I can.
Are there any step by step instructions or working examples that can be leveraged for this?
Regards,

Ivan

**Comment by MandiOhlinger** [comment]
@BigIve Thank you for the extra information. That helped. There are some examples in [Set preferences for Microsoft Defender for Endpoint](https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-atp/mac-preferences). We added a link to that article. The changes should be live later today.

Once you add/create the plist, you can add an example to the Intune article, if you'd like. We want and encourage community contributions. The steps to create a pull request are at [https://github.com/MicrosoftDocs/memdocs](https://github.com/MicrosoftDocs/memdocs). Just scroll past the folder view.
