### ISSUE TITLE
Incorrect KVP in APP

### ISSUE THREAD

**Issue by zlDev** [MicrosoftDocs/memdocs#1209]
**All Apps** is not a correct value for the **Transfer telecommunication data to** setting in **Level 2 enterprise enhanced data protection** section

Probably should say **Any dialer App**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d9a11b1-ff48-8c1e-9dbe-c48a7e4dc350
* Version Independent ID: 6bd15450-157a-e2e8-c636-e692c7ff6e81
* Content: [Data protection framework using app protection policies - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-framework)
* Content Source: [memdocs/intune/apps/app-protection-framework.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-protection-framework.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by lenewsad** [comment]
Thanks for pointing that out @zlDev. I'll confirm the correct value with our product team and get this article updated.

**Comment by lenewsad** [comment]
Hi @zlDev, "Any dialer app" is the correct value. You should see that change go live within the next week. Thanks again for your contribution!
