### ISSUE TITLE
MEM/SCCM Product Key for M365 E5/EMS E5

### ISSUE THREAD

**Issue by fryjr82** [MicrosoftDocs/memdocs#121]
I am being bounced around like a pinball trying to find someone to provide us with a Product Key.  We have both M365 E5/EMS E5 licenses directly with MS (no CSP).

I mention the internal KB but still nothing: https://internal.support.services.microsoft.com/en-us/help/4033838

This has been an issue for almost 2yrs according to [this Github Issue](https://github.com/MicrosoftDocs/SCCMdocs/issues/493).

It would be nice to know exact steps required to get a Product Key than just call MS Support.  MS Support sends me to 365 Support and I just keep getting bounced around for days.  Last bounce was to a Tech Support on Intune team.

**Comment by fryjr82** [comment]
Well it only took 4 days of being bounced around to get back to the MS Online Service team and she provided me the Keys.  So I am not sure why the docs say to contact MS Support though.  

This is who helped me (I truncated her Last Name):
Abigail Z.| Microsoft Online Service | Office 365 Online Support Team

**Comment by aczechowski** [comment]
Hi @fryjr82 thanks for the feedback, and sorry for the difficulty. I'm glad that you were finally able to get help.
