### ISSUE TITLE
Docume ntation require amendment

### ISSUE THREAD

**Issue by zlDev** [MicrosoftDocs/memdocs#1210]
"Biometric instead of PIN for access" is not a valid setting in APP
probably should read as "Touch ID instead of PIN for access (iOS 8+/iPadOS)" and "Face ID instead of PIN for access (iOS 11+/iPadOS)"
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d9a11b1-ff48-8c1e-9dbe-c48a7e4dc350
* Version Independent ID: 6bd15450-157a-e2e8-c636-e692c7ff6e81
* Content: [Data protection framework using app protection policies - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-framework)
* Content Source: [memdocs/intune/apps/app-protection-framework.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-protection-framework.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@zlDev - Thanks for the feedback. Making these changes now.
