### ISSUE TITLE
Confirm a statement: This task sequence step runs only in Windows PE. It doesn't run in the full OS.

### ISSUE THREAD

**Issue by gwblok** [MicrosoftDocs/memdocs#1215]
[Enter feedback here]
https://docs.microsoft.com/en-us/mem/configmgr/osd/understand/task-sequence-steps#BKMK_CaptureUserState
Under "Capture User State" it says:
This task sequence step runs only in Windows PE. It doesn't run in the full OS.
That doesn't seem true, I run the capture during the full OS.
I have some images here of a capture during full OS: 
https://docs.recastsoftware.com/ConfigMgr-Docs/TaskSequence/SCCM_TaskSequence_Step_UserState_ComboStep.html

Can you confirm this was meant to say that is has to be run in WinPE?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8d2232b-5503-07b6-29fd-8afcdcea9a89
* Version Independent ID: 9621b35d-5928-2319-1048-eff6fa6a2e70
* Content: [Task sequence steps - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/osd/understand/task-sequence-steps#BKMK_CaptureUserState)
* Content Source: [memdocs/configmgr/osd/understand/task-sequence-steps.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/osd/understand/task-sequence-steps.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @gwblok for catching that, it's incorrect. I'll revise today
