### ISSUE TITLE
Command-line Arguments

### ISSUE THREAD

**Issue by amayacitta** [MicrosoftDocs/memdocs#122]
Could you include some info about command line arguments? In testing I've found that the /i /qn options are implied. The /i is pretty obvious due to the way the MSI file is pushed and renamed through BITS but the /qn were not so obvious. I've also found variables for logging such as %TEMP% don't work and kick out an invalid path error. I dont see anything here on this, there are 3rd party articles which have examples but they seem out of date compared to how it works today.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 872bb519-684a-aca1-dae9-280686f0dd37
* Version Independent ID: 500146ba-b836-9df2-af7b-caf8dc50d929
* Content: [Add a Windows line-of-business app to Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/lob-apps-windows#feedback)
* Content Source: [memdocs/intune/apps/lob-apps-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/lob-apps-windows.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Nimra-Abid** [comment]
I am also facing issue in deployment of MSI file with command line parameters. According to some third party documentation Do not include the “msiexec” command or arguments, such as /i or /x, as they are automatically used in intune. I have also tried to deploy without  using these arguments but no success.

**Comment by Erikre** [comment]
@amayacitta and @Nimra-Abid - Thanks for the feedback. We have recently updated the related topic with additional command line details and a link to more details. I hope this helps.
