### ISSUE TITLE
Documentation need update

### ISSUE THREAD

**Issue by zlDev** [MicrosoftDocs/memdocs#1220]
Missing recommendation for the "Select number of previous PIN values to maintain" setting in the Android application protection policy.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d9a11b1-ff48-8c1e-9dbe-c48a7e4dc350
* Version Independent ID: 6bd15450-157a-e2e8-c636-e692c7ff6e81
* Content: [Data protection framework using app protection policies - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-framework)
* Content Source: [memdocs/intune/apps/app-protection-framework.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-protection-framework.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by lenewsad** [comment]
Thanks for your contribution @zlDev, I am working on getting this updated!

**Comment by smithre4** [comment]
doc fix in progress.
