### ISSUE TITLE
LOB app installing automatically

### ISSUE THREAD

**Issue by sunilnm84** [MicrosoftDocs/memdocs#1231]
LOB app gets installed automatically when its updated in Endpoint Manager Admin center.
The app developers who provides the app for us to make it available on Intune, they don't want the app to be updated automatically by Intune. They want to release it from their end so that the app will ask the users to update, so that there wont be any data loss in the app. They want the user to replicate it within the app to fetch the new version.

**Comment by lenewsad** [comment]
Hi @sunilnm84, Thanks for taking the time to provide feedback about your experience with Microsoft Intune! I think our engineering team would find this information useful so please resubmit your feedback through our dedicated feedback channel, [Microsoft Intune Feedback]( https://microsoftintune.uservoice.com/forums/291681-ideas).  Closing this issue b/c there isn't anything actionable for Docs at this time. Thanks again!
