### ISSUE TITLE
Incorrect Link

### ISSUE THREAD

**Issue by zlDev** [MicrosoftDocs/memdocs#1234]
Set the Permission state for each permission. You can choose from Prompt, Auto grant, or Auto deny. For more information about permissions, see [Android Enterprise settings to mark devices as compliant or not compliant using Intune](https://docs.microsoft.com/en-gb/mem/intune/protect/compliance-policy-create-android-for-work).

I don't believe [Android Enterprise settings to mark devices as compliant or not compliant using Intune](https://docs.microsoft.com/en-gb/mem/intune/protect/compliance-policy-create-android-for-work) is the correct link to use in this context, probably meant something else. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e8bafee-0bf4-dda7-c6bf-1172172ea6af
* Version Independent ID: 44a90577-639a-91a3-21de-3fd4de64f562
* Content: [Add app configuration policies for managed Android Enterprise devices - Microsoft Intune](https://docs.microsoft.com/en-gb/mem/intune/apps/app-configuration-policies-use-android)
* Content Source: [memdocs/intune/apps/app-configuration-policies-use-android.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-configuration-policies-use-android.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by lenewsad** [comment]
Hi @zlDev, thank you for your contribution. I agree that the link wasn't helpful and didn't make sense alongside that step--I just removed it. Thanks again!
