### ISSUE TITLE
Update AppleID in Apple Certificates

### ISSUE THREAD

**Issue by jogmeznj** [MicrosoftDocs/memdocs#1235]
Is it possible to change the AppleID on a existing Apple certificate (VPP, Device or Push certificates)?
Is there a document with this information or details about the limitation? Should there be a notice about it?

Thank you for your feedback
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd130267-c54b-41e3-d534-831d4a86bae6
* Version Independent ID: bdfa7eca-a356-3dde-7643-9a759f952007
* Content: [Enroll iOS/iPadOS devices by using ADE - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-ios#renew-an-automated-device-enrollment-token)
* Content Source: [memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
9200603

**Comment by ErikjeMS** [comment]
Repinging PM...

**Comment by lenewsad** [comment]
Hi @jogmeznj,  thank you for reaching out to the Microsoft Intune docs team with your question. We've been unable to review and get an answer for your issue in a timely manner, and we sincerely apologize for the delayed response. We've created an internal work item to investigate your question and update docs if needed. We are closing this issue for now, but feel free to comment here as necessary. #please-close
