### ISSUE TITLE
Please don't use non-common place acronyms

### ISSUE THREAD

**Issue by webash** [MicrosoftDocs/memdocs#124]
`Windows devices that are enrolled using "userless" methods, such as **DEM** and **WCD**`

Please expand these two acronyms, as it is not obvious what they refer to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a9ef909-c4fb-f052-9d2e-c794efc9efd7
* Version Independent ID: 655e8b80-0471-5789-8bf1-20403390c012
* Content: [Remotely administer devices in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/remote-actions/teamviewer-support)
* Content Source: [memdocs/intune/remote-actions/teamviewer-support.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/remote-actions/teamviewer-support.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@webash Thanks! I'll fix it today.
