### ISSUE TITLE
Diagnostic Data Collected from the EEA and Switerland

### ISSUE THREAD

**Issue by ajp999** [MicrosoftDocs/memdocs#1241]
[Enter feedback here]

Should the information note that explains that diagnostic data is not collected from devices located in European countries (EEA and Switzerland) be updated to also include the United Kingdom. The UK is no longer part of the European Economic Area.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae3a0675-959f-840c-bc51-199cee1d71d5
* Version Independent ID: eb5ed4c2-332f-5816-5d1f-7f2958b8e410
* Content: [Desktop Analytics - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/desktop-analytics/overview)
* Content Source: [memdocs/configmgr/desktop-analytics/overview.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/desktop-analytics/overview.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @ajp999 for noting this. I'll make that change soon.
