### ISSUE TITLE
macOS ADE / conditional access configuration

### ISSUE THREAD

**Issue by chrisphiz** [MicrosoftDocs/memdocs#1242]
Can you please add some guidance around the necessary conditional access configuration that will allow macOS Setup Assistant/ADE enrollments into Intune?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0319ece7-6b1f-d737-618c-778d3f196313
* Version Independent ID: 20b5b39e-56e2-d88e-e4b2-22a79b5d3ccb
* Content: [Enroll macOS devices - Apple Business Manager or Apple School Manager](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-macos)
* Content Source: [memdocs/intune/enrollment/device-enrollment-program-enroll-macos.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/device-enrollment-program-enroll-macos.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
9200701

**Comment by ErikjeMS** [comment]
Repinging PM...

**Comment by arnabbiswas** [comment]
@AnyaNovicheva1 is the right PM owner

**Comment by AnyaNovicheva1** [comment]
For automated device enrollment for macOS, if the device was assigned to an enrollment profile with user affinity, the end user must sign in to the Company Portal for Azure AD registration and Conditional Access. Conditional Access policies can be whatever the admin wants to configure, and having ADE enrolled macs does not mean you need specific CA policies. However if you do have a CA policy targeted to an ADE enrolled mac with user affinity, the end user does need to sign into the Company Portal app. This document outlines the various ways to get the CP on a macOS device - https://docs.microsoft.com/en-us/mem/intune/apps/apps-company-portal-macos

**Comment by ErikjeMS** [comment]
Thanks, @AnyaNovicheva1!
@chrisphiz If Anya's response doesn't answer your question, let us know and I'll reopen this issue.
