### ISSUE TITLE
Not seeing the source

### ISSUE THREAD

**Issue by ml58158** [MicrosoftDocs/memdocs#1245]
Where does these settings show as changed in the registry?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee0dbbde-b15e-4adf-b162-1114fddd8846
* Version Independent ID: 78275b5f-4d5b-f318-0cbf-a27ad35dffa0
* Content: [Configure Windows 10 feature updates policy in Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/windows-10-feature-updates)
* Content Source: [memdocs/intune/protect/windows-10-feature-updates.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/windows-10-feature-updates.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@ml58158   Hello Matt, While Windows 10 Feature Updates can be managed by Intune, documentation for the registry details for these Windows Updates settings are outside the scope of Intune documentation. Direct to the relevant registry key, I wasn't able to find this documented by Windows, though I was able to identify the Windows Update CSP that manages this value:   See **Update/TargetReleaseVersion** at https://docs.microsoft.com/ /windows/client-management/mdm/policy-csp-update#update-targetreleaseversion. 

For details about the registry keys or values involved for this Windows Update setting, you'll need to reach out to the Windows Update team, either through a support case or possibly through the Windows Update documentation, similar to this GitHub issue.
