### ISSUE TITLE
Download PDF link is broken

### ISSUE THREAD

**Issue by AbfSailor** [MicrosoftDocs/memdocs#125]
This link in the left column https://docs.microsoft.com/en-us/mem/opbuildpdf/configmgr/core/toc.pdf?branch=live takes you to a 404 page not found error. 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cde5172d-116c-1b4a-25e8-26209d437e83
* Version Independent ID: 4015e361-351e-2f6c-3be4-8868cf6a0973
* Content: [Plan site system roles - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/hierarchy/plan-for-site-system-servers-and-site-system-roles)
* Content Source: [memdocs/configmgr/core/plan-design/hierarchy/plan-for-site-system-servers-and-site-system-roles.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/hierarchy/plan-for-site-system-servers-and-site-system-roles.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @AbfSailor, we just moved this content to a new repo, thanks for catching this, I'm looking into it.

**Comment by aczechowski** [comment]
There's a build failure for the PDFs after moving to the [new repo](https://docs.microsoft.com/mem/configmgr/core/understand/use-docs#consolidation-of-documentation-for-microsoft-endpoint-manager). I'm working to resolve the failure, I hope this will correct itself tomorrow morning (Wednesday, 4/22) by noon Pacific. I'll keep this issue open until I can confirm the PDFs are published.

**Comment by AbfSailor** [comment]
Thank you @aczechowski for the quick response. I hope you're well and cheers from down the road. I'm in Kirkland.

**Comment by aczechowski** [comment]
It's fixed now. I confirmed the PDF is available from this page and others. Closing the issue.

**Comment by AbfSailor** [comment]
Thank you sir!
