### ISSUE TITLE
Nexus Certificate Manager

### ISSUE THREAD

**Issue by nexmar** [MicrosoftDocs/memdocs#1250]
Hello,

I would like to inform about the Intune support in Nexus Certificate Manager as third-party CA software.

[Nexus Group](https://doc.nexusgroup.com/display/PUB/Certificate+Manager+interfaces)

Best regards,
Martin Furuhed
Product Manager
Nexus Group

martin.furuhed@nexusgroup.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cda83a64-56ae-a632-dc81-dfd1a03984c1
* Version Independent ID: b93da48e-4097-4c3a-f6c8-02a5c4e0a616
* Content: [Use third-party certification authorities (CA) with SCEP in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/certificate-authority-add-scep-overview)
* Content Source: [memdocs/intune/protect/certificate-authority-add-scep-overview.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certificate-authority-add-scep-overview.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@nexmar  Thanks!  I've passed your contact information on to our product team who will follow up with you on this.
