### ISSUE TITLE
Configure Azure services page missing reference for "Update Application settings" option to enable Device Token.

### ISSUE THREAD

**Issue by BeatrizMS2** [MicrosoftDocs/memdocs#1252]
Many customers are unaware on how to enable device token on their environment. 
There´s no reference on "how to" on current docs (or not easy to find), as we have details for Secret key renewal process.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 639e477d-6e9d-a7b1-7978-f7d0f0283fc6
* Version Independent ID: 60b40c21-741b-42f8-a3e5-5f5a86811f59
* Content: [Configure Azure services - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/azure-services-wizard#azure-app-properties)
* Content Source: [memdocs/configmgr/core/servers/deploy/configure/azure-services-wizard.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/deploy/configure/azure-services-wizard.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @BeatrizMS2 😄 
We already have an item tracking adding something about that action, #390 
If you have more information about that action in the context of enabling device token, please email me

**Comment by aczechowski** [comment]
Oops, @mestew let me know that you already added this. 😄 Reference MicrosoftDocs/memdocs-pr#3298
