### ISSUE TITLE
add missing info under iOS/iPadOS App protection policy settings

### ISSUE THREAD

**Issue by FadiJo** [MicrosoftDocs/memdocs#1253]
there is some missing details for a features released before couple of months need to be added to the table under this section https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policy-settings-log#iosipados-app-protection-policy-settings  for
 _**Open data into Org documents**_ 
and 
_**Allow users to open data from selected services**_ 

the missing info should be the below:
OpenDataIntoOrgDocumnetBlocked =
1 Block 
0 Allow

OpenDataFromManagedLocations =
0 Nothing selected
1 OneDrive
2 Sharepoint
3 Camera
4 Onedrive&sharepoint
5 Onedrive&camera
6 Sharepoint&camera
7 Onedrive&sharepoint&camera

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68951bae-f5e8-5155-e688-1cee4fd2396a
* Version Independent ID: 29c669da-2640-d398-e203-7cbac91f056e
* Content: [Review app protection policy logs - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policy-settings-log)
* Content Source: [memdocs/intune/apps/app-protection-policy-settings-log.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-protection-policy-settings-log.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by lenewsad** [comment]
Thanks for the contribution @FadiJo. I am working on getting this updated.

**Comment by smithre4** [comment]
Fixed and will go out later this week. Note there were a few mistakes in what was reported above (Camera and OneDrive&SharePoint are swapped).
