### ISSUE TITLE
Windows 10 IoT Core is not included in the list of supported platforms

### ISSUE THREAD

**Issue by buhibu9** [MicrosoftDocs/memdocs#1257]
Intune enrollment method for "Windows 10 IoT Core" is published in a separate document, and several Policy CSPs can be distributed by Intune Custom policy.

However, Windows 10 IoT Core is not included in the list of supported platforms, so please add it.

https://docs.microsoft.com/en-us/windows/iot-core/manage-your-device/intunedeviceenrollment
https://docs.microsoft.com/en-us/windows/client-management/mdm/configuration-service-provider-reference?redirectedfrom=MSDN#iotcoresupport
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f70a020-9214-3316-5419-ee35ba6ff91a
* Version Independent ID: 9cc74430-af54-a2ac-7e4f-5a70b415c66e
* Content: [Operating systems and browsers supported by Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/supported-devices-browsers)
* Content Source: [memdocs/intune/fundamentals/supported-devices-browsers.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/supported-devices-browsers.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
9207425

**Comment by lenewsad** [comment]
Hi @buhibu9, thank you for contacting the Microsoft Intune Docs team and bringing this article to our attention. I confirmed that at this time, Microsoft Intune does not support enrollment for the Windows IoT Core platform.  If that changes in the future, we will add it as a supported platform in [Operating systems and browsers supported by Microsoft Intune](https://docs.microsoft.com/mem/intune/fundamentals/supported-devices-browsers).
