### ISSUE TITLE
v_GS_SYSTEMHEALTHAGENT view

### ISSUE THREAD

**Issue by russrimm** [MicrosoftDocs/memdocs#126]
I'm not finding this view v_GS_SYSTEMHEALTHAGENT, has it been removed from the product?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 931870af-92b6-3bd3-1928-94fe3d0ece9a
* Version Independent ID: bfa95bdb-ed33-d8c3-8ca8-f3ac740abb5d
* Content: [Hardware inventory views - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/develop/core/understand/sqlviews/hardware-inventory-views-configuration-manager?source=docs)
* Content Source: [memdocs/configmgr/develop/core/understand/sqlviews/hardware-inventory-views-configuration-manager.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/develop/core/understand/sqlviews/hardware-inventory-views-configuration-manager.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @russrimm, yes, that's for NAP, removed in 1511. Would make a good contribution to remove that section from this article. 😉

**Comment by aczechowski** [comment]
I put in a change for this issue (as well as a reference in another article). It should publish live later this afternoon.
