### ISSUE TITLE
IIS Request Filtering Registry Value does not exist (SRV2019)

### ISSUE THREAD

**Issue by Martony78** [MicrosoftDocs/memdocs#1264]
My IIS is well configured on my 2019 NDES server, everything seems ok, but there is no such values in the registry, is it still needed?
"Validate this configuration by viewing the following registry key to confirm it has the indicated values:
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\HTTP\Parameters
The following values are set as DWORD entries:
Name: MaxFieldLength, with a decimal value of 65534
Name: MaxRequestBytes, with a decimal value of 65534"
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9107185-e6c7-b178-4e22-819797fe4880
* Version Independent ID: 1153b441-94f0-b471-52a2-3cf556c68581
* Content: [Configure infrastructure to support SCEP certificate profiles with Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/certificates-scep-configure#set-up-ndes)
* Content Source: [memdocs/intune/protect/certificates-scep-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certificates-scep-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@Martony78  Thanks for the question, and per the information provided to me by our product team: Yes, you’ll need to follow the guidance provided in that articles  section and procedure [Configure the NDES service](https://docs.microsoft.com/mem/intune/protect/certificates-scep-configure#configure-the-ndes-service) to configure NEDS and IIS, which will result in the modification of that registry key.  

Step three of that procedure is the explicit configuration of IIS request filtering, which adds to IIS support for the long URLs (queries) that are required to support SCEP.  

Should you run into difficulties or unexpected results while configuring these settings, please contact support for assistance, as we’re unable to investigate or troubleshoot problems through this docs feedback forum. However, should you discover incorrect or confusing information in the article, that I can act on directly.

**Comment by Martony78** [comment]
Hi
I followed the guidance and configured request filtering in the IIS management console and I can see the configuration is OK but there is no such registry values under HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\HTTP\Parameters
Anyway ,it works, but just to warn people don't having these values that it is no bigdeal
