### ISSUE TITLE
Minimum PIN length

### ISSUE THREAD

**Issue by b-col** [MicrosoftDocs/memdocs#1266]
On iOS devices, configuring the "minimum" PIN length is actually just the PIN length; you are unable to set a PIN with **more** or less characters. This appears to be exclusive to iOS as I am able to set a PIN longer than the minimum length set on Android devices.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c81b9a99-a379-a3b6-0dde-8781da62d16a
* Version Independent ID: 33b4409f-9687-feb7-07ab-7d6bc0d8b9f5
* Content: [iOS/iPadOS app protection policy settings - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policy-settings-ios#conditional-launch)
* Content Source: [memdocs/intune/apps/app-protection-policy-settings-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-protection-policy-settings-ios.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@b-col - Thanks for the feedback. I'll pass this along to the product team.
