### ISSUE TITLE
CN vs OU

### ISSUE THREAD

**Issue by dcpopescu** [MicrosoftDocs/memdocs#1268]
For example, enter OU=Mine,DC=Contoso,DC=com. Don't enter quotation marks. To use the well-known computer object container (CN=Computers, DC=Contoso, DC=Com), leave this property blank.

I think it should be OU=Computers and not CN=Computers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06881bc7-a1ce-f3e8-4dcb-e1970d8134cb
* Version Independent ID: 665a4ee8-e658-3910-c535-2ab097a19a23
* Content: [Domain join profile settings for Windows 10 in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/domain-join-configure)
* Content Source: [memdocs/intune/configuration/domain-join-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/domain-join-configure.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@dcpopescu That's good info. Why do you think that? I'm not questioning your input; just trying to understand why. I hope that makes sense.

**Comment by dcpopescu** [comment]
Please disregard, the article it is correct.
I just verified on my server and the Computers folder is actually a CN.

**Comment by MandiOhlinger** [comment]
@dcpopescu Thank you for testing, and confirming.
