### ISSUE TITLE
Software update ring also breaks ESP

### ISSUE THREAD

**Issue by sveinungre** [MicrosoftDocs/memdocs#127]
Please update documentation to state that software update rings also trigger restart and breaks ESP. Confirmed in Microsoft Support ticket 19080113.  Currently only workaround is to ensure the device or user does not have an software update ring assigned during enrollment.....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92ba0166-1d3c-40ca-a2f3-2954dcfe4411
* Version Independent ID: e07d50e2-7a95-868d-5800-ea548c84e884
* Content: [Set up an Enrollment Status Page - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/windows-enrollment-status)
* Content Source: [memdocs/intune/enrollment/windows-enrollment-status.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/windows-enrollment-status.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
(7061878)

**Comment by ErikjeMS** [comment]
@sveinungre From the PM: "No, update rings do not break ESP.  They *do* trigger a computer restart at the end of device ESP, and as a result of any restart the user will need to sign in again as credentials are not preserved across reboots for security reasons."

**Comment by sveinungre** [comment]
Software update rings triggers a restart during ESP and the result is that Autopilot Deployment Profile OOBE supress settings are ignored, for enterprise customers this means that yes it breaks ESP. This is confirmed in Microsoft Support ticket 19080113.

**Comment by ErikjeMS** [comment]
@sveinungre The PM will follow up with support. Thanks!
