### ISSUE TITLE
Common ways to use Microsoft Intune

### ISSUE THREAD

**Issue by pickwick129** [MicrosoftDocs/memdocs#1271]
Re: link to the technical case study on IT Showcase, I wasn't able to find the case study. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad94ab1a-762f-4ea0-c27a-330c09742981
* Version Independent ID: 043e4081-aa4a-0524-38c3-c7f2b2a9bf64
* Content: [Common ways to use Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/common-scenarios#feedback)
* Content Source: [memdocs/intune/fundamentals/common-scenarios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/common-scenarios.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @dougeby
* Microsoft Alias: **dougeby**

**Comment by MandiOhlinger** [comment]
@pickwick129 You're right. I suspect it's referring to [Managing Windows 10 devices with Microsoft Intune](https://www.microsoft.com/itshowcase/managing-windows-10-devices-with-microsoft-intune), or the **Related content** links at [How Microsoft is modernizing device management](https://www.microsoft.com/itshowcase/how-microsoft-is-modernizing-device-management).

If you go to the [IT Showcase Library](https://www.microsoft.com/itshowcase), and search for **Intune**, you see the available topics.

I updated the article to reflect this information. The doc changes should be live later today. Thank you for bringing this to our attention.
