### ISSUE TITLE
Additional link in article for hybrid endpoint whitelisting

### ISSUE THREAD

**Issue by localandremote** [MicrosoftDocs/memdocs#1272]
[Enter feedback here]
Hi Team, for this page of Intune endpoints for whitelisting, can information please be linked to point customers to other whitelisting required for hybrid configurations?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c9c3475-56d4-026b-349f-f9cbc258537c
* Version Independent ID: 9c6476ed-8a47-bcb4-dfbf-25ba305c3b24
* Content: [Network endpoints for Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/intune-endpoints)
* Content Source: [memdocs/intune/fundamentals/intune-endpoints.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/intune-endpoints.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by msbemba** [comment]
@localandremote Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2479

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @localandremote Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
