### ISSUE TITLE
DeploymentFlags property for instances under CacheInfoEx under SoftwareMgmtAgent on Client

### ISSUE THREAD

**Issue by Hammarskjold** [MicrosoftDocs/memdocs#1275]
Is it possible to get some documentation on how the DeploymentFlags property is put together for these instances?

It's taking some time to figure out by hand... :-)

//A

**Comment by aczechowski** [comment]
Hi @Hammarskjold, right now we're not actively investing in the SDK content beyond basic maintenance and occasional new content when requested by engineering. So I'm closing this issue as it's not something we'll realistically get to.
