### ISSUE TITLE
Remediation error if you do not use NetworkIsolation CSP or App protection policy for Edge

### ISSUE THREAD

**Issue by sveinungre** [MicrosoftDocs/memdocs#128]
Please update documentation to state that Microsoft Defender ATP security baseline (or built-in device configuration profile) is not sufficient to enable Application Guard. You also need to configure 1) custom device configuation profile using NetworkIsolation CSP or 2) app protection policy for Edge. If you do not you receive remediation error for settings Download files to host file system, Clipboard behavior, Collect Logs, Clipboard content and Graphics acceleration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10ff4382-415c-4e80-e958-3bd77252fe2d
* Version Independent ID: 398a5b4b-e8bd-1f7d-ae30-38d812daf90d
* Content: [Intune security baselines settings for Microsoft Defender Advanced Threat Protection - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/security-baseline-settings-defender-atp)
* Content Source: [memdocs/intune/protect/security-baseline-settings-defender-atp.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/security-baseline-settings-defender-atp.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@sveinungre Thanks for this feedback, which I’ve shared with our engineering team. They believe this a scenario gap in the ATP Security baseline which they are discussing with our ATP team. We expect this to result in a baseline revision or a content update to cover this, depending on how this shakes out.  

As this is an action now tracked and managed by the engineering team, I’ll be closing this GitHub issue.
