### ISSUE TITLE
Site Token - MP type can't be HTTP

### ISSUE THREAD

**Issue by shazayed** [MicrosoftDocs/memdocs#1281]
on the main table for the client authentication, we can't have MP as HTTP for the site Token, as HTTP MP is not supported for CMG clients.
if you keep the MP as HTTP, you will not have the option to enable CMG on the MP. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 487b0a14-24a7-c5dc-9350-cde232264ea0
* Version Independent ID: 61c19523-86f3-e983-6021-cd3a1267f4be
* Content: [Configure CMG client authentication - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/configure-authentication)
* Content Source: [memdocs/configmgr/core/clients/manage/cmg/configure-authentication.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/cmg/configure-authentication.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @shazayed, that's actually the point of the [token-based authentication](https://docs.microsoft.com/mem/configmgr/core/clients/deploy/deploy-clients-cmg-token) in version 2002 or later. So if it's not working for you, then there's some other issue.

I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://docs.microsoft.com/answers/products/mem). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by aczechowski** [comment]
I was corrected by the feature PM:

> In order for a HTTP MP to support CMG you need to enable “Use Configuration Manager-generated certificates for HTTP site systems” in the site properties.
>
>Until that is enabled, enhanced HTTP will not be used and the MP option to support CMG will be greyed out.

Reopening this issue, I'll need to make some revisions to this article and possibly others.
