### ISSUE TITLE
Clarification about "Create the device configuration profile to onboard Windows devices"

### ISSUE THREAD

**Issue by sebsalvat** [MicrosoftDocs/memdocs#1282]
The information under the subheading "Create the device configuration profile to onboard Windows devices" does not include an example of when you have intune connected to defender. 

It appears to me that in that case, the only two options present under Endpoint Detection and Response are "Sample sharing for all files" and "Expedite telemetry reporting frequency".

The missing storage blob and configuration options cause uncertainty and confusion.

**Comment by Brenduns** [comment]
Article: https://docs.microsoft.com/en-us/mem/intune/protect/advanced-threat-protection-configure

**Comment by Brenduns** [comment]
@sebsalvat  Your right.  While the note before the image declares that it’s is the UI seen when you *have not* created a connection to Defender for Endpoint, that’s not the expected scenario, and not terribly useful. After consulting with the product group, they’ve filed a bug to update the UI. It should not display those options to configure the blobs as the scenario today expects you to have the connection configured between Intune and Defender for Endpoint. 

I’ve submitted a content update to revise the image and docs to reflect the expected scenario.
