### ISSUE TITLE
The steps have been reversed

### ISSUE THREAD

**Issue by robinhobo** [MicrosoftDocs/memdocs#1283]
The steps have been reversed, the steps under "For Android Enterprise" belong to "For Android device administrator" and vice versa.

Regards,

Robin Hobo
Microsoft MVP - Enterprise Mobility

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91c6e4c4-96e2-14c6-8028-a2b947740e73
* Version Independent ID: 94bd0e7c-03c8-151d-6569-5d12985824e6
* Content: [Automatically enroll Android devices using Samsung's Knox Mobile Enrollment - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/android-samsung-knox-mobile-enroll?source=docs)
* Content Source: [memdocs/intune/enrollment/android-samsung-knox-mobile-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/android-samsung-knox-mobile-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by robinhobo** [comment]
See this new blog for the Android Enterprise steps, perhaps it is changed after this doc was realeased : https://www.robinhobo.com/how-to-setup-samsung-knox-mobile-enrollment-with-microsoft-intune/

**Comment by msbemba** [comment]
@robinhobo Thank you for your feedback. I can confirm the steps for Android enterprise and  Android device administrator are correct now. You are right, perhaps this changed after the document was released.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @robinhobo Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
