### ISSUE TITLE
Dynamic group expression syntax is wrong?

### ISSUE THREAD

**Issue by nicholashennellfoley** [MicrosoftDocs/memdocs#1284]
Under Create an Autopilot device group using Intune > Step 2, there seem to be erroneous open brackets ( before the underscores _
This does not match the syntax in [Dynamic membership rules for groups in Azure Active Directory](https://docs.microsoft.com/en-us/azure/active-directory/enterprise-users/groups-dynamic-membership).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97ce79c0-0014-f6f0-95f7-58574bfdefb3
* Version Independent ID: 40b3877e-a094-8d05-c95b-ca842c5ca8ce
* Content: [Enroll devices with Windows Autopilot - Microsoft Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/autopilot/enrollment-autopilot)
* Content Source: [memdocs/autopilot/enrollment-autopilot.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/enrollment-autopilot.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
9352695

**Comment by ErikjeMS** [comment]
@nicholashennellfoley The parenthesis are a coding style or preference. While not technically required, they don't cause an error.
