### ISSUE TITLE
"White Glove" Pre-Provisioning does ONLY work if Region or Keyboard is not preset in Autopilot Profile

### ISSUE THREAD

**Issue by meisterheister** [MicrosoftDocs/memdocs#1285]
### Issue:
We experienced that Windows Autopilot "White Glove" pre-provisioning setup was not working anymore since setting the **Language (Region)** to "operating system default"  (or specified region)  and **Automatically configure keyboard** to "No".
#### Observations:
When booting up the device (previously onboarded to Autopilot) into OOBE (Out-Of-the-Box-Experience) it was showing directly the email address field and the company name on top since the assigned Autopilot profile was successfully downloaded. When pressing the Windows key five times to get to the "additional options dialog" nothing happened. 
When choosing "change account" on the same screen (bottom left) the device reboots and shows the country selection. Now when pressing the Windows key five times I get to the "additional options dialog" and when choosing "Windows Autopilot provisioning" from there I get a red screen reporting "**No AutoPilot profile was found**". No QR-Code is shows nor any error code and the other fields show:

- Organization: No organization found
- Profile: No profile found
- Assigned user: Not assigned
- Elapsed time: NaN

#### Troubleshooting:
The diagnostics that you can download from the red screen  include a "AutopilotDDSZTDFile.json" which contains all the needed information but the Event log included in the diagnostics package ("microsoft-windows-moderndeployment-diagnostics-provider-autopilot.evtx") reports events such as "Autopilot policy [DeploymentProfileName] not found."

### Workaround:
Change the Autopilot Profile settings at least for **Automatically configure keyboard** to "Yes" or **Language (Region)** to "user select" in order to get to the "additional options dialog" right after the first device boot after reset into OOBE. After selecting "Windows Autopilot provisioning" the screen turns blue and shows an QR-Code and the assigned organization.

### Conclusion:
This seems to me like a bug. If you cannot enter the (While Glove) Windows Autopilot provisioning setup when having region set to "operating system default" (or specified region) and automatic keyboard configuration to "No" in the Autopilot Profile settings then why should you be able to enable "Allow White Glove OOBE" in the same place? It should not be available then.
Also when I click "change account" why does Windows Autopilot provisioning not work at all?

In the Docs Article "**[Windows Autopilot for pre-provisioned deployment](https://docs.microsoft.com/mem/autopilot/pre-provision)**" you write the following sentences:

Under "[Preparation](https://docs.microsoft.com/mem/autopilot/pre-provision#preparation)"
> **Note:**
> Select the language mode as user specified in Autopilot profiles to ensure easy access into pre-provisioning mode. 

Under Scenarios > "[Technician Flow](https://docs.microsoft.com/mem/autopilot/pre-provision#technician-flow)"
> - From the first OOBE screen (which could be a language selection or locale selection screen), don't click Next. Instead, press the Windows key five times to view an additional options dialog.

**Please change the article to so that it is clear to everyone that the Autopilot profile that will be assigned to the device is set to at least either automatically keyboard selection to "No" or Language to "user select". Otherwise Autopilot provisioning will not work with White Glove!** 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0f572e0-1bc0-6f14-7f60-989eb67fb7e7
* Version Independent ID: e4ec5b25-d9a6-d260-6cf6-ff4f3eb3ecb8
* Content: [Windows Autopilot for pre-provisioned deployment](https://docs.microsoft.com/en-us/mem/autopilot/pre-provision)
* Content Source: [memdocs/autopilot/pre-provision.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/pre-provision.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by meisterheister** [comment]
Realized that there is another issue open currently explaining that this issue came up since Windows 10 Version 2004 onwards

Duplicate of #1075

**Comment by frankroj** [comment]
Thank you for the feedback @meisterheister. I apologize for the time it took to get back to you regarding this feedback item. Since you filed this feedback item, this issue has been resolved and should work in the latest versions of Windows 10 22H2 and Windows 11 22H2. You shouldn't need to set **Automatically configure keyboard** to **No** or the language to **User select** for it to work. I have personally tested this configuration and can confirm I can hit the Windows key 5 times to start the pre-provision deployment when the device first boots up. If you are finding you are having the problems with older but still supported version of Windows, please let me know.
