### ISSUE TITLE
Note to the unlicensed admin online doc regarding delays for the changes to take effect

### ISSUE THREAD

**Issue by tktracker** [MicrosoftDocs/memdocs#1287]
Could you add a note to the unlicensed admin online doc stating that there can be a delay for up to 48 hours for the change to take effect? I discussed this with Intune engineering team owning the feature and they said the delay can be as much as 48 hours due to several components involved in processing the workflow. Thanks!

**Comment by Brenduns** [comment]
/intune/fundamentals/unlicensed-admins

**Comment by Brenduns** [comment]
@tktracker  Thanks for the information. [The article](https://docs.microsoft.com/en-us/mem/intune/fundamentals/unlicensed-admins) will update later today to reflect the delay period.
