### ISSUE TITLE
Defender Catch-Up Quick Scan conflicting statement

### ISSUE THREAD

**Issue by rex657** [MicrosoftDocs/memdocs#1293]
Hi Team,

Please have a check and kindly provide a clarification for the following question:
>information does conflict
This article states Catchup Quick Scan is enabled by default, and the CSP is Defender/DisableCatchupQuickScan
https://docs.microsoft.com/en-us/mem/intune/protect/antivirus-microsoft-defender-settings-windows#scan
![image](https://user-images.githubusercontent.com/64514282/106697712-45bb0780-661a-11eb-94b2-ccb33cc643e4.png)

But from the Policy CSP, the doc states if the value is not configured, the Catch-up quick scans will be turned off:
https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-defender#defender-disablecatchupquickscan
![image](https://user-images.githubusercontent.com/64514282/106702533-78b5c900-6623-11eb-9a5d-54bd1e71b14a.png)

Seems the information is conflicting, while from the device side, if there is no policy enabled, the key will not be set in path: 
HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender

>Intune doc is conflict with actual behavior:
from the Intune portal in Antivirus policy, the option for "Disable catch-up quick Scan" is saying "Yes" is to enforce the settings:
![image](https://user-images.githubusercontent.com/64514282/106702827-fbd71f00-6623-11eb-9470-61bfc2ff66fa.png)

from the device side, if admin assign policy with "Disable catch-up quick Scan" set to "Yes", the key will be created under Defender reg path:
HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender\Policy Manager   ##key "DisableCatchupQuickScan" will be created and set to 1.

According to the doc and also Intune UI, “Disable catch-up quick Scan" need to be set to "Yes" to enforce the Catchup Quick Scan.

From the local GPO however, if the same policy is set to Enable, the reg key added would be:
![image](https://user-images.githubusercontent.com/64514282/106708646-30e86f00-662e-11eb-9ed4-8da2e37f4cff.png)

Could you please help to confirm the actual behavior for this settings and if needed to update the doc.

Thank you
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b84f6130-b993-bd26-0147-29748c3b7449
* Version Independent ID: 231c5984-ee21-059b-22d4-21b2f009124e
* Content: [Windows 10 Antivirus policy settings for Microsoft Defender Antivirus for Intune](https://docs.microsoft.com/en-us/mem/intune/protect/antivirus-microsoft-defender-settings-windows#scan)
* Content Source: [memdocs/intune/protect/antivirus-microsoft-defender-settings-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/antivirus-microsoft-defender-settings-windows.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@rex657  Thanks for this question. After consulting with our engineering team, the content is accurate. However, the UI text on which it’s based might not be the most straight forward. I believe both the underlying Windows CSP and Setting in Intune invoke double-negative scenarios that make this hard to unravel.

Breaking this all down: 
1.	The Windows CSP reference (https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-defender#defender-disablecatchupquickscan) states:  _If you enable this setting, catch-up scans for scheduled quick scans will be turned off_.  That doc then goes on to define the CSPs supported values: 
•	1 – Disabled (default) 
•	0 – Enabled 

Navigating the CSP description and values: 
•	If you _Disable_ the CSP (a value of 1), where the CSP is named _Disable catch-up quick scan_, you get (due to the double negative of its name + configured action) the result that scans that do run.  
•	If you _Enable_ the CSP (a value of 0), where the CSP is named _Disable catch-up quick scan_, you get what’s advertised by the CSPs name: scans are disabled.   

2.	Now, reading the Intune UI and docs:  
•	**Yes** results in the scan running.   For this value, you’ve confirmed it sets a 1 in the registry, which per the CSP’s own guidance means that we are disabling that CSP. That allows the scans to run. 
•	**No** results in the scan not running. This sets a value of 0 in the device registry, which enables the CSP. That means the CSP is active and does as advertised: Disables the scan.
•	**Not configured** results in the client default.  In this case, 1 is the default per the CSP, which we’ve already seen means that scans will run.  

The double-negatives in the rule names are painful to unravel at times, especially when a setting uses options like Yes or No, which don't necessarily speak clearly to the intent/name of the setting. But, in the end, the docs and the UI describe the behavior you’ll get – so long as you don’t over-think the name of the setting vs the name of the options to manipulate it.  

As to the Group Policy, I can’t comment, I’ve not experience on how its structured nor implements the quick scan.

**Comment by Brenduns** [comment]
@rex657  I have an update. We've confirmed that the Windows CSP for the scan setting received an update to the default behavior. That changed from running to turning off the scan.  The Intune UI notes setting this to Not configured invokes the clients default which is to run the scan.  That is incorrect. We're updating that in content, and the UI will eventually get the fix as well.

**Comment by rex657** [comment]
Hi @Brenduns Thanks for the update. Also please note that for the comment on the configuration behavior, I do not think it is a double-negative situation.

For the option: Disable catch-up quick Scan, the UI and doc states are **(why Not Configure "Disable catch-up quick Scan" will result in disable catch-up for full scans...)**
![image](https://user-images.githubusercontent.com/64514282/107895000-9d3b6a80-6f6c-11eb-8b16-ff091fedb765.png)


- Not configured (default) - The setting is returned to client default, which is to disable catch-up scans for full scans.

- No - The setting is disabled. Device users can't change this setting.

- Yes - Catch-up scans for scheduled quick scans are enforced and the user can't disable them. If a computer is offline for two consecutive scheduled scans, a catch-up scan is started the next time someone signs in to the computer. If there's no scheduled scan configured, there will be no catch-up scan run. Device users can't change this setting.

By deploying the Disable catch-up quick Scan with Yes, the device will receive a settings to Disable the catch-up quick scan, and the doc says this could enforce the feature but the actual behavior indicates this would literally disable Catch-up quick scan.

When Disable catch-up quick Scan is set to No, the device would run the Catch-up quick scan. and doc says it could disable the catch-up quick scan.

So the point is if Admin does not read the doc or review the UI tips, he can configure this without confusion, But if he reviewed these contents, he will then get confused and would not know what to configure to achieve his goal.

**Comment by Brenduns** [comment]
@Paul-Sagnola-RR     Hello and thanks for this feedback.  I don’t think anyone would disagree about the confusion in some of the settings name and labels as found in the Intune UI vs the underlying CSPs. This has been raised with the Intune product group several times for different settings and areas for a few years now, and not all of that feedback is something that has been acted on as of yet. 

However, with the recent efforts invested in the [new settings format and policies]( https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new#new-profile-templates-and-settings-structure-for-endpoint-security-policies) that have begun to be released staring in April,  we don’t expect further efforts to update or revise these existing policies will be done. 

Instead, I recommend reviewing the settings format the new policies provide, and until a migration solution from old to new policy formats are provided, consider manually recreating policies where you can.  at work is underway.

**Comment by Brenduns** [comment]
Hi Pual, looks like I missed that last question about the grid. My bad.

The details in the Defender CSP content are authoritative for how that CSP is implemented.  So I'd have to say yes, that grid is accurate. Even if it's not necessarily clear.  That CSP content tells me when the CSP Named DisableCatchupQuickScan is set to 1 (disabled - which is the default for the CSP on any device that doesn't have this CSP actively configured to 0 - enabled) the device will not perform a quickscan. You must actively manage the setting on the device to set it to Enabled (0) to get the quickscan to run.  The CSP Name and the Options seem to be reversed.  If that's how it operates, then it's a coding issue for Defender and its CSPs. I would personally expect a CSP that is named Disable anything to disable it only when that CSP is enabled (or active). Not the reverse.

If you find any problems with the information in the Defender CSP content, I'd recommend opening a support call with the Defender security team to have that CSP and its content investigated.

For Intune's involvement, the Intune baselines and Endpoint security policies provide a group of settings that toggle the CSPs that are on devices, and its in the Intune UI that we see the sometimes wonky setting names and options that don't clearly line up to the underlying CSP the Intune UI is managing.  Then again, the CSPs can present a bit of a quandary as well - as we see here.   It's the Intune UI that is being fixed via the new Intune policies - by directly leveraging the source  CSP name and options, and not trying to interpret them.

**Comment by Paul-Sagnola-RR** [comment]
Thank you for the reply I really appreciate it.

I checked and my policy is on the old yes/no format, not the new CSP version that uses enable/disable wording. The new format does look more clear. However, when I look closer the tool tip wording inside of Intune must be incorrect for the Quick scan, but is correct for the full scan.

Take a look below and see if you concur.

![image](https://user-images.githubusercontent.com/94648255/168151282-a43a8bd1-13b5-4b26-a28f-222e0315222b.png)

![image](https://user-images.githubusercontent.com/94648255/168151310-d9991c5b-eb73-4cec-af20-4e4ea0673a76.png)

**Comment by Brenduns** [comment]
Good gravy!  Those are not the same. From what I was informed about the release of the new policies, they would/should be the same.

I'm raising this question with the product team (again. But as an issue that's new to this new policy instance).  Normally, or in the future, this being a UI to CSP issue, we'd direct you through support so they can get customer impact directly attributed to a bug (something I can't collect/provide via docs feedback).  But as I've had a conversation with the Intune feature team around this type of mismatch earlier this week - I'll see what I can shake loose about this directly.   If/when I can get anything of use, I'll  update you.
