### ISSUE TITLE
Can you confirm that the "email" that the company never has access to, would be personal email; and that company email provided is in fact protected via InTune?  

### ISSUE THREAD

**Issue by jonathan-waldrop** [MicrosoftDocs/memdocs#1296]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb1f7fe9-6bae-6fc5-eb77-d456e08f8736
* Version Independent ID: b0d12a58-0a77-67dc-7006-49e98589ca7f
* Content: [What info can your company see when you enroll your device?](https://docs.microsoft.com/en-us/mem/intune/user-help/what-info-can-your-company-see-when-you-enroll-your-device-in-intune)
* Content Source: [memdocs/intune/user-help/what-info-can-your-company-see-when-you-enroll-your-device-in-intune.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/user-help/what-info-can-your-company-see-when-you-enroll-your-device-in-intune.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @jonathan-waldrop, thanks for reaching out to the Intune Docs team! I'm working on confirming the answer with our product team. Thanks for your patience.

**Comment by lenewsad** [comment]
Hi @jonathan-waldrop, That's correct, your organization can use Intune to configure and protect the email account you use for work. It does not give them access to view/read your personal and work-related emails.
