### ISSUE TITLE
Are the Intune Azure Logs really still in preview?

### ISSUE THREAD

**Issue by ThomasWeinm** [MicrosoftDocs/memdocs#1297]
"Operational Logs" and "Device Compliance Organizational Logs" still mentioned to be in preview for nearly a year now. Is this still correct? If yes, when can we expect to have them released?

Regards
Thomas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1cee1ad-3f38-5bde-09a3-32742d8d39cd
* Version Independent ID: bf4cf7d8-e162-80ec-98b0-e46b452e44cb
* Content: [Route logs to Azure Monitor using Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/fundamentals/review-logs-using-azure-monitor)
* Content Source: [memdocs/intune/fundamentals/review-logs-using-azure-monitor.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/review-logs-using-azure-monitor.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
https://msazure.visualstudio.com/Intune/_workitems/edit/9352305

**Comment by MandiOhlinger** [comment]
@ThomasWeinm Thank you for asking. We removed the "preview" text. The changes should be live later today.
