### ISSUE TITLE
"The complete guide to WSUS and Configuration Manager SUP maintenance"

### ISSUE THREAD

**Issue by andykn** [MicrosoftDocs/memdocs#1298]
The link in the doc is old, that article is now here;

https://docs.microsoft.com/en-US/troubleshoot/mem/configmgr/wsus-maintenance-guide

Rgds
Andy Knowles
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80d4abf9-0716-e1d4-56d8-928496b41214
* Version Independent ID: 76abfa7a-b4ac-5b24-ecd6-86b3c75a046f
* Content: [Software updates maintenance - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/sum/deploy-use/software-updates-maintenance)
* Content Source: [memdocs/configmgr/sum/deploy-use/software-updates-maintenance.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/sum/deploy-use/software-updates-maintenance.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @andykn for the feedback, we just fixed that link, so it should show properly now.
