### ISSUE TITLE
Android 10 Face Unlock Support

### ISSUE THREAD

**Issue by specterz** [MicrosoftDocs/memdocs#13]
Hi,

Please provide support for Face Unlock Android 10. As we see more and more phones with no fingerprint sensor (e.g. Pixel 4, 4XL), this makes us to enter password each single time.

Thanks,

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d16c28db-1e8e-31fa-6127-3050a2940422
* Version Independent ID: 4cf9a244-1ae5-1637-48f7-3f503d400da6
* Content: [What's new in Microsoft Intune - Azure](https://docs.microsoft.com/en-ca/mem/intune/fundamentals/whats-new#company-portal-updates)
* Content Source: [memdocs/intune/fundamentals/whats-new.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/whats-new.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@specterz Thanks for taking the time to provide feedback on Microsoft Intune! This is an interesting feature idea, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we have dedicated channels for that very purpose. See the [Microsoft Intune Feedback]( https://microsoftintune.uservoice.com/forums/291681-ideas). I'm closing this issue as there's nothing actionable for docs at this time.
