### ISSUE TITLE
Safari Pop-up Blocker

### ISSUE THREAD

**Issue by scottclarke1** [MicrosoftDocs/memdocs#130]
Hey Guys

There is a context in language variance between the documentation on this page and the tool tip within the actual Intune interface itself for the following;

Safari Pop-ups: Block disables the pop-up blocker in the web browser. When set to Not configured (default), Intune doesn't change or update this setting. By default, the OS might allow the pop-up blocker.

Whereas in the tool tip, the "Safari Pop-ups" control says "Block pop-ups in web browser".

Which context is right in this instance? Blocking of pop-ups or the disablement of the pop-up blocker?

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88932dd8-abce-bf23-9624-1df5f60a946d
* Version Independent ID: ab2d932f-e375-2485-a6e5-e02daf7a27c4
* Content: [iOS/iPadOS device settings in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-ios#feedback)
* Content Source: [memdocs/intune/configuration/device-restrictions-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/device-restrictions-ios.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@scottclarke1 Good question. And, sorry for the confusion. The settings, values, and tooltips are all being updated in the next few release cycles. So, it will be more clear.

As for your specific question, the tooltip is correct. This setting blocks all pop-ups in Safari. The description is updated, and changes should be live later today. Thanks!
