### ISSUE TITLE
Windows Autopilot + Windows Hello for Business considerations

### ISSUE THREAD

**Issue by pkothare** [MicrosoftDocs/memdocs#1304]
I am in the process of rolling out Windows Hello for Business (WHfB) as well as Windows Autopilot for our organization. In doing so I want to understand the minimum required infrastructure that will support both of them without incurring too much friction or overhead. For WHfB, there are [2 models](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust) that we are interested in:

- [Hybrid Azure AD Joined Key Trust Deployment](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust)
- [Hybrid Azure AD Joined Certificate Trust Deployment](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust)

For Windows Autopilot, we are interested in [User-driven mode for hybrid Azure Active Directory join with VPN support](https://docs.microsoft.com/en-us/mem/autopilot/user-driven). Within this document I noticed the following statement:

> User certificates aren't supported because they can't be deployed until the user logs in. Also, because they aren't installed until after the user signs in, non-Microsoft UWP VPN plug-ins delivered from the Windows Store aren't supported.

Based on the information above, I'm trying to understand, is the term *user certificate* (under the docs used in Windows Autopilot) synonymous with *key trust* (under WHfB)? If so, is the implication that rolling out *certificate trust deployment* for Windows Hello will also enable support for Windows Autopilot in user driven mode for hybrid AAD?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b57c9838-1004-157d-e0b1-363e770c7246
* Version Independent ID: 4fa6f34f-9438-9748-712c-c949eb22863d
* Content: [Windows Autopilot User-Driven Mode](https://docs.microsoft.com/en-us/mem/autopilot/user-driven)
* Content Source: [memdocs/autopilot/user-driven.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/user-driven.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by frankroj** [comment]
Thanks @pkothare  for taking the time to share this with the Windows documentation team. I apologize for the long delay that it took to reply to this feedback. The question doesn't quite make sense. Autopilot requires a device certificate to establish the VPN tunnel. The certificates provisioned in the Hello container are user certificates. The WHFB cert will be deployed only after a user signs in. In other words, if we are understanding the question correctly, the answer is no.
