### ISSUE TITLE
Fix Microsoft Whiteboard invalid link in MS apps table

### ISSUE THREAD

**Issue by anomaalia** [MicrosoftDocs/memdocs#1306]
Microsoft Whiteboard iOS(link) is linking towards Visio Viewer instead.
![image](https://user-images.githubusercontent.com/37367951/107211545-61ede880-6a0e-11eb-825b-aa0d4c28ddaf.png)

Correct link would be: https://apps.apple.com/us/app/microsoft-whiteboard/id1352499399

Referrect  section: https://docs.microsoft.com/en-us/mem/intune/apps/apps-supported-intune-apps#microsoft-apps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02165898-ec07-86e1-adc5-18f60bec9689
* Version Independent ID: 7b6c64c4-3304-42b0-079a-7dee609c5e4f
* Content: [Supported Microsoft Intune apps](https://docs.microsoft.com/en-us/mem/intune/apps/apps-supported-intune-apps)
* Content Source: [memdocs/intune/apps/apps-supported-intune-apps.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/apps-supported-intune-apps.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@anomaalia - Thanks for the feedback. I'm making this update now.
