### ISSUE TITLE
potentially incorrect sentence order in a paragraph

### ISSUE THREAD

**Issue by zlDev** [MicrosoftDocs/memdocs#1307]
Hello

I think below paragraph needs rephrasing. 

For corporate-owned devices with a work profile, some settings only apply in the work profile. For fully managed and dedicated devices, these settings apply device-wide. **These settings have (work profile-level) in the setting name.**

I find the above statement confusing. 

Does that mean that device-wide setting has (work profile-level) in the setting name? I believe this is incorrect.
Should it say something like this instead:

For corporate-owned devices with a work profile, some settings only apply in the work profile. **These settings have (work profile-level) in the setting name**. For fully managed and dedicated devices, these settings apply device-wide. 

Please clarify.

Regards

-Dimi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 900e72be-d42b-49ba-f304-602df23cbb04
* Version Independent ID: 2ce5c45d-15be-d316-1c57-92bea37358e0
* Content: [Android Enterprise device settings in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-android-for-work)
* Content Source: [memdocs/intune/configuration/device-restrictions-android-for-work.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/device-restrictions-android-for-work.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@zlDev You are right. Thank you. We fixed it. Changes should be live later today.
