### ISSUE TITLE
Per-App VPN doesn't autostart on Android

### ISSUE THREAD

**Issue by svenhallauer** [MicrosoftDocs/memdocs#1308]
The document doesn't clearly state that the per-app VPN does not automatically start on an Android device when the application associated with the per-app VPN is launched.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4538f49d-8c19-9227-0acf-77bef7f8d4a8
* Version Independent ID: 1b1b2c40-1fd8-3909-37ae-05ab0d27efb5
* Content: [Install and configure the Microsoft Tunnel VPN solution for Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/microsoft-tunnel-configure)
* Content Source: [memdocs/intune/protect/microsoft-tunnel-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/microsoft-tunnel-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@svenhallauer   Thanks for this submission. Your correct, and I've submitted a content update that will go out later today.  The Android per-app VPN won't automatically start with the application. It must be started manually by the device user. However, if the VPN is also configured as Always-on, that VPN will connect when the device starts, and will then be available when the app launches.  With Always-on VPNs, while they remain active, only the apps that are configured to use them will do so.
