### ISSUE TITLE
Publishing the Headers and verbs for CMG message as we have in IBCM 

### ISSUE THREAD

**Issue by BeatrizMS2** [MicrosoftDocs/memdocs#1309]
Asking if would be possible to publish under CMG communications the Headers and verbs for the client messages as we have for IBCM. That would be really useful to ensure customer is not messing at network level with them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0894e83-ae5e-960f-169c-cb5ea0e85a10
* Version Independent ID: 2a3ad459-44e9-7fe1-f2b9-a6b8ad58afa9
* Content: [Internet-based client management - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/plan-internet-based-client-management)
* Content Source: [memdocs/configmgr/core/clients/manage/plan-internet-based-client-management.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/plan-internet-based-client-management.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @BeatrizMS2 for the feedback! I checked with the engineering team, and the same HTTP headers and verbs would apply in a CMG scenario. I'm adding a new section to the CMG [Data flow](https://docs.microsoft.com/mem/configmgr/core/clients/manage/cmg/data-flow) article, which should publish later today or early tomorrow.

**Comment by BeatrizMS2** [comment]
Thank you!

Beatriz Moran Serrano
  Support Escalation Engineer
Empowering, Helping, and Advising Customers
Customer Service & Support
+34 (91) 3919641​
***@***.******@***.***>

 ***@***.***D731D9.A831F6F0]
