### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by PJMarcum** [MicrosoftDocs/memdocs#131]
Should this "and select Plan deployments" actually say "and select Deployment Plans"? I don't have "Plan Deployments" in my 2002 console.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93b0864e-3fa3-54c2-a9cc-96cff884cc08
* Version Independent ID: 7a29f204-30d6-7482-47cb-98498899ea3b
* Content: [Set up Desktop Analytics - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/desktop-analytics/set-up#feedback)
* Content Source: [memdocs/configmgr/desktop-analytics/set-up.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/desktop-analytics/set-up.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @PJMarcum, not a typo. It's the button on the overview page when you select the Desktop Analytics Servicing node:
![image](https://user-images.githubusercontent.com/26784733/79911368-101f9780-83d5-11ea-95ab-b9140ffe7d14.png)

**Comment by PJMarcum** [comment]
Thanks Aaron. I was expanding "Desktop Analytics Servicing" and seeing "Deployment Plans" rather than clicking it to see "Plan Deployments". I'm probably the only person who doesn't follow directions well enough to make this mistake. :-)
