### ISSUE TITLE
Domain Join OU Path With Spaces

### ISSUE THREAD

**Issue by benjaminjamesowens** [MicrosoftDocs/memdocs#1313]
Example given is not valid as it has a space in **Level 1**

"OU=Level 1,OU=Level2,DC=contoso,DC=com"

Post should be amended

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f93dd93-e003-36fc-02d6-07166537d914
* Version Independent ID: 1b860d13-bcf5-50da-89f9-ee12ece6edb2
* Content: [Enrollment for hybrid Azure AD-joined devices - Windows Autopilot](https://docs.microsoft.com/en-us/mem/autopilot/windows-autopilot-hybrid)
* Content Source: [memdocs/autopilot/windows-autopilot-hybrid.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/windows-autopilot-hybrid.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
9307765

**Comment by benjaminjamesowens** [comment]
> Thank you for your feedback @benjaminjamesowens. I've gone ahead and removed the spaces from the examples. Thanks again for letting us know about this.

Thanks
