### ISSUE TITLE
Page has nothing going on with "Intune Company Portal"

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/memdocs#1314]
The main heading and page title make reference to enrolling "with Intune Company Portal", but there is nothing else in the sections that involves the Company Portal, not the app, nor the web version.  Why is this, is there something I'm missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc53a657-80d3-fa90-4d6c-4565ad0dd567
* Version Independent ID: 6ffc793f-bfab-4cd8-5cc5-1a13c127d88d
* Content: [Enroll Windows 10 device in Intune Company Portal](https://docs.microsoft.com/en-us/mem/intune/user-help/enroll-windows-10-device)
* Content Source: [memdocs/intune/user-help/enroll-windows-10-device.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/user-help/enroll-windows-10-device.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @JeremyTBradshaw, thank you for your contribution to the Intune docs.  Sorry for the confusion!During setup, some of the on-screen steps (not documented) you'd see are from Company Portal. I agree that the app/website shouldn't be the focus of the article so I updated the doc title and intro to avoid further confusion. Those changes will be live within the next couple of days.

**Comment by JeremyTBradshaw** [comment]
Thanks very much!
