### ISSUE TITLE
Unicast responses to multicast - require or block?

### ISSUE THREAD

**Issue by HanzOhlo** [MicrosoftDocs/memdocs#1315]
For the baseline firewall profile setting "Unicast responses to multicast broadcasts required", the associated CSP is "/DisableUnicastResponsesToMulticastBroadcast."  According to the CSP doc for this, "If it is true, unicast responses to multicast broadcast traffic is blocked."  The baseline firewall setting label seems counterintuitive then.  If enabled, the setting is not "requiring" unicast, but rather "disabling/blocking" it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10ff4382-415c-4e80-e958-3bd77252fe2d
* Version Independent ID: 398a5b4b-e8bd-1f7d-ae30-38d812daf90d
* Content: [Intune security baselines settings for Microsoft Defender for Endpoint - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/security-baseline-settings-defender-atp)
* Content Source: [memdocs/intune/protect/security-baseline-settings-defender-atp.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/security-baseline-settings-defender-atp.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@HanzOhlo   Thanks for your feedback, which I’ve shared with the product team, and which has been shared in the past as well.  

I agree with you that the name reversal between the Intune setting and the source CSP can be counter-intuitive. At least I find it confusing. Especially in the case like this setting where there is no explanatory text provided by Intune in the UI as to how the Intune options are applied to the device. In these instances I try to apply the intent of the option (like Yes, or Enabled, or Not configured) to the name of the setting to understand what it might do. While not always a perfect fit, it usually makes sense. 

We don't have the backstory on this particular settings name reversal, but I suspect this setting (and others which are also reversals of the source CSP name) was an attempt to clarify the intent of the setting, removing what are double-negative scenarois for the setting. Those can occur when the setting or in this case Windows CSP is named as ‘_Disable an action or thing_’ for which you then must choose an option to _disable_ the CSP named _disable..._ should you  want that action or thing to actually happen. 

As I don't' see a question about the docs that we can assist with (other than to confirm your feedback has been shared), I'm going to close this GitHub issue.  But if you do have a question that's unanswered, reply back and I'll do my best to address that.
