### ISSUE TITLE
Select Settings > Windows Encryption.

### ISSUE THREAD

**Issue by PaddyMaddy** [MicrosoftDocs/memdocs#1316]
[Enter feedback here]

The screen is an obsolete screen from the old intune portal...
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54cccf1d-81fd-5331-aee7-59a35b39cb15
* Version Independent ID: 81d14392-fe74-4fd9-047f-7b8292d84f0c
* Content: [Encrypt Windows 10 devices with BitLocker in Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/encrypt-devices)
* Content Source: [memdocs/intune/protect/encrypt-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/encrypt-devices.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@PaddyMaddy  Thanks for calling attention to that. I've submitted an update to bring that screen capture up to date. That should be live later in the day.
