### ISSUE TITLE
Android Enterprise and Android Device Admin Instructions Mislabelled?

### ISSUE THREAD

**Issue by jonnyterex** [MicrosoftDocs/memdocs#1317]
I believe the Android Enterprise and Android Device Admin Instructions are mislabelled, they appear to be the wrong way round, it's very confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91c6e4c4-96e2-14c6-8028-a2b947740e73
* Version Independent ID: 94bd0e7c-03c8-151d-6569-5d12985824e6
* Content: [Automatically enroll Android devices using Samsung's Knox Mobile Enrollment - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/android-samsung-knox-mobile-enroll)
* Content Source: [memdocs/intune/enrollment/android-samsung-knox-mobile-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/android-samsung-knox-mobile-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@jonnyterex Thanks for finding that error! I'll fix it today.
