### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by GenerAhl** [MicrosoftDocs/memdocs#132]
The section on remote management reads "For more information, see Use TeamViewer to remotely administer Intune devices" but the link to https://docs.microsoft.com/en-us/intune/device-profile-android-teamviewer is broken and gives a 404-error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb77e43-2878-baba-6ebf-114b7aa48704
* Version Independent ID: 9320a651-b523-3011-4998-d2424507e554
* Content: [Remote actions with co-management - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/comanage/quickstart-remote-actions)
* Content Source: [memdocs/configmgr/comanage/quickstart-remote-actions.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/comanage/quickstart-remote-actions.md)
* Product: **configuration-manager**
* Technology: **configmgr-comanage**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @GenerAhl for catching that. I'll get it fixed today. Proper link is https://docs.microsoft.com/mem/intune/remote-actions/teamviewer-support
