### ISSUE TITLE
ObjectType is not updated to reflect the latest Current Branch

### ISSUE THREAD

**Issue by Anoni-Mouse** [MicrosoftDocs/memdocs#1320]
[Enter feedback here]

I am querying the property ObjectType from the class SMS_ObjectContainerNode and in my case (ConfigMgr 2002) I see values of 5000, 5001, 6000, 6001 and others that are not documented. Can you please update the article?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 477c92b2-48f9-5199-e1cc-1199dd88f778
* Version Independent ID: 572e19a8-1e80-e8c1-58fb-ac4aa8f72678
* Content: [SMS_ObjectContainerNode Class - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/develop/reference/core/servers/console/sms_objectcontainernode-server-wmi-class)
* Content Source: [memdocs/configmgr/develop/reference/core/servers/console/sms_objectcontainernode-server-wmi-class.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/develop/reference/core/servers/console/sms_objectcontainernode-server-wmi-class.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Anoni-Mouse for sharing the feedback. The ConfigMgr WMI SDK content is an area in which we're not actively investing beyond basic maintenance and some new functionality. I often just close such feedback on these articles, as right now we're not realistically going to be able to resource and prioritize the work. But in this case, thanks to @jpcast88 who made the change while I was out on vacation. 😃 His change will go live later this afternoon.
