### ISSUE TITLE
Instructions are missing

### ISSUE THREAD

**Issue by urbndude** [MicrosoftDocs/memdocs#1321]
This page is supposed to be a "how to" on deploying apps, but there is no how to information here.  It just talks about all the supported configurations on deploying applications.  Some documentation on how to actually push the apps to workstations would be very helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 925b5dc0-9a45-5ac2-7132-80f8cc158d66
* Version Independent ID: ceb01ba2-5a90-1fda-ed25-36887099da71
* Content: [Windows 10 app deployment by using Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-windows-10-app-deploy)
* Content Source: [memdocs/intune/apps/apps-windows-10-app-deploy.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/apps-windows-10-app-deploy.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@urbndude - Thanks for the feedback. I included an additional link near the beginning of the topic to help readers find how to assign an app to a group of end users. This doc update should be publish tomorrow. Thanks
