### ISSUE TITLE
More info required on Android 11 Trusted Root CA

### ISSUE THREAD

**Issue by NickDorak** [MicrosoftDocs/memdocs#1322]
It looks like Android 11 has broken Intune managing internal certificates completely. 
The article explains that this no longer works and says to "Manually provision the device with the trusted root certificate", but does not provide any guidance on how this is to be accomplished. I think that if Intune can no longer automatically manage certificates, more clear instructions need to be provided on how to manually setup. 

https://docs.microsoft.com/en-us/mem/intune/protect/certificates-trusted-root#trusted-certificate-profiles-for-android-device-administrator

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8028845-9342-149b-1fe8-e8bb1d5c1eb4
* Version Independent ID: b6cc3ec5-1eb4-07f4-8789-3be60ef73edd
* Content: [Create trusted certificate profiles in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/certificates-trusted-root)
* Content Source: [memdocs/intune/protect/certificates-trusted-root.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certificates-trusted-root.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@NickDorak Hello Nick,  thanks for this ask.  Today I’ve submitted an article update that should go live later tonight, which adds general guidance to help in manually provisioning the trusted root certificate.  We expect this will help bracket the steps required to distribute and register the certificate on applicable devices.
