### ISSUE TITLE
Contradiction regarding installing apps on unmanaged devices

### ISSUE THREAD

**Issue by jordi-j** [MicrosoftDocs/memdocs#1325]
At the top of the document it says "It is important to note that you can assign an app to a device whether or not the device is managed by Intune". However, the 2nd row of the table afterwards is Assign to devices + Devices not enrolled with Intune = No, which contradicts the phrase quoted.

A better wording would be  "It is important to note that you can **deploy** an app to a device whether or not the device is managed by Intune".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7ad786b-eac9-7979-9509-25e05673b35a
* Version Independent ID: 42d279ce-086f-be9f-821f-53d7100fa838
* Content: [Assign apps to groups in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-deploy)
* Content Source: [memdocs/intune/apps/apps-deploy.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/apps-deploy.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@jordi-j - Thanks for the Feedback. Yes, this makes sense. I'm updating the topic now. Thanks
