### ISSUE TITLE
Snooze durations?

### ISSUE THREAD

**Issue by imasupersadpanda** [MicrosoftDocs/memdocs#1326]
Is there a way to control the snooze durations offered when a deployment-related reboot is pending? 8 hours? 3 hours?

**Comment by Erikre** [comment]
@imasupersadpanda - Thanks for the feedback. Is this issue related to Intune Win32 apps? If so, you can choose to **Allow user to snooze the restart notification**. Select the **snooze duration (minutes)**. The default value is 240 minutes (4 hours). The snooze value can't be more than the reboot grace period. For more information, see [Set Win32 app availability and notifications](https://docs.microsoft.com/mem/intune/apps/apps-win32-app-management#set-win32-app-availability-and-notifications).

**Comment by Erikre** [comment]
If you have additional questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

Please use the above channels if you don't already have a solution.
