### ISSUE TITLE
For 3rd part VPN connection types (e.g. CheckPoint Capsule), do we also need to deploy the app?

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/memdocs#1327]
I have found that when you deploy the VPN profile on its own, while the connection gets created and shows up in Windows 10's Settings app, it doesn't install the app, and so clicking "Connect" will result in "No application found".

I'm wondering - should it be installing automatically as part of the VPN profile, or does the app need to be deployed as well?  It doesn't seem to be a documented requirement on this docs article, [or this other one](https://docs.microsoft.com/en-us/mem/intune/configuration/vpn-settings-configure).  If the app does indeed need to be deployed as well/additional to the VPN profile, I would add that note to both of these pages in a PR (I'm holding off until it's confirmed that it is in fact necessary).

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e16582-5730-9f22-2ced-686fc074d5c0
* Version Independent ID: b334cc28-f6ed-103f-3770-4cddb42e666c
* Content: [Windows 10 VPN settings in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/vpn-settings-windows-10)
* Content Source: [memdocs/intune/configuration/vpn-settings-windows-10.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/vpn-settings-windows-10.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@JeremyTBradshaw Yes - you must install the app. And, this information is documented in [Create VPN profiles to connect to VPN servers in Intune](https://docs.microsoft.com/mem/intune/configuration/vpn-settings-configure). Search for `Before you can use VPN profiles`.

But, if you missed it, then others will to. I've moved that text to the top so it's easier to find. The changes should be live later today. Thank you for questioning.

**Comment by JeremyTBradshaw** [comment]
Thanks @MandiOhlinger .  I just went over to that page, scrolled down and DO in fact see the blue info note box stating this as you mentioned.  Not sure how I missed it, but I do appreciate that you're also making it even harder to miss.  Thanks very much.
