### ISSUE TITLE
Link to data being collected

### ISSUE THREAD

**Issue by svenhallauer** [MicrosoftDocs/memdocs#1328]
It would be super useful to either include a table or a link to another page that has a table that details what additional data is being collected when a device affiliation is changed from personal to corporate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcd313b3-e225-849a-def5-8a32a08a92e9
* Version Independent ID: 917b6190-a8bd-f55d-3e71-f403a395721f
* Content: [Add corporate identifiers to Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/corporate-identifiers-add)
* Content Source: [memdocs/intune/enrollment/corporate-identifiers-add.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/corporate-identifiers-add.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
9340314

**Comment by ErikjeMS** [comment]
@svenhallauer Here is the response from the PM: "We don't have a list of the data collected for personal-owned versus corporate-owned devices. But the Windows documentation should detail the difference between Full, Basic, Enhanced, etc. Privacy modes and what type of info is collected."
I can add your request to our queue of requests, but I can't guarantee when or if it will be added. Thanks!
