### ISSUE TITLE
Tableau Mobile for Intune Google Play link should be add.

### ISSUE THREAD

**Issue by Yogesh-Shede** [MicrosoftDocs/memdocs#1329]
Hi Team,

Please update Partner productivity apps for Tableau Mobile for Intune [Google Play link
![Tableau Mobile for Intune_Android](https://user-images.githubusercontent.com/73707106/107791459-fc855900-6d79-11eb-832f-0931f29c3ce7.jpg)
 (Android)](https://play.google.com/store/apps/details?id=com.Tableau.TableauApp.Intune&hl=en_IN&gl=US)

Link from Google Play Store > https://play.google.com/store/apps/details?id=com.Tableau.TableauApp.Intune&hl=en_IN&gl=US 

Please check attachment for more details.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02165898-ec07-86e1-adc5-18f60bec9689
* Version Independent ID: 7b6c64c4-3304-42b0-079a-7dee609c5e4f
* Content: [Supported Microsoft Intune apps](https://docs.microsoft.com/en-us/mem/intune/apps/apps-supported-intune-apps)
* Content Source: [memdocs/intune/apps/apps-supported-intune-apps.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/apps-supported-intune-apps.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@Yogesh-Shede - Thanks for the feedback. I verified this app should be added. I appreciate the detailed message and image. This docs update should be published later today. Thanks

**Comment by Yogesh-Shede** [comment]
@Erikre Thanks for your support for updating this article.
