### ISSUE TITLE
Multiple certificates?

### ISSUE THREAD

**Issue by scerazy** [MicrosoftDocs/memdocs#133]
It sems that there is only a single certificate that can be added, but that is not mentioned in text

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2320f32-f46c-c4a8-1c22-1a79b44f1075
* Version Independent ID: abd36170-7d28-8708-29d6-45260ef44df5
* Content: [Create certificates profile in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/certificates-configure#feedback)
* Content Source: [memdocs/intune/protect/certificates-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certificates-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@scerazy Thank you for the feedback. When deploying a trusted root certificate, the certificate profile does support only one certificate be included – as the intent is to deploy a root certificate to establish a chain of trust back to specific CA entity. For now, unless there is a compelling reason to call out that the profiles support only one certificate each and not multiple certificates, we’ll leave the article unchanged as its unclear that the addition of that information would lend any clarity to the article. Should we see new information that suggests this type of clarification is necessary, we'll revisit that.
