### ISSUE TITLE
Logic on documentation is swapped for local storage and power policies settings

### ISSUE THREAD

**Issue by hathin** [MicrosoftDocs/memdocs#1330]
The documentation for Local Storage and Power Policies are reversed. Tested this on a device and was set both Local Storage and Power Policies to 'Disabled' I was **not** able to save files locally and I was **not** able to change power settings on the device

**Current**:
Local Storage: With local storage, users can save and view files on the device's hard drive. Your options:
Not configured (default): Intune doesn't change or update this setting.
Enabled: Prevents users from saving and viewing files on the device's hard drive.
Disabled: Allows users to see and save files locally using File Explorer.

Power Policies: Allow or prevent users from changing the power settings. Your options:
Not configured (default): Intune doesn't change or update this setting.
Enabled: Users can't turn off hibernate, can't override all sleep actions (such as closing the lid), and can't change the power settings.
Disabled: Users can hibernate the device, can close the lid to sleep the device, and change the power settings.

**Should be:**
Local Storage: With local storage, users can save and view files on the device's hard drive. Your options:
Not configured (default): Intune doesn't change or update this setting.
Enabled: Allows users to see and save files locally using File Explorer.
Disabled: Prevents users from saving and viewing files on the device's hard drive.

Power Policies: Allow or prevent users from changing the power settings. Your options:
Not configured (default): Intune doesn't change or update this setting.
Enabled: Users can hibernate the device, can close the lid to sleep the device, and change the power settings.
Disabled: Users can't turn off hibernate, can't override all sleep actions (such as closing the lid), and can't change the power settings.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe42a212-bb45-2823-80e7-584df7898e53
* Version Independent ID: 969f46bf-e963-fc1f-22b8-78c18df19098
* Content: [Windows 10 shared device settings - Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/shared-user-device-settings-windows)
* Content Source: [memdocs/intune/configuration/shared-user-device-settings-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/shared-user-device-settings-windows.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@hathin Good catch. Thank you. The changes should be live later today or tomorrow. In the future, it'd be great if you created a pull request when you find doc bugs like this. We appreciate the help.
