### ISSUE TITLE
Self deploying mode in EDU

### ISSUE THREAD

**Issue by jgudmundson-RETSD** [MicrosoftDocs/memdocs#1333]
Hi,
Should "Azure AD joined with Autopilot (Self deploying mode)" be marked as "Commonly used in EDU"?  I would think so with all the shared devices.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0661ead-7e0e-08c0-212e-80f810fe1734
* Version Independent ID: d0ab8fec-c7e7-65f4-e6ff-75f3653ecd4e
* Content: [Intune enrollment method capabilities for Windows devices - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/enrollment-method-capab)
* Content Source: [memdocs/intune/enrollment/enrollment-method-capab.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/enrollment-method-capab.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
9340400

**Comment by ErikjeMS** [comment]
@jgudmundson-RETSD The PM has noted that many schools use 1:1 device usage. Since the table entries are subjective, he suggests that we leave it as is. Thanks!
