### ISSUE TITLE
Can I do a fresh installation of ConfigMgr with sql database in Always-On? or I first need setup in a database without high availability and after move it to the Always-On environment?

### ISSUE THREAD

**Issue by JeissonL** [MicrosoftDocs/memdocs#1334]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49301fc3-9163-d533-1057-f8d994e95bbf
* Version Independent ID: 3c3fbdf1-25ec-3c5f-be4c-46983216d3b5
* Content: [Prepare to use an availability group - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database)
* Content Source: [memdocs/configmgr/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Yes, you can install a new site to an availability group. From [Configure an availability group](https://docs.microsoft.com/mem/configmgr/core/servers/deploy/configure/configure-aoag#bkmk_configure):

> When installing a new site, after you have created and configured the availability group, direct setup to use the FQDN of the availability group listener.
