### ISSUE TITLE
Disabled - If you don't want to use Windows Hello for Business, select this setting. All other settings on the screen are then unavailable.

### ISSUE THREAD

**Issue by Anoni-Mouse** [MicrosoftDocs/memdocs#1335]
[Enter feedback here]

Hello
_Disabled - If you don't want to use Windows Hello for Business, select this setting. All other settings on the screen are then unavailable._

This is incorrect. If I click DISABLED, I get the same options as ENABLED. Please fix this. Here is a screenshot
https://i.postimg.cc/hc0FzNwd/UTV.jpg

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb79dc64-b652-b0e4-90c8-f8789c373dd7
* Version Independent ID: 49ce0336-2eab-e3e1-57c3-e1a84e062ff2
* Content: [Windows Hello for Business settings in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/identity-protection-windows-settings)
* Content Source: [memdocs/intune/protect/identity-protection-windows-settings.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/identity-protection-windows-settings.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@Anoni-Mouse   This feedback was attached to our article on **Identify protection** settings, which use a device configuration profile. Configuring WHfB via device configuration profiles is intended to configure discrete groups of devices and in this context the content is accurate to the UI behavior:  When the _identity protection_ profile setting for **Configure Windows Hello for Business** is set to **Disable**, the various settings for configuring Windows Hello for Business _are_ hidden. There is one additional setting in the Identity protection profile which isn’t hidden. **Use security keys for sign-in** remains visible as its not directly a WHfB setting.

It’s possible you found this Identity Protection settings article while working through Windows Hello for Business for _Enrollment_ which defines WHfB as a tenant-wide setting.  See **Windows 10 device settings to enable Windows Hello for Business in Intune** @ https://docs.microsoft.com/mem/intune/protect/windows-hello.  That article provides guidance on configuring the tenant-wide policy and discusses the different ways Intune can help you configure and manage Windows Hello for business, which also include using different security baselines.

Tenant wide settings for WHfB are distinct from the device configuration profile settings.  For the enrollment scenario (tenant-wide), selecting **Disabled** does result in the settings for WHfB displaying – which is intended.  The description of Disabled for this tenant wide policy is: 
-	**Disabled**. If you don't want to enable Windows Hello for Business during device enrollment, select this option. When disabled, users can't provision Windows Hello for Business. When set to Disabled, you can still configure the subsequent settings for Windows Hello for Business even though this policy won't enable Windows Hello for Business.

Based on the collision of tenant-wide vs the identity protection profile settings, I’ve submitted an update to this articles introduction to clarify its focus on the identity protection profile’s settings, and to help redirect the reader to the tenant-wide details and profile if necessary.  

If you are configuring an Identity Protection profile (and not setting the tenant-wide policy), and the settings are not hidden when you select Disable, please contact Support for investigation.
