### ISSUE TITLE
Applicability Rules' Version number examples not good enough

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/memdocs#1336]
In the **Applicability Rules** section the examples provided for version number are not sufficient.  It should perfectly clear what numbers are accepted, and what aren't.  There should be a link to an official page that shows actual version/build numbers.

The way it is today, you have to go to Wikipedia, AnoopCNair, or PeteVanderWoude to get examples.  It shouldn't be this way, Microsoft should document their own product.  Trial and error for something like this is not fair either, if every customer in the world has to do the same trial and error exercise to figure out what's going to work.

Where Microsoft went through the trouble of adding the OS Version applicability rule to the Intuen/MEM product in the first place, they should also document what the acceptable inputs are.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d8832b0-265d-5c37-9f9d-4adbaa8202de
* Version Independent ID: 48c4745d-166e-01a6-0f29-8bfc2a86d07a
* Content: [Create device profiles in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/device-profile-create)
* Content Source: [memdocs/intune/configuration/device-profile-create.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/device-profile-create.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@JeremyTBradshaw I added a link to [Windows 10 release information](https://docs.microsoft.com/windows/release-health/release-information), which includes more version numbers. The changes should be live later today or tomorrow.

If there's other information you think should be added, it'd be great if you created a pull request with your recommended changes. We review every pull request before it gets published. So we'll make sure your changes are correct.
