### ISSUE TITLE
What has happened when Windows 10 devices enroll and ownership is marked as "Unknown"?

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/memdocs#1337]
There seems to be a missing bit of documentation which describes the behavior for when Intune is unable to determine whether an enrolling Windows 10 device is either corporate-owned or personally-owned.

When users sign-into modern auth aware applications, like MS Office, and they leave the option of "Allow my organization to manage this device", their devices are deemed as Device Ownership = Unknown.  They're not blocked from enrolling even if Personally-owned is Blocked in the effective Device Type restriction.

When this happens, what has occurred within Intune/Endpoint Manager, as it relates to the effectiveness of Enrollment Restrictions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e8c2d91-8808-a504-da13-526b152a5cfe
* Version Independent ID: 037b60a6-d6b5-75ad-1933-39d0f7a69048
* Content: [Set enrollment restrictions in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/enrollment-restrictions-set#default-restrictions)
* Content Source: [memdocs/intune/enrollment/enrollment-restrictions-set.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/enrollment-restrictions-set.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
9352321
