### ISSUE TITLE
Incorrect public property in example command

### ISSUE THREAD

**Issue by PJMarcum** [MicrosoftDocs/memdocs#134]
"SMSSiteCode=ABC" is a msi public property it has to be in all upper case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 875e279b-9029-d1e5-8a6c-0e93ce38ddba
* Version Independent ID: 80bc34d7-3ef7-1c4f-da41-0474b1c5f4a4
* Content: [Co-manage internet-based devices - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/comanage/how-to-prepare-Win10#feedback)
* Content Source: [memdocs/configmgr/comanage/how-to-prepare-Win10.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/comanage/how-to-prepare-Win10.md)
* Product: **configuration-manager**
* Technology: **configmgr-comanage**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @PJMarcum for the feedback.

If you want to make the change yourself, see [How to contribute to docs](https://docs.microsoft.com/mem/configmgr/core/understand/use-docs#bkmk_contribute). 😉

**Comment by mestew** [comment]
Fixing this now. Thanks for reporting this @PJMarcum
