### ISSUE TITLE
Reset ? Which one ?

### ISSUE THREAD

**Issue by sgrienen** [MicrosoftDocs/memdocs#1340]
[Enter feedback here]

What kind of reset does it trigger ? Is that a "wipe" command in Intune ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33c723fe-d989-7e65-d1df-409be5b55f30
* Version Independent ID: f5648275-a803-14f9-5ac0-cc29358163de
* Content: [Reset device from Intune Company Portal for Windows](https://docs.microsoft.com/en-us/mem/intune/user-help/reset-device-company-portal-windows)
* Content Source: [memdocs/intune/user-help/reset-device-company-portal-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/user-help/reset-device-company-portal-windows.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @sgrienen, thanks for reaching out to the Intune docs team! Yes, that's correct. The "Reset" option that device users see restores the phone to its factory default settings; the "Wipe" action that you'd see in Microsoft Intune/Microsoft Endpoint Manager does the same thing.

**Comment by sgrienen** [comment]
Not talking about phones here, but Windows 10 PC, is that the same I guess ?

Thanks !


Le mer. 17 févr. 2021 à 22:22, Laura Newsad <notifications@github.com> a
écrit :

**Comment by lenewsad** [comment]
Hi @sgrienen, pardon me--yes, it's the same for Windows 10 PC! :)
