### ISSUE TITLE
MAM policy can only be applied to Android or iOS client platforms.

### ISSUE THREAD

**Issue by SRE93** [MicrosoftDocs/memdocs#1341]
Is there any ETA on when this will be available for WIP without enrollment to enforce App protection policies for Windows 10?

**Comment by MandiOhlinger** [comment]
@SRE93 Hey Sandro - What article are you referring?

**Comment by MandiOhlinger** [comment]
Closing this GitHub issue. If you add the article you're referring, we can reopen it.
