### ISSUE TITLE
Is this for existing user or new user?

### ISSUE THREAD

**Issue by Croftee** [MicrosoftDocs/memdocs#1343]
Hi team, 

The documentation mentions this is suitable for a new user but it retains previous details such as WIFI. How is this appropriate if for example user A has added their home WIFI credentials and this data is retained when handing the device to user B? I always thought AP Reset was if the existing user was keeping the device and the Wipe function was to be used if giving to a new user.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8411fd84-8a1d-28e6-1535-30143be7ede2
* Version Independent ID: 4e5ecbe1-aa9b-cfa0-7b67-1ac1dcb0c465
* Content: [Windows Autopilot Reset](https://docs.microsoft.com/en-us/mem/autopilot/windows-autopilot-reset)
* Content Source: [memdocs/autopilot/windows-autopilot-reset.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/windows-autopilot-reset.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
The reset scenario is common for a device being reallocated to a new user. However, the new user can easily be utilizing the same WiFi network, such as a corporate WiFi.
