### ISSUE TITLE
Please review the -Citrix flag for Intune App Wrapper Tool for Android

### ISSUE THREAD

**Issue by alexandru-stefan1** [MicrosoftDocs/memdocs#1344]
Please review the -Citrix flag for Intune App Wrapper Tool for Android.

The -Citrix parameter for the Intune App Wrapper Tool for Android does not exist yet, and it cannot be used to wrap apps with the Intune SDK and make use of Citrix mVPN.
The parameter is only available for the Intune App Wrapper Tool for **iOS**, where it works as expected.
Please add this info to the "**On-demand application VPN connections with Citrix mVPN**" section, mentioning that the -citrix flag can be used for Intune App Wrapper Tool for **iOS**, but not for Android at the moment.

This is the result of a support case I have handled where I have tested the -Citrix parameter for Intune App Wrapper Tool for Android and it does not exist in the Powershell command (yet, possibly to be added later by the Product Group).

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 254d2121-2117-2261-e145-7c705b90c170
* Version Independent ID: 449e00c1-f2a0-c1cf-552e-6103dcdfb50c
* Content: [Benefits of Intune App SDK - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk)
* Content Source: [memdocs/intune/developer/app-sdk.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/developer/app-sdk.md)
* Service: **microsoft-intune**
* Sub-service: **developer**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@alexandru-stefan1 - Thanks for the feedback. I'm updating the docs now.
