### ISSUE TITLE
VPN connection types for Microsoft Tunnel Android platform

### ISSUE THREAD

**Issue by Yogesh-Shede** [MicrosoftDocs/memdocs#1347]
[Enter feedback here]
Hi Team,

Please add VPN connection types for Microsoft Tunnel on Android platform. When I tried to create test VPN profile for Android Enterprise I can see Microsoft Tunnel is available. So I think on [portal ](https://docs.microsoft.com/en-us/mem/intune/configuration/vpn-settings-configure) this need to be updated as well.

Also I am able to see Microsoft Tunnel APP is available on Google Play Store 
Link > https://play.google.com/store/apps/details?id=com.microsoft.tunnel&hl=en_IN&gl=US 

**- Android Enterprise personally owned devices with a work profile
- Android Enterprise fully managed and corporate-owned work profile**

Please check attached screenshot as well for your reference.
![VPN connection types for Microsoft Tunnel](https://user-images.githubusercontent.com/73707106/108534171-d7f02a80-72ff-11eb-9efa-ddc7434f8bed.jpg)
![VPN connection types for Microsoft Tunnel MS Doc update](https://user-images.githubusercontent.com/73707106/108534331-0a9a2300-7300-11eb-9252-329e006ec518.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3772dd31-1256-2aad-758a-395c40864a73
* Version Independent ID: 95193c13-5acd-f133-31e4-722a6cbd4929
* Content: [Add VPN settings to devices in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/vpn-settings-configure)
* Content Source: [memdocs/intune/configuration/vpn-settings-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/vpn-settings-configure.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by Yogesh-Shede** [comment]
@MandiOhlinger do you have any update on this ?

**Comment by MandiOhlinger** [comment]
@Yogesh-Shede You are correct. Thank you. The doc changes have been made, and should be live later today.

**Comment by Yogesh-Shede** [comment]
@MandiOhlinger I have checked link today even it is not updated yet showing me as last updated on 02/16/2021

Link: https://docs.microsoft.com/en-us/mem/intune/configuration/vpn-settings-configure
