### ISSUE TITLE
Cannot remove Web clips after management profile deletion

### ISSUE THREAD

**Issue by apmattingly** [MicrosoftDocs/memdocs#1348]
After removing the management profile from a users iOS device the user or admins are not able to remove the web links from the device. The web links do not have icons and in some cases are multiple instances (see attached)
![Service Desk and Tips bookmarks](https://user-images.githubusercontent.com/79331565/108545703-2082f600-72b6-11eb-955c-521c8462ceb5.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804899ad-0aaf-4e3d-32f1-98055153a251
* Version Independent ID: 51b1dd58-5c58-c5eb-8b46-96517a339fc8
* Content: [Add web apps to Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/web-app)
* Content Source: [memdocs/intune/apps/web-app.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/web-app.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@apmattingly - I believe the following information relates to the issue:
_Currently, deployment of Intune web apps to iOS/iPadOS devices is associated with the management profile and cannot be removed manually. You can change the deployment type to Uninstall in Intune, at which point the web app can be removed automatically. However, if you remove the deployment before changing the app assignment intent to Uninstall, the web app will be permanently in place on the device until the device is un-enrolled from Intune._

If you have additional questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

Please use the above channels if you have addition questions.
