### ISSUE TITLE
Seems like screenshots from the iOS version are out of date

### ISSUE THREAD

**Issue by thomyg** [MicrosoftDocs/memdocs#135]
My iPhone just stopped syncing with the company portal. So did my iPad and so did the iPhone of a coworker. I'm not here to talk about the root cause of my current problem, but I tried to follow the steps mentioned here but the screenshots look totally different on my phone plus the described button to fix the issue as quoted below just doesn't exist in my version. I'm using version 4.4.1 of the Intune Company Portal app on iOS. 

"To fix the issue, users must select the Set up button, which is to the right of the Unable to sync notification. The Set up button takes users to the Company Access Setup flow screen, where they can follow the prompts to enroll their device."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa3dc6d8-fc75-fca4-9b64-8761e2ced0d0
* Version Independent ID: 9c63db6b-4de4-9271-37f0-ceca18778b5c
* Content: [Troubleshoot device enrollment - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/troubleshoot-device-enrollment-in-intune#feedback)
* Content Source: [memdocs/intune/enrollment/troubleshoot-device-enrollment-in-intune.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/troubleshoot-device-enrollment-in-intune.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
(7086685)

**Comment by ErikjeMS** [comment]
This doc is in our doc team update queue.
