### ISSUE TITLE
Broken "Unlicensed Admins" Link

### ISSUE THREAD

**Issue by oharveyCloudwell** [MicrosoftDocs/memdocs#1351]
The link for more information about Unlicensed Admins is a dead link pointing to: https://docs.microsoft.com/en-us/unlicensed-admins.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73c7bea7-ccff-ca28-35e4-820494059bf6
* Version Independent ID: 42e6e56f-d5ca-4124-f409-7e34ca609a3a
* Content: [Licenses available for Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/licenses)
* Content Source: [memdocs/intune/fundamentals/licenses.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/licenses.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@oharveyCloudwell Thanks! I'll fix it asap (PR created).
