### ISSUE TITLE
BitlockerMangementHandler.log or BitlockerManagementHandler.log

### ISSUE THREAD

**Issue by Anoni-Mouse** [MicrosoftDocs/memdocs#1352]
[Enter feedback here]
Is the log name really called BitlockerMangementHandler.log or this is a typo? **MangeMent**?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d362145-5048-abf3-fad0-1b6c25f76447
* Version Independent ID: 988e83fa-54da-9bf6-ba19-98006f0043a2
* Content: [Deploy BitLocker management - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/protect/deploy-use/bitlocker/deploy-management-agent)
* Content Source: [memdocs/configmgr/protect/deploy-use/bitlocker/deploy-management-agent.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/protect/deploy-use/bitlocker/deploy-management-agent.md)
* Product: **configuration-manager**
* Technology: **configmgr-protect**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Anoni-Mouse for catching that. It's a typo. I confirmed against the client logs directory on my device. I'll update that now (but won't publish until Monday morning)
