### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by cuatrix-bensonlee** [MicrosoftDocs/memdocs#1353]
The link for unlicensed admins point to a 404 page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73c7bea7-ccff-ca28-35e4-820494059bf6
* Version Independent ID: 42e6e56f-d5ca-4124-f409-7e34ca609a3a
* Content: [Licenses available for Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/licenses)
* Content Source: [memdocs/intune/fundamentals/licenses.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/licenses.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@cuatrix-bensonlee Thanks! I'll fix it asap (created PR).
