### ISSUE TITLE
Wrong MDM-Agent URL for Android Enterprise and Device Admin

### ISSUE THREAD

**Issue by TechTrooper** [MicrosoftDocs/memdocs#1355]
Hello,

Someone has recently mixed up the MDM-agent URL's on this page. Please "do the needful" to correct errors.

**Android Enterprise** MDM Agent APK is supposed to be 
`https://aka.ms/intune_kme_deviceowner`

**Android device administrator** MDM Agent APK is supposed to be 
`https://aka.ms/intune_kme`

My colleague almost choked on his coffee after seeing this and thinking we had it incorrectly configured, when in fact the URL's are now reversed in docs.
![image](https://user-images.githubusercontent.com/3955313/108833441-7ff24600-75d5-11eb-802e-2133e18e5a75.png)
![image](https://user-images.githubusercontent.com/3955313/108833517-9a2c2400-75d5-11eb-817d-d8a820c2bb82.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91c6e4c4-96e2-14c6-8028-a2b947740e73
* Version Independent ID: 94bd0e7c-03c8-151d-6569-5d12985824e6
* Content: [Automatically enroll Android devices using Samsung's Knox Mobile Enrollment - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/android-samsung-knox-mobile-enroll)
* Content Source: [memdocs/intune/enrollment/android-samsung-knox-mobile-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/android-samsung-knox-mobile-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@TechTrooper Thanks! I'll fix it asap! (PR created)

**Comment by TechTrooper** [comment]
Additional note: JSON is also incorrect and reversed for both scenarios. 
Might be easiest to restore both tables to last known good version.
