### ISSUE TITLE
Issues #1677 & #1970 do not appear to have been merged yet

### ISSUE THREAD

**Issue by gary-cassidy** [MicrosoftDocs/memdocs#1356]
[Issue #1677](https://github.com/MicrosoftDocs/SCCMdocs/issues/1677) & [PR #1970](https://github.com/MicrosoftDocs/SCCMdocs/pull/1970) do not appear to have been merged yet. Can this be merged into the main document as having this official will save many hours of content transfer between WAN linked sites.

Suggested text from #1677: 
Starting in version 1802, this feature lets you reassign a distribution point to another site without redistributing the content. The target and destination sites can be either a primary or secondary site.

New content: 
This feature lets you reassign a distribution point to another site without redistributing the content. The target and destination sites can be either a primary or secondary site.

Sorry, I don't know how to use GitHub properly.

(admin edit: adding links to original items in sccmdocs repo)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47242ed6-ef2e-f497-6f04-61a790b9935b
* Version Independent ID: c1180f2a-0caa-1295-7b22-bc7897c56d4b
* Content: [Manage distribution points - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/install-and-configure-distribution-points)
* Content Source: [memdocs/configmgr/core/servers/deploy/configure/install-and-configure-distribution-points.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/deploy/configure/install-and-configure-distribution-points.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @gary-cassidy for the feedback. I can see the [commit](https://github.com/MicrosoftDocs/memdocs/commit/dda5a40ae06e9cb0fd8de80108b0224e2c5cdd55) in our current repo, but it doesn't show in the file history. I can't explain this. 🤔 (Which makes me worry about what else might be missing...)

So I'll just add it back now. The change should publish live on Monday morning.
