### ISSUE TITLE
Do iOS users need to install Microsoft Authenticator?

### ISSUE THREAD

**Issue by rcmpgi** [MicrosoftDocs/memdocs#1357]
According to this they do: https://docs.microsoft.com/en-us/mem/intune/protect/app-based-conditional-access-intune#how-app-based-conditional-access-works

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 722586de-b648-851d-307b-7891b2adc2dd
* Version Independent ID: 2084fe9a-5ad0-ff34-ab66-60214f03a9f0
* Content: [iOS/iPadOS apps with app protection policies](https://docs.microsoft.com/en-us/mem/intune/fundamentals/end-user-mam-apps-ios)
* Content Source: [memdocs/intune/fundamentals/end-user-mam-apps-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/end-user-mam-apps-ios.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@rcmpgi Thank you for your feedback.  We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2491

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @rcmpgi Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
