### ISSUE TITLE
Multiple Managed Identities

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/memdocs#136]
Please add details on support for multiple work accounts within managed apps.  What scenarios are support, what is blocked, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3929b5a0-f852-ce35-4ecd-72d5b9b4a948
* Version Independent ID: 33b804a6-5bf9-75e6-13e0-f2a35e07ef8f
* Content: [Frequently asked questions about MAM and app protection](https://docs.microsoft.com/en-us/mem/intune/apps/mam-faq#feedback)
* Content Source: [memdocs/intune/apps/mam-faq.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/mam-faq.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@danmyhre - Thanks for the feedback. We do have the following topics related to multi-identity:
- [App protection policies overview](https://docs.microsoft.com/mem/intune/apps/app-protection-policy#multi-identity)
- [App protection features](https://docs.microsoft.com/mem/intune/apps/mam-faq#app-protection-features)

Additionally, multi-identity is mentioned in our [iOS and Android SDK docs](https://docs.microsoft.com/mem/intune/developer/app-sdk#support-multi-identity).

**Comment by Erikre** [comment]
@danmyhre - Also, if you have additional questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

This question is in our documentation feedback channel and it may be best to handle this question as a support request. For this reason, I'm closing this issue. Please use the above channels if you don't already have a solution.

**Comment by danmyhre** [comment]
To clarify, I am referring to needing documentation on support for multiple work accounts, not a combination of 1 work account and 1 personal account.
