### ISSUE TITLE
The UI and steps seem out of sync with the MEM console

### ISSUE THREAD

**Issue by svenhallauer** [MicrosoftDocs/memdocs#1360]
Some of the steps and screen shots are out of sync with the present MEM experience.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37f4d965-ae4c-c1d4-3318-4c4827324555
* Version Independent ID: 5e33c778-0522-da5b-e8c8-bfac4784ba84
* Content: [Use role-based access control (RBAC) and scope tags for distributed IT in Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/scope-tags)
* Content Source: [memdocs/intune/fundamentals/scope-tags.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/scope-tags.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@svenhallauer Thanks! I'll put this in our queue to review and update.

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @svenhallauer Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
