### ISSUE TITLE
Link to whitepaper doesn't work properly 

### ISSUE THREAD

**Issue by cameronkcox** [MicrosoftDocs/memdocs#1361]
[Enter feedback here]
The link to the Whitepaper is dead, it only goes to the new replacement for technet but doesn't bring up the whitepaper directly. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71c362cc-3c61-a76f-63e9-0959247b1f47
* Version Independent ID: e5bfb6ea-af69-cf8b-85ce-a5b9bddc8ddd
* Content: [Recommended hardware - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/configs/recommended-hardware)
* Content Source: [memdocs/configmgr/core/plan-design/configs/recommended-hardware.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/configs/recommended-hardware.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @cameronkcox for filing this issue. Anoop filed one in our old repo (MicrosoftDocs/SCCMdocs#2337), and I put in a fix for it.

**Comment by aczechowski** [comment]
Fixed as of Monday
