### ISSUE TITLE
CMGCP - Service or Deployment Name

### ISSUE THREAD

**Issue by CCWT** [MicrosoftDocs/memdocs#1364]
Hello,

in the box Tipp there's stated that the CMG connection point communicates with the service name

```
CMG service name: The common name (CN) of the CMG server authentication certificate. Clients and the CMG connection point site system role communicate with this service name. For example, GraniteFalls.contoso.com or GraniteFalls.cloudapp.net.
```

Under CMG connection point is written that the connection point need access to the deployment name.

```
The CMG connection point needs access to the following service endpoints:

Deployment name (for CMG or CDP):
    <name>.cloudapp.net (Azure public cloud)
    <name>.usgovcloudapp.net (Azure US Government cloud)
```

Does the CMGCP use the service or deployment name?

(admin edit: add article metadata for proper linking)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a9e88a5-bc7d-4982-4564-ceea80bde0e7
* Version Independent ID: 817824fe-5b44-ebeb-75c4-9eeb2dfa13ce
* Content: [Internet access requirements - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/network/internet-endpoints#cloud-services)
* Content Source: [memdocs/configmgr/core/plan-design/network/internet-endpoints.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/network/internet-endpoints.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @CCWT for the feedback and catching that discrepancy. Let me check...

**Comment by aczechowski** [comment]
I confirmed with engineering, it's just the service name. I'll revise the doc
