### ISSUE TITLE
Were already at iOS 14, iOS 11 was released 4 years ago.

### ISSUE THREAD

**Issue by TrustClever** [MicrosoftDocs/memdocs#1366]
"On your device, go to Settings and find your connected accounts. On an iOS 11+ device, for example, you'd select Password & Accounts."

There is no "Password & Accounts" in iOS 14, please adjust the documentation please.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24173ba8-09e1-5e94-0e1e-231d2cd025db
* Version Independent ID: 346a015d-b720-e5fc-bdaa-9fd3134dd91a
* Content: [Existing work email account was found](https://docs.microsoft.com/en-us/mem/intune/user-help/existing-company-email-account-found)
* Content Source: [memdocs/intune/user-help/existing-company-email-account-found.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/user-help/existing-company-email-account-found.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Thank you for your contribution @TrustClever. I just updated the article and changes will be live by 3/31/2021.
