### ISSUE TITLE
Starting in Configuration Manager version 2020

### ISSUE THREAD

**Issue by rdoloto** [MicrosoftDocs/memdocs#1367]
[Enter feedback here]
Should that say Starting in Configuration Manager version 2010? not Starting in Configuration Manager version 2020

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 240ffd09-b912-426a-39fe-4b80d67aa021
* Version Independent ID: c3cb3aad-b115-6fa8-2ba2-45b8ddaf4f28
* Content: [Configure Wake on LAN - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/deploy/configure-wake-on-lan)
* Content Source: [memdocs/configmgr/core/clients/deploy/configure-wake-on-lan.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/deploy/configure-wake-on-lan.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @rdoloto 😄, thanks for catching that! Yep, just a typo. I'll fix it to "2010" right now. The change will go live on Monday morning.
