### ISSUE TITLE
Supported OS

### ISSUE THREAD

**Issue by account9** [MicrosoftDocs/memdocs#1371]
Is Windows 10 Business supported? Its not on the list

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee0dbbde-b15e-4adf-b162-1114fddd8846
* Version Independent ID: 78275b5f-4d5b-f318-0cbf-a27ad35dffa0
* Content: [Configure Windows 10 feature updates policy in Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/windows-10-feature-updates)
* Content Source: [memdocs/intune/protect/windows-10-feature-updates.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/windows-10-feature-updates.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@account9   
Thanks for this question.   _Windows 10 Business_ isn’t a distinct Windows SKU (or supported Operating System version) and instead from what I can discover [represents a set of cloud services and device management capabilities](https://docs.microsoft.com/microsoft-365/business/set-up-windows-devices?view=o365-worldwide) that compliment Windows 10 operating systems (like Windows 10 Pro).  To confirm if your devices are supported for Feature Updates policy (the focus of this article), you’ll need to review their actual installed Windows SKU. This list is based on the Windows 10 SKUs that are supported by Intune that support the [Feature Updates feature](https://docs.microsoft.com/windows/deployment/update/get-started-updates-channels-tools#types-of-updates) from Windows Update. 

For a larger list of what operating systems are supported by Intune, in general, see [Supported configurations](https://docs.microsoft.com/mem/intune/fundamentals/supported-devices-browsers).
