### ISSUE TITLE
Defender for Endpoint Connector Prerequisites confusing

### ISSUE THREAD

**Issue by v-rechau** [MicrosoftDocs/memdocs#1372]
The way the docs list the requirements is slightly confusing as it hint at multiple options for licensed tenants such as:
- Having EMS E3 and Windows E5
- OR having Microsoft 365 Business Premium

The later of which does not have Microsoft Defender ATP subscription (Which comes with Windows E5 or Microsoft 365 E5).

I understand that the overall point is to say that the requirements are a Microsoft Defender ATP license and an Intune license, which should be clearly stated such as Microsoft 365 Business premium and EMS E3 do not provide an ATP subscription as listed here: https://docs.microsoft.com/en-us/microsoft-365/security/mtp/prerequisites?view=o365-worldwide

> To use Microsoft Defender for Endpoint with Intune, be sure you have the following configured, and ready for use:
> 
> A Microsoft Defender ATP subscription, which provides you access to the Microsoft Defender Security Center (ATP portal)
> Licensed tenant for Enterprise Mobility + Security E3 and Windows E5 (or Microsoft 365 Business Premium)
> Microsoft Intune environment, with Intune managed, running one of the following:

Having a clear outline of which licenses provides the Defender ATP subscription and which licenses provide the Intune subscription should reduce confusion instead of just listing licenses that provides Intune.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d129246-93fe-04ec-0e49-8e9ac1c910a8
* Version Independent ID: 66d3e475-e2b9-1974-f04a-2ae8b31f96bd
* Content: [Use Microsoft Defender for Endpoint in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/advanced-threat-protection?WT.mc_id=Portal-Microsoft_Intune_DeviceSettings)
* Content Source: [memdocs/intune/protect/advanced-threat-protection.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/advanced-threat-protection.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@v-rechau   Thanks for your feedback on the content. I agree that this should be easier to navigate.  To that end, I've submitted an edit that should go live later today. The updated prerequisites will express the two products more clearly, with some common licensing options for each (including some options that overlap like Microsoft 365 E5 which includes licenses for both Defender for Endpoint and for Intune). These aren't intended to be comprehensive lists, but should help. The update will also include links to content that is more authoritative on the current methods or options for licensing of each product.
