### ISSUE TITLE
Application Management > Block app installations with elevated privileges :  Badly worded

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/memdocs#1373]
Hello,

How can I suggest to Microsoft to re-word this setting, not only here on Docs, but also in the product itself?

> **Block app installations with elevated privileges**
> This policy setting directs Windows Installer to use elevated permissions when it installs any program on the system. If you enable this policy setting, privileges are extended to all programs. This enables users to install programs that require access to directories that the user might not have permission to view or change, including directories on highly restricted computers. Default: Not configured.
> [Learn more](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-applicationmanagement#applicationmanagement-msialwaysinstallwithelevatedprivileges)

The name of the setting is worded so that it sounds like, if enabled, it should BLOCK the user from installing programs with these elevated permissions.

The associated CSP policy is [**ApplicationManagement/MSIAlwaysInstallWithElevatedPrivileges**](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-applicationmanagement#applicationmanagement-msialwaysinstallwithelevatedprivileges), which clearly states the exact opposite behavior:

> If you enable this policy setting, privileges are extended to all programs. These privileges are usually reserved for programs that have been assigned to the user (offered on the desktop), assigned to the computer (installed automatically), or made available in Add or Remove Programs in Control Panel. This profile setting lets users install programs that require access to directories that the user might not have permission to view or change, including directories on highly restricted computers.
> 
> If you disable or do not configure this policy setting, the system applies the current user's permissions when it installs programs that a system administrator does not distribute or offer.

What I'm suggesting is to rename the setting from **_Block app installations_ with elevated privileges** to **_Always install_ with elevated privileges**.  It just doesn't make any sense to be named what it is named today.  My understanding is that this setting would never be enabled by default, and so we don't need to worry about blocking it.  The way the setting is described, is exactly how the CSP policy is described, where we enable this setting to **enable the feature** (of always installing with elevated priviliges).  We would **Not Configure** it to **block** the feature (by leaving it dormant due to being unconfigured).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f0f4d5d-fdd1-22e7-6372-9916b199209f
* Version Independent ID: caeb9f8b-30ad-7f02-4740-56522b2f9b1b
* Content: [Intune security baselines settings for Windows 10 MDM - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/security-baseline-settings-mdm-all?pivots=mdm-december-2020)
* Content Source: [memdocs/intune/protect/security-baseline-settings-mdm-all.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/security-baseline-settings-mdm-all.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@JeremyTBradshaw   Thanks for this feedback Jeremy, I’ve passed this on directly to the PM for this area. This would not be the first time that similar feedback has been provided to the product team. However, to get more direct traction and perhaps satisfaction, I recommend using the [Intune User Voice](https://www.bing.com/search?q=Intune+user+voice&cvid=5d2e85cbb244480d86b8a70e2103eba0&pglt=163&FORM=ANNAB1&PC=U531) channel to submit this request. 

User Voice submissions are reviewed by our engineering team and can be up-voted by other users to help bubble up issues of most concern or interest to the larger community.  The product group also provides feedback on those submissions and actions that might be taken or underway to resolve them.

**Comment by JeremyTBradshaw** [comment]
Thanks @Brenduns .  I'll see about the User Voice suggestion.  My big fear is that it won't be popular and will get no votes or traction.  But I totally understand the advice and will think about it.
