### ISSUE TITLE
Control Panel and Settings > Gaming -  CSP Unclear

### ISSUE THREAD

**Issue by PsychoData** [MicrosoftDocs/memdocs#1379]
Blocking settings through **Control Panel and Settings** > **Gaming** blocks Focus assist. I submitted feedback on that [here](https://aka.ms/AAbclpq) but the documentation doesn't seem to reference what CSP this ties to (Though it links to "settings" csp above it, I am not sure if that is a different thing?) 

What CSP Does this setting tie to? 
![image](https://user-images.githubusercontent.com/3719116/109538357-f982ac00-7a8d-11eb-931f-2d342575d3f8.png)

![image](https://user-images.githubusercontent.com/3719116/109538084-ac9ed580-7a8d-11eb-8a1d-d56bbd7d2648.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7874ff8b-727f-b013-27f8-fd714ebb53a5
* Version Independent ID: 05674b42-613e-d54d-2895-1f2db41b613a
* Content: [Device restriction settings for Windows 10 in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-windows-10#control-panel-and-settings&)
* Content Source: [memdocs/intune/configuration/device-restrictions-windows-10.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/device-restrictions-windows-10.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@PsychoData The **Gaming** setting uses the [Settings/PageVisibilityList CSP](https://docs.microsoft.com/windows/client-management/mdm/policy-csp-settings#settings-pagevisibilitylist). I updated the description to include that link. Hopefully the doc changes will be live this week.

**Comment by PsychoData** [comment]
Thank you very much!
