### ISSUE TITLE
Clarity around dependency on Microsoft Defender for Endpoint (p.k.a. Microsoft Defender ATP)

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/memdocs#1380]
Can you please clarify if Antivirus policies truly require a Microsoft Defender for Endpoint subscription?  I'm referring to this sentence:

> To use Antivirus policy, integrate Intune with Microsoft Defender for Endpoint as a Mobile Threat Defense solution.

It seems like this policy type is available for all customers, just waiting to be consumed, and appears to work even without Microsoft Defender for Endpoint.  However, if that is not supported until a proper subscription for MD for Endpoint is owned, is it prohibited from use?  Is the proper alternative to instead use ~the "Endpoint Protection" Device Configuration Profile type~ **Device Restriction** Device Configuration Profile and configure the **Microsoft Defender Antivirus** settings?

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8be30a8-9667-8c23-d70f-43e97a2385ab
* Version Independent ID: 2463e335-26cf-f26d-4883-36de3d558109
* Content: [Manage antivirus settings with endpoint security policies in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/endpoint-security-antivirus-policy)
* Content Source: [memdocs/intune/protect/endpoint-security-antivirus-policy.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/endpoint-security-antivirus-policy.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
Hello Jeremy, I thought this had been answered at the time we updated our introductory article for the ‘protect’ area of content for Intune, so this is a bit late, but I hope useful. 

Generally, the profiles you can configure as part of Antivirus polices do have a requirement for Microsoft Defender for Endpoint though there isn’t any prohibition to their use. Just very limited value until you have Microsoft Defender for Endpoint. If you drill into the policies and review the underlying CSP’s, you’ll see that they focus and connect directly to Microsoft Defender for Endpoint details so without that product on a device, the profiles won’t have anything to manage.

However, there is on exception: The **Windows Security experience** profile. This profile doesn’t require Microsoft Defender for Endpoint as it manages the Windows Security app on Windows 10 devices, which is used by a number of Windows security features to provide notifications about the health and security of the machine. These include notifications about firewalls, antivirus products, Windows Defender SmartScreen, and others – many of which are independent of Microsoft Defender for Endpoint.

Without Microsoft Defender for Endpoint, I would suggest focusing on using the Endpoint Protection and Device Restriction profiles from Device configuration.

**Comment by JeremyTBradshaw** [comment]
@Brenduns thanks very much for the clear explanation and guidance.
