### ISSUE TITLE
You have a reporting services point item 1

### ISSUE THREAD

**Issue by gayatria99** [MicrosoftDocs/memdocs#1382]
following 
1. In **Reporting Server Configuration Manager**, back up the Encryption Keys. For more information, see SSRS Encryption Keys - Back Up and Restore Encryption Keys.

to be replaced with
1. In **Reporting Services Configuration Manager**, back up the Encryption Keys. For more information, see SSRS Encryption Keys - Back Up and Restore Encryption Keys.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb13fff2-41ef-fa3d-4685-7b5b17c6b2a7
* Version Independent ID: 7e541e95-40de-b779-dd3e-b03f5fb5b911
* Content: [Integrate with Power BI Report Server - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/manage/powerbi-report-server)
* Content Source: [memdocs/configmgr/core/servers/manage/powerbi-report-server.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/manage/powerbi-report-server.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @gayatria99 for catching that. I'll revise now, it will publish live Monday morning
