### ISSUE TITLE
Question about "Use an authorization type that Azure Active Directory supports in OOBE."

### ISSUE THREAD

**Issue by JanuszGal** [MicrosoftDocs/memdocs#1383]
What are the supported authorization types for AAD in OOBE? Is this listed on another Docs page?

For a federated/ADFS environment, I see that certificates/smartcards are not a supported authorization type, but that's the only information I have found: https://docs.microsoft.com/en-us/azure/active-directory/devices/hybrid-azuread-join-plan#federated-environment  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f93dd93-e003-36fc-02d6-07166537d914
* Version Independent ID: 1b860d13-bcf5-50da-89f9-ee12ece6edb2
* Content: [Enrollment for hybrid Azure AD-joined devices - Windows Autopilot](https://docs.microsoft.com/en-us/mem/autopilot/windows-autopilot-hybrid)
* Content Source: [memdocs/autopilot/windows-autopilot-hybrid.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/windows-autopilot-hybrid.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
9439355

**Comment by frankroj** [comment]
Thank you for the feedback @JanuszGal . I apologize for the long time it took to respond back to this feedback item. This is more of feedback for the AAD docs than the Autopilot docs. If you could please find the appropriate place in the AAD docs for your questions and file your feedback there, they may be able to better answer your questions.
