### ISSUE TITLE
ESP and Supercedence

### ISSUE THREAD

**Issue by ryandorman** [MicrosoftDocs/memdocs#1389]
This section is unclear.  What is the behavior of an application that has a supersedence relationship if it IS targeted in an ESP.  For example does this mean that the original ("A") application is installed during ESP and then the relationships are considered after the user is logged in or does the supersedence NEVER trigger if an app is installed at ESP?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95d2a103-e681-fa04-d3ff-3bffd1e41ca0
* Version Independent ID: 865c635a-2ee7-9c87-7a32-61464e5255ff
* Content: [Add Win32 app supersedence - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-win32-supersedence)
* Content Source: [memdocs/intune/apps/apps-win32-supersedence.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/apps-win32-supersedence.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@ryandorman - Thanks for the feedback. After discussing with the product team, I'm updating the related doc with the following content:
_The Enrollment Status Page (ESP) is not supported with the supersedence public preview. ESP displays provisioning progress after a new device is enrolled, as well as when new users sign into the device. For the supersedence public preview, if an app has a supersedence relationship, it will not be enforced during ESP even if it is included as a selected app in an ESP policy. Additionally, apps that are involved in supersedence relationships will not be sent to the client device during ESP. However, the apps will be sent to the device after ESP completes, and the supersedence relationship will be respected._

If you continue to have questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

Please use the above channels if you don't already have a solution. Thanks
