### ISSUE TITLE
Information about Network access account usage is not complete

### ISSUE THREAD

**Issue by rrifonasmsft** [MicrosoftDocs/memdocs#1391]
We have the information below for the network access account usage:
+ Used by clients to connect to a distribution point and access content. **By default, the computer account is tried first.**

This give an impression that anonymous access is never used, and conflicts with the information under "Client to distribution point communication" - https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/hierarchy/communications-between-endpoints#bkmk_client2dp - where it says "Anonymous access" is the first connection method attempted for HTTP DPs:

DP type | Client authentication
-- | --
HTTP | - Anonymous, if allowed- Windows-integrated authentication with computer account or network access account- Content access token (Enhanced HTTP)

This can create some confusion for customers, and they might ask why the IIS logs have the attempt with anonymous auth before the computer account/NAA/token.

Using the following phrase would be 'better' to describe the behavior on this case: **By default, anonymous access and the computer account is attempted before trying this account**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5263a701-fb87-ecf7-fe4c-b016f166f312
* Version Independent ID: 4a835af3-41e7-3312-0f5d-7242c1cbddad
* Content: [Content management fundamentals - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/hierarchy/fundamental-concepts-for-content-management)
* Content Source: [memdocs/configmgr/core/plan-design/hierarchy/fundamental-concepts-for-content-management.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/hierarchy/fundamental-concepts-for-content-management.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @rrifonasmsft for the feedback, good point. I made a change to clarify, it will publish Monday morning.
