### ISSUE TITLE
Wipe Option for personal iOS devices

### ISSUE THREAD

**Issue by moonman1875** [MicrosoftDocs/memdocs#1393]
The note mentioned in the Wipe section:
The Wipe action is not available for iOS/iPadOS devices enrolled with User Enrollment.

This does not appear to be the case, the wipe action is available for user enrolled devices...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cdcc7fd-5bd9-1645-abf4-a73d3ea7adaa
* Version Independent ID: 5022b2ba-5fb0-18ce-9079-1b65ad0b2e17
* Content: [Retire or wipe devices using Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/remote-actions/devices-wipe#feedback)
* Content Source: [memdocs/intune/remote-actions/devices-wipe.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/remote-actions/devices-wipe.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by v-rechau** [comment]
I agree with you that the note can be quite misleading. In this context, I believe "User Enrollment" refers specifically to the Apple User Enrollment and not user-initiated Device Enrollments (BYOD):
Wipe is not a supported action as listed here: https://docs.microsoft.com/en-us/mem/intune/enrollment/ios-user-enrollment-supported-actions
Docs on how to set up User Enrollment profiles: https://docs.microsoft.com/en-us/mem/intune/enrollment/ios-user-enrollment

**Comment by msbemba** [comment]
@moonman1875 Thank you for your feedback. 

Admins can only perform the following actions  and other actions like wipe are not supported on ios user enrollment

Retire
Delete
Remote Lock
Sync.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @moonman1875 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
