### ISSUE TITLE
Update Boundary group options for peer downloads options

### ISSUE THREAD

**Issue by saad-youssef** [MicrosoftDocs/memdocs#1395]
Hi Team,

Could you please update the update in the "Boundary group options for peer downloads" section as below:

- Prefer distribution points over peers **within** the same subnet
- Prefer could based sources over on-premises sources

![image](https://user-images.githubusercontent.com/80152796/110210122-89f72d00-7e90-11eb-86b9-76f9ab8dabec.png)

Thanks.

Regards,
Youssef

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a2d3a58-d1b9-6f56-8f0c-dfdf2733b670
* Version Independent ID: 436c5f30-086a-5c8a-d9b3-98a017f9f55b
* Content: [Configure boundary groups - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/boundary-groups)
* Content Source: [memdocs/configmgr/core/servers/deploy/configure/boundary-groups.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/deploy/configure/boundary-groups.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @saad-youssef for the feedback. There are a few other instances that are wrong, so I'll get them fixed up today.

**Comment by saad-youssef** [comment]
You are welcome @aczechowski.
