### ISSUE TITLE
please explain 'protected' status

### ISSUE THREAD

**Issue by peterjello** [MicrosoftDocs/memdocs#1396]
[Enter feedback here]
Hello,

could You explain what does it mean 'well protected' ? When the device meets requirements to be protected ?

_Protected
Data type: Boolean
Access type: Read/Write
Qualifiers: none
true if the client is well protected._

Regards
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 660a78ce-6b51-8431-ae80-4f1690fa9e2c
* Version Independent ID: eea11607-9996-10cd-fc12-afdc46178dd6
* Content: [SMS_G_System_EndpointProtectionStatus Class - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/develop/reference/protect/sms_g_system_endpointprotectionstatus-server-wmi-class#feedback)
* Content Source: [memdocs/configmgr/develop/reference/protect/sms_g_system_endpointprotectionstatus-server-wmi-class.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/develop/reference/protect/sms_g_system_endpointprotectionstatus-server-wmi-class.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @peterjello. The ConfigMgr SDK content hasn't changed in a long time, and it's an area in which we're not actively investing beyond basic maintenance and some new functionality. I did a quick check of one resource I have and it didn't have any further information on this attribute. 😞 

If you have more information and would like to submit a change for this issue, see [How to contribute](https://docs.microsoft.com/mem/use-docs#bkmk_contribute).
