### ISSUE TITLE
Procedure needs to be updated 

### ISSUE THREAD

**Issue by marchi86** [MicrosoftDocs/memdocs#1398]
Register the web (server) app / Step no. 5 cannot be done as ID tokens is no longer available. it can be added by clicking on "Add Platform" but in this case "Redirect URI" cannot be left blank. (as this field became mandatory)
"In the menu of the app properties, select Authentication. Select the ID tokens option at the bottom."

(admin edit: add article metadata for proper linking)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5da6c8b-447a-d0c7-4243-095745d85306
* Version Independent ID: 64b13b3d-22b4-2f04-0a7d-7d34a7b62395
* Content: [Manually register Azure AD apps - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/manually-register-azure-ad-apps#register-the-web-server-app)
* Content Source: [memdocs/configmgr/core/clients/manage/cmg/manually-register-azure-ad-apps.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/cmg/manually-register-azure-ad-apps.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by MP-feedback** [comment]
I see the same issue, on the Authentication tab of the App registrations there is nothing that says "ID tokens" there is only an option for "Allow public client flows,"  is this same option renamed? or has the option been moved to another tab?

![image](https://user-images.githubusercontent.com/82178689/114085001-a3abdb80-9865-11eb-819a-5bfce030808d.png)

**Comment by aczechowski** [comment]
Thanks @marchi86 for the feedback. I'm using #1417 to track the changes to this article, so closing this issue as a duplicate. You can subscribe to that issue to get status.
