### ISSUE TITLE
Administrator or standard user

### ISSUE THREAD

**Issue by JohnMoor** [MicrosoftDocs/memdocs#14]
Does the newly assigned primary user also receive admin privileges (e.g. added to the administrator group)? 

In normal cases only the enrolled (so primary user) is given admin access. Any other user who logs in is a standard user.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d40af25-83c1-4041-abde-19803c3352f1
* Version Independent ID: e089f511-d044-7511-e096-b23c7ac0cc18
* Content: [Find the primary user of a Microsoft Intune device.](https://docs.microsoft.com/en-us/mem/intune/remote-actions/find-primary-user#feedback)
* Content Source: [memdocs/intune/remote-actions/find-primary-user.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/remote-actions/find-primary-user.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
(6488391)

**Comment by Scottduf** [comment]
No. Changing the Primary User in Intune does not touch any local device group membership.
