### ISSUE TITLE
Require CTRL+ALT+DEL to log on

### ISSUE THREAD

**Issue by icelava** [MicrosoftDocs/memdocs#140]
The options explanations appear to be reversed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f2a095c-452e-c494-a013-0626b9f3728d
* Version Independent ID: a4787d69-187f-fe55-d071-3a37b9b082e9
* Content: [Protection settings for Windows 10 devices in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/endpoint-protection-windows-10#local-device-security-options)
* Content Source: [memdocs/intune/protect/endpoint-protection-windows-10.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/endpoint-protection-windows-10.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@icelava  Yep, those were reversed, and will appear correctly later today.  Thanks for reporting this one as well..
