### ISSUE TITLE
Are these new features also available in GCC/GCC High?

### ISSUE THREAD

**Issue by JavannJones** [MicrosoftDocs/memdocs#1401]
Hi all! I was wondering if it was safe to assume that these new features are going to be available in GCC and GCC High? If not, would that be annotated? Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d16c28db-1e8e-31fa-6127-3050a2940422
* Version Independent ID: 4cf9a244-1ae5-1637-48f7-3f503d400da6
* Content: [What's new in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new)
* Content Source: [memdocs/intune/fundamentals/whats-new.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/whats-new.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
9530794

**Comment by Brenduns** [comment]
When known, support for GCC or GCC High is added to a features core doc content.
