### ISSUE TITLE
MDM policy for eSIM?

### ISSUE THREAD

**Issue by dfconroy** [MicrosoftDocs/memdocs#1403]
I see this documentation for eSIM usage with Intune (https://docs.microsoft.com/en-us/mem/intune/configuration/esim-device-configuration) but I don't see any documentation on how to utilize it with client management via MDM. There's no policy or CSP. Is there any documentation on how to configure devices this way?

**Comment by MandiOhlinger** [comment]
@dfconroy The [eUICCs CSP](https://docs.microsoft.com/windows/client-management/mdm/euiccs-csp) is used. You can create a custom OMA-URI profile. Deploy one custom profile for each device. The profile must include the device ICCID and matching activation code from the carrier for each device. I updated the article with this information. The changes should be live later today.

If you create the custom profile, and want to share your findings, it'd be great if you updated the article with a pull request. We want and encourage community contributions.

To answer your question, no. Intune doesn't have a policy experience where you upload a CSV containing activation code/ICCID pairs, and randomly distributes the activation codes to the pool of targeted devices.

**Comment by dfconroy** [comment]
Thank you!
