### ISSUE TITLE
ClientCheckPass 3 and null not documented

### ISSUE THREAD

**Issue by Anoni-Mouse** [MicrosoftDocs/memdocs#1404]
[Enter feedback here]
On some machines I find a value of 3 and sometimes no value at all. Why aren't these documented?

Value | Client health check status
-- | --
1 | Client is healthy
2 | Client is unhealthy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 636234ad-acdf-47d8-1928-80fb50b61c65
* Version Independent ID: fe429803-8241-fed3-bc92-18750007be08
* Content: [SMS_CombinedDeviceResources Class - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/develop/reference/core/clients/collections/sms_combineddeviceresources-server-wmi-class)
* Content Source: [memdocs/configmgr/develop/reference/core/clients/collections/sms_combineddeviceresources-server-wmi-class.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/develop/reference/core/clients/collections/sms_combineddeviceresources-server-wmi-class.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @Anoni-Mouse. The ConfigMgr SDK content is an area in which we're not actively investing at this time beyond basic maintenance and some new functionality. I looked at one internal resource I have and didn't see any additional information on this attribute. 😞 

If you'd like to submit a change for this issue, see [How to contribute](https://docs.microsoft.com/mem/use-docs#bkmk_contribute).
