### ISSUE TITLE
Domain Join - Preview or GA

### ISSUE THREAD

**Issue by neilpaton** [MicrosoftDocs/memdocs#1407]
[Enter feedback here]
In Create and Assign Domain Join Profile section, https://docs.microsoft.com/en-us/mem/autopilot/windows-autopilot-hybrid#create-and-assign-a-domain-join-profile, it mentions 'Select Domain Join (Preview)'
In the console it no longer shows as Preview, so is it preview or is it now GA.
If GA, should documentation need to be updated?
Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f93dd93-e003-36fc-02d6-07166537d914
* Version Independent ID: 1b860d13-bcf5-50da-89f9-ee12ece6edb2
* Content: [Enrollment for hybrid Azure AD-joined devices - Windows Autopilot](https://docs.microsoft.com/en-us/mem/autopilot/windows-autopilot-hybrid#create-and-assign-a-domain-join-profile)
* Content Source: [memdocs/autopilot/windows-autopilot-hybrid.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/windows-autopilot-hybrid.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
9530932

**Comment by ErikjeMS** [comment]
PM confirmed that it's no longer in preview. I'll remove the notation today. Thanks!
