### ISSUE TITLE
What is  the SQL edition required  to prepare the SQL always on availability group for SCCM HA  

### ISSUE THREAD

**Issue by yunwa** [MicrosoftDocs/memdocs#1409]
[Enter feedback here]
In this document , it mentioned that we shall use an Enterprise edition of the SQL server. 
https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database

But if we setup Basic Availability Group for SQL , it only required Standard SQL edition from SQL perspective. So may I know why we still need Enterprise edition of SQL server for this HA solution ?
Is Basic Availability Group as SQL HA not supported by SCCM ?

Edition
**Use an Enterprise edition of SQL Server.**
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49301fc3-9163-d533-1057-f8d994e95bbf
* Version Independent ID: 3c3fbdf1-25ec-3c5f-be4c-46983216d3b5
* Content: [Prepare to use an availability group - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database)
* Content Source: [memdocs/configmgr/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @yunwa, see the [Limitations and known issues](https://docs.microsoft.com/mem/configmgr/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database#unsupported-sql-server-options-and-configurations) section, which has more information on this topic: 

> Basic availability groups: Introduced with SQL Server 2016 Standard edition, basic availability groups don't support read access to secondary replicas. Configuration requires this access.
