### ISSUE TITLE
Wiped device requirement?

### ISSUE THREAD

**Issue by bballpaul4work** [MicrosoftDocs/memdocs#1411]
Will there ever be a way to configure "Corporate-owned devices with work profile" without requiring the device be wiped first? If not, it will be quite the undertaking moving from Android device administrator if we tell everyone they need to wipe their phones first. For personal devices with a work profile it is not required, so what are the technical differences?

Additionally, when will Android 11 be supported?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4024ea9e-bd99-03a1-7dd2-5afb73736558
* Version Independent ID: ac95c8b2-ad77-e524-d0da-01449afc0bfd
* Content: [Enroll Android Enterprise dedicated, fully managed, or corporate-owned work profile devices in Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/android-dedicated-devices-fully-managed-enroll)
* Content Source: [memdocs/intune/enrollment/android-dedicated-devices-fully-managed-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/android-dedicated-devices-fully-managed-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@bballpaul4work We can't make any announcements about planned features or support that isn't already listed in the Intune [Features in Development article](https://docs.microsoft.com/en-us/mem/intune/fundamentals/in-development). To see what features we have in the pipeline, check with that article each month.

Intune supports Android 11.

For quicker response about technical operation questions, you can post on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
