### ISSUE TITLE
Wrong unit MB instead of GB

### ISSUE THREAD

**Issue by pc222** [MicrosoftDocs/memdocs#1412]
Hey guys,

check the disk space unit for available space in 

https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/configs/site-size-performance-guidelines#azure-machine-and-disk-performance

, please. Should be GB instead of MB.

BR

Phillipp

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cda5d744-c604-5cf1-2174-44a82db01053
* Version Independent ID: fd18ea2a-485e-67b0-dcbf-efa9784e2d3e
* Content: [Site size and performance guidelines - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/configs/site-size-performance-guidelines)
* Content Source: [memdocs/configmgr/core/plan-design/configs/site-size-performance-guidelines.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/configs/site-size-performance-guidelines.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @pc222 for the feedback. This article was created from a whitepaper that our engineering team put together a few years ago. As the paragraph above notes, Azure is constantly changing this information, so I think it's meant as a general reference for IOPS and limiting factors. But I'll check with the engineers to see if this was a typo or intended, and if they have any more current information.

**Comment by aczechowski** [comment]
Yep, confirmed it should be GB. Good catch. I'm updating it now, should publish live tomorrow morning.
