### ISSUE TITLE
Modify DA Connected services \ Enroll devices section 

### ISSUE THREAD

**Issue by ivaldesMSFT** [MicrosoftDocs/memdocs#1413]
We should either add a note to clarify that the number 'Devices sending data' represents (in DA portal Connected Services \ Enroll devices section) does not equal the number 'Properly Enrolled' devices represents (in ConfigMgr Connection Health Dashboard in console), or consider changing the section header / blue tile reference to 'X devices **properly enrolled**'

While the end-goal for this section is to show the number of 'Devices sending data' this is often misinterpreted identifying this with the number of 'Properly enrolled' devices, mostly cause we literally call it like that on the tile header ('X devices properly enrolled'). This is not correct, and 'Properly enrolled' devices are typically only shown in the ConfigMgr Connection Health Dashboard. 'Devices sending data' number in Connected services \ Enroll devices section is built on devices that are 'Properly enrolled' but it also includes devices that are present in DA portal where we have InventoryCompleteness=False, and these devices are not into the 'Properly enrolled' category on-prem

Attached a screenshot highlighting the 'conflict' with the 'properly enrolled' usage in the DA portal  Connected Services \ Enroll devices section.

This section reports 'Devices 
<img width="376" alt="WINWORD_z4O8TQQSdu" src="https://user-images.githubusercontent.com/55737748/111371852-378cec00-869a-11eb-8404-618c36feded0.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 819ede64-7469-d780-6420-bc785f459a1e
* Version Independent ID: d80b24c8-02d3-8958-79cb-10db3a6c8785
* Content: [Monitor connection health - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/desktop-analytics/monitor-connection-health)
* Content Source: [memdocs/configmgr/desktop-analytics/monitor-connection-health.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/desktop-analytics/monitor-connection-health.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
a private PR will add some content for this, as discussed via email, closing the issue.
