### ISSUE TITLE
This article is needing updating to the current Azure AD interface, it is missing steps and details needed to manually register the web and native client apps.

### ISSUE THREAD

**Issue by CliffHughes** [MicrosoftDocs/memdocs#1417]
This article is needing updating to the current Azure AD interface, it is missing steps and details needed to manually register the web and native client apps, especially around the ID Tokens interface as well as the secret keys in the app you have to make sure you note the details for later, and it only tells you this later during the import process when its too late. so you have to make sure and do that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5da6c8b-447a-d0c7-4243-095745d85306
* Version Independent ID: 64b13b3d-22b4-2f04-0a7d-7d34a7b62395
* Content: [Manually register Azure AD apps - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/manually-register-azure-ad-apps)
* Content Source: [memdocs/configmgr/core/clients/manage/cmg/manually-register-azure-ad-apps.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/cmg/manually-register-azure-ad-apps.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by MP-feedback** [comment]
As an example, on the Authentication tab of the App registrations there is nothing that says "ID tokens" there is only an option for "Allow public client flows," is this same option renamed? or has the option been moved to another tab?

![image](https://user-images.githubusercontent.com/82178689/114085252-f71e2980-9865-11eb-9505-6a610cb7a4f4.png)

**Comment by aczechowski** [comment]
Thanks @CliffHughes and @MP-feedback for the feedback. I created this article about six months ago, and obviously AAD has already changed in that time. 🤦
