### ISSUE TITLE
Modify URL in Japanese page

### ISSUE THREAD

**Issue by sufuruka** [MicrosoftDocs/memdocs#1419]
Docs link is old in Japanese.
Could you please change the URL from resourses.azure.com to https://aka.ms/endpointanalytics ?

![image](https://user-images.githubusercontent.com/57698840/111560346-a884ee80-87d5-11eb-929e-f661523a916b.png)

**Comment by ErikjeMS** [comment]
@sufuruka Which article does this suggestion apply to?

**Comment by aczechowski** [comment]
I reproduced the issue on https://docs.microsoft.com/ja-jp/mem/analytics/enroll-configmgr, which gets content from analytics/includes/onboard.md. The same issue occurs with the enroll-intune article that uses the same include file. The en-us source has the correct link, so this is an issue with the localization engine. I'm going to close this issue, but will forward it to our localization team to investigate and fix.

Thanks @sufuruka for reporting it!
