### ISSUE TITLE
User Based Deployments does not work on an Internet Client (IBCM)

### ISSUE THREAD

**Issue by motaj1** [MicrosoftDocs/memdocs#142]
This part of the documentation needs to be revised as User based deployments doesn't work anymore on an Internet Client in IBCM Scenario. It looks like this worked with Application Catalog and stopped working after App Catalog was deprecated.
"Software deployment to users unless the internet-based management point can authenticate the user in Active Directory Domain Services by using Windows authentication (Kerberos or NTLM). This is possible when the internet-based management point trusts the forest where the user account resides."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0894e83-ae5e-960f-169c-cb5ea0e85a10
* Version Independent ID: 2a3ad459-44e9-7fe1-f2b9-a6b8ad58afa9
* Content: [Internet-based client management - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/plan-internet-based-client-management#feedback)
* Content Source: [memdocs/configmgr/core/clients/manage/plan-internet-based-client-management.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/plan-internet-based-client-management.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Correct, the traditional user-targeted scenario required the app catalog, which provided user authentication. To support user authentication for policies in Software Center, it requires Azure AD.I have some other updates to make for CMG soon, I'll add this in.

**Comment by DustinThyme** [comment]
WOW. This would have been really nice information to have before I did my upgrade to CM1910.  Thank you motaj1 for saying something.

**Comment by aczechowski** [comment]
I made a change for this issue, it should publish live later this afternoon.
