### ISSUE TITLE
Conflicting translation

### ISSUE THREAD

**Issue by VigneshMitsume** [MicrosoftDocs/memdocs#1420]
[Enter feedback here]
In this page, the english content is showing that "The device is removed from Intune" but in the Japanese translation it is saying that "The device will not be removed from Intune". Need to be updated appropriately.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 515d32cb-c6b5-7487-347c-f4134291ce3d
* Version Independent ID: 1d0312aa-9068-19c4-9309-97606169ba56
* Content: [Unenroll device in Company Portal for macOS app - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/user-help/unenroll-your-device-from-intune-macos?source=docs)
* Content Source: [memdocs/intune/user-help/unenroll-your-device-from-intune-macos.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/user-help/unenroll-your-device-from-intune-macos.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @ishasahni1, could you please help with this localization issue?

**Comment by ishasahni1** [comment]
@lenewsad i am no longer part of loc team. Please contact @SonjaSaltzman

**Comment by lenewsad** [comment]
Hi @SonjaSaltzman, could you please point me in the right direction for a localization contact for the Microsoft Intune docs?

**Comment by SonjaSaltzman** [comment]
the loc contact is @nokura
