### ISSUE TITLE
Duplicate Line and Wrong Variable Type

### ISSUE THREAD

**Issue by armen-danielyan** [MicrosoftDocs/memdocs#1423]
This Line is duplicated
`atesAssignment["NotifyUser"].BooleanValue = newNotifyUser;`

---------------------------------------------------------------------------------------------

Wrong Variable Type, StringValue should be DateTimeValue
`newSUMUpdatesAssignment["StartTime"].StringValue = newStartTime;`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78c0ddfb-4bd9-01ef-795c-4b8c4721ea66
* Version Independent ID: 68e022a2-1a7f-9c53-052e-bd229d3340e1
* Content: [Configure and Deploy Updates - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/develop/sum/how-to-configure-and-deploy-updates?source=docs)
* Content Source: [memdocs/configmgr/develop/sum/how-to-configure-and-deploy-updates.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/develop/sum/how-to-configure-and-deploy-updates.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @armen-danielyan for the feedback. We're generally not doing much with the ConfigMgr SDK content these days, but this is a quick fix.
