### ISSUE TITLE
Actions for Noncompliant device when multiple policies apply

### ISSUE THREAD

**Issue by rasldasl** [MicrosoftDocs/memdocs#1425]
[Enter feedback here]

How are actions applied when multiple policies apply, especially when device is already noncompliant at the time a new policy with new actions is created? 

Example: 
Old policy - mark device noncompliant 0 days (for example due to PIN too short)
New policy - mark device noncompliant 0 days, email and push notifications, retire at 30 days (new policy on PIN but with different actions and scope)
Device is already marked noncompliant, it appears that the further actions are not taken (email and push notifications, add to list for retirement). 
Is this behavior to be expected and, if so, what is the best way to apply a new policy and have the actions performed? 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2e7ac08-bfd6-9560-ad25-bced9b944822
* Version Independent ID: 6b1f70f0-aed3-52ac-25eb-1de55babc9d0
* Content: [Noncompliant message and actions with Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/actions-for-noncompliance)
* Content Source: [memdocs/intune/protect/actions-for-noncompliance.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/actions-for-noncompliance.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@rasldasl  Thanks for the submission, and I'm sorry to hear the policies are not applying. I've consulted with our engineering team, and they confirm that later policies,, created and applied to a device already marked as noncompliant by an earlier policy, should have their actions applied. 

As we're not able to provide troubleshooting via this feedback venue, if that continues to be an issue, please contact support to get this investigated and unravel why the later policies are not being applied/acted upon. To contact support, see [Get support](https://docs.microsoft.com/en-us/mem/get-support) in the Microsoft Endpoint Manager documentation.
