### ISSUE TITLE
sms_usermachinerelationship-server-wmi-class documentation

### ISSUE THREAD

**Issue by eraleigh** [MicrosoftDocs/memdocs#1426]
This page mentions [source].  It correlates to 8 items in an array.  However, running command-let Get-CMUserDeviceAffinity returns:

isactive resourceid resourcename    sources     
-------- ---------- ------------    -------     
    True   16808262 <hostname>  {4, 7, 9} 

What does source '9' refer to?  We are using SCCM 2012 version 2010.

Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 768c3af0-295b-772d-11fd-4de326a200e0
* Version Independent ID: a279c605-9a16-c2d0-ea2b-bd5b9fb21bf5
* Content: [SMS_UserMachineRelationship class - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/develop/reference/core/clients/manage/sms_usermachinerelationship-server-wmi-class)
* Content Source: [memdocs/configmgr/develop/reference/core/clients/manage/sms_usermachinerelationship-server-wmi-class.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/develop/reference/core/clients/manage/sms_usermachinerelationship-server-wmi-class.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @eraleigh. The ConfigMgr SDK content is an area in which we're not actively investing right now beyond basic maintenance and some new functionality. I did a quick check in one internal resource I have, and I didn't find further information on this attribute.

Some other options to consider:

- Post on [Configuration Manager forums](https://docs.microsoft.com/answers/products/mem). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

**Comment by aczechowski** [comment]
I found another resource, which defines `9` as **Secure Usage Agent**. I don't know what that means, but I'll add it to the docs, so it's at least there.
