### ISSUE TITLE
Renew Token Section - Wrong wording... Adjust intune preferably?

### ISSUE THREAD

**Issue by thesling1** [MicrosoftDocs/memdocs#1427]
[Hello MS Support,

The token renewal section advises: 
Select Renew token. You'll see a confirmation that the token is renewed:

Please note that inside Intune that at this point Intune does not have a button that says "Renew Token", it actually says create token.

Ideally in this scenario... I agree Intune should have a button stating "renew".

Thank you,
Tony.

]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd130267-c54b-41e3-d534-831d4a86bae6
* Version Independent ID: bdfa7eca-a356-3dde-7643-9a759f952007
* Content: [Enroll iOS/iPadOS devices by using ADE - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-ios)
* Content Source: [memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@thesling1 Thank you for your feedback. I was able to test and I see the renew token option in Intune. Looks like this might have been fixed recently after you posted the issue.

![image](https://user-images.githubusercontent.com/45987684/159621664-930088ca-515c-4a4e-8176-bd401af6b2f1.png)

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit This can be closed.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @thesling1 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
