### ISSUE TITLE
Powershell Script Error Return not documented

### ISSUE THREAD

**Issue by IN-jwink** [MicrosoftDocs/memdocs#1428]
No information about what constitutes a failure and what can be used inside the script as a return to trigger a recording of failure in Intune for later reporting and remediation.  Are all scripts assumed successful if they execute at all?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d6b1270-e554-dc36-2a51-1cdab303e91a
* Version Independent ID: 4a62c248-5737-13cc-3270-1f9649bd147d
* Content: [Add PowerShell scripts to Windows 10 devices in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/apps/intune-management-extension)
* Content Source: [memdocs/intune/apps/intune-management-extension.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/intune-management-extension.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@IN-jwink - You can use `AgentExecutor.log` as the log file to track PowerShell script execution details. For more information, see [ntune management extension logs](https://docs.microsoft.com/mem/intune/apps/intune-management-extension#intune-management-extension-logs).

If you have additional questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

Please use the above channels if you need additional information.
