### ISSUE TITLE
Block setting up new nearby devices and allowProximitySetupToNewDevice

### ISSUE THREAD

**Issue by MarcLaf** [MicrosoftDocs/memdocs#1429]
In trying to block the proximity setup for new devices I've come across the following setting in Intune which I believe is the same thing however I'm unable to see what key this is modifying. According to Apple's config profile reference, there is a key called **allowProximitySetupToNewDevice** which controls the prompt to setup new devices that are nearby. The closest I found in Intune was the setting called **Block setting up new nearby devices** however, the Apple documentation states that this setting requires the device to be Supervised. The Intune documentation does not state this fact nor do any tooltips on the Device configuration profile setup page. If these settings are in fact the same, could you please add whether or not they require the device to be Supervised? This would greatly speed up troubleshooting.

For reference the only thing stated on the Intune docs is this:

> Block setting up new nearby devices: Yes disables the prompt to set up new devices that are nearby. When set to Not configured (default), Intune doesn't change or update this setting. By default, the OS might allow prompts for users to connect to other nearby Apple devices.

The other request I have which may or may not be possible but can you add which keys these configuration settings modify? For example:

allowProximitySetupToNewDevice - Boolean - True/False

or however you may see fit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88932dd8-abce-bf23-9624-1df5f60a946d
* Version Independent ID: ab2d932f-e375-2485-a6e5-e02daf7a27c4
* Content: [iOS/iPadOS device settings in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-ios)
* Content Source: [memdocs/intune/configuration/device-restrictions-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/device-restrictions-ios.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@MarcLaf Here are the answers to your questions:

**Q1**: allowProximitySetupToNewDevice which controls the prompt to setup new devices that are nearby. The closest I found in Intune was the setting called Block setting up new nearby devices...
**Answer**: The **Block setting up new nearby devices** setting does use the **allowProximitySetupToNewDevice** key.

**Q2**: ...could you please add whether or not they require the device to be Supervised?
**Answer**: The tooltip doesn't say "supervised", and won't say "supervised. The device configuration profile setup does state "supervised".

In the UI, all the settings are organized by enrollment type, such as **Automated device enrollment**. For this specific setting, the enrollment type description says "supervised":

![image](https://user-images.githubusercontent.com/3229224/112162438-6fc48b00-8bc2-11eb-9b1b-c392aedd9d7a.png)

**Q3**: ...can you add which keys these configuration settings modify?
**Answer**: Apple changes their key names often. It's not feasible to maintain the list, and keep it correct. It's possible that could change in the future.
