### ISSUE TITLE
confusing text in example command line

### ISSUE THREAD

**Issue by PJMarcum** [MicrosoftDocs/memdocs#143]
Rather than showing, "ccmsetup.exe CCMHOSTNAME=CONTOSO.CLOUDAPP.NET/CCM_Proxy_MutualAuth/72186325152220500 SMSSiteCode=ABC AADCLIENTAPPID=7506ee10-f7ec-415a-b415-cd3d58790d97 AADRESOURCEURI=https://contososerver SMSMP=https://mp1.contoso.com PROVISIONTS=PRI20001" in the example command it would be more clear if you showed it using ccmsetup.msi as that's the file that's uploaded to Intune. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 875e279b-9029-d1e5-8a6c-0e93ce38ddba
* Version Independent ID: 80bc34d7-3ef7-1c4f-da41-0474b1c5f4a4
* Content: [Co-manage internet-based devices - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/comanage/how-to-prepare-Win10)
* Content Source: [memdocs/configmgr/comanage/how-to-prepare-Win10.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/comanage/how-to-prepare-Win10.md)
* Product: **configuration-manager**
* Technology: **configmgr-comanage**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @PJMarcum for the feedback.

If you want to submit the change, see [How to contribute](https://docs.microsoft.com/mem/configmgr/core/understand/use-docs#bkmk_contribute). 😉

**Comment by PJMarcum** [comment]
Aaron,
I'll try to start doing the edits myself I'm just swamped right now. Per a fellow MVP, the example command-line should actually look like this. The "CCMSETUPCMD=" and the quotes are required: 
 CCMSETUPCMD=”CCMHOSTNAME=MYCMGC.CLOUDAPP.NET/CCM_Proxy_MutualAuth/1234567890 SMSSiteCode=XXX”

**Comment by mestew** [comment]
Editing this now. thanks @PJMarcum
