### ISSUE TITLE
Ready (with remediation) devices do not show in ConfigMgr Pilot collection 

### ISSUE THREAD

**Issue by g4m3c4ck** [MicrosoftDocs/memdocs#1432]
Running MEMCM 2002.
If this is a bug then it should state the below instead until it is fixed. I lost days of work because this page was untrue.

Use the following definitions to differentiate between pilot and production:

Pilot: A subset of your devices that you want to validate before you deploy to a larger set. Use Desktop Analytics to add individual devices to the pilot set. Devices in the pilot are ready to upgrade when:

- **All assets that have Microsoft known issues have been marked with Ready.**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91ad839e-81cb-c95f-20e0-ea725f6a3791
* Version Independent ID: 9602c6f1-b564-a057-115b-75a80f07c2d3
* Content: [How to deploy to pilot - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/desktop-analytics/deploy-pilot)
* Content Source: [memdocs/configmgr/desktop-analytics/deploy-pilot.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/desktop-analytics/deploy-pilot.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by g4m3c4ck** [comment]
I have heard the Devs were fixing this so this needs to be confirmed. But the issue is Ready (with Remediation) devices are not being added to the Pilot collection.

**Comment by aczechowski** [comment]
I discussed with the engineering team. The behavior is as you state, and wrong in the docs. I'll revise that now. They're discussing possible future improvements, but for now, the device has to be marked "ready" to be included in ConfigMgr collections for pilot or production.
