### ISSUE TITLE
Wrong order to delete

### ISSUE THREAD

**Issue by mmelkersen** [MicrosoftDocs/memdocs#1435]
This order is not correct.

You cannot delete an AAD record if it is Autopilot registered.

Completely removing a device from your tenant requires you to delete the Intune device, the Azure Active Directory device, and the Windows Autopilot device records. These deletions can all be done from Intune:

If the devices are enrolled in Intune, you must first delete them from the Intune All devices blade.

Delete the devices in Azure Active Directory devices at Devices > Azure AD devices.

Delete the devices from Windows Autopilot at Devices > Windows > Windows enrollment > Devices (under Windows Autopilot Deployment Program). Choose the devices you want to delete, then choose Delete. Windows Autopilot device deletion can take a few minutes to complete.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea4a659b-65d0-26ec-c36a-9a21a72a09a8
* Version Independent ID: bff44b73-9021-6659-e212-66349c759989
* Content: [Manually register devices with Windows Autopilot](https://docs.microsoft.com/en-us/mem/autopilot/add-devices#edit-autopilot-device-attributes)
* Content Source: [memdocs/autopilot/add-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/add-devices.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
Thanks for catching this - step 3 will be moved to step 1 in the live content this afternoon. I've merged this change to master already in the private repo.
