### ISSUE TITLE
Incorrect "tab" name in this doc

### ISSUE THREAD

**Issue by PJMarcum** [MicrosoftDocs/memdocs#1438]
In this sentence, "Deployment Option tab of the deployment" "Deployment Option" is not the name of the tab, the tab is "Distribution Points" and "Deployment Options" is a section on that tab. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a85202b8-4198-2bda-e55f-48ef2db6768f
* Version Independent ID: 676fa801-586d-90d2-9c2a-2411ab35abc4
* Content: [Configure pre-cache content - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/osd/deploy-use/configure-precache-content)
* Content Source: [memdocs/configmgr/osd/deploy-use/configure-precache-content.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/osd/deploy-use/configure-precache-content.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @PJMarcum, good catch. I'll fix that now.
