### ISSUE TITLE
Workloads left on Configuration Manager

### ISSUE THREAD

**Issue by ajp999** [MicrosoftDocs/memdocs#1439]
[Enter feedback here]

It would be useful to explain what management features would remain in Configuration Manager if you switched all the currently available workloads to Intune i.e. features of Configuration Manager that are not supported by co-management.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 405b6221-1ae4-bb22-2352-fe8afadc8a88
* Version Independent ID: 1fd26b13-4706-b171-1977-2f70b3858422
* Content: [Switch co-management workloads - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/comanage/how-to-switch-workloads)
* Content Source: [memdocs/configmgr/comanage/how-to-switch-workloads.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/comanage/how-to-switch-workloads.md)
* Product: **configuration-manager**
* Technology: **configmgr-comanage**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @ajp999 for the feedback. That's a long list, and ever changing, which would be difficult to maintain. We maintain the [list of workloads](https://docs.microsoft.com/mem/configmgr/comanage/workloads), so then anything _not_ listed there isn't supported by co-management.
