### ISSUE TITLE
The pre-requisite check for the supported  SQL Native client does NOT check remote systems

### ISSUE THREAD

**Issue by BritV8** [MicrosoftDocs/memdocs#144]
Document states
"This check makes sure the site has a supported version of the SQL Native Client. Starting in version 1810, the minimum version is SQL 2012 SP4 (11.*.7001.0).
"
This is not true as I had a remote Reporting services point and no warning was raised running the check

I sent a frown and got this back

"We are not checking each of the remote site system for the SQL native client version"

Perhaps some clarity around this would be good e.g. 
"if any of these system roles are remote to the site server, you will need to check them manually"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc1a8434-edaa-fb23-492a-62e7b1c04f08
* Version Independent ID: db6b1c4d-064b-982d-bcaf-8749104713e0
* Content: [Prerequisite checks - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/install/list-of-prerequisite-checks#sql-server-native-client)
* Content Source: [memdocs/configmgr/core/servers/deploy/install/list-of-prerequisite-checks.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/deploy/install/list-of-prerequisite-checks.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @BritV8 for the feedback.

If you want to submit the change yourself, see [How to contribute](https://docs.microsoft.com/mem/configmgr/core/understand/use-docs#bkmk_contribute). 😉

**Comment by mestew** [comment]
Verifying this with engineering so we can clarify the doc

**Comment by mestew** [comment]
@BritV8 I've verified this with engineering. I updated the doc to mention that the prereq check doesn't verify SQL Native Client version on remote site systems. You'll be able to see the change within the next 24 hours. Thanks much for bringing this to our attention.
