### ISSUE TITLE
Lack of guidance on open-in management setting

### ISSUE THREAD

**Issue by svenhallauer** [MicrosoftDocs/memdocs#1440]
The text in the article mentions "Set Open-in management restrictions in configuration settings and then deploy them using your MDM solution" - but fails to provide the needed details for Intune or link to a page that does.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1837d30e-1cb7-a2aa-6bad-f4014c32e6c1
* Version Independent ID: 23b6fd50-90f7-1651-d68e-13b99e13175c
* Content: [Manage transferring data between iOS apps - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/data-transfer-between-apps-manage-ios)
* Content Source: [memdocs/intune/apps/data-transfer-between-apps-manage-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/data-transfer-between-apps-manage-ios.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@svenhallauer - Thanks for the feedback. I agree and have updated the related topic to help clarify the setting. I also added links to additional information, such as steps for app protection policies, iOS details related to **Open-in**, and more. Thanks
