### ISSUE TITLE
2 new Compliance Partners are supported with Endpoint Manager

### ISSUE THREAD

**Issue by floremsft** [MicrosoftDocs/memdocs#1442]
https://docs.microsoft.com/en-us/mem/intune/protect/device-compliance-partners#supported-device-compliance-partners

2 new Compliance Partners are supported

Supported device compliance partners
The following partners are supported as generally available:

JAMF Pro
MobileIron Device Compliance On-prem
VMware Workspace ONE UEM (formerly AirWatch)
**IBM MaaS360
Citrix Workspace**

![image](https://user-images.githubusercontent.com/38796491/112324261-fba0ea80-8c88-11eb-82f7-25ae2c8c37b5.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81bcb445-ada9-e2e3-d8a8-a5693a5a3850
* Version Independent ID: 6214bb16-5087-c21c-fd43-d5f0a6f405c1
* Content: [Device compliance partners in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/device-compliance-partners)
* Content Source: [memdocs/intune/protect/device-compliance-partners.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/device-compliance-partners.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by floremsft** [comment]
Confusing... It appears IBM only offers the App Protection policies capability, not the Device Compliance capability?
https://www.ibm.com/support/knowledgecenter/en/SS8H2S/com.ibm.mc.doc/pag_source/concepts/intune_app_policies_overview.htm

**Comment by Brenduns** [comment]
@floremsft   Hello, and thanks for this submission.  There are currently four partner products visible in the UI which are not yet supported by Intune. Please see the GitHub issue https://github.com/MicrosoftDocs/memdocs/issues/1058  for more details on why this is.  But in short, those are partners in private previews which require their products to be visible in the public UI while being developed. 

As per that GitHub issue issue from November of 2020, I've passed the information from this issue to our engineering team to first confirm if the list of supported partners has changed, and to consider the confusion this different of supported/visible can create.

At this time, I'll be closing this GitHub issue. However, should I hear back from our engineering partners that there is any change to the support list, or that an update for the core doc has been approved, I'll reply back to you via this same issue with that update.

**Comment by Brenduns** [comment]
@floremsft    Our engineering team met with the two compliance partners to confirm their offerings (_IBM MaaS360_, and - _Cotrix Workspace device compliance_) are ready to be listed as supported. Both of these partner products are in a  public preview stage.  Our content will update later today to reflect this.
