### ISSUE TITLE
The values listed for EPProductStatus are incorrect

### ISSUE THREAD

**Issue by TerenceDurning** [MicrosoftDocs/memdocs#1446]
The values listed for EPProductStatus are incorrect.  Value 0 is listed twice ("No status flags are set", "Service not running") and comparing the statuses to what shows in the Configuration Manager console (1 is "Service not running", for instance), it looks like they are all off and can be corrected by shifting the values up, like:

Value | Hex Value | EP Product status
0 | 0 | No status flags are set.
1 | 1 | Service not running.
2 | 2 | Service started without any malware protection engine.
4 | 4 | Pending a full scan due to threat action.
8 | 8 | Pending a reboot due to threat action.
16 | 10 | Pending manual steps due to threat action.
32 | 20 | AV signatures out of date.
64 | 40 | AS signatures out of date.
128 | 80 | No quick scan has happened for a specified period.
256 | 100 | No full scan has happened for a specified period.
512 | 200 | System initiated scan in progress.
1024 | 400 | System initiated clean in progress.
2048 | 800 | There are samples pending submission.
4096 | 1000 | Product running in evaluation mode.
8192 | 2000 | Product running in non-genuine Windows mode.
16384 | 4000 | Product expired.
32768 | 8000 | Off-line scan required.

Additionally, these values can be combined, and for whatever reason, 524288 (0x80000) is added to a bunch of computers.  A sample workstation has an EP_ProductStatus value of 524384 (0x20 + 0x40 + 0x80000) and shows in the console as "AV signatures out of date; AS signatures out of date".
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 636234ad-acdf-47d8-1928-80fb50b61c65
* Version Independent ID: fe429803-8241-fed3-bc92-18750007be08
* Content: [SMS_CombinedDeviceResources Class - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/develop/reference/core/clients/collections/sms_combineddeviceresources-server-wmi-class)
* Content Source: [memdocs/configmgr/develop/reference/core/clients/collections/sms_combineddeviceresources-server-wmi-class.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/develop/reference/core/clients/collections/sms_combineddeviceresources-server-wmi-class.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @TerenceDurning for the feedback. I think I found the other values for this attribute, the first 16 matched exactly, so I'm assuming these values are appropriate for it as well:

| Decimal value | Hexidecimal value | Status |
| ----- | ----- | ----------------- |
|32768|8000|Off-line scan required.|  
|65536|10000|Service is shutting down as part of system shutdown.|
|131072|20000|Threat remediation failed critically.|
|262144|40000|Threat remediation failed non-critically.|
|524288|80000|No status flags set (well initialized state).|
|1048576|100000|The platform is out of date.|
|2097152|200000|Platform update is in progress.|
|4194304|400000|The platform is about to be outdated.|
|8388608|800000|The signature or platform end of life is past or is impending.|

I'll update the doc to include this info, as well as a blurb about combining the values as you suggest.

p.s. I don't know what the status means for 524288....
