### ISSUE TITLE
Confusing guidance

### ISSUE THREAD

**Issue by svenhallauer** [MicrosoftDocs/memdocs#1447]
This page has a Note that reads: "Deploy IntuneMAMUPN app configuration settings to the target managed app which sends data, not the receiving app."

This should instead read: "Deploy IntuneMAMUPN managed device app configuration settings to the target app which sends data, adding the app configuration key to the receiving app is optional."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1837d30e-1cb7-a2aa-6bad-f4014c32e6c1
* Version Independent ID: 23b6fd50-90f7-1651-d68e-13b99e13175c
* Content: [Manage transferring data between iOS apps - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/data-transfer-between-apps-manage-ios)
* Content Source: [memdocs/intune/apps/data-transfer-between-apps-manage-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/data-transfer-between-apps-manage-ios.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@svenhallauer Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2488

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @svenhallauer Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
