### ISSUE TITLE
Intune roles required to access create Device Catergories

### ISSUE THREAD

**Issue by jadams0003** [MicrosoftDocs/memdocs#1448]
It would be very helpful for documents to include what Intune roles are required to create device categories or to access anything with in Intune.   It is a lot of trial and error required to figure which settings apply to what and would be nice if the documents just listed what is required.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a205db9e-c21f-b505-b5e9-d54fe44ececb
* Version Independent ID: a85d08c2-8ef1-fcd4-52de-f74ea8f41124
* Content: [Categorize devices into groups in Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-group-mapping)
* Content Source: [memdocs/intune/enrollment/device-group-mapping.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/device-group-mapping.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by msbemba** [comment]
@jadams0003 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2487

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jadams0003 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
