### ISSUE TITLE
Enhanced jailbreak detection: Topic seems to flow over in another topic

### ISSUE THREAD

**Issue by yvesrosius** [MicrosoftDocs/memdocs#145]
Enhanced jailbreak detection describes enhanced detection of jailbreaked devices, but then carries over to location detection.

Shouldn't this be another bullet?

Also, this is a bit of a strange place to include. The topic describes ways to deploy device compliance policies. Now it includes 2 of the compliance checks (jail-broken, location).
https://docs.microsoft.com/en-us/mem/intune/protect/device-compliance-get-started?source=docs#ways-to-deploy-device-compliance-policies

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c19b6ee-2218-cd97-96a4-2832c0302d7e
* Version Independent ID: da3ff20c-91cb-d760-708c-8e56af5d59d8
* Content: [Device compliance policies in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/device-compliance-get-started?source=docs#ways-to-deploy-device-compliance-policies)
* Content Source: [memdocs/intune/protect/device-compliance-get-started.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/device-compliance-get-started.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@yvesrosius  This article does seem to munge a few things together. I’ve added a bug to my work queue for a future review and restructure of this article - to sort out what seems an odd inclusion.  For now, I’ve submitted an edit for some minor clarifications, but restructuring the mix of device specific compliance settings with default actions for non-compliance will occur at a future time.   The entire article will be reviewed at that time.
