### ISSUE TITLE
lowest supported database compatibility level

### ISSUE THREAD

**Issue by ingebeumer** [MicrosoftDocs/memdocs#1450]
Hi, 
Documentation doesn't seem consistent with configuration. Section https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/configs/support-for-sql-server-versions#database-compatibility-level states 110 is the lowest supported compatibility level for SQL Server 2019, however 100 is also configurable. I don't have lower version instances at hand so can't check for SQL Server 2017, 2016, 2014 now. Please check if documentation is eligible for improvement.
Kind regards, Inge

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 142474e9-8dd5-6412-85ca-b1d2dc8c01ac
* Version Independent ID: d4de0aa7-2579-acdf-f7f5-04a39d8045d8
* Content: [Supported SQL Server versions - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/configs/support-for-sql-server-versions)
* Content Source: [memdocs/configmgr/core/plan-design/configs/support-for-sql-server-versions.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/configs/support-for-sql-server-versions.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Compatibility level 100 (and others) might be available on those versions of SQL, but they're not supported by Configuration Manager. Level 100 = SQL Server 2008 R2. [Reference](https://docs.microsoft.com/sql/t-sql/statements/alter-database-transact-sql-compatibility-level#arguments)

**Comment by ingebeumer** [comment]
Hi @aczechowski 
Now I see, I mistakenly ended up in Configuration Manager documentation while I needed to be in SQL Server documentation. Apologies for the confusion.
Kind regards, Inge
