### ISSUE TITLE
Need precision about the CRL with token authentication

### ISSUE THREAD

**Issue by JuGhithub** [MicrosoftDocs/memdocs#1452]
When we implement the CMG with a token-based authentication for client, the CRL need to be checked or not?

https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/security-and-privacy-for-cloud-management-gateway#publish-the-certificate-revocation-list
----------------------------------------------------------------------------------
This CMG option verifies the client authentication certificate.
If the client is using Azure AD authentication, the CRL doesn't matter.
If you use PKI, and externally publish the CRL, then enable this option (recommended).
If you use PKI, don't publish the CRL, then disable this option.
If you misconfigure this option, it can cause additional traffic from clients to the CMG. This additional traffic can increase the Azure egress data, which can increase your Azure costs.
-----------------------------------------------------------------------------------------------

Regards, 

Julien

(admin edit: add article metadata for proper tracking)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e622722a-ce0f-0829-100a-0c6cbf86230a
* Version Independent ID: 93bff21c-14ba-7cd4-a36e-d7e5edecbcfa
* Content: [CMG security and privacy - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/security-and-privacy-for-cloud-management-gateway#publish-the-certificate-revocation-list)
* Content Source: [memdocs/configmgr/core/clients/manage/cmg/security-and-privacy-for-cloud-management-gateway.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/cmg/security-and-privacy-for-cloud-management-gateway.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @JuGhithub for the feedback. In this instance, ConfigMgr token auth is similar to AAD. I'll add that for clarification.
