### ISSUE TITLE
Delete Aged Scenario Health History Maintenance Task Missing

### ISSUE THREAD

**Issue by PrajwalDesai** [MicrosoftDocs/memdocs#1454]
The Delete Aged Scenario Health History maintenance task is missing from the list.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8964669d-7a44-83d9-ae6c-9765aabf221c
* Version Independent ID: fce0954c-706c-11a3-fc92-9b9a433da8a6
* Content: [Reference for maintenance tasks - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/manage/reference-for-maintenance-tasks)
* Content Source: [memdocs/configmgr/core/servers/manage/reference-for-maintenance-tasks.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/manage/reference-for-maintenance-tasks.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @PrajwalDesai for the feedback, I'll add it now
