### ISSUE TITLE
Out of Date Feature Descriptions Remain Listed

### ISSUE THREAD

**Issue by ajp999** [MicrosoftDocs/memdocs#1455]
[Enter feedback here]

There are a number of feature descriptions listed "In development for Microsoft Intune" that have already been implemented that should be removed from this page. Some items include:
- Microsoft Intune ends support for Windows Phone 8.1 and Windows 10 Mobile
- End of support for legacy PC management
- Move to the Microsoft Endpoint Manager admin center for all your Intune management
- Decreasing support for Android device administrator
- User experience of impacted settings on impacted devices
- Additional impacts based on Android OS version
- Plan for Change: Intune Enrollment Flow Update for Apple’s Automated Device Enrollment for iOS/iPadOS

It also states under "Microsoft Endpoint Manager ending support for Android 5.x" that support for Android 5.x devices will end in a future update. I believe this will be April 2021 so it would be useful to state this.

Even though it states that "When a feature enters production, whether it's a preview or generally available, the feature description will move from this page to What's new." this does not appear to be occurring regularly. 

Also please avoid referencing months i.e. March without adding the year (2021) so that it is clear which year is being referred.
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66f915d1-8486-44dc-a605-280f979d6f9b
* Version Independent ID: 23c6b2c3-64c1-2df3-ad51-d9be083871a1
* Content: [In development - Microsoft Intune](https://docs.microsoft.com/en-gb/mem/intune/fundamentals/in-development)
* Content Source: [memdocs/intune/fundamentals/in-development.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/in-development.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@ajp999 Thanks for noting these.
Items under Notices are often left therein for some time so users can quickly see when such things happened. I'll work with the PMs to find out if they want these removed.
Often, we can't put a specific release month for an impending feature due to the possibility of scheduling changes.
When we include months I'll work on also including the year.
