### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by RoelJanssens** [MicrosoftDocs/memdocs#1456]
How do I use the include and exclude WQL queries? If I enter them as a query rule for a collection I get syntax errors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6343751a-43fa-72fa-dc95-1bdae8cea4c8
* Version Independent ID: d0f550f1-6d1e-558d-3627-9773c1227c31
* Content: [Collections best practices - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/collections/best-practices-for-collections)
* Content Source: [memdocs/configmgr/core/clients/manage/collections/best-practices-for-collections.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/collections/best-practices-for-collections.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @RoelJanssens for the feedback. I assume you're referring to the sample WQL statements in the section [Consider collection depth and cross-referencing](https://docs.microsoft.com/mem/configmgr/core/clients/manage/collections/best-practices-for-collections#consider-collection-depth-and-cross-referencing). The table names are wrong, they should be `SMS_R_System`. And then you replace `[collection id]` with a collection ID like `XYZ0003F`. I'll update the doc to clarify.
