### ISSUE TITLE
macOS enrollment after setup assistant doesnt support MFA

### ISSUE THREAD

**Issue by rstenborg** [MicrosoftDocs/memdocs#1457]
Hi,

You should clearify that when enrolling after setup assistant with "sudo profiles renew -type enrollment" with UDA enabled you need to make sure that the user enrolling the device does not need to authenticate with MFA. This is not supported and you will just get reprompted for credentials all the time without any error message if you have MFA enforcement on your account. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0319ece7-6b1f-d737-618c-778d3f196313
* Version Independent ID: 20b5b39e-56e2-d88e-e4b2-22a79b5d3ccb
* Content: [Enroll macOS devices - Apple Business Manager or Apple School Manager](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-macos)
* Content Source: [memdocs/intune/enrollment/device-enrollment-program-enroll-macos.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/device-enrollment-program-enroll-macos.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by rstenborg** [comment]
You can refer to support case 23423762 😊

**Comment by zackrspv** [comment]
given that MFA is supported with the company portal option now with ADE, I assume this issue can be closed - however, it still appears it doesn't always register, even if the person registering is ENFORCED for MFA, is signed into the company portal, but the setup screen doesn't ask for MFA.
