### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by chiners68** [MicrosoftDocs/memdocs#1458]
There dosent seem to be a good place to feedback on this preview feature

1. Documentation says all settings in templates are all in settings catalog. Tell me where **Desktop background picture URL (Desktop only)** is, as Search or personalization path dosent give this setting.
2. Default file association dosent apply when you add XML contents.
3. Force a specific default lock screen and logon image dosent seem to apply either. 

these settings appear and work fine in old Templates/Custom Settings.

cheers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 671037ee-a099-5796-04c1-713be23f7d17
* Version Independent ID: 68957221-d9f4-9cf6-0988-83df9386d067
* Content: [Create a policy using settings catalog in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/settings-catalog)
* Content Source: [memdocs/intune/configuration/settings-catalog.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/settings-catalog.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
https://msazure.visualstudio.com/Intune/_workitems/edit/9617318

**Comment by MikeDano** [comment]
@chiners68 
We're continuing to add additional settings and the ones with special control requirements like image upload and preview are under construction.
I'll look into the Application defaults, but I wanted to ask if the value entered is b64 encoded.
https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-ApplicationDefaults?WT.mc_id=Portal-Microsoft_Intune_Workflows#applicationdefaults-policies

**Comment by chiners68** [comment]
Hi Mike,
  If I recall it didn’t mention what format it wanted. I tried both XML and base64 as per the custom setting application but neither worked. I then moved back to base64 on a custom policy and it worked straight away.

Regards

Mark

**Comment by MandiOhlinger** [comment]
@chiners68 Thank you for the extra information. If you're still trying to get this to work, we suggest [get supporting for Microsoft Intune](https://docs.microsoft.com/mem/get-support) to help find root cause. We can update this article based on any findings.
