### ISSUE TITLE
NTFS Permissions for WSFB to include Owner

### ISSUE THREAD

**Issue by leebow55** [MicrosoftDocs/memdocs#146]
Hello - I have had Support Ticket 19518516 open for issues with WSFB being able to synchronise new content after a File Server Upgrade which affected the permissions of the Content Location. Only once the Owner for the WSFB directory, and subdirectories was updated to be the Computer Object of the Service Connection Point would this resolve the issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e288d68-2af5-e86c-07cf-6412a921d091
* Version Independent ID: 8767d47a-971a-48f9-5c2a-b5857c365563
* Content: [Troubleshoot MSfB integration - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/apps/deploy-use/troubleshoot-microsoft-store-for-business-integration#feedback)
* Content Source: [memdocs/configmgr/apps/deploy-use/troubleshoot-microsoft-store-for-business-integration.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/apps/deploy-use/troubleshoot-microsoft-store-for-business-integration.md)
* Product: **configuration-manager**
* Technology: **configmgr-app**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @leebow55 for sharing this info. I confirmed some further details with folks in support, and submitted a change to the article. It should publish live later this afternoon.
