### ISSUE TITLE
Do users need an email license to be properly assigned to a Multi-App Kiosk?

### ISSUE THREAD

**Issue by ARGs-code** [MicrosoftDocs/memdocs#1460]
Multi-App Kiosk
User Logon Type 
Azure AD user or group (Windows 10, version 1803 and later): Requires user credentials to sign in to the device. Select Add to choose Azure AD users or groups from the list. You can select multiple users and groups. Choose Select to save your changes.

This doesn't list any other requirements for AAD users besides they are a user or user group. When assigning an AAD user to a multi-app Kiosk configuration, if they do not have an email license, InTune shows "Not Configured" and throws an error for that user.

Is an email license required in order for Multi-App Kiosks to work properly for AAD users?

[Example](https://gyazo.com/e982da9939bd077b8aff049160679c8b)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba5d70f6-d84b-8955-9013-dafec5560869
* Version Independent ID: f89428e5-1510-b939-aefe-eb283e1af319
* Content: [Kiosk settings for Windows Holographic for Business in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/kiosk-settings-holographic)
* Content Source: [memdocs/intune/configuration/kiosk-settings-holographic.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/kiosk-settings-holographic.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
https://msazure.visualstudio.com/Intune/_workitems/edit/9617281

**Comment by MikeDano** [comment]
@ARGs-code 
Email license shouldn't be required for this. 
Does the scenario work other than that text field?
Is the email license tied to the AAD/Intune license via EMS or M365?
I was looking at this doc but I don't see any other requirements for the user.

https://docs.microsoft.com/en-us/windows/configuration/lock-down-windows-10-to-specific-apps
Sections titled:
Config for individual accounts
Config for group accounts

**Comment by ARGs-code** [comment]
The email license is coming from an E3 O365 License. I have not tested the scenario because it throws an error and does not display the proper information hence I am not allowed to proceed until this error is resolved.

**Comment by MandiOhlinger** [comment]
@ARGs-code Thank you for the extra information. If you're using Office 365, you'll need an Intune license. If you're still trying to get this to work, or want some guidance, we suggest [get support for Microsoft Intune](https://docs.microsoft.com/mem/get-support) to help find root cause. We can update this article based on any findings.
