### ISSUE TITLE
FIx link to ASP.NET MVC 4.0

### ISSUE THREAD

**Issue by bmilbauer** [MicrosoftDocs/memdocs#1463]
In the section on BitLocker prerequisites, the page states to install the ASP.NET MVC 4.0 redistributable, but links to a page that only has an installer for ASP.NET 4 for Visual Studio, which is a development tool, not the redistributable. This is confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf7e568d-98a0-49a9-89fe-aac009de175a
* Version Independent ID: 67d813c3-cc8f-70b0-16dd-bfdb4363f1c7
* Content: [Plan for BitLocker management - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/protect/plan-design/bitlocker-management)
* Content Source: [memdocs/configmgr/protect/plan-design/bitlocker-management.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/protect/plan-design/bitlocker-management.md)
* Product: **configuration-manager**
* Technology: **configmgr-protect**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @bmilbauer for the feedback. I double-checked with one of our BitLocker experts, Visual Studio isn't required in this instance. I'll add a note to this article for future reference.
