### ISSUE TITLE
Article is not for AE

### ISSUE THREAD

**Issue by fox-on-the-run** [MicrosoftDocs/memdocs#1465]
While we are targeting on Android Enterprise, wouldn't it make sense to add a link to https://docs.microsoft.com/en-us/mem/intune/apps/apps-add-android-for-work 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1db1ab6d-5a57-353e-965b-643546f69501
* Version Independent ID: 5a240f35-587d-c50e-55a1-084979f13235
* Content: [Add Android store apps to Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/store-apps-android?source=docs)
* Content Source: [memdocs/intune/apps/store-apps-android.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/store-apps-android.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@fox-on-the-run Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2480

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @fox-on-the-run Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
