### ISSUE TITLE
Website setup doesn't work with co-hosted SQL https://www.prajwaldesai.com/sccm-bitlocker-management-portal-installer-error/

### ISSUE THREAD

**Issue by bmilbauer** [MicrosoftDocs/memdocs#1467]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b28d3556-29c0-eaad-9855-8fdeb91bad84
* Version Independent ID: 84234954-f695-0c7d-ca04-7474550a455f
* Content: [Set up BitLocker portals - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/protect/deploy-use/bitlocker/setup-websites)
* Content Source: [memdocs/configmgr/protect/deploy-use/bitlocker/setup-websites.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/protect/deploy-use/bitlocker/setup-websites.md)
* Product: **configuration-manager**
* Technology: **configmgr-protect**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
This isn't a common/broad issue, and not for collocated SQL. I checked with our CSS lead for BitLocker management in ConfigMgr, they have seen cases with the same error, but it's usually where the user running the script doesn't have sysadmin rights to SQL, or a typo in the script command line.
