### ISSUE TITLE
Unable to switch WIFI in MHS for Android 10 and 11 due to Google API Change "AddNetworkSuggestions"

### ISSUE THREAD

**Issue by Mobazzar** [MicrosoftDocs/memdocs#1469]
Based on the Article https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-android-for-work#device-experience it says on Corporate Owned Dedicated Devices with MultiApp Kiosk (MHS) scenario Users will be unable to Switch WIFI if the device is connected to a stable network after entering the correct wifi password, this need to be more clarified to add something like that:

Due to the New changes in android API starting from Android 10 and above the function used to switch the WIFI (AddNetwork) is deprecated and its now using (AddNetworkSuggestions) from Endpoint manager Admin can add the list of suggested Networks when the user is connected to a stable network in MHS changing the WIFI manually will not make any change to the current connection unless the connected network is go down or the connection is out of range then the MHS will send the suggestion to the device to switch the WIFI to the new network.

**Comment by MandiOhlinger** [comment]
https://msazure.visualstudio.com/Intune/_workitems/edit/9685944

**Comment by MandiOhlinger** [comment]
@Mobazzar We state that already, so I feel like we're missing something. Please create a pull request (PR) with your recommended text changes. That'll allow us to understand your intent. We review every PR before if it's published.

If you've never created a PR, the steps are at [https://github.com/MicrosoftDocs/memdocs](https://github.com/MicrosoftDocs/memdocs). Just scroll past the folder view.

Thanks!
