### ISSUE TITLE
About Device Lock

### ISSUE THREAD

**Issue by kennethvs** [MicrosoftDocs/memdocs#1472]
[Enter feedback here]

When looking at the configured settings for "Device Lock" in the Windows 10 MDM security baseline for December 2020, I notice the following settings:

Require password: Yes
Required password: Alphanumeric
Password expiration (days): 60
Password minimum character set count: 3
Prevent reuse of previous passwords: 24
Minimum passwrod length: 8
Number of sign-in failures before wiping device: 10
Block simple passwords: Yes
Password minimum age in days: 1
Prevent use of camera: Enabled
Prevent slide show: Enabled

With this MDM security baseline applied I verified on whether these settings are enforced, which is not the case. I can unlock my device with my 6 digit pincode, the pincode doesn't expire as well.

So, what is the expected behavior of these settings? I was always under the impression that all settings in the baseline would be effective and I can also see that the "Required password" setting has been applied successfully, but have now determined that this is not the case, even though the setting reports as successfully applied.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f0f4d5d-fdd1-22e7-6372-9916b199209f
* Version Independent ID: caeb9f8b-30ad-7f02-4740-56522b2f9b1b
* Content: [Intune security baselines settings for Windows 10 MDM - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/security-baseline-settings-mdm-all?pivots=december-2020)
* Content Source: [memdocs/intune/protect/security-baseline-settings-mdm-all.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/security-baseline-settings-mdm-all.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
Still investigating.

**Comment by Brenduns** [comment]
@kennethvs I've an update for you on this which is partial, but possibly of use. I'll be out for about a week so I wanted to pass this on now, not later. Just this morning the Intune engineering team (security baselines) and folks from Windows who own the underlying CSP's that are being configured, worked out what might be going on. Per the Windows folks, The Device Lock CSPs are ignored as regards PINs when the Passport for Work CSP (Window's Hello for Business) is set on the same device. (There are other details in discussion but that might be the crux of what your seeing?)

So that is to say: If the device is managed by Windows Hello policies, you might test removing that policy to see if with only Device Lock policy the results improve. (This only applies to PIN, as Passport for Work policies are not applied to passwords - and should still be set separately.

Once the dust from discussion finally settles, I'll update you and also work up a content update for this. But that won't be until early June.

**Comment by kennethvs** [comment]
Hi Brent,

Thank you for your comment and explanation. For documentation purposes it might be good to document which CSP's get ignored when other CSP's are configured. I haven't seen or found any documentation there yet.

The issue we (as implementation consultants) have is that it's really hard to determine if settings defined in the MEM admin center are being applied to the device that we target them to. That's because the settings in the MEM admin center are being translated into a policy which only contains the CSP settings. On the endpoint there is not way to determine for example where a specific setting is coming from. For this we would actually need like a gpresult substitute but then for MEM giving us an overview of which policies (friendly names from the MEM admin portal) have been applied, where the (possible) conflicts are, and which setting won. For the settings in the security baseline it's undoable to verify whether all the settings are actually applied and cases like this, make me wonder which other settings coming from the baseline are not affective on our endpoints, is this a rare incident or are we talking about a structural issue here?

Thanks again for your effort to get this clear.

/Kenneth

**Comment by Brenduns** [comment]
@kennethvs   Hello Kenneth, There hasn't been any new information on this, but as to your comment about documentation about which CSPs might be ignored when others are configured, I can say that the Intune engineering feature teams are starting to have those conversations and what emerges we expect to see turned into customer facing guidance and best practices. That will take some time and work as they'll need to partner with the Windows teams that own the underlying device configuration CSPs that are involved - and which themselves are don't necessarily make those connections clear. 

As this time I'll go ahead and close this GitHub issue. However, if I overlooked answering a question about the docs that you might still have, let me know as I can reopen this or provide a response even when an issue is closed.

**Comment by sanderdewit** [comment]
any updates on this?
