### ISSUE TITLE
About Retire the noncompliant device

### ISSUE THREAD

**Issue by kennethvs** [MicrosoftDocs/memdocs#1473]
[Enter feedback here]
Retire the noncompliant device currently doesn't mention Windows 10 - while this is working. If configured in the compliance policy the device will end up under "Retire noncompliant devices"

Please update the documentation to reflect this.

Thanks in advance,

Kenneth van Surksum

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2e7ac08-bfd6-9560-ad25-bced9b944822
* Version Independent ID: 6b1f70f0-aed3-52ac-25eb-1de55babc9d0
* Content: [Noncompliant message and actions with Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/actions-for-noncompliance)
* Content Source: [memdocs/intune/protect/actions-for-noncompliance.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/actions-for-noncompliance.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@kennethvs   Thanks Kenneth, I've submitted a doc edit that will add Windows 10 to the list. Not sure how that slipped through for so long.  But no more!  Expect that update to be live in docs later today.
