### ISSUE TITLE
Assignments

### ISSUE THREAD

**Issue by Derrynm70** [MicrosoftDocs/memdocs#1474]
"What is the point of this warning on the assignments page: When excluding groups, you cannot mix user and device groups across include and exclude. Click here to learn more."
When you can only assign to users?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cde34bc-bab0-d412-5971-cbc1f515a486
* Version Independent ID: ac355bba-5f6f-0168-49f3-67b7a2ddb2d4
* Content: [Create and deploy app protection policies - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policies)
* Content Source: [memdocs/intune/apps/app-protection-policies.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-protection-policies.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@Derrynm70 - Thanks for the feedback. I believe this is a message in Intune that is displayed when selecting any assignment, but relates to assigning user and device profiles in Intune. Here's the topic that the link point to:
[Assign user and device profiles in Microsoft Intune](https://docs.microsoft.com/mem/intune/configuration/device-profile-assign#exclude-groups-from-a-profile-assignment)
