### ISSUE TITLE
Site Server Local Admin to Remote Service Connection Point / Site System Installation Account?

### ISSUE THREAD

**Issue by GambitC90** [MicrosoftDocs/memdocs#1479]
I would like some clarification around this section...

I have setup a Remote Service Connection Point and it appears to be working as expected with only having the Site Server with local admin, and no Site System Installation Account.

Can you confirm this should be an OR statement where you need Site Server local admin OR Site System Installation Account?

**********************************************************************************

Remote site system requirements
When you install the service connection point on a site system server that's remote from the site server, configure the following requirements:

The computer account of the site server must be a local admin on the computer that hosts a remote service connection point.

Set up the site system server that hosts this role with a site system installation account. The distribution manager on the site server uses the site system installation account to transfer updates from the service connection point.

**********************************************************************************

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 519cef62-a212-4f56-1b48-5761b186ce6f
* Version Independent ID: 2b9cf41f-3900-387e-72bf-ef96cdf9875f
* Content: [Service connection point - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/about-the-service-connection-point)
* Content Source: [memdocs/configmgr/core/servers/deploy/configure/about-the-service-connection-point.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/deploy/configure/about-the-service-connection-point.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @GambitC90 for the feedback. Yep, it's an OR. I'll revise now.
