### ISSUE TITLE
Co-Management Azure Premium Requirement Clarification

### ISSUE THREAD

**Issue by bryandam** [MicrosoftDocs/memdocs#148]
At MMS Jazz David James confirmed that Azure Premium (P1) is not a requirement for co-management.  It's a requirement for 'four features' of co-management but I don't think he could remember all four and I certainly don't remember all four and promised updated docs surrounding this.

Assuming he wasn't lying, can we get that clarified here or point me to the clarifying docs?
   Thanks,
       Bryan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f61451a-aad4-f7c3-d52b-03e8422cccb2
* Version Independent ID: 5c80c81e-3da8-9d62-d9c4-23b0cf77bfe2
* Content: [Co-management for Windows 10 devices - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/comanage/overview)
* Content Source: [memdocs/configmgr/comanage/overview.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/comanage/overview.md)
* Product: **configuration-manager**
* Technology: **configmgr-comanage**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
I clarified with Bryan offline. At this time, AADP is a requirement for co-management, because MDM auto-enrollment is a requirement. Until I revise this article, for more info see MicrosoftDocs/SCCMDocs#2221
