### ISSUE TITLE
WQL Equivalent Queries

### ISSUE THREAD

**Issue by kaiserschloss** [MicrosoftDocs/memdocs#1480]
Are there WQL queries equivalent to the provided SQL queries that can be used for collection membership?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 487a9587-702f-ab98-a65b-4f7980bb5b0a
* Version Independent ID: c0c3cad7-4307-b49d-c955-c46f4d39c9a6
* Content: [Sample queries for compliance settings - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/develop/core/understand/sqlviews/sample-queries-compliance-settings-configuration-manager)
* Content Source: [memdocs/configmgr/develop/core/understand/sqlviews/sample-queries-compliance-settings-configuration-manager.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/develop/core/understand/sqlviews/sample-queries-compliance-settings-configuration-manager.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @kaiserschloss, this section is specific to SQL Views for reporting, so they are all SQL queries. It might be possible to achieve the same with a WQL query, but I don't know for certain. You might try asking on [Configuration Manager forums](https://docs.microsoft.com/answers/products/mem). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
