### ISSUE TITLE
RSS inactive and not working

### ISSUE THREAD

**Issue by sfarnik** [MicrosoftDocs/memdocs#1481]
Hello Erik,

Both RSS feeds for `What's new' and `Features in Development' are inactive for month and not working.
eg in Feedly I see that both have their latest article 29 or 25 month ago.

Would be appreciated if those feeds are coming again.
thanks, Stefan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d16c28db-1e8e-31fa-6127-3050a2940422
* Version Independent ID: 4cf9a244-1ae5-1637-48f7-3f503d400da6
* Content: [What's new in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new)
* Content Source: [memdocs/intune/fundamentals/whats-new.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/whats-new.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by aczechowski** [comment]
Thanks for the feedback. We've received other feedback on this issue. I'm making a change to remove the example and point back to [How to use the docs](https://docs.microsoft.com/mem/use-docs#notifications), which has more explanation. I'm hoping that some variation on the query string will work.

If it _still_ doesn't work, we'll just need to remove the tip to get notified. The RSS functionality comes from the docs.ms platform (we can promote the issue to that team if needed), and obviously we don't know what sort of RSS application you're using. Unfortunately docs.ms doesn't offer another option for notification. 😞
