### ISSUE TITLE
Missing "/usepkicert"

### ISSUE THREAD

**Issue by MaikKoster** [MicrosoftDocs/memdocs#1483]
If you are using a PKI issued computer certificate for authentication of the client, make sure to add "/usepkicert" to the command line arguments, as otherwise ConfigMgr client installation starting with version 5.0.9049.x (2103) might fail. It would be helpful to have a note in this documentation about this specific argument.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 875e279b-9029-d1e5-8a6c-0e93ce38ddba
* Version Independent ID: 80bc34d7-3ef7-1c4f-da41-0474b1c5f4a4
* Content: [Co-manage internet-based devices - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/comanage/how-to-prepare-win10)
* Content Source: [memdocs/configmgr/comanage/how-to-prepare-Win10.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/comanage/how-to-prepare-Win10.md)
* Product: **configuration-manager**
* Technology: **configmgr-comanage**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @MaikKoster, we had some internal discussion with Jeffrey and the devs, and generally decided not to make changes, as we want to encourage customers to use Azure AD authentication if it's present.

But I do think there's some clarity that I can make to include some additional detail to help customers in the future.
