### ISSUE TITLE
Location awareness in Windows 10?

### ISSUE THREAD

**Issue by Pickell** [MicrosoftDocs/memdocs#1484]
For the entry:
Locate device remote action for Windows 10 devices
You'll be able to use a new locate device remote action to get the geographical location of a device. Supported devices include:

Windows 10 version 20H2 (10.0.19042.789) or later
Windows 10 version 2004 (10.0.19041.789) or later
Windows 10 version 1909 (10.0.18363.1350) or later
Windows 10 version 1809 (10.0.17763.1728) or later
To see the new action, sign in to the Microsoft Endpoint Manager admin center and choose Devices > Windows > choose a Windows 10 > Locate device.

This action will work in a similar manner as the current Locate device action for Apple devices (but will not include any lost mode functionality).

Question:
Does this mean that there will be embedded location awareness on enrolled Windows 10 devices? Can this be leveraged to set the proper Time Zone on the device via a Config policy? Or a PowerShell script?  This is currently a challenge during our Autopilot configuration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66f915d1-8486-44dc-a605-280f979d6f9b
* Version Independent ID: 23c6b2c3-64c1-2df3-ad51-d9be083871a1
* Content: [In development - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/in-development)
* Content Source: [memdocs/intune/fundamentals/in-development.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/in-development.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
9694127

**Comment by ErikjeMS** [comment]
@Pickell The PM responded with "This feature does not enable ongoing tracking of device locations. It is a manual, one time pull each time the command is executed." If this doesn't answer your question, let me know and I'll reopen this issue.
