### ISSUE TITLE
This page as all other pages I have visited in the last few months, lacks information on how to create a support ticket with Microsoft.

### ISSUE THREAD

**Issue by rvoj** [MicrosoftDocs/memdocs#149]
I have been banging my head against the wall for several months on how to create a boot image in SCCM with version 18362.418.
The installed ADK and it's WinPE plugin is not updated, it's at version 18362.1.
This boot image does not boot on VMWare, so it's impossible for us to test Task Sequences with VMWare clients.
It just freezes on the Windows logo without any error message.
According to a post on Reddit, the fix is to upgrade the boot image to version 18362.418, but I'm unable to find a method to do this within SCCM.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9c165c0-acf3-96fd-0e25-963c0b4a28a0
* Version Independent ID: 5a6b4ca0-d281-f06d-ea7e-e78962c35d59
* Content: [Support Center - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/support/support-center)
* Content Source: [memdocs/configmgr/core/support/support-center.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/support/support-center.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @rvoj I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

For example, when you go to the Microsoft Support page linked above, you could select options such as:
![image](https://user-images.githubusercontent.com/26784733/80263659-2aac7780-8646-11ea-87f0-6becc62a0914.png)
On page 2, describe the problem. On page 3, you select or add a support plan. Continue through the wizard to submit.

I'm closing this issue as there's nothing actionable for docs at this time.
