### ISSUE TITLE
Page Microsoft Intune fundamentals have a duplicate links

### ISSUE THREAD

**Issue by foolishhare** [MicrosoftDocs/memdocs#1493]
On page https://docs.microsoft.com/en-us/mem/intune/fundamentals/ there are two duplicated links to https://docs.microsoft.com/en-us/mem/intune/fundamentals/tutorial-walkthrough-endpoint-manager.
![image](https://user-images.githubusercontent.com/14123319/114013519-4cf7cf00-9870-11eb-88a5-e12ee9033748.png)

**Comment by foolishhare** [comment]
Link to "Walkthrough Intune in the Azure portal" the same as "Walkthrough Intune in Microsoft Endpoint Manager"

**Comment by Erikre** [comment]
@foolishhare - Thanks for the feedback. I believe I retired the older walkthough, but didn't remove the above link. Appreciate the help. I'm updating this page now. Thanks
