### ISSUE TITLE
clarify "limited to single partner per platform"

### ISSUE THREAD

**Issue by jkulir** [MicrosoftDocs/memdocs#1494]
On the page, plese clarify this statement:
"
You're limited to a single partner per platform, even if you have added multiple compliance partners to Azure AD.
"

Does this mean that once first 3rdparty compliance partner is integrated (example: IBM MaaS360), the whole tenant needs to use this partner only and cannot use another, such as JAMF?

thanks for reply

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81bcb445-ada9-e2e3-d8a8-a5693a5a3850
* Version Independent ID: 6214bb16-5087-c21c-fd43-d5f0a6f405c1
* Content: [Device compliance partners in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/device-compliance-partners)
* Content Source: [memdocs/intune/protect/device-compliance-partners.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/device-compliance-partners.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@jkulir       Thanks for your question.  The _single partner per platform_ means that Intune supports use of only one compliance partner for each device platform type.  So, that's a single partner for all your Android devices, and a single partner for all of your macOS devices, and so on.  Intune doesn't support using one partner on some of your Android devices while using a second partner for a different group of Android devices in the same Intune tenant.  

You can use a different compliance partner for different platforms however. So you might use VMware for Android  while using JamfPro for macOS, or Citrix for iOS.  What isn't supported would be to set up both VMware and Citrix Workspace for your Android devices.

**Comment by jkulir** [comment]
Thank you for the answer.

In that case we will need to rely on "registered app" instead of "device compliance" for conditional access, since our case involves multiple sister companies in one Tenant and only one company wants the MDM.
