### ISSUE TITLE
Import-Module Steps Missing in Docs

### ISSUE THREAD

**Issue by thetechgy** [MicrosoftDocs/memdocs#1495]
The code provided isn't complete and assumes you know that you need to complete the steps below between the code blocks for 'Install-Module' and 'Connect-MSGraph'. Between those I believe the following PowerShell commands are missing:

```
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned
Import-Module AzureAD
Import-Module WindowsAutopilotIntune
Import-Module Microsoft.Graph.Intune
```

And then once they complete the steps, they probably want to go back and revert their PS execution policy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cb0ab9e-0902-8c43-5cb9-8ade31c88f5f
* Version Independent ID: d30aebff-dc9c-bcd9-2ffd-c7158da55026
* Content: [Windows Autopilot Deployment for existing devices](https://docs.microsoft.com/en-us/mem/autopilot/existing-devices)
* Content Source: [memdocs/autopilot/existing-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/existing-devices.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by aczechowski** [comment]
Thanks @thetechgy for the feedback. In talking with the engineers about this, from Powershell 3.0 and up, it implicitly imports the module once a function is invoked. But yes, Import after Install is required to load the module into memory. So I'll add those import statements.

I don't think you should need to change execution policy, unless you are running this as a script (but then you wouldn't do that inside the script, but before you run the script). So I'm not going to include that one.
