### ISSUE TITLE
Stale link to Citrix documentation.

### ISSUE THREAD

**Issue by vinaykothiyal** [MicrosoftDocs/memdocs#1498]
The link to Citrix documentation in this document are pointing to old version that have been archived. Could you please update the links with text "Integrate NetScaler with Intune for NAC" and "Integrate Citrix NetScaler with Intune" to point to following document? It should stay current all the time.
https://docs.citrix.com/en-us/citrix-gateway/current-release/microsoft-intune-integration/configuring-network-access-control-device-check-for-citrix-gateway-virtual-server-for-single-factor-authentication-deployment.html

Thanks,
Vinay

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c4b9bdf-975f-6116-51cc-08b29431ebbc
* Version Independent ID: 8a82d44e-4535-27a9-63d4-ab9612f30d64
* Content: [Network access control integration with Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/network-access-control-integrate#:~:text=NAC%20solutions%20check%20the%20device%20enrollment%20and%20compliance,for%20enrollment%2C%20or%20for%20a%20device%20compliance%20check.)
* Content Source: [memdocs/intune/protect/network-access-control-integrate.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/network-access-control-integrate.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@vinaykothiyal   
Thanks for the updated link destination. I've submitted a content edit that will publish that later today. 

In the future, if you'd like to submit a PR yourself, and get an attribution for contributing to the docs directly, read our  **[Contributor guide](https://docs.microsoft.com/contribute/)** to learn how.  We always appreciate the assist in keeping docs current and accurate from our community of readers.
