### ISSUE TITLE
We should be calling out that URIs need to be unique.  

### ISSUE THREAD

**Issue by CJRicard** [MicrosoftDocs/memdocs#1499]
We should be calling out that URIs need to be unique.  See active case number: 25060990 for details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73637c76-0466-8a0f-f614-c5ef3607d4a4
* Version Independent ID: 15fd3771-a7f3-f233-51bd-0be30cd0a020
* Content: [Configure Azure AD for CMG - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/configure-azure-ad)
* Content Source: [memdocs/configmgr/core/clients/manage/cmg/configure-azure-ad.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/cmg/configure-azure-ad.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @CJRicard, in the mention of the **App ID URI** value, that's the first sentence. 😄 

> App ID URI: This value needs to be unique in your Azure AD tenant.

I'm closing this issue, but let me know if I'm missing something

**Comment by CJRicard** [comment]
Sorry if I missed it!
