### ISSUE TITLE
Can Microsoft 365 Business Premium use the preview Intune "Windows 10 feature updates policy"?

### ISSUE THREAD

**Issue by felinepc** [MicrosoftDocs/memdocs#1500]
The documentation says:

In addition to a license for Intune, your organization must have one of the following subscriptions:
 
- Windows 10 Enterprise E3 or E5 (included in Microsoft 365 F3, E3, or E5)
- Windows 10 Education A3 or A5 (included in Microsoft 365 A3 or A5)
- Windows Virtual Desktop Access E3 or E5

It doesn't mention M365 Business Premium. However, all Windows AutoPilot provisioned Windows 10 machines with the Microsoft 365 Business Premium license do show "Windows 10 Enterprise" under Windows settings. Additionally, Microsoft 365 Business Premium does include Windows Virtual Desktop.

Also, if a license requirement is met, will there any kind of warning/status available? Currently this is not available in Intune.

Clarifications here would be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee0dbbde-b15e-4adf-b162-1114fddd8846
* Version Independent ID: 78275b5f-4d5b-f318-0cbf-a27ad35dffa0
* Content: [Configure Windows 10 feature updates policy in Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/windows-10-feature-updates)
* Content Source: [memdocs/intune/protect/windows-10-feature-updates.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/windows-10-feature-updates.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@felinepc   Thanks for your submission. _Microsoft 365 Business Premium_ should be listed and I've submitted a content update to add that, which will go live later today.  

As to when a license requirement is or isn't met -  Intune doesn't have a mechanism to identify or to surface to the Admin in the Microsoft Endpoint Manager admin center.   That might be a great feature enhancement to build in by providing device specific status or awareness via reports as to which devices do or don't meet assessable prerequisites for specific features.  I encourage you to submit this product ask directly to the engineering team via the  [Intune User Voice](https://microsoftintune.uservoice.com/forums/291681-ideas) forum.
