### ISSUE TITLE
Management of SQL/Linux only via Azure Management?

### ISSUE THREAD

**Issue by LindaLF** [MicrosoftDocs/memdocs#1505]
Is it true that as this page states "_After Configuration Manager 1810, customers should consider **_Microsoft Azure Management_** for managing Linux servers_."  I would have thought that perhaps **System Center Operations Manager** [SCOM] might be used, as there is a management pack for LINUX with SCOM, but that isn't mentioned.
https://www.microsoft.com/en-us/download/details.aspx?id=58208

Perhaps this is a typo?  I am not sure I would want to use Azure to manage an on-premisis environment yet.

Regards,
Linda A. Lorentz Fletcher

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db61e072-89f3-4858-28cb-9be2b1199a06
* Version Independent ID: d05107c8-92fb-40d5-ef62-974ba92d331a
* Content: [New version 1802 - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/changes/whats-new-in-version-1802?source=docs)
* Content Source: [memdocs/configmgr/core/plan-design/changes/whats-new-in-version-1802.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/changes/whats-new-in-version-1802.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @LindaLF, not a typo, our primary recommendation is to use Azure to manage Linux devices. SCOM can _monitor_ Linux devices, but I don't think it has the full scope of management capabilities that exist in Azure.
