### ISSUE TITLE
Incorrect ----- dsergcmd /status 

### ISSUE THREAD

**Issue by yunwa** [MicrosoftDocs/memdocs#1506]
[Enter feedback here]

correct one: **dsregcmd /status** 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c3725e1-17a8-3e43-8912-cdfa8322b532
* Version Independent ID: 3f777863-e1c9-c0c7-3762-0bbae61b86ab
* Content: [Azure AD authentication workflow - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/azure-ccmsetup)
* Content Source: [memdocs/configmgr/core/clients/manage/azure-ccmsetup.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/azure-ccmsetup.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @yunwa for catching that typo, I've fixed it
