### ISSUE TITLE
_SMSTSMPCerts missing

### ISSUE THREAD

**Issue by chboeye** [MicrosoftDocs/memdocs#1508]
It seems this variable is missing from the list, could not find any documentation, even internally. Only a quick reference to it. Any idea of what it is?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d19a7bae-9409-05b3-96d1-409dd2cb0946
* Version Independent ID: 5dcc1789-cea0-fdba-bb36-2769730f8f78
* Content: [Task sequence variable reference - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/osd/understand/task-sequence-variables)
* Content Source: [memdocs/configmgr/osd/understand/task-sequence-variables.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/osd/understand/task-sequence-variables.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @chboeye, there are a lot of TS variables that aren't documented. Many of them are for internal use, with little to no use for customers. I think this one falls into that category. On first glance, it looks like maybe a certificate thumbprint. So I'm going to close this issue. But let me know if you think there's a good reason why we need to document this.
