### ISSUE TITLE
Tally with Windows 10 CSP items?

### ISSUE THREAD

**Issue by icelava** [MicrosoftDocs/memdocs#151]
Is the point of this page to declare that out of the 41 available settings in Windows 10,
https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-defender
Intune can only handle 27?

For the matter, it doesn't tally either with the **Microsoft Defender Antivirus** section of Device restrictions in Intune.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b84f6130-b993-bd26-0147-29748c3b7449
* Version Independent ID: 231c5984-ee21-059b-22d4-21b2f009124e
* Content: [Windows 10 Antivirus policy settings for Microsoft Defender Antivirus for Intune](https://docs.microsoft.com/en-us/mem/intune/protect/antivirus-microsoft-defender-settings-windows)
* Content Source: [memdocs/intune/protect/antivirus-microsoft-defender-settings-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/antivirus-microsoft-defender-settings-windows.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by icelava** [comment]
Neither is this in sync with https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-windows-10#microsoft-defender-antivirus

**Comment by Brenduns** [comment]
@icelava   Thanks for your feedback. This reference article is for *Antivirus* policy, which is a focused security policy available in the Endpoint security node. It's distinct from *Device Restriction* and other policy types.

Content about the Endpoint security node is pending, and when that goes live, there will be a bit more background on this, including cross article links. For the information that’s available today, see [this entry in the What’s New article](https://docs.microsoft.com/mem/intune/fundamentals/whats-new#use-a-preview-of-security-administrator-focused-policies-as-part-of-endpoint-security) from a few weeks ago.

**Comment by icelava** [comment]
Gosh it took me a long time to discover that Endpoint security is not the same as the Endpoint protection configuration profile. (Always had the left menu pane shrunk to icons only.) There's still a long way to go for providing clear terminology for products and features.

So the direction going forward is to not use Microsoft Defender Antivirus section in Device restrictions?

**Comment by Brenduns** [comment]
@icelava  The policy type to use probably depends on your specific needs. The policies in the Endpoint Security node are more focused - as in limited - to specific settings for specific tasks and intended to give the _Security Admin_ persona a single location where they can address specific actions and configurations they typically manage.

 If you use co-management, then the Antivirus policy _should_ be used: 

- The Microsoft Defender Antivirus profile is a separate instance of the antivirus settings found in the Device Restriction profile for Device Compliance policy.

- Unlike the antivirus settings in a Device Restriction profile, you can use these settings to with devices that are co-managed. To use these settings, the co-management workload slider for Endpoint Protection must be set to Intune.

**Comment by icelava** [comment]
If by "co-management" you mean on-premise hybrid AD and SCCM, no we do not have that. Ours is purely Office 365, AAD, and Intune.

But at this point, Intune alone is presenting confusing fragments of UIs making it difficult to know which type of config will be the "winner" when there are multiple avenues to control a given settings.

For example with regards to SmartScreen, I've to date encountered _five separate avenues_ to configure it, and they don't afford clear differentiation between SmartScreen for Edge, or SmartScreen for Windows (Explorer) in general, how their jurisdictions overlap or don't overlap, or the order of precedence between the configuration profile types. Also, some can enforce the settings (greyed out) in Windows client, and some don't. It takes plenty of grass-tossing to figure out exactly where the wind blows.
