### ISSUE TITLE
Hardened UNC Path Invalid Input "-"

### ISSUE THREAD

**Issue by danbu** [MicrosoftDocs/memdocs#1512]
When attempting to enter a "Server Path" with "-" in it the UI gives a "Invalid Input" error

(admin edit: add article metadata for proper tracking)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f0f4d5d-fdd1-22e7-6372-9916b199209f
* Version Independent ID: caeb9f8b-30ad-7f02-4740-56522b2f9b1b
* Content: [Intune security baselines settings for Windows 10 MDM - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/security-baseline-settings-mdm-all?pivots=mdm-december-2020)
* Content Source: [memdocs/intune/protect/security-baseline-settings-mdm-all.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/security-baseline-settings-mdm-all.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by ErikjeMS** [comment]
@danbu Which articled are you asking about here?

**Comment by danbu** [comment]
Sorry thought it linked to the page when I reported - https://docs.microsoft.com/en-us/mem/intune/protect/security-baseline-settings-mdm-all?pivots=mdm-december-2020

**Comment by Brenduns** [comment]
@danbuf  Thanks for this question. I wanted to get you and update.  The product group is still investigating this. The correct Windows CSP for this is setting is @ https://docs.microsoft.com/windows/client-management/mdm/policy-csp-connectivity?WT.mc_id=Portal-fx#connectivity-hardeneduncpaths, which doesn't list a character limitation for hyphens. However, this CSP is tied to ADMX policy, for which there might be a bug on hyphens. That's what is being looked into now. Once we have more information to share, I'll update this feedback channel.

**Comment by danbu** [comment]
Great thanks for the follow up good there is a work around most things are going in the Settings Catalog now anyway.
