### ISSUE TITLE
Clarification on Client Install Options/Client Push Support for CMG

### ISSUE THREAD

**Issue by AdamGrossTX** [MicrosoftDocs/memdocs#1514]
The table on this page shows that several client install methods that are supported including automatic client upgrades but calls out Client Push as not supported.  Can you provide any additional information about this? 

Example:  If I attempt a client push to existing CMG/Internet-Based clients following a site upgrade, will the client push cause the existing clients to break, or will it just fail to contact the device to perform the upgrade? My guess is that the push will fail from the server side since it may not be able to contact the devices since they are on the internet.

And how does this compare to the Automatic Client Upgrade feature that is listed as supported? Does that work since it's client initiated, vs server push?

My main concern is that I regularly attempt client push installations to repair clients or install new clients post site upgrade and I want to ensure that the push won't cause the client to get into an unsupported state if the client is connected to the CMG.

https://docs.microsoft.com/en-us/mem/configmgr/core/clients/deploy/deploy-clients-to-windows-computers#BKMK_ClientPush

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86c2d9b9-2c17-ec9b-ea1f-9965167bae38
* Version Independent ID: 873b1b0f-6e38-32d3-8109-59cab914f774
* Content: [Supported configurations for CMG - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/supported-configurations)
* Content Source: [memdocs/configmgr/core/clients/manage/cmg/supported-configurations.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/cmg/supported-configurations.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
It's unsupported because the site server requires access to the client that it can't get via CMG. E.g., I think it needs access to the admin$ share and remote WMI as well. Auto upgrade is client talking to MP over HTTPS, so that's why it works over CMG. So you can try client push to a client that's over CMG, but it will fail because it won't be able to communicate with it.
