### ISSUE TITLE
link doesn't goto right place 

### ISSUE THREAD

**Issue by brendanmain** [MicrosoftDocs/memdocs#1515]
this link https://gallery.technet.microsoft.com/Intune-deployment-planning-fae156c2 for the following doesn't goto right place anymore This template is also available to download at Intune deployment planning, design, and implementation - Table templates.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be85a977-5f68-8336-b1f9-87f6ab44c31c
* Version Independent ID: 0264b998-409d-69bc-86ab-a494a39f6a4e
* Content: [Planning guide to move to Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/fundamentals/intune-planning-guide#personal-devices-vs-organization-owned-devices)
* Content Source: [memdocs/intune/fundamentals/intune-planning-guide.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/intune-planning-guide.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@brendanmain Good catch! With the TechNet Gallery being removed, this download slipped passed us. It's now available on the Download Center - https://www.microsoft.com/download/details.aspx?id=103005.

The link in the article is updated. The changes should be live later today. Thank you!
