### ISSUE TITLE
Update new versions for standard users

### ISSUE THREAD

**Issue by icelava** [MicrosoftDocs/memdocs#152]
When the Chromium-based version has already been deployed (via Intune) to computers of standard users, are they able to manually update the version themselves? (Settings &gt; About Microsoft Edge), or does the app definition in Intune regularly get re-pushed to their computers for new versions?

So far it appears to be up-to-date on my test VM, but it does not report the release dates of each version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d593916-e493-8120-2f18-6c32c5cc31d0
* Version Independent ID: ca4bcd19-5783-8a69-6fd4-cc5270403411
* Content: [Add Microsoft Edge for Windows 10 to Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-windows-edge?toc=https%3A%2F%2Fdocs.microsoft.com%2FDeployEdge%2Ftoc.json&bc=https%3A%2F%2Fdocs.microsoft.com%2FDeployEdge%2Fbreadcrumb%2Ftoc.json)
* Content Source: [memdocs/intune/apps/apps-windows-edge.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/apps-windows-edge.md)
* Service: **microsoft-intune**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@icelava -  Automatic updates of Microsoft Edge are On by default. If you have additional questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

This question is in our documentation feedback channel and it may be best to handle this question as a support request. For this reason, I'm closing this issue. Please use the above channels if you don't already have a solution.
