### ISSUE TITLE
Wording update

### ISSUE THREAD

**Issue by zlDev** [MicrosoftDocs/memdocs#1520]
Instead of saying

"Simple passwords: Yes blocks simple passwords..."

should say

"**Block** simple passwords: Yes blocks simple passwords..."

to reflect how the control is named in the device restrictions profile.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88932dd8-abce-bf23-9624-1df5f60a946d
* Version Independent ID: ab2d932f-e375-2485-a6e5-e02daf7a27c4
* Content: [iOS/iPadOS device settings in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-ios)
* Content Source: [memdocs/intune/configuration/device-restrictions-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/device-restrictions-ios.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@zlDev Thank you! I updated the text. The changes should be live later today.

FYI - You can make changes like this yourself. We want and encourage community contributions to the documentation. If you're unsure of how to update an article, go to [https://github.com/MicrosoftDocs/memdocs](https://github.com/MicrosoftDocs/memdocs), and scroll past the folder view. The steps are listed.
