### ISSUE TITLE
adminservice: removing UserMachineRelationship

### ISSUE THREAD

**Issue by StoffePro** [MicrosoftDocs/memdocs#1526]
Hello. I'm synchronizing primary users in SCCM with data from another system, and would like to rewrite this job to use the adminservice instead of using CIM and the SCCM commandlets. However, there is one detail I can't find in the official documentation, or anywhere on the net.

The method to call is SMS_UserMachineRelationship.RemoveType, but as we see, this method doesn't take a RelationshipResourceID

```
<Action Name="RemoveType" IsBound="true"><Parameter Name="bindingParameter" Type="AdminService.SMS_UserMachineRelationship" />
<Parameter Name="TypeId" Type="Edm.Int64" />
<ReturnType Type="Edm.Intand32" />
</Action>

```

..so this needs to be called from the correct instance, I guess? Normally I would retrieve the instance by GETing `https://ServerFQDN/AdminService/wmi/SMS_UserMachineRelationship(<RelationshipResourceID>)`, but this doesn't seem to work with the POST method. Here's my actual attempt and result (redacted, of course):

```
PS C:\> $headers

Name                           Value
----                           -----
Content-Type                   Application/json

PS C:\> $bodyrem
{
  "TypeId": 1
}
PS C:\> Invoke-RestMethod -Method Post "https://ServerFQDN/AdminService/wmi/SMS_UserMachineRelationship(25178589).RemoveType" -UseDefaultCredentials -Headers $headers -Body $bodyrem
Invoke-RestMethod: {"error":{"code":"404","message":"Bad Request - Error in query syntax."}}
```

What am I not getting?  It would be great if the documentation could clarify this. Even if the answer is no.

This is the relevant file, I guess: https://github.com/MicrosoftDocs/memdocs/blob/9bb349fc443e17c444fbced16c704c3d7d40e873/memdocs/configmgr/develop/adminservice/usage.md

(admin edit: adding article metadata for proper tracking)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4eed1add-4e7a-1103-2dcd-2f20c3dc6ad9
* Version Independent ID: 025e21a1-28ed-8a7c-422f-fa2293a65751
* Content: [How to use the admin service - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/develop/adminservice/usage)
* Content Source: [memdocs/configmgr/develop/adminservice/usage.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/develop/adminservice/usage.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @StoffePro, I was about to close this and suggest you ask in the forums, but was able to get a quick response from one of the devs:

> instead call this method using URI `https://ServerFqdn/AdminService/wmi/SMS_UserMachineRelationship(<RelationshipId>)/AdminService.RemoveType`

If that works, I'd like to get it added to this article as a functional example. You can either [contribute it yourself](https://docs.microsoft.com/mem/use-docs#contribute), or let me know and I'll take care of it at some point.

If it that doesn't work...I suggest one of the following options for further assistance:
- Post on [Configuration Manager forums](https://docs.microsoft.com/answers/products/mem). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

**Comment by StoffePro** [comment]
Thank you, the suggested method did indeed work. I can add a paragraph about it to the docs.
