### ISSUE TITLE
Error in text? Semi-Annual channel has a six month deferral

### ISSUE THREAD

**Issue by g7cnp** [MicrosoftDocs/memdocs#1527]
Under the Servicing channel option this page states the Semi-Annual channel has a six month deferral, and devices will install updates six months after release!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401fe085-6254-6dbb-24c6-7e6fe56d0f3a
* Version Independent ID: 774ae4fb-b28e-1fb3-46d9-5802c0e4ac6c
* Content: [Windows for Business Update settings for  Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/windows-update-settings)
* Content Source: [memdocs/intune/protect/windows-update-settings.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/windows-update-settings.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@g7cnp  Thanks for asking about this text.  That statement appears to be part of a broken example that isn't complete, and isn't necessary anymore.    After investigating this, I'll be removing that short paragraph example, as its not relevant as there isn't a deferral for the channel.  I'll also add in a new link to some Windows documentation about the different servicing channels to provide more insight to the following list of channels, @ https://docs.microsoft.com/windows/deployment/update/get-started-updates-channels-tools#servicing-channels

That content update should go out later today.
