### ISSUE TITLE
Include mention to select different subscriptions using the Change Directory feature

### ISSUE THREAD

**Issue by maicon-strapasson** [MicrosoftDocs/memdocs#1528]
By enabling Diagnostic settings Azure integration in Intune, you might not see the desired subscription when selecting, for instance, to send information to Log Analytics.

You might need to click on the logged user icon (top right corner) and select "Switch directory", to then enable to subscription you want to use, so it can be selected.

Please add this information in the Intune documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1cee1ad-3f38-5bde-09a3-32742d8d39cd
* Version Independent ID: bf4cf7d8-e162-80ec-98b0-e46b452e44cb
* Content: [Route logs to Azure Monitor using Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/fundamentals/review-logs-using-azure-monitor)
* Content Source: [memdocs/intune/fundamentals/review-logs-using-azure-monitor.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/review-logs-using-azure-monitor.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@maicon-strapasson That's good info to add. Thank you. It'd be great if created a pull request (PR) with your recommended changes. The steps to create a PR are listed at [https://github.com/MicrosoftDocs/memdocs](https://github.com/MicrosoftDocs/memdocs). Just scroll past the folder view.

**Comment by MandiOhlinger** [comment]
Doc changes should be live later today.
