### ISSUE TITLE
Populate the the super peer cache with a Task Sequence

### ISSUE THREAD

**Issue by nclinch** [MicrosoftDocs/memdocs#153]
https://deploymentresearch.com/pre-caching-content-for-p2p-in-a-configmgr-environment/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dd8d1df-2db9-b8bf-56dc-c62b4e248e30
* Version Independent ID: c6163b43-306b-db86-c3e2-4b86292ab877
* Content: [Client Peer Cache - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/hierarchy/client-peer-cache#feedback)
* Content Source: [memdocs/configmgr/core/plan-design/hierarchy/client-peer-cache.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/hierarchy/client-peer-cache.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @nclinch, can you elaborate on this feedback? I'm not sure what action you're suggesting we take.

**Comment by aczechowski** [comment]
I'm not sure what this feedback is, so I'm closing the issue. If you can elaborate, please reopen the issue.
