### ISSUE TITLE
Remove 'never expiring' option from docs

### ISSUE THREAD

**Issue by madansr7** [MicrosoftDocs/memdocs#1530]
We recently removed the option to set never expiring credentials in Azure AD app registration portal. The following lines need to be removed from the doc: https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/changes/whats-new-in-version-2010#additional-options-when-creating-app-registrations-in-azure-active-directory. 

**Lines to remove:**
"Additional options when creating app registrations in Azure Active Directory
You can now specify Never for the expiration of a secret key when creating Azure Active Directory app registrations. For more information about creating app registrations, see Configure Azure Services."

**Comment by madansr7** [comment]
fyi @mestew @aczechowski

**Comment by madansr7** [comment]
The following doc (https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/azure-services-wizard#create-server-application-dialog) also requires an update to remove "Starting in Configuration Manager version 2010, you can specify Never for the expiration of a secret key. The field is called Secret Key validity period, but specifying Never sets the secret key to never expire."

**Comment by aczechowski** [comment]
Hi @madansr7, will followup via email with feature team
