### ISSUE TITLE
Log Analytics Role Requirement

### ISSUE THREAD

**Issue by saderemipcgus** [MicrosoftDocs/memdocs#1531]
Has the Log Analytics Role Requirement for the MALogAnalyticsReader service principal changed to "Log Analytics Reader" from "Reader"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a33ce77-d953-4b87-933e-d36390a7bf45
* Version Independent ID: 165847fd-38dd-31ac-877d-3432fcd5cd48
* Content: [Troubleshoot Desktop Analytics - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/desktop-analytics/troubleshooting#bkmk_MALogAnalyticsReader)
* Content Source: [memdocs/configmgr/desktop-analytics/troubleshooting.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/desktop-analytics/troubleshooting.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
What we have documented is still technically accurate:
![image](https://user-images.githubusercontent.com/26784733/115318236-384ded80-a132-11eb-8314-7ff793db5728.png)

There are a few minor tweak to other wording in the workflow that I'll revise, though.
