### ISSUE TITLE
If you also use the Install Company Portal with VPP option below

### ISSUE THREAD

**Issue by bleek00** [MicrosoftDocs/memdocs#1532]
In this section https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-macos#create-an-apple-enrollment-profile
it says: ״If you also use the Install Company Portal with VPP option below״ 

that's not applicable for macOS (only for iOS and iPadOS) and there is no "....option below" as state in this article.

it seems that you copy and paste from the iOS/iPad article but didn't edited it correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0319ece7-6b1f-d737-618c-778d3f196313
* Version Independent ID: 20b5b39e-56e2-d88e-e4b2-22a79b5d3ccb
* Content: [Enroll macOS devices - Apple Business Manager or Apple School Manager](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-macos)
* Content Source: [memdocs/intune/enrollment/device-enrollment-program-enroll-macos.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/device-enrollment-program-enroll-macos.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@bleek00 Yes, that was a cut and paste error. I'll fix it. Thanks!
