### ISSUE TITLE
operatingSystemVersion property missing. 

### ISSUE THREAD

**Issue by AbfSailor** [MicrosoftDocs/memdocs#1534]
I noticed the operatingSystemVersion property is not listed on this page. Was the property depreciated or is it just missing from the page?

I'm on SCCM Current Branch 2010 and I'm looking at the SQL database.  dbo.v_R_System and I see the property of 'operatingSystemVersion' listed. We're experiencing some issues and they are potentially related to this property; that's what led me to investigate this. 

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93005875-faf2-8b7f-5f7d-7de3cbde3f99
* Version Independent ID: bf8a6e1f-e7d8-26f8-5b02-54f1aa4e5c82
* Content: [SMS_R_System Class - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/develop/reference/core/clients/manage/sms_r_system-server-wmi-class)
* Content Source: [memdocs/configmgr/develop/reference/core/clients/manage/sms_r_system-server-wmi-class.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/develop/reference/core/clients/manage/sms_r_system-server-wmi-class.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @AbfSailor for the feedback. The ConfigMgr SDK is an area in which we're not actively investing beyond basic maintenance and some new functionality. If you'd like to submit a change for this issue, see [How to contribute](https://docs.microsoft.com/mem/use-docs#bkmk_contribute). 

It's most likely the it's a newer property that hasn't been added to this article. I have one resource that I'll do a quick check for questions like these, and I wasn't able to find more information in this context.

I’m sorry that you’re having problems. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://docs.microsoft.com/answers/products/mem). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

**Comment by AbfSailor** [comment]
Hey, @aczechowski  Thank you for the information. I'm slightly baffled; I know this is labeled as SDK but this document also serves as the only reference (that I can find) for information and details about the SMS_R_SYSTEM (SCCM Discovery Data) class, which is a key component of how SCCM works and crucial to understanding when writing queries. 

As always, I appreciate the response and helpful nature your team brings to the table.
