### ISSUE TITLE
Example to add quotes in CN value

### ISSUE THREAD

**Issue by sbv2291** [MicrosoftDocs/memdocs#1538]
Can we add some examples of how to add quotes if there are any special escaped special characters in the certificate subject?
I am talking about the below section. I am still struggling with how to use this.

https://docs.microsoft.com/en-us/mem/intune/protect/certificates-profile-scep#avoid-certificate-signing-requests-with-escaped-special-characters

My SCEP profile is having subject name format: CN={{OnPrem_Distinguished_Name}}
and our DN is like this CN="LastName\, FirstName,OU=UserAccounts,DC=corp,DC=contoso,DC=com"

Now I know I need to make it like below by adding quotes
CN=""LastName, FirstName”,OU=UserAccounts,DC=corp,DC=contoso,DC=com"

But the value for {{OnPrem_Distinguished_Name}} is generating automatically and no information available on how to modify it.
Can you please add some instructions like creating a rule in AD connect sync rules to modify the value or a way to directly modify in SCEP profile?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30c444f9-5cc4-7276-6882-d6b32ee453ea
* Version Independent ID: f1ec96ac-c890-2ed1-ede4-179de4b4e4cc
* Content: [Use SCEP certificate profiles with Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/certificates-profile-scep)
* Content Source: [memdocs/intune/protect/certificates-profile-scep.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certificates-profile-scep.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by sbv2291** [comment]
Able to fix the issue. Can you please consider adding below two points in the DOC so it helps everyone in future. 

Main credit goes to Cici Wu-MSFT : https://docs.microsoft.com/en-us/answers/questions/364488/windows-hello-for-business-certificate-issue.html

Point 1: If {{OnPrem_Distinguished_Name}} is having comma in CN value then Subject name format must be CN="{​​​​​​​​{​​​​​​​​OnPrem_Distinguished_Name}​​​​​​​​}​​​​​​​​"

Point 2: If the subject name lenght is more than 64 characters , need to disable name length enforcement using command "certutil -setreg ca\EnforceX500NameLengths 0" on Internal CA server
Reference: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc784789(v=ws.10)?redirectedfrom=MSDN#disable-dn-length-enforcement

**Comment by Brenduns** [comment]
@sbv2291  Thanks for the question, and the follow up which identified the solution. I've submitted a content update to add both bits of detail into the article.  That will show in the live content by Friday morning.
