### ISSUE TITLE
Add further information for Sending custom notification for a single device

### ISSUE THREAD

**Issue by fabiobaleizao** [MicrosoftDocs/memdocs#1539]
Good morning,

I stepped onto a case where customer is saying that he cannot send a custom notification for a specific device.
After analyzing the case, I saw he was trying to send a custom notification for an Android Corporate owned device type.
After looking into my tenant, I realized we cannot send custom notifications for this kind of enrollment.
For instance, if you have a Fully managed device or corporate owned device, you cannot send a custom notification.
This only works for BYOD enrollment type.
However, this is not specified in our public article.

Could you update the article to have this specification mentioned?

You can get in touch with me if you need further details.
Thank you in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 992e6528-c0a0-5b47-3133-28b6a9086d65
* Version Independent ID: d48c3237-1ea2-a6cd-4b3a-561d4ea964c5
* Content: [Send custom notifications to users with Microsoft Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/remote-actions/custom-notifications#send-a-custom-notification-to-a-single-device)
* Content Source: [memdocs/intune/remote-actions/custom-notifications.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/remote-actions/custom-notifications.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
Investigating full extent of this limitation.

**Comment by Brenduns** [comment]
Closing without content action/clarification. The PM/Dev team was unable to comment or provide clarifications, and since April 2021 no further asks about this have been raised.
