### ISSUE TITLE
"Salesforce App and Microsoft Intune" URL cannot find 

### ISSUE THREAD

**Issue by sufuruka** [MicrosoftDocs/memdocs#1544]
"Third-party apps such as the Salesforce mobile app work with Intune in specific ways to protect corporate data. To learn more about how the Salesforce app in particular works with Intune (including MDM app configurations settings), see **Salesforce App and Microsoft Intune**."

The above "Salesforce App and Microsoft Intune" link is to  https://docs.microsoft.com/en-us/samples/browse/?redirectedfrom=TechNet-Gallery .
But the link does not find "Salesforce App and Microsoft Intune" details Docs.
Could you please update link?

(admin edit: adding article metadata for proper tracking)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17955fd7-d652-8f0e-4446-00b8628d58cc
* Version Independent ID: 46755b3c-43a5-f5c9-0b74-ce2b7ede7d40
* Content: [App protection policies overview - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policy)
* Content Source: [memdocs/intune/apps/app-protection-policy.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-protection-policy.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by sufuruka** [comment]
Hi Team,
do you have any update?

**Comment by msbemba** [comment]
@sufuruka Thank you for your feedback. The salesforce doc is no longer available on Technet - so we have removed the reference from this document.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @sufuruka Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
