### ISSUE TITLE
MacOS Locked enrolment  and removal

### ISSUE THREAD

**Issue by sebsalvat** [MicrosoftDocs/memdocs#1546]
Is there any additional information about the Locked enrollment feature?

We've found that sometimes configuration profiles get "Tattooed" to the profiles menu and there doesn't seem to be a way to remove them from the Intune portal end.

Other than a device wipe, what options to admins have for removing old configurations from a device with Locked enrolment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5973e60e-024a-6578-734a-9e50c42db0a9
* Version Independent ID: 49f6f728-13c4-02ab-bfec-a3054c3f4fd1
* Content: [macOS device enrollment guide for  Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/fundamentals/deployment-guide-enrollment-macos)
* Content Source: [memdocs/intune/fundamentals/deployment-guide-enrollment-macos.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/deployment-guide-enrollment-macos.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@sebsalvat [Automatically enroll iOS/iPadOS devices by using Apple's Automated Device Enrollment](https://docs.microsoft.com/mem/intune/enrollment/device-enrollment-program-enroll-ios) states:

```If a BYOD device is converted to an Apple ADE device and enrolled with a profile that has locked enrollment enabled, the user will be allowed to use Remove Device and Factory Reset for 30 days.```

Also, it's possible you could use the [ProfileRemovalPassword](https://developer.apple.com/documentation/devicemanagement/profileremovalpassword) payload in a custom configuration policy. The Intune UI doesn't support this setting, and we haven't tested it. If you do, we recommend trying on one test device.

Good luck!
