### ISSUE TITLE
What does the Windows updates do exactly?

### ISSUE THREAD

**Issue by kennethvs** [MicrosoftDocs/memdocs#1547]
[Enter feedback here]

When configuring this policy there are 2 options to select: Windows updates and Endpoint analytics

Endpoint analytics I understand, but what exactly gets enabled when I select Windows Updates? The CSP documentation doesn't mention anything on this? 

Is the Windows Updates function the equivallent to provisioning the commercial ID via a custom policy, since that is my best guess on what it could possibly do?

/Kenneth

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c822884d-e84d-01fa-f7ba-503e08437dd8
* Version Independent ID: 8774dbd5-d8bc-e1c9-99cc-adca3e640423
* Content: [Create a Windows Health Monitoring profile in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/windows-health-monitoring)
* Content Source: [memdocs/intune/configuration/windows-health-monitoring.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/windows-health-monitoring.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by kennethvs** [comment]
I already found the answer, it's needed for: https://docs.microsoft.com/en-us/mem/intune/protect/windows-update-compliance-reports please include a reference in the documentation to this.

/Kenneth

**Comment by MandiOhlinger** [comment]
@kennethvs Good find. Thank you. The article is updated. Changes should be live later today/tomorrow.
