### ISSUE TITLE
Reversed defintions - SmartScreen for Microsoft Edge

### ISSUE THREAD

**Issue by icelava** [MicrosoftDocs/memdocs#155]
"SmartScreen for Microsoft Edge: Require turns off Microsoft Defender SmartScreen and prevent users from turning it on. Not configured (default) turns on SmartScreen. Helps protect users from potential threats and prevent users from turning it off."

What???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7874ff8b-727f-b013-27f8-fd714ebb53a5
* Version Independent ID: 05674b42-613e-d54d-2895-1f2db41b613a
* Content: [Device restriction settings for Windows 10 in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-windows-10#microsoft-defender-smart-screen)
* Content Source: [memdocs/intune/configuration/device-restrictions-windows-10.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/device-restrictions-windows-10.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@icelava Hey Aaron - Good catch. Thank you. In the future, it'd be great if you created a pull request with these types of fixes. There are hundreds of these settings, and we definitely appreciate the help.

This is fixed, and the changes should be live later today.

**Comment by icelava** [comment]
Frankly don't know how to do that; I primarily report problems/questions in the comments section of the respective docs.microsoft.com page.

**Comment by MandiOhlinger** [comment]
Ah! Good to know. The specific steps are at [https://github.com/MicrosoftDocs/memdocs](https://github.com/MicrosoftDocs/memdocs). Scroll past the folder view, and you'll see **Contribute to your documentation**.

These steps apply to almost every article on Docs.microsoft.com. GitHub will prompt you to sign a CLA, which is a one-time thing. Then, you're good to go. In the Intune space, we review every pull request before it gets published, so know that we've got your back.
