### ISSUE TITLE
Could the section "App protection Global policy" be clarified? Or does it need to be replaced?

### ISSUE THREAD

**Issue by balktl** [MicrosoftDocs/memdocs#1553]
The section "App protection Global policy" needs some clarification - it indicates that people should use the OneDrive for Business Admin Center to set this policy up. But then there is this documentation https://docs.microsoft.com/en-us/onedrive/control-access-to-mobile-app-features that indicates that Microsoft is not updating this feature anymore and then says to use Mobile Endpoint Manager admin Center to create and assign app protection policies. So, it's unclear what should be done and what method is best to use to set up App protection policies. Is it still OK to utilize Global App Protection policies?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17955fd7-d652-8f0e-4446-00b8628d58cc
* Version Independent ID: 46755b3c-43a5-f5c9-0b74-ce2b7ede7d40
* Content: [App protection policies overview - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policy#app-protection-global-policy)
* Content Source: [memdocs/intune/apps/app-protection-policy.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-protection-policy.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by yogkumgit** [comment]
@balktl Thank you very much for the contribution and updating the documentation with PR. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
