### ISSUE TITLE
Configure Windows Hello for Business:

### ISSUE THREAD

**Issue by Perrinw** [MicrosoftDocs/memdocs#1556]
[Enter feedback here]
When setting Configure Windows Hello for Business: to "Disabled" this page states 

Disabled - If you don't want to use Windows Hello for Business, select this setting. All other settings on the screen are then unavailable.

When doing so in the Windows Hello for Business:  Windows enrollment screen the settings are shown as unavailable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb79dc64-b652-b0e4-90c8-f8789c373dd7
* Version Independent ID: 49ce0336-2eab-e3e1-57c3-e1a84e062ff2
* Content: [Windows Hello for Business settings in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/identity-protection-windows-settings)
* Content Source: [memdocs/intune/protect/identity-protection-windows-settings.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/identity-protection-windows-settings.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@Perrinw   Thanks for the submission. I’m not sure if you’re asking a question here, or seeking confirmation about the differences between the two Windows Hello for Business policy UI experiences: Identify protection (this article – for specific policies), and Enrollment (found here: https://docs.microsoft.com/mem/intune/protect/windows-hello – for tenant wide settings).  Both set policies tht manage Windows Hello for Business, but the behavior for configuration via the Intune UI _is_ different.  Enrollment is Tenant wide and a single policy/configuration is allowed, which seems to be why those settings might remain visible. The identify protection policies can be deployed to discreet sets of devices, and each set might receive different configurations - thus there is no benefit to showing settings in a policy configuration when its not enabled.   That's the best reasoning I've been able to run down with the product group. 

A recent GitHub issue for this same article asked about that behavior, so if that GitHub post might be worth checking out if this seems related to a question you might have: https://github.com/MicrosoftDocs/memdocs/issues/1335 

For now, I’ll close this GitHub issue. However, should you have a question behind the comments you can make clear, go ahead and reply with that, and we’ll be able to continue via this same GitHub issue.
