### ISSUE TITLE
locate iphone

### ISSUE THREAD

**Issue by Ellwia** [MicrosoftDocs/memdocs#1557]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf0d4fa4-c4a0-6a69-3d86-5b34ccf8cbad
* Version Independent ID: 112c8b86-6df1-6fb8-4b7c-9bc2b5d15c2a
* Content: [Find lost iOS/iPadOS devices with Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/remote-actions/device-locate)
* Content Source: [memdocs/intune/remote-actions/device-locate.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/remote-actions/device-locate.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@Ellwia Looks like this issue was a mistake? Or you forgot to include the information? Please add the info and ping me and I'll reopen this item. Thanks!
