### ISSUE TITLE
Issue in 'Experiance' section

### ISSUE THREAD

**Issue by yogeshasalkar** [MicrosoftDocs/memdocs#156]
When Block Windows Spotlight is set to Yes, the following settings are available.

In the actual configuration of the MDM baseline, when 'Block Windows Spotlight is set to Yes' other sub-settings are invisible and when 'Block Windows Spotlight is set to not configured' sub-settings are available.
 Please review this bug in MDM baseline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f0f4d5d-fdd1-22e7-6372-9916b199209f
* Version Independent ID: caeb9f8b-30ad-7f02-4740-56522b2f9b1b
* Content: [Intune security baselines settings for Windows 10 MDM - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/security-baseline-settings-mdm-all?pivots=mdm-may-2019#experience)
* Content Source: [memdocs/intune/protect/security-baseline-settings-mdm-all.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/security-baseline-settings-mdm-all.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by yogeshasalkar** [comment]
<img width="960" alt="experiance in mdm baseline" src="https://user-images.githubusercontent.com/50020908/80481298-cbb17000-896f-11ea-83a9-946b4fe2ff6f.PNG">
Please refer the SS

**Comment by Brenduns** [comment]
@yogeshasalkar  Thank you for reporting this. I've passed the UI bug to the engineering team.  I'll keep this issue open for a day or so to see if I can report back with details on the behavior of the settings involved while the UI is problematic.

**Comment by Brenduns** [comment]
@yogeshasalkar   Update for you, and a content update is on the way.  This setting and the UI is functioning as intended, though some of the details in content prior to the pending update, are incorrect.  

This setting (when it is set to _Yes_) blocks use of all Spotlight features . If its set to _Not configured,_ then Spotlight isn't blocked, and the child options are available so you can choose to block those aspects of Windows Spotlight. After the content revisions publish, this should be more clear.

**Comment by yogeshasalkar** [comment]
Thanks @Brenduns
