### ISSUE TITLE
X in the Feature comparison table means it has that function or does not allow the function?

### ISSUE THREAD

**Issue by D-Jeffrey** [MicrosoftDocs/memdocs#1562]
Just a minor thing, I assume the X in the "Feature comparison" table means it is supported?  Maybe you could use a different symbol? 

Thanks,
Darren

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55564daa-5298-5b0b-9ff2-df25c5bbc0ea
* Version Independent ID: 26cb3db3-eba8-ab4b-bd6e-9d2487ae225d
* Content: [Prepare apps for mobile application management with Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/developer/apps-prepare-mobile-application-management)
* Content Source: [memdocs/intune/developer/apps-prepare-mobile-application-management.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/developer/apps-prepare-mobile-application-management.md)
* Service: **microsoft-intune**
* Sub-service: **developer**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@D-Jeffrey Thank you for your feedback. This table lists the settings that are enabled if an app uses the App SDK or the App Wrapping Tool. So an X means the feature is supported.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @D-Jeffrey Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
