### ISSUE TITLE
Cannot Enable Defender for Endpoint

### ISSUE THREAD

**Issue by mikesierra2** [MicrosoftDocs/memdocs#1564]
Hello

I tried to follow the instructions at the top of this page to enable Defender for Endpoint in Intune. None of the screen shots match the Intune UI.

"Open the Microsoft defender security center" is not a link on that page. Available instead:

"Open the Microsoft defender for endpoint admin console"
"create a trial account for microsoft defender for endpoint"

I clicked the first option, and clicked Settings, but the "Microsoft Intune connection" is not an option there.

Advice greatly appreciated.

I have gone ahead and deployed the defender for endpoint sensor on all of the devices in our organisation that are used by users with the Defender for Endpoint license.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24fa182f-ace6-e7e2-ff98-91951be7d10e
* Version Independent ID: f1acb398-6d69-b91c-5ee0-3da3bbf7809f
* Content: [Configure Microsoft Defender for Endpoint in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/advanced-threat-protection-configure)
* Content Source: [memdocs/intune/protect/advanced-threat-protection-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/advanced-threat-protection-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@Mikesierra2  I’m sorry that you’re not seeing the expected link. In reviewing your details and the documentation and UI, I think you’ve progressed beyond the procedure to enable the connection – and its already enabled!

In reviewing the image in docs, and a live tenant, the image remains accurate, and the link is present – prior to setting **Microsoft Intune connection** to **On**.     

After that connection is set to On, you’ll see the following page in  the Microsoft Endpoint Manager admin center, which is what I think your describing:  (this might have configurations you’ve not made yet, as its an active tenant with Microsoft Defender for Endpoint in use):
 
![image](https://user-images.githubusercontent.com/17034749/116282991-3ee6f100-a740-11eb-938a-c76b6248d306.png)

That first link you mention, _**Open the Microsoft defender for endpoint admin console**_, will open the Microsoft Defender Security Center.  To view that connection configuration, open the Security Center, go to **Settings**, and then **Advanced features**. (You mentioned viewing Settings, but not Advanced features).  When you view the Advanced features, you should see a list of options with toggles, one of which is the **Microsoft Intune Connection**, about three items up from the bottom:
 
![image](https://user-images.githubusercontent.com/17034749/116283075-58883880-a740-11eb-9060-ebddd85ef6e2.png)

If your toggle is set to **On**, your good to go, and the intent of the that procedure is completed.  If that’s the situation, you should be ready to onboard devices, which it sounds like you have started. 

I don’t think you need any assistance for this at this time. I will however update content to make it clear what is seen after that connection is set to On.  That isn’t something that was accessible when this content was drafted. But as I now have access to that post-configuration UI, I can definitely make it clear for future readers.
