### ISSUE TITLE
Token Based Install Issues - /MP Switch

### ISSUE THREAD

**Issue by mattwailes** [MicrosoftDocs/memdocs#1565]
Hello, 

We were struggling to get token based install to work with our new CMG.  Our devices are workgroup only devices not using certs or AAD Join.  Our site communication is E-HTTP.  We are running ConfigMgr 2010 and we setup our CMG with a virtual machine scale set with a public cert. 

We were getting errors getting the client installed.  We were getting 0x87d0027e, 0x80004005 errors during CCMSetup.  We were using the /mp, CCMHOSTNAME, SMSSITECODE, /NoCRLCheck, /RegToken

We ultimately got it working accidently by removing the /MP switch.  We finally got our client installed using the CCMHOSTNAME, SMSSITECODE,  /NoCRLCheck and /RegToken

Feel free to reach out for more information if needed. 

Thank you 

Matt
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3f3e45d-8f9d-aa5a-8b6a-d8c51c50d11e
* Version Independent ID: f5305fc4-894b-19dd-26c8-6f90901d4b1e
* Content: [Client installation parameters and properties - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/deploy/about-client-installation-properties)
* Content Source: [memdocs/configmgr/core/clients/deploy/about-client-installation-properties.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/deploy/about-client-installation-properties.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @mattwailes for the feedback. I'll check with engineering if there's anything specific to that scenario we need to clarify.

Were you working with Microsoft support or a customer engineer (fka PFE)?

**Comment by mattwailes** [comment]
Thanks for looking into this.  We are standing up the CMG for one of our enterprise clients.  No Microsoft intervention this time but we were about to pick up the phone 🙂 We figured out the client installation string accidently through trial and error after we were starting to get desperate.

Matt

________________________________

**Comment by aczechowski** [comment]
When I asked one of the engineers about it, they asked to see logs. That's not really doable here (and not the purpose of this feedback site). But his general response was that /mp may not be needed in some circumstances. So I'll add a tip with that error code and removing that parameter as a work around. If you have other issues, or need further assistance, please use one of the following resources:

- Post on [Configuration Manager forums](https://docs.microsoft.com/answers/products/mem). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

This issue will close when the change merges. At this point it probably won't publish live until Monday
