### ISSUE TITLE
Misleading Location-based Compliance article

### ISSUE THREAD

**Issue by wcneumann219** [MicrosoftDocs/memdocs#1566]
This article leads one to believe this is available for more than the legacy Android platform. It's a great capability that I happen to need for Windows devices.

The article should clarify this is ONLY available for Android Device Administrator Compliance policies,

Microsoft should extend this capability to all platforms--why for just the one that's being depricated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe321859-0fce-bcce-5fc7-95d9bc5f9991
* Version Independent ID: 3931af25-92c1-7559-9095-87f7ca073c65
* Content: [Bind Android devices by network location in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/use-network-locations)
* Content Source: [memdocs/intune/protect/use-network-locations.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/use-network-locations.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@wcneumann219   Thanks for your feedback. I agree this article needs to call out the limited platform for which is applies. I've submitted an edit that should go live in the morning for that.  I've also passed your feedback on the limited support to our engineering team and the program manager for this feature.
