### ISSUE TITLE
Clarification on when 2013 will be available as a baseline media

### ISSUE THREAD

**Issue by mash2010** [MicrosoftDocs/memdocs#1567]
[Enter feedback here]

The first paragraph of this article states that the Version 2013 is also available as baseline media in MVLS but as stated in the other article, it won't be on MVLS till after the update is globally available.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f1bc9d9-9e48-3a13-293a-d8c16a9c79eb
* Version Independent ID: 82c646de-cb5e-7f5b-6542-46e157c862f1
* Content: [What's new in version 2103 - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/changes/whats-new-in-version-2103)
* Content Source: [memdocs/configmgr/core/plan-design/changes/whats-new-in-version-2103.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/changes/whats-new-in-version-2103.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @mash2010 for the feedback 😉
