### ISSUE TITLE
Start Orchestration; Step 4c - Typos

### ISSUE THREAD

**Issue by TeslaSysA** [MicrosoftDocs/memdocs#157]
Simple typos:

"From the Orchestration Group **_nose_**, click the Start Orchestration button to restart orchestration. **_reset that status it by using Start Orchestration button._**"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c5f0d89-c8f6-19a5-70b1-03b590fa59ee
* Version Independent ID: 2202ffcd-6bcf-454c-11ae-f62b31ac31e2
* Content: [Orchestration Groups - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/sum/deploy-use/orchestration-groups#feedback)
* Content Source: [memdocs/configmgr/sum/deploy-use/orchestration-groups.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/sum/deploy-use/orchestration-groups.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
@TeslaSysA thanks for sniffing out those typos and copy/paste errors. Sorry, couldn't resist making a  horrible pun =) I'll have this fixed shortly. Thanks again!
