### ISSUE TITLE
Not enough details on Windows devices

### ISSUE THREAD

**Issue by ybeltrikov** [MicrosoftDocs/memdocs#1570]
The page does not provide much information on locating Windows devices. 
There might be some pre-requisities as in my environment it works for some Windows 10 devices and is greyed our on others. 
Moreover, this page is in the iOS section of the documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf0d4fa4-c4a0-6a69-3d86-5b34ccf8cbad
* Version Independent ID: 112c8b86-6df1-6fb8-4b7c-9bc2b5d15c2a
* Content: [Find lost devices with Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/remote-actions/device-locate)
* Content Source: [memdocs/intune/remote-actions/device-locate.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/remote-actions/device-locate.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@ybeltrikov The Supported platforms section lists the specific Win10 devices that are supported.
I'll move the Table of Contents entry to the Other Devices section.
Thanks!
