### ISSUE TITLE
Microsoft Code Signing certificate - Where do I get it?

### ISSUE THREAD

**Issue by PaulKlerkx** [MicrosoftDocs/memdocs#1571]
this section - "The Microsoft Edge installer and CMPivot are signed with the Microsoft Code Signing certificate. If that certificate isn't listed in the Trusted Publishers store, you'll need to add it. Otherwise, the Microsoft Edge installer and CMPivot won’t run when the PowerShell execution policy is set to AllSigned."
we use Allsigned and use Windows 10 build 1809 and 1903 and neither have this certificate in the operating system trusted publisher cert store.  I don't seem to get any hits on searching for that cert online either.  Where can I find this "Microsoft Code Signing" certificate?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1b08c59-efa1-088a-b7d1-0e67e1f19281
* Version Independent ID: 60612563-0056-bdad-b145-c5c934c0cc1c
* Content: [Deploy and update Microsoft Edge, version 77 and later - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/apps/deploy-use/deploy-edge)
* Content Source: [memdocs/configmgr/apps/deploy-use/deploy-edge.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/apps/deploy-use/deploy-edge.md)
* Product: **configuration-manager**
* Technology: **configmgr-app**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Let me do some checking on how this is _supposed_ to be. On my device, the **Microsoft Code Signing PCA 2011** certificate is in the **Intermediate Cert Authority** store for my _user account_. I didn't find it in any stores for the local machine, but was just doing a visual search.

I found a [TechCommunity discussion](https://techcommunity.microsoft.com/t5/system-center/untrusted-certificate-when-installing-microsoft-edge/m-p/1479788) on the same topic.

**Comment by aczechowski** [comment]
Internal reference CMADO-7585106
