### ISSUE TITLE
Pre-script and post-script character limit for MECM 2010

### ISSUE THREAD

**Issue by ofortun** [MicrosoftDocs/memdocs#1575]
There appears to be a 5000 character limit for pre-scripts and post-scripts in MECM 2010 (I have not tried 2103). This is not documented.  I would add this as a bullet point under: 

> For Configuration Manager version 2010 and earlier, add scripts to your orchestration groups on the Pre-Script and Post-Script tabs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c5f0d89-c8f6-19a5-70b1-03b590fa59ee
* Version Independent ID: 2202ffcd-6bcf-454c-11ae-f62b31ac31e2
* Content: [Orchestration Groups - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/sum/deploy-use/orchestration-groups)
* Content Source: [memdocs/configmgr/sum/deploy-use/orchestration-groups.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/sum/deploy-use/orchestration-groups.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @ofortun, I tried it on a 2103 site, and I could paste 43679 characters multiple times on multiple lines. I'll double-check with the dev, because I don't see any bugs fixed for this in 2103. At what point are you blocked with adding more than 5000 characters? Can you share the script that you're using?

**Comment by aczechowski** [comment]
Nevermind my previous questions, I confirmed that in 2103 it changed to 50k limit. I'll add a note to the article. Thanks for the feedback! 😄
