### ISSUE TITLE
Unsupported Scenario: Available deployments to user collections

### ISSUE THREAD

**Issue by codeX004** [MicrosoftDocs/memdocs#1576]
Statement: Software Center doesn't display applications and packages as available that are deployed to user or user group collections.

This has been tested with CNG v3 certificates and it works (tested with MEMCM CB 2010) - is this still an unsupported scenario or has the page not yet been updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e3033ee-1c86-a8af-dcce-6246142ca45f
* Version Independent ID: 1e2cc4d7-83cb-22c0-7a1b-3cfaf84a9f23
* Content: [CNG v3 certificates overview - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/network/cng-certificates-overview)
* Content Source: [memdocs/configmgr/core/plan-design/network/cng-certificates-overview.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/network/cng-certificates-overview.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @codeX004, thanks for the feedback. You're not the first to ask this question, and I've been trying to get a straight response from engineering for a while. But given multiple customers have said it's working, and based on one response from engineering, I think the scenario should be working ok. I'll revise the article.
