### ISSUE TITLE
Recovery PIN not accepted second time ?

### ISSUE THREAD

**Issue by CIOWPSMDM** [MicrosoftDocs/memdocs#1577]
Hi, I tried to do this but after entering the Recovery PIN and after it was accepted the restore from the device hanged.
After a few hours nothing happening I reset the device with the power-button but the Recovery PIN is now not accepted if I try it again. **Error: Wrong passcode. Try again.**
Is this a known issue and how can I recover from this issue ?

Martijn

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f756249-1cd7-0a08-6e99-c5f5add14b21
* Version Independent ID: 3749a819-5ab0-d5c1-cee0-162db2951949
* Content: [Erase a macOS device - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/remote-actions/device-erase)
* Content Source: [memdocs/intune/remote-actions/device-erase.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/remote-actions/device-erase.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@CIOWPSMDM Thanks for taking the time to share this with the Intune documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a few options available to provide the best level of support for this:   
- Post on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.   
- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.   
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.   

I'm closing this issue as there's nothing actionable for docs at this time.
