### ISSUE TITLE
Apple iPad > Settings > Privacy > Local LAN

### ISSUE THREAD

**Issue by HandyAndyOnGitHub** [MicrosoftDocs/memdocs#1579]
Hi, is there any documentation explaining how, when Kiosked, we can permit an App to have network access on the local LAN to a complimentary device?  

For example, one may wish to enable the Zoom Room video conferencing controller app on a Kiosked iPad to connect with the Zoom Room PC on the same LAN.  Currently I have to disable Kiosk mode for all devices managed by the iPad's device Configuration Profile and manually permit:
Apple iPad > Settings > Privacy > Local LAN > Zoom Rooms

Documentation on this would be nice.
Andy
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88932dd8-abce-bf23-9624-1df5f60a946d
* Version Independent ID: ab2d932f-e375-2485-a6e5-e02daf7a27c4
* Content: [iOS/iPadOS device settings in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-ios)
* Content Source: [memdocs/intune/configuration/device-restrictions-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/device-restrictions-ios.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@HandyAndyOnGitHub Good question. You could create a custom configuration profile that enables the Zoom Room video conferencing controller app, and apply that profile first, Then, apply the kiosk profile. But, that may be more steps than what you're already doing.

As for documenting this scenario, it's not on our radar. If you blog this scenario, then I suggest adding the link to this GitHub issue.
