### ISSUE TITLE
Clarification needed on supported platforms?

### ISSUE THREAD

**Issue by r3dsubmarine** [MicrosoftDocs/memdocs#158]
I've found that I'm unable to lock my Windows 10 machines via the Company Portal app as described. They are Azure AD joined and auto-enrolled in Intune for MDM. 

The following two articles don't list Windows 10 as a supported target for remote device locking. Is this article mistaken, or is Company Portal just the only supported method for locking a Windows 10 device? 

https://docs.microsoft.com/en-us/mem/intune/remote-actions/device-remote-lock
https://docs.microsoft.com/en-us/mem/intune/user-help/remote-lock-your-device-cp-app

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efa2b3a1-8393-c78b-0c73-ad0fe6350a61
* Version Independent ID: c1cac54e-811c-897e-dcaf-ffbd6f7e49c7
* Content: [Lock your device from the Company Portal](https://docs.microsoft.com/en-us/mem/intune/user-help/remote-lock-your-device-cpwebsite#feedback)
* Content Source: [memdocs/intune/user-help/remote-lock-your-device-cpwebsite.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/user-help/remote-lock-your-device-cpwebsite.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @r3dsubmarine, thank you for your question. I'm doublechecking with the product team and will let you know what I find out.

**Comment by andreletz** [comment]
Hi @lenewsad - I have the exact same question.  Do you have any definitive answer, yet?  Thank you!

**Comment by lenewsad** [comment]
Hi @r3dsubmarine and @andreletz, thank you for reaching out and for your patience. There is no remote lock option on the Company Portal website for Windows 10 devices.  I've removed mention of it from the list of supported devices in this article.
