### ISSUE TITLE
Typo - Grammar

### ISSUE THREAD

**Issue by Zucky16** [MicrosoftDocs/memdocs#1580]
[Enter feedback here]

Conditional Access introduction

When configuring Conditional Access in the Microsoft Endpoint Manager admin center, **your** configuring it in the Conditional Access blades from the Azure portal, which means that user interface is a bit different than when you create other types of **policy** for Intune.

change to _you're_ or even better _you are_
change to _policies_
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 733b08c2-5666-0d9b-8e78-28fba3456a6f
* Version Independent ID: ab6a321b-d6c0-c301-8156-96ccfdd21192
* Content: [Tutorial - Protect Exchange Online email on unmanaged devices - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/tutorial-protect-email-on-unmanaged-devices)
* Content Source: [memdocs/intune/protect/tutorial-protect-email-on-unmanaged-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/tutorial-protect-email-on-unmanaged-devices.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@zucky16   Thanks for this issue. I've submitted an update to the content to fix those references, which should go live later this afternoon.
