### ISSUE TITLE
Updates to Windows Company Portal keyboard shortcuts

### ISSUE THREAD

**Issue by kagillig** [MicrosoftDocs/memdocs#1582]
A few updates should be made to the Windows Company Portal keyboard shortcuts table:
1. Devices row should be changed to be labeled Devices - Device tile
2. Devices section should remove the Available row and instead include the same rename, remove, and check access options listed for the home - device tile option and the device details option
3. Add either a section for each page (home, search, all apps, app categories, downloads and updates page) or just one item for app tiles and one item for app list detail item to include keyboard shortcut for Install, Ctrl + I

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40ee2465-52c8-8fd0-ece0-c2dc498d025f
* Version Independent ID: 02b42d75-b82e-acb5-3457-7ecd3c45326f
* Content: [How to configure the Intune Company Portal apps, Company Portal website, and Intune app - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/company-portal-app)
* Content Source: [memdocs/intune/apps/company-portal-app.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/company-portal-app.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by kagillig** [comment]
@Erikre, FYI, my teammate, Allison Durkan, is working on putting out a PR with these updates now.

**Comment by allydurks** [comment]
Linked this with #1581

**Comment by yogkumgit** [comment]
@allydurks Thank you very much for the contribution and updating the documentation with PR. @kagillig Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
