### ISSUE TITLE
Online apps - Azure AD join requirement

### ISSUE THREAD

**Issue by dnbgaese** [MicrosoftDocs/memdocs#1587]
I deploy an online licensed app to a user collection as available. The user is able to install the app from Software Center even if the device is not Azure AD joined or hybrid joined. The device is Azure AD registered only.

This should not be possible based on the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 766b1855-dc0a-3664-5d0f-184a34998900
* Version Independent ID: d459b52e-76bb-1af1-6c99-4cd0b7e3f11e
* Content: [Microsoft Store apps - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/apps/deploy-use/manage-apps-from-the-windows-store-for-business)
* Content Source: [memdocs/configmgr/apps/deploy-use/manage-apps-from-the-windows-store-for-business.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/apps/deploy-use/manage-apps-from-the-windows-store-for-business.md)
* Product: **configuration-manager**
* Technology: **configmgr-app**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @dnbgaese thanks for the feedback. While at the top this article explicitly says cloud or hybrid joined only, there's a bullet further down in the section [Deploying online apps using the Microsoft Store for Business and Education to devices that run the Configuration Manager client](https://docs.microsoft.com/mem/configmgr/apps/deploy-use/manage-apps-from-the-windows-store-for-business#deploying-online-apps-using-the-microsoft-store-for-business-and-education-to-devices-that-run-the-configuration-manager-client):

> - Register or join devices to the same Azure AD tenant where you registered the Microsoft Store for Business and Education as a management tool.

The article in general needs to be updated, as all of the Windows 10 versions it mentions are out of support. So I'll do a general revision of the article, and make sure to include "registered" in the bullet at the top of the page.

**Comment by dnbgaese** [comment]
Many thanks for the clarification and the quick edit, Aaron!

Have a good time
Philipp
