### ISSUE TITLE
Duplicate No Name Licenses keep re-appearing

### ISSUE THREAD

**Issue by afield1235** [MicrosoftDocs/memdocs#1590]
Whenever we wipe an iPad to re-assign it, Intune still keeps some record somewhere, when the new user enrolls and downloads apps, intune assigns another 15-20 licenses to a "no user" with the same serial number. I've opened a ticket and they couldn't escalate it to the developers to be fixed? This is completely broken and not near production ready. What is going on?

![image](https://user-images.githubusercontent.com/18271134/117229022-1198e380-adcf-11eb-911d-df57b0826779.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6be83bf7-b364-60e3-1b4f-97bbde969ada
* Version Independent ID: 02a2bedd-1af7-3a14-7314-11e0853e4c98
* Content: [Manage Apple volume-purchased apps - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/vpp-apps-ios)
* Content Source: [memdocs/intune/apps/vpp-apps-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/vpp-apps-ios.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by afield1235** [comment]
@Erikre Any update on this? It's causing a lot of issues with our auditing and our GUI is completely junked up by this. Should not even be an issue at all. No other MDM providers have this issue.

**Comment by msbemba** [comment]
@afield1235 Thank you for your feedback. Sorry about the delay in response, hope this isn't a problem anymore. Ideally, in such cases, you open a support ticket via the need help section on the admin center and have them escalate it if it is a bug.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @afield1235 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
