### ISSUE TITLE
Document any end-user implications of just assigning a compliance policy

### ISSUE THREAD

**Issue by clajes** [MicrosoftDocs/memdocs#1595]
We have seen customers migrating co-management compliance workload for all users from SCCM to MEM and as part of that suddenly some users were suddenly notified that they did not have BitLocker enabled. Other customers have seen notifications related to password/pin on some platforms. So the ask is that we document all implications of assigning users to a Compliance Policy without having a configuration policy that configures what compliance checks for and without having a CA policy that  require compliance . Not sure if we can call it documentation of any implicit auto-remediation for assigning compliance policies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c19b6ee-2218-cd97-96a4-2832c0302d7e
* Version Independent ID: da3ff20c-91cb-d760-708c-8e56af5d59d8
* Content: [Device compliance policies in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/device-compliance-get-started#reference-for-non-compliance-and-conditional-access-on-the-different-platforms)
* Content Source: [memdocs/intune/protect/device-compliance-get-started.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/device-compliance-get-started.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@clajes   Thanks for this Github issue ask. I've created an internal work item to track this ask for consideration in a future content sprint.  With this ask being actively tracked, we'll close this Github issue.
