### ISSUE TITLE
PKCS Certificates Removal undocumented option

### ISSUE THREAD

**Issue by JordiSG** [MicrosoftDocs/memdocs#1596]
Hi Team,

in the section "Windows Devices" -> "PKCS Certificates", it says:

> A PKCS certificate is revoked and removed when:
> 
> A user unenrolls.
> An administrator runs the wipe action.
> An administrator runs the retire action.

After some testing, if you remove the Device from the Profile (either excluding the device or just removing the assignment) the profiles get also removed.

Could you please add this to the docs?

Thanks in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14c29d43-a41a-a660-4e79-4c06d6da76c0
* Version Independent ID: 5c69148b-56e4-df34-08b7-5bf5df3ad2fb
* Content: [Remove SCEP or PKCS certificates in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/remove-certificates#windows-devices)
* Content Source: [memdocs/intune/protect/remove-certificates.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/remove-certificates.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@JordiSG  Thanks for this feedback. I've asked our engineering team to review and confirm the behavior - so we can update the docs accurately. They're looking at more than just the one entry, and it's dragging on longer than expected, but still in progress. Once the results are in, I'll update this feedback thread and then apply any changes to content.

**Comment by Brenduns** [comment]
@JordiSG  The final update form the engineering team is in. It looks like PKCS certificates are _removed_ when the profile is no longer assigned to a user or device, but the cert is not actually _revoked_.  This is similar as seen for PKCS certs on iOS, which also has a condition of removal but not revocation.

Per your observation, yes, the PKCS certificate is removed. But it isn't going to be revoked, which might not be what you expected. (Its not what I expected. :) 

I'll be updating the content later today to reflect the results of this engineering review of the action and results that apply to the certificates.
