### ISSUE TITLE
Incomplete Defender deployment instructions

### ISSUE THREAD

**Issue by maximvelichko** [MicrosoftDocs/memdocs#1597]
This page misses an important step of Defender onboarding (deploying a mandatory configuration profile with a blob downloaded from Microsoft Security Portal, plus a bunch of other configuration profiles with system payload - only KEXT is mentioned though there are more of them). Users who use this page as a primary source of Defender installation assume that deploying an app through Intune is sufficient to have a fully functional system - which is not correct.

Please mention that these config profiles are required, and refer a reader to [Defender's onboarding guide](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-install-with-intune) for instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19789902-54c4-7af6-a822-f7756a5b0f65
* Version Independent ID: 6ce44e59-3e0e-0b5f-d6dc-fcad16ec1084
* Content: [Add Microsoft Defender for Endpoint to macOS devices using Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-advanced-threat-protection-macos)
* Content Source: [memdocs/intune/apps/apps-advanced-threat-protection-macos.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/apps-advanced-threat-protection-macos.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@maximvelichko Thank you for your feedback. We have made changes to the document to include the next steps and this can be tracked via PR#https://github.com/MicrosoftDocs/memdocs/pull/2486

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @maximvelichko Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
