### ISSUE TITLE
Limitations for company owned devices

### ISSUE THREAD

**Issue by xNiklasJern** [MicrosoftDocs/memdocs#16]
The DEM enrollmens has a limitations of 1000 devices. Does the DEP hav anything similar?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc877512-e9ea-ae59-6804-c783e90d2f94
* Version Independent ID: 3823734f-05b9-df40-532f-33473a5d3134
* Content: [Set up enrollment for macOS devices - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/macos-enroll)
* Content Source: [memdocs/intune/enrollment/macos-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/macos-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...

**Comment by ErikjeMS** [comment]
Repinged PM...

**Comment by ErikjeMS** [comment]
@xNiklasJern DEP has changed to Automated Device Enrollment. You can find the supported volume information here: https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-ios#supported-volume Thanks!
