### ISSUE TITLE
Grey area when configure the PullDP to use CDP as a source

### ISSUE THREAD

**Issue by bala503** [MicrosoftDocs/memdocs#160]
Hi,
When we configure the PullDP to use CDP as a source, the PullDP has to use the proxy to get the content, here either configuring the proxy on PullDP's site system property or on the Configmgr control panel applet doesn't help, the only case when the PullDP communicates with CDP when we configure the proxy on Winhttp service. So i believe this is still a grey area whether this is an expected behavior or bug or so and has to be documented as well.

Though the PullDP uses CCMFramework of the the client component, still it is listed as a site systems and we can't expect an admin to configure the proxy out of the box on the PullDPs.so there is still some work left and to be addressed.

Thanks in advancs.
Bala

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a39441b-ee2c-5b1b-5e64-ffd26fc7fd71
* Version Independent ID: a28c1d6d-fec8-86d3-e584-e086b27b3ced
* Content: [Pull-distribution point - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/hierarchy/use-a-pull-distribution-point#feedback)
* Content Source: [memdocs/configmgr/core/plan-design/hierarchy/use-a-pull-distribution-point.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/hierarchy/use-a-pull-distribution-point.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @bala503, thanks for the feedback. I think we should treat this as product feedback. The pull DP is a site system, and it has a tab for proxy. If that's not working, I think that's a bug. Here are your options:
- File [product feedback](https://docs.microsoft.com/mem/configmgr/core/understand/find-help#product-feedback) (send a frown)
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
I'm closing this issue.

**Comment by bala503** [comment]
Hi @aczechowski, thanks for your time to check my feedback, I have already raised a user voice for the product feedback, also i was raising this point here to include the manual winhttp proxy config in the docs at-least until it is being fixed.

Thanks.
