### ISSUE TITLE
Availability

### ISSUE THREAD

**Issue by kennethvs** [MicrosoftDocs/memdocs#1600]
[Enter feedback here]
Nice addition, can't wait to start exploring the possibilities.

I was wondering why this functionality isn't mentioned under "What's new" or "In development" - did I miss it's announcement somewhere?

/Kenneth

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e458d85e-5eda-1421-a8eb-5775da1e8725
* Version Independent ID: 10a95675-5f3d-245b-c1f4-57f6faa97300
* Content: [Create filters in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/fundamentals/filters)
* Content Source: [memdocs/intune/fundamentals/filters.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/filters.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@kennethvs It will be in "What's new" mid-week. I _think_ that's when rollout completes.

@Scottduf For awareness...

**Comment by kennethvs** [comment]
Thank you,

But why isn't it/ wasn't it under "in development" ?

Regards,

Kenneth

**Comment by MandiOhlinger** [comment]
@kennethvs It was in "In development". It was removed. You can see this change in the [https://github.com/MicrosoftDocs/memdocs/commit/dac3210e1ec3ca4e961ec96957b089fc7ea69f1d#diff-1cc323f35e1f110bee63d48644bb3521c09ad9f3d6961c4975bf9e6f80810b8b](https://github.com/MicrosoftDocs/memdocs/commit/dac3210e1ec3ca4e961ec96957b089fc7ea69f1d#diff-1cc323f35e1f110bee63d48644bb3521c09ad9f3d6961c4975bf9e6f80810b8b) commit.

**Comment by kennethvs** [comment]
Thank you for clarifying this, have a nice day!
