### ISSUE TITLE
Add 30 days of grace period mention for MDM push certificate renewal

### ISSUE THREAD

**Issue by rockon908** [MicrosoftDocs/memdocs#1602]
As mentioned in https://techcommunity.microsoft.com/t5/intune-customer-success/intune-and-the-apns-certificate-faq-and-common-issues/ba-p/280121

is it possible to add the mention of 30 days of grace period of expired MDM certificates?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: babf49ae-ec79-e627-9dbf-2df2eb8909ab
* Version Independent ID: 90f3f372-9326-473e-3f82-e28e89853d49
* Content: [Get an Apple MDM Push certificate for Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/apple-mdm-push-certificate-get#renew-apple-mdm-push-certificate)
* Content Source: [memdocs/intune/enrollment/apple-mdm-push-certificate-get.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/apple-mdm-push-certificate-get.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by msbemba** [comment]
@lenewsad Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2485

Once the author approves, the changes will be merged.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @rockon908 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
