### ISSUE TITLE
Silent Bitlocker enablement during OOBE with Windows Autopilot

### ISSUE THREAD

**Issue by jpawlowski** [MicrosoftDocs/memdocs#1603]
Hi team,

I think it might be beneficial to point out that it is important to have any Bitlocker polices assigned directly to a device or a device group, _not_ to a user object (or a group of users).

If somebody would like to silently enable Bitlocker and adjust the encryption settings for devices like Surface Notebooks that come with pre-configured Bitlocker settings, it is important that these settings are available to the device during the _Device setup_ already. The only way to achieve this is to assign the device configuration policy to the device object. Assigning the device configuration policy to a user object will not ensure the policy is available at the early stage as required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ff0284d-e040-ea4a-dd6e-8184914ea702
* Version Independent ID: c756c9fe-f38a-e121-68a3-72489921e0e5
* Content: [Setting the BitLocker encryption algorithm for Autopilot devices](https://docs.microsoft.com/en-us/mem/autopilot/bitlocker)
* Content Source: [memdocs/autopilot/bitlocker.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/bitlocker.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by frankroj** [comment]
Thank you for the feedback @jpawlowski. I apologize for the time it took to get back to you regarding this feedback item. We just released a new set of Autopilot doc under the Tutorial section. This Tutorial section will be expanding with several new topics in the coming months. One of the topics we will be working on is implementing BitLocker during Autopilot. I will definitely make sure I mention your suggestion in this new section.
