### ISSUE TITLE
Missing PIN - Biometric Change information

### ISSUE THREAD

**Issue by svenhallauer** [MicrosoftDocs/memdocs#1604]
This page is missing the information that when the biometric data changes the user is required to enter the PIN instead.  See https://docs.microsoft.com/en-us/mem/intune/apps/mam-faq#what-happens-if-i-add-or-remove-a-fingerprint-or-face-to-my-device 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c81b9a99-a379-a3b6-0dde-8781da62d16a
* Version Independent ID: 33b4409f-9687-feb7-07ab-7d6bc0d8b9f5
* Content: [iOS/iPadOS app protection policy settings - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policy-settings-ios)
* Content Source: [memdocs/intune/apps/app-protection-policy-settings-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-protection-policy-settings-ios.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@svenhallauer Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2481

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @svenhallauer Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
