### ISSUE TITLE
disable / uninstall connected cache

### ISSUE THREAD

**Issue by pilgi3** [MicrosoftDocs/memdocs#1606]
It would be great if there is a uninstall / disable section.
Because we disabled the connected cache but what should we do with the files, schedulded tasks (still running)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30ebeddc-a833-92a7-c1d4-4c7af579d99f
* Version Independent ID: bbbae6d5-a470-e475-3262-0f304ecd619f
* Content: [Troubleshoot Connected Cache - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/troubleshoot-microsoft-connected-cache)
* Content Source: [memdocs/configmgr/core/servers/deploy/configure/troubleshoot-microsoft-connected-cache.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/deploy/configure/troubleshoot-microsoft-connected-cache.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by pilgi3** [comment]
@aczechowski 
The "Doinc" files are still there in c:\Doinc, SMS_DP$\Ms.Dsp.Do.Inc.Setup and specified volume for Connected Cache.
But without any modification after disabling the feature (except C:\Doinc\Product\Install\Logs).
Also the schedulded tasks are still available and running.
![image](https://user-images.githubusercontent.com/44865075/117929953-af277200-b2fd-11eb-942c-8e56a1c3d2d7.png)

Could we delete the files and the schedulded task?

**Comment by andyrivMSFT** [comment]
Yeah, those items should have been deleted and can be deleted manually. We will investigate this on our side.  Thanks!

**Comment by aczechowski** [comment]
Thanks @pilgi3 for the feedback. I'm closing this issue as Andy captured the feedback, and I don't want to make any changes to the doc at this time.

**Comment by pilgi3** [comment]
Great, we will delete this manually. Thanks for the reply!
