### ISSUE TITLE
Please complete the instructions for setting up Update Compliance in Intune.

### ISSUE THREAD

**Issue by treestryder** [MicrosoftDocs/memdocs#1608]
For a week after following the instructions on this page, I have been looking for a way to report a bug in Update Compliance. Only our SCCM PCs had names, when our Intune managed PCs did not. Today I learned from [this blog post](https://www.jeffgilb.com/update-compliance-with-intune/) that more than just the one CSP must be configured for Windows to send names and detailed telemetry to Update Compliance.

That solved, now I need to find the User Voice / Feed Back Hub to up-vote adding Update Compliance as a native MEM feature. =)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7024ad8-b24b-598c-8b16-2da8bc15e9e4
* Version Independent ID: 230e96a7-e771-e6dd-d5f4-ac8b514fb4d4
* Content: [Use Update Compliance reports for Windows Updates in Microsoft Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/windows-update-compliance-reports#use-update-compliance)
* Content Source: [memdocs/intune/protect/windows-update-compliance-reports.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/windows-update-compliance-reports.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@treestryder  Thanks for this submission.  Its revealed that something went sideways in that an edit from last September to add in the correct path for the commercial ID provider ( _Provider/ProviderID/CommercialID_ - as identified by Jeff, the author of the excellent blog you reference) was 'undone' or reverted in January. Gar!  I'll be restoring that later today, which should help.  

To help ensure we get this right, can you confirm the other CSP your referencing if it wasn't that? If your referencing something else I'm not clear as to what that might be. Jeff' blog covers a bit of territory for Update Compliance, and its not clear which of the additional details are necessary vs useful. I'm balancing Jeff's information with details provided from our engineering team to get the right set of required facts into docs. This isn't something I can setup to test myself at this time.

**Comment by treestryder** [comment]
That is just the thing. I was vague in the bug report because I am new to this and am having to test in production.

With what I had done following those instructions, our SCCM Co-managed PCs, previously setup for Device Compliance, seemed to all have names. And I can only guess that it was our fully Intune managed PC which are missing names, or had "#" as their name. Yesterday, after missing the daily update, I added the 3 new to me CSPs that Jeff mentioned, in particular "AllowDeviceNameInDiagnosticData" and was hoping for better results, today after 3 PM ET. 

However, I had not noticed that Jeff said the Commercial ID should be in "./Vendor/MSFT/DMClient/Provider/ProviderID/CommercialID", when the official doc said "./Vendor/MSFT/DMClient/Provider/MS DM Server/CommercialID". Which is it? Maybe if I fix it fast, I'll catch a few before the update.

**Comment by Brenduns** [comment]
@treestryder  The correct path is  ./Vendor/MSFT/DMClient/Provider/ProviderID/CommercialID

That was fixed in September, but then reverted. The incorrect path (in the doc today) was originally provided by the product group, but isn't valid. (I'll get that fixed in docs later today, even if there remains more to add/fix later as I know the current detail isn't correct)

**Comment by treestryder** [comment]
Updated. No improvement to the name situation, yet. I'll check tomorrow.

**Comment by treestryder** [comment]
Good news. Following Jeff's blog post, I am now seeing names and both Co-Managed and Intune Managed devices.

Turns out, all of the first batch of PCs (with and without names) were only Co-Managed, which must not have ever been configured to send names.

**Comment by treestryder** [comment]
My success only came after following [Jeff's blog post](https://www.jeffgilb.com/update-compliance-with-intune/). The doc in question still lacks a mention of the CSPs required for the data collection to work as expected.

**Comment by Brenduns** [comment]
@treestryder   Some changes for content are on the way!  Primarily, this article will be reworked a bit, and will soon  point off to a new article in the Update Compliance space that was built leveraging Jeff's Blog.  You can find that new article here:  https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-configuration-manual

This new article fixes many of the problems in this current content, and will be the defacto configuration doc destination soon. We expect that content will not only help resole the challenge you and other have run into, but should then stay more current as this is all really a configuration for Update compliance that will then be owned by that team - and thus can be kept synced to future changes with that service.

**Comment by treestryder** [comment]
Thank you. And thanks for making the world a better place.

Wrong forum to say this, but just in case someone from both teams might be reading along. I would prefer this functionality were built into Intune.

Creating, and giving the group who needs this information access, to the "WaaSUpdateInsights" Solution is a pain.

Then, don't get me started on that "script" (a convoluted CMD file, that calls a Powershell script, that runs a hodgepodge of executables) in the new article. I will stick to the 4 simple CSPs until they break. 😉
