### ISSUE TITLE
Comply with (rather than "comply to")

### ISSUE THREAD

**Issue by GenerAhl** [MicrosoftDocs/memdocs#161]
Throughout this page/topic you consistently write "comply to" which isn't correct. It should be "comply with".
https://www.merriam-webster.com/thesaurus/comply%20(with)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c19b6ee-2218-cd97-96a4-2832c0302d7e
* Version Independent ID: da3ff20c-91cb-d760-708c-8e56af5d59d8
* Content: [Device compliance policies in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/device-compliance-get-started)
* Content Source: [memdocs/intune/protect/device-compliance-get-started.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/device-compliance-get-started.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@GenerAhl  The fix is in and should be live later today.
