### ISSUE TITLE
Is having Global Admin role sufficient?

### ISSUE THREAD

**Issue by beanska** [MicrosoftDocs/memdocs#1613]
_"Enter the user Global Administrator or Intune Administrator role credentials. The user account must have an assigned Intune license."_

Please verify this is correct. It might be a timing thing but I was unable to continue with just having the GA account I had to assign myself the Intune Administrator role to be able to sign-in to the connector. Should GA without IA be sufficient?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f93dd93-e003-36fc-02d6-07166537d914
* Version Independent ID: 1b860d13-bcf5-50da-89f9-ee12ece6edb2
* Content: [Enrollment for hybrid Azure AD-joined devices - Windows Autopilot](https://docs.microsoft.com/en-us/mem/autopilot/windows-autopilot-hybrid)
* Content Source: [memdocs/autopilot/windows-autopilot-hybrid.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/windows-autopilot-hybrid.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by msbemba** [comment]
@beanska Thank you for your feedback. I was able to test and find that the Global admin role is sufficient. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @beanska Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
