### ISSUE TITLE
Apple/AAD Federation for Shared iPads

### ISSUE THREAD

**Issue by PaulSIsaac** [MicrosoftDocs/memdocs#1614]
In the document entitled **What are shared iOS and iPadOS devices?**, in the Important considerations when choosing a shared device solution for iOS and iPadOS table, item AAD federation with Apple Business or School Manager says: Required. This enables users to sign in using their AAD username and password.

But on the very next line; Managed Apple ID it says: AAD federation automatically creates Managed Apple ID when user signs in on Shared iPad for the first time.
If AAD federation is not set up, Managed Apple IDs can be created manually in Apple Business or School Manager and shared with users for signing in.

This basically negates the REQUIRED in the previous row. If federation is not set up and Managed Apple Ids can be created manually, then the doesn't that mean that federation is not REQUIRED, but rather a preferred option to manual creation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc1b101e-c3df-3d36-8b2a-d9a0e5586a27
* Version Independent ID: a6d21c24-21b7-63e4-f5c9-eec2f1c56e50
* Content: [Shared iOS and iPadOS devices - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-shared-ios)
* Content Source: [memdocs/intune/enrollment/device-enrollment-shared-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/device-enrollment-shared-ios.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by yogkumgit** [comment]
@lenewsad Please help us in resolving this issue. Thanks

**Comment by lenewsad** [comment]
Hi @PaulSIsaac, thanks for reaching out to the Microsoft Intune Docs team for clarification about this information. The Azure AD instance must be federated in Apple Business Manager for the user group policy assignment to succeed. In instances that aren't federated, there will be additional, manual steps that you'll have to take in Apple Business Manager to set the devices up for users (creating and distributing their sign-in information, for example).  For more information about the automated capabilities federation enables, and how to configure Shared iPads in Intune, see [Configure Shared iPad](..https://learn.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-shared-ipad#configure-shared-ipad).  

CC @yogkumgit

**Comment by yogkumgit** [comment]
@PaulSIsaac Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
