### ISSUE TITLE
Limitations for using DEM account in co-managed scenario missing?

### ISSUE THREAD

**Issue by OneUser1** [MicrosoftDocs/memdocs#1615]
Intune support told me that there are possible issues when using a DEM account to do the user-driven Autopilot enrollment in a co-management scenario. I was not able to find information in the docs regarding any limitations. Please check this issue internally and if needed update this doc (or another one if needed?). Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7786d9c0-55b0-9bff-fc0a-f4ee70ee0615
* Version Independent ID: cf0c17a0-fdc7-e0af-db82-913e36d2ec7c
* Content: [Enroll devices using a device enrollment manager account - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-manager-enroll)
* Content Source: [memdocs/intune/enrollment/device-enrollment-manager-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/device-enrollment-manager-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by lenewsad** [comment]
Thanks for your question @OneUser1 and sorry that we missed your question for so long. I checked with the product team and didn't learn of any new limitations pertaining to the co-management scenario you described, so no updates are needed right now. If I find out any additional information, I'll be sure to update the doc.
