### ISSUE TITLE
Please add section regarding TLS 1.3 ...

### ISSUE THREAD

**Issue by bdcoder2** [MicrosoftDocs/memdocs#1616]
Can someone please add a sub-section regarding TLS 1.3 on **Windows Server**? - Have searched for hours and have found only a few (obscure) references as to when TLS 1.3 will be supported.  It would be nice if some **official** information was posted with regard to when TLS 1.3 will be supported on Windows Server (which versions?) along with information on how to enable it as well.

A list similar to the following would help: [https://sockettools.com/kb/windows-and-supported-tls-versions/](https://sockettools.com/kb/windows-and-supported-tls-versions/)

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6cf928e-5f22-82a4-1abe-ea3e28d6369d
* Version Independent ID: f7696046-487d-945d-278c-fc12c25ecd84
* Content: [Enable TLS 1.2 on servers - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/security/enable-tls-1-2-server)
* Content Source: [memdocs/configmgr/core/plan-design/security/enable-tls-1-2-server.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/security/enable-tls-1-2-server.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by bdcoder2** [comment]
... Several hours later -- found the following references:

[https://devblogs.microsoft.com/premier-developer/microsoft-tls-1-3-support-reference/](https://devblogs.microsoft.com/premier-developer/microsoft-tls-1-3-support-reference/)

... the link above, makes reference to the following page (the link text reads "TLS 1.3 **is also supported on Windows 1903**"), and the link goes to:
[https://docs.microsoft.com/en-us/windows/release-information/status-windows-10-1903](https://docs.microsoft.com/en-us/windows/release-information/status-windows-10-1903)

... which results in a 404 page being displayed (ugh).

As stated in the original post -- trying to find something **official** with regard to Windows Server TLS 1.3 support continues to be a bit of task (if you have no idea where to look).

**Comment by aczechowski** [comment]
Thanks @bdcoder2 for the feedback. At this time we don't have anything to document because we don't yet support it. We generally don't document what we don't support. As the blog post you referenced mentions, several of our product dependencies don't yet support it. Our engineering team is testing with it, but we need to wait for other dependencies to support it first.
I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by bdcoder2** [comment]
Thanks - makes sense -- however, if a section for TLS 1.3 was added it could simply state what you posted above -- at least then, for those of us that look for something "official", we would know that: 

a) "it is not officially supported" (at this time), however ...

b) It is in testing and we can expect support for it in the future

-- both points would seem to be relevant in the docs -- rather than combing through 15 other non-Microsoft sites that post all kinds of speculative articles about whether or not TLS 1.3 will ever be supported.

Thanks again.

**Comment by evanggt** [comment]
รองรับ
