### ISSUE TITLE
How can I set allowmetered for the standard SCCM Client Push

### ISSUE THREAD

**Issue by mf029** [MicrosoftDocs/memdocs#1617]
We utilise the client push within SCCM and would like to set the allowmetered, however it is not recognised by the client when its entered into the client push installation properties as /allowmetered or allowmetered

(admin edit: add article metadata for proper tracking)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3f3e45d-8f9d-aa5a-8b6a-d8c51c50d11e
* Version Independent ID: f5305fc4-894b-19dd-26c8-6f90901d4b1e
* Content: [Client installation parameters and properties - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/deploy/about-client-installation-properties#allowmetered)
* Content Source: [memdocs/configmgr/core/clients/deploy/about-client-installation-properties.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/deploy/about-client-installation-properties.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @mf029 for the feedback. A similar request came in through the product feedback last year, here's a summary of the response from engineering to that item:

> /AllowMetered is meant to be used directly in ccmsetup command line only. The client push properties are mostly used for client push but are also published to AD for WSUS/GPO installation. In the past, only MSI properties such as SMSSITECODE= can be specified there. Several years ago, some ccmsetup switches are also allowed but it's only a subset of them are allowed. The set doesn't include this new switch of /AllowMetered.
>
> We can consider adding that to the allow list but wonder if it's really useful. Because if the client can be pushed or can access AD, is it really on metered network only? Does it still need this switch? Appreciate if you can elaborate your use case a bit.

That should give you some context to help explain.

I'll use this issue to make some tweaks to the docs to note this.

After reading the above response, if you think that client push should support this parameter, please file [product feedback](https://docs.microsoft.com/mem/configmgr/core/understand/product-feedback) with more information about your use case to help the engineering team understand the need for the design change.

**Comment by aczechowski** [comment]
(internal reference 8867061)
