### ISSUE TITLE
Device type restriction - MDM/Windows 10

### ISSUE THREAD

**Issue by Remi007** [MicrosoftDocs/memdocs#1619]
Hello,

The content of the document seems to be imprecise in what form to provide the version of the OS/Windows 10 in the "Device  type restriction"
In the chapter "Create a device type restriction"  (https://docs.microsoft.com/en-us/mem/intune/enrollment/enrollment-restrictions-set#create-a-device-type-restriction), in point 5:  "Windows supports major.minor.build.**rev** for Windows 10 only"

but in the "Note" in the same point: "Windows 10 does not provide the rev number during enrollment so for instance if you enter in 10.0.17134.100 and the device is 10.0.17134.174 it will be blocked during enrollment."

Check the screenshot:
![image](https://user-images.githubusercontent.com/17315868/118614816-6de10780-b7c0-11eb-9ff1-45d7ef7b5c93.png)

BR,
Remi
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e8c2d91-8808-a504-da13-526b152a5cfe
* Version Independent ID: 037b60a6-d6b5-75ad-1933-39d0f7a69048
* Content: [Set enrollment restrictions in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/enrollment-restrictions-set?source=docs)
* Content Source: [memdocs/intune/enrollment/enrollment-restrictions-set.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/enrollment-restrictions-set.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by msbemba** [comment]
@Remi007 Thank you for your feedback. I have updated the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2484

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Remi007 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
