### ISSUE TITLE
Missing prerequisites on user permission

### ISSUE THREAD

**Issue by chboeye** [MicrosoftDocs/memdocs#162]
The intune "remote tasks" privilege is not sufficient alone, you need to have some permission in MEM CM too. This seems obvious because you are "extending" your privilege to Intune but this deserve a note or something.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2eb4acb-7311-79d3-3daa-6f27ea42aee7
* Version Independent ID: 123f2a5c-04c1-8184-05a4-689d9c591981
* Content: [Microsoft Endpoint Manager tenant attach - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/tenant-attach/device-sync-actions)
* Content Source: [memdocs/configmgr/tenant-attach/device-sync-actions.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/tenant-attach/device-sync-actions.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
@chboeye
Hey Charles, I'm sending you an email. I'm pretty sure I found you in the GAL =)
