### ISSUE TITLE
Bitlocker Defaults with Intune

### ISSUE THREAD

**Issue by gatewood502** [MicrosoftDocs/memdocs#1620]
Does bitlocker always configure with 128bit with Azure AD joined and MSA or can it be set to use 256-bit encryption instead?

This is from the article:

However, on Azure AD Join and Microsoft Account (MSA) registration/login automatic encryption can apply enabling BitLocker at XTS-AES 128-bit encryption.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcec0953-586b-f8aa-5620-685199a24caf
* Version Independent ID: 0bc2907b-2300-058b-db4d-9a46f11f673d
* Content: [Intune endpoint security disk encryption policy settings](https://docs.microsoft.com/en-us/mem/intune/protect/endpoint-security-disk-encryption-profile-settings)
* Content Source: [memdocs/intune/protect/endpoint-security-disk-encryption-profile-settings.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/endpoint-security-disk-encryption-profile-settings.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@gatewood502 Thank you for your feedback. You are correct, XTS- AES 128-bit is the Windows default encryption method. 

However, you can change it to 256 by configuring. For more details, you can review the below article

https://docs.microsoft.com/en-us/windows/client-management/mdm/bitlocker-csp#encryptionmethodbydrivetype

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @gatewood502 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
