### ISSUE TITLE
What version field is String (version) detecting?

### ISSUE THREAD

**Issue by MarcLaf** [MicrosoftDocs/memdocs#1621]
When using File as a detection rule and setting method to String (version), is this querying the files File Version field or Product Version field? There are no examples of this on the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca840cce-3b99-3009-c8fa-d5fab6ae37d0
* Version Independent ID: 928b9e37-626a-8d50-c6a1-ac0b5cad4be4
* Content: [Add and assign Win32 apps to Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-win32-add)
* Content Source: [memdocs/intune/apps/apps-win32-add.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/apps-win32-add.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@MarcLaf Thank you for your feedback. It queries the file version whether it is associated with a 32-bit app on 64-bit clients When using File as a detection rule.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @MarcLaf Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
