### ISSUE TITLE
Kernel extensions on m1

### ISSUE THREAD

**Issue by ThomasDBosboom** [MicrosoftDocs/memdocs#1623]
It is still possible to use kernel extensions on M1 Macs - it requires an Apple Silicon optimized KEXT + some work to install.
 https://support.apple.com/guide/deployment-reference-macos/kernel-extensions-in-macos-apd37565d329/web
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 369bc918-1853-e861-80cf-98a7ad2779b5
* Version Independent ID: dcde8fca-d69c-b718-6b26-d7abf00e43b3
* Content: [Create macOS system and kernel extensions with Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/kernel-extensions-overview-macos)
* Content Source: [memdocs/intune/configuration/kernel-extensions-overview-macos.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/kernel-extensions-overview-macos.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@ThomasDBosboom That's an interesting link. We've added it. Thank you! Changes should be live later today sometime.
