### ISSUE TITLE
Tips statement is wrong. 

### ISSUE THREAD

**Issue by limjianan** [MicrosoftDocs/memdocs#1625]
Previously, IOS can use MFA authenticator as broker and android will need the intune company portal.
This statement now is the opposite, which is incorrect.
Can someone verify this and correct 

########### 
[!TIP] The Company Portal app is required by Intune mobile application management (MAM) scenarios. On Android devices, the Authenticator app includes functions of the broker and might be used as the broker in some situations, such as when the Authenticator was installed before the Company Portal app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca76fcaf-979f-7b6b-c410-34080685d415
* Version Independent ID: eaceac76-73c4-c586-952c-8dfa90390c6e
* Content: [App-based Conditional Access with Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/app-based-conditional-access-intune)
* Content Source: [memdocs/intune/protect/app-based-conditional-access-intune.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/app-based-conditional-access-intune.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@limjianan    This Note was added to content in December 2020 abased on an investigation by our engineering team. For reference, see https://github.com/MicrosoftDocs/memdocs/issues/1045, which is another GitHub issue submitted to this same article.
