### ISSUE TITLE
CMG example scenarios

### ISSUE THREAD

**Issue by dmalanga999** [MicrosoftDocs/memdocs#1627]
I'd like to recommend adding a scenario to describe how globally dispersed MECM clients connect to the CMG and access content located near their Azure region. We have our Primary Site in the UK with clients from the US and India accessing content for software updates and app deployments.  Is the content copied to regions globally? Is there a way to design CMG placement by Azure region?

Thanks,
dan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07d4e4f7-68ed-e604-b577-2c18617d1c2e
* Version Independent ID: 1ce10bc0-2a6d-405a-a9ae-46adfaac8fe6
* Content: [Plan for cloud management gateway - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/plan-cloud-management-gateway#hierarchy-design)
* Content Source: [memdocs/configmgr/core/clients/manage/cmg/plan-cloud-management-gateway.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/cmg/plan-cloud-management-gateway.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @dmalanga999 for the feedback. See the following tip in the article:

> You don't need to deploy more than one CMG for the purposes of geolocation. The Configuration Manager client is mostly unaffected by the slight latency that can occur with the cloud service, even when geographically distant.

Internet communication generally impacts latency, which affects real-time traffic. Content just needs bandwidth for faster downloads. There should be negligible performance difference between different Azure regions in this regard.

**Comment by dmalanga999** [comment]
Thanks

**Comment by aczechowski** [comment]
Another good point that one of our PMs reminded me about, is this bit from the article on [cloud distribution points](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/hierarchy/use-a-cloud-based-distribution-point):

> Even though you install cloud distribution points in specific regions of Azure, clients aren't aware of the Azure regions. They randomly select a cloud distribution point. If you install cloud distribution points in multiple regions, and a client receives more than one in the content location list, the client might not use a cloud distribution point from the same Azure region.
