### ISSUE TITLE
Clarify user-defined option

### ISSUE THREAD

**Issue by jpcast88** [MicrosoftDocs/memdocs#1628]
Under ASR rules profile [section](https://docs.microsoft.com/en-us/mem/intune/protect/endpoint-security-asr-profile-settings#attack-surface-reduction-rules) some rules have a 'user defined' option. Can someone clarify what this does and/or provide use cases of how this would work on an endpoint?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f71f2647-ec06-5301-015f-9b29df00f9da
* Version Independent ID: 00b110b0-25a3-a7de-0955-db33d7f0f036
* Content: [Intune endpoint security Attack surface reduction settings](https://docs.microsoft.com/en-us/mem/intune/protect/endpoint-security-asr-profile-settings)
* Content Source: [memdocs/intune/protect/endpoint-security-asr-profile-settings.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/endpoint-security-asr-profile-settings.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
The use of _User Defined_ remains an enigma that I’ve not been able to get an answer for. The endpoint security policies included this option for five separate settings, but this option doesn’t appear to have a functional use, at least that can be configured through Intune policy today. The use and concept for Attack Surface Reduction Rules are detailed in the content for Microsoft Defender for Endpoint (https://docs.microsoft.com/microsoft-365/security/defender-endpoint/enable-attack-surface-reduction?view=o365-worldwide ), and _User Defined_ isn’t part of their background.  

Today, you can configure policy for these same settings via the [Settings Catalog](https://docs.microsoft.com/mem/intune/configuration/settings-catalog), in which this option doesn’t exist. Instead, the available options align to what's described in the Defender content for these rules.  This reinforces that its an unused or unintended setting.

The Settings Catalog uses a new settings format that directly aligns to the underling configuration service providers (CSP) for a setting (when they are available), and which provide a clearer description for settings.  This new settings format should be coming to the endpoint security policies soon, which will make the question of this odd option a non-issue soon.
If you still need more information about this, I recommend opening a support issue to pursue that.

**Comment by jpcast88** [comment]
@Brenduns I appreciate the detailed response and follow up on this. This should be all the clarification I need moving forward. Thanks.
