### ISSUE TITLE
Clarification for Device Prerequisites for Silently enable BitLocker on devices

### ISSUE THREAD

**Issue by ThomasBalder** [MicrosoftDocs/memdocs#163]
Is it true that devices that are -hybrid-joined do not qualify for drive encryption with Intune? If so, could you make that more clear in the prerequisites? Now it's kind of confusing because of the use for Client-driven recovery password rotation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54cccf1d-81fd-5331-aee7-59a35b39cb15
* Version Independent ID: 81d14392-fe74-4fd9-047f-7b8292d84f0c
* Content: [Encrypt devices with the platforms supported encryption method - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/encrypt-devices#feedback)
* Content Source: [memdocs/intune/protect/encrypt-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/encrypt-devices.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@ThomasBalder  I've been seeking confirmation from our engineering team on this for some time and am now tracking this through an internal content bug. However, via another more recent github issue on this same question, for which more information was provided that concurs, that hybrid-joined devices can't be enabled silently. (see https://github.com/MicrosoftDocs/memdocs/issues/255)   So, while I've yet to get official confirmation from our product group, this seems to be accurate. 

With this tracked internally, I'll be closing this github issue. Once the details are worked out and ready to revise in content, I'll update you by adding an update to this GitHub issue. If there are other wrinkles to share that might make the scenario plausible, I'll also comment on that.
