### ISSUE TITLE
Associate apps with this connection Example?

### ISSUE THREAD

**Issue by o0MattE0o** [MicrosoftDocs/memdocs#1633]
Associate apps with this connection? do you have an example on how to create the CSV that this option is looking for? 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e16582-5730-9f22-2ced-686fc074d5c0
* Version Independent ID: b334cc28-f6ed-103f-3770-4cddb42e666c
* Content: [Windows 10 VPN settings in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/vpn-settings-windows-10)
* Content Source: [memdocs/intune/configuration/vpn-settings-windows-10.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/vpn-settings-windows-10.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
https://msazure.visualstudio.com/Intune/_workitems/edit/10114470

**Comment by MandiOhlinger** [comment]
@o0MattE0o Good feedback. Thank you! We added some examples. Changes should be live sometime tomorrow.
