### ISSUE TITLE
Critical changes not mentioned in documentation

### ISSUE THREAD

**Issue by jenoola** [MicrosoftDocs/memdocs#1637]
I was trying to make Intune work on an Android 7.1.1 device and thought everything should be fine since the page states Android 4.4+ is required, but after 3 hours (two of them with Helpdesk) of troubleshooting and re-installing everything in every order imaginable I got a message that Android 9 is required. Why wasn't the documentation updated with this critical change? Why nothing is clearly stated in the logs (I was given, say, incident IDs 7THMYNV7 and 8EEAW68H)?

Steps taken:
1) Install MS Authenticator
2) Register for phone authentication
3) Install, say, Outlook
4) When prompted by Outlook, install Intune
5) Log into Intune with company credentials 
6) At this point the app just proceeds and given no prompt to accept terms and conditions
7) Go to devices, choose My Android
8) Device status settings are Unknown, tap Check device settings 
9) Get an error saying "something happened, upload logs and email tech support"
10) Get the incident ID for uploaded logs

The first three to five steps have been tried in MANY different orders, one of them, for some reason, resulted in the prompt to accept terms and conditions in Intune, and then I got a message that Android 9 is required.

It's a shame for a customer-oriented company to ignore internal customers and neither update documentation nor inform Helpdesk about new requirements. I wasted 3 hours of my work time on this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b4eb41-d66a-b1c3-b417-4946643ba3d6
* Version Independent ID: 6f6e2af0-eb71-16e8-62d0-d86c73a56332
* Content: [Enroll Android device with Intune Company Portal](https://docs.microsoft.com/en-us/mem/intune/user-help/enroll-device-android-company-portal)
* Content Source: [memdocs/intune/user-help/enroll-device-android-company-portal.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/user-help/enroll-device-android-company-portal.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by yogkumgit** [comment]
@lenewsad Please help us in resolving this issue. Thanks

**Comment by lenewsad** [comment]
Hi @jenoola, thank you for reaching out to the Intune Docs team. I'm sorry for the frustration this issue caused and wanted to follow up to let you know that we've since updated the supported versions in the article. In addition, I'm opening an internal work item to have this article reviewed again by our product team, to make sure everything is up to date for October 2022 and on. 

FYI @yogkumgit
