### ISSUE TITLE
LDAPS and port 636

### ISSUE THREAD

**Issue by Tripp2loo** [MicrosoftDocs/memdocs#164]
Should we also include ports 636. As of CM 1910 it now supports LDAPS.
Enforce LDAP channel binding and LDAP signing
The security of Active Directory domain controllers can be improved by configuring the server to reject Simple Authentication and Security Layer (SASL) LDAP binds that do not request signing or to reject LDAP simple binds that are performed on a clear text connection. Starting in version 1910, Configuration Manager supports enforcing LDAP channel binding and LDAP signing. For more information, see https://support.microsoft.com/en-us/help/4520412/2020-ldap-channel-binding-and-ldap-signing-requirements-for-windows

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0976187e-be77-b141-9269-7064d7f1371d
* Version Independent ID: a4a4fdea-c0cd-4a5e-d298-c0b2ede10506
* Content: [Ports used for connections - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/hierarchy/ports#feedback)
* Content Source: [memdocs/configmgr/core/plan-design/hierarchy/ports.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/hierarchy/ports.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Tripp2loo for the feedback. I'm putting in a change to add that info. It should publish live later this afternoon.

**Comment by qafzal** [comment]
> Should we also include ports 636. As of CM 1910 it now supports LDAPS. Enforce LDAP channel binding and LDAP signing The security of Active Directory domain controllers can be improved by configuring the server to reject Simple Authentication and Security Layer (SASL) LDAP binds that do not request signing or to reject LDAP simple binds that are performed on a clear text connection. Starting in version 1910, Configuration Manager supports enforcing LDAP channel binding and LDAP signing. For more information, see https://support.microsoft.com/en-us/help/4520412/2020-ldap-channel-binding-and-ldap-signing-requirements-for-windows
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 0976187e-be77-b141-9269-7064d7f1371d
> * Version Independent ID: a4a4fdea-c0cd-4a5e-d298-c0b2ede10506
> * Content: [Ports used for connections - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/hierarchy/ports#feedback)
> * Content Source: [memdocs/configmgr/core/plan-design/hierarchy/ports.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/hierarchy/ports.md)
> * Product: **configuration-manager**
> * Technology: **configmgr-core**
> * GitHub Login: @aczechowski
> * Microsoft Alias: **aaroncz**

Hello kindly can you please share link of release notes stating sccm suport ldap binding and signing , 

Also a customer want to use port 636 instead of 389 
And port 3269 instead of 3268 . is it possible to do ?
