### ISSUE TITLE
Missing new policy requirement

### ISSUE THREAD

**Issue by jandreacola** [MicrosoftDocs/memdocs#1643]
Missing the new policy requirement documented here - https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-configuration-manual

As of May 10, 2021, a new policy is required to use Update Compliance: "Allow Update Compliance Processing." For more details, see the Mobile Device Management policies and Group policies tables.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7024ad8-b24b-598c-8b16-2da8bc15e9e4
* Version Independent ID: 230e96a7-e771-e6dd-d5f4-ac8b514fb4d4
* Content: [Use Update Compliance reports for Windows Updates in Microsoft Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/windows-update-compliance-reports#use-update-compliance)
* Content Source: [memdocs/intune/protect/windows-update-compliance-reports.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/windows-update-compliance-reports.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@jandreacola Thanks for this comment!  We have some changes coming to this article as earlier this week, new content was published to the Update Compliance content which provides [much improved details for configuring MEM devices for Update Compliance](https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-configuration-mem
) and that new article includes the link you mention. 

As there is a pending task to revise this article to redirect to that new guidance, we won't be revising this article to add that link at this time. Those revisions should be complete sometime next week. Should the revisions leave room to add this link to this article, I'll have it added as part of that work.
