### ISSUE TITLE
Org allowed accounts mode Conflict

### ISSUE THREAD

**Issue by BLTTEST** [MicrosoftDocs/memdocs#1645]
Hi Teams,

This article says: "At this time, only Office for Android supports org allowed accounts mode." However, another article says "The following apps process the above app configuration and only allow organization accounts" and lists Office for iOS. 

https://docs.microsoft.com/en-us/mem/intune/apps/app-configuration-policies-use-ios#allow-only-configured-organization-accounts-in-multi-identity-apps

Please kindly check which one is correct.

Best Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 453cfdb5-f571-0d84-5e4a-f7a9e98e7c8b
* Version Independent ID: 462d1b00-8320-b4d6-cead-8e0ef26c4d35
* Content: [Manage Office for iOS and Android with Intune](https://docs.microsoft.com/en-us/mem/intune/apps/manage-microsoft-office)
* Content Source: [memdocs/intune/apps/manage-microsoft-office.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/manage-microsoft-office.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@BLTTEST Thank you for your feedback. You are correct, the following apps that process the above app configuration and only allow organization accounts:

Edge for iOS (44.8.7 and later)
Office, Word, Excel, PowerPoint for iOS (2.41 and later)
OneDrive for iOS (10.34 and later)
OneNote for iOS (2.41 and later)
Outlook for iOS (2.99.0 and later)
Teams for iOS (2.0.15 and later)

The document has been updated with details on configuring the org allowed accounts mode in both Android and IOS.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @BLTTEST Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
