### ISSUE TITLE
Provide More Detail Around How Modern Standby Power Plans Work

### ISSUE THREAD

**Issue by nkasco** [MicrosoftDocs/memdocs#1646]
As of CM 2010 the High Performance Power Plan functionality has been changed to better support machines with modern standby. There is a bit of key functionality not documented that would be extremely helpful to sysadmins:

- Modifies standby, monitor, disk, and hibernate timeout values (AC and DC power) to 0 for this temporary power plan which prevents these machines from falling asleep during OSD.

Product team has confirmed this is how this works here: https://configurationmanager.uservoice.com/forums/300492-ideas/suggestions/42189484-prevent-devices-with-modern-standby-from-going-to

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c22e3a22-310a-c33f-69a9-90c04e29a7f9
* Version Independent ID: 57821b74-d098-ccf5-65d0-131db824f50d
* Content: [Manage task sequences - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/osd/deploy-use/manage-task-sequences-to-automate-tasks#known-issue)
* Content Source: [memdocs/configmgr/osd/deploy-use/manage-task-sequences-to-automate-tasks.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/osd/deploy-use/manage-task-sequences-to-automate-tasks.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @nkasco for the feedback! I put in a pull request to add that information. It should publish live later today.

**Comment by nkasco** [comment]
Looks good to me. Thanks!
