### ISSUE TITLE
Console Extension SDK for CB2103, new extension

### ISSUE THREAD

**Issue by jemmail** [MicrosoftDocs/memdocs#1647]
When will Microsoft release an updated version of the SDK for new console extension released in CB 2103 ?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a0e72c9-c1da-5d21-cc99-6837b9b77b74
* Version Independent ID: cad48fd3-8440-8b48-7c37-2bfc815aba58
* Content: [Console Extension Architecture - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/develop/core/servers/console/console-extension-architecture)
* Content Source: [memdocs/configmgr/develop/core/servers/console/console-extension-architecture.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/develop/core/servers/console/console-extension-architecture.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @jemmail, thanks for the feedback. The short answer: soon. 😁 We have a draft that we've shared with MVPs, and plan to have more publicly available content in the future.
