### ISSUE TITLE
Add remote lock for windows 10 desktop

### ISSUE THREAD

**Issue by mathie25** [MicrosoftDocs/memdocs#165]
This is a basic feature that is not available on windows 10 desktop, but is available on other devices... It should be available. macOS devices are simpler to manage than Windows 10 devices

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c79f5e46-0615-682c-0368-5a14cfa738e7
* Version Independent ID: 08094776-efc7-d7b1-0b82-0aee1dac5634
* Content: [Lock devices with Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/remote-actions/device-remote-lock#feedback)
* Content Source: [memdocs/intune/remote-actions/device-remote-lock.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/remote-actions/device-remote-lock.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@mathie25 Thanks for taking the time to provide feedback on Microsoft Intune! This is an interesting feature idea, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. See the [Microsoft Intune Feedback]( https://microsoftintune.uservoice.com/forums/291681-ideas). I'm closing this issue as there's nothing actionable for docs at this time.
