### ISSUE TITLE
Completely misleading page

### ISSUE THREAD

**Issue by svenhallauer** [MicrosoftDocs/memdocs#1650]
The term build-in apps is widely used for applications that are bundled into the OS.  Things such as Mail, Calendar, Safari.  But for some reason this article seems to be about Microsoft apps and maybe others that support Intune App Protection Policy - none of which are build-in.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7a68e9c-e8b3-2b04-147e-ac80c355e1e5
* Version Independent ID: 6ce17516-1f98-d0c4-04a9-3cc606252beb
* Content: [Add built-in apps to mobile devices using Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-add-built-in)
* Content Source: [memdocs/intune/apps/apps-add-built-in.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/apps-add-built-in.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@svenhallauer Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2519
Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @svenhallauer Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by svenhallauer** [comment]
Thanks!
