### ISSUE TITLE
Prerequisites

### ISSUE THREAD

**Issue by mgebbinck** [MicrosoftDocs/memdocs#1652]
It would be good to articulate that the licenses need to be assigned **to the account** that is running the guided scenario. 

This was not obvious to me and I assumed that those licenses need to available within the tenant. Specifically since small and medium business, would run with Microsoft 365 Business Premium (that includes all licenses) but a global admin would not get a Microsoft 365 Business Premium assigned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f62628a8-9de9-be85-f349-3d0d4d397ab8
* Version Independent ID: fe01f18c-b003-1eb7-bb8c-97d1db8ef3fa
* Content: [Use Windows cloud configuration in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/fundamentals/cloud-configuration)
* Content Source: [memdocs/intune/fundamentals/cloud-configuration.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/cloud-configuration.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@mgebbinck That's a very good point. Thank you! Any interest in adding your recommended doc changes in a pull request (PR)? Seeing the doc changes in your words helps us understand the intent better, if that makes sense.

If you've never created a PR before, the steps are at [https://github.com/MicrosoftDocs/memdocs](https://github.com/MicrosoftDocs/memdocs). Just scroll past the folder view.

**Comment by MandiOhlinger** [comment]
@mgebbinck The article now included this information. Thank you! Changes should be live later today.
