### ISSUE TITLE
Clarification on HA scenarios

### ISSUE THREAD

**Issue by russrimm** [MicrosoftDocs/memdocs#1653]
Might be worth mentioning that in an HA scenario it will only check the active node, and that the SQL broker check will only check the active node as well?  I'll be happy to submit this as a doc edit if this is confirmed to be the case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab3d4fa9-01dd-6e1f-118e-53a36cd5cedc
* Version Independent ID: 6652b46c-92c6-88c8-f70f-4a0f3afe9bc6
* Content: [Monitor scenario health - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/manage/scenario-health)
* Content Source: [memdocs/configmgr/core/servers/manage/scenario-health.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/manage/scenario-health.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @russrimm for the feedback. I got a quick response from the engineer:

> It is correct. For the scenario health related to SQL Service broker, it only verify the SQL service broker e2e. (technically the active node of the SQL always on env)
> For client action scenario health, it is validating certain components on the site server, if there is active/passive site server, it is validating the components running on the active site server.

If you want to drop a pull request to add a blurb about this, I'll happily review and approve 😄
