### ISSUE TITLE
CMG Connection Point -> MP

### ISSUE THREAD

**Issue by nickekallen** [MicrosoftDocs/memdocs#1658]
In addition to port 443, port 80 (TCP) is required to a Management Point

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0976187e-be77-b141-9269-7064d7f1371d
* Version Independent ID: a4a4fdea-c0cd-4a5e-d298-c0b2ede10506
* Content: [Ports used for connections - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/hierarchy/ports)
* Content Source: [memdocs/configmgr/core/plan-design/hierarchy/ports.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/hierarchy/ports.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @nickekallen for the feedback. Is your environment using enhanced HTTP? I wonder if I just never updated this list when changes were made to allow the MP to be HTTP, instead of as it was originally when the MP had to be HTTPS.

**Comment by nickekallen** [comment]
Hello,

yeah, eHTTP would be the case. Per the link to more detailed docs - it is 443 or 80. But... if testing the setup using the connectivity analyzer - port 443 is used. So - it should be an and.
