### ISSUE TITLE
Intune doesn't Capture and inventor ICCID for Android Dedicated and Fully Managed Devices

### ISSUE THREAD

**Issue by FadiJo** [MicrosoftDocs/memdocs#166]
[we need to update the Doc as below :
1. add Asterisk (*) beside Android for ICCID.
2. Add ICCID with the Phone number in the Note Box ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905c303e-4306-38ec-2a30-4852a8c1bc2b
* Version Independent ID: ceb7e815-e19a-386f-902c-6e6bf53d5766
* Content: [View device details with Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/remote-actions/device-inventory#feedback)
* Content Source: [memdocs/intune/remote-actions/device-inventory.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/remote-actions/device-inventory.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
(7130452)

**Comment by jimmyeao** [comment]
Would love to see this fixed - raised with O365 support who blamed the Google API. Like many others, our billing revolves around ICCID numbers, we absolutely must have these available. How can we best escalate this to the engineering teams?

**Comment by ErikjeMS** [comment]
Repinged PM....

**Comment by ErikjeMS** [comment]
Repinged PM...

**Comment by MandiOhlinger** [comment]
@FadiJo You are correct. Thank you. We updated this article to reflect this information. Changes should be live tomorrow sometime. 

In the future, for doc updates like this, it'd be great if you created a pull request (PR) with your recommended changes. We review every PR before it publishes. We want and encourage community contributions to our docs.

Thanks again.
