### ISSUE TITLE
Example formatting is not good

### ISSUE THREAD

**Issue by FlashGordon7** [MicrosoftDocs/memdocs#1660]
Example is on one line
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afc639e9-9f0e-b677-1dfc-7ba61e82dbfa
* Version Independent ID: 7f5379f8-9295-b299-3c9c-c7605751f25e
* Content: [Apply Custom Client Settings - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/develop/core/clients/programming/how-to-apply-custom-client-settings)
* Content Source: [memdocs/configmgr/develop/core/clients/programming/how-to-apply-custom-client-settings.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/develop/core/clients/programming/how-to-apply-custom-client-settings.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @FlashGordon7 for the feedback, I'll revise.
