### ISSUE TITLE
Cert Template OS Level

### ISSUE THREAD

**Issue by ercgoodman** [MicrosoftDocs/memdocs#1662]
Hello!  The documentation says to select 2003 for the compatibility when duplicating the certificate templates.  Is that still required?  I have several clients that have asked why this is the case but I cannot find anything else official as to why this cannot be set to anything higher.  If this is still required, could you possible elaborate as to why so we can send appropriate links/blurbs to the inquiring security teams?  If it's potentially not required anymore could you please update the documentation?  If it's not an either/or situation, would you kindly consider modifying the documentation to discuss why you would chose certain compatibility options over others, along with their ramifications, etc?

Thanks in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a41a19c-d822-1ee7-80a7-3672e1d47077
* Version Independent ID: 305cb6a2-adf1-87d5-212e-456e945cf5fd
* Content: [Example PKI certificate deployment - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/network/example-deployment-of-pki-certificates#to-create-and-issue-the-web-server-certificate-template-on-the-certification-authority)
* Content Source: [memdocs/configmgr/core/plan-design/network/example-deployment-of-pki-certificates.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/network/example-deployment-of-pki-certificates.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Closing, see [Twitter thread](https://twitter.com/goodmane/status/1399807363264229379)
