### ISSUE TITLE
Legacy link about Salesforce

### ISSUE THREAD

**Issue by BLTTEST** [MicrosoftDocs/memdocs#1663]
Hi Teams,

In the "See also" section of this page, a legacy link of "Salesforce App and Microsoft Intune" is still being quoted: https://gallery.technet.microsoft.com/Salesforce-App-and-Intune-c47d44ee/file/188000/1/Salesforce%20App%20and%20Intune%20for%20external.pdf

This also happens in the "See also" section of another page: https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-framework#see-also

Considering gallery technet has been retired, I think the new link to the pdf should be updated. Please kindly check this.

Best Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17955fd7-d652-8f0e-4446-00b8628d58cc
* Version Independent ID: 46755b3c-43a5-f5c9-0b74-ce2b7ede7d40
* Content: [App protection policies overview - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policy)
* Content Source: [memdocs/intune/apps/app-protection-policy.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-protection-policy.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @BLTTEST Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
