### ISSUE TITLE
The Reporting and Telemetry section needs updating.

### ISSUE THREAD

**Issue by TeamTerry** [MicrosoftDocs/memdocs#1664]
https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-windows-10#reporting-and-telemetry - 
This section needs updating as the Intune portal has different options that are not reflected in this artical.
Options available are -
- Not configured
- Diagnostic data off
- Required
- Enhanced (1903 and earlier)
- Optional

Please update urgently with a description of each option.

![image](https://user-images.githubusercontent.com/22141439/120544362-b0494c00-c430-11eb-8b96-9fa4b1f1bd8e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7874ff8b-727f-b013-27f8-fd714ebb53a5
* Version Independent ID: 05674b42-613e-d54d-2895-1f2db41b613a
* Content: [Device restriction settings for Windows 10 in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-windows-10#reporting-and-telemetry)
* Content Source: [memdocs/intune/configuration/device-restrictions-windows-10.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/device-restrictions-windows-10.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
The article includes the new options.

**Comment by TeamTerry** [comment]
Thanks for updating this Team !!
