### ISSUE TITLE
PowerShell command is not found

### ISSUE THREAD

**Issue by susanthasilva** [MicrosoftDocs/memdocs#1665]
Cannot find the PowerShell command. Looks like it's not available in the given repository.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea4a659b-65d0-26ec-c36a-9a21a72a09a8
* Version Independent ID: bff44b73-9021-6659-e212-66349c759989
* Content: [Manually register devices with Windows Autopilot](https://docs.microsoft.com/en-us/mem/autopilot/add-devices)
* Content Source: [memdocs/autopilot/add-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/add-devices.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
Are you talking about https://www.powershellgallery.com/packages/Get-WindowsAutoPilotInfo/3.5

The command is there. What is the exact message you are getting?

**Comment by Morcie** [comment]
This is the error I get when I try to run "Install-Script -Name Get-WindowsAutoPilotInfo"

WARNING: Source Location 'https://www.powershellgallery.com/api/v2/package/Get-WindowsAutoPilotInfo/3.5.0' is not
valid.
PackageManagement\Install-Package : Package 'Get-WindowsAutoPilotInfo' failed to download.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:3538 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\Users\MORC\A...PilotInfo.nupkg:String) [Install-Package], Excep
   tion
    + FullyQualifiedErrorId : PackageFailedInstallOrDownload,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPac
   kage

**Comment by frankroj** [comment]
Thanks @susanthasilva for taking the time to share this with the Windows documentation team. I apologize for the time it took to get back to you regarding this feedback item. We have tested the scripts on the page and they work as expected. It appears that the problem may be with something in your environment. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Microsoft](https://learn.microsoft.com/answers/tags/415/intune). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Windows Autopilot support information](https://support.microsoft.com/windows) to find your available support options.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
