### ISSUE TITLE
Ping-like messages : elaborate 

### ISSUE THREAD

**Issue by jemmail** [MicrosoftDocs/memdocs#1666]
"It sends **ping-like** message" : can you elaborate and tell what are those "ping-like" messages please ?

We do have some computers which are online (via VPN for example). They can communicate with their MP, but are still "offline" in the console, We would like to troubleshoot and would like to know what are those "ping-like" message (port, protocol),
thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42c9ccff-7126-eab6-2d00-d8a8814c10b8
* Version Independent ID: 12cd6269-5e3b-12a2-1616-d52c36d07d62
* Content: [Monitor clients - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/monitor-clients)
* Content Source: [memdocs/configmgr/core/clients/manage/monitor-clients.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/monitor-clients.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @jemmail, I think it's using the client notification channel. See the ports reference article for [Client->MP traffic](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/hierarchy/ports#BKMK_PortsClient-MP).

Would be worthwhile to add a reference to that in this article, I'll use this issue to track that change.

Also, this isn't the best place to assist with troubleshooting. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://docs.microsoft.com/answers/products/mem). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

I don't know when I'll get time to make the change to add the cross-reference, so please let me know if you find out anything further that might impact what we have documented for this.
