### ISSUE TITLE
List of public Certificate Authorities in the article.

### ISSUE THREAD

**Issue by doublewooly** [MicrosoftDocs/memdocs#1668]
"Use a certificate from a public and globally trusted certificate provider. For example, but not limited to, DigiCert, Thawte, or VeriSign."

Both Thawte and VeriSign, by a history of mergers and acquisition, are essentially Digicert at this point.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ade53de5-3c7a-669d-2786-41d14fb6cea8
* Version Independent ID: 036c9651-1adc-fdcb-7d67-32d212e574e5
* Content: [CMG server authentication certificate - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/server-auth-cert)
* Content Source: [memdocs/configmgr/core/clients/manage/cmg/server-auth-cert.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/cmg/server-auth-cert.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @doublewooly for the feedback! At this point I may just remove those references. There are several instances in other articles as well that I'll clean up. An internet search for "globally trusted certificate provider" returns multiple sites with suggestions and recommendations, that will be a better source than whatever list we have at any given time. And helps us avoid looking like we're recommending or promoting a specific vendor.

**Comment by doublewooly** [comment]
That seems like an ideal solution. Thank you.

**Comment by aczechowski** [comment]
Closing the issue, the change merged a couple of weeks ago. Although it won't publish live until 2107 CB releases... soon 😉
