### ISSUE TITLE
Reporting and Telemetry Needs to be Updated

### ISSUE THREAD

**Issue by gmarnold25** [MicrosoftDocs/memdocs#1669]
"Configure Telemetry as part of a [Device Restriction policy](../configuration/device-restrictions-configure.md) for Windows 10 or later. In the device restriction profile, under *Reporting and Telemetry*, configure the **Share usage data** with a minimum value of **Basic**. Values of **Enhanced** or **Full** are also supported."

The telemetry option described here says Enhanced is no longer supported on 1909 and later. Basic is now listed as required. And Full is now listed as Optional.

**Comment by Brenduns** [comment]
The quoted text appears in both _windows-10-feature-updates.md_ and _windows-10-update-rings.md_.

**Comment by Brenduns** [comment]
@gmarnold25   Thanks for this submission. Looks like the product team revised some UI here including the settings that are available for **Share usage data** in the device restriction profiles to align to the underlying Windows CSP for AllowTelemetry - but didn't alert docs.  I've submitted a content update to  align the doc references to those Telemetry, changes. The updates should be live later today.

That will also include a link to the article from Windows that defines those changes:  https://docs.microsoft.com/en-us/windows/privacy/changes-to-windows-diagnostic-data-collection.
