### ISSUE TITLE
Is there a time limit on /lifetime

### ISSUE THREAD

**Issue by strunker** [MicrosoftDocs/memdocs#167]
Nothing is specified in the documentation that i am seeing.  thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60a7510b-10d9-e7e2-f848-d57d69d7fe10
* Version Independent ID: d4e9a557-ca23-3727-52b8-b81c6f767757
* Content: [Token-based authentication for CMG - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/deploy/deploy-clients-cmg-token#feedback)
* Content Source: [memdocs/configmgr/core/clients/deploy/deploy-clients-cmg-token.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/deploy/deploy-clients-cmg-token.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @strunker, good feedback. The maximum value is 10,080 (seven days). I'm fixing it now, should publish live later this afternoon.
