### ISSUE TITLE
Intune doesn't support IMEI 

### ISSUE THREAD

**Issue by nahira-ms** [MicrosoftDocs/memdocs#1670]
Hi 

I know that Intune doesn't support IMEI.

What does this mean?

>The device's IMEI number is listed in Device enrollment > Corporate device identifiers.

>Windows | Not supported | Not supported
https://docs.microsoft.com/en-us/mem/intune/enrollment/corporate-identifiers-add

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e8c2d91-8808-a504-da13-526b152a5cfe
* Version Independent ID: 037b60a6-d6b5-75ad-1933-39d0f7a69048
* Content: [Set enrollment restrictions in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/enrollment-restrictions-set#blocking-personal-windows-devices)
* Content Source: [memdocs/intune/enrollment/enrollment-restrictions-set.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/enrollment-restrictions-set.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ra-ful** [comment]
Is anyone know about this?

**Comment by msbemba** [comment]
@nahira-ms Thank you for your feedback. Intune does support or read the IMEI number However, Serial Numbers are the recommended form of identification for iOS/iPad devices.

Here is the updated list of platform that this feature is supported -https://docs.microsoft.com/en-us/mem/intune/enrollment/corporate-identifiers-add#identify-corporate-owned-devices-with-imei-or-serial-number

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @nahira-ms Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
