### ISSUE TITLE
NO INTERNET = Now What???

### ISSUE THREAD

**Issue by carbjos** [MicrosoftDocs/memdocs#1671]
NO INTERNET (Now What?)
US Government & Military sites with No Internet is moot
It is presumed an entire global support team is tracking this convoluted quagmire.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1bc3f2a-edf6-24e0-4f45-86dc75717572
* Version Independent ID: 2789eb96-6e74-71c0-9c57-65be3d7d802c
* Content: [Updates and servicing - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/manage/updates#bkmk_note1)
* Content Source: [memdocs/configmgr/core/servers/manage/updates.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/manage/updates.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @carbjos, see this article that explains how to update site when the service connection point is in offline mode, which would be the case for an airgap network: [Use the service connection tool](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/manage/use-the-service-connection-tool)

If you're referring to something else, please clarify.
