### ISSUE TITLE
Prerequisite section needs to be updated to reflect changes in Reporting and Telemetry options.

### ISSUE THREAD

**Issue by TeamTerry** [MicrosoftDocs/memdocs#1677]
Hi Team, in the prerequisites section - https://docs.microsoft.com/en-us/mem/intune/protect/windows-10-update-rings#prerequisites - it mentions that Basic must set as a minimum.
You recently updated the Docs here - https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-windows-10#reporting-and-telemetry - regarding the changes to the options (Basic no longer available).

Can you please update this page to clearly advise what the minimum setting is that is needed for telemetry for Windows Update Rings.

Thanks,
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d67fb1e-47ec-a448-e2bd-757d898169d9
* Version Independent ID: df76b3b7-a69b-5ee9-e632-81d864fe6142
* Content: [Configure Windows 10 update rings policy in Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/windows-10-update-rings)
* Content Source: [memdocs/intune/protect/windows-10-update-rings.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/windows-10-update-rings.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@TeamTerry  Whooops!  It appears that when we updated the bulk of the details for that requirement, we missed flipping _Basic_ to be _Required_ in the lead of that bullet point. :)   Thanks for bringing that to our attention. 

I've submitted a new edit for that, which should go live on Tuesday.
