### ISSUE TITLE
Hybrid devices

### ISSUE THREAD

**Issue by nhogarth86** [MicrosoftDocs/memdocs#1679]
Autopilot Reset doesn't support Hybrid Azure AD Joined devices, however the documentation is misleading. At the top of the article it says:

Note
The Autopilot Reset does not support Hybrid Azure AD joined devices.

Then down the bottom it says:

Note
When a hybrid device is reset it may take up to 24 hours for it to be ready to be deployed again. You can expedite this request by re-registering the device.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8411fd84-8a1d-28e6-1535-30143be7ede2
* Version Independent ID: 4e5ecbe1-aa9b-cfa0-7b67-1ac1dcb0c465
* Content: [Windows Autopilot Reset](https://docs.microsoft.com/en-us/mem/autopilot/windows-autopilot-reset)
* Content Source: [memdocs/autopilot/windows-autopilot-reset.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/windows-autopilot-reset.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
The second comment was added 10 days ago. I'm checking, but I think there is an error in it.  It probably should say AD-joined instead of hybrid.

**Comment by greg-lindsay** [comment]
Apparently the second note refers to a full device reset, not an Autopilot Reset. I will either remove the note or set the context for it.

**Comment by nhogarth86** [comment]
Thanks. Does full reset refer to the reset done within Windows settings?

**Comment by greg-lindsay** [comment]
Yes, this is accomplished through settings by going to Update & Security > Recovery > Reset this PC.  It can also be done from the command line with the systemreset -CleanPC command, with DISM, or with any MDM product that accesses the CleanPC CSP (https://docs.microsoft.com/windows/client-management/mdm/cleanpc-csp)

**Comment by greg-lindsay** [comment]
I've changed the first note to say that a full device reset is needed if reset is required on a hybrid device and removed the second note.

**Comment by JuGhithub** [comment]
Hi, 

I have a question regarding the "When a hybrid device is reset it may take up to 24 hours for it to be ready to be deployed again. You can expedite this request by re-registering the device."

Can you clarify the "Up to 24 Hours"? If a reset a hybrid Azure domain join device from windows settings, it can use Autopilot or not? What's happen during this 24 Hours?

Or I need to delete the computer from Autopilot devices and reimport it?

Thanks
