### ISSUE TITLE
ccmsetup.log location is incorrect in documentation

### ISSUE THREAD

**Issue by vhothur-ms** [MicrosoftDocs/memdocs#1684]
[Enter feedback here]
ccmsetup.log are located in %WinDir%\ccmsetup\Logs\ccmsetup.log and not under %WinDir%\ccmsetup\ccmsetup.log

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3f3e45d-8f9d-aa5a-8b6a-d8c51c50d11e
* Version Independent ID: f5305fc4-894b-19dd-26c8-6f90901d4b1e
* Content: [Client installation parameters and properties - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/deploy/about-client-installation-properties)
* Content Source: [memdocs/configmgr/core/clients/deploy/about-client-installation-properties.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/deploy/about-client-installation-properties.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @vhothur-ms, good catch! I'll fix that now.

p.s. in the future, you can submit this sort of edit yourself. For more info on the process, see [How to contribute to docs](https://docs.microsoft.com/mem/use-docs#contribute). 😄
