### ISSUE TITLE
my installation does not contain indicated group policy

### ISSUE THREAD

**Issue by dhoke4tdb** [MicrosoftDocs/memdocs#1689]
The only alphabetically close item to Windows Defender Antivirus is "Windows Defender SmartScreen".
Elsewhere there is a "Microsoft Defender Antivirus" but that doesn't seem to contain items matching the rest of the instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76b07dd3-8f84-c715-76f5-c22c2a98b5f3
* Version Independent ID: b212305e-9b54-f6cd-81bd-f23254f6891a
* Content: [Turn on Windows Defender](https://docs.microsoft.com/en-us/mem/intune/user-help/turn-on-defender-windows)
* Content Source: [memdocs/intune/user-help/turn-on-defender-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/user-help/turn-on-defender-windows.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @dhoke4tdb, thanks for your contribution. The name did change to "Microsoft Defender Antivirus" so I updated the instructions to match what's shown in Group Policy. Those changes will be live soon.
