### ISSUE TITLE
Azure Sign-In Step, note needs to be added.

### ISSUE THREAD

**Issue by mattsmacblog** [MicrosoftDocs/memdocs#169]
Add extra note suggestion:  

I kept getting Access Denied errors doing this Step below.  After going into my Azure Portal finding my Global Admin account I had to also assign the account an Enterprise Mobility + Security License to make this login step work.

"On the Subscription page of the wizard, configure the following settings:

The Azure environment to use. For example, the Azure Public Cloud or the Azure US Government Cloud.
Select Sign In. Sign in as an Azure AD global administrator, and then select Next."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b813a55b-0679-f80c-983f-782b394c748c
* Version Independent ID: ea738339-f10c-10f2-91ab-a2b87b342b12
* Content: [Tutorial: Enable co-management for existing clients - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/comanage/tutorial-co-manage-clients#feedback)
* Content Source: [memdocs/configmgr/comanage/tutorial-co-manage-clients.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/comanage/tutorial-co-manage-clients.md)
* Product: **configuration-manager**
* Technology: **configmgr-comanage**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @mattsmacblog for the feedback. That requirement is mentioned in the [main prereqs list](https://docs.microsoft.com/mem/configmgr/comanage/overview#licensing), but probably worth calling out in the tutorials as well.

**Comment by davisdre** [comment]
Yeah, I kind of notice that it asked for it, but never at least showed a screenshot of how that dialog box appears to enter credentials.

**Comment by mestew** [comment]
I'm adding the tip from the [main prereqs list](https://docs.microsoft.com/mem/configmgr/comanage/overview#licensing) inline with the global admin prereq in the tutorial. 
Thanks!
