### ISSUE TITLE
Need some background on the role of Limiting collections

### ISSUE THREAD

**Issue by Peripheral72** [MicrosoftDocs/memdocs#1692]
I have gone through the list of documents and see no reference to Limiting Collections.
For me, this is foundational as any membership rules are based on the Limiting Collection.
Further, I was not able to populate the resulting collection until I included both an Including and Excluding collection.
Supplying a Limiting and Excluding collection resulted in no evaluations, even with the knowledge that Exclusions have precedence.
Of course, I always stand corrected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e416191-9e1a-7779-46ad-3e138a6a38e5
* Version Independent ID: 825f7f36-6968-2592-e44f-9ffdac59a7b6
* Content: [Create collections - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/collections/create-collections)
* Content Source: [memdocs/configmgr/core/clients/manage/collections/create-collections.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/collections/create-collections.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @Peripheral72, the best resource on that is probably the accompanying article on [Collection evaluation](https://docs.microsoft.com/mem/configmgr/core/clients/manage/collections/collection-evaluation), which explains the process in more detail.
