### ISSUE TITLE
What portion of the URL needs to be used from the Microsoft Store

### ISSUE THREAD

**Issue by dreeves14** [MicrosoftDocs/memdocs#1693]
The documentation doesn't clearly state the amount of the URL that is needed to make sure this works. The tooltip example within Azure also doesn't fully explain.

If for instance I go looking for the Azure VPN Client that URL is: 
https://www.microsoft.com/en-us/p/azure-vpn-client/9np355qt2sqb?activetab=pivot:overviewtab

I'm going to assume you don't need that whole thing, but again the info is not clear. Would the correct answer be **https://www.microsoft.com/en-us/p/azure-vpn-client/9np355qt2sqb**     ??  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ded6cdc4-3c0a-ae18-9d9c-b3d5db3c0708
* Version Independent ID: 34a4b4be-cd8b-25b3-49ef-f5142a87b9ef
* Content: [Add Microsoft Store apps to Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/store-apps-windows)
* Content Source: [memdocs/intune/apps/store-apps-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/store-apps-windows.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@dreeves14 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2521

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @dreeves14 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
