### ISSUE TITLE
The DownloadContents method doesn't seem to be working.

### ISSUE THREAD

**Issue by dimitar-nedelchev-dxc-com** [MicrosoftDocs/memdocs#1696]
This method doesn't seem to be working. It always returns **"A null reference pointer was passed to the stub."**. Would it be possible to provide an example in this article?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f20fc6d-4c63-b82e-4d6a-f44283800a34
* Version Independent ID: 43a0ebf8-0a42-bbef-013a-a1f31465d3f1
* Content: [DownloadContents Method - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/develop/reference/core/clients/sdk/downloadcontents-method-in-class-ccm_application?source=docs)
* Content Source: [memdocs/configmgr/develop/reference/core/clients/sdk/downloadcontents-method-in-class-ccm_application.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/develop/reference/core/clients/sdk/downloadcontents-method-in-class-ccm_application.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @dimitar-nedelchev-dxc-com, I'm sorry you're having problems. The ConfigMgr SDK content hasn't changed in a long time, and it's an area in which we're not actively investing beyond basic maintenance and some new functionality. There are a couple of options available to provide the best level of support for this:

- Post on [Configuration Manager forums](https://docs.microsoft.com/answers/products/mem). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
