### ISSUE TITLE
User Rights

### ISSUE THREAD

**Issue by Oldmanheat** [MicrosoftDocs/memdocs#17]
User Rights is not showing under Endpoint Protection Profile below Xbox services. Is this a known issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f2a095c-452e-c494-a013-0626b9f3728d
* Version Independent ID: a4787d69-187f-fe55-d071-3a37b9b082e9
* Content: [Protection settings for Windows 10 devices in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/endpoint-protection-windows-10#user-rights)
* Content Source: [memdocs/intune/protect/endpoint-protection-windows-10.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/endpoint-protection-windows-10.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@oldmanheat   Thanks for the question about the category. I've checked with our product group about this. The _User Rights_ section of settings was recently removed from the Endpoint Protection profile, and these settings are no longer available to configure or manage.  The content for these settings will soon be removed from the docs in a future update.  

The settings reflect underlying Windows CSPs that have not returned the expected values, which led to reporting of failure regardless of configuration. Its possible the settings will return in the future if the CSP issues for those settings are resolved.
