### ISSUE TITLE
Document which DCs are required to be accessed

### ISSUE THREAD

**Issue by Yupiter2005** [MicrosoftDocs/memdocs#170]
We have a part for the ports we need to be opened against DCs: https://docs.microsoft.com/en-us/configmgr/core/plan-design/hierarchy/ports#BKMK_PortsSite-DC

However it would be nice also to document directions: 
1) only to the domain where ConfigMgr is installed?
2) to root domain (and btw yes, it's required)?
3) to domains being discovered?
...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0976187e-be77-b141-9269-7064d7f1371d
* Version Independent ID: a4a4fdea-c0cd-4a5e-d298-c0b2ede10506
* Content: [Ports used for connections - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/hierarchy/ports#feedback)
* Content Source: [memdocs/configmgr/core/plan-design/hierarchy/ports.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/hierarchy/ports.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Yupiter2005 for the feedback. However, I don't think we'll ever have the time to test/research/validate this functionality with the resources we have.

**Comment by Yupiter2005** [comment]
@aczechowski - I had at least two premier cases ended up with opening access to the root domain and can pinpoint the exact code lines.

E.g. we use this HRESULT  or both AD User and System discoveries:
CADSource::populateVariables( ADSynchronizer * pSynchronizer )

And this specifically tries to reach forest root DCs:
            CHECKLOG(ERROR_SUCCESS == (retVal = **DsGetDcName**(NULL,
                dci->**DnsForestName**,
                NULL,
                NULL,
                DS_DIRECTORY_SERVICE_REQUIRED,
                &**dciForest**)),
                E_FAIL,
                LOGERROR("Failed to look up DNS forest GUID error = %d", retVal));

So if there is no way to reach the DC, the discovery will just fail though the child domain is reachable.
