### ISSUE TITLE
New changes?

### ISSUE THREAD

**Issue by jogmeznj** [MicrosoftDocs/memdocs#1700]
I don't exactly recall if this documentation said that was in General Availability but it's now saying that is back to "Public Preview". Though, in the Endpoint Portal White-Glove setting does not show as "Public Preview". 

Who should the customer believe, the Microsoft documentation or the feature in the Endpoint Manager?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0f572e0-1bc0-6f14-7f60-989eb67fb7e7
* Version Independent ID: e4ec5b25-d9a6-d260-6cf6-ff4f3eb3ecb8
* Content: [Windows Autopilot for pre-provisioned deployment](https://docs.microsoft.com/en-us/mem/autopilot/pre-provision)
* Content Source: [memdocs/autopilot/pre-provision.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/pre-provision.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
There was some back and forth about this. Originally the doc was published without the public preview tag, even though the feature was technically still in preview. I have mail from the product team saying that definitely the "pre-provisioning" aka white glove process is still in public preview.  If you don't see this tagged in Intune as public preview, that's an oversight.
