### ISSUE TITLE
MDM Agent APK link “ https://aka.ms/intune_kme” is no longer working

### ISSUE THREAD

**Issue by alaaadly** [MicrosoftDocs/memdocs#1702]
[Enter feedback here]

Hello Team,

Would like to report a none working link in the document which affecting Enrollment using KME for Android device administrator profile

MDM Agent APK | Yes | https://aka.ms/intune_kme
-- | -- | --

Is it possible to provide another working link or fix the existing one ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91c6e4c4-96e2-14c6-8028-a2b947740e73
* Version Independent ID: 94bd0e7c-03c8-151d-6569-5d12985824e6
* Content: [Automatically enroll Android devices using Samsung's Knox Mobile Enrollment - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/android-samsung-knox-mobile-enroll#for-android-device-administrator)
* Content Source: [memdocs/intune/enrollment/android-samsung-knox-mobile-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/android-samsung-knox-mobile-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by msbemba** [comment]
@alaaadly Thank you for your feedback. The link is functional again - https://aka.ms/intune_kme  and I'm able to download the apk file.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @alaaadly Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
