### ISSUE TITLE
https://aka.ms/intune_kme link is broken

### ISSUE THREAD

**Issue by cdonohoe** [MicrosoftDocs/memdocs#1704]
The https://aka.ms/intune_kme link is broken, it is linked in this document as a location to download the Company Portal APK 404 error when accessed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91c6e4c4-96e2-14c6-8028-a2b947740e73
* Version Independent ID: 94bd0e7c-03c8-151d-6569-5d12985824e6
* Content: [Automatically enroll Android devices using Samsung's Knox Mobile Enrollment - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/android-samsung-knox-mobile-enroll)
* Content Source: [memdocs/intune/enrollment/android-samsung-knox-mobile-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/android-samsung-knox-mobile-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by josekast** [comment]
Yes, the link is broken.
https://aka.ms/intune_kme --> https://download.microsoft.com/download/5/8/5/5854FA0B-A11F-4810-AEFE-B6F3C4FA0CC2/com.microsoft.windowsintune.companyportal.apk

The URL shortener should point to: https://download.microsoft.com/download/5/8/5/5854FA0B-A11F-4810-AEFE-B6F3C4FA0CC2/com.microsoft.windowsintune.companyportal**### -signed**.apk

Please, fix it.

**Comment by msbemba** [comment]
@cdonohoe Thank you for your feedback. The LInk is functional again and I'm able to download the apk file.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @cdonohoe Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
