### ISSUE TITLE
Feedback: Provide more details about what traffic eHTTP covers for Client Communication

### ISSUE THREAD

**Issue by brmcmill** [MicrosoftDocs/memdocs#1705]
Hey Team,

I think would be very helpful as the roadmap to sunset HTTP is progressing, to see if this doc can be updated to cover what the latest features of eHTTP will cover overtime.  My understanding as of today (v2103), eHTTP would cover the following traffic channels:

1. Client to MP
2. Client to DP
3. Console to SMS Provider (For a small subset of nodes in the console only -- if that can be expanded on, I think that would be helpful too)

Based on our [Ports/Protocols Doc](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/hierarchy/ports#BKMK_PortsClient-ClientWakeUp), do we think it may help to provide additional context on what specifically is not covered at this time?  

My guess on what traffic channels are **not** currently covered:

1. Client --> Client
2. Client --> FSP (Assuming if the FSP role ever is overhauled to HTTPS one day)
3. Client --> Global Catalog DC
4. Client --> Software Update Point
5. Client --> State Migration Point
6. Console --> Client (Remote Control as an example)

I appreciate your time!  Thanks again.

- Brandon

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac80195f-d429-0ffd-2a32-fb23e57c6697
* Version Independent ID: c4e06cf7-5c50-8fb4-d8b9-ecce874f118b
* Content: [Enhanced HTTP - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/hierarchy/enhanced-http)
* Content Source: [memdocs/configmgr/core/plan-design/hierarchy/enhanced-http.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/hierarchy/enhanced-http.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @brmcmill for the feedback. I have some plans to update this article, including a diagram to help visualize the components and flows. But that's a good idea to include the scenarios that it doesn't currently support.

**Comment by aczechowski** [comment]
Closing this issue, my PR merged, but won't go live until 2107 CB releases...soon 😉
