### ISSUE TITLE
Compliance for shared devices

### ISSUE THREAD

**Issue by JiriHy** [MicrosoftDocs/memdocs#1706]
The wording is obviously incorrect in the article https://docs.microsoft.com/en-us/mem/intune/protect/create-compliance-policy :
"Enroll devices to one user, or enroll without a primary user. Devices enrolled to multiple users aren't supported."

There is no way to enroll a single device to multiple users at the same time. It is also not true that compliance is not supported if there are multiple users logged on at the same time. Based on https://docs.microsoft.com/en-us/mem/intune/protect/compliance-policy-monitor this scenario is possible.

(admin edit, adding metadata for proper article link and tracking)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eca8b85b-ba3d-2d08-156b-f13d910f16e2
* Version Independent ID: 5d1bdaea-3ae8-d35a-3a78-2dea9e1d1c7c
* Content: [Create device compliance policies in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/create-compliance-policy)
* Content Source: [memdocs/intune/protect/create-compliance-policy.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/create-compliance-policy.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@JiriHy Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2530

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @JiriHy Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
