### ISSUE TITLE
Incorrect information and typo's.

### ISSUE THREAD

**Issue by ozthe2** [MicrosoftDocs/memdocs#171]
Step 8 in Create the app protection policy is a bit garbled with half a sentence cut off: "don't need to configure these settings."

Also, surely one would be required to configure these settings?  How would the policy work if it were not assigned?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 733b08c2-5666-0d9b-8e78-28fba3456a6f
* Version Independent ID: ab6a321b-d6c0-c301-8156-96ccfdd21192
* Content: [Tutorial - Protect Exchange Online email on unmanaged devices - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/tutorial-protect-email-on-unmanaged-devices)
* Content Source: [memdocs/intune/protect/tutorial-protect-email-on-unmanaged-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/tutorial-protect-email-on-unmanaged-devices.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@ozthe2  Thanks for reporting that, I've submitted an edit to remove the junky line that appears to have been an accidental copy into that spot from step 7.   For this tutorial, it's not necessary to assign this policy to a group, per the preceding line in step 8.
