### ISSUE TITLE
Android Enterprise corporate owned in the list of automatically assigned corporate-owned

### ISSUE THREAD

**Issue by TaniaLimaP** [MicrosoftDocs/memdocs#1710]
Hi team, is there a particular reason why we don't include Android Enterprise corporate owned in the list of automatically assigned corporate-owned? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcd313b3-e225-849a-def5-8a32a08a92e9
* Version Independent ID: 917b6190-a8bd-f55d-3e71-f403a395721f
* Content: [Add corporate identifiers to Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/corporate-identifiers-add)
* Content Source: [memdocs/intune/enrollment/corporate-identifiers-add.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/corporate-identifiers-add.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by msbemba** [comment]
@TaniaLimaP Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2524

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @TaniaLimaP Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
