### ISSUE TITLE
Build process completely unclear

### ISSUE THREAD

**Issue by AzureAzim** [MicrosoftDocs/memdocs#1716]
VS Module requirements are completely absent from this article. A standard install of VS 2019 does not include what is required to build this solution. It is very unclear on how to successfully make this article work. Frankly asking customers to build these modules in visual studio is very cumbersome and not very customer centric. 

![image](https://user-images.githubusercontent.com/11980156/122659562-5b534880-d147-11eb-89e2-146856430a45.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa43fc11-ff6b-20c8-5bfa-a89572295223
* Version Independent ID: ea0f43b6-5c74-6f9e-7e0c-ec86db3e4400
* Content: [Use imported PFX certificates in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/certificates-imported-pfx-configure)
* Content Source: [memdocs/intune/protect/certificates-imported-pfx-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certificates-imported-pfx-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@AzureAzim  Thanks for the feedback on your experience and the process.  I've reached out to our product and engineering team to share your feedback, and they've opened up a work item so they can investigate the changes with later Visual Studio versions, and drive a content update to help address just what modules are needed, or how to make the process work if not using the original VS 2015 which was used when that GitHub project was drafted. 

Unfortunately, I can't provide any immediate relief or guidance on this, nor an ETA on when the GitHub project will be updated. The difference that led to VS 2109 not functioning as expected isn't a known delta - yet. But with this need now known and being tracked, keep an eye on the GitHub project for changes.
