### ISSUE TITLE
Update June 9 to June 9 2020

### ISSUE THREAD

**Issue by DavidTaig** [MicrosoftDocs/memdocs#1717]
Folks

Please update
For update packages released on and after June 9
to
For update packages released on and after **June 9 2020**

this has also confused MS Support - 2106010010000264

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6522d91-b65f-6415-3ffd-1634a3ce8589
* Version Independent ID: 450506df-ca8f-726f-cc19-44a28a932808
* Content: [Manage Microsoft 365 Apps updates - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/sum/deploy-use/manage-office-365-proplus-updates#bkmk_channel)
* Content Source: [memdocs/configmgr/sum/deploy-use/manage-office-365-proplus-updates.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/sum/deploy-use/manage-office-365-proplus-updates.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @DavidTaig for the feedback. I'm making that change now, it should publish live in the next hour. 😄
