### ISSUE TITLE
Microsoft Store for Business - 

### ISSUE THREAD

**Issue by carlova** [MicrosoftDocs/memdocs#172]
In the section "Distribute Offline Apps from the Store for Business using Intune", Step 1- GCC High and DoD (Azure Government) accounts cannot be used to log into the Store for Business. A commercial identity must be used. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44ac8695-df39-549c-569a-2e8ceaddc38c
* Version Independent ID: 6da292aa-7b48-f588-625e-e955a6b44869
* Content: [Apps for GCC High and DoD environments - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-deploy-gcc-dod?source=docs#feedback)
* Content Source: [memdocs/intune/apps/apps-deploy-gcc-dod.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/apps-deploy-gcc-dod.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@carlova - The note includes the following:
'For commercial environments, a tenant admin can sync their Store for Business with Intune, however for GCC High and DoD environments, this service is not available. Admins in this situation must deploy an app by uploading directly to Intune.'

If you have questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

This question is in our documentation feedback channel and it may be best to handle this question as a support request. For this reason, I'm closing this issue. Please use the above channels if you don't already have a solution.
