### ISSUE TITLE
Missing documentation for SMS_Client WMI Methods

### ISSUE THREAD

**Issue by joshwright10** [MicrosoftDocs/memdocs#1720]
Only 8 out of 10 methods are documented for the SMS_Client Client WMI Class.
If we browse the WMI on a Windows 10 device with the SCCM Client 5.00.8790.1007 installed, we can see a total of 10.

The following two are missing from the documentation:

- RepairClient
- ResetGlobalLoggingConfiguration

In addition, SetClientProvisioningMode is mentioned but has no information. It simply says _Reserved_.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a568e8f9-269f-0380-c7a6-a8708e48c3b0
* Version Independent ID: 855377fe-fdae-df0f-1b7e-b35af17891fc
* Content: [SMS_Client Class - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/develop/reference/core/clients/client-classes/sms_client-client-wmi-class)
* Content Source: [memdocs/configmgr/develop/reference/core/clients/client-classes/sms_client-client-wmi-class.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/develop/reference/core/clients/client-classes/sms_client-client-wmi-class.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @joshwright10 for the feedback. The ConfigMgr SDK content is an area in which we're not actively investing beyond basic maintenance and some new functionality. I recommend using [WMI Explorer](https://github.com/vinaypamnani/wmie2) to help understand current classes, properties, and methods.

We have a plan to be able to add updated SDK information in the future, but still have work to do to make it a reality.
