### ISSUE TITLE
Azure Host Override

### ISSUE THREAD

**Issue by doylecm4** [MicrosoftDocs/memdocs#1721]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ed29a03-7065-24d2-b616-4b503e37eeb1
* Version Independent ID: ce56bac9-9ef8-8de0-b3bd-15d265c3f18a
* Content: [Endpoint Protection malware definitions from WSUS - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/protect/deploy-use/endpoint-definitions-wsus)
* Content Source: [memdocs/configmgr/protect/deploy-use/endpoint-definitions-wsus.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/protect/deploy-use/endpoint-definitions-wsus.md)
* Product: **configuration-manager**
* Technology: **configmgr-protect**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @doylecm4, we're not sure what this means. To help us understand the feedback for this article, please provide more information and reopen the issue.

**Comment by doylecm4** [comment]
Hey man. So basically I have a cloud security service company remoting into my PC and Gmail. The service was caused by forgery and now I'm trying to remove it. Believe the company is Dynatrace and has full remote and azure authentication. Any tips or advice would help!
