### ISSUE TITLE
Incorrect instructions for sysctl.conf

### ISSUE THREAD

**Issue by yanmannqc** [MicrosoftDocs/memdocs#1723]
At the beginning of section "Network", it is written to edit the /etc/sysctl.conf file to enable ip forwarding for ipv4.

Sadly, this file does not include such line. After searching and reading a bit, this is what I have executed (based on this web page: https://www.digitalocean.com/community/questions/how-to-enable-ip-masquerading-forwarding-on-centos-7):

1. sudo -s
2. touch 100-sysctl.conf
2. echo "net.ipv4.ip_forward = 1" > /etc/sysctl.d/100-sysctl.conf
3. sudo sysctl -p
4. sudo sysctl -a | grep ip_forward
5. exit

Step 4 is for validation. I'm not sure that the "sudo" were mandatory for steps #3 and 4.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8df9199b-37e9-34d9-c440-97cf4f9ca109
* Version Independent ID: 8352cc27-2887-715e-4809-77520a5b5054
* Content: [Identify the prerequisites to install and use the Microsoft Tunnel VPN solution for Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/microsoft-tunnel-prerequisites)
* Content Source: [memdocs/intune/protect/microsoft-tunnel-prerequisites.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/microsoft-tunnel-prerequisites.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@yanmannqc  Thanks for this information and feedback. I've asked our engineering team to look into the missing entries, but the current expectation is that they should be there.  

However, as they might not be present today, and could go missing in the future, we're adding some details to the docs about how to check on the status and how to enable or what to add should IP forwarding entries be missing.  That will be live in a day or so. As this will be generic information, we will recommend consulting the docs for the distribution that's in use for more specific guidance, when available.
