### ISSUE TITLE
APNS Download Format - Now downloads as .cer

### ISSUE THREAD

**Issue by macmillernz** [MicrosoftDocs/memdocs#1725]
[Enter feedback here]
I have just been though this process and the certificate was downloaded as a .cer.
Please add instruction to rename file format to .pem or allow .cer uplad in Intune.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: babf49ae-ec79-e627-9dbf-2df2eb8909ab
* Version Independent ID: 90f3f372-9326-473e-3f82-e28e89853d49
* Content: [Get an Apple MDM Push certificate for Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/apple-mdm-push-certificate-get)
* Content Source: [memdocs/intune/enrollment/apple-mdm-push-certificate-get.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/apple-mdm-push-certificate-get.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by msbemba** [comment]
@macmillernz Thank you for your feedback. The file downloads in CSR format. Later, Select Create your MDM push Certificate to go to the Apple Push Certificates Portal. Sign in with your company email address Apple ID, and then click Create a Certificate. Select Choose File and browse to the certificate signing request file, and then choose Upload. On the Confirmation page, choose Download to the download the certificate (.pem) file, and save the file locally.

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit  This can be closed.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @macmillernz Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
