### ISSUE TITLE
Configure email settings for Gmail

### ISSUE THREAD

**Issue by NickDarvey** [MicrosoftDocs/memdocs#1726]
This page says:

>An IT administrator creates email profiles with specific settings to connect to a mail server, such as Microsoft 365 and Gmail.

However there's no documentation on how to set up a profile Gmail. The configuration settings only describe an Exchange server for the 'email server' option. Is this actually a supported option? If so, how?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 018599c4-f643-2ee2-285b-66ddafb46893
* Version Independent ID: a01b9433-58dc-6acd-281a-11125177bc79
* Content: [Configure email settings in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/email-settings-configure)
* Content Source: [memdocs/intune/configuration/email-settings-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/email-settings-configure.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@NickDarvey You are correct. It was confusing. We updated the text, and the changes should be live later today. The email profiles include settings to connect to Exchange. Thanks for questioning.
