### ISSUE TITLE
License requirements unclear

### ISSUE THREAD

**Issue by Martony78** [MicrosoftDocs/memdocs#1727]
The tip at the beginning of the page is pretty confusing:
"You must be licensed to use Endpoint Protection to manage clients in your Configuration Manager hierarchy."
What does it mean? Do we need an extra license to use Endpoint Protection in our Configuration Manager hierarchy? And what license should we purchase?
It makes no sense since EM+S E3 licenses already covers ConfigMgr and Endpoint Protection in Intune.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac1e9ae8-a9de-99f3-5335-2460fb9d69ce
* Version Independent ID: d2109d70-4f53-7033-1573-3ca6ad43e2f9
* Content: [Endpoint Protection - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/protect/deploy-use/endpoint-protection)
* Content Source: [memdocs/configmgr/protect/deploy-use/endpoint-protection.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/protect/deploy-use/endpoint-protection.md)
* Product: **configuration-manager**
* Technology: **configmgr-protect**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @Martony78 for the feedback, that's probably a legacy statement that I don't think applies any more. Definitely confirm with your account team or whoever provides your licensing. But my understanding is that System Center Endpoint Protection used to be separately licensed, although frequently bundled with ConfigMgr. We can probably just remove that statement altogether.

**Comment by Martony78** [comment]
Hi @aczechowski and thanks for your reply. That is my understanding too, but I can't find anything within docs.microsoft.com or on the web that confirm this. We asked our licenses provider but he was not able to answer this either.
