### ISSUE TITLE
Azure Active Directory Graph support

### ISSUE THREAD

**Issue by cmateiescu** [MicrosoftDocs/memdocs#1729]
On Step 6 on "Register the native (client) app" it's mentioned that if you are using Azure AD User Discovery in Configuration Manager the API permissions needs to be changed from Microsoft Graph to Azure Active Directory Graph.

But doing that is against the recomendation to use Microsoft Graph instead of Azure Active Directory Graph as the support for the latter will end on June 30, 2022. See https://techcommunity.microsoft.com/t5/azure-active-directory-identity/have-you-updated-your-applications-to-use-the-microsoft/ba-p/1144698

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5da6c8b-447a-d0c7-4243-095745d85306
* Version Independent ID: 64b13b3d-22b4-2f04-0a7d-7d34a7b62395
* Content: [Manually register Azure AD apps - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/manually-register-azure-ad-apps#register-the-native-client-app)
* Content Source: [memdocs/configmgr/core/clients/manage/cmg/manually-register-azure-ad-apps.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/cmg/manually-register-azure-ad-apps.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @cmateiescu for the feedback. I confirmed with engineering, you're correct, it should be Microsoft Graph not Azure AD Graph.

**Comment by cmateiescu** [comment]
Thank you @aczechowski for confirming. 
We used Configuration Manager to automate the creation of the apps as described here https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/configure-azure-ad about a year and a half ago using ver 1910. The apps created have Azure Active Directory Graph permissions and the client app shows up as using ADAL in the Azure AD sign-in analysis workbook mentioned in https://techcommunity.microsoft.com/t5/azure-active-directory-identity/have-you-updated-your-applications-to-use-the-microsoft/ba-p/1144698
I have checked the other page (https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/configure-azure-ad)  and the FAQ page (https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/cloud-management-gateway-faq) for any notes regarding the need to change to Microsoft Graph permissions and MSAL but couldn't find any reference. I have also checked the Release notes from 1910 onwards. We are now using 2010.
I guess the question is, would we need to change to Microsoft Graph permissions, and would that change mean it will also change the use of ADAL to MSAL, when the apps have been created automatically using Configuration Manager?
Rather than raising another issue I have used this so hopefully it's ok.

**Comment by aczechowski** [comment]
I'll fix this with broader changes to the CMG content for 2107 current branch release. You'll see the issue close when my pull request merges, but it won't go live until the 2107 CB content publishes.

To your other question re auto-generated apps...I suggest that you [file a frown](https://docs.microsoft.com/mem/configmgr/core/understand/product-feedback) to put in feedback to the engineering team.

**Comment by aczechowski** [comment]
Actually...I got an answer on your question yesterday. I'm putting together an item for the CMG FAQ on it. Basically, if you use cloud-attached services, as long as you stay current with ConfigMgr (within one or two versions) you'll be good come next June. (And honestly, if you're cloud-attached and NOT current with on-prem version, that doesn't make sense to me.) The only other thing you should do is check those permissions to make sure that they're using Microsoft Graph API and not AAD Graph. But you don't need to recreate the app registrations or redeploy/reconnect anything.

Also closing this issue...it should have happened automatically when my PR merged. Again, the change won't go live until 2107 CB content publishes.
