### ISSUE TITLE
Will not work without correct settings set

### ISSUE THREAD

**Issue by contactbrenton** [MicrosoftDocs/memdocs#1730]
This article should have some form of information box explaining that the "Let Apps Access Location" must be set to force allow, ideally with a link on how to do this. The location will not work if the device has been autopiloted as the default setting for this is off.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf0d4fa4-c4a0-6a69-3d86-5b34ccf8cbad
* Version Independent ID: 112c8b86-6df1-6fb8-4b7c-9bc2b5d15c2a
* Content: [Find lost devices with Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/remote-actions/device-locate)
* Content Source: [memdocs/intune/remote-actions/device-locate.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/remote-actions/device-locate.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by contactbrenton** [comment]
Please see this tweet.
https://mobile.twitter.com/scottbreen/status/1387325757819555851

**Comment by msbemba** [comment]
@contactbrenton Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2506

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @contactbrenton Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
