### ISSUE TITLE
Intune: all Huawei devices flagged as "not up to date"

### ISSUE THREAD

**Issue by Camusensei** [MicrosoftDocs/memdocs#1734]
Hi, what about all Huawei devices all flagged as "not up to date" when android shows they ARE up to date.
Example on a Huawei P20 lite: "Security patch level: 1 april 2021", but the application writes "your organization requires this app to run on devices with the 2020-12-01 Android security patch or higher"
I have the same example on a P20, and a Huawei P30 (with different dates in the android settings)
I have tested other brands, only Huawei has this problem. I've been in contact with the huawei support for 3 months now but they don't have access to the intune code nor to a company account with the same security setting. So they are a bit at a loss.

I'm pretty sure the problem must be coming from Huawei, but the solution can only come from your side to let them know what they did wrong.

Please cover this case in the page listing Huawei as an exception or find a way to let them know of this issue? I've been trying all I can but I'm just a simple consumer in the end...
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e37cb639-47d7-b981-18a2-f69209b035b6
* Version Independent ID: 8052cc2d-1ddf-6b0c-1d5f-c801ae61a9f0
* Content: [You need to update your Android device](https://docs.microsoft.com/en-us/mem/intune/user-help/you-need-to-update-your-device-OS-security-patch-android)
* Content Source: [memdocs/intune/user-help/you-need-to-update-your-device-OS-security-patch-android.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/user-help/you-need-to-update-your-device-OS-security-patch-android.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@Camusensei Thank you for your feedback. Sorry about the delay. Since this is related to Huawei devices and if this issue still persists, I'd recommend you contact Microsoft support via the need help section on the admin center. If they find it as a bug, it will be escalated and fixed in the backend.

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@Camusensei I'll verify with the author/ product group and update the document if needed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@lenewsad Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@lenewsad Gentle reminder

**Comment by yogkumgit** [comment]
@Camusensei Technical team is aware of this issue and working internally. Author will update the document once new inputs are available. We proceed here to close this issue. Thanks for your patience and feedback,

**Comment by Camusensei** [comment]
It's been like this for years, I don't think the technical teams will change anything regarding that.
Updating the documentation to let people know of the issue is the smart move here, rather than sweeping it under the carpet. I have spent entire weeks to get to understand where the problem was. If we can with 3 words in a documentation avoid that to anyone, it's what we should do.
