### ISSUE TITLE
Microsoft Account Sign-in Assistant service requirements under Prerequisites

### ISSUE THREAD

**Issue by bmwilson1978** [MicrosoftDocs/memdocs#1735]
I've noticed on many devices I have (21H1) that the display name of the wlidsvc service is "Microsoft Account Sign-in Assistant" and not "Microsoft Sign-In Assistant".

Additional to this the prerequisites state the service must be running, by default it appears this service is set to Manual (Trigger Start) and not Automatic, therefore it's not running unless needed?.  Is this correct or does the Startup Type for this service need to be changed on each device to Automatic so that it's running all the time?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee0dbbde-b15e-4adf-b162-1114fddd8846
* Version Independent ID: 78275b5f-4d5b-f318-0cbf-a27ad35dffa0
* Content: [Configure Windows 10 feature updates policy in Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/windows-10-feature-updates)
* Content Source: [memdocs/intune/protect/windows-10-feature-updates.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/windows-10-feature-updates.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@bmwilson1978   Thanks for the feedback.  I've got a content edit on the way to update the service name as your right that the display name we list wasn't accurate. 

As to the service's status, while I've not been able to confirm how it is the service starts and stops as needed, I can confirm that what your seeing is the correct or expected configuration.  The service appears to default to _Manual (Trigger Start)_ and not to Automatic.  Manual (Trigger Start) is fine and you don't need to change the service on your devices.   I'll also be updating the content around this as well with the intent to head off similar questions or confusion about the service.
