### ISSUE TITLE
Versioning convention should match Apple's iOS versioning convention 

### ISSUE THREAD

**Issue by moatazelgamal** [MicrosoftDocs/memdocs#174]
This is regarding iOS LOB App upload for Intune
https://docs.microsoft.com/en-us/mem/intune/apps/lob-apps-ios

----
The requirement of always incrementing the Build Number (CFBundleVersion) contradicts Apple's definition and use of  CFBundleVersion for iOS. 

https://developer.apple.com/library/archive/technotes/tn2420/_index.html#//apple_ref/doc/uid/DTS40016603-CH1-HOW_THESE_NUMBERS_WORK_TOGETHER

A newer version is indicated by Version Number (CFBundleShortVersionString ) , not the build number  (CFBundleShortVersion). Build number is OK to be repeated across releases with different version numbers.

**Comment by Erikre** [comment]
We have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. If you have continue to have questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

Please use the above channels if you don't already have a solution.
