### ISSUE TITLE
Can't escape my former employer's Company Portal Account

### ISSUE THREAD

**Issue by notuntoward** [MicrosoftDocs/memdocs#1746]
I'm trying to remove my android phone from my former employer's company portal connection.  I'm unable to delete the app from my phone, and I'm unable to log in to the Company Portal Site, as directed [here](https://docs.microsoft.com/en-us/mem/intune/user-help/remove-your-device-cpwebsite#feedback), because my former employer has already shut down that account. 

So, this page's advice is not helpful with what must be a very common situation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c42be61-fb09-680c-894c-340af18058c0
* Version Independent ID: 4ea72422-c6ff-8e33-2893-bf6d008ca3f3
* Content: [Remove your device from the Company Portal](https://docs.microsoft.com/en-us/mem/intune/user-help/remove-your-device-cpwebsite#feedback)
* Content Source: [memdocs/intune/user-help/remove-your-device-cpwebsite.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/user-help/remove-your-device-cpwebsite.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @notuntoward, thanks for reaching out to the Microsoft Intune docs team. If this happens again in the future, see [Unenroll Android device](https://docs.microsoft.com/mem/intune/user-help/unenroll-your-device-from-intune-android), which goes over all of the ways to remove your device from management.
