### ISSUE TITLE
Dead link to support.samsungknox.com

### ISSUE THREAD

**Issue by creature124** [MicrosoftDocs/memdocs#1747]
This page contains a dead link, the domain support.samsungknox.com appears to no longer exist.

This link appears on the line 'Enrolling Samsung Knox devices may require you to enable access to Samsung servers.'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f70a020-9214-3316-5419-ee35ba6ff91a
* Version Independent ID: 9cc74430-af54-a2ac-7e4f-5a70b415c66e
* Content: [Operating systems and browsers supported by Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/supported-devices-browsers)
* Content Source: [memdocs/intune/fundamentals/supported-devices-browsers.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/supported-devices-browsers.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by Leicham** [comment]
Thanks @creature124. The link has already been updated.

**Comment by yogkumgit** [comment]
@creature124 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
