### ISSUE TITLE
Order of Operation - Configuration Items 

### ISSUE THREAD

**Issue by gwblok** [MicrosoftDocs/memdocs#175]
Can someone speak to the order in which the CIs run on a client that are part of the same baseline?
I need to have a specific CI run before another CI, but have not seen how to get to happen.  

It would also appear in my testing that it runs the discovery on all CIs before starting the Remediation on any of them.  Very much like it is a very serial process... CI1 Discovery, CI2 Discovery, CI1 Remediation, CI2 Remediation.

I would like to know if I can arrange them in a way that I can force CI1 Remediation to take place before CI2 Discovery takes place, and also if I can Force CI1 to run first.  Sometimes CI2 starts first.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55a9f600-0a02-17b1-9465-9f0c464808bb
* Version Independent ID: 10240feb-044f-43bd-27af-c951159f38eb
* Content: [Create configuration baselines - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/compliance/deploy-use/create-configuration-baselines#feedback)
* Content Source: [memdocs/configmgr/compliance/deploy-use/create-configuration-baselines.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/compliance/deploy-use/create-configuration-baselines.md)
* Product: **configuration-manager**
* Technology: **configmgr-compliance**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @gwblok, good question. I was able to get a quick reply back from engineering: there's no provision for specifying the order that CIs are evaluated in a baseline. It's non-deterministic.

Probably a good tip to add to this article.

**Comment by aczechowski** [comment]
I added a tip at the top of the article, it should publish live tomorrow morning
