### ISSUE TITLE
Checking if *.cloudapp.net DNS name is available - procedure no longer valid

### ISSUE THREAD

**Issue by merlinfrombelgium** [MicrosoftDocs/memdocs#1750]
The documented way to check if a DNS name is available, is no longer valid since the classic cloud service is no longer available in the Azure Marketplace. I have searched for an alternative and best I could find was this REST API: https://docs.microsoft.com/en-us/rest/api/virtualnetwork/check-dns-name-availability/check-dns-name-availability
But it seems to be context-sensitive for an Azure subscription and region.

Any recommendation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ade53de5-3c7a-669d-2786-41d14fb6cea8
* Version Independent ID: 036c9651-1adc-fdcb-7d67-32d212e574e5
* Content: [CMG server authentication certificate - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/server-auth-cert)
* Content Source: [memdocs/configmgr/core/clients/manage/cmg/server-auth-cert.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/cmg/server-auth-cert.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @merlinfrombelgium for the feedback. That's a good find. However, the updated version of this article for 2107 CB focuses on virtual machine scale set and the storage account. 😄
