### ISSUE TITLE
Require and end to end flow digram

### ISSUE THREAD

**Issue by WITHIAL1** [MicrosoftDocs/memdocs#1751]
To ensure that this works correctly in some enterprise environments where networking is restricted, we really need to see the complete and detailed end to end flow of the enrolment process - e.g. OOBE->Check in with AutoPilot Endpoint URLs->Download of AutoPilot Profile->Azure AD Auth->AzureAD device registration->etc->etc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82c5b872-c031-9ed9-c4cc-c8a1a8e93e0a
* Version Independent ID: ac837825-11e3-cf43-7516-0d94b496a59f
* Content: [Windows Autopilot networking requirements](https://docs.microsoft.com/en-us/mem/autopilot/networking-requirements)
* Content Source: [memdocs/autopilot/networking-requirements.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/networking-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by Leicham** [comment]
@WITHIAL1 - Thanks for your comment.  This already exists @ https://docs.microsoft.com/en-us/mem/autopilot/deployment-process

**Comment by frankroj** [comment]
Thank you for the feedback @WITHIAL1. I apologize for the time it took to get back to you regarding this feedback item. Besides the link mentioned by @Leicham, we are working on possibly adding additional flow diagrams. I can't commit that they will be added or a time frame, but we agree that they are a good idea and will definitely look at possibly getting some added to the docs.
