### ISSUE TITLE
Link to latest version of toolkit

### ISSUE THREAD

**Issue by aewald303** [MicrosoftDocs/memdocs#1753]
Should include a link to latest version of the toolkit. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa68c3c1-8f4a-5e56-0dc1-d45832598a1c
* Version Independent ID: 77c73540-9395-3fe7-71df-8e7a63ee439c
* Content: [Configuration Manager Tools - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/support/tools)
* Content Source: [memdocs/configmgr/core/support/tools.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/support/tools.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @aewald303 thanks for the feedback. The link in this article to the 2012 toolkit is for anyone who might need that older version of the tools. All of the current versions are available on the site server, there's no public download for the latest tools.
