### ISSUE TITLE
09046805281

### ISSUE THREAD

**Issue by zinabtanha** [MicrosoftDocs/memdocs#1757]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f506cf9a-8eaf-f70b-0ae9-60fe1a575bea
* Version Independent ID: 8ba07dd4-1a0e-4cc9-e506-17810dad5b6a
* Content: [Connect Configuration Manager - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/desktop-analytics/connect-configmgr#bkmk_connect)
* Content Source: [memdocs/configmgr/desktop-analytics/connect-configmgr.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/desktop-analytics/connect-configmgr.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Assuming this is a test or a misfire, closing
