### ISSUE TITLE
HTTPS MP is not required anymore for making apps available to users.

### ISSUE THREAD

**Issue by motaj1** [MicrosoftDocs/memdocs#1761]
As per this link, E-HTTP and HTTPS both support User and Device Scenarios now.
https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/configure-authentication

Seems like we need to update the following section and remove HTTPS MP as a requirement for deploying apps as available to users.
**Azure AD-joined devices**
_If you deploy applications as available to users, they can browse and install them through Software Center on Azure AD devices. Configure the following prerequisites to enable this scenario:_

**Enable HTTPS on the management point**

I used CM 2103 environment and AAD Joined device with a user account created in AAD, connected through CMG for testing and I can confirm deploying apps as available to user works with E-HTTP.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2a2c700-0bea-521d-ce8e-25404ce6a8bd
* Version Independent ID: 29475b33-2b3b-0cb1-54d4-62a340cda4d2
* Content: [Prerequisites to deploy user-available apps - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/apps/plan-design/prerequisites-deploy-user-available-apps)
* Content Source: [memdocs/configmgr/apps/plan-design/prerequisites-deploy-user-available-apps.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/apps/plan-design/prerequisites-deploy-user-available-apps.md)
* Product: **configuration-manager**
* Technology: **configmgr-app**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @motaj1 for the feedback. I confirmed with engineer:

> CMG will be able to proxy the call using EHTTP through proxy connector if MP is HTTP. 

I'm doing a bunch of CMG-related updates for 2203 release, so will include this with that.
