### ISSUE TITLE
Licensing Information not clear

### ISSUE THREAD

**Issue by schenardie** [MicrosoftDocs/memdocs#1764]
The licensing requirement specify that a enterprise or education subscription is required but the supported editions mentions windows 10 pro?

That means we need at least on of the mentioned subscriptions on the tenant or one per device (in that case the device wont be pro as it will be automatically converted to Enterprise if the license is assigned to the user who log on that device).

Please provide more information

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e6d726f-bd44-d168-0af5-c0fe73e06eb9
* Version Independent ID: a87f06b1-f284-42db-a5ed-2cba46bdf2b9
* Content: [Use Intune to expedite Windows 10 quality updates - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/windows-10-expedite-updates)
* Content Source: [memdocs/intune/protect/windows-10-expedite-updates.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/windows-10-expedite-updates.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Leicham** [comment]
@schenardie - thanks for your issue!  You can find the supported editions at https://docs.microsoft.com/en-us/mem/intune/fundamentals/supported-devices-browsers . Also, joining to MEM/Intune does not automatically upgrade the edition, this must be configured and depends on the type of licenses you have available.

**Comment by Leicham** [comment]
@schenardie - Thanks for your comment.  It looks like this has been updated already. It now shows the supported editions are Pro, Enterprise, Pro Edu, and Edu.
