### ISSUE TITLE
Instructions have changed

### ISSUE THREAD

**Issue by jantoney** [MicrosoftDocs/memdocs#177]
The instructions have vastly changed for the Intune steps and they need a major review

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52bf17f6-f22f-c2ab-6729-8535dbab2252
* Version Independent ID: 0cfba665-614c-7c6c-4c86-1556c63e770b
* Content: [Kiosk settings for Windows and Holographic devices in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/kiosk-settings)
* Content Source: [memdocs/intune/configuration/kiosk-settings.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/kiosk-settings.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@jantoney Thank you! Yes - we're aware. There are a few Windows profiles types that need updated, which should be done in the next couple of weeks.
