### ISSUE TITLE
Escaping spaces

### ISSUE THREAD

**Issue by kevintaber** [MicrosoftDocs/memdocs#1770]
For OMA-URI, if the profile name as a space in it, you need to escape it with %20

Example: ./Vendor/MSFT/WiFi/Profile%20Example/SSID/Settings

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98d2bcb4-cdd3-eed8-5263-4b6fe525b277
* Version Independent ID: b7cbf0dc-9223-1876-d667-adf1c9ffe2fd
* Content: [Create WiFi profile with pre-shared key in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/wi-fi-profile-shared-key)
* Content Source: [memdocs/intune/configuration/wi-fi-profile-shared-key.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/wi-fi-profile-shared-key.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by tycastMSFT** [comment]
@MandiOhlinger , this is correct -- spaces need to be escaped.

**Comment by MandiOhlinger** [comment]
@kevintaber Thank you! It's been added to the article. Changes should be live later today. In the future, it'd be great if you created a pull request for changes like this. We want and encourage community contributions.
