### ISSUE TITLE
MeteredNetworkUsage = 4

### ISSUE THREAD

**Issue by JoshTech1** [MicrosoftDocs/memdocs#1771]
[Enter feedback here]
Hi, I have some SCCM clients on WWAN MBN connections reporting a value of 4 for MeteredNetworkUsage in CCM_NetworkSettings. They are not able to download policy or application packages. This value 4 is undefined on this page. Can you please add information stating what the value of 4 means in this case?

Example:
PS C:\> Get-CIMInstance -Namespace root\ccm\Policy\Machine\ActualConfig -ClassName CCM_NetworkSettings

MeteredNetworkUsage Reserved SiteSettingsKey PSComputerName
------------------- -------- --------------- --------------
                  4                        1

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7a5dbff-328f-b97a-8ea8-74ab3e487bf7
* Version Independent ID: 840876fb-95c8-dab5-bd33-3ccb8bf5d8cd
* Content: [CCM_NetworkSettings Class - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/develop/reference/core/clients/sdk/ccm_networksettings-client-wmi-class)
* Content Source: [memdocs/configmgr/develop/reference/core/clients/sdk/ccm_networksettings-client-wmi-class.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/develop/reference/core/clients/sdk/ccm_networksettings-client-wmi-class.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @JoshTech1 for the feedback. I looked at the code, and found the following value map for this property:

- Unknown = 0
- Allow = 1
- Limit = 2
- Block = 4

And another place mentioned that the "default is block"

I'll update the doc right now to reflect the list from code.
I hope this helps.
