### ISSUE TITLE
Confusing regarding OOB and B patches with same number.

### ISSUE THREAD

**Issue by MarcLaf** [MicrosoftDocs/memdocs#1776]
If a patch is released OOB and is labeled for example, 2021.07 OOB and then on patch Tuesday there is a 2021.07 B, does that mean the patch Tuesday contains the previous OOB patch (same number)? So if there were no expedited profiles created before patch Tuesday, if you make one after then you only need to select the 2021.07 B patch and not create two profiles, one for the OOB and one for the B? Am I understanding this correctly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e6d726f-bd44-d168-0af5-c0fe73e06eb9
* Version Independent ID: a87f06b1-f284-42db-a5ed-2cba46bdf2b9
* Content: [Use Intune to expedite Windows 10 quality updates - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/windows-10-expedite-updates)
* Content Source: [memdocs/intune/protect/windows-10-expedite-updates.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/windows-10-expedite-updates.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by illuvtar** [comment]
> If a patch is released OOB and is labeled for example, 2021.07 OOB and then on patch Tuesday there is a 2021.07 B, does that mean the patch Tuesday contains the previous OOB patch (same number)? So if there were no expedited profiles created before patch Tuesday, if you make one after then you only need to select the 2021.07 B patch and not create two profiles, one for the OOB and one for the B? Am I understanding this correctly?
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 4e6d726f-bd44-d168-0af5-c0fe73e06eb9
> * Version Independent ID: a87f06b1-f284-42db-a5ed-2cba46bdf2b9
> * Content: [Use Intune to expedite Windows 10 quality updates - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/windows-10-expedite-updates)
> * Content Source: [memdocs/intune/protect/windows-10-expedite-updates.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/windows-10-expedite-updates.md)
> * Service: **microsoft-intune**
> * Sub-service: **protect**
> * Technology: ****
> * GitHub Login: @Brenduns
> * Microsoft Alias: **brenduns**

I don’t believe you will have both 2021.07 B and 2021.07 OOB available at the same time. OOB represents a security patch released after the normal patch Tuesday cycle (B) and therefore would replace the original patch for anyone who has not yet installed the update, if B has already been deployed to a device and then an OOB is released the device will have to wait the deferral period defined in its update ring before installing the OOB update.

**Comment by MarcLaf** [comment]
Hi illuvtar, thanks for the reply. Currently I see both 2021.07 B and 2021.07 OOB in Intune. I'm wondering if when this happens, do I need to make a profile for both, or will doing just the B be sufficient?
![expedite](https://user-images.githubusercontent.com/8569591/125958227-8d1b6c49-39b3-48c0-ad12-53de94664617.png)

**Comment by msbemba** [comment]
@MarcLaf Thank you for your feedback.  OOB represents a patch released after the normal patch and will replace the original patch. In your case selecting B would be sufficient.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @MarcLaf Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
