### ISSUE TITLE
Sentence repeated...

### ISSUE THREAD

**Issue by jpcast88** [MicrosoftDocs/memdocs#1777]
Under this section Monitor scenario health

"Configuration Manager simulates activities to expose performance metrics and failure points. It simulates activities to expose performance metrics and failure points."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55ba9622-311f-0c2c-bce3-f0510a4d2b79
* Version Independent ID: 49d1ca0a-b8b0-bfa9-c735-d45c7118ac9a
* Content: [Enable data sharing - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/desktop-analytics/enable-data-sharing#support-for-new-windows-10-diagnostic-data-levels)
* Content Source: [memdocs/configmgr/desktop-analytics/enable-data-sharing.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/desktop-analytics/enable-data-sharing.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @jpcast88, good catch! Closing this issue as it's fixed
