### ISSUE TITLE
Confusing detail note about TeamViewer not working with Organization-owned devices

### ISSUE THREAD

**Issue by crshovrd41** [MicrosoftDocs/memdocs#1779]
Hi,

I was reviewing this document and noticed a note that said, 

> Organization-owned devices are not supported. Team viewer works with the Company portal app. It doesn't work with the Intune app.

Can someone please explain to me what this means? For example, if my devices are all autopilot and the "ownership" is "corporate," does that mean I can't use the TeamViewer plug-in?

If not, what's the point of the TeamViewer plug-in? Seems relatively useless.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a9ef909-c4fb-f052-9d2e-c794efc9efd7
* Version Independent ID: 655e8b80-0471-5789-8bf1-20403390c012
* Content: [Remotely administer devices in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/remote-actions/teamviewer-support)
* Content Source: [memdocs/intune/remote-actions/teamviewer-support.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/remote-actions/teamviewer-support.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by jorge-ataide** [comment]
Hello @ErikjeMS, could you please answer this question?
Thanks!

**Comment by jorge-ataide** [comment]
Please @ErikjeMS, could you help giving any feedback here? Thank you

**Comment by ErikjeMS** [comment]
@jorge-ataide Here's what the PM had to say. Does this answer your question?

For Android, this note is meant to mean that we do not support TeamViewer on our corporate-owned, Android Enterprise solutions which we manage with the Intune app. This includes Android Enterprise fully managed, dedicated, and corporate-owned work profile devices. Separately, we do support TeamViewer on Android device administrator, and Android Enterprise personal-owned work profile enrollments, both of which are managed by the Company Portal app. 

This note has nothing to do with the corporate vs. personal toggle that ITs can optionally choose to leverage in the device object – for example, if I have an Android device enrolled with device administrator privileges and choose to mark it as a “corporate” device, the TeamViewer plugin will still work if I have the appropriate licensing etc.

**Comment by jorge-ataide** [comment]
@ErikjeMS, thanks for the explanation!
