### ISSUE TITLE
iOS Error code: 0x87D13B6B A user licensed app is assigned to a device with userless enrollment.

### ISSUE THREAD

**Issue by treestryder** [MicrosoftDocs/memdocs#178]
Please add iOS Error code "0x87D13B6B A user licensed app is assigned to a device with userless enrollment".

In part due to the recent UI change, when I deployed an App it defaulted to the license type of "User". After many experiments and failed web searches, I finally figured out that I had to change the deployment to "Device" license type.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 826eb5cf-dadc-a5a6-ff24-793f7e9fb371
* Version Independent ID: 92227d8c-1eb3-e5b7-8dc1-52aaa1eabfd4
* Content: [App installation error codes - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-install-error-codes#feedback)
* Content Source: [memdocs/intune/apps/app-install-error-codes.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-install-error-codes.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by JDFlannery** [comment]
Error code: 0x80190194
The requested URL does not exist on the server - error we get in deploying apps to Windows devices and no reference to this code in you app install error codes

**Comment by Erikre** [comment]
@treestryder and @JDFlannery - Thanks for your feedback. I'm working with the product team to get more info on each of these error conditions. Once I have more info, I'll add the details to the docs. I'm closing this issue now because I'm tracking this work internally.

**Comment by JDFlannery** [comment]
Looking into an additional error code we are seeing now and it's not listed anywhere in your documentation.
0x87D13B8A
More specifically - License Assignment failed with TokenRevoked. (0x87D13B8A) 
Our token isn't revoked and I can't see get any new apps to sync from apple school manager (net new purchased licenses.)
