### ISSUE TITLE
XML example needed

### ISSUE THREAD

**Issue by kevets** [MicrosoftDocs/memdocs#1781]
[Enter feedback here]
I am working on an integration involving another EDR and would like to request an example Intune XML file including the <key>SystemPolicyAllFiles</key> setting for all files access, as well as one for remote control. This will help us integrate trusted tools using Intune MDM instead of having to use an alternative.

My initial attempts are located here, which are passing validation but not getting the desired results.
https://github.com/kevets/intunemdm.com.sentinelone

SK

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5ec92e3-63c1-ce3b-2292-26d9ff83b032
* Version Independent ID: d807ebf3-7d03-4274-6250-2ea99237f788
* Content: [Add preference file settings to macOS devices in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/preference-file-settings-macos)
* Content Source: [memdocs/intune/configuration/preference-file-settings-macos.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/preference-file-settings-macos.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@kevets [https://support.apple.com/guide/mdm/mdm9ddb7e0b5/1/web/1.0](https://support.apple.com/guide/mdm/mdm9ddb7e0b5/1/web/1.0) may have some info you're looking for. 

For questions like this, I suggest posting to [Microsoft Q&A](https://docs.microsoft.com/answers/products/enterprise-mobility-security). If you start creating the XML, and need some help, it's possible the Intune support team help. They don't wrote XML examples, but might be able to provide some guidance:

- Use [get support for Microsoft Intune](https://docs.microsoft.com/mem/get-support) to open a support case.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
