### ISSUE TITLE
Does this only work during autopilot provisioning?

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/memdocs#1785]
Hello, I'm looking to install the company portal on intune enrolled devices without going through autopilot provisioning, this article looks like it will get me there.

If this works for any intune device, I suggest changing the title and this step:

Title:
> Add and assign the Windows 10 Company Portal app for ~~Autopilot~~ enrolled devices - Microsoft Intune

Step:
> To Assign the Company Portal app as a required app to your selected ~~autopilot~~ device groups, select Properties > Edit (next to Assignments) > Add Group (below Required) and then select a device group to assign the app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42b3ccb0-592e-a0bf-aa4f-ab37e00e1195
* Version Independent ID: d0af9188-3489-0f15-ef25-5b6d83edb76c
* Content: [Add and assign the Windows 10 Company Portal app for Autopilot provisioned devices - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/store-apps-company-portal-autopilot)
* Content Source: [memdocs/intune/apps/store-apps-company-portal-autopilot.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/store-apps-company-portal-autopilot.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by jonwbstr** [comment]
Hi @Leicham,

I've been looking into this further and haven't worked out why the guide is for doing an Offline app instead of an Online app. Why would we want to lock the company portal to a specific version?

The online version requires different steps, maybe the author thought offline was less complicated to setup? 

Is offline really recommended over online, or should we should prefer online unless business requirements call for the offline approach?

**Comment by jonwbstr** [comment]
I found a non autopilot version of the article with an internet search and notice it's under the heading "Company Portal app - Download" I haven't tried to compare the two articles very closely but adding the app to intune and adding it to autopilot should be identical aside from which group the app is assigned to since they both use intune...

Company Portal app - Autopilot
Add and assign the Windows 10 Company Portal app for Autopilot provisioned devices

Company Portal app - Download
Add the Windows 10 Company Portal app by using Microsoft Intune

**Comment by jonwbstr** [comment]
Hello,

I notice the table of contents lists "Company Portal app - Download" and the title of the article is "Add the Windows 10 Company Portal app by using Microsoft Intune"

https://docs.microsoft.com/en-us/mem/intune/apps/store-apps-company-portal-app

Looking at the two articles they seem to be be the same article but the authors chose to provide detailed steps for different areas of the process... not really sure what is going on here

**Comment by yogkumgit** [comment]
@jonwbstr Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by jonwbstr** [comment]
@yogkumgit did you want me to open separate issues for the other items?

Merge with or reference the other article?
Add the word offline to the title?
Explain in what scenarios if any, someone would prefer offline to online

**Comment by yogkumgit** [comment]
@jonwbstr Thanks for the follow up. Please go ahead and do it. I will get it reviewed and resolved it. Appreciate your interest.
