### ISSUE TITLE
RSS Feed link does not work correctly

### ISSUE THREAD

**Issue by ThiloBaron** [MicrosoftDocs/memdocs#1790]
Hello,

I tried with two different RSS Feed readers the link
https://docs.microsoft.com/api/search/rss?search=%22in+development+-+microsoft+intune%22&locale=en-us 
and both are not showing all and latest Microsoft announcements.

KR
Thilo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d16c28db-1e8e-31fa-6127-3050a2940422
* Version Independent ID: 4cf9a244-1ae5-1637-48f7-3f503d400da6
* Content: [What's new in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new)
* Content Source: [memdocs/intune/fundamentals/whats-new.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/whats-new.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by aczechowski** [comment]
Thanks for the feedback. We've received other feedback on this issue. I'm making a change to remove the example and point back to [How to use the docs](https://docs.microsoft.com/mem/use-docs#notifications), which has more explanation. I'm hoping that some variation on the query string will work.

If it _still_ doesn't work, we'll just need to remove the tip to get notified. The RSS functionality comes from the docs.ms platform (we can promote the issue to that team if needed), and obviously we don't know what sort of RSS application you're using. Unfortunately docs.ms doesn't offer another option for notification. 😞
