### ISSUE TITLE
More information for SQL edition licensing included with Configuration Manager

### ISSUE THREAD

**Issue by andrewjohnporter** [MicrosoftDocs/memdocs#1791]
[Enter feedback here]
Under the section **What are the use rights associated with the SQL Server technology provided with Configuration Manager?**

Please can you give information about which SQL editions the SQL license for ConfigMgr includes. Does it cover the Enterprise and Standard?

Some expanded information on CAL and Core licensing would be good as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e55ebfe-c297-9cd2-34ec-4680cbd2f9fd
* Version Independent ID: 26debf60-c3c1-caa6-7f78-a04a8b8e73af
* Content: [Product and licensing FAQ - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/understand/product-and-licensing-faq)
* Content Source: [memdocs/configmgr/core/understand/product-and-licensing-faq.yml](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/understand/product-and-licensing-faq.yml)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @andrewjohnporter, thanks for the feedback, but we made a decision earlier last year to specifically not include that topic in this article. For more information, see the following historical issues:

- MicrosoftDocs/SCCMdocs#1274
- MicrosoftDocs/SCCMdocs#464
