### ISSUE TITLE
Add “cloudpc” as a devicemodel value

### ISSUE THREAD

**Issue by blecerf** [MicrosoftDocs/memdocs#1795]
We've been advised that in order to capture all CP devices, you must also include Value = “Cloud PC” or “cloudpc” for the devicemodel property.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83466fa4-a465-0919-226b-03ed3af507da
* Version Independent ID: 0daf4065-4a81-ec2e-c343-ea20d6a4a254
* Content: [Create a dynamic device group for all Cloud PCs - Azure](https://review.docs.microsoft.com/en-us/windows-365/create-dynamic-device-group-all-cloudpcs?branch=release-windows-365)
* Content Source: [windows-365/create-dynamic-device-group-all-cloudpcs.md](https://github.com/MicrosoftDocs/memdocs/blob/master/windows-365/create-dynamic-device-group-all-cloudpcs.md)
* Service: **cloudpc**
* Sub-service: ****
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Noted in live docs here: https://docs.microsoft.com/en-us/windows-365/create-dynamic-device-group-all-cloudpcs
