### ISSUE TITLE
Typo on this page

### ISSUE THREAD

**Issue by blecerf** [MicrosoftDocs/memdocs#1796]
The top of the page says: You can do this by creating a dynamic device group containing all level 2 Cloud PCs provisioned from a specific provisioning policy.

However, the dynamic group query only looks for cloud pc and level 2 - it does not filter on a specific provisioning policy.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb45d047-a619-7ffc-4528-e755de836c4b
* Version Independent ID: 1278256f-d6b1-becd-c4b5-d44bc95d9b67
* Content: [Create a dynamic device group for all level 2 Cloud PCs - Azure](https://review.docs.microsoft.com/en-us/windows-365/create-dynamic-device-group-all-level-2-cloudpcs?branch=release-windows-365)
* Content Source: [windows-365/create-dynamic-device-group-all-level-2-cloudpcs.md](https://github.com/MicrosoftDocs/memdocs/blob/master/windows-365/create-dynamic-device-group-all-level-2-cloudpcs.md)
* Service: **cloudpc**
* Sub-service: ****
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
This doc was removed before launch.
