### ISSUE TITLE
Add new levels

### ISSUE THREAD

**Issue by blecerf** [MicrosoftDocs/memdocs#1797]
This includes "Level 2" CPCs, but at launch there will be 4 SKUs.

We should include those as well as call out their respective devicemodel property values.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb45d047-a619-7ffc-4528-e755de836c4b
* Version Independent ID: 1278256f-d6b1-becd-c4b5-d44bc95d9b67
* Content: [Create a dynamic device group for all level 2 Cloud PCs - Azure](https://review.docs.microsoft.com/en-us/windows-365/create-dynamic-device-group-all-level-2-cloudpcs?branch=release-windows-365)
* Content Source: [windows-365/create-dynamic-device-group-all-level-2-cloudpcs.md](https://github.com/MicrosoftDocs/memdocs/blob/master/windows-365/create-dynamic-device-group-all-level-2-cloudpcs.md)
* Service: **cloudpc**
* Sub-service: ****
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
The "level" descriptors were replaced by spec info for the different Cloud PCs available. So, no change here is needed any more.
