### ISSUE TITLE
Heading links

### ISSUE THREAD

**Issue by VeloChap** [MicrosoftDocs/memdocs#18]
Several headings on this page do not have URLs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ccdf61a-a456-9c6f-9c2f-10c9fd774a31
* Version Independent ID: 07a9f40b-9710-faa7-8210-a81fabec3bf8
* Content: [Use private and public key certificates in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/certficates-pfx-configure)
* Content Source: [memdocs/intune/protect/certficates-pfx-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certficates-pfx-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@VeloChap   Thanks for the heads-up on this.   This appears to be a publishing issue for the page and might be affecting other pages (though I've not found any).  However, the most recent publishing run didn't fix the issue that I can see, so were handing off an investigation to our publishing team. 

Meanwhile, I do see that while the Links for headers are not being 'displayed' on the page during mouse over of a heading, they are still functional.  Each level 2 header still appears in our _In this article_ list which is at the upper right of the article and seems to function. (Only level 2 headers are expected in that list).

For lower level headers, links also still function as expected - though not shown on the page during mouse over.   For example,  the URL link to the **Subject name format** sub section isn't visually indicated in the article but functions.   To test that you can add the header to the article URL as follows: add **#subject-name-format** to the end of the articles default URL.  That looks like the following full URL:   https://docs.microsoft.com/en-us/mem/intune/protect/certficates-pfx-configure#subject-name-format
