### ISSUE TITLE
documentation for v4 baseline?

### ISSUE THREAD

**Issue by sveinungre** [MicrosoftDocs/memdocs#180]
Where is documentation for the v4 profile - I can see its available in Intune.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10ff4382-415c-4e80-e958-3bd77252fe2d
* Version Independent ID: 398a5b4b-e8bd-1f7d-ae30-38d812daf90d
* Content: [Intune security baselines settings for Microsoft Defender Advanced Threat Protection - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/security-baseline-settings-defender-atp)
* Content Source: [memdocs/intune/protect/security-baseline-settings-defender-atp.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/security-baseline-settings-defender-atp.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@sveinungre   It looks like the product group released and update and docs wasn't looped in.  The only change from the previous v3 baseline is that the setting **On Access Protection ** had its default change from *Yes* in v3, to be *Not configured* in v4. 

The content has now updated, and similar to other baselines, there is now a selector at the top so you can flip between the two.
