### ISSUE TITLE
Contradictory information about required factory reset

### ISSUE THREAD

**Issue by robinhobo** [MicrosoftDocs/memdocs#1802]
The text on this page is contradictory in some places. For example, 'Android Enterprise fully managed', what steps are required when the device is managed by another MDM solution and you want to migrate to Intune? First at states "To be fully managed by Intune, users need to unenroll from the current MDM provider, and then enroll in Intune" and a few lines later "Factory reset the devices. This step is required."

Kind regards,

Robin Hobo

Microsoft MVP - Enterprise Mobility
![0066](https://user-images.githubusercontent.com/60141658/126493768-c8ee83c3-0cdd-41ff-b4db-d04581573262.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ace6b22-6f66-fd63-321f-14b4a6b0e295
* Version Independent ID: e5e2c425-99ac-df60-2439-2335d12a68df
* Content: [Android device enrollment guide for  Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/fundamentals/deployment-guide-enrollment-android)
* Content Source: [memdocs/intune/fundamentals/deployment-guide-enrollment-android.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/deployment-guide-enrollment-android.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@robinhobo Thank you! Both statements are correct. So, we're going to keep the current text. 

That being said, if you think more info should be added after "To be fully managed...", please create a pull request with your recommended changes. I think I understand your intent, but would benefit from seeing it in your words. If you're unsure how to create a pull request, the steps are at [https://github.com/MicrosoftDocs/memdocs](https://github.com/MicrosoftDocs/memdocs). Just scroll past the folder view.

Thanks!

**Comment by robinhobo** [comment]
@MandiOhlinger, thank you for your replay.

Yes, in some way both statements are correct. However, there is a difference between a full wipe / factory reset what is required as administrator tasks and will ALL data from a device (also personal photos for example), and just an unenrollment where the user just removes the MDM profile from the old MDM solution and starts the MDM enrollment with downloading the Intune Company Portal. In the last case the private data stays remain on the device. So for a company and the end user this is a major different. So in my opinion the first statement should be replaced by the second one (administrator actions) to be completely clear what the impact is of the device migration.
