### ISSUE TITLE
Clarification on assigning PKCS certificates and related configuration profiles on Android Enterprise

### ISSUE THREAD

**Issue by jRob2k** [MicrosoftDocs/memdocs#1803]
[Enter feedback here]
After working with Microsoft Support for a few weeks we found that all related configurations must be deployed to the same kind (user/device) of group or else Wi-Fi or Identity certificates can get stuck with a "Pending" status on Android Enterprise devices indefinitely. 

I think a note that all related configurations (Trust certificates, PKCS Certificate and Wifi configuration) must target the same kind of assignment group would be beneficial. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41df2048-2b0e-4218-1fc4-d8a657f860cc
* Version Independent ID: e26c4390-87a3-7d5a-4e6f-529b4ccf8759
* Content: [Use private and public key certificates in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/certificates-pfx-configure)
* Content Source: [memdocs/intune/protect/certificates-pfx-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certificates-pfx-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@jRob2k   Hi Jay, looks like this slipped our net for a response. The content does call out in in the assignement step of two procedures that the _trusted certificate profile_ and _PKCS certificate profile_ need to be deployed to the same groups.  If that doesn't cover what your asking, then I'm missing a nuance of this that would meet what your asking for.  While I would hope that our Support team would have submitted a content edit to assist in fixing this, perhaps you could provide your thoughts on what a note or content update might say and where that informtaion might land in this article to help others avoid the same problem?  With the right information, I can then evaluate possible doc solutions. 

Perhaps the current statements need expansion to mention distributoin to the same groups that recieve relevant wi-fi or VPN profiles?

**Comment by jRob2k** [comment]
Hi Brent,

Thanks for the response. Related profiles like "Wi-Fi" profiles need to be
distributed to the same kind of group. For example, I deployed Trust
Certificates to all devices, PKCS Certificates to user groups and WiFi
configurations to device groups and the WiFi and PKCS certificate
configurations hung at pending indefinitely.

After weeks of troubleshooting with Microsoft support they determined that
deploying all related configurations to a user or device groups, but not
mixing them.

I'm not sure if this is a bug or by design, but hopefully a note added to
the doc can save others some frustration. I like your suggested note. I
think that covers it if this is by design.

**Comment by yogkumgit** [comment]
@Brenduns Please help is resolving this issue. Thanks

**Comment by Brenduns** [comment]
Content has been updated via https://github.com/MicrosoftDocs/memdocs-pr/pull/7688. Merged on May 26, 2022, and expected to publish on 5/27/2022.

Closing issue as resolved.
