### ISSUE TITLE
Licensing Error - "Can't connect to the connected user experience and telemetry endpoint (Vortex). Check your network/proxy settings"

### ISSUE THREAD

**Issue by PaulKlerkx** [MicrosoftDocs/memdocs#1804]
Hi,
something that should maybe be added to this section - it would have saved me some time, may help others.  

> 
> Windows diagnostic endpoint connectivity
> If this check is successful, then the device can connect to the Connected User Experience and Telemetry endpoint (Vortex).
> 
> Otherwise, it may show one of the following errors:
> 
> Can't connect to the connected user experience and telemetry endpoint (Vortex). Check your network/proxy settings
> 
> Can't check connectivity to the connected user experience and telemetry endpoint (CheckVortexConnectivity). Check the logs for the exception details
> 
> Devices verify connectivity with a GET request to the following endpoint based on OS version:
> 
> WINDOWS DIAGNOSTIC ENDPOINT CONNECTIVITY
> OS version	Endpoint
> - Windows 10, version 1809 or later
> - Windows 10, version 1803 with the 2018-09 cumulative update or later	https://v10c.events.data.microsoft.com/health/keepalive
> Windows 10, version 1803 without the 2018-09 or later cumulative update	https://v10.events.data.microsoft.com/health/keepalive
> Windows 10, version 1709 or earlier	https://v10.vortex-win.data.microsoft.com/health/keepalive
> Windows 7 or Windows 8.1	https://vortex-win.data.microsoft.com/health/keepalive
> Make sure the device can communicate with the service. This check validates some but not all of the required endpoints. For more information, see Endpoints.
> 
> For more information, review M365AHandler.log on the client.

The message - "Can't connect to the connected user experience and telemetry endpoint (Vortex). Check your network/proxy settings" may have nothing to do with network or proxy.  It may indicate a licensing error in that the logged in user of the device hasn't been issued a license that allows connection to DA.  (E3/E5)
I have tested and proved this theory in our environment.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 819ede64-7469-d780-6420-bc785f459a1e
* Version Independent ID: d80b24c8-02d3-8958-79cb-10db3a6c8785
* Content: [Monitor connection health - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/desktop-analytics/monitor-connection-health)
* Content Source: [memdocs/configmgr/desktop-analytics/monitor-connection-health.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/desktop-analytics/monitor-connection-health.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @PaulKlerkx for the feedback!
