### ISSUE TITLE
Spelling mistake in section 5

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/memdocs#1806]
Only a minor change
I have noticed a spelling mistake in section 5 of this page.
nonmanged should read non-managed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a115de4-fba0-d631-b536-b26295137afa
* Version Independent ID: 403182cd-fa95-98cd-6e27-3d5d0ba86863
* Content: [Guided scenario - Secure Microsoft Office mobile apps - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/guided-scenarios-office-mobile)
* Content Source: [memdocs/intune/fundamentals/guided-scenarios-office-mobile.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/guided-scenarios-office-mobile.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Crimsonfox89** [comment]
Fixed in https://github.com/MicrosoftDocs/memdocs/pull/1879
