### ISSUE TITLE
Script enters an endless loop if there are no existing profiles in Endpoint Manager

### ISSUE THREAD

**Issue by noblevarghese** [MicrosoftDocs/memdocs#1810]
If a customer is settings this for first time and if the customer doesn't have any profile footprint, because of below code, the script enters an endless loop and doesn't timeout or show any error

while($profileNameExist)
    {
        foreach($display in $profiles)
        {
            $name = $display.displayName.Split("-")
            $profileNameExist = $false
            if($name[0] -eq $profileName)
            {
                $profileNameExist = $true
                $profileName = Read-Host -Prompt $Strings.ProfileExists
                while(-not($profileName))
                {
                    $profileName = Read-Host -Prompt $Strings.ProfileCannotBeBlank 
                }        
                break
            }
        }
    }

Either add this as a prerequisite or fix this so that the loop breaks. Thanks! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bffd4704-acbf-a7e8-073f-7b0de922dcd8
* Version Independent ID: 39cc8624-ede4-2ec9-ea79-607347e5d17d
* Content: [Endpoint security firewall rule migration tool for Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/endpoint-security-firewall-rule-tool#switches)
* Content Source: [memdocs/intune/protect/endpoint-security-firewall-rule-tool.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/endpoint-security-firewall-rule-tool.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by yogkumgit** [comment]
@Brenduns Please help us in resolving this issue. Thanks

**Comment by Brenduns** [comment]
@noblevarghese   We've passed this information on to the development/PM team some time back so it could be investigated. That doesn't appear to have been completed, or to be a current priority, and I believe the script has remained unchanged. If you continue to have issues with the script, I recommend opening a support call to seek assistance, which can bring more urgency to getting investigation and a possible fix for this condition add to the script.
