### ISSUE TITLE
Using Invoke-MbamClientDeployment.ps1 in Task Sequence

### ISSUE THREAD

**Issue by Ickis99** [MicrosoftDocs/memdocs#1812]
So, does this mean it supported again to use the Invoke-MbamClientDeployment.ps1 to encrypt clients when
Bitlocker Integration is used? Or is ist still unsupported as described in https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/how-to-enable-bitlocker-by-using-mbam-as-part-of-a-windows-deploymentmbam-25 and it just prevents the policy storms?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 984e9d4a-d2f4-f8ae-4dad-afa19955baac
* Version Independent ID: b5fda0d5-71f1-6f30-45d0-1c9b6f9a0947
* Content: [Using the MBAM Agent to escrow BitLocker recovery keys generates excessive policies in Configuration Manager version 2103 - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/hotfix/2103/10372804)
* Content Source: [memdocs/configmgr/hotfix/2103/10372804.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/hotfix/2103/10372804.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by vinaypamnani-msft** [comment]
@Ickis99 supportability of the script is being evaluated, but the hotfix does prevent the policy storm. Technically, the script has never been supported with BitLocker implementation in ConfigMgr but it continued to work without causing issues, and the hotfix maintains that status-quo. If the official supportability stance changes, we'll update the docs.

**Comment by Ickis99** [comment]
I understand. Thank you for the information.

Regards

Jürgen Winter


Base-IT GmbH
Haider Straße 23 | 4052 Ansfelden | Austria | www.baseit.at
​UID: ATU 65374524
Follow us on
Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, 
 informieren Sie bitte unverzüglich den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet. 
 This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) 
 please notify the sender immediately and destroy this e-mail. Any unauthorized copying, disclosure or distribution of the material in this e-mail is strictly forbidden.
Von: Vinay Pamnani ***@***.***>
Gesendet: Donnerstag, 29. Juli 2021 22:21
An: MicrosoftDocs/memdocs ***@***.***>
Cc: Winter Juergen | base-IT ***@***.***>; Mention ***@***.***>
Betreff: Re: [MicrosoftDocs/memdocs] Using Invoke-MbamClientDeployment.ps1 in Task Sequence (#1812)


@Ickis99<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FIckis99&data=04%7C01%7C%7Cca3f4e9bbd9140c84f5608d952ce6036%7C95daffb5be3a4f10bafa3ab2069eebfc%7C0%7C0%7C637631868603880545%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3JxARoq9O8NJF3hTm0cg1aABp9iD5KiJ%2BItWHye%2BlTM%3D&reserved=0> supportability of the script is being evaluated, but the hotfix does prevent the policy storm. Technically, the script has never been supported with BitLocker implementation in ConfigMgr but it continued to work without causing issues, and the hotfix maintains that status-quo. If the official supportability stance changes, we'll update the docs.

-
