### ISSUE TITLE
Clarification for GPO setting 'AllowDesktopAnalyticsProcessing'

### ISSUE THREAD

**Issue by faceball2000** [MicrosoftDocs/memdocs#1814]
Clarification required please regarding new setting 'AllowDesktopAnalyticsProcessing'

Is this an optional policy or must this now be set via GPO for Desktop Analytics to function? (Config Manager 2006+ does not set this policy in registry although document states it does)

In one section it states; "Desktop Analytics requires a value of 2 for data collection to work correctly." 
Further down on page it states "If you configure this policy to Disabled (0), devices may not appear in Desktop Analytics."

So, I'm uncertain if this policy setting is now a pre-requirement for DA to function, or we only set if we want to block DA.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f7dc639-d79e-84da-1ec9-66407ac237ee
* Version Independent ID: 8846b4d9-ee8d-2961-5c70-c60a3af81552
* Content: [Group policy settings - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/desktop-analytics/group-policy-settings)
* Content Source: [memdocs/configmgr/desktop-analytics/group-policy-settings.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/desktop-analytics/group-policy-settings.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @faceball2000, thanks for the feedback. A couple of comments:
- If you're finding CM v2006+ not setting the policies, please file a frown in the console to file a bug, and/or call support to investigate. Configuration Manager sets the policies as necessary, you shouldn't have to do anything in policy. This article is provided as a reference for more technical detail, and in case you have more complex business requirements.
- Have you seen this recent change notice? [Support for the Windows diagnostic data processor configuration](https://docs.microsoft.com/mem/configmgr/desktop-analytics/whats-new#support-for-the-windows-diagnostic-data-processor-configuration)
- ConfigMgr should set AllowDesktopAnalyticsProcessing to 2 on enrolled devices for DA to work. Note you'll only see it on supported versions of Windows 10. You don't need to set this value. If you do set it to 0 via some other means (like GPO), then you'll effectively disable DA.
