### ISSUE TITLE
Pending Action

### ISSUE THREAD

**Issue by vanessbrckn** [MicrosoftDocs/memdocs#1817]
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c79f5e46-0615-682c-0368-5a14cfa738e7
* Version Independent ID: 08094776-efc7-d7b1-0b82-0aee1dac5634
* Content: [Lock devices with Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/remote-actions/device-remote-lock)
* Content Source: [memdocs/intune/remote-actions/device-remote-lock.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/remote-actions/device-remote-lock.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by msbemba** [comment]
@vanessbrckn Thank you for your feedback. If the remote lock option is not going through and is stuck in pending, there could be various reasons for this issue. I'd recommend you open a support case with Microsoft via the need help section on the admin center.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @vanessbrckn Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
