### ISSUE TITLE
Require app protection policy  is no longer in preview  

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/memdocs#1819]
When creating a Conditional Access Policy  under Access controls the Require app protection policy is now as showing as available as the wording '(preview)' has now been removed when setting up a policy 
![image](https://user-images.githubusercontent.com/69439002/127703930-45d1e344-b770-4be6-a0c2-1f640d01fa14.png)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae85fdc5-1194-80b9-ecb5-def834573789
* Version Independent ID: 184b3caf-5c85-b808-3025-19b024400597
* Content: [Set up app-based Conditional Access policy with Intune - Microsoft Intune](https://docs.microsoft.com/en-gb/mem/intune/protect/app-based-conditional-access-intune-create)
* Content Source: [memdocs/intune/protect/app-based-conditional-access-intune-create.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/app-based-conditional-access-intune-create.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@nikki-c  Thanks for the heads up on that change. I've submitted a content edit to align docs to that change to GA for the opton. That will update on-line later today.
