### ISSUE TITLE
Broker app can validate if the app is authorized for use by the user?

### ISSUE THREAD

**Issue by derekharkin** [MicrosoftDocs/memdocs#182]
This flow is great and I understand almost all of it except this part of #5

"There's a security layer so the broker app can validate if the app is authorized for use by the user."

Can this point be expanded more? What is the validation and authorization?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca76fcaf-979f-7b6b-c410-34080685d415
* Version Independent ID: eaceac76-73c4-c586-952c-8dfa90390c6e
* Content: [App-based Conditional Access with Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/app-based-conditional-access-intune#feedback)
* Content Source: [memdocs/intune/protect/app-based-conditional-access-intune.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/app-based-conditional-access-intune.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@derekharkin  Following up on orphaned questions. I apologize that this has taken so long to get a response on. 

You asked about validation and authorization, and I’ve received the following slight expansion  on the details from our engineering team. I hope this a more complete explanation and of use. 

_The broker confirms the Azure AD device ID, the user, and the application. This information is passed to the Azure AD login servers to validate access to the requested service._
