### ISSUE TITLE
List of supported platforms.

### ISSUE THREAD

**Issue by randomat123** [MicrosoftDocs/memdocs#1822]
Does the table of supported plataform is correct/updated?

All documentation gives the impression that IMEI is a supported way of registering devices, but in the table IMEI is not supported with any of the plataforms.

Also, I confirmed we can use IMEI at least with iOS devices.

(admin edit: adding article metadata for proper tracking)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcd313b3-e225-849a-def5-8a32a08a92e9
* Version Independent ID: 917b6190-a8bd-f55d-3e71-f403a395721f
* Content: [Add corporate identifiers to Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/corporate-identifiers-add)
* Content Source: [memdocs/intune/enrollment/corporate-identifiers-add.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/corporate-identifiers-add.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@jorge-ataide Which article are you referring to?

**Comment by jorge-ataide** [comment]
Hello @ErikjeMS, this one: https://docs.microsoft.com/en-us/mem/intune/enrollment/corporate-identifiers-add

If you prefer, I can open this issue there. I didn't see I sent in the wrong place.

Thanks!

**Comment by ErikjeMS** [comment]
@jorge-ataide Yes, it's probably best if you close this one and open a new on on the target article. It's easier for us to track that way.

**Comment by jorge-ataide** [comment]
@ErikjeMS, ok, doing it right now. Thanks!

**Comment by jorge-at123** [comment]
Hello @ErikjeMS, please, is there any update about this topic?

**Comment by msbemba** [comment]
@randomat123 Thank you for your feedback. We have updated the list with Support platforms. IMEI is supported in Android Enterprise personally-owned work profile, before Android 12. Serial Numbers are the recommended form of identification for iOS/iPadOS devices, However it is Supported in some cases where there is only one IMEI number( Some Android and iOS/iPadOS devices have multiple IMEI numbers).

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @randomat123 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
