### ISSUE TITLE
Need a little clarification of a sentence

### ISSUE THREAD

**Issue by baardhermansen** [MicrosoftDocs/memdocs#1823]
Hi

There's a sentence that reads 

> As a best practice, create and assign apps specifically for your user groups, and separately for your device groups.

Does that mean we should create two versions of the same application, one for users and another for computers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f336a29-b7e7-8ba2-1306-2c4d7ebdbb45
* Version Independent ID: 0bf92b5d-2e69-d207-233d-fdef9b314b9f
* Content: [Include and exclude app assignments in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-inc-exl-assignments)
* Content Source: [memdocs/intune/apps/apps-inc-exl-assignments.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/apps-inc-exl-assignments.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by yogkumgit** [comment]
@baardhermansen Thank you very much for opening the issue.  Considering the nature of the issue please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
