### ISSUE TITLE
Conflicting Boundary group options for peer downloads

### ISSUE THREAD

**Issue by ChadSimmons** [MicrosoftDocs/memdocs#183]
When a computer is assigned of more than one Boundary Group due to overlapping Boundaries, what is the resultant policy for Boundary Group Peer download options that conflict?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a2d3a58-d1b9-6f56-8f0c-dfdf2733b670
* Version Independent ID: 436c5f30-086a-5c8a-d9b3-98a017f9f55b
* Content: [Configure boundary groups - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/boundary-groups#bkmk_bgoptions)
* Content Source: [memdocs/configmgr/core/servers/deploy/configure/boundary-groups.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/deploy/configure/boundary-groups.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @ChadSimmons, I just made a revision to this article late last week that explains the client behaviors when there is a conflict in the boundary group configuration. In [this section](https://docs.microsoft.com/mem/configmgr/core/servers/deploy/configure/boundary-groups#bkmk_bgoptions), see the bullets that start with the line, "If a device is in more than one boundary group, the following behaviors apply for these settings..."
If that doesn't answer your question, can you please clarify?

**Comment by ChadSimmons** [comment]
Thanks Aaron.  Great timing.
