### ISSUE TITLE
Cloud PC - Incorrect Device Model

### ISSUE THREAD

**Issue by justinstanley** [MicrosoftDocs/memdocs#1831]
Cloud PC's are being created with the Device Model of "Virtual Machine" not "Cloud PC" as indicated in this article. 

![image](https://user-images.githubusercontent.com/15387023/127919935-880e1c16-b27b-4993-ab11-32b33d4d965b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83466fa4-a465-0919-226b-03ed3af507da
* Version Independent ID: 0daf4065-4a81-ec2e-c343-ea20d6a4a254
* Content: [Create a dynamic device group for all Cloud PCs](https://docs.microsoft.com/en-us/windows-365/create-dynamic-device-group-all-cloudpcs)
* Content Source: [windows-365/create-dynamic-device-group-all-cloudpcs.md](https://github.com/MicrosoftDocs/memdocs/blob/master/windows-365/create-dynamic-device-group-all-cloudpcs.md)
* Service: **cloudpc**
* Sub-service: ****
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...

**Comment by ErikjeMS** [comment]
@justinstanley The PM tells me it should be "Cloud PC". If you can consistently repro this he suggests that you open a support ticket to resolve.
