### ISSUE TITLE
Remote Desktop App shows Windows 8.1

### ISSUE THREAD

**Issue by PaulTozer** [MicrosoftDocs/memdocs#1835]
Thought 8.1 was not supported in the Windows Remote Desktop Client Application. Should this be Windows 7 as that is.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 936bcfce-ca8b-7262-45f0-8c99b65264d1
* Version Independent ID: abc7b844-be0c-374e-ba66-5af2ab8e928a
* Content: [Accessing Cloud PCs](https://docs.microsoft.com/en-gb/windows-365/end-user-access-cloud-pc)
* Content Source: [windows-365/end-user-access-cloud-pc.md](https://github.com/MicrosoftDocs/memdocs/blob/master/windows-365/end-user-access-cloud-pc.md)
* Service: **cloudpc**
* Sub-service: ****
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@Paultozer, what is your request here? We don't mention 8.1 in this article.

**Comment by PaulTozer** [comment]
It looks to have moved location, but the mention is still there. It is now

"Remote Desktop clients | Microsoft Docs" https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-clients

Applies to: Windows Server 2022, Windows 10, Windows 8.1, Windows Server 2019, Windows Server 2016, Windows Server 2012 R2

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ErikjeMS** [comment]
@PaulTozer I see. That article is outside my doc set. To get that article changed, you'll need to go to that page and open a new Issue on it. I'll close this issue as there's nothing for me to do in this article. Thanks!
