### ISSUE TITLE
List of supported platforms

### ISSUE THREAD

**Issue by jorge-ataide** [MicrosoftDocs/memdocs#1836]
Does the table of supported plataform is correct/updated?

All documentation gives the impression that IMEI is a supported way of registering devices, but in the table IMEI is not supported with any of the plataforms.

Also, I confirmed we can use IMEI at least with iOS devices.

**Comment by aczechowski** [comment]
Closing as a dupe of #1822 
I know @ErikjeMS suggested opening a new issue, but it still didn't pick up the article metadata, so I manually added it to the other issue. 😄
