### ISSUE TITLE
UST now required for Site Server installation

### ISSUE THREAD

**Issue by andrewjohnporter** [MicrosoftDocs/memdocs#1837]
Hi,

Just wondering why USMT is now required for the Site Server install. It's failing a pre-check because this component isn't installed. In the past you didn't need it and I don't intend to capture or restore data so won't use this feature.

Thanks,

Andrew

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dfe68a2-a99f-0b41-bd9a-9cc916e02076
* Version Independent ID: b862a3e8-7605-23d6-60b8-5360bd5ba9cf
* Content: [OSD infrastructure requirements - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/osd/plan-design/infrastructure-requirements-for-operating-system-deployment)
* Content Source: [memdocs/configmgr/osd/plan-design/infrastructure-requirements-for-operating-system-deployment.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/osd/plan-design/infrastructure-requirements-for-operating-system-deployment.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @andrewjohnporter, the ADK has always been required on the site server, and USMT is part of the ADK. That's not a new prereq check. Also see:

- [Site server prerequisites](https://docs.microsoft.com/mem/configmgr/core/plan-design/configs/site-and-site-system-prerequisites#central-administration-site-and-primary-site-servers) (note the ADK subsection)
- [List of prereq checks](https://docs.microsoft.com/mem/configmgr/core/servers/deploy/install/list-of-prerequisite-checks#usmt-installed)

**Comment by andrewjohnporter** [comment]
Thanks. Sure, I know ADK is required but from from 2016-2019 I'm pretty sure only the Deployment Tools feature of ADK was required to install ConfigMgr, the USMT was not a required feature just an optional feature. Now it's failing the pre-check because it doesn't have USMT installed but it does have ADK (deployment tools) installed.

**Comment by aczechowski** [comment]
What version of Configuration Manager are you updating to?

**Comment by andrewjohnporter** [comment]
It's a completely fresh install with baseline version 2103
________________________________

**Comment by aczechowski** [comment]
I double-checked with one of our senior OSD engineers:

> USMT has always been required – nothing changed.
> In a hierarchy it’s required on CAS along with WinPE and tools/DISM, primaries do not require it, they require WinPE and tools/DISM.
> On standalone primary it’s required along with WinPE, and Tools/DISM

So perhaps you're remembering installing on a child primary in the past?

**Comment by andrewjohnporter** [comment]
I was just installing regular primary sites.

There's a chance I could be remembering wrong I guess but I'm 90% sure. To check I had a look through a few of the MVP blogs which have installation guides just to check, some had USMT selected and some didn't. I'll have to ask around the community. I suppose it's not very important either way but would be good to know if the requirement was changed and why.

Thanks.
________________________________
