### ISSUE TITLE
cloud pc provisioning

### ISSUE THREAD

**Issue by n1ge1m** [MicrosoftDocs/memdocs#1842]
I have managed to create a cloud pc by adding a W365 license to a user which then built a W10 cloud pc.  When I look in MEM\Intune under 'Provisioning' I see 'Windows 365' however, there are no options to create a connection or create a policy etc.  Any suggestions - My MEM admin user has owner on the sub, network contributor on the rg and the vnet and my users have M365 BP license?
![cpc](https://user-images.githubusercontent.com/27770962/128214339-3659c2c4-e972-42f0-bcec-faabf1fe3c0c.PNG)

**Comment by n1ge1m** [comment]
Answering my own question!

There are 2 SKUs for Cloud PCs, Business and Enterprise.  For Business SKU you just assign the license to a user and the Cloud PC gets provisioned automatically.  For the Enterprise SKU you get to use MEM for management activities so once the Enterprise licence is assigned the W365 options will become available.

Cloud PC Business
![cpcbusiness](https://user-images.githubusercontent.com/27770962/128347252-45c262f5-de24-47f2-9a37-15f99065de19.PNG)

Cloud PC Enterprise
![cpcenterprise](https://user-images.githubusercontent.com/27770962/128347319-b3ce4fb8-d4a1-41e7-971a-92d4c7e16710.PNG)

**Comment by aczechowski** [comment]
@n1ge1m I'm going to close this issue. I think since you filed this, we've published more detailed documentation on Windows 365, see https://docs.microsoft.com/windows-365/
If you still have feedback on this topic, please reopen the issue.
