### ISSUE TITLE
Add Foxpass to the Third-party certification authority partners section list

### ISSUE THREAD

**Issue by danishfoxpass** [MicrosoftDocs/memdocs#1843]
Add [Foxpass](https://docs.foxpass.com/docs/scep#windows-devices--intune-settings) to the Third-party certification authority partners section [list of partners here](https://docs.microsoft.com/en-us/mem/intune/protect/certificate-authority-add-scep-overview#third-party-certification-authority-partners)

---
#### Document Details

Add [Foxpass](https://docs.foxpass.com/docs/scep#windows-devices--intune-settings) to the Third-party certification authority partners section [list of partners here](https://docs.microsoft.com/en-us/mem/intune/protect/certificate-authority-add-scep-overview#third-party-certification-authority-partners)

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cda83a64-56ae-a632-dc81-dfd1a03984c1
* Version Independent ID: b93da48e-4097-4c3a-f6c8-02a5c4e0a616
* Content: [Use third-party certification authorities (CA) with SCEP in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/certificate-authority-add-scep-overview#third-party-certification-authority-partners)
* Content Source: [memdocs/intune/protect/certificate-authority-add-scep-overview.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certificate-authority-add-scep-overview.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by danishfoxpass** [comment]
Hello, any update on this? Thanks

**Comment by Brenduns** [comment]
@danishfoxpass   The PM for this feature area will reach out to you regarding the process to get Foxpass added to the article. If you've not been contacted by 8/20, let me know here and i'll bump that task for them.
