### ISSUE TITLE
Misleading set of actions.

### ISSUE THREAD

**Issue by Mal-G** [MicrosoftDocs/memdocs#1844]
[
The list of actions that can be performed under "Select Devices > All devices > select one of your listed devices to open its details:" on this page are wrong and misleading - some may say Windows-centric.
For example, you can perform a Restart action on iOS/iPadOS Supervised devices, even some Android devices. 
That whole section needs a rewrite. 
]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905c303e-4306-38ec-2a30-4852a8c1bc2b
* Version Independent ID: ceb7e815-e19a-386f-902c-6e6bf53d5766
* Content: [View device details with Microsoft Intune](https://docs.microsoft.com/en-gb/mem/intune/remote-actions/device-inventory#hardware-device-details)
* Content Source: [memdocs/intune/remote-actions/device-inventory.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/remote-actions/device-inventory.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by msbemba** [comment]
@Mal-G  Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2507

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Mal-G Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
