### ISSUE TITLE
Timeframe clarification

### ISSUE THREAD

**Issue by ssmiller60** [MicrosoftDocs/memdocs#1845]
https://docs.microsoft.com/en-us/mem/intune/configuration/device-profile-troubleshoot#what-happens-when-a-profile-is-deleted-or-no-longer-applicable

In this section it is mentioned there is a timeframe of 7 hrs + "platform-specific policy refresh cycle".  The  platform-specific policy refresh cycle (or physical device sync) is explained but the 7 hrs is not explained.

For troubleshooting purposes, the 7 hrs must be clarified as the time it takes for the profile to be removed from assignment to the Intune object in the Intune portal/database.

Also for troubleshooting purposes, it should be better clarified that it is a 2 step process:
1. Removal of the profile from the Intune object in the portal/database
2. Sync of the physical device with its Intune object

Furthermore for troubleshooting purposes, it should additionally clarified that each part of the process above has its individual timeframe expectations instead of lumping them together into one total timeframe
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14c045c9-2ccb-e24b-9eaa-bfd65b64a48c
* Version Independent ID: 355e928b-5ad8-ac1d-24d4-1d2e8f11cb4d
* Content: [Troubleshoot device profiles in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/configuration/device-profile-troubleshoot#what-happens-when-a-profile-is-deleted-or-no-longer-applicable)
* Content Source: [memdocs/intune/configuration/device-profile-troubleshoot.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/device-profile-troubleshoot.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by msbemba** [comment]
@ssmiller60 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2525

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ssmiller60 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
