### ISSUE TITLE
trademark missing

### ISSUE THREAD

**Issue by rjwinchester** [MicrosoftDocs/memdocs#1846]
[Enter feedback here]
"Symantec" should have a proper trademark 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 979d9182-7aa8-9a97-399b-2a495164f1a7
* Version Independent ID: b293cc1c-53ce-d06f-c991-a0f1a27214fc
* Content: [Windows 10 compliance settings in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/compliance-policy-create-windows#configuration-manager-compliance)
* Content Source: [memdocs/intune/protect/compliance-policy-create-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/compliance-policy-create-windows.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by rjwinchester** [comment]
well no body is perfect... I mistyped trademark... :)

**Comment by Brenduns** [comment]
@rjwinchester   Thanks for this feeback.  As the docs reflect our product UI in this area, i've passed this on to our product team so they can look into updating that reference here and in other locations.  Similarly, the Microsoft Defender refernce in those same UI text strings isn't accurate as well, being that would be Microsoft Defender Antrivirus, with Microsoft Defender not being a correct product reference.
