### ISSUE TITLE
"It's only supported with a standalone primary site" on 2107?

### ISSUE THREAD

**Issue by hillihappo** [MicrosoftDocs/memdocs#1849]
Is "It's only supported with a standalone primary site" only a limitation on 2010 and 2103? Does it work via a CAS on 2107?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07d4e4f7-68ed-e604-b577-2c18617d1c2e
* Version Independent ID: 1ce10bc0-2a6d-405a-a9ae-46adfaac8fe6
* Content: [Plan for CMG - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/plan-cloud-management-gateway)
* Content Source: [memdocs/configmgr/core/clients/manage/cmg/plan-cloud-management-gateway.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/cmg/plan-cloud-management-gateway.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @hillihappo - that's correct. You'll see that limitation (among others) is only listed for 2010/2103, and not for 2107. Support for virtual machine scale set deployments is out of pre-release in 2107. Other than the couple of remaining limitations, we recommend customers deploy CMG as a virtual machine scale set, and convert existing CMG instances to a virtual machine scale set. That includes on primary sites or CAS.
