### ISSUE TITLE
Type Powershell script line 5

### ISSUE THREAD

**Issue by FrankvL** [MicrosoftDocs/memdocs#1850]
[Enter feedback here]

The Powershell script contains a typo within line 5

Get-WindowsAutoPilotInfo.ps1 -OutputFile AutoPilotHWID.csv

Should be (without **.ps1**)

Get-WindowsAutoPilotInfo -OutputFile AutoPilotHWID.csv

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea4a659b-65d0-26ec-c36a-9a21a72a09a8
* Version Independent ID: bff44b73-9021-6659-e212-66349c759989
* Content: [Manually register devices with Windows Autopilot](https://docs.microsoft.com/en-us/mem/autopilot/add-devices)
* Content Source: [memdocs/autopilot/add-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/add-devices.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
It works either way, but it's probably cleaner to drop the extension.

C:\> Get-WindowsAutoPilotInfo.ps1

Hardware Hash
-------------
T0GZAgEAHAAAAAoAigNhSgAACgBWBGFKasSeKOQCCQUCABAACQABAAYADAABAAAABQAZAEAAAAAAAAAAYAAAAAAAAAAIAAEAAwMAEQBHZW51aW5lSW50...


C:\> Get-WindowsAutoPilotInfo

Hardware Hash
-------------
T0GZAgEAHAAAAAoAigNhSgAACgBWBGFKbcSeKOQCCQUCABAACQABAAYADAABAAAABQAZAEAAAAAAAAAAYAAAAAAAAAAIAAEAAwMAEQBHZW51aW5lSW50...

**Comment by greg-lindsay** [comment]
Pushing out this change. It will appear later today.
