### ISSUE TITLE
The description of permissions for Azure AD accounts to sign in on the Intune Connector UI has been removed

### ISSUE THREAD

**Issue by buhibu9** [MicrosoftDocs/memdocs#1855]
Please add a description

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9107185-e6c7-b178-4e22-819797fe4880
* Version Independent ID: 1153b441-94f0-b471-52a2-3cf556c68581
* Content: [Configure infrastructure to support SCEP certificate profiles with Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/certificates-scep-configure#download-install-and-configure-the-certificate-connector-for-microsoft-intune)
* Content Source: [memdocs/intune/protect/certificates-scep-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certificates-scep-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@buhibu9    This github issue was opened with a title of "Please add a decription".  From that, it's not clear what you might be asking about. I'm going to close this issue as non-actionable for now.  However, if you do have a question or ask about the documentation, you can respond back and we can then respond to or reopen this issue to address that.
