### ISSUE TITLE
Wrong connector linked

### ISSUE THREAD

**Issue by MRae86** [MicrosoftDocs/memdocs#1857]
[
Hi,

In the documentation under **Download and install the connector software** you describe how to download the file _IntuneCertificateConnector.exe_. If I try to download the file in the Microsoft Endpoint Manager admin center like explained I get the file _PfxCertificateConnectorBootstrapper.exe_ which is the wrong connector.

If I remember right, a few weeks ago there was a special connector for SCEP (_NDESConnectorSetup.exe_) and for PKCS#12/PFX (_PfxCertificateConnectorBootstrapper.exe_).

Is it possible that the wrong connector is linked? How can I get the new connector _IntuneCertificateConnector.exe_ which is mentioned in the doc.

Thank you for your feedback.
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 497646f6-1498-0647-cc54-b8013d71dca6
* Version Independent ID: e1fa4f5d-35b1-6fad-a4d2-3e8f5952230c
* Content: [Install the Certificate Connector for Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/certificate-connector-install#configure-the-certificate-connector)
* Content Source: [memdocs/intune/protect/certificate-connector-install.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certificate-connector-install.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@MRae86      I've just signed into my own public tenant to check the link and download, and this morning it's working as expected, meaning that the correct file (IntuneCertificateConnector.exe) is what downlaoded for me. The file you're referencing is the old connector install file, which should no longer be available for download and isn't the current destination of the download link.  Please check that again to see if the issue persists, or if it has corrected itself. It's possible that the fwlink was redirectred, but it seems valid now.

While I can't provide trouleshooting via this doc feedback venu, I do have the following things to check:

* In the console, right-click on the connector download link and select *Copy link*.  Then, paste the copy into Word or something similar. You should see the folloiwng FWLink:   **https://go.microsoft.com/fwlink/?linkid=2168535**    
* That FWLink points to the new connector download file.

If you don't see that FWlink ID, and/or  if your use of that link (which you can paste into another web browser to access the download) doens't take you to the correct file, please [contact Support](https://docs.microsoft.com/mem/get-support) to have that investigated.   With the correct link showing in my own public tenant as a test, and direct use of the link from my tenants UI resulting in the correct file download, something beyond our abiilty to investigate via this docs feedback forum is going on.

**Comment by MRae86** [comment]
Hi Brent,

Thanks for your fast feedback. It seems to be an issue at least with the
"german version" of the Microsoft Endpoint Manager Admin Center. There I´m
still getting the link
https://download.microsoft.com/download/1/3/D/13DA07F1-5B9A-4A57-AD43-4E48F6150E7D/PfxCertificateConnectorBootstrapper.exe.
With the english version it works like a charm and I´m getting the correct
link https://go.microsoft.com/fwlink/?linkid=2168535.

I should have figured it out right away.

Cheers
Martin

Am Fr., 6. Aug. 2021 um 18:54 Uhr schrieb Brent Dunsire <
***@***.***>:

**Comment by Brenduns** [comment]
Thanks for that information. I'll pass that on so those who work on the service can figure out why the old link persists in that version.

-Brent
