### ISSUE TITLE
Sample XML formatting for Executable Actions

### ISSUE THREAD

**Issue by Maymne** [MicrosoftDocs/memdocs#1859]
[Enter feedback here]
The sample XML for Executable Actions is all compressed into a single line, which makes it harder to read and understand. The sample XML for the other Custom Actions such as AssemblyType Actions actually have line breaks and are much easier to read. It would be appreciated if Executable Actions also had line breaks like the other Custom Actions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36128f07-1639-5c42-6391-16860b6121f0
* Version Independent ID: a19a3bd3-f826-9b37-d302-ab1bc306ce1c
* Content: [Configuration Manager Executable Action](https://docs.microsoft.com/en-us/mem/configmgr/develop/core/servers/console/executable-action)
* Content Source: [memdocs/configmgr/develop/core/servers/console/executable-action.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/develop/core/servers/console/executable-action.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Maymne for the feedback. I just put in a PR to sort out the page breaks. It should publish later today
