### ISSUE TITLE
I have checked on my tenant but could not find any option for sync under bulk device action 

### ISSUE THREAD

**Issue by kayshw** [MicrosoftDocs/memdocs#186]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31e25900-7638-befa-571d-0e27cb07a4f5
* Version Independent ID: f07dd67e-ba85-1933-c758-6ba83083d1b4
* Content: [Use bulk device actions in Microsoft Intune device.](https://docs.microsoft.com/en-us/mem/intune/remote-actions/bulk-device-actions)
* Content Source: [memdocs/intune/remote-actions/bulk-device-actions.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/remote-actions/bulk-device-actions.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@kayshw Thanks for taking the time to share this with the Intune documentation team. I checked my test environment and I see the Sync action under **Device action** of the **Basics** page under **Bulk device action**. You might have found a bug. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a few options available to provide the fastest level of support for this:   
- Post on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.   
- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.   
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.   
I'm closing this issue as there's nothing actionable for docs at this time.
