### ISSUE TITLE
Articles tip with an error

### ISSUE THREAD

**Issue by Ricasti** [MicrosoftDocs/memdocs#1868]
[Enter feedback here]
The Tip of the article has a reference to a md file instead of the list of OS where are trusted certificates supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8028845-9342-149b-1fe8-e8bb1d5c1eb4
* Version Independent ID: b6cc3ec5-1eb4-07f4-8789-3be60ef73edd
* Content: [Create trusted certificate profiles in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/certificates-trusted-root?source=docs)
* Content Source: [memdocs/intune/protect/certificates-trusted-root.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certificates-trusted-root.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Crimsonfox89** [comment]
Opened PR https://github.com/MicrosoftDocs/memdocs/pull/1888 to fix

**Comment by Brenduns** [comment]
@Crimsonfox89  Thanks for this headsup, and more so for the PR that fixes that link.
