### ISSUE TITLE
Requirements are not clear

### ISSUE THREAD

**Issue by ahanafyMS** [MicrosoftDocs/memdocs#1869]
1- i am wondering which devices will be valid to receive such built-in apps, for example is it applicable for Android enterprise enrolled devices ? i have tried fir fully managed devices but didn't deploy .. more clarification needed here. 
as i can assign the same app but from the managed google play .

2- small correction to **step 3 In the Select app type pane, under the available Store app types, select Built-In app**., 
--- built-in apps are located under **Other**  category but **NOT** **Store App** 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7a68e9c-e8b3-2b04-147e-ac80c355e1e5
* Version Independent ID: 6ce17516-1f98-d0c4-04a9-3cc606252beb
* Content: [Add built-in apps to mobile devices using Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-add-built-in)
* Content Source: [memdocs/intune/apps/apps-add-built-in.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/apps-add-built-in.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@ahanafyMS Thank you for your feedback. How you assign apps to Android Enterprise fully managed work profile devices differs from how you assign them to standard Android devices. All apps you install for Android Enterprise fully managed work profiles come from the Managed Google Play store. You use Intune to browse for the apps you want and approve them. The app then appears in the Licensed apps node of the portal, and you can manage assignment of the app as you would any other app.

I have also made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2526 for changes in Step3

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ahanafyMS Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
