### ISSUE TITLE
Regarding MECM Client Setting: "Automatically register new Windows 10 domain joined devices with Azure Active Directory"

### ISSUE THREAD

**Issue by Navneet-Singh-Ghura** [MicrosoftDocs/memdocs#187]
This doc needs to be updated as this client setting: "Automatically register new Windows 10 domain joined devices with Azure Active Directory" is not limited to Windows 10 OS. This policy applies to newer server Operating Systems(such as Windows Server 2016 and 2019)  as well. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 537cf5a4-8072-7332-e579-35394ecda457
* Version Independent ID: 03ec8ffa-d42c-f3d6-cedb-0deedc6606ba
* Content: [Install the client with Azure AD - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/deploy/deploy-clients-cmg-azure#feedback)
* Content Source: [memdocs/configmgr/core/clients/deploy/deploy-clients-cmg-azure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/deploy/deploy-clients-cmg-azure.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Navneet-Singh-Ghura for the feedback. While technically accurate, I’m going to close this issue. Most of our Azure AD scenarios are for remote management, which I think is unlikely for a server OS. For those that do have a use case for it, I think they can figure out that the setting also applies to similar server editions.
