### ISSUE TITLE
RBAC Role required

### ISSUE THREAD

**Issue by fishingTX** [MicrosoftDocs/memdocs#1870]
It would be nice if, for all of these activities, it stated in the beginning which RABC role is required to perform the activity

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4371c64-7ea5-4a97-e106-1ecba406c1c2
* Version Independent ID: 3cb4719e-4160-f906-bae2-cda35451f5e0
* Content: [Set up device-based Conditional Access with Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/create-conditional-access-intune)
* Content Source: [memdocs/intune/protect/create-conditional-access-intune.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/create-conditional-access-intune.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by yogkumgit** [comment]
@msbemba Please check PR comment and confirm.

**Comment by msbemba** [comment]
@yogkumgit yes this was merged and I don't see issues anymore.

**Comment by msbemba** [comment]
@fishingTX Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2527

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @fishingTX Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
