### ISSUE TITLE
Not the same info in the portal and in the docs

### ISSUE THREAD

**Issue by nicoride93** [MicrosoftDocs/memdocs#1872]
Hello. 

Checking the docs, on the part that says, 
As part of the connection process, the Windows 365 service is granted the following permissions:

Reader permission on the Azure subscription.
**_Owner permission on the specified resource group._**
Network contributor permission on the virtual network.

The one on bold and curl is different from the information that appears in the portal and what is actually happening. 

![image](https://user-images.githubusercontent.com/5413171/128942739-f34fc804-d606-4e8a-8a74-c5a9a70bceed.png)

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5afb0b9e-c4d3-5c75-b3fd-c4921b718e1f
* Version Independent ID: 02ec87f8-0ce5-9705-92ae-f32ced46cfa8
* Content: [Create on-premises network connections for Windows 365](https://docs.microsoft.com/en-us/windows-365/create-on-premises-network-connection)
* Content Source: [windows-365/create-on-premises-network-connection.md](https://github.com/MicrosoftDocs/memdocs/blob/master/windows-365/create-on-premises-network-connection.md)
* Service: **cloudpc**
* Sub-service: ****
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@nicoride93 The PMs conferred and tell me that it should read: "Network contributor permission on the specified resource group." This should be updated in the docs today. Thanks!
