### ISSUE TITLE
CMG server Certificate (VMSS) Name check method is not sufficient

### ISSUE THREAD

**Issue by Divshree** [MicrosoftDocs/memdocs#1883]
[Enter feedback here]
https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/server-auth-cert#virtual-machine-scale-set

Sign in to the Azure portal.

From the Azure portal home page, select Create a resource under Azure services.

Search for Virtual machine scale set. Select Create.

Select the Subscription and Resource group that you'll use for the CMG.

In the Virtual machine scale set name field, type the prefix that you want. For example, GraniteFalls.

Select the Region that you'll use for the CMG. For example, (US) West US.

Above steps don't for finding a unique name for CMG (VMSS).  I checked for name cmg in Eastus and it passed me only  to fail in CMG creation and gave me below,

Cloudmgr.log
The vault name 'cmg' is already in use. Vault names are globaly unique so it is possible that the name is already taken. If you are sure that the vault name was not taken then it is possible that a vault with the same name was recently deleted but not purged after being placed in a recoverable state. If the vault is in a recoverable state then the vault will need to be purged before reusing the name

If we check in Key Vaults , it clearly stated that name was not unique. So above steps either need to be be appended with  Key Vault check or replaced with Key Vault check.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ade53de5-3c7a-669d-2786-41d14fb6cea8
* Version Independent ID: 036c9651-1adc-fdcb-7d67-32d212e574e5
* Content: [CMG server authentication certificate - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/server-auth-cert)
* Content Source: [memdocs/configmgr/core/clients/manage/cmg/server-auth-cert.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/cmg/server-auth-cert.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Divshree for the feedback. I'm checking with the engineering team if there's a better way

**Comment by aczechowski** [comment]
I made a change to clarify, it will publish with the 2203 release
