### ISSUE TITLE
BitLocker Enterprise Compliance Dashboard: Policy not enforced on 100% compliant system?

### ISSUE THREAD

**Issue by Ram419** [MicrosoftDocs/memdocs#1884]
What does **Policy not enforced** mean in the **BitLocker Enterprise Compliance Dashboard**? I have a system that was encrypted without issue.  It shows 100% compliant in the report but shows **Compliance Status Details** = **Policy Is Not Enforced**

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec4c8398-a7f9-abd8-e76e-b472c647958f
* Version Independent ID: c9667799-90fd-295b-18d7-f114474a1da8
* Content: [View BitLocker reports - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/protect/deploy-use/bitlocker/view-reports)
* Content Source: [memdocs/configmgr/protect/deploy-use/bitlocker/view-reports.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/protect/deploy-use/bitlocker/view-reports.md)
* Product: **configuration-manager**
* Technology: **configmgr-protect**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Ram419 for the feedback. I'm checking with the engineering team.

**Comment by aczechowski** [comment]
A comment from a support engineer:

> was caused by a device that is encrypted and has previously escrowed its key but for whatever reason cannot currently escrow its key. Because it cannot escrow its key it does not enforce policy anymore. He would have to open a case though for us to really be able to determine what is going on

I'll add a note about this to the doc, the change will publish with the 2111 release.
