### ISSUE TITLE
UserInstallStatusAggregateByApp and DeviceInstallStatusByApp Reports require the Application ID filter 

### ISSUE THREAD

**Issue by Mobazzar** [MicrosoftDocs/memdocs#1887]
[Enter feedback here]

**DeviceInstallStatusByApp** and **UserInstallStautsAggregateByApp** require a filter in the POST body to work this filter will represent the Application ID that the query will run for , if this filter is not added the POST query will return error 400 , in this doc in the UserInstallStautsAggregateByApp section you mentioned that No Filter is required. below sample of the correct POST Query:

URL: https://graph.microsoft.com/beta/deviceManagement/reports/exportJobs
Method: POST
Body:
{ 
    "reportName": "UserInstallStautsAggregateByApp", 
**filter: "(ApplicationId eq 'PasteTheAppID')"  ---> this filter is required for the query to work** 
}

**The Same applied to the other Report 'DeviceInstallStatusByApp'**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b656dcde-1a91-0f18-035e-37cf7384ff5e
* Version Independent ID: f80149f3-110e-1aff-b916-c926514afdf4
* Content: [Use Graph APIs to export Intune Reports](https://docs.microsoft.com/en-us/mem/intune/fundamentals/reports-export-graph-apis)
* Content Source: [memdocs/intune/fundamentals/reports-export-graph-apis.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/reports-export-graph-apis.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@Mobazzar Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2528

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Mobazzar Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
