### ISSUE TITLE
Incorrect Support End Date for SCCM 1810

### ISSUE THREAD

**Issue by moppu31** [MicrosoftDocs/memdocs#189]
As per the MS guidelines, a version till 18 months from its release date. Considering that, SCCM 1810 should be supported till May'20.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1bc3f2a-edf6-24e0-4f45-86dc75717572
* Version Independent ID: 2789eb96-6e74-71c0-9c57-65be3d7d802c
* Content: [Updates and servicing - Configuration Manager](https://docs.microsoft.com/en-gb/mem/configmgr/core/servers/manage/updates#feedback)
* Content Source: [memdocs/configmgr/core/servers/manage/updates.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/manage/updates.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @moppu31, we extended the support date for version 1810 to December. For more information, see [Lifecycle changes to end of support and servicing dates](https://support.microsoft.com/help/4557164/lifecycle-changes-to-end-of-support-and-servicing-dates)
