### ISSUE TITLE
Certs are exportable

### ISSUE THREAD

**Issue by jeffjcom** [MicrosoftDocs/memdocs#1890]
In section: Configure certificate templates on the CA step 6 note you mention cert will be marked not exportable once installed to device.  Unfortunately this isn't the case.  They are exportable.  I agree it would be better if they were not.

Also for device certificates there maybe another bug as it seems to generate more than just one cert and installs as System and as User.  Not huge deal, but I would think device certs should only be generated once.

Thanks,

Jeff

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41df2048-2b0e-4218-1fc4-d8a657f860cc
* Version Independent ID: e26c4390-87a3-7d5a-4e6f-529b4ccf8759
* Content: [Use private and public key certificates in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/certificates-pfx-configure)
* Content Source: [memdocs/intune/protect/certificates-pfx-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certificates-pfx-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by bjornprins** [comment]
This is a serious issue, because this worked as documented (on Windows 10). PKCS Certificates deployed by NDES/Intune were non-exportable, but as of today on Windows 11 (in my case) ARE exportable, so this is a real security issue. Can someone confirm this is (changed) by design, which means the documentation is incorrect or is this a "bug" in NDES/Intune causing the certificates to be exportable on the client.

**Comment by Bjoern-LW52** [comment]
Keys created via **SCEP / NDES** are always flagged as **not** exportable on the device
Keys created or transported via **PKCS** are always flagged as exportable on the device

This is one of the most important difference between these two implementations.

**Comment by MrPRSmith** [comment]
It may be worth adding to the existing note which currently states:

> Unlike SCEP, with PKCS the certificate private key is generated on the server where the certificate connector is installed and not on the device. The certificate template must allow the private key to be exported so that the connector can export the PFX certificate and send it to the device.
> 
> When the certificates install on the device itself, the private key is marked as not exportable.

Wording to explain that as the certificate template on which the certificate is based allows the private key to be exported the certificates MMC on Windows devices will not "_grey out_" the option to export PKCS issued certs with the private key - however this is just a UI bug and attempts to do so will fail as the private key is not exportable.

Attempts to export generates a message as follows:

> The export failed
> Key not valid for use in specified state

**Comment by Donovand4** [comment]
Hi All, 
My customer has the same issue with Windows Version 21h2 (Build 19044.1566). Certs key show as exportable but when trying to export it errors.

**Comment by msbemba** [comment]
@jeffjcom @MrPRSmith Thank you for your feedback. I was able to test and the export failed. This is indeed a UI bug and can be reported via our feedback portal - https://feedbackportal.microsoft.com/

I'll report this as well to the dev team via the feedback portal.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@jeffjcom Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
