### ISSUE TITLE
Update Silent Install command

### ISSUE THREAD

**Issue by philjorgensen** [MicrosoftDocs/memdocs#1891]
The silent install command should be updated due to incorrect quote placement, which results in an invalid argument in the ConfigMgrAdminUISetup log.

It should be:

ConsoleSetup.exe /q "TargetDir=%ProgramFiles%\ConfigMgr Console" DefaultSiteServerName=MyServer.Contoso.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4afc0177-a70c-a3e7-b6fb-63284b157020
* Version Independent ID: e255af71-58f9-1086-73aa-736b22c4b8f0
* Content: [Install console - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/install/install-consoles#install-from-a-command-prompt)
* Content Source: [memdocs/configmgr/core/servers/deploy/install/install-consoles.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/deploy/install/install-consoles.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @philjorgensen for the feedback. I'll update that now.
