### ISSUE TITLE
Incorrect link title

### ISSUE THREAD

**Issue by MikeSchorr** [MicrosoftDocs/memdocs#1892]
[Enter feedback here]
The link at the bottom of the page for Troubleshooting WiFi Profiles, only states "Troubles Wifi Profiles".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0af6ee08-7a61-ea54-566b-275570dd7808
* Version Independent ID: 3c055149-944f-1ec9-0416-2dbefed5dff8
* Content: [Create a Wi-Fi profile for devices in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/configuration/wi-fi-settings-configure)
* Content Source: [memdocs/intune/configuration/wi-fi-settings-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/wi-fi-settings-configure.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by Crimsonfox89** [comment]
Opened PR https://github.com/MicrosoftDocs/memdocs/pull/1898 to fix

**Comment by MandiOhlinger** [comment]
Closing this GitHub issue. Typo fixed in https://github.com/MicrosoftDocs/memdocs/pull/1898.
