### ISSUE TITLE
Conflicts

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/memdocs#1894]
This page says "If a configuration policy setting conflicts with a setting in another configuration policy, this conflict is shown in Intune. Manually resolve these conflicts."

Another page, https://docs.microsoft.com/en-us/troubleshoot/mem/intune/troubleshoot-policies-in-microsoft-intune, says "When two policies with different levels of restriction apply to the same device or user, the more restrictive policy applies."

Are these both true? If so, why does this page not say how the conflict is resolved?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14c045c9-2ccb-e24b-9eaa-bfd65b64a48c
* Version Independent ID: 355e928b-5ad8-ac1d-24d4-1d2e8f11cb4d
* Content: [Troubleshoot device profiles in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/configuration/device-profile-troubleshoot#if-multiple-policies-are-deployed-to-the-same-user-or-device-how-do-i-know-which-settings-are-applied)
* Content Source: [memdocs/intune/configuration/device-profile-troubleshoot.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/device-profile-troubleshoot.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@Air-Git Good point. That note is how conflicting compliance policies are handled, not device configuration profiles. I created a PR to have that note removed.
