### ISSUE TITLE
When you create an OS image, you need a description to remove the recovery partition

### ISSUE THREAD

**Issue by micachi** [MicrosoftDocs/memdocs#1895]
When you create an OS image, you need a description to remove the recovery partition.
It seems that you need to delete the "recovery partition" that exists at the end of the partition as well as having a 64 GB OS disk. If you don't do this, it won't automatically resize to your SKU, but I couldn't find any mention of that. I asked the Windows 365 support desk and learned it for the first time, so the explanation is clearly lacking.

Japanese:
OS イメージを作成するときに、回復パーティションを削除することの説明が必要です。
64 GB の OS ディスクを持つだけではなく、パーティションの末尾に存在する「回復パーティション」の削除を行う必要があるようです。この手順を行わない場合、SKU に応じたサイズに自動調整されることはありませんが、そのことに関する記述が見当たりませんでした。Windows 365 のサポート窓口に質問して、初めて知ったため、説明が明らかに不足しています。

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 159c035d-d9d2-1a88-33a3-f4d2864fd2db
* Version Independent ID: 9d27c2cb-cb0a-2b99-a09d-ab8acd04bda8
* Content: [Device images in Windows 365](https://docs.microsoft.com/en-us/windows-365/device-images)
* Content Source: [windows-365/device-images.md](https://github.com/MicrosoftDocs/memdocs/blob/master/windows-365/device-images.md)
* Service: **cloudpc**
* Sub-service: ****
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by micachi** [comment]
The following steps are required.

1. Mount the system image VHD using a working Windows PC environment.
2. Start a command prompt with administrator privileges and execute the following command.
`diskpart`
3.  Check the VHD disk number.
`list disk`
4. Select VHD disk number.
`select disk <disk number>`
5. Check the recovery partition number.
`list partition`
6. Select recovery partition number.
`select partition <partition number>`
7. Delete recovery partition.
`delete partition override`
8. Exit diskpart.
`exit`
9. Launch PowerShell.
`powershell`
10. Get the maximum size of the OS drive.
`$SizeMax = (Get-PartitionSupportedSize -DriveLetter <Mounted OS drive letter>).SizeMax`
11. Expand OS drive to maximum size.
`Resize-Partition -DriveLetter <Mounted OS drive letter> -Size $SizeMax`
12. Unmount the VHD and use this VHD to provision to Windows 365.

**Comment by ErikjeMS** [comment]
Investigating with PM...
36084489
