### ISSUE TITLE
Domain Joined laptops and Company Portal?

### ISSUE THREAD

**Issue by KayceeSue05** [MicrosoftDocs/memdocs#1899]
This document doesn't include information about domain joined devices. I assume domain joined computers are by default 'blessed' and I should not be getting this error from my edge browser on my company laptop. But it would be awesome to know that for sure or not from this article

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dfb6a39-013e-7ca3-8133-9617458ed9f2
* Version Independent ID: 35e0cece-eb65-53a8-0aed-3648ccae0e07
* Content: [What is device enrollment](https://docs.microsoft.com/en-us/mem/intune/user-help/use-managed-devices-to-get-work-done)
* Content Source: [memdocs/intune/user-help/use-managed-devices-to-get-work-done.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/user-help/use-managed-devices-to-get-work-done.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@KayceeSue05 Thank you for your feedback. The configuration below needs to be set for domain-joined devices to get auto-enrolled. This is covered in a different article -https://docs.microsoft.com/en-us/microsoft-365/admin/setup/manage-windows-devices?view=o365-worldwide

In the Microsoft Endpoint Manager admin center, go to Devices > Windows > Windows Enrollment > Automatic Enrollment.

Verify MDM user scope is enabled.

To enroll all computers, set to All to automatically enroll all user computers that are joined to Azure AD and new computers when the users add a work account to Windows.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @KayceeSue05 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
