### ISSUE TITLE
How to get a partner app listed on this page

### ISSUE THREAD

**Issue by marksalamon** [MicrosoftDocs/memdocs#19]
My company is interested in having our app listed on this page.  What is the process for doing that?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf5828d-2528-a52c-6526-f860f81fbf6c
* Version Independent ID: acbd3994-1978-6f7c-9e98-90c769ae5643
* Content: [Add iOS store apps to Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/store-apps-ios#feedback)
* Content Source: [memdocs/intune/apps/store-apps-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/store-apps-ios.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@marksalamon - Do you want to have your app included on this page and available through the App app store?
[Microsoft Intune protected apps](https://docs.microsoft.com/mem/intune/apps/apps-supported-intune-apps)

If so, here's the information you need. Please see the following topic:
https://docs.microsoft.com/mem/intune/developer/app-sdk-get-started#register-your-store-app-with-microsoft

I hope this helps.
