### ISSUE TITLE
Add explanation for ComplianceState in sms_appdeploymentassetdetails-server-wmi-class.md

### ISSUE THREAD

**Issue by StoffePro** [MicrosoftDocs/memdocs#1903]
The file `memdocs/configmgr/develop/reference/apps/sms_appdeploymentassetdetails-server-wmi-class.md` lacks an explanation for the values of the `ComplianceState` property.

Other classes, such as `sms_ci_currentcompliancestatus-server-wmi-class.md` exposes a second property, `ComplianceStateName`, which seems to always be:

Value|Compliance state
-|-
0|Compliance State Unknown
1|Compliant
2|Non-Compliant
4|Error

so I'd assume it's the same in this case, but this should be verified with someone who has access to the actual source code.

(admin edit: add article metadata for proper linking)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93173219-d3a7-a318-6033-71fca60fe734
* Version Independent ID: b3a5e2f1-3266-cbb3-79f0-05a0e862a7b0
* Content: [SMS_AppDeploymentAssetDetails Class - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/develop/reference/apps/sms_appdeploymentassetdetails-server-wmi-class)
* Content Source: [memdocs/configmgr/develop/reference/apps/sms_appdeploymentassetdetails-server-wmi-class.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/develop/reference/apps/sms_appdeploymentassetdetails-server-wmi-class.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @StoffePro, I looked at one internal reference that I have and couldn't find more information on this value.
The ConfigMgr SDK content is an area in which we're not actively investing beyond basic maintenance and some new functionality. In general, I recommend using [WMI Explorer](https://github.com/vinaypamnani/wmie2) to help understand current classes, properties, and methods. But I don't think that will unveil much more on this specific property.
I think it'll need someone from the engineering team to investigate and provide the details. You could try to "file a frown" in the console, but I can't guarantee that will get a response.
