### ISSUE TITLE
NuGet need TLS12

### ISSUE THREAD

**Issue by capekvl** [MicrosoftDocs/memdocs#1907]
[Enter feedback here]

Hello from Prague, 
the script at the article does not download NUGET without this:

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

Bye
Vladimir

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea4a659b-65d0-26ec-c36a-9a21a72a09a8
* Version Independent ID: bff44b73-9021-6659-e212-66349c759989
* Content: [Manually register devices with Windows Autopilot](https://docs.microsoft.com/en-us/mem/autopilot/add-devices#collecting-the-hardware-hash-from-existing-devices-using-powershell)
* Content Source: [memdocs/autopilot/add-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/add-devices.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by frankroj** [comment]
Thank you for the feedback @capekvl. I apologize for the time it took to get back to you regarding this feedback item. We've gone ahead and added the suggested line to the scripts. Thanks again for bringing this to our attention.
