### ISSUE TITLE
Monitoring for incoming and outgoing files

### ISSUE THREAD

**Issue by markaldridge** [MicrosoftDocs/memdocs#191]
It appears you're missing information about 
Monitoring for incoming and outgoing files
which is listed under the Real-time protection profile section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b84f6130-b993-bd26-0147-29748c3b7449
* Version Independent ID: 231c5984-ee21-059b-22d4-21b2f009124e
* Content: [Windows 10 Antivirus policy settings for Microsoft Defender Antivirus for Intune](https://docs.microsoft.com/en-us/mem/intune/protect/antivirus-microsoft-defender-settings-windows#feedback)
* Content Source: [memdocs/intune/protect/antivirus-microsoft-defender-settings-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/antivirus-microsoft-defender-settings-windows.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@markaldridge   Thanks for spotting that. I've added that missing setting to the article and that update should be live later today.
