### ISSUE TITLE
Storage Account Name can only use lowercase letters

### ISSUE THREAD

**Issue by rasldasl** [MicrosoftDocs/memdocs#1910]
In example provided...and in testing for my storage account name...validation fails when using uppercase letters. 

Storage account name

GraniteFalls
Error shown: The field can contain only lowercase letters and numbers. Name must be between 3 and 24 characters.

granitefalls
(no validation error)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ade53de5-3c7a-669d-2786-41d14fb6cea8
* Version Independent ID: 036c9651-1adc-fdcb-7d67-32d212e574e5
* Content: [CMG server authentication certificate - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/server-auth-cert)
* Content Source: [memdocs/configmgr/core/clients/manage/cmg/server-auth-cert.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/cmg/server-auth-cert.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @rasldasl for the feedback! Confirmed via the article on [Azure storage accounts](https://docs.microsoft.com/en-us/azure/storage/common/storage-account-overview#storage-account-endpoints). I'll fix this shortly.
