### ISSUE TITLE
How to find referred certificate

### ISSUE THREAD

**Issue by joaonltome** [MicrosoftDocs/memdocs#1917]
In the Automatically delete devices with cleanup rules section of this documented it is referred that "If a removed device checks in before its device certification expires, it will reappear in the console."

What specific certificate is being mentioned here? How can it be found in the local device? Is it possible also to check the certificate validity in Azure?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cdcc7fd-5bd9-1645-abf4-a73d3ea7adaa
* Version Independent ID: 5022b2ba-5fb0-18ce-9079-1b65ad0b2e17
* Content: [Retire or wipe devices using Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/remote-actions/devices-wipe#delete-devices-from-the-intune-portal)
* Content Source: [memdocs/intune/remote-actions/devices-wipe.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/remote-actions/devices-wipe.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by msbemba** [comment]
@joaonltome Thank you for your feedback.  The certificates referred are SCEP and PKCS certificates.In Microsoft Intune, you can use Simple Certificate Enrollment Protocol (SCEP) and Public Key Cryptography Standards (PKCS) certificate profiles to add certificates to devices. These are removed when you wipe or retire a device.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @joaonltome Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
