### ISSUE TITLE
Suggestion for CMG setup docs

### ISSUE THREAD

**Issue by motorhead018** [MicrosoftDocs/memdocs#1918]
Could you add sub topic bullet points or clickables to subsections in the following screenshot:

![image](https://user-images.githubusercontent.com/38567415/130293662-229ca8bd-503c-4bf4-9a67-e382c2726a62.png)

It would make it easier to figure out what resource providers are required, amongst other settings as well.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73637c76-0466-8a0f-f614-c5ef3607d4a4
* Version Independent ID: 15fd3771-a7f3-f233-51bd-0be30cd0a020
* Content: [Configure Azure AD for CMG - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/configure-azure-ad#create-the-native-client-app-registration)
* Content Source: [memdocs/configmgr/core/clients/manage/cmg/configure-azure-ad.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/cmg/configure-azure-ad.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @motorhead018, thanks for the feedback, but unfortunately the docs platform doesn't support that sort of subcategorization in the table of contents. The "solution" to your proposal would be to break out those sections as separate articles. But I'm reluctant to do that for a number of reasons.
