### ISSUE TITLE
License required to see Endpoint Devices Provisioning Windows 365

### ISSUE THREAD

**Issue by sveinungre** [MicrosoftDocs/memdocs#1919]
I suggest to specify in the documentation that you need a license to actually prepare and see anything under https://endpoint.microsoft.com/ -> Devices -> Windows 365. Meaning you cannot configure and play around with the settings until you have purchased your first license, probably enterprise license.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39ef0807-f356-7144-e8ce-c5231e310a7a
* Version Independent ID: 65d069cf-3d9e-0ef7-6c2d-d371f88544c7
* Content: [Windows 365 deployment overview](https://docs.microsoft.com/en-us/windows-365/deployment-overview)
* Content Source: [windows-365/deployment-overview.md](https://github.com/MicrosoftDocs/memdocs/blob/master/windows-365/deployment-overview.md)
* Service: **cloudpc**
* Sub-service: ****
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM
37831488

**Comment by ErikjeMS** [comment]
The following note was added: After your organization has purchased one or more Windows 365 licenses, the Windows 365 node in Microsoft Endpoint Manager will become active for management. At this point, you can provision Cloud PCs.
