### ISSUE TITLE
Add link to Intune RBAC Table

### ISSUE THREAD

**Issue by p0shkar** [MicrosoftDocs/memdocs#192]
I've been looking for a more thorough description of each custom permission when creating custom roles, but havn't found it. The closest I got was a outdated blog which was still kind of general in the descriptions. Now I noticed in the second video you have linked in the ingress of this page that there is such a document, namely "Intune RBAC Table". And honestly, this document is a gold mine. Please add it as a link directly in this article.

https://gallery.technet.microsoft.com/Intune-RBAC-table-2e3c9a1a

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3eaa886-918b-127e-ad4b-d829e99b0d44
* Version Independent ID: 87240468-dd25-7f45-740b-f078cd5deac7
* Content: [Role-based access control (RBAC) with Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/role-based-access-control)
* Content Source: [memdocs/intune/fundamentals/role-based-access-control.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/role-based-access-control.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@p0shkar The Intune RBAC table was out of date and removed. The product team is considering alternate ways to provide this information. A good way for you to provide your feedback is to use the  the [Microsoft Intune Feedback]( https://microsoftintune.uservoice.com/forums/291681-ideas) page. That way, the product team will get your request for the RBAC table directly.  I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by p0shkar** [comment]
User Voice created.
https://microsoftintune.uservoice.com/forums/291681-ideas/suggestions/40354303-add-intune-rbac-table-or-similar-to-docs

**Comment by hkystar35** [comment]
For those still looking, Internet Archive has a copy of the docx

[Intune-RBAC-table](https://web.archive.org/web/20200318161338/https://gallery.technet.microsoft.com/Intune-RBAC-table-2e3c9a1a/file/215780/1/Intune%20RBAC%20Table.docx)
