### ISSUE TITLE
Client upgrade is triggered by clientservicing since 1906, instead of execmgr

### ISSUE THREAD

**Issue by IvyMS1990** [MicrosoftDocs/memdocs#1920]
[Enter feedback here]

I tested in 2107, client upgrade is triggered by clientservicing, not execmgr. The note in this page is out of date. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4614fdad-6894-1768-3b54-3349951ad0ab
* Version Independent ID: f6eb50a9-fca3-1734-14eb-ead1ef7e1a9f
* Content: [Upgrade clients on Windows - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/upgrade/upgrade-clients-for-windows-computers)
* Content Source: [memdocs/configmgr/core/clients/manage/upgrade/upgrade-clients-for-windows-computers.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/upgrade/upgrade-clients-for-windows-computers.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @IvyMS1990 for the feedback, I'll update it.
