### ISSUE TITLE
Password change issue for Network/Mobile AD account

### ISSUE THREAD

**Issue by dbello123** [MicrosoftDocs/memdocs#1921]
The password policy requires a change at next auth after enrolling or upgrading a device to big sur. During login,  password change for network/mobile AD accounts tend to fail due to loss of connectivity to the active directory esp. if VPN is required or company policy doesn't allow that. This blocks users from logging in to their device until they are excluded from the password policy. 
Can this policy be applied to only local accounts or can we include a note to users warning them of this scenarios.
Identify users on network or mobile account, ask the to migrate to local first before enrolling or upgrading to bigsur
Thanks

**Comment by ErikjeMS** [comment]
@dbello123 Which article does issue apply to?

**Comment by MandiOhlinger** [comment]
@dbello123 In [macOS device restrictions settings> Password](https://docs.microsoft.com/mem/intune/configuration/device-restrictions-macos#password), we document this behavior in the **Important** info at the top. Also, we're working with the compliance team on this behavior. Currently, no ETA.

In an [upcoming release](https://docs.microsoft.com/mem/intune/fundamentals/in-development#new-macos-settings-in-settings-catalog-), the **Change At Next Auth** setting in the settings catalog will be available for you to configure and deploy. This setting uses the [Passcode payload > changeAtNextAuth property](https://developer.apple.com/documentation/devicemanagement/passcode) (opens Apple's web site). This setting may help with the behavior you're seeing:

- If you have a password compliance policy and the **Change At Next Auth** setting configured in a device configuration profile, then you might still see this behavior.
- If you don't have a password compliance policy and only have the **Change At Next Auth** setting configured in a device configuration profile, then you might not see this behavior.

In the meantime, if you've got a good work-around, and don't mind sharing, it'd be great if you created a pull request with what you're doing. It could help others. 

If you want to know what others might be doing, the [Microsoft Q&A](https://docs.microsoft.com/answers/topics/intune-general.html) might be a good resource.
