### ISSUE TITLE
Adjust information regarding the first section regarding skipping Outbound Proxy (autopilot-hybrid-connector-proxy)

### ISSUE THREAD

**Issue by 0fflineDocs** [MicrosoftDocs/memdocs#1923]
"add the proxy address and proxy port in the section shown in this code sample:"
Where? This is not clear today. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1546e07f-4168-140d-508e-bf7fcb3661bb
* Version Independent ID: e1deb787-f2b9-b024-e921-68f6b0d5d4cb
* Content: [Configure proxy settings for the Intune Connector for Active Directory](https://docs.microsoft.com/en-us/mem/intune/enrollment/autopilot-hybrid-connector-proxy)
* Content Source: [memdocs/intune/enrollment/autopilot-hybrid-connector-proxy.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/autopilot-hybrid-connector-proxy.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @master11218
* Microsoft Alias: **erikje**

**Comment by lenewsad** [comment]
Hi @0fflineDocs, thanks for reaching out to the Microsoft Intune Docs team with your question. Completely agree that it's not clear what's going on in this code sample. I'll get clarification and let you know when it's updated.

**Comment by lenewsad** [comment]
Hi @0fflineDocs, I haven't been able to get clarification on the code sample. But I opened a doc bug with the product team and I'll keep trying to get a clearer code sample for this article.

**Comment by lenewsad** [comment]
Hi @0fflineDocs, we updated the code sample in this doc. The doc update clarifies what needs to be edited to disable the proxy connector:

"To disable outbound proxy usage for the connector, edit the ``:\Program Files\Microsoft Intune\ODJConnector\ODJConnectorUI\ODJConnectorUI.exe.config`` file and set the default proxy to ` "False" `..." 

That line now aligns with the example shown in the code sample. You'll be able to see the changes by end-of-day today. Thanks again for your question!
