### ISSUE TITLE
Informations about client installation in Windows Server

### ISSUE THREAD

**Issue by ingd** [MicrosoftDocs/memdocs#1924]
Hey guys. How are you?

I am trying to find any information about managing Windows Server in MECM, but this FAQ page cannot clarify my doubts if I have rights (considering that I have an M365 E5 license) to install and use in this line of Microsoft products.

Someone please could give their considerations?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f3023a8-ab6c-1d77-0111-77cc7583347c
* Version Independent ID: 26debf60-c3c1-caa6-7f78-a04a8b8e73af
* Content: [Product and licensing FAQ - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/understand/product-and-licensing-faq)
* Content Source: [memdocs/configmgr/core/understand/product-and-licensing-faq.yml](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/understand/product-and-licensing-faq.yml)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @ingd I think this question is better asked of your account executive and/or whoever manages your licensing. I think there is a "licensing desk" that they should be able to contact to help answer customer questions like yours.
