### ISSUE TITLE
Filters not working in ESP

### ISSUE THREAD

**Issue by E-Abiri** [MicrosoftDocs/memdocs#1925]
Hello, 

Today i'm testing with the Filter options inside Intune.

Filters are very handy! But they are not working in ESP assignments.

Am I the only one?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e458d85e-5eda-1421-a8eb-5775da1e8725
* Version Independent ID: 10a95675-5f3d-245b-c1f4-57f6faa97300
* Content: [Create filters in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/filters)
* Content Source: [memdocs/intune/fundamentals/filters.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/filters.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@E-Abiri You are correct. Filters don't work on the Enrollment Status Page (ESP). They will work in a future release; No ETA. We suggest monitoring [In development](https://docs.microsoft.com/mem/intune/fundamentals/in-development) and [What's new](https://docs.microsoft.com/mem/intune/fundamentals/whats-new) for product updates.
