### ISSUE TITLE
Update Modify CMG document for new certificate

### ISSUE THREAD

**Issue by usurper117** [MicrosoftDocs/memdocs#1927]
Update Modify CMG document.

Currently, there is no information for customers who are getting a new certificate for their existing CMG with a property change to the new certificate, such as Organization name changes.
This requires the customer to build a new CMG with the new certificate (with a property change to the cert) > migrate clients to this new CMG then decommission the prior CMG. If they try to add the new certificate, with property change, there is a high probability the CMG will reject the certificate and cause the clients to become no longer managed. Thanks!
https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/modify-cloud-management-gateway

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12ab4165-870a-9fea-872a-35c03d2ba338
* Version Independent ID: b9015594-b05d-05dd-ef03-a99c3a4be225
* Content: [Modify a CMG - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/modify-cloud-management-gateway)
* Content Source: [memdocs/configmgr/core/clients/manage/cmg/modify-cloud-management-gateway.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/cmg/modify-cloud-management-gateway.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @usurper117 for the feedback. That's a good callout that broader changes to the certificate will necessitate redeploying the service.

**Comment by usurper117** [comment]
Glad to help got the confirmation from Bea. I work as an MEMCM SE this came up with a customer.  Will.
