### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by mattsmacblog** [MicrosoftDocs/memdocs#1930]
This whole process seems overly complex and surely can be automated into the product or streamlined in 2021... Especially with the Business / Education Stores days now numbered....  Could we not just link the actual Company Portal Store App to Intune and have it installed that way vs this whole download the appx and dependencies process...

This whole thing should really just be a tick box in the Settings somewhere for "on device enrolment install the company portal app"  Y / N.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43ae0d4a-eefd-7770-b2a4-d4f72f7272a3
* Version Independent ID: 1001276c-ddd3-14bd-cd5e-74ce47490d19
* Content: [Manually add the Windows 10 Company Portal app - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/store-apps-company-portal-app)
* Content Source: [memdocs/intune/apps/store-apps-company-portal-app.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/store-apps-company-portal-app.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by yogkumgit** [comment]
@mattsmacblog Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
