### ISSUE TITLE
Confusing/incorrect info

### ISSUE THREAD

**Issue by ssmiller60** [MicrosoftDocs/memdocs#1931]
https://docs.microsoft.com/en-us/mem/intune/apps/mam-faq#is-it-possible-to-have-both-mdm-and-mam-policies-applied-to-the-same-user-at-the-same-time--for-different-devices--for-example--if-a-user-could-be-able-to-access-their-work-resources-from-their-own-mam-enabled-machine--but-also-come-to-work-and-use-an-intune-mdm-managed-device--are-there-any-caveats-to-this-idea

This: "So when you create an app protection policy, next to Target to all app types, you'd select No. Then do any of the following:"

Should say this instead: "So when you create an app protection policy, next to **Target to apps on all device types**, you'd select No. Then do any of the following:"

In the current state it is referencing app types, when it should reference device types (managed or unmanaged).

Thanks!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3929b5a0-f852-ce35-4ecd-72d5b9b4a948
* Version Independent ID: 33b804a6-5bf9-75e6-13e0-f2a35e07ef8f
* Content: [Frequently asked questions about MAM and app protection](https://docs.microsoft.com/en-us/mem/intune/apps/mam-faq)
* Content Source: [memdocs/intune/apps/mam-faq.yml](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/mam-faq.yml)
* Service: **microsoft-intune**
* Sub-service: **apps**
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@ssmiller60 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2508

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ssmiller60 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
