### ISSUE TITLE
Docs error - ":Password sync - Kerberos only" section under SSO 

### ISSUE THREAD

**Issue by hilde-msft** [MicrosoftDocs/memdocs#1937]
Our docs here state this is for sync of local password to Azure AD but the Apple docs state this is for Active Directory (and specifically NOT AAD).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b4d6112-d991-a27a-6515-e3c48d600d09
* Version Independent ID: 42f0eba4-d096-9447-446d-9580fc340210
* Content: [macOS device feature settings in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/configuration/macos-device-features-settings)
* Content Source: [memdocs/intune/configuration/macos-device-features-settings.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/macos-device-features-settings.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@hilde-msft You are correct. Thank you. The description is updated, and changes should be live later today.

**Comment by MandiOhlinger** [comment]
https://msazure.visualstudio.com/Intune/_workitems/edit/10732176
