### ISSUE TITLE
Subscription requirements misleading

### ISSUE THREAD

**Issue by yjhgdipgfj** [MicrosoftDocs/memdocs#1939]
The subscription requirements on this page is misleading, customers may wondering the Azure subscription is included in the EMS subscriptions they have. 
![image](https://user-images.githubusercontent.com/50049070/131274548-29e0b1fe-2c53-468d-ae43-82ee0d7118be.png)

What we may update is perhaps as following:

An active global Azure subscription.

An active global Azure Active Directory. 

 Note

Most of the equivalent subscriptions for Configuration Manager also include Azure AD. For example, see Microsoft 365 plans and Enterprise Mobility + Security licensing.

At least one Intune license for you as the administrator to access the Intune portal.

Devices enrolled in Desktop Analytics need a valid Configuration Manager license. For more information, see Configuration Manager licensing.

Users of the device need one of the following licenses:

Windows 10 Enterprise E3 or E5 (included in Microsoft 365 F3, E3, or E5)

Windows 10 Education A3 or A5 (included in Microsoft 365 A3 or A5)

Windows 10 Virtual Desktop Access (VDA) per user

 Note

Beyond the cost of these license subscriptions, there's no additional cost for using Desktop Analytics within Azure Log Analytics. The data types ingested by Desktop Analytics are free from any Log Analytics data ingestion and retention charges. As non-billable data types, this data is also not subject to any Log Analytics daily data ingestion cap. For more information, see Log Analytics usage and costs.

If you use another Azure solution that uses the same Log Analytics workspace, you may be charged for devices. For example, Azure Security Center. To make sure you're not billed for Desktop Analytics devices, use a separate Log Analytics workspace for these other billed solutions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae3a0675-959f-840c-bc51-199cee1d71d5
* Version Independent ID: eb5ed4c2-332f-5816-5d1f-7f2958b8e410
* Content: [Desktop Analytics - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/desktop-analytics/overview)
* Content Source: [memdocs/configmgr/desktop-analytics/overview.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/desktop-analytics/overview.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @yjhgdipgfj for the feedback. I'll revise to clarify.
