### ISSUE TITLE
Example command with all parameters doesn't include 'noCRLCheck'

### ISSUE THREAD

**Issue by NeighborGeek** [MicrosoftDocs/memdocs#1942]
The example command which says it includes all of the parameters is missing one, the '/noCRLCheck' parameter.  As that parameter is the only one listed which uses a slash, it seems it may require slightly different syntax from the others, so including it in the example would be very useful.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 875e279b-9029-d1e5-8a6c-0e93ce38ddba
* Version Independent ID: 80bc34d7-3ef7-1c4f-da41-0474b1c5f4a4
* Content: [Co-manage internet-based devices - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/comanage/how-to-prepare-Win10)
* Content Source: [memdocs/configmgr/comanage/how-to-prepare-Win10.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/comanage/how-to-prepare-Win10.md)
* Product: **configuration-manager**
* Technology: **configmgr-comanage**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @NeighborGeek, thanks for the feedback. Fair point, however I'll counter that it's best to publish the CRL and not use that parameter. We usually strive to be secure-by-default with the examples we provide, so I'm somewhat inclined to _not_ include that parameter in the example. If anything, maybe just provide a reference to the [explanation of the parameter](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/deploy/about-client-installation-properties#nocrlcheck). We'll chat about it... 😉
