### ISSUE TITLE
Clarity on folder permissions required for passive site server

### ISSUE THREAD

**Issue by PotentEngineer** [MicrosoftDocs/memdocs#1943]
This document outlines required permissions for the content library but no other locations such as content source files. This is required for updating boot images, driver packages, servicing WIMs, and other OSD content modification.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4e5077b-89ed-62a1-8690-722a8cb49658
* Version Independent ID: 3fa4245d-27f9-5062-24aa-b5b1a9d38005
* Content: [Site server high availability - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/site-server-high-availability#prerequisites)
* Content Source: [memdocs/configmgr/core/servers/deploy/configure/site-server-high-availability.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/deploy/configure/site-server-high-availability.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @PotentEngineer for filing the feedback! 😁
