### ISSUE TITLE
Alert type: setting language usage

### ISSUE THREAD

**Issue by danbu** [MicrosoftDocs/memdocs#1944]
The language used for "Alert Type" is unclear from the Apple UI options or the Apple MDM specs

"Banner: A banner is briefly shown with the notification."
"Modal: The notification is shown and users must manually dismiss it before continuing to use the device."

The Apple Developer page for this MDM setting is as follows

1: Temporary Banner
2: Persistent Banner

The UI on the device is also "Temporary" and "Persistent"
https://developer.apple.com/documentation/devicemanagement/notifications/notificationsettingsitem

The use of "Banner" and "Modal" is confusing and not clear.  Changing the term used in the InTune UI might have some impact but the documentation should use the words "Temporary" and "Persistent" to align with Apple's MDM and UI usage.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a7b8e75-3872-6bbd-4d9b-b26d1eb11f81
* Version Independent ID: 74769948-8c98-19de-df74-2fcf1d399387
* Content: [iOS/iPadOS device feature settings in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/configuration/ios-device-features-settings)
* Content Source: [memdocs/intune/configuration/ios-device-features-settings.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/ios-device-features-settings.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@danbu Agreed. It'd be great if you created a pull request with your recommended changes. We'd love the help. We review every PR, so know that we got your back.

**Comment by danbu** [comment]
@MandiOhlinger I don't work for Microsoft, I'm your customer.  I'm telling you the documentation is wrong.  That is as far as I'm willing to go on the issue, I don't really understand pull requests in the context of documentation and I'm not writing your documentation for you.

**Comment by msbemba** [comment]
@danbu Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/issues/1944. Once the author approves, the changes will be live.

Thanks
Sri

**Comment by msbemba** [comment]
@danbu Thank you for your feedback. While I saw the Apple Developer page for this MDM setting is as follows

1: Temporary Banner
2: Persistent Banner

I have got a confirmation from the author that this cannot be changed in the document as it doesn't match our UI.

@yogkumgit  This can be closed.

Thanks
Sri

**Comment by danbu** [comment]
My whole point of this request is that the InTune UI and documentation does match what is displayed on the Apple device or in  Apple's documentation.  When trying to figure out what a setting does having consistence in the Vendors UI and documentation should at least be noted if the UI can't be updated as it is their setting and their API.

**Comment by msbemba** [comment]
@danbu  Could you please check the Intune UI now and provide us a screenshot?  As per the Apple documentation, I understand there is a difference however In this article, the setting names match the UI.

Thanks
Sri
