### ISSUE TITLE
New URLs for telemetry

### ISSUE THREAD

**Issue by rrifonasmsft** [MicrosoftDocs/memdocs#1947]
I've found recently that Windows 10 20H2 might try to access **us-v10c.events.data.microsoft.com** instead of v10c.events.data.microsoft during the cycle to upload telemetry, found this in the UTC Trace.
Is it possible to confirm if this endpoint is really required and if there are other endpoints for different regions? If they are new endpoints, it must be documented to avoid  problems with firewall, proxy and ssl inpection appliances.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55ba9622-311f-0c2c-bce3-f0510a4d2b79
* Version Independent ID: 49d1ca0a-b8b0-bfa9-c735-d45c7118ac9a
* Content: [Enable data sharing - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/desktop-analytics/enable-data-sharing)
* Content Source: [memdocs/configmgr/desktop-analytics/enable-data-sharing.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/desktop-analytics/enable-data-sharing.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @rrifonasmsft I checked with the engineering team on this. They're not aware of any changes to the collector endpoints. There's support for regional endpoints like you noted, but that's not by default.

> If you are seeing traffic to the US endpoint, that would imply that the registry has been configured on the device to use the US endpoint. This could either be done by the custom m365 prefix or VortexRegion policy.
