### ISSUE TITLE
No Remote Lock for Windows??

### ISSUE THREAD

**Issue by rbishop-etq** [MicrosoftDocs/memdocs#1948]
Why hasnt this Intune Remote Lock function been setup/activated for windows machines yet?
When will this be done?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c79f5e46-0615-682c-0368-5a14cfa738e7
* Version Independent ID: 08094776-efc7-d7b1-0b82-0aee1dac5634
* Content: [Lock devices with Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/remote-actions/device-remote-lock)
* Content Source: [memdocs/intune/remote-actions/device-remote-lock.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/remote-actions/device-remote-lock.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@rbishop-etq We can't give dates for when features will be released due possible future changes in the development schedule. However, you can check the [In Development article](https://docs.microsoft.com/en-us/mem/intune/fundamentals/in-development) to see a list of features in development.

**Comment by rbishop-etq** [comment]
@ErikjeMS the page you linked has nothing listed i can see referencing the Remote Lock function.
Can you confirm that this is currently on a development schedule to be added at SOME point? I really dont understand how the one OS owned by Microsoft is one of the few that do not support this function.

**Comment by ErikjeMS** [comment]
@rbishop-etq If it's not listed on the In Development page then the feature has not been announced. If you'd like to suggest a feature for Intune you can do so here: [https://microsoftintune.uservoice.com/forums/291681-ideas](https://microsoftintune.uservoice.com/forums/291681-ideas)

**Comment by rbishop-etq** [comment]
It was requested in there over 2 years ago, and clearly this is needed. Any ideas what the holdup is with adding this?
https://microsoftintune.uservoice.com/forums/291681-ideas/suggestions/36485080-enable-remote-lock-for-windows-10-desktop-devices

**Comment by ErikjeMS** [comment]
@rbishop-etq I can't give you any more information as I can't comment on features that haven't been officially announced.
