### ISSUE TITLE
Wipe device after failed X passcode attempts

### ISSUE THREAD

**Issue by GuyPartridge** [MicrosoftDocs/memdocs#1950]
Hi,
Does the wipe device after x failed password attempts (Intune Device Restriction Setting) still apply to devices enrolled with User Enrolment? As we do not want the personal data to be wiped in the scenario that a user enters the incorrect passcode x times (max is 11). Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c16a041-dc8e-5f4b-645d-7ea6d261878b
* Version Independent ID: 6f59dfd1-3d95-4c00-060c-0d5d36a64120
* Content: [Intune actions and options supported with Apple User Enrollment - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/ios-user-enrollment-supported-actions#feedback)
* Content Source: [memdocs/intune/enrollment/ios-user-enrollment-supported-actions.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/ios-user-enrollment-supported-actions.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@GuyPartridge Thank you for your feedback. That is correct, Intune Device Restriction Setting does not apply to user enrollments, Meaning it does not wipe personal data in case of X failed password attempts.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @GuyPartridge Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
