### ISSUE TITLE
Pre-Req Update

### ISSUE THREAD

**Issue by sympleconfigmgr** [MicrosoftDocs/memdocs#1954]
At least one Intune license for you as the administrator to access the Intune portal. - I think this requirement is no longer valid. Can we verify and remove?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2eb4acb-7311-79d3-3daa-6f27ea42aee7
* Version Independent ID: 123f2a5c-04c1-8184-05a4-689d9c591981
* Content: [Microsoft Endpoint Manager tenant attach - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/tenant-attach/device-sync-actions)
* Content Source: [memdocs/configmgr/tenant-attach/device-sync-actions.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/tenant-attach/device-sync-actions.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @sympleconfigmgr, that prereq was literally added 23 days ago at the request of the engineering team. So still valid.
