### ISSUE TITLE
Who is managing who?

### ISSUE THREAD

**Issue by kstpebe** [MicrosoftDocs/memdocs#1958]
This line feels a bit weird. Is it monitored and managed by itself?
"Microsoft Defender for Endpoint manages and monitors Microsoft Defender for Endpoint"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac1e9ae8-a9de-99f3-5335-2460fb9d69ce
* Version Independent ID: d2109d70-4f53-7033-1573-3ca6ad43e2f9
* Content: [Endpoint Protection - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/protect/deploy-use/endpoint-protection)
* Content Source: [memdocs/configmgr/protect/deploy-use/endpoint-protection.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/protect/deploy-use/endpoint-protection.md)
* Product: **configuration-manager**
* Technology: **configmgr-protect**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
😆 Thanks @kstpebe for catching that. I suspect that's the result of a bulk edit during rebranding. I'll fix it up now, should be ConfigMgr manages and monitors MDE.
