### ISSUE TITLE
AllowTelemetry Registry value for Optional (limited)

### ISSUE THREAD

**Issue by Saswatikatripathy** [MicrosoftDocs/memdocs#1959]
As per this  document, AllowTelemetry value for optional (limited) is **3**. But when configured in lab with optional (limited) telemetry level ,  I see AllowTelemetry is set to 2 **under HKLM\Software\policies\Microsoft\Windows\Datacollection**

PFA  snippet
<img width="501" alt="AllowTelemetry" src="https://user-images.githubusercontent.com/90273267/132379835-5c266fbf-f06f-4bad-b3ec-9d787f969f01.PNG">
<img width="718" alt="AllowTelemtry1" src="https://user-images.githubusercontent.com/90273267/132379859-53658830-defe-41b4-8523-546562614552.PNG">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f7dc639-d79e-84da-1ec9-66407ac237ee
* Version Independent ID: 8846b4d9-ee8d-2961-5c70-c60a3af81552
* Content: [Group policy settings - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/desktop-analytics/group-policy-settings)
* Content Source: [memdocs/configmgr/desktop-analytics/group-policy-settings.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/desktop-analytics/group-policy-settings.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @Saswatikatripathy, the values in this article match what's documented for the Windows Policy CSP, see https://docs.microsoft.com/windows/client-management/mdm/policy-csp-system#system-allowtelemetry

**Comment by Saswatikatripathy** [comment]
In windows Policy CSP doc, do not see **optional (limited)** setting  . 
we have the value for **Optional (Full)** instead

https://docs.microsoft.com/windows/client-management/mdm/policy-csp-system#system-allowtelemetry

**Comment by aczechowski** [comment]
Before I continue, I should ask: which part of this article are you referring to?

**Comment by Saswatikatripathy** [comment]
I am referring below values 


1 – Required (Basic) Sends basic device info, including quality-related data, app compatibility, and other similar data to keep the device secure and up-to-date.

2 – (Enhanced) Sends the same data as a value of 1, plus additional insights, including how Windows apps are used, how they perform, and advanced reliability data, such as limited crash dumps.

 Note

Enhanced is no longer an option for Windows Holographic, version 21H1.

3 – Optional (Full) Sends the same data as a value of 2, plus additional data necessary to identify and fix problems with devices such as enhanced error logs.
