### ISSUE TITLE
App Detection - Script Method

### ISSUE THREAD

**Issue by gwblok** [MicrosoftDocs/memdocs#196]
I believe the context in which the Detection Method script runs is different based on deployment type (User vs Machine).
In my Testing, it would appear that the Detection Script runs under USER Context when the application is deployed to a user collection, and SYSTEM context when deployed to machines.  
Due to this odd functionality, my the detection on my applications does NOT work when deployed to users.  
It comes back as "Current State = Error"  because parts of the script error (access denied) when looking up WMI entries. But the BUT.. the same script comes back as "Current State = Installed" when I deploy to Machines and run AppEval.

Either this is a bug, or if it is functioning as intended (which would really stink) and then the docs should reflect the difference in how the detection scripts run based on deployment.  
FYI.. we didn't notice at first because some users who were testing the app installs were logged into the computer with local admin accounts, which then really complicated the results.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 791c915c-953e-a9a5-c85a-ec7e06098473
* Version Independent ID: d9e0b4fd-987d-2b12-a6be-3f2651ef214f
* Content: [Create applications - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/apps/deploy-use/create-applications#feedback)
* Content Source: [memdocs/configmgr/apps/deploy-use/create-applications.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/apps/deploy-use/create-applications.md)
* Product: **configuration-manager**
* Technology: **configmgr-app**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @gwblok, good question. I'll see if I can find out from engineering.

**Comment by gwblok** [comment]
Thank you for looking into it.  Let me know if I should send a frown face
or UV to have the behavior corrected.  In it's current state, it's causing
us difficulty transitioning to a user self service model.

**Comment by aczechowski** [comment]
I didn't get a response from engineering. Please file a frown on the behavior. If the response is "by design" then reopen this issue 😉
