### ISSUE TITLE
Product name in my.visualstudio.com 

### ISSUE THREAD

**Issue by CJRicard** [MicrosoftDocs/memdocs#1962]
Article states to search MVLS for "Microsoft Endpoint Configmgr (current branch)."  I noticed in my.visualstudio.com that the baseline version is titled "Microsoft Endpoint Configuration Manager - Version 2103" and that a search on "Configmgr" doesn't return any results.  So, I'm asking if 1) you can verify that the these instructions for the MVLS site are accurate (I don't have MVLS access or I'd do this myself) 2) you could add an example for customers who want to download a baseline version from my.visualstudio.com that reflects the accurate product name "Microsoft Endpoint Configuration Manager - Version 2103" - as an example so they don't waste time looking for an incorrect product name.

Thanks!
Curt

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1bc3f2a-edf6-24e0-4f45-86dc75717572
* Version Independent ID: 2789eb96-6e74-71c0-9c57-65be3d7d802c
* Content: [Updates and servicing - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/manage/updates#version-details)
* Content Source: [memdocs/configmgr/core/servers/manage/updates.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/manage/updates.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @CJRicard for the feedback. I just double-checked MVLS and can confirm that it's still "Microsoft Endpoint Configmgr (current branch)"
Let me check with our release manager about the Visual Studio site. Ideally both show the same brand.

**Comment by aczechowski** [comment]
There are different string requirements between the different systems 🙄
I'll add a note re VS.com. Thanks for letting us know.
