### ISSUE TITLE
Script signature check is it required to run silently? looks it runs silently any way. 

### ISSUE THREAD

**Issue by AntonK-Github** [MicrosoftDocs/memdocs#1964]
> "Enforce script signature check: Select Yes to verify that a trusted publisher has signed the script, which will allow the script to run with no warnings or prompts displayed. The script will run unblocked. Select No (default) to run the script with user confirmation without signature verification."

How this "user confirmation without signature verification: looks like? We never get it. Is it really implemented this way?  Our experience that detection script always runs silently just you can control whether you want to check signature or not. 

(admin edit: add article metadata for proper tracking)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca840cce-3b99-3009-c8fa-d5fab6ae37d0
* Version Independent ID: 928b9e37-626a-8d50-c6a1-ac0b5cad4be4
* Content: [Add and assign Win32 apps to Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-win32-add)
* Content Source: [memdocs/intune/apps/apps-win32-add.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/apps-win32-add.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@AntonK-Github Thank you for your feedback. I was able to test and by default, no warning or prompt displays, and the script runs unblocked.  I have updated the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2529

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @AntonK-Github Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
