### ISSUE TITLE
note clear default setting

### ISSUE THREAD

**Issue by emarana** [MicrosoftDocs/memdocs#1966]
Hi all, 

Isn't clear which is the default setting:

_Compatible TPM startup key
CSP: SystemDrivesRequireStartupAuthentication This setting is available when Startup authentication required is set to Yes.

Blocked - Block the use of startup keys.
Required (default) - Require BitLocker have a startup key and TPM present to enable BitLocker. For silent enable scenarios (including Autopilot) this setting can't be successful, as user interaction is required. It's recommended that startup keys be disabled where silent enablement of BitLocker is required.
Allowed - Enable BitLocker using the TPM if present, and allow a startup key (such as a USB drive) be present to unlock the drives.
Not configured (default)_

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10ff4382-415c-4e80-e958-3bd77252fe2d
* Version Independent ID: 398a5b4b-e8bd-1f7d-ae30-38d812daf90d
* Content: [Intune security baselines settings for Microsoft Defender for Endpoint - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/security-baseline-settings-defender-atp?pivots=atp-december-2020#bitlocker)
* Content Source: [memdocs/intune/protect/security-baseline-settings-defender-atp.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/security-baseline-settings-defender-atp.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@emarana    Thanks for this submission as this is a clear error in the doc.   
For this setting, the Security Baselines default value for _Compatible TPM startup key_ is _Requried_.  We appear to have two defaults listed. Not good.  I've submitted an edit that will remove the _default_ indicator from the value of Not configured.
