### ISSUE TITLE
Another typo

### ISSUE THREAD

**Issue by emarana** [MicrosoftDocs/memdocs#1967]
Which one is the default? 

Configure encryption method for removable data-drives
CSP: EncryptionMethodByDriveType
This setting is available when BitLocker removable drive policy is set to Configure.

Configure the encryption method and cipher strength for removable data-drives disks. **XTS- AES 128-bit is the Windows default encryption method and the recommended value.**

Not configured
AES 128bit CBC **(default)**
AES 256bit CBC
AES 128bit XTS
AES 256bit XTS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10ff4382-415c-4e80-e958-3bd77252fe2d
* Version Independent ID: 398a5b4b-e8bd-1f7d-ae30-38d812daf90d
* Content: [Intune security baselines settings for Microsoft Defender for Endpoint - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/security-baseline-settings-defender-atp?pivots=atp-december-2020#bitlocker)
* Content Source: [memdocs/intune/protect/security-baseline-settings-defender-atp.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/security-baseline-settings-defender-atp.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@emarana    Thanks for this question. I see the doc isn't too clear, so we'll fix that today.

For this setting, _Configure encryption method for removable data-drives_ the baseline uses a default of _AES 128bit CBC_, which is what is indicated in the doc. 

However, the confusion comes from an attempt to be transparent as to what the CSP for this setting describes as the Windows default behavior, which jumped a rail and is incorrect.

Per the CSP:  
- This setting is applied on a device when BitLocker is turned on, 
- If you disable or do not configure this policy setting on a device when BitLocker is on and this setting applies,  BitLocker will use the default encryption method of XTS-AES 128-bit or the encryption method specified by any setup script.
  
  However, tht default value for this setting isn't the recomended setting for removable drives. That would be per the CSP either AES-CBC 128-bit or AES-CBC 256-bit.  The baseline uses the recommendation from our Windows partners to set the encryption as defined by the default, at AES-CBC1280-bit.
 
To remove confusion, I am removing the extra text out the description from the CSP.  As always, we encourage the reader to follow the CSP link to get the direct information about the setting from the source, while this Intune reference doc will focus on what the baseline in Intune can do or sets as defaults.
