### ISSUE TITLE
Contradictory

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/memdocs#1969]
The information on header rows in the CSV seems contradictory:
- Note 2 says: delete the header information
- Under "Add devices" it shows a header row
- Note 3 says: headers are case sensitive

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea4a659b-65d0-26ec-c36a-9a21a72a09a8
* Version Independent ID: bff44b73-9021-6659-e212-66349c759989
* Content: [Manually register devices with Windows Autopilot](https://docs.microsoft.com/en-gb/mem/autopilot/add-devices)
* Content Source: [memdocs/autopilot/add-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/add-devices.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
Deleting headers is incorrect. The headers should be present. Thanks for pointing this out I will correct it.
