### ISSUE TITLE
DPLocality flags wrong

### ISSUE THREAD

**Issue by matbe** [MicrosoftDocs/memdocs#197]
According to the documentation the flags are:
4=DP_DOWNLOAD_FROM_LOCAL
6=DP_DOWNLOAD_FROM_REMOTE
17=DP_NO_FALLBACK_UNPROTECTED
18=DP_ALLOW_WUMU
19=DP_ALLOW_METERED_NETWORK

But when querying WMI and doing a bitwise comparison all the flags seem to be off with one, the correct values should be:
5=DP_DOWNLOAD_FROM_LOCAL
7=DP_DOWNLOAD_FROM_REMOTE
18=DP_NO_FALLBACK_UNPROTECTED
19=DP_ALLOW_WUMU
20=DP_ALLOW_METERED_NETWORK

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a57a0fa9-1142-4797-190f-cc4f43506e12
* Version Independent ID: b71c4d38-47e9-46cd-3bc6-02be187b7422
* Content: [SMS_CIAssignmentBaseClass Class - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/develop/reference/compliance/sms_ciassignmentbaseclass-server-wmi-class)
* Content Source: [memdocs/configmgr/develop/reference/compliance/sms_ciassignmentbaseclass-server-wmi-class.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/develop/reference/compliance/sms_ciassignmentbaseclass-server-wmi-class.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @matbe, thanks for the feedback. I did some research on this one. MVP Robert Marshall has a blog from last year where he went into more detail on this topic: http://configmgr2012.com/tag/dplocality/

I also checked with the engineering team, interestingly they say the doc is accurate based on what's in the code. 🤔 

However, the outcome is that DPLocality is deprecated. There's a note from devs that instead should use DeploymentFlags, but I still need to track down what specifically what that is. When I do, that's the update I'll make to this article.

**Comment by matbe** [comment]
After reading the blog I understand I must have done something wrong in my calculations and also I am unable to recreate the issue. You can go ahead an close this issue put please update the documentation if you find any information about DeploymentFlags. Sorry for taking your time.
