### ISSUE TITLE
Configure Azure Active Directory custom branding

### ISSUE THREAD

**Issue by anl-do** [MicrosoftDocs/memdocs#1970]
In [Phase 1, Step 2](https://docs.microsoft.com/en-us/mem/cloud-native-windows-endpoints#step-2---enrollment-and-licensing) a very important ToDo is missing, which is AAD company branding. I'm referencing to [this link](https://docs.microsoft.com/en-us/mem/autopilot/configuration-requirements).

I suggest to add this Bullet point:

> - Configure Azure Active Directory custom branding
> To display an organization-specific logon page, you must configure Azure Active Directory with the images and text that you want to be displayed. For more information, see [Quickstart: Add company branding to your sign-in page in Azure AD](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/customize-branding). Key elements for Autopilot include the "square logo", "sign-in page text", and Azure Active Directory tenant name. The tenant name is configured separately in the Azure AD tenant properties.
> 

I've learned from projects in the past, that without a company branding, the Autopilot process won't take place. Therefore, I also suggest to highlight the section or mention the importance, for instance:

> - Configure Azure Active Directory custom branding (**mandatory**)
> To display an organization-specific logon page, you must configure Azure Active Directory with the images and text that you want to be displayed. For more information, see [Quickstart: Add company branding to your sign-in page in Azure AD](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/customize-branding). Key elements for Autopilot include the "square logo", "sign-in page text", and Azure Active Directory tenant name. The tenant name is configured separately in the Azure AD tenant properties.
> 

best regards
Andreas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dc09f8f-4d26-effb-ff7f-9820f811f714
* Version Independent ID: 9278d98d-5759-1e40-b383-e304a042e315
* Content: [Get started with cloud native Windows endpoints - Microsoft Endpoint Manager](https://docs.microsoft.com/en-us/mem/cloud-native-windows-endpoints)
* Content Source: [memdocs/cloud-native-windows-endpoints.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/cloud-native-windows-endpoints.md)
* Service: **mem**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @scottbreenmsft
* Microsoft Alias: **brenduns**

**Comment by scottbreenmsft** [comment]
Thanks so much for the feedback Andreas! We'll add in some comments about this.

**Comment by scottbreenmsft** [comment]
Thanks for your feedback @anl-do, the doc was updated in #5441 #please-close
