### ISSUE TITLE
Microsoft Intune has moved! from Azure Portal.

### ISSUE THREAD

**Issue by Yogesh-Shede** [MicrosoftDocs/memdocs#1972]
[Hi Team,

I have query on page https://docs.microsoft.com/en-us/mem/intune/enrollment/enrollment-restrictions-set#change-enrollment-restriction-priority  as it should be either updated correctly. 

You can change the priority of any non-default restriction.

Sign in to the Azure portal.
Select More Services, search for Intune, and then choose Intune.
Select Device enrollment > Enrollment restrictions.
Hover over the restriction in the priority list.
Using the three vertical dots, drag the priority to the desired position in the list.

Above steps now not applicable as if we logged to Azure portal and search for Intune then it will show message as below '
Microsoft Intune has moved!
Our new home is the Microsoft Endpoint Manager admin center. (https://endpoint.microsoft.com)

Hence I think either this need to be updated ? What is your thoughts on this ?
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e8c2d91-8808-a504-da13-526b152a5cfe
* Version Independent ID: 037b60a6-d6b5-75ad-1933-39d0f7a69048
* Content: [Set enrollment restrictions in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/enrollment-restrictions-set#feedback)
* Content Source: [memdocs/intune/enrollment/enrollment-restrictions-set.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/enrollment-restrictions-set.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @Yogesh-Shede, thanks for your contribution! I just updated the article so that it aligns with what you'd experience in the Endpoint Manager admin center. You should see those changes go live on September 14.
