### ISSUE TITLE
Provide updated tutorial with for the new enrollment method "setup assistant with modern authentication"

### ISSUE THREAD

**Issue by Derusi** [MicrosoftDocs/memdocs#1975]
[Enter feedback here]
As the enrollment profile "Setup assistant with modern auth" seems like the suggested way to enroll iOS devices with Apple business management (see MC284343), it would be nice to have an updated tutorial on how to implement this enrollment variation.

Especially please have a focus on MFA enrollments, as someone else requested in an older comment on this document.
In our company for example, we need the possibility to disable MFA during the setup assistant enrollments. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e94556e6-69f3-5c56-f77d-01a810473e6a
* Version Independent ID: 8928627b-e085-2660-38dc-bf6a0ce9a6d8
* Content: [Tutorial - Use Apple Business Manager to enroll iOS/iPadOS devices in Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/tutorial-use-device-enrollment-program-enroll-ios)
* Content Source: [memdocs/intune/enrollment/tutorial-use-device-enrollment-program-enroll-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/tutorial-use-device-enrollment-program-enroll-ios.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by yogkumgit** [comment]
@Derusi  Thank you very much for your kind feedback. Your feedback will be forwarded to PG. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
