### ISSUE TITLE
IP Address needs to be added

### ISSUE THREAD

**Issue by mariosaelikeit** [MicrosoftDocs/memdocs#198]
152.199.21.175 is also required for Win32 apps to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c9c3475-56d4-026b-349f-f9cbc258537c
* Version Independent ID: 9c6476ed-8a47-bcb4-dfbf-25ba305c3b24
* Content: [Network endpoints for Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/intune-endpoints#feedback)
* Content Source: [memdocs/intune/fundamentals/intune-endpoints.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/intune-endpoints.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
(7170533)

**Comment by MatthewWhiteMoJ** [comment]
Also noticed this troubleshooting Win32 app deployments.

**Comment by mariosaelikeit** [comment]
13.89.51.159 also needs to be investigated

**Comment by ErikjeMS** [comment]
Repinged PM...

**Comment by ErikjeMS** [comment]
@mariosaelikeit The PM is unable to confirm those as requirements. I suggest you open a support ticket to see if they can work through this with you.
- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.
