### ISSUE TITLE
Link to Windows 365 Business

### ISSUE THREAD

**Issue by simontaylor-msft** [MicrosoftDocs/memdocs#1985]
Can we add a link to the Windows 365 Business documentation https://docs.microsoft.com/en-us/microsoft-365/admin/setup/get-started-windows-365-business?view=o365-worldwide?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c0d529d-00e8-2e98-0492-4f49242a1c91
* Version Independent ID: 80b4f39a-a834-0e53-d24b-7099a3a0c18d
* Content: [What is Windows 365?](https://docs.microsoft.com/en-us/windows-365/overview)
* Content Source: [windows-365/overview.md](https://github.com/MicrosoftDocs/memdocs/blob/master/windows-365/overview.md)
* Service: **cloudpc**
* Sub-service: ****
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@simontaylor-msft Good idea! I'll add it in this morning.
