### ISSUE TITLE
Do not see feature for app targeting - dropdown to select Microsoft apps

### ISSUE THREAD

**Issue by rasldasl** [MicrosoftDocs/memdocs#1990]
I do not see the recently added feature of selecting Microsoft Apps (core or all) when selecting apps for a new or existing App Protection Policy. Is the documentation incorrect or do I need to open a ticket/ 

![image](https://user-images.githubusercontent.com/38565287/133797269-6e5d9792-17ba-4125-8346-1839574d89cd.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cde34bc-bab0-d412-5971-cbc1f515a486
* Version Independent ID: ac355bba-5f6f-0168-49f3-67b7a2ddb2d4
* Content: [Create and deploy app protection policies - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policies)
* Content Source: [memdocs/intune/apps/app-protection-policies.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-protection-policies.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@rasldasl Thank you for your feedback. 

I think you are referring to the below screen
![image](https://user-images.githubusercontent.com/45987684/158072247-807df549-2bfe-4219-a001-233f0cd7fd4d.png)

The options are updated in a different way

![image](https://user-images.githubusercontent.com/45987684/158072281-7d9c7305-6a17-4c12-bcee-957b24f2a755.png)

Hope this helps!

@yogkumgit  There are no changes needed in this document.

Thanks
Sri

**Comment by rasldasl** [comment]
Yes, I had another discussion with someone and determined I would need 2 policies. I think that could be made more clear. 1 policy for all public apps and 1 policy for all custom apps. There is not way to add custom apps when targeting all public in the same policy.


Sent from my iPhone

On Mar 13, 2022, at 12:45 PM, Sriraman M S ***@***.***> wrote:

﻿

@rasldasl<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frasldasl&data=04%7C01%7C%7C42754d64208a40480c8308da05195262%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637827903553261723%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=UeH3P61kCHNFAqg60tzPN9j%2B2hFpJuhRTgcbPS7UqV4%3D&reserved=0> Thank you for your feedback.

I think you are referring to the below screen
[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F45987684%2F158072247-807df549-2bfe-4219-a001-233f0cd7fd4d.png&data=04%7C01%7C%7C42754d64208a40480c8308da05195262%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637827903553261723%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8jf3%2BWxh%2Bnf2BlNuh5c8DgXfDi%2FTA57c1ir73E3DwSI%3D&reserved=0>

The options are updated in a different way

[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F45987684%2F158072281-7d9c7305-6a17-4c12-bcee-957b24f2a755.png&data=04%7C01%7C%7C42754d64208a40480c8308da05195262%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637827903553261723%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=A3eY40Iiesrd1rVdzR3qMbUaa%2BsHekLiAqsGMrUR994%3D&reserved=0>

Hope this helps!

@yogkumgit<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fyogkumgit&data=04%7C01%7C%7C42754d64208a40480c8308da05195262%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637827903553261723%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Mdc6vm5e2cxjTg8VqakaLxoTZt4R2gGKUIZ7VgqCb%2Bw%3D&reserved=0> There are no changes needed in this document.

Thanks
Sri

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmemdocs%2Fissues%2F1990%23issuecomment-1066149530&data=04%7C01%7C%7C42754d64208a40480c8308da05195262%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637827903553261723%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=oFnUzrQoA1AK6B%2FPun0JOvnIaQAF4yeYt8CvRYdhICo%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJGHLJ5746I2JPGPFI6LQP3U7YSVDANCNFSM5EHKVW6Q&data=04%7C01%7C%7C42754d64208a40480c8308da05195262%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637827903553261723%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jmg6biXtE16W740g1CB8xYPT4byXFKfLfD713NUtY3s%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C42754d64208a40480c8308da05195262%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637827903553261723%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=bS5V8QaVjl83%2F9x3l9vlmo56QV2UpCayv70zHPy7w3c%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C42754d64208a40480c8308da05195262%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637827903553261723%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=tVYMfTNUcIXL0MclqmnTa%2Bzz3DtSUHzqwyf%2BOCPBtWg%3D&reserved=0>.

**Comment by msbemba** [comment]
@rasldasl Thank you for your quick response. I have added that to the Document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2545 to reduce ambiguity.

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @rasldasl Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
