### ISSUE TITLE
Section appears to be contradictory

### ISSUE THREAD

**Issue by BrissyScott** [MicrosoftDocs/memdocs#1992]
In the section "How Intune resolves policy conficts" the second dot point appears to contradict the first dot point. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1a645fd-8887-d268-1ed5-984ebaeef577
* Version Independent ID: f9b5d099-41ea-b3f3-536f-de61885ac1d5
* Content: [Monitor device compliance policies in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/compliance-policy-monitor)
* Content Source: [memdocs/intune/protect/compliance-policy-monitor.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/compliance-policy-monitor.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@BrissyScott Thank you for your feedback. The second point states that if there are two compliance policies that conflict, Intune uses the most secure of these policies. However, the first point discussed conflicts between a compliance policy and a configuration policy.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @BrissyScott Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by BrissyScott** [comment]
Thank you. This allowed me to understand the passage better. Must have been a late night as it seems obvious now.
________________________________
