### ISSUE TITLE
MIssing references to AAD

### ISSUE THREAD

**Issue by GenerAhl** [MicrosoftDocs/memdocs#1994]
[Enter feedback here]
This page is missing all references to Azure Active Directory discovery methods.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3fc7fd4-b3de-1574-1546-e9722aa96bcb
* Version Independent ID: e982e9ac-94bd-852e-2013-eaadc9dbfbbc
* Content: [Discover device and user resources - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/run-discovery)
* Content Source: [memdocs/configmgr/core/servers/deploy/configure/run-discovery.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/deploy/configure/run-discovery.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @GenerAhl for the feedback 😃
