### ISSUE TITLE
Clarifying required for multiple domains and or/connectors

### ISSUE THREAD

**Issue by RobertEbbrecht** [MicrosoftDocs/memdocs#1995]
Every connector installed requires permissions for all domains and OU that are used in the Domain Join profiles.

The connectors are chosen randomly and do not represent their own domain.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f93dd93-e003-36fc-02d6-07166537d914
* Version Independent ID: 1b860d13-bcf5-50da-89f9-ee12ece6edb2
* Content: [Enrollment for hybrid Azure AD-joined devices - Windows Autopilot](https://docs.microsoft.com/en-us/mem/autopilot/windows-autopilot-hybrid)
* Content Source: [memdocs/autopilot/windows-autopilot-hybrid.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/windows-autopilot-hybrid.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by msbemba** [comment]
@RobertEbbrecht Thank you for your feedback. if you are planning to install multiple connectors and have multiple domains in the organization. You need to install connectors using a Service account that can create Objects in all domains and OU. This way even if it does not represent their own domain they have access to all domains and OU that are used in the Domain Join profiles.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @RobertEbbrecht Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by RobertEbbrecht** [comment]
@msbemba The "better" and more secure design would be to allow targeting of the connector chosen by parsing the policy that defines the AD domain name and OU. The random choice results in service accounts that require permissions to create AD computer objects in all connected on premise AD forests. In complex environments with many AD forests having multiple merger and acquisition history this results in the requirement to have all connectors in the same security tier and firewall ruleset as the AADC sync servers just to create computer objects for Windows client OS.

**Comment by msbemba** [comment]
@RobertEbbrecht I understand the scenario when there is a complex environemtn. I would recommend you to post this on our feedback portal -  https://feedbackportal.microsoft.com/.

This way you will have our product/dev team work on it and provide you direct feedback.

Thanks
Sri

**Comment by RobertEbbrecht** [comment]
See/vote here:  [](https://feedbackportal.microsoft.com/feedback/idea/bed49093-6ba4-ec11-a81c-6045bd7cdb8a)
