### ISSUE TITLE
Hybrid join no longer a requirement if VM is only AAD joined?

### ISSUE THREAD

**Issue by theonlycoder** [MicrosoftDocs/memdocs#1997]
Hi,

The article states that a session host VM (in my case single-session / personal) must be hybrid joined to make use of Intune for management. However, Microsoft have recently released support for pure AAD join of session hosts. See here: https://techcommunity.microsoft.com/t5/azure-virtual-desktop/announcing-general-availability-of-azure-ad-joined-vms-support/ba-p/2751083

I think I am right in saying that if you are making use of the newly-released feature and your VMs are AAD joined only, use of Intune is still supported (minus the few exceptions mentioned in the article). It certainly seems to be working so far in the little testing I have done in my lab. If that's the case, logically that would mean that hybrid join is no longer a requirement to make use of Intune in this case. If that's true, should the article be updated to make it clear that Intune is supported in that scenario as well? Presumably the bits about MDM auto enrollment using GPO etc would also no longer apply as you are enrolling the VM in AAD during the VM creation process in the AVD portal.

I appreciate that the GA release of AD join is not really suitable for multi-session / pooled session hosts due to the lack of support for FS Logix. I also understand that Intune support for the multi-session edition of Windows 10 is also quite limited. However, this article seems to deal primarily with the single-session use case and refers to other docs for multi-session. With single session, I would expect everything to be supported that would have been supported when hybrid joined (i.e. everything other than the exceptions mentioned in the article).

Hope that helps & thanks for all your hard work. Makes the job of people like me a lot easier!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c838c69f-95e7-e3de-25e6-6e52f43edf77
* Version Independent ID: 9f3dd8bf-d060-5ccf-e8a8-9fc10d619b58
* Content: [Using Azure Virtual Desktop single-session with Microsoft Endpoint Manager](https://docs.microsoft.com/en-us/mem/intune/fundamentals/azure-virtual-desktop)
* Content Source: [memdocs/intune/fundamentals/azure-virtual-desktop.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/azure-virtual-desktop.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@theonlycoder The PM has added a bullet item about Azure AD join which will go live later today. Thanks!
