### ISSUE TITLE
Old command 

### ISSUE THREAD

**Issue by OffColour** [MicrosoftDocs/memdocs#200]
WARNING: The command 'Get-IntuneAuthenticationToken' is obsolete. Use Set-IntuneAuthenticationToken and
Remove-IntuneAuthenticationToken instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa43fc11-ff6b-20c8-5bfa-a89572295223
* Version Independent ID: ea0f43b6-5c74-6f9e-7e0c-ec86db3e4400
* Content: [Use imported PFX certificates in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/certificates-imported-pfx-configure#create-a-pkcs-imported-certificate-profile)
* Content Source: [memdocs/intune/protect/certificates-imported-pfx-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certificates-imported-pfx-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@OffColour  Thanks for the feedback. I’ve checked in with our developers on this, and they’ve confirmed we can replace Get-IntuneAuthenticationToken with Set-IntuneAuthenticationToken. 

In addition, we no longer need to set this to a local variable to hold the token, which means we can remove the references to **$authResult** and the parameters it sets. That will also simplify a few other steps in that same procedure. 

I’ve submitted a content update for this, which should be live in content later today.
