### ISSUE TITLE
Assign user certificate type to a device group

### ISSUE THREAD

**Issue by toxarisswe** [MicrosoftDocs/memdocs#2003]
Hello.
Is it possible to create a SCEP profile configured as a user certificate type to a group containing devices. Or do I have to deploy the SCEP profile to groups containing users?
Also are there any difference between iOS and AE Corporate Owned (Fully Managed or Work Profile)?

I'm trying to build a scenario with different usage scenarios on device level. And depending on usage scenario I need to identify the device type using the user certificate. The certificates are used when the device is authenticating against the WiFi and VPN. Depending on certificate attributes the user get different network access depending on what type of device.

We have four types of devices, Administrative and HealthCare, two AE and two iOS.
iOS: depending on DEP profile the device is a Administrative or a HealthCare device
AE Corporate Owned: Fully Managed device are HealthCare devices and Work Profile are Administrative

The devices are divided in to four dynamic groups based on device.enrollmentProfileName. On these groups I intend to deploy user certificated type based SCEP profiles, each containing information about device usage type in Subject Name, example "CN={{UserName}}-Administrative" or "CN={{UserName}}-HealthCare". By that the RADIUS servers will be able to filter out if the device is a Administrative or HealthCare and who is using the device and by that assign different network access.

Is it possible to setup this scenario?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30c444f9-5cc4-7276-6882-d6b32ee453ea
* Version Independent ID: f1ec96ac-c890-2ed1-ede4-179de4b4e4cc
* Content: [Use SCEP certificate profiles with Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/certificates-profile-scep)
* Content Source: [memdocs/intune/protect/certificates-profile-scep.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certificates-profile-scep.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@toxarisswe Thank you for your feedback. Sorry about the delay in responding. We handle modifications regarding the documents. For questions, Issues, or How-to queries, I'd recommend you contact Support via the need help section on the M365 Admin center.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @toxarisswe Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
