### ISSUE TITLE
Wrong email listed on page

### ISSUE THREAD

**Issue by clau3107** [MicrosoftDocs/memdocs#2005]
The article has an email link in "Select Email details or email Microsoft using this template." portion
Emails sent to that email address bounce back as undeliverable.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 625b644a-74ca-4da7-167d-01d59a1136a3
* Version Independent ID: a791f224-c88d-bd03-bfc5-9fd84a4e90f4
* Content: [Send errors from your Mac device to your company support](https://docs.microsoft.com/en-us/mem/intune/user-help/send-errors-macos)
* Content Source: [memdocs/intune/user-help/send-errors-macos.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/user-help/send-errors-macos.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @clau3107, thanks for your contribution to Docs! That email address/method of contact is no longer supported so I removed it from the article. I'm also opening an internal task for us to look over the rest of this article this month and make sure it's up-to-date.
