### ISSUE TITLE
Incorrect GPO Path

### ISSUE THREAD

**Issue by pnwnightowl** [MicrosoftDocs/memdocs#2009]
Under the section **Configure the default language using Group Policy,** step 11 should have the GPO path:

User Configuration > Preferences > Control Panel

regional options is not located under Windows Settings....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62545a05-9f9e-6bb9-8dbc-f920e9ca1793
* Version Independent ID: f981ac59-e2a1-133f-ef36-fb24f33b5189
* Content: [Provide users a localized Windows experience on their Cloud PC](https://docs.microsoft.com/en-us/windows-365/provide-localized-windows-experience#add-languages-to-windows-using-a-script-and-capture-the-image)
* Content Source: [windows-365/provide-localized-windows-experience.md](https://github.com/MicrosoftDocs/memdocs/blob/master/windows-365/provide-localized-windows-experience.md)
* Service: **cloudpc**
* Sub-service: ****
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@pnwnightowl Thanks! I'll fix it.
