### ISSUE TITLE
enable-data-sharing.md

### ISSUE THREAD

**Issue by KONIKPK** [MicrosoftDocs/memdocs#201]
can you please provide IP address for required services ?

(admin edit: add metadata for target article)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55ba9622-311f-0c2c-bce3-f0510a4d2b79
* Version Independent ID: 49d1ca0a-b8b0-bfa9-c735-d45c7118ac9a
* Content: [Enable data sharing - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/desktop-analytics/enable-data-sharing)
* Content Source: [memdocs/configmgr/desktop-analytics/enable-data-sharing.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/desktop-analytics/enable-data-sharing.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by ErikjeMS** [comment]
@KONIKPK Please provide more detail on your request. Also, to which article does this issue apply?

**Comment by aczechowski** [comment]
Thanks @KONIKPK for the feedback. I'll add a link similar to what we have in the broader ConfigMgr [internet access requirements](https://docs.microsoft.com/mem/configmgr/core/plan-design/network/internet-endpoints#microsoft-public-ip-addresses):

> For more information on the Microsoft IP address ranges, see [Microsoft Public IP Space](https://www.microsoft.com/download/details.aspx?id=53602). These addresses update regularly. There's no granularity by service, any IP address in these ranges could be used.
