### ISSUE TITLE
Language Code is an unclear term for the registry value data

### ISSUE THREAD

**Issue by pnwnightowl** [MicrosoftDocs/memdocs#2010]
Under the section **Configure the default language using Group Policy** on step 6 the Value Data is asking for a Language Code and when you click on the [link in the Note](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/available-language-packs-for-windows#language-packs), it's not clear from the four columns in the table which is the Language Code.  Instead of asking for Language Code for the value, we should ask for the Region Name, Region Tag, Region ID, or Region Decimal ID and also include an example of what that value would be.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62545a05-9f9e-6bb9-8dbc-f920e9ca1793
* Version Independent ID: f981ac59-e2a1-133f-ef36-fb24f33b5189
* Content: [Provide users a localized Windows experience on their Cloud PC](https://docs.microsoft.com/en-us/windows-365/provide-localized-windows-experience#add-languages-to-windows-using-a-script-and-capture-the-image)
* Content Source: [windows-365/provide-localized-windows-experience.md](https://github.com/MicrosoftDocs/memdocs/blob/master/windows-365/provide-localized-windows-experience.md)
* Service: **cloudpc**
* Sub-service: ****
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@pnwnightowl Thanks! It's fixed as you suggest.
