### ISSUE TITLE
Targetting LoB and Win32 packages not supported

### ISSUE THREAD

**Issue by jotheman0303** [MicrosoftDocs/memdocs#2016]
Please put this note "Make sure not to target both win32 and LOB apps to the same device." in huge block letters, underlined, bold and italic. I hear so many people that mess up on this (including myself at some point). In all seriousness, making this a purple balloon remark stating "**Note!**:" would definitely help.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0f572e0-1bc0-6f14-7f60-989eb67fb7e7
* Version Independent ID: e4ec5b25-d9a6-d260-6cf6-ff4f3eb3ecb8
* Content: [Windows Autopilot for pre-provisioned deployment](https://docs.microsoft.com/en-us/mem/autopilot/pre-provision)
* Content Source: [memdocs/autopilot/pre-provision.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/pre-provision.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
PR is merged and the text will be highlighted at the next publish cycle. Thanks for the suggestion!
