### ISSUE TITLE
Grammar Police in the house

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/memdocs#2023]
eh? "and respond and manage risk" perhaps something like this instead?
"and respond to & manage risk"

it's weird to bookend a word with "and." Bookend means to put something before and after a word.

> These services are part of the Microsoft 365 stack to help secure access, protect data, and respond and manage risk.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fb7e4a5-d1a2-deb7-73d4-a9b3b4ce07ab
* Version Independent ID: 43915b87-3076-18dd-21e8-3c44a0c653f2
* Content: [Microsoft Endpoint Manager overview](https://docs.microsoft.com/en-us/mem/endpoint-manager-overview)
* Content Source: [memdocs/endpoint-manager-overview.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/endpoint-manager-overview.md)
* Service: **mem**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@jonwbstr Agreed. I updated the text. Changes should be live tomorrow sometime. In the future, it'd be great if you created pull requests for doc updates like this. We appreciate the help.
