### ISSUE TITLE
Add verbiage about encryption at rest to "Windows 365 data storage" section 

### ISSUE THREAD

**Issue by BrianLe-Cerf** [MicrosoftDocs/memdocs#2025]
Our customer was concerned about what we're doing to keep their data safe once it gets to our systems, particularly about encryption. This article covers some aspects of data storage, but it does not talk about data encryption explicitly.

Adding one or two sentences to the article in the "Windows 365 data storage" section that covers fact we use encryption at rest for server side encryption would help address this customer concern.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41d9aa30-5324-b3cc-8b7c-a6dee2373aba
* Version Independent ID: f1a0996c-c2fc-3966-55d2-279e9049af58
* Content: [Privacy and personal data in Windows 365](https://docs.microsoft.com/en-us/windows-365/privacy-personal-data)
* Content Source: [windows-365/privacy-personal-data.md](https://github.com/MicrosoftDocs/memdocs/blob/master/windows-365/privacy-personal-data.md)
* Service: **cloudpc**
* Sub-service: ****
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
36777177

**Comment by ErikjeMS** [comment]
I'll add a link to the encryption article.
https://learn.microsoft.com/en-us/windows-365/enterprise/encryption
