### ISSUE TITLE
Discoverability issue - add reference link to article about Teams media optimizations in custom images

### ISSUE THREAD

**Issue by BrianLe-Cerf** [MicrosoftDocs/memdocs#2027]
One of our customers had questions about configuring Teams media optimizations in custom images.

This is called out in a separate article, https://docs.microsoft.com/en-us/windows-365/create-custom-image-support-teams . 
However, this article is hard to find as it's located under How-to-guides/Apps/Microsoft Teams, and customers looking for guidance around custom images might not find it.

It would be great if the "Custom images" section of this page referenced this article: https://docs.microsoft.com/en-us/windows-365/create-custom-image-support-teams in order to avoid discoverability issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 159c035d-d9d2-1a88-33a3-f4d2864fd2db
* Version Independent ID: 9d27c2cb-cb0a-2b99-a09d-ab8acd04bda8
* Content: [Device images in Windows 365](https://docs.microsoft.com/en-us/windows-365/device-images)
* Content Source: [windows-365/device-images.md](https://github.com/MicrosoftDocs/memdocs/blob/master/windows-365/device-images.md)
* Service: **cloudpc**
* Sub-service: ****
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@BrianLe-Cerf I'll add a link to the apps section in the Next steps. Thanks!
