### ISSUE TITLE
Please expand on this note.

### ISSUE THREAD

**Issue by arcum** [MicrosoftDocs/memdocs#203]
"To delay the visibility of software updates for a specific amount of time on your supervised iOS/iPadOS devices, configure those settings in Device Restrictions. Software update policies override any device restrictions. When you set both a software update policy and restriction to delay visibility of software updates, the device forces a software update per the policy. The restriction applies so that users don't see the option to update the device themselves, and the update is pushed as defined by your iOS update policy."

So. Do the restrictions to hide updates for x days still apply? If not. Why do we have this option then? I want to keep my devices up to date, but only after x days of testing them on our testgroup.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc473a5-4b72-9486-f9db-8f3beb0aeeff
* Version Independent ID: bf102862-75c3-2b2e-cfae-c1cd4fa34e3f
* Content: [Configure iOS/iPadOS software update policies in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/software-updates-ios?source=docs)
* Content Source: [memdocs/intune/protect/software-updates-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/software-updates-ios.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@arcum  Thanks for the feedback. Device restrictions prevent users from seeing an update until the device restriction period ends or until a software update policy overrides the device restriction and installs the update per its own schedule.  

I'm looking at how to revise the note to make this more clear to the reader who is new to this content. How does the following seem?

- You can use device restrictions to hide an update from device users for a period of time on your supervised iOS/iPadOS devices. A restriction period can give you time to test an update before its visible to users to install. After the device restriction period expires, the update becomes visible to users. Users can then choose to install it, or your Software update policies might automatically install it soon after.

  When you use a device restriction to hide an update, review your software update policies to ensure they wont schedule the install of the update before that restriction period ends. Software update policies install updates based on their own schedule, regardless of the update being hidden or visible to the device user.

**Comment by arcum** [comment]
@Brenduns That is indeed much clearer. Thanks for this.

**Comment by Brenduns** [comment]
@arcum   Thanks for confirming. I'll submit an update the article with this same information, which should go live later today
