### ISSUE TITLE
Settings applied based on user affinity table has conflicting info for iOS/macOS ADE

### ISSUE THREAD

**Issue by chitch** [MicrosoftDocs/memdocs#2031]
In the Settings applied based on user affinity, there is conflicting information for iOS/macOS ADE.  

| Device platform | User affinity | Azure applies | Intune applies |
| ----- | ----- | ----- | ----- | ----- |
| iOS/macOS Automated Device Enrollment (ADE) | Yes | Yes | Yes |
| iOS/macOS ADE | No | Yes | No |

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0e6e96c-331b-20e6-c646-45cb351e3fdf
* Version Independent ID: dacdefe3-7674-9083-e5be-c10a3b615e03
* Content: [Understand between Intune and Azure device limit restrictions](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-limit-intune-azure)
* Content Source: [memdocs/intune/enrollment/device-limit-intune-azure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/device-limit-intune-azure.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@chitch Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2544

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @chitch Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
