### ISSUE TITLE
"Startup memory to at least 1024000 MB, preferably 4096000 MB"??? Really???

### ISSUE THREAD

**Issue by micachi** [MicrosoftDocs/memdocs#2038]
> 8. On the Assign Memory page, set Startup memory to at least 1024000 MB, preferably 4096000 MB. Select Next.

I've never seen a Windows client machine with 4 TB of memory.
Isn't it 1024 MB and 4096 MB correctly?

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: bd48fb7a-2fa7-4143-1397-9b825de70e25
* Version Independent ID: f9a3a626-9a10-fd2e-48aa-77e6abfec189
* Content: [Convert custom device images to generation 2 virtual machines in Windows 365](https://docs.microsoft.com/ja-jp/windows-365/device-images-convert-generation-2)
* Content Source: [windows-365/device-images-convert-generation-2.md](https://github.com/MicrosoftDocs/memdocs/blob/master/windows-365/device-images-convert-generation-2.md)
* Service: **cloudpc**
* Sub-service: ****
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM
37831582

**Comment by ErikjeMS** [comment]
Corrected to 4096 MB
