### ISSUE TITLE
Enable Microsoft Defender for Endpoint in Intune

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/memdocs#2040]
Hello,

Our setup run:

1. All users use the Microsoft 365 E3
2. We use Azure Security Center with Defender ATP enabled for VM, so we have Windows Security Center with Vulnerability management already available
3. We have bought extra protection for admin accounts using Microsoft 365 E5 Security per user licenses

Now, if we will enable the:
"Enable Microsoft Defender for Endpoint in Intune"
![image](https://user-images.githubusercontent.com/39700914/135441970-04b74bac-204e-47cf-a551-b5a9942afe11.png)

Is it possible that all devices from Microsoft 365 E3 will be enabled to Defender ATP and we will have a bill for every device we have in a tenant?
Or only devices that are included in the on-boarding package (create via Intune MDM) will be on-boarded to the Defender ATP?
And does Microsoft 365 E5 Security per user license requires the same onboarding process via Intune MDM?
And how a bill will be set for the user who has "Microsoft 365 E5 Security per user license" and user device onboarded via onboarding package, is it possible that we will have:
1. Bill from Azure Security Center per device
2. Bill for Microsoft 365 E5 Security per user license

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24fa182f-ace6-e7e2-ff98-91951be7d10e
* Version Independent ID: f1acb398-6d69-b91c-5ee0-3da3bbf7809f
* Content: [Configure Microsoft Defender for Endpoint in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/advanced-threat-protection-configure)
* Content Source: [memdocs/intune/protect/advanced-threat-protection-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/advanced-threat-protection-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by yogkumgit** [comment]
@lightupdifire Considering the nature of the issue, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
