### ISSUE TITLE
how do you "export a device list as a .csv file from Cloud provisioning and use it to Manually register devices with Windows Autopilot."

### ISSUE THREAD

**Issue by greinjjcop** [MicrosoftDocs/memdocs#2041]
the note under cloud provisioning is real interesting, maybe it will be clearer in a new release but how do you actually do this??
The page in link does not say

note i am talking about: 
You can export a device list as a .csv file from Cloud provisioning and use it to Manually register devices with Windows Autopilot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45c861f2-b63e-62be-d8f5-b26e0ce0828d
* Version Independent ID: 1a781b01-2383-441c-ee8e-0becf94886e3
* Content: [Work from anywhere (preview) report in Endpoint analytics - Microsoft Endpoint Manager](https://docs.microsoft.com/en-us/mem/analytics/work-from-anywhere)
* Content Source: [memdocs/analytics/work-from-anywhere.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/analytics/work-from-anywhere.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by frankroj** [comment]
Thank you for the feedback @greinjjcop. I apologize for the long time it took to respond back to this feedback item. The following link describes the format that the CSV files should be in if you want to import a list of devices for Autopilot.

https://learn.microsoft.com/en-us/mem/autopilot/add-devices#ensure-that-the-csv-file-meets-requirements

If you have additional questions or feedback, please open a new feedback item.
