### ISSUE TITLE
Edition "Switches" that are valid

### ISSUE THREAD

**Issue by mattsmacblog** [MicrosoftDocs/memdocs#2043]
I have been through a MS Support ticket about why this doesn't work for going from Win10 Enterprise KMS to Win10 Enterprise MAK.  Could you spell out on the Documentation page here what "edition upgrades" are supported?  To me, this is an Edition switch but perhaps not to MS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9f9139b-7f10-e11d-7633-215e2d4c0a51
* Version Independent ID: 463f2b3e-116b-2ab4-632c-a53dfc2833d7
* Content: [Windows 10 upgrade and S mode settings in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/configuration/edition-upgrade-windows-settings)
* Content Source: [memdocs/intune/configuration/edition-upgrade-windows-settings.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/edition-upgrade-windows-settings.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@mattsmacblog In this Intune doc, we only list the options available in the Endpoint Manager admin center. We won't be adding options not available in the admin center.

As for KMS, maybe [Windows 10 edition upgrade](https://docs.microsoft.com/windows/deployment/upgrade/windows-10-edition-upgrades) in the Windows documentation would be helpful. FYI, I added a link to this Windows Deployment article to the Intune article. The changes should be live sometime tomorrow.
