### ISSUE TITLE
API Permissions need updating

### ISSUE THREAD

**Issue by K-to-the-B** [MicrosoftDocs/memdocs#2046]
The article states the following
```
Select Add a permission again.
On the Request API permissions page, select Azure Active Directory Graph > Application permissions.
Expand Application and select the checkbox for Application.Read.All (Read all applications).
Select Add permissions to save this configuration.
```
Azure Active Director Graph is no longer available. https://techcommunity.microsoft.com/t5/azure-active-directory-identity/update-your-applications-to-use-microsoft-authentication-library/ba-p/1257363

Is there another permission that needs to be added or can this section be ignored/removed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cda83a64-56ae-a632-dc81-dfd1a03984c1
* Version Independent ID: b93da48e-4097-4c3a-f6c8-02a5c4e0a616
* Content: [Use third-party certification authorities (CA) with SCEP in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/certificate-authority-add-scep-overview)
* Content Source: [memdocs/intune/protect/certificate-authority-add-scep-overview.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certificate-authority-add-scep-overview.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@K-to-the-B Thank you for your feedback. You are correct the capability to add Azure AD Graph permissions to the required permissions for an app registration through the Azure portal is now disabled. The document has already been updated with the Correct steps to avoid confusion.

The correct steps are 

n the navigation pane for the app, go to API permissions, which are under Manage. You're going to add three separate application permissions:

Select Add a permission:

On the Request API permissions page, select Intune and then select Application permissions.
Select the checkbox for scep_challenge_provider (SCEP challenge validation).
Select Add permissions to save this configuration.
Select Add a permission again.

On the Request API permissions page, select Microsoft Graph > Application permissions.
Expand Application and select the checkbox for Application.Read.All (Read all applications).
Select Add permissions to save this configuration.

Hope this helps!

@yogkumgit  There are no changes required in the document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @K-to-the-B Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
