### ISSUE TITLE
Assign a user to a specific Autopilot device

### ISSUE THREAD

**Issue by ajp999** [MicrosoftDocs/memdocs#2047]
[Enter feedback here]

After assigning a user to a specific Autopilot device, the user will no longer see a personalized hello screen with a pre-populated Azure AD User Principal Name and will now need to manually enter their login credentials when prompted.

Please can this page be updated to reflect this change in behavior within Windows Autopilot
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97ce79c0-0014-f6f0-95f7-58574bfdefb3
* Version Independent ID: 40b3877e-a094-8d05-c95b-ca842c5ca8ce
* Content: [Create device groups for Windows Autopilot - Microsoft Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/autopilot/enrollment-autopilot)
* Content Source: [memdocs/autopilot/enrollment-autopilot.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/enrollment-autopilot.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by msbemba** [comment]
@ajp999 Thank you for your feedback. You are correct, After assigning a user to a specific Autopilot device, the user will no longer see a personalized hello screen with a pre-populated Azure AD User Principal Name

The Note on the page mentions it as well "Assigning a licensed user to a registered Autopilot device using Microsoft Endpoint Manager no longer pre-fills any user information as described below." 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ajp999 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
