### ISSUE TITLE
How can I register my mobile in Intune

### ISSUE THREAD

**Issue by Prabhpreet1699** [MicrosoftDocs/memdocs#2048]
How can I register my mobile in   #1704 

[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb1f7fe9-6bae-6fc5-eb77-d456e08f8736
* Version Independent ID: b0d12a58-0a77-67dc-7006-49e98589ca7f
* Content: [What info can your company see when you enroll your device?](https://docs.microsoft.com/en-gb/mem/intune/user-help/what-info-can-your-company-see-when-you-enroll-your-device-in-intune)
* Content Source: [memdocs/intune/user-help/what-info-can-your-company-see-when-you-enroll-your-device-in-intune.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/user-help/what-info-can-your-company-see-when-you-enroll-your-device-in-intune.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@Prabhpreet1699  Thank you for your feedback. The LInk is functional again and I'm able to download the apk file.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Prabhpreet1699 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
