### ISSUE TITLE
How can I register my mobile in Intune

### ISSUE THREAD

**Issue by Prabhpreet1699** [MicrosoftDocs/memdocs#2049]
How can I register my mobile in Intune as It is regularly showing the error and not able to register.
Please Help

**Comment by aczechowski** [comment]
I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Intune forums](https://docs.microsoft.com/answers/products/mem). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
