### ISSUE TITLE
ConvertTo-AutopilotConfigurationJSON only supports piping the Autopilot profile

### ISSUE THREAD

**Issue by o-l-a-v** [MicrosoftDocs/memdocs#2050]
https://docs.microsoft.com/en-us/mem/autopilot/existing-devices#create-the-json-file

Following works, all information is included:

```powershell
Get-AutopilotProfile | ConvertTo-AutopilotConfigurationJSON
```

Following does not work, a lot of information is not included:

```powershell
# One profile
ConvertTo-AutopilotConfigurationJSON -profile (Get-AutopilotProfile)[0]

# All profiles
$([array](Get-AutopilotProfile)).ForEach{ConvertTo-AutopilotConfigurationJSON -profile $_}
```

Attributes ```CloudAssignedDeviceName```, ```Comment_File``` and ```ZtdCorrelationId``` gets no value (= null) when not piping.

## Side note

Maybe it's time to move this functionality into the ```Microsoft.Graph``` module, ref:

* https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/891

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cb0ab9e-0902-8c43-5cb9-8ade31c88f5f
* Version Independent ID: d30aebff-dc9c-bcd9-2ffd-c7158da55026
* Content: [Windows Autopilot Deployment for existing devices](https://docs.microsoft.com/en-us/mem/autopilot/existing-devices#create-the-json-file)
* Content Source: [memdocs/autopilot/existing-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/existing-devices.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by aczechowski** [comment]
Hi @o-l-a-v, this article only uses the first syntax that you list (`Get-AutopilotProfile | ConvertTo-AutopilotConfigurationJSON`), so I'm assuming that your feedback is more general about the cmdlets themselves. I think there are two options on how best to share this feedback with the Intune engineering team:

- With administrative access to the admin center, you can use the Help and Support option to file an on-line support ticket for a supported service. For more information, see https://docs.microsoft.com/mem/get-support
- File product feedback: https://feedbackportal.microsoft.com/feedback/forum/ef1d6d38-fd1b-ec11-b6e7-0022481f8472

I'm closing this issue as I don't think there's anything actionable on this article at this time.
