### ISSUE TITLE
Missing steps in Task 4 for proper device collection synchronization

### ISSUE THREAD

**Issue by dmcwee** [MicrosoftDocs/memdocs#2052]
The documentation for [Task 4](https://docs.microsoft.com/en-us/mem/intune/protect/tenant-attach-intune#task-4-enable-collections-for-endpoint-security-policies) should include the need to map an existing AAD Security Group to the device collection either as a Note or as an additional sub-task. Without this step the device collection will not be created or populated in AAD. It may also be helpful to point users to [this blog post](https://techcommunity.microsoft.com/t5/configuration-manager-blog/cloud-attach-your-future-part-i-configmgr-to-azuread-groups/ba-p/1424519) from Intune+SCCM PM for a script that can help them automate the creation of the security groups in AAD.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1719f99-2899-f3ba-dcd4-35e0b799713e
* Version Independent ID: f87bc1b4-9818-2658-89b8-53d2abe65c9a
* Content: [Use Intune policies with tenant attached Configuration Manager devices](https://docs.microsoft.com/en-us/mem/intune/protect/tenant-attach-intune#enable-collections-for-use-with-endpoint-security-policies)
* Content Source: [memdocs/intune/protect/tenant-attach-intune.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/tenant-attach-intune.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@dmcwee Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2546

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @dmcwee Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
