### ISSUE TITLE
Inconsistent documentation regarding Endpoint Analytics Licensing 

### ISSUE THREAD

**Issue by gatesry** [MicrosoftDocs/memdocs#2054]
Hello,

Please clarify the licensing requirements for Endpoint Analytics. Under [What is Endpoint analytics - Licensing Prerequisites ](https://docs.microsoft.com/en-us/mem/analytics/overview#licensing-prerequisites) it states these are required.

- Windows 10 Enterprise E3 or E5 (included in Microsoft 365 F3, E3, or E5)
- Windows 10 Education A3 or A5 (included in Microsoft 365 A3 or A5)
- Windows 10 Virtual Desktop Access (VDA) per user

Under [Microsoft Intune licensing](https://docs.microsoft.com/en-us/mem/intune/fundamentals/licenses#microsoft-intune), It states the following are eligible.

- Microsoft 365 E5
- Microsoft 365 E3
- Enterprise Mobility + Security E5
- Enterprise Mobility + Security E3
- Microsoft 365 Business Premium
- Microsoft 365 F1
- Microsoft 365 F3
- Microsoft 365 Government G5
- Microsoft 365 Government G3
- Intune for Education

@ahuang2640
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73c7bea7-ccff-ca28-35e4-820494059bf6
* Version Independent ID: 42e6e56f-d5ca-4124-f409-7e34ca609a3a
* Content: [Licenses available for Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/licenses)
* Content Source: [memdocs/intune/fundamentals/licenses.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/licenses.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by msbemba** [comment]
@gatesry Thank you for your feedback. 

To use Endpoint analytics, All users would need is Intune enrolled or co-managed devices i.e valid license for the use of Microsoft Endpoint Manager.

However, For proactive remediation, users need to have one of the following

Windows 10 Enterprise E3 or E5 (included in Microsoft 365 F3, E3, or E5)
Windows 10 Education A3 or A5 (included in Microsoft 365 A3 or A5)
Windows 10 Virtual Desktop Access (VDA) per user

Unfortunately, proactive remediation just isn’t available to the business license or other SKUs not mentioned.

Hope this helps!

Thanks
Sri

**Comment by gatesry** [comment]
> @gatesry Thank you for your feedback.
> 
> To use Endpoint analytics, All users would need is Intune enrolled or co-managed devices i.e valid license for the use of Microsoft Endpoint Manager.
> 
> However, For proactive remediation, users need to have one of the following
> 
> Windows 10 Enterprise E3 or E5 (included in Microsoft 365 F3, E3, or E5) Windows 10 Education A3 or A5 (included in Microsoft 365 A3 or A5) Windows 10 Virtual Desktop Access (VDA) per user
> 
> Unfortunately, proactive remediation just isn’t available to the business license or other SKUs not mentioned.
> 
> Hope this helps!
> 
> Thanks Sri

Thank you Sri.
