### ISSUE TITLE
iOS 15 is released

### ISSUE THREAD

**Issue by GenerAhl** [MicrosoftDocs/memdocs#2056]
The last update of this page was Oct 1 but it still says "Later this year, Apple is expected to release iOS 15", which happened Sep 20.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66f915d1-8486-44dc-a605-280f979d6f9b
* Version Independent ID: 23c6b2c3-64c1-2df3-ad51-d9be083871a1
* Content: [In development - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/in-development)
* Content Source: [memdocs/intune/fundamentals/in-development.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/in-development.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @dougeby
* Microsoft Alias: **dougeby**

**Comment by msbemba** [comment]
@GenerAhl Thank you for your feedback. I have made changes via PR#https://github.com/MicrosoftDocs/memdocs/pull/2547

Once the author approves, the changes will be live.

Thanks
Sri
