### ISSUE TITLE
Deadline and Deferral verbiage is confusing

### ISSUE THREAD

**Issue by maro13** [MicrosoftDocs/memdocs#2059]
[Enter feedback here]
It is unclear in this specific doc that the deadline starts on the publication date as mentioned in other docs regarding these settings. Also, does the Deferral also start on the publication date? if so, then the text needs to be the same for both deferral and deadline. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401fe085-6254-6dbb-24c6-7e6fe56d0f3a
* Version Independent ID: 774ae4fb-b28e-1fb3-46d9-5802c0e4ac6c
* Content: [Windows for Business Update settings for  Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/windows-update-settings)
* Content Source: [memdocs/intune/protect/windows-update-settings.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/windows-update-settings.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@maro13 Thank you for your feedback. Deferral and Deadline are both different. 

When you defer feature updates, new Windows features won’t be offered, downloaded, or installed for a period of time that is greater than the deferral period set.  More information can be found here - https://support.microsoft.com/en-us/help/4026834/windows-10-defer-feature-updates

However, Deadline Continuously checks for updates and allows specifying the number of days that a user has before quality and feature updates are installed on their device automatically. Also, there is an option to set a grace period after which the operating system restarts automatically.

Hope this clarifies and answers your question.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @maro13 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
