### ISSUE TITLE
Parameter clarity, example key name and other items

### ISSUE THREAD

**Issue by OffColour** [MicrosoftDocs/memdocs#206]
"Add-IntuneKspKey "Microsoft Software Key Storage Provider" "PFXEncryptionKey"" should be
"Add-IntuneKspKey -ProviderName "Microsoft Software Key Storage Provider" -KeyName "PFXEncryptionKeyName"" 

This makes is clear that you're giving the generated key a name and not providing details of the key itself.

Get-IntuneUserPfxCertificate does not takes $authresult as a parameter.

The available IntendedPurpose options don't match up with those available in Intune when setting up a profile. Not sure if they should, but seems logical.

Can you also add a note that Imported PKCS cannot be used for VPNs even though it's available as one of the intended purposes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa43fc11-ff6b-20c8-5bfa-a89572295223
* Version Independent ID: ea0f43b6-5c74-6f9e-7e0c-ec86db3e4400
* Content: [Use imported PFX certificates in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/certificates-imported-pfx-configure)
* Content Source: [memdocs/intune/protect/certificates-imported-pfx-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certificates-imported-pfx-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@OffColour  We’ll be updating content to add those parameter descriptions. Those are a great addition, thanks! I'm also adding a simple note about VPN per your comments. 

For the other items (IntendedPurpose),  the engineering team is looking at some changes to align the PowerShell code and UI, and to remove the reference to VPNs as they aren’t supported.

With the content updates I can make today on the way, I’ll close this GitHub issue. If the team removes or revises the underlying PowerShell or the UI to a degree hat content revisions are needed, they’ll loop me in to make those in a future content update.
