### ISSUE TITLE
April 2021 feature still listed under "in-development"

### ISSUE THREAD

**Issue by GenerAhl** [MicrosoftDocs/memdocs#2060]
Why is a feature that was implemented in April 2021 still listed on the "in-development" page?

https://docs.microsoft.com/en-us/mem/intune/fundamentals/in-development#plan-for-change-intune-moving-to-support-android-60-and-higher-in-april-2021

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66f915d1-8486-44dc-a605-280f979d6f9b
* Version Independent ID: 23c6b2c3-64c1-2df3-ad51-d9be083871a1
* Content: [In development - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/in-development)
* Content Source: [memdocs/intune/fundamentals/in-development.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/in-development.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @dougeby
* Microsoft Alias: **dougeby**

**Comment by msbemba** [comment]
@GenerAhl Thank you for your feedback. This document inherits data from another document called Important notices -https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new#notices

I see that both documents do not have the April 2021 update. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @GenerAhl Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
