### ISSUE TITLE
CA Policy compliant evaluation for Intune

### ISSUE THREAD

**Issue by dloder0** [MicrosoftDocs/memdocs#2068]
[Enter feedback here]
The page at https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/howto-conditional-access-policy-compliant-device has a note that says compliance is not evaluated for Intune Enrollment even if set.  This page (https://docs.microsoft.com/en-us/mem/intune/enrollment/multi-factor-authentication) says to not mark the compliance setting.  Which page is right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f28c4b3-8ccc-e353-2ead-65c4022b437a
* Version Independent ID: 643425fd-9969-6322-0735-2bffb125cefc
* Content: [Require multi-factor authentication for Intune device enrollment - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/multi-factor-authentication)
* Content Source: [memdocs/intune/enrollment/multi-factor-authentication.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/multi-factor-authentication.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@dloder0 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2548

Require device to be marked as compliant control does not block Intune enrollment. Once the author approves, the changes will be live.

Thanks
Sri
