### ISSUE TITLE
Imported PKCS profile

### ISSUE THREAD

**Issue by OffColour** [MicrosoftDocs/memdocs#207]
Does this support Imported PKCS profiles? I've gone through everything in https://docs.microsoft.com/en-us/mem/intune/protect/certificates-configure but when I get to setting up the VPN configuration it it says "No certificates available. Create one first."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3772dd31-1256-2aad-758a-395c40864a73
* Version Independent ID: 95193c13-5acd-f133-31e4-722a6cbd4929
* Content: [Add VPN settings to devices in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/vpn-settings-configure)
* Content Source: [memdocs/intune/configuration/vpn-settings-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/vpn-settings-configure.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@OffColour Good question. Certificates added using the **PKCS imported certificate** profile type aren't supported for VPN authentication. The article now includes this information. The changes should be live later today.

 Certificates added using the **PKCS certificates** profile type are supported in VPN profiles.

**Comment by OffColour** [comment]
Well that's just completely ruined my expectation being able to deploy VPN connections via Intune ☹️

**Comment by MandiOhlinger** [comment]
@tgakk @tycastMSFT For awareness, adding Lance and Tyler.

**Comment by tgakk** [comment]
@OffColour - Generally, customers create a unique authentication cert per device rather than share the same certificate across devices.  PFX import is mainly for S/MIME encryption certs where the encryption cert history is needed across devices to support decryption of email.  Can you provide more information on your scenario for using PFX import certs for VPN auth instead of SCEP or PKCS certs?

**Comment by OffColour** [comment]
Hi @tgakk,
We're a relatively small company of about 200 people. We don't have a CA infrastructure set up and simply haven't needed one.
With WFH coming to the fore we needed a VPN into Azure. We started with Azure AD sign in, but it causes too many problems when your users are on prem AD, i.e. if they forget their password we can't reset it for them as they can't connect to AD over the VPN until they've logged in.
Hence we need to move to Always On cert based. Self signed root and child certificates were perfectly adequate for what we needed.

**Comment by tgakk** [comment]
Hi @OffColour - I understand your scenario and the challenges with PKI.  This hasn't been a common ask for us.  I'd suggest opening a Uservoice item on microsoftintune.microsoft.com to build support for the feature.  In the meantime, the other option would be to spin up a simple CA for that, or investigate a managed PKI service from a partner.

**Comment by OffColour** [comment]
@tgakk Working through a CA now. Thanks for the feedback.

**Comment by davidenco** [comment]
Two years later and the issue hasn't been fixed. Any ideas?
