### ISSUE TITLE
add more capabilities into Device filters 

### ISSUE THREAD

**Issue by inpatilh** [MicrosoftDocs/memdocs#2070]
[Enter feedback here]

This is great feature; but needs some improvements; 

1. should have option to filter devices based on its primary user principal name.
2. should have option to filter devices if a primary user is member of another group.

This way we can filter out testers/pilot devices from the larger group of devices

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e458d85e-5eda-1421-a8eb-5775da1e8725
* Version Independent ID: 10a95675-5f3d-245b-c1f4-57f6faa97300
* Content: [Create filters in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/filters#feedback)
* Content Source: [memdocs/intune/fundamentals/filters.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/filters.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@inpatilh This is good feedback. The product feature PMs don't monitor these GitHub issues, as they're for doc updates. To submit product feedback, open the [article](https://docs.microsoft.com/mem/intune/fundamentals/filters), and select **Product Feedback** at the bottom.
