### ISSUE TITLE
Possibility to add more "Tokens used in the property list"?

### ISSUE THREAD

**Issue by hillihappo** [MicrosoftDocs/memdocs#2077]
Any change that the <Phone number> value found under Hardware (for Android/iOS/iPadOS devices) will be supported in the future?

(admin edit - adding metadata for assumed target article for proper link)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee33d638-3024-87d5-1b02-c4568478d1ce
* Version Independent ID: fe0f2aa3-b2dc-486a-4883-9c25ee361fe8
* Content: [Add app configuration policies for managed iOS/iPadOS devices - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-configuration-policies-use-ios#tokens-used-in-the-property-list)
* Content Source: [memdocs/intune/apps/app-configuration-policies-use-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-configuration-policies-use-ios.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@hillihappo Thank you for your feedback. This is the updated token type in the property list. If you would like to have a specific type in the property list, I'd recommend submitting feedback on our portal - https://feedbackportal.microsoft.com/

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@hillihappo  Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback
