### ISSUE TITLE
Mixing Win32 apps and LOB apps during Autopilot

### ISSUE THREAD

**Issue by ChadSimmons** [MicrosoftDocs/memdocs#2079]
Regarding the note about not mixing Win32 apps and LOB apps during Autopilot...

> Important
> When deploying Win32 apps using an installation file with the .msi extension (packaged in an .intunewin file using the Content Prep Tool), consider using Intune Management Extension. If you mix the installation of Win32 apps and line-of-business apps during AutoPilot enrollment, the app installation may fail.
> 

I've had multiple customers ask **WHY** this is the case but I've never found/seen a technical answer until Nathan Gardner explained in a forum:
> You cannot mix these app types as they both use the Trusted Installer service and if each app tries to use this service at the same time the install will fail and ESP will timeout.  In addition to this if you are deploying any MS Store apps to the same group make sure they are Offline version not online and they are configured for Device license not User.

Can we get the product team to confirm this technical detail then get that added to the documentation?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 872bb519-684a-aca1-dae9-280686f0dd37
* Version Independent ID: 500146ba-b836-9df2-af7b-caf8dc50d929
* Content: [Add a Windows line-of-business app to Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/lob-apps-windows)
* Content Source: [memdocs/intune/apps/lob-apps-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/lob-apps-windows.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@ChadSimmons Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2549

Once the changes are approved, the document will be live.

Thanks
Sri

**Comment by ChadSimmons** [comment]
closing based on published PR #2549

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ChadSimmons Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by ChadSimmons** [comment]
Thank you @msbemba
