### ISSUE TITLE
Disabled Features Keys

### ISSUE THREAD

**Issue by IvanShattuck** [MicrosoftDocs/memdocs#208]
The key listed on this page to disable the feature to offer to save passwords is listed as com.microsoft.intune.mam.managedbrowser.disableFeatures but this does not disable the feature. 
This key did not function for my org when we were trying to disable both the password and inprivate features. 
Changing the key to com.microsoft.intune.mam.managedbrowser.disabledFeatures also did not work and seemed to conflict with the other copy of the key for inprivate. 
After removing the listed key for password and adding the password value to the "disabled" key as "inprivate|password", both features were properly disabled. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a31e5a24-4f06-9e36-eacb-689bed95cd59
* Version Independent ID: ede9248e-1114-3e1a-9e80-34e5fe547707
* Content: [Manage Microsoft Edge for iOS and Android with Intune](https://docs.microsoft.com/en-us/mem/intune/apps/manage-microsoft-edge?source=docs#feedback)
* Content Source: [memdocs/intune/apps/manage-microsoft-edge.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/manage-microsoft-edge.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@IvanShattuck - Thanks for the feedback. I'm passing this information along to the product team and I'll confirm before updating the topic.
