### ISSUE TITLE
Include a note to clarify which domain to choose in a multi-domain forest

### ISSUE THREAD

**Issue by pnwnightowl** [MicrosoftDocs/memdocs#2081]
Please consider adding a Note after step 6 or 8 that provides clarification on which domain to use when there are multiple domains in the forest.  For example, if you have parent-child domains in a forest and you want to deploy Cloud PC's in an OU that is in the child domain, be sure to enter the child domain name, not the parent domain name for the AD Domain Name value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d58c1adf-aec3-d3a5-7b61-de59a39cec30
* Version Independent ID: 44149af3-1f86-1bfb-42b9-6a75af1086db
* Content: [Create on-premises network connections for Windows 365](https://docs.microsoft.com/en-us/windows-365/enterprise/create-on-premises-network-connection)
* Content Source: [windows-365/enterprise/create-on-premises-network-connection.md](https://github.com/MicrosoftDocs/memdocs/blob/master/windows-365/enterprise/create-on-premises-network-connection.md)
* Service: **cloudpc**
* Sub-service: ****
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Added the following: Cloud PCs that use the defined ANC will be joined to the domain and OU specified. Make sure that the domain selected is the desired domain for the computers to join
