### ISSUE TITLE
Clarify differences in section "ADE end user tasks"

### ISSUE THREAD

**Issue by OneUser1** [MicrosoftDocs/memdocs#2088]
The bullet points are so similar that it is not clear which point resembles which Intune configuration of the enrollment profile options. The description of the end user behaviour/task does only help a little and I need to compare the texts to guess which is the case I am looking for.

Example 1:
- Enroll with user affinity + Setup Assistant (legacy) + Company Portal app
- Enroll with user affinity + Setup Assistant (legacy) - Company Portal app

Example 2:
- Enroll with user affinity + Setup Assistant with modern authentication + Company Portal app
- Enroll with user affinity + Setup Assistant with modern authentication - Company Portal app

The only difference is the + / -. Does this mean the Company Portal app is install / not installed? If so, the description says something different..

Please clarify the bullet points. An idea could be to include screenshots of the settings or the settings name with its value.. thanks in advance.

(admin edit - adding metadata for assumed target article)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 778eac62-a9ea-604e-9d47-8c2a4ed5aa73
* Version Independent ID: a137faa0-8b25-f98f-4ca1-18393871923c
* Content: [iOS/iPadOS device enrollment guide for  Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/deployment-guide-enrollment-ios-ipados)
* Content Source: [memdocs/intune/fundamentals/deployment-guide-enrollment-ios-ipados.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/deployment-guide-enrollment-ios-ipados.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@OneUser1 Thank you very much for this feedback. We updated the article to include images (great idea). Changes should be live sometime today or tomorrow.

**Comment by OneUser1** [comment]
@MandiOhlinger Super, looks good! Thank you very much for the improvements.
