### ISSUE TITLE
Add note about SA /w Modern Auth is moving to become unsupported

### ISSUE THREAD

**Issue by p0shkar** [MicrosoftDocs/memdocs#2089]
You should add a note-box regarding "Setup Assistant with Modern Authentication for Automated Device Enrollment" is moving to become unsupported "on or shortly after December 10, 2021" as stated in MessageCenter message MC284343.

MC284343:
> Last spring, we announced public preview of Setup Assistant with Modern Authentication for iOS/iPadOS 13+ and macOS 10.15+ for Automated Device Enrollment (ADE), and in August, we made this enrollment flow generally available. This authentication method for ADE allows your organization to require authentication with Azure Active Directory (Azure AD) in an out-of-box experience (OOBE) during enrollment with Setup Assistant, prior to users accessing the home screen. You have the option to also require multi-factor authentication (MFA) depending on the settings in your Conditional Access policy. **On or shortly after December 10, 2021, we will be ending support for the older enrollment method that allows you to force run Company Portal in Single App Mode until authentication.**

> (...)  **you’ll want to move** to this new authentication prior to the December date. (...) The setting Run Company Portal in Single App Mode until authentication (Devices > iOS/iPadOS > Enrollment Program Tokens > select/create Profile > Management Settings) **will no longer be available after this change.**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd130267-c54b-41e3-d534-831d4a86bae6
* Version Independent ID: bdfa7eca-a356-3dde-7643-9a759f952007
* Content: [Enroll iOS/iPadOS devices by using ADE - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-ios#create-an-apple-enrollment-profile)
* Content Source: [memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@p0shkar Thank you for your feedback. Authenticate with Company Portal method was deprecated in December last year according to MC284343.

You likely have already moved to use Setup Assistant with modern authentication, however, if you have not, you’ll want to move to this new authentication. This does not affect existing enrolled devices.

Hope this helps!
Thanks
Sri
