### ISSUE TITLE
wrong configuration for device Type

### ISSUE THREAD

**Issue by MoahmedGebril** [MicrosoftDocs/memdocs#2099]
when creating a policy for Exchange Active Sync clients) step 6 
 - Under Assignments, select Conditions > Device platforms.
-  Under Configure, select Yes.
 - On the Include tab, select **Any device**, and then select Done.
this configuration block Microsoft team on windows 10 devices.
During configuration for  MFA policy for Modern Authentication clients also recommended in step 6 , we see the same configuration(Any device).
but when we try to save it we get a warning that MAM policy can only be applied to Android or IOS platforms 
this configuration need to be changed in the article to advise choosing (android and IOS) and not any device as described in article

(admin edit - adding metadata for assumed target article for proper link)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 733b08c2-5666-0d9b-8e78-28fba3456a6f
* Version Independent ID: ab6a321b-d6c0-c301-8156-96ccfdd21192
* Content: [Tutorial - Protect Exchange Online email on unmanaged devices - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/tutorial-protect-email-on-unmanaged-devices#create-a-policy-for-exchange-active-sync-clients)
* Content Source: [memdocs/intune/protect/tutorial-protect-email-on-unmanaged-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/tutorial-protect-email-on-unmanaged-devices.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@MoahmedGebril Thank you for your feedback. we have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2551

Once the author approves, changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MoahmedGebril Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
