### ISSUE TITLE
New device owner when user data is not retained, duplicate AAD record

### ISSUE THREAD

**Issue by ssccaavvookk** [MicrosoftDocs/memdocs#210]
When doing a Fresh Start, not retaining user data, and having a different user take the device results in a duplicate entry being made in AAD with the previous entry destined to become stale. Although unclear the root cause, it also results in unpredictable issues with apps not deploying, conditional access compliance checks failing despite being compliant, and more. These issues do not present themselves when the device is deleted from AAD after a fresh start but before a new owner takes over. Is there a reason why the AAD device is kept for non-BYOD devices? Is there a best practice for using this while changing users that can be documented?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d84711c-d9ca-95f2-1ed2-2f74e2c0ed7b
* Version Independent ID: aa151613-1d88-bf38-96fe-9bd2e19bae4d
* Content: [Reset Windows 10 devices with Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/remote-actions/device-fresh-start#feedback)
* Content Source: [memdocs/intune/remote-actions/device-fresh-start.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/remote-actions/device-fresh-start.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
(7180642)

**Comment by ErikjeMS** [comment]
Repinged PM...

**Comment by ErikjeMS** [comment]
The documentation team hasn’t been able to find an answer for this issue. If this is still an issue for you can try any of the following: 
- Open a support ticket by following the steps here: [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support). 
- Post on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.   
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.   
 I'm closing this issue as there's nothing actionable for docs at this time.
