### ISSUE TITLE
Capabilities by enrollment method updates

### ISSUE THREAD

**Issue by ChadSimmons** [MicrosoftDocs/memdocs#2102]
Regarding **Capabilities by enrollment method**

Update or add a clarification that the **Ability to run PowerShell scripts** for GPO enrolled Windows devices should work.

Add the **Win32 Apps** capability since it is tied directly to the IME like PowerShell is.

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0661ead-7e0e-08c0-212e-80f810fe1734
* Version Independent ID: d0ab8fec-c7e7-65f4-e6ff-75f3653ecd4e
* Content: [Intune enrollment method capabilities for Windows devices - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/enrollment-method-capab)
* Content Source: [memdocs/intune/enrollment/enrollment-method-capab.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/enrollment-method-capab.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ChadSimmons Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
