### ISSUE TITLE
Latest iOS Company portal app version supported

### ISSUE THREAD

**Issue by maiwa** [MicrosoftDocs/memdocs#2105]
[In this doc](https://docs.microsoft.com/en-us/mem/intune/user-help/install-a-new-version-of-the-company-portal-app#update-on-ios-device) there is a statement as below.

`[!NOTE] The minimum supported version of the iOS Company Portal app is v4.16.0. If you are running v4.14.1 or below, you will be prompted for an update at login.`

I think the version mentioned there is old as iOS 13 is the current minimum supported iOS version. Could you please check the minimum supported app version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a38eb4e-ff5e-2d73-a85f-73e9d2b3a541
* Version Independent ID: c49e17c5-9565-87f2-6e4f-2f099ca18329
* Content: [How to update the Company Portal app](https://docs.microsoft.com/en-us/mem/intune/user-help/install-a-new-version-of-the-company-portal-app#feedback)
* Content Source: [memdocs/intune/user-help/install-a-new-version-of-the-company-portal-app.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/user-help/install-a-new-version-of-the-company-portal-app.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @maiwa Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
