### ISSUE TITLE
Include WSUS content share as a practical scenario to download content from 

### ISSUE THREAD

**Issue by merlinfrombelgium** [MicrosoftDocs/memdocs#211]
About this:

> **Download software updates from a location on the local network:** Select this setting to download the software updates from a local directory or shared folder. This setting is useful when the computer that runs the wizard doesn't have internet access. Any computer with internet access can preliminarily download the software updates. Then store them in a location on the local network that's accessible from the computer that runs the wizard.

I just learned today, after 11 years of working with ConfigMgr, that you can enter the WsusContent share in this path. The above documentation led me to understand that one would have to organize the software update content somehow, in an undocumented manner. It's a feature I therefore never used until today. As a work-around to avoid a known issue with ADRs not bypassing proxy as they should when fetching (3rd party content) on the LAN.

I suggest to include the example of using "\\servername\WsusContent" as the network location. If I would rewrite it, this is what it would read:

> **Download software updates from a location on the local network:** Select this setting to download the software updates from a local directory or shared folder. This setting is useful when the computer that runs the wizard doesn't have internet access. Any computer with internet access can preliminarily download the software updates. Then store them in a location on the local network that's accessible from the computer that runs the wizard. Another scenario could be when downloading content that is published through SCUP or a third party patching solution. The WSUS content share can be entered as the network location to download from, such as `\\server\WsusContent`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c904bbcd-1551-d6a8-16e6-a0950202df5c
* Version Independent ID: 0ba1218c-c28a-4aa1-2d01-ee9212da593b
* Content: [Automatically deploy software updates - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/sum/deploy-use/automatically-deploy-software-updates)
* Content Source: [memdocs/configmgr/sum/deploy-use/automatically-deploy-software-updates.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/sum/deploy-use/automatically-deploy-software-updates.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
@merlinfrombelgium I agree. I'm putting your suggestion in with only some minor style edits.
