### ISSUE TITLE
Direct Enrollment with apple configurator

### ISSUE THREAD

**Issue by Xtraim** [MicrosoftDocs/memdocs#2110]
in this page : https://docs.microsoft.com/en-us/mem/intune/fundamentals/deployment-guide-enrollment-macos

it is written in the note that there is no enrollment by profile apple configurator that it is an error that will be corrected. Outside here the article specifies that one can do it. Who is right?
![image](https://user-images.githubusercontent.com/48596203/137748030-0599c65a-1fd4-4019-8171-d3d4a59dbede.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93802f93-2259-e9d7-1d76-874cadf181c2
* Version Independent ID: c0a958ae-f00c-7b9e-7301-177a9480b966
* Content: [Use Direct Enrollment for macOS devices - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-direct-enroll-macos)
* Content Source: [memdocs/intune/enrollment/device-enrollment-direct-enroll-macos.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/device-enrollment-direct-enroll-macos.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@Xtraim Thank you for your feedback. The Note has been removed as this was fixed in the next release.

Hope this helps!

Thanks
Sri
