### ISSUE TITLE
Link needs to be updated

### ISSUE THREAD

**Issue by rconiv** [MicrosoftDocs/memdocs#2113]
Under the list of different ways to get InTune, the Azure link goes to a link has changed, go to https://endpoint.microsoft.com, and update your bookmarks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4449a43-c48c-ab8f-90af-03d43ef42467
* Version Independent ID: 3f29a46d-4349-140f-f0f6-8107a5dd14e4
* Content: [What is Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/what-is-intune)
* Content Source: [memdocs/intune/fundamentals/what-is-intune.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/what-is-intune.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @dougeby
* Microsoft Alias: **dougeby**

**Comment by yogkumgit** [comment]
@rconiv Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by rconiv** [comment]
Does it take a while for the change to propagate?  If I go to https://docs.microsoft.com/en-us/mem/intune/fundamentals/what-is-intune the issue of when I click on the link at As a stand-alone [Azure service](https://go.microsoft.com/fwlink/?linkid=2090973) it takes me to the page has moved, change your links to Our new home is the Microsoft Endpoint Manager admin center. (https://endpoint.microsoft.com)
