### ISSUE TITLE
List of required URLs for proxy configuration

### ISSUE THREAD

**Issue by cvoigt** [MicrosoftDocs/memdocs#212]
I'm severely lacking a documentation of which URLs/IPs need to be accessed by the Intune Connector for AD (UI and Windows Service).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1546e07f-4168-140d-508e-bf7fcb3661bb
* Version Independent ID: e1deb787-f2b9-b024-e921-68f6b0d5d4cb
* Content: [Configure proxy settings for the Intune Connector for Active Directory](https://docs.microsoft.com/en-us/mem/intune/enrollment/autopilot-hybrid-connector-proxy)
* Content Source: [memdocs/intune/enrollment/autopilot-hybrid-connector-proxy.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/autopilot-hybrid-connector-proxy.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @master11218
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@cvoigt The connector requires the same endpoints as Intune, which you can find here: https://docs.microsoft.com/en-us/mem/intune/fundamentals/intune-endpoints. Thanks!
