### ISSUE TITLE
Windows 10 Support for Remote Lock

### ISSUE THREAD

**Issue by aydeisen** [MicrosoftDocs/memdocs#2123]
In the document, it states:
> Remote lock isn't supported for:
>  - Windows 10 desktop

With the varying notes in other pages under the "Remote Actions" topic stating the termination of support of Windows 8.1 Mobile and Windows 10 Mobile devices, I interpreted `Windows 10 desktop` to mean "not the mobile operating system".  I do not interpret it to mean "a desktop chassis type of computer"

So, while I know it's not quite the same thing, if I look in the Find my device portal of my Microsoft account, I do see that it is possible to Remotely Lock my Surface Pro 4, but not my Dell XPS Desktop.  I assume that Microsoft uses their own technology, even of the backend of the personal accounts, and therefore assume that this feature is backed by a Microsoft-hosted version of Intune.

Given the above, is there any criteria for Intune where Remote Lock _is_ supported on a Windows 10 device?  For example, is it only supported on Surface devices?  Is it only supported when Microsoft PIN Reset Service is registered with Azure AD, and Windows Hello for Business is enabled?  Is it actually checking the device chassis type to determine whether the feature is supported?

Thank you in advance for your response to these questions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c79f5e46-0615-682c-0368-5a14cfa738e7
* Version Independent ID: 08094776-efc7-d7b1-0b82-0aee1dac5634
* Content: [Lock devices with Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/remote-actions/device-remote-lock)
* Content Source: [memdocs/intune/remote-actions/device-remote-lock.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/remote-actions/device-remote-lock.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by msbemba** [comment]
@aydeisen Thank you for your feedback.  I have got a confirmation that the Remote lock device action in Intune isn’t supported for Windows 10 desktop and Windows 11 desktops. The option to remotely lock and reset passcode device actions are disabled or greyed out for Windows OS in Intune.

However, you can post the questions about the criteria for Intune (remote lock on windows device) in our feedback portal and get the answers directly from our Product/developer team.

Link for main feedback portal - https://feedbackportal.microsoft.com/

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @aydeisen Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
