### ISSUE TITLE
Missing params

### ISSUE THREAD

**Issue by emarana** [MicrosoftDocs/memdocs#2125]
Hi, 

For "Unicast responses to multicast broadcasts required" in the firewall domain profile are missing parameters and default value recommended.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10ff4382-415c-4e80-e958-3bd77252fe2d
* Version Independent ID: 398a5b4b-e8bd-1f7d-ae30-38d812daf90d
* Content: [Intune security baselines settings for Microsoft Defender for Endpoint - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/security-baseline-settings-defender-atp?pivots=atp-december-2020#microsoft-defender)
* Content Source: [memdocs/intune/protect/security-baseline-settings-defender-atp.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/security-baseline-settings-defender-atp.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@emarana    Thanks for this submission, which unfortunately fell off our radar for some time.  I've now submitted the content update to add those missing details, which should publish later today.   Like the private and public firewall profiles, the default is *Yes*, with an option to not configure (not manage) this setting through that baseline instance.
