### ISSUE TITLE
Scope Tags Correction

### ISSUE THREAD

**Issue by PrajwalDesai** [MicrosoftDocs/memdocs#2127]
While creating a Windows Health Monitoring profile in Intune, there is no option to add Scope tags. Please check and rectify.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c822884d-e84d-01fa-f7ba-503e08437dd8
* Version Independent ID: 8774dbd5-d8bc-e1c9-99cc-adca3e640423
* Content: [Create a Windows Health Monitoring profile in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/configuration/windows-health-monitoring?source=docs)
* Content Source: [memdocs/intune/configuration/windows-health-monitoring.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/windows-health-monitoring.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@PrajwalDesai You are correct. It's removed, and the changes should be live sometime tomorrow. In the future, it'd be great if you created a pull request for changes like this. We appreciate the help.
