### ISSUE TITLE
Group Change for 'Synchronize Software Updates' in 1910 Current Branch

### ISSUE THREAD

**Issue by OftKilted** [MicrosoftDocs/memdocs#213]
This location appears to have changed in the Current Branch release and  number 3 in https://docs.microsoft.com/en-us/mem/configmgr/sum/get-started/synchronize-software-updates#manually-start-software-updates-synchronization appears to be incorrect.

"On the **Home** tab, in the **Create** group, click **Synchronize Software Updates**. Click **Yes** in the dialog box to confirm that you want to initiate the synchronization process."

Should be "On the **Home** tab, in the **All Software Updates** group, click **Synchronize Software Updates**. Click **Yes** in the dialog box to confirm that you want to initiate the synchronization process."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34802da0-5f77-fc77-d379-c4dc794b5435
* Version Independent ID: fff11161-e7da-1190-9109-91cf01c404df
* Content: [Manage software updates synchronization - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/sum/get-started/synchronize-software-updates#manually-start-software-updates-synchronization)
* Content Source: [memdocs/configmgr/sum/get-started/synchronize-software-updates.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/sum/get-started/synchronize-software-updates.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
@OftKilted good catch! Changing this now.
