### ISSUE TITLE
Trusted Network Detection only working for Domain-Joined Windows Devices

### ISSUE THREAD

**Issue by wbach82** [MicrosoftDocs/memdocs#2130]
[Enter feedback here]

With AzureAD Joined devices Trusted Network Detection (TND) won't work... i.e. VPN Connection won't disconnect in corporate networks. It looks like TND is only working for AD Domain Joined Devices. Please evaluate and clarify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e16582-5730-9f22-2ced-686fc074d5c0
* Version Independent ID: b334cc28-f6ed-103f-3770-4cddb42e666c
* Content: [Windows 10 VPN settings in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/configuration/vpn-settings-windows-10)
* Content Source: [memdocs/intune/configuration/vpn-settings-windows-10.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/vpn-settings-windows-10.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by wbach82** [comment]
@MandiOhlinger any updates please?

**Comment by MandiOhlinger** [comment]
@wbach82 Hey - We're not aware of this limitation. We suggest working with the support team for a possible cause. If they find something we should document, then they can loop me in.
