### ISSUE TITLE
Download RDP Client App

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/memdocs#2132]
There is no download app section on the target page listed

_Download App page on www.microsoft.com/windows-365?rtc=1._

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7d87bdd-2e11-2610-a712-d4ea3f14274f
* Version Independent ID: ee8ec646-dc82-27c9-4db6-9ea281c97e5c
* Content: [Accessing Cloud PCs](https://docs.microsoft.com/en-us/windows-365/enterprise/end-user-access-cloud-pc)
* Content Source: [windows-365/enterprise/end-user-access-cloud-pc.md](https://github.com/MicrosoftDocs/memdocs/blob/master/windows-365/enterprise/end-user-access-cloud-pc.md)
* Service: **cloudpc**
* Sub-service: ****
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM
37831285

**Comment by ErikjeMS** [comment]
Fixed
