### ISSUE TITLE
Misleading description for "Block app installations with elevated privileges"?

### ISSUE THREAD

**Issue by stromnessian** [MicrosoftDocs/memdocs#2137]
Surely the description for this setting must be wrong?  It's basically saying that the default of "Yes" opens up a security vulnerability.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f0f4d5d-fdd1-22e7-6372-9916b199209f
* Version Independent ID: caeb9f8b-30ad-7f02-4740-56522b2f9b1b
* Content: [Intune security baselines settings for Windows 10/11 MDM - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/security-baseline-settings-mdm-all)
* Content Source: [memdocs/intune/protect/security-baseline-settings-mdm-all.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/security-baseline-settings-mdm-all.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@stromnessian Thank you for your feedback. I was able to test this and below are the findings. This works as described in the document as well.

when we set the setting "Block app installations with elevated privileges" as yes, it will create a registry key "HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\Installer\AlwaysInstallElevated" with value 0 which means 
 it is disabled.

If you disable or do not configure this policy setting, the system applies the current user's permissions when it installs programs that a system administrator does not distribute or offer.

![image](https://user-images.githubusercontent.com/45987684/158417901-e817aaa5-6ca8-4feb-a182-3909e8b55406.png)

Hope this clarifies your question.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @stromnessian Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
