### ISSUE TITLE
What is a low/medium/high level threat?

### ISSUE THREAD

**Issue by DontNeedNoGit** [MicrosoftDocs/memdocs#2139]
I've read this page thorough and all that it says about the threat levels. For example a Low Threat Level means "The device is compliant if only low-level threats are present. " 

Okay, but what is a low-level threat? What is a medium-level threat? What is a high-level threat? How/what determines this? Is this Apple, is it Microsoft Defender? Something else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba42b876-3fa3-6af3-e2fe-ba04a184ab4a
* Version Independent ID: 810cac0b-b3c9-3cfd-c48d-89d0c1f59771
* Content: [Create a Mobile Threat Defense (MTD) device compliance policy with Microsoft Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/mtd-device-compliance-policy-create#to-create-an-mtd-device-compliance-policy)
* Content Source: [memdocs/intune/protect/mtd-device-compliance-policy-create.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/mtd-device-compliance-policy-create.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @DontNeedNoGit Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
