### ISSUE TITLE
Please clarify concept/section

### ISSUE THREAD

**Issue by ckssaas** [MicrosoftDocs/memdocs#214]
Hello,

I have found step 3 under "Create an Apple enrollment profile" very difficult to understand. I believe there is a typo (the word "target" should be replaced with "targeting"). I also believe this step is loaded with information that could be broken down into separate steps and possible broken out into their own sections with significant elaboration/background. It's a very confusing paragraph.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd130267-c54b-41e3-d534-831d4a86bae6
* Version Independent ID: bdfa7eca-a356-3dde-7643-9a759f952007
* Content: [Enroll iOS/iPadOS devices - Device Enrollment Program - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-ios#feedback)
* Content Source: [memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@ckssaas That paragraph is confusing! I'll pull out the tangential information into a separate section about AAD dynamic groups and reword it a bit. However, to fully understand the AAD dynamic group process, you'll need to visit the link in the paragraph. Thanks for pointing this out! You should see the change in a day or so.
