### ISSUE TITLE
Event ID from Intune Certificate Connector

### ISSUE THREAD

**Issue by simonkw2000** [MicrosoftDocs/memdocs#2140]
From the article, it mentioned that below EventID ranges will be generated under different certificate operation scenarios. Can we have a full list of event IDs so that we can put them into the monitoring tool? The objective is to capture the failure certificate operations in the connector so that the administrators can take necessary actions to remediate it. Thanks.

0001-0999 - Not associated with any specific scenario
1000-1999 - PKCS
2000-2999 - PKCS Import
3000-3999 - Revoke
4000-4999 - SCEP

https://docs.microsoft.com/en-us/mem/intune/protect/certificate-connector-overview#logging

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8cd9e78-0ae6-c0e4-f318-1e5a6ec816fc
* Version Independent ID: f50ddc5d-311a-5810-3361-4160b5bc5f4b
* Content: [Overview of Certificate Connector for Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/certificate-connector-overview)
* Content Source: [memdocs/intune/protect/certificate-connector-overview.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certificate-connector-overview.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by yogkumgit** [comment]
@Brenduns Please help us in resolving this issue. Thanks

**Comment by Brenduns** [comment]
Tracking by internal work item 13958578.

**Comment by Brenduns** [comment]
@simonkw2000   Following up on this ask, which I'm now tracking internally. If I'm able to get the expanded Event ID details, I'll seek to add those to the content. Because I'm tracking this internally, I'll close this issue submission, though it will still support communication back to you once I know more. 

Once I know if that's possible, being done, or not something we can provide, I'll follow up with you again via this Issue.

**Comment by Brenduns** [comment]
@simonkw2000   The product group was able to provide some additional details for the event IDs, which I've added to the docs. That should show up in the live docs in a day or so.
