### ISSUE TITLE
'Box' is now available as a managed location for 'Allow user to save copies to selected services'

### ISSUE THREAD

**Issue by maiwa** [MicrosoftDocs/memdocs#2144]
Now 'Box' is available as a managed location for 'Allow user to save copies to selected services'
Please update the doc to reflect the new option. This can be a public preview feature.
(doc for Android) https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policy-settings-android#data-protection
(doc for iOS)) https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policy-settings-ios#data-protection
(doc for What's new) https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new

![image](https://user-images.githubusercontent.com/25226052/138987289-ed59a3db-4352-4369-8909-e1a647d753c8.png)

(admin edit: adding metadata for at least one of the articles for linking and tracking)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 521e26fd-bb00-1174-b238-a1c445140cd6
* Version Independent ID: 21341639-85f8-2f94-1834-59cb778bd21b
* Content: [Android app protection policy settings - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policy-settings-android#data-protection)
* Content Source: [memdocs/intune/apps/app-protection-policy-settings-android.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-protection-policy-settings-android.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@maiwa Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2554

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @maiwa Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
