### ISSUE TITLE
Grace Period value in Computer Agent settings cannot be set to "yes"

### ISSUE THREAD

**Issue by AquinoN** [MicrosoftDocs/memdocs#215]
Document states "If you want to give users more time to install required application or software update deployments beyond the deadline, set this option to Yes." but the value is an integer between 1 and 120.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c666f0e-89a1-dbe2-af7d-700a46aeea61
* Version Independent ID: 774f99b8-9403-1c77-abe5-54934f0d2f71
* Content: [Client settings - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/deploy/about-client-settings#feedback)
* Content Source: [memdocs/configmgr/core/clients/deploy/about-client-settings.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/deploy/about-client-settings.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @AquinoN for the feedback. Looks like the second paragraph covers the revised values, but we missed adjusting the intro sentence. Will fix that now, change should publish later today. 😄
