### ISSUE TITLE
Cannot change device category for Android Full Managed

### ISSUE THREAD

**Issue by sdaitech** [MicrosoftDocs/memdocs#2154]
[Enter feedback here]

If is a known issue to change device category for Android fully managed please add it on the article on Further Information or a Known issue section should be and include other issue if they are.

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a205db9e-c21f-b505-b5e9-d54fe44ececb
* Version Independent ID: a85d08c2-8ef1-fcd4-52de-f74ea8f41124
* Content: [Categorize devices into groups in Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-group-mapping)
* Content Source: [memdocs/intune/enrollment/device-group-mapping.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/device-group-mapping.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@sdaitech Thank you for your feedback. Changing the Device category on Android devices ((Corporate-owned, fully managed user) after enrollment is not a known issue.

If this is still an issue, I'd recommend you to contact Microsoft support via the need help section on the Admin center.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @sdaitech Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
