### ISSUE TITLE
Missing Baseline

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/memdocs#216]
This session at Ignite https://myignite.techcommunity.microsoft.com/sessions/83532 showed an baseline for Office 365, what happened to that? how come it is not described on this page or available in my tenant?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c553157-31cf-faf9-0b4c-00f1a56f0545
* Version Independent ID: c91b6b7b-3264-f0f7-688e-baac0ce3a718
* Content: [Use security baselines in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/security-baselines)
* Content Source: [memdocs/intune/protect/security-baselines.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/security-baselines.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@deangross  We aren't able to provide insight as to when future baselines will release. I expect the product group is eager to get that released given their announcement at Ignite.  For now, I recommend keeping an eye on our [In Development](https://docs.microsoft.com/mem/intune/fundamentals/in-development) article where we announce what’s on the way (when a feature or update has a firm release expectation), and the [What’s new]( https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new) article where we’ll announce those new features or updates once they are available.
