### ISSUE TITLE
Disable Catch Up Full/Quick Scan values

### ISSUE THREAD

**Issue by CharyMora** [MicrosoftDocs/memdocs#2161]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b84f6130-b993-bd26-0147-29748c3b7449
* Version Independent ID: 231c5984-ee21-059b-22d4-21b2f009124e
* Content: [Windows Antivirus policy settings for Microsoft Defender Antivirus for Intune](https://docs.microsoft.com/en-us/mem/intune/protect/antivirus-microsoft-defender-settings-windows)
* Content Source: [memdocs/intune/protect/antivirus-microsoft-defender-settings-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/antivirus-microsoft-defender-settings-windows.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@charyMora  Thanks for this submission.  While it can be confusing, this is an issue with the Defender configuration service provider (CSP) for this setting, for which the Intune UI is aligned in intent, if not the _exact_ labels.  I can’t speak to what the PowerShell module invokes as Intune’s UI aligns ultimately to the underlying CSP.  

- Both the name of the setting in the Intune UI, and the  name of the CSP from Defender are named in the form of   ‘_Disable <type> Scan’._  

- The CSP uses a value of **0** to mean **Enable**, which the CSP states will _turn on_ the scan.  This isn’t the CSP default. The default is to not enable but to _Disable_, which turns off the scan - which is the stated intent of the CSP.   I think most folks would agree that isn’t intuitive.

- The Intune UI uses a value of **Yes** (which aligns to the CSPs value of Enable) to also turn on the scan.  Intune uses **No** or **Not configured** (the setting default) which aligns to the CSPs default of _Disabled_ and its description – which results in the scan being enabled. 

So, unfortunately, while it might be confusing, this issue starts and is driven by the Defender CSPs format.  The docs align to the Intune UI, which in this case matches the CSP from Defender. 

If you find that the Defender CSP and the PowerShell module are configured or operate differently, then please open a support issue with Defender to investigate.
