### ISSUE TITLE
Disable Catch Up Scan values 

### ISSUE THREAD

**Issue by eyveree** [MicrosoftDocs/memdocs#2162]
The description of the two values in Disable catch up scans are inverted
 
No - The setting is disabled. Device users can't change this setting.
Yes - Catch-up scans for scheduled full/quick scans are enforced and the user can't disable them. If a computer is offline for two consecutive scheduled scans, a catch-up scan is started the next time someone signs in to the computer. If there's no scheduled scan configured, there will be no catch-up scan run. Device users can't change this setting.
 
The expected behavior is:
when set to "Yes" the computer does not run catch-up scans for scheduled full/quick scans.
and, when set to "No" after the computer misses two scheduled full scans, Windows Defender runs a catch-up scan the next time someone logs on to the computer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b84f6130-b993-bd26-0147-29748c3b7449
* Version Independent ID: 231c5984-ee21-059b-22d4-21b2f009124e
* Content: [Windows Antivirus policy settings for Microsoft Defender Antivirus for Intune](https://docs.microsoft.com/en-us/mem/intune/protect/antivirus-microsoft-defender-settings-windows)
* Content Source: [memdocs/intune/protect/antivirus-microsoft-defender-settings-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/antivirus-microsoft-defender-settings-windows.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@eyveree   Thanks for this submission.  While it can be confusing, this is an issue with the Defender configuration service provider (CSP) for this setting, for which the Intune UI is aligned in intent, if not the _exact_ labels.  What I mean is this: 

- Both the name of the setting in the Intune UI, and the  name of the CSP from Defender are named in the form of   ‘_Disable <type> Scan’._  

- The CSP uses a value of **0** to mean **Enable**, which the CSP states will _turn on_ the scan.  This isn’t the CSP default. The default is to not enable but to _Disable_, which turns off the scan - which is the stated intent of the CSP.   I think most folks would agree that isn’t intuitive.

- The Intune UI uses a value of **Yes** (which aligns to the CSPs value of Enable) to also turn on the scan.  Intune uses **No** or **Not configured** (the setting default) which aligns to the CSPs default of _Disabled_ and its descripiton – which results in the scan being enabled. 

So, unfortunately, while it might be confusing, this issue starts and is driven by the Defender CSPs format.  The docs align to the Intune UI, which in this case matches the CSP from Defender. 

To gain traction on a fix, I recommend submitting feedback to the Defender team to revise the presentation of the configuration service provider for device scans.  I've previously provided various feedback internally when settings, labels and results don't align, or could be considered counter-intuitive.
