### ISSUE TITLE
Include Windows 365 Administrator role in this page

### ISSUE THREAD

**Issue by BrianLe-Cerf** [MicrosoftDocs/memdocs#2163]
[Enter feedback here]

The "Role and identity requirements" Windows 365 requirements article mentions "Admin role: You must be an Intune Administrator in Azure AD to provision Cloud PCs." 

Now that the Windows 365 Administrator role has been released, we should replace "Intune Administrator" with it in this statement as it is the least privileged role.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dbf3611-f317-5455-990b-76d67549cd53
* Version Independent ID: 0f83b4c7-a653-1f7d-ec57-fb8933d984be
* Content: [Windows 365 requirements](https://docs.microsoft.com/en-us/windows-365/enterprise/requirements#role-and-identity-requirements)
* Content Source: [windows-365/enterprise/requirements.md](https://github.com/MicrosoftDocs/memdocs/blob/master/windows-365/enterprise/requirements.md)
* Service: **cloudpc**
* Sub-service: ****
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM
37830799

**Comment by ErikjeMS** [comment]
Added win365 admin to req.
