### ISSUE TITLE
Missing Internet Access for Vault

### ISSUE THREAD

**Issue by Shalzayed** [MicrosoftDocs/memdocs#2166]
[Enter feedback here]
for this Section 
https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/network/internet-endpoints#cmg-connection-point-for-cloud-services

under this table 

Type | Azure public cloud | Azure US Government cloud
-- | -- | --
Service name | <prefix>.<region>.cloudapp.azure.com | <prefix>.usgovcloudapp.net
Storage endpoint 1 | <prefix>.blob.core.windows.net | <prefix>.blob.core.usgovcloudapi.net
Storage endpoint 2 | <prefix>.table.core.windows.net | <prefix>.table.core.usgovcloudapi.net

it is missing CMG VMSS key Vault access URL  **https://prefix.vault.azure.net** 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a9e88a5-bc7d-4982-4564-ceea80bde0e7
* Version Independent ID: 817824fe-5b44-ebeb-75c4-9eeb2dfa13ce
* Content: [Internet access requirements - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/network/internet-endpoints)
* Content Source: [memdocs/configmgr/core/plan-design/network/internet-endpoints.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/network/internet-endpoints.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Shalzayed for the feedback. I'll double-check with engineering, but assume this is correct since I know vault is a component with the CMG deployment with virtual machine scale set, with a minimal associated cost (reference: https://docs.microsoft.com/mem/configmgr/core/clients/manage/cmg/cost#other-costs)
