### ISSUE TITLE
You cannot use the built-in application deployment of Microsoft Edge for workplace join computers

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/memdocs#217]
Hello,
About this Note: "You cannot use the built-in application deployment of Microsoft Edge for workplace join computers".
This is temporary or it is planned to change this in the future?
Asking because it makes important deployment scenario, if we deploy to All Users, then EDGE will be deployed only to Azure AD joined devices (company), if later on, this "Note" will be changed, then the "workplace join" (personal) devices will receive browser package too, this will be not good.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d593916-e493-8120-2f18-6c32c5cc31d0
* Version Independent ID: ca4bcd19-5783-8a69-6fd4-cc5270403411
* Content: [Add Microsoft Edge for Windows 10 to Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-windows-edge)
* Content Source: [memdocs/intune/apps/apps-windows-edge.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/apps-windows-edge.md)
* Service: **microsoft-intune**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
We have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. If you have continue to have questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

Please use the above channels if you don't already have a solution.
