### ISSUE TITLE
Where in the world is this  Configuration Manager console?

### ISSUE THREAD

**Issue by ok2play** [MicrosoftDocs/memdocs#2170]
[Enter feedback here]
Why is Microsoft so against putting links in their documentation? Where in the world is this  Configuration Manager console?

"In the Configuration Manager console, click Assets and Compliance."

With the million different consoles just give me a freaking link and with your many new consoles maybe try and keep your documentation up to date! In the "All Admin Centers nothing by the name of "Configuration Manager". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5323f58e-36b4-db69-23d8-c53a672b6cdc
* Version Independent ID: 80143b20-f40c-0db2-5db5-3b2819579237
* Content: [Endpoint Protection antimalware policies - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/protect/deploy-use/endpoint-antimalware-policies#exclusion-settings)
* Content Source: [memdocs/configmgr/protect/deploy-use/endpoint-antimalware-policies.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/protect/deploy-use/endpoint-antimalware-policies.md)
* Product: **configuration-manager**
* Technology: **configmgr-protect**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @ok2play, sorry for your frustration. This article (and everything under docs.ms/mem/configmgr) is for the on-premises enterprise product Microsoft Endpoint Configuration Manager. Most of this documentation, and the referenced console, is for IT administrators that have installed the Configuration Manager server. For more information, start with [What is Configuration Manager?](https://docs.microsoft.com/mem/configmgr/core/understand/introduction).

I'm going to close this issue as I don't think there's anything actionable for this specific article right now.

If you can let me know what you're trying to accomplish, I can try to help redirect.
