### ISSUE TITLE
Typo in last Note

### ISSUE THREAD

**Issue by garricko42** [MicrosoftDocs/memdocs#2171]
There is a typo in the last Note section of the page. The text reads:

If your configuring NDES to support the older

and should read:

If you're configuring NDES to support the older

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9107185-e6c7-b178-4e22-819797fe4880
* Version Independent ID: 1153b441-94f0-b471-52a2-3cf556c68581
* Content: [Configure infrastructure to support SCEP certificate profiles with Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/certificates-scep-configure#set-up-ndes)
* Content Source: [memdocs/intune/protect/certificates-scep-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certificates-scep-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@garricko42   Thanks for the heads up on that typo. I've submited an edit that will fix that in the live docs later today.
