### ISSUE TITLE
How do we refer to the product now... via initials?

### ISSUE THREAD

**Issue by ChadSimmons** [MicrosoftDocs/memdocs#2172]
Regarding 

> How do we refer to the product now?

Can we get an official guide/recommendation added for referring to Configuration Manager by its initials?  Is it...

- MECM (Microsoft Endpoint Configuration Manager) as the *full brand name* suggests
OR 
- MEMCM (Microsoft Endpoint Manager Configuration Manager)

I know hashtags are not product names #1099 but some guidance to try to tame the naming sprawl and speak the same language/terms would be really appreciated.

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0847f1f-4207-1380-4c05-0b9b9b4bf6c9
* Version Independent ID: 0dd578d7-5a6d-482d-04d6-cc2b29f5b9ec
* Content: [Microsoft Endpoint Configuration Manager FAQ - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/understand/microsoft-endpoint-manager-faq#how-do-we-refer-to-the-product-now-)
* Content Source: [memdocs/configmgr/core/understand/microsoft-endpoint-manager-faq.yml](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/understand/microsoft-endpoint-manager-faq.yml)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Same response as I gave in that prior feedback still applies 😉 
As this FAQ says, in space-constrained instances, **ConfigMgr** is the short version. IMO, that applies to hashtags.
