### ISSUE TITLE
HoloLens cannot exit kiosk mode

### ISSUE THREAD

**Issue by jimlam552** [MicrosoftDocs/memdocs#2173]
[Enter feedback here]
Hello, I set up the hololens kiosk mode.
I through the device portal page to open the kiosk mode to open an application each time login.
May I know any way to turn off the kiosk mode without connecting to the device portal page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba5d70f6-d84b-8955-9013-dafec5560869
* Version Independent ID: f89428e5-1510-b939-aefe-eb283e1af319
* Content: [Kiosk settings for Windows Holographic for Business in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/configuration/kiosk-settings-holographic)
* Content Source: [memdocs/intune/configuration/kiosk-settings-holographic.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/kiosk-settings-holographic.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by msbemba** [comment]
@jimlam552 Thank you for your feedback. I could not find a way to exit without connecting to the device portal page. I'd recommend you contact Support via the need help section on the admin center so that an engineer can assist you.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jimlam552 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
