### ISSUE TITLE
View what filter actually filters

### ISSUE THREAD

**Issue by chiners68** [MicrosoftDocs/memdocs#2174]
Would be good if there was the ability to view what he filter filters to before you apply it to a policy and its not correct. Similar to the preview updates in SCCM Automatic deployment rules where you can see what the filter will return before you commit to your rule.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e458d85e-5eda-1421-a8eb-5775da1e8725
* Version Independent ID: 10a95675-5f3d-245b-c1f4-57f6faa97300
* Content: [Create filters in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/filters)
* Content Source: [memdocs/intune/fundamentals/filters.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/filters.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@chiners68 :) It's available now.
