### ISSUE TITLE
Convert all targeted devices to Autopilot

### ISSUE THREAD

**Issue by nhogarth86** [MicrosoftDocs/memdocs#2175]
For the option "Convert all targeted devices to Autopilot", in the other page https://docs.microsoft.com/en-us/mem/autopilot/existing-devices it says that "Converting all targeted devices to Autopilot is not supported for transforming a hybrid Azure AD device into a Azure AD Autopilot device" but it does not say it on this page. Is this statement correct? If so, it would make sense to add it to this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9c44d0-d5d9-54af-b98e-0f33e73879af
* Version Independent ID: b67acfdf-2640-9376-c588-cb251078fb91
* Content: [Configure Autopilot profiles](https://docs.microsoft.com/en-us/mem/autopilot/profiles)
* Content Source: [memdocs/autopilot/profiles.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/profiles.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by aczechowski** [comment]
Based on https://github.com/MicrosoftDocs/memdocs/issues/2181#issue-1045033833, there's also a reference in https://docs.microsoft.com/en-us/mem/autopilot/automatic-registration

**Comment by aczechowski** [comment]
Thanks @nhogarth86 for the feedback. I checked with the PM:

> Yup, Nick’s right, it should say it there as well.  It can say that exact text in a note bubble.
