### ISSUE TITLE
Enhanced Security Configuration & Synced User

### ISSUE THREAD

**Issue by ertansimsek** [MicrosoftDocs/memdocs#2177]
Unfortunately, two information are missing in the documentation.
The "Enhanced Security Configuration" must be deactivated.
The Azure login must be performed from a synchronized user account.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 497646f6-1498-0647-cc54-b8013d71dca6
* Version Independent ID: e1fa4f5d-35b1-6fad-a4d2-3e8f5952230c
* Content: [Install the Certificate Connector for Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/certificate-connector-install)
* Content Source: [memdocs/intune/protect/certificate-connector-install.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certificate-connector-install.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@ertansimsek   Thanks for this content feedback.  This article has a fair number of steps - could you provide more details as to where those instructions fit? 

 Better yet, we encourage our users to contribute to docs when possible. If you'd like to do so, you can use the [Microsoft Docs Contributors Guide](https://docs.microsoft.com/en-us/contribute/) to get started. By submitting edits you see as needed directly, we'll be able to review, and sign-off on getting those published and accessible to others with less delay. You’ll also get added as a contributor to the article!

**Comment by ertansimsek** [comment]
@Brenduns I've edited the the pages where I think the information is missing.

**Comment by Brenduns** [comment]
The PR has been accepted and the update willl appear on-line later today.  Thankyou for that submission.
