### ISSUE TITLE
add note about button being greyed out if DP role is present on site server

### ISSUE THREAD

**Issue by davehop** [MicrosoftDocs/memdocs#2178]
Hi,
in the Prerequisites section of this doc, it is stated that the site server cannot have the Distribution Point role.  However, it is not stated that if the DP role is present, the Manage Content Library button will be greyed out in the ribbon or right-click menu.  Seems obvious, but this can be confusing to admins when trying to re-locate the content library.  

Please add a note at this point in the doc stating that if the DP role is present, the Manage Content Library Button will be greyed out until the role is removed.

it would also be great if the actual button in the console could have a tool tip or something when greyed out that says 'remove DP role in order to use this feature' or something along those lines.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8818c35b-2368-58dd-e0a9-7a72bb5df035
* Version Independent ID: 38fa8fde-6c09-909d-7817-e82cbd6a601a
* Content: [Configure a remote content library - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/hierarchy/remote-content-library)
* Content Source: [memdocs/configmgr/core/plan-design/hierarchy/remote-content-library.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/hierarchy/remote-content-library.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @davehop for the feedback. If you'd like to add that note yourself, I'll happily review and publish your contribution! 😉 https://docs.microsoft.com/mem/use-docs#contribute

As for the final point about tool tip, please file a frown from the console to get that suggestion to the engineering team. https://docs.microsoft.com/mem/configmgr/core/understand/product-feedback

**Comment by davehop** [comment]
Hey Aaron,
Cool I’ll dig in and do it!  Thanks!

Dave

**Comment by davehop** [comment]
Done and done. 😃

From: Dave Hoppert
Sent: Thursday, November 4, 2021 3:10 PM
To: MicrosoftDocs/memdocs ***@***.***>; MicrosoftDocs/memdocs ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [MicrosoftDocs/memdocs] add note about button being greyed out if DP role is present on site server (Issue #2178)

Hey Aaron,
Cool I’ll dig in and do it!  Thanks!

Dave
