### ISSUE TITLE
Confusing choice of words

### ISSUE THREAD

**Issue by svenhallauer** [MicrosoftDocs/memdocs#2179]
In this document we presently write:  "Approved apps: List the apps that users are allowed to install. **To stay compliant, users must not install other apps.** "  This is very confusing to users, because the work "compliant" implies a connection with the device compliance status, but this isn't the case for this feature as there is no connection to either the compliance policy or the device compliance status.  I suggest to instead use the work "conform" as in "**To conform with this requirement users must not install other apps.**"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce650df8-125e-4905-e54b-81cf4f893bbd
* Version Independent ID: b0764c62-d1a2-ea82-a7c4-98777e615b18
* Content: [macOS device settings in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-macos)
* Content Source: [memdocs/intune/configuration/device-restrictions-macos.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/device-restrictions-macos.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@svenhallauer Good call. I updated the text. Changes should be live sometime tomorrow. In the future, it'd be great if you created a pull request for doc changes like this. We appreciate the help.
