### ISSUE TITLE
Wrong section of the doc

### ISSUE THREAD

**Issue by svenhallauer** [MicrosoftDocs/memdocs#2180]
This bullet is listed under General in the section for all enrollment types:
"Block screenshots and screen recording: Device must be enrolled in Apple's Automated Device Enrollment (DEP). Yes prevents users from saving screenshots of the display. It also prevents the Classroom app from observing remote screens. When set to Not configured (default), Intune doesn't change or update this setting. By default, the OS might allow users to capture screenshots, and allows the Classroom app to view remote screens."

As is clear from the text itself this feature only applies to device that have been enrolled as corporate.  This needs to be moved one section lower in the doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce650df8-125e-4905-e54b-81cf4f893bbd
* Version Independent ID: b0764c62-d1a2-ea82-a7c4-98777e615b18
* Content: [macOS device settings in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-macos)
* Content Source: [memdocs/intune/configuration/device-restrictions-macos.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/device-restrictions-macos.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@svenhallauer That setting applies to all enrollment types, and doesn't require ADE. The text is removed, and the changed should be live later today. Thank you for questioning.
