### ISSUE TITLE
Built-in apps purpose

### ISSUE THREAD

**Issue by MaksimLyzaev** [MicrosoftDocs/memdocs#2182]
[Enter feedback here]
Hi,
It is not clear, why built-in apps should be used... Could you provide more information about difference between apps from store and built-in apps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5668fbc5-12af-7e46-f084-51f22ae83471
* Version Independent ID: dc7b6838-86d6-95ab-fedc-154c6572a040
* Content: [Guided scenario - Deploy Microsoft Edge for Mobile - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/guided-scenarios-edge)
* Content Source: [memdocs/intune/fundamentals/guided-scenarios-edge.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/guided-scenarios-edge.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@MaksimLyzaev Thank you for your feedback. Built-in apps provide a quicker way of deploying typical enterprise apps. The actual apps do not differ from the ones from the store. All built-in apps are eligible for app protection and configuration policies.

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit This can be closed.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @MaksimLyzaev Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
