### ISSUE TITLE
Tested VPN for Autopilot Hybrid Azure AD join

### ISSUE THREAD

**Issue by eogmau** [MicrosoftDocs/memdocs#2183]
Hi would likle to add one more VPN client that works for Hybrid Azure AD join to teh list of VPN clients that are known to be tested and validated.

FortiClient EMS
Allows to connect to VPN via Sign in option from loggon screen on Windows 10.

We have started our journay to Autopilot without knowing if our FortClient VPN will work for Hybrid Azure AD join scenarios.

Will be great if the list of VPN tested is kept updated.
https://docs.microsoft.com/en-us/mem/autopilot/windows-autopilot-hybrid#supported-byo-vpns

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f93dd93-e003-36fc-02d6-07166537d914
* Version Independent ID: 1b860d13-bcf5-50da-89f9-ee12ece6edb2
* Content: [Enrollment for hybrid Azure AD-joined devices - Windows Autopilot](https://docs.microsoft.com/en-us/mem/autopilot/windows-autopilot-hybrid)
* Content Source: [memdocs/autopilot/windows-autopilot-hybrid.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/windows-autopilot-hybrid.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by msbemba** [comment]
@eogmau Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2584

Once the author approves, the changes will be live.

Thanks
Sri
