### ISSUE TITLE
Conditional Access points to old documentation. 

### ISSUE THREAD

**Issue by Coopem16** [MicrosoftDocs/memdocs#2184]
Under the CA support:
https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-get-started#enable-your-ios-or-android-app-for-app-based-conditional-access
It points to old documentation. 
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-authentication-libraries

Can this be updated to the current supported libraries?
https://docs.microsoft.com/en-us/azure/active-directory/develop/ and point directly to the correct URL. 
Thanks
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f22dc1e-ad50-d834-2485-b3dad26972a7
* Version Independent ID: 5ef787c5-79cc-da5f-b4af-7647a84bd62d
* Content: [Get started with the Microsoft Intune App SDK](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-get-started)
* Content Source: [memdocs/intune/developer/app-sdk-get-started.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/developer/app-sdk-get-started.md)
* Service: **microsoft-intune**
* Sub-service: **developer**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@Coopem16 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2585

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Coopem16 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
