### ISSUE TITLE
Contradiction for iOS passcode requirements docs

### ISSUE THREAD

**Issue by evalerr** [MicrosoftDocs/memdocs#2187]
[Enter feedback here]

this is a contradiction in the help page for iOS passcode requirements  on the Authenticator wiki 

sett try a passcode that only contains numbers

Then says 

Set a passcode that contains  a mixture of numbers and alpha-numeric 

“

Passcode must only contain numbers. |Set a passcode that only contains numbers.

-- | --

Passcode must only contain alphanumeric characters. | Set a passcode that contains a mix of numbers and letters.

“

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 627e68f4-967b-9c95-abfe-da94f946af5a
* Version Independent ID: 2633cc4a-dc50-8f7a-9bf6-a3718a61928c
* Content: [Password requirements for Intune-enrolled devices](https://docs.microsoft.com/en-gb/mem/intune/user-help/password-does-not-meet-it-administrator-requirements)
* Content Source: [memdocs/intune/user-help/password-does-not-meet-it-administrator-requirements.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/user-help/password-does-not-meet-it-administrator-requirements.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @evalerr, thanks for reaching out to the Intune docs team. Could you clarify what your question is? The information provided on this page pertains to the Intune Company Portal app and is a list of all the requirements that your organization could enforce. It is up to your organization to decide which ones to actually enforce. Requirements will vary between different Microsoft apps.

**Comment by evalerr** [comment]
I’ve already shown you the exact wording that is wrong , read it and you see it’s wrong it’s contracting it’s own info in the few lines previous , can’t you see that ???

**Comment by evalerr** [comment]
If your not capable of proof reading your page , especially when I’ve highlighted the exact lines that are wrong / contradictory, then there is no hope for you.It wasn’t a question I had so I can’t clarify what  my question was  (again you failed to read my original email properly I don’t have time for thisYour loss if you can’t be arsed to read
    	L From: Laura Newsad ***@***.***>Sent: Thursday, November 11, 2021 1:06 amTo: MicrosoftDocs/memdocsCc: evalerr; MentionSubject: Re: [MicrosoftDocs/memdocs] Contradiction for iOS passcode requirements docs (Issue #2187) 
Hi @evalerr, thanks for reaching out to the Intune docs team. Could you clarify what your question is? The information provided on this page pertains to the Intune Company Portal app and is a list of all the requirements that your organization could enforce. It is up to your organization to decide which ones to actually enforce. Requirements will vary between different Microsoft apps.

**Comment by lenewsad** [comment]
Hi @evalerr, I'm sorry if I upset you and am happy to provide further clarification. _Kindly_ let me know if I'm still misunderstanding.  

I'm not sure what the Authenticator wiki is that you're referring to, so I'll address the article you left the comment on instead. This is a reference article that lists all of the possible password messages you could receive from Company Portal. For example, when your organization sets their password requirements, they could require that your "Passcode must only contain numbers" _or_ they could that your password "Passcode must only contain alphanumeric characters." They will not require both. The next step I'd recommend is to reach out to your IT suppot person for clarification about their password requirements.

**Comment by lenewsad** [comment]
The [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/), which outlines the expectations for community interactions in and around docs.microsoft.com, is designed to help "provide a welcoming and inspiring community for all." The content of this issue appears to be out of sync with the code of conduct, so we have closed it.
