### ISSUE TITLE
Some rules fail to migrate

### ISSUE THREAD

**Issue by ipetrocheilos** [MicrosoftDocs/memdocs#2188]
I am trying to use the tool, and it only managed to migrate 37 out of 88 rules. I get this error message

> Get-NetFirewallAddressFilter :Object not Found.
> At C:\Windows\system32\Intune-PowerShell-Management-master\Scenario Modules\IntuneFirewallRulesMigration\IntuneFirewallRulesMigration\Private\ConvertTo-IntuneFirewallRule-Helper.ps1
> :831 char:12
> + return Get-NetFirewallAddressFilter -AssociatedNetFirewallRule $A ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> + CategoryInfo : ObjectNotFound: (MSFT_NetAddressFilter:root/standardcimv2/MSFT_NetAddressFilter) [Get-NetFirewallAddressFilter], CimException
> + FullyQualifiedErrorId : MI RESULT 6,Get-NetFirewallAddressFilter
> 

I pulled the error xlsx and all the rules are failing with the error message

> Cannot bind argument to parameter 'addressRange' because it is null.

I don't know if the error is on the tool's end at the moment, I am still looking into it.

**Comment by aczechowski** [comment]
Thanks @ipetrocheilos for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post on [MEM forums](https://docs.microsoft.com/answers/products/mem). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://docs.microsoft.com/mem/get-support) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Customer Engineer or Technical Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
