### ISSUE TITLE
WMI device data

### ISSUE THREAD

**Issue by dongearhart** [MicrosoftDocs/memdocs#219]
It would be helpful to include the namespace the class is under. When manually troubleshooting a device with WMI Explorer or PowerShell there's no way to know if the class doesn't exist or if you're just looking in the wrong place.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f3684c-7f3f-ba2b-93eb-565640777161
* Version Independent ID: d666e010-2bea-3559-7dda-fb2e79bd8733
* Content: [Monitor co-management - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/comanage/how-to-monitor#feedback)
* Content Source: [memdocs/configmgr/comanage/how-to-monitor.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/comanage/how-to-monitor.md)
* Product: **configuration-manager**
* Technology: **configmgr-comanage**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @dongearhart for the feedback. We're checking with engineering to track it down.

**Comment by mestew** [comment]
@dongearhart it's in the site server's **ROOT\SMS\site_&lt;SITECODE>** namespace. I am adding that to the doc. Thanks much!

**Comment by dongearhart** [comment]
Thank you! It’s really appreciated.
