### ISSUE TITLE
Case Study missing or not available

### ISSUE THREAD

**Issue by MarianoAlegre** [MicrosoftDocs/memdocs#2191]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e969102-a98f-fcda-4bf3-7645f52a7896
* Version Independent ID: 92586124-bfff-4cde-3f07-cad9a61955f7
* Content: [Windows Autopilot with co-management - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/comanage/quickstart-autopilot)
* Content Source: [memdocs/configmgr/comanage/quickstart-autopilot.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/comanage/quickstart-autopilot.md)
* Product: **configuration-manager**
* Technology: **configmgr-comanage**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @MarianoAlegre for the feedback. It looks like several other case studies in that area aren't available anymore. Since the target site doesn't return a 404, our automatic tool didn't detect the failure. At this point I'll just remove the links.
