### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by matziq** [MicrosoftDocs/memdocs#2192]
There is a typo in https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/site-server-high-availability#remove-a-site-server-in-passive-mode

Where it says "The process to **remote** a site server in passive mode is the same as any site system role."
It should read "The process to **remove** a site server in passive mode is the same as any site system role."

Thanks!
John Rea

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4e5077b-89ed-62a1-8690-722a8cb49658
* Version Independent ID: 3fa4245d-27f9-5062-24aa-b5b1a9d38005
* Content: [Site server high availability - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/site-server-high-availability)
* Content Source: [memdocs/configmgr/core/servers/deploy/configure/site-server-high-availability.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/deploy/configure/site-server-high-availability.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @matziq for catching that. I'll get it fixed with another change I'm making elsewhere today.

Note: in the future, you can submit this sort of edit yourself. 😉 For more info, see https://docs.microsoft.com/mem/use-docs#contribute

**Comment by matziq** [comment]
I thought about that after I submitted it. I'll do that going forward.
Thanks, Aaron!
John
