### ISSUE TITLE
Publish a new public app for Google Play Store

### ISSUE THREAD

**Issue by PlayPratz** [MicrosoftDocs/memdocs#2194]
There is no mention of publishing new Public apps to the Google Play Store by using the Intune App Wrapping Tool. 

If there isn't a way, something along the lines of "There is no way of publishing a new Public app to the Play Store by using the Intune App Wrapping Tool" should be mentioned clearly. This is most likely the case because since August 2021, you can no longer publish APKs for new apps; only Android App Bundles (AABs) are allowed. However, Intune App Wrapping Tool does not support AABs.

However, if there is a way, it should be detailed in the document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f83f5455-d85e-e47b-867d-0e312a4d348c
* Version Independent ID: e91fef51-15df-3757-3ffd-ef7ec9cab7b5
* Content: [Wrap Android apps with the Intune App Wrapping Tool](https://docs.microsoft.com/en-us/mem/intune/developer/app-wrapper-prepare-android)
* Content Source: [memdocs/intune/developer/app-wrapper-prepare-android.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/developer/app-wrapper-prepare-android.md)
* Service: **microsoft-intune**
* Sub-service: **developer**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@PlayPratz Thank you for your feedback. We have added a note on the document that talks about this

If your input app is an Android App Bundle (.aab), you will need to convert it to an APK before using the Intune App Wrapping Tool. For details, see [Convert Android App Bundle (AAB) to APK](https://docs.microsoft.com/en-us/mem/intune/developer/app-wrapper-prepare-android#convert-android-app-bundle-aab-to-apk). 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @PlayPratz Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
