### ISSUE TITLE
Add "primary user" as column option in the "all devices" table

### ISSUE THREAD

**Issue by Derusi** [MicrosoftDocs/memdocs#22]
It would be useful if the newly added "primary user" could be shown in the "all devices" table.
Our company enrolls meeting room devices with a dedicated enroller-account, and we would like to simply add the room-specific Skype/Teams-account as primary user and have the overview of the assigned users in the table.

**Comment by ErikjeMS** [comment]
@Derusi Thanks for taking the time to provide feedback on Microsoft Intune! This is an interesting feature idea, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. See the [Microsoft Intune Feedback]( https://microsoftintune.uservoice.com/forums/291681-ideas). I'm closing this issue as there's nothing actionable for docs at this time.
