### ISSUE TITLE
AAD registered vs AAD joined

### ISSUE THREAD

**Issue by velden** [MicrosoftDocs/memdocs#220]
I think the first diagram and prerequisites are contradictory:

The diagram states for a Windows 10 device: 'AAD REGISTERED'
 
However the prerequisites state:
"Windows 10 devices must be joined to Azure AD. They can be either of the following types:
Hybrid Azure AD-joined, where the device is joined to your on-premises Active Directory and joined to your Azure Active Directory.
Azure AD-joined only. (This type is sometimes referred to as "cloud domain-joined")"

Registered is different from (hybrid) joined. https://docs.microsoft.com/en-us/azure/active-directory/devices/overview

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f61451a-aad4-f7c3-d52b-03e8422cccb2
* Version Independent ID: 5c80c81e-3da8-9d62-d9c4-23b0cf77bfe2
* Content: [Co-management for Windows 10 devices - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/comanage/overview#feedback)
* Content Source: [memdocs/configmgr/comanage/overview.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/comanage/overview.md)
* Product: **configuration-manager**
* Technology: **configmgr-comanage**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @velden, we had an issue on this previously, and I was working to track down the original source file for the diagram (originally created by someone else). I discovered that I can make a string change inside an SVG, so I'll take care of that this afternoon.

**Comment by velden** [comment]
Thank you @aczechowski for your swift reply. 

_For editing SVG files you could have a look at the free and open source editor Inkscape (inkscape.org)_
