### ISSUE TITLE
Update doc 

### ISSUE THREAD

**Issue by Selimachak** [MicrosoftDocs/memdocs#2200]
Based on this article https://docs.microsoft.com/en-us/mem/intune/apps/intune-management-extension
BYOD and device enrolled in GPO  are able to run script. Can you please update the doc accordingly.

thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0661ead-7e0e-08c0-212e-80f810fe1734
* Version Independent ID: d0ab8fec-c7e7-65f4-e6ff-75f3653ecd4e
* Content: [Intune enrollment method capabilities for Windows devices - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/enrollment-method-capab)
* Content Source: [memdocs/intune/enrollment/enrollment-method-capab.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/enrollment-method-capab.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Thank you for your contribution, @Selimachak. I'm verifying the change with the product team and then will update the article.

**Comment by msbemba** [comment]
@lenewsad Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2586

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Selimachak Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
