### ISSUE TITLE
request to update "Enrollment methods supported by DEM accounts" info

### ISSUE THREAD

**Issue by sufuruka** [MicrosoftDocs/memdocs#2202]
Hello Team,
I request to update "Enrollment methods supported by DEM accounts" info.
I asked MS dev team and they confirmed DEM account + AADJ senario is supportable.

It is marked as supported in the docs chart - Capabilities by enrollment method(https://docs.microsoft.com/en-us/mem/intune/enrollment/enrollment-method-capab?form=MY01SV&OCID=MY01SV#capabilities-by-enrollment-method), 
however the enrollment scenario is not listed in another doc below. 

Title: Enrollment methods supported by DEM accounts
URL: https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-manager-enroll#enrollment-methods-supported-by-dem-accounts

■ Adding phrase to the above Docs "Enrollment methods supported by DEM accounts"
DEM initiated via Azure AD join 
(or "automatic enrollment after Azure AD join")

If you have any good phrases, please proceed with it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7786d9c0-55b0-9bff-fc0a-f4ee70ee0615
* Version Independent ID: cf0c17a0-fdc7-e0af-db82-913e36d2ec7c
* Content: [Enroll devices using a device enrollment manager account - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-manager-enroll#enrollment-methods-supported-by-dem-accounts)
* Content Source: [memdocs/intune/enrollment/device-enrollment-manager-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/device-enrollment-manager-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by sufuruka** [comment]
Hi Team,
I would appreciate if you could confirm this request.

**Comment by msbemba** [comment]
@sufuruka Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2587

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @sufuruka Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
