### ISSUE TITLE
Create the client certificate template

### ISSUE THREAD

**Issue by nhogarth86** [MicrosoftDocs/memdocs#2206]
Hi, I think its misleading leaving the section "Create the client certificate template" included in the document. It should have the same note that is displayed in https://docs.microsoft.com/en-us/mem/intune/protect/certificates-scep-configure#certificates-and-templates that says "The following certificate is not used with the Certificate Connector for Microsoft Intune. This information is provided for those who have not yet replaced the older connector for SCEP (installed by NDESConnectorSetup.exe) with the new connector software." Otherwise it sounds like it is still needed for the new Intune Certificate Connector.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9107185-e6c7-b178-4e22-819797fe4880
* Version Independent ID: 1153b441-94f0-b471-52a2-3cf556c68581
* Content: [Configure infrastructure to support SCEP certificate profiles with Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/certificates-scep-configure)
* Content Source: [memdocs/intune/protect/certificates-scep-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certificates-scep-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@nhogarth86   Thanks for the feedback. I've submitted a content edit to add that note, and clarify the name of hte connector that the client certificate _was_ applicable to.   That should be live later today.
