### ISSUE TITLE
Where can one find clear information about which mobile device operating systems are required for App Protection?

### ISSUE THREAD

**Issue by 0fflineDocs** [MicrosoftDocs/memdocs#2209]
[Enter feedback here]
On this page I find a reference to a link but the target does not provide information about required operating systems for running App protection.
_"Before using this feature, make sure you meet the Outlook for iOS/iPadOS and Android requirements. "_

Here I can find information and a reference to the required Android version. https://docs.microsoft.com/en-us/mem/intune/fundamentals/supported-devices-browsers

But where is iOS/iPadOS stated?
Shouldn't this be crystal clear? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17955fd7-d652-8f0e-4446-00b8628d58cc
* Version Independent ID: 46755b3c-43a5-f5c9-0b74-ce2b7ede7d40
* Content: [App protection policies overview - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policy)
* Content Source: [memdocs/intune/apps/app-protection-policy.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-protection-policy.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@0fflineDocs Thank you for your feedback. I can find the details updated in the document after you reported the issue-https://docs.microsoft.com/en-us/mem/intune/fundamentals/supported-devices-browsers


Apple iOS 13.0 and later
Apple iPadOS 13.0 and later
macOS 10.15 and later

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @0fflineDocs Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
