### ISSUE TITLE
Nothing about Co-management

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/memdocs#221]
There is nothing about how SCCM's co-management functionality should be considered. Please provide some information about how this fits into the device management pictuer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65bf267f-ba37-dad4-532f-08d3acb67c97
* Version Independent ID: fbfd67d1-e138-b3e0-62ae-104b84968f7b
* Content: [Device management in Microsoft 365](https://docs.microsoft.com/en-us/mem/intune/fundamentals/what-is-device-management)
* Content Source: [memdocs/intune/fundamentals/what-is-device-management.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/what-is-device-management.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@DeanGross You're right. Thank you. We're updating this article to include co-management. The changes should be live in the next couple of days.
