### ISSUE TITLE
Intune network requirements checker

### ISSUE THREAD

**Issue by Martony78** [MicrosoftDocs/memdocs#2210]
Is there any way to easily check if the Intune network requirements are ok?
can we use use something like test-netconnection?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c9c3475-56d4-026b-349f-f9cbc258537c
* Version Independent ID: 9c6476ed-8a47-bcb4-dfbf-25ba305c3b24
* Content: [Network endpoints for Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/intune-endpoints)
* Content Source: [memdocs/intune/fundamentals/intune-endpoints.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/intune-endpoints.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by msbemba** [comment]
@Martony78 Thank you for your feedback.  I don't know of anything off-hand but this sounds like a really good idea to have one like https://testconnectivity.microsoft.com. These Design changes or new feature requests should be posted in our Main feedback portal: https://feedbackportal.microsoft.com/ so one of the dev/product team members will contact you.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@Martony78 Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.

**Comment by o-l-a-v** [comment]
I did not find any Microsoft Feedback on this, so I created it.

* https://feedbackportal.microsoft.com/feedback/idea/36f5aabb-80b5-ec11-a81c-000d3a7ce453
