### ISSUE TITLE
Issues connecting to Azure AD

### ISSUE THREAD

**Issue by freakynl** [MicrosoftDocs/memdocs#2211]
Hi,

during the configuration process I get an error "Can't connect securely to this page" at the 'Azure AD Sign In' step.

Now we've done some hardening on TLS ciphers, but not sure why it's causing this yet. The client only seems to offer:
![image](https://user-images.githubusercontent.com/3298106/141968436-1c38af50-dd51-4ae1-a917-d4e9db5e2f74.png)
as indicated by packet capture. Edge doesn't have issues connecting to https://portal.manage.microsoft.com on this 2019 server, IE does however. .NET is set to use system TLS stack and strongciphers (SchUseStrongCrypto & SystemDefaultTlsVersions).

So ran a scan against the site. It doesn't offer ECDHE-RSA-AES???-GCM-SHA???.

$ sslscan portal.manage.microsoft.com
Version: 2.0.10-static
OpenSSL 1.1.1k  25 Mar 2021

Connected to 52.138.193.149

Testing SSL server portal.manage.microsoft.com on port 443 using SNI name portal.manage.microsoft.com

  SSL/TLS Protocols:
SSLv2     disabled
SSLv3     disabled
TLSv1.0   enabled
TLSv1.1   enabled
TLSv1.2   enabled
TLSv1.3   disabled

  TLS Fallback SCSV:
Server does not support TLS Fallback SCSV

  TLS renegotiation:
Secure session renegotiation supported

  TLS Compression:
Compression disabled

  Heartbleed:
TLSv1.2 not vulnerable to heartbleed
TLSv1.1 not vulnerable to heartbleed
TLSv1.0 not vulnerable to heartbleed

  Supported Server Cipher(s):
Preferred TLSv1.2  256 bits  ECDHE-RSA-AES256-SHA384       Curve P-384 DHE 384
Accepted  TLSv1.2  128 bits  ECDHE-RSA-AES128-SHA256       Curve P-256 DHE 256
Accepted  TLSv1.2  256 bits  ECDHE-RSA-AES256-SHA          Curve P-384 DHE 384
Accepted  TLSv1.2  128 bits  ECDHE-RSA-AES128-SHA          Curve P-256 DHE 256
Accepted  TLSv1.2  256 bits  AES256-GCM-SHA384            
Accepted  TLSv1.2  128 bits  AES128-GCM-SHA256            
Accepted  TLSv1.2  256 bits  AES256-SHA256                
Accepted  TLSv1.2  128 bits  AES128-SHA256                
Accepted  TLSv1.2  256 bits  AES256-SHA                   
Accepted  TLSv1.2  128 bits  AES128-SHA                   
Preferred TLSv1.1  256 bits  ECDHE-RSA-AES256-SHA          Curve P-384 DHE 384
Accepted  TLSv1.1  128 bits  ECDHE-RSA-AES128-SHA          Curve P-256 DHE 256
Accepted  TLSv1.1  256 bits  AES256-SHA                   
Accepted  TLSv1.1  128 bits  AES128-SHA                   
Preferred TLSv1.0  256 bits  ECDHE-RSA-AES256-SHA          Curve P-384 DHE 384
Accepted  TLSv1.0  128 bits  ECDHE-RSA-AES128-SHA          Curve P-256 DHE 256
Accepted  TLSv1.0  256 bits  AES256-SHA                   
Accepted  TLSv1.0  128 bits  AES128-SHA                   

  SSL Certificate:
Signature Algorithm: sha384WithRSAEncryption
RSA Key Strength:    2048

Subject:  Portal.manage.microsoft.com
Altnames: DNS:m.manage.microsoft.com, DNS:fei.msub01.manage.microsoft.com, DNS:portal.fei.msub01.manage.microsoft.com, DNS:m.fei.msub01.manage.microsoft.com, DNS:fei.msub02.manage.microsoft.com, DNS:portal.fei.msub02.manage.microsoft.com, DNS:m.fei.msub02.manage.microsoft.com, DNS:fei.msub03.manage.microsoft.com, DNS:portal.fei.msub03.manage.microsoft.com, DNS:m.fei.msub03.manage.microsoft.com, DNS:fei.msub05.manage.microsoft.com, DNS:portal.fei.msub05.manage.microsoft.com, DNS:m.fei.msub05.manage.microsoft.com, DNS:fei.amsub0102.manage.microsoft.com, DNS:portal.fei.amsub0102.manage.microsoft.com, DNS:m.fei.amsub0102.manage.microsoft.com, DNS:fei.amsub0202.manage.microsoft.com, DNS:portal.fei.amsub0202.manage.microsoft.com, DNS:m.fei.amsub0202.manage.microsoft.com, DNS:fei.amsub0302.manage.microsoft.com, DNS:portal.fei.amsub0302.manage.microsoft.com, DNS:m.fei.amsub0302.manage.microsoft.com, DNS:fei.amsub0502.manage.microsoft.com, DNS:portal.fei.amsub0502.manage.microsoft.com, DNS:m.fei.amsub0502.manage.microsoft.com, DNS:fei.amsub0601.manage.microsoft.com, DNS:portal.fei.amsub0601.manage.microsoft.com, DNS:m.fei.amsub0601.manage.microsoft.com, DNS:Portal.manage.microsoft.com
Issuer:   Microsoft Azure TLS Issuing CA 06

Not valid before: Nov  2 20:47:38 2021 GMT
Not valid after:  Jan 31 20:47:38 2022 GMT

Presuming it's still running on server 2012 (R2) or something.

Can someone have a look at the cipher suites?

I'll try removing the hardening, not sure why it's not offering anything but ECDHE+GCM variants. There should be more enabled.

**Comment by freakynl** [comment]
Hardening had set the ciphersuites quite strict. This is mostly due to reduce what IIS offers, but it affects TLS clients using the Microsoft TLS stack as well (Edge apparently does not).

Have removed it for now. Most URLs that are accessed seem to offer ECDHE-RSA-GCM variants, but at least portal.manage.microsoft does not.

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Cryptography\Configuration\SSL\00010002]
"Functions"="TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_DHE_RSA_WITH_AES_256_GCM_SHA384,TLS_DHE_RSA_WITH_AES_128_GCM_SHA256"

**Comment by aczechowski** [comment]
Thanks @freakynl for taking the time to share this with the MEM documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post on [MEM forums](https://docs.microsoft.com/answers/products/mem). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://docs.microsoft.com/mem/get-support) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.

p.s. if your feedback is to suggest a change in the service, you can file [product feedback](https://feedbackportal.microsoft.com/feedback/forum/ef1d6d38-fd1b-ec11-b6e7-0022481f8472).
