### ISSUE TITLE
Missing details

### ISSUE THREAD

**Issue by IN-jwink** [MicrosoftDocs/memdocs#2213]
Documentation unclear if the Assignments of the policy set control all assignment or if the assignment of the policy set happens first and then the assignments of the items within the policy set (those that have assignments) then act as a second layer of application.

Guessing the first but not certain.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9efa1fad-ddb2-4f04-dc17-ddc7872df0d4
* Version Independent ID: 9be69699-ffb0-9fb3-ff1e-d1a4a9209589
* Content: [Policy sets - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/policy-sets)
* Content Source: [memdocs/intune/fundamentals/policy-sets.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/policy-sets.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@IN-jwink Thank you for your feedback. you are correct, assignments of the policy set to control all assignments. When you create a policy set, you create a single unit of assignment.

Hope this helps!

Thanks
Sri

**Comment by IN-jwink** [comment]
So the documentation has been disambiguated?  I haven’t checked yet.

**Comment by msbemba** [comment]
Yes, the document has been updated with the wordings "When you create a policy set, you create a single unit of assignment"

**Comment by msbemba** [comment]
@yogkumgit This can be closed.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @IN-jwink Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
