### ISSUE TITLE
Port 123 UDP/NTP for all hosts

### ISSUE THREAD

**Issue by MHimken** [MicrosoftDocs/memdocs#2218]
Hi everyone,

can you please clarify the following:
"Allow access to all hosts via port 80 (HTTP), 443 (HTTPS), and 123 (UDP/NTP)." - does this refer to time.windows.com alone? Surely it's not required to open 123 UDP/NTP in general to all hosts, but to that specific URL? This is also reflected [here](https://docs.microsoft.com/en-us/mem/autopilot/known-issues#windows-autopilot-device-provisioning-can-fail) and [here](https://social.technet.microsoft.com/wiki/contents/articles/54286.intune-network-ports-requirements.aspx)

Regards
Martin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82c5b872-c031-9ed9-c4cc-c8a1a8e93e0a
* Version Independent ID: ac837825-11e3-cf43-7516-0d94b496a59f
* Content: [Windows Autopilot networking requirements](https://docs.microsoft.com/en-us/mem/autopilot/networking-requirements)
* Content Source: [memdocs/autopilot/networking-requirements.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/networking-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by aczechowski** [comment]
Hi @MHimken, I think you're correct, I assume the same. But I want to verify with the feature team. (I'm also checking on the broad need for port 80...I would hope that most everything is HTTPS now, except for maybe CRLs or similar.)

**Comment by ajf8729** [comment]
While the page mentions "Allow access to all hosts via port 80 (HTTP), 443 (HTTPS), and 123 (UDP/NTP)" near the top, further done in the same page, under each section, it appears to describe specific hosts and port(s) required for each part to function. Perhaps the bit at the top part just needs to be clarified a bit more, or removed in favor of a reference table describing each URL, port, and direction needed to be allowed.
