### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by larsinus** [MicrosoftDocs/memdocs#222]
There is no information about the last TAB in the Co-Mgmt wizard; REPORTING.
We can sign in to Intune to add reporting but we don't say anything about what kind of information, which reports/where we can find the information.
The application we create in Azure AD is not mentioned here either. Where is it, what does it do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96f4b08d-966b-c023-b9df-cee774b1d4de
* Version Independent ID: 16bb8aae-2f24-0c77-f1c8-b59e93353174
* Content: [Enable co-management - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/comanage/how-to-enable)
* Content Source: [memdocs/configmgr/comanage/how-to-enable.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/comanage/how-to-enable.md)
* Product: **configuration-manager**
* Technology: **configmgr-comanage**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @larsinus for the feedback, we're checking on this

**Comment by aczechowski** [comment]
It's a preview-only feature that will soon be removed, it became obsolete with [tenant attach](https://docs.microsoft.com/mem/configmgr/tenant-attach/).
