### ISSUE TITLE
Please add some info about the supported ADK for Windows 10 21H2

### ISSUE THREAD

**Issue by bccgeorge** [MicrosoftDocs/memdocs#2222]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 670cd640-4b94-a886-8c62-76bf390ea259
* Version Independent ID: d902e190-3813-e8ae-a93d-f1bc3785a20b
* Content: [Support for the Windows ADK - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/configs/support-for-windows-adk)
* Content Source: [memdocs/configmgr/core/plan-design/configs/support-for-windows-adk.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/configs/support-for-windows-adk.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @bccgeorge, see the following note from this blog post: https://techcommunity.microsoft.com/t5/windows-it-pro-blog/what-s-new-for-it-pros-in-windows-10-version-21h2/ba-p/2971409

> As Windows 10, version 21H2 shares a common core and an identical set of system files with version 2004, 20H2, and 21H1, the Windows Assessment and Deployment Kit (Windows ADK) for Windows 10, version 2004 and the Windows PE add-on for the Windows ADK, version 2004 already work with version 21H2 and do not need to be updated.
