### ISSUE TITLE
Updates Needed to clarify compatibility. 

### ISSUE THREAD

**Issue by HoutzOfGit** [MicrosoftDocs/memdocs#2223]
[Just reading the Quick Start Guides gives me the impression that either the MDT isn't expected to be used with Windows 10 and/or it's no longer supported. I've been using it on a 2016 Server and deploying Windows 10 21H2 so I know it works with newer products but even the Note at the top of the page doesn't mention anything newer than Server 2012 R2 and Windows 8.1. I see in the release notes for the MDT it mentions support for Win10 but would be nice if the documentation was updated too.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85dce28c-0f6f-a586-ecc5-36f1283755b1
* Version Independent ID: 2861004f-bdff-9de9-95dd-7f7670b86a0f
* Content: [Quickstart - LTI - Microsoft Deployment Toolkit](https://docs.microsoft.com/en-us/mem/configmgr/mdt/lite-touch-installation-guide?redirectedfrom=MSDN)
* Content Source: [memdocs/configmgr/mdt/lite-touch-installation-guide.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/mdt/lite-touch-installation-guide.md)
* Product: **configuration-manager**
* Technology: **configmgr-mdt**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @HoutzOfGit 
Two key articles to reference:

- [MDT Release Notes - Supported Platforms](https://docs.microsoft.com/mem/configmgr/mdt/release-notes#supported-platforms)
- [MDT FAQ - Is this release only supported with version 'X' of Windows client, Windows ADK, or Configuration Manager?](https://docs.microsoft.com/mem/configmgr/mdt/faq#is-this-release-only-supported-with-version--x--of-windows-client--windows-adk--or-configuration-manager-)

The MDT content is an area in which we're not actively investing beyond basic maintenance and any new builds. We encourage the community to participate and contribute to the MDT docs! For more info on how to get started, see [How to contribute](https://docs.microsoft.com/mem/use-docs#bkmk_contribute).
