### ISSUE TITLE
ServerState Property Value definitions

### ISSUE THREAD

**Issue by sinktap** [MicrosoftDocs/memdocs#2229]
Hello MS.

I am trying to find the definition for the values of the 'ServerState' Property in the SMS_SCI_SysResUse class. Can you point me in the right direction ?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ab9e4fd-1b32-e777-9a52-3c761fc3bd86
* Version Independent ID: 725ab67f-a548-3931-d007-daa3759d32f1
* Content: [SMS_SCI_SysResUse Class - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/develop/reference/core/servers/configure/sms_sci_sysresuse-server-wmi-class)
* Content Source: [memdocs/configmgr/develop/reference/core/servers/configure/sms_sci_sysresuse-server-wmi-class.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/develop/reference/core/servers/configure/sms_sci_sysresuse-server-wmi-class.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @sinktap I checked one resource I have, and it didn't have any further detail on that property. For example, if you use the [WMI Explorer](https://github.com/vinaypamnani/wmie2) tool, it doesn't show any further description or value map. 

At this time, the ConfigMgr SDK content is an area in which we're not actively investing beyond basic maintenance and some new functionality.

**Comment by aczechowski** [comment]
Oh, you could try asking on [Configuration Manager forums](https://docs.microsoft.com/answers/products/mem). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
