### ISSUE TITLE
InTune Migration

### ISSUE THREAD

**Issue by rconiv** [MicrosoftDocs/memdocs#2232]
When I click on the link for InTune sign in under the Microsoft area, it takes me to a page has moved.  

Our new home is the Microsoft Endpoint Manager admin center. (https://endpoint.microsoft.com)

If it wouldn't cause issues, might be worth updating the link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c3f2675-9769-6b63-3ce8-3c7eb1c6c703
* Version Independent ID: bdd28d63-4fc5-6e2d-b54e-2225896ce493
* Content: [Sign up or sign in to Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/account-sign-up)
* Content Source: [memdocs/intune/fundamentals/account-sign-up.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/account-sign-up.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by msbemba** [comment]
@rconiv Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2588

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @rconiv Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
