### ISSUE TITLE
Offline App Update Verbiage

### ISSUE THREAD

**Issue by Aegrum** [MicrosoftDocs/memdocs#2233]
[Enter feedback here]

> Offline apps are updated using Intune, whereas online apps are updated by the store. Use offline apps when you need to install and maintain a specific app version.

This is confusingly written to imply that the Company Portal (Offline) app will somehow both stay at a specific version while also being updated by Intune. Assuming it works this way (need product team confirmation), I would suggest it to be edited to say:

> Offline apps are updated using Intune, whereas online apps are updated by the store. When synced from the Microsoft Store for Business and deployed as a Microsoft Store app, the Company Portal (Offline) updates will occur automatically to any required assignments. If maintaining a specific version of the Company Portal is required, please refer to [Manually add the Windows 10 company portal app.](https://docs.microsoft.com/en-us/mem/intune/apps/store-apps-company-portal-app)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42b3ccb0-592e-a0bf-aa4f-ab37e00e1195
* Version Independent ID: d0af9188-3489-0f15-ef25-5b6d83edb76c
* Content: [Add and assign the Windows 10 Company Portal app for Autopilot provisioned devices - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/store-apps-company-portal-autopilot)
* Content Source: [memdocs/intune/apps/store-apps-company-portal-autopilot.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/store-apps-company-portal-autopilot.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@Aegrum Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2589

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Aegrum Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
