### ISSUE TITLE
"Profiles & Device Management" Menu Item has been replaced with "VPN & Device Management"

### ISSUE THREAD

**Issue by GeoffP1501** [MicrosoftDocs/memdocs#2234]
"Profiles & Device Management" Menu Item has been replaced with "VPN & Device Management", or replace Profiles with VPN...

Same issue inside the Intune App Install Wizard on an iOS device.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4afb785e-fdfb-ab5d-109f-9f21b58451d2
* Version Independent ID: 06757d5d-fae0-f983-80cc-75a876b7ff75
* Content: [Set up iOS device access to your company resources](https://docs.microsoft.com/en-us/mem/intune/user-help/enroll-your-device-in-intune-ios#prerequisites)
* Content Source: [memdocs/intune/user-help/enroll-your-device-in-intune-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/enroll-your-device-in-intune-ios.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Thank you for your contribution @GeoffP1501. I updated the documentation to reflect the changes to the iOS labels. Changes will be live later this week.
