### ISSUE TITLE
Outdated baseline

### ISSUE THREAD

**Issue by thomasforde** [MicrosoftDocs/memdocs#2237]
[Enter feedback here]
Needs updating. Latest baseline is January 2021

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f0f4d5d-fdd1-22e7-6372-9916b199209f
* Version Independent ID: caeb9f8b-30ad-7f02-4740-56522b2f9b1b
* Content: [Intune security baselines settings for Windows 10/11 MDM - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/security-baseline-settings-mdm-all)
* Content Source: [memdocs/intune/protect/security-baseline-settings-mdm-all.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/security-baseline-settings-mdm-all.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@thomasforde   The content includes the latest details which include the November 2021 baseline, as well as the December 2020, and August 2020.  The November 2021 baseline released this month as [announced in the What's New article](https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new#updates-for-security-baselines), but like all new features can take some time to roll out to all tenants, from a few days to sometimes a week or more.  You should be seeing the baseline as available by next week.
