### ISSUE TITLE
Clarification - is Software Inventory a prerequisite of Software Metering or not?

### ISSUE THREAD

**Issue by PaulKlerkx** [MicrosoftDocs/memdocs#2243]
_**"The Admin configures software inventory to inventory files that have the extension .exe by configuring the software inventory client setting Inventory these file types."

This sentence needs clarification.  Software inventory is not listed as a prerequisite for Software metering at the top of the page, however this sentence in the example suggests that maybe Software inventory is a prerequisite.  

Please clarify the reason the admin configures software inventory - is this a prerequisite, what reason did they enable this inventory?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea61c8fe-a8af-1990-5a6c-8097fb30c852
* Version Independent ID: 8ec2a794-d42c-4a5d-5a77-db6578a77824
* Content: [Monitor app usage with software metering - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/apps/deploy-use/monitor-app-usage-with-software-metering#prerequisites-for-software-metering)
* Content Source: [memdocs/configmgr/apps/deploy-use/monitor-app-usage-with-software-metering.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/configmgr/apps/deploy-use/monitor-app-usage-with-software-metering.md)
* Product: **configuration-manager**
* Technology: **configmgr-app**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @PaulKlerkx for the feedback, we already have an issue tracking this request: #1569
