### ISSUE TITLE
Missing reference to the override of enrollment restrictions

### ISSUE THREAD

**Issue by rbishop-etq** [MicrosoftDocs/memdocs#2245]
This page is missing a very critical piece of information that was recently changed. As stated here, the iOS enrollment types OVERRIDES the enrollment restriction policies:
https://docs.microsoft.com/en-us/mem/intune/enrollment/enrollment-restrictions-set#blocking-personal-iosipados-devices

This page going over the enrollment types for iOS needs to clearly state this so that anybody setting up the enrollment types is aware that this will overrule any of their enrollment restriction policies. The overall poor design of having of this overrule of enrollment restrictions is a separate issue, but this article needs to clearly indicate this recent change of function so that anybody setting these up is made aware that setting these up may render another function useless. We learned this the hard way once personal iOS devices suddenly started being able to enroll despite our enrollment restrictions clearly indicating a block for all personal devices.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59482bb2-51be-0adf-0452-ad2381233577
* Version Independent ID: 82fe5d21-4a76-dd37-db40-84eeaf6f6294
* Content: [Enroll iOS/iPadOS devices with user enrollment in Microsoft Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/ios-user-enrollment)
* Content Source: [memdocs/intune/enrollment/ios-user-enrollment.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/ios-user-enrollment.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@rbishop-etq Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2590

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @rbishop-etq Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
