### ISSUE TITLE
The documentation about enabling this feature doesnt seem to work

### ISSUE THREAD

**Issue by raymonvt3fifty** [MicrosoftDocs/memdocs#2246]
I enabled preview settings on my account but when i look at endpoint settings i cant see the " Configuration Management " settings. Therefore im unable to follow the rest of the instructions. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b166b931-f3f7-3323-7288-758cfa5934f1
* Version Independent ID: b166b931-f3f7-3323-7288-758cfa5934f1
* Content: [Use Microsoft Defender for Endpoint Security Configuration Management in Microsoft Endpoint manager](https://docs.microsoft.com/en-us/mem/intune/protect/mde-security-integration)
* Content Source: [memdocs/intune/protect/mde-security-integration.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/mde-security-integration.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@raymonvt3fifty   The lack of toggles/options in the Microsoft Endpoint Manager admin center suggests your tenant hasn’t yet received the capabilities/feature.  As noted at the top of the article, this feature is rolling out to tenants slowly over the course of  week or two.  Keep checking back every day or two. Those options should show up soon!
