### ISSUE TITLE
Behaviour when specifying multiple servers unclear

### ISSUE THREAD

**Issue by choccychops** [MicrosoftDocs/memdocs#2247]
Hi,

Unclear from the docs and a general bit of online research as to what happens when multiple servers are defined in a Windows VPN profile. 

The article currently states :

Servers: Add one or more VPN servers that devices connect to. 

I've done this, setting server A's default status to 'True' and server B's default status to 'False. I thought when we then took down Server A, we'd see connectivity flow through Server B but this is not the case - seemingly after any number of failed attempts to dial the connection or time-based period.

Further research suggests that there is no failover support, without the use of load balancers, which leads me to ask : what purpose does the server list fulfil if not for failover?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e16582-5730-9f22-2ced-686fc074d5c0
* Version Independent ID: b334cc28-f6ed-103f-3770-4cddb42e666c
* Content: [Windows 10 VPN settings in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/configuration/vpn-settings-windows-10)
* Content Source: [memdocs/intune/configuration/vpn-settings-windows-10.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/vpn-settings-windows-10.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@choccychops We're not aware of this issue. If you haven't already, we suggest working with the Intune support team, and do some troubleshooting. Also, the [Microsoft Q&A](https://docs.microsoft.com/answers/products/enterprise-mobility-security) might be a good option.

**Comment by choccychops** [comment]
I can do that @MandiOhlinger but as mentioned I did a fair amount of troubleshooting back in November when I raised the query. I’m sure you can understand my frustration to hear nothing for two months, then be told to log a call with support, after detailing a pretty specific scenario where the doc guidance is unclear.

**Comment by MandiOhlinger** [comment]
@choccychops For questions like this, I encourage Microsoft Q&A, and/or opening a support ticket. These GitHub issues aren't monitored by engineering or the support teams, which are the teams needed to verify what you found.

If you open a support ticket, and find some interesting info, the support team can update the article. It's possible it could be a bug, but they need to troubleshoot to determine that. If it's a bug, they also have a path to the engineering team to possibly getting it updated.

If we get more users suggesting this setting doesn't work, then we can update the article to state that there might be an issue. Either way, I suggest:

1. Start with Microsoft Q&A to see if others have seen this, what they did to work around the issue, etc.
2. Open the support ticket. If the setting doesn't behave as it should, the support team should investigate.

Thanks again for your input.
