### ISSUE TITLE
Update Documentation for "Install the Certificate Connector for Microsoft Intune"

### ISSUE THREAD

**Issue by nov-26** [MicrosoftDocs/memdocs#2248]
Hi,

Please consider updating **Step 4** under the **Configure the certificate connector** section in the KB below

https://docs.microsoft.com/en-us/mem/intune/protect/certificate-connector-install#configure-the-certificate-connector

It currently reads

> On the Proxy page, add details for your proxy server if you require a proxy for internet access.

We believe it should read something similar to

> On the Proxy page, add details for your proxy server if you require a proxy for internet access. This should be in the format of _"http://proxy.contoso.com"_

We found that by simply entering _"proxy.contoso.com"_ at this step would cause an error and the Intune Certificate Connector Service was unable to connect to the Intune Service. 
Once we added the _"http"_ at the start of the URL it worked fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 497646f6-1498-0647-cc54-b8013d71dca6
* Version Independent ID: e1fa4f5d-35b1-6fad-a4d2-3e8f5952230c
* Content: [Install the Certificate Connector for Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/certificate-connector-install)
* Content Source: [memdocs/intune/protect/certificate-connector-install.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/certificate-connector-install.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@nov-26   Thanks for the suggestion. I've submited an edit this morning which will add that to the docs, and which should be live later today.
