### ISSUE TITLE
Allow Intrusion Prevention System

### ISSUE THREAD

**Issue by BorisKornienko** [MicrosoftDocs/memdocs#2250]
[Enter feedback here]
this setting doesn't exist on https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-defender#defender-allowintrusionpreventionsystem

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38247693-2a29-0b81-223e-8483bbb75c67
* Version Independent ID: de67fc03-ddde-cce0-8dc9-769ed209f5b3
* Content: [Windows Antivirus policy settings from Microsoft Defender Antivirus for tenant attached devices](https://docs.microsoft.com/en-us/mem/intune/protect/antivirus-microsoft-defender-settings-windows-tenant-attach)
* Content Source: [memdocs/intune/protect/antivirus-microsoft-defender-settings-windows-tenant-attach.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/antivirus-microsoft-defender-settings-windows-tenant-attach.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@BorisKorniendo  Thanks for the question on this. I’ve reached out to our engineering team for feedback. Not only is the destination URL for that setting missing, none of the settings in that section of policy (well, across that entire policy) have links to CSPs for reference. Once we run down the correct references, I’ll update this issue, and docs. 

For the regular Antivirus policy (for non-tenant attached devices), the setting appears as _Turn on intrusion prevention_, which points to the following CSP: https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-defender#defender-enablenetworkprotection.

I’ve noted this to the engineering team as well, as the discrepancy in setting names can be confusing, and that CSP is somewhat general and not specific to intrusion prevention configurations.

**Comment by Brenduns** [comment]
@BorisKornienko  Hello Boris, thanks for being patient. Unfortunately, the best information I’ve been able to get from our product team is that this setting appears to be in process of deprecation, without further information available about that.  It seems the CSP that we once linked to no longer exists either. (I'll be editing docs to remove links to the missing CSP).  I have sought to have a product bug filed for this policy area and questions around this and related setttings.

While the Intune engineering/product team is now aware of this question, they are not able to investigate this via this documentation feedback forum.  To progress on this, I recommend opening a support incident to deep dive into the details involved around this setting – which we cannot do via the doc feedback forum. 

I’ll be closing this feedback issue for now, but should more information come to light in the days ahead, I will still be able to respond to you via this issue to provide that update.
