### ISSUE TITLE
Insufficient Explanation

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/memdocs#2256]
In the second note, it says that a pre-provisioned device must be deleted in Intune before being re-enrolled. 
When the device is deleted there is no longer an account to log on to the device. How can the device begin a new Autopilot enrolment?

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0f572e0-1bc0-6f14-7f60-989eb67fb7e7
* Version Independent ID: e4ec5b25-d9a6-d260-6cf6-ff4f3eb3ecb8
* Content: [Windows Autopilot for pre-provisioned deployment](https://docs.microsoft.com/en-us/mem/autopilot/pre-provision)
* Content Source: [memdocs/autopilot/pre-provision.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/pre-provision.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by aczechowski** [comment]
Hi @Air-Git, I double-checked with the feature PM to confirm my thinking: when you remove the device in Intune, it doesn't remove the user's Azure AD credentials. The device is just no longer enrolled in Intune. That's what the Autopilot logic uses for it to re-enroll.

**Comment by Air-Git** [comment]
There are two problems with this:
1) It does not seem to be true that you need to delete the device. If you do a normal Fresh Start in Intune it deletes the device and re-enrols it
2) If you do delete the device, you have no local account to log on, and no obvious way to re-enrol. As far as I can tell you need to do a factory reset, which is not easy to do.

**Comment by aczechowski** [comment]
I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post on [MEM forums](https://docs.microsoft.com/answers/products/mem). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- [How to get support in Microsoft Endpoint Manager admin center](https://docs.microsoft.com/mem/get-support)
- Contact your Microsoft Premier team, such as a Customer Engineer or Technical Account Manager.

**Comment by Air-Git** [comment]
Thanks, but I am not looking for support. I have access to a Microsoft Premier Support agreement. I am doing my bit to improve the documentation.

**Comment by aczechowski** [comment]
I checked back with the PM:

> 1. It does not seem to be true that you need to delete the device. If you do a normal Fresh Start in Intune it deletes the device and re-enrols it. 
>>[PM] Any action that removes the enrollment record from Intune should likely work, we just recommend doing the device deletion. I should have said, deleting the device record does not delete the user record. If you are redeploying a device, if you delete the Intune record, it is still registered in Autopilot so when the device boots up, it will look for the Autopilot profile, then does a check
>2. If you do delete the device, you have no local account to log on, and no obvious way to re-enrol. As far as I can tell you need to do a factory reset, which is not easy to do.
>>[PM] You re-enrol the device by resetting it, once it’s reset, and it detects that there is no enrollment in Intune but is an AP registered device, it will automatically re-enroll the device in Intune. You delete the record in Intune and then perform a reset.

I'm going to open this feedback and let the article author come back to it. He's on extended leave right now, but probably best for him to review later and decide what's best to do here.

Thanks for the feedback!

**Comment by Air-Git** [comment]
That's the issue:
1) It is easy to do a "Fresh Start". This will delete the device in Intune, and cause the device to restart, clean Windows, and restart in Autopilot
2) If you actually "Delete" the device, then everything is removed, including the ability to log on. You cannot reset the device, because you cannot log on to the device to reset it. You cannot do a "Fresh Start" in Intune, because it has been deleted. The only way to get it back to autopilot is to re-image, or use the power and volume buttons to enter the Recovery mode.

So my tests show that all you need to do is to do a Fresh Start, which is what you would want to do anyway when re-issuing a device to another user.

Possibly the significance of the article is that you cannot do "Autopilot Reset" which only removes the user and does not rebuild the device. I have not tested this, but perhaps that is what the article means.

**Comment by frankroj** [comment]
Thank you for the feedback @Air-Git. I apologize for the time it took to get back to you regarding this feedback item. You are correct in some of your assessments. There are certain scenarios where only a full device reimage will bring a device back to a state that you can use Autopilot on it. For such scenarios, if you have Microsoft ConfigMgr Manager available, I would suggest possibly using Autopilot for existing devices which will greatly simplify the process. We have recently released new documentation on this scenario:

https://learn.microsoft.com/en-us/mem/autopilot/tutorial/existing-devices/existing-devices-workflow

Other than that, you may be asking for features that don't currently exist in Intune or Autopilot, which is outside the scope of doc feedback. I am going to go ahead and close this feedback item but if you have any other questions, please let me know.

**Comment by frankroj** [comment]
One other comment. Autopilot reset will only work on devices that are currently enrolled as an Autopilot device. We have also released updated documentation on Autopilot Reset which you can find below:

https://learn.microsoft.com/en-us/mem/autopilot/tutorial/reset/autopilot-reset-overview
