### ISSUE TITLE
Typo in uinstallation command

### ISSUE THREAD

**Issue by dzejzipl** [MicrosoftDocs/memdocs#2258]
Hey,
Uninstallation string is wrong:
is:

```
For Uninstall command line, specify remotehelp.exe/ uninstall /quiet acceptTerms=Yes
```

should be:

```
For Uninstall command line, specify remotehelp.exe /uninstall /quiet acceptTerms=Yes
```

Space for /uninstall parameter in wrong place.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bc62c89-a452-0d3f-01f3-c5982803809e
* Version Independent ID: 6bc62c89-a452-0d3f-01f3-c5982803809e
* Content: [Remotely assist users that are authenticated by your organization.](https://docs.microsoft.com/en-us/mem/intune/remote-actions/remote-help#deploy-remote-help-as-a-win32-app)
* Content Source: [memdocs/intune/remote-actions/remote-help.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/remote-help.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@dzejzipl  Thanks for this feedback. We did have a space jump the line to make that command line broken. That's now fixed in the live content.
