### ISSUE TITLE
Remote help (preview) location in enable procedure is wrong. 

### ISSUE THREAD

**Issue by andydhollander** [MicrosoftDocs/memdocs#2259]
The "Task 1 – Enable remote help" has a mistake in it. 
It points to "**Tenant administration > Connectors and tokens > Remote help (preview).**" to enable Remote help, but "**Remote help (preview)**" is located directly under "**Tenant administration**" in the MEM portal. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bc62c89-a452-0d3f-01f3-c5982803809e
* Version Independent ID: 6bc62c89-a452-0d3f-01f3-c5982803809e
* Content: [Remotely assist users that are authenticated by your organization.](https://docs.microsoft.com/en-us/mem/intune/remote-actions/remote-help)
* Content Source: [memdocs/intune/remote-actions/remote-help.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/remote-help.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@andydhollander  Thanks for this issue Andy.  Per the documentation, and per this screen capture I made this morning from my own public tenant, _Remote help (Preview)_ should be appearing under the **Connectors and tokens** node as documented:  
![image](https://user-images.githubusercontent.com/17034749/144464251-468dd07f-11e4-4164-8986-f4a8dc774e38.png)

 I'm concerned with what you’re seeing, so I've reached out to our engineering team for their thoughts. Can you refresh your connection and add a screen shot that shows the URL and the location from your Tenant?

**Comment by andydhollander** [comment]
@Brenduns It looks like I can't upload a screenshot here, it's probably blocked by a security restriction from our side. 
But the URL where I see it is: "https://endpoint.microsoft.com/#blade/Microsoft_Intune_DeviceSettings/TenantAdminMenu/tenantStatus". 
It's in the menu right below **Tenant status**, so basically the 2nd item in the Tenant admin blade. 

Our tenant is in North America 0201 and on Service release 2111 if that helps.

**Comment by Brenduns** [comment]
@andydhollander   I've reached out to our engineering team who will contact you soon, if they haven't alreday. They are aware of this location change for remote help, as a test for a few select tenants, of which they believe your tenant is one. For now, the docs are accurte to all but a handful of test tenants, and will update in the future should this location change rollout to more/all tenants.

**Comment by andydhollander** [comment]
@Brenduns Thanks! Good to know it's just a few select tenants then :)
