### ISSUE TITLE
Azure AD User Group delta sync 

### ISSUE THREAD

**Issue by robinherbert** [MicrosoftDocs/memdocs#226]
The limitation for Azure AD User Group discovery https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/configure-discovery-methods#limitations (delta disabled) - is that still true, and if so, when won't it be true?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09a88524-a2af-cdb2-630d-86177e245753
* Version Independent ID: b5590ca8-3ce9-c277-e8c3-9c78a69945c1
* Content: [Configure discovery - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/configure-discovery-methods#feedback)
* Content Source: [memdocs/configmgr/core/servers/deploy/configure/configure-discovery-methods.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/deploy/configure/configure-discovery-methods.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @robinherbert, thanks for the question. At least in the test environment I have, the option is enabled. We're checking on whether that's in production builds, and if so when it changed. If it's not yet in production builds, we can't comment on when it might change.

**Comment by mestew** [comment]
Just confirmed with dev that the limitation was removed in 1910. Updated the doc. Thanks!
