### ISSUE TITLE
Active developing?

### ISSUE THREAD

**Issue by jflieben** [MicrosoftDocs/memdocs#2261]
"We're actively developing new script packages" 

Since the feature was in preview not a single package has been developed or even updated....so maybe remove the 'actively developing' from the text, or replace it with a roadmap page/something that tells us what is actually being developed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d35a1251-2323-4239-85d7-ca21f44cf93a
* Version Independent ID: d8bd22fc-6af5-075f-ecee-bb084483bbce
* Content: [Tutorial - Proactive remediations - Microsoft Endpoint Manager](https://docs.microsoft.com/en-us/mem/analytics/proactive-remediations)
* Content Source: [memdocs/analytics/proactive-remediations.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/analytics/proactive-remediations.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @jflieben for the feedback. The PM just updated the article to remove that sentence. The change will publish live in a few hours.
