### ISSUE TITLE
Layout change

### ISSUE THREAD

**Issue by rconiv** [MicrosoftDocs/memdocs#2262]
A fair amount of things in this article have changed from when it was written.

The options have changed, and the following is completely different.

Warning for other disk encryption = Block is now Hide prompt about third-party encryption and is under Bitlocker - Base Settings

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54cccf1d-81fd-5331-aee7-59a35b39cb15
* Version Independent ID: 81d14392-fe74-4fd9-047f-7b8292d84f0c
* Content: [Encrypt Windows devices with BitLocker in Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/encrypt-devices)
* Content Source: [memdocs/intune/protect/encrypt-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/encrypt-devices.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@rconiv   Thanks for this feedback.  Yep, looks like a lot has been changed without raising awareness to docs. I've opened a work item in my docs backlog so I can work with our engineering team to unravel the details based on recent UI changes.  With that internal tracking of this work, I’ll close this GitHub issue, but I'll reply to you via this issue once we have a content update ready.
