### ISSUE TITLE
How to update apps that users installed based on "Available Intent"

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/memdocs#2264]
If a user installed an app from the company portal and that app was published as available, how does the admin update that app with a new version? Is there a way to do that or does the user have to manually install the update via the company portal?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95d2a103-e681-fa04-d3ff-3bffd1e41ca0
* Version Independent ID: 865c635a-2ee7-9c87-7a32-61464e5255ff
* Content: [Add Win32 app supersedence - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-win32-supersedence)
* Content Source: [memdocs/intune/apps/apps-win32-supersedence.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/apps-win32-supersedence.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@danmyhre Thank you for your feedback. If it is installed and published as available, the admin will be able to make detection method on the app version and update the app that way.

If you have trouble doing that, I recommend working closely with our Support team via the need help Icon on the admin center.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @danmyhre Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
