### ISSUE TITLE
Both versions in company portal - Available Intent

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/memdocs#2265]
This part is wrong - only the superseding app is shown in the company portal

<html>
<body>

Both superseding and superseded apps will be shown in the company portal if they have the applicable targeting. However, currently only the superseding apps can be installed.
--

<br class="Apple-interchange-newline">
</body>
</html>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95d2a103-e681-fa04-d3ff-3bffd1e41ca0
* Version Independent ID: 865c635a-2ee7-9c87-7a32-61464e5255ff
* Content: [Add Win32 app supersedence - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-win32-supersedence)
* Content Source: [memdocs/intune/apps/apps-win32-supersedence.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/apps-win32-supersedence.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@danmyhre Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2592

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @danmyhre Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
