### ISSUE TITLE
Device and User

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/memdocs#2266]
The wording seems to be inconsistent when referring to installation of apps. 

For Win32 apps, "Install behaviour" is "User" or "System" (although in this case "System" is per-machine installation context, and "User" is per-user installation context.). For Store Apps, "Supports device context assignment" is true or false

The document uses the terms:
- per machine
- per user
- installation context = Device

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92ba0166-1d3c-40ca-a2f3-2954dcfe4411
* Version Independent ID: e07d50e2-7a95-868d-5800-ea548c84e884
* Content: [Set up the Enrollment Status Page - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/windows-enrollment-status)
* Content Source: [memdocs/intune/enrollment/windows-enrollment-status.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/windows-enrollment-status.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @Air-Git, thanks for contacting the Microsoft Intune Docs team. I opened a task for us to review and update this article, with special attention to the inconsistent wording. Closing this issue and tracking internally.
