### ISSUE TITLE
Windows Security app notifications

### ISSUE THREAD

**Issue by danwdavey** [MicrosoftDocs/memdocs#2267]
Windows Security app notifications

Does setting this back to not configured revert to defaults or leave in last state? documentation does not state however appears to leave in last state (e.g. if Block All then not configured, device is left in Not Configured)

CSP: DisableNotifications

Use this setting to block Windows Security notifications to your users for all of the preceding feature settings. Alternatively, you can manage the Windows Security app notifications per feature by using the proceeding settings.

Not configured (default) - All Windows Security app notifications that are not controlled by another setting are allowed.
Block non-critical notification - Notifications such as scan completions are blocked.
Block all notifications - Critical and non-critical notifications are blocked for all Windows Security features.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6609b7ea-8483-b2f5-fc99-6dbcdf360fbd
* Version Independent ID: 47cadd40-b9ff-d49d-e36c-b018984db20d
* Content: [Antivirus policy settings for Windows Security experience policy for Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/antivirus-security-experience-windows-settings)
* Content Source: [memdocs/intune/protect/antivirus-security-experience-windows-settings.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/antivirus-security-experience-windows-settings.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@danwdavey  Thanks for this question.  When set to Not configured, Intune behavior is to not enforce a block notifications via _this_ setting, which works as a universal block of all notifications. Instead, when set to not configured, notifications are allowed on the device unless one of the other settings from this policy is set in a way which blocks notifications for that specific area, such as hiding the App and browser control area, or hiding the Firewall and network protection areas.

**Comment by danwdavey** [comment]
> @danwdavey Thanks for this question. When set to Not configured, Intune behavior is to not enforce a block notifications via _this_ setting, which works as a universal block of all notifications. Instead, when set to not configured, notifications are allowed on the device unless one of the other settings from this policy is set in a way which blocks notifications for that specific area, such as hiding the App and browser control area, or hiding the Firewall and network protection areas.
> 
> Update: I've submitted a content edit that will publish later today and that should make the behavior of Not configured more clear.

Thanks @Brenduns - If this was previously set however does a 'not configured' set it back to allow notifications. My limited testing indicates it does not, still shows as follows. Even when policy deleted still shows as follows; 

![Screenshot 2021-12-06 175327](https://user-images.githubusercontent.com/95633382/144896760-65e2e995-6d5b-4f04-b56d-bebe607230d5.png)

**Comment by Brenduns** [comment]
Ok, let me check into that more deeply.  Sometimes a Not configured just stops managing it. There is no option to allow all notifications, and Not configured is intended by its current description and expectation to do so. It might have been implemented differently. However,  there is the potential that other settings are blocking those same notifications.  Intune, and specifically, this policy source is one of many methods a device can receive configurations.

Once I get some validation back from engineering, I'll update you here.

**Comment by Brenduns** [comment]
@danwdavey  I've been able to get a response that indicates this setting is believed to be tied into two CSPs, combining the resulting functionality of both. Unfortunately, which other CSP and just how that works wasn't made clear - and that seems to be the extent of details I can get via this doc-feedback forum and investigation of the underlying setting. :(   

To progress, please consider opening a support issue to get the deeper details of this setting. Support can then invest the necessary resources to get to the bottom of this and the expected behavior, and also submit those details for documentation.  However, in the meantime, the engineering team has been made aware of the questions here, even though they've not been able to provide clarifications. Should new information become available, I'll be able to update this post and alert you to that.
