### ISSUE TITLE
Supportability for LTSC

### ISSUE THREAD

**Issue by GenerAhl** [MicrosoftDocs/memdocs#2268]
The section "Since Windows 10 Enterprise 2019 LTSC is based on Windows 10 version 1809, self-deploying mode is also not supported on Windows 10 Enterprise 2019 LTSC" makes it sound like Autopilot is supported on LTSC, just not the 2019 version.
As the Software requirement page https://docs.microsoft.com/en-us/mem/autopilot/software-requirements calls out "A supported version of Windows 10 Semi-Annual Channel is required." it doesn't sound like ANY version of LTSC is or will be supported.
If this is the case, you should probably not dive into the details of why LTSC 2019 isn't supported and rather state that LTSC is not supported, full stop.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25e8c073-c36b-180e-a841-ed57ac32dc83
* Version Independent ID: 739ddac5-64f1-161f-b047-50cb737c58da
* Content: [Windows Autopilot self-deploying mode (Public Preview)](https://review.docs.microsoft.com/en-us/mem/autopilot/self-deploying)
* Content Source: [memdocs/autopilot/self-deploying.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/self-deploying.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by aczechowski** [comment]
Thanks @GenerAhl for the feedback. An edit to the article is removing that sentence.
