### ISSUE TITLE
Recovery PIN display period

### ISSUE THREAD

**Issue by haven564** [MicrosoftDocs/memdocs#227]
Clarification is needed on how long the 6-digit recovery PIN displays in the portal for MacOS. It no longer displays in the portal after 7 days has passed, even if no other device action was sent.  This can really bite anyone that isn't aware of this and expects the PIN to be retrievable after 7 days since no further device action sent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c79f5e46-0615-682c-0368-5a14cfa738e7
* Version Independent ID: 08094776-efc7-d7b1-0b82-0aee1dac5634
* Content: [Lock devices with Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/remote-actions/device-remote-lock#feedback)
* Content Source: [memdocs/intune/remote-actions/device-remote-lock.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/remote-actions/device-remote-lock.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
(7207822)

**Comment by haven564** [comment]
FYI, this is what Intune support stated: "Also to clarify the time period for how long the PIN is displayed/recovered. You can see the PIN in the Intune console for up to 7 days, while on the back-end, we have access to the data for 30 days. "

**Comment by ErikjeMS** [comment]
@haven564 A note on this was added to the doc back in May.

**Comment by amopportunities** [comment]
Huge issue, how do we recover the PIN if it is no longer displayed?
