### ISSUE TITLE
error under "configuration issues"

### ISSUE THREAD

**Issue by rjohnstonmcsa** [MicrosoftDocs/memdocs#2270]
Under configuration issues at the bottom, in the table there is a duplicated text item under "Windows update rings do not apply" referring to Win32 apps, which seems to be a copy paste error from the above item in the table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 591d8748-ca94-f818-2ea3-9143b8e41697
* Version Independent ID: 7b0d2d80-8bf4-b9b6-7a2a-b0f3dc50a125
* Content: [Using Azure Virtual Desktop multi-session with Microsoft Intune (preview)](https://docs.microsoft.com/en-us/mem/intune/fundamentals/azure-virtual-desktop-multi-session)
* Content Source: [memdocs/intune/fundamentals/azure-virtual-desktop-multi-session.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/azure-virtual-desktop-multi-session.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @dougeby
* Microsoft Alias: **dougeby**

**Comment by msbemba** [comment]
@rjohnstonmcsa Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2593

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @rjohnstonmcsa Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
