### ISSUE TITLE
What about Server OS?

### ISSUE THREAD

**Issue by AlexSchwerzmann** [MicrosoftDocs/memdocs#2271]
Are there any plans for supporting Windows Server OS? If not, what's the recommended Cloud-Approach (not SCCM)?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f70a020-9214-3316-5419-ee35ba6ff91a
* Version Independent ID: 9cc74430-af54-a2ac-7e4f-5a70b415c66e
* Content: [Operating systems and browsers supported by Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/supported-devices-browsers)
* Content Source: [memdocs/intune/fundamentals/supported-devices-browsers.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/supported-devices-browsers.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by msbemba** [comment]
@AlexSchwerzmann Thank you for your feedback.  It's not possible to MDM-enroll Windows Server devices to Intune, but it's totally possible to see Windows Server devices in the MEMAC using Tenant-Attach. I'd recommend you post the feedback on our main feedback portal -https://feedbackportal.microsoft.com/ so one of the dev/product team members will be able to provide you an update if this is in the roadmap.

Hope this helps!

Thanks
Sri
