### ISSUE TITLE
Need to update the Doc by removing Safe boot and Debugging Features

### ISSUE THREAD

**Issue by FadiJo** [MicrosoftDocs/memdocs#2273]
Hi Team,

We need to update this Document as the two settings in the subject is not in the UI anymore and they have been replaced by Developer settings as Google Deprecated those settings API and its making confusion for others.

You may check the change as its added here https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new#plan-for-change-safe-boot-and-debugging-features-in-android-enterprise-device-restrictions-will-be-replaced 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 900e72be-d42b-49ba-f304-602df23cbb04
* Version Independent ID: 2ce5c45d-15be-d316-1c57-92bea37358e0
* Content: [Android Enterprise device settings in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-android-for-work#fully-managed-dedicated-and-corporate-owned-work-profile-devices)
* Content Source: [memdocs/intune/configuration/device-restrictions-android-for-work.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/device-restrictions-android-for-work.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@FadiJo You are correct. Thank you! The settings have been removed. The changes should be live sometime tomorrow.
