### ISSUE TITLE
remote help silent install fails due to 

### ISSUE THREAD

**Issue by Ukn0wnD3v** [MicrosoftDocs/memdocs#2274]
[Enter feedback here]

remotehelp.exe /install /quiet /acceptTerms=yes

This doesn't work and interactively running the install always ask the question if I want to terminate the install in the middle of install. This causes failure of silent installation 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bc62c89-a452-0d3f-01f3-c5982803809e
* Version Independent ID: 6bc62c89-a452-0d3f-01f3-c5982803809e
* Content: [Remotely assist users that are authenticated by your organization.](https://docs.microsoft.com/en-us/mem/intune/remote-actions/remote-help)
* Content Source: [memdocs/intune/remote-actions/remote-help.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/remote-help.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Ukn0wnD3v** [comment]
Just tested without the "/" before acceptTerms and experienced the same issue.
Running it with just /install shows the terminate prompt during installation if the engineering team would like to verify themselves.

**Comment by Brenduns** [comment]
@Ukn0wnD3v  Thanks for the additional confirmation. I've just received an update from our engineering team, and they note that they have an issue under investigation with the installer failing in some cases (or prompting to cancel during interactive installation). 

They think you might be hitting that issue but were not able to share any actual details about that. Their recommendation is to have you reach out to Support (See [Get support](https://docs.microsoft.com/mem/get-support). We’re not able to provide more than a cursory investigation via the GitHub issue channel.

We've very recently added some details about the install logs for remote help to the article, so if you do reach out to support, please have those handy!  That information follows: 

Installation of remote help - When remote help installs or uninstalls, the following two logs are created in the device users Temp folder, for example C:\Users\<username>\AppData\Local\Temp. The * in the log file name represents a date and time stamp of when the log was created.
•	Remote_help_*_QuickAssist_Win10_x64.msi.log
•	Remote_help_*.log

With the engineering recommendation to contact Support, and no change of details for the docs available at this time, I'll need to close out this GitHub issue. Should support and engineering glean information about the issue, they'll pass that on for docs, but you can also always reply back to a closed GitHub issue, which I'll receive/see in case there is something more we can review or provide.
