### ISSUE TITLE
Step 3a ist not available in my tendent.

### ISSUE THREAD

**Issue by FabianNiesen** [MicrosoftDocs/memdocs#2277]
Step 3a ist not available in my tendent. Getting redirected to security.microsoft.com and their is no such option under Settings

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24fa182f-ace6-e7e2-ff98-91951be7d10e
* Version Independent ID: f1acb398-6d69-b91c-5ee0-3da3bbf7809f
* Content: [Configure Microsoft Defender for Endpoint in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/advanced-threat-protection-configure)
* Content Source: [memdocs/intune/protect/advanced-threat-protection-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/advanced-threat-protection-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@fabianNiesen  Hello Fabian, is the issue your seeing (line 3.a) about the link from the preceeding step #2, where you use the link in the Microsof Endpoint Manager admin center to open the _Microsoft Defender Security Center_?  That link from MEM does go to the expected Defender portal, the correct destination. Hoever, it seems there hsa been some rebranding at the destiation where the Microsoft Defender Security Portal is now wrapped up into the rebranded  _Microsoft 365 Defender_ portal at https://security.microsoft.com.  If your account/tenant is enabled for Defender for Endpoint, you should then have access to continue.  

If that's correct, then you should be able to proceed.  The Settings > Endpoints > Avanced features is still the same as it was in the previously branded portal instance.  

I've also now passed on to our engineering team that the link name in the UI could use an update. Meanwhile, i'll update docs to make it clear that the UI reference does in deed land you on the recently rebranded Microsoft 365 Defender site, which is the new name of the Defender Security Center.  This Defender content page makes clear tehre has been a portal change (which hasn't reached our Intune/MEM UI):  https://docs.microsoft.com/microsoft-365/security/defender/microsoft-365-defender?view=o365-worldwide

**Comment by Brenduns** [comment]
@FabianNiesen Hello Fabian, is the issue your seeing (line 3.a) about the link from the preceding step #2, where you use the link in the Microsoft Endpoint Manager admin center to open the _Microsoft Defender Security Center_? 

I’ve checked in with our Defender partners, and they confirm that the securitycenter.windows.com site is going away (has gone away already?) and links to it are being redirected to _Microsoft 365 Defender_ at https://security.microsoft.com .  With the new portal, you use the same path of Settings > Endpoints > Advanced Features in 3.a. 

If you can't see Endpoints after selecting settings, then your account might lack the correct permissions for the Defender portal or there is an issue with your Defender suscription for your tenant. If you believe your account should have those permissions already assigned to it, you'll need to reach out to Support for Defender to have that investigated.  For my own personal tenant that doesn't have a subscription for Defender, I can open the Microsoft 365 Defender portal, but when I select Settings I only see a few of the expected options (which is expected), and  Endpoints isn't one of them. 

As for Docs, they will be updated to reflect the new portal name, and I’ve passed that portal change on to our engineering team so they can look at updating the UI.
