### ISSUE TITLE
Client settings titles are not correct

### ISSUE THREAD

**Issue by scchram** [MicrosoftDocs/memdocs#228]
I am running Config manager 1910.  the descriptions/titles of the computer restart settings do not match what I show in my console.  I doubt your article is wrong, but the title of a setting such as " Display a temporary notification to the user that indicates the interval before the user is logged off or the computer restarts (minutes)" I cannot find in any of the client agent settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cdffa2e-043f-10f1-104f-7f0a76d6d6b2
* Version Independent ID: 90732577-ae31-2396-066d-8645a949fac0
* Content: [Device restart notifications - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/deploy/device-restart-notifications#feedback)
* Content Source: [memdocs/configmgr/core/clients/deploy/device-restart-notifications.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/deploy/device-restart-notifications.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @scchram for the feedback. We're tracking this via an internal item (7182335)

**Comment by scchram** [comment]
Is there any way for me to track this request? internal item (7182335) ??

**Comment by aczechowski** [comment]
No, sorry, it's in our internal Azure DevOps system. I'll take a note to comment back here when the work is done.

**Comment by aczechowski** [comment]
I revamped this article to include the new strings and made a bunch of other improvements, including a section of examples from engineering. I expect the revision to publish tomorrow. Thanks again for the feedback.
