### ISSUE TITLE
Article contains contradictory information regarding supported configurations

### ISSUE THREAD

**Issue by Wardrop** [MicrosoftDocs/memdocs#2281]
I just ran through these instructions installing the NDES service on the same server as my certificate authority. There's a warning toward the top of the article that states:

> We recommend you don’t use NDES that's installed on the server that hosts the Enterprise CA. While use of NDES that's installed on an Enterprise CA is supported, this configuration represents a security risk when the CA services internet requests.

I proceed with installing NDES on the same server as our CA anyway, but then at the very bottom of the page, it says "The connector isn't supported on the same server as your issuing Certification Authority (CA).".

One part of the article simply advises against it but states the NDES on the same server as the CA is supported, but then at the end of the article it says it's unsupported in the context of the InTune Connector.

This really needs to be cleared up, and all information needs to be at the top of the page. No good saying something is unsupported at the end of the article after going through everything.

Cheers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9107185-e6c7-b178-4e22-819797fe4880
* Version Independent ID: 1153b441-94f0-b471-52a2-3cf556c68581
* Content: [Configure infrastructure to support SCEP certificate profiles with Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/certificates-scep-configure)
* Content Source: [memdocs/intune/protect/certificates-scep-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/certificates-scep-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@wardrop 
Thanks for the feedback. It does look like that information got away from us. I've submitted an update to bring the connector installation conflict into the details near the top, as well as when describing the connector and NDES server roles - to help others avoid the unsupported configuration.  Those updates should be live later today.
