### ISSUE TITLE
"Your device is already being managed by an organization" alternative issue

### ISSUE THREAD

**Issue by mnelson4** [MicrosoftDocs/memdocs#2292]
I was getting the error "Your device is already being managed by an organization" when trying to register a Windows device. Unfortunately, *I am* the IT support person.

The problem was that I had already signed into my work account on the Windows computer, and was then trying to use the Company Portal app to enroll the device, which was where I was getting the error. (I was accustomed to using the Company Portal app to register just like on Mac computers.)

After a long time, I eventually saw noticed I could enroll the device from Settings App: https://docs.microsoft.com/en-us/windows/client-management/mdm/mdm-enrollment-of-windows-devices#use-the-settings-app-1 which worked.

Some mention fo that could be made form here.
For example, after

> Resolution
> Contact your IT support person to find out how they want you to proceed.

it could say

> Also, if you're getting this error using the Portal App, try instead enrolling using [the Settings app](https://docs.microsoft.com/en-us/windows/client-management/mdm/mdm-enrollment-of-windows-devices#use-the-settings-app-1)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c84bc4f1-ce78-2b16-47e3-bac8d3fc1522
* Version Independent ID: dc6ad881-08a5-d94c-c3c3-01c5c41400af
* Content: [Troubleshoot Windows 10/11 device access for school or work](https://docs.microsoft.com/en-us/mem/intune/user-help/troubleshoot-your-windows-10-device-windows)
* Content Source: [memdocs/intune/user-help/troubleshoot-your-windows-10-device-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/troubleshoot-your-windows-10-device-windows.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @mnelson4, thanks for reaching out to the Docs team and sharing your steps. 

Could you tell me (if you can recall), did you follow step 5 as instructed [in the IT Pro docs](https://docs.microsoft.com/en-us/windows/client-management/mdm/mdm-enrollment-of-windows-devices#use-the-settings-app-1)? I'm asking because step 5 in the [device user article](https://docs.microsoft.com/mem/intune/user-help/troubleshoot-your-windows-10-device-windows#add-work-or-school-account-in-settings-app) is identical _up to_ step 5, so trying to figure out if that's an oversight on our end. I'm also checking with the product team and will update the doc as soon as I confirm. Appreciate your help!

**Comment by lenewsad** [comment]
Hi @mnelson4, we recommend that device users/non-IT professionals reach out to their support person for help if they're still experiencing enrollment issues after they try all  troubleshooting steps. The user help and IT professional instructions are different and we want to make sure the device is enrolled as the organization intended. 

We're looking into how we can improve the doc experiences for IT pros encountering this enrollment issue. If you want to find out exactly what went wrong in your specific case, there are a couple of options:  

- Post on [Microsoft Intune forums](https://docs.microsoft.com/answers/products/mem). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful. 

- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support. 

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.  

I'm closing this issue as there's nothing actionable for docs at this time. Thank you!
