### ISSUE TITLE
Path to "MobileClient.tcf"

### ISSUE THREAD

**Issue by dridley23** [MicrosoftDocs/memdocs#2295]
The correct folder location for is "<installationfolder>\bin\i386\MobileClient.tcf"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dc1b7c8-1005-c581-b9d5-dd3769fb3ca5
* Version Independent ID: 85c42241-97da-f8d4-39f5-48f60f2a47dd
* Content: [Configure security - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/security/configure-security#pre-provision-a-client-with-the-trusted-root-key-by-using-a-file)
* Content Source: [memdocs/configmgr/core/plan-design/security/configure-security.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/configmgr/core/plan-design/security/configure-security.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @dridley23 for the feedback, that's correct! There are a couple of spots in this article that use that incorrect path. The only other references to the two .tcf files are in one other article, which says:

> This file is in the `\bin\<platform>` subfolder of the Configuration Manager installation directory on the site server.

I'll update this article to match that language.
