### ISSUE TITLE
Permissions Required for Log Analytics Workspace

### ISSUE THREAD

**Issue by Kazzan** [MicrosoftDocs/memdocs#2297]
You should list the permissions required for Log Analytics Workspace and the Subscription for Azure if someone want to integrate the Logs. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1cee1ad-3f38-5bde-09a3-32742d8d39cd
* Version Independent ID: bf4cf7d8-e162-80ec-98b0-e46b452e44cb
* Content: [Route logs to Azure Monitor using Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/review-logs-using-azure-monitor)
* Content Source: [memdocs/intune/fundamentals/review-logs-using-azure-monitor.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/review-logs-using-azure-monitor.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by msbemba** [comment]
@Kazzan Thank you for your feedback. The document lists the prerequisites here -https://docs.microsoft.com/en-us/mem/intune/fundamentals/review-logs-using-azure-monitor#prerequisites

To use this feature, you need:

An Azure subscription that you can sign in to. If you don't have an Azure subscription, you can [sign up for a free trial](https://azure.microsoft.com/free/).
A Microsoft Intune environment (tenant) in Azure
A user who's a Global Administrator or Intune Service Administrator for the Intune tenant.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Kazzan Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Kazzan** [comment]
Hi, I just wondering if you even read my initial comment or not.

I asked to clarify the permissions for Workspace itself. If I only have Reader permissions to Workplace it does not get connected to Intune. Will Owner of Resource Group work? Maybe, maybe Not, but definitely you need the Contributor for Workspace at least.

This is the single thing which article does not mention. Not everybody are Global Admin and Subscription Owners in these days in time of least privilege access times.

Thanks for thinking about it and clarify these roles.

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@Kazzan Thank you for your response and sorry about the confusion. You are correct, you need to have a Log Analytics Contributor to be able to Configure the collection of logs from Azure Storage. More details can be found here-
anhttps://docs.microsoft.com/en-us/azure/azure-monitor/logs/manage-access#manage-access-using-azure-permissions

I have also added this to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2612

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by Kazzan** [comment]
Thanks. 👍

**Comment by msbemba** [comment]
@yogkumgit The changes have been made. The issue can be closed.
