### ISSUE TITLE
Auto Log Off User when exit Remote Help

### ISSUE THREAD

**Issue by Mela-SAG** [MicrosoftDocs/memdocs#2298]
Closing the App by "X" or by END Remote Help, log off the End User automatically.

**Comment by MandiOhlinger** [comment]
@Mela-SAG Which article? If you're recommending a documentation change, you can create a pull request. The specific steps are at [https://github.com/MicrosoftDocs/memdocs](https://github.com/MicrosoftDocs/memdocs). Scroll past the folder view.

**Comment by Mela-SAG** [comment]
@MandiOhlinger , sorry, I wanted to report an issue to the product and not to the Page...
https://docs.microsoft.com/en-us/mem/intune/remote-actions/remote-help

**Comment by MandiOhlinger** [comment]
@Mela-SAG Ah - thank you! To submit product feedback, go to the [page](https://docs.microsoft.com/mem/intune/remote-actions/remote-help), scroll to the bottom, and select **Feedback** > **This product**.
