### ISSUE TITLE
Type in page

### ISSUE THREAD

**Issue by ThijsLecomte** [MicrosoftDocs/memdocs#23]
Take in this page
MAM iiOS/iPadOSOS targeted managed app protection
=&gt; iOS should be with with 'i'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9efa1fad-ddb2-4f04-dc17-ddc7872df0d4
* Version Independent ID: 9be69699-ffb0-9fb3-ff1e-d1a4a9209589
* Content: [Policy sets - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/policy-sets)
* Content Source: [memdocs/intune/fundamentals/policy-sets.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/policy-sets.md)
* Service: **microsoft-intune**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by ThijsLecomte** [comment]
+ iPadOSOS :)

**Comment by Erikre** [comment]
@ThijsLecomte - Thanks for the feedback. We're fixing this now.
