### ISSUE TITLE
What are the minimum attributes needed to update an existing record? 

### ISSUE THREAD

**Issue by Garthmj** [MicrosoftDocs/memdocs#230]
Guid for sure but is MAC address also needed? These are the only two that have the GUID/Key flags above. I also curious why Name isn't listed and why NetBios_name is?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e9bcf9c-9ac1-1f22-c857-8f791ef383b8
* Version Independent ID: 94f02a8a-d06b-d445-6061-bfc791bdcb7b
* Content: [Add New Properties to an Existing Resource Type](https://docs.microsoft.com/en-us/mem/configmgr/develop/core/servers/configure/how-to-add-new-properties-to-an-existing-resource-type)
* Content Source: [memdocs/configmgr/develop/core/servers/configure/how-to-add-new-properties-to-an-existing-resource-type.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/develop/core/servers/configure/how-to-add-new-properties-to-an-existing-resource-type.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by Garthmj** [comment]
My quick test show you only need the GUID.

**Comment by aczechowski** [comment]
Thanks @Garthmj for the feedback. The ConfigMgr SDK content hasn't changed in a long time, and it's an area in which we're not actively investing beyond basic maintenance and some new functionality. If you'd like to submit a change for this issue, see [How to contribute](https://docs.microsoft.com/sccm/core/understand/use-docs#bkmk_contribute).
