### ISSUE TITLE
Typo in current version string

### ISSUE THREAD

**Issue by ncrutch13** [MicrosoftDocs/memdocs#2300]
Windows reports this file version has not having the trailing 0

Site reads
"The most recent version of remote help is 10.0.100110.16384"

However the file currently available shows a version that is actually, 10.0.10011.16384

The correct version is listed on step 4
"For Value, specify the version of remote help your deploying. For example, 10.0.10011.16384"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bc62c89-a452-0d3f-01f3-c5982803809e
* Version Independent ID: 6bc62c89-a452-0d3f-01f3-c5982803809e
* Content: [Remotely assist users that are authenticated by your organization.](https://docs.microsoft.com/en-us/mem/intune/remote-actions/remote-help#download-remote-help)
* Content Source: [memdocs/intune/remote-actions/remote-help.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/remote-help.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@ncrutch13   Thanks for this submission. Looks like a recent doc update for the change from version 10 to 11  went a bit off track. The version is as you note, and that will be reflected in the docs later this afternoon.
