### ISSUE TITLE
 There should be another section in this article with more tips for tracking down per-setting Conflicts, for both Devices and Users

### ISSUE THREAD

**Issue by rsulliva** [MicrosoftDocs/memdocs#2308]
[Enter feedback here]

One can go in circles for a while 'til realizing that Endpoint Security "config profiles" apply too, not just the ones in Endpoint Manager.  Once I knew to look there too, I could begin to find conflicts.  

Where else do settings (with potential to conflict) come from?  Do some "compliance policies" do more than measure compliance... do they apply settings too!  Other settings UI in the tenant, perhaps with tenant wide settings that have been there since before Endpoint Manager and Defender for Endtpoint and Endpoint Security were filled in?

It really be nice if the MDM DIagnostic Report could provide a complete csv, xml or json of every single setting line item AND the Configuration Profile is coming in from, and it's status (did it apply ok?).  

Or maybe something like this could be generated and placed in the /Users/Public/Documents along with the MDM Diag Report.  It could then be grabbed and loaded into Excel or filtered and sifted in some other way to sort and sift, to see exactly what settings are trying to apply.

It would be a bonus if any local GPO's or local settings with potential to override InTune settings (and cause errors?) could be shown too, or if it could correlate & scoop up correlated events (setting by setting as they most recently applied, setting by setting?).  That could be included too.

Anything like this could also be included in the .cab file of logs that is generated and transmitted when Diagnostics are requested.  

This could be as useful as RSoP and ADMX is in the Active Directory / GPO world and it's sorely missing!

Thanks.  Rob

I'm really curious about Powershell that I saw recently that can be used to backup & restore Intune and configuration profiles.  It looks like the "backups" are json files that could be exported, filtered and compared, to do what I'm looking for.  I plan to explore that more... see Intune Backup & Restore, https://github.com/jseerden/IntuneBackupAndRestore 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14c045c9-2ccb-e24b-9eaa-bfd65b64a48c
* Version Independent ID: 355e928b-5ad8-ac1d-24d4-1d2e8f11cb4d
* Content: [Troubleshoot device profiles in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/configuration/device-profile-troubleshoot)
* Content Source: [memdocs/intune/configuration/device-profile-troubleshoot.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/device-profile-troubleshoot.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@rsulliva There's a lot of good information in your post. 

- In [Common questions and answers with device policies and profiles in Microsoft Intune](https://docs.microsoft.com/mem/intune/configuration/device-profile-troubleshoot), we added some of the information you recommended, including a link to the [Intune reports](https://docs.microsoft.com/mem/intune/fundamentals/reports), which help troubleshoot conflicts. The changes should go live later today.

- For your reporting feedback, I suggest submitting product feedback so the PMs for these areas can see your ideas. To do this, go to [Intune reports](https://docs.microsoft.com/mem/intune/fundamentals/reports), scroll to the bottom, and select **This product**. You can follow these steps for any article.

  <img width="223" alt="image" src="https://user-images.githubusercontent.com/3229224/173909093-b17aa31c-55e6-46d8-8d54-de83f2229386.png">

- In the [Deployment guide: Setup or move to Microsoft Intune > Tenant to tenant migration section](https://docs.microsoft.com/mem/intune/fundamentals/deployment-guide-intune-setup#tenant-to-tenant-migration), we have some information that's *kinda* related to backup/restore. Just wanted to share that info in case you're not aware it exists.

Thanks for the info!
