### ISSUE TITLE
Prerequisites missing Intune license requirement

### ISSUE THREAD

**Issue by svenhallauer** [MicrosoftDocs/memdocs#2314]
We need to add a bullet to the prerequisites portion of the page to state that users must have an Intune license assigned. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81bcb445-ada9-e2e3-d8a8-a5693a5a3850
* Version Independent ID: 6214bb16-5087-c21c-fd43-d5f0a6f405c1
* Content: [Device compliance partners in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/device-compliance-partners)
* Content Source: [memdocs/intune/protect/device-compliance-partners.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/device-compliance-partners.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@Svenhallauer  Thanks for that feedback. I've submited a content edit that will go live later today to clarify that (adding that missing bullet point).

**Comment by svenhallauer** [comment]
Thanks!
