### ISSUE TITLE
Automatic VPN -> On-demand VPN -> Establish VPN -> All Domains item description is misleading

### ISSUE THREAD

**Issue by jdonaandara** [MicrosoftDocs/memdocs#2315]
Hello Team ,

The description for setting "All domains: Select this option to apply your rule to all domains in your organization." is misleading. It suggests the setting all demands includes Domain's/Internal sites only. This is not true as the setting configures both internal and external sites equally. The description should be updated so it is easier for the reader to know it does covers ALL sites.

Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a4e2ec1-b0f9-aee4-e7df-eed9ab445091
* Version Independent ID: bff2d59c-7fe4-fca0-60ad-d39438fe8f27
* Content: [Configure VPN settings to iOS/iPadOS devices in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/configuration/vpn-settings-ios#automatic-vpn)
* Content Source: [memdocs/intune/configuration/vpn-settings-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/vpn-settings-ios.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@jdonaandara Thank you for bringing this to our attention. I've shared this info with the engineering team. No ETA on if/when it'll be addressed. But, they're aware of it.
