### ISSUE TITLE
enrollmentProfileName -eq null filter in MEM

### ISSUE THREAD

**Issue by TechTrooper** [MicrosoftDocs/memdocs#2320]
Hello,

With dynamic device groups it is possible to do query e.g. 
`(device.enrollmentProfileName -eq "null")`

We are able to find devices with empty enrollmentProfileName attributes and add them into the group.
This doesn't work as espected with filters. For example Android Enterprise, Fully Managed user devices don't have enrollmentProfileName value, but searching for null value doesn't result in a match.

It's also not possible to search for empty value. 
Trying to create filter e.g.
`(device.enrollmentProfileName -eq "")`
Results in error. 

Can you please allow us to filter for empty enrollmentProfileName? The goal here is to create working filter for Android Enterprise Fully Managed user devices.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c23357f-dd50-8ad1-084b-47ece285105f
* Version Independent ID: fa8f5486-8120-1548-a146-8f2e96995e9b
* Content: [Supported filter device properties and operators in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/filters-device-properties)
* Content Source: [memdocs/intune/fundamentals/filters-device-properties.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/filters-device-properties.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by msbemba** [comment]
@TechTrooper Thank you for your feedback. I was not able to search for empty value as well. Since this is more of a design change/feature request it needs to be routed to the appropriate team. I'd request you to provide this feedback in our main feedback portal - https://feedbackportal.microsoft.com/ so our Dev/product team member will be able to provide you more information.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@TechTrooper  Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
