### ISSUE TITLE
Create an Autopilot for existing devices Task Sequence - Mispelling

### ISSUE THREAD

**Issue by iamweasel658** [MicrosoftDocs/memdocs#2321]
Important

"TThe AutopilotConfigurationFile.json file will persist on the device across all future device wipes and resets. The only way for the JSON file to be fully removed is to perform a clean install of the operating system."

The is misspelled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cb0ab9e-0902-8c43-5cb9-8ade31c88f5f
* Version Independent ID: d30aebff-dc9c-bcd9-2ffd-c7158da55026
* Content: [Windows Autopilot Deployment for existing devices](https://docs.microsoft.com/en-us/mem/autopilot/existing-devices)
* Content Source: [memdocs/autopilot/existing-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/existing-devices.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by aczechowski** [comment]
Thanks @iamweasel658 for catching that! I'll fix it now.

In the future, I encourage you to submit simple changes like this yourself! 😄 For more info, see https://docs.microsoft.com/mem/use-docs#contribute
