### ISSUE TITLE
Only Polycom devices are excluded?!

### ISSUE THREAD

**Issue by tamirlevy** [MicrosoftDocs/memdocs#2322]
I wanted to verify if the limitation is only a docs mistake or I should contact someone specifically from the product since we mention "This requirement does NOT apply to Polycom Android-based Teams devices running 4.4. These devices will continue to be supported"
What about other Teams certified devices running Android OS lower than 9? not polycom but Lenovo or Yaelink? why aren't they excluded from this requirement as well? 
do we expect customer to replace all their Teams phones and prefer Polycom on other vendors?
in case we're not planning to add other vendors, how can customers exclude their Teams devices from App Protection Policies?
so that their personal devices will continue to require MAM but their Teams devices will sign-in without requiring MAM?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f70a020-9214-3316-5419-ee35ba6ff91a
* Version Independent ID: 9cc74430-af54-a2ac-7e4f-5a70b415c66e
* Content: [Operating systems and browsers supported by Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/supported-devices-browsers)
* Content Source: [memdocs/intune/fundamentals/supported-devices-browsers.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/supported-devices-browsers.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by MandiOhlinger** [comment]
@tamirlevy We definitely recommend working with the product team to answer your questions. When you get them, if there are specific doc updates that should be made, it'd be great if you created a pull request (PR) with your changes. If you need some guidance with creating the PR, ping me over Teams, and I'll help.

**Comment by tamirlevy** [comment]
Thanks Mandi
I've confirmed with @Ross Smith ***@***.***> who's one of the authors this is a mistake in our doc and it should be fixed
Not sure if I still need to create a PR for that

Regards,
Tamir Levy
Architect | Microsoft 365 FastTrack
***@***.******@***.***> | Mobile: +972 (52) 5991219
***@***.***

**Comment by MandiOhlinger** [comment]
@tamirlevy Yes - please create the pull request. Or, whomever you worked with can create the pull request.

**Comment by tamirlevy** [comment]
This is addressed in Article updates by smithre4 · Pull Request #6525 · MicrosoftDocs/memdocs-pr (github.com)<https://github.com/MicrosoftDocs/memdocs-pr/pull/6525>.

Ross
Sent from Outlook for Mac


From: Tamir Levy ***@***.***>
Date: Thursday, January 20, 2022 at 2:00 AM
To: MicrosoftDocs/memdocs ***@***.***>, MicrosoftDocs/memdocs ***@***.***>, Ross Smith IV ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [MicrosoftDocs/memdocs] Only Polycom devices are excluded?! (Issue #2322)
Thanks Mandi
I’ve confirmed with @Ross Smith ***@***.***> who’s one of the authors this is a mistake in our doc and it should be fixed
Not sure if I still need to create a PR for that

Regards,
Tamir Levy
Architect | Microsoft 365 FastTrack
***@***.******@***.***> | Mobile: +972 (52) 5991219
***@***.***

**Comment by tamirlevy** [comment]
Is this expected due to my permission to the pull requests?
[Graphical user interface, website  Description automatically generated]

**Comment by ross** [comment]
> I’ve confirmed with @ross Smith ***@***.***> who’s one of the authors this is a mistake in our doc and it should be fixed

The `@ross Smith` is not getting the ross you are intending and I'm getting cc'd on all of these notifications.

**Comment by MandiOhlinger** [comment]
@tamirlevy Thank you! I've signed off on the PR, and it should get merged sometime today.
