### ISSUE TITLE
The following .BAT file works well for me and might be an easier method for some.

### ISSUE THREAD

**Issue by EJ-W** [MicrosoftDocs/memdocs#2323]
[Enter feedback here]
The following .BAT file works well for me and might be an easier method for some.
(It leverages the same underlying technology and script, but is easy for me to run.)

@Echo Off
call powershell.exe -ExecutionPolicy ByPass -Command "$null=Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force"
call powershell.exe -ExecutionPolicy ByPass -Command "$null=Install-Script -Name Get-WindowsAutoPilotInfo -force"
call powershell.exe -ExecutionPolicy ByPass -Command "& $env:ProgramFiles\WindowsPowerShell\Scripts\Get-WindowsAutoPilotInfo.ps1 -OutputFile AutoPilotHWID.CSV">NUL
type AutoPilotHWID.CSV

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea4a659b-65d0-26ec-c36a-9a21a72a09a8
* Version Independent ID: bff44b73-9021-6659-e212-66349c759989
* Content: [Manually register devices with Windows Autopilot](https://docs.microsoft.com/en-us/mem/autopilot/add-devices)
* Content Source: [memdocs/autopilot/add-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/add-devices.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by frankroj** [comment]
Thank you for the feedback @EJ-W. I apologize for the time it took to get back to you regarding this feedback item. Unfortunately for security reasons we can't add user and community generated scripts into our docs. Any scripts added to our docs are developed internally and properly vetted to make sure they work in all supported scenarios. We do appreciate your suggestion though.
