### ISSUE TITLE
Content superseeded

### ISSUE THREAD

**Issue by enricogiacomin** [MicrosoftDocs/memdocs#2325]
Section "Add the app to Intune"

Sign in to Microsoft Endpoint Manager admin center, select Apps > All apps > Add.
In the App type drop-down box, **select Windows 10**.

The drop down menu has changed. Please update or I would suggest to replace the content to provision Microsoft Edge for Windows 10 and later. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 430077aa-292c-7627-9320-4e192f68246f
* Version Independent ID: 215b9820-81a6-1be5-adb2-e115b4e7a171
* Content: [Quickstart - Add and assign an app - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/quickstart-add-assign-app?source=docs)
* Content Source: [memdocs/intune/apps/quickstart-add-assign-app.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/quickstart-add-assign-app.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@enricogiacomin Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2661

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @enricogiacomin Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
