### ISSUE TITLE
Site Version mismatch ?

### ISSUE THREAD

**Issue by jemmail** [MicrosoftDocs/memdocs#2326]
Site Version mismatch (Wiki Page / in-console update description) :

Wiki Page : 5.00.906**0**.100**0**
Full Site Version :  5.00.906**8**.100**8**  in the in-console update description  (\Administration\Overview\Updates and Servicing)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b76ebf48-65a3-cf8b-a90b-9445bcac4971
* Version Independent ID: b76ebf48-65a3-cf8b-a90b-9445bcac4971
* Content: [Update for Microsoft Endpoint Configuration Manager version 2111 - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/hotfix/2111/12709700)
* Content Source: [memdocs/configmgr/hotfix/2111/12709700.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/configmgr/hotfix/2111/12709700.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @bhuney
* Microsoft Alias: **brianhun**

**Comment by aczechowski** [comment]
Thanks @jemmail for the feedback! @bhuney is going to update the article.

**Comment by aczechowski** [comment]
The article is updated, thanks again for the feedback
