### ISSUE TITLE
Missing Step?

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/memdocs#233]
How come these instructions don't include anything about setting the authority on https://endpoint.microsoft.com/#blade/Microsoft_Intune_DeviceSettings/TenantAdminMenu/tenantStatus page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b813a55b-0679-f80c-983f-782b394c748c
* Version Independent ID: ea738339-f10c-10f2-91ab-a2b87b342b12
* Content: [Tutorial: Enable co-management for existing clients - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/comanage/tutorial-co-manage-clients#configure-auto-enrollment-of-devices-to-intune)
* Content Source: [memdocs/configmgr/comanage/tutorial-co-manage-clients.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/comanage/tutorial-co-manage-clients.md)
* Product: **configuration-manager**
* Technology: **configmgr-comanage**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @DeanGross for the question. I don't think it is required for co-management setup, but I'm checking with the engineering team.

**Comment by aczechowski** [comment]
Hi @DeanGross, response from engineering:

> That’s going to depend on their starting point. Brand new subscription or any tenant set up and using Intune MDM or MAM there is no action.
>
> If they’re coming from another authority such as hybrid or MIFO then they would need to follow the guidance specific to their starting point.

Most customers are in the first bucket, so we're not going to make any changes to the article.
