### ISSUE TITLE
How to remove/disable the "Date Modified" field from Software Center 

### ISSUE THREAD

**Issue by anique9999** [MicrosoftDocs/memdocs#2335]
Hi,
Can you please tell me how can I disable the "Date Modified" field from the Software Center?
![image](https://user-images.githubusercontent.com/90675448/148772100-2413c87d-0bb8-4947-be73-da2e1a5819d4.png)

**Comment by aczechowski** [comment]
Thanks @anique9999 for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post on [Configuration Manager forums](https://docs.microsoft.com/answers/products/mem). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

Arguably we could have something in our content that explains this value more, but doesn't meet the bar right now. So I'm closing this issue.
