### ISSUE TITLE
MS Tunnel with LetsEncypt

### ISSUE THREAD

**Issue by khoenicke** [MicrosoftDocs/memdocs#2336]
Dear all,
I had a problem with my SAN Certificate, so I wanted to use Letsencypt.
Sadly this was not easy cause the Letsencrypt CA does crosssign and MSTunnel Setup does not like that. I needed to add --_preferred-chain "ISRG Root X1"_ to the certbot request.
Also the lifetime for a cert is only 90days.
But it is working with the code below
With the change of the crontab it should auto update the certificate and restart the MSTunnel service.

1. Allow Port 80 on Firewall 
2. run MSTunnel Setups once. Cancel Setup at certificates section
3.  run the code below
```
sudo snap install --classic certbot
sudo ln -s /snap/bin/certbot /usr/bin/certbot
sudo certbot certonly --standalone --preferred-challenges http --preferred-chain "ISRG Root X1"
sudo ln -s /etc/letsencrypt/live/mstunnel.nordmann.global/fullchain.pem /etc/mstunnel/certs/site.crt
sudo ln -s /etc/letsencrypt/live/mstunnel.nordmann.global/privkey.pem /etc/mstunnel/private/site.key
```
4. edit the crontab (like task scheduler in Windows)
`sudo crontab -e`
(choose e.g 1)
5. paste lines at the end. It will try to renew the certificate each Sunday at 02:00.
```
00 02 * * 0 /usr/local/sbin/certbot-auto renew
00 02 * * 0 /usr/sbin/mst-cli import_cert
00 02 * * 0 /usr/sbin/mst-cli server restart
```
6. strg +x (to exit editor)
7. y (to allow override)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4538f49d-8c19-9227-0acf-77bef7f8d4a8
* Version Independent ID: 1b1b2c40-1fd8-3909-37ae-05ab0d27efb5
* Content: [Install and configure the Microsoft Tunnel VPN solution for Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/microsoft-tunnel-configure)
* Content Source: [memdocs/intune/protect/microsoft-tunnel-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/microsoft-tunnel-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by CloudifiedLLC** [comment]
This was immensely helpful!  Thank you for sharing this information.

FYI, the certbot path for me was slightly different when configuring crontab:

/usr/bin/certbot renew
/usr/sbin/mst-cli import_cert
/usr/sbin/mst-cli server restart
