### ISSUE TITLE
"HKCU\Software\Policies\Microsoft\Office\16.0\Common\Security\Trusted Protocols" seems unsupported

### ISSUE THREAD

**Issue by billgatesfan** [MicrosoftDocs/memdocs#2337]
Hi, 

you are mentioning a registry key for Office group policy (HKCU\Software\Policies\Microsoft\Office\16.0\Common\Security\Trusted Protocols\All Applications\softwarecenter:) , but this key does not even exist in your most-recent ADMX group policy templates (I downloaded the latest ones from Dec 2021 and could not find any reference to "Common\Security\Trusted Protocols" string).

Does it mean this is an Office-unsupported registry hack?  

In case this key is still read by Outlook application, would it be a good idea to open a ticket to MS Office support, and ask why this setting is not visible neither in the ADMX templates, nor in your Intune MDM product? ;-) 

Thx!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7875c21-8d0e-4b0f-a2db-80db70851135
* Version Independent ID: 54bac3b1-ea92-8bb1-48c2-5a4adf8e2b4c
* Content: [Share applications in the Software Center - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/apps/deploy-use/share-applications)
* Content Source: [memdocs/configmgr/apps/deploy-use/share-applications.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/configmgr/apps/deploy-use/share-applications.md)
* Product: **configuration-manager**
* Technology: **configmgr-app**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @billgatesfan for the feedback! This tip was added a few years ago from a community contribution, and after review we think the best course of action is to remove it from the official product docs. If the security alert with Software Center is still an issue, please file [product feedback](https://docs.microsoft.com/mem/configmgr/core/understand/product-feedback) from the ConfigMgr console to raise it with the engineering team.
