### ISSUE TITLE
Document is dated and needs to be updated to be correct

### ISSUE THREAD

**Issue by austingsmith** [MicrosoftDocs/memdocs#2339]
using this document to walk through setting up intune, the instructions for expressions are incorrect.  I am not all the way completed with the document, however, this one part - that seems very important - has been changed in the actual process.  The documentation does not reflect the updated change.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97ce79c0-0014-f6f0-95f7-58574bfdefb3
* Version Independent ID: 40b3877e-a094-8d05-c95b-ca842c5ca8ce
* Content: [Create device groups for Windows Autopilot - Microsoft Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/autopilot/enrollment-autopilot)
* Content Source: [memdocs/autopilot/enrollment-autopilot.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/enrollment-autopilot.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by msbemba** [comment]
@austingsmith Thank you for your feedback. I found most of them to be accurate, however, the feature for Azure AD roles is not under preview. So We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2662

Once the author approves, the changes will be live.

Thanks
Sri
