### ISSUE TITLE
COPE is a supported enrollment profile in KME/Intune.

### ISSUE THREAD

**Issue by RHPhilipsen** [MicrosoftDocs/memdocs#2340]
In contrary to what is stated under the faq. COPE is currently supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91c6e4c4-96e2-14c6-8028-a2b947740e73
* Version Independent ID: 94bd0e7c-03c8-151d-6569-5d12985824e6
* Content: [Automatically enroll Android devices using Samsung's Knox Mobile Enrollment - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/android-samsung-knox-mobile-enroll)
* Content Source: [memdocs/intune/enrollment/android-samsung-knox-mobile-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/android-samsung-knox-mobile-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @RHPhilipsen Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
