### ISSUE TITLE
How to link Intune(MEM portal) to Azure portal from our team

### ISSUE THREAD

**Issue by stchien** [MicrosoftDocs/memdocs#2341]
Hi Intune team,
    We have the Azure subscription in Azure portal from our team, which cannot link to Intune(MEM portal). Do you know how? Any suggestion is appreciated!

Azure Subscription:  WER China Engineering

Resource Groups:
Resource Group	Owner
WER_Hailey	Steven

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c3f2675-9769-6b63-3ce8-3c7eb1c6c703
* Version Independent ID: bdd28d63-4fc5-6e2d-b54e-2225896ce493
* Content: [Sign up or sign in to Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/account-sign-up)
* Content Source: [memdocs/intune/fundamentals/account-sign-up.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/account-sign-up.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @stchien Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
