### ISSUE TITLE
Please Reference Resizing Guidance for Cloud PC Users Who Don't Have Access to Resize Function

### ISSUE THREAD

**Issue by michaelbunney** [MicrosoftDocs/memdocs#2343]
This page doesn't make clear that the Resize function is only available on Enterprise plans.  (This page is part of Enterprise documentation, but if you found it by web search you are looking only at the content, not the browseable navigation hierarchy of where it is stored.)

Also, it doesn't say what the alternative is if the Resize feature is not available.  Do you have to build a new Cloud PC from scratch and reinstall all software and files?  Or is there a way to back up the machine, reallocate it, and restore content?

Adding RAM or storage is a routine need, and Business (non-Enterprise) users need guidance on how to accomplish this with a Cloud PC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d40c7cfc-19e8-bfc7-5998-701fb4be40f2
* Version Independent ID: 1553fed2-80ac-ae21-1f87-1358bd34878d
* Content: [Resize a Cloud PC](https://docs.microsoft.com/en-us/windows-365/enterprise/resize-cloud-pc)
* Content Source: [windows-365/enterprise/resize-cloud-pc.md](https://github.com/MicrosoftDocs/memdocs/blob/main/windows-365/enterprise/resize-cloud-pc.md)
* Service: **cloudpc**
* Sub-service: ****
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
39259635
