### ISSUE TITLE
Info is more for iOS

### ISSUE THREAD

**Issue by cashxx** [MicrosoftDocs/memdocs#2347]
Under the MacOS section:  Info about restricting apps and links to bundle ids are more for iOS/iPadOS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce650df8-125e-4905-e54b-81cf4f893bbd
* Version Independent ID: b0764c62-d1a2-ea82-a7c4-98777e615b18
* Content: [macOS device settings in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-macos)
* Content Source: [memdocs/intune/configuration/device-restrictions-macos.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/device-restrictions-macos.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@cashxx Good point. Thank you! We added some macOS info to the article. The changes should be live later today or sometime tomorrow. 

If you see changes like this in the future, it'd be great if you created a pull request with your recommended changes. We want and encourage community contributions.

Thanks again!
