### ISSUE TITLE
Incomplete

### ISSUE THREAD

**Issue by ErikN78** [MicrosoftDocs/memdocs#2349]
This guide seems to be incomplete. There are only 6 steps mentioned in "Virtual machine scale set", although there are a lot more options/parameters that need to be set when creating a "Virtual machine scale set". Where is the rest of it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ade53de5-3c7a-669d-2786-41d14fb6cea8
* Version Independent ID: 036c9651-1adc-fdcb-7d67-32d212e574e5
* Content: [CMG server authentication certificate - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/server-auth-cert)
* Content Source: [memdocs/configmgr/core/clients/manage/cmg/server-auth-cert.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/configmgr/core/clients/manage/cmg/server-auth-cert.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @ErikN78, thanks for the feedback. A question for you: are you referring to the steps to determine a [globally unique name for the VM scale set](https://docs.microsoft.com/mem/configmgr/core/clients/manage/cmg/server-auth-cert#globally-unique-name), or in general how to set it up? The 6-step section in this article is specifically for how to check that the name is unique. The rest of the section has the overall steps on how to set up a CMG, as there are multiple steps involved.

Assuming that you're referring to how to make sure the name is unique, I literally have an email thread going right now with the feature team on this topic. So might have more info to share soon.

**Comment by aczechowski** [comment]
I did make changes to this article via #1883 to note that the key vault also needs to be globally unique. These changes will publish live with the 2203 current branch release. I'm closing this issue, if you have additional detail to add to this feedback, please comment back.
