### ISSUE TITLE
TPM Version

### ISSUE THREAD

**Issue by jiorblommaert** [MicrosoftDocs/memdocs#235]
Are there any requirements which TPM version a Windows 10 device must have when performing an automatic enrollment using group policy's?

(ACzechowski edit: adding metadata to what I think is the proper article)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f1e311c-c5ff-1c68-028d-e4fddda23324
* Version Independent ID: 1d2174e5-8984-8d9c-34c5-dfbcc619b410
* Content: [Set up enrollment for Windows devices by using Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/windows-enroll#enable-windows-10-automatic-enrollment)
* Content Source: [memdocs/intune/enrollment/windows-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/windows-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
(7261663)

**Comment by ErikjeMS** [comment]
@jiorblommaert Here's the response from the PM:
"There are no direct TPM requirements for Intune enrollments.  Autopilot does require TPM 2.0 for some scenarios (self-deploying and white glove).  You can refer to this link for more info:  https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/tpm-recommendations#tpm-and-windows-features"
