### ISSUE TITLE
Certificate encoding not specified

### ISSUE THREAD

**Issue by MarcLaf** [MicrosoftDocs/memdocs#2350]
The instructions say to export the root certificate in .CER format but the article does not say what encoding is needed. DER encoded binary or Base-64 encoded are two of the options given from Microsoft ADCS. Both can be exported with the .CER extension.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8028845-9342-149b-1fe8-e8bb1d5c1eb4
* Version Independent ID: b6cc3ec5-1eb4-07f4-8789-3be60ef73edd
* Content: [Create trusted certificate profiles in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/certificates-trusted-root)
* Content Source: [memdocs/intune/protect/certificates-trusted-root.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/certificates-trusted-root.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@MarcLaf    Hello Mark, after discussion with our developers and product PM team, I'm updating the content today to indicate the export should be as a DER-encoded .cer file.  This is the encoding format that has been tested and the product group will support.  I don't have visibility to plans to test Base-64 at this time or insight to any potential issues, but as its not yet tested, we can't list that in our docs at this time.    Thanks for asking this question!
