### ISSUE TITLE
Update doc to highlight important detail

### ISSUE THREAD

**Issue by chrisclime** [MicrosoftDocs/memdocs#2354]
Possible move this bullet item in the "Before you start" to a "Important" blue highlighted section:

Multiple required or available app assignments are not additive. A later app assignment will overwrite pre-existing installed app assignments. For example, if the first set of Office apps contains Word, and the later one does not, Word will be uninstalled. This condition does not apply to any Visio or Project applications.

This was overlooked our first implementation in the rest of the bullets and lead to issues with install/uninstall due to the way Md365 and Visio and Project were set up to deploy via Intune.   Since it can have such a drastic impact, and the Intune GUI allows you to create deployments that end up in this state.  Maybe move the bullet to a highlighted important bullet for more chances for it to be identified and followed.

Thanks
[](url)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fd6b61e-8f22-40cf-1827-d47a6b32ddc9
* Version Independent ID: 462829d9-6577-9f86-afff-9945abaa7b1c
* Content: [Add Microsoft 365 apps to Windows 10/11 devices using Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-add-office365#before-you-start)
* Content Source: [memdocs/intune/apps/apps-add-office365.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/apps-add-office365.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@chrisclime Thank you for your feedback. The document has been updated with the important note "Multiple required or available app assignments are not additive. A later app assignment will overwrite pre-existing installed app assignments." without the example.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @chrisclime Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
