### ISSUE TITLE
Missing information for whitelisting.

### ISSUE THREAD

**Issue by monoael** [MicrosoftDocs/memdocs#2357]
We have observed that while everything is working fine when we put the whitelistings in place, requesting a security code has a blocker as it requires this IP to be whitelisted "152.199.19.160".
 For remote help for intune.

**Comment by MandiOhlinger** [comment]
@monoael Hi - Which article? It'd be great if you created a pull request with your recommended changes. The steps are listed at [https://github.com/MicrosoftDocs/memdocs](https://github.com/MicrosoftDocs/memdocs). Scroll past the folder view.

**Comment by monoael** [comment]
@MandiOhlinger Thank you for your reply, the article is https://docs.microsoft.com/en-us/mem/intune/remote-actions/remote-help . The IP thought seems to point on some kind of CDN so I don't know if the IP will not change in the future.

I will proceed with creating a pull request.
