### ISSUE TITLE
MECM and Intune co-management, licensing requirements for devices?

### ISSUE THREAD

**Issue by c3rberus** [MicrosoftDocs/memdocs#236]
Can someone add a section to clearly outline the licensing requirements for co-management? If we are using ConfigMgr to manage our client machines, are we entitled to co-management with Intune without any additional cost or do we need to purchase Intune licensing for co-managed devices?

I see there is something mentioned about Azure AD Premium, just to confirm this means every user that is logging into the co-managed machine has to have Azure AD P1 assigned to their account?

**Comment by aczechowski** [comment]
Hi @c3rberus, we already have multiple items tracking this, so I'm closing this as a duplicate. I'm working with the feature PM and marketing team to further clarify.

- https://github.com/MicrosoftDocs/SCCMdocs/issues/2221
- https://github.com/MicrosoftDocs/memdocs/issues/148
- Internal work item 7202432

Currently available content:
- https://docs.microsoft.com/configmgr/core/understand/product-and-licensing-faq#bkmk_mem
- https://docs.microsoft.com/mem/configmgr/comanage/overview#prerequisites

**Comment by aczechowski** [comment]
I have a change for this issue in review, I hope it will publish in the next several days. The main tracking issue 2221 above should auto-close when the change merges, at which time it will publish within one business day.
