### ISSUE TITLE
clarification Licensing for Proactive remediations

### ISSUE THREAD

**Issue by tokar04** [MicrosoftDocs/memdocs#2361]
Would like a clarification on why Proactive remediations is not included in M365 Business Premium.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f003e4ec-77c1-80fd-1c19-51ee2c78595f
* Version Independent ID: 47b778f5-909a-7432-3da3-ee9afe24146b
* Content: [What is Endpoint analytics? - Microsoft Endpoint Manager](https://docs.microsoft.com/en-us/mem/analytics/overview#licensing-prerequisites)
* Content Source: [memdocs/analytics/overview.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/analytics/overview.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @tokar04 for taking the time to provide feedback on Endpoint Analytics! I talked with the PM for this feature, and there's not much to clarify, it was a business decision for the pricing. My best suggestion is to [file feedback](https://feedbackportal.microsoft.com/feedback/forum/4669adfc-ee1b-ec11-b6e7-0022481f8472) to let the product team know.

I'm closing this issue as there's nothing actionable for docs at this time.
