### ISSUE TITLE
Supported settings windows multi session OS

### ISSUE THREAD

**Issue by Egoorbis** [MicrosoftDocs/memdocs#2362]
Under https://docs.microsoft.com/en-us/mem/intune/fundamentals/azure-virtual-desktop-multi-session#configuration-issues the following is mentioend:

Configuration policy reports as Not applicable | Some policies are not applicable to Azure Virtual Desktop VMs. For a detailed list, review the documentation.

However no documentation is linked to which settings really are supported. Are they available somewhere?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 591d8748-ca94-f818-2ea3-9143b8e41697
* Version Independent ID: 7b0d2d80-8bf4-b9b6-7a2a-b0f3dc50a125
* Content: [Using Azure Virtual Desktop multi-session with Microsoft Intune (preview)](https://docs.microsoft.com/en-us/mem/intune/fundamentals/azure-virtual-desktop-multi-session)
* Content Source: [memdocs/intune/fundamentals/azure-virtual-desktop-multi-session.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/azure-virtual-desktop-multi-session.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @dougeby
* Microsoft Alias: **dougeby**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Egoorbis Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
