### ISSUE TITLE
Name Change Incosistency

### ISSUE THREAD

**Issue by JEmlay** [MicrosoftDocs/memdocs#2363]
When referring to the on-premises component:

    On first reference, use the full brand name: Microsoft Endpoint Configuration Manager

Then why does Microsoft to this very day continue to name the product System Center Configuration Manager 2022?  It's all still System Center and the sub product is Configuration Manager.

This back and forth with cloud products and on-premise naming conventions is getting old.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0847f1f-4207-1380-4c05-0b9b9b4bf6c9
* Version Independent ID: 0dd578d7-5a6d-482d-04d6-cc2b29f5b9ec
* Content: [Microsoft Endpoint Configuration Manager FAQ - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/understand/microsoft-endpoint-manager-faq)
* Content Source: [memdocs/configmgr/core/understand/microsoft-endpoint-manager-faq.yml](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/configmgr/core/understand/microsoft-endpoint-manager-faq.yml)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @JEmlay, thanks for asking. Can you let me know where you saw a reference to "System Center Configuration Manager 2022"? I don't think that's a thing.

**Comment by aczechowski** [comment]
Yep, confirmed it's not a thing. I found one reference in a System Center 2022 blog post that we're working to get removed. Sorry for the confusion. Please let me know if there are any other references.

I'm closing this issue as there's nothing we need to change in docs, what's in this article is current and accurate. (But please let me know of any other references that we can hunt down.)
