### ISSUE TITLE
Download the settings

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/memdocs#2366]
Hi, I thought you used to be able to download all the settings that get applied in a spreadsheet form but can't find it now. It would be really helpful if this page has a link to it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10ff4382-415c-4e80-e958-3bd77252fe2d
* Version Independent ID: 398a5b4b-e8bd-1f7d-ae30-38d812daf90d
* Content: [Intune security baselines settings for Microsoft Defender for Endpoint - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/security-baseline-settings-defender-atp)
* Content Source: [memdocs/intune/protect/security-baseline-settings-defender-atp.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/security-baseline-settings-defender-atp.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@thommck  If you find such a spreadsheet download, let us know! That isn't something our content team has previously published or had access to.  Nor has our product team provided that that I'm aware of. One thing you can do is from the Microsoft Endpoint Manager admin center UI is to select a profile for a baseline and then from its Per-setting status export those details.  Perhaps that is what your seeking?
