### ISSUE TITLE
Coud-PC devices

### ISSUE THREAD

**Issue by dbroughton79** [MicrosoftDocs/memdocs#2367]
Whats are coud-PC devices?

"Intune’s remote action to Collect diagnostics will soon collect additional details from Windows 365 (Coud-PC) devices. (Devices > Windows > select a Windows 365 device > Collect diagnostics)"

(admin edit - add article metadata for proper linkage)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66f915d1-8486-44dc-a605-280f979d6f9b
* Version Independent ID: 23c6b2c3-64c1-2df3-ad51-d9be083871a1
* Content: [In development - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/in-development)
* Content Source: [memdocs/intune/fundamentals/in-development.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/in-development.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @dougeby
* Microsoft Alias: **dougeby**

**Comment by aczechowski** [comment]
Thanks @dbroughton79 for catching that. I fixed the typo to "Cloud PC"
The update should publish later this afternoon.
