### ISSUE TITLE
Be good to have an ETA or a tracking reference for the DeviceStatus CSP issue with Windows 10 Home

### ISSUE THREAD

**Issue by uowdaniel** [MicrosoftDocs/memdocs#237]
It might be helpful to have some idea of timescale, or at least a reference to somewhere that has one, to expand on:
"The DeviceStatus CSP for Antivirus isn’t supported for Windows 10 Home and reports a status of Not applicable. The Intune team is working on a fix."
and
"The DeviceStatus CSP for Antispyware isn’t supported for Windows 10 Home and reports a status of Not applicable. The Intune team is working on a fix."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 979d9182-7aa8-9a97-399b-2a495164f1a7
* Version Independent ID: b293cc1c-53ce-d06f-c991-a0f1a27214fc
* Content: [Windows 10 compliance settings in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/compliance-policy-create-windows#feedback)
* Content Source: [memdocs/intune/protect/compliance-policy-create-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/compliance-policy-create-windows.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@uowdaniel  I hear you. Unfortunately, we can't provide that guidance. As active work, investigation must complete, code revisions be tested, and then a release time or update cycle be leveraged. At this stage there's too much variance for us to provide that. From what I've gleaned from our developers, I think this _could_ be resolved with next months update (In June).
