### ISSUE TITLE
Please provide a document or process for enabling filters to view the device enrollment page.

### ISSUE THREAD

**Issue by ImaBadCoder** [MicrosoftDocs/memdocs#2370]
/Snip

 Note

You must enable filters to view the device enrollment page. Report data is only available for devices enrolled after the Microsoft Intune 2112 service release. No results are available for devices enrolled prior to that release. This page is not available for Android devices.
/snip

Would love to have an explanation and maybe a link to better understand the requirements and next steps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e8c2d91-8808-a504-da13-526b152a5cfe
* Version Independent ID: 037b60a6-d6b5-75ad-1933-39d0f7a69048
* Content: [Set enrollment restrictions in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/enrollment-restrictions-set)
* Content Source: [memdocs/intune/enrollment/enrollment-restrictions-set.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/enrollment-restrictions-set.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @ImaBadCoder, thank you for reaching out to the Docs team. I added a link in that note to the filters how-to documentation. It will be live later this week.
