### ISSUE TITLE
CSV schema detail in FAQ is not precise

### ISSUE THREAD

**Issue by dctardy** [MicrosoftDocs/memdocs#2371]
In the CSV schema section of this doc the section that lists a limit to the number of devices is not consistent with the limit for manual uploads.  The following two docs clearly state the limit of 500 for the manual import through Intune while other methods have the 1000 limit.  Please update this FAQ to be consistent.

https://docs.microsoft.com/en-us/mem/autopilot/add-devices#ensure-that-the-csv-file-meets-requirements

https://docs.microsoft.com/en-us/mem/autopilot/manual-registration#platforms-for-device-registration

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1b12323-90a7-00db-16ea-8daec3a9306f
* Version Independent ID: 0c1a1865-cf35-0862-b328-02371bb30441
* Content: [Windows Autopilot FAQ](https://docs.microsoft.com/en-us/mem/autopilot/autopilot-faq#csv-schema)
* Content Source: [memdocs/autopilot/autopilot-faq.yml](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/autopilot-faq.yml)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by frankroj** [comment]
Thank you for the feedback @dctardy. I apologize for the time getting back to you on this feedback. This document was recentely corrected to indicate 500 instead of 1000.
