### ISSUE TITLE
Bug in UI for Dynamic Rules

### ISSUE THREAD

**Issue by MarcLaf** [MicrosoftDocs/memdocs#2372]
In the section for creating a dynamic rule such as (device.devicePhysicalIds -any _ -eq "[OrderID]:179887111881"), the UI will stick an extra " in if you're building it via rule builder (the dropdowns). This will result in an invalid rule and will squawk when saving. Suggest to add a note in document stating you should paste it directly into the rule syntax text box and not use the rule builder.

Please pass this onto the Azure AD team if possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f93dd93-e003-36fc-02d6-07166537d914
* Version Independent ID: 1b860d13-bcf5-50da-89f9-ee12ece6edb2
* Content: [Enrollment for hybrid Azure AD-joined devices - Windows Autopilot](https://docs.microsoft.com/en-us/mem/autopilot/windows-autopilot-hybrid#install-the-intune-connector)
* Content Source: [memdocs/autopilot/windows-autopilot-hybrid.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/windows-autopilot-hybrid.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MarcLaf Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
