### ISSUE TITLE
Steps under Plan section for CMG role removal

### ISSUE THREAD

**Issue by stewmang** [MicrosoftDocs/memdocs#2374]
Hi

The steps around removing roles, specifically for CMG, are unclear. Does this mean the CMG itself needs to be removed prior to CAS removal or is it referring to the Cloud Management Gateway Connection Point role, or both?

I logged a case with Premier Support and have been told that because the Cloud Management Gateway Connection Point is installed at the Primary Site in our environment, the CMG itself does not need to be removed.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7afe8fcc-7879-de1a-31ee-9686db58d0a9
* Version Independent ID: 6791e866-a02f-bd12-3d5f-90ee1a18cde4
* Content: [Remove CAS - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/install/remove-central-administration-site)
* Content Source: [memdocs/configmgr/core/servers/deploy/install/remove-central-administration-site.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/configmgr/core/servers/deploy/install/remove-central-administration-site.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by MdMeera** [comment]
Hi @stewmang , I understand from your post that CAS Removal will move the CMG ownership from CAS to standalone primary while reconfiguring Service Connection Point Role. Correct me if that is true. 

I don't think we don't need to re-deploy CMG from Primary after CAS removal.

**Comment by stewmang** [comment]
Hi

Yes that's what I'm asking, does the CMG role need to be removed prior to
collapsing the CAS then redeployed from the Primary site.

Thanks

**Comment by aczechowski** [comment]
I made a change to clarify, it will publish with the 2203 release
