### ISSUE TITLE
Preview status out of date?

### ISSUE THREAD

**Issue by RichardGallo-MS** [MicrosoftDocs/memdocs#2376]
In the section of this article [here](https://docs.microsoft.com/en-us/mem/intune/enrollment/enrollment-restrictions-set?source=docs#create-a-device-platform-restriction-preview)

It states it's in preview. However, this feature has been available for some time now and there is nothing in the actual Endpoint Manager UI that says preview, so it's confusing to customers as to whether or not it's actually in Preview. Is it possible to confirm if it is in Preview still and, if not, update the page to remove Preview from the title?

Thanks so much!
-Richard Gallo, Customer Engineer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e8c2d91-8808-a504-da13-526b152a5cfe
* Version Independent ID: 037b60a6-d6b5-75ad-1933-39d0f7a69048
* Content: [Set enrollment restrictions in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/enrollment-restrictions-set?source=docs#create-a-device-platform-restriction-preview)
* Content Source: [memdocs/intune/enrollment/enrollment-restrictions-set.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/enrollment-restrictions-set.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @RichardGallo-MS, thanks for reaching out to docs! Enrollment restrictions are still in preview as of today. They are supposed to be generally available with the next service release, so I'll remove the tag from docs as soon as that happens.
