### ISSUE TITLE
Update Intune/JAMF Integration Documentation

### ISSUE THREAD

**Issue by nov-26** [MicrosoftDocs/memdocs#2377]
Hi,

While integrating Jamf Pro and Intune recently, we noticed that the Microsoft documentation could use a few updates.

In the **Prerequisites** section
- There is no mention of the AAD Administrator roles required to perform the integration from the Microsoft side. We found varying success with the Cloud Application Administrator role, but in the end we needed to call in a Global Administrator for the integration to be successful. This is useful as not all administrators will have the correct permissions.

In the **Create an application in Azure Active Directory** section
- When adding the required API permissions for the integration, the Microsoft documentation only mentions the **Intune API**. We found that the integration would not work with the Intune API on its own, and requires the Microsoft Graph and Windows Azure Active Directory APIs also. Jamf has this documented under Step 1 in their documentation (https://docs.jamf.com/technical-papers/jamf-pro/microsoft-intune/10.34.0/Manually_Configure_the_Connection_Between_Jamf_Pro_and_Microsoft_Intune.html)

In the **Configure Microsoft Intune Integration in Jamf Pro** section
- The **Open administrator consent URL** step is missing from the Microsoft documentation. This is listed in Step 3 of the Jamf documentation (https://docs.jamf.com/technical-papers/jamf-pro/microsoft-intune/10.34.0/Manually_Configure_the_Connection_Between_Jamf_Pro_and_Microsoft_Intune.html)
- There is no mention of the **Sovereign Cloud** option and what to select

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54745d43-7151-b13a-57f6-7329856e5d2b
* Version Independent ID: 07d2ffd1-49b6-3046-cc07-a4aa35e4fe61
* Content: [Integrate Jamf Pro with Microsoft Intune for compliance - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/conditional-access-integrate-jamf)
* Content Source: [memdocs/intune/protect/conditional-access-integrate-jamf.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/conditional-access-integrate-jamf.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@nov-26 Thank you for the feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2626

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @nov-26 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
