### ISSUE TITLE
Lack of information on more interesting domain scenarios

### ISSUE THREAD

**Issue by James-Noble** [MicrosoftDocs/memdocs#2379]
At the bottom of this article I was expecting more information on scenarios such as off-domain machines and machines joined to a separate domain or forest, with or without a trust relationship.

I assume none of these scenarios will work correctly because Azure AD Connect is limited to connecting a single domain/forest to Azure AD.  Until this restriction is resolved (if it ever will be), our organisation can't take advantage of this approach.  It would be useful if this document gave or linked to information on what approach would work in these scenarios.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b166b931-f3f7-3323-7288-758cfa5934f1
* Version Independent ID: b166b931-f3f7-3323-7288-758cfa5934f1
* Content: [Use Microsoft Defender for Endpoint Security Configuration Management in Microsoft Endpoint manager](https://docs.microsoft.com/en-us/mem/intune/protect/mde-security-integration)
* Content Source: [memdocs/intune/protect/mde-security-integration.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/mde-security-integration.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by yogkumgit** [comment]
@Brenduns Please help us in resolving this issue. Thanks

**Comment by Brenduns** [comment]
@james-noble  Thanks for your feedback on this. I’ve also shared your thoughts with our product group.
As to the current state of this scenario, there remains a reliance on the trust to the Azure AD tenant where MDE is hosted. As of yet, there has not been deep investigation alternatives for this scenario sufficient to drive content.  Should that change, we’ll update the docs to reflect that, though there is nothing committed to this in the foreseeable future.
