### ISSUE TITLE
Rephrase sentence for clarity?

### ISSUE THREAD

**Issue by fswgm** [MicrosoftDocs/memdocs#2381]
The sentence below could probably use a bit of clarification:
"Devices that are not Azure AD joined or hybrid Azure AD-joined are evaluated as not applicable."

I initially read that as devices not joined to AAD, OR those that are hybrid joined, are evaluated as not applicable, which disagrees with the point above it on the page.

Suggested phrasing: 

"Devices that are neither Azure AD joined or hybrid Azure AD-joined are evaluated as not applicable." 

or 

"Devices that are not Azure AD joined or are not hybrid Azure AD-joined are evaluated as not applicable."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cc5f200-8f38-ec2d-d05e-d76828ce0cef
* Version Independent ID: 4cc5f200-8f38-ec2d-d05e-d76828ce0cef
* Content: [Use custom compliance settings in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/compliance-use-custom-settings)
* Content Source: [memdocs/intune/protect/compliance-use-custom-settings.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/compliance-use-custom-settings.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@fswgm  Thank you for this feedback.  The content was updated shortly after this issue was submitted, but we failed to close the loop with you on that.   You'll find the updated language aligns to your second suggestion.
