### ISSUE TITLE
Bundle ID of Sunmi

### ISSUE THREAD

**Issue by syuu0202** [MicrosoftDocs/memdocs#2383]
_com.sunmi.oemconfig.V2**5**_ should be _com.sunmi.oemconfig.V2**S**_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fea6e079-c3f1-8fde-1af5-4f23efb19c86
* Version Independent ID: da471838-5729-f1d8-2218-f778bc47ff11
* Content: [Use OEMConfig on Android Enterprise devices in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/configuration/android-oem-configuration-overview)
* Content Source: [memdocs/intune/configuration/android-oem-configuration-overview.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/android-oem-configuration-overview.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@syuu0202 Thank you! This is fixed. The changes should be live sometime today. In the future, for changes like this, it'd be great if you created a pull request with your recommended changes. For the steps, go to [https://github.com/MicrosoftDocs/memdocs](https://github.com/MicrosoftDocs/memdocs), and scroll past the folder view.

We want and appreciate the help. Thanks again!
