### ISSUE TITLE
I think Step 8 is wrong

### ISSUE THREAD

**Issue by svenhallauer** [MicrosoftDocs/memdocs#2385]
I'm pretty certain that for Autopilot to work the MDM user scope needs to be set, but the MAM user scope doesn't.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adbfe90c-635e-5d23-f0b3-2d015565e311
* Version Independent ID: bcc85788-87a8-c3b5-1b60-a4938a09e541
* Content: [Quickstart - Set up automatic enrollment in Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/quickstart-setup-auto-enrollment)
* Content Source: [memdocs/intune/enrollment/quickstart-setup-auto-enrollment.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/quickstart-setup-auto-enrollment.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@svenhallauer Thank you for your feedback.  While is not mandatory to select the scope for MAM, Many productivity apps, such as the Microsoft Office apps, can be managed by Intune MAM. It is also used to manage data on your workforce's devices.

I don't think we need to remove the step as it is still an option available under All services > M365 Azure Active Directory > Azure Active Directory > Mobility (MDM and MAM).

@yogkumgit No changes are needed on the document for now.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @svenhallauer Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
