### ISSUE TITLE
Please clarify vTPM on Intune

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/memdocs#2389]
It has passed several years, when Hyper-V Server and Azure VM's started supporting "secure mode", including "secure boot" and "vTPM".

Please justify, does Intune/MDM support, or does not support, Windows 10 and Windows 11 with VMs for using TPM when using BitLocker ? Or as secure boot compliance or configuration requirement.

In Gen 2 virtual machines with they have normally working TPM which is also visible in local System Information

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 681e9efc-3d61-6ab6-c6e8-ece46c6272ba
* Version Independent ID: 9850a321-96e5-dd67-db61-64549d9c715d
* Content: [Using Windows 10 virtual machines with Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/windows-10-virtual-machines#configuration)
* Content Source: [memdocs/intune/fundamentals/windows-10-virtual-machines.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/windows-10-virtual-machines.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by yogkumgit** [comment]
@Smritib17 Please help us in resolving this issue. Thanks

**Comment by Smritib17** [comment]
@yogkumgit, the article has been updated.

**Comment by hkusulja** [comment]
Sorry, but where it is documented, what is referral, that Autopilot requires physical TPM and does not work with vTPM ? it should be normally working and from my test it also normally works on Windows 10 with VM with Windows 10 and Gen 2...

**Comment by Smritib17** [comment]
The following articles include a note - Configuration and compliance policies for Secure Boot and features leveraging vTPM (Virtual Trusted Platform Module) are not supported at this time for Azure Virtual Desktop VMs.

https://docs.microsoft.com/en-us/mem/intune/fundamentals/azure-virtual-desktop
https://docs.microsoft.com/en-us/mem/intune/fundamentals/azure-virtual-desktop-multi-session
