### ISSUE TITLE
Clarify limitations

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/memdocs#2390]
Please check with product group and update page with limitations.

Scenario: Azure Virtual Desktop with Azure VM's Gen2 supporting vTPM and Secure Boot.
Does Intune MDM support then Secure Boot with vTPM for compliance scenario or is it limitation applied?

Kind regards
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c838c69f-95e7-e3de-25e6-6e52f43edf77
* Version Independent ID: 9f3dd8bf-d060-5ccf-e8a8-9fc10d619b58
* Content: [Using Azure Virtual Desktop single-session with Microsoft Endpoint Manager](https://docs.microsoft.com/en-us/mem/intune/fundamentals/azure-virtual-desktop)
* Content Source: [memdocs/intune/fundamentals/azure-virtual-desktop.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/azure-virtual-desktop.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by yogkumgit** [comment]
@Smritib17 Please help us in resolving this issue. Thanks

**Comment by Smritib17** [comment]
@yogkumgit, the article has been updated.
