### ISSUE TITLE
URL for Microsoft Update Catalog is incorrect

### ISSUE THREAD

**Issue by rossmpersonal** [MicrosoftDocs/memdocs#2392]
The page says the URL for the Microsoft Update Catalog is https:\\catalog.update.microsoft.com . https:\\catalog.update.microsoft.com is not the correct URL for the Microsoft Update Catalog . Please correct the page to say the correct URL for the Microsoft Update Catalog . I believe the correct URL for the Microsoft Update Catalog is https://catalog.update.microsoft.com but I'm not sure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0150e043-d08d-bb83-e39a-7f27ba25198f
* Version Independent ID: fb88957c-9a3d-9cc8-c11a-c131c5137f56
* Content: [Configure classifications and products - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/sum/get-started/configure-classifications-and-products)
* Content Source: [memdocs/configmgr/sum/get-started/configure-classifications-and-products.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/configmgr/sum/get-started/configure-classifications-and-products.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @rossmpersonal for the feedback, looks like a simple typo with incorrect slashes. Although when I copy and paste the address, it still works 😉 But I'll fix it up right now.
