### ISSUE TITLE
the instructions on this page are wrong

### ISSUE THREAD

**Issue by CrazyDymond88** [MicrosoftDocs/memdocs#2393]
This document is incorrect.  Cloud PC's have a device type of "Virtual Machine" not "Cloud PC"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b79c826-85e2-155c-331b-81f127d9fb93
* Version Independent ID: 14f49025-4d41-d08d-4cb3-d2feba6b8d66
* Content: [Create a dynamic device group for all Cloud PCs](https://docs.microsoft.com/en-us/windows-365/enterprise/create-dynamic-device-group-all-cloudpcs)
* Content Source: [windows-365/enterprise/create-dynamic-device-group-all-cloudpcs.md](https://github.com/MicrosoftDocs/memdocs/blob/main/windows-365/enterprise/create-dynamic-device-group-all-cloudpcs.md)
* Service: **cloudpc**
* Sub-service: ****
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
39259529

**Comment by ErikjeMS** [comment]
@CrazyDymond88 Here's the response from the PM: 
Since Octoberish, we've been setting the Device Model to match the license of the created Cloud PC. Can you confirm confirm when you provisioned or to see if you can reprovision so they can get this desired behavior.

**Comment by ErikjeMS** [comment]
Closing issue.
