### ISSUE TITLE
0x87D3013A Intune dmg

### ISSUE THREAD

**Issue by BorisKornienko** [MicrosoftDocs/memdocs#2395]
I got error 0x87D3013A in .dmg install. Not in dmg install errors list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85d01df7-5b63-f6bf-e310-5f4afec1c36b
* Version Independent ID: 85d01df7-5b63-f6bf-e310-5f4afec1c36b
* Content: [Add a macOS DMG app to Microsoft Intune](https://docs.microsoft.com/En-Us/mem/intune/apps/lob-apps-macos-dmg)
* Content Source: [memdocs/intune/apps/lob-apps-macos-dmg.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/lob-apps-macos-dmg.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by annerajb** [comment]
Same here specifically on the google drive dmg

**Comment by Alslinet** [comment]
Same issue but with anyconnect.

**Comment by Kazzan** [comment]
Yes, Cisco AnyConnect Client 4.10 versions throw the same errors or "Content cannot be downloaded".

**Comment by djarya86** [comment]
I am getting the same error message for the Absolute package. 

I also got the same error message when I wrapped the Adobe for macOS intune. 

I found this, but it didn't help me with my issue. 

https://docs.microsoft.com/en-us/troubleshoot/mem/intune/error-0x87d13ba2-deploy-macos-lob-app

**Comment by msbemba** [comment]
@BorisKornienko Thank you for your feedback. I have added information about this to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2632 

If the error is still not fixed, I'd recommend you contact Microsoft support via the need help section on the admin center.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @BorisKornienko Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
