### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by PaulEdlund** [MicrosoftDocs/memdocs#2399]
[Enter feedback here]
When I'm on this page and click on the following link, I get the error: "We are sorry, the page you requested is temporarily unavailable."
https://www.microsoft.com/windows-365/enterprise/compare-plans-pricing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 695c2e9d-4fe9-dbe2-102c-72f97d7fe8bd
* Version Independent ID: dab608ec-0f8c-7605-b232-6e9929fb1183
* Content: [Assign licenses for Windows 365](https://docs.microsoft.com/en-us/windows-365/enterprise/assign-licenses)
* Content Source: [windows-365/enterprise/assign-licenses.md](https://github.com/MicrosoftDocs/memdocs/blob/main/windows-365/enterprise/assign-licenses.md)
* Service: **cloudpc**
* Sub-service: ****
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@PaulEdlund Thanks! Looks like they moved that info to here: https://www.microsoft.com/en-us/windows-365/all-pricing

I'll update this doc page later today.
