### ISSUE TITLE
Entities vary between consoles

### ISSUE THREAD

**Issue by dridley23** [MicrosoftDocs/memdocs#2405]
How come the entities available in OnPrem ConfigMgr are different to the entities available in Tenant Attach (and vice versa)?
eg FileContent not available in Tenant Attach

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0b43530-0bd6-e050-0db7-ce62ee0445f6
* Version Independent ID: 03bbca1d-d022-bf6a-e717-ad7f583c5686
* Content: [Tenant attached CMPivot usage overview - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/tenant-attach/cmpivot-overview-attached)
* Content Source: [memdocs/configmgr/tenant-attach/cmpivot-overview-attached.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/configmgr/tenant-attach/cmpivot-overview-attached.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @dridley23 for taking the time to provide feedback on Configuration Manager! There are a handful of CMPivot entities that are only available on-premises. For more info, see [Additional entities, operators, and functions for CMPivot from Configuration Manager](https://docs.microsoft.com/mem/configmgr/core/servers/manage/cmpivot-overview#bkmk_onprem_only).

I suggest you file [product feedback](https://feedbackportal.microsoft.com/feedback/forum/4669adfc-ee1b-ec11-b6e7-0022481f8472) to let the engineering team know of your interest in having that entity available in the admin center. That also allows other customers to upvote the feedback.

I'm closing this issue as there's nothing actionable for docs at this time.
