### ISSUE TITLE
Password Manager default

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/memdocs#2411]
The default for the following setting seems contradictory to Microsoft's overall messaging on passwords:
**_Enable saving passwords to the password manager** Microsoft Edge CSP: [Browser/AllowPasswordManager](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-browser#browser-allowpasswordmanager)_

Microsoft (and many other orgs) embrace the use of password managers to stop people re-using passwords. Is there a way to highlight this on the doc or feedback to the baseline team? It seems odd to have the default setting turn off a valuable feature

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96f97bff-7548-846a-026d-8eda5e94da45
* Version Independent ID: 377b6f76-fec1-a55e-157a-d2db7060b56b
* Content: [Intune security baselines settings for Microsoft Edge - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/security-baseline-settings-edge?pivots=edge-sept-2020)
* Content Source: [memdocs/intune/protect/security-baseline-settings-edge.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/security-baseline-settings-edge.md)
* Service: **microsoft-intune**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@thommck  Thanks for this feedback. The baselines are provided by the relevant product security teams, so I've passed this feedback to our Intune product team via the PM for this area, who in turn can work with the source of the baselines that Intune makes available. With that feedback passed on, I'll be closing this issue. However, should I receive information to share back to you about this, I can still update you via an @ to your alias posted in this feedback issue.
