### ISSUE TITLE
Check vcredist installation on Secondary Site before launching the upgrade process on it

### ISSUE THREAD

**Issue by daves83** [MicrosoftDocs/memdocs#2418]
Starting from last two release of CM, Microsoft Visual C ++ 2015-2019 redistributable version 14.28.29914.0 is a prerequisite. As reported in the What’s new documentation ([link](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/changes/whats-new-in-version-2107#updated-visual-c-prerequisite)), the VCRedist is installed automatically on the primary site and on the secondary site during the installation process; in this upgrade checklist, it is not indicated to install anything during the Secondary Site upgrade procedure and this cause the upgrade to fail with the following error: -1073741701 (hex: 0xC000007B) if the vcredist is not installed.

If this is not a bug related to the upgrade procedure, would it be possible to insert in the documentation to install vcredist before launching the secondary site upgrade procedure?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36e62ca5-32b6-14a9-dfdf-06398d4f8d2d
* Version Independent ID: 36e62ca5-32b6-14a9-dfdf-06398d4f8d2d
* Content: [Checklist for 2111 - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/manage/checklist-for-installing-update-2111)
* Content Source: [memdocs/configmgr/core/servers/manage/checklist-for-installing-update-2111.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/configmgr/core/servers/manage/checklist-for-installing-update-2111.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @daves83 thanks for the feedback. I got the same feedback the other day from an MVP (perhaps one and the same?)
Please file a frown from the console to get the issue submitted to the engineering team. If it turns out the behavior is accurate and the docs are wrong, that filed issue can help engineering confirm. Then we can reopen this issue and/or repurpose the filed issue as a doc bug to update this doc.
