### ISSUE TITLE
Confusing actions for troubleshooting custom compliance

### ISSUE THREAD

**Issue by GenerAhl** [MicrosoftDocs/memdocs#2419]
Under the Troubleshooting heading it says "To see errors related to the PowerShell script, add the following line to the end of the PowerShell script file: return $hash | ConvertTo-Json -Compress" yet, on the requirements page for the Powershell script (https://docs.microsoft.com/en-us/mem/intune/protect/compliance-custom-script) it says "Must include the following line at the end of the script: return $hash | ConvertTo-Json -Compress".

If the Powershell script is required to have the "return $hash | ConvertTo-Json -Compress" at the end, there's no point in asking the user to add it for troubleshooting? It's already there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cc5f200-8f38-ec2d-d05e-d76828ce0cef
* Version Independent ID: 4cc5f200-8f38-ec2d-d05e-d76828ce0cef
* Content: [Use custom compliance settings in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/compliance-use-custom-settings?source=docs)
* Content Source: [memdocs/intune/protect/compliance-use-custom-settings.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/compliance-use-custom-settings.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@GenerAhl  Thanks for the feedback.  While not creating a critical conflict, the one instance does suggest that script line might be optional, where per the other doc, and what I understand - it's expected to be present. 

I've updated the line to reinforce the expectation that line is present in the troubleshooting section, and removed the working that suggests it's an optional line to add.  With this change we can help someone who uses this troubleshooting section and isn't seeing the expected details, without them having to revisit the initial custom script requirements in the other article to puzzle that out. 

That will update in content later today.
