### ISSUE TITLE
Domain Join profile steps is incorrect

### ISSUE THREAD

**Issue by jerryabo** [MicrosoftDocs/memdocs#2422]
Profile type for Domain Join profile now requires selecting Profile type: Templates, then selecting Domain Join.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f93dd93-e003-36fc-02d6-07166537d914
* Version Independent ID: 1b860d13-bcf5-50da-89f9-ee12ece6edb2
* Content: [Enrollment for hybrid Azure AD-joined devices - Windows Autopilot](https://docs.microsoft.com/en-us/mem/autopilot/windows-autopilot-hybrid)
* Content Source: [memdocs/autopilot/windows-autopilot-hybrid.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/windows-autopilot-hybrid.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by jerryabo** [comment]
![2022-02-04 18_26_09-Microsoft Endpoint Manager admin center - Create a profile - Microsoft Endpoint ](https://user-images.githubusercontent.com/94194023/152620407-4e694dc2-5757-4bc0-b620-d0cf5f48081e.png)

**Comment by msbemba** [comment]
@jerryabo Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2633

Once the author approves, the changes will be live.

Thanks
Sri
