### ISSUE TITLE
retire apps from service link

### ISSUE THREAD

**Issue by JDFlannery** [MicrosoftDocs/memdocs#243]
this link goes to - https://docs.microsoft.com/en-us/mem/intune/remote-actions/device-management not to anything to do with Retire apps from service. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ba0a531-62e8-d924-7601-2cd73c817aad
* Version Independent ID: 93256b46-514e-74f6-c2ea-757e03590fb6
* Content: [Overview of the app lifecycle for Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-lifecycle)
* Content Source: [memdocs/intune/apps/app-lifecycle.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-lifecycle.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@JDFlannery - Thanks for the feedback. I'm updating the link now. This should be publish tomorrow morning.
