### ISSUE TITLE
`Learn more` wrong item link

### ISSUE THREAD

**Issue by UniverseCitiz3n** [MicrosoftDocs/memdocs#2430]
Hey,
I've noticed that in section **Remote Management**, config policy **Block client digest authentication**

`Learn more` hyperlink points to wrong **Policy CSP** source.

Currently it is -
https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-remotemanagement#remotemanagement-disallownegotiateauthenticationclient

I think that `Learn more` should link to - https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-remotemanagement#remotemanagement-disallowdigestauthentication

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f0f4d5d-fdd1-22e7-6372-9916b199209f
* Version Independent ID: caeb9f8b-30ad-7f02-4740-56522b2f9b1b
* Content: [Intune security baselines settings for Windows 10/11 MDM - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/security-baseline-settings-mdm-all)
* Content Source: [memdocs/intune/protect/security-baseline-settings-mdm-all.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/security-baseline-settings-mdm-all.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@UniverseCitiz3n   Thanks for this feedback. I've passed this on to my Intune product group contact for this area, who will then follow up with the Windows team, the source of that baseline.  

I agree with what you point out.  However, what the correct setting name/description, and linked CSP combination should be isn't yet clear.  But in reviewing that I do see that the setting name and its information text both align to the CSP you note, not to the CSP its link goes to.  So this is more than a bad link. There is something to be sorted and updated. 

I'll close this feedback issue for now, but should I receive confirmation of the correct setting, I'll reply back via this same issue with an update. And of course, if there ais a change I can mitigate via content until the baseline updates, I'll publish those once the dust settles.  Any changes in the baseline would come from the Windows team, and I have zero visibility to that process.
