### ISSUE TITLE
How does Hybrid Azure AD join affect this method? 

### ISSUE THREAD

**Issue by richard-artes** [MicrosoftDocs/memdocs#2431]
How does Hybrid Azure AD join affect this method? Do you need to add the CNAME records for Hybrid AD Join?
Thanks
Richard.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f1e311c-c5ff-1c68-028d-e4fddda23324
* Version Independent ID: 1d2174e5-8984-8d9c-34c5-dfbcc619b410
* Content: [Set up enrollment for Windows devices by using Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/windows-enroll#enable-windows-10-automatic-enrollment)
* Content Source: [memdocs/intune/enrollment/windows-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/windows-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@richard-artes Thank you for your feedback. Deploying Hybrid AD join devices by using intune and windows autopilot is different from this document. 

We have a another document which talks about that in detail -https://docs.microsoft.com/en-us/mem/autopilot/windows-autopilot-hybrid

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @richard-artes Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
