### ISSUE TITLE
Question regarding Broker apps

### ISSUE THREAD

**Issue by jasonkatz424** [MicrosoftDocs/memdocs#2433]
Hello,

On step 2 under "How app-based Conditional Access with Intune" works, it is written:

" The broker app can be either the Microsoft Authenticator for iOS, or the Microsoft Company portal for Android devices.

To clarify, can the broker app be either Microsoft Authenticator or the Company Portal for iOS?  Or only the Authenticator app for iOS and only the Company Portal app for Android devices?

Just want to make sure that this is accurate in that the only broker app permissible for iOS is the Company Portal App.

Thank you

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca76fcaf-979f-7b6b-c410-34080685d415
* Version Independent ID: eaceac76-73c4-c586-952c-8dfa90390c6e
* Content: [App-based Conditional Access with Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/app-based-conditional-access-intune)
* Content Source: [memdocs/intune/protect/app-based-conditional-access-intune.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/app-based-conditional-access-intune.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@jasonkatz424 Thank you for your feedback. There is a slight change in the broker app as it can be the Microsoft Authenticator for iOS, or either the Microsoft Authenticator or Microsoft Company portal for Android devices. I have updated the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2634

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by jasonkatz424** [comment]
Thank you!

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jasonkatz424 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
