### ISSUE TITLE
Conflicting statements about BYOD scenarios

### ISSUE THREAD

**Issue by VathekVan** [MicrosoftDocs/memdocs#2436]
There are conflicting statements in the article:

`Microsoft Intune supports two Android deployment scenarios for bring-your-own-device (BYOD):`

vs

`Android Enterprise personally-owned work profiles are the core Android Enterprise deployment scenario and the **only** scenario targeted at BYOD use cases.`

Can someone reconcile or clarify the contradiction?

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ed3c68e-46ea-bd65-ae42-f5caea1697b7
* Version Independent ID: 90042f91-f826-0797-7221-14ef24ca5076
* Content: [App protection policies and Android Enterprise personally-owned work profiles in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/android-deployment-scenarios-app-protection-work-profiles)
* Content Source: [memdocs/intune/apps/android-deployment-scenarios-app-protection-work-profiles.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/android-deployment-scenarios-app-protection-work-profiles.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@VathekVan Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2635

Once the author approves, the change will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
