### ISSUE TITLE
Resource Providers for VMSS

### ISSUE THREAD

**Issue by dereklangMSFT** [MicrosoftDocs/memdocs#2437]
Just a suggestion, in regards to the specific resource providers needed for Virtual Machine Scale Set, even though we do have the link on this page, it would be helpful to list them directly on the page for extra visibility since it is a complete blocker if the customer attempts to create or upgrade their CMG and these are missing:

When converting or creating a new virtual machine scale set, register following resource providers before starting the process:

Microsoft.KeyVault
Microsoft.Storage
Microsoft.Network
Microsoft.Compute

Thanks!

**Comment by aczechowski** [comment]
Thanks @dereklangMSFT for filing this feedback, I'm using #2434 to track this change. You can subscribe to that issue for notifications, and/or add more information there as necessary. I'm closing this one.
