### ISSUE TITLE
MAM-WE Windows BYOD application management

### ISSUE THREAD

**Issue by mushmasha** [MicrosoftDocs/memdocs#2438]
Hello!

In MAM WE deployment guide it will be very useful to add a Note that it is not possible to deploy Windows Applications to BYOD Windows devices with MAM WE, because All Windows app types require enrollment (https://docs.microsoft.com/en-us/mem/intune/apps/apps-windows-10-app-deploy).

The lines of "Direct users to the Company Portal web site at portal.manage.microsoft.com. When they sign in with their organization credentials, they see a list of apps, including required apps. They can get the apps from this site" and "Go to the Company Portal web site at portal.manage.microsoft.com, and sign in with their organization credentials (user@contoso.com). Once signed in, they see a list of available apps, including required apps." can be confusing, since for Windows BYOD devices this will not work like described for MAM-WE scenario  until device is enrolled to MDM.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27e8db50-59e4-79a2-5d93-933457b4175f
* Version Independent ID: 1af97289-d517-d893-299e-7eb505d64dbb
* Content: [MAM-WE device enrollment guide for  Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/deployment-guide-enrollment-mamwe)
* Content Source: [memdocs/intune/fundamentals/deployment-guide-enrollment-mamwe.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/deployment-guide-enrollment-mamwe.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by yogkumgit** [comment]
@MandiOhlinger Please help us in resolving this issue. Thanks

**Comment by MandiOhlinger** [comment]
@mushmasha Good catch! Thank you. We added that info. Changes should be live later today.
