### ISSUE TITLE
Documentation outdated

### ISSUE THREAD

**Issue by JLangthaler** [MicrosoftDocs/memdocs#2439]
The documentation in this part is severely outdated: https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policies-monitor

The mentioned reports refer to paths in the Endpoint Manager admin center that do not exist anymore (e.g. "select Apps > App protection status > Reports", which nowadays would be Apps --> Monitor --> App Protection Status.
Furthermore, the screenshots are not from the current admin center (endpoint.microsoft.com) and should be updated to reflect the GUI that has been in use for years.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5778af76-6c42-fbea-b07b-dc001749732a
* Version Independent ID: 4f0cc443-bd3e-dfdf-1fba-f35e9bb3f87f
* Content: [How to monitor app protection policies - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policies-monitor)
* Content Source: [memdocs/intune/apps/app-protection-policies-monitor.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/app-protection-policies-monitor.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@JLangthaler Thank you for your feedback. I could locate the reports under Apps > App protection status > Reports and I'm able to test this in multiple tenants.

![image](https://user-images.githubusercontent.com/45987684/162684304-e1c6cf05-beba-4b5c-b621-cbf3c4bb5079.png)

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@JLangthaler Thank you for your feedback. Sorry about the delay. We have made changes via PR#https://github.com/MicrosoftDocs/memdocs/pull/2663

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @JLangthaler Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
