### ISSUE TITLE
Correction for Configuration Manager control panel applet

### ISSUE THREAD

**Issue by dereklangMSFT** [MicrosoftDocs/memdocs#2440]
This note should say 'Network tab' instead of Internet tab:

Note
The Internet tab is available only if the client has a client PKI certificate.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9aeb5c91-a34d-46e9-bcba-695f12081a28
* Version Independent ID: 69bc3a9d-9f52-6e0f-e884-69c706269999
* Content: [Deploy clients to Windows - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/deploy/deploy-clients-to-windows-computers)
* Content Source: [memdocs/configmgr/core/clients/deploy/deploy-clients-to-windows-computers.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/configmgr/core/clients/deploy/deploy-clients-to-windows-computers.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @dereklangMSFT for the feedback. I'll put in a change for this now. In the future, you can submit this contribution yourself by using the **Edit** option. 😄 For more info, see https://docs.microsoft.com/en-us/mem/use-docs#contribute

**Comment by dereklangMSFT** [comment]
Will use the Edit option for small changes in the future, thanks Aaron.

Derek Lang
Support Escalation Engineer
Modern Work – Microsoft Endpoint Manager
(469) 775-0607
***@***.******@***.***>
Microsoft Premier Support: (800) 936-3100

 ***@***.***
