### ISSUE TITLE
About the phrase "fully managed work profile"

### ISSUE THREAD

**Issue by Ikuko-Konno** [MicrosoftDocs/memdocs#2445]
In the "For company-owned devices" section of "Android Enterprise", it is described as "Only apps installed in the Android Enterprise fully managed work profile".
We recognize that this means that only apps installed within the work profile on the "Android Enterprise personally owned work profile device" will be detected.

The phrase "fully managed work profile" can easily be confused with an Android Enterprise fully managed device, so please correct the phrase.

Best Regards,
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2f41921-6680-75b6-5b95-55327279861a
* Version Independent ID: a0178c17-b82b-b762-49f6-17e2abcbd775
* Content: [Discovered apps - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-discovered-apps#details-of-discovered-apps)
* Content Source: [memdocs/intune/apps/app-discovered-apps.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/app-discovered-apps.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@Ikuko-Konno Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2640

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Ikuko-Konno Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
