### ISSUE TITLE
Link to UpdateChannel values doesn't have values

### ISSUE THREAD

**Issue by JakeMoe** [MicrosoftDocs/memdocs#2448]
In the section "[Check the Office registry keys](https://docs.microsoft.com/en-us/mem/configmgr/sum/deploy-use/manage-office-365-proplus-updates#bkmk_channel)", it mentions that values can be found here: https://docs.microsoft.com/en-us/mem/configmgr/sum/deploy-use/manage-office-365-proplus-updates#bkmk_channel

However, when I follow that link, I can't find the value in my registry, nor anything similar: http://officecdn.microsoft.com/pr/55336b82-a18d-4dd6-b5f6-9e5095c314a6

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401bfab7-6edd-0852-65f5-b8dd28585bab
* Version Independent ID: 0cba6ac6-486c-447c-85cb-c0e6a927d983
* Content: [Update Microsoft 365 using administrative templates in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/configuration/administrative-templates-update-office)
* Content Source: [memdocs/intune/configuration/administrative-templates-update-office.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/administrative-templates-update-office.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @JakeMoe Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
