### ISSUE TITLE
Install and Bind Certificates section

### ISSUE THREAD

**Issue by OffColour** [MicrosoftDocs/memdocs#245]
https://docs.microsoft.com/en-us/mem/intune/protect/certificates-scep-configure#install-and-bind-certificates-on-the-server-that-hosts-ndes
This section needs expanding on how to get the certificate. Everything else on the pages walks through perfectly in great detail and then this part leaves the reader rather lost.

I've just found this https://techcommunity.microsoft.com/t5/intune-customer-success/support-tip-how-to-configure-ndes-for-scep-certificate/ba-p/455125 which seems to cover the missing items. Would be great to get this incorporated.

https://docs.microsoft.com/en-us/mem/intune/protect/certificates-scep-configure#to-configure-a-value-that-can-be-set-from-within-the-intune-console

I don't think bullet points 2 and 3 are related to modifying the validity period and need to be done in all cases.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9107185-e6c7-b178-4e22-819797fe4880
* Version Independent ID: 1153b441-94f0-b471-52a2-3cf556c68581
* Content: [Configure infrastructure to support SCEP certificate profiles with Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/certificates-scep-configure#create-the-scep-certificate-template)
* Content Source: [memdocs/intune/protect/certificates-scep-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certificates-scep-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@OffColour   Thanks for this feedback.. Where I thought I'd be able to tackle this before now, previous backlog and new release work has continued to push this back.  It doesn't' appear that we'll be able to get to this soon.  Therefore I've created a tracking bug in my own work queue backlog so we can properly evaluate and track this ask for future work.  

As I can't provide an ETA for when we might be able to act, please consider contributing to the docs directly yourself. If your interested in direct doc contributions, take a look at our on-line [Contributors Guide](https://docs.microsoft.com/en-us/contribute/) to learn how.
