### ISSUE TITLE
Issue with links

### ISSUE THREAD

**Issue by JeffsRealm** [MicrosoftDocs/memdocs#2458]
[Enter feedback here]
Still need help? Contact your IT support person. For contact information, check the [Company Portal website](https://go.microsoft.com/fwlink/?linkid=2010980).

Link doesn't work well it might but not for everyone. So the link redirects to commercial which I have not commercial accounts. So I am not sure where this is going. It is hidden under a go.microsot.com link which takes you to a log in. What I am logging into I do not know as it never takes me there. The reason I say this I am in GCC High and DOD which have different URLS for azure. 

I can ususally correct this if I know what the path is, so for example if it is going to enpoint.microsoft.com I can change the url to endpont.microsoft.us however this URL is completely hidden. 

Could you please update either the shortcut to poin t directly to where it needs to go or add rediectly links to the GCC, GCC High etc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a38eb4e-ff5e-2d73-a85f-73e9d2b3a541
* Version Independent ID: c49e17c5-9565-87f2-6e4f-2f099ca18329
* Content: [How to update the Company Portal app](https://docs.microsoft.com/en-us/mem/intune/user-help/install-a-new-version-of-the-company-portal-app)
* Content Source: [memdocs/intune/user-help/install-a-new-version-of-the-company-portal-app.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/install-a-new-version-of-the-company-portal-app.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@JeffsRealm Thank you for your feedback. The URL for the company portal would be https://portal.manage.microsoft.com/

Microsoft uses a go.microsoft.com/fwlink in documents for the Admin center and other Microsoft product-related URLs. That is why you do not see the exact URL in the document.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @JeffsRealm Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
