### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by PaulKlerkx** [MicrosoftDocs/memdocs#2462]
Might be worth mentioning in this section.  
"Process to convert a CMG to a virtual machine scale set"

The Feature "Cloud Managment Gateway with Azure VM scale set" must be enabled or the "convert" button does not appear.  

Microsoft feedback gave me that answer when I mentioned I was missing the button in MECM 2111.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12ab4165-870a-9fea-872a-35c03d2ba338
* Version Independent ID: b9015594-b05d-05dd-ef03-a99c3a4be225
* Content: [Modify a CMG - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/modify-cloud-management-gateway#process-to-convert-a-cmg-to-a-virtual-machine-scale-set)
* Content Source: [memdocs/configmgr/core/clients/manage/cmg/modify-cloud-management-gateway.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/configmgr/core/clients/manage/cmg/modify-cloud-management-gateway.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @PaulKlerkx for the feedback. A good tip to include.

**Comment by aczechowski** [comment]
This note will be added when the content is updated for the 2203 current branch release. Thanks again for the feedback.

**Comment by aczechowski** [comment]
(Internal reference 13180442)
