### ISSUE TITLE
Internet Endpoints missing for Azure Services

### ISSUE THREAD

**Issue by Ayelsama** [MicrosoftDocs/memdocs#2463]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a9e88a5-bc7d-4982-4564-ceea80bde0e7
* Version Independent ID: 817824fe-5b44-ebeb-75c4-9eeb2dfa13ce
* Content: [Internet access requirements - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/network/internet-endpoints#feedback)
* Content Source: [memdocs/configmgr/core/plan-design/network/internet-endpoints.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/configmgr/core/plan-design/network/internet-endpoints.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by Ayelsama** [comment]
Internet Endpoints needed to configure cloud-attach(probably needed for all Azure services as well), not mentioned explicitly on the docs:
**portal.office.com and portal.azure.com**

**Comment by aczechowski** [comment]
Thanks @Ayelsama for the feedback. I don't think any ConfigMgr component programatically needs access to those URLs. They are just for admins from administrative workstations. That list of URLs that admins would need access to is likely a long one, and not something we want to try to include.
