### ISSUE TITLE
Incorrect App version

### ISSUE THREAD

**Issue by chiners68** [MicrosoftDocs/memdocs#2465]
This line of text is incorrect, the current version is 10.0.22467.1000

**The most recent version of remote help is 10.0.10011.16384**

can you also provide a change log to display what has changed in versions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bc62c89-a452-0d3f-01f3-c5982803809e
* Version Independent ID: 6bc62c89-a452-0d3f-01f3-c5982803809e
* Content: [Remotely assist users that are authenticated by your organization.](https://docs.microsoft.com/en-us/mem/intune/remote-actions/remote-help)
* Content Source: [memdocs/intune/remote-actions/remote-help.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/remote-help.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by yogkumgit** [comment]
@Zephyrusg Thank you very much for the contribution and updating the documentation with PR. @chiners68 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
