### ISSUE TITLE
User logon type: Azure AD user or group

### ISSUE THREAD

**Issue by MarkusMory** [MicrosoftDocs/memdocs#2467]
The User logn type for Azure AD user or group is not well described.  What exactly happens if you choose one ore more users or even a hole AAD group. If you choose multiple accounts which Azure AD user will automatically sign in? 

Thank you for your support.

Markus

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97b3556b-5cb1-2eeb-e793-5efff254ddd7
* Version Independent ID: 16117a39-76b5-a7ef-7aa5-86678fe38013
* Content: [Kiosk settings for Windows 10/11 in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/configuration/kiosk-settings-windows#feedback)
* Content Source: [memdocs/intune/configuration/kiosk-settings-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/kiosk-settings-windows.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by msbemba** [comment]
@MarkusMory Thank you for your feedback. If you choose multiple accounts,  the list of user accounts added will be able to automatically sign in. The same goes for groups. All users part of the group will be able to sign in automatically.

Hope this helps!

Thanks
Sri

**Comment by MarkusMory** [comment]
@msbemba Thank you for your response. But I must admit it doesn't really explain it.
Let's say I configure User1 for automatic logon. I would expect that I turn on the computer and after Windows is booted User1 is automatically logged on. But if I configure User1 and User2 for automatic logon. Which one is going to be logged in after the computer booted?

Thank you very much

**Comment by msbemba** [comment]
@MarkusMory  Thank you for your feedback. The user has to sign in with the credentials for login. They will be prompted to sign in, unlike auto logon. users added via Azure AD user or groups will be able to sign in to the Kiosk. Maybe the word automatically created ambiguity.

Hope this helps!

Thanks
Sri

**Comment by MarkusMory** [comment]
@msbemba  Thank you for the clarification.

Have a nice day.

Markus
