### ISSUE TITLE
Taxomony for security configuration link

### ISSUE THREAD

**Issue by JakeMoe** [MicrosoftDocs/memdocs#2468]
This document links to a GitHub site for "[a new taxonomy for security configuration](https://github.com/microsoft/SecCon-Framework)".  This doc has been updated rather recently, however the GitHub repo hasn't been updated in 3 years.  Is it still current and / or valid?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d9a11b1-ff48-8c1e-9dbe-c48a7e4dc350
* Version Independent ID: 6bd15450-157a-e2e8-c636-e692c7ff6e81
* Content: [Data protection framework using app protection policies - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-framework)
* Content Source: [memdocs/intune/apps/app-protection-framework.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/app-protection-framework.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @JakeMoe Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
