### ISSUE TITLE
This needs to be bolded please

### ISSUE THREAD

**Issue by wowwser69** [MicrosoftDocs/memdocs#247]
For devices that are not enrolled in Intune, the Company Portal app must be installed on the device. However, the user does not have to launch or sign into the Company Portal app before they can use apps that are managed by app protection policies.

The Company Portal app is a way for Intune to share data in a secure location. Therefore, the Company Portal app is a requirement for all apps that are associated with app protection policies, even if the device is not enrolled in Intune.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7de3e51f-1f77-d105-3e67-3c56d2d9927b
* Version Independent ID: a929eff9-1635-f09d-9f01-2eb4a21a67a5
* Content: [Android apps with app protection policies](https://docs.microsoft.com/en-us/mem/intune/fundamentals/end-user-mam-apps-android#feedback)
* Content Source: [memdocs/intune/fundamentals/end-user-mam-apps-android.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/end-user-mam-apps-android.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
@wowwser69 Thank you for your feedback and I'll share with the docs team that you'd like this info to pop/stand out more. Closing this issue as there are no content changes to make now.
