### ISSUE TITLE
Add M365BP to licences that include Endpoint Analytics

### ISSUE THREAD

**Issue by greg-youthorizons** [MicrosoftDocs/memdocs#2473]
Please add Microsoft 365 Business Premium to the list of licences that includes Endpoint Analytics.
The service description lists Endpoint Analytics as available for this licence.
https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWR6bM

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d35a1251-2323-4239-85d7-ca21f44cf93a
* Version Independent ID: d8bd22fc-6af5-075f-ecee-bb084483bbce
* Content: [Tutorial - Proactive remediations - Microsoft Endpoint Manager](https://docs.microsoft.com/en-us/mem/analytics/proactive-remediations#licensing)
* Content Source: [memdocs/analytics/proactive-remediations.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/analytics/proactive-remediations.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @greg-youthorizons for the feedback. I checked with the feature PMs, this question has come up before and the result was the first paragraph of the main [licensing prerequisites section in the enroll Intune devices article](https://docs.microsoft.com/mem/analytics/enroll-intune#licensing-prerequisites):

> Devices enrolled in Endpoint analytics need a valid license for the use of Microsoft Endpoint Manager.

As linked from this article.

It's arbitrary to explicitly add M365 BP to the list, as Intune is included in [over 10 different licensing bundles](https://docs.microsoft.com/mem/intune/fundamentals/licenses).
