### ISSUE TITLE
Powershell example

### ISSUE THREAD

**Issue by mpartes** [MicrosoftDocs/memdocs#2494]
SettingDefinitions display name might have changed

$desiredSettingDefinition = $settingDefinitions.value | ? {$_.DisplayName -Match "Silently sign in users to the OneDrive sync client with their Windows credentials"}

no longer works as displayname "Silently sign in users to the OneDrive sync **app** with their Windows credentials"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f187188e-9838-b9ca-fdde-9dd3cbd5ba00
* Version Independent ID: 75de9a7f-098b-58c6-279c-61e5f31efcc6
* Content: [Walkthrough - Create administrative template in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/configuration/tutorial-walkthrough-administrative-templates)
* Content Source: [memdocs/intune/configuration/tutorial-walkthrough-administrative-templates.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/tutorial-walkthrough-administrative-templates.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by msbemba** [comment]
@mpartes Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2667

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @mpartes Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
