### ISSUE TITLE
Best practices for configuring BitLocker for Intune

### ISSUE THREAD

**Issue by o0MattE0o** [MicrosoftDocs/memdocs#2496]
why is there no best practices? or are you stating by looking at this article the best practices is not configured?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54cccf1d-81fd-5331-aee7-59a35b39cb15
* Version Independent ID: 81d14392-fe74-4fd9-047f-7b8292d84f0c
* Content: [Encrypt Windows devices with BitLocker in Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/encrypt-devices)
* Content Source: [memdocs/intune/protect/encrypt-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/encrypt-devices.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@o0MattE0o   Thanks for the feedback.  While Intune policies are one of several methods to manage BitLocker on devices, there are many possible scenarios for why to use different settings or configurations. As such, this type of Windows Security guidance is beyond the scope of Intune as a management tool to provide. Instead, I recommend you start with the guidance provided by the Windows Security team which owns the BitLocker technology.  One starting place is [Windows guidance for BitLocker](https://docs.microsoft.com/windows/security/information-protection/bitlocker/bitlocker-management-for-enterprises) in the Windows security documentation. What I can do is update this article later today to add a link to that Windows content.
