### ISSUE TITLE
Audit logs for Sessions Requested using TeamViewer connected to Intune - Feature Request

### ISSUE THREAD

**Issue by timkmsft** [MicrosoftDocs/memdocs#2498]
My client is looking for guidance on the logging in TeamViewer for the Remote Assistance which have been integrated into Intune. Since there is a connector, is it not possible to do logging/auditing to show the status of sessions initiated or ended etc. 
We can see that Teamviewer is logging the events, however, those logs can only be exported via CSV and the client would like to have those brought either into Endpoint Manager, or by preference into Sentinel.
Is this possible? Thank you kindly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a9ef909-c4fb-f052-9d2e-c794efc9efd7
* Version Independent ID: 655e8b80-0471-5789-8bf1-20403390c012
* Content: [Remotely administer devices in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/remote-actions/teamviewer-support)
* Content Source: [memdocs/intune/remote-actions/teamviewer-support.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/teamviewer-support.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@timkmsft Thank you for your feedback. I have tested and does not look like we have an option to inject the logs to Sentinel or to Endpoint manager. However, since this is a new feature request you can provide these details through the main feedback portal and our Dev/Product team will look into it.

Main feedback portal- https://feedbackportal.microsoft.com/
Hope this helps!

Thanks
Sri

**Comment by timkmsft** [comment]
Ah great, thank you very much Sri. I have opened a feedback request and hopefully its something that other customers may also want to see.
Much appreciated.
