### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by SabRom** [MicrosoftDocs/memdocs#25]
Hello, the "Enroll your Windows device in Intune" link lead up to a 404 page, please correct it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f1e311c-c5ff-1c68-028d-e4fddda23324
* Version Independent ID: 1d2174e5-8984-8d9c-34c5-dfbcc619b410
* Content: [Set up enrollment for Windows devices by using Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/windows-enroll#feedback)
* Content Source: [memdocs/intune/enrollment/windows-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/windows-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@SabRom Thanks! I'll fix the link.
