### ISSUE TITLE
Enhanced Startup PIN for BitLocker 

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/memdocs#250]
Are you able to configure Azure AD Joined devices to use an Enhanced Startup PIN - e.g. alphanumeric via Intune?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f2a095c-452e-c494-a013-0626b9f3728d
* Version Independent ID: a4787d69-187f-fe55-d071-3a37b9b082e9
* Content: [Protection settings for Windows 10 devices in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/endpoint-protection-windows-10#bitlocker-base-settings)
* Content Source: [memdocs/intune/protect/endpoint-protection-windows-10.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/endpoint-protection-windows-10.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@thommck  This isn't a setting that Intune can configure today. There might be technical reasons under the covers, but I've not been able to confirm more about that yet.  If something comes up in the days ahead - I'll update you via this same GitHub issue. 

As its not an option today, you might consider submitting an [Intune User Voice](https://microsoftintune.uservoice.com/forums/291681-ideas) request to add in this capability. The product group regularly reviews, triages and acts on user voice submissions.
