### ISSUE TITLE
No explaination of copy asset detail feature

### ISSUE THREAD

**Issue by tbiles** [MicrosoftDocs/memdocs#2501]
[This section](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/manage/admin-console-tips#copy-details-in-monitoring-views) explains the existence of a feature that I discoverd by accident.  However, the section does not explain the contents you get when copying the data from the asset detail pane.  In my case, it shows a list of systems that were non-compliant for a given deployment of a configuration baseline.  When I copied the data and pasted to a text editor, it appears that there is list of csv records, but there is no header or anything to explain what is in each field.  Some fields can be deduced from the content (like the asset name) but others are not obvious (like yes or no types of strings).

It would be helpful to have an explaination of what type of data is being copied (either in the help in the app, or on this page).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7abd33f-b2b5-a194-fcbf-afbd0c9a5430
* Version Independent ID: adf34189-82be-78cb-2db4-3d66fe891a06
* Content: [Console changes and tips - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/manage/admin-console-tips)
* Content Source: [memdocs/configmgr/core/servers/manage/admin-console-tips.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/configmgr/core/servers/manage/admin-console-tips.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by tbiles** [comment]
I discovered after some further investigation that there are extra columns in the asset detail window that are hidden by default.  After turning those columns on, there are labels for each of the data fields that show up which make the csv Copy output make more sense.

So, technically, the information is there, it just isn't intuitive how to "find" it.  I would like to see the documentation link expanded to explain that a bit more, or not have so much data hidden by default so it is more obvious that the data isn't a single column of server names which is sort of what is implied by the view.

**Comment by aczechowski** [comment]
Thanks @tbiles for the feedback. I think this is probably best routed through the engineering team to either expose all columns by default, or only export the columns that are shown. To do that, see [Product feedback](https://docs.microsoft.com/mem/configmgr/core/understand/product-feedback).

If you want to add something about this to the doc, please submit a contribution. For more info, see [How to contribute to docs](https://docs.microsoft.com/mem/use-docs#contribute).
