### ISSUE TITLE
SQL License section should be corrected

### ISSUE THREAD

**Issue by ddubs1** [MicrosoftDocs/memdocs#2502]
The license section should be clarified to specify only a standard license is covered.   This issue comes up when a customer has to use enterprise because they want to use SQL always on
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f3023a8-ab6c-1d77-0111-77cc7583347c
* Version Independent ID: 26debf60-c3c1-caa6-7f78-a04a8b8e73af
* Content: [Product and licensing FAQ - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/understand/product-and-licensing-faq)
* Content Source: [memdocs/configmgr/core/understand/product-and-licensing-faq.yml](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/configmgr/core/understand/product-and-licensing-faq.yml)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @ddubs1, there's some history here. For more info, see https://github.com/MicrosoftDocs/memdocs/issues/965#issuecomment-722028851 and other older issues linked there.
