### ISSUE TITLE
Unable to wipe Apple Silicon (M1) Macbook Pro using intune

### ISSUE THREAD

**Issue by RedVortex** [MicrosoftDocs/memdocs#2503]
Intune erase/wipe doesn't work as expected for Apple Macbook M1 Pro devices enrolled in intune. It works for Intel-based devices but not Apple Silicon ones. I'm running Monterey 12.2.1

You trigger the wipe, the interfaces says "Wipe Pending..." but nothing happens on the device.

I see that the "Company Portal" isn't logged anymore but the "Profiles" all remain under System Preferences. If I manually remove the "Management Profile" that seems to trigger the wipe as the Macbook immediately rebooted and I saw that the OS was indeed wiped.

So, unless the user cooperate with you to complete the remote wipe, this is not working for Apple M1 Pro device under Monterey 12.2.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f756249-1cd7-0a08-6e99-c5f5add14b21
* Version Independent ID: 3749a819-5ab0-d5c1-cee0-162db2951949
* Content: [Erase a macOS device - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/remote-actions/device-erase)
* Content Source: [memdocs/intune/remote-actions/device-erase.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/device-erase.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by RedVortex** [comment]
I completely reinstalled everything and wiped it again, this time the device got deleted properly from intune. Not sure what happened on the first wipe that ended up in failed instead of deleted.

**Comment by msbemba** [comment]
@RedVortex Thank you for your feedback. This could have been a bug at that time when you reported the issue. I'm glad that it is working fine now. In case, the issue reoccurs you can report it directly to our Support team via the need help section on the admin center so that they can verify if this is a bug or an ongoing issue.

Hope this helps!

Thanks
Sri
