### ISSUE TITLE
Using variables in File Path results in "Invalid regEx format"

### ISSUE THREAD

**Issue by MarcLaf** [MicrosoftDocs/memdocs#2511]
Under **Microsoft Defender Firewall Rules** > **Application Settings** > **File Path** there are two examples given. A literal path of C:\Windows\System\Notepad.exe and one using a system variable of %WINDIR%\Notepad.exe. If you use a system variable when crafting the firewall rules, the UI gives an error of "Invalid regEx format" without indicating how to properly use a variable.

Please update documentation (or UI tooltip) to indicate how to properly use system variables in the File Path.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 788dd3b1-947d-937b-6375-cf0f0a071fab
* Version Independent ID: 22b5d531-34d4-837a-84f9-88bc78b0042f
* Content: [Intune endpoint security firewall settings](https://docs.microsoft.com/en-us/mem/intune/protect/endpoint-security-firewall-profile-settings)
* Content Source: [memdocs/intune/protect/endpoint-security-firewall-profile-settings.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/endpoint-security-firewall-profile-settings.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by yogkumgit** [comment]
@Brenduns Please help us in resolving this issue. Thanks

**Comment by Brenduns** [comment]
@MarcLaf    Helo Marc, for that setting, I'll be updating the docs later today remove the system variable example. The settings are beholden to the CSP and don't provide functionality they don't include. Today, I see the CSP this is based on (found at https://docs.microsoft.com/windows/client-management/mdm/firewall-csp#filepath) doesn't document the path with a variable example. 

I will also be requesting our product team to review the details in the UI. Those should now be pulled directly from the CSP information, and what is in the UI today clearly doesn't.  

 Of note, the content you've referenced will not apply to the new platform/profiles for Firewall policies that [recently replaced the previous profile templates](https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new#new-profile-templates-and-settings-structure-for-endpoint-security-policies).  But, as the older profiles remain supported, that content still requires an update. 

While the settings/CSPs are the same as before, we don't provide docs specific to the new profiles (though are working on something for that), as the UI text, setting name, and options are all taken directly from the CSP's which own the content and behaviors.  (or in the case of this setting, should have been!)   

cc @yogkumgit
