### ISSUE TITLE
Supervised enhanced security has recommendation for "personal" device. Shouldn't this be supervised/company-owned?

### ISSUE THREAD

**Issue by brsieff** [MicrosoftDocs/memdocs#2513]
In the verbiage below, I believe Supervised enhanced security (Level 2) should say: 
Level 2 is the recommended configuration for **supervised** devices where users access more sensitive information. 

Current verbiage:
Supervised enhanced security (Level 2)
Level 2 is the recommended configuration for **personal** devices where users access more sensitive information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4c41392-9a7e-593b-ce89-290b28692faa
* Version Independent ID: 48ff272a-996c-035b-e16c-d5f1e483c668
* Content: [iOS/iPadOS supervised device security configurations - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/ios-ipados-supervised-device-security-configurations)
* Content Source: [memdocs/intune/enrollment/ios-ipados-supervised-device-security-configurations.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/ios-ipados-supervised-device-security-configurations.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by brsieff** [comment]
Hello, any updates?

**Comment by brsieff** [comment]
Assigned for almost 3 weeks and might be a just a slight change in language and still no update.... sad 👎

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @brsieff Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
