### ISSUE TITLE
Supervised device settings are listed under Personal Device Security Configuration

### ISSUE THREAD

**Issue by v-rechau** [MicrosoftDocs/memdocs#2515]
Under Personal Enhanced Security Level 2, the following settings are listed:
Built-in Apps | Block Siri for dictation |
Built-in Apps | Block Siri for translation | Yes

According to the Device Restrictions docs: https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-ios#built-in-apps
These settings do not apply to Apple User Enrollments, which is likely to be a personal device enrollment. If those settings are indeed pushed with the personal security configuration, then there should be a notice that mention that if the personal device was enrolled using the Apple User Enrollment method these settings would not take effect. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a44c055-b6a0-5e6a-d0c1-b8054ae20afb
* Version Independent ID: a86a7293-9a9f-045d-c866-275489840cf9
* Content: [iOS/iPadOS personal device security configurations - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/ios-ipados-personal-device-security-configurations)
* Content Source: [memdocs/intune/enrollment/ios-ipados-personal-device-security-configurations.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/ios-ipados-personal-device-security-configurations.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@v-rechau I have received an update from the  owner of device configuration for Apple MDM that these settings do apply to personal devices and are available for devices enrolled using User Enrollment (screenshots attached):

Apple Dev Documentation:
![image](https://user-images.githubusercontent.com/45987684/165487122-a70d1688-cf6c-45ce-90b2-e8d15a9348c0.png)

Testing on a personal device

![image](https://user-images.githubusercontent.com/45987684/165487186-9bef9808-1119-49b9-9c69-90ba1c09219b.png)

So we may need Additional context to understand why the settings aren't pushed to your device.

Thanks
Sri

**Comment by v-rechau** [comment]
Hey @msbemba, I do not currently have a device with that issue. The original goal was to highlight a potential issue with the two documentation pages listed above.

Those settings are found under the heading:
**Settings apply to: Device enrollment, Automated device enrollment (supervised)**

According to the discussion on that PR and the Apple Dev Documentation provided, those settings apply to User Enrollments as well. This would actually flip the issue I want to report in which https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-ios#built-in-apps should have those two settings under the header:
**Settings apply to: All enrollment types**

Since it applies to User Enrollments but our documentation states they only apply to Device enrollments.

Would that be possible instead?

Thanks

**Comment by yogkumgit** [comment]
@msbemba

**Comment by v-rechau** [comment]
Here's a screenshot from the Intune portal that also implies those settings wouldn't apply to user enrollments, so this is quite the interesting discovery:
![image](https://user-images.githubusercontent.com/62122998/165798061-bb064e34-387c-43cd-9c32-ae5d800cb270.png)

**Comment by msbemba** [comment]
Thank you  @v-rechau  I'll work with the team and get back to you. This is indeed an interesting discovery. Rest assured we will get the document fixed.

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@lenewsad Please

**Comment by lenewsad** [comment]
Hi @msbemba @yogkumgit Both docs mentioning these settings are up-to-date and this issue can be resolved. UI changes are not expected.

**Comment by yogkumgit** [comment]
@v-rechau Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
