### ISSUE TITLE
Wrong or misleading title , Intune can NOT switch windows INTO S mode as tittle suggests

### ISSUE THREAD

**Issue by alfonso-rodriguez-2022** [MicrosoftDocs/memdocs#2523]
The portiion about the  Mode switch  (  S  or NOT S  mode)
is as follows:
Switch **out** of S mode: Switches the device out of S mode. Your options:

**No configuration**: Intune doesn't change or update this setting. By default, the S mode device might stay in S mode. User can switch the device out of S mode.
**Keep in S mode**: Prevents users from switching the device out of S mode.
**Switch**: Allows users to switch the device out of S mode.
[Enter feedback here]
In no part of the 3 options can you switch INTO S  mode, as the title would suggest.
This part of the configuration profile is only applicable is you are IN S mode, and want that device to:
remain 'secure' in the S mode, would select  **Keep in S mode**,  as  the two others say that they 'Allows users to switch the device out of S mode, or  'User can switch the device out of S  mode' that is essentially the same.
As far as the document implies,  Intune CAN not  force a device into S mode, but can only switch it OUT of S mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9f9139b-7f10-e11d-7633-215e2d4c0a51
* Version Independent ID: 463f2b3e-116b-2ab4-632c-a53dfc2833d7
* Content: [Windows 10 upgrade and S mode settings in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/configuration/edition-upgrade-windows-settings)
* Content Source: [memdocs/intune/configuration/edition-upgrade-windows-settings.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/edition-upgrade-windows-settings.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by msbemba** [comment]
@alfonso-rodriguez-2022 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2671

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @alfonso-rodriguez-2022 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
