### ISSUE TITLE
Inaccurate Info in this doc

### ISSUE THREAD

**Issue by PJMarcum** [MicrosoftDocs/memdocs#2533]
The following is no longer true, it was the case up until the IME was supported on AAD registered devices but not now.:

"Windows devices must be Azure AD joined or hybrid Azure AD joined."

"Workplace joined or Azure AD registered devices aren't supported."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dfe2e38-2c39-cb67-b4c7-d07f0c38a59f
* Version Independent ID: 3646bf8a-8960-2b8c-3236-4f9029724190
* Content: [Quickstart - Enroll Intune devices - Microsoft Endpoint Manager](https://docs.microsoft.com/en-us/mem/analytics/enroll-intune)
* Content Source: [memdocs/analytics/enroll-intune.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/analytics/enroll-intune.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
I confirmed with PMs, it's not supported. Closing issue.
