### ISSUE TITLE
Add Azure Subscription Resource Providers Prerequisite Requirements?

### ISSUE THREAD

**Issue by zebulonsmith** [MicrosoftDocs/memdocs#2535]
When creating a CMG in a VM Scale Set, the following Resource Providers must be registered in the subscription used:
Microsoft.Keyvault
Microsoft.Network
Microsoft.Storage
Microsoft.Compute

This isn't mentioned anywhere in the documentation that I was able to find and could be difficult to troubleshoot for some administrators. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07d4e4f7-68ed-e604-b577-2c18617d1c2e
* Version Independent ID: 1ce10bc0-2a6d-405a-a9ae-46adfaac8fe6
* Content: [Plan for CMG - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/plan-cloud-management-gateway)
* Content Source: [memdocs/configmgr/core/clients/manage/cmg/plan-cloud-management-gateway.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/configmgr/core/clients/manage/cmg/plan-cloud-management-gateway.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @zebulonsmith, this is mentioned in a couple of spots:

**Plan for CMG** article, [Virtual machine scale sets](https://docs.microsoft.com/mem/configmgr/core/clients/manage/cmg/plan-cloud-management-gateway#virtual-machine-scale-sets) section:

> With a few exceptions, the configuration, operation, and functionality of the CMG remains the same.
>
> Other [Azure resource providers](https://docs.microsoft.com/mem/configmgr/core/clients/manage/cmg/configure-azure-ad#configure-azure-resource-providers) in your Azure subscription.

**Configure Azure AD for CMG** article (step 2 of the "Set up" process), [Configure Azure resource providers](https://docs.microsoft.com/mem/configmgr/core/clients/manage/cmg/configure-azure-ad#configure-azure-resource-providers) section.

Based on feedback from #2434, I've also added mention of this prerequisite to the **Modify a CMG** article, [Convert](https://docs.microsoft.com/mem/configmgr/core/clients/manage/cmg/modify-cloud-management-gateway#convert) section.

So I'm going to close this issue. If there's any other spot that you think we need to mention this prerequisite, please comment back.
