### ISSUE TITLE
make "Active Directory Forest Discovery Account" linkable to another page that describes what permissions are needed for specified account on target domain.

### ISSUE THREAD

**Issue by brianfgonzalez** [MicrosoftDocs/memdocs#2539]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 628ef324-b5ed-9f39-b9b3-df731be685ac
* Version Independent ID: c7bcff0a-f066-53b7-423f-c7d491606ec6
* Content: [Discovery methods - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/about-discovery-methods)
* Content Source: [memdocs/configmgr/core/servers/deploy/configure/about-discovery-methods.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/configmgr/core/servers/deploy/configure/about-discovery-methods.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @brianfgonzalez for the feedback. That's a good idea to cross link it with the Accounts article that has more information. For example, the one you're asking about is here: https://docs.microsoft.com/mem/configmgr/core/plan-design/hierarchy/accounts#active-directory-forest-account

**Comment by aczechowski** [comment]
I made changes for this, they'll publish with the 2203 release
