### ISSUE TITLE
start ms-availablenetworks: not working on Windows 11

### ISSUE THREAD

**Issue by hammondjx** [MicrosoftDocs/memdocs#2540]
[Enter feedback here]
start ms-availablenetworks: not working on Windows 11 when trying to connect to WiFi during Whiteglove Provisioning. You can instead use other settings URI to facilitate this, for example going to start ms-settings:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0f572e0-1bc0-6f14-7f60-989eb67fb7e7
* Version Independent ID: e4ec5b25-d9a6-d260-6cf6-ff4f3eb3ecb8
* Content: [Windows Autopilot for pre-provisioned deployment](https://docs.microsoft.com/en-us/mem/autopilot/pre-provision)
* Content Source: [memdocs/autopilot/pre-provision.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/pre-provision.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by frankroj** [comment]
Thank you for the feedback @hammondjx . I apologize for the delay in answering this feedback. Both Windows 10 22H2 and Windows 11 22H2 currently check for a network connection at the start of OOBE. If there is no network connection, then it will automatically prompt to connect to a wireless network. This may be a change in the latest versions of Windows. If you are not seeing this with other currently supported versions of Windows, please let me know and I will dig more into it. When testing, please make sure you are using the latest ISO with the latest updates for that version of Windows. If you can still reproduce the issue, please let me know the exact version of Windows where this is happening.
