### ISSUE TITLE
Duplicate step?

### ISSUE THREAD

**Issue by LijuV-MSFT** [MicrosoftDocs/memdocs#2555]
Under https://docs.microsoft.com/en-us/mem/intune/protect/certificate-authority-add-scep-overview#create-an-application-in-azure-active-directory, isn't steps **7b** and **7c** identical?

Select Add a permission again.
- On the Request API permissions page, select Microsoft Graph > Application permissions.
- Expand Application and select the checkbox for **Application.Read.All (Read all applications).**
- Select Add permissions to save this configuration.

Use Microsoft Graph to add the following permissions to the app:
- **Application.Read.All (Read all applications**).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cda83a64-56ae-a632-dc81-dfd1a03984c1
* Version Independent ID: b93da48e-4097-4c3a-f6c8-02a5c4e0a616
* Content: [Use third-party certification authorities (CA) with SCEP in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/certificate-authority-add-scep-overview#set-up-third-party-ca-integration)
* Content Source: [memdocs/intune/protect/certificate-authority-add-scep-overview.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/certificate-authority-add-scep-overview.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by LijuV-MSFT** [comment]
@yogkumgit , just checking to see if you have an update. This is affecting a customer of mine looking to deploy this solution.

**Comment by msbemba** [comment]
@LijuV-MSFT Thank you for your feedback. I think both give the same permission, I have made the changes via PR#https://github.com/MicrosoftDocs/memdocs/pull/2672

I'll wait for the author to approve, Once this is approved the changes will be live.

Thanks
Sri

**Comment by Brenduns** [comment]
This issue and now the PR are pending feedback from PM/Dev. Stay tuned.

**Comment by yogkumgit** [comment]
@Brenduns

**Comment by yogkumgit** [comment]
@LijuV-MSFT Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
