### ISSUE TITLE
Allow installation from unknown sources - Please clarify functionality or fix if not working as intended

### ISSUE THREAD

**Issue by TechTrooper** [MicrosoftDocs/memdocs#256]
Intune has a device restriction setting "**Allow installation from unknown sources**" for **Android Enterprise** and it's described in this article under [Applications](https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-android-for-work#applications), 

Despite setting this to "**Allow**", what ends up actually happening is that manually installed APK packages disappear from all devices and a prompt is displayed on devices "Removed by your administrator"

Please clarify what this setting actually does or is it just not working as intended?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 900e72be-d42b-49ba-f304-602df23cbb04
* Version Independent ID: 2ce5c45d-15be-d316-1c57-92bea37358e0
* Content: [Android Enterprise device settings in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-android-for-work)
* Content Source: [memdocs/intune/configuration/device-restrictions-android-for-work.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/device-restrictions-android-for-work.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@TechTrooper Good question. What your seeing is expected. There are two settings that are related here:

- **Allow installation from unknown sources**: **Allow** lets users turn on Unknown sources. This setting allows apps to install from unknown sources, including sources other than the Google Play Store. When set to **Not configured** (default), Intune doesn't change or update this setting. By default, the OS might prevent users from turning on Unknown sources.

- **Allow access to all apps in Google Play store**: When set to **Allow**, users get access to all apps in Google Play store. They don't get access to the apps the administrator blocks in [Client Apps](https://docs.microsoft.com/mem/intune/apps/apps-add-android-for-work. When set to **Not configured** (default), Intune doesn't change or update this setting. By default, the OS might force users to only access the apps the administrator makes available in the Google Play store, or apps required in [Client Apps](https://docs.microsoft.com/mem/intune/apps/apps-add-android-for-work). 

Key points:

- The **Allow Installation from unknown sources** setting does allow users to side-load apps on the device using means other than the Play Store, as you've seen.
- The Google Play store behavior on these devices is that, by default, any apps that are detected as being installed by users outside of the Play Store are automatically uninstalled. To turn off this auto-uninstall behavior, change the **Allow access to all apps in Google Play store** to **Allow**.

So, if you really do want to enable side-loading, set both settings to **Allow**.

I updated our documentation to include this information. The changes should be live in the next couple of days.

In case you're not aware, the [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod) are a great resource for questions like this.
