### ISSUE TITLE
Defender for Endpoint missing from supported MTD list

### ISSUE THREAD

**Issue by deanellerby** [MicrosoftDocs/memdocs#2565]
List of supported MTD products for unenrolled devices does not include DfE.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 726a7fae-8a03-49fc-7f60-31e4fcc282cd
* Version Independent ID: 5ce29d71-8f06-5973-7591-d5529c5b5fc9
* Content: [Add Mobile Threat Defense apps to unenrolled devices - Microsoft Intune](https://docs.microsoft.com/en-gb/mem/intune/protect/mtd-add-apps-unenrolled-devices)
* Content Source: [memdocs/intune/protect/mtd-add-apps-unenrolled-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/mtd-add-apps-unenrolled-devices.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @deanellerby Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
