### ISSUE TITLE
Consider adding a note about SSL inspection of traffic to 'manage.microsoft.com' endpoint.

### ISSUE THREAD

**Issue by davidpaMSFT** [MicrosoftDocs/memdocs#2567]
As per discussion with a PM, we do not allow inspection of management traffic to our cloud services. Consider adding a note on SSL inspection (not being allowed/supported) in the section where we already mention that "Intune requires unauthenticated proxy server access to manage.microsoft.com".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c9c3475-56d4-026b-349f-f9cbc258537c
* Version Independent ID: 9c6476ed-8a47-bcb4-dfbf-25ba305c3b24
* Content: [Network endpoints for Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/intune-endpoints#access-for-managed-devices)
* Content Source: [memdocs/intune/fundamentals/intune-endpoints.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/intune-endpoints.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@davidpaMSFT Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2675

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @davidpaMSFT Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
