### ISSUE TITLE
Name Mismatch..

### ISSUE THREAD

**Issue by infoachieve** [MicrosoftDocs/memdocs#2569]
[Enter feedback here]
Hi Team,
Good Day. Hope everyone is fine and in good health.
While creating a policy in the MEM Admin Center we see "Profile Type" and not as "Policy Type". I have attached the snapshot for the same. Kindly check from your end and do the needful.
**_For Policy type, select either Fully managed, dedicated, and corporate-owned work profile or Personally-owned work profile, and then click Create._**
![Create Policy](https://user-images.githubusercontent.com/101454828/159208798-11740bbc-2d54-4797-ad50-bbea9d119a26.jpg)
Hope this helps.

Regards,
Aswani Kumar

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79f7c3fe-966f-82fa-c4b4-54e4987fc3f1
* Version Independent ID: 5901345a-609e-5a79-13cf-bda760f70ca1
* Content: [Quickstart - Password compliance policy for Android Enterprise devices - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/quickstart-set-password-length-android?source=docs)
* Content Source: [memdocs/intune/protect/quickstart-set-password-length-android.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/quickstart-set-password-length-android.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@infoachieve Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2676

Once the author confirms, the changes will be live.

Thanks
Sri

**Comment by infoachieve** [comment]
Thanks for the update.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @infoachieve Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
