### ISSUE TITLE
Mistakes in FAQ

### ISSUE THREAD

**Issue by lesca** [MicrosoftDocs/memdocs#2576]
Original statement:
> If you apply a MAM policy to the user without setting the **device state**[1], the user will get the MAM policy on both the BYOD device and the Intune-managed device. You can also apply a MAM policy based on the **managed state**[1]. So when you create an app protection policy, next to **Target to all app types**[2], you'd select No. Then do any of the following:

What's the problem:
1. **device state** vs **managed state**, I suppose they are the same, which is "device management state" as the setting in point 2. If so, update it to avoid confusing.  If not, please clarify the differences. 
2. **Target to all app types** is wrong, correct one is "Target to apps on all **device** types" as you can see when you create a new protection policy. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3929b5a0-f852-ce35-4ecd-72d5b9b4a948
* Version Independent ID: 33b804a6-5bf9-75e6-13e0-f2a35e07ef8f
* Content: [Frequently asked questions about MAM and app protection](https://docs.microsoft.com/en-us/mem/intune/apps/mam-faq)
* Content Source: [memdocs/intune/apps/mam-faq.yml](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/mam-faq.yml)
* Service: **microsoft-intune**
* Sub-service: **apps**
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@lesca Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2679

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @lesca Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
