### ISSUE TITLE
Data Threshold Mismatch

### ISSUE THREAD

**Issue by dereklangMSFT** [MicrosoftDocs/memdocs#2577]
In the CMG properties in the console, the default shows as 10000 GB:
- 14-day threshold for outbound data transfer (GB). The default value is 10000

In this document, we state the default is only 10GB:

[https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/monitor-clients-cloud-management-gateway#set-up-outbound-traffic-alerts](url)

- Specify the 14-day data threshold for outbound data transfer in gigabytes (GB). This threshold helps you to monitor the amount of data that transfers from the CMG to clients every two weeks. By default, this threshold is 10 GB

Just looking for clarification if the CMG properties are correct and the document needs to be changed to 1TB in the statement above. Or, the CMG properties are wrong and need to be changed to read in MB instead of GB if the true default is really 10GB.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 900fc69f-f7c4-95f9-fee2-eae88adca763
* Version Independent ID: 9f8b263b-8f05-0c51-c9b4-615fa306631e
* Content: [Monitor the CMG - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/monitor-clients-cloud-management-gateway#set-up-outbound-traffic-alerts)
* Content Source: [memdocs/configmgr/core/clients/manage/cmg/monitor-clients-cloud-management-gateway.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/configmgr/core/clients/manage/cmg/monitor-clients-cloud-management-gateway.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @dereklangMSFT for catching this. I double-checked with engineering: Default value should be 10T and 2T respectively

I'm making some other updates to CMG content for the 2203 release, so will include this.

**Comment by dereklangMSFT** [comment]
Thanks again Aaron
