### ISSUE TITLE
Firewall Import Tool not functional

### ISSUE THREAD

**Issue by lberenberg** [MicrosoftDocs/memdocs#2578]
The firewall import tool doesn't appear to be working, it hangs after asking for a policy name. This has happened across multiple tenants and when run on different machines. Not sure if this is a wider issue with the tool or something more specific.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bffd4704-acbf-a7e8-073f-7b0de922dcd8
* Version Independent ID: 39cc8624-ede4-2ec9-ea79-607347e5d17d
* Content: [Endpoint security firewall rule migration tool for Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/endpoint-security-firewall-rule-tool)
* Content Source: [memdocs/intune/protect/endpoint-security-firewall-rule-tool.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/endpoint-security-firewall-rule-tool.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@lberenberg Thank you for your feedback. We have not had any other feedback about the tool. Having said that you can contact the support team directly via the need help section on the admin center so that they can verify and confirm if this is a bug or if it can be fixed.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @lberenberg Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
