### ISSUE TITLE
"*.manage.microsoft.com" is not enough since it does not include "manage.microsoft.com"

### ISSUE THREAD

**Issue by Martony78** [MicrosoftDocs/memdocs#2579]
The doc tells us to allow "*.manage.microsoft.com" but does not mention "manage.microsoft.com", which is not included in "*.manage.microsoft.com" because of the dot before. I spent days troubleshooting an issue, then I opened manage.microsoft.com and everything went fine.
More info here:
[https://techcommunity.microsoft.com/t5/microsoft-intune/connector-for-active-directory-enrollment-fails/m-p/3034657/emcs_t/S2h8ZW1haWx8YW5zd2VyX2FjY2VwdGVkX2FzX3NvbHV0aW9ufEtXWVFYTjBSOUdSQ09SfDMwMzQ2NTd8QUNDRVBURURfU09MVVRJT05TfGhL#M8626](url)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c9c3475-56d4-026b-349f-f9cbc258537c
* Version Independent ID: 9c6476ed-8a47-bcb4-dfbf-25ba305c3b24
* Content: [Network endpoints for Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/intune-endpoints)
* Content Source: [memdocs/intune/fundamentals/intune-endpoints.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/intune-endpoints.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@Martony78 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2680

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Martony78 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
