### ISSUE TITLE
Turn off IE Enhanced Security Configuration - needs moving up the document

### ISSUE THREAD

**Issue by chiners68** [MicrosoftDocs/memdocs#258]
Turn off IE Enhanced Security Configuration needs to be moved up in the document. If you dont have this disabled when you try to sign into the intune connector you end in a credential loop and the connector will not complete the comunication. Thefore it needs to be before the intune connector install.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a94c428-95df-632b-46e8-4386ad551a03
* Version Independent ID: f23998f0-52ff-1203-1a0c-ff5c25b08c1c
* Content: [Enrollment for hybrid Azure AD-joined devices - Windows Autopilot](https://docs.microsoft.com/en-us/mem/intune/enrollment/windows-autopilot-hybrid#feedback)
* Content Source: [memdocs/intune/enrollment/windows-autopilot-hybrid.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/windows-autopilot-hybrid.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
(7261604)

**Comment by ErikjeMS** [comment]
@chiners68 I'm changing the doc today. Thanks!
