### ISSUE TITLE
Share Logs iOS/iPadOS

### ISSUE THREAD

**Issue by danbu** [MicrosoftDocs/memdocs#2581]
There is no "about > intunehelp" option in Microsoft Edge for iOS/iPadOS.  If you select the "..." to bring up the menu then select "Settings" there is a "About Microsoft Edge" option but thne there is no "intunehelp" option to select.  just "Terms of use", "Services agreement", "Privacy statement", "Third-party notices", "Open source software", "Chromium", and "Help"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f99adcae-3960-b5f8-efd3-1603490519c7
* Version Independent ID: d9164111-640b-d88c-3dad-661179e5114e
* Content: [App configuration policies for Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-configuration-policies-overview#managed-devices)
* Content Source: [memdocs/intune/apps/app-configuration-policies-overview.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/app-configuration-policies-overview.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@danbu Thank you for your feedback. We have made changes to document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2681

You can Type about:intunehelp in the address box. to follow the instructions and share logs.

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @danbu Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
