### ISSUE TITLE
Missing Appstore Submission Note

### ISSUE THREAD

**Issue by dil-asagar** [MicrosoftDocs/memdocs#2582]
[Enter feedback here]
[!NOTE] If you use the framework, you must manually strip out the simulator architectures from the universal framework before you submit your app to the App Store. See [Submit your app to the App Store](https://github.com/MicrosoftDocs/IntuneDocs/blob/main/intune/developer/app-sdk-ios.md#submit-your-app-to-the-app-store) for more details.

this is quite important : should be added to the page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 893c295c-9fa2-954f-4c9c-8b776d43f182
* Version Independent ID: dd4a72fe-ddde-4ed7-c408-c987f18c5d2a
* Content: [Microsoft Intune App SDK for iOS developer guide](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios)
* Content Source: [memdocs/intune/developer/app-sdk-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/developer/app-sdk-ios.md)
* Service: **microsoft-intune**
* Sub-service: **developer**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @dil-asagar Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
