### ISSUE TITLE
Add clarification on support for PXE

### ISSUE THREAD

**Issue by JCapretta** [MicrosoftDocs/memdocs#2583]
Documentation states: 

> If you require PXE or multicast support, you need an on-premises distribution point to respond to these boot requests.

This is misleading as it only applies if you need to PXE boot on the same broadcast domain. PXE  server can function without broadcast/multicast traffic between client and server using ip helpers as per https://docs.microsoft.com/en-us/troubleshoot/mem/configmgr/boot-from-pxe-server

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c839c644-12fe-b28c-f269-d833f1d8532b
* Version Independent ID: 2c974db5-592d-0736-e211-dcb762f3527c
* Content: [Configuration Manager on Azure FAQ - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/understand/configuration-manager-on-azure#what-about-content-distribution-and-content-management)
* Content Source: [memdocs/configmgr/core/understand/configuration-manager-on-azure.yml](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/configmgr/core/understand/configuration-manager-on-azure.yml)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @JCapretta, in the context of this article (ConfigMgr on Azure), it means that you can't have a DP in Azure that responds to PXE or multicast requests from on-premises clients, that's not supported. It might technically work if you configure things appropriately, but the engineering team hasn't tested and verified all situations.
