### ISSUE TITLE
Wrong version? 

### ISSUE THREAD

**Issue by lemondave** [MicrosoftDocs/memdocs#2596]
[Enter feedback here]

We deployed what I thought was the latest version of Remote Help by following these steps.  The app deployed from Intune without any issues.  However, when users first launch the program they are asked to install an update.  Users without admin rights are unable to install the update.  

The deployed version shows up in Add/Remove programs as 3.8.0.12 with the remotehelp.exe file having a version number of 10.0.22467.1000.  After running the update that the app asks for on first run, the version numbers are unchanged?  

Is this a bug in the app or a missed step in the documentation.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bc62c89-a452-0d3f-01f3-c5982803809e
* Version Independent ID: 6bc62c89-a452-0d3f-01f3-c5982803809e
* Content: [Remotely assist users that are authenticated by your organization.](https://docs.microsoft.com/en-us/mem/intune/remote-actions/remote-help#download-remote-help)
* Content Source: [memdocs/intune/remote-actions/remote-help.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/remote-help.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@lemondave Thank you for your feedback. This sounds like a bug to me, However, The most recent version of remote help is 4.0.0.0. I'd recommend you to contact support via the need help section on the admin center to see if the support team can file a bug or fix this issue.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @lemondave Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by abrownKGF** [comment]
The version numbers are different in the registry and in the file properties. The version number has changed in the registry (4.0.0.0), but not in the details of the file (10.0.22467.1000), which is the app detention rules provided on this page.  

![image](https://user-images.githubusercontent.com/103725370/164909382-ab6879f6-6983-43e9-8f23-028ade3ea967.png)

Be nice if version numbers were updated and stored where the detaction rules are lopoking.

![image](https://user-images.githubusercontent.com/103725370/164909403-2d2b1456-068d-4256-936b-bbd22033d997.png)
