### ISSUE TITLE
Prerequisites for Intune onboarding

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/memdocs#2597]
Hello,

I lead to this page from: https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-endpoints-mdm?view=o365-worldwide
On the above page it says: 
![image](https://user-images.githubusercontent.com/39700914/160105097-43054dcb-fdc8-4221-974c-5122e6ea045a.png)
And it is applied to:
![image](https://user-images.githubusercontent.com/39700914/160105186-0422888d-b762-47f6-9d4c-725d94a91a22.png)

Now on this page of "Follow the instructions from [Intune]." the URL "https://docs.microsoft.com/en-us/mem/intune/protect/advanced-threat-protection"

If we look into "Licensing requirements"
![image](https://user-images.githubusercontent.com/39700914/160105260-a54ddefe-a2fd-473e-8aaf-61b0884d3418.png)

It shows it applies to:

![image](https://user-images.githubusercontent.com/39700914/160105377-1c4e35ac-8163-4ce2-9f24-378ab988e76b.png)

Then OK, I see a note "see [Requirements for Defender for Endpoint Plan 1](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mde-p1-setup-configuration?view=o365-worldwide#review-the-requirements)."

![image](https://user-images.githubusercontent.com/39700914/160105496-383af92a-37a9-4be4-87ee-d8b5e802785b.png)

But if I click that link, I go to: https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mde-p1-setup-configuration?view=o365-worldwide#review-the-requirements

Then in this link, I go to "How to onboard with Microsoft Endpoint Manager/ Mobile Device Manager "

![image](https://user-images.githubusercontent.com/39700914/160105888-f6e926c2-94e0-4f52-910e-5a224b2fcd46.png)

That brings me back to the first one: https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-endpoints-mdm?view=o365-worldwide

Is it really needed to do such a loop between articles when at the end, the Intune on-boarding process for Defender Plan 1 or Defender Plan 2 is the same process?

![image](https://user-images.githubusercontent.com/39700914/160107682-90f45ec3-74a7-4778-9638-fe927a0879f4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d129246-93fe-04ec-0e49-8e9ac1c910a8
* Version Independent ID: 66d3e475-e2b9-1974-f04a-2ae8b31f96bd
* Content: [Use Microsoft Defender for Endpoint in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/advanced-threat-protection)
* Content Source: [memdocs/intune/protect/advanced-threat-protection.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/advanced-threat-protection.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@lightupdifire   Thank you for your dedication to detail this journey. This is timely feedback as I'm close to wrapping up a review/recommendation task for some intertwined Intune and Defender content to align our message/details, fix the context for links vs destinations, and more. Many of the article you note here are involved in that review, though I didn't pick up on the journey you've described. 

Question: If that first link to Intune  > _Follow the instructions from [Intune](https://docs.microsoft.com/en-us/intune/advanced-threat-protection)_< linked to this Article: [Configure Defender for Endpoint](https://docs.microsoft.com/en-us/mem/intune/protect/advanced-threat-protection-configure), would that path have had a better result and been successful for you?  

My review already includes a recommendation to redirect  that _Intune_ link to the Configure... article, but I'd like to understand if that change improves the journey from the perspective of where you started, with the Defender onboarding article @ https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-endpoints-mdm?view=o365-worldwide.

**Comment by lightupdifire** [comment]
@Brenduns 
I think yes, this will be a better article. And thanks for reviewing those docs! With "Defender Plan 1" and "Defender Plan 2" and other namings as "Defender for Endpoint" makes it a little bit complex reading in terms of thinking, which license users are covered, which settings we can enable in the "Security portal of Defender 365" then which way we can onboard devices and make sure the on-boarding is for the licensed devices :) If a task is already created, then feel free to close this case.

**Comment by Brenduns** [comment]
@lightupdifire   I'll submit that link change to the Defender content later today, in place of leaving it others at a later time via the larger bulk of feedback I have. I also am correcting a similar link in the Data Loss Prevention content, as onboarding to MDE also onboards to DLP as it turns out, and they use the same link to the same destination article, that doesn't deliver the onboarding goods. 

 As I am including your other feedback with that effort, I'll go ahead and close this specific issue. Thanks again!
