### ISSUE TITLE
Change Operating Systems to proper names

### ISSUE THREAD

**Issue by StamperStumper** [MicrosoftDocs/memdocs#260]
Suggest making this article more coherent by changing Operating Systems to their correct names rather than the manufacturer.
For Example...operating systems are:  iOS,  Android, Windows10
Not:  Apple, Google, Microsoft

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f70a020-9214-3316-5419-ee35ba6ff91a
* Version Independent ID: 9cc74430-af54-a2ac-7e4f-5a70b415c66e
* Content: [Operating systems and browsers supported by Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/supported-devices-browsers#feedback)
* Content Source: [memdocs/intune/fundamentals/supported-devices-browsers.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/supported-devices-browsers.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@StamperStumper Thanks for the suggestion! However, we'll continue to group the OS headers by manufacturer for easier scanning.
