### ISSUE TITLE
Request to modify how to check device/user check-in status, device assignment status, and per-configuration status in the configuration profile.

### ISSUE THREAD

**Issue by houkoku** [MicrosoftDocs/memdocs#2601]
[Enter feedback here]
Please correct and update the following Intune new feature release, which changes the way device/user check-in status, device assignment status, and status per setting are displayed in the configuration profile.

<Document
Title Device Configuration｜New Features of Microsoft Intune
URL : https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new#device-configuration

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 690d37a7-7b6a-3e5e-9b7e-1842cdd45b59
* Version Independent ID: 1f431cf8-8e5f-15ef-3391-55790e3c853e
* Content: [See device profiles with Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/configuration/device-profile-monitor)
* Content Source: [memdocs/intune/configuration/device-profile-monitor.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/device-profile-monitor.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by msbemba** [comment]
@houkoku Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2687

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @houkoku Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
