### ISSUE TITLE
Proxy configuration

### ISSUE THREAD

**Issue by svwie** [MicrosoftDocs/memdocs#2608]
I've just upgraded from the legacy NDES Connector for SCEP to the new unified SCEP/PKCS/PFX Intune connector.  That was a rather painful experience, since the proxy configuration has changed. The legacy connector was configured with "proxyserver.domain" and the according port. I've just reused this configuration with the new unified connector.

Installation runs smoothly, connector is created and shown in the MEM Tenant administration.

Certificates, though, are not issued and I was encountering the following error in event log:
"The password in the certificate request cannot be verified. It may have been used already. Obtain a new password to submit with this request."

Long story short: The proxy configuration was incorrect and a new syntax is required. Please point out in the documentation that the http prefix is required and has changed from the previous legacy connector. After changing the proxy configuration to "http://proxyserver.domain" instead of "proxyserver.domain" it started working right away.

Due to the irritating error message this took quite some time to troubleshoot.

Possibly this should be listed in the troubleshooting section, as well:
https://docs.microsoft.com/en-us/troubleshoot/mem/intune/troubleshoot-scep-certificate-device-to-ndes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 497646f6-1498-0647-cc54-b8013d71dca6
* Version Independent ID: e1fa4f5d-35b1-6fad-a4d2-3e8f5952230c
* Content: [Install the Certificate Connector for Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/certificate-connector-install)
* Content Source: [memdocs/intune/protect/certificate-connector-install.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/certificate-connector-install.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by svwie** [comment]
@Brenduns exactly. Usually proxy configuration is either accepting both or pointing out the correct syntax, e.g. with a pre filled example. In this case the resulting error message is really off, so you don't get it connected with a proxy issue.

**Comment by Brenduns** [comment]
@svwie   I've submitted an update that will publish later today. This adds a tip (for visual awareness) about the change of required syntax to that step.  Thanks for the feedback on this.
