### ISSUE TITLE
Add a section to disable sync on Edge

### ISSUE THREAD

**Issue by meetshamir** [MicrosoftDocs/memdocs#261]
Use key com.microsoft.intune.mam.managedbrowser.account.syncDisabled with value True.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a31e5a24-4f06-9e36-eacb-689bed95cd59
* Version Independent ID: ede9248e-1114-3e1a-9e80-34e5fe547707
* Content: [Manage Microsoft Edge for iOS and Android with Intune](https://docs.microsoft.com/en-us/mem/intune/apps/manage-microsoft-edge)
* Content Source: [memdocs/intune/apps/manage-microsoft-edge.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/manage-microsoft-edge.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by smithre4** [comment]
This is going to be addressed in a future article update.

**Comment by Erikre** [comment]
@meetshamir - Thanks for the feedback. I believe the information you requested is now documented in the following article section:
[Manage account synchronization](https://docs.microsoft.com/mem/intune/apps/manage-microsoft-edge#manage-account-synchronization)
