### ISSUE TITLE
Defender for Endpoint / Intune - Mismatch in docs

### ISSUE THREAD

**Issue by mikerobyn** [MicrosoftDocs/memdocs#2613]
Hi everyone,

in the docs it says:
Select Endpoint security > Microsoft Defender for Endpoint, and then select **Open the Microsoft Defender Security Center**.
There is no such link in the portal.

Cheers,
Mike

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24fa182f-ace6-e7e2-ff98-91951be7d10e
* Version Independent ID: f1acb398-6d69-b91c-5ee0-3da3bbf7809f
* Content: [Configure Microsoft Defender for Endpoint in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/advanced-threat-protection-configure)
* Content Source: [memdocs/intune/protect/advanced-threat-protection-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/advanced-threat-protection-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@mikerobyn Thank you for your feedback. It is now called Microsoft defender for endpoint admin console. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2688

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@yogkumgit The change is accurate as far as what I see in the tenant. So I have reopened the pull request after discussing it with the author. 

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @mikerobyn Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
