### ISSUE TITLE
Android Enterprise

### ISSUE THREAD

**Issue by konradturlejski** [MicrosoftDocs/memdocs#262]
What about Android Enterprise Requirements?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c9c3475-56d4-026b-349f-f9cbc258537c
* Version Independent ID: 9c6476ed-8a47-bcb4-dfbf-25ba305c3b24
* Content: [Network endpoints for Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/intune-endpoints#feedback)
* Content Source: [memdocs/intune/fundamentals/intune-endpoints.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/intune-endpoints.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
(7261604)

**Comment by ErikjeMS** [comment]
@konradturlejski Here is the Android port information: https://firebase.google.com/docs/cloud-messaging/concept-options#messaging-ports-and-your-firewall
I'm adding this link to this article today. Thanks!
