### ISSUE TITLE
Missing "Blocking personal devices" info for MacOS devices 

### ISSUE THREAD

**Issue by ztrhgf** [MicrosoftDocs/memdocs#2636]
The page is missing information about how MacOS devices are recognized. I mean when it is taken as a corporate device and when as a personal device. 

This information is available for other platforms...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e8c2d91-8808-a504-da13-526b152a5cfe
* Version Independent ID: 037b60a6-d6b5-75ad-1933-39d0f7a69048
* Content: [Set enrollment restrictions in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/enrollment-restrictions-set)
* Content Source: [memdocs/intune/enrollment/enrollment-restrictions-set.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/enrollment-restrictions-set.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by yogkumgit** [comment]
@lenewsad Please help us in resolving this issue. Thanks

**Comment by lenewsad** [comment]
Hi @ztrhgf, thank you for reaching out to the Microsoft Intune Docs team. 

Here are some resources I recommend: 

* For more information about macOS enrollment methods for personal and corporate-owned devices, see our [macOS enrollment guide](https://learn.microsoft.com/mem/intune/fundamentals/deployment-guide-enrollment-macos).  
* The method that's best for personal devices is the [BYOD: Device enrollment](https://learn.microsoft.com/mem/intune/fundamentals/deployment-guide-enrollment-macos#byod-device-enrollment) option.  By default, devices are marked personal. This method isn't intended for corporate-owned devices. If you are enrolling corporate-owned devices via this method, you can add the MacBook serial numbers to the corporate device identifiers to mark the devices as corporate.  
* The other Intune-supported enrollment methods for macOS listed in that article are recommended for corporate-owned devices only.  
* For information about adding corporate identifiers in Intune, see [Add corporate identifiers](https://learn.microsoft.com/mem/intune/enrollment/corporate-identifiers-add).  

Hope this information is helpful! 
CC @yogkumgit

**Comment by yogkumgit** [comment]
@ztrhgf Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
