### ISSUE TITLE
Version 2203 opt-in script is pointing to EnableEarlyUpdateRing2111.exe

### ISSUE THREAD

**Issue by manuelsinger-msft** [MicrosoftDocs/memdocs#2637]
Link to the [Version 2203 opt-in script](https://go.microsoft.com/fwlink/?linkid=2099733) is still pointing to EnableEarlyUpdateRing2111.exe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d91b3bd0-c3bb-b144-619c-33d958e14c95
* Version Independent ID: d91b3bd0-c3bb-b144-619c-33d958e14c95
* Content: [Checklist for 2203 - Configuration Manager](https://review.docs.microsoft.com/en-us/mem/configmgr/core/servers/manage/checklist-for-installing-update-2203?branch=release-cm2203-cb#early-update-ring)
* Content Source: [memdocs/configmgr/core/servers/manage/checklist-for-installing-update-2203.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/configmgr/core/servers/manage/checklist-for-installing-update-2203.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
It looks like this is already resolved. It's pointing to the 2203 script now.
