### ISSUE TITLE
Functional 

### ISSUE THREAD

**Issue by sokarblue** [MicrosoftDocs/memdocs#2641]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff4c5218-bbe4-110c-c74d-3eed1179ac61
* Version Independent ID: b7c148dc-574b-fbed-7637-29699f3eb97a
* Content: [Configure the Microsoft Managed Home Screen app - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-configuration-managed-home-screen-app?back=https%3A%2F%2Fwww.google.com%2Fsearch%3Fclient%3Dsafari%26as_qdr%3Dall%26as_occt%3Dany%26safe%3Dactive%26as_q%3DConfiguraci%C3%B3n+Home+Screen%26channel%3Daplab%26source%3Da-app1%26hl%3Des)
* Content Source: [memdocs/intune/apps/app-configuration-managed-home-screen-app.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/app-configuration-managed-home-screen-app.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@sokarblue Thank you for your feedback. The Managed Home Screen provides IT admins the ability to customize their devices and to restrict the capabilities that the end user can access. Not sure, what exactly is the functional requirement on Managed Home Screen.

If you would like to see more information or have some suggestions on this document, please let us know.

Hope this helps!
Thanks
Sri
