### ISSUE TITLE
Android Native VPN?

### ISSUE THREAD

**Issue by mattsmacblog** [MicrosoftDocs/memdocs#2642]
Will there eventually be a "Android Native VPN" option?   Settings > Connections > More Connection Settings > VPN > Add VPN Profile  (which exists on Android 9+)

Connection type: Select the VPN connection type. Your options:

Check Point Capsule VPN
Cisco AnyConnect
SonicWall Mobile Connect
F5 Access
Pulse Secure
Citrix SSO
"GOOGLE NATIVE VPN" ????

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8d02217-a059-2aeb-5e8e-8350d6acbafc
* Version Independent ID: 56db7c58-6da7-f274-ab2a-55f16a2dd59a
* Content: [Use VPN settings for Android devices in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/configuration/vpn-settings-android)
* Content Source: [memdocs/intune/configuration/vpn-settings-android.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/vpn-settings-android.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by yogkumgit** [comment]
@mattsmacblog Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
