### ISSUE TITLE
This doesn't work for me - can't remove company account for company I left months ago

### ISSUE THREAD

**Issue by johnhaire89** [MicrosoftDocs/memdocs#2644]
I'm not sure what the issue is but I was unable to set a PIN and unable to disconnect the inactive company account from the company I left months ago. This is on my personal PC.

I have information events in Applications and Services Logs->Microsoft->Windows->DeviceManagement-Enterprise-Diagnostics-Provider->Admin saying "Impersonation result. Result: (An attempt was made to reference a token that does not exist.)."

https://community.spiceworks.com/topic/1679554-how-to-remove-work-or-school-account-in-windows-10-please-help

I found my company email address in the registry in a registry entry at HKEY_USERS\<lots of nubmers>\SOFTWARE\Microsoft\Office\16.0\Common\Identity\Identities

Going to try scrubbing it according to this article https://www.urtech.ca/2019/03/solved-scrub-office-license-credentials-identity-to-solve-sorry-another-account-from-your-organization-is-already-signed-in-on-this-computer/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8186a91-73b1-1276-9710-70ee92a491e5
* Version Independent ID: b8210dcf-6694-e920-1ea7-9761ad02f810
* Content: [Remove your Windows device from Intune management](https://docs.microsoft.com/en-us/mem/intune/user-help/unenroll-your-device-from-intune-windows)
* Content Source: [memdocs/intune/user-help/unenroll-your-device-from-intune-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/unenroll-your-device-from-intune-windows.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @johnhaire89 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
