### ISSUE TITLE
Takes longer to Wipe than 30 mins

### ISSUE THREAD

**Issue by Dburke225** [MicrosoftDocs/memdocs#2646]
The App selective wipe takes longer than 30 mins. 

For me it goes over an hour. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e31bcb79-bae1-8398-9a3d-0559e4445e23
* Version Independent ID: ffb05284-00c1-a071-9683-402b1ce93e3c
* Content: [How to wipe only corporate data from apps - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-selective-wipe)
* Content Source: [memdocs/intune/apps/apps-selective-wipe.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/apps-selective-wipe.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by yogkumgit** [comment]
@Dburke225 Considering the nature of the issue, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Dburke225** [comment]
Support is useless, I'm just dealing with it.


Dillon Burke
Assistant Systems Engineer
Qosina Corp. | QOSMEDIX
2002-Q Orville Drive North
Ronkonkoma, NY 11779 USA
T: +1 (631) 242-3000, ext. 421
Email: ***@***.******@***.***>
www.qosina.com<http://www.qosina.com>  www.qosmedix.com<http://www.qosmedix.com>
