### ISSUE TITLE
Miss one prerequisite: the location of Azure tenant and SCCM SCP server should be the same

### ISSUE THREAD

**Issue by IvyMS1990** [MicrosoftDocs/memdocs#2647]
[Enter feedback here]
There is one more prerequisite. During onboarding, the service check the GEOLocation for tenant and the service. Thus, if the location are different, onboarding will failed with error code 400. I encounter this issue when the location is different. It cannot onboard to MEMAC. 

 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd48cfb-8d4a-0eae-a189-94f4b90907b3
* Version Independent ID: 7cd48cfb-8d4a-0eae-a189-94f4b90907b3
* Content: [Microsoft Endpoint Manager tenant attach prerequisites - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/tenant-attach/prerequisites)
* Content Source: [memdocs/configmgr/tenant-attach/prerequisites.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/configmgr/tenant-attach/prerequisites.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@IvyMS1990 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2723

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit  This can be closed.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @IvyMS1990 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
