### ISSUE TITLE
Docs article refers to "Sample sharing for all files", however Intune blade says "Block sample sharing for all files  "

### ISSUE THREAD

**Issue by SLeuthold** [MicrosoftDocs/memdocs#2649]
Docs article refers to "Sample sharing for all files", however Intune blade says "Block sample sharing for all files 
". Does this setting block or allow? Please update docs to clarify :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19c5d836-1b10-7c46-ab3f-a1d845eb557b
* Version Independent ID: 9c5f53d8-28c6-05bf-9ee3-8a3dc77acc09
* Content: [Intune endpoint security Endpoint detection and response settings](https://docs.microsoft.com/en-us/mem/intune/protect/endpoint-security-edr-profile-settings)
* Content Source: [memdocs/intune/protect/endpoint-security-edr-profile-settings.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/endpoint-security-edr-profile-settings.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@SLeuthold   Thanks for this question. The CSP for this setting _should_ be Configuration/SampleSharing found on this content page (but I am still seeking that confirmation): https://docs.microsoft.com/en-us/windows/client-management/mdm/windowsadvancedthreatprotection-csp   That CSP supports sharing all, or none.  

If that's the correct CSP, then the setting name in the UI is a bit off (not an unknown problem with a lot of settings.)  The text in the docs might have been an attempt to correct for that, however without explicit details as to the result of **yes** and **not configured**, it remains a bit muddled.  As it is in the UI where the name of the setting starts with 'block', the UI name appears to invert the intent of the CSP.  

Once I hear back from our PM/Dev team as to what we send for Yes and Not configured, I'll update you. 

FYI:  We have some [new profiles out that are replacing these old ones](https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new#new-profile-templates-and-settings-structure-for-endpoint-security-policies). The new profiles include the same settings as the old profiles, but use a newer settings format that is a bit more direct, and clear.  In the new profile for EDR this settings name is _Sample Sharing_, and the options now line up directly with that CSP (which is my _best guess_ at being the correct one - until confirmed). In that new profile, the options are Enabled/Disabled which directly line up to  "Sample sharing - All (enabled)" or "Sample Sharing - None (disabled)".

**Comment by Brenduns** [comment]
Tracking> Include https://github.com/MicrosoftDocs/memdocs/issues/2670

**Comment by Brenduns** [comment]
When the profile setting of **Block sample sharing for all files** is set to **Yes**, the result is that the CSP is configured to block the sharing (set to 0).  When the setting is left _not configured_ which is both the Intune UI default and the CSP default, you'll Sample sharing is active (set to 1).
