### ISSUE TITLE
"If it is deployed to a user, it is evaluated for compliance when the user logs on."

### ISSUE THREAD

**Issue by cwmoriarty** [MicrosoftDocs/memdocs#265]
What is the re-run logic for a user collection deployment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6929f52-59ed-036a-8070-2de8290605a6
* Version Independent ID: 70a45bc4-bc54-c327-9a60-c059d688bba7
* Content: [Deploy configuration baselines - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/compliance/deploy-use/deploy-configuration-baselines#feedback)
* Content Source: [memdocs/configmgr/compliance/deploy-use/deploy-configuration-baselines.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/compliance/deploy-use/deploy-configuration-baselines.md)
* Product: **configuration-manager**
* Technology: **configmgr-compliance**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @cwmoriarty for the feedback. I'm assuming you're asking, is the evaluation _only_ when the user signs in, or is it re-evaluated on the schedule after? I need to check to be sure.

**Comment by cwmoriarty** [comment]
I'd like to know the complete evaluation logic. Will it run once or RunAlways (subsequent signins), etc.

**Comment by mestew** [comment]
Eval should happen according to the schedule for the baseline for user collections. 
![image](https://user-images.githubusercontent.com/33289333/116287618-76a46780-a745-11eb-90cf-6afc4c4e48d7.png)

**Comment by cwmoriarty** [comment]
Thanks @mestew 

The logic is still ambiguous-- is it perhaps "when the user next logs in" _after_ the defined schedule is set to evaluate?
