### ISSUE TITLE
Encoding specifications unclear

### ISSUE THREAD

**Issue by MHimken** [MicrosoftDocs/memdocs#2650]
Hi everyone,

can you please clarify if the required encoding is UTF-8 or UTF-8-BOM? We had a script that without switching to UTF-8-BOM didn't work. Mind you it was a script copied from github. 

Regards
Martin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d35a1251-2323-4239-85d7-ca21f44cf93a
* Version Independent ID: d8bd22fc-6af5-075f-ecee-bb084483bbce
* Content: [Tutorial - Proactive remediations - Microsoft Endpoint Manager](https://docs.microsoft.com/en-us/mem/analytics/proactive-remediations)
* Content Source: [memdocs/analytics/proactive-remediations.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/analytics/proactive-remediations.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @MHimken, yes see https://docs.microsoft.com/en-us/mem/analytics/troubleshoot#script-requirements-for-proactive-remediations

But we should probably call it out in the list of requirements as well.
