### ISSUE TITLE
What does Hightest mean when referring to priority for ESP?

### ISSUE THREAD

**Issue by AdamGrossTX** [MicrosoftDocs/memdocs#2653]
The docs say that Highest priority wins.  The ESP list is numerical but is also sorted from least to greatest with Default at the bottom of the list. When you say highest, does this refer to the displayed order with 1 being the literal highest in the list or highest as in the ESP with the largest number wins?

Also, I know this isn't part of docs, but it would be great if that was actually listed directly in the portal where the ESP's are.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92ba0166-1d3c-40ca-a2f3-2954dcfe4411
* Version Independent ID: e07d50e2-7a95-868d-5800-ea548c84e884
* Content: [Set up the Enrollment Status Page - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/windows-enrollment-status#prioritize-profiles)
* Content Source: [memdocs/intune/enrollment/windows-enrollment-status.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/windows-enrollment-status.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@AdamGrossTX Thank you for your feedback. You are correct, “1” has the highest priority.

I agree it would be nice to have them listed directly in the portal where the ESPs are. Since this is a design change, it goes through the dev/product group. So I'd recommend you raise the feedback in the main feedback portal- https://feedbackportal.microsoft.com/ so one of our dev/product engineers will be able to look at it. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@AdamGrossTX  Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@AdamGrossTX Thank you for your feedback. I have added information about the priority via PR#https://github.com/MicrosoftDocs/memdocs/pull/2737

Once the author approves, the changes will be live.

Thanks
Sri
