### ISSUE TITLE
How to ensure, iOS considers contacts as "managed" and thus protects from unmanaged apps

### ISSUE THREAD

**Issue by taikuli** [MicrosoftDocs/memdocs#2655]
Hello,

I had an email profile configured which only synced contacts and expected the managed contacts to be inaccessible to unmanaged apps. However, tests showed that the contacts were in fact accessible to unmanaged apps.

I had **Allow users to change sync settings** set to **Yes** and only after I changed this to **No**, the contacts were inaccessible to unmanaged apps.

I don't know much about the magic that happens in the background of Intune and iOS, but maybe you can ask someone who is more famliar with both, whether this setting is essential for iOS to consider the information from this profile as "managed" and thus applying appropriate policies.

If this (and possibly other settings) are essential, I'd love to see this article updated with a big red box explaining which settings are important for iOS to consider information from this profile as "managed".

Best

Martin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51f67ba8-c680-7e6d-1b80-cdfe45924e87
* Version Independent ID: 332fbbaf-173c-fad9-ead8-d36a44634b8c
* Content: [Configure Email settings for iOS/iPadOS devices in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/configuration/email-settings-ios)
* Content Source: [memdocs/intune/configuration/email-settings-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/email-settings-ios.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by yogkumgit** [comment]
@MandiOhlinger Please help us in resolving this issue. Thanks.

**Comment by MandiOhlinger** [comment]
@taikuli This is a good question. We're not sure if this behavior is expected, or if it's something else. If you're still interested, it'd be great if you opened a support case. They can test & verify, and work directly with engineering if needed. Just something to consider if you want to pursue this.

If you work with the support team, then we can update this article based on their findings. 

Thanks,
Intune doc team
