### ISSUE TITLE
Impossible supported OS

### ISSUE THREAD

**Issue by BenLeggiero** [MicrosoftDocs/memdocs#266]
The documentation states:

&gt; You will need a Mac OS computer that runs OS X 10.8.5 or later, and also has Xcode 9 or later installed.

Xcode 9 requires macOS 10.12, so no dev can use OS X 10.8.5

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 893c295c-9fa2-954f-4c9c-8b776d43f182
* Version Independent ID: dd4a72fe-ddde-4ed7-c408-c987f18c5d2a
* Content: [Microsoft Intune App SDK for iOS developer guide](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#feedback)
* Content Source: [memdocs/intune/developer/app-sdk-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/developer/app-sdk-ios.md)
* Service: **microsoft-intune**
* Sub-service: **developer**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@BenLeggiero - Thanks for the feedback. I'm updating the topic now.
