### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by aseflova** [MicrosoftDocs/memdocs#2665]
Hi, I am missing information about licensing - who needs to have license assigned - the user that is providing help (support stuff that is connecting to other device), the user that needs help, or both? This is important to know for estimating the number of licenses that needs to be purchased.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bc62c89-a452-0d3f-01f3-c5982803809e
* Version Independent ID: 6bc62c89-a452-0d3f-01f3-c5982803809e
* Content: [Remotely assist users that are authenticated by your organization.](https://docs.microsoft.com/en-us/mem/intune/remote-actions/remote-help)
* Content Source: [memdocs/intune/remote-actions/remote-help.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/remote-help.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@aseflova Thank you for your feedback. The add-on license needs to be assigned for both the user providing help and the user that needs help. This information has been added to the prerequisites section of the document.

Hope this helps!

Thanks
Sri

**Comment by aseflova** [comment]
@msbemba Thank you for clarification. I hope Microsoft understands that the fact that both admin and user needs to be licensed means that nobody will purchase this addon because it does not make sense - the price in so high in comparison with competition and it only supports Windows where you can easily use several different solutions.

**Comment by msbemba** [comment]
@aseflova Thank you for your quick response. You make a fair point about the price being high. I'd recommend you raise this feedback on our main feedback portal - https://feedbackportal.microsoft.com/ and one of our dev/product team members will be able to explain why the price is high or if there are any roadmap items for remote help which could bring the cost down.

Hope this helps!

Thanks
Sri

**Comment by aseflova** [comment]
@msbemba Thank you for quick response
