### ISSUE TITLE
Add note to call out AADDS

### ISSUE THREAD

**Issue by jeffbryantmsft** [MicrosoftDocs/memdocs#2677]
In the Prerequisites section, consider adding a note that Intune is not supported if the session hosts have been added to Azure AD Domain Services as per (https://docs.microsoft.com/en-us/azure/virtual-desktop/prerequisites#:~:text=If%20you%27re%20joining%20session%20hosts%20to%20an%20Azure%20AD%20DS%20domain%2C%20you%20can%27t%20manage%20them%20using%20Intune).

It is easy to miss this since the info is under AADDS docs while most customer will be looking at this page to get Intune setup with AVD.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 591d8748-ca94-f818-2ea3-9143b8e41697
* Version Independent ID: 7b0d2d80-8bf4-b9b6-7a2a-b0f3dc50a125
* Content: [Using Azure Virtual Desktop multi-session with Microsoft Intune (preview)](https://docs.microsoft.com/en-us/mem/intune/fundamentals/azure-virtual-desktop-multi-session)
* Content Source: [memdocs/intune/fundamentals/azure-virtual-desktop-multi-session.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/azure-virtual-desktop-multi-session.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @SMBhardwaj
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@jeffbryantmsft Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2720

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jeffbryantmsft Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
