### ISSUE TITLE
Documentation on below link is not proper

### ISSUE THREAD

**Issue by viveknegi51288** [MicrosoftDocs/memdocs#269]
I have create an xamarin forms application with MSAL library to fetch access token and I am able to get it. Now i want to integrate intunes sdk so that company policies can be applied .

I have followed every step you mentioned in the following page but didn't work.

I have my own splash screen, and intunes has its own, how to override it.

So currently in my application, once the user click on app icon it will automatically open the microsoft login page as MSAL library already integrated, user will enter username and password he will get appoval and deny notification in microsoft authenticator app as MFA is enable for the user from azure. 

Once he will approve it, my appilcation will get access token and i can process further.

Now as per your documentation, adding IntuneMAMSettings dictionary will override intunes adal methods, I have done this, and added AutoEnrollOnLaunch YES and MAMPolicyRequired YES too.

Now, once my application opened it open login screen user entered username and password , no MFA notification is coming on authenticator application, and then my custom splash screen opened and hanged.. 

Even i removed my custom splash, after login it again going to login screen as MSAL libarary and trying to get access token.

PLEASE I NEED STEPS TO FOLLOW TO INTEGRATE INTUNES AS I ALREADY CONFIGURED MSAL TO FETCH ACCESS TOKEN. PLEASE HELP

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 123cb14f-5edf-1bdd-1f16-00ce32443583
* Version Independent ID: c41ef518-bc7a-d87e-b03c-31cba1de6d0a
* Content: [Microsoft Intune App SDK Xamarin Bindings](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-xamarin)
* Content Source: [memdocs/intune/developer/app-sdk-xamarin.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/developer/app-sdk-xamarin.md)
* Service: **microsoft-intune**
* Sub-service: **developer**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@viveknegi51288 - Thanks for sharing this with the Intune documentation team. If you are still running into problems related to this issue, we want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

This question is in our documentation feedback channel and it may be best to handle this question as a support request. For this reason, I'm closing this issue. Please use the above channels if you don't already have a solution.
