### ISSUE TITLE
Microsoft Store for Business: Add Note that It's Being Retired

### ISSUE THREAD

**Issue by karen-gre** [MicrosoftDocs/memdocs#2690]
This page would lead admins to setup a Business App in Intune only to be met with warnings that the service is being retired in Q1 of 2023. Might want to warn admins ahead of time. 
Link the to the announcement: https://techcommunity.microsoft.com/t5/windows-it-pro-blog/evolving-the-microsoft-store-for-business-and-education/ba-p/2569423

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dac06439-a7c6-b637-3268-e1ed8f59ad15
* Version Independent ID: c43caaad-0392-394c-62ca-1216dd488652
* Content: [Manage VPP apps from Microsoft Store for Business - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/windows-store-for-business)
* Content Source: [memdocs/intune/apps/windows-store-for-business.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/windows-store-for-business.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@karen-gre Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2721

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @karen-gre Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
