### ISSUE TITLE
Android12 not working for intune - BLOCKER

### ISSUE THREAD

**Issue by bplasmeijer** [MicrosoftDocs/memdocs#2692]
[Android 12] 

The intune app doesn't work on Android12, see https://docs.microsoft.com/en-us/answers/questions/679297/intune-company-portal-enrollment-fails-after-andro.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 709b2e42-8daf-0af2-d3de-6fd6d450b8fc
* Version Independent ID: a27d1326-46c5-2a0a-f37b-80c9e861bd3d
* Content: [Why enroll your Android device](https://docs.microsoft.com/en-us/mem/intune/user-help/why-enroll-android-device)
* Content Source: [memdocs/intune/user-help/why-enroll-android-device.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/why-enroll-android-device.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@bplasmeijer Thank you for your feedback. We are aware of this known issue and at this time, we’re aware of three device types that can have this issue. For more information, you can follow the blog- https://techcommunity.microsoft.com/t5/intune-customer-success/known-issue-android-devices-lose-access-to-intune-managed/ba-p/3249657

There are no changes needed in the document as this does not affect all Android 12 devices.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @bplasmeijer Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
