### ISSUE TITLE
Teams Meeting Rooms licenses

### ISSUE THREAD

**Issue by MarineBDCoru** [MicrosoftDocs/memdocs#2693]
Hello!
It seems that the licenses "Teams Meeting Rooms" are included Intune service. 
https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/rooms-licensing 
It would be needed to add these licenses in this article. 
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73c7bea7-ccff-ca28-35e4-820494059bf6
* Version Independent ID: 42e6e56f-d5ca-4124-f409-7e34ca609a3a
* Content: [Licenses available for Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/licenses)
* Content Source: [memdocs/intune/fundamentals/licenses.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/licenses.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@MarineBDCoru Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2722

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by MarineBDCoru** [comment]
Hello Sri,
Thanks for you answer. Do you know if the change will be made?

**Comment by yogkumgit** [comment]
@MarineBDCoru Closing, as per author's comment in the PR. Thanks
