### ISSUE TITLE
Lots of pages redirect to here as a way to install applications 

### ISSUE THREAD

**Issue by dootdootbeep** [MicrosoftDocs/memdocs#27]
However, there are no examples or instructions on how to use Intune Management Extension to deploy applications.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d6b1270-e554-dc36-2a51-1cdab303e91a
* Version Independent ID: 4a62c248-5737-13cc-3270-1f9649bd147d
* Content: [Add PowerShell scripts to Windows 10 devices in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/apps/intune-management-extension#feedback)
* Content Source: [memdocs/intune/apps/intune-management-extension.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/intune-management-extension.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by dootdootbeep** [comment]
For example: https://docs.microsoft.com/en-us/mem/intune/apps/apps-win32-app-management

"When deploying Win32 apps, consider using Intune Management Extension exclusively, particularly when you have a multi-file Win32 app installer. If you mix the installation of Win32 apps and line-of-business apps during AutoPilot enrollment, the app installation may fail."

**Comment by Erikre** [comment]
@dootdootbeep - Thanks for the feedback. I've update the docs to help make this more clear. Here are the main details I've added (at the top of the topic):

Once the Intune management extension prerequisites are met, the Intune management extension installs automatically when a PowerShell script or Win32 app is assigned to the user or device. For more information, see Intune Management Extensions [prerequisites](https://docs.microsoft.com/en-us/mem/intune/apps/intune-management-extension#prerequisites).
