### ISSUE TITLE
Is E-HTTP MP mandatory?

### ISSUE THREAD

**Issue by ashutosh-3004** [MicrosoftDocs/memdocs#270]
can you please clarify if E-HTTP is mandatory for using token based auth on clients? can client system use token based auth with HTTPS MPs and CMG functioning in environment but without Client systems having PKI cert?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60a7510b-10d9-e7e2-f848-d57d69d7fe10
* Version Independent ID: d4e9a557-ca23-3727-52b8-b81c6f767757
* Content: [Token-based authentication for CMG - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/deploy/deploy-clients-cmg-token)
* Content Source: [memdocs/configmgr/core/clients/deploy/deploy-clients-cmg-token.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/deploy/deploy-clients-cmg-token.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @ashutosh-3004, EHTTP isn't required or a client auth cert. Those are presented as challenges that this solution resolves. I'll add a few words to help make that more clear. Thanks for the feedback!
