### ISSUE TITLE
And No information on when the app complaints "work profile cannot be created"

### ISSUE THREAD

**Issue by sijucm** [MicrosoftDocs/memdocs#2701]
The user is left with google searches in the wild world with n o useful information that can be guessed from the "very useful" microsoft error messages. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50b13370-965f-0a72-9226-f119229ba68a
* Version Independent ID: 089ce4b0-bf8d-3936-82a9-e29029fc7df1
* Content: [Enroll device and create Android work profile - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/user-help/enroll-device-android-work-profile)
* Content Source: [memdocs/intune/user-help/enroll-device-android-work-profile.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/enroll-device-android-work-profile.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@sijucm Thank you for your feedback. This document is specifically created with steps to enroll devices and create an android work profile. We have documents that talk about troubleshooting android enrollment issues, 

https://docs.microsoft.com/en-us/troubleshoot/mem/intune/troubleshoot-android-enrollment
https://docs.microsoft.com/en-us/troubleshoot/mem/intune/configure-android-enterprise-devices-intune
https://docs.microsoft.com/en-us/troubleshoot/mem/intune/troubleshoot-device-enrollment-in-intune

If you are unable to locate steps to fix this issue, I'd recommend contacting Microsoft via the need help section and they would be able to fix the issue and also help with the related documentation.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @sijucm Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
