### ISSUE TITLE
Devices cannot be add by Serial Number

### ISSUE THREAD

**Issue by MarineBDCoru** [MicrosoftDocs/memdocs#2704]
Hello, 

I believe that the point 7. of "Step 2. Use your key to download a token from Apple" needs to changed. 
It's not possible to add devices to ABM by serial number anymore. Now we have only two options: Apple Customer number or Reseller Number. To add an device manually, the only option seems to be Apple Configurator. 

I attached some Apple documentation:
· https://support.apple.com/fr-fr/guide/apple-business-manager/axm6a88f692e/web 
· https://support.apple.com/en-us/HT204142
· https://discussions.apple.com/thread/251829918

Thanks! 
Marine

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0319ece7-6b1f-d737-618c-778d3f196313
* Version Independent ID: 20b5b39e-56e2-d88e-e4b2-22a79b5d3ccb
* Content: [Enroll macOS devices - Apple Business Manager or Apple School Manager](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-macos)
* Content Source: [memdocs/intune/enrollment/device-enrollment-program-enroll-macos.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/device-enrollment-program-enroll-macos.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@MarineBDCoru Thank you for your feedback. I'm currently checking with the author and will update the document if need be,

Thanks
Sri

**Comment by MarineBDCoru** [comment]
Ok, thanks! Waiting for your update :)

**Comment by tiburd** [comment]
@MarineBDCoru 
Hi,
Thank you for your submission.
The product team has confirmed that the steps are outdated and will post an update soon.
Thanks!

**Comment by tiburd** [comment]
@yogkumgit
