### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by SCIS-guy** [MicrosoftDocs/memdocs#2705]
There is a typo under the first bullet point of "Home Screen App Order." The word "the" was misspelled as "tThe" and is driving my OCD crazy. Please, fix it and use a spell check next time. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8976417-16d9-58c1-8831-5c06aee65ad2
* Version Independent ID: b00e84d9-a244-9739-832a-9a02261112fb
* Content: [Configure Microsoft Launcher for Android Enterprise with Intune](https://docs.microsoft.com/en-us/mem/intune/apps/configure-microsoft-launcher)
* Content Source: [memdocs/intune/apps/configure-microsoft-launcher.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/configure-microsoft-launcher.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by yogkumgit** [comment]
@colealbrecht Thank you very much for the contribution and updating the documentation with PR. @SCIS-guy Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
