### ISSUE TITLE
No additional licensing required for Remote Help? You sure?!

### ISSUE THREAD

**Issue by deanellerby** [MicrosoftDocs/memdocs#2706]
The table suggests that Remote Help doesn't require "additional licensing", when in reality it actually requires significant additional licensing, to the extent that there is almost no point in including it in the table at all. No organization will purchase this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bd171a5-fb03-c97a-d1ed-e00a2dfc1ed6
* Version Independent ID: 166f8cb0-e33b-ec9a-1e47-9d8ffb0163e0
* Content: [Remotely assist mobile devices managed by Intune](https://docs.microsoft.com/en-us/mem/intune/remote-actions/remote-assist-mobile-devices)
* Content Source: [memdocs/intune/remote-actions/remote-assist-mobile-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/remote-assist-mobile-devices.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@deanellerby Thank you for your feedback. We have added the license requirement to the prerequisites section "Remote help add-on license for all IT support workers (helpers) and users (https://aka.ms/PremiumAddOnsDocs)"

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @deanellerby Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by deanellerby** [comment]
Thanks :-)

You also appear to have removed the page (and table) that I was commenting
on altogether. Is there another docs page that covers the feature matrix
between Quick Assist, Team Viewer, Remote Help and Remote Control?

Thanks,
Dean
