### ISSUE TITLE
SoftwareCode doesn't exist in v_LU_SoftwareList_Editable

### ISSUE THREAD

**Issue by AquinoN** [MicrosoftDocs/memdocs#271]
I think you meant to join on SoftwareKey - can you confirm?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23fda686-e17b-01ca-1e3e-fdbbe7a5b0ac
* Version Independent ID: 8c0a9e98-1941-629d-9c10-e2586e8b0f9f
* Content: [Sample queries for asset intelligence - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/develop/core/understand/sqlviews/sample-queries-asset-intelligence-configuration-manager)
* Content Source: [memdocs/configmgr/develop/core/understand/sqlviews/sample-queries-asset-intelligence-configuration-manager.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/develop/core/understand/sqlviews/sample-queries-asset-intelligence-configuration-manager.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @AquinoN for the feedback. The ConfigMgr SDK content hasn't changed in a long time, and it's an area in which we're not actively investing beyond basic maintenance and some new functionality. If you'd like to submit a change for this issue, see [How to contribute](https://docs.microsoft.com/sccm/core/understand/use-docs#bkmk_contribute).
