### ISSUE TITLE
No mention of health check devices

### ISSUE THREAD

**Issue by johnjohnjohn87** [MicrosoftDocs/memdocs#2714]
There is no mention here (on anywhere else I could find) of "CPC-Hth" devices, which I assume are used for health checks. This blog post implies that they are created during health checks, but you can imagine our surprise when we stumbled across them in our environment. https://techcommunity.microsoft.com/t5/healthcare-and-life-sciences/deploy-co-management-collections-for-windows-365-cloud-pc/ba-p/3282792

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cedbfe8-0fd2-a186-8477-642aa1df16c2
* Version Independent ID: 2a4e990f-345a-302c-fb52-fb43db662a09
* Content: [Azure network connection health checks in Windows 365](https://docs.microsoft.com/en-us/windows-365/enterprise/health-checks)
* Content Source: [windows-365/enterprise/health-checks.md](https://github.com/MicrosoftDocs/memdocs/blob/main/windows-365/enterprise/health-checks.md)
* Service: **cloudpc**
* Sub-service: ****
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
39258193

**Comment by mutualtrust-it** [comment]
Any updates to John's question? We have recently configured W365 and I have noticed the CPC-HTH* PC object as well. Don't want to remove in just in case it causes issues with the service.

**Comment by ErikjeMS** [comment]
Repinged PM.
