### ISSUE TITLE
Differentiate between Scope Tags on Role and Role Assignment.

### ISSUE THREAD

**Issue by chblac** [MicrosoftDocs/memdocs#2718]
Both Role and Role Assignment have "Scope Tags".  How are they different?  When should each be used?  What happens if the Role defines Tag1, and the Role Assignment defines Tag2?  Does the user have Tag1, Tag2, Tag1+Tag2?  What if one of them defines the Default tag?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3eaa886-918b-127e-ad4b-d829e99b0d44
* Version Independent ID: 87240468-dd25-7f45-740b-f078cd5deac7
* Content: [Role-based access control (RBAC) with Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/role-based-access-control)
* Content Source: [memdocs/intune/fundamentals/role-based-access-control.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/role-based-access-control.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@chblac Thank you for your feedback. The scope tags on your roles are not the ones that are used to control what the admins can actually see, but just setting up a scope tag for this specific role.

You can assign scope tags to an Intune admin only from the role assignments blade. You can only assign a scope tag you have in your role assignment(s).

If it is still not clear, I'd recommend you watch our Video on Intune Role-Based Access and Scope Tags

https://www.youtube.com/watch?v=loiAtmpQbmo

Hope this helps


Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@msbemba Gentle reminder

**Comment by msbemba** [comment]
@chblac I have added a note to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2839

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @chblac Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
