### ISSUE TITLE
Scope Groups need more clarity

### ISSUE THREAD

**Issue by chblac** [MicrosoftDocs/memdocs#2719]
The explanation for "Scope (Groups)" needs improvement.  It currently says "a group containing the users/devices that the member above will be allowed to manage."  A different page, under "Scope Tag details", adds "You can only target groups that are listed in the Scope (Groups) of your role assignment."

Scope Groups constrain two things:
1. You can only target groups that are listed in the Scope (Groups) of your role assignment.
2. You can only modify objects which are untargeted, or which are only targeted to groups listed in the Scope (Groups) of your role assignment.

Both of those things should be listed here, in the primary place where Scope (Groups) are described.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f1d18db-e70a-fc44-a6c2-0de778d625c2
* Version Independent ID: bad0c80b-675f-dd39-7f01-8020e62f1d0a
* Content: [Assign a role to an Intune user](https://docs.microsoft.com/en-us/mem/intune/fundamentals/assign-role)
* Content Source: [memdocs/intune/fundamentals/assign-role.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/assign-role.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@chblac Thank you for your feedback.  You create scope groups first and when you assign a scope tag, you can only target groups that are listed in the Scope (Groups) of your role assignment.

You are correct, you can only modify which are only targeted to groups listed in the Scope (Groups) of your role assignment.

I'm not sure if this document needs modification as this is available in the doc set already.

Hope this helps!

Thanks
Sri

**Comment by chblac** [comment]
+ @Joshua ***@***.***>, @Karthic ***@***.***>, @Alemeshet ***@***.***>

This is regarding documentation feedback Scope Groups need more clarity · Issue #2719 · MicrosoftDocs/memdocs (github.com)<https://github.com/MicrosoftDocs/memdocs/issues/2719>, filed in response to this ICM: Incident-304188375 Details - IcM (microsofticm.com)<https://portal.microsofticm.com/imp/v3/incidents/details/304188375/home>.

Hi Sri,

Can you please share where that information is clearly explained in the doc set?  I couldn't find it, nor could several others, which suggests customers may not easily find it either.  Even if it is described elsewhere, it should also​ be described (or at least linked to) from this page.

Thanks,
Chris

________________________________

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@chblac I have added a note to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2840

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit The changes are merged.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @chblac Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
