### ISSUE TITLE
MMA clearification

### ISSUE THREAD

**Issue by johnjohnjohn87** [MicrosoftDocs/memdocs#272]
Does the 2002+ ATP onboarding include installation of the MMA for OSs below Windows 10 and Server 2019? If so, will ConfigMgr be handling updates of the MMA automatically?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57274525-66aa-bdf5-9536-7c0b42187d2e
* Version Independent ID: 7515bc3f-b501-a8c2-91b0-c64a0284e129
* Content: [Microsoft Defender Advanced Threat Protection - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/protect/deploy-use/windows-defender-advanced-threat-protection#feedback)
* Content Source: [memdocs/configmgr/protect/deploy-use/windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/protect/deploy-use/windows-defender-advanced-threat-protection.md)
* Product: **configuration-manager**
* Technology: **configmgr-protect**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by johnjohnjohn87** [comment]
clarification :(

**Comment by aczechowski** [comment]
Thanks @johnjohnjohn87 for the question. I'm checking with the engineering team

**Comment by johnjohnjohn87** [comment]
Sorry, but I didn't see an answer to this question anywhere. Did I miss it?

John
________________________________

**Comment by mestew** [comment]
@johnjohnjohn87 The doc changes should be published live a bit later. Probably by tomorrow 11 AM pacific if I had to guess. 
Onboarding will install the MMA agent if it's needed by the client. CM doesn't update it automatically.
