### ISSUE TITLE
VPP workflow is no longer valid. 

### ISSUE THREAD

**Issue by brkdncr** [MicrosoftDocs/memdocs#2725]
Hi, the workflow for renewing VPP with Apple has changed significantly.  The steps and screenshots are no longer valid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: babf49ae-ec79-e627-9dbf-2df2eb8909ab
* Version Independent ID: 90f3f372-9326-473e-3f82-e28e89853d49
* Content: [Get an Apple MDM Push certificate for Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/apple-mdm-push-certificate-get)
* Content Source: [memdocs/intune/enrollment/apple-mdm-push-certificate-get.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/apple-mdm-push-certificate-get.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@brkdncr Thank you for your feedback. I was able to check and looks like the steps are up to date. In case, you need any specific changes, feel free to mention them in your feedback.

Thanks
Sri

**Comment by NxSoftware** [comment]
The linked document is for MDM APNs certificate creation and renewals, not VPP.

**Comment by msbemba** [comment]
@yogkumgit This can be closed. The document is up to date and no changes are required.
