### ISSUE TITLE
Word change in navigation guidance .... select a policy > Overview

### ISSUE THREAD

**Issue by gbms311** [MicrosoftDocs/memdocs#2726]
This info https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new#updated-app-configuration-policies-list, should, be changed 

from
... to view whether an app configuration policy has been assigned, navigate to [Microsoft Endpoint Manager admin center] > Apps > App configuration policies > _select a policy_ > **Overview**.

To
... to view whether an app configuration policy has been assigned, navigate to [Microsoft Endpoint Manager admin center] > Apps > App configuration policies > _select a policy_ > **Properties**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d16c28db-1e8e-31fa-6127-3050a2940422
* Version Independent ID: 4cf9a244-1ae5-1637-48f7-3f503d400da6
* Content: [What's new in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new)
* Content Source: [memdocs/intune/fundamentals/whats-new.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/whats-new.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@gbms311 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2754

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @gbms311 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
