### ISSUE TITLE
No longer part of organization

### ISSUE THREAD

**Issue by tmccasland** [MicrosoftDocs/memdocs#2729]
I am no longer with the organization who manages my device so I can't do step 1 listed below:

Remove a device
Follow these steps to remove a device you no longer need for work or school from Intune.
1. Sign in to the Company Portal app and select Devices.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de7015db-d547-9c56-fbcd-9d99b8e6186c
* Version Independent ID: 8a31fdf7-e4b4-5688-d467-e63546938dfd
* Content: [Remove your iOS device from Intune](https://docs.microsoft.com/en-us/mem/intune/user-help/unenroll-your-device-from-intune-ios)
* Content Source: [memdocs/intune/user-help/unenroll-your-device-from-intune-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/unenroll-your-device-from-intune-ios.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@tmccasland Thank you for your feedback. Ideally, the organization should have disabled your account inturn removing your device from intune. However, if this is not the case, I'd recommend contacting your Old Organization's Support person as even Microsoft support cannot fix it from the backend.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @tmccasland Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
