### ISSUE TITLE
Why aren't the required providers referenced here?  The conversions fail if they are not present.

### ISSUE THREAD

**Issue by cjr145** [MicrosoftDocs/memdocs#2730]
This doc should list the required providers like this blogger does:  

https://model-technology.com/blog/how-to-convert-your-cloud-management-gateway-to-a-virtual-machine-scale-set/?msclkid=9c8590fac70911ec8c0b646f6ed5faea

Might also be nice to have some info on updating your DNS like the blog does too.

Thanks for listening.

-Curt

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12ab4165-870a-9fea-872a-35c03d2ba338
* Version Independent ID: b9015594-b05d-05dd-ef03-a99c3a4be225
* Content: [Modify a CMG - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/modify-cloud-management-gateway)
* Content Source: [memdocs/configmgr/core/clients/manage/cmg/modify-cloud-management-gateway.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/configmgr/core/clients/manage/cmg/modify-cloud-management-gateway.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @cjr145. See the important note at the top of the section [Process to convert a CMG to a virtual machine scale set](https://docs.microsoft.com/mem/configmgr/core/clients/manage/cmg/modify-cloud-management-gateway#process-to-convert-a-cmg-to-a-virtual-machine-scale-set):

> First review the prerequisites for [virtual machine scale sets](https://docs.microsoft.com/mem/configmgr/core/clients/manage/cmg/plan-cloud-management-gateway#virtual-machine-scale-sets). For example, make sure that you register the necessary [Azure resource providers](https://docs.microsoft.com/mem/configmgr/core/clients/manage/cmg/configure-azure-ad#configure-azure-resource-providers) in the subscription.

And also see the section on [Update or create a DNS CNAME](https://docs.microsoft.com/mem/configmgr/core/clients/manage/cmg/modify-cloud-management-gateway#update-or-create-a-dns-cname). After a brief review, it looks the same as what's referenced in the blog post.

Let me know if I'm missing something.
