### ISSUE TITLE
This document does not reflect the current Endpoint site's setup.  it is not useful in it's current form.

### ISSUE THREAD

**Issue by therainkin** [MicrosoftDocs/memdocs#2733]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c91281a-bdba-ff2d-6cb5-7ac45396397e
* Version Independent ID: 1a9e425f-7977-66be-eeb5-b41646de2d52
* Content: [Windows Autopilot motherboard replacement](https://docs.microsoft.com/en-us/mem/autopilot/autopilot-mbr)
* Content Source: [memdocs/autopilot/autopilot-mbr.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/autopilot-mbr.md)
* Product: **w10**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @therainkin for the feedback. We have plans to review and revise the Autopilot content, so thanks for calling attention to this one.

**Comment by frankroj** [comment]
Thanks for the feedback @therainkin. I am not sure I quite understand your comment regarding this particular document. However we have recently made significant updates to this document. I am going to go ahead and close out this feedback item, but if you have any additional feedback regarding this document, please open a new feedback item and provide as much detail as you can regarding the document, including sections that you feel need clarification.
