### ISSUE TITLE
Please  correct  'Andriod'  should be  'Android'

### ISSUE THREAD

**Issue by alfonso-rodriguez-2022** [MicrosoftDocs/memdocs#2739]
[Enter feedback here]

Here is the link:

It's also mispelled in the Title.

https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new#support-for-audio-alert-on-**andriod**-corporate-owned-work-profiles-and-fully-managed-cobo-and-cope-devices

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d16c28db-1e8e-31fa-6127-3050a2940422
* Version Independent ID: 4cf9a244-1ae5-1637-48f7-3f503d400da6
* Content: [What's new in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new)
* Content Source: [memdocs/intune/fundamentals/whats-new.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/whats-new.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@alfonso-rodriguez-2022 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2755

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @alfonso-rodriguez-2022 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
