### ISSUE TITLE
MSFT SE - Suggestion for Note in MECM Bitlocker TS - HAADJ = AAD escrow

### ISSUE THREAD

**Issue by GitBurgr** [MicrosoftDocs/memdocs#2740]
Please make a note to state that if during an OSD TS, the computer is HAADJ prior to the step where the Bitlocker step escrows to AAD, the bitlocker-api will escrow to AAD first. 

We have internal docs and case numbers proving this and it could prevent some cases.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8d2232b-5503-07b6-29fd-8afcdcea9a89
* Version Independent ID: 9621b35d-5928-2319-1048-eff6fa6a2e70
* Content: [Task sequence steps - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/osd/understand/task-sequence-steps#choose-where-to-create-the-recovery-key)
* Content Source: [memdocs/configmgr/osd/understand/task-sequence-steps.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/configmgr/osd/understand/task-sequence-steps.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @GitBurgr for the feedback. I talked with a SME in Microsoft Support (Frank) who made a good point that this is really behavior of the OS/BitLocker, not ConfigMgr/task sequence. At some point we need to draw the line on how much core BitLocker behavior we include in the already extensive ConfigMgr docs. So I'm going to close this issue.

But if you're passionate about adding something to the Enable BitLocker task sequence step section, you can make the contribution yourself! 😄 For more info, see https://docs.microsoft.com/contribute
