### ISSUE TITLE
Windows 10 Enterprise LTSC

### ISSUE THREAD

**Issue by jcameron4580** [MicrosoftDocs/memdocs#2741]
Does Windows 10 Enterprise LTSC is supported for Kiosk mode multi apps ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97b3556b-5cb1-2eeb-e793-5efff254ddd7
* Version Independent ID: 16117a39-76b5-a7ef-7aa5-86678fe38013
* Content: [Kiosk settings for Windows 10/11 in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/configuration/kiosk-settings-windows)
* Content Source: [memdocs/intune/configuration/kiosk-settings-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/kiosk-settings-windows.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by msbemba** [comment]
@jcameron4580 Thank you for your feedback. From the information that we have, it is not supported for Kiosk mode multi apps 
https://techcommunity.microsoft.com/t5/windows-it-pro-blog/ltsc-what-is-it-and-when-should-it-be-used/ba-p/293181

However, I'd recommend you leave a feedback on our Main feedback portal so a Product/dev engineer can provide you information if this is in the roadmap.

Main feedback portal - https://feedbackportal.microsoft.com/

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@jcameron4580  Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
