### ISSUE TITLE
Unable to Complete the Bypass

### ISSUE THREAD

**Issue by dmylar** [MicrosoftDocs/memdocs#2742]
Attempted to perform this action. Which worked up to a point. When attempting to sign into the device only using the 'Activation lock bypass code' I was unable to input the code only and leave the username field blank. To get the password field to populate you have to enter some kind of username. I tried with just an 'a' and with the prior iCloud account username and used the full code and the code without the hyphens. Of which, none were successful. Did this process change recently as Apple changes the setup process quite regularly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dc4921c-d09a-69b3-4e1d-639d51c18cbc
* Version Independent ID: 5026148c-f64e-e824-64da-63fcfa371244
* Content: [Bypass iOS/iPadOS Activation Lock with Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/remote-actions/device-activation-lock-disable)
* Content Source: [memdocs/intune/remote-actions/device-activation-lock-disable.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/device-activation-lock-disable.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@dmylar Thank you for your feedback. There has been no information about the change in process, However, in your case, I'd recommend you to contact Microsoft support via the need help section in the admin center so that one of our support representatives will be able to assist you.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @dmylar Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
