### ISSUE TITLE
Remove sentence

### ISSUE THREAD

**Issue by felizondojr** [MicrosoftDocs/memdocs#2744]
Please remove the sentence in the first paragraph stating customers can leave the workloads in Pilot Intune indefinitely. A pilot should be just that--a pilot. This will (and has) perpetuated the stance to keep things "as-is". I get we need to meet customers where they are, but we don't want them to maintain status quo.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96f4b08d-966b-c023-b9df-cee774b1d4de
* Version Independent ID: 16bb8aae-2f24-0c77-f1c8-b59e93353174
* Content: [Enable co-management - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/comanage/how-to-enable)
* Content Source: [memdocs/configmgr/comanage/how-to-enable.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/configmgr/comanage/how-to-enable.md)
* Product: **configuration-manager**
* Technology: **configmgr-comanage**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @felizondojr for the feedback...I don't disagree, but at the same time, that's how the product works today. So I think this might be better aimed as product feedback to not call it a pilot group but some other terminology. You can file product feedback for ConfigMgr at https://feedbackportal.microsoft.com/feedback/forum/4669adfc-ee1b-ec11-b6e7-0022481f8472
