### ISSUE TITLE
2nd root cause for 0x80180014  identified 

### ISSUE THREAD

**Issue by itguysocal** [MicrosoftDocs/memdocs#2748]
The resolution provided for 0x80180014 is incomplete. The 2nd remedy is to remove the device enrollment restriction for Windows (MDM) Personally owned devices.

![image](https://user-images.githubusercontent.com/43482381/166866395-0ba7fe4a-ea92-4701-b6e8-3a2750d0d6ea.png)

#ATCP

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2da4bbd-faa6-e6d5-07c1-946f5f7da2f5
* Version Independent ID: d1040d9e-7e73-b308-65a1-e141f07ed2dc
* Content: [Windows Autopilot known issues](https://docs.microsoft.com/en-us/mem/autopilot/known-issues#device-based-conditional-access-policies)
* Content Source: [memdocs/autopilot/known-issues.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/known-issues.md)
* Product: **w10**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @itguysocal for the feedback. I'm making some changes to the Autopilot content, which I hope will publish next week. I'll sneak this change in.
