### ISSUE TITLE
Limitations on applying token Auth to large environment?

### ISSUE THREAD

**Issue by ashutosh-3004** [MicrosoftDocs/memdocs#275]
1) - Is there any limitation on applying token based Auth in environment having 100K+ client base? We do anyway look to actively use it for 30-40% client base.
2) - Is token Auth FIPS-compliant from encryption aspects?

Thanks in advance!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60a7510b-10d9-e7e2-f848-d57d69d7fe10
* Version Independent ID: d4e9a557-ca23-3727-52b8-b81c6f767757
* Content: [Token-based authentication for CMG - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/deploy/deploy-clients-cmg-token)
* Content Source: [memdocs/configmgr/core/clients/deploy/deploy-clients-cmg-token.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/deploy/deploy-clients-cmg-token.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @ashutosh-3004, I'm confirming with engineering before I respond

**Comment by ashutosh-3004** [comment]
Hi @aczechowski Just checking if you got any update on topics.

**Comment by aczechowski** [comment]
1. No limitations. We’ve tested with large scale environments and not found any issues. Managing bulk tokens in a large environment might be challenging. But for the auto-generated tokens, will be fine. Azure AD has been using similar tokens for years.
2. The same story for FIPS compliant as always – Windows supports FIPS, we support Windows. All of our [crypto algorithms](https://docs.microsoft.com/mem/configmgr/core/plan-design/security/cryptographic-controls-technical-reference) are FIPS-compliant.
