### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Rowantrek** [MicrosoftDocs/memdocs#2752]
Links to Intune are broken/old.

Menu Structure has changed.

I can no longer see the Education Profiles in Intune.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bc0159d-5a5e-ea2c-042d-bd5ead842d0b
* Version Independent ID: 83266995-5234-3b09-784d-75bb1844e5f3
* Content: [Intune settings for the iOS/iPadOS Classroom app - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/education-settings-configure-ios)
* Content Source: [memdocs/intune/fundamentals/education-settings-configure-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/education-settings-configure-ios.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@Rowantrek Thank you for your feedback. I'll update the document with the navigation changes shortly. 

Thanks
Sri

**Comment by msbemba** [comment]
@Rowantrek Thank you for your feedback. For the Profiles navigation, I have involved the author to fix it. We have made changes to the Intune LInks via PR#https://github.com/MicrosoftDocs/memdocs/pull/2817

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Rowantrek Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
