### ISSUE TITLE
Can set up CMG on azure china, 21Vianet?

### ISSUE THREAD

**Issue by IvyMS1990** [MicrosoftDocs/memdocs#2753]
[Enter feedback here]
My cx want to set up CMG on azure china. However, in this doc, it only allow public azure and us government. Can set up CMG on azure china?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08585d2d-c8d3-d732-5884-1a01069270ae
* Version Independent ID: 982da2bc-3015-cdad-cc51-a35cb1f9d19a
* Content: [Set up checklist for CMG - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/set-up-checklist)
* Content Source: [memdocs/configmgr/core/clients/manage/cmg/set-up-checklist.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/configmgr/core/clients/manage/cmg/set-up-checklist.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by msbemba** [comment]
@IvyMS1990 Thank you for your feedback. You are correct, it is only available for Azure US government cloud or Azure public Cloud. It is not available for Azure China yet. You can provide your feedback about this directly on our main feedback portal -https://feedbackportal.microsoft.com/, so one of our dev/product engineers can let you know if it is the roadmap or why this is not available in China yet.

Hope this helps!

Thanks
Sri
