### ISSUE TITLE
Updated solutions of Microsoft Endpoint Manager brand

### ISSUE THREAD

**Issue by ChadSimmons** [MicrosoftDocs/memdocs#2757]
Currently, the following solutions are listed as part of the Microsoft Endpoint Manager brand

https://docs.microsoft.com/en-us/mem/configmgr/core/understand/microsoft-endpoint-manager-faq#what-is-microsoft-endpoint-manager-

- [Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/)
- [Intune](https://docs.microsoft.com/en-us/mem/intune/)
- [Desktop Analytics](https://docs.microsoft.com/en-us/mem/configmgr/desktop-analytics/overview)
- [Autopilot](https://docs.microsoft.com/en-us/mem/autopilot/enrollment-autopilot)
- Other features in the [Microsoft Endpoint Manager admin console](https://techcommunity.microsoft.com/t5/enterprise-mobility-security/microsoft-intune-rolls-out-an-improved-streamlined-endpoint/ba-p/937760)

With the pending retirement of Desktop Analytics and growth of Endpoint Analytics, is it time to update the brand?

- [Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/)
- [Intune](https://docs.microsoft.com/en-us/mem/intune/)
- [Desktop Analytics](https://docs.microsoft.com/en-us/mem/configmgr/desktop-analytics/overview)*
- [Endpoint Analytics](https://docs.microsoft.com/en-us/mem/analytics/overview)
- [Update Compliance](https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-get-started)
(though this may technically be part of Windows, not MEM)
- [Autopilot](https://docs.microsoft.com/en-us/mem/autopilot/enrollment-autopilot)
- Other features in the [Microsoft Endpoint Manager admin console](https://techcommunity.microsoft.com/t5/enterprise-mobility-security/microsoft-intune-rolls-out-an-improved-streamlined-endpoint/ba-p/937760)

*retirement scheduled for November 30, 2022

**Comment by frankroj** [comment]
Thank you for the feedback @ChadSimmons. There has been major rebranding of Configuration Manager, Intune, and Autopilot since you provided this feedback. Additionally there really wasn't anything actionable from the doc team regarding this request. For these reasons I am going to go ahead and close this feedback item. If you have additional feedback regarding the docs themselves, please let us know.
