### ISSUE TITLE
Application Status reporting behavior is not detailed for Microsoft Store apps

### ISSUE THREAD

**Issue by jerryabo** [MicrosoftDocs/memdocs#2764]
Device View
Install status view on the Windows device will show "Available for install" and will not be updated whether a user installs or uninstalls the application.

Application View (device and user)
"No results"

Proposed minimum edit to this page, for consideration, under the first Note:

From: Android Store apps that are deployed as Available do not report their installation status.
To: **_Microsoft Store and_** Android Store apps that are deployed as Available do not report their installation status.

For additional context, see incident 301285330 and/or ping jerryabo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c71db3d2-8cf6-0d67-4784-f704a2829bbc
* Version Independent ID: e8911088-a16a-e8db-b415-f8b61e4e6f5a
* Content: [Monitor app information and assignments - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-monitor#device-and-user-status-graphs)
* Content Source: [memdocs/intune/apps/apps-monitor.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/apps-monitor.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@jerryabo Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2782

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jerryabo Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
