### ISSUE TITLE
ConfigMgr client during Autopilot typo?

### ISSUE THREAD

**Issue by nhogarth86** [MicrosoftDocs/memdocs#2765]
Under the important note about installing the ConfigMgr client during Autopilot with Hybrid Azure AD Join, it says "You can't deploy the Configuration Manager client while provisioning a new computer in Windows Autopilot user-driven mode for hybrid Azure AD join. This limitation is due to the identity change of the device during the Azure AD-join process". Is it a typo where it says "This limitation is due to the identity change of the device during the Azure AD-join process" ? 

Shouldn't it say "during the Hybrid Azure AD Join process" because the device is originally a device in Azure AD with the serial name, but the computer name is then renamed based on the Intune domain join profile.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 875e279b-9029-d1e5-8a6c-0e93ce38ddba
* Version Independent ID: 80bc34d7-3ef7-1c4f-da41-0474b1c5f4a4
* Content: [Co-manage internet-based devices - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/comanage/how-to-prepare-win10#windows-autopilot)
* Content Source: [memdocs/configmgr/comanage/how-to-prepare-Win10.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/configmgr/comanage/how-to-prepare-Win10.md)
* Product: **configuration-manager**
* Technology: **configmgr-comanage**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @nhogarth86 fair feedback :) I'm making some changes to that article for an upcoming release, so added "hybrid" as you suggested. Thanks!
