### ISSUE TITLE
Device Restart Behaviour

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/memdocs#2766]
How does "Determine behavior based on return codes" differ from "App install may force a device restart"? I can read the words, but they seem to amount to the same thing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca840cce-3b99-3009-c8fa-d5fab6ae37d0
* Version Independent ID: 928b9e37-626a-8d50-c6a1-ac0b5cad4be4
* Content: [Add and assign Win32 apps to Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-win32-add)
* Content Source: [memdocs/intune/apps/apps-win32-add.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/apps-win32-add.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@Air-Git  Thank you for your feedback.

Determine behavior based on return codes: This option means that the device will restart based on the configured return code. With this configuration a Hard reboot return code will immediately trigger a restart of the device and a Soft reboot return code will notify the user that a restart is required to finish the installation.


App install may force a device restart: This option means that the Win32 app installation is allowed to complete without suppressing restarts. With this configuration, a Hard reboot return code will notify the user that a restart of the device will be triggered in 120 minutes and a Soft reboot return code will notify the user that a restart is required to finish the installation.

I have added this information to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2783

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Air-Git Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by jmerriweather** [comment]
"App install may force a device restart: This option means that the Win32 app installation is allowed to complete without suppressing restarts. **With this configuration, a Hard reboot return code will notify the user that a restart of the device will be triggered in 120 minutes and a Soft reboot return code will notify the user that a restart is required to finish the installation.**" 

This does not reflect the behaviour of Intune as of July 2023.
