### ISSUE TITLE
Eval link doesn't work

### ISSUE THREAD

**Issue by burtybob** [MicrosoftDocs/memdocs#2768]
The https://www.microsoft.com/evalcenter/evaluate-system-center-configuration-manager-and-endpoint-protection link no longer goes to the eval center and ends up going to the generic download (https://www.microsoft.com/en-us/download) area. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b412c586-a84c-7c81-ed61-05011d4bf36d
* Version Independent ID: 8becebc8-69c0-08a4-c89f-cb3d2bfe4708
* Content: [Get installation media - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/install/get-install-media)
* Content Source: [memdocs/configmgr/core/servers/deploy/install/get-install-media.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/configmgr/core/servers/deploy/install/get-install-media.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @burtybob for filing the feedback. We're aware of the issue. I'm investigating next steps.

**Comment by aczechowski** [comment]
See https://techcommunity.microsoft.com/t5/windows-11/accessing-trials-and-kits-for-windows-eval-center-workaround/m-p/3361125

We'll update this and other articles soon.
