### ISSUE TITLE
Azure AD vs Certificate/token-based

### ISSUE THREAD

**Issue by JonathanLefebvreGlobensky** [MicrosoftDocs/memdocs#277]
it should more clear what differences are between the various client auth options available. It can be pretty important to know that user based application deployment only works with AAD and not over Certificate/token-based auth.  It's only visible in the scenarios with this small note: Management activities are the same as the first scenario, as well as: Software distribution to the user.

easy to miss this out

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07d4e4f7-68ed-e604-b577-2c18617d1c2e
* Version Independent ID: 1ce10bc0-2a6d-405a-a9ae-46adfaac8fe6
* Content: [Plan for cloud management gateway - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/plan-cloud-management-gateway#feedback)
* Content Source: [memdocs/configmgr/core/clients/manage/cmg/plan-cloud-management-gateway.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/cmg/plan-cloud-management-gateway.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @JonathanLefebvreGlobensky for the feedback. It's mentioned in several other places:
- [Table of supported features](https://docs.microsoft.com/mem/configmgr/core/clients/manage/cmg/plan-cloud-management-gateway#support-for-configuration-manager-features)
- [Deploy an app](https://docs.microsoft.com/mem/configmgr/apps/deploy-use/deploy-applications#deploy-user-available-applications-on-azure-ad-joined-devices)
- CMG certificates article section on [different MP configurations](https://docs.microsoft.com/mem/configmgr/core/clients/manage/cmg/certificates-for-cloud-management-gateway#management-point-client-connection-mode-summary)
- Article on comm between endpoints, section on [client to MP comms](https://docs.microsoft.com/mem/configmgr/core/plan-design/hierarchy/communications-between-endpoints#bkmk_client2mp)

But...this question has come up a few times recently. So I'll add something to the [CMG FAQ](https://docs.microsoft.com/mem/configmgr/core/clients/manage/cmg/cloud-management-gateway-faq) as well. 😄

**Comment by aczechowski** [comment]
I added to the FAQ, it should publish live later today
