### ISSUE TITLE
Microsoft Lens is missing

### ISSUE THREAD

**Issue by svenhallauer** [MicrosoftDocs/memdocs#2770]
The Microsoft Lens app for iOS and Android is missing from the list of apps that support App Protection Policies.  The app was formerly known as Office Lens, but that one isn't in the table either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02165898-ec07-86e1-adc5-18f60bec9689
* Version Independent ID: 7b6c64c4-3304-42b0-079a-7dee609c5e4f
* Content: [Supported Microsoft Intune apps](https://docs.microsoft.com/en-us/mem/intune/apps/apps-supported-intune-apps)
* Content Source: [memdocs/intune/apps/apps-supported-intune-apps.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/apps-supported-intune-apps.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@yogkumgit  The Document is updated and the issue can be closed.
