### ISSUE TITLE
Missing instruction to connect to Wi-Fi in OOBE

### ISSUE THREAD

**Issue by RhysCLCsAustralia** [MicrosoftDocs/memdocs#2772]
This section does not address modern laptops with only Wi-Fi (no ethernet):
https://docs.microsoft.com/en-us/mem/autopilot/add-devices#:~:text=While%20OOBE%20is%20running%2C%20you%20can%20start%20uploading%20the%20hardware%20hash%20by%20opening%20a%20command%20prompt%20(Shift%2BF10%20at%20the%20sign%2Din%20prompt)%20and%20using%20the%20following%20commands%3A

Please include instruction on how to connect to Wi-Fi during OOBE:
While OOBE is running, you can start uploading the hardware hash by opening a command prompt (Shift+F10 at the sign-in prompt_**, you may need to connect to Wi-Fi first via the command "start ms-availablenetworks:"**_) and using the following commands:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea4a659b-65d0-26ec-c36a-9a21a72a09a8
* Version Independent ID: bff44b73-9021-6659-e212-66349c759989
* Content: [Manually register devices with Windows Autopilot](https://docs.microsoft.com/en-us/mem/autopilot/add-devices)
* Content Source: [memdocs/autopilot/add-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/add-devices.md)
* Product: **w10**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by frankroj** [comment]
Thank you for the feedback @RhysCLCsAustralia. I apologize for the delay in answering this feedback. Both Windows 10 22H2 and Windows 11 22H2 currently check for a network connection at the start of OOBE. If there is no network connection, then it will automatically prompt to connect to a wireless network. This may be a change in the latest versions of Windows. If you are not seeing this with other currently supported versions of Windows, please let me know and I will dig more into it. When testing, please make sure you are using the latest ISO with the latest updates for that version of Windows.
