### ISSUE TITLE
Define what Intune Connector access is required in "The computer must also have access to the internet and your Active Directory."

### ISSUE THREAD

**Issue by jerryabo** [MicrosoftDocs/memdocs#2776]
We defer to Network Requirements for Intune, on the Intune connector requirements,  but that doesn't appear to cover the access requirements needed for Onprem AD here: "The computer must also have access to the internet and your Active Directory." --Please explicitly define what protocols/ports are required or link to existing Windows AD requirements and required services (e.g. https://docs.microsoft.com/en-us/troubleshoot/windows-server/networking/service-overview-and-network-port-requirements) if they cover what is required by the connector - thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f93dd93-e003-36fc-02d6-07166537d914
* Version Independent ID: 1b860d13-bcf5-50da-89f9-ee12ece6edb2
* Content: [Enrollment for hybrid Azure AD-joined devices - Windows Autopilot](https://docs.microsoft.com/en-us/mem/autopilot/windows-autopilot-hybrid#install-the-intune-connector)
* Content Source: [memdocs/autopilot/windows-autopilot-hybrid.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/windows-autopilot-hybrid.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by msbemba** [comment]
@jerryabo Thank you for your feedback. We have added this to the Prerequisites section now

Have access to an Active Directory domain controller. The device must be connected to the organization's network so that it can:
1) Resolve the DNS records for the AD domain and the AD domain controller.
2) Communicate with the domain controller to authenticate the user.

Hope this helps!

Thanks
Sri

**Comment by jerryabo** [comment]
This isn't enough. Communication needs to be defined specifically - meaning protocols and open ports, e.g. ldap tcp port 389, rpc, etc.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by msbemba** [comment]
@jerryabo I will check with the author on the specific ports etc and provide an update.

Thanks
Sri

**Comment by yogkumgit** [comment]
@dougeby Please help us in resolving this issue. Thanks

**Comment by frankroj** [comment]
Assigning request to myself to take care of documenting what ports are needed. Researching and will update once I have more information.

**Comment by frankroj** [comment]
Linked the following articles:

https://learn.microsoft.com/troubleshoot/windows-server/identity/config-firewall-for-ad-domains-and-trusts
https://learn.microsoft.com/azure/active-directory/hybrid/reference-connect-ports
https://learn.microsoft.com/troubleshoot/windows-server/networking/service-overview-and-network-port-requirements

via https://github.com/MicrosoftDocs/memdocs-pr/pull/9130

These article should address any questions the customer may have regarding ports.

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
Thank you @frankroj . @yogkumgit These articles should address any questions the customer may have regarding ports.

https://learn.microsoft.com/troubleshoot/windows-server/identity/config-firewall-for-ad-domains-and-trusts
https://learn.microsoft.com/azure/active-directory/hybrid/reference-connect-ports
https://learn.microsoft.com/troubleshoot/windows-server/networking/service-overview-and-network-port-requirements

**Comment by jerryabo** [comment]
@msbemba @yogkumgit it does not, please reopen this.

**Comment by frankroj** [comment]
Worked with PG and Jerry and finally found answers to ask. Made required changes via PR https://github.com/MicrosoftDocs/memdocs-pr/pull/9484

**Comment by sukh8282** [comment]
@frankroj The link (https://github.com/MicrosoftDocs/memdocs-pr/pull/9484) doesn't appear to work ?

**Comment by frankroj** [comment]
@sukh8282 The Memdocs-pr repository is only accessible to Microsoft employees. I just tried the link and it works fine.

**Comment by sukh8282** [comment]
@frankroj Thanks - I don't see the updated documentation that clearly defines "Still working internally on getting what specific AD ports are need by the connector to talk to AD." but your comment says "Worked with PG and Jerry and finally found answers to ask. Made required changes via PR" - Where are those answers documented please ?

**Comment by frankroj** [comment]
@sukh8282 It is located under the prerequisites at the top of the article. See the purple note in the following section:

https://learn.microsoft.com/mem/autopilot/windows-autopilot-hybrid#intune-connector-server-prerequisites

**Comment by sukh8282** [comment]
@frankroj Thanks
