### ISSUE TITLE
MDM profile removable, yes or no meaning

### ISSUE THREAD

**Issue by jackchenwork** [MicrosoftDocs/memdocs#2779]
[Enter feedback here]

"MDM profile removable: Tells you if users can remove the MDM profile from an enrolled device. Options:
Yes: Device users cannot unenroll devices.
No: Device users can unenroll devices."

Shouldn't "Yes" means device user can remove/unenroll device?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ee4c4fc-8cd2-34e7-9bfa-f4378a3a46b5
* Version Independent ID: e62806ea-d183-a3e3-08fd-9c0d1c3e7b50
* Content: [What is Microsoft Intune device enrollment - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment)
* Content Source: [memdocs/intune/enrollment/device-enrollment.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/device-enrollment.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @jackchenwork, thank you for reaching out to the Intune docs team. You are correct that the definitions should be switched around. We've updated the doc with that change and updated the values in the table to match. Those changes will be live by end of week. Thanks for your contribution!
