### ISSUE TITLE
UI Bug or documentation incorrect?

### ISSUE THREAD

**Issue by muelsSD** [MicrosoftDocs/memdocs#278]
On the intune portal, when I select disabled, all the options under enabled still show (Use tpm, pin length, etc.)  The only option that does not show those settings is not configured.  According to your documentation here, those options should only show when enabled is selected, which makes sense.  However, that is not what I have experienced, and I have heard of many others that experienced the same thing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6d32682-0e4e-449b-6ad5-001c631735d2
* Version Independent ID: 66419be7-51dc-f5e1-cf18-1a55866e4193
* Content: [Integrate Windows Hello for Business with Microsoft Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/windows-hello#feedback)
* Content Source: [memdocs/intune/protect/windows-hello.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/windows-hello.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@muelsSD   I’ve run this down with our engineering team and have an update for you, which I thought had been sent back in early June. :(  This policy area is being reworked as the current UI has some issues, including enabled and disabled being reversed (the underlying Windows CSP is called *Block* which isn't how Intune represents it here), and the visible list of settings behavior is different than it should be.  

Following is the short explanation for the primary setting, **Configure Windows Hello for Business**, which was updated i content earlier this month. 
Behavior for Configure Windows Hello for Business, when set to:  
-	**Disabled**, you *enable* WHfB. You have access to the settings, and they will apply.  
-	**Enabled**, you *disable* WHfB. These settings should be hidden.  
-	**Not configured**, the client devices default settings remain, and users can change them. These settings are hidden from the UI and won’t apply to devices.
