### ISSUE TITLE
Typo in text: Andriod -> Android

### ISSUE THREAD

**Issue by chapmanfreebornIT** [MicrosoftDocs/memdocs#2781]
Support for Audio Alert on Andriod corporate owned work profiles and fully managed (COBO and COPE) devices

should be:

Support for Audio Alert on Android corporate owned work profiles and fully managed (COBO and COPE) devices

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d16c28db-1e8e-31fa-6127-3050a2940422
* Version Independent ID: 4cf9a244-1ae5-1637-48f7-3f503d400da6
* Content: [What's new in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new)
* Content Source: [memdocs/intune/fundamentals/whats-new.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/whats-new.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@chapmanfreebornIT Thank you for your feedback. I could not find the typo anymore. Looks like the document has been recently updated as well.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@chapmanfreebornIT Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
