### ISSUE TITLE
Version 1910:  still can't set installation behavior as user, only system?

### ISSUE THREAD

**Issue by rejohnson76** [MicrosoftDocs/memdocs#279]
Doc notes "Version 1906: Set the deployment type installation behavior to Install for system.".  Trying to include an application that must be installed as user and nothing shows up for the PC.  Is this requirement fixed at some point?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e71a2bc-fe1a-6b20-6b97-6db8768c8e42
* Version Independent ID: c42cb159-f9c6-cec3-366b-cef5e902c0d0
* Content: [Create application groups - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/apps/deploy-use/create-app-groups)
* Content Source: [memdocs/configmgr/apps/deploy-use/create-app-groups.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/apps/deploy-use/create-app-groups.md)
* Product: **configuration-manager**
* Technology: **configmgr-app**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by rejohnson76** [comment]
I think this is actually OK now.  I had changed the application from install as system to install as user and refreshed the content but that didn't allow the application group to show up in Software Center.  I had to delete the user-based application, apply the change, then add the application to the group again.  Then the application group showed up in Software Center and successfully deployed.

**Comment by aczechowski** [comment]
Hi @rejohnson76 thanks for following up. It's not uncommon in various places to have to recreate the object (or sometimes just make some change to the object) after a site update for the new behavior to take effect.
