### ISSUE TITLE
What time measurement is used?

### ISSUE THREAD

**Issue by mcmaurer0** [MicrosoftDocs/memdocs#2795]
Ever heard of specifying units of measurement?

Minutes? Seconds? Miliseconds? Hours? Days? Centuries? 

What amount of time are we specifying? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c9c2c10-9fc0-4d62-af69-8155e7383005
* Version Independent ID: f6c78cb4-884a-5e60-0716-7f9d20c89f86
* Content: [Set up device to automatically lock when screen turns off - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/user-help/set-the-amount-of-time-before-your-device-is-locked-android)
* Content Source: [memdocs/intune/user-help/set-the-amount-of-time-before-your-device-is-locked-android.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/set-the-amount-of-time-before-your-device-is-locked-android.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @mcmaurer0, thanks for reaching out to the Microsoft Intune docs team with your question. 

The options on my phone range from "immediately" to _x_ seconds to _x_ minutes (all the way up to 30 minutes).  

As an example of how this requirement works: If my organization requires that devices lock after 15 minutes of idling, I could set my screen to auto lock at _15 minutes_, _15 seconds_, or _immediately_ and still meet their requirement. If I select an option that's greater than 15 minutes, such as _30 minutes_, or if I turn my screen lock off, I will not satisfy their requirement.  

Ideally, the initial message you receive about this requirement would tell you the time limit they set. Do you recall if it specified that info in the message? If not, let me know and I'll keep that in mind when updating this article. 

To help out a little more, I added a line to the article about needing to contact a support person for more details--your support person can clarify exactly what the requirement entails.
