### ISSUE TITLE
Policy Assignment and Tags

### ISSUE THREAD

**Issue by jamie-evans-at-mecro-dot-tech** [MicrosoftDocs/memdocs#280]
If an administrator creates a policy and assigns it to "All Devices", but they only have access to one scope (ie. the policy has the admin's scope tag applied), will the policy only apply to devices which have that tag, or will it apply to all devices regardless of the device's tags?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37f4d965-ae4c-c1d4-3318-4c4827324555
* Version Independent ID: 5e33c778-0522-da5b-e8c8-bfac4784ba84
* Content: [Use role-based access control (RBAC) and scope tags for distributed IT in Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/scope-tags#feedback)
* Content Source: [memdocs/intune/fundamentals/scope-tags.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/scope-tags.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
(7330462)

**Comment by ErikjeMS** [comment]
Repinged PM...

**Comment by praj-jain** [comment]
Hi Erik,

Please assign this to Craig Marl who is RBAC owner for Intune.
I am not part of Intune team.

Thanks,
Prajakta.

**Comment by MandiOhlinger** [comment]
@jamie-evans-at-mecro-dot-tech In your scenario, the assignment should fail. The assignment to all devices would be outside the admin’s delegated scope.
