### ISSUE TITLE
Acronym undefined

### ISSUE THREAD

**Issue by Ksbooth01** [MicrosoftDocs/memdocs#2800]
**VPP** apps and ebooks associated with the **VPP** token inherit the scope tags assigned to the associated **VPP** token.
- article contains NO reference to this acronym.  If you are going to abbreviate, please enumerate this first instance of the abbreviation 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37f4d965-ae4c-c1d4-3318-4c4827324555
* Version Independent ID: 5e33c778-0522-da5b-e8c8-bfac4784ba84
* Content: [Use role-based access control (RBAC) and scope tags for distributed IT in Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/scope-tags)
* Content Source: [memdocs/intune/fundamentals/scope-tags.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/scope-tags.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Ksbooth01 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
