### ISSUE TITLE
Licensing clarification FU policies

### ISSUE THREAD

**Issue by 0fflineDocs** [MicrosoftDocs/memdocs#2801]
Needs clarification. Is the following statement correct?
Windows Update for Business > requires at least Windows Pro
Feature Update policies in Intune > requires at least Windows Enterprise

Pre-requisites here state that E3/E5 or A3/A5 is required. But the Feature Update is supported for Windows Pro.
Does this mean that we only need one E3-license in the tenant and then we can target the Feature Update policy to all our Intune managed Windows Pro-devices? Or does every user/device targeted by a Feature Update policy need to at least have an Windows Enterprise license?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee0dbbde-b15e-4adf-b162-1114fddd8846
* Version Independent ID: 78275b5f-4d5b-f318-0cbf-a27ad35dffa0
* Content: [Configure feature updates policy for Windows 10 Windows 11 devices in Intune](https://docs.microsoft.com/en-us/mem/intune/protect/windows-10-feature-updates)
* Content Source: [memdocs/intune/protect/windows-10-feature-updates.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/windows-10-feature-updates.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@0fflineDocs Thank you for your feedback.

You are correct, Feature update is supported for windows Pro. M365 Business premium has also been added to the prerequisites. 

Every user/device targeted by a Feature Update policy need to at least have one of  the below licensing

Windows 10/11 Enterprise E3 or E5 (included in Microsoft 365 F3, E3, or E5)
Windows 10/11 Education A3 or A5 (included in Microsoft 365 A3 or A5)
Windows 10/11 Virtual Desktop Access (VDA) per user
Microsoft 365 Business Premium

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit  This can be closed.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @0fflineDocs Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
