### ISSUE TITLE
wrong file name for ps1

### ISSUE THREAD

**Issue by snydertl** [MicrosoftDocs/memdocs#2804]
[Enter feedback here]
The file name is mst-ca-provisioning.ps1 not mst-CA-readiness.ps1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d63aaa4-b32f-5ac0-6fd4-85fa9322b811
* Version Independent ID: 051eeee2-4aaf-38e7-8ff6-a0624a4f6855
* Content: [Use Microsoft Tunnel VPN gateway with Conditional Access policies](https://docs.microsoft.com/en-us/mem/intune/protect/microsoft-tunnel-conditional-access)
* Content Source: [memdocs/intune/protect/microsoft-tunnel-conditional-access.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/microsoft-tunnel-conditional-access.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@snydertl Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2827

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @snydertl Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
