### ISSUE TITLE
Classic PC Agent

### ISSUE THREAD

**Issue by iftikhariqbal** [MicrosoftDocs/memdocs#2809]
The page mentions 'For some tasks (like downloading software updates for the classic pc agent),..' can we get a reference link on it or some more information on what exactly is the classic pc agent?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c9c3475-56d4-026b-349f-f9cbc258537c
* Version Independent ID: 9c6476ed-8a47-bcb4-dfbf-25ba305c3b24
* Content: [Network endpoints for Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/intune-endpoints)
* Content Source: [memdocs/intune/fundamentals/intune-endpoints.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/intune-endpoints.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by yogkumgit** [comment]
@Smritib17 Please help us in resolving this issue. Thanks.

**Comment by Smritib17** [comment]
@iftikhariqbal, you are right. The Classic PC agent is legacy and has been removed from here. The changes should be live tomorrow.
