### ISSUE TITLE
Note section clarity

### ISSUE THREAD

**Issue by felizondojr** [MicrosoftDocs/memdocs#2812]
More clarity is needed on the note section around the assignment of a compliance policy to a device without a user sign-in. At face value, this doesn't make sense. What device isn't going to have a user signed at some point? I'm assuming this means there should be a compliance policy assigned to user groups and another assigned to device groups to cover compliance at all check-ins?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1a645fd-8887-d268-1ed5-984ebaeef577
* Version Independent ID: f9b5d099-41ea-b3f3-536f-de61885ac1d5
* Content: [Monitor results of your device compliance policies in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/compliance-policy-monitor)
* Content Source: [memdocs/intune/protect/compliance-policy-monitor.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/compliance-policy-monitor.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@felizondojr Thank you for your feedback.

Device groups are useful for managing devices that do not have dedicated users, such as kiosk devices, devices shared by shift workers, or devices assigned to a specific location.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @felizondojr Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
