### ISSUE TITLE
Outdated instructions for creating Autopilot device group

### ISSUE THREAD

**Issue by aronsmithdonovan** [MicrosoftDocs/memdocs#2815]
Instructions to [create an autopilot device group using Intune](https://docs.microsoft.com/en-us/mem/autopilot/enrollment-autopilot#create-an-autopilot-device-group-using-intune) are incorrect.

Correct group configuration (changes are bolded):
- Group type: Security
- Group name and group description: *arbitrary*
- Azure AD roles can be assigned to the group: **No**
- Membership type: **Dynamic device**
- Owners: *arbitrary*
- Dynamic device member: **select "Add dynamic query" and add rules as needed:**
  - to create a group that contains all Autopilot-registered devices: **Property = devicePhysicalIds, Operator = Contains, Value = [ZTDID]**
  - to create a group that includes all Autopilot devices with a specific group tag (the Azure AD device `OrderID`): **Property = devicePhysicalIds, Operator = Equals, Value = [OrderID]:179887111881**
  - to create a group that includes all your Autopilot devices with a specific Purchase Order ID: **Property = devicePhysicalIds, Operator = Equals, Value = [PurchaseOrderId]:76222342342**
- **Save dynamic device rules**
- **Create group**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97ce79c0-0014-f6f0-95f7-58574bfdefb3
* Version Independent ID: 40b3877e-a094-8d05-c95b-ca842c5ca8ce
* Content: [Create device groups for Windows Autopilot - Microsoft Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/autopilot/enrollment-autopilot)
* Content Source: [memdocs/autopilot/enrollment-autopilot.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/enrollment-autopilot.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @aronsmithdonovan for the feedback. We have a backlog of work in this area and hope to have someone soon that can devote some time to reviewing and updating. In the meantime, you're always welcome to contribute changes directly, which are more likely to happen sooner than later. 😉 For more info, see http://docs.microsoft.com/contribute.

**Comment by frankroj** [comment]
Thank you @aronsmithdonovan for the feedback. Sorry for the long delay in getting back to you on this. That article has since been updated. Additionally, this task is documented in detail several times in the new Autopilot cookbook. For example:

https://learn.microsoft.com/en-us/mem/autopilot/tutorial/user-driven/azure-ad-join-device-group
