### ISSUE TITLE
Typo in the text

### ISSUE THREAD

**Issue by wdiggle** [MicrosoftDocs/memdocs#2820]
I've noticed a typo in this page... in the starting paragraph it says...

App configuration policies can help you eliminate app setup up problems...

The paragraph has "setup" and "up" straight after it.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f99adcae-3960-b5f8-efd3-1603490519c7
* Version Independent ID: d9164111-640b-d88c-3dad-661179e5114e
* Content: [App configuration policies for Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-configuration-policies-overview)
* Content Source: [memdocs/intune/apps/app-configuration-policies-overview.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/app-configuration-policies-overview.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@wdiggle Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2828

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @wdiggle Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
