### ISSUE TITLE
Groups supported by The Available for enrolled devices (for Fully Managed and Corporate owned work profile devices)

### ISSUE THREAD

**Issue by Ikuko-Konno** [MicrosoftDocs/memdocs#2831]
The documentation describes it as follows

--------------
The Available for enrolled devices deployment intent is only supported for device groups when targeting Android Enterprise fully managed devices (COBO) and Android Enterprise corporate-owned personally-enabled (COPE) devices.
--------------

However, in The Available for enrolled devices assignment, Fully Managed and Corporate-owned work profile devices allows for both user groups and device groups to be deployed.
The way the documentation is written is misleading in that user groups are not supported.
Shouldn't the description be modified to say that both user groups and device groups are supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7ad786b-eac9-7979-9509-25e05673b35a
* Version Independent ID: 42d279ce-086f-be9f-821f-53d7100fa838
* Content: [Assign apps to groups in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-deploy)
* Content Source: [memdocs/intune/apps/apps-deploy.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/apps-deploy.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Ikuko-Konno Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
