### ISSUE TITLE
Contradictive sentence?

### ISSUE THREAD

**Issue by Zerowalker** [MicrosoftDocs/memdocs#2842]
Isn't this sentence contradictive, or am i just reading it wrong?
(I bolded the relevant part)

> Company Portal and **available apps are not supported:** Intune Company Portal app, the Intune Company Portal website are not supported on Shared iPads. Apps must be assigned as “required” to device groups containing the Shared iPad to install. **Available apps are supported** on Shared iPad.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c684f0e8-0795-4b02-1467-0f3eae2932d2
* Version Independent ID: b56cb3ec-36e9-eac2-46f0-cdd3ca75dcb4
* Content: [Shared iPad devices - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-shared-ipad)
* Content Source: [memdocs/intune/enrollment/device-enrollment-shared-ipad.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/device-enrollment-shared-ipad.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@Zerowalker Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2884

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Zerowalker Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
