### ISSUE TITLE
App protection Policies Microsoft Lists for android, and Lens for iOS and Android. 

### ISSUE THREAD

**Issue by Coopem16** [MicrosoftDocs/memdocs#2844]
I do not believe that Lists on Android and Lens on Android and iOS support support App Protection. Neither are listed on this page:
https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/concept-conditional-access-grant#require-approved-client-app
I have them configured in my app protection policies however, neither app picks up the policy and lens does not ever request a log in. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02165898-ec07-86e1-adc5-18f60bec9689
* Version Independent ID: 7b6c64c4-3304-42b0-079a-7dee609c5e4f
* Content: [Supported Microsoft Intune apps](https://docs.microsoft.com/en-us/mem/intune/apps/apps-supported-intune-apps)
* Content Source: [memdocs/intune/apps/apps-supported-intune-apps.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/apps-supported-intune-apps.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@Coopem16 Thank you for your feedback.  We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2885

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Coopem16 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
