### ISSUE TITLE
Policies out of date

### ISSUE THREAD

**Issue by JakeMoe** [MicrosoftDocs/memdocs#2845]
I'm trying to follow the instructions here, but have two issues:

Under Endpoint Security -> Microsoft Defender for Endpoint, there's a new section at the top that this page doesn't explain: "Endpoint Security Profile Settings", with a single setting "Allow Microsoft Defender for Endpoint to enforce Endpoint Security Configurations"

And then in the Endpoint Detection and Response policy, a new setting for "Microsoft Defender for Endpoint client configuration package type" is available, which I believe should be set to "Auto from Connector", according to this page: https://docs.microsoft.com/en-us/mem/intune/protect/endpoint-security-edr-policy#devices-managed-by-microsoft-endpoint-manager

However, I'm getting a message "An error occurred" when I try to set this, with nothing in "Request error details".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24fa182f-ace6-e7e2-ff98-91951be7d10e
* Version Independent ID: f1acb398-6d69-b91c-5ee0-3da3bbf7809f
* Content: [Configure Microsoft Defender for Endpoint in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/advanced-threat-protection-configure#enable-microsoft-defender-for-endpoint-in-intune)
* Content Source: [memdocs/intune/protect/advanced-threat-protection-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/advanced-threat-protection-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@JakeMoe  Hello Jake, and thanks for the questions.

For the first item, the setting **Allow Microsoft Defender for Endpoint to enforce Endpoint Security Configurations** is a toggle to enable support for a recently added capability, enforcing Defender for Endpoint configuration on devices that _are not_ managed by Intune, meaning not enrolled with Intune. 
-  For information on this, see:  [MDE Security Configuration Management](https://docs.microsoft.com/mem/intune/protect/mde-security-integration).  I'm submittin an update to call this out and link to that article.    

For the second item, the **Microsoft Defender for Endpoint client configuration package type** setting was added a couple months back. Unfortunately, we can’t help investigate an error or issue like that via this docs feedback forum. The error isn’t something I can reproduce on my tenant this morning and might have been transitory.  However, if that issue persists, reach out to support so they can investigate this for your tenant.

**Comment by JakeMoe** [comment]
Hi @Brenduns, I was mainly submitting that error in case there was something missing from the doco (a prereq or some additional config) that was preventing it from working.  I'd already submitted a support request for this, and we resolved it by creating a new policy rather than trying to modify the existing one.  I was just mentioning it in case it meant the docs needed further update.  :-)

**Comment by JakeMoe** [comment]
Hi @Brenduns I don't see the change in this page that you mentioned?  Does it take some time to roll out?

**Comment by Brenduns** [comment]
Hi Jake,

Unfortunately, publishing isn't on demand.  However, there is a greater delay than usual as something is gumming up the publishing queue today. I'd expect this will update by 11am pacific on Tuesday.  The new entry will be as follows, added to the opening section:


In addition to managing settings for Microsoft Defender for Endpoint on devices you manage with Intune, you can manage Defender for Endpoint security configurations on devices that aren't enrolled with Intune. This scenario is called Security Management for Microsoft Defender for Endpoint and requires configuring the Allow Microsoft Defender for Endpoint to enforce Endpoint Security Configurations toggle to On. For more information, see MDE Security Configuration Management<https://docs.microsoft.com/en-us/mem/intune/protect/mde-security-integration>.
