### ISSUE TITLE
Cannot find related Intune connection settings

### ISSUE THREAD

**Issue by luxu-ms** [MicrosoftDocs/memdocs#2849]
Hi Team,

[Enter feedback here]
In Microsoft 365 Defender -> settings, there is no setting of "endpoint" and "advanced features".
Only the three settings are as below:
<img width="844" alt="image" src="https://user-images.githubusercontent.com/92287281/172284559-bf964530-1136-40ac-a99b-37ca49757be6.png">

Please help guide how to enable the "Microsoft Intune connection" in current Microsoft 365 defender?

Thanks & Regards,
Lyle Xu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24fa182f-ace6-e7e2-ff98-91951be7d10e
* Version Independent ID: f1acb398-6d69-b91c-5ee0-3da3bbf7809f
* Content: [Configure Microsoft Defender for Endpoint in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/advanced-threat-protection-configure)
* Content Source: [memdocs/intune/protect/advanced-threat-protection-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/advanced-threat-protection-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by luxu-ms** [comment]
Hi @yogkumgit , 

Is it because the product behavior changed but the documentation still need time to sync?
Is there any guide how to configure Microsoft Defender for Endpoint in Intune?

Thanks & Regards,
Lyle Xu

**Comment by Brenduns** [comment]
@[luxu-ms](https://github.com/luxu-ms) Thanks for this question. While this isn't truly an Intune question, you got there while trying to connect Defender and Intune. I reached out to our Defender for Endpoint content writes and their product PMs. They took at look at this feedback and suggest this is one of two things:
1.	It might be (or have been?) a licensing refresh issue where it takes time for the license eligibility information to appear in MDE, which means it retuned not eligible and the relevant sections in the Defender portal don't show up.
2.	Another option, not believed to be relevant to this example but in general, is if the tenant had the license but the user doesn’t have sufficient permissions to MDE. that user would not see some nodes in MDE.
The content is accurate, so long as the backend details are in place (subscription, permissions, etc.). With that, there is nothing for us to fix in the current content. If this issue persists for your Tenant, please contact Support to get assistance. From a purely MDE standpoint, I recommend starting with Defender for Endpoint support in that case so you can get to useful assistance quickly. Once connected, issues with what’s visible in the MEM admin center would land with Intune.
