### ISSUE TITLE
Client communication on metered internet connections important note

### ISSUE THREAD

**Issue by silvermarkg** [MicrosoftDocs/memdocs#285]
The important note under the Limit option of the "Client communication on metered internet connections" section is confusing as it seems to imply the same as the two points above it. Does this note only apply to the Limit option, in which case, what does it mean? If it applies regardless of the setting, it should be moved to a more appropriate location.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c666f0e-89a1-dbe2-af7d-700a46aeea61
* Version Independent ID: 774f99b8-9403-1c77-abe5-54934f0d2f71
* Content: [Client settings - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/deploy/about-client-settings#metered-internet-connections)
* Content Source: [memdocs/configmgr/core/clients/deploy/about-client-settings.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/deploy/about-client-settings.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @silvermarkg for the feedback. I think it's a general statement, I'll move it to the bottom. Basically, if the user initiates an action (install an app) while on a metered connection, then the client honors that user intent.
