### ISSUE TITLE
video link doesn't load

### ISSUE THREAD

**Issue by nekkron** [MicrosoftDocs/memdocs#2854]
[Enter feedback here]
Youtube video link is broken - doesn't load

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b4eb41-d66a-b1c3-b417-4946643ba3d6
* Version Independent ID: 6f6e2af0-eb71-16e8-62d0-d86c73a56332
* Content: [Enroll Android device with Intune Company Portal](https://docs.microsoft.com/en-us/mem/intune/user-help/enroll-device-android-company-portal)
* Content Source: [memdocs/intune/user-help/enroll-device-android-company-portal.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/enroll-device-android-company-portal.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @nekkron Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
