### ISSUE TITLE
Its a great article. Can you please list the limitations?

### ISSUE THREAD

**Issue by vikhyat-lulu** [MicrosoftDocs/memdocs#2857]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c838c69f-95e7-e3de-25e6-6e52f43edf77
* Version Independent ID: 9f3dd8bf-d060-5ccf-e8a8-9fc10d619b58
* Content: [Using Azure Virtual Desktop single-session with Microsoft Endpoint Manager](https://docs.microsoft.com/en-us/mem/intune/fundamentals/azure-virtual-desktop)
* Content Source: [memdocs/intune/fundamentals/azure-virtual-desktop.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/azure-virtual-desktop.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by vikhyat-lulu** [comment]
I don't wish to miss-out on the key insights that would impact the process of integrating Intunes.
So completing the limitations section within the posted article will be very helpful.
It's a super product, great work!

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @vikhyat-lulu Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
