### ISSUE TITLE
Enterprise Mobility + Security A5 has intune capability

### ISSUE THREAD

**Issue by l4m3us3r** [MicrosoftDocs/memdocs#2858]
[Enterprise Mobility + Security A5
Enterprise Mobility + Security A3 have the intune capability too]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73c7bea7-ccff-ca28-35e4-820494059bf6
* Version Independent ID: 42e6e56f-d5ca-4124-f409-7e34ca609a3a
* Content: [Licenses available for Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/licenses)
* Content Source: [memdocs/intune/fundamentals/licenses.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/licenses.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@l4m3us3r Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2874

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @l4m3us3r Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
