### ISSUE TITLE
/mp and /source - priority of which parameter gets used

### ISSUE THREAD

**Issue by JoshTech1** [MicrosoftDocs/memdocs#286]
Please make a note that if the command-line contains both /mp and /source, ccmsetup will use /mp and ignore the /source.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3f3e45d-8f9d-aa5a-8b6a-d8c51c50d11e
* Version Independent ID: f5305fc4-894b-19dd-26c8-6f90901d4b1e
* Content: [Client installation parameters and properties - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/deploy/about-client-installation-properties#feedback)
* Content Source: [memdocs/configmgr/core/clients/deploy/about-client-installation-properties.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/deploy/about-client-installation-properties.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @JoshTech1 for the feedback. We have a section in the [boundary group article](https://docs.microsoft.com/mem/configmgr/core/servers/deploy/configure/boundary-groups#bkmk_ccmsetup) about this behavior, but it doesn't talk about this point. I want to confirm with engineering where /source falls in the priority list for ccmsetup, and then will update both places.

**Comment by aczechowski** [comment]
I added new information to the boundary group article (with links from this article), it should publish tomorrow morning around 11:00 Pacific time.
