### ISSUE TITLE
Clarify correlation with Managed Google Play apps

### ISSUE THREAD

**Issue by OneUser1** [MicrosoftDocs/memdocs#2861]
Last night I wanted to add a Android Enterprise system app to Intune, in my case it was the Gmail app which is normally pre-installed on devices. This app should be useable on Android Enterprise fully-managed user devices which hides app by default.

I created the app as needed but Intune showed me an error which was not very helpful:
![image](https://user-images.githubusercontent.com/80819060/173093940-4e17fbf5-36c9-4cb2-9e32-fdd05a8fba70.png)

When I go to all apps we see that there is not only one app of the type Android Enterprise system app:
![Intune_AllApps](https://user-images.githubusercontent.com/80819060/173094331-76640ea4-c6fb-44ca-92e7-fb54301bbd49.png)

I had a support call on this topic and we then realized the following: The tricky thing is that the error does not say that another "Android Enterprise *system* app" exists but only an "Android Enterprise app" which includes Managed Google Play apps...
--> It would be great to clarify the docs so that everybody knows that you cannot create an Android Enterprise system app when there is the same app as Managed Google Play app in Intune. This would be a perfect note for this article.

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ab6cd11-f97f-dece-e56e-9948c9a1d247
* Version Independent ID: 3c1bef2e-5d28-6e62-827f-1696a07f1592
* Content: [Manage Android Enterprise system apps in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-ae-system)
* Content Source: [memdocs/intune/apps/apps-ae-system.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/apps-ae-system.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@OneUser1 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2886

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @OneUser1 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by OneUser1** [comment]
Thanks!
