### ISSUE TITLE
There is a new known issue - KB5013942 breaks the ability to read the hardware hash for Windows 10 21H2

### ISSUE THREAD

**Issue by pholdridge** [MicrosoftDocs/memdocs#2863]
We found that KB5013942 which is included now in a May cumulative update breaks the ability to read the hardware hash and register a device in autopilot using Get-WindowsAutopilotInfo.ps1 script. We have to uninstall the updates first. 
https://docs.microsoft.com/en-us/answers/questions/848571/get-autopilotinfops1-get-the-hash-if-available-err.html
wusa.exe /uninstall /KB:5013942

When will this be fixed?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2da4bbd-faa6-e6d5-07c1-946f5f7da2f5
* Version Independent ID: d1040d9e-7e73-b308-65a1-e141f07ed2dc
* Content: [Windows Autopilot known issues](https://docs.microsoft.com/en-us/mem/autopilot/known-issues)
* Content Source: [memdocs/autopilot/known-issues.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/known-issues.md)
* Product: **w10**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @pholdridge thanks for sharing this with us. I checked with the feature PM, and they're not aware of the issue, haven't heard from other customers, and would like to validate before including in the documentation. Is this something that you worked with Microsoft Support on? If so, do you have case details that you can share? If not, do you have more details?

**Comment by pholdridge** [comment]
@aczechowski I provided a link to you in my post, did you read it? Other people are having the issue and it was this post that helped us resolve the issue and remove the KB update.

**Comment by aczechowski** [comment]
It's actually similar to another known issue that was recently posted: https://docs.microsoft.com/mem/autopilot/known-issues#autopilot-profile-not-being-applied-when-assigned 
The PM just put in a modification to clarify, it should publish later today.
thanks again for the feedback.

**Comment by pholdridge** [comment]
@aczechowski  how you came to the conclusion that these were similar I don't know. They have nothing to do with each other based on the link you provided. You are quick to close this, why?
