### ISSUE TITLE
Azure Roles Missing

### ISSUE THREAD

**Issue by WELLBOREIS** [MicrosoftDocs/memdocs#2864]
The following Built-in roles do not exist in Azure AD:

    "Application Manager": May possibly be called "Application administrator" now?
    "Endpoint Security Manager": Can't find any role that fits this description.
    "Help Desk Operator": May possibly be called "Helpdesk administrator" now?
    "Intune Role Administrator": May possibly be called "Intune administrator" now?
    "Policy and Profile Manager": Can't find any role that fits this description.
    "Read Only Operator": Can't find any role that fits this description.
    "School Administrator": Can't find any role that fits this description.

The following "Azure Active Directory roles with Intune access" do not exist:
    
    "Intune Service Administrator": May possibly be called "Intune administrator" now?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3eaa886-918b-127e-ad4b-d829e99b0d44
* Version Independent ID: 87240468-dd25-7f45-740b-f078cd5deac7
* Content: [Role-based access control (RBAC) with Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/role-based-access-control#built-in-roles)
* Content Source: [memdocs/intune/fundamentals/role-based-access-control.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/role-based-access-control.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@WELLBOREIS Thank you for your feedback. These roles are the built-in role that is available. I have made some changes to the missing roles and navigation in the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2882
![image](https://user-images.githubusercontent.com/45987684/174556803-9f50a790-1627-4184-97ea-ae54cbba910a.png)

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @WELLBOREIS Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by SJNZGh** [comment]
Hi yogkumgit,
I am not seeing the following roles "Read Only Operator" and" Help Desk Operator" in our AzureAD. Sorry I didn't quite get what needs to be done to fix this issue.
Any help would be much appreciated. Many Thanks.

**Comment by msbemba** [comment]
@SJNZGh By default, it should be visible. If not, I'd recommend contacting Microsoft via the need help section to fix the permissions.

Thanks
Sri
