### ISSUE TITLE
Remote help versioning causing issues with intune deployment and upgrades

### ISSUE THREAD

**Issue by poindexter6** [MicrosoftDocs/memdocs#2866]
The remote help version listed is in consistent and causing errors in Intune deployment. The document says "The most recent version of remote help is 4.0.1.7" and while this is true, there appears to be at least two different builds under this version number: 10.0.22467.1000 and 10.0.22467.1007. Non admin users that have .1000 can not update to .1007 and I can't use intune to push up an update to .1007 because the 4.0.1.7 version was not incremented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bc62c89-a452-0d3f-01f3-c5982803809e
* Version Independent ID: 6bc62c89-a452-0d3f-01f3-c5982803809e
* Content: [Remotely assist users that are authenticated by your organization.](https://docs.microsoft.com/en-us/mem/intune/remote-actions/remote-help)
* Content Source: [memdocs/intune/remote-actions/remote-help.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/remote-help.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@poindexter6 Thank you for your feedback. I will test this and update you shortly.

Thanks
Sri

**Comment by msbemba** [comment]
@poindexter6 Thank you for your feedback. This sounds more like a product bug and needs to be reported to the Developer or the product group. I recommend contacting Microsoft support via the need help section on the admin center so that a support engineer can register a ticket and file the bug.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @poindexter6 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
