### ISSUE TITLE
Don't lock users out - make sure Authenticator is backed up

### ISSUE THREAD

**Issue by SCJDigital** [MicrosoftDocs/memdocs#2870]
This page is missing key advice (which is not in the Apple page linked either and it is not their issue). 
Wiping a phone with MS Authenticator will delete the account from the phone and (there was, but not now at the time of writing) there is currently no way to restore this - authentication requests will be sent nowhere, locking the user out permanently.
-> Check Authenticator is backing up to iCloud or similar first.
Fixing lockout issue would also be great.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1d7dbdd-0282-a877-16ed-267ab6c3330c
* Version Independent ID: a7890366-83a0-b95e-0082-6b0e53d4b7a0
* Content: [Back up and restore iOS/iPadOS - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/backup-restore-ios?WT.mc_id=365AdminCSH_SupportCentral)
* Content Source: [memdocs/intune/enrollment/backup-restore-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/backup-restore-ios.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@SCJDigital Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2960

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @SCJDigital Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
