### ISSUE TITLE
Wrong description of the Dock Mode option.

### ISSUE THREAD

**Issue by tgerbaud-we-ker** [MicrosoftDocs/memdocs#2875]
Original
"Allows you to enable the dock on the device when the user swipes to the right on the home screen."

Correction
"Allows you to enable the dock on the device when the user swipes up from the bottom on the home screen."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8976417-16d9-58c1-8831-5c06aee65ad2
* Version Independent ID: b00e84d9-a244-9739-832a-9a02261112fb
* Content: [Configure Microsoft Launcher for Android Enterprise with Intune](https://docs.microsoft.com/en-us/mem/intune/apps/configure-microsoft-launcher)
* Content Source: [memdocs/intune/apps/configure-microsoft-launcher.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/configure-microsoft-launcher.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@tgerbaud-we-ker Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2940

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @tgerbaud-we-ker Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
