### ISSUE TITLE
"Remove" should be "rename" in this document

### ISSUE THREAD

**Issue by pianofu** [MicrosoftDocs/memdocs#2876]
In "https://docs.microsoft.com/en-us/mem/intune/user-help/rename-your-device-cpapp"
"Rename device from Device details page"
Complete the following step to "remove" a device from the Company Portal Device details page.

It should be "rename", not "remove".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aaaa98d-b08e-876e-9bd8-57d57317c0df
* Version Independent ID: 46d83f08-ca32-29fd-0132-b4ddbdf02d97
* Content: [Rename device from the Intune Company Portal app for Windows](https://docs.microsoft.com/en-us/mem/intune/user-help/rename-your-device-cpapp)
* Content Source: [memdocs/intune/user-help/rename-your-device-cpapp.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/rename-your-device-cpapp.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @pianofu, thanks for reaching out the Intune docs team with your contribution. I updated the doc to remove the errors you pointed out, so those changes will be live soon.
