### ISSUE TITLE
Add info that rename device won't be reflected in MEM portal

### ISSUE THREAD

**Issue by pianofu** [MicrosoftDocs/memdocs#2877]
This document could use a sentence letting customers know that renaming the device in Company Portal is not expected to be reflected in MEM Portal (rename in MEM portal: https://docs.microsoft.com/en-us/mem/intune/remote-actions/device-rename).

Most of the other actions in Company Portal will reflect in MEM Portal, so this is a divergence/expected behavior.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aaaa98d-b08e-876e-9bd8-57d57317c0df
* Version Independent ID: 46d83f08-ca32-29fd-0132-b4ddbdf02d97
* Content: [Rename device from the Intune Company Portal app for Windows](https://docs.microsoft.com/en-us/mem/intune/user-help/rename-your-device-cpapp)
* Content Source: [memdocs/intune/user-help/rename-your-device-cpapp.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/rename-your-device-cpapp.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by yogkumgit** [comment]
@msbemba Please review again and comment.

**Comment by msbemba** [comment]
@pianofu Thank you for your feedback. I have received an update  from the author that this article is for device users (employees and students) and they never have access to MEM admin center.

Hope this helps!

@yogkumgit  This can be closed.
