### ISSUE TITLE
Suggested correction in "Deploy the task sequence using the Desktop Analytics deployment plan" section

### ISSUE THREAD

**Issue by henrywang08** [MicrosoftDocs/memdocs#288]
[Enter feedback here]
Correction in "Deploy the task sequence using the Desktop Analytics deployment plan" section:

"3. In the Pilot status tile, choose Task sequence from the drop-down list, and then select Deploy."

Correction: The "drop-down" list is not implemented yet. This step should be "In the Pilot status tile, select Deploy. "

"4. On the General page of the Deploy Software Wizard, select Browse next to the Software field. Select your Windows 10 in-place upgrade task sequence, and select Next."

Correction: The field is "Task sequence". This step should be "On the General page of the Deploy Software Wizard, select Browse next to the Task sequence field. Select your Windows 10 in-place upgrade task sequence, and select Next.""
- 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6c3e494-65a1-6c1b-118d-963e1ac8ca06
* Version Independent ID: 776ca6de-38a8-3c95-4910-9e7cffec0661
* Content: [Tutorial - Deploy Windows 10 - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/desktop-analytics/tutorial-windows10)
* Content Source: [memdocs/configmgr/desktop-analytics/tutorial-windows10.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/desktop-analytics/tutorial-windows10.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @henrywang08 for the feedback. I fixed this text for the 2010 content release. You'll see this issue auto close when my change merges into our release branch, but it won't go live until the 2010 content publishes with the product release in the near future. 😉
