### ISSUE TITLE
Terrible Contents - Zero Guidance

### ISSUE THREAD

**Issue by p-moran-gd** [MicrosoftDocs/memdocs#2889]
These pages are terrible, the reference to where you are supposed to be/ where the referenced options, menus etc, actually are located. 
I got here from the Azure/365  Enterprise documentation looking for application control.
There isn't a SINGLE link to the place you are supposed to be within Defender, or In MEM, or Azure, I don't know where, because somebody has written this without actually telling people where they should be. I can't find a single menu or page labelled anything within this set of documents. ZERO.

Other documents thin Microsoft are great, they say at the beginning, FROM Microsoft Endpoint Manager, go here - anid then next to or beneath that sentence  the they 
 provides a link to where everything in the article is referring to, and not ONLY other documents that continue to 

overall the majority of the Microsoft Document is awful, it assumes that the person reading knows almost everything and has a very very extensive knowledge. Half of the documents have not been updated since Microsoft just decided to change the layout and menus and pages and setout/

I am using Intune through MEM through ONLINE AZURE system, with ZERO ON PREMISES servers or management, why is it so hard to find informatiomn on this and why do I keep being sent to documentation for on premises settings.=
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86a78339-e2a6-fa1d-c790-564426cc65ab
* Version Independent ID: 4dbe99b6-9216-f0ab-1e96-8d3d4d077c7c
* Content: [Deploy applications - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/apps/deploy-use/deploy-applications#bkmk_deploy-settings)
* Content Source: [memdocs/configmgr/apps/deploy-use/deploy-applications.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/configmgr/apps/deploy-use/deploy-applications.md)
* Product: **configuration-manager**
* Technology: **configmgr-app**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
The [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/), which outlines the expectations for community interactions in and around docs.microsoft.com, is designed to help "provide a welcoming and inspiring community for all." The content of this issue appears to be out of sync with the code of conduct, so we have closed it.

I'm sorry that you're having difficulties. The content for which you've provided feedback is specifically for the on-premises Configuration Manager, which is part of the Microsoft Endpoint Manager solution with Microsoft Intune. If you're using Intune for application management, then I suggest you start with the content for managing application in Intune: https://docs.microsoft.com/mem/intune/apps/app-management
