### ISSUE TITLE
The code in Program.cs is  missing the final "}" 

### ISSUE THREAD

**Issue by CloudlinkAdmin** [MicrosoftDocs/memdocs#289]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ae2a36c-2b94-a3c4-a20f-ef4ed3c226c7
* Version Independent ID: 0d83f965-49af-4443-2876-47590f5e694e
* Content: [Get data from the Data Warehouse API with a REST client - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/developer/reports-proc-data-rest)
* Content Source: [memdocs/intune/developer/reports-proc-data-rest.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/developer/reports-proc-data-rest.md)
* Service: **microsoft-intune**
* Sub-service: **developer**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@CloudlinkAdmin - Thanks for the feedback. I'm fixing this now.
