### ISSUE TITLE
Gmail app needs Chrome app installed to support modern authentication

### ISSUE THREAD

**Issue by scheblein** [MicrosoftDocs/memdocs#2892]
I recently had a support case opened with Intune support to find out why the Gmail app wasn't allowing modern authentication. It turns out that you need to have the Chrome app installed in the work profile to enable modern auth for Gmail. To save someone a case to Microsoft support, it would be good to see that requirement listed in the documentation here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf522825-2177-8bc3-371c-9f1dd340315c
* Version Independent ID: d7ca5010-368f-39ec-57e7-a14ad57113bb
* Content: [Android email settings in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/configuration/email-settings-android)
* Content Source: [memdocs/intune/configuration/email-settings-android.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/email-settings-android.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by msbemba** [comment]
@scheblein Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2944

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by msbemba** [comment]
@scheblein We have got confirmation from the author that the requirement does not apply to Android device administrators.

@yogkumgit  This can be closed.

Thanks
Sri

**Comment by scheblein** [comment]
That is correct. It’s only android enterprise. If this article is only for android device administrator, then I agree it can be closed. If this article mentions android enterprise at all, this info should be an added.

**Comment by msbemba** [comment]
@scheblein That is correct. This document talks about Android Device administrator.

@yogkumgit This can be closed.
