### ISSUE TITLE
Cannot read autoconfig file

### ISSUE THREAD

**Issue by rmuhammad4** [MicrosoftDocs/memdocs#2896]
Is this artifact still accurate? I cannot get my existing device to read autoconfig json file?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cb0ab9e-0902-8c43-5cb9-8ade31c88f5f
* Version Independent ID: d30aebff-dc9c-bcd9-2ffd-c7158da55026
* Content: [Windows Autopilot for existing devices](https://docs.microsoft.com/en-us/mem/autopilot/existing-devices)
* Content Source: [memdocs/autopilot/existing-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/existing-devices.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @rmuhammad4 for taking the time to share this with the Windows documentation team. I recently updated this article based on feedback from product managers.

I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
