### ISSUE TITLE
Please include reference to new role

### ISSUE THREAD

**Issue by BrissyScott** [MicrosoftDocs/memdocs#2897]
Can we please add a reference for the new role Windows 365 Administrator to replace the Cloud PC Administrator?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5289bd8b-7543-4d2c-1ea0-decd4b35b538
* Version Independent ID: 5289bd8b-7543-4d2c-1ea0-decd4b35b538
* Content: [Azure network connection overview](https://docs.microsoft.com/en-us/windows-365/enterprise/azure-network-connections)
* Content Source: [windows-365/enterprise/azure-network-connections.md](https://github.com/MicrosoftDocs/memdocs/blob/main/windows-365/enterprise/azure-network-connections.md)
* Service: **cloudpc**
* Sub-service: ****
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Cloud PC admin replaced with W365 admin
