### ISSUE TITLE
Documentation out of date with panel changes

### ISSUE THREAD

**Issue by truekonrads** [MicrosoftDocs/memdocs#2899]
Documentation specifies this path to access Windows enrollment settings ,but it is no longer valid - the menu panels don't have this path anymore:
![image](https://user-images.githubusercontent.com/1421150/175803913-eb2ebb8b-36a7-47f6-9d0c-f4e136ea5aba.png)

It's a minor edit - "instead of enrollment" it now says "Enroll devices"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6d32682-0e4e-449b-6ad5-001c631735d2
* Version Independent ID: 66419be7-51dc-f5e1-cf18-1a55866e4193
* Content: [Configure a tenant-wide Windows Hello for Business policy with Microsoft Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/windows-hello)
* Content Source: [memdocs/intune/protect/windows-hello.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/windows-hello.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@truekonrads Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2945

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @truekonrads Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
