### ISSUE TITLE
Azure App creation step need updating to ref the new reg process. 

### ISSUE THREAD

**Issue by Garthjag** [MicrosoftDocs/memdocs#2900]
The steps for creating the Azure App are out of date or incomplete. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5e14127-3656-1554-7b19-6e6122e6ea0f
* Version Independent ID: 8f48f0a7-258d-9b45-c3b2-663269d32e31
* Content: [How to use Azure AD to access Intune APIs in Microsoft Graph - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/developer/intune-graph-apis)
* Content Source: [memdocs/intune/developer/intune-graph-apis.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/developer/intune-graph-apis.md)
* Service: **microsoft-intune**
* Sub-service: **developer**
* Technology: ****
* GitHub Login: @dougeby
* Microsoft Alias: **dougeby**

**Comment by msbemba** [comment]
@Garthjag Thank you for your feedback. I was able to create a register with the steps provided in the document

![image](https://user-images.githubusercontent.com/45987684/179375298-df01a5f9-6e10-47ab-b3e6-16722cadc56a.png)


Could you please specify what options needs to be corrected?

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and digging deep into it.  @Garthjag We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
