### ISSUE TITLE
Need FW link updated. 

### ISSUE THREAD

**Issue by Garthjag** [MicrosoftDocs/memdocs#2901]
The FW link is taking you to the home page and not the the righ tURL. https://endpoint.microsoft.com/#blade/Microsoft_Intune_Enrollment/ReportingMenu/dataWarehouse

The base URL can be found by viewing the Data Warehouse API blade in the [Microsoft Endpoint Manager admin center](https://go.microsoft.com/fwlink/?linkid=2109431).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1197470e-4be2-3dd3-c47d-efb6dac2a2f0
* Version Independent ID: 0ef3e215-fa85-385c-dca2-92dda99b6e87
* Content: [Intune Data Warehouse API endpoint - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/developer/reports-api-url?source=docs)
* Content Source: [memdocs/intune/developer/reports-api-url.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/developer/reports-api-url.md)
* Service: **microsoft-intune**
* Sub-service: **developer**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@Garthjag Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2946

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Garthjag Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
