### ISSUE TITLE
Update behaviour on clients 

### ISSUE THREAD

**Issue by pedrr** [MicrosoftDocs/memdocs#2903]
The documentation is not clear about the update behaviour on the clients.
We deploy a LOB App (.pkg) as 'available for enrolled devices'
Does the client automatically update the app if we upload a new Version to Intune? Or does a user have to reinstall / initiate the update on the client on their own?

Best Regards
Simon

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54e4efd6-d1de-dba7-6ae5-a91c7a28b662
* Version Independent ID: f529438b-becd-3b8e-dc6c-02413af9854f
* Content: [How to add macOS line-of-business apps to Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/lob-apps-macos)
* Content Source: [memdocs/intune/apps/lob-apps-macos.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/lob-apps-macos.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@pedrr Thank you for your feedback. We have updated the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2958

Intune will update the app when this schedule elapses, provided that any previous version of the app is still present on the device.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @pedrr Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
