### ISSUE TITLE
Microsoft Tunnel (Preview)

### ISSUE THREAD

**Issue by svenhallauer** [MicrosoftDocs/memdocs#2904]
The Microsoft Tunnel client based on the Defender for Endpoint app has reached GA.  We need to remove the "(Preview)" qualifier from all references in these docs when it comes to the Microsoft Tunnel option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4538f49d-8c19-9227-0acf-77bef7f8d4a8
* Version Independent ID: 1b1b2c40-1fd8-3909-37ae-05ab0d27efb5
* Content: [Install and configure Microsoft Tunnel VPN solution for Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/microsoft-tunnel-configure)
* Content Source: [memdocs/intune/protect/microsoft-tunnel-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/microsoft-tunnel-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@yogkumgit  This can be closed as resolved, as the requested changes have perviously been made, driven by internal/scheduled updates.  There are no more changes required.
