### ISSUE TITLE
Using outdated powershell incapable of modern authentication

### ISSUE THREAD

**Issue by bobfrankly** [MicrosoftDocs/memdocs#2908]
The documentation here is pointing at using:
https://www.powershellgallery.com/packages/Microsoft.Graph.Intune/6.1907.1.0
https://www.powershellgallery.com/packages/WindowsAutoPilotIntune/5.0

These 2 powershell modules. The first one is abandoned and hasn't been updated since 2019. The second one is built on top of the first one. These directions need to be updated to use the proper MS Graph module, as the old one doesn't support either multi-factor modern authentication, not does it support service principals with certificate authentication. Stored Secrets are basically passwords, and everyone agrees that passwords are insecure.

Please modernize these directions for your customers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cb0ab9e-0902-8c43-5cb9-8ade31c88f5f
* Version Independent ID: d30aebff-dc9c-bcd9-2ffd-c7158da55026
* Content: [Windows Autopilot for existing devices](https://docs.microsoft.com/en-us/mem/autopilot/existing-devices)
* Content Source: [memdocs/autopilot/existing-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/existing-devices.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @bobfrankly for the feedback. I recently updated this article and confirmed those cmdlets with the engineering team. So the feedback is best provided with engineering to revise the fundamental process. I think Autopilot feedback is best provided through the Feedback Portal for Microsoft Intune: https://feedbackportal.microsoft.com/feedback/forum/ef1d6d38-fd1b-ec11-b6e7-0022481f8472
