### ISSUE TITLE
Found some features missing

### ISSUE THREAD

**Issue by cnita2** [MicrosoftDocs/memdocs#2910]
[hi all, 

reading this text:
_Device group membership report (Organizational)
The Group membership report provides the group membership of all AAD groups for a specific managed device. The report provide the following columns:

Name
Object Id
Membership Type
Direct or Transitive
When you click on a group, you can see the AAD pane for the group. You can identify whether the device's membership is assigned or dynamic and whether the device is a direct member or a transitive member. This report supports all device platforms and management types. This report provides filtering, searching, paging, and sorting capabilities. Also, you can drill down to help troubleshoot.

To see the report for a device, you can use the following steps:

Sign in to the [Microsoft Endpoint Manager admin center](https://go.microsoft.com/fwlink/?linkid=2109431).
Select Devices > Monitor > select a device > Group Membership._

However, when looking in Intune, we don't have such feature available. Was it released in 2206 or it will be in 2207?]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d16c28db-1e8e-31fa-6127-3050a2940422
* Version Independent ID: 4cf9a244-1ae5-1637-48f7-3f503d400da6
* Content: [What's new in Microsoft Intune](https://docs.microsoft.com/en-gb/mem/intune/fundamentals/whats-new)
* Content Source: [memdocs/intune/fundamentals/whats-new.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/whats-new.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by yogkumgit** [comment]
@msb

**Comment by msbemba** [comment]
@cnita2 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2959

This is under **Devices** > **All Devices** > *select a device* > **Group Membership**.

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @cnita2 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
