### ISSUE TITLE
Feedback on MEM Endpoint Security - EDR policy

### ISSUE THREAD

**Issue by 0fflineDocs** [MicrosoftDocs/memdocs#2913]
[Enter feedback here]
Step 6 in the onboarding (https://docs.microsoft.com/en-us/mem/intune/protect/endpoint-security-edr-policy#create-edr-policies)
is not correct. We actually can configure the settings there like this:

![image](https://user-images.githubusercontent.com/25408117/177093455-7e8a4aa8-2fa9-427e-9763-c5458d339767.png)

I think it should be adjusted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4107154e-9df1-0380-e9af-a10b86dba3fa
* Version Independent ID: e41f3685-3d96-8610-6b24-568d19f2610c
* Content: [Manage endpoint detection and response settings with endpoint security policies in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/endpoint-security-edr-policy)
* Content Source: [memdocs/intune/protect/endpoint-security-edr-policy.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/endpoint-security-edr-policy.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@0fflineDocs Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2947

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @0fflineDocs Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
