### ISSUE TITLE
Wi-Fi IPv4 address on Windows devices

### ISSUE THREAD

**Issue by MarineBDCoru** [MicrosoftDocs/memdocs#2914]
Hello! 

On the article, we can read that Wi-Fi IPv4 address is only visible on Android Enterprise fully managed, dedicated and corp-owned work profiles.

Is it correct? Because on my tenant, I have Windows devices with this setting available. 

Thank you,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905c303e-4306-38ec-2a30-4852a8c1bc2b
* Version Independent ID: ceb7e815-e19a-386f-902c-6e6bf53d5766
* Content: [View device details with Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/remote-actions/device-inventory)
* Content Source: [memdocs/intune/remote-actions/device-inventory.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/device-inventory.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@MarineBDCoru Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2948

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @MarineBDCoru Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
