### ISSUE TITLE
Confusing statement about assigning autopilot profiles to users

### ISSUE THREAD

**Issue by Charbird** [MicrosoftDocs/memdocs#2924]
I find the following statement confusing because it's my understanding that Autopilot deployment profiles should be assigned to devices and not users. Unless this document is referencing a different profile type. 

'A user receives a new organization-owned device. The user signs in to the device with their domain account. The device is automatically registered in Azure AD, and automatically managed by Intune. This profile is a good scenario to assign to a users group.'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb9f0c71-ac8b-b047-9934-1bffb895e75c
* Version Independent ID: 44f25bbe-ccc6-5480-09b4-cfa18832b0bb
* Content: [Assign device profiles in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/configuration/device-profile-assign#exclude-groups-from-a-profile-assignment)
* Content Source: [memdocs/intune/configuration/device-profile-assign.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/device-profile-assign.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@Charbird Thank you for your feedback. 

These are device profiles - https://docs.microsoft.com/en-us/mem/intune/configuration/device-profile-create

Auto deployment profiles are different- https://docs.microsoft.com/en-us/mem/autopilot/profiles

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Charbird Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
