### ISSUE TITLE
States its currently for only windows insider

### ISSUE THREAD

**Issue by chiners68** [MicrosoftDocs/memdocs#2928]
This pages states this universal print connection works with Windows 11. but in the settings catalog in every tenant I have looked this only applies currently to windows insider. Can you please update this document to detail current supported OS's. See attached image re insider

![image](https://user-images.githubusercontent.com/41296237/178494744-928dbfd5-a40b-4eb0-9397-30e995e75bdc.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c561ca3-51c0-3256-4826-9c1683110c69
* Version Independent ID: 2c561ca3-51c0-3256-4826-9c1683110c69
* Content: [Configure Universal Print policy using settings catalog in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/configuration/settings-catalog-printer-provisioning)
* Content Source: [memdocs/intune/configuration/settings-catalog-printer-provisioning.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/settings-catalog-printer-provisioning.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by msbemba** [comment]
@chiners68 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2949

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by MandiOhlinger** [comment]
@msbemba We typically don't list Windows Insiders in the applies to section. I did confirm in an upcoming release (no ETA), that it will be available to Windows 11, not just Windows Insiders. This feature has also been backported to Windows 10.

I updated the text, and the PR is merged.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @chiners68 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
