### ISSUE TITLE
ADK 2004 is supported?

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/memdocs#293]
@tahakogi commented 18 hours ago 

Windows ADK for Windows 10 ver 2004 is released.
Is this version supported or not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce35f51b-8368-6cfa-868c-404a3e533b67
* Version Independent ID: f4b5e0ed-226f-5811-dfa0-628bf57a0bbd
* Content: [Support for Windows 10 - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/configs/support-for-windows-10)
* Content Source: [memdocs/configmgr/core/plan-design/configs/support-for-windows-10.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/configs/support-for-windows-10.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @tahakogi, yes it is supported with ConfigMgr version 2002. We have an update to the article that will publish tomorrow or Thursday with the general availability of the Windows 10 version 2004 release.

(Internal reference MicrosoftDocs/MEMDocs-pr#767)
