### ISSUE TITLE
Customer owns a device license and intend to use devices in Kiosk mode - why is user license required? 

### ISSUE THREAD

**Issue by ss0724** [MicrosoftDocs/memdocs#2934]
[QUESTION: Customer intends to use Apple iPads in kiosk mode, and is aware of limitations with device-only license. Their users are shift workers and share devices amongst themselves. However, they all are not user licensed. Everything checks out however, the "or" statement in this quote from the documentation is causing confusion: 
"If a device is used by more than one user, each requires a device software license or all users require a user software license."
Since they won't authenticate to any Microsoft or non-Microsoft apps, why would their users be required a software license? They want to remain compliant and would like "legal terms of use", so they are protected. Happy to provide further explanation. Thank you!]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49021e82-460a-201b-90f0-ca27b1acc1f4
* Version Independent ID: b45ff723-d40f-8325-eafd-0b5703065498
* Content: [Assign Microsoft Intune licenses](https://docs.microsoft.com/en-us/mem/intune/fundamentals/licenses-assign)
* Content Source: [memdocs/intune/fundamentals/licenses-assign.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/licenses-assign.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@ss0724 Thank you for your feedback. Each device requires a software license, If not all users who log in to the device require a user software license.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ss0724 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
