### ISSUE TITLE
How to update the version of Intune Company Portal App automatically installed at ADE registration

### ISSUE THREAD

**Issue by Ikuko-Konno** [MicrosoftDocs/memdocs#2936]
If not assigned, the Intune Company Portal App, which is automatically installed upon ADE registration, will not be able to update its version, either manually or automatically.
Therefore, the Intune Company Portal App will become unusable with the latest version release of the Intune Company Portal App.
We would like to see it stated in the official documentation that if you want to update the version of the Intune Portal Site App, you must assign a device license as a mandatory requirement.

* In the official documentation, there is the following explanation. However, I interpret this explanation to be about Device Staging. If this interpretation is wrong, it is because the explanation is difficult to understand. Therefore, I would like you to describe it separately from Device Staging.

---------------------
To enable the Company Portal to update automatically and provide the Company Portal app on devices already enrolled with ADE, deploy the Company Portal app through Intune as a required VPP app with an application configuration policy applied. Deploy the Company Portal app in this way to enable Device Staging for devices only without user affinity. With Device Staging, a device is fully enrolled and receives device policies before the addition of a user affinity. Device Staging can also be used to transition a device without user affinity, to a device with user affinity.
---------------------

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd130267-c54b-41e3-d534-831d4a86bae6
* Version Independent ID: bdfa7eca-a356-3dde-7643-9a759f952007
* Content: [Enroll iOS/iPadOS devices by using ADE - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-ios)
* Content Source: [memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by yogkumgit** [comment]
@lenewsad Please help us in resolving this issue. Thanks

**Comment by lenewsad** [comment]
Hi @Ikuko-Konno, thank you for your contribution to the Microsoft Intune enrollment docs. We made changes to the section based on your feedback, which is now live.

**Comment by lenewsad** [comment]
FYI @yogkumgit
