### ISSUE TITLE
Device Tunnel & Azure AD Joined Devices

### ISSUE THREAD

**Issue by LadtoHelp** [MicrosoftDocs/memdocs#2938]
_Device tunnel (IKEv2 only): Enable connects the device to the VPN automatically without any user interaction or sign in. This setting applies to devices joined to Azure Active Directory (AD)._

Does that specifically **exclude** Hybrid Azure Ad Joined  and only apply to pure Azure AD Joined devices?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e16582-5730-9f22-2ced-686fc074d5c0
* Version Independent ID: b334cc28-f6ed-103f-3770-4cddb42e666c
* Content: [Windows 10/11 VPN settings in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/configuration/vpn-settings-windows-10?source=docs)
* Content Source: [memdocs/intune/configuration/vpn-settings-windows-10.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/vpn-settings-windows-10.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by msbemba** [comment]
@LadtoHelp Thank you for your feedback. I have checked and it It applies to all Azure Ad joined devices and does not exclude Hybrid Azure Ad Joined.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @LadtoHelp Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
