### ISSUE TITLE
Remote help will be available for M365 A1/A3/A5 later this calendar year

### ISSUE THREAD

**Issue by AdSto** [MicrosoftDocs/memdocs#2939]
Hi Team, 

My feedback is in regards to the docs article [Remotely assist users that are authenticated by your organization. | Microsoft Docs] / /https://docs.microsoft.com/en-us/mem/intune/remote-actions/remote-help#prerequisites

Under the Prerequisites there should be a clarification added that  _‘Remote help will be available for M365 A1/A3/A5 Education customers later this calendar year.'_ Education customers with M365 A1/A3/A5  which include Intune subscription will have Remote Help with their license and they won’t require the ‘Remote Help Add-on’.

Thank you 

Best Regards, 
Adriana

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bc62c89-a452-0d3f-01f3-c5982803809e
* Version Independent ID: 6bc62c89-a452-0d3f-01f3-c5982803809e
* Content: [Remotely assist users that are authenticated by your organization.](https://docs.microsoft.com/en-us/mem/intune/remote-actions/remote-help#prerequisites)
* Content Source: [memdocs/intune/remote-actions/remote-help.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/remote-help.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@AdSto Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2961

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by msbemba** [comment]
@AdSto Thank you for your feedback. I have got a confirmation that we will be able to add this information only after it goes live.

We will ensure that it is updated at that point in time.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @AdSto Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
