### ISSUE TITLE
App Store Link Issue

### ISSUE THREAD

**Issue by BiggsSkeedR** [MicrosoftDocs/memdocs#2952]
The link provided to the Microsoft Store (https://www.microsoft.com/store/apps) now appears to redirect to the new store interface (https://apps.microsoft.com/store/apps?hl=en-us&gl=us&rtc=1) and does not provide the required link for the apps.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ded6cdc4-3c0a-ae18-9d9c-b3d5db3c0708
* Version Independent ID: 34a4b4be-cd8b-25b3-49ef-f5142a87b9ef
* Content: [Add Microsoft Store apps to Microsoft Intune](https://docs.microsoft.com/en-gb/mem/intune/apps/store-apps-windows)
* Content Source: [memdocs/intune/apps/store-apps-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/store-apps-windows.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@BiggsSkeedR Thank you for your feeback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2996

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @BiggsSkeedR Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
