### ISSUE TITLE
[SaaF][ICM 314709081][Repair]: Confirm and document that the End user update status Last Scanned Time will return Not scanned yet until a user logon and scan is performed

### ISSUE THREAD

**Issue by jerryabo** [MicrosoftDocs/memdocs#2965]
Re: "Select End user update status to view information about the policy."

Ref: Incident 314709081

--It appears that for USO scan to kick off the user must log on to a device at least once, and subsequent scans are not dependent on logon.

Please confirm this behavior and document/caveat a related note on the End user update status, i.e. why the **Last Scanned Time** column will currently/expectedly show a value of **Not scanned yet** until a user logon is performed. 

Sample text for review/consideration:

Note: The End user update status Last Scanned Time value will return 'Not scanned yet' until an initial user logon and Update Session Orchestrator (USO) scan is initiated. For more information on the Unified Update Platform (UUP) architecture and related components, see [Get started with Windows Update](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-overview).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee0dbbde-b15e-4adf-b162-1114fddd8846
* Version Independent ID: 78275b5f-4d5b-f318-0cbf-a27ad35dffa0
* Content: [Configure feature updates policy for Windows 10 Windows 11 devices in Intune](https://docs.microsoft.com/en-us/mem/intune/protect/windows-10-feature-updates?source=docs#feedback)
* Content Source: [memdocs/intune/protect/windows-10-feature-updates.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/windows-10-feature-updates.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@jerryabo Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2995

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jerryabo Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
