### ISSUE TITLE
macOS Endpoint Security docs link to App Bundle IDs for iOS. macOS is not iOS

### ISSUE THREAD

**Issue by mberry1212** [MicrosoftDocs/memdocs#2970]
On this page:
https://docs.microsoft.com/en-us/mem/intune/protect/endpoint-protection-macos?toc=%2Fintune%2Fconfiguration%2Ftoc.json&bc=%2Fintune%2Fconfiguration%2Fbreadcrumb%2Ftoc.json#firewall

The links for the "App Bundle ID" link to Apple documentation which refers to iOS apps. 
iOS related data should not be within the macOS documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07310e6e-6d1d-71b7-2dbb-04c8fdd763fb
* Version Independent ID: 05c4ca55-1589-54ea-8ac5-85eaffc849b6
* Content: [Configure endpoint protection on macOS devices with Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/endpoint-protection-macos)
* Content Source: [memdocs/intune/protect/endpoint-protection-macos.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/endpoint-protection-macos.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by yogkumgit** [comment]
@Brenduns Please help us in resolving this issue. Thanks

**Comment by Brenduns** [comment]
@mberry1212     Thanks for the feedback – that was an old link that was in need of a fix, which I’ve just submitted. That update should be live on the web around 4pm pacific today (8/15/2022).  I've been out for a few weeks, so I hope this update remains of immediate value for you. 

As we don’t have a dedicated article for macOS bundle IDs (as we have for iOS/iPadOS), I added the process for finding a bundle ID for macOS to the relevant content location in this article and removed the confusing links. 

cc @yogkumgit
