### ISSUE TITLE
Revise title to use approved Term Studio term for product name: Microsoft 365 Apps

### ISSUE THREAD

**Issue by PacoCruz** [MicrosoftDocs/memdocs#2973]
Please revise title to use Term Studio approved name: 'Microsoft 365 Apps' (correct) instead of 'Microsoft 365 apps' (incorrect)

![image](https://user-images.githubusercontent.com/28814079/181140001-f60c4ee7-8a8f-4acc-9483-6e4e0227107d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fd6b61e-8f22-40cf-1827-d47a6b32ddc9
* Version Independent ID: 462829d9-6577-9f86-afff-9945abaa7b1c
* Content: [Add Microsoft 365 apps to Windows 10/11 devices using Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-add-office365)
* Content Source: [memdocs/intune/apps/apps-add-office365.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/apps-add-office365.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@PacoCruz Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2994

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @PacoCruz Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
