### ISSUE TITLE
Edge Link Error

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/memdocs#2976]
The link for "[Add Microsoft Edge](https://docs.microsoft.com/en-us/mem/intune/apps/manage-microsoft-edge)" takes you to a page about edge on iOS and Android...this needs to be updated to content for macOS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a569ac8e-188b-fcdd-70d6-3946a4a87060
* Version Independent ID: 0a8d47e1-84f2-6fa4-d589-1b242bf26120
* Content: [Deployment guide to manage macOS devices in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/deployment-guide-platform-macos)
* Content Source: [memdocs/intune/fundamentals/deployment-guide-platform-macos.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/deployment-guide-platform-macos.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@danmyhre Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2993

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @danmyhre Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
