### ISSUE TITLE
Company Portal App on Windows PC doesn't have the "remove" option anymore. this page needs to be corrected. It has only Rename, Reset and Reset PIN options.

### ISSUE THREAD

**Issue by yasseramicrosoft** [MicrosoftDocs/memdocs#2977]
Company Portal App on Windows PC doesn't have the "remove" option anymore. this page needs to be corrected. It has only Rename, Reset and Reset PIN options

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8186a91-73b1-1276-9710-70ee92a491e5
* Version Independent ID: b8210dcf-6694-e920-1ea7-9761ad02f810
* Content: [Remove your Windows device from Intune management](https://docs.microsoft.com/en-gb/mem/intune/user-help/unenroll-your-device-from-intune-windows)
* Content Source: [memdocs/intune/user-help/unenroll-your-device-from-intune-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/unenroll-your-device-from-intune-windows.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@yasseramicrosoft Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2991

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @yasseramicrosoft Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
