### ISSUE TITLE
Factory Reset Protection Smails setting unclear

### ISSUE THREAD

**Issue by Nickbert7** [MicrosoftDocs/memdocs#2979]
If I understand the documentation correctly, it should be possible to keep the list of email addresses empty to "disable" the factory reset protection. (Anyone should be able to bypass the FRP with any account)
![image](https://user-images.githubusercontent.com/14938497/181460161-0a1b4cd7-0bfb-459f-ac87-e5b704ef2572.png)
Unfortunately the email field seems to be required, I'm not able to specify no email address:
![image](https://user-images.githubusercontent.com/14938497/181460444-4e1240dc-e7a3-4294-8f4c-af910c76673a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 900e72be-d42b-49ba-f304-602df23cbb04
* Version Independent ID: 2ce5c45d-15be-d316-1c57-92bea37358e0
* Content: [Android Enterprise device settings in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-android-for-work#feedback)
* Content Source: [memdocs/intune/configuration/device-restrictions-android-for-work.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/device-restrictions-android-for-work.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by msbemba** [comment]
@Nickbert7 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2992

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Nickbert7 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
