### ISSUE TITLE
Compatibility level/certificate template version

### ISSUE THREAD

**Issue by elc-cs** [MicrosoftDocs/memdocs#298]
For workstation authentication the document last updated in February 2017 states: 

> However, if you are running the issuing CA on Windows Server 2012, you're not prompted for the certificate template version. Instead, specify this on the Compatibility tab of the template properties:
> 
> Certification Authority: Windows Server 2003
> Certificate recipient: Windows XP / Server 2003 

Is this still a requirement for clients running Windows 10 with Endpoint Configuration Manager 2002? It seems odd to require this step and causes issues for organisations (such as ours) which already have a workstation certificate for other purposes set to a later version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a41a19c-d822-1ee7-80a7-3672e1d47077
* Version Independent ID: 305cb6a2-adf1-87d5-212e-456e945cf5fd
* Content: [Example PKI certificate deployment - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/network/example-deployment-of-pki-certificates)
* Content Source: [memdocs/configmgr/core/plan-design/network/example-deployment-of-pki-certificates.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/network/example-deployment-of-pki-certificates.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @elc-cs, no you can use newer templates for many scenarios. See the [CNG certificates overview](https://docs.microsoft.com/mem/configmgr/core/plan-design/network/cng-certificates-overview).

We have an internal item (2841906) to track rework on this article and the PKI requirements article, both of which haven't been touched in a long time. So I'm going to close this item.
