### ISSUE TITLE
Writing about supporting Autopilot for Windows IoT in the document

### ISSUE THREAD

**Issue by minakash** [MicrosoftDocs/memdocs#2981]
My OEM customer cannot judge whether Autopilot is supported for Windows IoT devices due to removing description about Windows IoT in the below document. I require to write that Autopilot is NOT supported for Windows IoT devices explicitly.

https://docs.microsoft.com/en-us/mem/autopilot/software-requirements

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca6f1187-d749-6db2-d46f-1d1d60bbc289
* Version Independent ID: f8154992-4a7a-c0ff-5cd6-c691f7fa26d3
* Content: [Windows Autopilot software requirements](https://docs.microsoft.com/en-us/mem/autopilot/software-requirements)
* Content Source: [memdocs/autopilot/software-requirements.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/software-requirements.md)
* Product: **w10**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @minakash we generally don't document what we don't support. In this case, the engineering team doesn't currently test with IoT or LTSC, thus it's not listed as a supported platform. I suggest that you file [product feedback](https://feedbackportal.microsoft.com/feedback/forum/ef1d6d38-fd1b-ec11-b6e7-0022481f8472) to send a signal to the engineering team to include support for these platforms.
