### ISSUE TITLE
TY#789

### ISSUE THREAD

**Issue by Masonta1976** [MicrosoftDocs/memdocs#2986]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ee4c4fc-8cd2-34e7-9bfa-f4378a3a46b5
* Version Independent ID: e62806ea-d183-a3e3-08fd-9c0d1c3e7b50
* Content: [What is Microsoft Intune device enrollment - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment)
* Content Source: [memdocs/intune/enrollment/device-enrollment.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/device-enrollment.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by Masonta1976** [comment]
security problem/keep shutting down when updating insider widow

**Comment by msbemba** [comment]
@Masonta1976 Thank you for your feedback. This sounds more like a bug or a technical issue for which you need assistance from Microsoft support. I'd recommend you to contact support via the need help section on the admin center so that a support engineer can assist you in fixing this.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Masonta1976 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
