### ISSUE TITLE
Gov environment addition

### ISSUE THREAD

**Issue by richardpomerleau** [MicrosoftDocs/memdocs#299]
Azure Gov customers (GCC) also require the change of the MDM URLS for auto enrollment to work correctly. 
https://portal.manage.microsoft.us/TermsofUse.aspx
https://enrollment.manage.microsoft.us/enrollmentserver/discovery.svc
https://portal.manage.microsoft.us/?portalAction=Compliance

These with the documented CNAME allowed me to register devices in Intune.
Another reference for documentation can be found here. https://github.com/MicrosoftDocs/IntuneDocs/issues/3448

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f1e311c-c5ff-1c68-028d-e4fddda23324
* Version Independent ID: 1d2174e5-8984-8d9c-34c5-dfbcc619b410
* Content: [Set up enrollment for Windows devices by using Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/windows-enroll#enable-windows-10-automatic-enrollment)
* Content Source: [memdocs/intune/enrollment/windows-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/windows-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
(7330496)

**Comment by ErikjeMS** [comment]
@richardpomerleau Here is the response from the PM: " For GCC High, they would have to change the URLs (surprised we don't do that automatically) to include the .us suffix, but for GCC I would expect them to use the same PE URLs."
If this doesn't resolve your issue, let me know and I'll reopen this item.
