### ISSUE TITLE
Broken link - Sign in via another device

### ISSUE THREAD

**Issue by Aegrum** [MicrosoftDocs/memdocs#3000]
[Enter feedback here]
There is a broken link [under this section](https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new#intune-supports-sign-in-from-another-device-during-iosipados-setup-assistant-with-modern-authentication) that should go [here](https://docs.microsoft.com/en-us/mem/intune/user-help/sign-in-to-the-company-portal#sign-in-via-another-device).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d16c28db-1e8e-31fa-6127-3050a2940422
* Version Independent ID: 4cf9a244-1ae5-1637-48f7-3f503d400da6
* Content: [What's new in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new#week-of-july-25-2022-service-release-2207)
* Content Source: [memdocs/intune/fundamentals/whats-new.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/whats-new.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@Aegrum Thank you for your feedback. We have fixed the broken link via PR#https://github.com/MicrosoftDocs/memdocs/pull/3016

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Aegrum Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
