### ISSUE TITLE
Review TPM startup PIN or key section

### ISSUE THREAD

**Issue by Warren-Stevens** [MicrosoftDocs/memdocs#3003]
Review TPM startup PIN or key section
comment does not make sense: 

"A device **must not require** use of a startup PIN or startup key.

When a TPM startup PIN or startup key is required on a device, "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54cccf1d-81fd-5331-aee7-59a35b39cb15
* Version Independent ID: 81d14392-fe74-4fd9-047f-7b8292d84f0c
* Content: [Encrypt Windows devices with BitLocker in Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/encrypt-devices?source=docs)
* Content Source: [memdocs/intune/protect/encrypt-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/encrypt-devices.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@Warren-Stevens Thank you for your feedback. The device must not be set to require a startup PIN or startup key. I have made changes in the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3015

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Warren-Stevens Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Warren-Stevens** [comment]
Hi Yogesh, It's only a pleasure.

Kind Regards
