### ISSUE TITLE
Dear all, the videos under https://docs.microsoft.com/en-us/mem/intune/fundamentals/role-based-access-control (the 5 videos) are from 2018! Nice explanation but completely outdated.

### ISSUE THREAD

**Issue by SashWind** [MicrosoftDocs/memdocs#3007]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3eaa886-918b-127e-ad4b-d829e99b0d44
* Version Independent ID: 87240468-dd25-7f45-740b-f078cd5deac7
* Content: [Role-based access control (RBAC) with Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/role-based-access-control)
* Content Source: [memdocs/intune/fundamentals/role-based-access-control.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/role-based-access-control.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by dougeby** [comment]
Thanks for the feedback. I removed the videos from the article for now. We'll see what we can do to improve the experience with updated content.
