### ISSUE TITLE
Rename of Android Enterprise devices

### ISSUE THREAD

**Issue by mdmuds** [MicrosoftDocs/memdocs#3009]
Rename of Android Enterprise devices will only change the name on Intune Portal and not on the device itself. 
The device name in settings is not in device management control, it is a friendly name that users are free to change.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab62517e-47bd-a28d-5907-5fd3841f8504
* Version Independent ID: 765044bd-ef1c-1dc3-c48e-3bbdb602e1c7
* Content: [Rename a device with Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/remote-actions/device-rename)
* Content Source: [memdocs/intune/remote-actions/device-rename.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/device-rename.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@mdmuds Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3014

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @mdmuds Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
