### ISSUE TITLE
Apple Business Manager Steps have changed

### ISSUE THREAD

**Issue by jantoney** [MicrosoftDocs/memdocs#301]
Steps under here have significantly changed
https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-ios#step-2-use-your-key-to-download-a-token-from-apple

New rough steps are
- Open https://business.apple.com
- Settings
- Device Management Settings
- Add MDM Server
- Enter in a name for your MDM Server
- Tick Allow this MDM Server to release devices
- Upload the Public Key
- Click Save
<< Now return back to uploading it to Device Management portal >>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd130267-c54b-41e3-d534-831d4a86bae6
* Version Independent ID: bdfa7eca-a356-3dde-7643-9a759f952007
* Content: [Enroll iOS/iPadOS devices - Device Enrollment Program - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-ios)
* Content Source: [memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
(7330592)

**Comment by ErikjeMS** [comment]
Repinged PM...

**Comment by MandiOhlinger** [comment]
@jantoney Thank you. We updated these steps. The changes should be live later today.
