### ISSUE TITLE
MS Tunnel app not available in App Store 

### ISSUE THREAD

**Issue by Alexey-Zheltov** [MicrosoftDocs/memdocs#3012]
Support for MS Tunnel app ended at 29th July and app no longer available in App Store and not working on existing devices. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71eb926f-f654-b9bc-d747-c8fb68f986b9
* Version Independent ID: fdaef279-6230-8fca-d707-213472b6ab88
* Content: [Use the Microsoft Tunnel app for iOS - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/user-help/use-microsoft-tunnel-ios)
* Content Source: [memdocs/intune/user-help/use-microsoft-tunnel-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/use-microsoft-tunnel-ios.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@Alexey-Zheltov Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3041

Once the author reviews the document and approves it, the updates will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Alexey-Zheltov Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
