### ISSUE TITLE
LEDBAT 2016 Requirements

### ISSUE THREAD

**Issue by XzeroR3** [MicrosoftDocs/memdocs#302]
KB4284833 with Server 2016 is noted as the prerequisite LEDBAT, however this update is no longer available on Windows Update (see https://www.catalog.update.microsoft.com/Search.aspx?q=KB4284833 )  

I am unable to see if update KB4284833 has been superseded, if so can an updated patch requirement be noted on this page?  

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47242ed6-ef2e-f497-6f04-61a790b9935b
* Version Independent ID: c1180f2a-0caa-1295-7b22-bc7897c56d4b
* Content: [Manage distribution points - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/install-and-configure-distribution-points)
* Content Source: [memdocs/configmgr/core/servers/deploy/configure/install-and-configure-distribution-points.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/deploy/configure/install-and-configure-distribution-points.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @XzeroR3 for the feedback. That patch is almost two years old (see the [support KB article](https://support.microsoft.com/help/4284833/windows-10-update-kb4284833)), so I _assume_ that a support patch level at this point is sufficient. But I'm confirming with the LEDBAT PM.

**Comment by mestew** [comment]
Hey @XzeroR3 KB4284833 was a cumulative update (CU) from June 2018. https://support.microsoft.com/en-us/help/4284833/windows-10-update-kb4284833 You can install any CU published after it, Same for the servicing stack update(SSU) as well. I am updating the doc to note "or later" along with the release dates of the CU and SSU.
