### ISSUE TITLE
Language is a little confusing

### ISSUE THREAD

**Issue by kamackill** [MicrosoftDocs/memdocs#3020]
This line made me laugh: "Tell your users how to enroll their Windows devices and what to expect after they're brought into management."

I assume the intention is to convey that the device is being "brought into management" rather than the user receiving a promotion, though it's not too clear from the sentence structure. Perhaps it would be better to write "Tell your users how to enroll their Windows devices and what to expect after _their devices are_ brought into management.", which is easier to understand.

I was imagining a conversation like: "Here's how to enroll your device... And we're bringing you into management. Expect to talk a lot more and get much less work done!"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f1e311c-c5ff-1c68-028d-e4fddda23324
* Version Independent ID: 1d2174e5-8984-8d9c-34c5-dfbcc619b410
* Content: [Set up enrollment for Windows devices by using Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/windows-enroll#feedback)
* Content Source: [memdocs/intune/enrollment/windows-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/windows-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @kamackill, thank you for reaching out to the Microsoft Docs team and for your contribution. I updated that section to make it easier to read--changes should be live by 4 PM PST.
