### ISSUE TITLE
A video on page shows "This Video is private"

### ISSUE THREAD

**Issue by pgdrews** [MicrosoftDocs/memdocs#3022]
Under the section "Reregister the repaired device using the new device ID" there is a video that shows "This video is private". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c91281a-bdba-ff2d-6cb5-7ac45396397e
* Version Independent ID: 1a9e425f-7977-66be-eeb5-b41646de2d52
* Content: [Windows Autopilot motherboard replacement](https://docs.microsoft.com/en-us/mem/autopilot/autopilot-mbr#deregister-from-intune)
* Content Source: [memdocs/autopilot/autopilot-mbr.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/autopilot-mbr.md)
* Product: **w10**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @pgdrews for the feedback. Some legacy videos were recently retired, I'll remove this reference.
