### ISSUE TITLE
Solution is lacking details for a any sort of work around. 

### ISSUE THREAD

**Issue by Charbird** [MicrosoftDocs/memdocs#3027]
Hello,

This page was helpful in determining the cause of our AutoPilot enrollment issues however the provided solution is only to remove the policy in question. This solution is lacking because the policy might be required so it would be helpful to provide a method to keep the policy in place and have a working Autopilot enrollment configuration. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d83efe8-84dd-3de4-da30-d4c89dec7aec
* Version Independent ID: 25ab91ff-489b-1591-9a0a-5923eccfd325
* Content: [Windows Autopilot policy conflicts](https://docs.microsoft.com/en-us/mem/autopilot/policy-conflicts)
* Content Source: [memdocs/autopilot/policy-conflicts.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/policy-conflicts.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by frankroj** [comment]
Thank you for the feedback @Charbird. The Autopilot docs are more geared towards explaining Autopilot and how to use it. There are some basic troubleshooting articles, but the aren't designed to go into details. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Microsoft](https://learn.microsoft.com/answers/tags/415/intune). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Windows Autopilot support information](https://support.microsoft.com/windows) to find your available support options.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
