### ISSUE TITLE
Update article to contain Autopilot changes

### ISSUE THREAD

**Issue by OneUser1** [MicrosoftDocs/memdocs#3028]
Pls include announced changes from https://techcommunity.microsoft.com/t5/intune-customer-success/return-of-key-functionality-for-windows-autopilot-sign-in-and/bc-p/3595040

Thx!

Edit: I refer to this article in the docs: https://docs.microsoft.com/en-us/mem/autopilot/autopilot-mbr - the link is not correct in the issue, sorry

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c91281a-bdba-ff2d-6cb5-7ac45396397e
* Version Independent ID: 1a9e425f-7977-66be-eeb5-b41646de2d52
* Content: [Windows Autopilot motherboard replacement](https://docs.microsoft.com/en-us/mem/autopilot/autopilot-mbr)
* Content Source: [memdocs/autopilot/autopilot-mbr.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/autopilot-mbr.md)
* Product: **w10**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by OneUser1** [comment]
Can we hope for a quick update on the docs regarding this critical process? This would be very helpful. Please move this issue to the correct document referred in my last comment. Thanks in advance!

**Comment by aczechowski** [comment]
Thanks @OneUser1 for the feedback. Once it's fully in effect for all hardware, we plan on updating the doc.

**Comment by aczechowski** [comment]
The PM made some updates to the article based on the info in the blog post. The changes should publish live in the next hour.

**Comment by OneUser1** [comment]
Thank you!
