### ISSUE TITLE
SCCM 2002 Baseline media still not available on MSDN/VLSC

### ISSUE THREAD

**Issue by Manohar-Pusala** [MicrosoftDocs/memdocs#303]
[Enter feedback here]
Although the Evaluation copy of baseline media was released couple of weeks back, licensed version is still not updated on MSDN or VLSC. Then how is this called as GA ?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 733080f2-5a95-e2c3-d4bf-dcb8fc35c2ed
* Version Independent ID: e4b6a579-98f3-5710-8acf-2c002b2628b6
* Content: [What's new in version 2002 - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/changes/whats-new-in-version-2002?source=docs)
* Content Source: [memdocs/configmgr/core/plan-design/changes/whats-new-in-version-2002.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/changes/whats-new-in-version-2002.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @Manohar-Pusala, the in-console update was available on 5/11 without requiring you to opt-in to the early update ring, thus the global availability. The version 2002 baseline media takes several weeks to process after the final build is generated. It has been available on VLSC as of 5/21. As mentioned in the note below the table of [supported versions](https://docs.microsoft.com/mem/configmgr/core/servers/manage/updates#version-details), you need to search for "System Center Config Mgr (current branch)" to find it. We haven't yet changed the name of it in VLSC (another process which takes time).
