### ISSUE TITLE
Page missing info on a machine type

### ISSUE THREAD

**Issue by raunn** [MicrosoftDocs/memdocs#3030]
Please add info on whether this W365 machine size is supported, either directly or via upgrade from it to 8 cpu:
     Cloud PC Enterprise 4vCPU/16GB/128GB

Current text reads:
     8vCPU/32 (Cloud PCs resized from 1vCPU/2GB and 2vCPU/4GB to 8vCPU/32GB aren't supported)

So only currently references 1, 2 or 8 CPU systems. No mention of 4 CPU systems.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a95c0ba5-42dc-2d86-50e5-f066a7b511ca
* Version Independent ID: a95c0ba5-42dc-2d86-50e5-f066a7b511ca
* Content: [Set up virtualization-based workloads on your Windows 365 Cloud PC.](https://docs.microsoft.com/en-us/windows-365/enterprise/nested-virtualization)
* Content Source: [windows-365/enterprise/nested-virtualization.md](https://github.com/MicrosoftDocs/memdocs/blob/main/windows-365/enterprise/nested-virtualization.md)
* Service: **cloudpc**
* Sub-service: ****
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Article has been updated
