### ISSUE TITLE
Confusion between roles of Helpers/Sharers/Users

### ISSUE THREAD

**Issue by Cosmo121** [MicrosoftDocs/memdocs#3031]
The documentation mentions _Helpers_ and _Sharers_, while the prerequisites mention that the Remote help add-on license is needed for Helpers and users. Who are _users_? Are _users_ _Sharers_ or _Helpers_?

> In this article, we'll refer to the users who provide help as helpers, and users that receive help as sharers as they share their session with the helper.

> Remote help add-on license for all IT support workers (helpers) and users

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bc62c89-a452-0d3f-01f3-c5982803809e
* Version Independent ID: 6bc62c89-a452-0d3f-01f3-c5982803809e
* Content: [Remotely assist users that are authenticated by your organization.](https://docs.microsoft.com/en-us/mem/intune/remote-actions/remote-help)
* Content Source: [memdocs/intune/remote-actions/remote-help.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/remote-help.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@Cosmo121 Thank you for your feedback and sorry about the confusion. Typically users are shares and the same has been updated in the pre-requisites section now  via PR#https://github.com/MicrosoftDocs/memdocs/pull/3042

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Cosmo121 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
