### ISSUE TITLE
Incorrect instructions for creating group

### ISSUE THREAD

**Issue by alnelsonau** [MicrosoftDocs/memdocs#3032]
1) Article advised to select "yes" for assigning role to group - the group does not need to assign roles, and in fact the advice to use a dynamic query will not work if the group can have a role assigned

2) It suggests to pickup "dynamic user, manual or dynamic device" for assigning a dynamic device query. This is confusing, clearly it should be a dynamic device membership group.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97ce79c0-0014-f6f0-95f7-58574bfdefb3
* Version Independent ID: 40b3877e-a094-8d05-c95b-ca842c5ca8ce
* Content: [Create device groups for Windows Autopilot - Microsoft Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/autopilot/enrollment-autopilot)
* Content Source: [memdocs/autopilot/enrollment-autopilot.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/enrollment-autopilot.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by msbemba** [comment]
@alnelsonau Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3047

Once the author approves, the changes will be live.

Thanks
Sri
