### ISSUE TITLE
Clarify "data on the device cannot be recovered"

### ISSUE THREAD

**Issue by matziq** [MicrosoftDocs/memdocs#3033]
Please clarify the statement, "A wipe is useful for resetting a device before you give the device to a new user, or when the device has been lost or stolen. Be careful about selecting Wipe. **Data on the device cannot be recovered.** This level of device wipe follows a **standard file delete process**, rather than a low-level delete."

It says the data cannot be recovered but then says the files are simply deleted. This indicates the data could be recovered with common tools like undelete software.

Perhaps add the word "easily" so that it reads "Data on the device cannot be easily recovered."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cdcc7fd-5bd9-1645-abf4-a73d3ea7adaa
* Version Independent ID: 5022b2ba-5fb0-18ce-9079-1b65ad0b2e17
* Content: [Retire or wipe devices using Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/remote-actions/devices-wipe)
* Content Source: [memdocs/intune/remote-actions/devices-wipe.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/devices-wipe.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@matziq Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3046

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @matziq Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
