### ISSUE TITLE
Sort Device Categories

### ISSUE THREAD

**Issue by SteveYauHK** [MicrosoftDocs/memdocs#3034]
After creating device categories, how can I sort them into ascending order when user want to assign a category in 
[https://portal.manage.microsoft.com/devices/](https://portal.manage.microsoft.com/devices/)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a205db9e-c21f-b505-b5e9-d54fe44ececb
* Version Independent ID: a85d08c2-8ef1-fcd4-52de-f74ea8f41124
* Content: [Categorize devices into groups in Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-group-mapping)
* Content Source: [memdocs/intune/enrollment/device-group-mapping.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/device-group-mapping.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by yogkumgit** [comment]
@lenewsad Please help us in resolving this issue. Thanks

**Comment by lenewsad** [comment]
Hi @SteveYauHK, thanks for reaching out to the Microsoft Intune Docs team. Intune doesn't currently support that feature, so it's not possible to control the order of the device categories in Company portal. 

CC @yogkumgit

**Comment by yogkumgit** [comment]
@lenewsad Thank you very much for sharing this explanation. @SteveYauHK Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
