### ISSUE TITLE
4GB file size limitation

### ISSUE THREAD

**Issue by CaptainUnlikely** [MicrosoftDocs/memdocs#304]
I can't see this documented anywhere but in my experience Pull DPs have a file size limitation.  The issue is almost identical to that described here - https://support.microsoft.com/en-us/help/2927111/a-bits-multirange-transfer-of-a-large-file-fails - but affects Windows 10 1809 and Server 2019 also, possibly others but that's all I've tested.  For clarity this means no files over a certain size can be transferred to Pull DPs, they need to be prestaged.  In my environment for example a 4.4GB file transfers OK but a 7GB file does not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a39441b-ee2c-5b1b-5e64-ffd26fc7fd71
* Version Independent ID: a28c1d6d-fec8-86d3-e584-e086b27b3ced
* Content: [Pull-distribution point - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/hierarchy/use-a-pull-distribution-point#limitations)
* Content Source: [memdocs/configmgr/core/plan-design/hierarchy/use-a-pull-distribution-point.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/hierarchy/use-a-pull-distribution-point.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
I'm checking with engineering, but it might be best to [file a frown](https://docs.microsoft.com/mem/configmgr/core/understand/product-feedback#send-a-frown) from the console, if you haven't already.

**Comment by mestew** [comment]
@CaptainUnlikely  the KB you pointed out is the only known issue with Pull DPs and large file sizes that I know of. If you find that this is a persistent issue for you, there are a few options to get help with this other than  [filing a frown](https://docs.microsoft.com/mem/configmgr/core/understand/product-feedback#send-a-frown) from the console which doesn't guarantee resolution.
A couple of options available to provide the best level of support for this:

- Post on [Configuration Manager forums](https://docs.microsoft.com/answers/products/mem). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
