### ISSUE TITLE
CP's enrollment remediation flow

### ISSUE THREAD

**Issue by mannie** [MicrosoftDocs/memdocs#3044]
Could we update the documentation below to include the following information, please?

The Company Portal enters the enrollment remediation flow when the user logs into CP and the device has not successfully checked in with Intune in 30+ days (or the device is noncompliant due to a "Lost contact" compliance reason). In this flow, we attempt to initiate a checkin one more time. If that still does not succeed, then we issue a retire command to allow the user to re-enroll the device manually.

This is related  to ICM https://portal.microsofticm.com/imp/v3/incidents/details/324717652/home

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c19b6ee-2218-cd97-96a4-2832c0302d7e
* Version Independent ID: da3ff20c-91cb-d760-708c-8e56af5d59d8
* Content: [Device compliance policies in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/device-compliance-get-started)
* Content Source: [memdocs/intune/protect/device-compliance-get-started.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/device-compliance-get-started.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@mannie Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3075

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @mannie Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
