### ISSUE TITLE
Peculiar note

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/memdocs#3049]
Under "Set Win32 app availability and notifications", what does the note mean: "Restart time is not registered when the user doesn't have admin privileges to the device."? Is it saying that this feature does not work unless the user is an admin? In that case, it will not work in most corporate environments using Intune. Does it mean it only works for device context apps, where the app is installed by the system account?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de85c97e-b22f-1b7d-0fb2-18e2c2b1970d
* Version Independent ID: 0744e16d-47f6-f1f4-0fbd-41074136e110
* Content: [Win32 app management in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-win32-app-management)
* Content Source: [memdocs/intune/apps/apps-win32-app-management.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/apps-win32-app-management.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@Air-Git Thank you for your feedback. From my testing, i see the restart time is getting registered when the user does not have admin rights. I have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3076

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by Air-Git** [comment]
In our case, the restart notification was displayed, but there was no countdown, no reminders, no dismissible warning. Not to be too negative, quite useless in forcing the user to restart but at a convenient time.

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Air-Git Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
