### ISSUE TITLE
Unclear if and how Software Inventory should be configured for Collect Client Logs.

### ISSUE THREAD

**Issue by merlinfrombelgium** [MicrosoftDocs/memdocs#305]
> The logs are returned using software inventory file collection.

The Prerequisites section doesn't mention whether the Client Settings need to be configured for Software Inventory. In my experience, the log files are never uploaded to Site if Software Inventory is disabled for the clients.

Please clarify.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 971935f4-ea20-555f-e232-4c496a498e86
* Version Independent ID: b8868418-6d27-9526-364b-bbb4a756a812
* Content: [Client notification - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/client-notification)
* Content Source: [memdocs/configmgr/core/clients/manage/client-notification.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/client-notification.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @merlinfrombelgium for the question. I confirmed with engineering: Software inventory doesn't need to be enabled for the clients, this has been tested. As long as you don’t disable the SINV site server component the feature will work. I'm personally not even sure how you would disable the server side component, so assume that's not broadly known.

To give a little more detail, we don’t actually use the SINVFC component of the client to send up the logs. A SINVFC message containing the logs is created and sent directly to the MP without using the client’s SINV component. If the feature isn’t working, enable verbose logging for the client and MP/server components to troubleshoot. Or open a support case to help.

I'll add a small note to this page that SINV doesn't need to be enabled.

**Comment by merlinfrombelgium** [comment]
Roger that Aaron, thanks for checking. Good to know.

Log collection didn't work so far but haven't spent the time to troubleshoot yet.
