### ISSUE TITLE
I do not see Register button or any actionable action so how can I register my machine from company portal

### ISSUE THREAD

**Issue by V-kellyz** [MicrosoftDocs/memdocs#3050]
I do not see Register button or any actionable action so how can I register my machine from company portal? I only can check Status and check Help topics. Not know how to use Company portal to make my machine compliance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb1f7fe9-6bae-6fc5-eb77-d456e08f8736
* Version Independent ID: b0d12a58-0a77-67dc-7006-49e98589ca7f
* Content: [What info can your company see when you enroll your device?](https://docs.microsoft.com/en-us/mem/intune/user-help/what-info-can-your-company-see-when-you-enroll-your-device-in-intune)
* Content Source: [memdocs/intune/user-help/what-info-can-your-company-see-when-you-enroll-your-device-in-intune.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/what-info-can-your-company-see-when-you-enroll-your-device-in-intune.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@V-kellyz Thank you for your feedback. Ideally, you should see an actionable item if the machine is not enrolled.  If this continues to be a problem, I'd recommend you contact your IT support or if you are an admin you can click on the need help icon on the admin center so that a Microsoft support engineer will be able to fix this.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @V-kellyz Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
