### ISSUE TITLE
The app protection policy doesn't work

### ISSUE THREAD

**Issue by Michal-Ziemba** [MicrosoftDocs/memdocs#306]
When followed the full article at https://docs.microsoft.com/en-us/mem/intune/protect/tutorial-protect-email-on-unmanaged-devices and tested it through I can say that the app protection policy doesn't work at all having impact on the locally installed Outlook app on the iPad. 
Even the policy restricts copying or require the device to be PIN protected, this is not enforced, and when checking at Azure Policy - no users check-in. 

if you need, I can give access to the test tenant where I am testing it. 

/Michal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 733b08c2-5666-0d9b-8e78-28fba3456a6f
* Version Independent ID: ab6a321b-d6c0-c301-8156-96ccfdd21192
* Content: [Tutorial - Protect Exchange Online email on unmanaged devices - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/tutorial-protect-email-on-unmanaged-devices)
* Content Source: [memdocs/intune/protect/tutorial-protect-email-on-unmanaged-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/tutorial-protect-email-on-unmanaged-devices.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@Michal-Ziemba  In a sweep of some orphaned issues we see this one was not addressed.  Unfortunately, we can’t engage in troubleshooting via this docs feedback forum. I regret the policy was problematic and not working as expected. If that condition persists, please open a support case where this can be properly investigated. The support process can then drive product feedback to engineering and to the docs team and published content.
