### ISSUE TITLE
SDK Android 10 support?

### ISSUE THREAD

**Issue by juelizon** [MicrosoftDocs/memdocs#307]
The SDK requirements for Android versions supported mention Android API 19 (Android 4.4+) through Android API 28 (Android 9.0).
Is Android 10 and later supported as well?
If not, is it on the roadmap?
Thanks.
J.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adadc1af-5730-8ab9-bd95-5d67a2023d90
* Version Independent ID: 3537d990-56b8-597f-1013-ec25b773d406
* Content: [Microsoft Intune App SDK for Android developer guide](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android#requirements)
* Content Source: [memdocs/intune/developer/app-sdk-android.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/developer/app-sdk-android.md)
* Service: **microsoft-intune**
* Sub-service: **developer**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by lenewsad** [comment]
The documentation team hasn’t been able to find an answer for this issue. If this is still an issue for you, please try one of these support channels:  

* Open a support ticket by following the steps here: [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support)  

* Post on [Microsoft Q & A](https://docs.microsoft.com/answers/products/?WT.mc_id=msdnredirect-web-msdn).

* Browse the old [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/home?forum=microsoftintuneprod). The site was recently replaced with Microsoft Q & A but still shows the old posts from our community MVPs who are very experienced, knowledgeable, and helpful.

* Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
