### ISSUE TITLE
Restart time is not registered when the user doesn't have admin privileges to the device. ????

### ISSUE THREAD

**Issue by ddubs1** [MicrosoftDocs/memdocs#3070]
[Enter feedback here]
"Restart time is not registered when the user doesn't have admin privileges to the device."  What does this note mean?   A specific example would be helpful being in testing restart times are being registered when the user does not have admin rights.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de85c97e-b22f-1b7d-0fb2-18e2c2b1970d
* Version Independent ID: 0744e16d-47f6-f1f4-0fbd-41074136e110
* Content: [Win32 app management in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-win32-app-management#set-win32-app-availability-and-notifications)
* Content Source: [memdocs/intune/apps/apps-win32-app-management.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/apps-win32-app-management.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@ddubs1 Thank you for your feedback. I was able to test this as well. We have a PR#https://github.com/MicrosoftDocs/memdocs/pull/3076 Open to remove the same. Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ddubs1 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
