### ISSUE TITLE
AOSP corporate owned, userless without access to camera

### ISSUE THREAD

**Issue by jobascott** [MicrosoftDocs/memdocs#3073]
I need to address the use case of enrolling an AOSP device (Pico 3 VR headset) without use of/access to a camera for device enrollment. Is there an enrollment profile that can be deployed to the device without the QR code option?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd3be747-2a3b-4ccd-b063-3ac21a25b65d
* Version Independent ID: fd3be747-2a3b-4ccd-b063-3ac21a25b65d
* Content: [Set up Android (AOSP) device management in Intune for corporate-owned userless devices - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/android-aosp-corporate-owned-userless-enroll)
* Content Source: [memdocs/intune/enrollment/android-aosp-corporate-owned-userless-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/android-aosp-corporate-owned-userless-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jobascott Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
