### ISSUE TITLE
Typo in Additional Information link.

### ISSUE THREAD

**Issue by smtpcx** [MicrosoftDocs/memdocs#3077]
The following line has a typo:

Current:
For related information about audit logs, see [Addition information](https://docs.microsoft.com/en-us/mem/intune/fundamentals/monitor-audit-logs#additional-information).

Proposed:
For related information about audit logs, see [Additional information](https://docs.microsoft.com/en-us/mem/intune/fundamentals/monitor-audit-logs#additional-information).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e5b9d48-b76c-6d66-a4f3-48936c51216b
* Version Independent ID: 208f04ee-503d-c6e8-cedc-59fd720c71bf
* Content: [Audit changes and events in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/monitor-audit-logs)
* Content Source: [memdocs/intune/fundamentals/monitor-audit-logs.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/monitor-audit-logs.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @dougeby
* Microsoft Alias: **dougeby**

**Comment by msbemba** [comment]
@smtpcx Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3096

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @smtpcx Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
