### ISSUE TITLE
No mention of `MAMStartupActivity`

### ISSUE THREAD

**Issue by MariusVolkhart** [MicrosoftDocs/memdocs#309]
Somewhere between version `6.0.0` and `6.5.3` of the Intune SDK, a requirement was added to have the `MAMStartupActivity` in the application manifest. This is undocumented. In fact, this document makes no references to `MAMStartupActivity`, not even an explanation of what it does, why it is needed, how it works together with other parts of Intune, or how to correctly configure it in the manifest.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adadc1af-5730-8ab9-bd95-5d67a2023d90
* Version Independent ID: 3537d990-56b8-597f-1013-ec25b773d406
* Content: [Microsoft Intune App SDK for Android developer guide](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android)
* Content Source: [memdocs/intune/developer/app-sdk-android.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/developer/app-sdk-android.md)
* Service: **microsoft-intune**
* Sub-service: **developer**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
We have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. If you have continue to have questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

Please use the above channels if you don't already have a solution.
