### ISSUE TITLE
hyperlink in enrollment restrictions page is incorrect

### ISSUE THREAD

**Issue by cloudyqintian** [MicrosoftDocs/memdocs#3092]
The links in "[What are enrollment restrictions?](https://docs.microsoft.com/en-us/mem/intune/enrollment/enrollment-restrictions-set)" for device platform enrollment restrictions & device limit enrollment restrictions' hyperlinks are leading to incorrect pages.
![image](https://user-images.githubusercontent.com/76044094/187336292-22771fbe-987f-41c2-80ef-13f0dd2705da.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e8c2d91-8808-a504-da13-526b152a5cfe
* Version Independent ID: 037b60a6-d6b5-75ad-1933-39d0f7a69048
* Content: [Overview of enrollment restrictions - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/enrollment-restrictions-set)
* Content Source: [memdocs/intune/enrollment/enrollment-restrictions-set.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/enrollment-restrictions-set.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@cloudyqintian Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3098

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @cloudyqintian Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
