### ISSUE TITLE
Remote Content Library on Azure File Storage supported configuration?

### ISSUE THREAD

**Issue by Sri-Boddupalli** [MicrosoftDocs/memdocs#3099]
For the HA feature is the Remote Content library supported when hosted on an Azure File Storage? Where the Site Servers and Site Systems are running in an IaaS configuration.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8818c35b-2368-58dd-e0a9-7a72bb5df035
* Version Independent ID: 38fa8fde-6c09-909d-7817-e82cbd6a601a
* Content: [Configure a remote content library - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/hierarchy/remote-content-library)
* Content Source: [memdocs/configmgr/core/plan-design/hierarchy/remote-content-library.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/configmgr/core/plan-design/hierarchy/remote-content-library.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
As long as it meets the requirements for ConfigMgr, site servers, and the content library. As the article states:

> A SAN is recommended, because it's highly available, and provides elastic storage that grows or shrinks over time to meet your changing content requirements.
