### ISSUE TITLE
less than 24 hr Maint Window?

### ISSUE THREAD

**Issue by slkissinger** [MicrosoftDocs/memdocs#310]
"The maximum duration of a window has to be less than 24 hours."
Is there a technical reason for this?  I've seen in our environment people making a 24 hour window from say... 6pm Friday to 6pm Saturday.  Is it just because people would make a daily 24 hr window--which is illogical?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41833b7b-2c49-1d57-72cb-b177ea054c2f
* Version Independent ID: 8bb9cc02-2b06-c8a0-1d45-693c1ddd60f5
* Content: [Use maintenance windows - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/collections/use-maintenance-windows)
* Content Source: [memdocs/configmgr/core/clients/manage/collections/use-maintenance-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/collections/use-maintenance-windows.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @slkissinger. The UI doesn't let you set it for more than 24 hours. I suppose you could set a daily recurring 24 hour MW, but then you won't be able to deploy anything to the device. Unless that's the intent....
I'm making some general updates to this article, I'll make a mention of this. The changes will probably publish tomorrow. 
Thanks for the feedback!

**Comment by slkissinger** [comment]
I think it's just wording?  "The maximum duration of a window has to be less than 24 hours".    
Sure... if you're talking about a daily window.   "The maximum duration of a Window of daily type has to be less than or equal to 24 hours."
A weekly Maintenance Window of Weekly on Saturday, 1am to 1am works fine, too.  We have service windows a lot like that--once a week, for a full day (or two, weekly, Saturday and Sunday).
It only came up because we're starting to onboard some server teams here...and they pointed to the docs as saying "Microsoft said" they can't have a full 24 hours a day on each weekend day.  And we know it can be done; so I said I'd "file a doc review request".  


 

    On Wednesday, June 3, 2020, 5:17:30 PM CDT, Aaron Czechowski <notifications@github.com> wrote:  
 
 


Closed #310.
