### ISSUE TITLE
Footnote 1 under App management capabilities by platform refers to WIP, which is being retired.

### ISSUE THREAD

**Issue by langjtl** [MicrosoftDocs/memdocs#3102]
[Enter feedback here]
Footnote 1 under App management capabilities by platform refers to WIP, which is being retired. The footnote 1 in this figure: https://docs.microsoft.com/en-us/mem/intune/apps/app-management#app-management-capabilities-by-platform refers to Windows Information Protection. The linked documentation says the feature is being decremented for non-enrolled devices. Some clarity on how to protect corporate data on BYOD Windows devices will be helpful here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a125bda-493d-8beb-e67f-09ff821e8fe4
* Version Independent ID: 39473e48-5fbd-a50c-6732-d86bcd1f7290
* Content: [What is app management in Microsoft Intune?](https://docs.microsoft.com/en-us/mem/intune/apps/app-management#feedback)
* Content Source: [memdocs/intune/apps/app-management.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/app-management.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@langjtl Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3126

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @langjtl Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
