### ISSUE TITLE
Company Portal on Android is STILL required to apply App Protection Policies

### ISSUE THREAD

**Issue by JonesMikael** [MicrosoftDocs/memdocs#3103]
Historically, the Microsft Company Portal was always required on Android to be able to apply App Protection Policies. However, this docs page changed on Apr 5 2022 by @msbemba stating "_The broker app can be either the Microsoft Authenticator or Microsoft Company portal for Android devices_".

We've done many hours of testing and it shows this is NOT true. We also had a support ticket with Microsoft [Case #:32525687] and they came to the same conclusion.

So I think we should change it back to Microsoft Company Portal for Android is required if nobody has some other information?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca76fcaf-979f-7b6b-c410-34080685d415
* Version Independent ID: eaceac76-73c4-c586-952c-8dfa90390c6e
* Content: [Use app-based Conditional Access policies with Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/app-based-conditional-access-intune)
* Content Source: [memdocs/intune/protect/app-based-conditional-access-intune.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/app-based-conditional-access-intune.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by JonesMikael** [comment]
Seems like @Erikre updated the article on Sep 1 to reflect this :)

**Comment by msbemba** [comment]
@JonesMikael Thank you for your feedback. I will test and update the document if need be.

Thanks
Sri

**Comment by msbemba** [comment]
@JonesMikael Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3157

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @JonesMikael Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
