### ISSUE TITLE
Link error in german version

### ISSUE THREAD

**Issue by chrisop** [MicrosoftDocs/memdocs#3105]
Hi Microsoft team,

in the german translation the link to the Company Portal has an issue.
It points to the following URI: https://go.microsoft.com/fwlink/?linkid=853070herunter
At the end of the link, the german word "herunter" is added.

Thx and best regards,
Christian

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 350323ac-7941-3fb1-6166-10a5130351e2
* Version Independent ID: f4512958-ce42-e9eb-7ea0-77d68ebd39b8
* Content: [Add the Company Portal for macOS app - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-company-portal-macos#install-company-portal-for-macos-as-a-macos-lob-app)
* Content Source: [memdocs/intune/apps/apps-company-portal-macos.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/apps-company-portal-macos.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by yogkumgit** [comment]
@tiburd Please help us finding the right person for this translation issue. Thanks

**Comment by tiburd** [comment]
Thank you!

I'll submit a translation bug to Global Services.

cc: @yogkumgit
