### ISSUE TITLE
Pilot Mode Instructions

### ISSUE THREAD

**Issue by rocksteve** [MicrosoftDocs/memdocs#3107]
Under the section 'Configure your tenant to support Microsoft Defender for Endpoint Security Configuration Management' when configurating for Pilot Mode there is no statement advising to un-tick both 'Windows Client devices' and 'Windows Server devices' to be able to use Pilot Mode using tagging. If these options are left enabled all devices are still onboarded into MEM via MDE.

Could this section be updated with this information once confirmed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b166b931-f3f7-3323-7288-758cfa5934f1
* Version Independent ID: b166b931-f3f7-3323-7288-758cfa5934f1
* Content: [Use Intune to manage Microsoft Defender for Endpoint Security on devices not enrolled with Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/mde-security-integration#feedback)
* Content Source: [memdocs/intune/protect/mde-security-integration.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/mde-security-integration.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@rocksteve Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3159

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @rocksteve Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by msbemba** [comment]
@yogkumgit This can be closed.
