### ISSUE TITLE
How to MAM LOB In Tune apps

### ISSUE THREAD

**Issue by awws** [MicrosoftDocs/memdocs#311]
Hello,

Please would you add how to do line of business apps under mam only i.e. no MDM?

I can't find documentation on how to do this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eda39475-7d32-b359-ed80-b1e3ed3aee70
* Version Independent ID: 4fe0e69a-fa68-1635-8c4c-6570032df2a7
* Content: [Add apps to Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-add)
* Content Source: [memdocs/intune/apps/apps-add.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/apps-add.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@awws - Please take a look at the following topic:
- [Assign apps to groups with Microsoft Intune](https://docs.microsoft.com/mem/intune/apps/apps-deploy)

Also, we have a number of topics related to LOB apps and Win32 apps that will help you create and add your LOB app to Intune. Once added, you can deploy your app in either a MDM or MAM scenario.

If you have additional questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

This question is in our documentation feedback channel and it may be best to handle this question as a support request. For this reason, I'm closing this issue. Please use the above channels if you don't already have a solution.
