### ISSUE TITLE
Contradiction or needs to be clearer?

### ISSUE THREAD

**Issue by garyjkane** [MicrosoftDocs/memdocs#3115]
So the article is telling me how i can pick an update, then set a schedule for when it is installed... fine, so why does it say 

"Apple MDM doesn't allow you to force a device to install updates by a certain time or date. "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc473a5-4b72-9486-f9db-8f3beb0aeeff
* Version Independent ID: bf102862-75c3-2b2e-cfae-c1cd4fa34e3f
* Content: [Use Microsoft Intune policies to manage iOS/iPadOS software updates](https://docs.microsoft.com/en-us/mem/intune/protect/software-updates-ios)
* Content Source: [memdocs/intune/protect/software-updates-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/software-updates-ios.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@garyjkane Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3124

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @garyjkane Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
