### ISSUE TITLE
Filters permissions are unclear

### ISSUE THREAD

**Issue by SeniorConsulting** [MicrosoftDocs/memdocs#3117]
Hi Team,

Can you please expand a little on the permissions: Filters/Create, Filters/Delete, Filters/Read, and Filters/Update? This is under the subheading [Custom role permissions](https://docs.microsoft.com/en-us/mem/intune/fundamentals/create-custom-role#custom-role-permissions)

I _**think**_ this refers to Intune Configuration Profile, App Deployment filters (https://docs.microsoft.com/en-us/mem/intune/fundamentals/filters), but it's not entirely clear as there are other filters (e.g. Page filters within each blade of Intune).

Inclusion of hyperlinks to the appropriate feature would be marvelous, or elaboration on what "filters" are in this context.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee559326-3f31-4a98-7399-21d571a42d9d
* Version Independent ID: 11eb7dee-44e1-d6bd-76c1-a6327199964d
* Content: [Create a custom role in Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/create-custom-role#custom-role-permissions)
* Content Source: [memdocs/intune/fundamentals/create-custom-role.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/create-custom-role.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@SeniorConsulting Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3125

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @SeniorConsulting Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by SeniorConsulting** [comment]
Perfect! Thanks for updating the documentation :)
