### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by sbsmiths** [MicrosoftDocs/memdocs#3119]
[Enter feedback here]
Hi Microsoft,

why we don't see on this page the two new Intune reports - still in preview - MEMUpgradeReadinessDevice and MEMUpgradeReadinessOrgAppAndDriverV2 which correspond to Windows feature update device readiness report and Windows feature update compatibility risks report (Preview)

Thanks
SB

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6c8cbcb-dd8c-62d8-88e5-ec1e8badc511
* Version Independent ID: b4b5007c-684c-d929-90cc-bb1e263bb21c
* Content: [Intune Graph API - Reports and properties](https://docs.microsoft.com/en-us/mem/intune/fundamentals/reports-export-graph-available-reports)
* Content Source: [memdocs/intune/fundamentals/reports-export-graph-available-reports.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/reports-export-graph-available-reports.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by yogkumgit** [comment]
@sbsmiths Thank you very much for your kind feedback. Considering your valuable feedback, please leave a feedback on our main feedback portal https://feedbackportal.microsoft.com/ so a Product/dev engineer can provide you information. Here we are limited to documentation fixes and improvements only. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
