### ISSUE TITLE
Suggestion: Use AAD for Azure Active Directory

### ISSUE THREAD

**Issue by mykl-ms** [MicrosoftDocs/memdocs#312]
Under "Endpoint Manager includes the following services:", one of the items is "Azure Active Directory (AD):".  Typically AD reference to on-premise Active Directory, and AAD is used for Azure Active Directory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fb7e4a5-d1a2-deb7-73d4-a9b3b4ce07ab
* Version Independent ID: 43915b87-3076-18dd-21e8-3c44a0c653f2
* Content: [Microsoft Endpoint Manager overview - Azure](https://docs.microsoft.com/en-us/mem/endpoint-manager-overview)
* Content Source: [memdocs/endpoint-manager-overview.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/endpoint-manager-overview.md)
* Service: **microsoft-intune**
* Sub-service: ****
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by aczechowski** [comment]
Hi @mykl-ms, thanks for the feedback. While that's commonly used in the community, here's a snip from our style guide:

> First mention: Microsoft Azure Active Directory (Azure AD)
> Subsequent mentions: Azure AD
> It's not acceptable to use the full acronym AAD or just AD.
