### ISSUE TITLE
This page is no longer accurate for Version 5.0.5616.0 of Microsoft Intune Company Portal for Android

### ISSUE THREAD

**Issue by TheVoice77** [MicrosoftDocs/memdocs#3122]
[Enter feedback here]

The instructions for sending logs from Company Portal are not correct for this new version of Company Portal.  When I tap Help, the next screen says Diagnostic Logs and does not have an option to "Email Support".  When sharing this link with a user to have them collect logs for a support incident, the user will become even more frustrated than they are with the issue we opened the support incident for.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 032a3331-b8f3-2fdb-f7be-d08782141f93
* Version Independent ID: dfd14384-9274-9133-b0e4-2595755ba112
* Content: [Upload and email app logs](https://docs.microsoft.com/en-us/mem/intune/user-help/send-logs-to-your-it-admin-by-email-android#feedback)
* Content Source: [memdocs/intune/user-help/send-logs-to-your-it-admin-by-email-android.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/send-logs-to-your-it-admin-by-email-android.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by yogkumgit** [comment]
@lenewsad Please help us in resolving this issue. Thanks

**Comment by lenewsad** [comment]
Hi @TheVoice77, Thanks for contacting the Microsoft Intune Docs team. The steps in [Send logs from Company Portal](https://learn.microsoft.com/mem/intune/user-help/send-logs-to-your-it-admin-by-email-android#send-logs-from-company-portal) have been updated and will be live by 5 PM PST on October 5.
