### ISSUE TITLE
Add info on changing Apple ID's for renewing ADE token

### ISSUE THREAD

**Issue by MarcLaf** [MicrosoftDocs/memdocs#3127]
In the section for Renewing the ADE token it says the following:

> You'll sometimes need to renew your tokens:
> 
> Renew your ADE token yearly. The Endpoint Manager admin center shows the expiration date.
> If the Apple ID password changes for the user who set up the token in Apple Business Manager, renew your enrollment program token in Intune and Apple Business Manager.
> If the user who set up the token in Apple Business Manager leaves the organization, renew your enrollment program token in Intune and Apple Business Manager.

There has been much confusion in the past when it comes to changing the Apple ID used for creating these tokens. Certain ones (such as APNS Certificate) cannot be changed without requiring all devices to be re-enrolled unless you contact Apple Support to perform the change on the back end. So while technically you can change it, it will cause issues. Changing the Apple ID for the ADE (DEP) token will not cause issues.

The last line in the above quote says you can renew the token if the user who set up the token in ABM leaves which is a bit vague. Can you add another bullet or modify this one to say something like "If you want to change the Apple ID used to create the ADE token. This change will not affect currently enrolled devices."

The Microsoft Endpoint Manager portal also refers to this as the DEP token and the documentation uses ADE. Perhaps adding this in somewhere too?

I believe this also applies to changing the VPP token in that it does not affect current devices but I don't know for certain.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd130267-c54b-41e3-d534-831d4a86bae6
* Version Independent ID: bdfa7eca-a356-3dde-7643-9a759f952007
* Content: [Enroll iOS/iPadOS devices by using ADE - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-ios#renew-an-automated-device-enrollment-token)
* Content Source: [memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@MarcLaf Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3189

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MarcLaf Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
