### ISSUE TITLE
not working for me

### ISSUE THREAD

**Issue by billzhang1123** [MicrosoftDocs/memdocs#3129]
I ran the wrapping process successfully. But Intune just couldn't install it - undecodable apk. I dont know where to troubleshoot it from.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f83f5455-d85e-e47b-867d-0e312a4d348c
* Version Independent ID: e91fef51-15df-3757-3ffd-ef7ec9cab7b5
* Content: [Wrap Android apps with the Intune App Wrapping Tool](https://docs.microsoft.com/en-us/mem/intune/developer/app-wrapper-prepare-android)
* Content Source: [memdocs/intune/developer/app-wrapper-prepare-android.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/developer/app-wrapper-prepare-android.md)
* Service: **microsoft-intune**
* Sub-service: **developer**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@billzhang1123 Thank you for your feedback. Since this is a technical issue, I'd recommend you contact Microsoft support via the need help section on the admin center, so that a support engineer can assist you in fixing the issue/bug.

Hope this helps!

Thanks
Sri
