### ISSUE TITLE
Not clear about whether _all_ Intune devices will be enrolled

### ISSUE THREAD

**Issue by webash** [MicrosoftDocs/memdocs#313]
It isn't explained whether all devices both existing and future that are MDM managed will be connected to MD ATP when you enable `Connect Windows devices version 10.0.15063 and above to Microsoft Defender ATP` or `Connect Android devices of version 6.0.0 and above to Microsoft Defender ATP` switches.

The article then continues and explains how to connect Intune MDM managed machines using configuration profiles, but this note further confuses whether you need to tick the above **and** use a configuration profile:
`If you've properly established a connection with Microsoft Defender ATP, Intune will automatically Onboard the configuration profile for you, and the Microsoft Defender ATP client configuration package type setting will not be available.`

So does the mere nature of the connection between MD ATP and Intune already having been setup mean that _no configuration **profile** is necessary_, or just that the deployment package is automatically added to the configuration profile, so _configuring **the setting** is not necessary_?

Please add clarification to the documentation to make it clear exactly what the two switches do, and thus whether a configuration profile is necessary to actually instruct a device to connect to MD ATP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d129246-93fe-04ec-0e49-8e9ac1c910a8
* Version Independent ID: 66d3e475-e2b9-1974-f04a-2ae8b31f96bd
* Content: [Use Microsoft Defender ATP in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/advanced-threat-protection)
* Content Source: [memdocs/intune/protect/advanced-threat-protection.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/advanced-threat-protection.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by syswpit** [comment]
This is not clear to me either. What exactly does the option do? 
Is it the same as putting "all users/devices" in the config profile?
Confusing..

**Comment by webash** [comment]
@Brenduns is this in research/discussion?

**Comment by aanavath** [comment]
My understanding is that both existing and future devices that are MDM managed will be connected to MDATP when `Connect Windows devices version 10.0.15063 and above to Microsoft Defender ATP` or `Connect Android devices of version 6.0.0 and above to Microsoft Defender ATP` are ticked.

You do need to tick the above and use the configuration profile both. The configuration profile is only for configuration - it only covers onboarding. The `Connect Windows devices...` indicates that you now want to use Defender signals for compliance calculation, as such, these settings are listed under 'MDM Compliance Policy Settings'.

As per the docs, if you've properly established a connection with Microsoft Defender ATP (AKA gone through the Security Center flow and switched on the Microsoft Intune toggle), Intune will automatically Onboard the configuration profile for you (AKA create a `Microsoft Defender ATP (Windows 10 Desktop)` profile type), and the Microsoft Defender ATP client configuration package type setting will not be available. 

Does this help? The Docs can be made clearer so thanks for bringing this to our attention.

**Comment by webash** [comment]
Yeap I think the bit that is missing (or not obvious enough) is that those toggles are for `Compliance`. Not for configuration. The wording `Connect x devices` is also misleading. The _devices_ aren't being connected by toggling that switch, just whether Intune will have access to their compliance information.

**Comment by syswpit** [comment]
@aanavath
It's very confusing, you don't need to tick that box at all, if you have "all users/devices" in the configuration (as per the documentation) all your devices will already be connected and showing in the ATP security portal.
You can then simply edit your existing compliance policy (which also has all your users, usually) and add ATP compliancy checks to it.
