### ISSUE TITLE
W365 Enterprise license needed to unlock management pane

### ISSUE THREAD

**Issue by sfarnik** [MicrosoftDocs/memdocs#3131]
Hello,

Within `Management requirements' can you please state/clarify that at least one W365 Enterprise license is needed in the tenant to access the [W365 provisioning/management](https://endpoint.microsoft.com/#view/Microsoft_Intune_DeviceSettings/DevicesMenu/~/Cloud%20PC) pane ?

We wasted one month to find it.

thanks,
Stefan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dbf3611-f317-5455-990b-76d67549cd53
* Version Independent ID: 0f83b4c7-a653-1f7d-ec57-fb8933d984be
* Content: [Windows 365 requirements](https://docs.microsoft.com/en-us/windows-365/enterprise/requirements)
* Content Source: [windows-365/enterprise/requirements.md](https://github.com/MicrosoftDocs/memdocs/blob/main/windows-365/enterprise/requirements.md)
* Service: **cloudpc**
* Sub-service: ****
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by sfarnik** [comment]
Its getting ridiculous. To create provisioning policies, you have to have User Administrator role enabled.
And to use an Azure network connection (ANC) in said profiles ... currently unknown, I suspect having ownership of the network.

**Comment by PhillyUrbs** [comment]
I have a pull request in to get this clarification added.
