### ISSUE TITLE
CA Policies templates to avoid

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/memdocs#3139]
According to https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/concept-conditional-access-policy-common#conditional-access-templates-preview there are 14 CA Policies available in AAD. Are there any those that should not be used for Win 365 scenarios? If so please identify them in this documentation. 

Also are there any specific things that we should do regarding CA policies, named locations, device groups etc when designing CA Policies for use with Win 365 machines?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95fbdbb9-e3c6-c3c2-1309-b731230c168e
* Version Independent ID: 4341c9a2-0336-2fa2-b3d3-b68ab841015a
* Content: [Set conditional access policies for Windows 365](https://docs.microsoft.com/en-us/windows-365/enterprise/set-conditional-access-policies)
* Content Source: [windows-365/enterprise/set-conditional-access-policies.md](https://github.com/MicrosoftDocs/memdocs/blob/main/windows-365/enterprise/set-conditional-access-policies.md)
* Service: **cloudpc**
* Sub-service: ****
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
41340609

**Comment by ErikjeMS** [comment]
@DeanGross The PM responded with this: "Took a look at the Templates. None of these are blocking for Windows 365."

I'll close this issue. If you have more questions on this issue, let me know here and I can reopen.

Thanks!
