### ISSUE TITLE
The error code -2016345060 is listed twice. Giveing different error mesasges and descriptions. 

### ISSUE THREAD

**Issue by CloudlinkAdmin** [MicrosoftDocs/memdocs#314]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 826eb5cf-dadc-a5a6-ff24-793f7e9fb371
* Version Independent ID: 92227d8c-1eb3-e5b7-8dc1-52aaa1eabfd4
* Content: [App installation error codes - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-install-error-codes)
* Content Source: [memdocs/intune/apps/app-install-error-codes.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-install-error-codes.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@CloudlinkAdmin - Thanks for the feedback. I see that this error is listed for Android, iOS, and other errors. They all seem to point to the same 'user uninstalled the app' issue, although this could be stated more clearly. I'll look into updating these descriptions.

If you have questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

This question is in our documentation feedback channel and it may be best to handle this question as a support request. For this reason, I'm closing this issue. Please use the above channels if you don't already have a solution.
