### ISSUE TITLE
Add PacketFence to list of third-party CAs that support Intune

### ISSUE THREAD

**Issue by trs80** [MicrosoftDocs/memdocs#3142]
PacketFence's internal CA also supports Intune SCEP https://www.packetfence.org/doc/PacketFence_Installation_Guide.html#_intune_integration

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cda83a64-56ae-a632-dc81-dfd1a03984c1
* Version Independent ID: b93da48e-4097-4c3a-f6c8-02a5c4e0a616
* Content: [Use third-party certification authorities (CA) with SCEP in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/certificate-authority-add-scep-overview)
* Content Source: [memdocs/intune/protect/certificate-authority-add-scep-overview.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/certificate-authority-add-scep-overview.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@trs80 As discussed in PR #3185 

What we need is for someone from PacketFence to reach out to Lance Crandall ( [lacranda@microsoft.com](mailto:lacranda@microsoft.com) ). Lance is the PM for this area. He's not heard of PacketFence before and has no contacts to work with. The proces requires the third-party company to reach out to us if they want thier solution to be listed in our offiical poroduct content. Once PacketFence reaches out, a proper evaluation of thier CA can be done, which can then lead to their being added as a supported partner for third party CAs.

Hope this helps!

@yogkumgit  This can be closed.
