### ISSUE TITLE
Add note to instructions that a logo must be present for the LOB app to appear in Company Portal

### ISSUE THREAD

**Issue by computer1up** [MicrosoftDocs/memdocs#3145]
Was wondering for a while why my LOB app wasn't showing up in Company Portal on my client devices. Turns out that adding a logo is a requirement, without adding a logo for the app, it won't be displayed in the Apps section. 

This is not currently explained in the docs, and selecting a logo is not a hard required setting in Intune. Maybe it would be a good idea to add this as a note. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54e4efd6-d1de-dba7-6ae5-a91c7a28b662
* Version Independent ID: f529438b-becd-3b8e-dc6c-02413af9854f
* Content: [How to add macOS line-of-business apps to Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/lob-apps-macos)
* Content Source: [memdocs/intune/apps/lob-apps-macos.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/lob-apps-macos.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@computer1up Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3192

Once the author approves, the changes will be live.

Thanks
Sri
