### ISSUE TITLE
Intune Scripts

### ISSUE THREAD

**Issue by TassieTrooper** [MicrosoftDocs/memdocs#3151]
Hi,

There seems to be ambiguity within this document or perhaps an error with the way Intune Scripts work as per the document....unless I am completely wrong ;)

If I set my script to run as user context the script runs EVERY TIME for any user for their first login on a device with primary user assigned (non-shared device) and I can see that the script has ran successfully before against the primary user.

When I read your statement, "Once the script executes, it doesn't execute again unless there's a change in the script or policy.", which in my interpretation is not right.

Thoughts??

Kind regards,

David Smith

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4d6b1270-e554-dc36-2a51-1cdab303e91a
* Version Independent ID: 4a62c248-5737-13cc-3270-1f9649bd147d
* Content: [Add PowerShell scripts to Windows 10/11 devices in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/apps/intune-management-extension)
* Content Source: [memdocs/intune/apps/intune-management-extension.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/intune-management-extension.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@TassieTrooper Thank you for your feedback. You are right, it should execute only when there is a new script or changes. I'd recommend you report this bug to Microsoft support via the need help section on the admin center so that a support engineer can resolve or escalate this issue.

Hope this helps!

Thanks
Sri

**Comment by TassieTrooper** [comment]
OK I will report it. Thanks for your time.
