### ISSUE TITLE
Is the console & client upgrade required after this update? 

### ISSUE THREAD

**Issue by Btreyo** [MicrosoftDocs/memdocs#3152]
I can see a site reset is required, after this update can i check whether an updated client agent & console is also created as part of this update?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8de2f392-97fd-d254-9bed-a13a822c7e7a
* Version Independent ID: 8de2f392-97fd-d254-9bed-a13a822c7e7a
* Content: [NTLM connection fallback update for Microsoft Endpoint Configuration Manager - Configuration Manager](https://learn.microsoft.com/en-us/mem/configmgr/hotfix/2207/15498768)
* Content Source: [memdocs/configmgr/hotfix/2207/15498768.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/configmgr/hotfix/2207/15498768.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @bhuney
* Microsoft Alias: **brianhun**

**Comment by bhuney** [comment]
#please-close
