### ISSUE TITLE
Android AOSP devices - hardware support

### ISSUE THREAD

**Issue by garyjkane** [MicrosoftDocs/memdocs#3156]
The prerequisites mention 

RealWear devices, updated to Firmware 11.2 or later.

Does this article only apply to those devices or all android AOSP devices? For example can we Intune enroll android devices which are running on other hardware, such as raspberry pi for example. 

Thanks
Gary

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fd3be747-2a3b-4ccd-b063-3ac21a25b65d
* Version Independent ID: fd3be747-2a3b-4ccd-b063-3ac21a25b65d
* Content: [Set up Android (AOSP) device management in Intune for corporate-owned userless devices - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/enrollment/android-aosp-corporate-owned-userless-enroll)
* Content Source: [memdocs/intune/enrollment/android-aosp-corporate-owned-userless-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/android-aosp-corporate-owned-userless-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @garyjkane, thanks for reaching out to the Microsoft Intune Docs team with your question. This doc is specifically for RealWear devices. Today, Microsoft Intune only supports AOSP device management for RealWear devices.
