### ISSUE TITLE
ConfigMgr does not allow Windows to update offline licensed app from the Store

### ISSUE THREAD

**Issue by codaamok** [MicrosoftDocs/memdocs#316]
May the below sentence be reviewed, please?

> When provisioning an offline licensed app, Configuration Manager doesn't allow Windows to automatically update it from the Microsoft Store.

I've just installed an appx via an Application and the Store updated it successfully. 

I feel like, [from reading this](https://docs.microsoft.com/en-us/mem/configmgr/apps/deploy-use/manage-apps-from-the-windows-store-for-business#next-steps), that the advice should be similar to this sentence:

> When deploying offline apps to Windows 10 devices with the Configuration Manager client, don't allow users to update applications external to Configuration Manager deployments. Control of updates to offline apps is especially important in multi-user environments such as classrooms. One option to disable the Microsoft Store is by using group policy.

It seems the client doesn't explicitly deny or deny any update action itself. In my testing this was at least true for installing an `.appx` Language Experience Pack.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c2002db-11a5-1cfb-be16-8881d6878b94
* Version Independent ID: 5f30f42b-bfb5-2e07-6080-284cd3d67354
* Content: [Create Windows applications - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/apps/get-started/creating-windows-applications#bkmk_provision)
* Content Source: [memdocs/configmgr/apps/get-started/creating-windows-applications.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/apps/get-started/creating-windows-applications.md)
* Product: **configuration-manager**
* Technology: **configmgr-app**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @codaamok for the feedback. I revised this article a while back and added that section at the end. I obviously just missed that other bit further up. I'll fix it now.
