### ISSUE TITLE
Conflicting information regarding browsing to NDES page with intune connector installed

### ISSUE THREAD

**Issue by cjohnston-hill** [MicrosoftDocs/memdocs#3165]
Under the heading [Configure the NDES Service](https://learn.microsoft.com/en-us/mem/intune/protect/certificates-scep-configure#configure-the-ndes-service) Step 4 shows "Browse to http://Server_FQDN/certsrv/mscep/mscep.dll. You should see an NDES page similar to the following image: and shows an image of the NDES config page. 

However this contradicts the information at https://learn.microsoft.com/en-us/troubleshoot/mem/intune/troubleshoot-scep-certificate-device-to-ndes#test-and-troubleshoot-the-scep-server-url - Which states that if the Intune Connector is working that you should get a 403 page if everything is working correctly.

What's the correct outcome?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c9107185-e6c7-b178-4e22-819797fe4880
* Version Independent ID: 1153b441-94f0-b471-52a2-3cf556c68581
* Content: [Configure infrastructure to support SCEP certificate profiles with Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/certificates-scep-configure#create-the-scep-certificate-template)
* Content Source: [memdocs/intune/protect/certificates-scep-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/certificates-scep-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@cjohnston-hill Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3190

once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@cjohnston-hill Closing the issue as per the author's comment in PR. Thanks
