### ISSUE TITLE
Add RSS feed

### ISSUE THREAD

**Issue by sympleconfigmgr** [MicrosoftDocs/memdocs#3169]
Please update this doc with a RSS feed, similar to the M365/Office page so customers can keep boundary devices up to date automatically

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0da01c49-7e99-aa7f-10e3-b2dc571e63cd
* Version Independent ID: 75a28ebe-c2df-e87f-e49d-c1c09d738c8d
* Content: [Network requirements for Windows 365](https://learn.microsoft.com/en-us/windows-365/enterprise/requirements-network)
* Content Source: [windows-365/enterprise/requirements-network.md](https://github.com/MicrosoftDocs/memdocs/blob/main/windows-365/enterprise/requirements-network.md)
* Service: **cloudpc**
* Sub-service: ****
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Unfortunately, our doc publish system doesn't fully support RSS.
