### ISSUE TITLE
Step 6. Delete the following files on the device if they exist

### ISSUE THREAD

**Issue by dan-snelson** [MicrosoftDocs/memdocs#317]
[Cause 6](https://docs.microsoft.com/en-us/mem/intune/protect/troubleshoot-jamf#cause-6)
Step 6. Delete the following files on the device if they exist:

Please carefully review this list for accuracy:
- The fourth bullet has an unintended line break
- Many files are actually in the **user** context
- /Users/{USERNAME MISSING}/Library/…

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 953344ed-f631-a20b-c38a-9eb31c96b1e9
* Version Independent ID: 3937361d-d0b2-6619-521e-894acb94e6cf
* Content: [Troubleshooting Jamf Pro integration with Microsoft Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/troubleshoot-jamf)
* Content Source: [memdocs/intune/protect/troubleshoot-jamf.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/troubleshoot-jamf.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@dan-snelson  Thanks for this feedback Dan. I don't have access to a this configuration directly, so I'd like to ensure I understand what your commenting on, so we can get this correct.  
- The line break in the fourth bullet point seems clear to fix based on standard software paths, and the following entry in that list.  
- Your second and third bullet points are not clear to me. Are those related to each other? 

I believe what your suggesting is where the /User/ path is invoked, we also need to call out the 'user name' in the path (between /Users/ and /Library/.  It looks as if a mistake for this article was made in the markdown, to not 'escape' the leading character of what would have been \<username>.  That is why two // appear in that path, without the username being noted.

That's and easy fix, but I want to ensure I understand your feedback, and don't gloss over something else of importance.

**Comment by Brenduns** [comment]
@dan-snelson I've submitted a fix that will be live later tonight. This will fix both the split line, and adds the *username* to the path of the other entries where it wasn't successfully published before.  Should there be more that I'm not aware of, let me know, and I'll submit further fixes.  Thanks!
