### ISSUE TITLE
Clarify Fresh Start is not Supported for Hybrid Devices

### ISSUE THREAD

**Issue by yeadubs** [MicrosoftDocs/memdocs#3173]
I have a support ticket open and they referenced this document regarding "Fresh Start" not being supported for hybrid devices.

This document only references Autopilot Reset and further clarification should be added regarding Fresh Start.

There should also be a document regarding the supported methods to reset/re-enroll a Windows 10 hybrid device to a new user.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8411fd84-8a1d-28e6-1535-30143be7ede2
* Version Independent ID: 4e5ecbe1-aa9b-cfa0-7b67-1ac1dcb0c465
* Content: [Windows Autopilot Reset](https://learn.microsoft.com/en-us/mem/autopilot/windows-autopilot-reset)
* Content Source: [memdocs/autopilot/windows-autopilot-reset.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/windows-autopilot-reset.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by frankroj** [comment]
Thank you for the feedback @yeadubs. This Autopilot article is specific about the Autopilot Reset scenario of Autopilot. This is different from Fresh Start, which isn't part of Autopilot. To further clarify, although Intune can utilize Autopilot, Autopilot isn't part of Intune. Fresh Start is an Intune feature which is covered in the following article:

https://learn.microsoft.com/mem/intune/remote-actions/device-fresh-start

If you don't find the information you are looking for at the above article, please provide feedback at the above article.

I hope this fully clarifies your question.

**Comment by yeadubs** [comment]
Thank you for the clarification.  The confusion with reading the article 7 months ago stems from devices which are Hybrid Azure AD joined and which method should be used to "reset" the device.  The articles Microsoft Support referenced were contradictory to each other (regarding Fresh Start and Autopilot Reset) as the supported method to reset a device depend on the join type.  These unsupported options are available for Hybrid AAD Joined devices in Intune which makes it extremely difficult to understand what methods should be used.
