### ISSUE TITLE
Changes to Company Portal And ADE.

### ISSUE THREAD

**Issue by Coopem16** [MicrosoftDocs/memdocs#3175]
With the changes coming to the Company portal:
https://techcommunity.microsoft.com/t5/intune-customer-success/upcoming-changes-to-ios-ipados-company-portal-app-deployment-for/ba-p/3627761
Will this document be updated. There are many questions around how to deploy going forward. 
When will this Document be updated to reflect these changes. We have to be prepared and plan out our new deployment, 
What does this change mean to my current devices. will a App config need to be deployed to all devices or just new devices after this change? 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ee33d638-3024-87d5-1b02-c4568478d1ce
* Version Independent ID: fe0f2aa3-b2dc-486a-4883-9c25ee361fe8
* Content: [Add app configuration policies for managed iOS/iPadOS devices - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/apps/app-configuration-policies-use-ios#configure-the-company-portal-app-to-support-ios-and-ipados-devices-enrolled-with-automated-device-enrollment)
* Content Source: [memdocs/intune/apps/app-configuration-policies-use-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/app-configuration-policies-use-ios.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@Coopem16 Thank you for your feedback. Yes, the changes will be made by the author/PG to the document as we go live with the changes to iOS/iPadOS Company Portal app deployment. The answers regarding whether this needs to be deployed to all devices will also be provided once we are close to going live with the changes.

If there are any specific questions regarding this feature, you could direct post on the techcommunity forum -https://techcommunity.microsoft.com/t5/intune-customer-success/upcoming-changes-to-ios-ipados-company-portal-app-deployment-for/ba-p/3627761  and our product group will be able to respond.

@yogkumgit  No changes are required as of now.

Thanks
Sri
