### ISSUE TITLE
Clarity for Pre-Requisites

### ISSUE THREAD

**Issue by almor1331** [MicrosoftDocs/memdocs#3176]
I am working with a customer that is inquiring about the pre-reqs:
- Activate "Windows Health Monitoring" via Intune
- Have "Update Health Tools" installed

They are wondering why there are dependencies on these specific pre-reqs.  Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4e6d726f-bd44-d168-0af5-c0fe73e06eb9
* Version Independent ID: a87f06b1-f284-42db-a5ed-2cba46bdf2b9
* Content: [Use Intune to expedite Windows quality updates](https://learn.microsoft.com/en-us/mem/intune/protect/windows-10-expedite-updates)
* Content Source: [memdocs/intune/protect/windows-10-expedite-updates.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/windows-10-expedite-updates.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@almor1331 Thank you for your feedback.

**Windows Health Monitoring** - This is a pre-requisite as  Microsoft can collect event data, and provide recommendations to improve performance on your Windows devices. [Endpoint Analytics](https://learn.microsoft.com/en-us/mem/analytics/overview) analyzes this data and can recommend software, help improve startup performance, and fix common support issues.

**Update Health Tools** - have you noticed that sometimes the Windows Update takes a lot longer? The computer also seems stuck while installing the update during a restart. This has been fixed using Microsoft Update Health Tools.

We have noticed that there are multiple issues with speeding up quality updates without these two enabled.

Hope this helps!

Thanks
Sri
