### ISSUE TITLE
The message function of Remote Help only supports single byte characters as the current limit.

### ISSUE THREAD

**Issue by Satoshi-Mori** [MicrosoftDocs/memdocs#3179]
[Enter feedback here]
The message function of Remote Help only supports single byte characters as the current limit.
Although Remote Help states that it supports the following languages, it should be noted that the current version of the Message feature does not support double byte characters.

Languages Supported 
https://learn.microsoft.com/en-us/mem/intune/remote-actions/remote-help#languages-supported
Remote help is supported in the following languages:

Czech
Danish
Dutch
English
Finnish
French
German
Greek
Hungarian
Italian
Japanese
Korean
Norwegian
Polish
Portuguese (Portugal)
Romanian
Russian
Spanish
Swedish
Turkish

e.g
Note:
The message function of Remote Help only supports single byte characters as the current limit.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6bc62c89-a452-0d3f-01f3-c5982803809e
* Version Independent ID: 6bc62c89-a452-0d3f-01f3-c5982803809e
* Content: [Remotely assist users that are authenticated by your organization.](https://learn.microsoft.com/en-us/mem/intune/remote-actions/remote-help?source=docs#languages-supported)
* Content Source: [memdocs/intune/remote-actions/remote-help.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/remote-help.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@Satoshi-Mori Thank you for your feedback. We have made changes to the document via pR#https://github.com/MicrosoftDocs/memdocs/pull/3191

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by msbemba** [comment]
@jerryabo we are waiting for author to approve and merge. Will update you once that is complete.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Satoshi-Mori Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Satoshi-Mori** [comment]
Thank you for your cooperation.
