### ISSUE TITLE
Approve - https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/manage-clients#approve

### ISSUE THREAD

**Issue by albozadz** [MicrosoftDocs/memdocs#318]
https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/manage-clients#approve

We should include also a clarification that AADJ devices are also automatically approved. I have been asked by customers for confirmation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f07d7995-e1f4-7c01-44de-49ebace42397
* Version Independent ID: 6e06c4c6-bb87-91aa-d2cf-2ec3ac02a238
* Content: [Manage clients - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/manage-clients#approve)
* Content Source: [memdocs/configmgr/core/clients/manage/manage-clients.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/manage-clients.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @albozadz for the feedback. I'll change that now.
