### ISSUE TITLE
10 ANC - Increase?

### ISSUE THREAD

**Issue by mundayn** [MicrosoftDocs/memdocs#3187]
"You can have up to 10 ANCs per tenant."

Do you know if this limit will be increased?

For security reasons if we have 20 different departments using Cloud PCs, we may want to have different subnets (So 20 different ANCs) so they can only access certain resources depending on the subnet they are in.

This way we can build Firewall rules based on department/subnet, without this we would have to make a more general ANC.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bce94c37-8191-57d5-1c9d-c8782e7d9b2a
* Version Independent ID: bce94c37-8191-57d5-1c9d-c8782e7d9b2a
* Content: [Create Azure network connections for Windows 365](https://learn.microsoft.com/en-us/windows-365/enterprise/create-azure-network-connection)
* Content Source: [windows-365/enterprise/create-azure-network-connection.md](https://github.com/MicrosoftDocs/memdocs/blob/main/windows-365/enterprise/create-azure-network-connection.md)
* Service: **cloudpc**
* Sub-service: ****
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by msbemba** [comment]
@mundayn Thank you for your feedback. We do not have information on whether the limit will increase. However, you can directly post questions on the main feedback portal (https://feedbackportal.microsoft.com/ ) so that a product engineer will be able to review and provide you with more information.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@mundayn  Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
