### ISSUE TITLE
Work Profile Only

### ISSUE THREAD

**Issue by Leon1983** [MicrosoftDocs/memdocs#319]
[Enter feedback here]

I believe the description "Work Profile Only" https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-android-for-work#work-profile-only is incorrect and not in line with the standards defined by Google https://developers.google.com/android/work/terminology#profile_owner_po 
It should read "Profile Owner" as the term describes the way in which the DPC has access to the device.

Note this also needs to be changed within the MEM Admin center interface

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 900e72be-d42b-49ba-f304-602df23cbb04
* Version Independent ID: 2ce5c45d-15be-d316-1c57-92bea37358e0
* Content: [Android Enterprise device settings in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-android-for-work)
* Content Source: [memdocs/intune/configuration/device-restrictions-android-for-work.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/device-restrictions-android-for-work.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by Leon1983** [comment]
Note that I have already submitted a Uservoice for changing the MEM Admin center interface https://microsoftintune.uservoice.com/forums/291681-ideas/suggestions/40203871-android-enterprise-configuration-profile-separatio

**Comment by illuvtar** [comment]
**profile owner** refers to the DPC while **work profile** refers to the self-contained profile on the device https://developers.google.com/android/work/terminology#work_profile, Checking solution sets also shows Googles use of work profile; https://developers.google.com/android/work/requirements/work-profile.
I believe the documentation is correct.

**Comment by Leon1983** [comment]
By my point is you are having two titles in the interface that mean different things, its is confusing. As in you have "Profile Owner" for the Fully Managed and Dedicated settings then "Work Profile". So one title for the settings describes a DPC mode and the other a solution set? Just a thought but I personally think its confusing

**Comment by illuvtar** [comment]
Yes it is confusing and needs to be aligned with Googles terminology. i.e. **device owner** should read **fully managed device** https://developers.google.com/android/work/terminology#fully_managed_device, this would become more of an issue if the setup DPC supported **fully managed device with a work profile** (formerly COPE)

**Comment by Leon1983** [comment]
I see there are two solutions here;

1. Rename **Work Profile** to **Profile Owner**
or
2. Rename **Device Owner** to **Fully Managed and Dedicated** because you need to take into consideration the two Solution sets supported in Device Owner mode within Intune

**Comment by MandiOhlinger** [comment]
@all These setting articles mimic the UI. We can add info to explain what "Work profile" and "Device owner" mean using Google's terms. Thoughts? What's your recommended text? 

We can update the following articles:

- [Device restrictions](https://docs.microsoft.com/mem/intune/configuration/device-restrictions-android-for-work)
- [VPN](https://docs.microsoft.com/mem/intune/configuration/vpn-settings-android-enterprise)
- [Wi-Fi](https://docs.microsoft.com/mem/intune/configuration/wi-fi-settings-android-enterprise)

**Comment by MandiOhlinger** [comment]
Closing this GitHub issue. 

We want and encourage community contributions to help make our docs better. So, if you have recommended text, please create a pull request with your recommended changes. Steps at [https://github.com/MicrosoftDocs/memdocs](https://github.com/MicrosoftDocs/memdocs) (scroll past the folder view). We review every PR before the changes go live, so know that we got your back.
