### ISSUE TITLE
Line 16 screenshot shows only one API permission, but we are giving two permissions with Admin consent.

### ISSUE THREAD

**Issue by rajinfosec** [MicrosoftDocs/memdocs#3196]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 54745d43-7151-b13a-57f6-7329856e5d2b
* Version Independent ID: 07d2ffd1-49b6-3046-cc07-a4aa35e4fe61
* Content: [Manually configure Jamf Pro Integration with Microsoft Intune - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/conditional-access-integrate-jamf)
* Content Source: [memdocs/intune/protect/conditional-access-integrate-jamf.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/conditional-access-integrate-jamf.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@rajinfosec Thank you for your feedback. We have made changes to the screenshot via PR#https://github.com/MicrosoftDocs/memdocs/pull/3283

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @rajinfosec Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
