### ISSUE TITLE
Remote Help is not available on GCC

### ISSUE THREAD

**Issue by Josh-Duncan** [MicrosoftDocs/memdocs#3199]
It looks like the documentation was updated to state that remote help is only not available on GCCH or DOD.  That is not accurate.  Remote help is not available on GCC, GCCH, or DOD.

The update should be reverted.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6bc62c89-a452-0d3f-01f3-c5982803809e
* Version Independent ID: 6bc62c89-a452-0d3f-01f3-c5982803809e
* Content: [Remotely assist users that are authenticated by your organization.](https://learn.microsoft.com/en-us/mem/intune/remote-actions/remote-help)
* Content Source: [memdocs/intune/remote-actions/remote-help.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/remote-help.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@Josh-Duncan Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3233

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@Josh-Duncan Closing as per Author's comment.
 this item has been addressed in https://github.com/MicrosoftDocs/memdocs-pr/pull/9036
