### ISSUE TITLE
COPE mode

### ISSUE THREAD

**Issue by shareef1273** [MicrosoftDocs/memdocs#32]
Any plans to introduce COPE support? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d16c28db-1e8e-31fa-6127-3050a2940422
* Version Independent ID: 4cf9a244-1ae5-1637-48f7-3f503d400da6
* Content: [What's new in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new#week-of-march-9-2020)
* Content Source: [memdocs/intune/fundamentals/whats-new.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/whats-new.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@shareef1273 We have not announced COPE support. If and when we support it, we'll announce it here and earlier on the [In Development page](https://docs.microsoft.com/en-us/mem/intune/fundamentals/in-development).
