### ISSUE TITLE
Requirements section.

### ISSUE THREAD

**Issue by samuelleung83** [MicrosoftDocs/memdocs#320]
Could the first dot point under 'Requirements' please be expanded to say

**- An Azure subscription to host the CMG. (CMG currently does NOT support CSP provided Azure Subscriptions)**

Although this is mentioned earlier in the document. Many people refer or are directed to the Requirements anchored section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07d4e4f7-68ed-e604-b577-2c18617d1c2e
* Version Independent ID: 1ce10bc0-2a6d-405a-a9ae-46adfaac8fe6
* Content: [Plan for cloud management gateway - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/plan-cloud-management-gateway)
* Content Source: [memdocs/configmgr/core/clients/manage/cmg/plan-cloud-management-gateway.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/cmg/plan-cloud-management-gateway.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @samuelleung83 for the feedback. I have some other updates to make to this article soon, so will include it.
