### ISSUE TITLE
"Convert all targeted devices to Autopilot" wording

### ISSUE THREAD

**Issue by ChadSimmons** [MicrosoftDocs/memdocs#3200]
In the Intune console / Microsoft Endpoint Manager admin center and in the several docs including

- Configure Autopilot profiles [web](https://learn.microsoft.com/en-us/mem/autopilot/profiles#create-an-autopilot-deployment-profile) [doc](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/profiles.md)
- Automatic registration of existing devices [web](https://learn.microsoft.com/en-us/mem/autopilot/automatic-registration) [doc](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/automatic-registration.md)
- Windows Autopilot deployment for existing devices [web](https://learn.microsoft.com/en-us/mem/autopilot/existing-devices) [doc](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/existing-devices.md)

the process of registering a Windows device with the Autopilot deployment service is described as **_convert_**ing.

This is confusing as nothing actually happens to the device.  The word **_convert_** also leads to confusion in that it somehow transforms a hybrid Azure AD device into a Azure AD Autopilot device as referenced in issues #2175, #2181, #2872, and #3082.

If the wording in the console/admin center and documentation were simply updated to say **_Register_ all targeted devices in Autopilot** I believe the confusion would disappear.

**Comment by frankroj** [comment]
Thank you for the feedback @ChadSimmons. I apologize for the long time it took to respond back to this feedback item. You are correct and the wording was confusing. We changed the wording to say registering instead of converting a couple months back. I hope it makes more sense now.
