### ISSUE TITLE
Ambiguous Wording

### ISSUE THREAD

**Issue by sedatesoftware** [MicrosoftDocs/memdocs#3205]
There is a Note embedded in the page which reads "Converting all targeted devices to Autopilot isn't supported for transforming a hybrid Azure AD device into a Azure AD Autopilot device."
However, it is not clear if it means:
1) a Hybrid AD Joined device cannot be converted to an Azure AD Joined device;
2) a Hybrid AD Joined device cannot be converted/migrated to an Windows Autopilot device, even staying as a Hybrid AD device.

While I have no expectations of the former option, the latter indicates that the device must deleted from Azure AD and be re-imaged to OEM, if Autopilot is desired/required.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aac6aa29-d930-773f-7b54-9467aaca5378
* Version Independent ID: b89a8390-faee-2a23-e435-bf36e5597b63
* Content: [Automatic registration of existing devices - Windows Autopilot](https://learn.microsoft.com/en-us/mem/autopilot/automatic-registration)
* Content Source: [memdocs/autopilot/automatic-registration.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/automatic-registration.md)
* Product: **w10**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by frankroj** [comment]
@sedatesoftware We recently updated the wording in this note. Please let me know if the new wording clarifies your questions or if you need further clarification.

**Comment by frankroj** [comment]
Fixed with PR https://github.com/MicrosoftDocs/memdocs-pr/pull/10144
