### ISSUE TITLE
There is only 1 baseline version (2110 - Oct 2021) available

### ISSUE THREAD

**Issue by kmsft** [MicrosoftDocs/memdocs#3212]
2110 (Oct 2010) should be the only baseline that exists for W365, as W365 GA'ed in Aug 2021.   There should be no 2101 (Jan 2021) version

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a8abba3e-b29f-3066-d8d5-778cdb2931ae
* Version Independent ID: a8abba3e-b29f-3066-d8d5-778cdb2931ae
* Content: [Settings list for the Windows 365 Cloud PC security baseline in Intune - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/security-baseline-settings-windows-365)
* Content Source: [memdocs/intune/protect/security-baseline-settings-windows-365.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/security-baseline-settings-windows-365.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@kmsft thank you for your feedback. We have made changes to the document via pR#https://github.com/MicrosoftDocs/memdocs/pull/3236

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @kmsft Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
