### ISSUE TITLE
Re-using the same managed google account not possible?

### ISSUE THREAD

**Issue by Emmity** [MicrosoftDocs/memdocs#322]
We had an active Intune tenant that had the Managed Google Play linked. The tenant was without licenses for couple of months and the whole Intune was emptied from settings.. that's fine, but now we are re-configuring the Intune and I try to link the SAME Managed Google Play accounted to the SAME Intune tenant: The Google's page asks for the account, and after that just says "You have already signed up with this enterprise.".. Yeah, I know, but how do I RE-SIGN it?

Is it possible to use the same Google Play account AGAIN? If so, please add instructions. If not, please add this info, explanation why not possible, and perhaps instruct to create a new Managed Google Play account, if that is the preferred solution? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9f750b6-7e0f-bd67-69b5-44f081f2afd6
* Version Independent ID: 8b3ba988-1184-82be-f35e-d161a199a305
* Content: [Connect your Intune account to your Managed Google Play account. - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/connect-intune-android-enterprise)
* Content Source: [memdocs/intune/enrollment/connect-intune-android-enterprise.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/connect-intune-android-enterprise.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@Emmity Thanks for taking the time to share this with the Intune documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a few options available to provide the fastest level of support for this:   
- Post on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.   
- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support. This option will also get the issue into support's queue for possible escalation to the doc team for doc changes.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.   
I'm closing this issue as there's nothing actionable for docs at this time.
