### ISSUE TITLE
September Date is Incorrect

### ISSUE THREAD

**Issue by fierylevi** [MicrosoftDocs/memdocs#3222]
Hi, 
This is a note to the author that the September 21, 2022 date entry incorrectly states the year as 2202. Please update the page to reflect the correct year. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f8cd9e78-0ae6-c0e4-f318-1e5a6ec816fc
* Version Independent ID: f50ddc5d-311a-5810-3361-4160b5bc5f4b
* Content: [Overview of Certificate Connector for Microsoft Intune - Azure](https://learn.microsoft.com/en-us/mem/intune/protect/certificate-connector-overview)
* Content Source: [memdocs/intune/protect/certificate-connector-overview.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/certificate-connector-overview.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@fierylevi Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3229

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @fierylevi Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
