### ISSUE TITLE
Incorrect options for Detect Potentially Unwanted Applications

### ISSUE THREAD

**Issue by WillsOG** [MicrosoftDocs/memdocs#323]
[Enter feedback here]
The options in the dropdown in Intune Device Restrictions are "Off, Enable, and Audit". The documentation list "Block and Audit". I think the documentation needs to be updated to reflect the actual options in Intune.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7874ff8b-727f-b013-27f8-fd714ebb53a5
* Version Independent ID: 05674b42-613e-d54d-2895-1f2db41b613a
* Content: [Device restriction settings for Windows 10 in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-windows-10#windows-defender-antivirus)
* Content Source: [memdocs/intune/configuration/device-restrictions-windows-10.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/device-restrictions-windows-10.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@WillsOG Thank you. We updated the options, and the changes should be live later today. In the future, it'd be great if you created a pull request when you see things like this. We certainly appreciate the help.
