### ISSUE TITLE
Unnecessary step 5 in "upload the converted VHD to Azure"

### ISSUE THREAD

**Issue by kmsft** [MicrosoftDocs/memdocs#3239]
I think Step 5 under **Upload the converted VHD to Azure** is actually optional.  On other pages the instructions are to create a Managed Image, which does not involve Azure Compute Gallery.  https://learn.microsoft.com/en-us/windows-365/enterprise/device-images.

I will ping PM also

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b8e11d78-e1dc-4716-e49f-b58a619e9d78
* Version Independent ID: c73e2ec1-1a7e-d52a-0ceb-399e3f31b512
* Content: [Convert custom device images to generation 2 virtual machines in Windows 365](https://learn.microsoft.com/en-us/windows-365/enterprise/device-images-convert-generation-2)
* Content Source: [windows-365/enterprise/device-images-convert-generation-2.md](https://github.com/MicrosoftDocs/memdocs/blob/main/windows-365/enterprise/device-images-convert-generation-2.md)
* Service: **cloudpc**
* Sub-service: ****
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Yes, this is optional. That's why the verb "can" is used instead of "must". To be clear, I'll add [Optiona] to the step.
