### ISSUE TITLE
Request for revision of Autopilot device group creation procedure

### ISSUE THREAD

**Issue by buhibu9** [MicrosoftDocs/memdocs#324]
[Enter feedback here]
https://docs.microsoft.com/ja-jp/mem/intune/enrollment/enrollment-autopilot#create-an-autopilot-device-group

Please revise the procedure described in the above section and the operation on the GUI are not synchronized.

https://endpoint.microsoft.com/?l=ja.ja-jp#blade/Microsoft_AAD_IAM/GroupsManagementMenuBlade/AllGroups

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0789d275-5672-266c-9394-380b0af2dac3
* Version Independent ID: 41f03a3b-e3ac-f779-3857-49659cbd3d3f
* Content: [Enroll devices using Windows Autopilot - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/enrollment-autopilot#create-an-autopilot-device-group)
* Content Source: [memdocs/intune/enrollment/enrollment-autopilot.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/enrollment-autopilot.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by MandiOhlinger** [comment]
@buhibu9 Thank you for letting us know about this. The article is updated with the latest steps. The changes should be live later today. 

If you see other articles that need updated, it'd be great if you created a pull request (PR) with your recommended changes. We review the PRs before they're published. We want and encourage community contributions. Something to consider for next time.

Thanks again.
