### ISSUE TITLE
Really need to be able to bypass device with filters with Conditional Access

### ISSUE THREAD

**Issue by cashxx** [MicrosoftDocs/memdocs#3242]
We have 12 Shared Device iPads that we need to use Teams with but users are locked down with CA policies.  But we need these devices able to be used in classrooms with Teams.  Only way I can find to get it to work is to bypass the CA per the devices but isn't supported.  If I put my self in and bypass per user it works, but I can't do that per user.  Needs to be per device.

From the note on the webpage that is highlighted as important:
Conditional Access conditions that use filters for devices.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bc1b101e-c3df-3d36-8b2a-d9a0e5586a27
* Version Independent ID: a6d21c24-21b7-63e4-f5c9-eec2f1c56e50
* Content: [Shared iOS and iPadOS devices - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-shared-ios)
* Content Source: [memdocs/intune/enrollment/device-enrollment-shared-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/device-enrollment-shared-ios.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@cashxx Thank you for your feedback. You are correct, Conditional Access conditions that use filters for devices are not supported. You can provide the feedback on our main feedback portal (https://feedbackportal.microsoft.com/)  so that our dev /product team members will be able to provide more information.

Hope this helps!

Thanks
Sri
