### ISSUE TITLE
Configure client settings misleading

### ISSUE THREAD

**Issue by nhogarth86** [MicrosoftDocs/memdocs#325]
The configure client settings part about registering the devices is misleading. It sounds like by selecting the box to automatically register the devices, it is joining the devices to Azure AD. It is registering the devices (which is what the option says), this enables Hybrid Azure AD Join. The devices are not joined to Azure AD as they will be Hybrid Azure AD Joined (joined to AD + registered in Azure AD). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 537cf5a4-8072-7332-e579-35394ecda457
* Version Independent ID: 03ec8ffa-d42c-f3d6-cedb-0deedc6606ba
* Content: [Install the client with Azure AD - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/deploy/deploy-clients-cmg-azure#configure-client-settings)
* Content Source: [memdocs/configmgr/core/clients/deploy/deploy-clients-cmg-azure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/deploy/deploy-clients-cmg-azure.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks Nick for the feedback! I double-checked a few things, and think you're right on this. I also think there are a few other places that we incorrectly refer to hybrid as joined to both AD & AAD. I'll fix those, and add some references to supporting docs from Azure AD folks:

- [Hybrid Azure AD joined devices](https://docs.microsoft.com/azure/active-directory/devices/concept-azure-ad-join-hybrid): "These devices are... joined to your on-premises Active Directory and registered with your Azure Active Directory."
- [dsregcmd command - device state](https://docs.microsoft.com/azure/active-directory/devices/troubleshoot-device-dsregcmd)
