### ISSUE TITLE
[If "Automatic app update" is set to "No", whether or not the Company Portal app can be updated manually.

### ISSUE THREAD

**Issue by Ikuko-Konno** [MicrosoftDocs/memdocs#3252]
This public information explains that Company Portal app can be updated manually even if the Automatic app update on the VPP token is set to "No". 

----------
To enable automatic app updates for Company Portal, go to your app token settings in the admin center and change Automatic app updates to Yes. See Upload an Apple VPP or Apple Business Manager location token for the steps to access your token settings. If you don't enable automatic updates, the device user will need to manually check for them on their own.
----------

In fact, however, we have received many inquiries from customers who are unable to manually update their Company Portal app when "Automatic app update" is set to "No.
Therefore, I believe this public information statement is incorrect.
If you are sure, we would like you to describe the prerequisites and procedures for manually updating the Company Portal app if the [Automatic app update] is [No].
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd130267-c54b-41e3-d534-831d4a86bae6
* Version Independent ID: bdfa7eca-a356-3dde-7643-9a759f952007
* Content: [Enroll iOS/iPadOS devices by using ADE - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-ios)
* Content Source: [memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@Ikuko-Konno Thank you for your feedback. From the information received from PMs the author has updated the document to state that " If you don't enable automatic updates, the device user will need to manually check for them on their own".  the steps to check for updates manually is available here-  https://learn.microsoft.com/en-us/mem/intune/user-help/install-a-new-version-of-the-company-portal-app

if you continue to face this issue, I'd recommend opening a support ticket-> product bug via the need help section on the admin center. Once you do that a support engineer will work with you to resolve or raise a bug.

Hope this helps

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Ikuko-Konno Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
