### ISSUE TITLE
Add info on LTSB definition changing to LTSC

### ISSUE THREAD

**Issue by samuelleung83** [MicrosoftDocs/memdocs#326]
Where it mentions LTSB in this article, is it worth updating it with a note about LTSC?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f3023a8-ab6c-1d77-0111-77cc7583347c
* Version Independent ID: 26debf60-c3c1-caa6-7f78-a04a8b8e73af
* Content: [Product and licensing FAQ - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/understand/product-and-licensing-faq)
* Content Source: [memdocs/configmgr/core/understand/product-and-licensing-faq.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/understand/product-and-licensing-faq.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @samuelleung83, thanks for the feedback! In this instance, all references are to the Configuration Manager long-term servicing branch, which was a one-time thing with version 1606. There's no channel for it like with Windows 10; there's no LTS _C_ of ConfigMgr.
