### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by sagaransal** [MicrosoftDocs/memdocs#3262]
Intune App package have dependency on msalsdk-dbusclient and that depends on libsdbus-c++0 (>= 0.8.3) and is not installable on Ubuntu 22.04 LTS

![image](https://user-images.githubusercontent.com/12928861/195964006-fa6440c8-fc6f-45b5-8d60-0a6d3ea0d8b2.png)

**Comment by benferse** [comment]
@sagaransal Thanks for the report - we're looking into fixing this. In the meantime, there's a workaround in #3270 that you could try to use the correct repo for 22.04. You may need to remove the 20.04 repo first:

```bash
$ sudo rm /etc/apt/sources.list.d/microsoft-ubuntu-focal-prod.list
$ sudo apt-get update
```

**Comment by dtjn** [comment]
Works for me with the updated instructions from https://learn.microsoft.com/en-us/mem/intune/user-help/microsoft-intune-app-linux after removing the 20.04 repo first. Thanks @benferse !

**Comment by gwynbleide** [comment]
Had the same issue. If you setup 20.04 repo it will not work as described. Cheers @benferse .

**Comment by lenewsad** [comment]
Hi @sagaransal, thanks again for reaching out to the Microsoft Intune docs team and bringing this to our attention. We updated the article with the correct command for Ubuntu 22.04 LTS: [Get the Microsoft Intune app for Linux](https://learn.microsoft.com/mem/intune/user-help/microsoft-intune-app-linux#install-intune-app)     

For anyone that's having problems after using the commands for version 20.04:  
1. Remove the 20.04 repo:  
    `$ sudo rm /etc/apt/sources.list.d/microsoft-ubuntu-focal-prod.list`  
     `$ sudo apt-get update`
2. Install the Microsoft package signing key again using the 22.04 commands.

**Comment by lenewsad** [comment]
Hi @thrdgeek, thanks for reaching out to the Microsoft Intune Docs team; I am reaching out to the product team to see if the 20.04 instructions require updates.

**Comment by xebug** [comment]
@thrdgeek @lenewsad 
Solution for Ubuntu 20.04:
`wget http://security.ubuntu.com/ubuntu/pool/universe/s/sdbus-cpp/libsdbus-c++0_0.8.3-4~bpo20.04.1_amd64.deb
sudo apt install ./libsdbus-c++0_0.8.3-4~bpo20.04.1_amd64.deb
wget https://packages.microsoft.com/ubuntu/20.04/prod/pool/main/m/msalsdk-dbusclient/msalsdk-dbusclient_1.0.0_amd64.deb
sudo apt install ./msalsdk-dbusclient_1.0.0_amd64.deb
sudo apt install intune-portal`

**Comment by anhnguyen1996** [comment]
@xebug 

It work for me. Thanks!

**Comment by benferse** [comment]
@thrdgeek @xebug Do you have the `focal-backports` repository disabled in your apt config? In 20.04 the [libsdbus-c++0](https://packages.ubuntu.com/focal-backports/libsdbus-c++0) package is available in backports, which is enabled by default, but it can be disabled which would trigger the missing dependency you noted.

**Comment by polatgo1** [comment]
If you're using 20.04, the doc from Microsoft doesn't install all required dependencies. Install all required libraries from "Requires" section in this link : https://ubuntu.pkgs.org/20.04/microsoft-prod-amd64/msalsdk-dbusclient_1.0.1_amd64.deb.html

**Comment by knutovesen-tietoevry-com** [comment]
On Ubuntu **22.04**.3 LTS this works for me: 
- download and install package: https://ubuntu.pkgs.org/22.04/ubuntu-universe-amd64/libsdbus-c++1_1.1.0-3_amd64.deb.html
- sudo apt install intune-portal
