### ISSUE TITLE
Please provide all dependencies to install intune-portal

### ISSUE THREAD

**Issue by benoithamet** [MicrosoftDocs/memdocs#3263]
Hi there

when you are trying to install intune-portal on Ubuntu there are quite few dependencies
please provide all dependencies and command to get them - I'm unable to get the libsdbus-c++0 one

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80924804-c247-d3bb-2245-fd3db3f3bd62
* Version Independent ID: 80924804-c247-d3bb-2245-fd3db3f3bd62
* Content: [Get the Microsoft Intune app for Linux](https://learn.microsoft.com/en-us/mem/intune/user-help/microsoft-intune-app-linux)
* Content Source: [memdocs/intune/user-help/microsoft-intune-app-linux.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/microsoft-intune-app-linux.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by benferse** [comment]
@benoithamet Were you trying to install on Ubuntu 22.04? There is a separate issue (#3270) that would result in unmet dependencies that I suspect you are running into.

**Comment by benoithamet** [comment]
Thanks Ben
I tried to use the updated repository but still having trouble to install libsdbus-c++0

~$ sudo apt install curl gpg
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
curl is already the newest version (7.81.0-1ubuntu1.4).
gpg is already the newest version (2.2.27-3ubuntu2.1).
The following package was automatically installed and is no longer required:
  systemd-hwe-hwdb
Use 'sudo apt autoremove' to remove it.
0 to upgrade, 0 to newly install, 0 to remove and 153 not to upgrade.
~$ curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   983  100   983    0     0   1972      0 --:--:-- --:--:-- --:--:--  1973
~$ sudo install -o root -g root -m 644 microsoft.gpg /usr/share/keyrings/
~$ sudo sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/ubuntu/22.04/prod jammy main" > /etc/apt/sources.list.d/microsoft-ubuntu-jammy-prod.list'
~$ sudo rm microsoft.gpg
~$ sudo apt update
Hit:1 http://au.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://au.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://au.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:5 https://packages.microsoft.com/repos/edge stable InRelease
Hit:6 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease
Hit:7 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
153 packages can be upgraded. Run 'apt list --upgradable' to see them.
~$ sudo apt install intune-portal
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
msalsdk-dbusclient : Depends: libsdbus-c++0 (>= 0.8.3) but it is not installable
E: Unable to correct problems, you have held broken packages.



***@***.***

**Comment by benoithamet** [comment]
and I tried on 20.04 too with the exact same issue
all dependencies are not installed (libssl, libsdbusc++)

**Comment by dtjn** [comment]
I am facing the same issue on a  22.04.1 test machine. I also was able to get the required libssl dependency libssl1.1 (seems like the current Ubuntu version ships with libssl3). But not luck on libsdbusc++0 >= 0.8.3 ...

**Comment by dtjn** [comment]
Ran into the same issue yesterday.

See https://github.com/MicrosoftDocs/memdocs/issues/3262 for the fix.

**Comment by benoithamet** [comment]
thanks @dtjn 
worked for me
@benferse worth adding a section 'Troubleshooting' covering this

**Comment by yogkumgit** [comment]
@lenewsad Please help us in resolving this issue. Thanks

**Comment by benoithamet** [comment]
one solution
https://github.com/MicrosoftDocs/memdocs/issues/3262

**Comment by lenewsad** [comment]
Hi @benoithamet, thank you for reaching out to the Intune docs team about this issue. I see that you found the solution in another issue: #3262. I'll post that info here for reference.  

We updated the article with the correct command for Ubuntu 22.04 LTS: [Get the Microsoft Intune app for Linux](https://learn.microsoft.com/mem/intune/user-help/microsoft-intune-app-linux#install-intune-app). 
For anyone that's having problems after using the command for version 20.04:  

1. Remove the 20.04 repo:  
    `$ sudo rm /etc/apt/sources.list.d/microsoft-ubuntu-focal-prod.list`
   `$ sudo apt-get update`
1. Install the Microsoft package signing key again using the 22.04 commands.
