### ISSUE TITLE
Multiple NDES server URLs handling

### ISSUE THREAD

**Issue by NickolajA** [MicrosoftDocs/memdocs#327]
In this section of the page:

---
SCEP Server URLs:

Enter one or more URLs for the NDES Servers that issue certificates via SCEP. For example, enter something like https://ndes.contoso.com/certsrv/mscep/mscep.dll. You can add additional SCEP URLs for load balancing as needed as URLs are randomly pushed to the device with the profile. If one of the SCEP servers isn't available, the SCEP request will fail and it's possible that on later device check-ins, the cert request could be made against the same server that is down.
---

Specifically the part stating "randomly pushed to the device" is incorrect as it indicates that Intune, not the client, is randomly selecting an URL. According to Lance Crandall, the following is the correct behavior:

"The entire NDES list is randomized and given to Windows Phone, Windows clients, and client will try them in order if the first fails."

I'd suggest that this page is updated to reflect the correct handling of the NDES server URLs when multiple entries are added to the configuration profile.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30c444f9-5cc4-7276-6882-d6b32ee453ea
* Version Independent ID: f1ec96ac-c890-2ed1-ede4-179de4b4e4cc
* Content: [Use SCEP certificate profiles with Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/certificates-profile-scep)
* Content Source: [memdocs/intune/protect/certificates-profile-scep.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certificates-profile-scep.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@NickolajA  I've gone ahead and updated that article. Thanks!
