### ISSUE TITLE
Wrong repository for Ubuntu 22.04

### ISSUE THREAD

**Issue by oya3un** [MicrosoftDocs/memdocs#3270]
The instructions on that page are only valid for Ubuntu 20.04 users. For those on 22.04, installation fails due to unmet dependencies. The correct repository for 22.04 needs to be set like this:

`$ sudo sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/ubuntu/22.04/prod jammy main" > /etc/apt/sources.list.d/microsoft-ubuntu-jammy-prod.list'
`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80924804-c247-d3bb-2245-fd3db3f3bd62
* Version Independent ID: 80924804-c247-d3bb-2245-fd3db3f3bd62
* Content: [Get the Microsoft Intune app for Linux](https://learn.microsoft.com/en-us/mem/intune/user-help/microsoft-intune-app-linux#feedback)
* Content Source: [memdocs/intune/user-help/microsoft-intune-app-linux.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/microsoft-intune-app-linux.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @oya3un, thank you for reaching out to the Microsoft Intune docs team. I updated the article with your contribution so it now shows the commands for each version.

**Comment by polatgo1** [comment]
If you're using 20.04, the doc from Microsoft doesn't install all required dependencies. Install all required libraries from "Requires" section in this link : https://ubuntu.pkgs.org/20.04/microsoft-prod-amd64/msalsdk-dbusclient_1.0.1_amd64.deb.html
