### ISSUE TITLE
I can't install `intune-portal` package because it's dependencie is old.

### ISSUE THREAD

**Issue by okash1n** [MicrosoftDocs/memdocs#3273]
I seem that `intune-portal` depends on the old `libssl1.1` and `msalsdk-dbusclient`. But these are deplicated.
Can you use `libssl3` or higher?

```
$ sudo apt install intune-portal
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 intune-portal : Depends: libssl1.1 (>= 1.1.0) but it is not installable
                 Depends: msalsdk-dbusclient (>= 1.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

```

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80924804-c247-d3bb-2245-fd3db3f3bd62
* Version Independent ID: 80924804-c247-d3bb-2245-fd3db3f3bd62
* Content: [Get the Microsoft Intune app for Linux](https://learn.microsoft.com/en-us/mem/intune/user-help/microsoft-intune-app-linux)
* Content Source: [memdocs/intune/user-help/microsoft-intune-app-linux.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/microsoft-intune-app-linux.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by benoithamet** [comment]
Hi @okash1n 
Having the same
You can get the libssl1.1 installed with the below commands but then you will face an issue to get the libsdbus-c++0

- wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb
- sudo dpkg -i libssl1.1_1.1.0g-2ubuntu4_amd64.deb

@benferse mentioned there is different issue reported and an update to the repo to use
I tried it but the same error

**Comment by okash1n** [comment]
Hi, @benoithamet san. Thanks for sharing your findings. I suppose I could temporarily ignore dependencies or manually install old packages, but that doesn't seem to be a fundamental solution.

**Comment by benoithamet** [comment]
Hi @okash1n 
you can try this one - worked for me
https://github.com/MicrosoftDocs/memdocs/issues/3262

**Comment by msbemba** [comment]
@benoithamet and @okash1n Thank you for your feedback. We updated the article with the correct command for Ubuntu 22.04 LTS: [Get the Microsoft Intune app for Linux](https://learn.microsoft.com/mem/intune/user-help/microsoft-intune-app-linux#install-intune-app)

For anyone that's having problems after using the commands for version 20.04:

Remove the 20.04 repo:
$ sudo rm /etc/apt/sources.list.d/microsoft-ubuntu-focal-prod.list
$ sudo apt-get update
Install the Microsoft package signing key again using the 22.04 commands.

Thanks
Sri

**Comment by okash1n** [comment]
@benoithamet @msbemba 

Thanks! That works perfectly.

**Comment by polatgo1** [comment]
If you're using 20.04, the doc from Microsoft doesn't install all required dependencies. Install all required libraries from "Requires" section in this link : https://ubuntu.pkgs.org/20.04/microsoft-prod-amd64/msalsdk-dbusclient_1.0.1_amd64.deb.html
