### ISSUE TITLE
Clarify timeline for "Plan for Change: Ending support for Company Portal authentication method for iOS/iPadOS ADE enrollment"

### ISSUE THREAD

**Issue by tcfinney** [MicrosoftDocs/memdocs#3274]
https://learn.microsoft.com/en-us/mem/intune/fundamentals/whats-new#plan-for-change-ending-support-for-company-portal-authentication-method-for-iosipados-ade-enrollment

Can you please add "CY" to "Q1 2023" in the first paragraph of the content? So, the request is that it should read "Q1 CY2023". 

Customers are asking for clarification, and they were told by Support that Q1 2023 would be in November 2023 since it "aligns to fiscal year"...but that's not accurate. Customers need to clearly understand that this change is currently targeted between January and end of March 2023.

Thank you,
Thomas

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d16c28db-1e8e-31fa-6127-3050a2940422
* Version Independent ID: 4cf9a244-1ae5-1637-48f7-3f503d400da6
* Content: [What's new in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/fundamentals/whats-new)
* Content Source: [memdocs/intune/fundamentals/whats-new.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/whats-new.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@tcfinney Thank you for your feedback. The document now reads Q1 of CY2023. 

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit  This can be closed.

**Comment by tcfinney** [comment]
@msbemba - many thanks for the quick response and documentation update!
