### ISSUE TITLE
Renew Apple MDM push certificate

### ISSUE THREAD

**Issue by nickbrownapollo** [MicrosoftDocs/memdocs#3277]
I don't believe that this statement is entirely accurate:
"Renew the MDM push certificate with the same Apple ID you used to create it."

It needs to be renewed with the same Apple _account_, but not necessarily the same Apple ID. It is possible for the Apple ID associated with the account to be changed.

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: babf49ae-ec79-e627-9dbf-2df2eb8909ab
* Version Independent ID: 90f3f372-9326-473e-3f82-e28e89853d49
* Content: [Get an Apple MDM Push certificate for Intune](https://learn.microsoft.com/en-gb/mem/intune/enrollment/apple-mdm-push-certificate-get#renew-apple-mdm-push-certificate)
* Content Source: [memdocs/intune/enrollment/apple-mdm-push-certificate-get.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/apple-mdm-push-certificate-get.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@nickbrownapollo Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3319

Once the author approves, the changes will be live.

Thanks
Sri
