### ISSUE TITLE
Hardware device details table incomplete for macOS

### ISSUE THREAD

**Issue by msft-rasgun** [MicrosoftDocs/memdocs#3278]
The Hardware Device Details table only lists macOS for Ethernet MAC and Product Name, but looking at the details on an actual managed macOS device, I can see

- Name
- Management name
- UDID
- Intune Device ID
- Azure AD Device ID
- Serial Number
- Operating System
- Storage details
- Manufacturer / Model / Architecture
- and much more

Please update table to reflect actual data gathered on a macOS device.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 905c303e-4306-38ec-2a30-4852a8c1bc2b
* Version Independent ID: ceb7e815-e19a-386f-902c-6e6bf53d5766
* Content: [View device details with Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/remote-actions/device-inventory)
* Content Source: [memdocs/intune/remote-actions/device-inventory.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/device-inventory.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@msft-rasgun Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3340

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @msft-rasgun Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
