### ISSUE TITLE
Endpoint Advanced features has moved.

### ISSUE THREAD

**Issue by LarryFluke** [MicrosoftDocs/memdocs#3284]
Step 3a was incorrect for me. To find the "Microsoft Intune connection" toggle, I had to browse to Endpoints > Advanced features, not Settings > Endpoints >Advanced features.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 24fa182f-ace6-e7e2-ff98-91951be7d10e
* Version Independent ID: f1acb398-6d69-b91c-5ee0-3da3bbf7809f
* Content: [Configure Microsoft Defender for Endpoint in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/advanced-threat-protection-configure#enable-microsoft-defender-for-endpoint-in-intune)
* Content Source: [memdocs/intune/protect/advanced-threat-protection-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/advanced-threat-protection-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@LarryFluke Thank you for your feedback. In order to get to endpoints, you will need to click on settings and endpoints

![image](https://user-images.githubusercontent.com/45987684/198816792-33bd5a1d-fc8d-463c-b436-8bd581ba153d.png)

Then click on Advanced features under general.

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit  This can be closed.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @LarryFluke Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
