### ISSUE TITLE
c# code example

### ISSUE THREAD

**Issue by DKusnir** [MicrosoftDocs/memdocs#329]
[Enter feedback here]
Hello

would you mind to add some c# examples how to create SCCM variables ? 

thanks a lot
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d86d92bf-561b-eff0-b565-cf7c5bd668f2
* Version Independent ID: b20a7712-f7b9-840a-86a9-60bc835154b4
* Content: [Use Task Sequence Variables in a Running Task Sequence - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/develop/osd/how-to-use-task-sequence-variables-in-a-running-task-sequence?source=docs)
* Content Source: [memdocs/configmgr/develop/osd/how-to-use-task-sequence-variables-in-a-running-task-sequence.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/develop/osd/how-to-use-task-sequence-variables-in-a-running-task-sequence.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @DKusnir for the feedback. The ConfigMgr SDK content hasn't changed in a long time, and it's an area in which we're not actively investing beyond basic maintenance and some new functionality. If you'd like to submit a change for this issue, see [How to contribute](https://docs.microsoft.com/sccm/core/understand/use-docs#bkmk_contribute).
