### ISSUE TITLE
Does on work on Win11 SE

### ISSUE THREAD

**Issue by BagginsLongshot** [MicrosoftDocs/memdocs#3296]
These instructions lead to successful installation on Win10 and Win11 devices. However, the installation fails on Win11SE (edu) devices. Waiting for support to identify why this fails as RemoteHelp is one of the few approved apps for Win11SE. It would be very helpful if there are different instructions or known issues for deploying RemoteHelp to Win11SE via Intune/Endpoint Manager. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6bc62c89-a452-0d3f-01f3-c5982803809e
* Version Independent ID: 6bc62c89-a452-0d3f-01f3-c5982803809e
* Content: [Remotely assist users that are authenticated by your organization.](https://learn.microsoft.com/en-us/mem/intune/remote-actions/remote-help)
* Content Source: [memdocs/intune/remote-actions/remote-help.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/remote-help.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by yogkumgit** [comment]
@Smritib17 Please help us in resolving this issue. Thanks

**Comment by Smritib17** [comment]
Hi @BagginsLongshot , thank you for your contribution to the Microsoft Intune documentation!

I hope the support case was resolved and gave you more insight into the problem. After discussion with the product team , I can confirm that there are no known issues or different instructions for deploying RemoteHelp to Win11SE via Intune/Endpoint Manager.

**Comment by yogkumgit** [comment]
closing
