### ISSUE TITLE
Include device installation restriction recommendations and Kernel DMA Protection

### ISSUE THREAD

**Issue by sveinungre** [MicrosoftDocs/memdocs#33]
The MDM Security Baseline documentation does not explain the questions regarding device installation restrictions and Kernel DMA Protection, it would be nice to explain that you can actually remove device installation restrictions if your device supports Kernel DMA Protection. Have a look at the documentation provided for the GPO counterpart under Thunderbolt:
https://techcommunity.microsoft.com/t5/microsoft-security-baselines/security-baseline-final-for-windows-10-v1909-and-windows-server/ba-p/1023093#

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f0f4d5d-fdd1-22e7-6372-9916b199209f
* Version Independent ID: caeb9f8b-30ad-7f02-4740-56522b2f9b1b
* Content: [Intune security baselines settings for Windows 10 MDM - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/security-baseline-settings-mdm-all?pivots=mdm-may-2019#feedback)
* Content Source: [memdocs/intune/protect/security-baseline-settings-mdm-all.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/security-baseline-settings-mdm-all.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
The settings in question link out to the Windows client MDM content where the functionality of the CSP is owned and described. If additional information is needed, the CSP content will need that update. The operation or interaction of the settings from Windows is outside the scope of this reference article.
