### ISSUE TITLE
On the Schedule tab - what is the duration checkbox for?

### ISSUE THREAD

**Issue by PaulKlerkx** [MicrosoftDocs/memdocs#330]
Hi,  Maybe this page could use some more clarity in the section for network discovery specifically for the schedule tab.  
It doesn't mention what the "duration" checkbox is for.  I would guess that it is the similiar to a scheduled task as per https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc748841(v=ws.10)?redirectedfrom=MSDN indicating this dictates that network discovery will repeatedly rerun till it has been running for as long as the duration is set.  the problem there is that in a scheduled task, duration is normally a part of "repeat task every..." but that isn't part of the network discovery schedule options.  

How do you calculate an appropriate time period.  I would just prefer network discovery run once completely through once a week however the duration is not optional.  

If I set duration to 1 hour but network discovery takes 2 hours, does it never finish. 
If I set duration to 1 hour and it takes 30 seconds to run, does that mean it will run 120 times and flood the network with a barrage of broadcasts.  
if I set a schedule of every 3 days and a duration of 3 days, does that mean it will always be running?

thanks for any clarity you can provide there.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09a88524-a2af-cdb2-630d-86177e245753
* Version Independent ID: b5590ca8-3ce9-c277-e8c3-9c78a69945c1
* Content: [Configure discovery - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/configure-discovery-methods)
* Content Source: [memdocs/configmgr/core/servers/deploy/configure/configure-discovery-methods.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/deploy/configure/configure-discovery-methods.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @PaulKlerkx, I found a description of this field from the SCCM 2007 Admin Companion:

> Duration indicates the period of time Network Discovery has to complete its search to resources. On a local subnet, two hours might be sufficient. however, if you perform a search of an enterprise network across several router hopes with several thousand potential resources, you might need to increase this number so that Network Discovery has enough time to complete its search. If Network Discovery runs out of time, it logs a message to that effect in the netdisc.log file, and completes DDRs only for the part of the search that is complete.

We'll pop that into this article (since it was written by Steven Kaczmarek, former manager of the smsdocs team, and published by Microsoft Press) 😄
