### ISSUE TITLE
Request correction of public information

### ISSUE THREAD

**Issue by ksaito12345** [MicrosoftDocs/memdocs#3300]
[Enter feedback here]
Since fixed versions are valid for LOB apps, not offline apps, request a fix as follows:

<Before correction>
Offline apps are updated using Intune, whereas online apps are updated by the store. Use offline apps when you need to install and maintain a specific app version.
↓
<After correction>
LOB apps are updated using Intune, whereas online apps are updated by the store. Use LOB apps when you need to install and maintain a specific app version.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 42b3ccb0-592e-a0bf-aa4f-ab37e00e1195
* Version Independent ID: d0af9188-3489-0f15-ef25-5b6d83edb76c
* Content: [Add and assign the Windows 10 Company Portal app for Intune managed devices - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/apps/store-apps-company-portal-autopilot)
* Content Source: [memdocs/intune/apps/store-apps-company-portal-autopilot.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/store-apps-company-portal-autopilot.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@ksaito12345 Thank you for your feedback. We have made changes to the documents via PR#https://github.com/MicrosoftDocs/memdocs/pull/3320

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by msbemba** [comment]
@ksaito12345  thank you for your feedback. Below is the update we have got from the author 

"Offline apps are managed by Intune, whereas online apps are managed by the store. Use offline apps when you need to install and maintain a specific app version. A line-of-business (LOB) app is an app that you add to Intune from an app installation file. This kind of app is typically written in-house."


Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit This can be closed.
