### ISSUE TITLE
Expanding built-in Office ATs

### ISSUE THREAD

**Issue by icelava** [MicrosoftDocs/memdocs#331]
Is there any timeline for Intune to inherently feature the complete Office ATs? Or do administrators have to manually setup ingestion for each and every Office app .admx file?

Chromium-based Edge's AT is already available in Intune's AT configuration profile.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f187188e-9838-b9ca-fdde-9dd3cbd5ba00
* Version Independent ID: 75de9a7f-098b-58c6-279c-61e5f31efcc6
* Content: [Walkthrough - Create administrative template in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/tutorial-walkthrough-administrative-templates)
* Content Source: [memdocs/intune/configuration/tutorial-walkthrough-administrative-templates.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/tutorial-walkthrough-administrative-templates.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@icelava The Office templates are behind. They're _estimated_ to be updated in the 2009 release. Timelines change often, so it could be pushed to a later release.

There's also a [User voice item](https://microsoftintune.uservoice.com/forums/291681-ideas/suggestions/40985632-update-administrative-templates-to-include-latest) for this same ask.

@mikedano for visibility.
