### ISSUE TITLE
Google ADMX

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/memdocs#3312]
Hello,

Something not good?

![image](https://user-images.githubusercontent.com/39700914/198542284-f5422fc9-96a4-4030-94f0-19661f86acd2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 798b808e-3d04-6965-c1a4-cbd4b685bb19
* Version Independent ID: 798b808e-3d04-6965-c1a4-cbd4b685bb19
* Content: [Import custom and third party partner ADMX templates in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/configuration/administrative-templates-import-custom)
* Content Source: [memdocs/intune/configuration/administrative-templates-import-custom.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/administrative-templates-import-custom.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by lightupdifire** [comment]
Worked after:
1. Installed ADMX windows 10 21h2
2. imported windows admx file
3. then imported chrome admx
![image](https://user-images.githubusercontent.com/39700914/198543491-26e01f4c-691e-4856-b776-82a228223299.png)

Maybe a document update for Google?
And what if we need Windows 11 and any new version of Windows ADMX or Chrome ADMXI?

**Comment by yogkumgit** [comment]
@MandiOhlinger Please help us in resolving this issue. Thanks

**Comment by lightupdifire** [comment]
Hello,
I see Google Chrome included per default in Intune ADMX, so maybe Google Chrome is not a good example to review here.
