### ISSUE TITLE
Request correction of content

### ISSUE THREAD

**Issue by ksaito12345** [MicrosoftDocs/memdocs#3313]
[Enter feedback here]
Offline apps are updated using Intune, whereas online apps are updated by the store. Use offline apps when you need to install and maintain a specific app version.
↓
LOB apps are updated using Intune, whereas online apps and offline apps are updated by the Microsoft store. Use LOB apps when you need to install and maintain a specific app version.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 42b3ccb0-592e-a0bf-aa4f-ab37e00e1195
* Version Independent ID: d0af9188-3489-0f15-ef25-5b6d83edb76c
* Content: [Add and assign the Windows 10 Company Portal app for Intune managed devices - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/apps/store-apps-company-portal-autopilot)
* Content Source: [memdocs/intune/apps/store-apps-company-portal-autopilot.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/store-apps-company-portal-autopilot.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@ksaito12345  This has been address in PR#https://github.com/MicrosoftDocs/memdocs/pull/3320

@yogkumgit This can be closed as a duplicate.

Thanks
Sri
