### ISSUE TITLE
Request correction of content

### ISSUE THREAD

**Issue by ksaito12345** [MicrosoftDocs/memdocs#3314]
[Enter feedback here]
Configure settings to show offline apps
↓
Configure settings to show offline apps in Microsoft Store for Business

Add the following description to the Download the offline Company Portal app section:
・ In this document, offline apps are referred to as offline apps because they are Microsoft Store for business use, but offline apps are LOB apps.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 43ae0d4a-eefd-7770-b2a4-d4f72f7272a3
* Version Independent ID: 1001276c-ddd3-14bd-cd5e-74ce47490d19
* Content: [Manually add the Windows 10 Company Portal app - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/apps/store-apps-company-portal-app)
* Content Source: [memdocs/intune/apps/store-apps-company-portal-app.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/store-apps-company-portal-app.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@ksaito12345 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3322

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@ksaito12345 closing as per author's comment in PR. Thanks
