### ISSUE TITLE
MTD App Inventory inconsistency

### ISSUE THREAD

**Issue by DuncanFairley** [MicrosoftDocs/memdocs#3317]
On <https://learn.microsoft.com/en-us/mem/intune/user-help/what-info-can-your-company-see-when-you-enroll-your-device-in-intune#app-inventory-details> in the App Inventory Details section about installing an MTD app,  it states: 
> Personal-owned device: Your organization can only view the details of your managed apps.

On <https://learn.microsoft.com/en-us/mem/intune/user-help/set-up-mobile-threat-defense#information-your-organization-can-see> it states:
>  The MTD app does report information about your apps, such as name and version, to your organization.

It's unclear if the second page is accurate for Personal-owned devices as well. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 15a2c16e-975e-cdee-226f-4f305f67401e
* Version Independent ID: 2355e80f-0abd-dff8-642d-bc2e982147b9
* Content: [Install Mobile Threat Defense on your mobile device](https://learn.microsoft.com/en-us/mem/intune/user-help/set-up-mobile-threat-defense)
* Content Source: [memdocs/intune/user-help/set-up-mobile-threat-defense.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/set-up-mobile-threat-defense.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@DuncanFairley Thank you for your feedback. We shall review both documents and make changes accordingly.

Thanks
Sri

**Comment by msbemba** [comment]
@DuncanFairley Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3374

Once the author approves, the changes will be live.

Thanks
Sri
