### ISSUE TITLE
Endpoint security firewall profile settings documentation

### ISSUE THREAD

**Issue by cybernerd2014** [MicrosoftDocs/memdocs#3323]
The below page needs a lot of improvement. The order that settings are listed are not in the order when creating a new firewall profile (Number of seconds a security association can be idle before it's deleted is a the top of the documentation but setting is at then end of the profile). Also some of the wording in the profile is different than in the documentation (Block unicast responses to multicast broadcasts < DOCUMENTATION VS Disable Unicast Responses To Multicast Broadcast < PROFILE). The CSP has things listed as Yes/No but the profile settings are True/False. It would also be great to get some best practices created for small businesses...There is one for GPO but not one for endpoint security that we could find.

[endpoint-security-firewall-profile-settings](https://learn.microsoft.com/en-us/mem/intune/protect/endpoint-security-firewall-profile-settings)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 788dd3b1-947d-937b-6375-cf0f0a071fab
* Version Independent ID: 22b5d531-34d4-837a-84f9-88bc78b0042f
* Content: [Intune endpoint security firewall settings](https://learn.microsoft.com/en-us/mem/intune/protect/endpoint-security-firewall-profile-settings)
* Content Source: [memdocs/intune/protect/endpoint-security-firewall-profile-settings.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/endpoint-security-firewall-profile-settings.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by yogkumgit** [comment]
@Brenduns Please help us in resolving this issue. Thanks

**Comment by Brenduns** [comment]
@cybernerd2014    Thanks for the feedback.  Unfortunately, we are no longer investing in these deprecated settings which apply only to those profiles created before April 2022. 

 As detailed in the note at the top of the article, in April, a new settings format was introduced that replaces the older format which often saw Intune present the name and options in different formats than the underlying setting as defined by Windows and documented in the Windows CSP content. (You call out a great example of that problem, for the _Block unicast responses to multicast broadcasts_ setting.) That disconnect in Intune’s presentation vs the actual setting details from Windows, who designs and owns the settings, often caused confusion about the actual use of the as presented in the admin center.

With the Intune UI now aligned directly to the Windows CSPs for both the name of the setting and its options, we won’t be duplicating that content in our doc set. Instead, we recommend use of the _Learn more_ link for a setting to open the Windows CSP content directly where you’ll find content that remains accurate and up-to-date from the CSP owners.  

If you’re using the profile Platform type of **Windows 10, Windows 11, and Windows Server**, this content article won’t apply.  If you’re editing an older profile Platform type of **Windows 10 and later** (this older templates should no longer be available to create new profiles), we recommend switching to the newer Platform type as any new settings or updates for Firewall settings won’t be added to the deprecated platform template.
