### ISSUE TITLE
additional expliation for "What you need to know"

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/memdocs#3331]
in the "What you need to know" section it says:

> Some ADMX files may have dependency prerequisites. Import any dependency ADMX files first. For example, to import Mozilla Firefox ADMX and ADML files, you:
> 
> Import the mozilla.admx and mozilla.adml files. Make sure the status shows Available.
> Import the firefox.admx and firefox.adml files.
> If you upload firefox.admx before mozilla.adml, then the import will fail.
> 
> To remove a dependency prerequisite, delete the associated ADMX file first. Then, delete the dependency prerequisite. In our Mozilla Firefox example, delete firefox.admx and then delete mozilla.admx.
> 

I suggest a sentence be added on how to identify a dependency in the first place. I had a hard time uploading the native kerberos.admx file only to realize it depended on the windows admx file, which was not clear by the generic error message on the portal. I propose something like: 

To see if your ADMX has a dependency, open it in a text editor and look for `using` references in the `policyNamespaces` node. For example, this kerberos.admx file requires the Windows.admx file be uploaded to Intune first:

```
  <policyNamespaces>
    <target prefix="kerberos" namespace="Microsoft.Policies.Kerberos" />
    <using prefix="windows" namespace="Microsoft.Policies.Windows" />
  </policyNamespaces>

```
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 798b808e-3d04-6965-c1a4-cbd4b685bb19
* Version Independent ID: 798b808e-3d04-6965-c1a4-cbd4b685bb19
* Content: [Import custom and third party partner ADMX templates in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/configuration/administrative-templates-import-custom)
* Content Source: [memdocs/intune/configuration/administrative-templates-import-custom.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/administrative-templates-import-custom.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by msbemba** [comment]
@Mike-Crowley Thank you for your feedback. We will review and incorporate the change to the document shortly.

Thanks
Sri

**Comment by msbemba** [comment]
@Mike-Crowley Thank you for your feedback. We have made changes to the document via pR#https://github.com/MicrosoftDocs/memdocs/pull/3421

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Mike-Crowley Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
