### ISSUE TITLE
Enrollment notifications only work with user-driven enrollment methods.

### ISSUE THREAD

**Issue by jerryabo** [MicrosoftDocs/memdocs#3332]
"User-driven enrollment methods" is not something explicitly defined that I could find, and may be perceived by some to be ambiguous. Does this mean any scenario with user affinity, byod, etc.? Can we enumerate the supported enrollment methods?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 90271d90-a909-6afd-31c8-f80561bd92de
* Version Independent ID: 90271d90-a909-6afd-31c8-f80561bd92de
* Content: [Set up enrollment notifications in Intune - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/enrollment/enrollment-notifications)
* Content Source: [memdocs/intune/enrollment/enrollment-notifications.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/enrollment-notifications.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @jerryabo, thanks for reaching out to the Microsoft Intune Docs team. Yes, good idea. I've added this as a task for the docs team so we'll work with the product team to get the doc updated/linked with a good explaination of what user-driven enrollment methods are.
