### ISSUE TITLE
Outdated docs 

### ISSUE THREAD

**Issue by bf** [MicrosoftDocs/memdocs#3334]
https://learn.microsoft.com/en-us/mem/intune/protect/encrypt-devices#silently-enable-bitlocker-on-devices

Allow standard users to enable encryption during Autopilot = Yes

is outdated, as it is not present in the Endpoint security | Disk encryption policy

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 54cccf1d-81fd-5331-aee7-59a35b39cb15
* Version Independent ID: 81d14392-fe74-4fd9-047f-7b8292d84f0c
* Content: [Encrypt Windows devices with BitLocker in Intune - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/encrypt-devices#silently-enable-bitlocker-on-devices)
* Content Source: [memdocs/intune/protect/encrypt-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/encrypt-devices.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@bf   Hello Benjamin.   The Autopilot setting becomes available after setting **Hide prompt about third-party encryption** to *Yes*.   If you enable that first setting in the list, and don’t see the Autopilot setting, I’d reach out to support for more assistance.  Here is the view from my public tenant this morning:
  
<img width="306" alt="image" src="https://user-images.githubusercontent.com/17034749/199531753-3a2d3d20-bf06-4399-9a6a-d12afadbef82.png">

**Comment by yogkumgit** [comment]
@Brenduns Thank you very much for sharing this explanation. @bf Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
