### ISSUE TITLE
ESP requirement on the DEVICE

### ISSUE THREAD

**Issue by kletsah** [MicrosoftDocs/memdocs#3336]
Hi all,

please make it more clear you have to assign a ESP profile to the device group where the autopilot devices are grouped. If you don't have a ESP profile for the device, your pre-provision will fail and you will see at Device Setup that it will fail at the defined time out in the ESP profile. (We had ESP profiles targetted to only users and pre-provisioning was failing)
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c0f572e0-1bc0-6f14-7f60-989eb67fb7e7
* Version Independent ID: e4ec5b25-d9a6-d260-6cf6-ff4f3eb3ecb8
* Content: [Windows Autopilot for pre-provisioned deployment](https://learn.microsoft.com/en-us/mem/autopilot/pre-provision)
* Content Source: [memdocs/autopilot/pre-provision.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/pre-provision.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by frankroj** [comment]
Thank you for the feedback @kletsah. We have actually recently released some new docs that makes these steps clearer. Please see the following link where these steps are specifically spelled out:

https://learn.microsoft.com/mem/autopilot/tutorial/pre-provisioning/azure-ad-join-device-group
https://learn.microsoft.com/mem/autopilot/tutorial/pre-provisioning/azure-ad-join-esp
