### ISSUE TITLE
The policy for Exchange Active Sync clients Blocks Microsoft Teams on Managed Desktop

### ISSUE THREAD

**Issue by ccapellan** [MicrosoftDocs/memdocs#3338]
[Enter feedback here]
After enabling the 2nd CA policy, I can no longer use Microsoft Teams on an Intune managed Windows PC.

![image](https://user-images.githubusercontent.com/68125213/199603121-16f7b49b-a8d0-49a7-a641-398e695b53b9.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 733b08c2-5666-0d9b-8e78-28fba3456a6f
* Version Independent ID: ab6a321b-d6c0-c301-8156-96ccfdd21192
* Content: [Tutorial - Protect Exchange Online email on unmanaged devices - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/tutorial-protect-email-on-unmanaged-devices)
* Content Source: [memdocs/intune/protect/tutorial-protect-email-on-unmanaged-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/tutorial-protect-email-on-unmanaged-devices.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@ccapellan Thank you for your feedback. That is interesting, ideally when yuenable the policy it should only affect Mobile and desktop clients using Exchange active sync. This looks like either a bug or another policy interfering, So I'd recommend you open a support ticket via the need help section on the admin center so that our support engineers can collect the logs and resolve/escalate if need be.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ccapellan Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
