### ISSUE TITLE
Updates for Apple Business Manager

### ISSUE THREAD

**Issue by afield1235** [MicrosoftDocs/memdocs#334]
Hello,
Can these instructions be updated for Apple business manager? The renewal steps are not accurate:

**Renew an ADE token**

1. Go to deploy.apple.com. 
2. Under Manage Servers, choose your MDM server associated with the token file that you want to renew.
3. Choose Generate New Token. 
4. Screenshot of generate new token.
5. Choose Your Server Token.

The only option in ABM is to download a new token. It's unclear if that will work the same:
![image](https://user-images.githubusercontent.com/18271134/83814960-21b2bb00-a674-11ea-8426-fbfe388bd061.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0319ece7-6b1f-d737-618c-778d3f196313
* Version Independent ID: 20b5b39e-56e2-d88e-e4b2-22a79b5d3ccb
* Content: [Enroll macOS devices - Apple Business Manager or Apple School Manager](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-macos)
* Content Source: [memdocs/intune/enrollment/device-enrollment-program-enroll-macos.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/device-enrollment-program-enroll-macos.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by afield1235** [comment]
One thing to add, when we initially created the MDM server in Apple Business manager, we had to upload an intune public key first. Do you not need to upload a new Intune Public key? There is no place to download a new one when renewing in Intune:

![image](https://user-images.githubusercontent.com/18271134/83819899-f7ff9100-a67f-11ea-9285-e14f37b3b684.png)

**Comment by afield1235** [comment]
Can we please get an update on this? We are reaching the end of our one year token life.

**Comment by ErikjeMS** [comment]
Investigating with PM...
8462797

**Comment by ErikjeMS** [comment]
@afield1235 I've updated the Renew an ADE token with the new ABM user interface. I'm still waiting on a response from the PM for your second question.

**Comment by ErikjeMS** [comment]
@afield1235 Here is the PMs response to your 2nd question. If this doesn't resolve your question, let me know and I'll reopen this issue. 
"You only need to download the public key when creating a new token within Intune. When renewing, you do not need to upload a new public key into ABM/ASM that you downloaded from Intune, and you only download a new one when creating a new token. The steps documented here are correct - [Enroll iOS/iPadOS devices - Automated Device Enrollment](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-ios#renew-an-automated-device-enrollment-token)"
