### ISSUE TITLE
Error in guide - BYOD devices won't show up in Enrolled devices in Endpoint Manager

### ISSUE THREAD

**Issue by flukestar** [MicrosoftDocs/memdocs#3342]
[Enter feedback here]

There seems to be an error in your two page quickstart guide from the perspective of adding a BYOD device, which will cause confusion for the person trying to learn.

You show a pic of the Window device enrolled in All Devices. This actually won't happen with BYOD devices as MAM will take precedence over MDM and so they won't actually enrol into Endpoint Manager as you stated.

Following your guide with a BYOD - In the first quick start page at point 8 in "Set up automatic enrolment" - https://learn.microsoft.com/en-us/mem/intune/enrollment/quickstart-setup-auto-enrollment
You instruct to add a user group to both MDM user scope and MAM user scope, and this is where the issue will arise.

You have noted that MDM won't be enabled as stated in your important note at Point 2 [in your other Setup Windows enrolment guide](https://learn.microsoft.com/en-us/mem/intune/enrollment/windows-enroll#enable-windows-10-automatic-enrollment). 

> For Windows BYOD devices, the MAM user scope takes precedence if both the MAM user scope and the MDM user scope (automatic MDM enrollment) are enabled for all users (or the same groups of users). The device will not be MDM enrolled, and Windows Information Protection (WIP) Policies will be applied if you have configured them.
> 
> If your intent is to enable automatic enrollment for Windows BYOD devices to an MDM: configure the MDM user scope to All (or Some, and specify a group) and configure the MAM user scope to None (or Some, and specify a group – ensuring that users are not members of a group targeted by both MDM and MAM user scopes).
> 
> For corporate devices, the MDM user scope takes precedence if both MDM and MAM user scopes are enabled. The device will get automatically enrolled in the configured MDM.

Following your guide with a BYOD device, **causes confusion** as the device is not enrolled in MDM as stated at the end of your quickstart guide.

Thanks
Chris

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c55656da-6383-1993-c757-5be898f26413
* Version Independent ID: 38216fa8-505c-3b4f-33ad-d32cca9ad277
* Content: [Quickstart - Enroll your Windows 10/11 desktop device in Microsoft Intune](https://learn.microsoft.com/en-gb/mem/intune/enrollment/quickstart-enroll-windows-device)
* Content Source: [memdocs/intune/enrollment/quickstart-enroll-windows-device.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/quickstart-enroll-windows-device.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@flukestar Thank you for your feedback. We will review the guide and the document and make changes if need be.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@flukestar Thank you for your feedback. I have added the important note after Step 8 to avoid confusion.

This can be tracked via PR#https://github.com/MicrosoftDocs/memdocs/pull/3570

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @flukestar Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
