### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by joealdeguer** [MicrosoftDocs/memdocs#3343]
The link https://github.com/msintuneappsdk/intune-app-wrapping-tool-mac is pointing to a page not found!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 54e4efd6-d1de-dba7-6ae5-a91c7a28b662
* Version Independent ID: f529438b-becd-3b8e-dc6c-02413af9854f
* Content: [How to add macOS line-of-business apps to Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/apps/lob-apps-macos?source=docs)
* Content Source: [memdocs/intune/apps/lob-apps-macos.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/lob-apps-macos.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@joealdeguer Thank you for the update. In August 2022, we removed the ability to upload wrapped .intunemac files in the Microsoft Endpoint Manager admin center. You can now upload *.pkg* files to the [Microsoft Endpoint Manager admin center](https://go.microsoft.com/fwlink/?linkid=2109431).

The document has been updated accordingly.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @joealdeguer Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
