### ISSUE TITLE
sentence fragment

### ISSUE THREAD

**Issue by CathyMoya** [MicrosoftDocs/memdocs#3346]
[Enter feedback here]
There's a part of a sentence - "The native Mail application on Windows 8.1 and later (when enrolled into MDM with Intune)" but that's all it says. It looks like the rest of the sentence got wiped out along the way.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6d40a143-767d-ea36-83e3-e5bdab481972
* Version Independent ID: 2fbd64e5-72bb-af91-3277-0bb8e696e1b4
* Content: [Create Exchange Conditional Access policy - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/conditional-access-exchange-create)
* Content Source: [memdocs/intune/protect/conditional-access-exchange-create.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/conditional-access-exchange-create.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@CathyMoya Thank you for your feedback. We have made changes(rephrased the statement) to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3362

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @CathyMoya Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
