### ISSUE TITLE
Compare Baseline Versions Needs Update

### ISSUE THREAD

**Issue by chriti** [MicrosoftDocs/memdocs#3348]
The UI has changed and there is no longer a "Compare Baselines" button. You need to go through the new Change Baseline Process to download and compare. Both the screenshots and process need updated. 

![MicrosoftTeams-image](https://user-images.githubusercontent.com/41973502/200646860-f32e5857-d598-4977-8d2c-3f2e0b4700c3.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1c553157-31cf-faf9-0b4c-00f1a56f0545
* Version Independent ID: c91b6b7b-3264-f0f7-688e-baac0ce3a718
* Content: [Learn about Windows security baselines you can deploy with Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/security-baselines#compare-baseline-versions)
* Content Source: [memdocs/intune/protect/security-baselines.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/security-baselines.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@chriti Thank you for your feedback. We will review and update the document if need be.

Thanks
Sri

**Comment by msbemba** [comment]
@chriti Thank you for your feedback. We have updated the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3420

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @chriti Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
