### ISSUE TITLE
Misleading chapter name after Linux content was added

### ISSUE THREAD

**Issue by GenerAhl** [MicrosoftDocs/memdocs#3349]
[Enter feedback here]
The legend/index out on the left side of the page has the name "PowerShell script for custom settings" for this page, which was true when it contained only Windows examples. With the addition of Linux content, the "Powershell" reference is misleading.
I suggest you change the name to "Scripts for custom compliance settings".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 013a6f8c-7d49-895e-1074-eae97d11b1f6
* Version Independent ID: 013a6f8c-7d49-895e-1074-eae97d11b1f6
* Content: [Create a discovery script for custom compliance policy in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/compliance-custom-script)
* Content Source: [memdocs/intune/protect/compliance-custom-script.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/compliance-custom-script.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@GenerAhl   Thanks again!  The Table of contents entry did escape revision wih the content update. THat has been fixed and will begin showing up in published content later today.

**Comment by GenerAhl** [comment]
Thanks for your swift attention @Brenduns !
