### ISSUE TITLE
"Not Applicable" vs "Not Detected" compliance

### ISSUE THREAD

**Issue by CaptainUnlikely** [MicrosoftDocs/memdocs#335]
"A configuration item rule is not evaluated if it is not detected or not applicable on a client device; however, the rule is returned as compliant."

In my experience this does not seem to be correct.  If a configuration item is not detected the rule is returned as noncompliant, however it it's not applicable then the rule is returned as compliant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85a85318-67b1-56cf-85c3-77d1ee5f7969
* Version Independent ID: a3fe8779-1f63-7e57-c9eb-432986deceef
* Content: [Monitor compliance settings - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/compliance/deploy-use/monitor-compliance-settings)
* Content Source: [memdocs/configmgr/compliance/deploy-use/monitor-compliance-settings.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/compliance/deploy-use/monitor-compliance-settings.md)
* Product: **configuration-manager**
* Technology: **configmgr-compliance**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @CaptainUnlikely for the feedback. This content and the feature shouldn't have changed much in the past 8ish years. I'll check with engineering though.

**Comment by aczechowski** [comment]
Response back from dev:

> It has always been that compliant is the default return value for not applicable or not detected, unless it is a DCM application CI with a detection method that is not detected for a baseline rule that says that it must be detected.

So maybe that's what you're seeing?
