### ISSUE TITLE
Referenced Utilities no longer exist

### ISSUE THREAD

**Issue by dharman0125** [MicrosoftDocs/memdocs#3351]
On this page there is reference to using IntuneAppUtil to prepare the LOB apps.  This utility is no longer available on the github page linked and infact returns a 404.  Can you please provide the current location for this utility. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 54e4efd6-d1de-dba7-6ae5-a91c7a28b662
* Version Independent ID: f529438b-becd-3b8e-dc6c-02413af9854f
* Content: [How to add macOS line-of-business apps to Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/apps/lob-apps-macos)
* Content Source: [memdocs/intune/apps/lob-apps-macos.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/lob-apps-macos.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@dharman0125 Thank you for your feedback. The Utility no longer exists and the document has been updated accordingly.

Once there is a new one available, the document will be updated.

Hope this helps!

@yogkumgit  This can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @dharman0125 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
