### ISSUE TITLE
TPM attestation failure with error code 0x81039001

### ISSUE THREAD

**Issue by sbv2291** [MicrosoftDocs/memdocs#3352]
[Enter feedback here]
https://learn.microsoft.com/en-us/mem/autopilot/known-issues#tpm-attestation-failure-with-error-code-0x81039001

Is there any status update on this? October 2022 is already gone and issue is still exist. Do we have any new ETA?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e2da4bbd-faa6-e6d5-07c1-946f5f7da2f5
* Version Independent ID: d1040d9e-7e73-b308-65a1-e141f07ed2dc
* Content: [Windows Autopilot known issues](https://learn.microsoft.com/en-us/mem/autopilot/known-issues#tpm-attestation-failure-with-error-code-0x81039001)
* Content Source: [memdocs/autopilot/known-issues.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/known-issues.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @sbv2291 for the feedback. There was an improvement made to the service in October to improve the experience in some circumstances, but not all instances. After checking with the PM, I'm removing the last sentence but keeping the rest of the section for reference.
