### ISSUE TITLE
Typo - thread defense instead of threat defense

### ISSUE THREAD

**Issue by BradyWi** [MicrosoftDocs/memdocs#3359]
Last sentence in the first paragraph of the linked section below has 'thread defense' instead of 'threat defense'.  
"Not all of the following options are supported by all Mobile Thread Defense partners."

Section: https://learn.microsoft.com/en-us/mem/intune/protect/mtd-connector-enable#mobile-threat-defense-toggle-options

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 34003d88-4545-4704-e4b7-7c26009197e9
* Version Independent ID: 32715c02-ce80-8300-0be3-65eb01da2ec4
* Content: [Enable Mobile Threat Defense connector in Microsoft Intune - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/mtd-connector-enable#mobile-threat-defense-toggle-options)
* Content Source: [memdocs/intune/protect/mtd-connector-enable.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/mtd-connector-enable.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@BradyWi,  Thanks for catching that.  @yogkumgit  It appears there is a second instance of the same typo in a second artricle:  
https://learn.microsoft.com/en-us/mem/intune/protect/sophos-mtd-connector-integration

**Comment by msbemba** [comment]
@Brenduns I have created a PR#https://github.com/MicrosoftDocs/memdocs/pull/3406 for the second article.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @BradyWi Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
