### ISSUE TITLE
Missing log - TSDTHandler.log

### ISSUE THREAD

**Issue by abndrew82** [MicrosoftDocs/memdocs#336]
While troubleshooting a case today, I found a log I had not previously seen - TSDTHandler.log

No reference to it on the site, but appears to track the process for Applications that use a Task Sequence as the deployment type.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 123e9d7b-1759-cc47-e73f-25e17b791636
* Version Independent ID: 966dca6c-9688-8a43-65cb-0f795d0a646a
* Content: [Log file reference - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/hierarchy/log-files)
* Content Source: [memdocs/configmgr/core/plan-design/hierarchy/log-files.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/hierarchy/log-files.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @abndrew82 for the feedback. There are unfortunately a number of missing logs. When new features come out, this is a standard question in our template for the feature team to fill out, but obviously is sometimes overlooked. I'll confirm with engineering.

**Comment by aczechowski** [comment]
I made a change to add this. It might make afternoon publishing, otherwise it will be live Monday morning.
