### ISSUE TITLE
RBAC scope is wrong

### ISSUE THREAD

**Issue by mmelkersen** [MicrosoftDocs/memdocs#3361]
Hi team

I discovered that the RBAC scope given in this doc is not correct. 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/MATTIA~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=Edit-Time-Data
href="file:///C:/Users/MATTIA~1/AppData/Local/Temp/msohtmlclip1/01/clip_editdata.mso">

<link rel=themeData
href="file:///C:/Users/MATTIA~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/MATTIA~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=DA style='tab-interval:65.2pt;word-wrap:break-word'>

User | Role / Access | Granted / denied -   token
-- | -- | --
A | Intune administrator |  No
A | Intune administrator + member of   AAD device join |  Yes
B | Teams Administrator +   member of AAD device join |  Yes

</body>

</html>

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 84a280df-a5f1-1cc2-8e58-80e2db7110b9
* Version Independent ID: e263811d-a2f9-2ff9-24ff-0e2a2d58907a
* Content: [Bulk enrollment for Windows devices - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/enrollment/windows-bulk-enroll?source=docs)
* Content Source: [memdocs/intune/enrollment/windows-bulk-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/windows-bulk-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by yogkumgit** [comment]
@lenewsad Please help us in resolving this issue. Thanks

**Comment by lenewsad** [comment]
Hi @mmelkersen, thanks for reaching out to the Microsoft Intune Docs team. I'm going to investigate this and update the docs accordingly. To clarify, does that chart show what you actually experienced?  CC @yogkumgit

**Comment by lenewsad** [comment]
Hi @yogkumgit, just pinged the PM again.

**Comment by lenewsad** [comment]
Hi @mmelkersen, thanks again for reaching out to us with this information. The third column in your table says both *grant* and *denied* so I'm not sure if the _yes/no_ values are in response to *grant* or *denied*. Kindly follow-up with more context if further clarification is needed. 

I confirmed with the product team that an Intune administrator role should have access to the token, so this may be a bug. If the problem persists where the Intune administrator isn't granted access, sign in to the [Microsoft Intune admin center](https://intune.microsoft.com) and go to **Troubleshooting + support** > **Help and support** to raise a support ticket with technical support.  For more information about support options in the admin center, see [How to get support in the Microsoft Intune admin center](https://learn.microsoft.com/mem/get-support). 

@yogkumgit

**Comment by yogkumgit** [comment]
@mmelkersen Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
