### ISSUE TITLE
Deprecated - MAM ?

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/memdocs#3365]
Please update documentation and state that MAM is deprecated for Windows and should not be used anymore. Please check with product group if needed.

As per statement from - https://techcommunity.microsoft.com/t5/windows-it-pro-blog/announcing-the-sunset-of-windows-information-protection-wip/ba-p/3579282
> A: After December 2022 customers will not be able to configure any new WIP policies for devices registered via [MEM without enrollment](https://docs.microsoft.com/en-us/mem/intune/fundamentals/deployment-guide-enrollment-mamwe). This does not apply to devices enrolled into MEM.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 27e8db50-59e4-79a2-5d93-933457b4175f
* Version Independent ID: 1af97289-d517-d893-299e-7eb505d64dbb
* Content: [Mobile Application Management (MAM) for unenrolled devices in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/fundamentals/deployment-guide-enrollment-mamwe)
* Content Source: [memdocs/intune/fundamentals/deployment-guide-enrollment-mamwe.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/deployment-guide-enrollment-mamwe.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by msbemba** [comment]
@hkusulja Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3407

Once the author approves, the changes will be live.

Thanks
Sri
