### ISSUE TITLE
Flawed Multi-Tenant Design Prompts Microsoft to Ask Everyone to Play Nicely

### ISSUE THREAD

**Issue by Tb0n3D** [MicrosoftDocs/memdocs#3375]
Everything in this article is accurate and it does offer a way to prevent "Device registered by another tenant" errors. Of course, it requires that every customer, partner, manufacturer, vendor and repair facility abide by the recommendations set forth in this article. Hardly a realistic solution. 

It also doesn't address the customers who have scores of devices that they can't enroll because the hash exists in another tenant. Microsoft's solution for customers is to open a case and then provide proof of purchase for each device. Requiring proof of purchase from a customer who has purchased 150k devices over a multi-year period is prohibitively time consuming.  Microsoft should provide an expedited service for enterprise level customers who are experiencing this problem. This is, after all, a record management problem in Azure. 

Again, if everyone performed the actions laid out in this article, we wouldn't have this problem. But that's not the world we live in. On the hand, if Microsoft created a better way of fixing these records once there is a problem... well, we would still have these problems, but at least it would be better. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8c91281a-bdba-ff2d-6cb5-7ac45396397e
* Version Independent ID: 1a9e425f-7977-66be-eeb5-b41646de2d52
* Content: [Windows Autopilot motherboard replacement](https://learn.microsoft.com/en-us/mem/autopilot/autopilot-mbr?source=docs)
* Content Source: [memdocs/autopilot/autopilot-mbr.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/autopilot-mbr.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
Thank you for the feedback @Tb0n3D. The feedback here is more intended for documentation feedback and not product feedback. In other words, issues in the docs themselves. I would recommend providing this feedback directly in the product itself. I believe the Intune portal has areas that you can provide feedback. I can tell you that we have worked closely with some OEMs to ensure that they properly wipe device ownership during motherboard swaps. We are in the process of updating docs to reflect this and there should be an update soon.

I'm closing this issue as there's nothing actionable for docs at this time.
