### ISSUE TITLE
The Company Portal device page content does not showing well in dark theme of browser 

### ISSUE THREAD

**Issue by JimmyLS** [MicrosoftDocs/memdocs#3376]
When end-user attempts to use the Company portal website devices page (https://portal.manage.microsoft.com/devices) in dark theme of browser, lot of content & device options (like rename, remove, etc) could not show up correctly. User Experience like below:

<img width="669" alt="image" src="https://user-images.githubusercontent.com/25541899/202954754-99a00a1d-16db-42d2-8f1a-c77ffa81ee06.png">

<img width="675" alt="image" src="https://user-images.githubusercontent.com/25541899/202954445-9d498505-ee00-4f1c-a13b-3107ca17df7b.png">

This looks like a bug of this website because we can repro the issue by using either Edge/Chrome browser. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 48cf2acc-8fc5-b70f-8e61-e53b24f358da
* Version Independent ID: 25b150b9-9b03-0c0f-6002-0e59ec1701a7
* Content: [Using the Intune Company Portal website](https://learn.microsoft.com/en-us/mem/intune/user-help/using-the-intune-company-portal-website)
* Content Source: [memdocs/intune/user-help/using-the-intune-company-portal-website.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/using-the-intune-company-portal-website.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@JimmyLS Thank you for your feedback. I was able to replicate this in a dark theme. This sounds like a design change request and I'd recommend you post this on our main feedback portal ( https://feedbackportal.microsoft.com) so that a dev/prodcut engineer will be able to provide assistance.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@JimmyLS Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
