### ISSUE TITLE
What about how Android is detected as either Personal or Corporate?

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/memdocs#338]
Hello,

I noticed that Android's section here doesn't mention anything about when an Android will be deemed personally owned or corporate-owned, while Windows and iOS/iPadOS both do show this info.  Is there anything that can be added here for Android?

I would suggest a statement to add but I'm not savvy enough.  I'm still unable to even decipher if Android enrollment requires Android Enterprise to be setup (or the older/less-supported Android Device Administrator), or if these things are purely optional.  If you can answer this too, that would be great.

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e8c2d91-8808-a504-da13-526b152a5cfe
* Version Independent ID: 037b60a6-d6b5-75ad-1933-39d0f7a69048
* Content: [Set enrollment restrictions in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/enrollment-restrictions-set#blocking-personal-windows-devices)
* Content Source: [memdocs/intune/enrollment/enrollment-restrictions-set.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/enrollment-restrictions-set.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
(7401951)

**Comment by JeremyTBradshaw** [comment]
I've since realized the answer to this question lives in another article (pre-loading IMEI's into Devices > Enroll Devices > Corporate Device Identifiers).  Closing this.
