### ISSUE TITLE
about:intunehelp doesn't exisit anymore

### ISSUE THREAD

**Issue by BurgerhoutJ** [MicrosoftDocs/memdocs#3382]
Hi,

Under the section [Use Edge for iOS and Android to access managed app logs](https://learn.microsoft.com/en-us/mem/intune/apps/manage-microsoft-edge#use-edge-for-ios-and-android-to-access-managed-app-logs), there is mentioned that you can use `about:intunehelp` for troubleshooting. But this URL has been changed to `edge://intunehelp/`.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a31e5a24-4f06-9e36-eacb-689bed95cd59
* Version Independent ID: ede9248e-1114-3e1a-9e80-34e5fe547707
* Content: [Manage Edge for iOS and Android with Intune](https://learn.microsoft.com/en-us/mem/intune/apps/manage-microsoft-edge)
* Content Source: [memdocs/intune/apps/manage-microsoft-edge.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/manage-microsoft-edge.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@BurgerhoutJ Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3408

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @BurgerhoutJ Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
