### ISSUE TITLE
Make sure not to target both win32 and LOB apps to the same device.

### ISSUE THREAD

**Issue by LookoutHill** [MicrosoftDocs/memdocs#3384]
How about a link to some supporting knowledge that explains why?!? This seems like a pretty big throwaway comment.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c0f572e0-1bc0-6f14-7f60-989eb67fb7e7
* Version Independent ID: e4ec5b25-d9a6-d260-6cf6-ff4f3eb3ecb8
* Content: [Windows Autopilot for pre-provisioned deployment](https://learn.microsoft.com/en-us/mem/autopilot/pre-provision)
* Content Source: [memdocs/autopilot/pre-provision.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/pre-provision.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
Thank you for the feedback @LookoutHill. The reason why is explained in the following docs:

https://learn.microsoft.com/mem/intune/apps/lob-apps-windows

I will add a link to this page to make finding the reason why easier.
