### ISSUE TITLE
Prerequisites outdated for iOS version?

### ISSUE THREAD

**Issue by pgdrews** [MicrosoftDocs/memdocs#3386]
Am I not mistaken, that now that iOS 16 is out, for PREREQUISITES on this page should be "Device running iOS 14.0 and later" ?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4afb785e-fdfb-ab5d-109f-9f21b58451d2
* Version Independent ID: 06757d5d-fae0-f983-80cc-75a876b7ff75
* Content: [Set up iOS device access to your company resources](https://learn.microsoft.com/en-us/mem/intune/user-help/enroll-your-device-in-intune-ios)
* Content Source: [memdocs/intune/user-help/enroll-your-device-in-intune-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/enroll-your-device-in-intune-ios.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@pgdrews Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3409

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @pgdrews Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
