### ISSUE TITLE
Slow processing of Imported Admin Templates on Endpoints

### ISSUE THREAD

**Issue by durrante** [MicrosoftDocs/memdocs#3388]
Hi there,

I've noticed that when using imported ADMX templates that the deployment of the settings to endpoints takes a LOT longer than normal for admin templates, is this to be expected? For example, Google Update ADMX, imported weeks ago, I made a change to a setting, all my endpoints (including freshly built) took a lot longer to update locally and then update their status within the tenant.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 798b808e-3d04-6965-c1a4-cbd4b685bb19
* Version Independent ID: 798b808e-3d04-6965-c1a4-cbd4b685bb19
* Content: [Import custom and third party partner ADMX templates in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/configuration/administrative-templates-import-custom#what-you-need-to-know)
* Content Source: [memdocs/intune/configuration/administrative-templates-import-custom.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/administrative-templates-import-custom.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by msbemba** [comment]
@durrante Thank you for your feedback. It is definitely not normal to take longer when using admin templates, this could be a bug on the tenant and I'd recommend you contact support via the help and support section on the admin center so that a Microsoft support engineer can assist and escalate if need be.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @durrante Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
