### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by SrDirko** [MicrosoftDocs/memdocs#3396]
![image](https://user-images.githubusercontent.com/51033218/204400522-07f0275d-59c2-4f8f-ae59-a0b57008224f.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 65fe2aaf-92db-2355-58da-d713ff94bc1d
* Version Independent ID: a7f55b77-717d-62f0-1b4f-733539e6da02
* Content: [Connect to the Data Warehouse with Power BI - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/developer/reports-proc-get-a-link-powerbi#azure-ad-and-intune-credential-requirements)
* Content Source: [memdocs/intune/developer/reports-proc-get-a-link-powerbi.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/developer/reports-proc-get-a-link-powerbi.md)
* Service: **microsoft-intune**
* Sub-service: **developer**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@SrDirko Thank you for your feedback. I'm sorry you are having trouble connecting to the data warehouse. Since this is a technical issue, I'd recommend you contact support via the help and support option in the admin center so that a support engineer can assist you in fixing this.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @SrDirko Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
