### ISSUE TITLE
Microsoft Store app (legacy) only, Microsoft Store app (new) option missing

### ISSUE THREAD

**Issue by ChrisLansdall** [MicrosoftDocs/memdocs#3398]
If I add a new Windows app at the Select app type stage I only see Microsoft Store app (legacy) option. Is there a prerequisite that I've missed?

![image](https://user-images.githubusercontent.com/119419180/204528118-2af2e6ef-cfc7-414f-af20-003e9b754f1d.png)
 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e2bdd473-2cca-8b38-71d0-5ac1e823fdeb
* Version Independent ID: e2bdd473-2cca-8b38-71d0-5ac1e823fdeb
* Content: [Add Microsoft Store apps to Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/apps/store-apps-microsoft)
* Content Source: [memdocs/intune/apps/store-apps-microsoft.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/store-apps-microsoft.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Paparacco** [comment]
Same issue in my tenant..
Any suggestions?
thanks a lot!

**Comment by msbemba** [comment]
@ChrisLansdall Thank you for your feedback. I'm able to replicate the issue. Will update the document accordingly.

Thanks
Sri

**Comment by msbemba** [comment]
@ChrisLansdall and @patrykprzep Thank you for your feedback. We have fixed the portal, and the option should be available now.

![image](https://user-images.githubusercontent.com/45987684/205580033-91d2b694-2d94-4228-a8b5-37ea046ee83c.png)

Hope this helps!

Thanks
Sri

**Comment by ChrisLansdall** [comment]
Hi Sri,

I can confirm that I now see the option.
Thank you.

Kind regards, Chris
