### ISSUE TITLE
Apple Store (Retail)

### ISSUE THREAD

**Issue by walkintom** [MicrosoftDocs/memdocs#34]
Would it be possible to add the bundle ID for the Apple Store (Retail) app - this appears to be a bundled app too now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b2b66b-11cc-ff00-fa15-ec4627c4124f
* Version Independent ID: d7d5ba1b-a933-f89e-fa7a-4238d6cf86d2
* Content: [iOS/iPadOS bundle IDs for built-in apps in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/bundle-ids-built-in-ios-apps#feedback)
* Content Source: [memdocs/intune/configuration/bundle-ids-built-in-ios-apps.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/bundle-ids-built-in-ios-apps.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@walkintom Absolutely. Feel free to add it in a pull request, and we'll get it merged ASAP.

**Comment by MandiOhlinger** [comment]
@walkintom Thank you for making the change. I'll get merged today. Closing this PR, as ID is added in https://github.com/MicrosoftDocs/memdocs/pull/38.
