### ISSUE TITLE
Microsoft Store block after Store for Business retirement

### ISSUE THREAD

**Issue by Dirk-Manderin** [MicrosoftDocs/memdocs#3400]
In the note under _Store group policies restrictions_, it states:

_If you would like to block installation of arbitrary applications from the Store application by the end user without blocking the Intune and Windows Package Manager store integration, set Store\Only display the private store within the Microsoft Store to Enabled._

I'd like some clarification around what happens if that setting is Enabled when the Microsoft Store for Business goes away in February.    Will it still effectively block users from being able to access the full Microsoft Store?  Ideally, with this new deployment method we would be able to finally disable the Microsoft Store in Windows altogether, but it doesn't appear that is the case.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e2bdd473-2cca-8b38-71d0-5ac1e823fdeb
* Version Independent ID: e2bdd473-2cca-8b38-71d0-5ac1e823fdeb
* Content: [Add Microsoft Store apps to Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/apps/store-apps-microsoft)
* Content Source: [memdocs/intune/apps/store-apps-microsoft.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/store-apps-microsoft.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@Dirk-Manderin Thank you for your feedback. Once Microsoft Store for Business is deprecated in February the block should still be in place to access the full Microsoft Store.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Dirk-Manderin Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
