### ISSUE TITLE
Intune for Linux (Ubuntu 20.04) missing dependency

### ISSUE THREAD

**Issue by thrdgeek** [MicrosoftDocs/memdocs#3403]
Ubuntu 20.04 instructions create a dependency error:
sudo apt install intune-portal
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
intune-portal : Depends: msalsdk-dbusclient (>= 1.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

If I try to install that missing package, it refers to another missing dependency and so on .....

What is next?

**Comment by Brenduns** [comment]
@thrdgeek  This feedback arrived unattached to an article for context. Can you provide that missing context?

**Comment by thrdgeek** [comment]
I found the missing dependency in my environment is located on the backport repo which we do not currently sync.  I created a work around for it.

function pre_install_config () {
	# Pre-Install Configuration
	echo "INFO: Initializing Pre-Install Configuration"
	install -o root -g root -m 644 /${LANDSCAPE_ATTACHMENTS}/microsoft.gpg /usr/share/keyrings/
	[ -f /etc/apt/sources.list.d/microsoft-ubuntu-focal-prod.list ] && rm -f /etc/apt/sources.list.d/microsoft-ubuntu-focal-prod.list
	case ${OS_RELEASE} in
        20.04)
            sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/ubuntu/20.04/prod focal main" > /etc/apt/sources.list.d/microsoft-ubuntu-focal-prod.list'
			sh -c 'echo " "  >> /etc/apt/sources.list.d/repo.list'
			sh -c 'echo "# Temp repo for Intune install"  >> /etc/apt/sources.list.d/repo.list'
			sh -c 'echo "deb http://internalrepo/ubuntu focal-backports main universe multiverse restricted" >> /etc/apt/sources.list.d/repo.list'
            ;;
        22.04)
            sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/ubuntu/22.04/prod jammy main" > /etc/apt/sources.list.d/microsoft-ubuntu-jammy-prod.list'
			sh -c 'echo " "  >> /etc/apt/sources.list.d/repo.list'
			sh -c 'echo "# Temp repo for Intune install"  >> /etc/apt/sources.list.d/repo.list'
			sh -c 'echo "deb http://internalrepo/ubuntu jammy-backports main universe multiverse restricted" > /etc/apt/sources.list.d/repo.list'
            ;;
	esac
}
