### ISSUE TITLE
Disabled Setting

### ISSUE THREAD

**Issue by mattsmacblog** [MicrosoftDocs/memdocs#3410]
The Disabled setting doesn't seem to do what it says here:

Disabled. If you don't want to enable Windows Hello for Business during device enrollment, select this option. When disabled, users can't provision Windows Hello for Business. When set to Disabled, you can still configure the subsequent settings for Windows Hello for Business even though this policy won't enable Windows Hello for Business.

The only subsequent setting you can configure is "Use security keys for sign-in" when picking Disabled.

These 3 settings in general don't really work as you'd expect them to either.  There needs to be a "Required" you have to create a PIN/Biometrics. Available, you can set a PIN/Biometrics if you want and you can turn it off if you want. Disabled it's Off you can't set a PIN/Biometrics at all, any set PIN's / Biometrics get wiped out.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d6d32682-0e4e-449b-6ad5-001c631735d2
* Version Independent ID: 66419be7-51dc-f5e1-cf18-1a55866e4193
* Content: [Configure a tenant-wide Windows Hello for Business policy with Microsoft Intune - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/windows-hello)
* Content Source: [memdocs/intune/protect/windows-hello.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/windows-hello.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@mattsmacblog Thank you for your feedback. That's a great idea, this is more of a design change or a new feature request, so I'd recommend you post this directly on our feedback portal(https://feedbackportal.microsoft.com/) so that the dev/prodcut team can update you on this. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@mattsmacblog Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
