### ISSUE TITLE
Shell script link is broken.

### ISSUE THREAD

**Issue by Inthedriversseat** [MicrosoftDocs/memdocs#3411]
Link [Intune Shell Script Samples - Company Portal](https://github.com/microsoft/shell-intune-samples/tree/master/macOS)
is broken, should point to https://github.com/microsoft/shell-intune-samples/blob/master/Apps/Company%20Portal/readme.md or similar link.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 350323ac-7941-3fb1-6166-10a5130351e2
* Version Independent ID: f4512958-ce42-e9eb-7ea0-77d68ebd39b8
* Content: [Add the Company Portal for macOS app - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/apps/apps-company-portal-macos)
* Content Source: [memdocs/intune/apps/apps-company-portal-macos.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/apps-company-portal-macos.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@Inthedriversseat Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3455

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by msbemba** [comment]
@Inthedriversseat The original link has been fixed.

**Comment by tiburd** [comment]
@msbemba 
Thank you! ...Closing this issue.

cc: @yogkumgit
