### ISSUE TITLE
How long for data to show in log analytics workspace?

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/memdocs#3415]
The FAQ provides timing info about storage accounts and event hubs, but does not mention log analytics workspace. Please provide some information about what we should expect when diagnostic information is being sent to that option. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b1cee1ad-3f38-5bde-09a3-32742d8d39cd
* Version Independent ID: bf4cf7d8-e162-80ec-98b0-e46b452e44cb
* Content: [Route logs to Azure Monitor using Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/fundamentals/review-logs-using-azure-monitor)
* Content Source: [memdocs/intune/fundamentals/review-logs-using-azure-monitor.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/review-logs-using-azure-monitor.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by yogkumgit** [comment]
@MandiOhlinger Please help us in resolving this issue. Thanks
