### ISSUE TITLE
Incorrect links

### ISSUE THREAD

**Issue by Dirk-Manderin** [MicrosoftDocs/memdocs#3418]
These links appear to be incorrect, as they point back to this page:

Add the iOS apps so that they can be deployed to the device. For more information, see [Add iOS store apps to Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/enrollment/ios-ipados-app-configuration-policies).

Create a policy for each Microsoft app as described in [Add app configuration policies for managed iOS/iPadOS devices](https://learn.microsoft.com/en-us/mem/intune/enrollment/ios-ipados-app-configuration-policies).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2bb725be-602c-3e3d-3a98-2dafae782d14
* Version Independent ID: 2296613e-3a28-f8d6-08f2-d40b3d3b3a44
* Content: [iOS/iPadOS security app configuration policies - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/enrollment/ios-ipados-app-configuration-policies)
* Content Source: [memdocs/intune/enrollment/ios-ipados-app-configuration-policies.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/ios-ipados-app-configuration-policies.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@Dirk-Manderin Thank you for your feedback. We have updated the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3454

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Dirk-Manderin Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
