### ISSUE TITLE
GCCH

### ISSUE THREAD

**Issue by J227668** [MicrosoftDocs/memdocs#3423]
Can you please confirm if these steps should work for GCCH? If not, can you please note that in the guidance? 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 43ae0d4a-eefd-7770-b2a4-d4f72f7272a3
* Version Independent ID: 1001276c-ddd3-14bd-cd5e-74ce47490d19
* Content: [Manually add the Windows 10 Company Portal app - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/apps/store-apps-company-portal-app#feedback)
* Content Source: [memdocs/intune/apps/store-apps-company-portal-app.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/store-apps-company-portal-app.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@J227668 Thank you for your feedback. Yes, the steps are the same for GCCH as well. For more information, see, Deploying apps using Intune on the GCC High and DoD Environments (https://learn.microsoft.com/en-us/mem/intune/apps/apps-deploy-gcc-dod)

Hope this helps!

Thanks
Sri
