### ISSUE TITLE
CName on External DNS

### ISSUE THREAD

**Issue by russrimm** [MicrosoftDocs/memdocs#343]
Doesn't the cname need to be on internal DNS also in order for the CMG Connection Point to be able to properly resolve the CMG fqdn?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3acff1ed-7ee4-df59-c29a-92e19585f0be
* Version Independent ID: 14f12770-6c44-0407-5445-6ca03527d23e
* Content: [CMG Certificates - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/certificates-for-cloud-management-gateway)
* Content Source: [memdocs/configmgr/core/clients/manage/cmg/certificates-for-cloud-management-gateway.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/cmg/certificates-for-cloud-management-gateway.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @russrimm for the question. It's definitely needed externally for the certificate from a public provider. Depending upon the environment's DNS infrastructure, it's possible another record may be needed elsewhere, but I would assume in general most internal devices can resolve from the external/public DNS. 😄 I don't want to get into the finer points of DNS management in this article, so closing this issue.
