### ISSUE TITLE
The year date information in the Note and the example is different

### ISSUE THREAD

**Issue by TaehyungAlexKim** [MicrosoftDocs/memdocs#3432]
[Enter feedback here]
The year date (2018) presented in the example description of the Datakey Range Filters item differs from the year date (2019) described in the Note.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1197470e-4be2-3dd3-c47d-efb6dac2a2f0
* Version Independent ID: 0ef3e215-fa85-385c-dca2-92dda99b6e87
* Content: [Intune Data Warehouse API endpoint - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/developer/reports-api-url)
* Content Source: [memdocs/intune/developer/reports-api-url.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/developer/reports-api-url.md)
* Service: **microsoft-intune**
* Sub-service: **developer**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**
![date](https://user-images.githubusercontent.com/63694948/206229072-5a4b5a9e-4936-4a1a-ac85-0b6654d1954f.png)

**Comment by msbemba** [comment]
@TaehyungAlexKim Thank you for your feedback. We have updated the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3453

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @TaehyungAlexKim Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
