### ISSUE TITLE
‎Reliable Autopilot Enrollment Date

### ISSUE THREAD

**Issue by gutjahr** [MicrosoftDocs/memdocs#3433]
The article says that the enrollment date MIGHT not be 'correct' for Autopilot devices.
Can you please be more specific? In which exact scenarios would this be the case?
(e.g. hardware hash uploaded by vendor?)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 905c303e-4306-38ec-2a30-4852a8c1bc2b
* Version Independent ID: ceb7e815-e19a-386f-902c-6e6bf53d5766
* Content: [View device details with Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/remote-actions/device-inventory)
* Content Source: [memdocs/intune/remote-actions/device-inventory.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/device-inventory.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@gutjahr Thank you for your feedback. The enrollment date might display the time when devices were registered with Autopilot instead of the time when they were enrolled. We have updated the notes to reduce ambiguity.

Hope this helps!

Thanks
Sri

**Comment by gutjahr** [comment]
@msbemba, thanks for the update. For me the most ambiguous part was and still is the word 'MIGHT' :-)
It sounds like not all devices that are registered with Autopilot would show an 'incorrect' enrollment date. What are the different scenarios with those devices and why do they behave differently?

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@gutjahr I see the confusion now. I have removed the word "might" as it always shows the  time when devices were registered with Autopilot instead of the time when they were enrolled. This can be tracked via PR#https://github.com/MicrosoftDocs/memdocs/pull/3457

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @gutjahr Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
