### ISSUE TITLE
The URL for the app store is no longer valid so you cannot add new apps.

### ISSUE THREAD

**Issue by bballpaul4work** [MicrosoftDocs/memdocs#3434]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ded6cdc4-3c0a-ae18-9d9c-b3d5db3c0708
* Version Independent ID: 34a4b4be-cd8b-25b3-49ef-f5142a87b9ef
* Content: [Add Microsoft Store apps to Intune (legacy)](https://learn.microsoft.com/en-us/mem/intune/apps/store-apps-windows)
* Content Source: [memdocs/intune/apps/store-apps-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/store-apps-windows.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@bballpaul4work Thank you for your feedback. The URL for the Microsoft store is working - https://apps.microsoft.com/store/apps

To find the Appstore URL, use the following steps:
Navigate to the [Microsoft Store](https://www.microsoft.com/store/apps).
Search for and select the desired app.
Click the Endpoint Manager link to display the Microsoft Endpoint Manager Details dialog box.
Copy the Link for Intune and use that link as the Appstore URL when adding the app to Intune.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @bballpaul4work Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
