### ISSUE TITLE
Sign Out Button?

### ISSUE THREAD

**Issue by mattsmacblog** [MicrosoftDocs/memdocs#3436]
There's a lot of options here for Sign-Out and Auto-Sign Out.  Wondering is there no option for Adding a dedicated SignOut button if you've also turned on the Auto-Sign Out feature to log inactive users out?

Also why no option for a Home Button on this bar?  "Floating" and "Swipe Up" but a sign out and home button would fit nicely on the Bar in this picture:   https://imgur.com/a/qn4ZB7D

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ff4c5218-bbe4-110c-c74d-3eed1179ac61
* Version Independent ID: b7c148dc-574b-fbed-7637-29699f3eb97a
* Content: [Configure the Microsoft Managed Home Screen app - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/apps/app-configuration-managed-home-screen-app)
* Content Source: [memdocs/intune/apps/app-configuration-managed-home-screen-app.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/app-configuration-managed-home-screen-app.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@mattsmacblog Thank you for your feedback. This sounds more like a new feature or design change request and I'd recommend you post it in our main feedback portal(https://feedbackportal.microsoft.com/), so that the dev or product team can update you on the same.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@mattsmacblog Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
