### ISSUE TITLE
Minor update needed

### ISSUE THREAD

**Issue by jsaccc75** [MicrosoftDocs/memdocs#3437]
The document currently says "At any time, users can open the Company Portal app, Settings > Sync". 

In iOS the steps are actually Company Portal app, Devices > Check Status.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 14c045c9-2ccb-e24b-9eaa-bfd65b64a48c
* Version Independent ID: 355e928b-5ad8-ac1d-24d4-1d2e8f11cb4d
* Content: [Troubleshoot device profiles in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/configuration/device-profile-troubleshoot#how-long-does-it-take-for-devices-to-get-a-policy-profile-or-app-after-they-are-assigned)
* Content Source: [memdocs/intune/configuration/device-profile-troubleshoot.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/device-profile-troubleshoot.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by msbemba** [comment]
@jsaccc75 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3451

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit The PR has been merged. Issue can be closed.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jsaccc75 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
