### ISSUE TITLE
About Unsupported functionality

### ISSUE THREAD

**Issue by lfinjapan** [MicrosoftDocs/memdocs#3450]
[Enter feedback here]
Hi, Erikre

Could you please tell me what exactlly "Device provisioning" means about  below Unsupported functionality? 
Does is mean provisioning package not support Micorosft Store UWP app, or Micorosft Store UWP app should not be assigned to device group.

**Device provisioning of Microsoft Store Universal Windows Platform (UWP) applications are not supported.**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e2bdd473-2cca-8b38-71d0-5ac1e823fdeb
* Version Independent ID: e2bdd473-2cca-8b38-71d0-5ac1e823fdeb
* Content: [Add Microsoft Store apps to Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/apps/store-apps-microsoft)
* Content Source: [memdocs/intune/apps/store-apps-microsoft.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/store-apps-microsoft.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@lfinjapan Thank you for your feedback. You are right, the provisioning package does not support the Micorosft Store UWP app.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @lfinjapan Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
