### ISSUE TITLE
Incorrect link on this page

### ISSUE THREAD

**Issue by Exzakto** [MicrosoftDocs/memdocs#3452]
This page has a link named "Enable Windows automatic enrollment".

It links to [here](https://learn.microsoft.com/en-us/mem/intune/enrollment/windows-enroll#windows-auto-enrollment-and-device-registration). But it should link to [here](https://learn.microsoft.com/en-us/mem/intune/enrollment/windows-enroll#enable-windows-automatic-enrollment) instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80a7404e-d660-fb5c-a18d-857caf9b7c4c
* Version Independent ID: 9adec0b6-7b1b-c1df-46fb-8a344110cfdb
* Content: [Windows Autopilot configuration requirements](https://learn.microsoft.com/en-us/mem/autopilot/configuration-requirements)
* Content Source: [memdocs/autopilot/configuration-requirements.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/configuration-requirements.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by PhillyUrbs** [comment]
@frankroj This is fixed in PR #9336 in the private branch.

**Comment by frankroj** [comment]
Fixed in PR# https://github.com/MicrosoftDocs/memdocs-pr/pull/9336
