### ISSUE TITLE
Autopilot reset primary user not updated

### ISSUE THREAD

**Issue by pmalyn** [MicrosoftDocs/memdocs#3456]
This page states "When Autopilot reset is used on a device, the device's primary user will be removed. The next user who signs in after the reset will be set as the primary user."

This does not work. We have Autopilot reset several devices using both local device reset and intune then issued the device to a new user. The reset works but the primary user does not get updated to the new user.

Is there some configuration required to make this work that is missing from the documentation? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8411fd84-8a1d-28e6-1535-30143be7ede2
* Version Independent ID: 4e5ecbe1-aa9b-cfa0-7b67-1ac1dcb0c465
* Content: [Windows Autopilot Reset](https://learn.microsoft.com/en-us/mem/autopilot/windows-autopilot-reset)
* Content Source: [memdocs/autopilot/windows-autopilot-reset.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/windows-autopilot-reset.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
Thanks @pmalyn for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems. At this time, we are not aware of anything missing from the documentation. I want to make sure you get to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
