### ISSUE TITLE
Limit of 10 devices for enrollment managers

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/memdocs#346]
Can an explanation for why this limit please be provided?  The linked article says nothing about it.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef08086b-dca6-2788-5669-c5c2aecc9b04
* Version Independent ID: e4c5afd1-a9bb-6f82-e36c-cb32c365cd30
* Content: [Enroll Android Enterprise work profile devices in Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/android-work-profile-enroll)
* Content Source: [memdocs/intune/enrollment/android-work-profile-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/android-work-profile-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
(7402074)

**Comment by ErikjeMS** [comment]
@JeremyTBradshaw Here's the response from the PM: This a limitation that comes from Managed Google Play on the Google side.  Google informed us directly and I'm not aware of a public reference to it.
