### ISSUE TITLE
MDE as tunnel App and MTD - instructions confusing

### ISSUE THREAD

**Issue by gbms311** [MicrosoftDocs/memdocs#3465]
This section does not make sense. It is talking about the MDE app doing both 'defense'/MTD and tunnel functions.

https://learn.microsoft.com/en-us/mem/intune/protect/microsoft-tunnel-configure#use-custom-settings-for-microsoft-defender-for-endpoint

**_If you use Microsoft Defender for Endpoint for MTD but not for Microsoft Tunnel, then you continue to use the app configuration profile to configure Microsoft Defender for Endpoint._**

We are on a page talking about the MDE client, on Android,  being configured to tunnel traffic. 
Shouldn't the sentence read .....

**_If you use Microsoft Defender for Endpoint for Microsoft Tunnel BUT NOT MTD , then you continue to use the app TUNNEL configuration profile to configure Microsoft Defender for Endpoint AS A TUNNEL CLIENT_**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4538f49d-8c19-9227-0acf-77bef7f8d4a8
* Version Independent ID: 1b1b2c40-1fd8-3909-37ae-05ab0d27efb5
* Content: [Install and configure Microsoft Tunnel VPN solution for Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/microsoft-tunnel-configure#use-custom-settings-for-microsoft-defender-for-endpoint)
* Content Source: [memdocs/intune/protect/microsoft-tunnel-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/microsoft-tunnel-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@gbms311 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3499

Once the author approves, the changes will be live.

Thanks
Sri
