### ISSUE TITLE
There is no GPO setting to enable Health Monitoring for updates

### ISSUE THREAD

**Issue by lexios** [MicrosoftDocs/memdocs#3466]
There is no GPO or Configuration Manager equivalent setting for clients that use Endpoint Analytics via Configuration Manager.
One that is using Hybrid (Configuration Manager + Intune) with Hybrid Azure AD Join and CoManagement, will be required to move the critical workload "Device Configuration" for this policy to apply on machines.

Is there another way to set this up other than a Configuration Profile?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c822884d-e84d-01fa-f7ba-503e08437dd8
* Version Independent ID: 8774dbd5-d8bc-e1c9-99cc-adca3e640423
* Content: [Create a Windows Health Monitoring profile in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/configuration/windows-health-monitoring)
* Content Source: [memdocs/intune/configuration/windows-health-monitoring.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/windows-health-monitoring.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by lexios** [comment]
I had a call from Intune Technical Support about this, and it seems that this is the only method to do this.
There is no support for this configuration to be applied otherwise.
Relevant Case -if helpful- is 2212191420000132 so you can verify on your end.

It would be nice to add this to the documentation.
CoManaged devices are required to have the Device Configuration workload migrated to Intune.

**Comment by MandiOhlinger** [comment]
@lexios Can you create a pull request with your recommended changes? I _think_ I understand what you mean but it'd be great to read what you/support team found in your words, if that makes sense.

**Comment by MandiOhlinger** [comment]
@lexios The article is updated to include this information. The changes should be live later today sometime. Thank you!

FYI @yogkumgit
