### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by jsantoro339as** [MicrosoftDocs/memdocs#3467]
[Enter feedback here]
We all do it, we all have that oops. but figured I could point it out so you can correct it.  In the paragraph below the word connectivity is spelled connectivty

That is all, just a quick edit and fix for you. 

Windows 10, version 1903 or later, or Windows 11
Windows Pro, Enterprise, or Education editions
An Intune subscription.
Physical devices that support TPM 2.0 and device attestation. Virtual machines aren't supported. The pre-provisioning process uses Windows Autopilot self-deploying capabilities, so TPM 2.0 is required. The TPM attestation process also requires access to a set of HTTPS URLs that are unique for each TPM provider. For more information, see the entry for Autopilot self-Deploying mode and Autopilot pre-provisioning in [Networking requirements](https://learn.microsoft.com/en-us/mem/autopilot/networking-requirements#tpm).
Network connectivity. Using wireless connectivty requires selecting region, language and keyboard before you are able to connect and start provisioning.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c0f572e0-1bc0-6f14-7f60-989eb67fb7e7
* Version Independent ID: e4ec5b25-d9a6-d260-6cf6-ff4f3eb3ecb8
* Content: [Windows Autopilot for pre-provisioned deployment](https://learn.microsoft.com/en-us/mem/autopilot/pre-provision)
* Content Source: [memdocs/autopilot/pre-provision.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/pre-provision.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
Thank you @jsantoro339as for bringing this to our attention. This has been fixed and should go live in the next day or two.

**Comment by frankroj** [comment]
Fixed as part of PR https://github.com/MicrosoftDocs/memdocs-pr/pull/9484
