### ISSUE TITLE
Deployment action

### ISSUE THREAD

**Issue by lumirjasny** [MicrosoftDocs/memdocs#347]
in the actions is missing the new action "Repair"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2e8cc8c-5c8e-e213-9dab-fdff6a2af3a2
* Version Independent ID: 5274afd1-2eba-7b97-35bc-d51976e799b5
* Content: [Introduction to app management - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/apps/understand/introduction-to-application-management)
* Content Source: [memdocs/configmgr/apps/understand/introduction-to-application-management.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/apps/understand/introduction-to-application-management.md)
* Product: **configuration-manager**
* Technology: **configmgr-app**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @lumirjasny for the feedback. As an introductory article, the intent is not to list all of the possible actions, just give an sense of the basics. Other articles go into more detail on all of the available actions.
