### ISSUE TITLE
Licensing requirements misstake

### ISSUE THREAD

**Issue by Miyu-dev** [MicrosoftDocs/memdocs#3476]
Is the "Endpoint Management + Security" listed in the Licensing requirements a mistake for "Enterprise Mobility + Security"?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 479aa85b-e0c0-49fb-5e02-946a3adbcfca
* Version Independent ID: 479aa85b-e0c0-49fb-5e02-946a3adbcfca
* Content: [Prerequisites for organizational messages](https://learn.microsoft.com/en-us/mem/intune/remote-actions/organizational-messages-prerequisites#policy-requirements)
* Content Source: [memdocs/intune/remote-actions/organizational-messages-prerequisites.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/organizational-messages-prerequisites.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@Miyu-dev Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3497

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Miyu-dev Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
