### ISSUE TITLE
Documentation says Intune Windows device rename limit is 63 characters. The Intune user interface limits new name to 15 characters.

### ISSUE THREAD

**Issue by fdc2005** [MicrosoftDocs/memdocs#3479]
The documentation on this page states:

"Rename a device in Intune... When renaming a Windows device, the new name must follow these rules: Less than or equal to 63 bytes..."

In the Intune user interface, when you rename a device, you are limited to 15 characters. The user interface states (see attached snapshot):

"Enter a new name for this device. The name will take effect the next time the device checks in to Intune. Names must follow these guidelines: 15 characters or less..."

<img width="289" alt="IntuneDialog" src="https://user-images.githubusercontent.com/63527410/209949373-acd8584d-cdc9-42b0-8b0a-919d7cd89a2f.png">

Side note 1: It's 2022 and our devices are AzureAD-joined and Intune-enrolled (no domain controller!). Why must we limit ourselves to the NETBIOS convention of 15 characters? NETBIOS was developed in 1983, when the top grossing movie was Star Wars: Return of the Jedi. Human-readable naming conventions are a nice thing. With the 15-character 1980s limit you end up with JNSM-DT-HM when you could be using JaneSmith-Desktop-Home. 

Side note 2: We are able to rename devices locally on the windows side, to a name with more than 15 characters, and after a sync these longer names appear in Intune. But we are unable to issue a rename request within Intune to a name longer than 15 characters. Why not?

Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ab62517e-47bd-a28d-5907-5fd3841f8504
* Version Independent ID: 765044bd-ef1c-1dc3-c48e-3bbdb602e1c7
* Content: [Rename a device with Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/remote-actions/device-rename)
* Content Source: [memdocs/intune/remote-actions/device-rename.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/device-rename.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by yogkumgit** [comment]
@Smritib17 Please help us in resolving this issue. Thanks

**Comment by boats2000** [comment]
I am current working through the Intune Fast track, this restriction breaks my company's current host name convention.  Netbios is not used anymore.  Also Serial number and a random number are only options for creating a host name, expectation are little higher that that.

**Comment by mselcox** [comment]
Hey folks, this is a limitation with the version of the policy that Intune currently supports. Your feedback that we should switch to the rename policy that supports up to 63 characters is noted and we'll see what we can do. In the meantime, I'd suggest using custom oma-uri [](https://learn.microsoft.com/en-us/mem/intune/configuration/custom-settings-windows-10) to configure the ./DevDetail/Ext/Microsoft/DNSComputerName policy as documented here [](./DevDetail/Ext/Microsoft/DNSComputerName).

**Comment by Smritib17** [comment]
@fdc2005 , to submit product feedback, go to the page (https://learn.microsoft.com/mem/intune/remote-actions/device-rename), scroll to the bottom, and select **Feedback > This product**. Thanks for taking out time to open the issue. Appreciate and encourage you to do the same in future also. Closing this issue.
