### ISSUE TITLE
Session controls step

### ISSUE THREAD

**Issue by MHMahantesh** [MicrosoftDocs/memdocs#3481]
See step number 9 in the section 'Configure Intune to require multifactor authentication at device enrollment'. 

I've 2 questions. 

Is sign-in frequency under 'Session Control' really needed to be configured for device enrollment?

Secondly, I followed all the steps to create the policy in my brand new lab, but I'm not able to choose ''Every Time" as the sign-in frequency. This option for me is greyed out. There is a contextual information that states the following. I quote, "Some of the applications currently selected are not compatible with the "Sign-in frequency" option of "Every time"".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8f28c4b3-8ccc-e353-2ead-65c4022b437a
* Version Independent ID: 643425fd-9969-6322-0735-2bffb125cefc
* Content: [Require multifactor authentication for Intune device enrollment - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/enrollment/multi-factor-authentication?toc=%2Fazure%2Factive-directory%2Fconditional-access%2FTOC.json)
* Content Source: [memdocs/intune/enrollment/multi-factor-authentication.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/multi-factor-authentication.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@MHMahantesh Thank you for your feedback. Sign-in frequency is required for the Session category. The option should not be grayed out, could you provide more information so I can verify if there are apps that don't support this feature?

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @MHMahantesh Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
