### ISSUE TITLE
This option does not exist for adding an App. 

### ISSUE THREAD

**Issue by Coopem16** [MicrosoftDocs/memdocs#3484]
Under section: ### **[Configure the Company Portal app to support iOS and iPadOS devices enrolled with Automated Device Enrollment](https://learn.microsoft.com/en-us/mem/intune/apps/app-configuration-policies-use-ios#configure-the-company-portal-app-to-support-ios-and-ipados-devices-enrolled-with-automated-device-enrollment
)**
In [Microsoft Endpoint Manager admin center](https://go.microsoft.com/fwlink/?linkid=2109431), add the Intune Company Portal app 1. if it has not been added yet, by going to Apps > All apps > Add > Managed devices.
There is not an option to add an App called Managed devices. The admin would either need to add the app via Vpp or as an App store app.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ee33d638-3024-87d5-1b02-c4568478d1ce
* Version Independent ID: fe0f2aa3-b2dc-486a-4883-9c25ee361fe8
* Content: [Add app configuration policies for managed iOS/iPadOS devices - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/apps/app-configuration-policies-use-ios#configure-the-company-portal-app-to-support-ios-and-ipados-devices-enrolled-with-automated-device-enrollment)
* Content Source: [memdocs/intune/apps/app-configuration-policies-use-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/app-configuration-policies-use-ios.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@Coopem16 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3501

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Coopem16 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
