### ISSUE TITLE
PAC Proxies are only supported by Microsoft Edge on Android

### ISSUE THREAD

**Issue by tawammar** [MicrosoftDocs/memdocs#3485]
There should be a note to clarify that PAC proxies are only supported by Microsoft Edge on Android at the moment. Other applications, including Android System WebView, only support proxy host/ip and port.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4538f49d-8c19-9227-0acf-77bef7f8d4a8
* Version Independent ID: 1b1b2c40-1fd8-3909-37ae-05ab0d27efb5
* Content: [Install and configure Microsoft Tunnel VPN solution for Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/microsoft-tunnel-configure)
* Content Source: [memdocs/intune/protect/microsoft-tunnel-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/microsoft-tunnel-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@tawammar Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3500

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
Closing as per PR comment. Thanks
