### ISSUE TITLE
Wrong Link

### ISSUE THREAD

**Issue by itazlin** [MicrosoftDocs/memdocs#3490]
Links to deploy.apple.com
Should be business.apple.com

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e94556e6-69f3-5c56-f77d-01a810473e6a
* Version Independent ID: 8928627b-e085-2660-38dc-bf6a0ce9a6d8
* Content: [Tutorial - Use Apple Business Manager to enroll iOS/iPadOS devices in Intune - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/enrollment/tutorial-use-device-enrollment-program-enroll-ios)
* Content Source: [memdocs/intune/enrollment/tutorial-use-device-enrollment-program-enroll-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/tutorial-use-device-enrollment-program-enroll-ios.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @itazlin, thanks for reaching out to the Microsoft Intune Docs team with your contribution. I am updating this article with the correct links. These changes will be live by the end of the week. 

cc: @yogkumgit
