### ISSUE TITLE
Kme support for corp owned work profile

### ISSUE THREAD

**Issue by SirdiJ** [MicrosoftDocs/memdocs#3505]
Hi, is the page up to date ie, can users use kme with corporate owned work profile too?  

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 91c6e4c4-96e2-14c6-8028-a2b947740e73
* Version Independent ID: 94bd0e7c-03c8-151d-6569-5d12985824e6
* Content: [Automatically enroll Android devices using Samsung's Knox Mobile Enrollment - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/enrollment/android-samsung-knox-mobile-enroll)
* Content Source: [memdocs/intune/enrollment/android-samsung-knox-mobile-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/android-samsung-knox-mobile-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @SirdiJ Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
