### ISSUE TITLE
Confusing title

### ISSUE THREAD

**Issue by ibawwad** [MicrosoftDocs/memdocs#3506]
[Enter feedback here]
The page title is very confusing, it gives the impression that the Activation Lock has been disabled although in fact, it allows having an override code, yet even in the device properties, the activation lock and Find My will show as enabled for the end user.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0dc4921c-d09a-69b3-4e1d-639d51c18cbc
* Version Independent ID: 5026148c-f64e-e824-64da-63fcfa371244
* Content: [Bypass iOS/iPadOS Activation Lock with Intune - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/remote-actions/device-activation-lock-disable)
* Content Source: [memdocs/intune/remote-actions/device-activation-lock-disable.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/device-activation-lock-disable.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by yogkumgit** [comment]
@Smritib17 Please help us in resolving this issue. Thanks

**Comment by Smritib17** [comment]
@ibawwad, thanks for this feedback. The page title comes from the **Device action** menu described in the page "Disable activation lock" and it maintains consistency with the interface. 
Also, activation lock will always be applied when **find my** is enabled – this is an Apple documented behavior: [Activation Lock for iPhone, iPad, and iPod touch - Apple Support. ](https://support.apple.com/en-us/HT201365) This is documented in the Disable activation lock article. 
If you want to submit product feedback, go to the documentation page, scroll to the bottom, and select Feedback > This product.
