### ISSUE TITLE
SafetyNet Attestation discontinuing

### ISSUE THREAD

**Issue by kuglidani** [MicrosoftDocs/memdocs#3510]
Safetynet attestation will be turned down: https://developer.android.com/training/safetynet/deprecation-timeline
How this will affect Intune policies and devices managed by Intune? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dc9c611f-edcb-81fd-b76e-207dd5b3fe04
* Version Independent ID: e5998630-06e9-2051-5d40-1e1509e7fddb
* Content: [Android Enterprise compliance settings in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/compliance-policy-create-android-for-work)
* Content Source: [memdocs/intune/protect/compliance-policy-create-android-for-work.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/compliance-policy-create-android-for-work.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@kuglidani Thank you for your feedback. At this moment, there is no impact and it is getting discontinued gradually after June 2023.  The plan is to replace details for [Play Integrity API](https://developer.android.com/google/play/integrity) which is going to replace Safetynet. The author will be updating details as they get the confirmation.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @kuglidani Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
