### ISSUE TITLE
Check device status is not possible if the device is not compliant

### ISSUE THREAD

**Issue by stalsberg** [MicrosoftDocs/memdocs#3512]
It is not possible to sign in to the Company Portal app on Linux if the device is not compliant. This also makes it impossible to get it compliant in the first place without excluding the user from the compliance policies. The application used to sign in to company portal is also not available in Azure AD for exclusion in conditional access.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3b7097c2-e496-cb8d-70a4-d95ac8da4b0c
* Version Independent ID: 3b7097c2-e496-cb8d-70a4-d95ac8da4b0c
* Content: [Enroll a Linux device in Intune](https://learn.microsoft.com/en-us/mem/intune/user-help/enroll-device-linux)
* Content Source: [memdocs/intune/user-help/enroll-device-linux.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/enroll-device-linux.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by stalsberg** [comment]
@msbemba I know about this, but the issue is that you cannot sign in to the Microsoft Intune app for Linux if the device is not compliant. As the Microsoft Intune app for Linux is also affected by the compliance policies, and there is no way to except it.

**Comment by stalsberg** [comment]
And you cannot enroll either if the device is not compliant before enrolling, which is of course impossible.

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
Email sent to the author to confirm behavior.

**Comment by lenewsad** [comment]
Hi @msbemba, I've reached out to the PM for more help.

**Comment by lenewsad** [comment]
Hi @stalsberg, thank you for reaching out to the Microsoft Intune Docs team. I checked with the product team and confirmed that it is possible to sign in to the Microsoft Intune app on a noncompliant device, so you may need a support person to investigate why this is happening. To confirm, you want to use the Microsoft Intune app, not the Intune Company Portal app. 

If you're still encountering this issue where it's just not letting you enroll or sign in, then please reach out to Intune support. For quick access to support options, sign in to the [Microsoft Intune admin center](https://intune.microsoft.com/ )and go to **Troubleshooting + support** > **Help and support**. 

@msbemba @yogkumgit
