### ISSUE TITLE
Import ADMX not available in Intune console

### ISSUE THREAD

**Issue by EastMaxiumum** [MicrosoftDocs/memdocs#3514]
The Import ADMX feature is no longer available under the "Windows\Configuration Profiles" section. There is a preview feature under the "Create a Profile\Windows 10 & Later\Templates\Imported Administrative Templates (Preview)"
![image](https://user-images.githubusercontent.com/123122895/213565145-9a3e5701-aad3-4e9c-86b5-293ce3bd0aa0.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 798b808e-3d04-6965-c1a4-cbd4b685bb19
* Version Independent ID: 798b808e-3d04-6965-c1a4-cbd4b685bb19
* Content: [Import custom and third party partner ADMX templates in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/configuration/administrative-templates-import-custom)
* Content Source: [memdocs/intune/configuration/administrative-templates-import-custom.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/administrative-templates-import-custom.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by msbemba** [comment]
@EastMaxiumum Thank you for your feedback. I'll test and update the document if need be.

Thanks
Sri

**Comment by EastMaxiumum** [comment]
Have checked again later and the adding of the ADMX, it is possible on the overall Configuration Profiles page, it's just not in the sub-view of Configuration Profiles (Windows). With ADML/ADMX being primarily Windows in the past, it would make sense for it to be added there as well, or notate that it's only available on the overview Configuration Profiles page.

**Comment by msbemba** [comment]
@EastMaxiumum Thank you for your feedback. The steps in the document seem to be accurate, however, if you would like to add them to the Configuration Profiles (Windows), I'd recommend you leave the feedback on our main feedback portal (https://feedbackportal.microsoft.com/) so that a dev/product engineer can help you with the design change.

Hope this helps!

Thanks
Sri
