### ISSUE TITLE
JSON sample is missing a closing curly brace

### ISSUE THREAD

**Issue by tomattto2** [MicrosoftDocs/memdocs#3515]
The sample JSON for the DPC extras has a minor typo that causes it not to work.  The closing curly brace is outside of the sample block, right below it on the page.  So when customers copy and paste this sample it won't include the closing curly brace.  Once pasted into their environment the end result is a failure.  Just need to update the sample and move that closing curly brace into the sample block.  Thanks!  You rock! 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4024ea9e-bd99-03a1-7dd2-5afb73736558
* Version Independent ID: ac95c8b2-ad77-e524-d0da-01449afc0bfd
* Content: [Enroll Android Enterprise dedicated, fully managed, or corporate-owned work profile devices in Intune - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/enrollment/android-dedicated-devices-fully-managed-enroll)
* Content Source: [memdocs/intune/enrollment/android-dedicated-devices-fully-managed-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/android-dedicated-devices-fully-managed-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @tomattto2, thanks for reaching out to the Microsoft Intune Docs team with your contribution! We fixed the code sample and appreciate you reporting the typo to us. That change will be live shortly.
