### ISSUE TITLE
Import CSV guidance specifies group tag and user but does not allow import

### ISSUE THREAD

**Issue by sk1tt1sh** [MicrosoftDocs/memdocs#3519]
The page guidance says to use:
Device Serial Number,Windows Product ID,Hardware Hash,Group Tag,Assigned User

While the import UI validates the file successfully, a 403 error is observed when clicking import and watching the browser console.

To resolve, remove the "Group Tag" and "Assigned User" columns.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ea4a659b-65d0-26ec-c36a-9a21a72a09a8
* Version Independent ID: bff44b73-9021-6659-e212-66349c759989
* Content: [Manually register devices with Windows Autopilot](https://learn.microsoft.com/en-us/mem/autopilot/add-devices)
* Content Source: [memdocs/autopilot/add-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/add-devices.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
Thanks @sk1tt1sh for taking the time to share this with the Windows documentation team. This is a feature that should work. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Microsoft](https://learn.microsoft.com/answers/tags/415/intune). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Windows Autopilot support information](https://support.microsoft.com/windows) to find your available support options.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
