### ISSUE TITLE
Missing ending bracket at the end of JSON code

### ISSUE THREAD

**Issue by pik10** [MicrosoftDocs/memdocs#3520]
I think there is a missing ending bracket } in the JSON configuration code.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4024ea9e-bd99-03a1-7dd2-5afb73736558
* Version Independent ID: ac95c8b2-ad77-e524-d0da-01449afc0bfd
* Content: [Enroll Android Enterprise dedicated, fully managed, or corporate-owned work profile devices in Intune - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/enrollment/android-dedicated-devices-fully-managed-enroll)
* Content Source: [memdocs/intune/enrollment/android-dedicated-devices-fully-managed-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/android-dedicated-devices-fully-managed-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@pik10 Thank you for your feedback. The  ending bracket } is added to the Json.

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit  this can be closed.
