### ISSUE TITLE
Legacy Setup Assistant option not available in Authentication method 

### ISSUE THREAD

**Issue by Alexey-Zheltov** [MicrosoftDocs/memdocs#3522]
Intune Portal offers only "Setup assistant" and "Company portal" options in "Authentication method" drop-down menu.

There is no such parameters:
Setup Assistant (legacy)
Setup Assistant with modern authentication

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd130267-c54b-41e3-d534-831d4a86bae6
* Version Independent ID: bdfa7eca-a356-3dde-7643-9a759f952007
* Content: [Enroll iOS/iPadOS devices with Apple ADE - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-ios?WT.mc_id=EM-MVP-5001447)
* Content Source: [memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@Alexey-Zheltov Thank you for your feedback. We will test and update the document if need be.

Thanks
Sri

**Comment by msbemba** [comment]
@Alexey-Zheltov Thank you for your feedback. From my testing I see the three options, I'd suggest opening up a support ticket via the need help section on the admin center so that a support engineer can review and fix it. 

![image](https://user-images.githubusercontent.com/45987684/215103745-27bac0a3-c547-46b9-9192-c345c4d5b1de.png)


Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Alexey-Zheltov Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
