### ISSUE TITLE
Instructions in the Troubleshoot using per-setting status differ from console.

### ISSUE THREAD

**Issue by AlBrough** [MicrosoftDocs/memdocs#3528]
Error has been italicized 

Troubleshoot using per-setting status
You deployed a security baseline, but the deployment status shows an error. The following steps give you some guidance on troubleshooting the error.

In Intune, _select Endpoint security > Security_ Baselines > select a baseline > Profiles.

Select a profile > Under Monitor > Per-setting status.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d9e34c6-0221-c998-a264-e74be05cf5a3
* Version Independent ID: cb9d4841-45ba-daba-8acb-df6a43ff30d1
* Content: [Check the success or failure of security baselines in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/security-baselines-monitor#troubleshoot-using-per-setting-status)
* Content Source: [memdocs/intune/protect/security-baselines-monitor.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/security-baselines-monitor.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
@AlBrough Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3534

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @AlBrough Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
