### ISSUE TITLE
Users vs Devices vs Filter

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/memdocs#3529]
Hello,

Just to confirm,
If the policy is assigned to All Users and used the Filter to filter All Azure AD Joined devices only,
Then in the Exclude section, we still add the Users group, is it correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cb9f0c71-ac8b-b047-9934-1bffb895e75c
* Version Independent ID: 44f25bbe-ccc6-5480-09b4-cfa18832b0bb
* Content: [Assign device profiles in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/configuration/device-profile-assign#exclude-groups-from-a-profile-assignment)
* Content Source: [memdocs/intune/configuration/device-profile-assign.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/device-profile-assign.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by lightupdifire** [comment]
Like below, is it supported? 
Assigned to All Users,
Filter set to filter only Azure AD Join Devices,
Exclude is the group with users or it should be with devices or this combination is not supported, so Filter should filter all who should be excluded
![image](https://user-images.githubusercontent.com/39700914/214811594-5cfbba02-16d3-4020-8481-688401010743.png)

**Comment by msbemba** [comment]
@lightupdifire Thank you for your feedback. Exclude can be with users or devices, the combination of users and devices should also work.

Hope this helps!

Thanks
Sri

**Comment by lightupdifire** [comment]
@msbemba 
It would be wonderful if this will be explained in this document or in the document for Include/Exclude assignments.
Else a little stuck with using: Assign All Users + Filter Devices + "what to exclude"? :)

**Comment by yogkumgit** [comment]
@msbemba Please comment.

**Comment by msbemba** [comment]
@lightupdifire Thank you for your feedback. We have made changes to the document  via PR#https://github.com/MicrosoftDocs/memdocs/pull/3922

Once the author approves, the changes will be live.

Thanks
Sri
