### ISSUE TITLE
Clarity on Supported Table

### ISSUE THREAD

**Issue by moravindMSFT** [MicrosoftDocs/memdocs#3533]
[Enter feedback here]
Great Article! The table mentioned here https://learn.microsoft.com/en-us/mem/intune/protect/mde-security-integration#which-solution-should-i-use reflects "Attack Surface Reduction Rules - All" is available only via Microsoft Endpoint Manager but there is a next entry which shows "Attack Surface Reduction Rules - Attack Surface Reduction Rules " available via MDE Security Configuration but there is no Green tick mark here. Does it mean only few ASR rules are available via this "Security Management for Microsoft Endpoint" not all ASR policies? Is it correct to understand that Account Protection, Device Compliance, Conditional Access, Security Baselines are not available via this MDE Security Configuration but they are available only via Intune?

For further questions, you may reach out to my alias moravind@microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b166b931-f3f7-3323-7288-758cfa5934f1
* Version Independent ID: b166b931-f3f7-3323-7288-758cfa5934f1
* Content: [Use Intune to manage Microsoft Defender for Endpoint Security on devices not enrolled with Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/mde-security-integration)
* Content Source: [memdocs/intune/protect/mde-security-integration.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/mde-security-integration.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by yogkumgit** [comment]
@Brenduns Please help us in resolving this issue. Thanks
