### ISSUE TITLE
Android Device Password: Prevent Password from Expiring

### ISSUE THREAD

**Issue by davideverall** [MicrosoftDocs/memdocs#3536]
Hi 

Could you please clarify the behaviour if the "Number of days until password expires" field is left blank. Would this result in the password never expiring or is there a default value that the system will revert to?

We would like to prevent the password from expiring, so need to confirm if this is the best way of achieving that.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 900e72be-d42b-49ba-f304-602df23cbb04
* Version Independent ID: 2ce5c45d-15be-d316-1c57-92bea37358e0
* Content: [Corporate-owned Android Enterprise device restriction settings in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/configuration/device-restrictions-android-for-work#device-password)
* Content Source: [memdocs/intune/configuration/device-restrictions-android-for-work.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/device-restrictions-android-for-work.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by msbemba** [comment]
@davideverall Thank you for your feedback. When the value is blank, Intune doesn't change or update this setting, meaning the original value entered in the source (AD/AAD) will take effect and there will be no restrictions. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@davideverall Thank you for your response. Sorry I was responding to computers registered in AD/AAD. For Android devices, when the field is left blank, Intune does not update the setting, in other words, they will not be forced to change the password. This will prevent the password from expiring.

Hope this helps!

Thanks
Sri

**Comment by davideverall** [comment]
Hi

Thanks for the clarification, that setting will work for us!

Feel free to close this issue off now.

David
