### ISSUE TITLE
Word order correction

### ISSUE THREAD

**Issue by tcfinney** [MicrosoftDocs/memdocs#3537]
The first sentence in the last paragraph of the first section, _Resize a Cloud PC (preview)_, the order for "you" and "let" needs to be corrected.

It currently reads "Resizing doesn't **you let** downsize disk space", but it should read "Resizing doesn't **let you** downsize disk space".

Thanks,
TC

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d40c7cfc-19e8-bfc7-5998-701fb4be40f2
* Version Independent ID: 1553fed2-80ac-ae21-1f87-1358bd34878d
* Content: [Resize a Cloud PC (preview)](https://learn.microsoft.com/en-us/windows-365/enterprise/resize-cloud-pc)
* Content Source: [windows-365/enterprise/resize-cloud-pc.md](https://github.com/MicrosoftDocs/memdocs/blob/main/windows-365/enterprise/resize-cloud-pc.md)
* Service: **windows-365**
* Sub-service: ****
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@tcfinney Thanks for pointing that out. I'll fix it today.
