### ISSUE TITLE
Add Fujitsu vendor as supported DFCI device

### ISSUE THREAD

**Issue by dzejzipl** [MicrosoftDocs/memdocs#3542]
As per: https://learn.microsoft.com/en-us/mem/intune/fundamentals/whats-new#week-of-january-23-2023-service-release-2301 to list of supported devices can be added Fujitsu.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9ff03bb5-d771-4d52-8368-def1495ded4a
* Version Independent ID: 8c9d6c92-9c99-bdd0-47f9-df549238d16f
* Content: [DFCI Management](https://learn.microsoft.com/en-us/mem/autopilot/dfci-management)
* Content Source: [memdocs/autopilot/dfci-management.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/dfci-management.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
Thanks for the feedback @dzejzipl. This was updated a few days after you submitted this request via the following PR:

https://github.com/MicrosoftDocs/memdocs-pr/pull/9556
