### ISSUE TITLE
Please elaborate on Hardware Change Detection / Fix Pending

### ISSUE THREAD

**Issue by treestryder** [MicrosoftDocs/memdocs#3550]
Regarding the "Hardware Change Detection / Fix Pending" status, the current English message shown on the detailed Autopilot profile status blade is, "A hardware change was detected on this device. We're trying to automatically register the new hardware. Status will be updated at the next check in."

Could this message be added to the documentation to make it easier to find? Then, could details be added as to the documentation explaining this process further. In particular, what exactly is meant by the "next check-in"? And, how to recover when this process fails?

This recently happened to a PC that would not perform an Intune Wipe, so the tech re-installed Windows. After this, the OOBE acted as though it was unable to communicate with Autopilot. So... the tech deleted the Autopilot and Azure AD objects, to re-import its hardware info.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 54d11e52-9a76-9f06-d40e-463bad0295db
* Version Independent ID: 24d9921a-3b7b-4923-ae2f-d7a641c66a93
* Content: [Tutorial - Use Autopilot to enroll devices in Intune - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/enrollment/tutorial-use-autopilot-enroll-devices)
* Content Source: [memdocs/intune/enrollment/tutorial-use-autopilot-enroll-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/tutorial-use-autopilot-enroll-devices.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by yogkumgit** [comment]
@lenewsad Please help us in resolving this issue. Thanks

**Comment by lenewsad** [comment]
Hi @treestryder @yogkumgit, thank you for reaching out to the Microsoft Intune documentation team with your idea. I've added it to our backlog and will work with the Windows Autopilot team to figure out the best place to document the error message.

**Comment by treestryder** [comment]
Thank you.

**Comment by frankroj** [comment]
Thank you for the feedback @treestryder. We have updated several spots on our documentation to better explain this status and what to do in case you run into this message. We have also added the message displayed when you select Fix Pending so that it is more discoverable. I am going to go ahead and close this feedback item but if you have any additional concerns or feedback, please let us know.

**Comment by treestryder** [comment]
Would you mind please sharing a link to the updated documentation. It does not seem to be the "Content" linked above.

We are still having problems with some PCs failing to enroll, showing an Autopilot profile status of "A hardware change was detected on this device. We're trying to automatically register the new hardware. Status will be updated at the next check in.", after a protected wipe was performed using Intune.

**Comment by frankroj** [comment]
Hello @treestryder. The following articles contain more information about the **Fix Pending** message. Please note that the docs are more informational and aren't intended to be an in-depth troubleshooting guide. If you need additional help with this issue, I recommend opening a case with support:

https://learn.microsoft.com/autopilot/troubleshoot-device-enrollment#autopilot-profile-not-applied-after-reimaging-to-an-older-os-version

https://learn.microsoft.com/autopilot/autopilot-motherboard-replacement

https://learn.microsoft.com/autopilot/tutorial/pre-provisioning/hybrid-azure-ad-join-autopilot-profile#verify-device-has-an-autopilot-profile-assigned-to-it
