### ISSUE TITLE
WSL2 based Ubuntu not supported

### ISSUE THREAD

**Issue by rovinbhandari** [MicrosoftDocs/memdocs#3554]
The doc should be caveated with the detail that Ubuntu on WSL2 is not supported. Currently, it's not possible to decipher that and intune-portal simply hangs while trying to register the virtual device.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3b7097c2-e496-cb8d-70a4-d95ac8da4b0c
* Version Independent ID: 3b7097c2-e496-cb8d-70a4-d95ac8da4b0c
* Content: [Enroll a Linux device in Intune](https://learn.microsoft.com/en-us/mem/intune/user-help/enroll-device-linux)
* Content Source: [memdocs/intune/user-help/enroll-device-linux.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/enroll-device-linux.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@rovinbhandari Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3569

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @rovinbhandari Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
