### ISSUE TITLE
Clarification Required

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/memdocs#3559]
One thing not made clear in the example given is that ALL returned values must be of the data type specified in the JSON.

If you looked for a registry key and it was not present, then the value in the JSON output would be "null", instead of a string or version or integer or whatever the value would be if it were present. The script would exit with result 0 (success) and a valid hash would be returned with @{"ComplianceTest":null}. But Intune would interpret the result as an error, because the value is not of the data type specified in the JSON.

In compliance tests, an error result does not change the existing compliance state. So a device that was compliant, but returned a null value for the compliance test, would remain compliant.

In my opinion, the back end processing of @{"ComplianceTest":null} is wrong, because it is a valid hash, and is not equal to the value required to be compliant, and so is not compliant. This used to be the case in Intune until very recently, but something has changed and it now returns an error. The new way of evaluating the result is fine, as long as it is made clear in the documentation. So I suggest the example is rewritten to give an example of a test that could return a null.

You could go further and say that, since a compliance result is a binary choice, then the script should always be written to provide a boolean output. Either the required compliance value is present, or it is not.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 013a6f8c-7d49-895e-1074-eae97d11b1f6
* Version Independent ID: 013a6f8c-7d49-895e-1074-eae97d11b1f6
* Content: [Create a discovery script for custom compliance policy in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/compliance-custom-script)
* Content Source: [memdocs/intune/protect/compliance-custom-script.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/compliance-custom-script.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by yogkumgit** [comment]
@Brenduns Please help us in resolving this issue. Thanks

**Comment by Brenduns** [comment]
@Air-Git   Thanks for this clear feedback. I've passed this directly to the product team that owns Compliance so they are aware and can investigate this. They will need to provide input before we can revise the script example, or take other possible updates. With that hand-off of information, I'll close this issue for now as we are tracking this internally.  Should this information lead to a content update or additional information to share back, I'll reopen this issue to alert you and/or track that content update.
