### ISSUE TITLE
Silent Bitlocker

### ISSUE THREAD

**Issue by nerfdaderp** [MicrosoftDocs/memdocs#3564]
I'm not sure I understand Silent Bitlocker via Intune (researching into the pba setting as that is erroring on my intune policy). 

If Intune encrypts the device without a PIN or unlocking mechanism, it will seemingly bypass PBA at which point, why even bother encrypting the device to begin with, won't it always be unlocked?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 54cccf1d-81fd-5331-aee7-59a35b39cb15
* Version Independent ID: 81d14392-fe74-4fd9-047f-7b8292d84f0c
* Content: [Encrypt Windows devices with BitLocker in Intune - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/encrypt-devices)
* Content Source: [memdocs/intune/protect/encrypt-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/encrypt-devices.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by yogkumgit** [comment]
@Brenduns Please help us in resolving this issue. Thanks

**Comment by Brenduns** [comment]
@nerfdaderp  This might not be a question we can assist with via the Intune documentation feedback. You seem to be asking a BitLocker behavior question, and not a question about the Intune documentation, and which setting(s) your referencing via ‘PBA’ isn’t clear.

Via Intune policy, the underlying [BitLocker CSP](https://learn.microsoft.com/windows/client-management/mdm/bitlocker-csp) is accessible to be configured via the settings presented, but the functional behaviors of these settings remains owned by the BitLocker team, including  explanations for combinations of BitLocker settings.  If this is still an active question, consider reaching out Windows/BitLocker via the BitLocker documentation for the CSP and setting in question.
