### ISSUE TITLE
Restricting ADE enrollment for some users

### ISSUE THREAD

**Issue by dschuette01** [MicrosoftDocs/memdocs#3573]
Is it possible to block ADE enrollment for some users? Or is it the case that if ADE / Setup Assistant enrollment is turned on that anyone in the tenant can enroll on that device?  I am not seeing this in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd130267-c54b-41e3-d534-831d4a86bae6
* Version Independent ID: bdfa7eca-a356-3dde-7643-9a759f952007
* Content: [Enroll iOS/iPadOS devices with Apple ADE - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-ios)
* Content Source: [memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by yogkumgit** [comment]
@lenewsad Please help us in resolving this issue,. Thanks

**Comment by lenewsad** [comment]
Hi @dschuette01,

Thank you for reaching out to the Microsoft Intune Docs team.  

The easiest way to prevent devices from being enrolled via automated device enrollment is to avoid assigning an automated device enrollment profile to those devices. Just assign the profile to the devices that are permitted to enroll via automated device enrollment. For imore information about that procedure, see [Assign enrollment profile](https://learn.microsoft.com/mem/intune/enrollment/device-enrollment-program-enroll-ios#assign-an-enrollment-profile-to-devices).   

Another option is to use an *enrollmentProfileName assignment filter* to include/exclude device configuration policies and apps from devices that enroll using a specific automated device enrollment profile.  For a list of device properties you can use in assignment filter rules, see [Filter properties](https://learn.microsoft.com/mem/intune/fundamentals/filters-device-properties#device-properties).  For information about how to set up assignment filters, see [Create a filter](https://learn.microsoft.com/mem/intune/fundamentals/filters#create-a-filter).  

At this time, there aren't any documentation changes needed for this issue. Hope this information was helpful. 

CC @yogkumgit

**Comment by dschuette01** [comment]
@lenewsad Thank your for the explanation and your solutions do make sense. I think it still might be beneficial to include in the corporate device enrollment restriction documentation that it is not possible to prevent a user from enrolling on an ADE device that has been assigned an enrollment profile. We purchase all our iOS devices from a wireless carrier and 100% of those devices are automatically assigned the default enrollment profile. Any staff member in our organization who attempts to enroll on one of these devices simply *can*. There is no way to prevent them from doing so, as far as I understand it. We were trying to ensure that only people who were assigned the correct policies via security group would be allowed to enroll on these devices. Otherwise, people enroll on the devices and simply have no policies applied to them at all.
