### ISSUE TITLE
Where is "Education Profile"???

### ISSUE THREAD

**Issue by kcurtis-dnusd** [MicrosoftDocs/memdocs#3591]
I cannot follow Step 2
(https://learn.microsoft.com/en-us/mem/intune/fundamentals/education-settings-configure-ios#step-2---create-and-assign-an-iosipados-education-profile-in-intune)

1. Sign in to [Intune](https://endpoint.microsoft.com/).
2. On the Intune pane, choose Device configuration.
3. On the Device configuration pane under the Manage section, choose Profiles.
4. On the profiles pane, choose Create profile.
5. On the Create profile pane, enter a Name and Description for the iOS/iPadOS education profile.
6. From the Platform drop-down list, choose iOS.
7. **From the Profile type drop-down list, choose Education.** - _This does not exist_
8. Choose Settings > Configure.

At this point, I get lost trying to mimic what I think needs to be done with what is not actually there in Intune.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9bc0159d-5a5e-ea2c-042d-bd5ead842d0b
* Version Independent ID: 83266995-5234-3b09-784d-75bb1844e5f3
* Content: [Intune settings for the iOS/iPadOS Classroom app - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/fundamentals/education-settings-configure-ios)
* Content Source: [memdocs/intune/fundamentals/education-settings-configure-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/education-settings-configure-ios.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@kcurtis-dnusd Thank you for your feedback. Looks like this could be a bug on the tenant. I'd recommend you contact support via the need help section on the admin center, so that our support representative can fix this.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @kcurtis-dnusd Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
