### ISSUE TITLE
Missing RBAC role

### ISSUE THREAD

**Issue by BurgerhoutJ** [MicrosoftDocs/memdocs#3593]
Hi,

I'm missing the new **Organizational Messages Manager** role on the Learn/Docs page. It's visible in my tenant, but not at the webpage. Can you add this role to the docs page?

![image](https://user-images.githubusercontent.com/25769575/219054368-a396a745-2b86-410a-b779-82b81ea35c21.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c3eaa886-918b-127e-ad4b-d829e99b0d44
* Version Independent ID: 87240468-dd25-7f45-740b-f078cd5deac7
* Content: [Role-based access control (RBAC) with Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/fundamentals/role-based-access-control)
* Content Source: [memdocs/intune/fundamentals/role-based-access-control.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/role-based-access-control.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@BurgerhoutJ Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3598

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @BurgerhoutJ Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
