### ISSUE TITLE
Intune fails to login on Linux

### ISSUE THREAD

**Issue by cloudcosmonaut** [MicrosoftDocs/memdocs#3594]
Hey there,

I'm trying to enroll my Linux machine using Intune. But sadly that doesn't work. As initially, when you try to login using Intune, you get the message stating I need to enroll using Intune.

When I started digging in the various log files, I notice `microsoft-identity-broker` is throwing errors that the $JAVA_HOME location does not existing (which is true, as it's hardcoded to point to a specific version that's no longer available (/urs/lib/jvm/java-11-openjdk-amd64/)). To resolve that, I installed the MS builds of JDK-11 and symlinked that on thas specific location and reinstalled intune and it's depedencies.

Now I see that the authentication and hand shaking takes places and the company SSO portal is opened to authenticate me. But that fails with a generic error when I try to enroll the device.

I _did_ save all the logs related to `intune-portal` and `microsoft-identity-broker`, which I can share with you when needed.

Cheers, Hindrik 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80924804-c247-d3bb-2245-fd3db3f3bd62
* Version Independent ID: 80924804-c247-d3bb-2245-fd3db3f3bd62
* Content: [Get the Microsoft Intune app for Linux](https://learn.microsoft.com/en-us/mem/intune/user-help/microsoft-intune-app-linux)
* Content Source: [memdocs/intune/user-help/microsoft-intune-app-linux.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/microsoft-intune-app-linux.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@cloudcosmonaut Thank you for your feedback. This sounds more like a technical issue and I'd recommend you contact Microsoft support via the need help section on the admin center. So that a Support engineer can collect logs and troubleshoot your issue.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @cloudcosmonaut Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
