### ISSUE TITLE
Custom permission for Adding/Changing Windows PowerShell scripts?

### ISSUE THREAD

**Issue by JLambEJG** [MicrosoftDocs/memdocs#3596]
Please document the custom role that is required for technicians to add/change Windows PowerShell scripts in Intune. We have users with the permissions to manage Apps, but they are unable to manage scripts.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ee559326-3f31-4a98-7399-21d571a42d9d
* Version Independent ID: 11eb7dee-44e1-d6bd-76c1-a6327199964d
* Content: [Create a custom role in Intune](https://learn.microsoft.com/en-us/mem/intune/fundamentals/create-custom-role)
* Content Source: [memdocs/intune/fundamentals/create-custom-role.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/create-custom-role.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by yogkumgit** [comment]
@Smritib17 Please help us in resolving this issue. Thanks

**Comment by JLambEJG** [comment]
What is the status of this? Is this incremental permission possible? We want our run-support team to be able to manage scripts without being an Intune Administrator.

**Comment by Smritib17** [comment]
@JLambEJG Thank you for your feedback. I've checked with the team and they confirmed that Powershell script creation and assignment to devices does not have its own permissions or role, it uses Device Configurations permissions. However, you can create a role and if you have permissions to create and assign device configurations, you can assign scripts to run. Hope this helps!

**Comment by yogkumgit** [comment]
@Smritib17 Thank you very much for sharing this explanation. @JLambEJG Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
