### ISSUE TITLE
Feedback about Wi-Fi config for corporate owned devices - undocumented behaviour.

### ISSUE THREAD

**Issue by velGhosT** [MicrosoftDocs/memdocs#3597]
[Enter feedback here]
Hello Team,

I was working with Microsoft Support about the case, where since we delivered Wi-Fi configuration profile to a corporate owned device (controlled by Intune), the Wi-Fi module gets launched (turned ON) even thought it was disabled (turned off) by a user.
Support case: 33949984
Microsoft SMEs concluded that is expected as MDM device profile for corporate owned devices seems to have more permissions than on personally owned ones.

Quotation:
_When a device is marked corporate the user gets to have little control and all control will be with the policies enforced
So when we push wifi profile for the device to be enabled to pick it, by design wifi will be made to turn on and only way to prevent this is to be on airplane mode or i should say like this is not possible as this is a by design behaviour_

Maybe could you include such notes in the article?
Best Regards
Marcin

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3ba02cac-ed62-ad81-b30f-0c72eae1ec06
* Version Independent ID: 336ccf7f-9ad9-05a4-6755-dcfa4ca71920
* Content: [Wi-Fi settings for Android Enterprise and kiosk devices - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/configuration/wi-fi-settings-android-enterprise)
* Content Source: [memdocs/intune/configuration/wi-fi-settings-android-enterprise.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/wi-fi-settings-android-enterprise.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by msbemba** [comment]
@velGhosT Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3599

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @velGhosT Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
