### ISSUE TITLE
Missing permissions

### ISSUE THREAD

**Issue by eschrader** [MicrosoftDocs/memdocs#3600]
What permissions are required to manually enroll devices? Can any user do it with Intune enrollment permissions, or do you need higher rights?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8361a1df-19a6-f364-cecd-a6937f4c6bbd
* Version Independent ID: eb62808e-a86e-8c7f-3a1a-91b939084b5d
* Content: [Manual registration of devices for Windows Autopilot](https://learn.microsoft.com/en-us/mem/autopilot/manual-registration)
* Content Source: [memdocs/autopilot/manual-registration.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/manual-registration.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
Hello @eschrader. This article covers registering a device as an Autopilot device. This isn't the same as enrolling the device in Intune. Registering a device is normally something done by an OEM, reseller, or IT admin. It's not something that is normally done by an end-user. In fact, it would defeat part of the whole purpose of Autopilot where interaction by the end-user is minimized. This is why we don't cover what permissions are needed by users for registering the device as an Autopilot device. For enrolling devices in Intune, the following article covers what needs to be done to allow users to enroll in Intune:

https://learn.microsoft.com/en-us/mem/autopilot/tutorial/user-driven/azure-ad-join-allow-users-to-join

If you are actually looking for what permissions are needed by an Intune admin to add devices as Autopilot devices, the following article describes the different types of Intune admins you can assign to users:

https://learn.microsoft.com/en-us/mem/intune/fundamentals/users-add#give-admin-permissions-in-microsoft-intune-admin-center

If you have additional questions, there are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by frankroj** [comment]
Just another follow up @eschrader. The following link gives further details on what roles are needed by an Intune admin to manage Autopilot devices:

https://learn.microsoft.com/en-us/mem/autopilot/add-devices#required-permissions
