### ISSUE TITLE
Root certificate for server validation

### ISSUE THREAD

**Issue by JasonNMS** [MicrosoftDocs/memdocs#3605]
[Enter feedback here]

Root certificate for server validation: Select one or more existing trusted root certificate profiles. When the client connects to the network, these certificates are presented to the server. They authenticate the connection.

This should be updated to read:

Root certificate for server validation: Select one or more existing trusted root certificate profiles. When the client connects to the network, these certificates are used to authenticate the certificate presented by the server. If your authentication server uses a public certificate, it is not necessary to include a root certificate.

----
I followed the instructions and my Wifi profile would not connect, until I removed the Root certificate.
I had included the Root certificate as I thought it necessary because I am using an internal certificate - issued by SCEP, that uses a trusted Root certificate. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b7d05088-c103-0498-a687-d7272b32528a
* Version Independent ID: 747a20c6-bb9c-b441-4d25-7399d1d8743e
* Content: [Configure Wi-Fi settings for macOS devices in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/configuration/wi-fi-settings-macos)
* Content Source: [memdocs/intune/configuration/wi-fi-settings-macos.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/wi-fi-settings-macos.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by msbemba** [comment]
@JasonNMS Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3618

Once the author approves, the changes will be live.

Thanks
Sri
