### ISSUE TITLE
Incorrect information

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/memdocs#3606]
The initial statement about what Defender for endpoint works with does not include any server operating systems, and it should, see https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/onboard-windows-server?view=o365-worldwide. 

Please correct this . 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5d129246-93fe-04ec-0e49-8e9ac1c910a8
* Version Independent ID: 66d3e475-e2b9-1974-f04a-2ae8b31f96bd
* Content: [Use Microsoft Defender for Endpoint in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/advanced-threat-protection)
* Content Source: [memdocs/intune/protect/advanced-threat-protection.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/advanced-threat-protection.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@DeanGross Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3617

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @DeanGross Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
