### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by p0shkar** [MicrosoftDocs/memdocs#361]
> You can assign scope tags to an Intune object type if the tenant can have multiple versions of that object (such as role assignments or apps). The following Intune objects are exceptions to this rule and don't currently support scope tags:
> * Windows ESP profiles
> * Device Categories
> * Enrollment Restrictions
> * Corp Device Identifiers
>* Autopilot Devices
>* Device compliance locations
>* Jamf devices

It now seems to be possible to set Scope Tags for Device Categories.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37f4d965-ae4c-c1d4-3318-4c4827324555
* Version Independent ID: 5e33c778-0522-da5b-e8c8-bfac4784ba84
* Content: [Use role-based access control (RBAC) and scope tags for distributed IT in Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/scope-tags)
* Content Source: [memdocs/intune/fundamentals/scope-tags.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/scope-tags.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@p0shkar Thanks! I'll strike that from the list today.
