### ISSUE TITLE
How to make our app an intune partner app and shown on this page

### ISSUE THREAD

**Issue by dknc** [MicrosoftDocs/memdocs#362]
[Enter feedback here]
We are going to implement intune integration for our app.
How to make our app listed on this page or how to make our app as an intune partner app after we publish the ios app ?

Can it be simply a pull request ?

Best Regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02165898-ec07-86e1-adc5-18f60bec9689
* Version Independent ID: 7b6c64c4-3304-42b0-079a-7dee609c5e4f
* Content: [Supported Microsoft Intune apps](https://docs.microsoft.com/en-us/mem/intune/apps/apps-supported-intune-apps)
* Content Source: [memdocs/intune/apps/apps-supported-intune-apps.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/apps-supported-intune-apps.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by dknc** [comment]
Can it be simply provide a PR ?

**Comment by Erikre** [comment]
@dknc - Please see the topic [Get started with the Microsoft Intune App SDK](https://docs.microsoft.com/mem/intune/developer/app-sdk-get-started). In this topic there's a section about the app registration process and a link to the Microsoft Intune App Partner Questionnaire. This is the place to start.

**Comment by ClaudioConsolmagno** [comment]
@Erikre My company recently started registration process and already sent over the signed agreement but haven't heard anything back. Any ideas on how long that process takes or who to reach out to check on the progress of the registration? I couldn't find any partner support email as such and we are keen on getting started on development and testing as soon as possible.

(sorry to hijack the issue but I feel it's related)

**Comment by ClaudioConsolmagno** [comment]
We created a ticket via https://partner.microsoft.com/en-GB/ . Hopefully that's the way to go.
