### ISSUE TITLE
Clarity of wording in the Gatekeeper section

### ISSUE THREAD

**Issue by emardee** [MicrosoftDocs/memdocs#3620]
I was just checking the settings for the Gatekeeper section, which currently reads:

> -  **Do not allow user to override Gatekeeper**
> 
>    Prevents users from overriding the Gatekeeper setting, and prevents users from Control clicking to install an app. When enabled, users can Control-click any app, and install it.
>    -   Not configured (default) - Users can Control-click to install apps.
>    -   Yes - Prevents users from using Control-click to install apps.

Unless I am misreading this (which is possible), the above wording appears to contradict itself. The description says when **enabled** users _can_ control-click. But the bullet point says **Yes**, _prevents_ users using control-click. This might be a straight typo. Or it might be just ambiguously worded to be not clear (based on what _enabling_ means on a "do not allow" on an over-ride! are you enabling gatekeeper to work, or enabling the not allowing etc)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 07310e6e-6d1d-71b7-2dbb-04c8fdd763fb
* Version Independent ID: 05c4ca55-1589-54ea-8ac5-85eaffc849b6
* Content: [Configure endpoint protection on macOS devices with Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/endpoint-protection-macos)
* Content Source: [memdocs/intune/protect/endpoint-protection-macos.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/endpoint-protection-macos.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @emardee Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
