### ISSUE TITLE
IPI address typo?

### ISSUE THREAD

**Issue by oobedan** [MicrosoftDocs/memdocs#3628]
[Enter feedback here]

"The TLS certificate secures the connection between the devices that use the tunnel and the Tunnel Gateway endpoint. The certificate must have the IPI address or FQDN of the Tunnel Gateway server in its SAN."

Is **IPI** a typo??

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4538f49d-8c19-9227-0acf-77bef7f8d4a8
* Version Independent ID: 1b1b2c40-1fd8-3909-37ae-05ab0d27efb5
* Content: [Install and configure Microsoft Tunnel VPN solution for Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/microsoft-tunnel-configure)
* Content Source: [memdocs/intune/protect/microsoft-tunnel-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/microsoft-tunnel-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@oobedan   Yes, that appears to be a typo.  I've just submitted a content fix that will see it corrected sometime on Thursday. Thank you for alerting us to that.
