### ISSUE TITLE
Script order

### ISSUE THREAD

**Issue by mattbalzan** [MicrosoftDocs/memdocs#363]
Is there an order in which all the scripts run? Or a dependency? Or a way the scripts can be ordered to deploy per user/per device?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d6b1270-e554-dc36-2a51-1cdab303e91a
* Version Independent ID: 4a62c248-5737-13cc-3270-1f9649bd147d
* Content: [Add PowerShell scripts to Windows 10 devices in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/apps/intune-management-extension)
* Content Source: [memdocs/intune/apps/intune-management-extension.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/intune-management-extension.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by lenewsad** [comment]
Thanks for reaching out to the Intune documentation team. We haven't been able to find an answer for this issue. If you're still seeking support, please try one of these support channels: 

* Open a support ticket by following the steps here: [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support)  

* Post on [Microsoft Q & A](https://docs.microsoft.com/answers/products/?WT.mc_id=msdnredirect-web-msdn).

* Browse the old [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/home?forum=microsoftintuneprod). The site was recently replaced with Microsoft Q & A but still shows the old posts from our community MVPs who are very experienced, knowledgeable, and helpful.

* Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
