### ISSUE TITLE
Please call out Microsoft Devices that require the add-on license

### ISSUE THREAD

**Issue by rasldasl** [MicrosoftDocs/memdocs#3633]
I can assume, based on the description, that Surface Hub and HoloLens will require an add-on. We are currently managing these devices in Intune so if an add-on is required it should be called out here and on the docs pages for these products. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2c813149-24b5-27c1-228e-e67d63afe34c
* Version Independent ID: 2c813149-24b5-27c1-228e-e67d63afe34c
* Content: [Managing Specialty devices with Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/fundamentals/specialty-devices-with-intune)
* Content Source: [memdocs/intune/fundamentals/specialty-devices-with-intune.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/specialty-devices-with-intune.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@rasldasl Thank you for your feedback. I have requested the author to confirm as there is a bit of ambiguity.
I'll update you shortly.

Thanks
Sri

**Comment by msbemba** [comment]
Email sent on 3-6-2023

**Comment by Smritib17** [comment]
This issue has been fixed.
