### ISSUE TITLE
Hyperlink to Autopatch

### ISSUE THREAD

**Issue by VigneshMitsume** [MicrosoftDocs/memdocs#3639]
As we officially support autopatch for windows 365 now, as best practice, we should add references here to using Autopatch for Windows Feature and Qualiity updates

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ee0dbbde-b15e-4adf-b162-1114fddd8846
* Version Independent ID: 78275b5f-4d5b-f318-0cbf-a27ad35dffa0
* Content: [Configure feature updates policy for Windows 10 Windows 11 devices in Intune](https://learn.microsoft.com/en-us/mem/intune/protect/windows-10-feature-updates?context=%2Fwindows-365%2Fcontext%2Fpr-context)
* Content Source: [memdocs/intune/protect/windows-10-feature-updates.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/windows-10-feature-updates.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by yogkumgit** [comment]
Duplicate #3638 , closing. Thanks
