### ISSUE TITLE
Add a link to the detailed data being collected

### ISSUE THREAD

**Issue by derekharkin** [MicrosoftDocs/memdocs#3646]
It would be helpful to add a link on this page to the page with the details on exactly what  is being collected.
It is already documented here: https://learn.microsoft.com/en-us/mem/intune/protect/client-apps-optional-data

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7256d8af-6999-f5d6-b0c7-adc6afdbf4eb
* Version Independent ID: 9fa03eed-2c9e-4738-6e51-f2af7427451e
* Content: [Turn off Microsoft data collection on Windows device - Microsoft Intune](https://learn.microsoft.com/en-gb/mem/intune/user-help/turn-off-microsoft-usage-data-collection-windows)
* Content Source: [memdocs/intune/user-help/turn-off-microsoft-usage-data-collection-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/turn-off-microsoft-usage-data-collection-windows.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@derekharkin Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3649

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @derekharkin Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
