### ISSUE TITLE
List of apps causing non-rooted device to be seen as rooted

### ISSUE THREAD

**Issue by chaseschuette** [MicrosoftDocs/memdocs#3651]
[Enter feedback here]

Please provide a list of apps recognized as being viewed the same as rooted. My non-rooted device is seen a rooted due to an unknown app.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0f6e01a3-5ed0-a660-0c24-31114915d33f
* Version Independent ID: 1eb97fff-c818-6016-2d2e-3790f1e9cb54
* Content: [Your Android device is rooted and can't connect - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/user-help/your-device-is-rooted-and-you-cant-connect-android)
* Content Source: [memdocs/intune/user-help/your-device-is-rooted-and-you-cant-connect-android.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/your-device-is-rooted-and-you-cant-connect-android.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by yogkumgit** [comment]
@lenewsad Please help us in resolving this issue. Thanks

**Comment by chaseschuette** [comment]
Thanks for getting this assigned. Let me know if there's anything further I can provide

**Comment by chaseschuette** [comment]
FYI, I am able to access my employers VDI pool through the Microsoft remote desktop client on this same device without a false root detection

**Comment by lenewsad** [comment]
Hi @chaseschuette, thanks for reaching out to the Microsoft Intune docs team. We recommend following the steps in the article, starting with uninstalling recently installed apps. If after you're still blocked from enrolling or accessing work resources, please follow up with your IT support person for help. They are familiar with your organization's device policies and may be able to help you resolve this issue.  If you learn anything in your experience that you think should be added to docs, please follow up with us and we'll review your contributions.  Thank you! 

@yogkumgit
