### ISSUE TITLE
MacOS Update Policy: Install immediately behaviour

### ISSUE THREAD

**Issue by Flazje** [MicrosoftDocs/memdocs#3653]
Hi,

I would expect that the install immediately behaviour in an Intune MacOS Update policy triggers a notification to reboot the device. I've created a ticket with MS (TrackingID#2302231420000659) for this but apparently the restart trigger mentioned in the documentation under 'Install immediately' is about restarting the update process said the support person.

I would expect a notification with a countdown of 60 seconds that the user can postpone like mentioned in this community blog:
https://tminus365.com/patching-macos-devices-in-microsoft-intune/

I would suggest the description of the 'Install Immediately' option to be more clear.
Also if install immediately is selected I would like a countdown for a reboot to begin on the device (user can still postpone).

Thank you for the feedback

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 90d56195-5237-ad7a-91b0-a331f038daef
* Version Independent ID: 90d56195-5237-ad7a-91b0-a331f038daef
* Content: [Use Microsoft Intune policies to manage macOS software updates](https://learn.microsoft.com/en-us/mem/intune/protect/software-updates-macos)
* Content Source: [memdocs/intune/protect/software-updates-macos.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/software-updates-macos.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@Flazje Thank you for your feedback. The Install immediately: Download the software update and trigger the restart countdown notification does trigger a countdown of 60 seconds that the user can postpone like mentioned in this community blog:
https://tminus365.com/patching-macos-devices-in-microsoft-intune/

If this is not working as expected, I'd suggest you tell the support person to engage the product team if need be.

Hope this helps!

Thanks
Sri

**Comment by Flazje** [comment]
Hi @msbemba
Thank you for your answer. This didn't seem to work in our environment. I will reopen my ticket with the support person.
