### ISSUE TITLE
Incorrect value in OS SKU table

### ISSUE THREAD

**Issue by ubernerdom** [MicrosoftDocs/memdocs#3656]
The numeric value listed for EnterpriseSN in the SKU table is incorrect.

The documentation currently says 162:

EnterpriseSN | Windows 10 Enterprise LTSC N (162)
-- | --

But the correct value is 126:

EnterpriseSN | Windows 10 Enterprise LTSC N (126)
-- | --

This can be verified by checking against the corresponding line from winnt.h

`#define PRODUCT_ENTERPRISE_S_N                      0x0000007E`

(`0x7e` in hex = `126` in decimal)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5c23357f-dd50-8ad1-084b-47ece285105f
* Version Independent ID: fa8f5486-8120-1548-a146-8f2e96995e9b
* Content: [Supported filter device properties and operators in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/fundamentals/filters-device-properties)
* Content Source: [memdocs/intune/fundamentals/filters-device-properties.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/filters-device-properties.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by msbemba** [comment]
@ubernerdom Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3674

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ubernerdom Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
