### ISSUE TITLE
Security Issue 

### ISSUE THREAD

**Issue by Bildar** [MicrosoftDocs/memdocs#3659]
There is a significant security issue with deploying the InTune connector while following these instructions that I have seen numerous times lately. It comes from a combination of these steps:

3. Find the User certificate template, right-click it, and choose Duplicate Template to open Properties of New Template.

8. In Subject Name, choose Supply in the request.

10. In Security, add the Computer Account for the server where you install the Certificate Connector for Microsoft Intune. Allow this account Read and Enroll permissions.

The User template which the documentation says to copy has Enroll rights given to the Domain Users group and has the Client Authentication (OID 1.3.6.1.5.5.7.3.2) EKU. By adding the "Supply in the Request" configuration option to this template it is now vulnerable to the ESC1 offensive technique documented by SpecterOps at https://posts.specterops.io/certified-pre-owned-d95910965cd2 .

This can be fixed by adding an additional step either before or after step 10 something like:

11. In Security, remove the Domain Users group from the list of groups or user names allowed permissions on this template by selecting the Domain Users group and pressing the remove button. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 41df2048-2b0e-4218-1fc4-d8a657f860cc
* Version Independent ID: e26c4390-87a3-7d5a-4e6f-529b4ccf8759
* Content: [Use a PKCS certificate profile to provision devices with certificates in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/certificates-pfx-configure)
* Content Source: [memdocs/intune/protect/certificates-pfx-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/certificates-pfx-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
Pending PM/Dev comment.

**Comment by Brenduns** [comment]
@Bildar   Thanks for this feedback. I've run this past our PM/Dev product team for a check. With that consult, I'll be updating this content a bit later today to include your suggested step.
