### ISSUE TITLE
TeamViewer Guidance give a 404

### ISSUE THREAD

**Issue by crbender** [MicrosoftDocs/memdocs#366]
The link https://www.teamviewer.com/support/documents/ has either moved or has been deleted. 

(edit: add metadata to target article)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a9ef909-c4fb-f052-9d2e-c794efc9efd7
* Version Independent ID: 655e8b80-0471-5789-8bf1-20403390c012
* Content: [Remotely administer devices in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/remote-actions/teamviewer-support)
* Content Source: [memdocs/intune/remote-actions/teamviewer-support.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/remote-actions/teamviewer-support.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@crbender I'll change the link to https://community.teamviewer.com/?category.id=en today. Thanks!
