### ISSUE TITLE
Embedded video

### ISSUE THREAD

**Issue by johnckirk** [MicrosoftDocs/memdocs#3663]
The "embedded video" section at the top of the page isn't working, i.e. it doesn't display the video.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 60b4eb41-d66a-b1c3-b417-4946643ba3d6
* Version Independent ID: 6f6e2af0-eb71-16e8-62d0-d86c73a56332
* Content: [Enroll Android device with Intune Company Portal](https://learn.microsoft.com/en-us/mem/intune/user-help/enroll-device-android-company-portal)
* Content Source: [memdocs/intune/user-help/enroll-device-android-company-portal.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/enroll-device-android-company-portal.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@johnckirk Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3675

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @johnckirk Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
