### ISSUE TITLE
Outdated info - Pre-provision re-enroll

### ISSUE THREAD

**Issue by PJMarcum** [MicrosoftDocs/memdocs#3669]
under the pre-reqs section there's an important note; "You cannot automatically re-enroll a device through Windows Autopilot after an initial deployment in pre-provisioning mode...." if I am not mistaken that change was rolled back and it is no longer required to delete the device.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c0f572e0-1bc0-6f14-7f60-989eb67fb7e7
* Version Independent ID: e4ec5b25-d9a6-d260-6cf6-ff4f3eb3ecb8
* Content: [Windows Autopilot for pre-provisioned deployment](https://learn.microsoft.com/en-us/mem/autopilot/pre-provision?source=docs)
* Content Source: [memdocs/autopilot/pre-provision.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/pre-provision.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
Thank you for the feedback @PJMarcum. I will research and confirm.

**Comment by frankroj** [comment]
Thank you again @PJMarcum for the feedback. You are correct that the change has been rolled back and you can now re-enroll a device using Autopilot without first having to delete it from Intune. This is explained in the following blog article:

https://techcommunity.microsoft.com/t5/intune-customer-success/return-of-key-functionality-for-windows-autopilot-sign-in-and/ba-p/3583130

I have gone ahead and updated the article and removed the Important note. Thank you again for letting us know about this issue.
