### ISSUE TITLE
Clarify what it means that the admin or the user needs to update the Company Portal

### ISSUE THREAD

**Issue by OneUser1** [MicrosoftDocs/memdocs#3672]
The docs say "The Company Portal app must be updated manually by you, or your users." in case we deploy the app using a VPP token during ADE. Can you pls add an explaination whether it is enough to have the app synced from ABM and deployed as VPP app to the devices enrolled by ADE?
I tought deploying the app during ADE is fine as long as updates are installed using the VPP app synced to Intune. Is this correct?

Thanks for your clarification!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 778eac62-a9ea-604e-9d47-8c2a4ed5aa73
* Version Independent ID: a137faa0-8b25-f98f-4ca1-18393871923c
* Content: [iOS/iPadOS device enrollment guide for  Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/fundamentals/deployment-guide-enrollment-ios-ipados)
* Content Source: [memdocs/intune/fundamentals/deployment-guide-enrollment-ios-ipados.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/deployment-guide-enrollment-ios-ipados.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by yogkumgit** [comment]
@MandiOhlinger Please help us in resolving this issue. Thanks

**Comment by MandiOhlinger** [comment]
@OneUser1 Assuming I understand your question correctly, no, it's not enough. You have to enable automatic app updates In the Intune admin center > app token settings. This info is documented at [Set up automated device enrollment in Intune - Deploying the Company Portal app](https://learn.microsoft.com/mem/intune/enrollment/device-enrollment-program-enroll-ios#deploying-the-company-portal-app).

I updated the article to include this info. Changes should be live later today.

FYI @yogkumgit

**Comment by OneUser1** [comment]
Hi @MandiOhlinger, thanks for your reply! So, do I understand you correctly: Deploying the Company Portal App using the ADE deployment profile option "Install Company Portal (VPP token)" PLUS enabling automatic app updates in the Apple VPP Token config does update the Company Portal app like any other app, right?

Thanks!👍🏻

**Comment by OneUser1** [comment]
Looks good in the docs. Thanks for updating!

**Comment by MandiOhlinger** [comment]
@OneUser1 Yes - Your understanding is correct.
