### ISSUE TITLE
Request to add the content of Important as described on the Microsoft Store for Business page to this page.

### ISSUE THREAD

**Issue by Satoshi-Mori** [MicrosoftDocs/memdocs#3679]
[Enter feedback here]
Intune's Microsoft Store for Business page does not provide detailed instructions only for retirement.
As a result, Intune users are inquiring about how to deal with store for business after retirement.
By adding the Important described below to the Intune page, the Intune user will be able to solve the problem by themselves, so we request that you add the Important content.

Please see this Important content of this link.
[Microsoft Store for Business and Microsoft Store for Education overview (Windows 10) | Microsoft Learn](https://learn.microsoft.com/en-us/microsoft-store/microsoft-store-for-business-overview)

------------
Important
Microsoft Store for Business and Microsoft Store for Education will be retired in the first quarter of 2023. 
You can continue to use the current capabilities of free apps until that time. 
For more information about this change, see [Update to Intune integration with the Microsoft Store on Windows](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/update-to-endpoint-manager-integration-with-the-microsoft-store/ba-p/3585077) and
 [FAQ: Supporting Microsoft Store experiences on managed devices](https://techcommunity.microsoft.com/t5/windows-management/faq-supporting-microsoft-store-experiences-on-managed-devices/m-p/3585286).
------------

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ded6cdc4-3c0a-ae18-9d9c-b3d5db3c0708
* Version Independent ID: 34a4b4be-cd8b-25b3-49ef-f5142a87b9ef
* Content: [Add Microsoft Store apps to Intune (legacy)](https://learn.microsoft.com/en-us/mem/intune/apps/store-apps-windows)
* Content Source: [memdocs/intune/apps/store-apps-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/store-apps-windows.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@Satoshi-Mori Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3703

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
Closing as changed are not approved. Thanks

**Comment by msbemba** [comment]
@yogkumgit  This can be closed.
