### ISSUE TITLE
"Configure off-premises clients for CMG" and DisAllowCMG

### ISSUE THREAD

**Issue by MaxXyzzy** [MicrosoftDocs/memdocs#368]
Should the section **Configure off-premises clients for CMG** include the registry value **DisAllowCMG** which is also important in that scenario?

Jason Sandys mentions it in his article here: [https://home.configmgrftw.com/cloud-management-gateway-choices/](https://home.configmgrftw.com/cloud-management-gateway-choices/)

 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6481482-eaca-ebae-03fe-cb30faf35557
* Version Independent ID: a0c07347-329f-d59c-0f47-7618e7fdbb14
* Content: [Set up cloud management gateway - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/setup-cloud-management-gateway#configure-off-premises-clients-for-cmg)
* Content Source: [memdocs/configmgr/core/clients/manage/cmg/setup-cloud-management-gateway.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/cmg/setup-cloud-management-gateway.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @MaxXyzzy for the feedback, I'm checking

**Comment by aczechowski** [comment]
I checked with the engineering team. The option is already exposed in client settings: “Enable clients to use a cloud management gateway”. There's really no reason an admin needs to control this via registry. We don't document every implementation detail, and this is one instance. We document the CMGFQDNs value to specifically help with the described scenario.
