### ISSUE TITLE
All endpoints for Intune should be consolidated here

### ISSUE THREAD

**Issue by jerryabo** [MicrosoftDocs/memdocs#3680]
There is some overlap with devices covered, but some items are missing - ideally everything would come back to a single point of truth like this page: https://learn.microsoft.com/en-us/mem/intune/protect/windows-10-expedite-updates

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c9c3475-56d4-026b-349f-f9cbc258537c
* Version Independent ID: 9c6476ed-8a47-bcb4-dfbf-25ba305c3b24
* Content: [Network endpoints for Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/fundamentals/intune-endpoints?source=docs)
* Content Source: [memdocs/intune/fundamentals/intune-endpoints.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/intune-endpoints.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by Smritib17** [comment]
> @Smritib17 Please help us in resolving this issue. Thanks

This issue has been fixed in the linked PR.
