### ISSUE TITLE
No ContosoWifi used in the example

### ISSUE THREAD

**Issue by markri-msft** [MicrosoftDocs/memdocs#3681]
This page on step 3 and 4 talk about "in this example, the profile name is ContosoWifi", but there is never any mention of this value in the example. Then in step 4 is says "in our example, the file name is Wi-Fi-ContosoWiFi.xml" but in fact this file name is never mentioned in the example.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7e46e8fe-9289-4d25-9959-3ac871c7a5a5
* Version Independent ID: fa0d6f1a-dd8e-4ac1-1ee3-a2fe567cf365
* Content: [Import Wi-Fi settings for Windows devices in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/configuration/wi-fi-settings-import-windows-8-1)
* Content Source: [memdocs/intune/configuration/wi-fi-settings-import-windows-8-1.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/wi-fi-settings-import-windows-8-1.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by msbemba** [comment]
@markri-msft Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3704

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @markri-msft Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
