### ISSUE TITLE
Maximum Password Expiration Date Value

### ISSUE THREAD

**Issue by Ikuko-Konno** [MicrosoftDocs/memdocs#3682]
In Apple's public information and on the [Microsoft Intune admin center] screen, the maximum value that can be set for the [Password expiration (days)] field is 730 days.
On the other hand, the Intune public information still states that the limit is 65535 days.
We are of the opinion that 730 days is the correct upper limit for password expiration.
Please correct the Intune documentation.

https://developer.apple.com/documentation/devicemanagement/passcode
-----------------
maxPINAgeInDays
integer
The number of days for which the passcode can remain unchanged. After this number of days, the user is forced to change the passcode before the device is unlocked.
Minimum Value: 0
Maximum Value: 730
-----------------

https://support.apple.com/guide/deployment/passcode-payload-settings-dep4d6a472a/1/web/1.0
-----------------
Maximum passcode or password age (in days)
Requires users to change their passcode or password at the interval you specify. It can be set to “none” or from 1 to 730 days.
-----------------
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 88932dd8-abce-bf23-9624-1df5f60a946d
* Version Independent ID: ab2d932f-e375-2485-a6e5-e02daf7a27c4
* Content: [iOS/iPadOS device settings in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/configuration/device-restrictions-ios)
* Content Source: [memdocs/intune/configuration/device-restrictions-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/device-restrictions-ios.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by msbemba** [comment]
@Ikuko-Konno Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3705

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Ikuko-Konno Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
