### ISSUE TITLE
IoT and LTSC Support

### ISSUE THREAD

**Issue by jonconwayuk** [MicrosoftDocs/memdocs#3690]
Get a lot of queries from customers about the support for Windows Autopilot on Windows 10/11 IoT Enterprise and/or LTSC.

Microsoft employees outside the main documentation have stated that variations are supported but Docs doesn't mention specifically which is ambiguous.

Example: https://techcommunity.microsoft.com/t5/learn-iot/ask-the-iot-expert-windows-10-iot-enterprise/m-p/1551016

I raised a support ticket and was told that the documentation only mentions supported scenarios and not unsupported scenarios but then the article above contradicts this. Very unclear.

Would it be possible to make a clear statement on this in the documentation to avoid further confusion?

**Comment by aczechowski** [comment]
See my responses to #2981 and #2969
