### ISSUE TITLE
Check-in intervals for MAM

### ISSUE THREAD

**Issue by Ikuko-Konno** [MicrosoftDocs/memdocs#3691]
MAM uses the MAM channel, not the MDM channel.
Therefore, I do not believe that the check-in behavior every 8 hours on the MDM channel is applicable to MAM.

However, this public information may mislead the reader since it states that MAM is also applicable.
-------------------
This article applies to the following policies:
・ App protection policies
-------------------

In the case of MAM, the following public information should be noted as applicable.
https://learn.microsoft.com/ja-jp/mem/intune/apps/app-protection-policy-delivery

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 14c045c9-2ccb-e24b-9eaa-bfd65b64a48c
* Version Independent ID: 355e928b-5ad8-ac1d-24d4-1d2e8f11cb4d
* Content: [Questions with policies and profiles in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/configuration/device-profile-troubleshoot)
* Content Source: [memdocs/intune/configuration/device-profile-troubleshoot.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/device-profile-troubleshoot.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by yogkumgit** [comment]
@MandiOhlinger Please help us in resolving this issue. Thanks

**Comment by MandiOhlinger** [comment]
@yogkumgit The https://learn.microsoft.com/mem/intune/configuration/device-profile-troubleshoot article is updated to include this info. You can close this GitHub issue.
