### ISSUE TITLE
Feedback on (Windows 10 only) 

### ISSUE THREAD

**Issue by iTc6PE** [MicrosoftDocs/memdocs#3692]
[Enter feedback here]
[Full Scan](https://learn.microsoft.com/en-us/mem/intune/configuration/device-restrictions-windows-10#microsoft-defender-antivirus) (Windows 10 only)
[Quick Scan](https://learn.microsoft.com/en-us/mem/intune/configuration/device-restrictions-windows-10#microsoft-defender-antivirus) (Windows 10 only)
Feedback on the above headword description.
I have the impression that (Windows 10 only) does not run on Windows 8.1 and Windows 11, so could you please state that it does run on Windows 11?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 217e72bd-8597-5640-7000-37a3eb2d5f29
* Version Independent ID: 202cad01-13d1-37c1-c794-6d31621cdab2
* Content: [Manage devices with Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/remote-actions/device-management#available-device-actions)
* Content Source: [memdocs/intune/remote-actions/device-management.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/device-management.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@iTc6PE Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3708

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by tiburd** [comment]
Merged PR
