### ISSUE TITLE
Clear the (iOS only) from Located Device.

### ISSUE THREAD

**Issue by Karr** [MicrosoftDocs/memdocs#3694]
The Locate Device (iOS only) needs to be updated by removing that only statement.  Other OS are supported.
[Locate device](https://learn.microsoft.com/en-us/mem/intune/remote-actions/device-locate) (iOS only)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 217e72bd-8597-5640-7000-37a3eb2d5f29
* Version Independent ID: 202cad01-13d1-37c1-c794-6d31621cdab2
* Content: [Manage devices with Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/remote-actions/device-management)
* Content Source: [memdocs/intune/remote-actions/device-management.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/device-management.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@Karr Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3709

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by tiburd** [comment]
Merged PR
