### ISSUE TITLE
Is this available to Android Enterprise dedicated devices?

### ISSUE THREAD

**Issue by weyCC81** [MicrosoftDocs/memdocs#37]
As there is no user logged in on the "Intune Company Portal" by default on dedicated devices.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804899ad-0aaf-4e3d-32f1-98055153a251
* Version Independent ID: 51b1dd58-5c58-c5eb-8b46-96517a339fc8
* Content: [Add web apps to Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/web-app)
* Content Source: [memdocs/intune/apps/web-app.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/web-app.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@weyCC81 - For Android Enterprise devices, see [Managed Google Play web links](https://docs.microsoft.com/mem/intune/apps/apps-add-android-for-work#managed-google-play-web-links).

You can use Intune to orchestrate app deployment through Managed Google Play for any Android Enterprise scenario (including work profile, dedicated, and fully managed enrollments). Managed Google Play web links are installable and manageable just like other Android apps.
