### ISSUE TITLE
So BitLocker is a firewall now????

### ISSUE THREAD

**Issue by uowdaniel** [MicrosoftDocs/memdocs#371]
"Built-in firewalls include BitLocker for Windows devices..."

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d33743f-adf4-680b-483a-b83a625774f0
* Version Independent ID: 4b822bef-289f-77dd-8c50-fd20fdbb5f00
* Content: [Manage firewall settings with endpoint security policies in Microsoft Intune](https://docs.microsoft.com/en-gb/mem/intune/protect/endpoint-security-firewall-policy)
* Content Source: [memdocs/intune/protect/endpoint-security-firewall-policy.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/endpoint-security-firewall-policy.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@uowdaniel  There's been a fix submitted for that statement. It appears that there was a bit of content cross over from an article on encryption.

**Comment by uowdaniel** [comment]
Hi Brent

☺

Same error also exists on https://docs.microsoft.com/en-gb/mem/intune/protect/endpoint-security-policy:

Firewall<https://docs.microsoft.com/en-gb/mem/intune/protect/endpoint-security-firewall-policy> - Use the endpoint security Firewall policy in Intune to configure a devices built-in firewall for devices that run macOS and Windows 10. Built-in firewalls include BitLocker for Windows devices and FileVault for macOS.

cheers,
Daniel

**Comment by Brenduns** [comment]
Thanks.  We’ll have to take a look to see how this mix up got in there, and then slid past the dedicated reviews.  So painful to see. But I do appreciate your spotting that and passing it on. It appears that the same blurb was used, and shall get the same hammer applied to it.
