### ISSUE TITLE
Windows 11 version error

### ISSUE THREAD

**Issue by severrol-msft** [MicrosoftDocs/memdocs#3710]
Hello,

there is an error on the line :
Windows 11, version 22H1 with KB5023774 (Pending Optional Update Release - March 2023)

You need : 
Windows 11, version 2**1**H**2** with KB5023774 (Pending Optional Update Release - March 2023)

Kr
Seb
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5ca72dde-b272-8df3-7fd8-0f8f16b13679
* Version Independent ID: 5ca72dde-b272-8df3-7fd8-0f8f16b13679
* Content: [Learn about using Endpoint Privilege Management with Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/epm-overview?source=docs)
* Content Source: [memdocs/intune/protect/epm-overview.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/epm-overview.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@severrol-msft Thank you for your feedback. The document now states Windows 11, version 21H2 with [KB5023774].

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @severrol-msft Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
