### ISSUE TITLE
How long will I get the result?

### ISSUE THREAD

**Issue by lonleekwok** [MicrosoftDocs/memdocs#3711]
[Enter feedback here]
How long will I have to wait after completed the Microsoft Intune App Partner Questionnaire? Anyway that I can check the status?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4f22dc1e-ad50-d834-2485-b3dad26972a7
* Version Independent ID: 5ef787c5-79cc-da5f-b4af-7647a84bd62d
* Content: [Get started with the Microsoft Intune App SDK](https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-get-started)
* Content Source: [memdocs/intune/developer/app-sdk-get-started.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/developer/app-sdk-get-started.md)
* Service: **microsoft-intune**
* Sub-service: **developer**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @lonleekwok Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
