### ISSUE TITLE
Global Admin is not able to start trials for Intune Add-ons

### ISSUE THREAD

**Issue by vipulsparsh** [MicrosoftDocs/memdocs#3712]
As per the page, the global admins should be able to add the Intune Add-ons, but being a global admin, the options the greyed out for me. 

![image](https://user-images.githubusercontent.com/63580915/227849942-5ed47e68-d50b-40d9-ae58-93606c3f5551.png)

![image](https://user-images.githubusercontent.com/63580915/227863850-c6c5178c-da1b-435f-ab03-744ba4f24126.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 558175bc-c355-cb12-dd8b-1e49f3c39430
* Version Independent ID: 558175bc-c355-cb12-dd8b-1e49f3c39430
* Content: [Use Intune Suite add-on capabilities - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/fundamentals/intune-add-ons)
* Content Source: [memdocs/intune/fundamentals/intune-add-ons.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/intune-add-ons.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@vipulsparsh I was able to test it in a few tenants and the option is available as described in the document.

![image](https://user-images.githubusercontent.com/45987684/229825999-7240ad0b-fe41-4608-b919-75102ed57a24.png)


I'd recommend you open a support case from that particular tenant so that a support engineer can fix or escalate this issue.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @vipulsparsh Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
