### ISSUE TITLE
RBAC

### ISSUE THREAD

**Issue by IntuneArchitect** [MicrosoftDocs/memdocs#3713]
[Please include the details of role that is required to update/configure the settings mentioned on this page]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 40ee2465-52c8-8fd0-ece0-c2dc498d025f
* Version Independent ID: 02b42d75-b82e-acb5-3457-7ecd3c45326f
* Content: [How to configure the Intune Company Portal apps, Company Portal website, and Intune app - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/apps/company-portal-app)
* Content Source: [memdocs/intune/apps/company-portal-app.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/company-portal-app.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@IntuneArchitect Thank you for your feedback. We have added the details to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3740

Once the author approves, the changes will be live.

Thanks
Sri
