### ISSUE TITLE
Policy targeting

### ISSUE THREAD

**Issue by baf** [MicrosoftDocs/memdocs#3716]
Can some language be added about targeting EPM policies to users and devices? Specifically, I'm wondering how policy targeting works - if you target a user, can they elevate on all devices? If a device, can all users on that device then elevate? Is there any capability to target a device's primary user?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e278a1ae-0701-bf86-4396-c0a0348e7a95
* Version Independent ID: e278a1ae-0701-bf86-4396-c0a0348e7a95
* Content: [Deployment considerations for Endpoint Privilege Management](https://learn.microsoft.com/en-us/mem/intune/protect/epm-deployment-considerations-ki)
* Content Source: [memdocs/intune/protect/epm-deployment-considerations-ki.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/epm-deployment-considerations-ki.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@baf  Thanks for the questions. I've consulted with our engineering team, and there's no connection for policies to target the primary device of a user. Instead, admins will need to manage the policies via both device and user targeting, with awareness that a user policy can override the settings in a device targeted policy.     

As to user vs device based policies, I want to direct your attention to this section in the article for rule guidance: [Deploying rules created with Endpoint Privilege Management](https://learn.microsoft.com/mem/intune/protect/epm-guidance-for-creating-rules#deploying-rules-created-with-endpoint-privilege-management). For this content, I’ve submitted an edit that adds a bit more detail around polices assigned to users vs devices.  This should be live later in the day on Tuesday.

**Comment by baf** [comment]
Thanks, @Brenduns - can you clarify then if it’s by design with the EPM product that any user of a machine should be allowed to run elevated apps according to the rules an admin defines, and if this is a design decision or something that will be augmented/changed later?
