### ISSUE TITLE
Broken link on page

### ISSUE THREAD

**Issue by velden** [MicrosoftDocs/memdocs#372]
You can download a template of the above table to enter your organization's use-case and sub-use-case scenarios --> contains to TechNet gallery but the specific target is not found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e85b5491-6bde-bd98-59cb-d3589a06d244
* Version Independent ID: 7f83ff32-4fce-cce4-e030-2db04bf5ec12
* Content: [Identify use case scenarios - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/planning-guide-scenarios)
* Content Source: [memdocs/intune/fundamentals/planning-guide-scenarios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/planning-guide-scenarios.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @dougeby
* Microsoft Alias: **dougeby**

**Comment by dougeby** [comment]
@velden, Thanks for the feedback! The TechNet Gallery content is being retired. We are also in the process of re-writing the planning content. I have removed the link for now and we will determine how best to include the templates in future releases. Thanks again!
