### ISSUE TITLE
Description of ESP Only fail selected blocking apps in technician phase is unclear

### ISSUE THREAD

**Issue by zygentoma** [MicrosoftDocs/memdocs#3725]
[Enter feedback here]
Only fail selected blocking apps in technician phase: Your options:

No: Only blocking apps will fail deployment during the technician phase of pre-provisioning.
Yes: Intune will attempt to install required apps targeted to the device, or user (if assigned and installed in device context), during the technician phase of pre-provisioning. If installation is unsuccessful, these apps won't fail the deployment unless they are part of the blocking apps you previously selected.

The section above does not make sense, or i have read it 10 times and I cannot get the sense of it. The problematic bit is > YES.... these apps won't fail the deployment unless they are part of the blocking apps you previously selected.

The explanation is clearer here > https://techcommunity.microsoft.com/t5/intune-customer-success/update-to-windows-autopilot-pre-provisioning-process-for-app/ba-p/3752516

The text in intune  <Only fail selected blocking apps in technician phase (preview)> is somewhat clearer but has room for improvement

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 92ba0166-1d3c-40ca-a2f3-2954dcfe4411
* Version Independent ID: e07d50e2-7a95-868d-5800-ea548c84e884
* Content: [Set up the Enrollment Status Page in the admin center - Microsoft Intune](https://learn.microsoft.com/en-gb/mem/intune/enrollment/windows-enrollment-status?source=docs)
* Content Source: [memdocs/intune/enrollment/windows-enrollment-status.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/windows-enrollment-status.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @zygentoma, thanks for contacting the Microsoft Intune docs team. We worked with the product team to clarify the setting description. Here are the updated values:  
        
- **No**: An attempt will be made to install the blocking apps. Autopilot deployment will fail if a blocking app fails to install. No attempt is made to install non-blocking apps. When the end user receives the resealed device and signs in for the first time, the ESP will attempt to install the non-blocking apps. 
 - **Yes**: An attempt will be made to install all required apps. Autopilot deployment will fail if a blocking app fails to install. If a non-blocking app that's targeted to the user fails to install, the ESP ignores it and deployment continues as normal. When the end user signs into the resealed device for the first time, the ESP will reattempt to install the apps that it couldn't in the technician phase. This is the default setting for pre-provisioned deployments. 

These updates will be live by 5 PM PST today.  Thanks for contributing to docs!

CC @yogkumgit
