### ISSUE TITLE
Azure Dynamic device membership rule

### ISSUE THREAD

**Issue by roman-schraner** [MicrosoftDocs/memdocs#373]
Hi,

The proposed syntax to create an Autopilot Device Group with a dynamic membership rule does not seem to work on current Azure AD versions anymore.

The stated Rule `(device.devicePhysicalIDs -any _ -contains "[ZTDId]")` has to be adjusted to `(device.devicePhysicalIDs -any (_ -contains "[ZTDId]"))` in order to work. The correct syntax is well documents here: https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/groups-dynamic-membership#rules-with-complex-expressions
This issue probably also occurs with the other dynamic rules stated in this Article.

Could you please fix the syntax?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0789d275-5672-266c-9394-380b0af2dac3
* Version Independent ID: 41f03a3b-e3ac-f779-3857-49659cbd3d3f
* Content: [Enroll devices using Windows Autopilot - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/enrollment-autopilot#create-an-autopilot-device-group)
* Content Source: [memdocs/intune/enrollment/enrollment-autopilot.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/enrollment-autopilot.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
7519060

**Comment by ErikjeMS** [comment]
@roman-schraner Thanks! I'll fix this today.

**Comment by roman-schraner** [comment]
@ErikjeMS Thanks for taking on this issue. But for me the Rule still seems wrong here https://docs.microsoft.com/en-us/mem/autopilot/enrollment-autopilot#create-an-autopilot-device-group

**Comment by ErikjeMS** [comment]
@roman-schraner Thanks! I'll fix it today.
