### ISSUE TITLE
youyr usual bs incorrect answers!

### ISSUE THREAD

**Issue by decard123** [MicrosoftDocs/memdocs#3730]
NO SUCH OPTION/SETTING

YR USUAL BS

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2a3ddb1a-e030-ac57-81b8-77290f3f36d2
* Version Independent ID: 0ebf6bb4-33f3-38d3-ebd9-f522b5d76e75
* Content: [Change User Access Control setting](https://learn.microsoft.com/en-us/mem/intune/user-help/you-need-to-enable-uac-windows)
* Content Source: [memdocs/intune/user-help/you-need-to-enable-uac-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/you-need-to-enable-uac-windows.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@decard123 Thank you for your feedback. I was able to test and the options do exist.

![image](https://user-images.githubusercontent.com/45987684/230306963-20b1f6ec-3783-4940-aeb8-a9f9c65b022b.png)

If you still have trouble, I'd recommend you raise a support ticket via the need help section on the admin center, so that a support technical can help you out.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @decard123 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
