### ISSUE TITLE
Regarding platforms supported by Apple Configurator certificates

### ISSUE THREAD

**Issue by Ikuko-Konno** [MicrosoftDocs/memdocs#3732]
We have received a response from Apple stating that Windows PCs are exempt from the control of connected devices via p12 format certificates issued by Apple Configurator 2.
Therefore, the phrase "macOS device or PC" in the official documentation is incorrect.
The description in the official documentation should be revised to say "macOS device only".
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd130267-c54b-41e3-d534-831d4a86bae6
* Version Independent ID: bdfa7eca-a356-3dde-7643-9a759f952007
* Content: [Enroll iOS/iPadOS devices with Apple ADE - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-ios)
* Content Source: [memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@Ikuko-Konno Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3753

Once the author approves, the changes will be live.

Thanks
Sri
