### ISSUE TITLE
Incorrect path to export App protection policy report

### ISSUE THREAD

**Issue by SrikanthPavan** [MicrosoftDocs/memdocs#3733]
Hi, 
Path Mentioned in the article: Apps > App protection status > App Protection Report: iOS/iPadOS, Android.
Correct path to export App Protection policy report is:
Apps > **Monitor** > App protection status > App Protection Report: iOS/iPadOS, Android.

Regards,
Sri.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5778af76-6c42-fbea-b07b-dc001749732a
* Version Independent ID: 4f0cc443-bd3e-dfdf-1fba-f35e9bb3f87f
* Content: [How to monitor app protection policies - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/apps/app-protection-policies-monitor)
* Content Source: [memdocs/intune/apps/app-protection-policies-monitor.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/app-protection-policies-monitor.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@SrikanthPavan Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3754

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @SrikanthPavan Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
