### ISSUE TITLE
Update to page for OS Support.

### ISSUE THREAD

**Issue by mkhwiu** [MicrosoftDocs/memdocs#3734]
This page says that Intune is available for 10.15 or higher, when I went to install it reports that it macOS 11 is required.
Thanks,
Matt

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 08300405-c9e4-b981-6151-a4309e6d11c7
* Version Independent ID: 8b5f54f1-07b3-dce5-4046-9ccf8798d3d0
* Content: [Enroll your Mac with Intune Company Portal](https://learn.microsoft.com/en-us/mem/intune/user-help/enroll-your-device-in-intune-macos-cp)
* Content Source: [memdocs/intune/user-help/enroll-your-device-in-intune-macos-cp.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/enroll-your-device-in-intune-macos-cp.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@mkhwiu Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3755

Once the author approves, the changes will be live.

Thanks
Sri
