### ISSUE TITLE
Device compliancy

### ISSUE THREAD

**Issue by jancotanis** [MicrosoftDocs/memdocs#3737]
My device was compliant in the portal app but unable to download/sync/print sharepoint documents due to using Firefox. Firefox had to add windows sso in security settings turned on to have this functioning.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8dfb6a39-013e-7ca3-8133-9617458ed9f2
* Version Independent ID: 35e0cece-eb65-53a8-0aed-3648ccae0e07
* Content: [What is device enrollment](https://learn.microsoft.com/en-us/mem/intune/user-help/use-managed-devices-to-get-work-done)
* Content Source: [memdocs/intune/user-help/use-managed-devices-to-get-work-done.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/use-managed-devices-to-get-work-done.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@jancotanis Thank you for your feedback. This document pertains to device enrollment and we don't discuss troubleshooting steps. I don't think we can add steps for individual browsers.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jancotanis Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
