### ISSUE TITLE
MSAL SDK needs to be used, not ADAL

### ISSUE THREAD

**Issue by bgavrilMS** [MicrosoftDocs/memdocs#374]
Please stop advertising ADAL SDK. ADAL is being deprecated and MSAL is the next gen identity library that needs to be used, including for Intune scenarios. This is an official recommendation, I am a developer on ADAL and MSAL libraries. Please contact us ASAP if you have any questions.

Note: We prioritize MSAL bugs higher than ADAL bugs, so people using ADAL are unlikely to get timely help. It is unlikely that we will fix any ADAL bug that is not a regression.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 123cb14f-5edf-1bdd-1f16-00ce32443583
* Version Independent ID: c41ef518-bc7a-d87e-b03c-31cba1de6d0a
* Content: [Microsoft Intune App SDK Xamarin Bindings](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-xamarin)
* Content Source: [memdocs/intune/developer/app-sdk-xamarin.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/developer/app-sdk-xamarin.md)
* Service: **microsoft-intune**
* Sub-service: **developer**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by bgavrilMS** [comment]
Hi @Erikre - ADAL's integration with the Android broker is badly broken by a Google update. We do not intend to fix this in ADAL. It is imperative that we tell customers to use MSAL for Intune.

**Comment by Erikre** [comment]
@bgavrilMS - Thanks for the feedback. Multiple documentation updates have been made related to this issue. The final updates have been approved to publish, which will happen either today or tomorrow. Thanks
