### ISSUE TITLE
Multiple Enrollment Profiles and Scope Tag behavior change

### ISSUE THREAD

**Issue by jerryabo** [MicrosoftDocs/memdocs#3743]
[
[Enter feedback here]](https://learn.microsoft.com/en-us/mem/intune/fundamentals/whats-new#support-for-multiple-enrollment-profiles-and-tokens-for-fully-managed-devices-)

With the support of multiple enrollment profiles, it appears that scope tags are now being honored on enrollment profiles. The prior behavior is reportedly what was unexpected. Please confirm if there was a behavior change here and consider updating this WN to note it, if so. 

Docs here to generically cover the scope tag setting: **https://learn.microsoft.com/en-us/mem/intune/enrollment/android-fully-managed-enroll**. 

Ref case/inc: 35725169/379590915 for additional details.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d16c28db-1e8e-31fa-6127-3050a2940422
* Version Independent ID: 4cf9a244-1ae5-1637-48f7-3f503d400da6
* Content: [What's new in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/fundamentals/whats-new)
* Content Source: [memdocs/intune/fundamentals/whats-new.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/whats-new.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by yogkumgit** [comment]
@Brenduns Please help us in resolving this issue. Thanks

**Comment by jerryabo** [comment]
Hey @Brenduns looping with you on the related thread

**Comment by Brenduns** [comment]
With details/follow moved to email communications, I am closing this external GitHub issue.  Any progress can be managed internally in conjunction with our product team partners.
