### ISSUE TITLE
Provide security advisory regarding "Supply in the request" Intune PKCS template 

### ISSUE THREAD

**Issue by milesgratz** [MicrosoftDocs/memdocs#3745]
The ```(Optional but recommended): Remove the Domain Users group...``` is a bit of a security understatement considering this is a "Supply in the Request" template without CA Manager Approval. This should be a (Required) setting or some sort of security advisory/tooltip that Domain Users would be able to request certificates on behalf of other users, such as a domain admin user. 

![image](https://user-images.githubusercontent.com/17114534/229921144-026c1ca1-87e2-4168-8f59-1810752055e2.png)
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 41df2048-2b0e-4218-1fc4-d8a657f860cc
* Version Independent ID: e26c4390-87a3-7d5a-4e6f-529b4ccf8759
* Content: [Use a PKCS certificate profile to provision devices with certificates in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/certificates-pfx-configure)
* Content Source: [memdocs/intune/protect/certificates-pfx-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/certificates-pfx-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@milesgratz Thank you for your feedback. I understand your concern, this is more of a design change request and I'd recommend you post this feedback on our main feedback portal (https://feedbackportal.microsoft.com/) so that a dev/product engineer can explain why it is setup this way or honor your request. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@milesgratz  Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
