### ISSUE TITLE
Intune Device License compliance assignment and compliance is VERY vague

### ISSUE THREAD

**Issue by wcneumann219** [MicrosoftDocs/memdocs#3748]
This page says the following:

> You can purchase licenses for any devices separately from user licenses. **Device licenses do not need to be assigned to the devices.** Each device that accesses and uses the online services and related software (including System Center software) **must have a device license.**

This paragraph first says that licenses do not have to be assigned. The next sentence says that each device has to "have a device license." These two sentences are contradictory!

I think you mean to say that in order for an organization to be in compliance with regards to Intune licenses that either the user of the device has to be licensed OR the organization has sufficient Intune device licenses for all the devices that are accessed by users that lack an Intune license.

Is my interpretation correct? If yes, consider changing the text to be clearer. If I'm not correct, please explain how one can ensure that a device has an Intune device license.

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 49021e82-460a-201b-90f0-ca27b1acc1f4
* Version Independent ID: b45ff723-d40f-8325-eafd-0b5703065498
* Content: [Assign Microsoft Intune licenses](https://learn.microsoft.com/en-us/mem/intune/fundamentals/licenses-assign)
* Content Source: [memdocs/intune/fundamentals/licenses-assign.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/licenses-assign.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@wcneumann219 Thank you for your feedback.  Microsoft Intune offers a device-only subscription service that helps organizations manage devices that aren't affiliated with specific users. 

Microsoft Intune device licenses are applicable when a device is enrolled through any of the following methods:

[Windows Autopilot Self-Deploying mode](https://learn.microsoft.com/en-us/windows/deployment/windows-autopilot/self-deploying)
[Apple Device Enrollment Program without user affinity](https://learn.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-ios)
[Apple School Manager without user affinity](https://learn.microsoft.com/en-us/mem/intune/enrollment/apple-school-manager-set-up-ios)
[Apple Configurator without user affinity](https://learn.microsoft.com/en-us/mem/intune/enrollment/apple-configurator-enroll-ios)
[Android Enterprise dedicated](https://learn.microsoft.com/en-us/mem/intune/enrollment/android-kiosk-enroll)
[Using a device enrollment manager account](https://learn.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-manager-enroll)

For more information, See https://learn.microsoft.com/en-us/mem/intune/fundamentals/licenses#device-only-licenses

Hope this helps!

Thanks
Sri

**Comment by wcneumann219** [comment]
Hi Sri,

Thanks for the information, but your information doesn’t address the fact that Microsoft says you don’t have to assign Intune device licenses to devices, but does require that each device has a license.

Those two statements are vague because they are contradictory, aren’t they? The first statement say no assignment is required. The second statement says that each device has to have a license.

Do you understand my concern? If yes, do you think the documentation could be clearer, i.e., say that while no assignment is required, a Client needs to have sufficient licenses that to cover the number of devices that need to leverage a device license.

Bill

Bill Neumann


***@***.******@***.******@***.***
Principal Solutions Architect - Microsoft Cloud
Microsoft Center of Excellence
***@***.******@***.***>
Phone: 240-565-1650
www.connection.com<http://www.connection.com/>​
***@***.***
LINKEDIN<https://www.linkedin.com/company/connection-it/>  l  TWITTER<https://twitter.com/ConnectionIT>  l  FACEBOOK<https://www.facebook.com/Connection4IT/>  l  INSTAGRAM<https://www.instagram.com/ConnectionIT/>  l  YOUTUBE<https://www.youtube.com/c/ConnectionIT>  l  BLOG<https://www.connection.com/social-blog>

**Comment by wcneumann219** [comment]
Hi Sri,

Great. Thanks!

Bill

Bill Neumann


***@***.******@***.******@***.***
Principal Solutions Architect - Microsoft Cloud
Microsoft Center of Excellence
***@***.******@***.***>
Phone: 240-565-1650
www.connection.com<http://www.connection.com/>​
***@***.***
LINKEDIN<https://www.linkedin.com/company/connection-it/>  l  TWITTER<https://twitter.com/ConnectionIT>  l  FACEBOOK<https://www.facebook.com/Connection4IT/>  l  INSTAGRAM<https://www.instagram.com/ConnectionIT/>  l  YOUTUBE<https://www.youtube.com/c/ConnectionIT>  l  BLOG<https://www.connection.com/social-blog>
