### ISSUE TITLE
Jamf Pro

### ISSUE THREAD

**Issue by socialkryptonite** [MicrosoftDocs/memdocs#3749]
Jamf Pro is showing the MacOS Intune Integration used for this as legacy and is going to be  retired this year. But this article is still being updated. Is this something is going to remain supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 54745d43-7151-b13a-57f6-7329856e5d2b
* Version Independent ID: 07d2ffd1-49b6-3046-cc07-a4aa35e4fe61
* Content: [Manually configure Jamf Pro integration with Microsoft Intune - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/conditional-access-integrate-jamf)
* Content Source: [memdocs/intune/protect/conditional-access-integrate-jamf.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/conditional-access-integrate-jamf.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@socialkryptonite Thank you for your feedback. Sorry about the confusion,  I have got this clarified with the product team and Conditional Access in the Jamf message isn’t Azure AD Conditional Access. So no changes in the current integration and it will continue to work. We hope to get them to clarify as soon as possible on their end.

Hope this helps!

Thanks

Sri
