### ISSUE TITLE
TCP port 135 is needed for Repl Link Analyzer to work when using Always On and Azure Load Balancer

### ISSUE THREAD

**Issue by treytro** [MicrosoftDocs/memdocs#375]
We removed TCP port 135 from our ILB. This was done to reduce surface area of attack and because it is not listed as a port needed under the section "After setup completes, the following ports must stay open for Configuration Manager".

While TCP 135 isn't technically needed for CM, it is apparently needed for Repl Link Analyzer so it might be worth mentioning that this port needs a load balancing rule in your ILB if you want to run Repl Link Analyzer in Azure with Always On configured.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49301fc3-9163-d533-1057-f8d994e95bbf
* Version Independent ID: 3c3fbdf1-25ec-3c5f-be4c-46983216d3b5
* Content: [SQL Server Always On - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database)
* Content Source: [memdocs/configmgr/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @treytro for the feedback. I made a tweek, it should publish tomorrow morning at the latest
