### ISSUE TITLE
About monthly update  order of Intune

### ISSUE THREAD

**Issue by mimiyano** [MicrosoftDocs/memdocs#3762]
Hi.I'd like to confirm the "Note" of Each monthly update.

What's new in Microsoft Intune
https://learn.microsoft.com/en-us/mem/intune/fundamentals/whats-new
![image](https://user-images.githubusercontent.com/30167845/230893032-3b1f8c3f-2c29-41c0-a703-447d22b9fa27.png)

It seems that each monthly update is always deployed to APAC first.
Some customers say that it seems that APAC is likely a tester area of others.
It isn't fair if it is true.

I checked the page "Microsoft Intune Service Updates" <https://techcommunity.microsoft.com/t5/intune-customer-success/microsoft-intune-service-updates/ba-p/358728>,and could understand ”There is a difference between us updating the service in the backend and when you see the updates reflected in the console.”

From my understanding,the Note is incorrect.And it causes misleading a lot.
So could you please rewrite this Note correctly like below?

Before(Now)：
Each monthly update may take up to three days to rollout and will be in the following order:
(There is a link to "Microsoft Intune Service Updates - Microsoft Community Hub" on the word "monthly update")

After(Expected)：
There is a difference between us updating the service in the backend and when you see the updates reflected in the console.
Please see here(add link to "Microsoft Intune Service Updates - Microsoft Community Hub" on the word "here").
Each monthly update of UI may take up to three days to rollout and will be in the following order:

Regards,

**Comment by Brenduns** [comment]
@mimiyano	Thanks for the GitHub issue and PR. I’ve shared your feedback with our larger communications team for Intune, and the decision is to not introduce a change to the What’s new article for this.  

The intent is to alert the reader in a simple manner that the rollout of service releases for Intune can take time, as it requires a phased update across several engineering/geographic regions. Deeper details about the rollout process will remain available via the blog link in the what’s new article, at [how Intune service updates are released](https://techcommunity.microsoft.com/t5/Intune-Customer-Success/Microsoft-Intune-Service-Updates/ba-p/358728).
