### ISSUE TITLE
Enable tamper protection to prevent Microsoft Defender being disabled

### ISSUE THREAD

**Issue by Trevor-G30IT** [MicrosoftDocs/memdocs#3764]
Disabling Tamper Protection isn't working via disabling this setting via Intune. For Windows 10 and 11 devices, it shows the state as "not applicable".

Should be noted the device is onboarded and enrolled in MDE via DFE P2 licensing via a ME5 license. The device is managed by MDE and not managed by Intune, which might make this an issue. 

Also, when you do this, it throws a high-level alert for the device or devices the policy touches; thus, IoCs have to be made.

Please look into this and let me know why this isn't working on disabling Tamper Protection. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2b8a34da-0faa-7a06-ff20-b3a2fa76f8b0
* Version Independent ID: 8bb1136b-c0ae-6bba-dd87-e16e34dac93d
* Content: [Windows Antivirus policy settings from Windows security settings for tenant attached devices in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/antivirus-windows-security-settings-windows-tenant-attach)
* Content Source: [memdocs/intune/protect/antivirus-windows-security-settings-windows-tenant-attach.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/antivirus-windows-security-settings-windows-tenant-attach.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@Trevor-G30IT Thank you for your feedback. This sounds more like a bug on the M365 tenant, I'd recommend you open a support ticket via the need help section on the admin center, so that a support engineer can help you fix this.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Trevor-G30IT Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
