### ISSUE TITLE
Clarify "device details" for Apple Configurator enrollment

### ISSUE THREAD

**Issue by jdgregson** [MicrosoftDocs/memdocs#3765]
Under the [Add Apple Configurator serial numbers](https://learn.microsoft.com/en-us/mem/intune/enrollment/apple-configurator-enroll-ios#add-apple-configurator-serial-numbers) section, readers are instructed to put the device serial number and "the details" in a CSV file:

    1. Create a two-column, comma-separated value (.csv) list without a header. Add the serial number in the left column, and the details in the right column. The current maximum for the list is 5,000 rows. In a text editor, the .csv list looks like this:

        F7TLWCLBX196,device details
        DLXQPCWVGHMJ,device details

However, I cannot see anything on the page or elsewhere that clarifies what "the details" or "device details" is referring to. I assume that these details can be anything that we want, such as the name of the user that will use the device, or a description of the device.

Please confirm that my assumption is correct or otherwise clarify what details are expected here.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5881e9f0-4f4d-7ca6-1308-48894cb17e87
* Version Independent ID: 1b8bb3b8-b3e9-b540-e4db-8d1facb6555e
* Content: [iOS/iPadOS device enrollment - Apple Configurator-Setup Assistant - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/enrollment/apple-configurator-enroll-ios)
* Content Source: [memdocs/intune/enrollment/apple-configurator-enroll-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/apple-configurator-enroll-ios.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by yogkumgit** [comment]
@lenewsad Please help us in resolving this issue. Thanks

**Comment by lenewsad** [comment]
Hi @jdgregson, thank you for reaching out to the Microsoft Docs team for more clairification. Yes, you are correct; you can add any details you want. I added a better example to the article that shows the type of details and formatting you can use. Those changes will be live soon. 

CC: @yogkumgit Thank you!

**Comment by OGPlugBone** [comment]
Having an issue where it accepts 1 of my 8 uploads, but when i remove the most recent added one and try to re-upload the other 7 receive a message of: "Failed to add devices. No new devices were added."

They are setup the exact way i used to upload the other successful device upload but cannot get these 7 added.
