### ISSUE TITLE
Documentation does not reflect Intune behavior

### ISSUE THREAD

**Issue by kludgefactory** [MicrosoftDocs/memdocs#3768]
Under https://learn.microsoft.com/en-us/mem/intune/remote-actions/device-sync#sync-a-device
"To see the status of the sync action, choose Devices > Monitor > Device actions."

Syncing is not one of the Actions shown in the "Monitor > Device Actions" table in Intune. Syncing is also not a filterable action.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a6cb3efe-0b30-d8e2-d81e-15e11b31cabe
* Version Independent ID: e9d478d0-9cb7-518d-cb47-023868caee0c
* Content: [Sync devices with Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/remote-actions/device-sync)
* Content Source: [memdocs/intune/remote-actions/device-sync.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/device-sync.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@kludgefactory  Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3801

Once the author approves, the changes will be live.

Thanks
Sri
