### ISSUE TITLE
Document

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/memdocs#377]
Hello,
Cannot access link under this part:
<<<see the Enterprise Mobility + Security blog post _**Better together: Intune and Azure Active Directory team up to improve user access.**_>>>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90ddc5ef-0a7a-cb85-e22e-e8e9f771d249
* Version Independent ID: da218a79-e209-223b-210d-ba31131fba86
* Content: [Manage corporate web access with a policy-protected browser - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-configuration-managed-browser)
* Content Source: [memdocs/intune/apps/app-configuration-managed-browser.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-configuration-managed-browser.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@lightupdifire - Thank you for the feedback. I just tried the link and it worked. Seems like a temporary issue, but the link works now.

**Comment by lightupdifire** [comment]
@Erikre 
Thanks for the check, indeed works fine now :)
