### ISSUE TITLE
About App Protection Policy documentation.

### ISSUE THREAD

**Issue by rodrigobcd** [MicrosoftDocs/memdocs#3776]
A note should be included warning that f the App Protection Policy is related to "Managed Devices" it is also necessary to create an App Configuration Profile of the application that has Intune integrated, adding the minimum configuration for it to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 893c295c-9fa2-954f-4c9c-8b776d43f182
* Version Independent ID: dd4a72fe-ddde-4ed7-c408-c987f18c5d2a
* Content: [Microsoft Intune App SDK for iOS developer guide](https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios?source=recommendations#configuring-a-test-user-for-app-protection-ca)
* Content Source: [memdocs/intune/developer/app-sdk-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/developer/app-sdk-ios.md)
* Service: **microsoft-intune**
* Sub-service: **developer**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@rodrigobcd Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3800

Once the author approves, the changes will be live.

Thanks
Sri
