### ISSUE TITLE
MDM, MAM and WIP

### ISSUE THREAD

**Issue by abragha** [MicrosoftDocs/memdocs#3777]
The document says following as important note.

For Windows BYOD devices, the MAM user scope takes precedence if both the MAM user scope and the MDM user scope (automatic MDM enrollment) are enabled for all users (or the same groups of users). **The device will not be MDM enrolled, and Windows Information Protection (WIP) policies will be applied if you have configured them.**

The WIP has been deprecated for MDM Unenrolled windows devices, hence above statement is confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: adbfe90c-635e-5d23-f0b3-2d015565e311
* Version Independent ID: bcc85788-87a8-c3b5-1b60-a4938a09e541
* Content: [Set up automatic enrollment in Intune](https://learn.microsoft.com/en-us/mem/intune/enrollment/quickstart-setup-auto-enrollment)
* Content Source: [memdocs/intune/enrollment/quickstart-setup-auto-enrollment.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/quickstart-setup-auto-enrollment.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@abragha Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3799

Once the author approves, the changes will be live.

Thanks
Sri
