### ISSUE TITLE
 Firewall Documentation of Baseline is unclear

### ISSUE THREAD

**Issue by weyCC81** [MicrosoftDocs/memdocs#3778]
The "Learn more" link in the Firewall area don't work, please update...

Does "Authorized application rules from group policy not merged" mean "MdmStore/PrivateProfile/AuthAppsAllowUserPrefMerge"
Does "Global port rules from group policy merged" mean "MdmStore/PrivateProfile/GlobalPortsAllowUserPrefMerge"

or the Site: https://github.com/MicrosoftDocs/IntuneDocs/blob/main/intune/protect/security-baseline-settings-defender-atp.md

The following site is better structutred to understand the impact: https://learn.microsoft.com/en-us/mem/intune/protect/endpoint-security-firewall-profile-settings-tenant-attach#private-profile

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 10ff4382-415c-4e80-e958-3bd77252fe2d
* Version Independent ID: 398a5b4b-e8bd-1f7d-ae30-38d812daf90d
* Content: [Settings list for the Microsoft Defender for Endpoint security baseline in Microsoft Intune - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/security-baseline-settings-defender-atp?pivots=atp-december-2020)
* Content Source: [memdocs/intune/protect/security-baseline-settings-defender-atp.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/security-baseline-settings-defender-atp.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by yogkumgit** [comment]
@Brenduns Please help us in resolving this issue. Thanks

**Comment by Brenduns** [comment]
@[weyCC81](https://github.com/weyCC81)   Thanks for this GitHub issue.  
**Short answer**: You are correct in matching the setting names from the baseline to the CSP settings: 
-	Authorized application rules from group policy not merged > AuthAppsAllowUserPrefMerge
-	Global port rules from group policy merged  > GlobalPortsAllowUserPrefMerge

**Background you might find interesting or of use:**
In security baseline docs are a direct UI reference and are not intended to provide additional detail but are intended to identify the default configuration of each setting, as that default represents the security baselines recommended configuration and security posture.

From the onset of Baselines, we attempted to provide a bit more content per setting, but that became untenable when CPS revised their details without our knowledge, which left our docs confusing/unclear/outdated.  Instead, we now rely on the source CSP for those details. That does raise the question about the links being somewhat generic to the CSP page, and the setting names not clearly aligned to the CSPs that apply to, which has been a longstanding problem.

You also noted the improved value in the other article (for a policy that is for tenant attached devices). That article is one that describes polices based on a new settings format that Intune began to roll out in April 2022 to some policies, and which we should see coming to security baselines soon.

That rollout will help resolve the challenges you’ve identified here, as the setting names in the UI will be direct matches to the CSP names (though we add spaces to make them more readable. For example, in the new format the CSP setting for _GlobalPortsAllowUserPerfMerge_ would appear in Intune as _Global Ports Allow User Perf Merge_). The information text for settings will also be pulled from the source CSP, which is the behavior and content owner for how CSPs function.
Hope that helps, and I’d say stay tuned for those future updates.
