### ISSUE TITLE
Document

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/memdocs#378]
Hello,
About this part:
<<<To restrict Azure AD-connected web apps to use the Intune Managed Browser on mobile platforms, you can create a Conditional Access policy requiring approved client applications.>>>
Maybe it is better to say "Managed Browser" instead of "Intune Managed Browser"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90ddc5ef-0a7a-cb85-e22e-e8e9f771d249
* Version Independent ID: da218a79-e209-223b-210d-ba31131fba86
* Content: [Manage corporate web access with a policy-protected browser - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-configuration-managed-browser)
* Content Source: [memdocs/intune/apps/app-configuration-managed-browser.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-configuration-managed-browser.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@lightupdifire - Thanks for the feedback. Yes, you are correct. The docs have been update to point to Edge. Thanks
