### ISSUE TITLE
Technology decisions for enabling BYOD with Microsoft Enterprise Mobility + Security (EMS)

### ISSUE THREAD

**Issue by lowfitcorp1** [MicrosoftDocs/memdocs#3783]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a91194ed-2496-2a49-f0cc-6f80fce1fbcc
* Version Independent ID: 0d780bfc-9d5e-b48d-4f92-c6b7b36ea456
* Content: [Technology decisions for BYOD with EMS](https://learn.microsoft.com/en-us/mem/intune/fundamentals/byod-technology-decisions)
* Content Source: [memdocs/intune/fundamentals/byod-technology-decisions.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/byod-technology-decisions.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @dougeby
* Microsoft Alias: **dougeby**

**Comment by msbemba** [comment]
@lowfitcorp1 Thank you for your feedback. Yes, the document does discuss and examine the simple use case of enabling BYOD access to the corporate email.

Hope this helps!

Thanks
Sri

**Comment by lowfitcorp1** [comment]
Thanks once again. Pleasure having you.
