### ISSUE TITLE
Update external link for Aruba ClearPass

### ISSUE THREAD

**Issue by tenokraat** [MicrosoftDocs/memdocs#3784]
The link to the "Integrate HP Aruba ClearPass with Intune"(https://support.arubanetworks.com/Documentation/tabid/77/DMXModule/512/Command/Core_Download/Default.aspx?EntryId=31271) is outdated and redirects to a page that no longer exists.

Please update either with the direct link to the Aruba portal: https://asp.arubanetworks.com/downloads;search=Intune;products=Aruba%20ClearPass%20Policy%20Manager%20%28CPPM%29 

Or alternatively, please link generically to the Aruba Support Portal: https://asp.arubanetworks.com/

Additionally, the product is no longer called "HP Aruba ClearPass" but "HPE Aruba Networking ClearPass".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0c4b9bdf-975f-6116-51cc-08b29431ebbc
* Version Independent ID: 8a82d44e-4535-27a9-63d4-ab9612f30d64
* Content: [Network access control integration with Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/network-access-control-integrate)
* Content Source: [memdocs/intune/protect/network-access-control-integrate.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/network-access-control-integrate.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@tenokraat Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3834

Once the author approves, the changes will be live.

Thanks
Sri
