### ISSUE TITLE
Scripts.log missing from the list

### ISSUE THREAD

**Issue by yulasinio** [MicrosoftDocs/memdocs#379]
Just notice today that logs related to managing or running scripts are missing from the list.
Maybe they can be added at some stage.

https://docs.microsoft.com/en-us/mem/configmgr/apps/deploy-use/create-deploy-scripts#log-files

Thank you.

(edit: add target article metadata for linking)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45ee8aa0-8e36-3e5b-ab3a-77400946aa82
* Version Independent ID: a26d29fc-18f4-4a36-9e81-b2e9c59bce15
* Content: [Create and run scripts - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/apps/deploy-use/create-deploy-scripts#log-files)
* Content Source: [memdocs/configmgr/apps/deploy-use/create-deploy-scripts.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/apps/deploy-use/create-deploy-scripts.md)
* Product: **configuration-manager**
* Technology: **configmgr-app**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @yulasinio for the feedback. It looks like "scripts.log" was added to this article already, but it's not in the main [Log file reference](https://docs.microsoft.com/mem/configmgr/core/plan-design/hierarchy/log-files) article. I'll include them there as well.

**Comment by yulasinio** [comment]
Fantastic work as always 👍🏻

Thanks
Julian
