### ISSUE TITLE
Instructions are wrong

### ISSUE THREAD

**Issue by RwYeAsNt** [MicrosoftDocs/memdocs#3794]
This page needs to be updated with new information. The Step 2 instructions are no longer relevant and are impossible to follow with the new Intune admin center.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9bc0159d-5a5e-ea2c-042d-bd5ead842d0b
* Version Independent ID: 83266995-5234-3b09-784d-75bb1844e5f3
* Content: [Intune settings for the iOS/iPadOS Classroom app - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/fundamentals/education-settings-configure-ios)
* Content Source: [memdocs/intune/fundamentals/education-settings-configure-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/education-settings-configure-ios.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @RwYeAsNt, thank you for reaching out to the Microsoft Intune documentation team.  This article is only applicable for Intune tenants with existing iOS/iPadOS education profiles in Intune.  Intune doesn't currently support configuring the Classroom app so if you don't have an existing education profile, the options described in this article won't be available. If you do have an existing profile, please follow up with us and we'll reopen this issue.

**Comment by RwYeAsNt** [comment]
I see. This is big a disappointment, but I appreciate you taking the time to explain it to me.

________________________________
