### ISSUE TITLE
How often are Settings Catalog updated?

### ISSUE THREAD

**Issue by JonesMikael** [MicrosoftDocs/memdocs#3807]
Can you please document how often Settings Catalog is updated? For example, there are some new **Google Chrome** settings available in the Administrative Templates that Google has released in Chrome 111. It is the following setting to be exact: https://chromeenterprise.google/policies/?policy=CloudAPAuthEnabled

When do you think we can expect this setting being available in Settings Catalog?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 671037ee-a099-5796-04c1-713be23f7d17
* Version Independent ID: 68957221-d9f4-9cf6-0988-83df9386d067
* Content: [Create a policy using settings catalog in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/configuration/settings-catalog)
* Content Source: [memdocs/intune/configuration/settings-catalog.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/settings-catalog.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by yogkumgit** [comment]
@MandiOhlinger Please help us in resolving this issue. Thanks

**Comment by MandiOhlinger** [comment]
@JonesMikael We don't have an ETA on when the Chrome ADMX template will be updated. It's definitely on our radar. When it happens, it should be announced in [What's New](https://learn.microsoft.com/mem/intune/fundamentals/whats-new).

As for the settings catalog, new settings are continually added. So far, settings have been added with every monthly release.

FYI @yogkumgit
