### ISSUE TITLE
Locate device setting is missing in the documentation 

### ISSUE THREAD

**Issue by GarnikMargaryan** [MicrosoftDocs/memdocs#3808]
![2023_04_21_20_09_06_Device_restrictions_Microsoft_Intune_admin_center_and_5_more_pages_Work_Mi](https://user-images.githubusercontent.com/131486944/233716065-b7ee0745-cef4-42dc-b24b-81f66841ab8f.jpg)
**Fully managed and corporate-owned work profile devices**
_These settings only work for fully managed and corporate-owned work profile devices._

Locate device: **Allow** or **Not Configured.**

Please provide information regarding the "Locate device" settings for fully managed and corporate-owned work profile devices. If this setting is not enabled, the "Locate device" remote action will be grayed out on the Intune portal for the following devices: dedicated devices, fully-managed devices, and corporate-owned work profile devices.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 900e72be-d42b-49ba-f304-602df23cbb04
* Version Independent ID: 2ce5c45d-15be-d316-1c57-92bea37358e0
* Content: [Corporate-owned Android Enterprise device restriction settings in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/configuration/device-restrictions-android-for-work)
* Content Source: [memdocs/intune/configuration/device-restrictions-android-for-work.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/device-restrictions-android-for-work.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by msbemba** [comment]
@GarnikMargaryan Thank you for your feedback. We will review and update the document shortly.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba

**Comment by MandiOhlinger** [comment]
@GarnikMargaryan Thank you! The setting is added. Changes should be live later today sometime.

FYI @yogkumgit
