### ISSUE TITLE
Blocking URL's

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/memdocs#381]
Hello,
Somehow block URL not work, please correct if doing something wrong:
If applied: domain.com -> block works fine but can browse any subfolder, as for example domain.com/about
If applied as an example:
https://www.lamborgini.com/*
https://\*.lamborgini.com/*
https://lamborgini.com
https://www.lamborgini.com
Still can browse to https://www.lamborghini.com/en-en/

So if there is as an example a phishing attack, we want to block site lamborghini.com and any subdomain and any folder, like \*.lamborghini.com\*?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90ddc5ef-0a7a-cb85-e22e-e8e9f771d249
* Version Independent ID: da218a79-e209-223b-210d-ba31131fba86
* Content: [Manage corporate web access with a policy-protected browser - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-configuration-managed-browser)
* Content Source: [memdocs/intune/apps/app-configuration-managed-browser.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-configuration-managed-browser.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by lightupdifire** [comment]
Hello,
Lambo site used just for a test :) here is my config, used based on this document, I will also open  Support Case.
![image](https://user-images.githubusercontent.com/39700914/84893739-039b8080-b0a0-11ea-8d9a-e9e174bc71e9.png)
I want to make sure that browser can't go to any folder or host of DNS lamborgini.com, but using above config I can browse to https://www.lamborghini.com/en-en/

**Comment by lightupdifire** [comment]
Please wait, I see a typo :) bad me, the site is **lamborghini**, missing H in my setup, testing new settings.

**Comment by lightupdifire** [comment]
Hello,
Ok, it works now, my bad :) typo with H, case close.

**Comment by lightupdifire** [comment]
Hello,

Found a bug in setup, so the document requires updates.
If Intune App Protect setup were done before this solution become available, which is possible for 90%+ of customers, then:
1. When changing the setup and apply this configuration to manage Edge for iOS -> after syncing device all work: Outlook asks to install Edge, Edge policy applied, and sites blocked.
2. When changing the setup and apply this configuration to manage Edge for Android -> require device re-enroll.

**This is really not nice, how can we communicate at the Enterprise level to our 1000+ Android users that they require to re-enroll their device?**

**Comment by Erikre** [comment]
@lightupdifire - Thanks for sharing this with the Intune documentation team. If you are still running into problems related to this issue, we want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

This question is in our documentation feedback channel and it may be best to handle this question as a support request. For this reason, I'm closing this issue. Please use the above channels if you don't already have a solution.
