### ISSUE TITLE
intune-portal pre-installation commands require updating with sudo/sudo -s

### ISSUE THREAD

**Issue by UsersHaveNames** [MicrosoftDocs/memdocs#3811]
On a fresh Ubuntu 22.04 installation, the issue was in the below one liner from the documentation:

`curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg`

The above one-liner has to be updated in the docs IMO, otherwise it only succeed. The user must use ` sudo -s` or prefix it with `sudo`.

NOTE: For some reason sudo is no longer needed once this has been done at least once on the OS.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80924804-c247-d3bb-2245-fd3db3f3bd62
* Version Independent ID: 80924804-c247-d3bb-2245-fd3db3f3bd62
* Content: [Get the Microsoft Intune app for Linux](https://learn.microsoft.com/en-us/mem/intune/user-help/microsoft-intune-app-linux)
* Content Source: [memdocs/intune/user-help/microsoft-intune-app-linux.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/microsoft-intune-app-linux.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by UsersHaveNames** [comment]
Apologies, things started working. The issue was in the below one liner:

`curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg`

The above oneliner has to be updated in the docs IMO, otherwise only succeed if the used first enters `sudo -s`

**Comment by lenewsad** [comment]
Hi @UsersHaveNames @yogkumgit, thanks for reaching out to the Microsoft Intune docs team and providing this info. I'm checking with the product team about PR #3816, and shared the info from this issue with them for context. I'll follow up with more info when I hear back.

**Comment by lenewsad** [comment]
Closing per [PR 3816(https://github.com/MicrosoftDocs/memdocs/pull/3816).
