### ISSUE TITLE
Grammar error - Intune Support For Windows LAPS

### ISSUE THREAD

**Issue by AlexVidal2** [MicrosoftDocs/memdocs#3813]
[Enter feedback here]
There is a grammar error in the page "Intune Support For Windows LAPS", under "Role based access controls for LAPS". 

To manage LAPS, an account (Error: must be) have sufficient role-based access control (RBAC) permissions to complete a desired task. The following are the available tasks with their required permissions:

[https://learn.microsoft.com/en-us/mem/intune/protect/windows-laps-overview](url)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8eac0015-5225-7fc1-eb61-155efc075492
* Version Independent ID: 8eac0015-5225-7fc1-eb61-155efc075492
* Content: [Manage Windows LAPS with Microsoft Intune policies](https://learn.microsoft.com/en-us/mem/intune/protect/windows-laps-overview)
* Content Source: [memdocs/intune/protect/windows-laps-overview.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/windows-laps-overview.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@AlexVidal2   Thanks for raising this to our awarness. I've just submitted an edit to fix that, which should show up later this evening in the published content.

**Comment by AlexVidal2** [comment]
Awesome, glad I could help!
