### ISSUE TITLE
Retirement of the Microsoft Store for Business needs to be updated in Product Documentation

### ISSUE THREAD

**Issue by SuhailASalam** [MicrosoftDocs/memdocs#3815]
[Enter feedback here]
According to the Blog Post written by the PM (Juanita Baptiste)
"Editor's note (3.23.2023): The retirement of the Microsoft Store for Business and the Microsoft Store for Education, originally scheduled for March 31, 2023, has been postponed. We will share an update here on future plans when they're available."
https://techcommunity.microsoft.com/t5/windows-it-pro-blog/support-tip-microsoft-store-for-business-retirement-and-windows/ba-p/3662691

This page needs to be updated to remove the retirement in the first Quarter of 2023.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dac06439-a7c6-b637-3268-e1ed8f59ad15
* Version Independent ID: c43caaad-0392-394c-62ca-1216dd488652
* Content: [Manage VPP apps from Microsoft Store for Business - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/apps/windows-store-for-business)
* Content Source: [memdocs/intune/apps/windows-store-for-business.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/windows-store-for-business.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@SuhailASalam Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3848

Once the author approves, the changes will be live.

Thanks
Sri
