### ISSUE TITLE
A full device wipe

### ISSUE THREAD

**Issue by kuvinod7** [MicrosoftDocs/memdocs#3817]
[Enter feedback here]

As per the document, it is stated as " For hybrid Azure AD join devices, a full device wipe is required." What is full device wipe? Is it this option when you do a Wipe from the device console?

**Wipe device, and continue to wipe even if device loses power. If you select this option, please be aware that it might prevent some devices running Windows 10 and later from starting up again**

It would be easier for us if we can specify the full device wipe in detail
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 34e607f9-65f4-5703-ad20-d9fa909ce015
* Version Independent ID: 34e607f9-65f4-5703-ad20-d9fa909ce015
* Content: [Overview for Windows Autopilot Reset in Intune](https://learn.microsoft.com/en-us/mem/autopilot/tutorial/reset/autopilot-reset-overview)
* Content Source: [memdocs/autopilot/tutorial/reset/autopilot-reset-overview.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/tutorial/reset/autopilot-reset-overview.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
Thank you for the feedback @kuvinod7. Yes a full device wipe in Intune as described here:

https://learn.microsoft.com/mem/intune/remote-actions/devices-wipe

You could also use the Windows Autopilot deployment for existing devices as described here:

https://learn.microsoft.com/mem/autopilot/tutorial/existing-devices/existing-devices-workflow

I'll update the docs to include links.
