### ISSUE TITLE
Conflicting information regarding AppPrefixAllowList

### ISSUE THREAD

**Issue by MarcLaf** [MicrosoftDocs/memdocs#3818]
In this article for iOS (not MacOS) devices, the configuration policy should have AppPrefixAllowList set to com.apple. as the recommended value and then right below in the examples say set it to com.microsoft.,com.apple. to allow both Microsoft and Apple. Then lower on the page it says "When you're done configuring the recommended settings, the settings look similar to the following values in your Intune configuration profile:" and goes on to show the entry com.microsoft.,com.apple.

On the Microsoft Enterprise SSO plug-in page [link](https://learn.microsoft.com/en-us/azure/active-directory/develop/apple-sso-plugin#enable-sso-for-all-apps-with-a-specific-bundle-id-prefix) it states:

For iOS, the default value would be set to com.apple. and that would enable SSO for all Apple apps. For macOS, the default value would be set to com.apple. and com.microsoft. and that would enable SSO for all Apple and Microsoft apps. 

Based on this, the iOS specific page (that this feedback is for) should not mention com.microsoft. in the example or what the settings should look like as it causes confusion to what the proper setting should be.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 960dfaaa-cc18-36aa-1a34-016326d2cf72
* Version Independent ID: 960dfaaa-cc18-36aa-1a34-016326d2cf72
* Content: [Configure iOS/iPadOS Enterprise SSO plug-in with MDM](https://learn.microsoft.com/en-us/mem/intune/configuration/use-enterprise-sso-plug-in-ios-ipados-with-intune?tabs=prereq-intune%2Ccreate-profile-intune)
* Content Source: [memdocs/intune/configuration/use-enterprise-sso-plug-in-ios-ipados-with-intune.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/use-enterprise-sso-plug-in-ios-ipados-with-intune.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @tbc
* Microsoft Alias: **alessanc**

**Comment by msbemba** [comment]
@MarcLaf Thank you for your feedback. We shall update the document and the screenshot shortly.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba

**Comment by MandiOhlinger** [comment]
@MarcLaf The current text is correct as-is, as it's documenting examples of what to add. I did clarify the example screen shot to state that it's allowing Apple & Microsoft apps.

The changes should be live later today sometime. Thank you!

FYI @yogkumgit
