### ISSUE TITLE
Add reference to EasyScep 

### ISSUE THREAD

**Issue by JustSoftwareNPE** [MicrosoftDocs/memdocs#3820]
Page should contain link to EasyScep CA for Intune also

Marketplace link:
https://azuremarketplace.microsoft.com/en-us/marketplace/apps/justsoftwareaps1663178247196.saas-easy-scep

Vendor page:
https://www.just-software.dk/easyscep

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cda83a64-56ae-a632-dc81-dfd1a03984c1
* Version Independent ID: b93da48e-4097-4c3a-f6c8-02a5c4e0a616
* Content: [Use third-party certification authorities (CA) with SCEP in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/certificate-authority-add-scep-overview)
* Content Source: [memdocs/intune/protect/certificate-authority-add-scep-overview.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/certificate-authority-add-scep-overview.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by yogkumgit** [comment]
@JustSoftwareNPE Internal communication is on. Will update once we hear back on this. Thanks

**Comment by Brenduns** [comment]
@JustSoftwareNPE  Some time back I passed this information to our product and engineering team for confirmation as to our validation of support for EasySCEP, but there has been no updates to indicate that testing is underway - or complete.  As our engineering team has not provided confirmation that EasySCEP has reached out to engage with Intune to be validated as a tested solution, and thus included as a Third-Party CA within our documentation, we won’t be able to add them to content at this time.  Should that change in the future and EasySCEP does become certified/reviewed by our product team, our internal team will then drive a content update to update our documentation.  

Not being listed in our docs doesn’t mean the solution won’t succeed, but typically if there are issues that require support, support success cannot be guaranteed for environments where a non-supported (non-validated/tested solution) is involved.
