### ISSUE TITLE
CN="{{OnPrem_Distinguished_Name}}" does not work

### ISSUE THREAD

**Issue by ncheymol** [MicrosoftDocs/memdocs#3821]
Hello,

the solution provided in the documentation when you have a comma in the Distinguished Name does not work, the NDES refuses the certificate request even when there is no comma.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 30c444f9-5cc4-7276-6882-d6b32ee453ea
* Version Independent ID: f1ec96ac-c890-2ed1-ede4-179de4b4e4cc
* Content: [Use SCEP certificate profiles with Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/certificates-profile-scep)
* Content Source: [memdocs/intune/protect/certificates-profile-scep.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/certificates-profile-scep.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@ncheymol Thank you for your feedback. This looks like a technical issue and I'd recommend you reaching out to support via the need help section on the admin center, so that our support team can help you fix the issue.

Hope this helps!

Thanks
Sri
