### ISSUE TITLE
Autopilot for existing devices

### ISSUE THREAD

**Issue by nhogarth86** [MicrosoftDocs/memdocs#3826]
Autopilot for existing devices doesn't explicitly require ConfigMgr, as the JSON file can be copied with MDT or other solutions.
Also I think a Con for Autopilot for existing devices should be that a group tag cannot be assigned, as there is no Autopilot registered device, as it uses the JSON file. Without the group tag you can't prestage policies/apps etc to the Azure AD group without a group tag because dynamic Azure AD Group rules don't kick in fast enough.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0e4148e8-0007-a7e9-1fec-c521786eb523
* Version Independent ID: 0e4148e8-0007-a7e9-1fec-c521786eb523
* Content: [Windows Autopilot scenarios](https://learn.microsoft.com/en-us/mem/autopilot/tutorial/autopilot-scenarios)
* Content Source: [memdocs/autopilot/tutorial/autopilot-scenarios.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/tutorial/autopilot-scenarios.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
Thank you for the feedback @nhogarth86. Yes, I agree that there are other methods and tools that can be used to implement Windows Autopilot for existing devices, but the docs cover what Microsoft explicitly supports and what is available natively in Microsoft products. For example, the ConfigMgr task sequence wizard has an option to create an Autopilot task sequence, but MDT doesn't. MDT also doesn't support Windows 11 so we really can't suggest using MDT.

Regarding Group Tags, that is actually going to be one of the next topics that we cover as part of this Tutorial section. I didn't want to start talking about Group Tags, for example as pro or con, until we had a section on Group Tags. Once we create that section, I will definitely look into adding it as con.

I do talk about having the register the device as an Autopilot device as the last step in the Windows Autopilot deployment for existing devices section:

https://learn.microsoft.com/en-us/mem/autopilot/tutorial/existing-devices/register-device
