### ISSUE TITLE
Include version examples

### ISSUE THREAD

**Issue by Kazzan** [MicrosoftDocs/memdocs#383]
Hi, Windows page have details and examples of version to compare within the minimum version of OS version and Build version. Such should be there also.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30e5c360-263e-fd7b-1f45-9334e647e0ef
* Version Independent ID: cb245be4-6704-8b05-630f-f40e63d091eb
* Content: [iOS/iPadOS device compliance settings in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/compliance-policy-create-ios)
* Content Source: [memdocs/intune/protect/compliance-policy-create-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/compliance-policy-create-ios.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
The Windows examples are provided n context of additional settings for Valid Operating System Builds, which isn't something that appears to be applicable to the iOS settings.

**Comment by Kazzan** [comment]
Hi, what is the inconsistency in this with Windows version numbering is that it is full build number.

Not version 10.
Not version 20H2.
Not version 19042.
But 10.0.19042.685.

On iOS one can ask, same as patch level on Android, it is 14.3 or 18C66?

But currently you start listing the minimum applicable version for each policy, so I mean that with this is clearer in overal context.
