### ISSUE TITLE
Wired network profile not in Windows 10/11 table

### ISSUE THREAD

**Issue by RalfVDL** [MicrosoftDocs/memdocs#3835]
The "Wired network" profile is not in the Windows 10/11 table*.

I am able to configure a Wired profile for Windows 10/11:

![image](https://user-images.githubusercontent.com/132268462/235448652-a4584b8f-4159-4cb4-b22a-11de1faffc31.png)

It does seem like filters are not supported in this profile:

![image](https://user-images.githubusercontent.com/132268462/235448808-9be6f191-1c25-44d1-9a61-5ab0897fb1f6.png)

Which is a major bummer, but that's a problem for another day.

\* It is in the macOS table though.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e48a40e1-7253-d2fb-e269-d1de88b34b8e
* Version Independent ID: bf0dd637-947c-33b6-9678-b09193946e95
* Content: [Platforms and policy types supported by filters in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/fundamentals/filters-supported-workloads)
* Content Source: [memdocs/intune/fundamentals/filters-supported-workloads.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/filters-supported-workloads.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by msbemba** [comment]
@RalfVDL Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3855

Once the author approves, the changes will be live.

Thanks
Sri
