### ISSUE TITLE
Autopilot for existing devices and pre-provisioning or self-deploying

### ISSUE THREAD

**Issue by nhogarth86** [MicrosoftDocs/memdocs#3841]
Hi, in the note where it says "The Windows Autopilot for existing devices scenario is a method to completely reinstall Windows on a device in preparation to run an Autopilot deployment. However the Windows Autopilot for existing devices scenario itself isn't technically an Autopilot deployment. After the Windows Autopilot for existing devices process completes, it automatically runs either the User-driven, Pre-provisioned, or Self-deploying Autopilot scenario."

I thought the JSON Autopilot profile does not support pre-provisioning or self-deploying? Or is the note here https://learn.microsoft.com/en-us/mem/autopilot/existing-devices "Windows Autopilot for existing devices only supports user-driven Azure AD and hybrid Azure AD profiles. Self-deploying and pre-provisioning profiles aren't supported." incorrect?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0e4148e8-0007-a7e9-1fec-c521786eb523
* Version Independent ID: 0e4148e8-0007-a7e9-1fec-c521786eb523
* Content: [Windows Autopilot scenarios](https://learn.microsoft.com/en-us/mem/autopilot/tutorial/autopilot-scenarios)
* Content Source: [memdocs/autopilot/tutorial/autopilot-scenarios.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/tutorial/autopilot-scenarios.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
Actually, I take it back @nhogarth86. Existing devices can potentially support both the pre-provisioning and self-deploying scenarios if the device is already an Autopilot device with an Autopilot profile assigned to the device. In this case the existing Autopilot profile assigned to the device will override the JSON file and it should work. I will clarify in the docs and make corrections where needed.

**Comment by frankroj** [comment]
Just FYI @nhogarth86 I tested a scenario using an existing devices task sequence where I specified a JSON file for a user-driven AAD Autopilot profile. However, the device I tested on was already an Autopilot device with a self-deploying Autopilot profile assigned to it. I confirmed that after the task sequence finished and it started Autopilot, that it used the self-deploying Autopilot profile and not the user-driven AAD profile from the JSON file.

**Comment by nhogarth86** [comment]
Thanks. Yes, it would be good if the docs could be updated to say for the JSON it supports initially only user driven (so not ideal for kiosks etc) but you can then target an Autopilot profile to convert the device to Autopilot, then use self deploying or pre prov depending on the use case. And the Autopilot profile will then take priority over the JSON. Thanks.

**Comment by frankroj** [comment]
Thanks so much again @nhogarth86 for the feedback. Your report allowed me to not only clarify this scenario, but also let me find some other information that needed to be clarified and/or fixed. For example, I accidentally included language saying you had to assign an Autopilot profile to the device, which you don't have to in the Autopilot for existing devices scenario. The changes cover several different pages and should go live some time tomorrow.  If you find any other problems after the pages update tomorrow, please let me know.
