### ISSUE TITLE
Clarification on process

### ISSUE THREAD

**Issue by jakesmith10** [MicrosoftDocs/memdocs#385]
Hi,

I spent hours trying to work out how to apply an app protection policy. The 2 things I did wrong were:
1) Not applying the policy to a group of users
2) Not waiting for the policy to apply to my iPhone before implementing the conditional access rule.

It would be great to have some more clarification around these points in your article. It would have saved me hours of head scratching!
Particularly for point 2 above, it would be worth noting that (a) it can take hours for app protection policies to apply to existing devices, (b) you'll see on the device when they are applied (a notification), and (c) conditional access rules should not be applied before app protection polices are applied, otherwise you'll get locked out of the app.

Thanks,
Jake
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cde34bc-bab0-d412-5971-cbc1f515a486
* Version Independent ID: ac355bba-5f6f-0168-49f3-67b7a2ddb2d4
* Content: [Create and deploy app protection policies - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policies)
* Content Source: [memdocs/intune/apps/app-protection-policies.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-protection-policies.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@jakesmith10 - Thanks for the feedback. I agree. I'm updating the docs now. Thanks again.
