### ISSUE TITLE
Correction for the autopilot diagnostics logs download button location. 

### ISSUE THREAD

**Issue by Wakyubi** [MicrosoftDocs/memdocs#3852]
[Enter feedback here]
The document state the location for the autopilot download log is 
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Sign in to the [Microsoft Intune admin center](https://go.microsoft.com/fwlink/?linkid=2109431)
Navigate to Devices > Monitor > Autopilot deployments (preview).
In the middle pane, select a device.
On the right-hand Properties pane, under Device Diagnostics, select Download.
The data zip file is added to your download tray, and you can save it to your computer.
>>>>>>>>>>>>>>>>>>>>>>>

However, that is wrong the location for the logs is 

Devices>windows devices > Name of the devices > Diagnostics logs > Download 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6b9a2b45-0c93-8161-8014-1765430c9b36
* Version Independent ID: ad42b14c-39db-d85c-6881-2c13a4fc551f
* Content: [Collect diagnostics from a Windows device - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/remote-actions/collect-diagnostics)
* Content Source: [memdocs/intune/remote-actions/collect-diagnostics.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/collect-diagnostics.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**
*

**Comment by msbemba** [comment]
@Wakyubi Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3866

Once the author approves, the changes will be live.

Thanks
Sri
