### ISSUE TITLE
Page needs update

### ISSUE THREAD

**Issue by p-graves** [MicrosoftDocs/memdocs#3853]
Doesn't account for current set up.

Under **Create and assign a Domain Join profile**

- A name is not yet entered in step 2
- Step 5 does not end after entering the OU
- Step 5 needs to have Assignments > Applicability Rules > Review + Create added

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3f93dd93-e003-36fc-02d6-07166537d914
* Version Independent ID: 1b860d13-bcf5-50da-89f9-ee12ece6edb2
* Content: [Enrollment for hybrid Azure AD-joined devices - Windows Autopilot](https://learn.microsoft.com/en-us/mem/autopilot/windows-autopilot-hybrid)
* Content Source: [memdocs/autopilot/windows-autopilot-hybrid.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/windows-autopilot-hybrid.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
Thank you for the feedback @p-graves. We actually just recently released new updated documentation with much more detailed steps and separate pages for each step. Check it out at this link:

https://learn.microsoft.com/en-us/mem/autopilot/tutorial/autopilot-scenarios

This includes steps for creating the domain join profile for hybrid Azure AD join scenarios:

https://learn.microsoft.com/en-us/mem/autopilot/tutorial/user-driven/hybrid-azure-ad-join-domain-join-profile
https://learn.microsoft.com/en-us/mem/autopilot/tutorial/pre-provisioning/hybrid-azure-ad-join-domain-join-profile

We most likely will retire this page in the new future and redirect it to the new content. If you find any problems with the new content, please let us know.
