### ISSUE TITLE
Azure Acitve Directory Screenshots

### ISSUE THREAD

**Issue by p-graves** [MicrosoftDocs/memdocs#3859]
On this page: https://learn.microsoft.com/en-us/mem/intune/enrollment/quickstart-setup-auto-enrollment

Under: **Set up automatic enrollment**

Instruction 1: In the [Microsoft Intune admin center](https://go.microsoft.com/fwlink/?linkid=2109431), choose All services > M365 Azure Active Directory > Azure Active Directory > Mobility (MDM and MAM).

This should be

In the [Microsoft Intune admin center](https://go.microsoft.com/fwlink/?linkid=2109431), choose All services > M365 Azure Active Directory > Azure Active Directory > **Settings** > Mobility (MDM and MAM).

It took me a while to figure out where Mobility was, following the instructions as written.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: adbfe90c-635e-5d23-f0b3-2d015565e311
* Version Independent ID: bcc85788-87a8-c3b5-1b60-a4938a09e541
* Content: [Set up automatic enrollment in Intune](https://learn.microsoft.com/en-us/mem/intune/enrollment/quickstart-setup-auto-enrollment)
* Content Source: [memdocs/intune/enrollment/quickstart-setup-auto-enrollment.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/quickstart-setup-auto-enrollment.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@p-graves Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3869

Once the author approves, the changes will be live.

Thanks
Sri
