### ISSUE TITLE
"Deploy Windows 10 in Configuration Manager" section assumes Windows 7 --> Windows 10

### ISSUE THREAD

**Issue by GenerAhl** [MicrosoftDocs/memdocs#386]
[Enter feedback here]

The section "Deploy Windows 10 in Configuration Manager" talks about using a Task Sequence for installing Windows 10. Surely this must be a remnant from Windows 7 --> Windows 10 days? Feature Upgrades are preferably deployed using the SUP and/or Windows Update these days.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6c3e494-65a1-6c1b-118d-963e1ac8ca06
* Version Independent ID: 776ca6de-38a8-3c95-4910-9e7cffec0661
* Content: [Tutorial - Deploy Windows 10 - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/desktop-analytics/tutorial-windows10)
* Content Source: [memdocs/configmgr/desktop-analytics/tutorial-windows10.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/desktop-analytics/tutorial-windows10.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @GenerAhl , thanks for the feedback. Lots of customers are still using task sequences for Windows 10 > Windows 10 updates, as they need to do additional activities at the same time, which they can't control the same with feature updates. Plus, Desktop Analytics only integrates with task sequences, there's no integration with Windows 10 servicing. That might make a good UserVoice idea!
