### ISSUE TITLE
undocumented option "Microsoft Defender for Endpoint client configuration package type"

### ISSUE THREAD

**Issue by kuzmeech** [MicrosoftDocs/memdocs#3862]
On this step "On the Configuration settings page, configure the following options for Endpoint Detection and Response:" there's also an option not mentioned in the document called "Microsoft Defender for Endpoint client configuration package type" with options "Auto from connector", onboard, offboard, not configured - which one is it recommended to choose? Auto or onboard? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 24fa182f-ace6-e7e2-ff98-91951be7d10e
* Version Independent ID: f1acb398-6d69-b91c-5ee0-3da3bbf7809f
* Content: [Configure Microsoft Defender for Endpoint in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/advanced-threat-protection-configure#enable-microsoft-defender-for-endpoint-in-intune)
* Content Source: [memdocs/intune/protect/advanced-threat-protection-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/advanced-threat-protection-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by yogkumgit** [comment]
@Brenduns Please help us in resolving this issue. Thanks

**Comment by Brenduns** [comment]
@kuzmeech  Hello, and thanks for this submission.  As I understand the Intune and Microsoft Defender connection/configuration, the option your asking about, the _Microsoft Defender for Endpoint client configuration package type_ setting, should only be visible when the Intune to Defender connection isn't set up correctly.  After that connection is established, you should not see that option as the onboarding blob will be automatically created for the policy.  I've also checked with our PM team to ensure this remains accurate and docs are not lagging any policy or behavior changes. 

Please check your connection to Microsoft Defender (per the top of the same article) and if all looks right, next reach out to support to have your tenant and connection, etc. investigated. You should not be offered that setting if everything is connecting as it should.  The onboarding package instead will automatically be configured for you with no option to configure it, per the note that follows the screen shot of the policy options.  

cc @yogkumgit
