### ISSUE TITLE
Template Download

### ISSUE THREAD

**Issue by justinmontgomeryCF** [MicrosoftDocs/memdocs#3864]
It would be helpful if this page stated _where_ you can download ADMX templates.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 798b808e-3d04-6965-c1a4-cbd4b685bb19
* Version Independent ID: 798b808e-3d04-6965-c1a4-cbd4b685bb19
* Content: [Import custom and third party partner ADMX templates in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/configuration/administrative-templates-import-custom)
* Content Source: [memdocs/intune/configuration/administrative-templates-import-custom.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/administrative-templates-import-custom.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by msbemba** [comment]
@justinmontgomeryCF Thank you for your feedback. The templates are third-party depending on what you would like to download, for example for Adobe- https://admx.help/?Category=AdobeReader

So, It is tough to keep track of URL changes since it is third-party.

Hope this helps!

Thanks
Sri
