### ISSUE TITLE
"If you're using Intune to deploy PowerShell scripts or Win32 apps, you'll also need to grant access to endpoints in which your tenant currently resides."

### ISSUE THREAD

**Issue by andykn** [MicrosoftDocs/memdocs#387]
Does this mean:
"If you're using Intune to deploy PowerShell scripts or Win32 apps, you'll also need to grant access to the Content Delivery Networks (CDN) used by your tenant's endpoints based on where your tenant currently resides. Mapping of Azure Scale Units (ASU) and Storage Names to CDNs:"
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c9c3475-56d4-026b-349f-f9cbc258537c
* Version Independent ID: 9c6476ed-8a47-bcb4-dfbf-25ba305c3b24
* Content: [Network endpoints for Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/intune-endpoints)
* Content Source: [memdocs/intune/fundamentals/intune-endpoints.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/intune-endpoints.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
7519036

**Comment by ErikjeMS** [comment]
@andykn The PM responded thus: "Yes they have to whitelist the CDN endpoints for the ASU's they are in. "
