### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by brucemcminn** [MicrosoftDocs/memdocs#3876]
There is a small typo in Learn/Microsoft Intune/Intune service/Microsoft Intune Data Warehouse data model.

"Dimension tables, _such as the like the User table_ are smaller and can retrain data for longer periods of time= than fact tables."

![image](https://github.com/MicrosoftDocs/memdocs/assets/93883569/c92c9da0-ff92-4037-958d-4e2624f8108f)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 78d3152b-c91c-5bf5-4e75-d4730db89a77
* Version Independent ID: 7e625b9f-2f03-fc8a-0781-7a90234c5306
* Content: [Data Warehouse data model - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/developer/reports-ref-data-model)
* Content Source: [memdocs/intune/developer/reports-ref-data-model.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/developer/reports-ref-data-model.md)
* Service: **microsoft-intune**
* Sub-service: **developer**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@brucemcminn Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3911

Once the author approves, the changes will be live.

Thanks
Sri
