### ISSUE TITLE
MIM/Intune IL5

### ISSUE THREAD

**Issue by jebalert** [MicrosoftDocs/memdocs#388]
Please note if Intune / MEM is approved for use in IL5/DoD

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44ac8695-df39-549c-569a-2e8ceaddc38c
* Version Independent ID: 6da292aa-7b48-f588-625e-e955a6b44869
* Content: [Apps for GCC High and DoD environments - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-deploy-gcc-dod)
* Content Source: [memdocs/intune/apps/apps-deploy-gcc-dod.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/apps-deploy-gcc-dod.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@jebalert - Please see the following docs related to your question:
[Microsoft Intune for US Government GCC High and DoD service description](https://docs.microsoft.com/enterprise-mobility-security/solutions/ems-intune-govt-service-description)
[What is Intune for Government?](https://docs.microsoft.com/mem/intune/fundamentals/introduction-intune-government)
