### ISSUE TITLE
No preview on LAPS

### ISSUE THREAD

**Issue by jerryabo** [MicrosoftDocs/memdocs#3880]
Picture and text for LAPS in Intune UX needs updating, or the UX needs the preview text on it. 

![image](https://github.com/MicrosoftDocs/memdocs/assets/94194023/8fa571d2-cfd9-4a09-bd7e-04e828b7932a)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0af68599-e111-42f0-758c-c126de6aa8b5
* Version Independent ID: 0af68599-e111-42f0-758c-c126de6aa8b5
* Content: [Create Intune policies to configure and manage Windows LAPS](https://learn.microsoft.com/en-us/mem/intune/protect/windows-laps-policy)
* Content Source: [memdocs/intune/protect/windows-laps-policy.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/windows-laps-policy.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@yogkumgit   We are investigating this internally at this time. No content edits are needed yet, and Jerry, is looped into that via email.

**Comment by Brenduns** [comment]
The disconnect between the live UI and the images in the article will be resolved in a few weeks time.  Currently, the feature remains in Preview despite the missing 'preview' tags in the UI, which can be considered a product bug.  For now, there are no content changes to be made.
