### ISSUE TITLE
Import ADMX Missing Step 

### ISSUE THREAD

**Issue by tombrowett** [MicrosoftDocs/memdocs#3884]
It looks like there's a mistake in 'Add the ADMX and ADML files' step 2 (or functional change).

The option to Import ADMX is only available if you navigate to 'Configuration profiles' by following 'Devices > **Windows** > Configuration profiles > Import ADMX'. If you don't first navigate by 'Windows' the Import ADMX option is not present.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 798b808e-3d04-6965-c1a4-cbd4b685bb19
* Version Independent ID: 798b808e-3d04-6965-c1a4-cbd4b685bb19
* Content: [Import custom and third party partner ADMX templates in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/configuration/administrative-templates-import-custom)
* Content Source: [memdocs/intune/configuration/administrative-templates-import-custom.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/administrative-templates-import-custom.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by msbemba** [comment]
@tombrowett Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3910

Once the author approves, the changes will be live.

Thanks
Sri
