### ISSUE TITLE
Mention AutoPilot removal

### ISSUE THREAD

**Issue by skywalkerisnull** [MicrosoftDocs/memdocs#3886]
This page does not have any details on when you wipe the device, it may retain the AutoPilot enrolment status, and if you are intending on wiping it completely (i.e. to give the machine to an employee as part of a recycling/upcycling program), you will need to do some extra steps.

Below is some where that it could be mentioned, and potentially with a link to the documents about how to unenroll the device from AutoPilot.

<html>
<body>

Wipe action | Retain enrollment state and user account | Removed from Intune management | Description
-- | -- | -- | --
Wipe | Not checked | Yes | Wipes all user accounts, data, MDM policies, and settings. Resets the operating system to its default state and settings. ***May retain AutoPilot enrolment see LINK for how to unenroll***
Wipe | Checked | No | Wipes all MDM Policies. Keeps user accounts and data. Resets user settings back to default. Resets the operating system to its default state and settings.

</body>
</html>

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7cdcc7fd-5bd9-1645-abf4-a73d3ea7adaa
* Version Independent ID: 5022b2ba-5fb0-18ce-9079-1b65ad0b2e17
* Content: [Retire or wipe devices using Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/remote-actions/devices-wipe)
* Content Source: [memdocs/intune/remote-actions/devices-wipe.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/devices-wipe.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by frankroj** [comment]
Thank you for the feedback @skywalkerisnull. I have added a note below the table calling this out with an appropriate link. This should go live in the next few days.
