### ISSUE TITLE
Limitations and pre-provisioning

### ISSUE THREAD

**Issue by nickh2308** [MicrosoftDocs/memdocs#3887]
I think Autopilot pre-provisioning should be added to the limitations (it already has self-driven Autopilot) but it should work the same, and if the default enrollment restriction is set to block, then pre-prov won't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4e8c2d91-8808-a504-da13-526b152a5cfe
* Version Independent ID: 037b60a6-d6b5-75ad-1933-39d0f7a69048
* Content: [Overview of enrollment restrictions - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/enrollment/enrollment-restrictions-set)
* Content Source: [memdocs/intune/enrollment/enrollment-restrictions-set.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/enrollment-restrictions-set.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by frankroj** [comment]
Thank you for the feedback @nhogarth86. Can you confirm that the section you are referring to is at the following link:

https://learn.microsoft.com/en-us/mem/intune/enrollment/windows-enrollment-status#create-new-profile

**Comment by nhogarth86** [comment]
Hi. It’s for https://learn.microsoft.com/en-us/mem/intune/enrollment/enrollment-restrictions-set#limitations

Regards,
Nick
________________________________

**Comment by frankroj** [comment]
Thanks @nhogarth86. Yes my previous reply was on the wrong item. I have since deleted it. Sorry for the confusion.

**Comment by frankroj** [comment]
Thanks for the feedback @nickh2308. Sorry for the long delay in getting to this. I have made the requested change. It should be live either later today or tomorrow.
