### ISSUE TITLE
Error in Only fail selected blocking apps in technician phase

### ISSUE THREAD

**Issue by drkmccy** [MicrosoftDocs/memdocs#3888]
Current:
  - **Yes**: An attempt will be made to install all required apps. Autopilot deployment will fail if a blocking app fails to install. If a non-blocking app that's targeted to the user fails to install, the ESP ignores it and deployment continues as normal. When the end user signs into the resealed device for the first time, the ESP will reattempt to install the apps that it couldn't in the technician phase. This is the default setting for pre-provisioned deployments.   

Suggested:
 - **Yes**: An attempt will be made to install all required apps. Autopilot deployment will fail if a blocking app fails to install. If a non-blocking app that's targeted to the **device** fails to install, the ESP ignores it and deployment continues as normal. When the end user signs into the resealed device for the first time, the ESP will reattempt to install the apps that it couldn't in the technician phase. This is the default setting for pre-provisioned deployments.

**Comment by frankroj** [comment]
Thank you for the feedback @nhogarth86. Can you confirm that the section you are referring to is at the following link:

https://learn.microsoft.com/en-us/mem/intune/enrollment/windows-enrollment-status#create-new-profile

**Comment by frankroj** [comment]
Thank you for the feedback @drkmccy. Can you confirm that the section you are referring to is at the following link:

https://learn.microsoft.com/en-us/mem/intune/enrollment/windows-enrollment-status#create-new-profile

**Comment by frankroj** [comment]
Thanks again for the feedback @drkmccy. We've confirmed the issue in the docs that you pointed out and have corrected it. It should be live in the next few days. Thanks again for letting us know.
