### ISSUE TITLE
Windows kiosk profiles not working with local admin users

### ISSUE THREAD

**Issue by bogom79** [MicrosoftDocs/memdocs#3894]
Hello everyone, hope you are doing good.

I have tested in my environment and when deploying a kiosk profile through Intune to a Windows device, although the policy is succeeded, the kiosk profile is not loading and I have the normal desktop interface. After some tests, I found my user was local admin in the machine and the kiosk profile is only shown with user that are not included in the local admin group.
Although this can be very obvious (I understand that kiosk profile is to limit the access and local admin has privileges in the device) and also the Windows article about how to implement the kiosk profile locally indicates that you have to use a standard account, for me it would be interesting if this clarification is included in the article, local admin users will not load the kiosk profile.

Thanks a lot!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 97b3556b-5cb1-2eeb-e793-5efff254ddd7
* Version Independent ID: 16117a39-76b5-a7ef-7aa5-86678fe38013
* Content: [Kiosk settings for Windows 10/11 in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/configuration/kiosk-settings-windows)
* Content Source: [memdocs/intune/configuration/kiosk-settings-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/kiosk-settings-windows.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by yogkumgit** [comment]
@MandiOhlinger Please help us in resolving this issue. Thanks
