### ISSUE TITLE
Firewall prerequisites

### ISSUE THREAD

**Issue by snitkjaer** [MicrosoftDocs/memdocs#3902]
What are the needed firewall openings for the Zebra FOTA client?

Maybe link to this?
https://supportcommunity.zebra.com/s/article/000022419?language=en_US

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til learn.microsoft.com ➟ GitHub-problemlinkning.*

* ID: 830e61b9-011a-4e7b-84d4-acb906cc6e9e
* Version Independent ID: 830e61b9-011a-4e7b-84d4-acb906cc6e9e
* Content: [Zebra LifeGuard Over-the-Air Integration with Microsoft Intune](https://learn.microsoft.com/da-dk/mem/intune/protect/zebra-lifeguard-ota-integration#step-2-enroll-devices-with-zebra-lg-ota-service)
* Content Source: [memdocs/intune/protect/zebra-lifeguard-ota-integration.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/zebra-lifeguard-ota-integration.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@snitkjaer Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3920

Once the author approves, the changes will be live.

Thanks
Sri
