### ISSUE TITLE
Intune's Reports Export Graph API Is Not Working For Some of "Export Parameters"

### ISSUE THREAD

**Issue by swahelamulla** [MicrosoftDocs/memdocs#3904]
POST https://graph.microsoft.com/beta/deviceManagement/reports/exportJobs
{
    "reportName": "FeatureUpdateDeviceState",
    "localizationType": "LocalizedValuesAsAdditionalColumn",
    "format": "csv",
    "select": [
        "UPN",
        "DeviceId",
        "AADDeviceId",
        "EventDateTimeUTC",
        "AlertType"
    ]
}

When I am running this post request, it is showing error message.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a6c8cbcb-dd8c-62d8-88e5-ec1e8badc511
* Version Independent ID: b4b5007c-684c-d929-90cc-bb1e263bb21c
* Content: [Intune Graph API - Reports and properties](https://learn.microsoft.com/en-us/mem/intune/fundamentals/reports-export-graph-available-reports)
* Content Source: [memdocs/intune/fundamentals/reports-export-graph-available-reports.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/reports-export-graph-available-reports.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@swahelamulla Thank you for your feedback. This looks like a technical issue or a bug, we recommend you raise a support request via the need help section on the admin center, so that our support engineer can fix it or file a bug.

Hope this helps!

Thanks
Sri
