### ISSUE TITLE
Minor typo in subsection for Universal Links support

### ISSUE THREAD

**Issue by secondsleep-blaine** [MicrosoftDocs/memdocs#3905]
In the second paragraph of the [Universal Links support](https://learn.microsoft.com/en-us/mem/intune/apps/app-protection-policy#universal-links-support) subsection, there is a minor typo. "In order to *user* Universal Links" should be "In order to *use* Universal Links" (emphasis added).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 17955fd7-d652-8f0e-4446-00b8628d58cc
* Version Independent ID: 46755b3c-43a5-f5c9-0b74-ce2b7ede7d40
* Content: [App protection policies overview - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/apps/app-protection-policy)
* Content Source: [memdocs/intune/apps/app-protection-policy.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/app-protection-policy.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@secondsleep-blaine Thank you for your feedback. We have fixed the typo via PR#https://github.com/MicrosoftDocs/memdocs/pull/3919

Once the author approves, the changes will be live.

Thanks
Sri
