### ISSUE TITLE
The 

### ISSUE THREAD

**Issue by henrywang08** [MicrosoftDocs/memdocs#3908]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c9c8322-fc0c-8e97-170d-e881e77889b9
* Version Independent ID: c924f234-8c65-b47d-1838-70c406cbdda9
* Content: [Network requirements and bandwidth details for Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/fundamentals/network-bandwidth-use)
* Content Source: [memdocs/intune/fundamentals/network-bandwidth-use.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/network-bandwidth-use.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@henrywang08 Thank you for your feedback. Looks like you wanted to add feedback to the document, however, it got cut short. PLease let us know what changes would you like to see in the document.

Thanks
Sri

**Comment by tiburd** [comment]
Closing this incomplete issue.
