### ISSUE TITLE
Hover text or documentation is incorrect

### ISSUE THREAD

**Issue by p0shkar** [MicrosoftDocs/memdocs#391]
> **A sync is run automatically every 12 hours.** You can also sync by clicking the Sync button (no more than once every 15 minutes). All sync requests are given 15 minutes to finish. The Sync button is disabled until a sync is completed. This sync will refresh existing device status and import new devices assigned to the Apple MDM server.

Either this text is incorrect or the hover text of the "Last requested sync" button need to be updated, the hover text currently states "Intune automatically syncs once per day".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd130267-c54b-41e3-d534-831d4a86bae6
* Version Independent ID: bdfa7eca-a356-3dde-7643-9a759f952007
* Content: [Enroll iOS/iPadOS devices - Device Enrollment Program - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-ios)
* Content Source: [memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@p0shkar The article is correct. The 2005 Intune Service Release reduced the sync interval from 24 hrs to 12 hours. I will tell the PM to update the product UI. Hopefully, that fix will make it into the next release. Thanks!
