### ISSUE TITLE
What is the permission we need for to create the device profile in Microsoft Intune ? 

### ISSUE THREAD

**Issue by balagcpcloud** [MicrosoftDocs/memdocs#3914]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2d8832b0-265d-5c37-9f9d-4adbaa8202de
* Version Independent ID: 48c4745d-166e-01a6-0f29-8bfc2a86d07a
* Content: [Create device profiles in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/configuration/device-profile-create)
* Content Source: [memdocs/intune/configuration/device-profile-create.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/device-profile-create.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by msbemba** [comment]
@balagcpcloud Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3921

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@balagcpcloud closing as author did not approve the changes. Thanks
