### ISSUE TITLE
Retire an Apple ADE device from Intune steps are outdated

### ISSUE THREAD

**Issue by ibawwad** [MicrosoftDocs/memdocs#3915]
With the latest update in ABM, steps starting with number 4 are wrong, those options aren't there anymore, instead, it should be
**4.** Select the device > Release from Organization
![image](https://github.com/MicrosoftDocs/memdocs/assets/62571306/bdef6f30-8012-46b0-8f06-ab9f0e27987b)

**5.** Confirm "I understand this cannot be undone" > Release
![image](https://github.com/MicrosoftDocs/memdocs/assets/62571306/11a3ea8a-1fbf-4ddd-8967-f354b1c39a84)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7cdcc7fd-5bd9-1645-abf4-a73d3ea7adaa
* Version Independent ID: 5022b2ba-5fb0-18ce-9079-1b65ad0b2e17
* Content: [Retire or wipe devices using Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/remote-actions/devices-wipe)
* Content Source: [memdocs/intune/remote-actions/devices-wipe.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/devices-wipe.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@ibawwad Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3918

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by ibawwad** [comment]
Hello,
The information is still wrong for the ABM device removal, the information
in the document is outdated.

*Best regards,*
Ibrahim Awwad
