### ISSUE TITLE
Add reference on increasing ocserv log verbosity

### ISSUE THREAD

**Issue by jerryabo** [MicrosoftDocs/memdocs#3916]
DEBUG_LEVEL reference may help customers self-help/resolve issues, or even know why they see no ocserv logs (ref incident 393605579)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cc4c7496-19c8-062e-d13f-3e5c7f6d7743
* Version Independent ID: 845402fc-e282-9e75-c70d-541d4bab9e36
* Content: [Monitor the status of the Microsoft Tunnel VPN solution for Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/microsoft-tunnel-monitor)
* Content Source: [memdocs/intune/protect/microsoft-tunnel-monitor.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/microsoft-tunnel-monitor.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by yogkumgit** [comment]
@Brenduns Please help us in resolving this issue. Thanks

**Comment by Brenduns** [comment]
@jerryabo   Thanks for the suggestion. I've passed this information on to our product team to see if we can generate a bit of information to add to content. With this passed on for internal review, I'll be closing this GitHub issue at this time.
