### ISSUE TITLE
Can a necessary second device for MFA being replaced by TAP?

### ISSUE THREAD

**Issue by pmeuser** [MicrosoftDocs/memdocs#3931]
"The second device is required because the primary device can't receive calls or text messages during the provisioning process."

Is my understanding correct, that also a Temporary Access Pass (TAP) should work for enrollment to satisfy MFA requirement? If this assumption is correct, it would be quite helpful to add this option in the article, too.

Thanks a lot for clarification!

Peter

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8f28c4b3-8ccc-e353-2ead-65c4022b437a
* Version Independent ID: 643425fd-9969-6322-0735-2bffb125cefc
* Content: [Require multifactor authentication for Intune device enrollment - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/enrollment/multi-factor-authentication)
* Content Source: [memdocs/intune/enrollment/multi-factor-authentication.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/multi-factor-authentication.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@pmeuser Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3961

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by msbemba** [comment]
@pmeuser Thank you for your feedback.  I checked with the author and she can't confirm if this is something that device users can use as an alternative option to this policy, so no change to the docs. If this is something that the product team identifies as an alternative in the future, we will be sure to add and expand upon it.

Hope this helps!

Thanks
Sri
