### ISSUE TITLE
About Azure Active Directory User

### ISSUE THREAD

**Issue by buhibu9** [MicrosoftDocs/memdocs#3933]
Please consider the following two improvements

1. description on en-us
https://learn.microsoft.com/en-us/mem/intune/protect/certificate-connector-prerequisites#azure-active-directory-user

[and must be a synchronized account from your local Active Directory.]

This may be misunderstood as a requirement for synchronization. 

2. description on en-jp
https://learn.microsoft.com/ja-jp/mem/intune/protect/certificate-connector-prerequisites#azure-active-directory-user

[コネクタを構成する場合は、グローバル管理者または Intune 管理者のいずれか、**_また_** Intune ライセンスが割り当てられているユーザー アカウントを使用する必要があり].

The above [also] is misleading. The correct term is [and].
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eb75d7d2-8872-8f8c-2ac1-211f2b35b9d8
* Version Independent ID: b1c06e06-bd5e-2b83-7e5f-92b4d0386bf5
* Content: [Prerequisites for use of the Certificate Connector for Microsoft Intune - Azure](https://learn.microsoft.com/en-us/mem/intune/protect/certificate-connector-prerequisites#azure-active-directory-user)
* Content Source: [memdocs/intune/protect/certificate-connector-prerequisites.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/certificate-connector-prerequisites.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by yogkumgit** [comment]
@tiburd Please help. Thanks

**Comment by tiburd** [comment]
Thank you for submitting this localization issue.

I submitted a translation bug: [#327814](https://dev.azure.com/GlobalCollaborationService/Global%20Collaboration%20Service%20Project/_workitems/edit/327814)

I'm closing this issue because the Global Services team will handle it from here.

cc: @yogkumgit
