### ISSUE TITLE
RBAC instruction for 'Add an app' missing

### ISSUE THREAD

**Issue by johanVAva3** [MicrosoftDocs/memdocs#3934]
[Enter feedback here]
In this page, there is no description of what rights are needed to have the 'Add+' button enabled.

We are compliant with all pre-requisies listed on the page.

We are using Intune RBAC to divide Intune access rights between different roles.
With rights for Apps management assigned to RBAC roles, the button in 'Apps > Windows Apps > Add +' still stays **greyed out**.
The only way is to use my Global Administrator account, but this is not possible for my peer colleagues.

So please add info on what RBAC or other rights are needed to have the Add+ button enabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e2bdd473-2cca-8b38-71d0-5ac1e823fdeb
* Version Independent ID: e2bdd473-2cca-8b38-71d0-5ac1e823fdeb
* Content: [Add Microsoft Store apps to Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/apps/store-apps-microsoft)
* Content Source: [memdocs/intune/apps/store-apps-microsoft.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/store-apps-microsoft.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@johanVAva3 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3962

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by johanVAva3** [comment]
Hi, just a heads-up: the info concerning RBAC has not appeared in the article yet ...

________________________________
