### ISSUE TITLE
Script referred to is outdated

### ISSUE THREAD

**Issue by RvM71** [MicrosoftDocs/memdocs#3936]
Hi,

In this article you are referring to the Get-WindowsAutopilotInfo.ps1 script. This script iuses the old AzureAD PowerShell module which is due for deprecation.

In the script there is a parameter called -AddToGroup. This option is not working any more sinds two weeks!

I believe it needs to be updated with the Microstf Graph API.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ea4a659b-65d0-26ec-c36a-9a21a72a09a8
* Version Independent ID: bff44b73-9021-6659-e212-66349c759989
* Content: [Manually register devices with Windows Autopilot](https://learn.microsoft.com/en-us/mem/autopilot/add-devices)
* Content Source: [memdocs/autopilot/add-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/add-devices.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
Thank you for the feedback @RvM71. We are aware of the AzureAD modules that are being deprecated and are working on replacements. We will post as soon as we have them.
