### ISSUE TITLE
Disable private or public store? 

### ISSUE THREAD

**Issue by mMDG0Oowa-3TPkpg7JOmdx4ff4IfPvyCGSAHbnh** [MicrosoftDocs/memdocs#394]
It is mentioned that: 
`If you disable the Store on managed devices (either manually, via policy or Group Policy), Online licensed apps will fail to install.` 
What is meant with 'disable the Store' in above sentence? Disabling the public store? Disabling the private store? 

In our configuration, we have disabled the PUBLIC Store, but online licensed applications (O365, Company portal) mostly seem to install fine. Only some installations fail. We are now testing whether adding these applications to the private store will make any difference. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dac06439-a7c6-b637-3268-e1ed8f59ad15
* Version Independent ID: c43caaad-0392-394c-62ca-1216dd488652
* Content: [Manage VPP apps from Microsoft Store for Business - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/windows-store-for-business)
* Content Source: [memdocs/intune/apps/windows-store-for-business.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/windows-store-for-business.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@mMDG0Oowa-3TPkpg7JOmdx4ff4IfPvyCGSAHbnh - I believe this means access to the store. I'm updating the docs now. 

If you have additional questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

This question is in our documentation feedback channel and it may be best to handle this question as a support request. For this reason, I'm closing this issue. Please use the above channels if you don't already have a solution.
