### ISSUE TITLE
BYOD Android 12+ Password Complexity

### ISSUE THREAD

**Issue by InutneAdmin1** [MicrosoftDocs/memdocs#3945]
If the assignment scope (specifically excluding a group of devices) of an existing policy with the "Password type" setting set is adjusted, will the BYOD Android 12 + devices still scoped by this policy automatically use the High Password Complexity? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dc9c611f-edcb-81fd-b76e-207dd5b3fe04
* Version Independent ID: e5998630-06e9-2051-5d40-1e1509e7fddb
* Content: [Android Enterprise compliance settings in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/compliance-policy-create-android-for-work#android-12-and-later---for-personally-owned-work-profile)
* Content Source: [memdocs/intune/protect/compliance-policy-create-android-for-work.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/compliance-policy-create-android-for-work.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@InutneAdmin1 Thank you for your feedback. That is correct it will be scoped by the policy to use the High Password Complexity.

Hope this helps!

Thanks
Sri
