### ISSUE TITLE
Semi-Annual Channel clarification

### ISSUE THREAD

**Issue by StuBeck32** [MicrosoftDocs/memdocs#395]
Documentation sent me to this page to review the settings for Windows Update setting. Other than using a Windows insider, it seems like the Semi-Annual only gives updates after six months. Is there a faster option? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401fe085-6254-6dbb-24c6-7e6fe56d0f3a
* Version Independent ID: 774ae4fb-b28e-1fb3-46d9-5802c0e4ac6c
* Content: [Windows for Business Update settings for  Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/windows-update-settings)
* Content Source: [memdocs/intune/protect/windows-update-settings.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/windows-update-settings.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@stubeck32  Intune is tapping into the available options from Windows Update, and only supports those options listed. That does mean you’ll have to use an Insider option if you’d like to speed updates along.  Intune doesn’t define these options but provides a configuration channel by which you can manage these options on your devices.  For more information about the update channels these settings represent, see the Windows Update servicing channel CSP can provide more details on that.  See Update/BranchReadinessLevel at https://docs.microsoft.com/windows/client-management/mdm/policy-csp-update#update-branchreadinesslevel.  You can also learn more about the Windows Servicing channels in the Windows Update documentation at https://docs.microsoft.com/en-us/windows/deployment/update/get-started-updates-channels-tools#servicing-channels

**Comment by StuBeck32** [comment]
I don't think you fully understand my question, but the second link did clarify. My question was regarding any windows updates, not just feature updates. The update options are confusing named. Semi-annual sounds like I'm waiting six months to get security updates, when its not...its the twice yearly windows 10 updates. I think the core problem is the switch from "security updates" to "quality updates" without clear indications of what that means on different pages. Microsoft has called security updates that for decades, and the change to quality update as a term hasn't been clarified consistently. https://support.microsoft.com/en-us/help/4524244/security-update-for-windows-10-february-11-2020 for example is still called a security update just a few months ago. 

I say this in pretty much every article I comment on, but condensing these different pages into one would help out with the confusion as well.
