### ISSUE TITLE
Device platform restriction policy isn't in the place identified in this page

### ISSUE THREAD

**Issue by ibawwad** [MicrosoftDocs/memdocs#3950]
[Enter feedback here]
The new Intune Admin Center is having a new layout, device restrictions is not Devices > Enroll devices > Enrollment device platform restrictions

![image](https://github.com/MicrosoftDocs/memdocs/assets/62571306/06b35af0-4a02-4218-bc48-e96def66d82e)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0c0a8f68-794f-9cdb-050a-b7e94bc61399
* Version Independent ID: 0c0a8f68-794f-9cdb-050a-b7e94bc61399
* Content: [Create device platform restrictions - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/enrollment/create-device-platform-restrictions)
* Content Source: [memdocs/intune/enrollment/create-device-platform-restrictions.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/create-device-platform-restrictions.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@ibawwad Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3963

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@ibawwad closing as PR is not approved. Thanks
