### ISSUE TITLE
Get-WindowsAutopilotInfo -Online no longer works due to deprecation of the Azure AD module

### ISSUE THREAD

**Issue by unearthnz** [MicrosoftDocs/memdocs#3953]
Hi there,

The -online switch used by [Get-WindowsAutopilotInfo.ps1](https://www.powershellgallery.com/packages/Get-WindowsAutoPilotInfo/3.5/Content/Get-WindowsAutoPilotInfo.ps1) as linked on this page relies upon the Azure AD module to authenticate and upload the hash to Intune - however [this module has now been deprecated](https://techcommunity.microsoft.com/t5/microsoft-entra-azure-ad-blog/update-your-applications-to-use-microsoft-authentication-library/ba-p/1257363) and has broken the script.

Can the script please be updated to use MS Graph as this is causing a real pain enrolling new machines to Autopilot.

Thanks,
Greg

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ea4a659b-65d0-26ec-c36a-9a21a72a09a8
* Version Independent ID: bff44b73-9021-6659-e212-66349c759989
* Content: [Manually register devices with Windows Autopilot](https://learn.microsoft.com/en-us/mem/autopilot/add-devices)
* Content Source: [memdocs/autopilot/add-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/add-devices.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
Thank you for the feedback @unearthnz. We are aware of these modules being deprecated and are working on replacements. We will post updates as soon as we have them.
