### ISSUE TITLE
Compliance conflicts with CSP settings

### ISSUE THREAD

**Issue by SkipToTheEndpoint** [MicrosoftDocs/memdocs#3954]
I utilise the [MaxInactivityTimeDeviceLock](https://learn.microsoft.com/en-gb/windows/client-management/mdm/policy-csp-devicelock#maxinactivitytimedevicelock) policy in my baseline and have done for some time. Something must have changed around 2 months ago as this particular policy started to flag as a conflict on every device.

After investigation, it was conflicting with the Compliance Policy setting for "Maximum minutes of inactivity before password is required", however this is not reflected in the docs page for Windows Compliance Settings, nor in the matrix of actions for non-compliance page here: https://learn.microsoft.com/en-us/mem/intune/protect/device-compliance-get-started#reference-for-non-compliance-and-conditional-access-on-the-different-platforms.

They both seem to manage the same registry key and if they do not match, the compliance policy takes precedence and remediates it:

![image](https://github.com/MicrosoftDocs/memdocs/assets/104939301/eae2c0f0-9ccf-4b70-8186-838834be9f61)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 979d9182-7aa8-9a97-399b-2a495164f1a7
* Version Independent ID: b293cc1c-53ce-d06f-c991-a0f1a27214fc
* Content: [Windows compliance settings in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/compliance-policy-create-windows?WT.mc_id=DX-MVP-5005288)
* Content Source: [memdocs/intune/protect/compliance-policy-create-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/compliance-policy-create-windows.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by yogkumgit** [comment]
@Brenduns Please help us in resolving this issue. Thanks

**Comment by Brenduns** [comment]
@SkipToTheEndpoint   Thanks for this insight to the conflict your seeing. However, this is not unxpected, though one you might not have been aware of. 

This section of Intune content describes the order of precedence for Intune policies: https://learn.microsoft.com/mem/intune/configuration/device-profile-troubleshoot#compliance-and-device-configuration-policies-that-conflict, and notes that compliance settings will take precedence over all other sources of configuration.  
Intune has several paths to manage device configuration settings, ranging across Security Baseline templates, endpoint security policies, to direct the original device configuration policies. And, as you've seen, Device compliance will reconfigure (remediate) this particular setting to align to  a configured compliance requirement.  
 
I'll note that i've not been able to discover any changes for how Intune manages those settings via different policies that apply to that CSP, but in the end, the Windows team owns the operation of that CSP and its possibly they introduced a change, though unlikely.
