### ISSUE TITLE
Updated Wandera logo on Diagrams

### ISSUE THREAD

**Issue by mattvlas** [MicrosoftDocs/memdocs#396]
Hello,
We have updated our logo since these diagrams were made, I believe by the Microsoft documentation team.

Can you please update the logo with the attached?

<img width="1265" alt="logo_Full-Colour@2x" src="https://user-images.githubusercontent.com/57152570/85072155-758dcb80-b16d-11ea-9fd3-65ce65ce84d6.png">

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27f9e3d9-f662-d149-e1de-13b3666a4904
* Version Independent ID: 618dd0a6-fe19-a4bc-3efa-d6a483a3cb34
* Content: [Set up Wandera Mobile Security with Intune - Intune on Azure](https://docs.microsoft.com/en-us/mem/intune/protect/wandera-mtd-connector)
* Content Source: [memdocs/intune/protect/wandera-mtd-connector.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/wandera-mtd-connector.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@mattvlas   Thanks for this feedback. I've submitted an update for the content images that uses the current Wandera logo. That should update in the published content on Friday.
