### ISSUE TITLE
(default) meaning

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/memdocs#397]
Hello,

By **(default)** do you mean that it is currently enabled in Edge?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96f97bff-7548-846a-026d-8eda5e94da45
* Version Independent ID: 377b6f76-fec1-a55e-157a-d2db7060b56b
* Content: [Intune security baselines settings for Microsoft Edge - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/security-baseline-settings-edge?pivots=edge-april-2020)
* Content Source: [memdocs/intune/protect/security-baseline-settings-edge.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/security-baseline-settings-edge.md)
* Service: **microsoft-intune**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by lightupdifire** [comment]
Hello,
It would be really nice to understand what is currently enabled or disabled in Edge by default.
If using "edge://flags", there are many settings, but not all from Security baseline, and most settings in "edge://flags" have option set as "Default", also not clear, it is Enabled or Disabled...

**Comment by Brenduns** [comment]
@lightupdifire   For default configurations of each setting found in Edge, you’ll need to work with the Edge product directly. I did some light searching for default settings, but wasn’t able to locate that. It might take a support ticket, or submitting feedback asking for that to the Edge team.

By default, Intune security baselines define the recommended security posture for a product. For Edge, that is determined by the team that develops and releases the Edge browser. Its beyond the Intune documentation scope to describe the Edge browser defaults, as defaults are subject to changes with subsequent releases or version updates to the browser. We do release a new security baseline version for products when the engineering teams involved identify the need to revise or update the security baseline configurations.

**Comment by lightupdifire** [comment]
@Brenduns 

Please give more light on this document, as an example, we take the first configuration:

A) Supported authentication schemes

- Enabled (default) - Schemes you select are used.
- Disabled
- Not configured - All four schemes are used.

What does this exactly mean here, in this document, the option **default**:

1. Is it default in the Edge browser?
2. Is it default in the Edge security baseline?
