### ISSUE TITLE
Enabled by default

### ISSUE THREAD

**Issue by toxarisswe** [MicrosoftDocs/memdocs#3976]
Hello.
Is the tenant wide WHfB setting enabled by default?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d6d32682-0e4e-449b-6ad5-001c631735d2
* Version Independent ID: 66419be7-51dc-f5e1-cf18-1a55866e4193
* Content: [Configure a tenant-wide Windows Hello for Business policy with Microsoft Intune - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/windows-hello)
* Content Source: [memdocs/intune/protect/windows-hello.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/windows-hello.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@toxarisswe Thank you for your feedback. Tenant wide WHfB setting is not enabled by default - https://learn.microsoft.com/en-us/mem/intune/protect/identity-protection-windows-settings#windows-hello-for-business

Hope this helps!

Thanks
Sri

**Comment by toxarisswe** [comment]
Yea, absolutely clear. Thx
