### ISSUE TITLE
Reports Reader Role doen't have read acces to all Intune data

### ISSUE THREAD

**Issue by tobi-coder** [MicrosoftDocs/memdocs#3979]
[Enter feedback here]
It is documented, that the AAD Reports Reader role has read access to all Intune data. My tests hows that this isn't true. Opening "All devices" in Intune gives an "Unauthorized" error.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c3eaa886-918b-127e-ad4b-d829e99b0d44
* Version Independent ID: 87240468-dd25-7f45-740b-f078cd5deac7
* Content: [Role-based access control (RBAC) with Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/fundamentals/role-based-access-control)
* Content Source: [memdocs/intune/fundamentals/role-based-access-control.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/role-based-access-control.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@tobi-coder Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3986

Once the author approves, the changes will be live.

Thanks
Sri
