### ISSUE TITLE
9e6c4e1f-7d60-472f-ba1a-a39ef669e4b2 Referenced as the GUID for 2 ASR Rules

### ISSUE THREAD

**Issue by joftrobert** [MicrosoftDocs/memdocs#3980]
9e6c4e1f-7d60-472f-ba1a-a39ef669e4b2 is referenced as the ASR Rule GUID for both **Block persistence through WMI event subscription** and **Block credential stealing from the Windows local security authority subsystem (lsass.exe)**.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f71f2647-ec06-5301-015f-9b29df00f9da
* Version Independent ID: 00b110b0-25a3-a7de-0955-db33d7f0f036
* Content: [Intune endpoint security Attack surface reduction settings](https://learn.microsoft.com/en-us/mem/intune/protect/endpoint-security-asr-profile-settings)
* Content Source: [memdocs/intune/protect/endpoint-security-asr-profile-settings.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/endpoint-security-asr-profile-settings.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@joftrobert Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3987
Once the author approves, the changes will be live.

Thanks
Sri
