### ISSUE TITLE
End User Update Status has been removed. Update documentation.

### ISSUE THREAD

**Issue by SrDirko** [MicrosoftDocs/memdocs#3981]
"Select End user update status to view information about the policy."

This is no longer an option after selecting a Feature update for Windows 10 and later.

![image](https://github.com/MicrosoftDocs/memdocs/assets/51033218/651279f6-7fa4-4778-8227-6995f95d557c)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ee0dbbde-b15e-4adf-b162-1114fddd8846
* Version Independent ID: 78275b5f-4d5b-f318-0cbf-a27ad35dffa0
* Content: [Configure feature updates policy for Windows 10 Windows 11 devices in Intune](https://learn.microsoft.com/en-us/mem/intune/protect/windows-10-feature-updates)
* Content Source: [memdocs/intune/protect/windows-10-feature-updates.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/windows-10-feature-updates.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@SrDirko Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/3995

Once the author approves, the changes will be live.

Thanks
Sri
