### ISSUE TITLE
Independent ID

### ISSUE THREAD

**Issue by Zayanusman221** [MicrosoftDocs/memdocs#3984]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5b36b2a6-b990-7f5a-51b5-13e9ce69f3d4
* Version Independent ID: 3624d242-db7c-f9d7-b4b1-7f9cfca69bc5
* Content: [How do I find the serial number on my iOS device?](https://learn.microsoft.com/en-us/mem/intune/user-help/how-do-i-find-the-serial-number-on-my-device-ios)
* Content Source: [memdocs/intune/user-help/how-do-i-find-the-serial-number-on-my-device-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/how-do-i-find-the-serial-number-on-my-device-ios.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@Zayanusman221 Thank you for your feedback. I'm not sure if you are referring to a unique independent Serial number

But yes, the document does provide steps to get the serial number

Go to the Home screen.
Tap the Settings app, then General.
Tap About, then scroll to Serial Number.

Hope this helps!

Thanks
Sri
