### ISSUE TITLE
Where do these logs go, and how do Admins get to them?

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/memdocs#399]
I am unable to find in docs.microsoft.com anywhere, what happens with these logs and how do admins access them after they been "uploaded to Microsoft".  The email that goes to the support email address which is setup for the Company Portal, it has nothing attached.

**Comment by ErikjeMS** [comment]
@JeremyTBradshaw Can you provide a link to the article that this refers to?

**Comment by JeremyTBradshaw** [comment]
Hi @ErikjeMS , somehow I opened this issue as an orphan I guess.  The page was https://docs.microsoft.com/en-us/mem/intune/user-help/send-logs-to-your-it-admin-by-email-android

I'm seeing now that the answer is on the exact same page:

> The actual error details are kept on your device in a special document called a diagnostic log. When you upload the logs to the Company Portal or Microsoft Intune app, they're first sent to the Microsoft developers that work on the app. They use the logs to improve the app's functionality and prevent future errors. An incident ID for your specific error is then provided to you to share with your company support person, for use in Microsoft Support cases.

So, with that, I will just close this one up:).  Thanks nonetheless.
