### ISSUE TITLE
Wrong information in the article.

### ISSUE THREAD

**Issue by jamesp286** [MicrosoftDocs/memdocs#3993]
[Under "Remove all AppLocker policies from a device (optional)" the text in point 2. says "Run this script on devices that have set the Intune Management Extension as a managed installer. This script removes only the Intune Management Extension as a managed installer." this information is incorrect since the script will effectively reset the Applocker Policy completely and remove all configured managed installers in the policy.]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d1c3d1e6-4314-d333-7e17-cca50f5d2fee
* Version Independent ID: d1c3d1e6-4314-d333-7e17-cca50f5d2fee
* Content: [Manage approved apps for Windows devices with Application Control policy and Managed Installers in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/endpoint-security-app-control-policy)
* Content Source: [memdocs/intune/protect/endpoint-security-app-control-policy.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/endpoint-security-app-control-policy.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@jamesp286 Thank you for your feedback. We have updated the document to reflect that This script removes **not only the Intune Management Extension as a managed installer,** but all managed installers as well as all policies based on Windows AppLocker from a device.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Please review and confirm. Thanks

**Comment by msbemba** [comment]
@yogkumgit  This has been reviewed. The document is up to date.

Thanks
Sri
