### ISSUE TITLE
business store decommissioning, update?

### ISSUE THREAD

**Issue by Bvanderstraeten** [MicrosoftDocs/memdocs#3994]
Any workaround as business store is planned to be closed ( i can't see the package)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 43ae0d4a-eefd-7770-b2a4-d4f72f7272a3
* Version Independent ID: 1001276c-ddd3-14bd-cd5e-74ce47490d19
* Content: [Manually add the Windows 10 Company Portal app - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/apps/store-apps-company-portal-app)
* Content Source: [memdocs/intune/apps/store-apps-company-portal-app.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/store-apps-company-portal-app.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@Bvanderstraeten Thank you for your feedback. The retirement of Microsoft Store for Business and Microsoft Store for Education has been postponed. We will update this notice when a new retirement date is announced. You can continue to use the current capabilities of free apps until that time.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@Bvanderstraeten Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/4033

Once the author approves, the changes will be live.

Thanks
Sri
