### ISSUE TITLE
Wrong link 

### ISSUE THREAD

**Issue by KONIKPK** [MicrosoftDocs/memdocs#4004]
You have wronmg link in this 

Sign in to the [Microsoft Intune admin center](https://go.microsoft.com/fwlink/?linkid=210943) and go to Tenant administration > Connectors and tokens > Windows data.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7928e48c-63f2-e459-db87-bb62eb5501b0
* Version Independent ID: 7928e48c-63f2-e459-db87-bb62eb5501b0
* Content: [Learn about Windows Driver updates policy for Windows 10 Windows 11 devices in Intune](https://learn.microsoft.com/en-us/mem/intune/protect/windows-driver-updates-overview)
* Content Source: [memdocs/intune/protect/windows-driver-updates-overview.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/windows-driver-updates-overview.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
#sign-off

**Comment by yogkumgit** [comment]
@Brenduns kindly link the PR you are talking about with this issues. Thanks.

**Comment by Brenduns** [comment]
@Yogkumgit PR https://github.com/MicrosoftDocs/memdocs-pr/pull/11274

**Comment by yogkumgit** [comment]
@Brenduns The PR link is 404. Kindly check.

**Comment by yogkumgit** [comment]
@KONIKPK it is fixed. Thanks

**Comment by KONIKPK** [comment]
its ok thnx
