### ISSUE TITLE
ETA missing

### ISSUE THREAD

**Issue by AlexSchwerzmann** [MicrosoftDocs/memdocs#4009]
Dear Microsoft

What is the ETA for that feature: Some applications and shortcuts fail to elevate when command-line parameters are present

--> we are heavely depending on that feature as we can't move on in a project. Do you have an ETA or a roadmap item?

Thanks
Alex

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e278a1ae-0701-bf86-4396-c0a0348e7a95
* Version Independent ID: e278a1ae-0701-bf86-4396-c0a0348e7a95
* Content: [Deployment considerations for Endpoint Privilege Management](https://learn.microsoft.com/en-us/mem/intune/protect/epm-deployment-considerations-ki?WT.mc_id=EM-MVP-5001447#some-applications-and-shortcuts-fail-to-elevate-when-command-line-parameters-are-present)
* Content Source: [memdocs/intune/protect/epm-deployment-considerations-ki.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/epm-deployment-considerations-ki.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@AlexSchwerzmann   Endpoint Privilege Management has been generally available since mid April 2023.  However, its functionality is not part of Intune by default and requires additional licensing to enable it as an  Intune Add-On.   For mor information about Intune Suite add-on capabilities, see https://learn.microsoft.com/mem/intune/fundamentals/intune-add-ons.

If you have purchased the Intune Suite or this feature as a stand-alone add-on and it’s not functional, then please work with Support so they can understand why its not working in your environment.

**Comment by AlexSchwerzmann** [comment]
Thanks, @Brenduns , but I was asking for the ETA of correct command line interpretation. You are writing 

> Some applications and shortcuts fail to elevate when command-line parameters are present
> Certain command line compositions can cause elevations to fail on the client. This issue will be fixed in future release.

When does this future release come? Is there a roadmap item for it?

**Comment by Brenduns** [comment]
@AlexSchwerzmann   Sorry to confuse that, I didn't realize that the PM had added that issue to the known issue list. I’ve reached out to the PM and product team to share this Issue submission, and to see if they can provide guidance as to when this might be resolved.  I'll update you through this GitHub issue once I have information to share.

**Comment by Brenduns** [comment]
@AlexSchwerzmann   If you find that it this behavior isn't resolved, and the issue of *some applications and shortcuts fail to elevate when command-line parameters are present* remains persistent in your environment, please contact support to have that investigated as to the cause.  If relevant, you can also reference this GitHub issue as indication that the product group no longer expects this problem to occur.

**Comment by AlexSchwerzmann** [comment]
Great, thanks! We'll do so.
