### ISSUE TITLE
Reference to azure portal

### ISSUE THREAD

**Issue by ThijsLecomte** [MicrosoftDocs/memdocs#401]
[Enter feedback here]
There are a few references for the Azure Portal. these should be changed to the new MEM portal (https://endpoint.microsoft.com) as Intune won't be managed through the Azure Portal in the future

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a125bda-493d-8beb-e67f-09ff821e8fe4
* Version Independent ID: 39473e48-5fbd-a50c-6732-d86bcd1f7290
* Content: [What is app management in Microsoft Intune?](https://docs.microsoft.com/en-us/mem/intune/apps/app-management)
* Content Source: [memdocs/intune/apps/app-management.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-management.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@ThijsLecomte - Thanks for the feedback. I'm updating this doc to point to the MEM admin console. Thanks again.
