### ISSUE TITLE
Profile precedence? 

### ISSUE THREAD

**Issue by mikemagarelli** [MicrosoftDocs/memdocs#4012]
If multiple profiles have a conflicting setting, how does Intune determine/apply preference? The documentation around this is not very clear; please clarify. Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 14c045c9-2ccb-e24b-9eaa-bfd65b64a48c
* Version Independent ID: 355e928b-5ad8-ac1d-24d4-1d2e8f11cb4d
* Content: [Questions with policies and profiles in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/configuration/device-profile-troubleshoot#if-multiple-policies-are-assigned-to-the-same-user-or-device-how-do-i-know-which-settings-gets-applied)
* Content Source: [memdocs/intune/configuration/device-profile-troubleshoot.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/device-profile-troubleshoot.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by mikemagarelli** [comment]
Hi. Any update on this?

**Comment by msbemba** [comment]
@mikemagarelli Thank you for your feedback. The conflict is handled differently depending on the type of policy as described here https://learn.microsoft.com/en-us/mem/intune/configuration/device-profile-troubleshoot#conflicts , is there a confusion around a particular scenario?

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @mikemagarelli Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
