### ISSUE TITLE
Company portal with new store is not being installed and support has no idea why 

### ISSUE THREAD

**Issue by seeavosh** [MicrosoftDocs/memdocs#4023]
[Enter feedback here]
We have added the company portal via the new store and it has errors for all the devices with one expectation. Since support has no idea why they just not answering for over a month. This is a horrible experience. It would be practical to test your changes and provide good documents on how to the migration. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 42b3ccb0-592e-a0bf-aa4f-ab37e00e1195
* Version Independent ID: d0af9188-3489-0f15-ef25-5b6d83edb76c
* Content: [Add and assign the Windows Company Portal app for Intune managed devices - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/apps/store-apps-company-portal-autopilot)
* Content Source: [memdocs/intune/apps/store-apps-company-portal-autopilot.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/store-apps-company-portal-autopilot.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@seeavosh Thank you for your feedback. This sounds more like a technical issue and needs to be resolved by support or the product group (if escalated). The steps in the document are correct and any errors that you receive should be troubleshoot by the support team. If you are not getting any traction on the support issue, I'd recommend contacting your Technical account manager at Microsoft to expedite the process.

Hope this helps!

Thanks
Sri
