### ISSUE TITLE
Badly linked.

### ISSUE THREAD

**Issue by mckenzm** [MicrosoftDocs/memdocs#4024]
This page is linked to from https://www.microsoft.com/en-us/download/confirmation.aspx?id=105219 which is supposedly a "company portal" app download (it probably isn't). It claims your page has instructions for installing this app (no, it does not).    

I was trying to install "Company Portal" on Windows Server 2022 DataCenter edition, and I am not having fun. Giving up for now.

In any case it may concern you that the page is misrepresented. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 872bb519-684a-aca1-dae9-280686f0dd37
* Version Independent ID: 500146ba-b836-9df2-af7b-caf8dc50d929
* Content: [Add a Windows line-of-business app to Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/apps/lob-apps-windows)
* Content Source: [memdocs/intune/apps/lob-apps-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/lob-apps-windows.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@mckenzm Thank you for your feedback. These instructions are  to be followed ] to add the app to Intune for distribution - https://learn.microsoft.com/en-us/mem/intune/apps/lob-apps-windows

I was not able to find a specific document that talks about installing it on a Windows Server 2022 DataCenter edition, So I'd recommend you contact support via the need help section so they can provide you a document and/or guide you to install it.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @mckenzm Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
