### ISSUE TITLE
Please remove the blank at the end of policy com.microsoft.intune.mam.managedbrowser.NetworkStackPref 

### ISSUE THREAD

**Issue by crushonme** [MicrosoftDocs/memdocs#4036]
[Enter feedback here]
Please remove the blank at the end of policy com.microsoft.intune.mam.managedbrowser.NetworkStackPref .

If we copy the policy from the document, there will be a blank at the end of policy, which might cause the policy do not take effect.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a31e5a24-4f06-9e36-eacb-689bed95cd59
* Version Independent ID: ede9248e-1114-3e1a-9e80-34e5fe547707
* Content: [Manage Microsoft Edge on iOS and Android with Intune](https://learn.microsoft.com/en-us/mem/intune/apps/manage-microsoft-edge#switch-network-stack-between-chromium-and-ios)
* Content Source: [memdocs/intune/apps/manage-microsoft-edge.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/manage-microsoft-edge.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@crushonme Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/4063

Once the author approves, the changes will be live.

Thanks
Sri
