### ISSUE TITLE
Disk encryption not detected in intune in default installation following below guide.

### ISSUE THREAD

**Issue by jasper-dresens** [MicrosoftDocs/memdocs#4040]
Please add the following command to allow the Company Portal to read the disk encryption:
sudo usermod -a -G disk <USER_ACCOUNT>

If you do not provide this command in Ubuntu the Company Portal cannot read the disk information and therefore not reports to Endpoint Manager if the disk is encrypted or not. This resulsts in devices not being compliant based on the set compliance policies.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80924804-c247-d3bb-2245-fd3db3f3bd62
* Version Independent ID: 80924804-c247-d3bb-2245-fd3db3f3bd62
* Content: [Get the Microsoft Intune app for Linux](https://learn.microsoft.com/en-us/mem/intune/user-help/microsoft-intune-app-linux)
* Content Source: [memdocs/intune/user-help/microsoft-intune-app-linux.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/microsoft-intune-app-linux.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@jasper-dresens Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/4061

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by lenewsad** [comment]
Hi @jasper-dresens, @msbemba, we're still investigating this issue. Someone is actively looking into it. Thanks for your patience!

**Comment by Foorack** [comment]
I humbly wish Microsoft carefully considers the security implications here. Adding regular users to the group `disk` is equivalent to giving them full root. Intune should ideally implement a different system/method for checking if the disk is encrypted.

**Comment by yogkumgit** [comment]
Closing as per Author's input. Thanks
