### ISSUE TITLE
transition to Azure native cloud

### ISSUE THREAD

**Issue by miamo19** [MicrosoftDocs/memdocs#4041]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f10ec7c1-f6f2-492e-19cd-93658c6dee47
* Version Independent ID: f10ec7c1-f6f2-492e-19cd-93658c6dee47
* Content: [Common issues and resolutions with cloud-native endpoints - Microsoft Intune](https://learn.microsoft.com/en-us/mem/solutions/cloud-native-endpoints/cloud-native-endpoints-known-issues)
* Content Source: [memdocs/solutions/cloud-native-endpoints/cloud-native-endpoints-known-issues.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/solutions/cloud-native-endpoints/cloud-native-endpoints-known-issues.md)
* Service: **microsoft-intune**
* Sub-service: ****
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @miamo19 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
