### ISSUE TITLE
Doc is wrong about assigning custom permissions to view LAPS information

### ISSUE THREAD

**Issue by adamgell** [MicrosoftDocs/memdocs#4051]
```Retrieve local Administrator password – To view password details, your account must have one of the following Azure Active Directory permissions:

microsoft.directory/deviceLocalCredentials/password/read
microsoft.directory/deviceLocalCredentials/standard/read
During the public preview, these permissions aren't available to add to custom Azure AD roles. Instead, your account must be assigned one of the following Azure AD built-in rules, which include these permissions by default:

Global Administrator
Cloud Device Administrator
In the future, Azure AD will add support for assigning the required permissions to custom Azure AD roles.
```

This section says you can't create a custom role. I was just able to do this on 7/20/2023 inside Azure AD/Entra ID

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8eac0015-5225-7fc1-eb61-155efc075492
* Version Independent ID: 8eac0015-5225-7fc1-eb61-155efc075492
* Content: [Manage Windows LAPS with Microsoft Intune policies](https://learn.microsoft.com/en-us/mem/intune/protect/windows-laps-overview)
* Content Source: [memdocs/intune/protect/windows-laps-overview.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/windows-laps-overview.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@adamgell Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/4076

Once the author approves, the changes will be live.

Thanks
Sri
