### ISSUE TITLE
Endpoint Security Disk Encryption policy is not the same as in the documentation.

### ISSUE THREAD

**Issue by wander1992** [MicrosoftDocs/memdocs#4052]
The Endpoint Security Disk Encryption policy changed. This makes it confusing to create a policy for Autopilot devices.
For example, the setting 'Require device to back up recovery information to Azure AD' is missing. I only see the option 'Choose how BitLocker-protected operating system drives can be recovered' -->  Configure Storate of BitLocker recovery information to **AD DS**.

---
#### Document Details
D
⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ff0284d-e040-ea4a-dd6e-8184914ea702
* Version Independent ID: c756c9fe-f38a-e121-68a3-72489921e0e5
* Content: [Setting the BitLocker encryption algorithm for Autopilot devices](https://learn.microsoft.com/en-us/mem/autopilot/bitlocker)
* Content Source: [memdocs/autopilot/bitlocker.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/bitlocker.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
Thanks for the feedback @wander1992. Sorry for the delayed response. I don't see specifically the policy you mentioned in the text of the doc. It may be in the screenshot, but I am planning to remove the screenshot since it is outdated. Are there any specific updates you were looking to be made in the text of the doc? Please let me know. Thank you.

**Comment by frankroj** [comment]
Hello @wander1992. I didn't hear back from you. The screenshot has been removed from the article to avoid confusion. If you have additional feedback, please open a new feedback item. Thank you.
