### ISSUE TITLE
Windows 365 Custom Roles?

### ISSUE THREAD

**Issue by Aegrum** [MicrosoftDocs/memdocs#4054]
[Enter feedback here]
Where is the documentation for Windows 365 custom role creation? Those have totally separate capabilities, but I don't see the details listed anywhere in this documentation or elsewhere. Just a brief mention of the built-in "Cloud PC Reader" and "Cloud PC Administrator" roles.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ee559326-3f31-4a98-7399-21d571a42d9d
* Version Independent ID: 11eb7dee-44e1-d6bd-76c1-a6327199964d
* Content: [Create a custom role in Intune](https://learn.microsoft.com/en-us/mem/intune/fundamentals/create-custom-role)
* Content Source: [memdocs/intune/fundamentals/create-custom-role.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/create-custom-role.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by Smritib17** [comment]
@Aegrum Here's the link for Windows 365 documentation:
https://learn.microsoft.com/en-us/windows-365/enterprise/role-based-access#custom-roles

Hope this helps.
