### ISSUE TITLE
Setting is managed by the administrator

### ISSUE THREAD

**Issue by NailMicro** [MicrosoftDocs/memdocs#4055]
[Enter feedback here]

I would like to activate clous-based real protection, but I say that this function is managed by the administrator. I don't know who that is. I have a private computer.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 76b07dd3-8f84-c715-76f5-c22c2a98b5f3
* Version Independent ID: b212305e-9b54-f6cd-81bd-f23254f6891a
* Content: [Turn on Microsoft Defender Antivirus on enrolled device](https://learn.microsoft.com/en-us/mem/intune/user-help/turn-on-defender-windows)
* Content Source: [memdocs/intune/user-help/turn-on-defender-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/turn-on-defender-windows.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@NailMicro Thank you for your feedback. This sounds to be a technical issue and there could be another admin account involved, I'd recommend you contacting support via the need help section on the Admin portal.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @NailMicro Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
