### ISSUE TITLE
Windows 10 Enterprise LTSC 2019 is not supported

### ISSUE THREAD

**Issue by PaddyMaddy** [MicrosoftDocs/memdocs#4056]
In the last the documentation was mentioned for 1809, since the documentation is changed to 1903 as pre-requirement for pre-provision, it will be great if we can write atleast a note as Windows 10 Enterprise LTSC 2019 not supported for Autopilot.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c0f572e0-1bc0-6f14-7f60-989eb67fb7e7
* Version Independent ID: e4ec5b25-d9a6-d260-6cf6-ff4f3eb3ecb8
* Content: [Windows Autopilot for pre-provisioned deployment](https://learn.microsoft.com/en-us/mem/autopilot/pre-provision?source=docs)
* Content Source: [memdocs/autopilot/pre-provision.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/pre-provision.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
Thank you for the feedback @PaddyMaddy. In documentation, we list what is supported, not what isn't supported. The list of unsupported items is infinite, so it would be impossible to document. For this reason, if you don't see an item listed under the supported or prerequisite items, then you can assume it's not supported.
