### ISSUE TITLE
You should add below very important information to plan the solution 

### ISSUE THREAD

**Issue by theg00d1** [MicrosoftDocs/memdocs#4058]
[Enter feedback here]
You have 14 days from the time you reseal the device to the time  the user starts the user flow Autopilot. 
 If over 14 days has passed when the user flow of Autopilot starts, the Account Setup Phase of ESP will fail approximately two hours after the user starts ESP.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c0f572e0-1bc0-6f14-7f60-989eb67fb7e7
* Version Independent ID: e4ec5b25-d9a6-d260-6cf6-ff4f3eb3ecb8
* Content: [Windows Autopilot for pre-provisioned deployment](https://learn.microsoft.com/en-us/mem/autopilot/pre-provision)
* Content Source: [memdocs/autopilot/pre-provision.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/pre-provision.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
Thank you for the feedback @theg00d1. Can you clarify what is needed as part of your feedback? I am not seeing the text you entered as part of your feedback anywhere in this documentation.

**Comment by theg00d1** [comment]
Yes thats what i meant that you need to enter above very important
information as this is missing and very important at the time of designing
the solution.

**Comment by frankroj** [comment]
Ok thank you @theg00d1. For future reference, you can make the desired edits directly by using the pencil "Edit This Document" icon on the top right corner of the page instead of filing a feedback item. For an issue like this, it will also allow us to see where in the document you want the item placed.

With that said, what is the authoritative source of information that you are pulling from regarding the behavior that you want documented. We need to make sure that anything added to the official docs is 100% technically correct. Please let me know.

**Comment by theg00d1** [comment]
Yes Frank this is correct you can check internally with autopilot team
about the same and update the article accordingly.

Why i suggested this because its something very important information which
should be documented by MS.

**Comment by frankroj** [comment]
Thank you @theg00d1. I am part of the Autopilot team and work closely with the Autopilot PM. I've never heard of such a restriction that you are asking to be added to the docs. Where are you getting this information from regarding the restriction you want documented? Anything that is added to the docs has to be 100% technically correct so I am trying to ascertain your source of information so I can verify. Please let me know.

**Comment by theg00d1** [comment]
https://www.endpointmanagermags.com/post/windows-autopilot-for-pre-provisioned-deployment-white-glove

**Comment by frankroj** [comment]
Thank you @theg00d1. I have confirmed with the Autopilot PM that the information in that blog post is not correct. There is no such limitation. Always be wary of information on blog sites when there is no supporting information to back it up on the official docs sites. I am going to go ahead and close this request, but if there is anything else you need regarding docs, please let me know.

**Comment by theg00d1** [comment]
Thanks for the insights sir n confirmation by validating it with Product team.
