### ISSUE TITLE
IPv6 support for Windows Autopilot networking

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/memdocs#4059]
Please document, if organization have IPv6 network implemented, is IPv6 supported for Windows Autopilot?

Some users are reporting errors, but no official information.
https://www.reddit.com/r/Intune/comments/iu0j6s/enrollment_error_caa7000a/

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 82c5b872-c031-9ed9-c4cc-c8a1a8e93e0a
* Version Independent ID: ac837825-11e3-cf43-7516-0d94b496a59f
* Content: [Windows Autopilot networking requirements](https://learn.microsoft.com/en-us/mem/autopilot/networking-requirements)
* Content Source: [memdocs/autopilot/networking-requirements.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/networking-requirements.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
Thank you for the feedback @hkusulja. I apologize for the delay in responding. At this time, IPv6 is not listed in the supported configurations because it's not yet fully supported. However, although we can't confirm that it will be eventually fully supported in the future, we are taking a look at it.

**Comment by hkusulja** [comment]
@frankroj please write in documentation if local network has IPv6 that this is not supported scenario.
After this, please close this github issue that is requesting documentation update, thank you

**Comment by frankroj** [comment]
Thanks again @hkusulja for the additional feedback. We don't document what isn't supported - that list is infinite. We only document what is supported. If you don't find documentation that something is supported, then you can assume it's not supported. This includes IPv6.

**Comment by hkusulja** [comment]
Sorry, but I do not agree.
Some pages on Microsoft Learn documentation states if IPv6 is or is not supported.
Therefore, please update documentation stating that "only IPv4" is supported. (since it is also not mentioned :P )

**Comment by frankroj** [comment]
There's nothing to disagree with here. In general, it's Microsoft policy not to document unsupported scenarios because that would be an impossible task. That is a fact. We occasional will specifically call out an unsupported scenario if it is causing high traffic into support. This scenario doesn't fall under that criteria. Ultimately there is no need to document this. As previously explained, if you don't see something documented as supported, then you can assume its unsupported, so you already have the info you need. There is no need to be redundant.

**Comment by hkusulja** [comment]
@frankoj saying that, also it is not documented that "IPv4 is supported" but it is (otherwise it would not work). Therefore, asking again to document, that connections only using IPv4 are required/supported . You do not need to document what is not supported.
anyhow documentation purpose is to clarify things so others could use it.

**Comment by frankroj** [comment]
IPv4 is the default of TCP/IP, so there is no need to document the defaults. There is no special configuration you need to make to make IPv4 work, whereas you do need to do extra/special configurations for IPv6. Although trying to document the defaults is not an infinite list, like unsupported scenarios, it still would be an extremely long list and clutter the documentation with unnecessary info, making the relevant info much harder to find. As previously mentioned several times, if you don't find something listed as supported, then you can assume its not supported. That is all of the clarification that you need.

We aren't making an exception here. If we document it here, then we have to document it everywhere, and then we need to start documenting other unsupported items. This will end up making our documentation very cluttered and making the relevant information much harder to find. That is just not a rabbit hole that we're going to go down.

**Comment by hkusulja** [comment]
Who says IPv4 id efault, and not IPv6. For IPv4 your need to have configuration (router, DHCP etc.) the same/similar as for IPv6.
IPv6 standard is also more than 20 years old. It is in production in our country and organization for more than 10 years. We do not require any special configuration it is already configured, like IPv4.
I can also link different Microsoft documentation articles, stating the IPv6 is supported, and some are not supported.
Asking here to clarify, is it supported or not for Windows Autopilot scenario?
