### ISSUE TITLE
Add endpoints *.azureedge.net   and graph.microsoft.com to this article

### ISSUE THREAD

**Issue by Intunesupport2023** [MicrosoftDocs/memdocs#4066]
Following URLs needed to be defined as “No Authenticated” on the proxy:

*.manage.microsoft.com

*.azureedge.net

graph.microsoft.com 

It would be great, if this information could be added to the Documentation under -  “For some tasks, Intune requires unauthenticated proxy server access to manage.microsoft.com.” 

This lists only one URL. If added the other two URLs, this would help Enterprise customers to get this working right away.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c9c3475-56d4-026b-349f-f9cbc258537c
* Version Independent ID: 9c6476ed-8a47-bcb4-dfbf-25ba305c3b24
* Content: [Network endpoints for Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/fundamentals/intune-endpoints)
* Content Source: [memdocs/intune/fundamentals/intune-endpoints.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/intune-endpoints.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@Intunesupport2023 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/4077

Once the author approves, the changes will be live.

Thanks
Sri
