### ISSUE TITLE
Disk encryption policy settings template 

### ISSUE THREAD

**Issue by adamgell** [MicrosoftDocs/memdocs#4067]
[Enter feedback here]
This page does not represent the Windows 10 or later policy as of 7/28/2023. 

New: 
![image](https://github.com/MicrosoftDocs/memdocs/assets/27519/041d3b3e-b5ce-44c7-8be3-742309c15607)

Old:
![image](https://github.com/MicrosoftDocs/memdocs/assets/27519/7fc66cda-7793-49aa-8b3f-cdcbbaee2e2f)

I also do not see the option to ensure recovery keys are uploaded to Intune/Entra ID. Is it implied it happens automatically? 

Old policy had: 
![image](https://github.com/MicrosoftDocs/memdocs/assets/27519/315e5007-0715-4f6c-8f12-939a9a2394be)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bcec0953-586b-f8aa-5620-685199a24caf
* Version Independent ID: 0bc2907b-2300-058b-db4d-9a46f11f673d
* Content: [Intune endpoint security disk encryption policy settings](https://learn.microsoft.com/en-us/mem/intune/protect/endpoint-security-disk-encryption-profile-settings)
* Content Source: [memdocs/intune/protect/endpoint-security-disk-encryption-profile-settings.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/endpoint-security-disk-encryption-profile-settings.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@adamgell   Thanks for your feedback, and you’re correct. There was a change that was not communicated by the product group until a few days ago. (See [this recent What’s New in Intune](https://learn.microsoft.com/en-us/mem/intune/fundamentals/whats-new#new-bitlocker-profile-for-intunes-endpoint-security-disk-encryption-policy) entry). Intune released an update to the BitLocker profile which has now been documented.  If you revisit the content today, you'll see that it’s been updated.

The new BitLocker profile uses an updated Device Configuration settings format that pull setting names and options directly from the underlying Configuration Service Providers (CSPs), in this case from the BitLocker CSP.   This removes that has been a point of confusion around setting names and options found in the older profile design/implementation.  

With this new settings format, we no longer detail the settings that are in a profile, which we comment on in the settings article.  The older (original) profiles can continue to be used but any new settings will only be found in the newer profile formats.  With the new profile, the settings are the same as before at the time of change over, but we now rely on the settings CSP content to describe them in detail, (the Information text in the Intune UI for each setting is pulled out of the CSP itself) as that CSP content is and remains authoritative for use of these settings, and already published by Windows.
