### ISSUE TITLE
Sentence appears to be incomplete

### ISSUE THREAD

**Issue by brianleesmith** [MicrosoftDocs/memdocs#4070]
https://learn.microsoft.com/en-us/mem/intune/user-help/enroll-your-device-in-intune-macos-cp#enroll-your-mac

Bullet 5 of the Enroll your Mac section is not worded correctly.  SHould it be that the settings window "opens"?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 08300405-c9e4-b981-6151-a4309e6d11c7
* Version Independent ID: 8b5f54f1-07b3-dce5-4046-9ccf8798d3d0
* Content: [Enroll your Mac with Intune Company Portal](https://learn.microsoft.com/en-us/mem/intune/user-help/enroll-your-device-in-intune-macos-cp)
* Content Source: [memdocs/intune/user-help/enroll-your-device-in-intune-macos-cp.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/enroll-your-device-in-intune-macos-cp.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@brianleesmith Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/4078

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@brianleesmith Closing. Thanks
