### ISSUE TITLE
Does not explain why I can't download attachments

### ISSUE THREAD

**Issue by hspereboom** [MicrosoftDocs/memdocs#4073]
In my company OWA, I get the following warning when opening or composing an e-mail with attachments:
```
Your organization doesn't allow you to download or print attachments from this device or browser. You can still view attachments in your browser. For more information, contact your IT administrator. _Learn More_
```

Sure enough, I can't download any attachments, which is a PITA. What's the point of having BitLocker then? What's the point of risking employees having _losable devices_ to begin with? Why not just let everyone work from terminals and kiosk PC's? Why even trust external networks at all?

Anyway, _Learn More_ links to the below page, which explains **access to internal resources**. I can access OWA from pretty much anywhere I like, however I like. If e-mail itself is an internal resource, as the page claims, then I should not be able to use OWA using non-company networks and devices.

**Conclusion**: The page does not adequately explain why I can read sensitive e-mails from any network and any device, but cannot download innocuous attachments to my encrypted company device.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8dfb6a39-013e-7ca3-8133-9617458ed9f2
* Version Independent ID: 35e0cece-eb65-53a8-0aed-3648ccae0e07
* Content: [What is device enrollment](https://learn.microsoft.com/en-us/mem/intune/user-help/use-managed-devices-to-get-work-done)
* Content Source: [memdocs/intune/user-help/use-managed-devices-to-get-work-done.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/use-managed-devices-to-get-work-done.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@hspereboom Thank you for your feedback. This document should help fix - https://learn.microsoft.com/en-us/sharepoint/control-access-from-unmanaged-devices

Hope this helps!

Thanks
Sri

**Comment by hspereboom** [comment]
1. I'm not an admin, and have no control over company IT policy, so the article doesn't apply.
2. Unless MS Exchange has somehow migrated its storage to OneDrive or SharePoint, the article doesn't apply.

I'll file this under Annoyances, and bring it up during the next company IT survey.
