### ISSUE TITLE
Hyperlink typo

### ISSUE THREAD

**Issue by nhogarth86** [MicrosoftDocs/memdocs#408]
The hyperlink isn't displaying for "See Set up an Enrollment Status Page" here https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new#enrollment-status-page-profiles-can-be-set-to-device-groups 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d16c28db-1e8e-31fa-6127-3050a2940422
* Version Independent ID: 4cf9a244-1ae5-1637-48f7-3f503d400da6
* Content: [What's new in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new#enrollment-status-page-profiles-can-be-set-to-device-groups)
* Content Source: [memdocs/intune/fundamentals/whats-new.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/whats-new.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@nhogarth86 That link works for me. I'll close this issue. If you see the problem again, let me know.
