### ISSUE TITLE
DoD-Graph version?

### ISSUE THREAD

**Issue by jpcast88** [MicrosoftDocs/memdocs#4083]
Is there a DoD-Graph version of this tool for .us tenants?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bffd4704-acbf-a7e8-073f-7b0de922dcd8
* Version Independent ID: 39cc8624-ede4-2ec9-ea79-607347e5d17d
* Content: [Endpoint security firewall rule migration tool for Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/endpoint-security-firewall-rule-tool)
* Content Source: [memdocs/intune/protect/endpoint-security-firewall-rule-tool.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/endpoint-security-firewall-rule-tool.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@jpcast88   Hello Jonathan, I checked with our feature area PM on this, and there doesn't seem to be such a version of this tool.  If this is something that would have broad value, consider raising it directly with the product team.  This docs feedback is good for driving content changes or clarifying existing functionality, but not so good for driving future development decisions by the product group. :)
