### ISSUE TITLE
Scope Tags tab removed from Intune

### ISSUE THREAD

**Issue by USRobotics1** [MicrosoftDocs/memdocs#4087]
The tab "Scope Tags" has been removed from the wizard "Update rings for Windows 10 and later" page.

How this change can be considered to identify the rules of applicability about this kind of policy related to the device group assigned?

Thank you

https://i.postimg.cc/vmYr1z6h/Immagine-03-08-23-13-31.jpg

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2d67fb1e-47ec-a448-e2bd-757d898169d9
* Version Independent ID: df76b3b7-a69b-5ee9-e632-81d864fe6142
* Content: [Configure Update rings for Windows 10 and later policy in Intune](https://learn.microsoft.com/en-us/mem/intune/protect/windows-10-update-rings)
* Content Source: [memdocs/intune/protect/windows-10-update-rings.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/windows-10-update-rings.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@USRobotics1   Thanks for this GitHub issue and feedback. After some investigation with the product group, it seems the presence of the Scope Tag configuration page will only be visible for some policy types when there is a custom scope tag configured in the tenant.  IF you have custom tags configured and still don't see the Scope Tag page when expected, please contact support.

This behavior was not previously disclosed to the conent team, though I have now confirmed it affects the Windows Update policies, but not necessarily others, like device configuration policies.  It’s really hit and miss based on some internal development paths, though it seems it was at one time an expected design behavo (to hide the scope tags page if no custom tag had been configured in the tenant). 

Regardless of the why behind this, we are working on content updates to our Scope Tags article that will describe this behavior in one centralized location.  As we learn more in the days ahead, we might see additional content, or drive a change of behavior.  Updates to the Scope Tag artcile are being tracked by our team internally, but should reach publication within a week or so.
