### ISSUE TITLE
Please comment on how this coexists with AAD Connect

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/memdocs#409]
Most customers using Co-Management are going to be using Azure AD Connect, which also syncs computer objects to Azure AD. Please describe how Tenant Attach is different than this and how objects are joined up in the tenant or otherwise coexist.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2eb4acb-7311-79d3-3daa-6f27ea42aee7
* Version Independent ID: 123f2a5c-04c1-8184-05a4-689d9c591981
* Content: [Microsoft Endpoint Manager tenant attach - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/tenant-attach/device-sync-actions)
* Content Source: [memdocs/configmgr/tenant-attach/device-sync-actions.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/tenant-attach/device-sync-actions.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
HI @Mike-Crowley, they are two different things. Azure AD Connect is about device identity, whereas co-management and tenant attach are about device management. We just recently published a [co-management FAQ](https://docs.microsoft.com/mem/configmgr/comanage/faq) that addresses this topic.
