### ISSUE TITLE
Incorrect GPO Export Method

### ISSUE THREAD

**Issue by DJChupa13** [MicrosoftDocs/memdocs#4093]
Section "Export a GPO as an XML file" does not walk the user through exporting to XML, but to HTM, which is incompatible with the upload step in the next section "Import GPOs and run analytics."

The steps should instead walk the user through using the "Export" function instead of the "Save Report" function.

I'm starting to think this may come down to a version difference of gpmc.  These steps may actually be valid on a different version of Windows Server (or whatever box is running gpmc in the existing screenshot) than the one I have access to, which is Server 2022.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a25290f1-8600-da24-363b-b356997b9080
* Version Independent ID: 59691936-95e6-eead-41fa-89c95ee73201
* Content: [Use group policy analytics to import and analyze GPOs in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/configuration/group-policy-analytics)
* Content Source: [memdocs/intune/configuration/group-policy-analytics.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/group-policy-analytics.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by yogkumgit** [comment]
@MandiOhlinger Please help us in resolving this issue. Thanks

**Comment by MandiOhlinger** [comment]
@DJChupa13 Thank you. I added some info to that article about the steps being different, depending on the GPMC version. Hopefully that'll help others. If you have other text ideas, feel free to create a pull request with your recommended changes. Thanks again!
