### ISSUE TITLE
Update RBAC Role Info

### ISSUE THREAD

**Issue by RichardGallo-MS** [MicrosoftDocs/memdocs#4099]
In the article under this section [https://learn.microsoft.com/en-us/mem/intune/protect/windows-laps-overview?source=docs#role-based-access-controls-for-laps](url) - it states - 

> During the public preview, these permissions aren't available to add to custom Azure AD roles. Instead, your account must be assigned one of the following Azure AD built-in rules, which include these permissions by default:
> 
> Global Administrator
> Cloud Device Administrator
>
> In the future, Azure AD will add support for assigning the required permissions to custom Azure AD roles.

This is no longer the case. You can now create a custom Azure AD role that includes these properties and it works as expected. Is it possible to change the verbage here to point to a doc talking about how to create a custom role in Azure AD, or just directly say how to do it here? Either way, this info is now outrdated.

Thanks so much for taking a look!!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8eac0015-5225-7fc1-eb61-155efc075492
* Version Independent ID: 8eac0015-5225-7fc1-eb61-155efc075492
* Content: [Manage Windows LAPS with Microsoft Intune policies](https://learn.microsoft.com/en-us/mem/intune/protect/windows-laps-overview?source=docs#role-based-access-controls-for-laps)
* Content Source: [memdocs/intune/protect/windows-laps-overview.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/windows-laps-overview.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by RichardGallo-MS** [comment]
> @RichardGallo-MS Hello Richard, thanks for this feedback. We do have a content update for this already in progrss, which will remove the expressed limitatin and instead link to the following Azure AD (or Entra ID) article for creating those custom roles. https://learn.microsoft.com/en-us/azure/active-directory/roles/custom-create.
> 
> The content should be udpated in a day or two to reflect this.

Oh perfect! Thanks again! :-)

**Comment by yogkumgit** [comment]
@Brenduns Thank you very much for sharing this information. @RichardGallo-MS Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
