### ISSUE TITLE
Update Apple DEP information

### ISSUE THREAD

**Issue by ApeCogs** [MicrosoftDocs/memdocs#41]
Under *Retire an Apple DEP device from Intune*, bullet #3 - please update to the new website which is business.apple.com - the previous website has been deprecated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cdcc7fd-5bd9-1645-abf4-a73d3ea7adaa
* Version Independent ID: 5022b2ba-5fb0-18ce-9079-1b65ad0b2e17
* Content: [Retire or wipe devices using Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/remote-actions/devices-wipe#feedback)
* Content Source: [memdocs/intune/remote-actions/devices-wipe.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/remote-actions/devices-wipe.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@ApeCogs I'll fix that! Thanks!
