### ISSUE TITLE
New internet endpoint requirement (OfficeCDN)

### ISSUE THREAD

**Issue by psluke** [MicrosoftDocs/memdocs#410]
I don't use any Microsoft 365 integration, but still see OfficeCDNWorker.log trying to connect to https://go.microsoft.com/fwlink/?linkid=2094253, which resolves to https://contentstorage.osi.office.net/sccmreadiness/sot_sccm_addinreadiness.cab.

This url is not listed in the docs so far. The connection is therefore forbidden for my primary site, hence SMS_SERVICE_CONNECTOR status is populated with an appropriate error message once per day.

Please add e.g. contentstorage.osi.office.net to the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a9e88a5-bc7d-4982-4564-ceea80bde0e7
* Version Independent ID: 817824fe-5b44-ebeb-75c4-9eeb2dfa13ce
* Content: [Internet access requirements - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/network/internet-endpoints)
* Content Source: [memdocs/configmgr/core/plan-design/network/internet-endpoints.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/network/internet-endpoints.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @psluke for the feedback. That looks like it's for the [Office 365 ProPlus upgrade readiness dashboard](https://docs.microsoft.com/en-us/mem/configmgr/sum/deploy-use/office-365-dashboard#bkmk_readiness-dash). I'll get it added today.
