### ISSUE TITLE
Available Actions: Retire the noncompliant device (Add device to retire list)

### ISSUE THREAD

**Issue by these-work** [MicrosoftDocs/memdocs#4101]
"Retire the noncompliant device: This action removes all company data of the device and removes the device from Intune management." appears to now read "Add device to retire list" in Intune Endpoint Manager drop down action menus. Should this language be updated? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c2e7ac08-bfd6-9560-ad25-bced9b944822
* Version Independent ID: 6b1f70f0-aed3-52ac-25eb-1de55babc9d0
* Content: [Configure compliance policies with actions for noncompliance in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/actions-for-noncompliance)
* Content Source: [memdocs/intune/protect/actions-for-noncompliance.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/actions-for-noncompliance.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by these-work** [comment]
Would it be better to replace the sentence:

"...This action removes all company data of the device and removes the device from Intune management."

with the explanation that comes after it:

"When this action is performed on a device, the device is included in a list at Devices > Compliance policies > Retire Noncompliant Devices in the Microsoft Intune admin center. However, the device isn't officially retired until an administrator explicitly initiates the retirement process."

**Comment by msbemba** [comment]
@these-work Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/4119

Once the author approves, the changes will be live.

Thanks
Sri
