### ISSUE TITLE
What email address does the notification email come from? 

### ISSUE THREAD

**Issue by HarrisburgUSysAdmin** [MicrosoftDocs/memdocs#4103]
What email address does the notification email come from? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 90271d90-a909-6afd-31c8-f80561bd92de
* Version Independent ID: 90271d90-a909-6afd-31c8-f80561bd92de
* Content: [Set up enrollment notifications in Intune - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/enrollment/enrollment-notifications)
* Content Source: [memdocs/intune/enrollment/enrollment-notifications.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/enrollment-notifications.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@HarrisburgUSysAdmin Thank you for your feedback. 

The emails are sent from microsoft-noreply@microsoft.com

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @HarrisburgUSysAdmin Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
