### ISSUE TITLE
Missing Remediation Scripts on Public Preview Devices

### ISSUE THREAD

**Issue by mfactor000** [MicrosoftDocs/memdocs#4104]
The Remediation Scripts link/page is missing from the Public Preview.  I had to switch back to the current view to access it. Other than that i do prefer the new view.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 874bc975-429a-0b62-0958-549567c66d92
* Version Independent ID: 874bc975-429a-0b62-0958-549567c66d92
* Content: [Try new Devices experience in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/fundamentals/microsoft-intune-admin-center-devices)
* Content Source: [memdocs/intune/fundamentals/microsoft-intune-admin-center-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/microsoft-intune-admin-center-devices.md)
* Service: **microsoft-intune**
* Sub-service: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@mfactor000  Thank you for your feedback. Since the feature is in public preview. You can leave your feedback directly on our Main feedback page https://feedbackportal.microsoft.com/  , so that the product or dev team can review and respond.

Hope this helps!

Thanks
Sri
