### ISSUE TITLE
The Bash snippets include the prefixed dollar sign (`$`) when copying

### ISSUE THREAD

**Issue by richard-stafflink** [MicrosoftDocs/memdocs#4111]
When I click the "copy" icon on the snippets, the dollar sign (`$`) is included in the text copied.
This means I can't use the multiple lines snippets (or single line ones) easily.

Is there a way to not include them (`$`) in the copy buffer?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80924804-c247-d3bb-2245-fd3db3f3bd62
* Version Independent ID: 80924804-c247-d3bb-2245-fd3db3f3bd62
* Content: [Get the Microsoft Intune app for Linux](https://learn.microsoft.com/en-us/mem/intune/user-help/microsoft-intune-app-linux?source=recommendations)
* Content Source: [memdocs/intune/user-help/microsoft-intune-app-linux.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/microsoft-intune-app-linux.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@richard-stafflink Thank you for your feedback. I tried and don't see the dollar sign ($) in the text copied.

Thanks
Sri

**Comment by richard-stafflink** [comment]
Confirmed, it's fixed now.
