### ISSUE TITLE
Is it true that the user flow must complete within 14 days of finishing the technician flow of pre-provision?

### ISSUE THREAD

**Issue by impala-sc** [MicrosoftDocs/memdocs#4114]
This may explain some failures I see.  Here is where I got the 14 days from:
https://www.endpointmanagermags.com/post/windows-autopilot-for-pre-provisioned-deployment-white-glove

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 96020c1f-5d34-de2f-06be-771d6ad35ff2
* Version Independent ID: 96020c1f-5d34-de2f-06be-771d6ad35ff2
* Content: [Windows Autopilot for pre-provisioned deployment Azure AD join - Step 8 of 9 - User flow](https://learn.microsoft.com/en-us/autopilot/tutorial/pre-provisioning/azure-ad-join-user-flow)
* Content Source: [autopilot/tutorial/pre-provisioning/azure-ad-join-user-flow.md](https://github.com/MicrosoftDocs/memdocs/blob/main/autopilot/tutorial/pre-provisioning/azure-ad-join-user-flow.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
@impala-sc no this information is not correct. We repeatedly get asked regarding this article and it's simply not correct.
