### ISSUE TITLE
Revocation of SCEP certificates

### ISSUE THREAD

**Issue by MarkusMory** [MicrosoftDocs/memdocs#4118]
Good morning,

the docs say that for Windows devices an existing certificate is removed and revoked when the device is moved out of the scope of the certificate profile (either by being removed from the group or by removing the group from the certificate profile).

This is not correct. The certificate is removed from the client but it don't get revoked. It does get revoked if I use the "wipe" feature on the device.

With best regards
Markus

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 14c29d43-a41a-a660-4e79-4c06d6da76c0
* Version Independent ID: 5c69148b-56e4-df34-08b7-5bf5df3ad2fb
* Content: [Remove SCEP or PKCS certificates in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/remove-certificates)
* Content Source: [memdocs/intune/protect/remove-certificates.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/remove-certificates.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@MarkusMory Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/4149

Once the author approves, the changes will be live.

Thanks
Sri
