### ISSUE TITLE
Update with GDAP

### ISSUE THREAD

**Issue by Kazzan** [MicrosoftDocs/memdocs#4120]
Hi, CSP partners are now transferred from DAP to GDAP. Can you please update this article to reflect which roles and permissions are needed for this type of access?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 14a38eab-4bee-7c13-f4ad-6926c4e20d91
* Version Independent ID: 14a38eab-4bee-7c13-f4ad-6926c4e20d91
* Content: [Windows Autopilot customer consent](https://learn.microsoft.com/en-us/autopilot/registration-auth)
* Content Source: [autopilot/registration-auth.md](https://github.com/MicrosoftDocs/memdocs/blob/main/autopilot/registration-auth.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
Researching...

**Comment by frankroj** [comment]
Thank you for the feedback @Kazzan. We're not aware of any changes here. We always encourage a dap-free process.

**Comment by Kazzan** [comment]
Hi, in the past the DAP was required. In the GDAP times, you say that the consent is not needed and the CSP status and connection itself is enough to upload device identifiers to customer tenant, right?

**Comment by frankroj** [comment]
Consent is needed but the consent does not automatically grant GDAP unless the IT customer explicitly selects it in the consent form. What were saying is that the little box at the top of the form for GDAP is no longer needed, but the relationship connection is.
