### ISSUE TITLE
Zebra OEMConfig new vs legacy

### ISSUE THREAD

**Issue by snitkjaer** [MicrosoftDocs/memdocs#4126]
Zebra now has two versions of OEMConfig.

The new one does not seem to support multiple profiles:
https://techcommunity.microsoft.com/t5/intune-customer-success/new-zebra-oemconfig-app-for-android-11-and-later/ba-p/3846730

If that is correct I think the documentation should cover it.

Bo
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a755d393-5137-f710-df71-92358dcabafd
* Version Independent ID: c40db0b0-c89a-8f45-05f3-cc263e8c330c
* Content: [Deploy OEMConfig profiles to Zebra devices using Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/configuration/oemconfig-zebra-android-devices)
* Content Source: [memdocs/intune/configuration/oemconfig-zebra-android-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/oemconfig-zebra-android-devices.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@snitkjaer Thank you! The app info is added and live at https://learn.microsoft.com/mem/intune/configuration/oemconfig-zebra-android-devices#oemconfig-apps-for-zebra-devices.
