### ISSUE TITLE
AVD WUfB Documentation is incosistent

### ISSUE THREAD

**Issue by chbragg** [MicrosoftDocs/memdocs#4127]
This section describes how to update a multi-session AVD Session host using Windows Update for Business:
https://learn.microsoft.com/en-us/mem/intune/fundamentals/azure-virtual-desktop-multi-session?toc=%2Fazure%2Fvirtual-desktop%2Ftoc.json&bc=%2Fazure%2Fvirtual-desktop%2Fbreadcrumb%2Ftoc.json#windows-update-for-business

This section specifically says, "Windows Update for Business policies aren't currently supported":
https://learn.microsoft.com/en-us/mem/intune/fundamentals/azure-virtual-desktop-multi-session#configuration-issues

Please update the documentation to provide more clairification over what is supported and what is not supported in regards to multi-session OS and Windows Update for Business.

**Comment by Smritib17** [comment]
@chbragg thank you for the feedack. After verifying, I've updated the configuration issues table here: https://learn.microsoft.com/en-us/mem/intune/fundamentals/azure-virtual-desktop-multi-session#configuration-issues 
The content should be updated in a day or two to reflect this.
