### ISSUE TITLE
Update EJBCA information

### ISSUE THREAD

**Issue by svenska-primekey** [MicrosoftDocs/memdocs#413]
Update the info for EJBCA.  It should read just EJBCA now.  EJBCA is now integrated to issue SCEP with Intune and no longer requires the Open Source connector.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cda83a64-56ae-a632-dc81-dfd1a03984c1
* Version Independent ID: b93da48e-4097-4c3a-f6c8-02a5c4e0a616
* Content: [Use third-party certification authorities (CA) with SCEP in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/certificate-authority-add-scep-overview#set-up-third-party-ca-integration)
* Content Source: [memdocs/intune/protect/certificate-authority-add-scep-overview.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certificate-authority-add-scep-overview.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@svenska-primekey  Thanks for the heads up on the change. The link text and URL destination in the article will update later today.
