### ISSUE TITLE
What is the 'Company Portal App'?

### ISSUE THREAD

**Issue by fLaMePr0oF** [MicrosoftDocs/memdocs#4130]
What is the 'Company Portal App'?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7256d8af-6999-f5d6-b0c7-adc6afdbf4eb
* Version Independent ID: 9fa03eed-2c9e-4738-6e51-f2af7427451e
* Content: [Turn off Microsoft data collection on Windows device - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/user-help/turn-off-microsoft-usage-data-collection-windows)
* Content Source: [memdocs/intune/user-help/turn-off-microsoft-usage-data-collection-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/turn-off-microsoft-usage-data-collection-windows.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@fLaMePr0oF Thank you for your feedback. Intune Company Portal is the app that lets you, as an employee or student in your organization, securely access those resources.
For more information, visit https://learn.microsoft.com/en-us/mem/intune/user-help/sign-in-to-the-company-portal

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @fLaMePr0oF Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
