### ISSUE TITLE
"None" meaning "Some"?

### ISSUE THREAD

**Issue by Arne-RFA** [MicrosoftDocs/memdocs#4138]
[Enter feedback here]
Highlight added for emphasis
"**None** of the features mentioned in Option 1 are supported in Apple Setup Assistant authentication methods."

The following points are **identical** on Option 1 and Option 2 "Setup Assistant with modern authentication"

- Use multi-factor authentication (MFA).
- Prompt users to change their passwords when they first sign in.
- Prompt users to reset their expired passwords during enrollment.
- Register devices in Azure AD and use features available with Azure AD, such as conditional access.
- Automatically install the Company Portal app during enrollment. If your company uses the Volume Purchase Program (VPP), you can automatically install Company Portal app during enrollment without user Apple IDs.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0dcb837b-adcd-ae49-8a10-1be81979f1ba
* Version Independent ID: 0dcb837b-adcd-ae49-8a10-1be81979f1ba
* Content: [Authentication methods for Apple automated device enrollment - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/enrollment/automated-device-enrollment-authentication)
* Content Source: [memdocs/intune/enrollment/automated-device-enrollment-authentication.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/automated-device-enrollment-authentication.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by yogkumgit** [comment]
@lenewsad Please help us in resolving this issue. Thanks

**Comment by lenewsad** [comment]
Hi @Arne-RFA, thanks for sharing your feeback! We've since updated this article and rewrote those sections to improve clarity. 

@yogkumgit This issue can be closed. Thank you!
