### ISSUE TITLE
SQL Server 2019 Scaler UDF known issue fixed

### ISSUE THREAD

**Issue by ScottEricksonJr** [MicrosoftDocs/memdocs#414]
The Scalar UDF bug has been fixed in CU5 for SQL Server 2019:
https://support.microsoft.com/en-us/help/4538581/fix-scalar-udf-inlining-issues-in-sql-server-2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 142474e9-8dd5-6412-85ca-b1d2dc8c01ac
* Version Independent ID: d4de0aa7-2579-acdf-f7f5-04a39d8045d8
* Content: [Supported SQL Server versions - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/configs/support-for-sql-server-versions)
* Content Source: [memdocs/configmgr/core/plan-design/configs/support-for-sql-server-versions.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/configs/support-for-sql-server-versions.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @ScottEricksonJr for the feedback. I revised this section last week, after I confirmed with engineering.
