### ISSUE TITLE
Cannot set-intuneauthenticationtoken

### ISSUE THREAD

**Issue by JLambEJG** [MicrosoftDocs/memdocs#4141]
In the section for importing the PFX into Intune, I get an error when executing this command. The project built just fine. I entered the AppID, TenantID and App secret into the PS1 file before building. The Azure app has the permissions that are documented. The Intune key was created successfully. My account is a global admin in the tenant. 

Set-IntuneAuthenticationToken -AdminUserName "jeff.lamb@~~~~~.com"

Set-IntuneAuthenticationToken : An error occurred while sending the request.
At line:1 char:1
+ Set-IntuneAuthenticationToken -AdminUserName "jeff.lamb@~~~~~.com"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-IntuneAuthenticationToken], HttpRequestException
    + FullyQualifiedErrorId : System.Net.Http.HttpRequestException,Microsoft.Management.Powershell.PFXImport.Cmdlets.SetAuthToken

Where do I start to troubleshoot this?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aa43fc11-ff6b-20c8-5bfa-a89572295223
* Version Independent ID: ea0f43b6-5c74-6f9e-7e0c-ec86db3e4400
* Content: [Use imported PFX certificates in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/certificates-imported-pfx-configure)
* Content Source: [memdocs/intune/protect/certificates-imported-pfx-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/certificates-imported-pfx-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@JLambEJG Thank you for your feedback. This sounds like a technical issue and needs to be resolved by the support team. Please contact them via the need help section on the admin center

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @JLambEJG Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
