### ISSUE TITLE
Mail Drop settings not found in Device Restrictions policy for iOS

### ISSUE THREAD

**Issue by tomattto2** [MicrosoftDocs/memdocs#4143]
Hello!  In the section of this doc called 'Settings that require supervised mode' there is this paragraph

"iOS/iPadOS supervised mode can only be enabled during initial device setup through Apple's Device Enrollment Program, or by using Apple Configurator. Once supervised mode is enabled, Intune can configure a device with the following functionality:"

In the list of functionality that follows there is an item listed, Mail Drop, for which there don't seem to be any settings in the Device Restrictions for iOS.  If this setting is not configurable in the Device Restriction policy it should be removed from this doc. I've had customers interested in blocking Mail Drop but it doesn't seem possible even though the doc says it its.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 88932dd8-abce-bf23-9624-1df5f60a946d
* Version Independent ID: ab2d932f-e375-2485-a6e5-e02daf7a27c4
* Content: [iOS/iPadOS device settings in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/configuration/device-restrictions-ios#cloud-and-storage)
* Content Source: [memdocs/intune/configuration/device-restrictions-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/device-restrictions-ios.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@tomattto2 Thank you! That's good feedback. We updated the article, and the changes should be live later today.
