### ISSUE TITLE
AzureAD joined devices (not hybrid) can pull GPO's?

### ISSUE THREAD

**Issue by scratchg0lfr** [MicrosoftDocs/memdocs#415]
The bottom of the page contains the following "To help, there are group policy templates included in the Security Compliance Toolkit that can help manage hybrid AD and Azure AD-joined devices. These devices can get MDM settings from the cloud (Intune) and group policy settings from on-premises domain controllers as needed."

This causes confusion.  How can AzureAD devices get policies from on-premise Domain Controllers?  Isn't the concept of a domain controller foreign to an AzureAD joined device?   Hybrid AD joined devices can pull GPO's but AzureAD joined?  If they can, please link the "how" to the documentation here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c553157-31cf-faf9-0b4c-00f1a56f0545
* Version Independent ID: c91b6b7b-3264-f0f7-688e-baac0ce3a718
* Content: [Use security baselines in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/security-baselines#q--a)
* Content Source: [memdocs/intune/protect/security-baselines.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/security-baselines.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@scratchg0lfr   This seems to be some older content that needs some clean-up.  The current dev team owner confirms that the Policy Analyzer Tool and LGPO tool can be used  to compare GPO policies to what’s available in the cloud via security baselines – and that is the intent here. Manage isn’t the correct term and is misleading.

I’ll be submitting an edit to reword that last point to focus it on using the tools from the Security Compliance Toolkit to help you identify options from the cloud-based security baselines to replace the use of GPOs.
