### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by Mhudson97** [MicrosoftDocs/memdocs#4153]
"The default value will become true after Aug 28, 2023 with new release avaiable on Edge for iOS and Android."

Spelling mistake:  "avaiable" should be "available"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a31e5a24-4f06-9e36-eacb-689bed95cd59
* Version Independent ID: ede9248e-1114-3e1a-9e80-34e5fe547707
* Content: [Manage Microsoft Edge on iOS and Android with Intune](https://learn.microsoft.com/en-us/mem/intune/apps/manage-microsoft-edge)
* Content Source: [memdocs/intune/apps/manage-microsoft-edge.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/manage-microsoft-edge.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@Mhudson97 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/4185

Once the author approves, the changes will be live.

Thanks
Sri
