### ISSUE TITLE
Sync your device with Intune issue, mac, not compliant

### ISSUE THREAD

**Issue by tinntvs** [MicrosoftDocs/memdocs#4154]
[Nhập phản hồi vào đây]
Please fix.
https://techcommunity.microsoft.com/t5/microsoft-intune/sync-your-device-with-intune-issue-mac-not-compliant/m-p/3678520
We need the answer asap.

Thank!

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho learn.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: 4b888765-eb52-6903-09b0-c4909b8c2f0e
* Version Independent ID: c9237a9a-e05d-052e-8235-c25b7189da09
* Content: [Manually sync your macOS device with Intune Company Portal](https://learn.microsoft.com/vi-vn/mem/intune/user-help/sync-your-device-manually-macos)
* Content Source: [memdocs/intune/user-help/sync-your-device-manually-macos.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/sync-your-device-manually-macos.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@tinntvs Thank you for your feedback. This looks like a technical issue/bug and needs to be reported to the support team for resolution/bug fix. I'd recommend you contact the support team via the need help section on the admin center.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @tinntvs Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
