### ISSUE TITLE
HTTPS requirement for Recovery Service is unclear

### ISSUE THREAD

**Issue by LucasArona** [MicrosoftDocs/memdocs#416]
You say that: `Configuration Manager automatically installs the recovery service on each management point with an HTTPS-enabled website`

But, here : https://docs.microsoft.com/en-us/mem/configmgr/protect/deploy-use/bitlocker/encrypt-recovery-data
you said that:
`Starting in version 2002, the HTTPS requirement is for the IIS website that hosts the recovery service, not the entire management point role.`

If the MP is not HTTPS, MEMCM will not install automatically the recovery service? So, how can I manually reconfigure the recovery service to use HTTPS if it wasn't installed ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d362145-5048-abf3-fad0-1b6c25f76447
* Version Independent ID: 988e83fa-54da-9bf6-ba19-98006f0043a2
* Content: [Deploy BitLocker management - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/protect/deploy-use/bitlocker/deploy-management-agent)
* Content Source: [memdocs/configmgr/protect/deploy-use/bitlocker/deploy-management-agent.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/protect/deploy-use/bitlocker/deploy-management-agent.md)
* Product: **configuration-manager**
* Technology: **configmgr-protect**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @LucasArona for the feedback. Just a missed entry in this article that I need to revise. I'll do that today.

For more information on the process, see [HTTPS server authentication certificate](https://docs.microsoft.com/mem/configmgr/protect/deploy-use/bitlocker/encrypt-recovery-data#https-server-authentication-certificate).

**Comment by aczechowski** [comment]
Actually, re-rereading the section of this article, I don't think there's anything to change. If the MP has an HTTPS-enabled website, then the recovery service installs. That could be because the MP is HTTPS-enabled, or you've added a cert to the website. It then refers to the article to encrypt recovery data, which has the details on the process to add the server auth cert. So I'm going to close this issue; if you have any additional thoughts on how I can clarify, let me know.

**Comment by LucasArona** [comment]
Thanks for answering, @aczechowski, consider this scenario :

- Everything is HTTP, no HTTPS-enabled MP, no HTTPS website
- I create a BitLocker management policy => ConfigMgr can't find any HTTPS-enabled website, so, no recovery service.
- Now, what? We can't use the feature without the recovery service, so the system is in an "in-between" state where you have a Bitlocker management policy but no recovery service, should I delete the policy, add a cert to a random website and create the policy again ? Is it possible to manually install the recovery service afterwards ?

I hope my point is a bit clearer that way.

**Comment by aczechowski** [comment]
Hi @LucasArona. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

Step 8 of this article has an important note to not configure the client management settings if you don't have a MP with an HTTPS-enabled website. My guess is that you could remove the policy, set up the HTTPS website, and then recreate the policy, but I'm not certain. There's no supported process to manually install the recovery service.

**Comment by LucasArona** [comment]
In fact, I'm still in the planning phase, so I'm not in this case but I wanted to make sure I understood beforehand.
I jumped directly to the "Recovery Service" section (I followed the link in the first paragraph "For more information, see Recovery service.") so didn't saw the note, but now it's clearer. Thanks !
