### ISSUE TITLE
Edit the line about devices that are not supported by device restart

### ISSUE THREAD

**Issue by StarScreamV2x** [MicrosoftDocs/memdocs#4163]
[Enter feedback here]
Should there be another word or two after Android in the line that reads
"Android and Android Enterprise personally-owned work profile devices - Not supported"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d5c62d5b-4e09-0362-c056-c265b721d5aa
* Version Independent ID: 2cada33a-b9ce-6d05-9384-3e676916ec9d
* Content: [Restart devices with Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/remote-actions/device-restart)
* Content Source: [memdocs/intune/remote-actions/device-restart.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/device-restart.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@StarScreamV2x  Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/4186

Once the author approves, the changes will be live.

Thanks
Sri
