### ISSUE TITLE
Prerequisites for Remote Help on Android Page need update

### ISSUE THREAD

**Issue by Yogesh-Shede** [MicrosoftDocs/memdocs#4168]
[Kindly update on page "https://learn.microsoft.com/en-us/mem/intune/fundamentals/remote-help-android#prerequisites-for-remote-help-on-android" 

Install the **Intune Company Portal** app on devices with a version higher than 5.0.5541.0]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62e90445-8b52-cdd3-45e8-195dcd0f5be6
* Version Independent ID: 62e90445-8b52-cdd3-45e8-195dcd0f5be6
* Content: [Use Remote Help on Android to assist users authenticated by your organization.](https://learn.microsoft.com/en-us/mem/intune/fundamentals/remote-help-android#prerequisites-for-remote-help-on-android)
* Content Source: [memdocs/intune/fundamentals/remote-help-android.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/remote-help-android.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@Yogesh-Shede Thank you for your feedback. I'll review this with the author and provide an update shortly.

Thanks
Sri
