### ISSUE TITLE
Clarify explicitly whether mixed licensing is allowed

### ISSUE THREAD

**Issue by apcsb** [MicrosoftDocs/memdocs#4169]
Customers complain that while the docs mention the "Mixed licensing" scenario, where the number of users licensed for Adv Analytics (say, via Intune Suite) < Total number of Intune users, it is not clear, whether this is a violation of licensing terms or not (if, say, they would not use Adv analytics for the devices of the users that do not have the add-on license). Please clarify it here to avoid unnecessary confusion and requests.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3961f6df-83ff-66ac-1298-cbdbc37a400f
* Version Independent ID: 3961f6df-83ff-66ac-1298-cbdbc37a400f
* Content: [What is advanced Endpoint analytics - Microsoft Intune](https://learn.microsoft.com/en-us/mem/analytics/advanced-endpoint-analytics)
* Content Source: [memdocs/analytics/advanced-endpoint-analytics.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/analytics/advanced-endpoint-analytics.md)
* Service: **microsoft-intune**
* Sub-service: **endpoint-analytics**
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by yogkumgit** [comment]
@Smritib17 Please help us in resolving this issue. Thanks

**Comment by Smritib17** [comment]
@apcsb . Thanks for the feedback. We don’t currently have the ability to scope the premium features to only a subset of enrolled devices but in the not-too-distant future we’ll be able to build the functionality in the product. No ETA on if/when it'll be addressed.

**Comment by apcsb** [comment]
This isn't about product features, this is about clearly written documentation. Currently the customer doesn't understand what happens if they buy 1 Intune Suite license and the Analytics experience for the whole tenant gets elevated. Could you please clearly and explicitly state that this is OK?
