### ISSUE TITLE
Incompatibility with SSPR From Logon screen

### ISSUE THREAD

**Issue by Luca-Campenni** [MicrosoftDocs/memdocs#418]
Hello.
It seems that this configuration profile is interfering with the [SSPR link from logon screen](https://docs.microsoft.com/en-us/azure/active-directory/authentication/howto-sspr-windows).
When the "_Secure assessment (Education)_" is deployed, the link "_Reset Password_" doesn't appear.
As soon as the "_Secure assessment (Education)_" is removed, then the link "_Reset Password_" appears again.
I didn't find any document about this situation.
Following there's an extract of the [SSPR general limitations](https://docs.microsoft.com/en-us/azure/active-directory/authentication/howto-sspr-windows#general-limitations).
Does the "_Secure assessment (Education)_" change one of the following parameters, interfering with the SSPR link?
- The following settings are known to interfere with the ability to use and reset passwords on Windows 10 devices
  - If Ctrl+Alt+Del is required by policy in versions of Windows 10 before v1809, Reset password will not work.
  - If lock screen notifications are turned off, Reset password will not work.
  - HideFastUserSwitching is set to enabled or 1
  - DontDisplayLastUserName is set to enabled or 1
  - NoLockScreen is set to enabled or 1
  - EnableLostMode is set on the device
  - Explorer.exe is replaced with a custom shell

---
#### Document Details

* ID: faaa0d3e-add1-8e77-8b1a-0fda87b4e2a7
* Version Independent ID: 3916b4b4-dc5c-5f77-0a1e-d79d257e15c9
* Content: [Windows 10 education settings in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/education-settings-windows)
* Content Source: [memdocs/intune/configuration/education-settings-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/education-settings-windows.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @Luca-Campenni, I'm sharing your feedback with our product team and will update you (and the article) as soon as I find out more info. Thanks for your contribution!

**Comment by lenewsad** [comment]
Hi @Luca-Campenni,
The documentation team hasn’t been able to find an answer for this issue. If you still need help with this issue, please try one of the following support channels: 

- Open a support ticket by following the steps here: [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support). 

- Check out the [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod) archives or post on [Microsoft Q&A](https://docs.microsoft.com/answers/products/?WT.mc_id=msdnredirect-web-msdn). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.   

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.   

 I'm closing this issue as there's nothing actionable for docs at this time.
