### ISSUE TITLE
Supported versions of Android

### ISSUE THREAD

**Issue by cwaddzz** [MicrosoftDocs/memdocs#4180]
[Enter feedback here]
A more upto date statement about supported Android and iOS would be useful. January 2022 looks like it shouldnt be trusted.

As of January 7, 2022, the minimum supported versions are:

Android 8.0 for mobile device management (MDM)
Android 9.0 for mobile application management (MAM)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bb71b0b6-6790-50f1-21d7-5c83028f78b8
* Version Independent ID: bb71b0b6-6790-50f1-21d7-5c83028f78b8
* Content: [Admin checklist for Android software updates in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/software-updates-guide-android)
* Content Source: [memdocs/intune/protect/software-updates-guide-android.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/software-updates-guide-android.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@cwaddzz Thank you for your feedback. This statement is still accurate and holds good. 

The supported versions are

Android 8.0 for mobile device management (MDM)
Android 9.0 for mobile application management (MAM)

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @cwaddzz Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
