### ISSUE TITLE
Wrong version number

### ISSUE THREAD

**Issue by DamagedDingo** [MicrosoftDocs/memdocs#4183]
I noticed that the July and September releases show the same version number and the file I downloaded matched. When trying remote help from inside Intune it is not sending a notification, so I think both the download link and the recent release are still on previous version. 

Version: 5.0.1045.0

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c382484d-663f-4878-13c9-9ed6f3eb3679
* Version Independent ID: c382484d-663f-4878-13c9-9ed6f3eb3679
* Content: [Using Remote Help on Windows to assist authenticated users. - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/fundamentals/remote-help-windows#september-7-2023)
* Content Source: [memdocs/intune/fundamentals/remote-help-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/remote-help-windows.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by yogkumgit** [comment]
@Smritib17 Please help us in resolving this issue. Thanks

**Comment by DamagedDingo** [comment]
Is there anywhere to get the exe version after 5.0.1045.0 that contains the notification? 
I'm not sure if there is a way for me to get MS to update the download link in your document, so even after you update the version number to the correct one, the link will be incorrect.

**Comment by Smritib17** [comment]
@DamagedDingo, thank you for your feedback. After checking with the Product team I can  confirm the download link is correct with the most recent version for Remote Help. The Windows remote launch feature was in a much earlier build. It appears there may be some other issue involved, so we suggest  working with the Intune support team, for some troubleshooting. If they find something we should document, then they can loop us in. Also, the Microsoft Q&A might be a good option.
