### ISSUE TITLE
Please add info that the SettingName is case sensitive

### ISSUE THREAD

**Issue by Runda24328** [MicrosoftDocs/memdocs#4191]
Hello,
could you please add an info section that the "SettingName" value is case sensitive and has to match exactly with the output from a discovery script? Otherwise, 65008(Setting missing in the script result) error is thrown. Ask me how I know :)
Thank you.
Daniel

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a6dc763d-d6c5-c4c9-d035-efc4622367b3
* Version Independent ID: a6dc763d-d6c5-c4c9-d035-efc4622367b3
* Content: [Create a JSON file for custom compliance settings in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/compliance-custom-json)
* Content Source: [memdocs/intune/protect/compliance-custom-json.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/compliance-custom-json.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@Runda24328 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/4206

Once the author approves, the changes will be live.

Thanks
Sri
