### ISSUE TITLE
Question: Corporate-owned vs Personally owned devices?

### ISSUE THREAD

**Issue by matthewjlevy** [MicrosoftDocs/memdocs#4194]
Is there a definitive list of more granular settings and policies for corporate-owned over personally owned devices?

> Microsoft Intune offers more granular settings and policies for devices classified as corporate-owned. For example, there are more password policies to choose from in Intune for corporate-owned devices, so you can enforce stricter password requirements. Microsoft Intune automatically marks devices that meet certain criteria as corporate-owned.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 69ef74b0-acd5-6ebd-a020-958ccc8ef20d
* Version Independent ID: e8faf21f-5cf9-e87c-04e7-a244872aafc5
* Content: [Device enrollment guide for Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/fundamentals/deployment-guide-enrollment)
* Content Source: [memdocs/intune/fundamentals/deployment-guide-enrollment.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/deployment-guide-enrollment.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by yogkumgit** [comment]
@MandiOhlinger Please help us in resolving this issue. Thanks
