### ISSUE TITLE
[Windows Defender ATP] Device policy

### ISSUE THREAD

**Issue by BHeshka** [MicrosoftDocs/memdocs#4196]
In the tip section where it talks about the classical conditional access policy, you should add in the policy name "[Windows Defender ATP] Device policy" so that when people search what it is then this page comes up.  If there are other policies like this thier names should also be listed.  

It is tough to determine old info from new info on the internet and this Microsoft page can be the definitive answer of whether this classical policy is still needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 24fa182f-ace6-e7e2-ff98-91951be7d10e
* Version Independent ID: f1acb398-6d69-b91c-5ee0-3da3bbf7809f
* Content: [Configure Microsoft Defender for Endpoint in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/advanced-threat-protection-configure)
* Content Source: [memdocs/intune/protect/advanced-threat-protection-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/advanced-threat-protection-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by BHeshka** [comment]
In the published document the [ and ] brackets do not show up.  this is part of the name in the classical policies.
________________________________

**Comment by yogkumgit** [comment]
@msbemba Please review
