### ISSUE TITLE
No mention of Fat(MSI) clients or how to handle those scenarios

### ISSUE THREAD

**Issue by spshumwa** [MicrosoftDocs/memdocs#42]
This doc doesn't explain that it only applies to UWP apps, nor does it give any info on Win32/MSI clients. Please add details
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3772dd31-1256-2aad-758a-395c40864a73
* Version Independent ID: 95193c13-5acd-f133-31e4-722a6cbd4929
* Content: [Add VPN settings to devices in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/vpn-settings-configure#feedback)
* Content Source: [memdocs/intune/configuration/vpn-settings-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/vpn-settings-configure.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@spshumwa Since you are with MSFT, it'd be great if you started an internal email thread on what specifically you're looking for. I'll include the appropriate PM.
