### ISSUE TITLE
VPP Token Renewal Needs more clarity

### ISSUE THREAD

**Issue by jenujose** [MicrosoftDocs/memdocs#420]
After the new VPP token is downloaded from Apple.

You need to select the existing VPP token that you have configured in MEM, go to Basic Settings --> VPP Token File and then upload the new VPP token that you downloaded from Apple.

Current documentation is not clear on this step.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6be83bf7-b364-60e3-1b4f-97bbde969ada
* Version Independent ID: 02a2bedd-1af7-3a14-7314-11e0853e4c98
* Content: [Manage Apple volume-purchased apps - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/vpp-apps-ios)
* Content Source: [memdocs/intune/apps/vpp-apps-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/vpp-apps-ios.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@jenujose - Thanks for the feedback. I'm updating this topic now. Thanks again.
