### ISSUE TITLE
Intune EDR Policy Non-Compliant Issue only 2019 and 2022 servers

### ISSUE THREAD

**Issue by OrlandoSharessaT** [MicrosoftDocs/memdocs#4207]
[Enter feedback here]

We are required by our insurance policy to have EDR policy applied to all servers. We are using the SCCM tenant attach/co-management with Windows Defender onboarding and EDR policy in Intune. We have had many tickets related to this configuration due to server 2012R2/2016 being moved from MMA to Unified client, and sensor data not working, etc. currently we have had an on-going issue with now the server 2019's and 2022's showing in Intune policy as non-compliant.

I am wondering if this is in part or entirely due to the fact that "For policies that target the Windows 10, Windows 11, and Windows Server (ConfigMgr) platform (Configuration Manager), you'll see an overview of compliance to the policy but can't drill-in to view additional details. The view is limited because the admin center receives limited status details from Configuration Manager, which manages the deployment of the policy to Configuration Manager devices."?  Quoted from this page. How can we validate if the impacted devices are actually non-compliant for our EDR policies or if this is merely a reporting issue and how can we get these devices to show as compliant if it is a reporting issue?

Thanks for all your help and support in this matter,
Orlando
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4107154e-9df1-0380-e9af-a10b86dba3fa
* Version Independent ID: e41f3685-3d96-8610-6b24-568d19f2610c
* Content: [Manage endpoint detection and response settings with endpoint security policies in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/endpoint-security-edr-policy)
* Content Source: [memdocs/intune/protect/endpoint-security-edr-policy.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/endpoint-security-edr-policy.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@OrlandoSharessaT Thank you for your feedback. This is a technical issue and needs to be addressed by the support team. I'd recommend you contact support via the need help section on the admin center so that the support engineer can assist you.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @OrlandoSharessaT Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
