### ISSUE TITLE
Product Scope & Use Cases

### ISSUE THREAD

**Issue by wkelly24** [MicrosoftDocs/memdocs#421]
Add Desktop/Laptop device supported operating system to the list of use cases. For Example: Windows 10 Laptop/iPad/Android.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e85b5491-6bde-bd98-59cb-d3589a06d244
* Version Independent ID: 7f83ff32-4fce-cce4-e030-2db04bf5ec12
* Content: [Identify use case scenarios - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/planning-guide-scenarios)
* Content Source: [memdocs/intune/fundamentals/planning-guide-scenarios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/planning-guide-scenarios.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @dougeby
* Microsoft Alias: **dougeby**

**Comment by dougeby** [comment]
@wkelly24 Thanks for the feedback! We are currently going through a complete rewrite for the plan and migrate content and I have provided this feedback to the author.
