### ISSUE TITLE
Page states instructions are for legacy store app deployment, are actually for new store app deployment

### ISSUE THREAD

**Issue by techaryben** [MicrosoftDocs/memdocs#4212]
KB states that it applies to "Add Microsoft Store apps to Intune (legacy)", yet instructions are clearly for Add Microsoft Store apps to Intune (**New**).
Step 3 makes that abundantly clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ded6cdc4-3c0a-ae18-9d9c-b3d5db3c0708
* Version Independent ID: 34a4b4be-cd8b-25b3-49ef-f5142a87b9ef
* Content: [Add Microsoft Store apps to Intune (legacy)](https://learn.microsoft.com/en-us/mem/intune/apps/store-apps-windows)
* Content Source: [memdocs/intune/apps/store-apps-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/store-apps-windows.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@techaryben Thank you for your feedback. We have made changes to the document via PR https://github.com/MicrosoftDocs/memdocs/pull/4263

Once the author approves, the changes will be live.

Thanks
Sri
