### ISSUE TITLE
Store for Business

### ISSUE THREAD

**Issue by enroll-bacon** [MicrosoftDocs/memdocs#4227]
This page needs to be updated when it comes to application distribution as Store for Business apps have been decomissioned

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 97b3556b-5cb1-2eeb-e793-5efff254ddd7
* Version Independent ID: 16117a39-76b5-a7ef-7aa5-86678fe38013
* Content: [Kiosk settings for Windows 10/11 in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/configuration/kiosk-settings-windows)
* Content Source: [memdocs/intune/configuration/kiosk-settings-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/kiosk-settings-windows.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by msbemba** [comment]
@enroll-bacon Thank you for your feedback. The retirement of Microsoft Store for Business has been postponed. We will update this notice when a new retirement date is announced. You can continue to use the current capabilities of free apps until that time

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @enroll-bacon Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
