### ISSUE TITLE
Clarification on document note

### ISSUE THREAD

**Issue by mdparkinson** [MicrosoftDocs/memdocs#4235]
Need Clarification on:

The purple "Note" section under "Active Directory Requirements", does the second paragraph apply to devices once they are rejoined back into AAD with the same Device ID or something different? 

Assuming yes, that is in fact the case, then the context for the second paragraph would be that once a device is back in AAD with the same Device ID, any previous dynamic AAD groups it was previously a member of, would be rejoined within 48 hours but any previous static group memberships the device was previously a part of would need to be manually rejoined? Is that correct?

Thx,
-Mark

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b166b931-f3f7-3323-7288-758cfa5934f1
* Version Independent ID: b166b931-f3f7-3323-7288-758cfa5934f1
* Content: [Use Intune to manage Microsoft Defender security settings management on devices not enrolled with Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/mde-security-integration?pivots=mdssc-ga&source=docs)
* Content Source: [memdocs/intune/protect/mde-security-integration.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/mde-security-integration.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@mdparkinson Thank you for your feedback. Yes, you are correct

1) If the device was part of a dynamic Azure AD group, the policy targeting the device will be resolved within a minimum of 48 hours.

2)  If the device was targeted as part of a static Azure AD group, administrators will need to go back and retarget the device.

Hope this helps!

Thanks
Sri

**Comment by mdparkinson** [comment]
@msbemba Appreciate it. It was a point of discussion so thanks for clarifying.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @mdparkinson Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
