### ISSUE TITLE
Personally owned work profile option doesn't exist

### ISSUE THREAD

**Issue by PaulLeRoy1028** [MicrosoftDocs/memdocs#4236]
Under deviceManagementType the operator "Personal-owned work profile" doesn't exist in the drop down in the rule editor. Manually creating the rule in syntax editor (app.deviceManagementType -eq "Personal-owned work profile") doesn't return any results

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5c23357f-dd50-8ad1-084b-47ece285105f
* Version Independent ID: fa8f5486-8120-1548-a146-8f2e96995e9b
* Content: [Supported filter device and app properties & operators in Microsoft Intune](https://learn.microsoft.com/en-gb/mem/intune/fundamentals/filters-device-properties)
* Content Source: [memdocs/intune/fundamentals/filters-device-properties.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/filters-device-properties.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by msbemba** [comment]
@PaulLeRoy1028 Thank you for your feedback. This seems to be a technical issue or a bug and needs to be reported to the support team for a fix. I'd recommend you raise a support ticket via the need help section on the admin center, so that our support team can fix this for you.

Hope this helps!

Thans
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @PaulLeRoy1028 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
