### ISSUE TITLE
Clarifying language with setup step for Admin sign in

### ISSUE THREAD

**Issue by Joyos7** [MicrosoftDocs/memdocs#4239]
Hello! This could be just me, but I tend to be very much black and white with how I read something and implement based on those intructions and wanted to comment on the part where it states: "This user account must be a Global Admin or an Intune Admin with an Intune license assigned."

How I interpreted this is, you can use a GA account or use an Intune Admin account that will need an intune license. Whereas if you were using a Global Admin account, you won't need that license. I did search online that many users had a similiar hang up with an error in installing the tool and the error you get at the Azure Sign In page, is just "Something Went Wrong". Once we assigned the license to the user account (Global Admin), the installation of the tool went through beautifully (but after a few days of trying to see why the tool failed).

If that specific sentence can be updated to state something like: "An Intune license will be required when attempting to sign in with a Global Admin or Intune Administrator account" or "An Intune license is required for the account that you are signing in with that can be either a Global Admin or Intune Administrator". That would help someone like me to have clearer concise steps to take in configuring this connector.

All other aspects of this article was clear and easy to understand and thank you for that!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 497646f6-1498-0647-cc54-b8013d71dca6
* Version Independent ID: e1fa4f5d-35b1-6fad-a4d2-3e8f5952230c
* Content: [Install the Certificate Connector for Microsoft Intune - Azure](https://learn.microsoft.com/en-us/mem/intune/protect/certificate-connector-install)
* Content Source: [memdocs/intune/protect/certificate-connector-install.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/certificate-connector-install.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@Joyos7 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/4261

Once the author approves, the changes will be live.

Thanks
Sri
