### ISSUE TITLE
WQL for creating a collection of Co-Managed devices.

### ISSUE THREAD

**Issue by treestryder** [MicrosoftDocs/memdocs#424]
Could you please include sample WQL? Something like the following.
`
select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_Client_ComanagementState on SMS_Client_ComanagementState.ResourceId = SMS_R_System.ResourceId where SMS_Client_ComanagementState.ComgmtPolicyPresent = 1 AND SMS_Client_ComanagementState.MDMEnrolled = 1 AND MDMProvisioned = 1
`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f3684c-7f3f-ba2b-93eb-565640777161
* Version Independent ID: d666e010-2bea-3559-7dda-fb2e79bd8733
* Content: [Monitor co-management - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/comanage/how-to-monitor)
* Content Source: [memdocs/configmgr/comanage/how-to-monitor.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/comanage/how-to-monitor.md)
* Product: **configuration-manager**
* Technology: **configmgr-comanage**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
@treestryder Thanks! We have a page of example collection queries that I'll add this to along with putting in a tip on the co-management page that points to the query. Look for an update shortly on [this page](https://docs.microsoft.com/mem/configmgr/core/servers/manage/create-queries#BKMK_Example).

**Comment by reticentnz** [comment]
What is the purpose of "MDMProvisioned = 1" at the end of the query? I've found by dropping this (and leaving  SMS_Client_ComanagementState.ComgmtPolicyPresent = 1 AND SMS_Client_ComanagementState.MDMEnrolled = 1) I have a collection which updates the collection faster. What is the step which updates MDMProvisioned, and why would a device have the other two settings set, but not this one?
