### ISSUE TITLE
extrenal link is inaccessible

### ISSUE THREAD

**Issue by LijuV-MSFT** [MicrosoftDocs/memdocs#4269]
`For more details on the permissions, read [this article](https://personal.support.lookout.com/hc/articles/114094105653) on the Lookout website.`

The link https://personal.support.lookout.com/hc/articles/114094105653 is inaccessible

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e8cd87dd-b2a8-9ab3-76a4-af1cc3833d2f
* Version Independent ID: c38c0f8e-fea6-89f9-993c-23c01591393d
* Content: [Set up Lookout Mobile Endpoint Security with Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/lookout-mtd-connector-integration)
* Content Source: [memdocs/intune/protect/lookout-mtd-connector-integration.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/lookout-mtd-connector-integration.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@LijuV-MSFT  Thanks for this submission. I've just reached out to our Lookout contacts to see if we can get a new destination for that link. Once we can fix it, I'll also seek to add a bit of context to the article around the intended link destination to assist in locating the same information on the Lookout site should any updated  link break again in the future.

I'll update this post once we have a content fix on the way.

**Comment by Brenduns** [comment]
@LijuV-MSFT  I've heard back from out contact for Lookout, and it appears that linked article is no longer avaialble. Its moved to behind a login page, and is no longer something we can link to/reference in our content.  As it wasn't seen as essential information by Lookout at this time, and in fact this link dates back several years, with it unclear when the link became non-accessible, we'll be removing from our doc that Tip that presented the link.
