### ISSUE TITLE
Security Baseline for Microsoft Defender documentation not accurate with default value particular for Additional amount of time to extend cloud protection timeout

### ISSUE THREAD

**Issue by monleyva** [MicrosoftDocs/memdocs#4276]
From the documentation below

https://learn.microsoft.com/en-us/mem/intune/protect/security-baseline-settings-defender-atp?pivots=atp-december-2020#:~:text=Additional%20amount%20of%20time%20(0%2D50%20seconds)%20to%20extend%20cloud%20protection%20timeout%0ABaseline%20default%3A%200

The setting: **Additional amount of time (0-50 seconds) to extend cloud protection timeout
Baseline default: 0**

However, if you check the Intune portal, the default value is set to 50

Kindly review and check if updating the document is needed

![image](https://github.com/MicrosoftDocs/memdocs/assets/147533732/29aba8dc-e405-4abd-9ba3-c4645aef2e86)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 10ff4382-415c-4e80-e958-3bd77252fe2d
* Version Independent ID: 398a5b4b-e8bd-1f7d-ae30-38d812daf90d
* Content: [Settings list for the Microsoft Defender for Endpoint security baseline in Microsoft Intune - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/security-baseline-settings-defender-atp)
* Content Source: [memdocs/intune/protect/security-baseline-settings-defender-atp.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/security-baseline-settings-defender-atp.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@monleyva  You are correct!  That does appear to be 50.  I've submitted a doc udpate that will fix that error in content, which will be live in the next day or so.   Thank you!
