### ISSUE TITLE
Custom Script detection method - Nothing is said about the path from where it's executed

### ISSUE THREAD

**Issue by Tuttu** [MicrosoftDocs/memdocs#428]
Hello, 

When using a custom script as a detection method for an application, it is not mentioned from which folder the script is executed. 
Is it the ccmcache subfolder used during the installation? Is it from C:\Windows\System32? You have no clue until you test it.

And testing I have done. The detection method scripts (At least for PowerShell) are executed from `C:\WINDOWS\CCM\SystemTemp`. It may be worth adding a note about that. :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 791c915c-953e-a9a5-c85a-ec7e06098473
* Version Independent ID: d9e0b4fd-987d-2b12-a6be-3f2651ef214f
* Content: [Create applications - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/apps/deploy-use/create-applications)
* Content Source: [memdocs/configmgr/apps/deploy-use/create-applications.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/apps/deploy-use/create-applications.md)
* Product: **configuration-manager**
* Technology: **configmgr-app**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Tuttu for the feedback. Can you share why this detail is important? I have an idea, but don't want to assume 😄

**Comment by Tuttu** [comment]
Hello @aczechowski.

When I wrote this, I had planned that my detection method would use a file that was located in the ccmcache folder used during installation. So I was wondering if the detection script could know which folder it was. Then I realized I was doing it wrong and used a better method.

Now that I think about it, it's not that important to know. Only point that could be of interest is that the folder is accessible only by the SYSTEM account and local administrators so you know it's quite a safe place.

I think this issue can be closed. Sorry for the wrong input, I should have think a bit more before opening the issue. :)

**Comment by aczechowski** [comment]
Thanks @Tuttu for following up. No need to apologize, just wanted to make sure I understood the intent. 😄

**Comment by Sri-Boddupalli** [comment]
I believe its important to have this information in Official docs where this folder(C:\WINDOWS\CCM\SystemTemp) is being used(CI/Custom Detection methods). The reasons behind it 

1. Our Defender portal alerted some malicious scripts are being run from folder C:\WINDOWS\CCM\SystemTemp and no documentation around that folder and where ConfigMgr is actually using it 
2. we cannot add that to exclusions unless we know what we are excluding from Defender
