### ISSUE TITLE
Defender for Endpoint Security Baseline + Defender for Business?

### ISSUE THREAD

**Issue by JMCA2** [MicrosoftDocs/memdocs#4281]
It should be clarified if the "Defender for Endpoint Security Baseline" it's also intended for Defender for Business (or Business Premium, which includes Defender for Business) or only for Defender for Endpoint Plan 1 and Plan 2.

I would think yes, since Defender for Business is a SKU that has more features than Defender for Endpoint P1, but it's not clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 10ff4382-415c-4e80-e958-3bd77252fe2d
* Version Independent ID: 398a5b4b-e8bd-1f7d-ae30-38d812daf90d
* Content: [Settings list for the Microsoft Defender for Endpoint security baseline in Microsoft Intune - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/security-baseline-settings-defender-atp)
* Content Source: [memdocs/intune/protect/security-baseline-settings-defender-atp.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/security-baseline-settings-defender-atp.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by JMCA2** [comment]
@Brenduns @yogkumgit 
On https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12934 the general requirements for using Defender for Endpoint where updated to include Defender for Endpoint, but still need clarity on whether Defender for Business use with the Defender for Endpoint baseline is supported.

I already contacted Microsoft Support and they gave contradicting answers, because they only look at the docs.

**Comment by yogkumgit** [comment]
@Brenduns Please help us in resolving this issue. Thanks

**Comment by JMCA2** [comment]
@Brenduns  @yogkumgit  Any news regarding this?

We want to do a deployment of Defender Endpoint security baseline in an org with only Defender for Business licenses, and want to make sure it's a supported scenario.
Microsoft basic tier 1 support initially said it is not supported, but then after https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12934 they said yes but seemed unsure, but want to obtain confirmation and a definitive answer before deployment

Thanks

**Comment by Brenduns** [comment]
@JMCA2    Perhapse I see some of the confusion.  Security baselines are not unique to Intune. However, Intune does provide a simple user interface to configure and deploy some baselines, including the Defender baseline.  However, to deploy these through Intune, you must have a _Microsoft Intune Plan 1_ subscirption.   Without an Intune subscription, Intune isn't an option.   Instead, the source product in question Defender might have a method to deploy and manage the baselines, but that isn't something Intune or we can assist with.
