### ISSUE TITLE
Saving passwords to the password manager is allowed in current Edge Security Default

### ISSUE THREAD

**Issue by JMCA2** [MicrosoftDocs/memdocs#4284]
https://techcommunity.microsoft.com/t5/microsoft-security-baselines/security-baseline-for-microsoft-edge-version-114/ba-p/3839728

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7f66a25f-effa-61a9-dbf6-412ed1c3ad86
* Version Independent ID: 7f66a25f-effa-61a9-dbf6-412ed1c3ad86
* Content: [List of settings for the Microsoft Edge security baseline in Intune - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/security-baseline-v2-edge-settings)
* Content Source: [memdocs/intune/protect/security-baseline-v2-edge-settings.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/security-baseline-v2-edge-settings.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@JMCA2   Thanks for the post. 
 
Today, Intune provides the Microsoft Edge security baseline v112, which defaults to having **Enable saving passwords to the password manager** set to _Disabled_.

In the future, should a newer baseline version be made avaialble, we can expect the content to update to reflect that baselines default configuration for each setting, including any changes to _Enable saving passwords to the password manager_. 

However, even with a default value set to _disabled_, this like all settings in a baseline can be customized. So while defaulting to disabled, this setting continues to support being enabled with the current baseline version 112.
