### ISSUE TITLE
Deprecate conflicts?

### ISSUE THREAD

**Issue by OffColour** [MicrosoftDocs/memdocs#429]
With security settings all within Endpoint Security now will the duplicate settings in Compliance policies be deprecated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 338f151f-3d50-8a62-54f0-c718c7a86514
* Version Independent ID: 191fa5e1-f919-af27-b177-19f0202fa8f5
* Content: [Manage endpoint security in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/endpoint-security#avoid-policy-conflicts)
* Content Source: [memdocs/intune/protect/endpoint-security.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/endpoint-security.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by MattShadboltMSFT** [comment]
@OffColour - Compliance policies and Endpoint security policies might share some settings, but they actually perform different things. Endpoint security policies are used to perform general security configuration (AV, FW, BitLocker, etc), while Compliance policies are used to feed into Conditional Access. CA uses the compliance state returned from the Compliance policy to grant/block access to resources. So to answer the specific question - no, our compliance policies will not be deprecated for the Endpoint security policy, as they're performing different functions. 

If you're finding you've introduced conflicts, we suggest you avoid conflicts by ensuring setting values match exactly or are Not configured in overlapping policies. This is true for all device configuration, as conflicts only occur when two settings do not match.

**Comment by OffColour** [comment]
@MattShadboltMSFT Apologies, I worded this incorrectly. I should have said configuration policies, not compliance policies.

**Comment by MattShadboltMSFT** [comment]
@OffColour no worries. For device configuration profiles, our new policies share the same backend implementation with some extra value built on-top (think tri-state, policy dupe, etc). So customers can continue to use the device configuration profiles if they are happy with the device configuration profile experience. We think the new Endpoint security policy experience is better, and plan to continue adding extra value to these new profile types though. We don't want to force customers who are happy with their old profiles to use our new ones though - the decision is up to you. We hope that you find more value in our new profiles and move over to the new experience.  
RE conflicts, conflicts will behave exactly the same as if there were conflicts between two device configuration profiles. As mentioned, they're the same back end settings, so like we've always suggested... you should avoid conflicts in general.

**Comment by JeremyTBradshaw** [comment]
Hi @MattShadboltMSFT , thanks for giving the guidance you have re: the hope and recommendation from Microsoft to use the newer Endpoint Security options.  Just wondering if there is any docs page or official announcement/blog post that mentions this same guidance.  If necessary I'll just refer to right here, but I always like to back my recommendations to customers with official statements if possible.  To confirm, I am all aboard the new policies for any of the settings they can control, so this is just curiosity about the official recommendation (if there is one).

Thanks.
