### ISSUE TITLE
RBAC role for the Microsoft Store app (New) option

### ISSUE THREAD

**Issue by BurgerhoutJ** [MicrosoftDocs/memdocs#4292]
Hi all,

Who can tell me which custom RBAC setting that I need to enable the Microsoft Store app (New) option? I can't find it, or understand it, but as well when I open the GE and explorer the built-in application manager role, which clearly has the option, I can't find it as a setting.

![image](https://github.com/MicrosoftDocs/memdocs/assets/25769575/8c3f55d8-ed5a-4e5e-8ad3-68eae0700fe3)

So, who can help me?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ee559326-3f31-4a98-7399-21d571a42d9d
* Version Independent ID: 11eb7dee-44e1-d6bd-76c1-a6327199964d
* Content: [Create a custom role in Intune](https://learn.microsoft.com/en-us/mem/intune/fundamentals/create-custom-role?source=docs)
* Content Source: [memdocs/intune/fundamentals/create-custom-role.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/create-custom-role.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@BurgerhoutJ Thank you for your feedback. This sounds like a technical bug in the tenant, I'd recommend you contact support via the need help section on the admin center, so that our support engineers can assist you.

Hope this helps!

Thanks
Sri

**Comment by BurgerhoutJ** [comment]
Hi @msbemba,

I found the solution in the last days. It was a lack of sync time, I think. But it is working now.
