### ISSUE TITLE
Add link to Addigy Documentation

### ISSUE THREAD

**Issue by cchambers-cap** [MicrosoftDocs/memdocs#4296]
Could you add a link to Addigy's documentation at the bottom of the page where you link to other vendors documentation.
https://support.addigy.com/hc/en-us/articles/12346305032211

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 81bcb445-ada9-e2e3-d8a8-a5693a5a3850
* Version Independent ID: 6214bb16-5087-c21c-fd43-d5f0a6f405c1
* Content: [Third-party device compliance partners support in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/device-compliance-partners)
* Content Source: [memdocs/intune/protect/device-compliance-partners.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/device-compliance-partners.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@cchambers-cap Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/4314

Once the author approves, the changes will be live.

Thanks
Sri
