### ISSUE TITLE
Take out Azure AD, it must me Azure Entra ID

### ISSUE THREAD

**Issue by TonyAtHex** [MicrosoftDocs/memdocs#4297]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e7ae4a10-6e60-61e4-69c9-392b73313748
* Version Independent ID: e7ae4a10-6e60-61e4-69c9-392b73313748
* Content: [Windows Autopilot networking requirements](https://learn.microsoft.com/en-us/autopilot/networking-requirements)
* Content Source: [autopilot/networking-requirements.md](https://github.com/MicrosoftDocs/memdocs/blob/main/autopilot/networking-requirements.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by TonyAtHex** [comment]
it must be, typo

**Comment by frankroj** [comment]
Thank you for the feedback @TonyAtHex. We are automating the replacement of Azure AD to Microsoft Entra over the next few weeks. Hopefully it will be done by the end of the month.
