### ISSUE TITLE
Instructions for adding Company Portal app for Autopilot are not clear

### ISSUE THREAD

**Issue by webash** [MicrosoftDocs/memdocs#430]
There are weird layout issues with the text in the first instance, but that aside, the instructions in the `Assign the Company Portal app` section don't seem to actually assist with doing so.

`Select theAppstab on the right pane.`
Does this mean the left-hand dock?

`SelectCompany Portal (Offline).`
This is not an option anywhere. Where should one be seeing this? Should we click `Add` first?

`You must either Wait for the sync schedule to complete or do a manual sync from Microsoft Endpoint Manager admin center.`
This doesn't look like a step, this perhaps should be a 'note' style above these steps to warn you to wait for that sync _before_ proceeding with the steps. Additionally, perhaps the guidance for setting this up should be linked to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42b3ccb0-592e-a0bf-aa4f-ab37e00e1195
* Version Independent ID: d0af9188-3489-0f15-ef25-5b6d83edb76c
* Content: [Add and assign the Windows 10 Company Portal app for Autopilot provisioned devices - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/store-apps-company-portal-autopilot)
* Content Source: [memdocs/intune/apps/store-apps-company-portal-autopilot.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/store-apps-company-portal-autopilot.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@webash - Thanks for the feedback. Yes, I agree. I'm updating these steps now with additional links and an additional section about syncing Microsoft Store for Business apps with Intune. This should be publish tomorrow. Thanks again.
