### ISSUE TITLE
Apple Configurator

### ISSUE THREAD

**Issue by rodrigobcd** [MicrosoftDocs/memdocs#4303]
Suggestion to update this page.
In July 2023, Apple announced that starting with iOS16, Apple Configurator could be run from ANY iOS device running iOS 16.
https://support.apple.com/es-es/guide/apple-configurator/apd4015ec300/ios 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e790bad6-7f3d-67c4-405a-40f2403a7fb8
* Version Independent ID: c819bff5-3a6e-f7ae-a980-f01a25e6023f
* Content: [Turn on iOS/iPadOS supervised mode with Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/remote-actions/device-supervised-mode)
* Content Source: [memdocs/intune/remote-actions/device-supervised-mode.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/device-supervised-mode.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by yogkumgit** [comment]
@Smritib17 Please help us in resolving this issue. Thanks

**Comment by beflamm** [comment]
@Smritib17 @yogkumgit This is valid. Apple Configurator for iPhone can be used to supervise devices, too. We should include a link to the Apple support doc: https://support.apple.com/guide/apple-configurator/intro-apd4015ec300/1.1/ios/17.0

**Comment by Smritib17** [comment]
@rodrigobcd, Thanks for your feedback. This issue has been resolved and the article is now updated.
