### ISSUE TITLE
Is the code correct?

### ISSUE THREAD

**Issue by erottier** [MicrosoftDocs/memdocs#4306]
I've started making my own remediation scripts using the examples on this page.
Now, the script I've made uses the same return and afterwards exit commands and doesn't fail, while I expect it to.

In the first example called "Detect_Expired_Issuer_Certificates.ps1", does this actually work?
```
        Return $results.count
        exit 1
```
In my experience and testing it returns the count of $results and never exits using the exit code 1.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 96b618f0-cdb5-f184-66e6-c2e19cf57ea0
* Version Independent ID: 96b618f0-cdb5-f184-66e6-c2e19cf57ea0
* Content: [PowerShell scripts for Remediations - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/fundamentals/powershell-scripts-remediation#powershell-scripts-for-remediations)
* Content Source: [memdocs/intune/fundamentals/powershell-scripts-remediation.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/powershell-scripts-remediation.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by Smritib17** [comment]
@erottier , for questions like this, I suggest posting to [Microsoft Q&A](https://docs.microsoft.com/answers/products/enterprise-mobility-security). If you are creating your own script, and need some help, you can talk to the Intune support team who might be able to provide some guidance:

Use [get support for Microsoft Intune](https://docs.microsoft.com/mem/get-support) to open a support case.

**Comment by erottier** [comment]
@Smritib17 Ok, I was just being polite. I down right telling you that code on your docs site is incorrect. It was NOT a question. 

TBH I'm tired of support people downplaying fixes. Why? Just that the code and fix it for the world instead of just closing the case without even looking. Yes Im a bit grumpy because this isn't my first brush with moderators or something who are not even listening/paying attention to the actual text. Do your job.
