### ISSUE TITLE
Typo in Powershell command

### ISSUE THREAD

**Issue by HC3NET** [MicrosoftDocs/memdocs#4311]
Step 3 of the "Create JSON File for Autopilot profile(s)" section has a typo in the PowerShell script.

The first command reads:
Connect-M**g**Graph -Scopes.....

It should read:
Connect-M**s**Graph -Scopes.....

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3e53867b-75ea-4ee7-f975-cdf30e2cdc42
* Version Independent ID: 3e53867b-75ea-4ee7-f975-cdf30e2cdc42
* Content: [Windows Autopilot deployment for existing devices in Intune and Configuration Manager - Step 3 of 10 - Create JSON file for Autopilot profile(s)](https://learn.microsoft.com/en-us/autopilot/tutorial/existing-devices/create-json-file)
* Content Source: [autopilot/tutorial/existing-devices/create-json-file.md](https://github.com/MicrosoftDocs/memdocs/blob/main/autopilot/tutorial/existing-devices/create-json-file.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
Thank you for the feedback @HC3NET. However there is no type. It is Connect-MgGraph. Connect-MsGraph was part of the older deprecated AzureAD Graph PowerShell modules. Instead it now uses the Microsoft Graph PowerShell modules including Connect-MgGraph. For more information, see the following articles:

https://techcommunity.microsoft.com/t5/microsoft-entra-azure-ad-blog/important-azure-ad-graph-retirement-and-powershell-module/ba-p/3848270

https://learn.microsoft.com/en-us/powershell/microsoftgraph/authentication-commands?view=graph-powershell-1.0
