### ISSUE TITLE
Include preferredaadtenantdomainname to the list of conflicting policies

### ISSUE THREAD

**Issue by Skorfulose** [MicrosoftDocs/memdocs#4312]
Please include the following policy to the list of conflicts. It also fails the Autopilot deployment (at least when assigned on device-base; didn't test with user assignment yet):
https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-authentication#preferredaadtenantdomainname

E.g. if you configure it with a value of "testtenant.com", it will add to the "defaultuser0" and hence fail the autologon.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4b1d28c0-a160-598d-3497-8fa8a6051124
* Version Independent ID: 4b1d28c0-a160-598d-3497-8fa8a6051124
* Content: [Windows Autopilot policy conflicts](https://learn.microsoft.com/en-us/autopilot/policy-conflicts)
* Content Source: [autopilot/policy-conflicts.md](https://github.com/MicrosoftDocs/memdocs/blob/main/autopilot/policy-conflicts.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
Researching...

**Comment by frankroj** [comment]
Thank you for the feedback @Skorfulose. This policy has been added to the docs. It should go live either later today or tomorrow.
