### ISSUE TITLE
Hardware Device Details is missing a field for "Total physical memory"

### ISSUE THREAD

**Issue by JinhoKim-MSFT** [MicrosoftDocs/memdocs#4318]
The [hardware device details](https://learn.microsoft.com/en-us/mem/intune/remote-actions/device-inventory#hardware-device-details) page includes storage space:
<html>
<body>

Total storage space | The total storage space on the device (in gigabytes). | Windows, macOS, iOS
-- | -- | --
Free storage space | The unused storage space on the device (in gigabytes). | Windows, iOS

</body>
</html>

It doesn't have an entry for `Total physical memory` though, which was added later (referred to as `physicalMemoryInBytes` in [graph](https://learn.microsoft.com/en-us/graph/api/resources/intune-devices-manageddevice?view=graph-rest-1.0)).

I think the description could be something like:
"The total physical memory on the device (in gigabytes)."

And I believe the only currently supported platform (as of 2023/10/20) is just Windows.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 905c303e-4306-38ec-2a30-4852a8c1bc2b
* Version Independent ID: ceb7e815-e19a-386f-902c-6e6bf53d5766
* Content: [View device details with Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/remote-actions/device-inventory#hardware-device-details)
* Content Source: [memdocs/intune/remote-actions/device-inventory.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/device-inventory.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@JinhoKim-MSFT Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/4326

Once the author approves, the changes will be live.

Thanks
Sri
