### ISSUE TITLE
Download link for Power BI sample reports is broken

### ISSUE THREAD

**Issue by ladewig** [MicrosoftDocs/memdocs#432]
The link to to download the Power BI sample reports is broken.

https://www.microsoft.com/download/details.aspx?id=101452

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 266131e1-466d-ec44-35d2-e1f4fc08d27c
* Version Independent ID: 063515f6-2ea9-0d47-455b-982e14ea5580
* Content: [Install Power BI sample reports - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/manage/powerbi-sample-reports)
* Content Source: [memdocs/configmgr/core/servers/manage/powerbi-sample-reports.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/manage/powerbi-sample-reports.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @ladewig for the feedback. I added a note last week, the download was temporarily removed to resolve issues.
