### ISSUE TITLE
When deploying Managed Google Play Web link, you need to click Select. 

### ISSUE THREAD

**Issue by kagebarowska** [MicrosoftDocs/memdocs#4323]
When deploying Managed Google Play Web link, you need to click Select. 
before this was not necessary, it was working by just initiating sync. As per the techcommunity article: https://techcommunity.microsoft.com/t5/intune-customer-success/support-tip-intune-moving-to-support-new-google-play-android/ba-p/3849875
When adding Managed Google Play private apps and **Google Play web links**, **admins will need to click Select** ([similar to adding public store apps](https://learn.microsoft.com/mem/intune/apps/apps-add-android-for-work#managed-google-play-store-apps)) in the Managed Google Play pane to add them.

This needs to be reflected on this article. This is now a mandatory thing to do and it confuses customers.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a5a2b8f0-f2a0-f4d6-94d9-06e6d9632f59
* Version Independent ID: 8c8d89cf-9ed7-bb02-2439-e7ce9bb03f0c
* Content: [Add and assign Managed Google Play apps to Android Enterprise devices - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/apps/apps-add-android-for-work#managed-google-play-web-links)
* Content Source: [memdocs/intune/apps/apps-add-android-for-work.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/apps-add-android-for-work.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by daveapsgithub** [comment]
OMG.  Are you kidding me.  You dont want to know how much time I have spent on this.  I know it is Google's code but it is the WORST UI ever.  When you do document it can it put it in flashing H1 red text surrounded by facepalm emojis?

**Comment by msbemba** [comment]
@kagebarowska Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/4379

Once the author approves, the changes will be live.

Thanks
Sri
