### ISSUE TITLE
RBAC roles and permissions to view security policies

### ISSUE THREAD

**Issue by ildrosos** [MicrosoftDocs/memdocs#4333]
Hello we are using the RBAC permissions model within defender for Endpoint to give our analysts permissions to view and/or manage some of the aspects of the product . 
Currently it is required for our read-only analysts to have the ability to view the security policies for a given device . 
There is no mention in the document about what are the exact permissions required to be able to view the security policies . 
Can you please explain how we can do that ? 
![image](https://github.com/MicrosoftDocs/memdocs/assets/10010081/f1c80b84-1c1e-43a8-9436-03c0d1395f4d)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b166b931-f3f7-3323-7288-758cfa5934f1
* Version Independent ID: b166b931-f3f7-3323-7288-758cfa5934f1
* Content: [Use Intune to manage Microsoft Defender security settings management on devices not enrolled with Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/mde-security-integration)
* Content Source: [memdocs/intune/protect/mde-security-integration.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/mde-security-integration.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@ildrosos Thank you for your feedback. The Endpoint Security Policies page in Microsoft 365 Defender is available only for [users with the security administrator role in Microsoft 365 Defender](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/assign-portal-access). Any other user role, such as Security Reader, cannot access the portal. When a user has the required permissions to view policies in the Microsoft 365 Defender portal, the data is presented based on Intune permissions. If the user is in scope for Intune role-based access control, it applies to the list of policies presented in the Microsoft 365 Defender portal.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ildrosos Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by ildrosos** [comment]
Thanks @msbemba  . So you need to be an admin to view the policies assigned to a devices ? This is very permissive and we hoped we can allow our Security readers or a custom role to view the policies.
