### ISSUE TITLE
Create an App Control for Business policy

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/memdocs#4338]
Hello,

The following setup was tested:

1. Installed Windows machine
2. Enrolled Intune + AADJ
3. Installed Firefox, MS Office
4. Deployed this policy only {63D1178A-816A-4AB6-8ECD-127F2DF0CE47}

Running new setup like Chrome or Firefox setup blocked:

![image](https://github.com/MicrosoftDocs/memdocs/assets/39700914/aa397adf-121b-45ff-9384-5f6456317706)

![image](https://github.com/MicrosoftDocs/memdocs/assets/39700914/7a98eb8c-6a1c-4666-b366-eba67e0a9a50)

But, the Firefox that was installed before, still can run without any issues:

![image](https://github.com/MicrosoftDocs/memdocs/assets/39700914/c4c682bd-e947-4906-af02-18f65cf86254)

When looking at the event log, then it shows that Validation 2, but Verification 21, so like approved and failed :)
Why Firefox App allowed to run?
How to block Firefox in this combination?

![image](https://github.com/MicrosoftDocs/memdocs/assets/39700914/1a556e06-525c-4bfe-983c-4ae85650e468)

If the test is done another way:

1. Installed Windows machine
2. Enrolled Intune + AADJ
3. Deployed this policy only {63D1178A-816A-4AB6-8ECD-127F2DF0CE47}
4. Then cannot install FF

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d1c3d1e6-4314-d333-7e17-cca50f5d2fee
* Version Independent ID: d1c3d1e6-4314-d333-7e17-cca50f5d2fee
* Content: [Manage approved apps for Windows devices with App Control for Business policy and Managed Installers in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/endpoint-security-app-control-policy)
* Content Source: [memdocs/intune/protect/endpoint-security-app-control-policy.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/endpoint-security-app-control-policy.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@lightupdifire Thank you for your feedback. This sounds more like a technical bug and needs to be fixed by the product team. I'd recommend you contact support via the need help section on the admin center so that our support team will be able to escalate it.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @lightupdifire Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
