### ISSUE TITLE
Remote Help for MacOS 14 (Sonoma)?

### ISSUE THREAD

**Issue by davejenner** [MicrosoftDocs/memdocs#4342]
This article states that Remote Help is available on MacOS 11, 12 & 13. With MacOS 14 out, should this be included, yet?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fe1b4d0e-3f2e-7063-db1b-b081e763f751
* Version Independent ID: fe1b4d0e-3f2e-7063-db1b-b081e763f751
* Content: [Use Remote Help to assist users authenticated by your organization.](https://learn.microsoft.com/en-us/mem/intune/fundamentals/remote-help)
* Content Source: [memdocs/intune/fundamentals/remote-help.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/remote-help.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@davejenner Thank you for your feedback. The document is currently updated with macOS 11, 12, 13 and 14

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @davejenner Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
