### ISSUE TITLE
Confusing wording

### ISSUE THREAD

**Issue by VitalKoshalew** [MicrosoftDocs/memdocs#4348]
The following wording is very confusing:
"The reset passcode option can't be used on all corporate-owned devices."
Need to change it to "some corporate-owned devices" or further clarify.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e3135437-2b7c-da11-38f1-eda3d07de967
* Version Independent ID: eecdb690-105c-7d4e-27bc-bfec129c25b4
* Content: [Reset device passcode from Intune Company Portal website](https://learn.microsoft.com/en-us/mem/intune/user-help/reset-your-passcode-cpwebsite)
* Content Source: [memdocs/intune/user-help/reset-your-passcode-cpwebsite.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/reset-your-passcode-cpwebsite.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@VitalKoshalew Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/4370

Once the author approves, the changes will be live.

Thanks
Sri
