### ISSUE TITLE
The Global administrator role is a temporary requirement at the time of installation.

### ISSUE THREAD

**Issue by danbu** [MicrosoftDocs/memdocs#4354]
[Enter feedback here]
"The Global administrator role is a temporary requirement at the time of installation."
This works with Intune Administrator role as well unclear if anything else works as well

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e96ba3fe-0f09-9cd5-77ff-d18daf124ce1
* Version Independent ID: e96ba3fe-0f09-9cd5-77ff-d18daf124ce1
* Content: [Windows Autopilot user-driven Microsoft Entra hybrid join - Step 2 of 10 - Install the Intune Connector](https://learn.microsoft.com/en-us/autopilot/tutorial/user-driven/hybrid-azure-ad-join-intune-connector)
* Content Source: [autopilot/tutorial/user-driven/hybrid-azure-ad-join-intune-connector.md](https://github.com/MicrosoftDocs/memdocs/blob/main/autopilot/tutorial/user-driven/hybrid-azure-ad-join-intune-connector.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by msbemba** [comment]
@danbu  Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/4372

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by frankroj** [comment]
Researching...

**Comment by frankroj** [comment]
Thank you for the feedback @danbu. We have reworded to clarify that whatever account is used is temporary. This should go live tomorrow.
