### ISSUE TITLE
Configuration Profile Creation Step need to be updated 

### ISSUE THREAD

**Issue by Yogesh-Shede** [MicrosoftDocs/memdocs#4358]
[Changes in steps to create Configuration Profile 

Import and export settings catalog policies
The Intune [settings catalog](https://learn.microsoft.com/en-us/mem/intune/configuration/settings-catalog) lists all the settings you can configure, and all in one place (Devices > Configuration profiles > **Create > New Policy**  > Select your platform > For Profile, select Settings catalog).

![Configuration Profile steps](https://github.com/MicrosoftDocs/memdocs/assets/73707106/e8c30272-6ba4-4867-9166-4b4adfc6998d)
]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d16c28db-1e8e-31fa-6127-3050a2940422
* Version Independent ID: 4cf9a244-1ae5-1637-48f7-3f503d400da6
* Content: [What's new in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/fundamentals/whats-new#import-and-export-settings-catalog-policies)
* Content Source: [memdocs/intune/fundamentals/whats-new.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/whats-new.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@Yogesh-Shede Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/4374

Once the author approves, the changes will be live.

Thanks
Sri
