### ISSUE TITLE
Task Sequence Content Download

### ISSUE THREAD

**Issue by EN-Admin** [MicrosoftDocs/memdocs#436]
I am trying to determine if certain uses are possible in our environment (CM 1910), but see some ambiguity between the different use cases:
1) Windows 10 in-place upgrade task sequence 
2) Task sequences that aren't using boot images and are deployed with an option: Download all content locally before starting task sequence
3) Task sequences that aren't using boot images

For items 1 and 3, neither use boot images, so I am not sure of the difference there.  Can this be elaborated?
For item 3, it states this is available in CM 1910.  Does this include the option to "Download content locally when needed by the running the running task sequence"?  Should all task sequence deployment scenarios be available with CM 1910?

Thank you,
EN
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07d4e4f7-68ed-e604-b577-2c18617d1c2e
* Version Independent ID: 1ce10bc0-2a6d-405a-a9ae-46adfaac8fe6
* Content: [Plan for cloud management gateway - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/plan-cloud-management-gateway)
* Content Source: [memdocs/configmgr/core/clients/manage/cmg/plan-cloud-management-gateway.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/cmg/plan-cloud-management-gateway.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @EN-Admin. The first is the [in-place upgrade task sequence](https://docs.microsoft.com/mem/configmgr/osd/deploy-use/create-a-task-sequence-to-upgrade-an-operating-system). The third is any other [custom task sequence](https://docs.microsoft.com/en-us/mem/configmgr/osd/deploy-use/create-a-custom-task-sequence) that doesn't deploy an OS.

For the second, it's explained in more detail in [Deploy Windows 10 in-place upgrade via CMG](https://docs.microsoft.com/en-us/mem/configmgr/osd/deploy-use/deploy-a-task-sequence#deploy-windows-10-in-place-upgrade-via-cmg). In 1906 and earlier, you could only use the "download all content locally before starting" option. 1910 added support for either option.

I'll add these references to this CMG article to help clarify.
