### ISSUE TITLE
Wi-Fi connection details

### ISSUE THREAD

**Issue by jminnselset** [MicrosoftDocs/memdocs#4365]
What "Wi-Fi connection details" are preserved across an Autopilot Reset? Will the PSK for the home office Wi-Fi network for the previous user of a laptop be available to the next user, and is that the intention?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ca1cdb90-ea7b-7178-810a-8242b88bec91
* Version Independent ID: ca1cdb90-ea7b-7178-810a-8242b88bec91
* Content: [Windows Autopilot Reset](https://learn.microsoft.com/en-us/autopilot/windows-autopilot-reset)
* Content Source: [autopilot/windows-autopilot-reset.md](https://github.com/MicrosoftDocs/memdocs/blob/main/autopilot/windows-autopilot-reset.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
I assume that any requirements needed for the Wi-Fi connection are preserved. Since there are different ways to implement Wi-Fi connections, getting into details of what is preserved would just clutter the doc. A simple test should confirm and answer your question.
