### ISSUE TITLE
to be or not to be global admin.

### ISSUE THREAD

**Issue by patg84** [MicrosoftDocs/memdocs#4367]
You say not to login as a global admin for day to day task but you list no alternative.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e0f883bc-4852-5d5c-9708-0f8878ff18b5
* Version Independent ID: 88d715fd-f8c2-ffe1-5451-a3ad6fae1730
* Content: [Add users and grant permissions - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/fundamentals/users-add)
* Content Source: [memdocs/intune/fundamentals/users-add.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/users-add.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@patg84 Thank you for your feedback. We have now listed that you can Sign in to [Microsoft 365 admin center](https://admin.microsoft.com/) with a global administrator or user management administrator account to 
add Intune users in the Microsoft 365 admin center.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @patg84 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
