### ISSUE TITLE
Possible error in text describing Known issue for Power settings?

### ISSUE THREAD

**Issue by baardhermansen** [MicrosoftDocs/memdocs#437]
The text reads "You need to create a new task sequence deployment to enable or disable this setting for high performance. The new setting appears on existing **deployments**, but it doesn't apply."

I can only see the setting on the task sequence itself, there's nothing on the **deployment** suggesting a high power setting. 
Is this a typo? Or is it just an unfortunate description?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c22e3a22-310a-c33f-69a9-90c04e29a7f9
* Version Independent ID: 57821b74-d098-ccf5-65d0-131db824f50d
* Content: [Manage task sequences - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/osd/deploy-use/manage-task-sequences-to-automate-tasks)
* Content Source: [memdocs/configmgr/osd/deploy-use/manage-task-sequences-to-automate-tasks.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/osd/deploy-use/manage-task-sequences-to-automate-tasks.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @baardhermansen for the feedback. I think "unfortunate description" is probably accurate. 🥴 When you change the Performance setting in task sequence properties, it doesn't change the performance plan of the existing deployments of the task sequence. Usually when you change settings in task sequence properties, it updates all existing deployments.

I'll revise
