### ISSUE TITLE
Wrong settings in page 

### ISSUE THREAD

**Issue by KONIKPK** [MicrosoftDocs/memdocs#438]
ON MECM 2002 doesn't exist this settings :
Enable Endpoint analytics data collection in Configuration Manager
In the Configuration Manager console, go to Administration > Client Settings > Default Client Settings.
Right-click and select Properties then select the Computer Agent settings.

**Set Enable Endpoint analytics data collection to Yes**

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1830a271-791e-1cc8-62ac-8e9e7bc08052
* Version Independent ID: 288242a3-d4ea-2518-fd44-8efb8de7233b
* Content: [Quickstart - Enroll Configuration Manager devices - Microsoft Endpoint Manager](https://docs.microsoft.com/en-us/mem/analytics/enroll-configmgr#bkmk_prereq)
* Content Source: [memdocs/analytics/enroll-configmgr.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/analytics/enroll-configmgr.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by baardhermansen** [comment]
@KONIKPK Are you sure about that? My environment is 2002 (without the latest patch) and i find that setting. 
It's present both in Default Client Settings and other custom client settings.

**Comment by mestew** [comment]
I'm also running 2002 without the rollup. I see the Enable Endpoint analytics data collection at the very bottom of the Computer Agent client settings as well. @KONIKPK I am going to close this issue. Reopen it if you still don't see it. Please add your console version and the site version when you reopen. 
![image](https://user-images.githubusercontent.com/33289333/87091915-5c69bf00-c1ef-11ea-879d-a05b2586befb.png)

![image](https://user-images.githubusercontent.com/33289333/87091586-c897f300-c1ee-11ea-91a5-67fe9aa639d5.png)

**Comment by mestew** [comment]
well..... reopening this for tracking =) Stay tuned.

**Comment by mestew** [comment]
Closing this again. I'm pretty sure I reopened because I was waiting on this: [KB4560496 - Update rollup for Microsoft Endpoint Configuration Manager version 2002](https://support.microsoft.com/help/4560496), which was added ad a prereq around Sept2020
