### ISSUE TITLE
Enable LAPS in Entra steps are incorrect.

### ISSUE THREAD

**Issue by ssccaavvookk** [MicrosoftDocs/memdocs#4380]
> Enable LAPS in Microsoft Entra:
> 
> 1. Sign in to the Microsoft Entra admin center as a [Cloud Device Administrator](https://learn.microsoft.com/en-us/azure/active-directory/roles/permissions-reference#cloud-device-administrator).
> 
> 2. Browse to Devices > Overview > Local administrator password recovery.
> 
> 3. Select Yes for the Enable Local Administrator Password Solution (LAPS) setting and select Save. You may also use the Microsoft Graph API [Update deviceRegistrationPolicy](https://learn.microsoft.com/en-us/graph/api/deviceregistrationpolicy-update?view=graph-rest-beta&preserve-view=true).

Step 2 is incorrect. The setting to enable LAPS is under Devices -> Device Settings. Not Local administrator password recovery.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8eac0015-5225-7fc1-eb61-155efc075492
* Version Independent ID: 8eac0015-5225-7fc1-eb61-155efc075492
* Content: [Manage Windows LAPS with Microsoft Intune policies](https://learn.microsoft.com/en-us/mem/intune/protect/windows-laps-overview)
* Content Source: [memdocs/intune/protect/windows-laps-overview.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/windows-laps-overview.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@ssccaavvookk    Thanks for this feedback to bring this to our awarness.  After a review of the current UI, I've submitted a content update to fix the Intune docs. This update should go live later today or in the morning.
