### ISSUE TITLE
Impact of removing Google Play account

### ISSUE THREAD

**Issue by a-jsneed** [MicrosoftDocs/memdocs#4381]
What would be the direct impact of disconnecting the Google Play store from Intune? Will all apps be pulled from devices? Will they need to redownload/install them on their android device?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d9f750b6-7e0f-bd67-69b5-44f081f2afd6
* Version Independent ID: 8b3ba988-1184-82be-f35e-d161a199a305
* Content: [Connect your Intune account to your Managed Google Play account. - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/enrollment/connect-intune-android-enterprise)
* Content Source: [memdocs/intune/enrollment/connect-intune-android-enterprise.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/connect-intune-android-enterprise.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @a-jsneed Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
