### ISSUE TITLE
Correction needed in wording from "NO" to "NEW"

### ISSUE THREAD

**Issue by cm-ta** [MicrosoftDocs/memdocs#4386]
Correction needed in "...but no longer adds **no** features to it."   

Should be "...but no longer adds **new** features to it."

"Windows introduced the ApplicationControl CSP to replace the AppLocker CSP. Windows continues to support the AppLocker CSP but no longer adds no features to it. Instead, development continues through the ApplicationControl CSP."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d1c3d1e6-4314-d333-7e17-cca50f5d2fee
* Version Independent ID: d1c3d1e6-4314-d333-7e17-cca50f5d2fee
* Content: [Manage approved apps for Windows devices with App Control for Business policy and Managed Installers in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/endpoint-security-app-control-policy)
* Content Source: [memdocs/intune/protect/endpoint-security-app-control-policy.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/endpoint-security-app-control-policy.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@cm-ta  Thanks for calling attention to this typo. The content has updated to resolve this.
