### ISSUE TITLE
Use of * when configuring whitelist URLs doesn't match the veribage in the Intune portal

### ISSUE THREAD

**Issue by hesslerc** [MicrosoftDocs/memdocs#439]
The documentation on this page under the Kiosk browser URL whitelisting says that use of wildcard * are not allowed. However in the Intune portal the verbiage says "users can access all websites from the Microsoft Kiosk Browser. To restrict access to a specific set of websites, upload a file with up to 500 URLs on separate lines. Then users will only have access to these URLs. **Wildcard(*) characters are permitted**.
"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97b3556b-5cb1-2eeb-e793-5efff254ddd7
* Version Independent ID: 16117a39-76b5-a7ef-7aa5-86678fe38013
* Content: [Kiosk settings for Windows 10 in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/kiosk-settings-windows)
* Content Source: [memdocs/intune/configuration/kiosk-settings-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/kiosk-settings-windows.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@hesslerc The documentation is correct. If you enter wildcards, the sites aren't allowed. We don't have an ETA on if/when the text in the admin center will be updated.

To summarize, don't enter wildcards. By default, Intune allows all subdomains of a website.
