### ISSUE TITLE
Duplicate text

### ISSUE THREAD

**Issue by jpcast88** [MicrosoftDocs/memdocs#4390]
There is duplicate text referencing the Firewall PolicyCSP
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5d33743f-adf4-680b-483a-b83a625774f0
* Version Independent ID: 4b822bef-289f-77dd-8c50-fd20fdbb5f00
* Content: [Manage firewall settings with endpoint security policies in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/endpoint-security-firewall-policy)
* Content Source: [memdocs/intune/protect/endpoint-security-firewall-policy.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/endpoint-security-firewall-policy.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@jpcast88   Thanks for this submission. We have a content udpate scheduled to go out on Tuesday, November 14th, which will clear that duplication. 

cc @yogkumgit

**Comment by yogkumgit** [comment]
@Brenduns Thank you very much for sharing this explanation. @jpcast88 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
