### ISSUE TITLE
Missing "Apple configurator" in the admin tasks for "Direct enrollment"

### ISSUE THREAD

**Issue by TarekAtefAlassraj** [MicrosoftDocs/memdocs#4402]
The below sentence need to be changed.

"In the [Intune admin center], create an enrollment profile. Select Enroll without user affinity (user-less devices or shared devices)."

You should mention they need to go to "apple configurator" first then create an enrollment profile for the admin tasks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5973e60e-024a-6578-734a-9e50c42db0a9
* Version Independent ID: 49f6f728-13c4-02ab-bfec-a3054c3f4fd1
* Content: [macOS device enrollment guide for  Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/fundamentals/deployment-guide-enrollment-macos)
* Content Source: [memdocs/intune/fundamentals/deployment-guide-enrollment-macos.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/deployment-guide-enrollment-macos.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by msbemba** [comment]
@TarekAtefAlassraj We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/4421

Once the author approves, the changes will be live.

Thanks
Sri
