### ISSUE TITLE
char passcode on numerical pad

### ISSUE THREAD

**Issue by azzurroverde** [MicrosoftDocs/memdocs#4405]
I had my company reset my passcode, but my phone requires a numeric PIN.
I find it absurd.
I'm stuck.
Is there a place to use this passcode?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e3135437-2b7c-da11-38f1-eda3d07de967
* Version Independent ID: eecdb690-105c-7d4e-27bc-bfec129c25b4
* Content: [Reset device passcode from Intune Company Portal website](https://learn.microsoft.com/en-us/mem/intune/user-help/reset-your-passcode-cpwebsite)
* Content Source: [memdocs/intune/user-help/reset-your-passcode-cpwebsite.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/reset-your-passcode-cpwebsite.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@azzurroverde Thank you for your feedback. Ideally, it should ask for a numeric pin if the company reset the passcode, I'd recommend you contact support  via the need help section on the admin center, so that the Support team can help you out.

Hope this helps!

Thanks
Sri
