### ISSUE TITLE
Licensing for paths to co-management

### ISSUE THREAD

**Issue by si-chan** [MicrosoftDocs/memdocs#442]
In Paths to co-management (https://docs.microsoft.com/en-us/mem/configmgr/comanage/quickstart-paths), it says you can setup devices for co-management by (2) Modern provisioning to bootstrap the ConfigMgr Agent.

However in the "Does anything change with the rebrand to Microsoft Endpoint Manager?" section, it says:

> Effective December 1, 2019, if you're already licensed for Configuration Manager, then you're also automatically licensed for Intune for enrolling Windows PCs in co-management.

I would interpret this to mean that you would be licensed for the end state described in Path (2) in the first link.

However, during Modern Provisioning using Intune, the PC doesn't know anything about ConfigMgr.
This document does clarify to say:
> Windows 10 devices enrolled into Intune by using other means require full Intune licenses.

i.e. it clearly states you need an Intune license to perform the bootstrap.

However, it is less clear what happens to licensing at the end of the bootstrap process.

Does the ConfigMgr Agent then effectively grant the PC an Intune license, and thus the user subscription license (USL) for Intune can be removed from that user and given to someone else (reassigned)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f3023a8-ab6c-1d77-0111-77cc7583347c
* Version Independent ID: 26debf60-c3c1-caa6-7f78-a04a8b8e73af
* Content: [Product and licensing FAQ - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/understand/product-and-licensing-faq#bkmk_mem)
* Content Source: [memdocs/configmgr/core/understand/product-and-licensing-faq.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/understand/product-and-licensing-faq.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @si-chan for the feedback. I have a revision in the works that I hope will clarify.

**Comment by aczechowski** [comment]
I have a change for this issue in review, I hope it will publish in the next several days. This issue should auto-close when the change merges, at which time it will publish within one business day.
