### ISSUE TITLE
Exclusion from Conditional Access Policies

### ISSUE THREAD

**Issue by AntonK-Github** [MicrosoftDocs/memdocs#443]
About this note: 
"If you have an Azure AD Conditional Access policy defined and applies to All Cloud apps - you must exclude the created Server Application from this policy. For more information on how to exclude specific apps, see Azure AD Conditional Access Documentation."

Appreciate if you can provide some explanation why it shouldn't work with Conditional Access. 
And why only Server app is concerned and not the Client App. 

Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 639e477d-6e9d-a7b1-7978-f7d0f0283fc6
* Version Independent ID: 60b40c21-741b-42f8-a3e5-5f5a86811f59
* Content: [Configure Azure services - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/azure-services-wizard#create-server-application-dialog)
* Content Source: [memdocs/configmgr/core/servers/deploy/configure/azure-services-wizard.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/deploy/configure/azure-services-wizard.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @AntonK-Github. One of our program managers added it based on an email thread with developers. I don't have any further info.

**Comment by aczechowski** [comment]
Internal reference MicrosoftDocs/SCCMDocs-pr#5203
