### ISSUE TITLE
WPEUTIL Shutdown only works in Windows PE, but system is not in PE

### ISSUE THREAD

**Issue by Ghostmokey582** [MicrosoftDocs/memdocs#4431]
[Enter feedback here]
In the section: Shut down device after the task sequence completes (optional)
It instructs us in step 5 a to Select the last task in the task sequence.
Then it has us add the following run command line:
wpeutil.exe shutdown

However, at step 6 in the Speed up task sequence, we boot into Windows, and WPEUTIL only functions in Windows PE. So are we missing steps or should we be running a different command to perform the shutdown.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 961e2376-b278-802a-2def-895d6bfae29e
* Version Independent ID: 961e2376-b278-802a-2def-895d6bfae29e
* Content: [Windows Autopilot deployment for existing devices in Intune and Configuration Manager - Step 8 of 10 - Speed up the deployment process (optional)](https://learn.microsoft.com/en-us/autopilot/tutorial/existing-devices/speed-up-deployment)
* Content Source: [autopilot/tutorial/existing-devices/speed-up-deployment.md](https://github.com/MicrosoftDocs/memdocs/blob/main/autopilot/tutorial/existing-devices/speed-up-deployment.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by Ghostmokey582** [comment]
Missed step 5b. Should

**Comment by frankroj** [comment]
Yes correct @Ghostmokey582. This task sequence runs entirely within and ends in WinPE. Step 5b removes all the steps that normally would take the task sequence into and run in the full OS.
