### ISSUE TITLE
customername wrong

### ISSUE THREAD

**Issue by rscphat** [MicrosoftDocs/memdocs#444]
the customer in the case study is called "DB S**c**henker"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e969102-a98f-fcda-4bf3-7645f52a7896
* Version Independent ID: 92586124-bfff-4cde-3f07-cad9a61955f7
* Content: [Windows Autopilot with co-management - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/comanage/quickstart-autopilot)
* Content Source: [memdocs/configmgr/comanage/quickstart-autopilot.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/comanage/quickstart-autopilot.md)
* Product: **configuration-manager**
* Technology: **configmgr-comanage**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @rscphat for the feedback, I'll correct that now.
