### ISSUE TITLE
Doc contradicts itself

### ISSUE THREAD

**Issue by PJMarcum** [MicrosoftDocs/memdocs#448]
This docs states, "A wildcard can only match an entire component of the hostname (separated by periods) or entire parts of the path (separated by forward slashes). For example, http://*contoso.com is not supported." but in the examples it shows, "**http://*contoso.com/*** | Matches all subdomains ending with contoso.com/ | http://news-contoso.comhttp://news-contoso.com.com/daily | http://news-contoso.host.com" I think there's a typo here, "http://*contoso.com/*" should be "http://*.contoso.com/*"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a31e5a24-4f06-9e36-eacb-689bed95cd59
* Version Independent ID: ede9248e-1114-3e1a-9e80-34e5fe547707
* Content: [Manage Edge for iOS and Android with Intune](https://docs.microsoft.com/en-us/mem/intune/apps/manage-microsoft-edge#url-formats-for-allowed-and-blocked-site-list)
* Content Source: [memdocs/intune/apps/manage-microsoft-edge.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/manage-microsoft-edge.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@PJMarcum - Thanks for the feedback. I reviewed this issue with the Intune product team and they made updates to the documentation specifically to address your feedback. Thanks for your help.

Here's the section that was updated:
[URL formats for allowed and blocked site list](https://docs.microsoft.com/mem/intune/apps/manage-microsoft-edge#url-formats-for-allowed-and-blocked-site-list)
