### ISSUE TITLE
the problem might be not with main device storage, but with a SD card

### ISSUE THREAD

**Issue by rafalfitt** [MicrosoftDocs/memdocs#450]
You could add this as a hint.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 294e7745-6b0e-61b0-f57b-c1b00b9e58db
* Version Independent ID: a41e69e2-2d7d-ccb5-8491-8fc1ac6cf3a6
* Content: [Your Android device seems to be encrypted](https://docs.microsoft.com/en-us/mem/intune/user-help/your-device-appears-encrypted-but-cp-says-otherwise-android)
* Content Source: [memdocs/intune/user-help/your-device-appears-encrypted-but-cp-says-otherwise-android.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/user-help/your-device-appears-encrypted-but-cp-says-otherwise-android.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @rafalfitt, thank you for the suggestion! I shared this suggestion with the product team. 

Closing as there are no current changes to be made to this article.
