### ISSUE TITLE
(default) meaning

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/memdocs#451]
Hello,

Referring to previous case #397

Please give more light on this document, as an example, we take the first configuration:

A) Supported authentication schemes

    Enabled (default) - Schemes you select are used.
    Disabled
    Not configured - All four schemes are used.

What does this exactly mean here, in this document, the option **default**:

1. Is it default in the Edge browser?
2. Is it default in the Edge security baseline?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96f97bff-7548-846a-026d-8eda5e94da45
* Version Independent ID: 377b6f76-fec1-a55e-157a-d2db7060b56b
* Content: [Intune security baselines settings for Microsoft Edge - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/security-baseline-settings-edge?pivots=edge-april-2020)
* Content Source: [memdocs/intune/protect/security-baseline-settings-edge.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/security-baseline-settings-edge.md)
* Service: **microsoft-intune**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@lightupdifire  The content for this baseline will update later today to add some clarification, as well as links to supporting content, for the underlying Edge policy for HTTP Authentication.  By default, when not managed by these settings, Edge supports all four authentication schemes. By using the first instance of this setting your managing the option for HTTP Authentication on Edge. When that's set to _enable_ in the Baseline, you gain access to the following setting of the same name where you then define (to enforce) which of those four HTTP Authentication methods Edge will use.
