### ISSUE TITLE
Update prerequisites

### ISSUE THREAD

**Issue by jmbush** [MicrosoftDocs/memdocs#453]
[Enter feedback here]
Please update prerequisites noted:
DISA Purebred **(iOS only)**: https://public.cyber.mil/pki-pke/purebred/

Based on May update and noted deployment statement on the page, DISA Purebred is now support on Android Enterprise fully managed devices. 
Thanks,
Jeff
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d241b80-3ec6-debc-4f49-f8e02e86fc81
* Version Independent ID: c0443988-fec8-db83-e2f3-ff06b687a834
* Content: [Use derived credentials for mobile devices in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/derived-credentials)
* Content Source: [memdocs/intune/protect/derived-credentials.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/derived-credentials.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@jmbush  Thanks for that feedback. Looks like the prerequisites weren't updated when the Android applicability for DISA was added.  That's now fixed, but won't be visible in the published content until later today.
