### ISSUE TITLE
Redirect URIs in wrong app

### ISSUE THREAD

**Issue by MrRoundRobin** [MicrosoftDocs/memdocs#455]
Hi, 

in the official doc there is a tip to manually create the redirect uris `ms-appx-web://Microsoft.AAD.BrokerPlugin/<ClientID>` on the server app. In contrast in the following blog article from a PFE colleague these URIs are added in the client app: https://techcommunity.microsoft.com/t5/premier-field-engineering/importing-apps-to-set-up-cloud-management-gateway-cmg-for/ba-p/740011.

In my Customer Environments they are also set on the client apps which makes more sense, am I correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 639e477d-6e9d-a7b1-7978-f7d0f0283fc6
* Version Independent ID: 60b40c21-741b-42f8-a3e5-5f5a86811f59
* Content: [Configure Azure services - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/azure-services-wizard)
* Content Source: [memdocs/configmgr/core/servers/deploy/configure/azure-services-wizard.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/deploy/configure/azure-services-wizard.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @MrRoundRobin for the feedback. I think it should be the client app as well. I'm making some structural changes to the CMG content that I hope to publish this week, so will update this as well. This issue will auto close when the pull request merges, and then the changes will go live with the next daily publishing.
