### ISSUE TITLE
what is the difference between wake on magic packet and wake on pattern match

### ISSUE THREAD

**Issue by zhengxi0922** [MicrosoftDocs/memdocs#456]
[Enter feedback here]

what is the difference between wake on magic packet and wake on pattern match?
should we turn enable both to get wake on LAN or wake on WLAN work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 240ffd09-b912-426a-39fe-4b80d67aa021
* Version Independent ID: c3cb3aad-b115-6fa8-2ba2-45b8ddaf4f28
* Content: [Configure Wake on LAN - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/deploy/configure-wake-on-lan)
* Content Source: [memdocs/configmgr/core/clients/deploy/configure-wake-on-lan.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/deploy/configure-wake-on-lan.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
@zhengxi0922  If you're using  1810 or higher, it will use magic packet to wake the machine. When you enable the client setting, **Allow network wake-up**, it will change the NIC properties to allow Wake on LAN. I don't believe it is enabling pattern match on the NIC since CM won't be using that.
