### ISSUE TITLE
Cannot find Configuration Manager

### ISSUE THREAD

**Issue by LuckyDucky583** [MicrosoftDocs/memdocs#457]
How do I even open the configuration manager from the Azure console? I am inside the Microsoft Endpoint Manager admin center, which seems to be related to the issue, but I still don't know where I can get the desired device information from here on. A bit of clarification would be much appreciated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 875e279b-9029-d1e5-8a6c-0e93ce38ddba
* Version Independent ID: 80bc34d7-3ef7-1c4f-da41-0474b1c5f4a4
* Content: [Co-manage internet-based devices - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/comanage/how-to-prepare-Win10#windows-autopilot)
* Content Source: [memdocs/configmgr/comanage/how-to-prepare-Win10.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/comanage/how-to-prepare-Win10.md)
* Product: **configuration-manager**
* Technology: **configmgr-comanage**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
@LuckyDucky583
You access the CM console from a device it's installed on. 
https://docs.microsoft.com/mem/configmgr/core/servers/deploy/install/install-consoles
Once it's installed, you configure it to connect to one of the CM site servers. 
https://docs.microsoft.com/mem/configmgr/core/servers/manage/admin-console

#please-close
