### ISSUE TITLE
Block users from ignoring SmartScreen warnings wrong description

### ISSUE THREAD

**Issue by dara2** [MicrosoftDocs/memdocs#458]
[Enter feedback here]
at SmartScreen
Block users from ignoring SmartScreen warnings

There is not much difference between

Yes (default): ** the user will be able to bypass it.**
and
Not configured: ** allows the user override.**

I think "Yes" should be changed to "the user will **not** be able to bypass it."
This is also confirmed by the CSP  doc of SmartScreen/PreventOverrideForFilesInShell

0 – Employees can ignore SmartScreen warnings and run malicious files.
1 – Employees cannot ignore SmartScreen warnings and run malicious files.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10ff4382-415c-4e80-e958-3bd77252fe2d
* Version Independent ID: 398a5b4b-e8bd-1f7d-ae30-38d812daf90d
* Content: [Intune security baselines settings for Microsoft Defender Advanced Threat Protection - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/security-baseline-settings-defender-atp?pivots=atp-april-2020)
* Content Source: [memdocs/intune/protect/security-baseline-settings-defender-atp.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/security-baseline-settings-defender-atp.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@dara2 Thank you for the feedback. I've submitted a fix for this docs content which will update later today for this article, as well as a couple other where this setting also appears with the same text. As our docs are based on the in product text, I've also worked with the engineering team which will be revising the _Information_ text for this setting. That in-product revision will update the UI in a future product update.
