### ISSUE TITLE
A mistake in CSP

### ISSUE THREAD

**Issue by obyazov** [MicrosoftDocs/memdocs#459]
The current CSP for "Scan all downloaded files and attachments" setting is EnableNetworkProtection. But this very CSP is mentioned in "Turn on network protection". At the same time, if we look at https://docs.microsoft.com/en-us/mem/intune/protect/security-baseline-settings-defender-atp?pivots=atp-march-2020#microsoft-defender the CSP for this setting must be AllowIOAVProtection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b84f6130-b993-bd26-0147-29748c3b7449
* Version Independent ID: 231c5984-ee21-059b-22d4-21b2f009124e
* Content: [Windows 10 Antivirus policy settings for Microsoft Defender Antivirus for Intune](https://docs.microsoft.com/en-us/mem/intune/protect/antivirus-microsoft-defender-settings-windows)
* Content Source: [memdocs/intune/protect/antivirus-microsoft-defender-settings-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/antivirus-microsoft-defender-settings-windows.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@obyazov Thanks for this feedback. It appears that the UI link to the CSP (which is reflected in this doc) is incorrect. I've passed this on to our engineering team so they can check and redirect the link to the correct destination. As you note, the ATP security baseline points to the following destination for this setting, which appears to be the correct reference: https://docs.microsoft.com/windows/client-management/mdm/policy-csp-defender#defender-allowioavprotection

With this information passed on to Engineering for a fix (which will fix it in the product, and docs), i'll close this feedback issue.
