### ISSUE TITLE
Change Autodiscovery

### ISSUE THREAD

**Issue by r-milne** [MicrosoftDocs/memdocs#461]
Hi folks,

The Exchange feature is called Autodiscover.  Can we call it by that name please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c08834b8-fcb3-49c9-331e-c1a052982ca4
* Version Independent ID: 94ead8b3-89d1-3c80-7ac6-8551415461c5
* Content: [Troubleshoot common problems for the Intune Exchange connector - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/troubleshoot-exchange-connector-common-problems)
* Content Source: [memdocs/intune/protect/troubleshoot-exchange-connector-common-problems.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/troubleshoot-exchange-connector-common-problems.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@r-milne  Thanks for this feedback. The content has had a fix summitted, which should be live later today.
