### ISSUE TITLE
Certificates needed for SRSRP/SSRS are missing

### ISSUE THREAD

**Issue by Yupiter2005** [MicrosoftDocs/memdocs#462]
It would be nice to have at least a link on how to choose a certificate for HTTPS on it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 174d8846-7eaa-9b3d-7822-77a7e89bd0d1
* Version Independent ID: fe152fd0-7a49-9214-f1ce-1e9eb25dbdae
* Content: [PKI certificate requirements - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/network/pki-certificate-requirements)
* Content Source: [memdocs/configmgr/core/plan-design/network/pki-certificate-requirements.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/network/pki-certificate-requirements.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @Yupiter2005 for the feedback. We have an internal item tracking rework to this article. 
(Internal reference CMADO-2841906)
