### ISSUE TITLE
No Orange banner

### ISSUE THREAD

**Issue by LuckyDucky583** [MicrosoftDocs/memdocs#463]
Hi, 

I am inside the microsoft Endpoint manager, but cannot see any orange banner, which I am supposedly able to see. Is there a way to set the mdm-authority without the orange banner?

Best,

Lucas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a76fc834-999b-2dea-10b7-984225b695dd
* Version Independent ID: 583b8b02-5c7b-aa08-ec28-07b89adbd994
* Content: [Set the mobile device management authority - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/mdm-authority-set)
* Content Source: [memdocs/intune/fundamentals/mdm-authority-set.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/mdm-authority-set.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with pm...

**Comment by ErikjeMS** [comment]
@LuckyDucky583 Here's the response from the PM:
The orange banner does not show up if you don't set it.
The 1911 service update changed how MDM authority is set for new tenants. For 1911 and later, new tenants are set to MDM authority = Intune automatically. So the orange banner doesn't appear.
For pre-1911 tenants, the orange banner still appears for new tenants.

I'll update the doc to reflect this new behavior.

To change the MDM authority you have to contact support and request it. Upon changing the MDM authority, all devices will be lost, etc. Such a change is usually only done when switching from SCCM to Intune as a one-time operation.

Thanks!
