### ISSUE TITLE
Clarify maintenance window vs. service window

### ISSUE THREAD

**Issue by Hastur77** [MicrosoftDocs/memdocs#464]
> - Updates you install at the central administration site automatically install at child primary sites. Control this timing by using a maintenance window at the primary site.

The timing of a site update on child primary site is not controlled by a maintenance window, according to [Service Windows](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/manage/service-windows) it's controlled by a service window configured in the site properties.

[Maintenance windows](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/collections/use-maintenance-windows) are used to control the timing of software (update) deployments and are configured in the collection properties.

This is misleading and should be clarified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1bc3f2a-edf6-24e0-4f45-86dc75717572
* Version Independent ID: 2789eb96-6e74-71c0-9c57-65be3d7d802c
* Content: [Updates and servicing - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/manage/updates#bkmk_Baselines)
* Content Source: [memdocs/configmgr/core/servers/manage/updates.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/manage/updates.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
@Hastur77 thanks for noticing that. One of our field engineers,@jpcast88, fixed this for you. It should update in a day or so. Thanks both of you!
