### ISSUE TITLE
No Google Play in China 

### ISSUE THREAD

**Issue by Eddieyc** [MicrosoftDocs/memdocs#469]
[Enter feedback here]
what about the Android devices in China without Google Play? How do we handle those devices?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9f750b6-7e0f-bd67-69b5-44f081f2afd6
* Version Independent ID: 8b3ba988-1184-82be-f35e-d161a199a305
* Content: [Connect your Intune account to your Managed Google Play account. - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/connect-intune-android-enterprise)
* Content Source: [memdocs/intune/enrollment/connect-intune-android-enterprise.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/connect-intune-android-enterprise.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
7671001

**Comment by ErikjeMS** [comment]
@Eddieyc Here's the response from the PM:
Android Enterprise is not available in China. Check [here ](https://support.google.com/work/android/answer/6270910?hl=en) for more information on Android Enterprise support by country.

For more information on using Intune in China, see [How to use Intune in environments without Google Mobile Services](https://docs.microsoft.com/en-us/mem/intune/apps/manage-without-gms).

Let me know if you need more info. Thanks!

**Comment by Eddieyc** [comment]
Thanks Team, this is useful!

Best Regards,

Eddie Chui
Solution Specialist – Modern Workpalce
Digital Sales

Office(HK)       : +852 37038104
Office(Sydney): +61 (2) 98703083
eddie.chui@microsoft.com<mailto:eddie.chui@microsoft.com>
