### ISSUE TITLE
Device enrollment options for iOS/Android

### ISSUE THREAD

**Issue by aaronjcouch** [MicrosoftDocs/memdocs#47]
Glad to see the addition of the Device enrollment setting options (Available with/without prompts, and Unavailable) for the Company Portal on iOS and Android.  Is there no way to configure a unique setting for each OS?  My organization prefers a different preference for iOS vs. Android. 
If it's possible to split the option by OS in the future, that would be quite useful.  Thanks! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40ee2465-52c8-8fd0-ece0-c2dc498d025f
* Version Independent ID: 02b42d75-b82e-acb5-3457-7ecd3c45326f
* Content: [How to customize the Intune Company Portal apps, Company Portal website, and Intune app - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/company-portal-app#feedback)
* Content Source: [memdocs/intune/apps/company-portal-app.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/company-portal-app.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by aaronjcouch** [comment]
Any feedback on this?

**Comment by Erikre** [comment]
@aaronjcouch - Thanks for the feedback. I have forwarded your request to the product team. If you have additional questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

**Comment by Erikre** [comment]
@aaronjcouch - The product team has the following feedback:
With the 2004 release, we added group targeting support to the Customization blade, so you can now target this setting to user groups. See the following:
https://docs.microsoft.com/mem/intune/fundamentals/whats-new#group-targeting-support-for-customization-pane

**Comment by aaronjcouch** [comment]
@Erikre - I appreciate the new information regarding user groups targeting, however this does not help with the scenario I'm looking to address with iOS vs. Android Comp Portal customization.
