### ISSUE TITLE
Missing URLS for Asset Intelligence Point

### ISSUE THREAD

**Issue by CraigTolley** [MicrosoftDocs/memdocs#470]
This page does not include any information on the URLs required for the Asset Intelligence Point. I have found that the url sc.microsoft.com is required. Could we get this information added?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a9e88a5-bc7d-4982-4564-ceea80bde0e7
* Version Independent ID: 817824fe-5b44-ebeb-75c4-9eeb2dfa13ce
* Content: [Internet access requirements - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/network/internet-endpoints#bkmk_aip)
* Content Source: [memdocs/configmgr/core/plan-design/network/internet-endpoints.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/network/internet-endpoints.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @CraigTolley for the feedback. Let me check with the engineering team if they can confirm and provide any other required endpoints.

**Comment by aczechowski** [comment]
I confirmed there are actually two endpoints for the current version of the service:

- https://sc.microsoft.com
- https://ssu2.manage.microsoft.com

I'll look into adding these soon.

I'll make a note here for myself, should probably also be explicit in this article that generally go.microsoft.com and aka.ms are both broadly used and should always be allowed.

**Comment by aczechowski** [comment]
I have a change in for this. It should publish live tomorrow morning by 11 Pacific.
