### ISSUE TITLE
Deploy hybrid Azure AD-joined devices by using Intune and Windows Autopilot - Now Supports VPN Clients

### ISSUE THREAD

**Issue by ajp999** [MicrosoftDocs/memdocs#472]
The prerequisites need to be updated to reflect that VPN clients are now supported in the hybrid Azure AD-joined device scenario meaning that line of sight to the domain controller is no longer required assuming that the option "Skip AD connectivity check (preview)" is enabled as part of the Windows Autopilot Deployment Profile.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a94c428-95df-632b-46e8-4386ad551a03
* Version Independent ID: f23998f0-52ff-1203-1a0c-ff5c25b08c1c
* Content: [Enrollment for hybrid Azure AD-joined devices - Windows Autopilot](https://docs.microsoft.com/en-us/mem/intune/enrollment/windows-autopilot-hybrid)
* Content Source: [memdocs/intune/enrollment/windows-autopilot-hybrid.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/windows-autopilot-hybrid.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
7671065

**Comment by ErikjeMS** [comment]
@ajp999 The PM confirms the VPN notation is no longer required. I'll delete that sentence from the bullet. You should see the change on Monday afternoon. Thanks!
