### ISSUE TITLE
Wrong description for "Block user control over installations."

### ISSUE THREAD

**Issue by DaravuthL** [MicrosoftDocs/memdocs#474]
On this page, the description for Application Management -> **Block** user control over installations
seems to be copied from a GPO called "**Allow** user control over installs".
One being allow, the other block. Therefore the behavior of the setting in Intune doesn't work as expected.

I found that page [Windows 10 (and newer) device settings to allow or restrict features using Intune](https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-windows-10#:~:text=User%20control%20over%20installations%3A%20Block,change%20or%20update%20this%20setting) contains a correct description.

Note that the CSP it refers ApplicationManagement/MSIAllowUserControlOverInstall is MSIAllow, and thus correct with the behaviour description of the CSP setting.

Maybe the Item label should be changed or the description should be changed (both in Doc and in Intune)
Dara

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f0f4d5d-fdd1-22e7-6372-9916b199209f
* Version Independent ID: caeb9f8b-30ad-7f02-4740-56522b2f9b1b
* Content: [Intune security baselines settings for Windows 10 MDM - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/security-baseline-settings-mdm-all)
* Content Source: [memdocs/intune/protect/security-baseline-settings-mdm-all.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/security-baseline-settings-mdm-all.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@DaravuthL   Thanks for this feedback on some content that needs fixing. I've submitted that fix and content should update by Tuesday morning to fix this in the docs.
