### ISSUE TITLE
Docs are inaccurate

### ISSUE THREAD

**Issue by PJMarcum** [MicrosoftDocs/memdocs#475]
Step 2. Use your key to download a token from Apple. substeps 6-8 are not required to get the token and you don't explain how to download the token. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd130267-c54b-41e3-d534-831d4a86bae6
* Version Independent ID: bdfa7eca-a356-3dde-7643-9a759f952007
* Content: [Enroll iOS/iPadOS devices - Automated Device Enrollment - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-ios)
* Content Source: [memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
7671146

**Comment by ErikjeMS** [comment]
Repinged PM...

**Comment by MandiOhlinger** [comment]
@PJMarcum Thank you. We updated these steps. Changes should be live later today.
