### ISSUE TITLE
Remove old/undocumented screenshot

### ISSUE THREAD

**Issue by mattvlas** [MicrosoftDocs/memdocs#477]
Hello,

Thanks for the recent documentation updates.  It appears that a screenshot is still floating in the documentation that is no longer relevant.  

Can you please remove the attached image from the documentation at your earliest convenience? Thanks!

![sync-group-name](https://user-images.githubusercontent.com/57152570/86825392-26d4a280-c044-11ea-9e9f-1bb0e727b53d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10505488-ac2b-affc-a54d-40ae274eb120
* Version Independent ID: 65fe0f8b-33e9-afdb-87ed-5257667a0224
* Content: [Set up Wandera Mobile Threat Protection integration with Intune - Intune on Azure](https://docs.microsoft.com/en-us/mem/intune/protect/wandera-mtd-connector-integration)
* Content Source: [memdocs/intune/protect/wandera-mtd-connector-integration.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/wandera-mtd-connector-integration.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@mattvlas  I've submitted the edit to remove the image. That should update by Tuesday afternoon.  With the PR submitted for that change, I'll close out this Issue. Thanks!
