### ISSUE TITLE
Contradictory Information in the Docs

### ISSUE THREAD

**Issue by emmanuelrd** [MicrosoftDocs/memdocs#478]
The "Deploy Edge" document contains contradictory information.

Under **Microsoft Edge Management dashboard**, the inventory class **Browser Usage (SMS_BrowserUsage)** is listed as a prerequisite for the dashboards.

Later in the doc under **Known Issues**, hardware inventory may fail to process is listed as an issue and the recommended mitigation is to disable the **Browser Usage (SMS_BrowerUsage)** hardware inventory class since this class isn't currently leveraged.

So, is this inventory class needed or not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1b08c59-efa1-088a-b7d1-0e67e1f19281
* Version Independent ID: 60612563-0056-bdad-b145-c5c934c0cc1c
* Content: [Deploy and update Microsoft Edge, version 77 and later - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/apps/deploy-use/deploy-edge#bkmk_edge-dash)
* Content Source: [memdocs/configmgr/apps/deploy-use/deploy-edge.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/apps/deploy-use/deploy-edge.md)
* Product: **configuration-manager**
* Technology: **configmgr-app**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
@emmanuelrd  So this is one of those issues that *might* happen in specific circumstances when you have [endpoint analytics](https://docs.microsoft.com/mem/analytics/overview) enabled and the SMS_BrowserUsage class enabled. This issue will probably be fixed relatively soon according to the [tweet from the director of engineering for CM](https://twitter.com/djammmer/status/1278967003634515968).  
I'm tweaking the wording of the known issue on the Edge article to remove that the class isn't leveraged. It's not leveraged by endpoint analytics, but the dashboard will use it.
