### ISSUE TITLE
What's the scope of the "admin" in this article?

### ISSUE THREAD

**Issue by FRoZenGuo** [MicrosoftDocs/memdocs#480]
Is the "admin" here for Intune administrator (AAD role) only or all the roles within Intune?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04418415-45d5-1775-ece7-94da93d6ab2f
* Version Independent ID: 483b6c54-8ec4-2842-bee8-8610fe97b677
* Content: [Unlicensed admins in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/unlicensed-admins)
* Content Source: [memdocs/intune/fundamentals/unlicensed-admins.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/unlicensed-admins.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
7671366

**Comment by ErikjeMS** [comment]
Repinged PM...

**Comment by ErikjeMS** [comment]
Repinged pm...

**Comment by MandiOhlinger** [comment]
@FRoZenGuo It applies to any administrator in any role. We updated the article so this information is more clear. Changes should be live later today.
