### ISSUE TITLE
Not up to date - enrollment restriction can be tagged

### ISSUE THREAD

**Issue by aseflova** [MicrosoftDocs/memdocs#481]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37f4d965-ae4c-c1d4-3318-4c4827324555
* Version Independent ID: 5e33c778-0522-da5b-e8c8-bfac4784ba84
* Content: [Use role-based access control (RBAC) and scope tags for distributed IT in Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/scope-tags)
* Content Source: [memdocs/intune/fundamentals/scope-tags.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/scope-tags.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@aseflova Thanks! I'll remove that bullet today.
