### ISSUE TITLE
Missing "Check Conditional Acces Compliance"

### ISSUE THREAD

**Issue by LUatWork** [MicrosoftDocs/memdocs#485]
Client Notification sub-menu description - missing explanation of item: "Check Conditional Acces Compliance".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 971935f4-ea20-555f-e232-4c496a498e86
* Version Independent ID: b8868418-6d27-9526-364b-bbb4a756a812
* Content: [Client notification - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/client-notification)
* Content Source: [memdocs/configmgr/core/clients/manage/client-notification.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/client-notification.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @LUatWork, I removed that option from the docs when the support for that functionality was removed last year as part of the hybrid end of service. For more information, see [Deprecated features](https://docs.microsoft.com/mem/configmgr/core/plan-design/changes/deprecated/removed-and-deprecated-cmfeatures#unsupported-and-removed-features). While the option is still in the product, it shouldn't do anything. You could file a frown in the console to suggest the engineering team remove the option.
