### ISSUE TITLE
Better documentation on Updates

### ISSUE THREAD

**Issue by schnabel45** [MicrosoftDocs/memdocs#489]
Under the section "Upload an Apple VPP or location token" there's decent documentation on Automatic app updates for anyone who has it enabled, but I cannot find documentation for what happens if you have it disabled. Are all updates just blocked indefinitely until I enable it? Can I push updates from the Admin Portal if automatic updates are disabled? Can I apply this policy on an per-app basis? I have so many questions about this functionality and I cannot tell if the documents are lacking, the Intune feature set is lacking, or both.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6be83bf7-b364-60e3-1b4f-97bbde969ada
* Version Independent ID: 02a2bedd-1af7-3a14-7314-11e0853e4c98
* Content: [Manage Apple volume-purchased apps - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/vpp-apps-ios)
* Content Source: [memdocs/intune/apps/vpp-apps-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/vpp-apps-ios.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
We have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. If you have continue to have questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

Please use the above channels if you don't already have a solution.
