### ISSUE TITLE
Android Enterprise terminology

### ISSUE THREAD

**Issue by Leon1983** [MicrosoftDocs/memdocs#49]
Hi,

Only a small correction required here but I feel you should not be referring to "COBO" any more, especially as the correct terminology of "Fully Managed" is mentioned in the following paragraph https://docs.microsoft.com/en-us/mem/intune/fundamentals/in-development#derived-credentials-support-on-android-cobo-devices

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66f915d1-8486-44dc-a605-280f979d6f9b
* Version Independent ID: 23c6b2c3-64c1-2df3-ad51-d9be083871a1
* Content: [In development - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/in-development)
* Content Source: [memdocs/intune/fundamentals/in-development.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/in-development.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@Leon1983 I'll fix it. Thanks!
