### ISSUE TITLE
The page on changing group policy didn't work for me

### ISSUE THREAD

**Issue by ManuelaJL** [MicrosoftDocs/memdocs#491]
Hello. I followed your instructions but there were some problems:

Under Administrative tools, there was no "Edit Group policy"
I used this to find it instead: https://www.isunshare.com/windows-10/5-ways-to-access-local-group-policy-editor-on-windows-10.html
(In my case the "Turn off Windows Defender Antivirus" is already set to "Not Configured", so nothing to do here.)

I get no results when I search for "Windows Defender Security Center". Clicked "Windows Security" instead. Clicked "Virus & threat protection"
There are no options for "Real-time protection" and "Cloud protection" there. The links are "open app" (doesn't work! Does nothing) and Windows Defender Options. There I can turn Periodic Scanning on, it asks for administrator permissions, and then the switch goes right back to off.

Under Local Group Policy editor Computer Configuration > Administrative Templates > Windows Components there is no "Windows Defender Security Center"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76b07dd3-8f84-c715-76f5-c22c2a98b5f3
* Version Independent ID: b212305e-9b54-f6cd-81bd-f23254f6891a
* Content: [Turn on Windows Defender](https://docs.microsoft.com/en-us/mem/intune/user-help/turn-on-defender-windows)
* Content Source: [memdocs/intune/user-help/turn-on-defender-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/user-help/turn-on-defender-windows.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @ManuelaJL, thank you for sharing what you experienced. This article is now up-to-date thanks to contributions from the community. Closing as there is not further action. Have a good one!
