### ISSUE TITLE
Option to enable "Automatically adjust active hours for this device based on activity"

### ISSUE THREAD

**Issue by SteffanH** [MicrosoftDocs/memdocs#492]
Since this is the way you can set the  'fixed' "Active Hours", I was hoping this also allowed the policy setting to Automatically adjust active hours for this device based on activity that was introduced in the April 2019 release.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401fe085-6254-6dbb-24c6-7e6fe56d0f3a
* Version Independent ID: 774ae4fb-b28e-1fb3-46d9-5802c0e4ac6c
* Content: [Windows for Business Update settings for  Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/windows-update-settings)
* Content Source: [memdocs/intune/protect/windows-update-settings.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/windows-update-settings.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@SteffanH    Currently, Intune doesn't have any options to manage settings for enabling devices to manage their own Active Hours, or to scoop that up for each devices.  While this isn’t something Intune does today, it might be worth requesting as a future enhancement, which you can do via the Intune UserVoice channel: https://microsoftintune.uservoice.com/forums/291681-ideas
