### ISSUE TITLE
Control the HomePage settings

### ISSUE THREAD

**Issue by alventech** [MicrosoftDocs/memdocs#493]
[With the “Old” Intune managed Browser and “com.microsoft.intune.mam.managedbrowser.homepage“ default HomePage. The HomePage added would automatically open the HomePage Specified , when the browser started. With the new Edge Browser this functionality is not possible. Any RoadMap to give this functionality back in EDGE?]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a31e5a24-4f06-9e36-eacb-689bed95cd59
* Version Independent ID: ede9248e-1114-3e1a-9e80-34e5fe547707
* Content: [Manage Edge for iOS and Android with Intune](https://docs.microsoft.com/en-us/mem/intune/apps/manage-microsoft-edge)
* Content Source: [memdocs/intune/apps/manage-microsoft-edge.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/manage-microsoft-edge.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
We have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. If you have continue to have questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

Please use the above channels if you don't already have a solution.
