### ISSUE TITLE
CFRMGR

### ISSUE THREAD

**Issue by Deni-eng-27** [MicrosoftDocs/memdocs#494]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8298c96c-4449-7066-a2a7-2623f8be8016
* Version Independent ID: d43800ff-eae7-1c77-5972-efc027d304d9
* Content: [Configure role-based administration - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/configure-role-based-administration)
* Content Source: [memdocs/configmgr/core/servers/deploy/configure/configure-role-based-administration.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/deploy/configure/configure-role-based-administration.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
I'm assuming this is a mistake, so I'm closing it. If you have feedback on this article, please reopen and edit the original comment, or file a new isue.
