### ISSUE TITLE
XML?  ...or JSON?

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/memdocs#495]
Hello, can you please confirm that where it says "Enter XML" throughout this page - is that just old information which is now superseded with "Enter JSON"?  It's completely different than what I see in the product today, and I'm new enough to Intune that I hadn't ever seen the XML version of the past - so I really don't know the answer here.  I assume the page is just out of date, even though it was updated as recently as a few days ago.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee33d638-3024-87d5-1b02-c4568478d1ce
* Version Independent ID: fe0f2aa3-b2dc-486a-4883-9c25ee361fe8
* Content: [Add app configuration policies for managed iOS/iPadOS devices - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-configuration-policies-use-ios)
* Content Source: [memdocs/intune/apps/app-configuration-policies-use-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-configuration-policies-use-ios.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@JeremyTBradshaw - The topic is up-to-date. You must enter XML. Please make sure you are using the Microsoft Endpoint Manager admin console. You can following the details in the [Create an app configuration policy](https://docs.microsoft.com/mem/intune/apps/app-configuration-policies-use-ios#create-an-app-configuration-policy) section of the doc.

**Comment by JeremyTBradshaw** [comment]
@Erikre thanks for that.  I had just been in to Endpoint Manager today and saw the JSON input area, so when saw your reply had to do a double take.  What happened is that I was thinking of App Configuration policies for Android (like here https://docs.microsoft.com/en-us/mem/intune/apps/app-configuration-policies-use-android), where it takes JSON instead of XML.

Looking back I can't remember if I was thinking I was reading the other page, or assuming both policy types we're the same.  In any case, thanks and good to know for certain regardless I guess.
