### ISSUE TITLE
Missing configuration from documentation.

### ISSUE THREAD

**Issue by JST1MOteKILLya** [MicrosoftDocs/memdocs#496]
Windows health monitoring information is missing from this article.  Unable to find what this configuration does or what Windows 10 versions it impacts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d8832b0-265d-5c37-9f9d-4adbaa8202de
* Version Independent ID: 48c4745d-166e-01a6-0f29-8bfc2a86d07a
* Content: [Create device profiles in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/device-profile-create)
* Content Source: [memdocs/intune/configuration/device-profile-create.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/device-profile-create.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@JST1MOteKILLya Good question. It'll be a few days, but this article will be updated.

**Comment by MandiOhlinger** [comment]
@JST1MOteKILLya Just an FYI, the Windows Health Monitoring profile doc is included in the 2011 release. So, you should see it in the near future.
