### ISSUE TITLE
Clarification on "manage PCs"

### ISSUE THREAD

**Issue by GenerAhl** [MicrosoftDocs/memdocs#5]
You might want to consider clarifying that the
"You might need to keep the Intune Service Administrator access in the classic portal if your admins still need access to manage PCs using Intune." is refering to PCs with the Intune Agent installed rather than MDM enrolled.
Administrators are "managing PCs" even using MDM.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3eaa886-918b-127e-ad4b-d829e99b0d44
* Version Independent ID: 87240468-dd25-7f45-740b-f078cd5deac7
* Content: [Role-based access control (RBAC) with Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/role-based-access-control#feedback)
* Content Source: [memdocs/intune/fundamentals/role-based-access-control.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/role-based-access-control.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
(6488416)

**Comment by ErikjeMS** [comment]
@GenerAhl Legacy will soon be deprecated. Therefore, to avoid confusion, I'll remove this section. Thanks!
