### ISSUE TITLE
Incorrect terminology for DEP

### ISSUE THREAD

**Issue by Leon1983** [MicrosoftDocs/memdocs#50]
Hi,

As announced in the Autumn, DEP is now called "Automated Device Enrolment" so this page needs an overhaul https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-ios

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd130267-c54b-41e3-d534-831d4a86bae6
* Version Independent ID: bdfa7eca-a356-3dde-7643-9a759f952007
* Content: [Enroll iOS/iPadOS devices - Device Enrollment Program - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-ios)
* Content Source: [memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
(6199678)

**Comment by Leon1983** [comment]
Hi I can see this has been closed, was there an update on it?

**Comment by ErikjeMS** [comment]
@Leon1983 I've started overhauling the doc. Changes should go live today. Thanks!
