### ISSUE TITLE
test.stats.update.microsoft.com doesn't seem to exist

### ISSUE THREAD

**Issue by MichielOverweel** [MicrosoftDocs/memdocs#501]
The URL "http://test.stats.update.microsoft.com" doesn't seem to exist (anymore). The IP address for the host name "test.stats.update.microsoft.com" doesn't resolve. Is this endpoint still required? Customers are worried that they are whitelisting URL's unnecessarily, and they need reassurance that the list of endpoints is validated on a regular basis.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a9e88a5-bc7d-4982-4564-ceea80bde0e7
* Version Independent ID: 817824fe-5b44-ebeb-75c4-9eeb2dfa13ce
* Content: [Internet access requirements - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/network/internet-endpoints#bkmk_sum)
* Content Source: [memdocs/configmgr/core/plan-design/network/internet-endpoints.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/network/internet-endpoints.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @MichielOverweel for the feedback. That endpoint doesn't resolve for me either, so I assume we can remove it. However, since there's a long list of endpoints there, I'm checking with the engineering team to validate them all for software updates.

**Comment by aczechowski** [comment]
I'm making a change to remove test.stats.update.microsoft.com. The change will publish live with the 2006 current branch content in the near future.
