### ISSUE TITLE
URL not working

### ISSUE THREAD

**Issue by BurgerhoutJ** [MicrosoftDocs/memdocs#502]
Under the Device Security section, the second bullet (App Bundle ID) is a website mentioned and linked. But the link will result in an error 404 page.
Please fix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30e5c360-263e-fd7b-1f45-9334e647e0ef
* Version Independent ID: cb245be4-6704-8b05-630f-f40e63d091eb
* Content: [iOS/iPadOS device compliance settings in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/compliance-policy-create-ios)
* Content Source: [memdocs/intune/protect/compliance-policy-create-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/compliance-policy-create-ios.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@BurgerhoutJ  Thanks for the heads up on the failed page. It appears that support article is no longer available. As such, I've revised the Intune article (which will update in the next day or so) with new guidance.  To find the bundle ID for common iOS or iPadOS apps, see [Bundle IDs for native iOS and iPadOS apps](https://support.apple.com/guide/mdm/native-ios-and-ipados-app-bundle-ids-mdm90f60c1ce/web) at Support.apple.com, or contact the software vendor of the app.
