### ISSUE TITLE
Number of sign in falures before wiping

### ISSUE THREAD

**Issue by nashuatek** [MicrosoftDocs/memdocs#506]
"Number of sign-in failures before wiping device: Enter the number of failed sign-ins before the device is wiped, from 4-11."

On the current Intune/Endpoint Management portal, this setting allows values between 2-11, can you confirm which is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88932dd8-abce-bf23-9624-1df5f60a946d
* Version Independent ID: ab2d932f-e375-2485-a6e5-e02daf7a27c4
* Content: [iOS/iPadOS device settings in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-ios)
* Content Source: [memdocs/intune/configuration/device-restrictions-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/device-restrictions-ios.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by jpcast88** [comment]
@nashuatek Seems as the docs are correct, but logic in the portal allows for a value of 2-11 to be entered during profile creation. For example, In my tenant I'm able to enter a value between 2-11 when specifying this setting, but the profile errors out when being created.
![image](https://user-images.githubusercontent.com/26827823/87592103-01b7e380-c685-11ea-8075-82a9a7951d5d.png)
![image](https://user-images.githubusercontent.com/26827823/87592197-2d3ace00-c685-11ea-98ed-368b0d3acb44.png)

**Comment by MandiOhlinger** [comment]
@nashuatek The documentation is correct. If you enter a value of '2' or '3', the profile fails to save. This behavior is being investigated internally; no ETA.

In the meantime, enter a value between 4-11.
