### ISSUE TITLE
Content Issue

### ISSUE THREAD

**Issue by stighe258** [MicrosoftDocs/memdocs#509]
I have implemented the code from the SDK on how to create an Application. I have substituted the notepad.exe for another exe. I am trying to duplicate what I can do manually in code but am unable to get the contents to be displayed: The screenshot to the left is the code from the sdk and the right is created manually. How did I fix this?
![image](https://user-images.githubusercontent.com/58857508/87579576-22436600-c6a4-11ea-903f-e9006281df0f.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fac5c51f-a86a-bfdf-356b-bac379a9a025
* Version Independent ID: 8ab1d160-12ba-4e38-b346-ca22fd089b64
* Content: [How to Create an Application with the Script Deployment Type - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/develop/apps/how-to-create-an-application-with-the-script-deployment-type)
* Content Source: [memdocs/configmgr/develop/apps/how-to-create-an-application-with-the-script-deployment-type.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/develop/apps/how-to-create-an-application-with-the-script-deployment-type.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @stighe258 for the feedback. The ConfigMgr SDK content hasn't changed in a long time, and it's an area in which we're not actively investing beyond basic maintenance and some new functionality.

 I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
