### ISSUE TITLE
BITS

### ISSUE THREAD

**Issue by nhogarth86** [MicrosoftDocs/memdocs#51]
I think the BITS section should be updates as it refers to configuring settings using the legacy Intune PC client (Intune agent policy) and also points to an older Technet page that is redirected to Docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c9c8322-fc0c-8e97-170d-e881e77889b9
* Version Independent ID: c924f234-8c65-b47d-1838-70c406cbdda9
* Content: [Network requirements and bandwidth details for Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/network-bandwidth-use#use-background-intelligent-transfer-service-bits-on-computers)
* Content Source: [memdocs/intune/fundamentals/network-bandwidth-use.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/network-bandwidth-use.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
(6607283)

**Comment by ErikjeMS** [comment]
@nhogarth86 I'll update the article to make it clear that BITS and BranchCache only work with Intune software client. Thanks!
