### ISSUE TITLE
Starting in version 2002, MECM Setup can create the database on a SQL Always On group

### ISSUE THREAD

**Issue by YvanMECM** [MicrosoftDocs/memdocs#512]
[Enter feedback here]
Changes for site Always on Setup
If availability group is functional, use the listener  sql name to setup MECM 2002.

Starting in version 2002, MECM Setup can create the database on a SQL Always On group. 

I

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 733080f2-5a95-e2c3-d4bf-dcb8fc35c2ed
* Version Independent ID: e4b6a579-98f3-5710-8acf-2c002b2628b6
* Content: [What's new in version 2002 - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/changes/whats-new-in-version-2002)
* Content Source: [memdocs/configmgr/core/plan-design/changes/whats-new-in-version-2002.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/changes/whats-new-in-version-2002.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @YvanMECM, that feature isn't new. I think what you're referring to was added in [version 1906](https://docs.microsoft.com/mem/configmgr/core/plan-design/changes/whats-new-in-version-1906#improvements-to-support-for-sql-always-on)
