### ISSUE TITLE
Bulk Enroll - Conditional Access

### ISSUE THREAD

**Issue by tp-g** [MicrosoftDocs/memdocs#516]
Numerous Microsoft articles state that when a device is bulk enrolled conditional access is not supported.

"Bulk enroll lets an authorized user join large numbers of new corporate-owned devices to Azure Active Directory and Intune. You create a provisioning package with the Windows Configuration Designer (WCD) app. Then, using USB media during initial Windows OOBE experience or from existing Windows PC, you install the provisioning package to automatically enroll the devices into Intune. This method does not allow the use of Conditional Access."

However the following documentation contradicts this information.
https://docs.microsoft.com/en-us/mem/intune/protect/troubleshoot-conditional-access

"Surface Hub, Bulk-Enrolled, and DEM enrolled Windows devices can support conditional access when a user who is assigned a license for Intune is signed in. However, you must deploy the compliance policy to device groups (not user groups) for correct evaluation."

Which information is correct, and if conditional access is supported on bulk enrolled devices is it dependant on a specific version of Windows and are the limitations listed above correct?

Also if a device has been bulk enrolled and conditional access is not supported what is the process to re-enroll the device?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94be1fd9-9f63-bfa2-b658-fec1c485299b
* Version Independent ID: d7b22857-059d-22ad-116f-c09517bdd61c
* Content: [Intune enrollment methods for Windows devices - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/windows-enrollment-methods)
* Content Source: [memdocs/intune/enrollment/windows-enrollment-methods.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/windows-enrollment-methods.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
7741099

**Comment by ErikjeMS** [comment]
The documentation team hasn’t been able to find an answer for this issue. If this is still an issue for you can try any of the following: 
- Open a support ticket by following the steps here: [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support). 
- Post on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.   
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.   
 I'm closing this issue as there's nothing actionable for docs at this time.
