### ISSUE TITLE
Microsoft Security Baselines change the requirements...

### ISSUE THREAD

**Issue by jones948** [MicrosoftDocs/memdocs#519]
If the workstation has the Microsoft Security Baselines applied, the local security policy item, "Access this computer from the network", is changed from the default of "Administrators,Backup Operators,Users,Everyone" to "Administrators; Remote Desktop Users".

Remote Control authentications are then denied unless the user is in "Administrators; Remote Desktop Users". It would be good to note this is a side effect of the baselines, or at least that "Access this computer from the network" is a requirement as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1353b374-cf89-dcd0-6975-8c2d3cbf8a5b
* Version Independent ID: 2842d2cb-42dc-ad27-9eaf-ebd35b4a7497
* Content: [Remote control prerequisites - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/remote-control/prerequisites-for-remote-control)
* Content Source: [memdocs/configmgr/core/clients/manage/remote-control/prerequisites-for-remote-control.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/remote-control/prerequisites-for-remote-control.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @jones948, while I don't disagree, it's opening a can of worms to determine what possible group policies might have an impact on this feature, as well as the other features of the product. That's a level of detail that we're just not resourced to provide.

If you're passionate about including this note in this article, you're welcome to [make a contribution](https://docs.microsoft.com/mem/use-docs#contribute) for us to review and approve. 😉
