### ISSUE TITLE
old content

### ISSUE THREAD

**Issue by mictsi** [MicrosoftDocs/memdocs#52]
Can you please update this page as the information is not relevant

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0f883bc-4852-5d5c-9708-0f8878ff18b5
* Version Independent ID: 88d715fd-f8c2-ffe1-5451-a3ad6fae1730
* Content: [Add users and grant permissions - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/users-add#feedback)
* Content Source: [memdocs/intune/fundamentals/users-add.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/users-add.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Updates will go live tonight.
