### ISSUE TITLE
Office 365 MDM Affected?

### ISSUE THREAD

**Issue by Kazzan** [MicrosoftDocs/memdocs#520]
Seems that Office 365 MDM is also affected by Categories configured in Intune, correct? Even if users does not have license, they must choose device category. Is this correct behave? If yes, should be mentioned there. If not, should be please fixed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a205db9e-c21f-b505-b5e9-d54fe44ececb
* Version Independent ID: a85d08c2-8ef1-fcd4-52de-f74ea8f41124
* Content: [Categorize devices into groups in Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-group-mapping)
* Content Source: [memdocs/intune/enrollment/device-group-mapping.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/device-group-mapping.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@Kazzan The documentation team hasn’t been able to find an answer for this issue. If this is still an issue for you can try any of the following: 
- Open a support ticket by following the steps here: [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support). 
- Post on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.   
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.   
I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by Kazzan** [comment]
Hi, I contacted Intune Support Team in this matter. Is not fortunate that documentation team cannot contact product or development team to verify such itself.

**Comment by ErikjeMS** [comment]
@Kazzan I erroneously closed this recent issue while I was closing out some other very old issues. Sorry about that! I've sent an internal query to the product team to find out if they have the answer.

**Comment by ErikjeMS** [comment]
@Kazzan Looks like you're working with support on this one. I'm going to close this issue.

**Comment by Kazzan** [comment]
I worked. They just send me statement that they will investigate with PG, but currently close as product limitation. And yes, Intune categories also apply to Office 365 or how it is now called. Unfortunately.
