### ISSUE TITLE
Control certificate to be non-exportable?

### ISSUE THREAD

**Issue by actionxp** [MicrosoftDocs/memdocs#521]
[Enter feedback here]
If we upload the PFX certificate to Intune via Graph API, and then create a “PKCS imported certificate” profile to push the cert to user mobile device. Can we set the certificate to be non-exportable when deploying it into the mobile device from Intune? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa43fc11-ff6b-20c8-5bfa-a89572295223
* Version Independent ID: ea0f43b6-5c74-6f9e-7e0c-ec86db3e4400
* Content: [Use imported PFX certificates in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/certificates-imported-pfx-configure)
* Content Source: [memdocs/intune/protect/certificates-imported-pfx-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certificates-imported-pfx-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@actionxp  Thanks for the question. While Intune deploys the imported certificate, Intune doesn’t edit nor alter the certificate, and doesn’t support a way to manage settings for the certificate like its exportability during deployment. That configuration should be introduced to the certificate outside of Intune.
