### ISSUE TITLE
Azure AD enterprise application

### ISSUE THREAD

**Issue by bleek00** [MicrosoftDocs/memdocs#522]
Does the options to show "Azure AD Enterprise Applications" and "Office Online Applications" in company portal refers to the desktop version of company portal or the website at "https://portal.manage.microsoft.com/"

It is enable on my tenant but the desktop version only shows intune apps, none Azure AD or 365 apps. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40ee2465-52c8-8fd0-ece0-c2dc498d025f
* Version Independent ID: 02b42d75-b82e-acb5-3457-7ecd3c45326f
* Content: [How to customize the Intune Company Portal apps, Company Portal website, and Intune app - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/company-portal-app#company-portal-customization)
* Content Source: [memdocs/intune/apps/company-portal-app.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/company-portal-app.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@bleek00 - Thanks for the feedback. The display of apps from other Microsoft services is only supported in the Windows Company Portal and the Company Portal website. The docs now have a note with this information.
