### ISSUE TITLE
Add details on creating policy to assign to particular devices rather than whole tenant

### ISSUE THREAD

**Issue by hoyty76** [MicrosoftDocs/memdocs#524]
I think details on setting up a configuration policy to apply WHfB to only particular devices rather than all users / devices. Describe setting up an Identity profile policy and apply to only certain users.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6d32682-0e4e-449b-6ad5-001c631735d2
* Version Independent ID: 66419be7-51dc-f5e1-cf18-1a55866e4193
* Content: [Integrate Windows Hello for Business with Microsoft Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/windows-hello#create-a-windows-hello-for-business-policy)
* Content Source: [memdocs/intune/protect/windows-hello.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/windows-hello.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@hoyty76  While I'm not clear on what your question or ask is, I think you might be seeking information about using Windows Hello for Business via policy you can deploy  to users, devices, or both - place of a tenant wide setting?  If so, 
 see https://docs.microsoft.com/mem/intune/protect/windows-hello in the Intune documentation, and let me know if that's what you're seeking. 

The links between this and that article are not that clear, so I'll submit a revision to make it more evident.  
If there is something else you need or are seeking, please restate your question and I'll try to assist.
