### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jamesorlando** [MicrosoftDocs/memdocs#525]
The example of:

Invoke-RestMethod -Method 'Get' -Uri "https://SMSProviderFQDN/AdminService/wmi/SMS_Site" -UseDefaultCredentials` 

either needs the backtick ( ` ) removed or a space added. If you copy it as is you will get the following: 

Invoke-RestMethod : A parameter cannot be found that matches parameter name 'UseDefaultCredentials`'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4eed1add-4e7a-1103-2dcd-2f20c3dc6ad9
* Version Independent ID: 025e21a1-28ed-8a7c-422f-fa2293a65751
* Content: [How to use the admin service - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/develop/adminservice/usage)
* Content Source: [memdocs/configmgr/develop/adminservice/usage.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/develop/adminservice/usage.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @jamesorlando for catching that and filing the feedback! @jpcast88 made a private contribution to correct it, that change should publish live later this afternoon.

In the future, you might consider making the change yourself! 😉 For more information, see [How to contribute to docs](https://docs.microsoft.com/mem/configmgr/core/understand/use-docs#bkmk_contribute).
