### ISSUE TITLE
MP Replica Documentation Suggestions.

### ISSUE THREAD

**Issue by fmokren** [MicrosoftDocs/memdocs#527]
In step 1. To configure the site database server. 

Sub step #2. It's not always possible to create a local user group. If the SQL server is also a domain controller then only domain groups can be created. This comes into play in sub step #5.

Sub step #4. There is no **Write** permission on Share Permissions. There is only **Full Control**, **Change** and **Read**.

Sub step #5. If the user was forced to create a different group type (domain instead of local) or use a different group name then they can specify the correct group as a parameter to spCreateMPReplicaPublication.
  
   e.g. **EXEC spCreateMPReplicaPublication N'MyDomain\ConfigMgr_MPReplicaAccess'**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b73a94dc-ff33-6490-6d99-5fc8d3d62ad8
* Version Independent ID: 4b78696d-6b14-cd17-e714-be7bdaa331ed
* Content: [Management point database replicas - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/database-replicas-for-management-points)
* Content Source: [memdocs/configmgr/core/servers/deploy/configure/database-replicas-for-management-points.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/deploy/configure/database-replicas-for-management-points.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @fmokren for the feedback. I made changes to this article
