### ISSUE TITLE
Text in step 2 is slightly incorrect

### ISSUE THREAD

**Issue by John-Welch** [MicrosoftDocs/memdocs#528]
In step 2, this page says "Turn on BitLocker" but the product instruction is "Turn BitLocker on".

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b24a11cd-2a69-4dea-1153-7b769ab61101
* Version Independent ID: ed855316-fc81-7986-f02d-dd07baaee300
* Content: [How to protect your Windows device with encryption](https://docs.microsoft.com/en-gb/mem/intune/user-help/encrypt-your-device-windows)
* Content Source: [memdocs/intune/user-help/encrypt-your-device-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/user-help/encrypt-your-device-windows.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
HI @John-Welch, thank you for your contribution. The 2nd step in this article still appears to be accurate; I don't see the option to "Turn BitLocker on" in Manage BitLocker so I'm going to leave the article as-is. Closing as no further action is needed.
