### ISSUE TITLE
Headers for Android/Android Enterprise backwards

### ISSUE THREAD

**Issue by pamcdo** [MicrosoftDocs/memdocs#53]
Hey there,

It appears on this page that the settings under Android are actually for Android Enterprise, and the settings for Android Enterprise are actually for Android.

So basically, flipping the headers between the two sections would fix the issue.

Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91c6e4c4-96e2-14c6-8028-a2b947740e73
* Version Independent ID: 94bd0e7c-03c8-151d-6569-5d12985824e6
* Content: [Automatically enroll Android devices using Samsung's Knox Mobile Enrollment - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/android-samsung-knox-mobile-enroll#feedback)
* Content Source: [memdocs/intune/enrollment/android-samsung-knox-mobile-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/android-samsung-knox-mobile-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@pamcdo Thanks! I'll fix that.
