### ISSUE TITLE
CNG Certs Clarification

### ISSUE THREAD

**Issue by CJRicard** [MicrosoftDocs/memdocs#531]
The PKI example references using certs in a Server 2003, not 2008, compatibility mode.  We should provide better clarification and/or link to:  https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/network/cng-certificates-overview.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 174d8846-7eaa-9b3d-7822-77a7e89bd0d1
* Version Independent ID: fe152fd0-7a49-9214-f1ce-1e9eb25dbdae
* Content: [PKI certificate requirements - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/network/pki-certificate-requirements)
* Content Source: [memdocs/configmgr/core/plan-design/network/pki-certificate-requirements.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/network/pki-certificate-requirements.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @CJRicard for the feedback. We have an internal work item tracking a larger review and revision project for the ConfigMgr PKI articles. (Internal reference [user story 2841906](https://msazure.visualstudio.com/Configmgr/_workitems/edit/2841906)). @Brenduns FYI
