### ISSUE TITLE
Update Note under step 6 of creating an apple enrollment profile as shown here:

### ISSUE THREAD

**Issue by Big-J2404** [MicrosoftDocs/memdocs#533]
In the Note under step 6 of creating an apple enrollment profile as shown here:

 _Note

If you want do any of the following, set Select where users must authenticate to Company Portal._

_use multifactor authentication
prompt users who need to change their password when they first sign in
prompt users to reset their expired passwords during enrollment
These aren't supported when authenticating with Apple Setup Assistant._

The wording is confusing and can lead to misinterpretations. 

Recommended wording: 

If you want do any of the following:_

_use multifactor authentication
prompt users who need to change their password when they first sign in
prompt users to reset their expired passwords during enrollment

Set: Select where users must authenticate to Company Portal.

These aren't supported features when authenticating with Apple Setup Assistant._

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd130267-c54b-41e3-d534-831d4a86bae6
* Version Independent ID: bdfa7eca-a356-3dde-7643-9a759f952007
* Content: [Enroll iOS/iPadOS devices - Automated Device Enrollment - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-ios#create-an-apple-enrollment-profile)
* Content Source: [memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by MandiOhlinger** [comment]
@Big-J2404 You're right. We simplified the text to make it more clear. Changes should be live later today or tomorrow. 

In the future, it'd be great if you created a pull request (PR) for doc updates like this. We'd love the help. We review every PR before it's published live. Something to consider for next time. 

Thanks again.
