### ISSUE TITLE
How long does it take to re-offer application again?

### ISSUE THREAD

**Issue by ra-ful** [MicrosoftDocs/memdocs#535]
This site shows Intune will offer the app again after 24 hours if Intune detects the app is not present on the device.

>If Intune detects that the app is not present on the device, Intune will offer the app again after 24 hours. This will only occur for apps targeted with required intent.

I checked above behavior but it seems to offer again within 24 hours.
It about 6 hours.

What's does it mean about "Intune will offer the app again after 24 hours"?

Below step is my check process.
1. I made .Intunewin application that detection rule of the application is to check application folder.
2. Deploy the application with required.
3. Check the device install successfully.
4. I remove the application folder.
5. Sync device by using  Intune campany portal and Intune portal and I checked the application isn't install Immediately.
6. I checked the application is installed after 6 hours.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de85c97e-b22f-1b7d-0fb2-18e2c2b1970d
* Version Independent ID: 0744e16d-47f6-f1f4-0fbd-41074136e110
* Content: [Add and assign Win32 apps to Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-win32-app-management#troubleshoot-win32-app-issues)
* Content Source: [memdocs/intune/apps/apps-win32-app-management.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/apps-win32-app-management.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@ra-ful - Thanks for the feedback. I updated the topic from "Intune will offer the app again after 24 hours" to "Intune will offer the app again within approximately 24 hours". Thanks
