### ISSUE TITLE
Duplicate Apple VPP tokens

### ISSUE THREAD

**Issue by TheGinger71** [MicrosoftDocs/memdocs#538]
Checking to see if there is a simple solution to this update as we currently have 3 admins who are able to purchase and deploy applications.  All 3 are linked to our 1 token so now we are stuck. I am guessing we will need to delete 2 of the accounts and then have 3 distinct tokens, 1 for each admin? Has anyone else had this issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d16c28db-1e8e-31fa-6127-3050a2940422
* Version Independent ID: 4cf9a244-1ae5-1637-48f7-3f503d400da6
* Content: [What's new in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new)
* Content Source: [memdocs/intune/fundamentals/whats-new.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/whats-new.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by Erikre** [comment]
@TheGinger71 - Thanks for sharing this with the Intune documentation team. If you are still running into problems related to this issue, we want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

This question is in our documentation feedback channel and it may be best to handle this question as a support request. For this reason, I'm closing this issue. Please use the above channels if you don't already have a solution.
