### ISSUE TITLE
Override Touch ID with PIN after timeout - how exactly does this work?

### ISSUE THREAD

**Issue by NavishkarSadheo** [MicrosoftDocs/memdocs#539]
Dear MS

How exactly does this (Override Touch ID with PIN after timeout) work?

and why must the "Timeout (minutes of inactivity)" be greater than the "Recheck the access requirements after (minutes of inactivity)"??

I don't understand how these 2 affect other?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c81b9a99-a379-a3b6-0dde-8781da62d16a
* Version Independent ID: 33b4409f-9687-feb7-07ab-7d6bc0d8b9f5
* Content: [iOS/iPadOS app protection policy settings - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policy-settings-ios)
* Content Source: [memdocs/intune/apps/app-protection-policy-settings-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-protection-policy-settings-ios.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
To use this setting, select Require and then configure an inactivity timeout. Specify a time in minutes after which either a passcode or numeric (as configured) PIN will override the use of a fingerprint or face as method of access. This timeout value should be greater than the value specified under 'Recheck the access requirements after (minutes of inactivity)'. For **Recheck the access requirements after (minutes of inactivity)**, you must configure the number of minutes of inactivity that must pass before the app requires the user to again specify the access requirements.

For example, an admin turns on PIN and Blocks rooted devices in the policy, a user opens an Intune-managed app, must enter a PIN, and must be using the app on a non-rooted device. When using this setting, the user would not have to enter a PIN or undergo another root-detection check on any Intune-managed app for a period of time equal to the configured value.

Note: On iOS/iPadOS, the PIN is shared amongst all Intune-managed apps of the same publisher. The PIN timer for a specific PIN is reset once the app leaves the foreground on the device. The user wouldn't have to enter a PIN on any Intune-managed app that shares its PIN for the duration of the timeout defined in this setting. This policy setting format supports a positive whole number.

If you have additional questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

We have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. Please use the above channels if you don't already have a solution.
