### ISSUE TITLE
ADMX templates

### ISSUE THREAD

**Issue by suraj-soerdjbali** [MicrosoftDocs/memdocs#54]
This page needs to be updated since the ADMX templates in Intune are updated. It is no longer possible to choose Office or Edge as a ADMX template to configure certain features. Now you can only choose between Computer Configuration and User Configuration. Also some Office ADMX features that initially were usable such as Use-Files-On-Demand (OneDrive) cannot be configured. You need to ingest a separate ADMX file into Intune. The download link to Office 365ProPlus ADMX is not complete since OneDrive ADMX is missing. Please fix this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f187188e-9838-b9ca-fdde-9dd3cbd5ba00
* Version Independent ID: 75de9a7f-098b-58c6-279c-61e5f31efcc6
* Content: [Walkthrough - Create administrative template in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/tutorial-walkthrough-administrative-templates#feedback)
* Content Source: [memdocs/intune/configuration/tutorial-walkthrough-administrative-templates.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/tutorial-walkthrough-administrative-templates.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@suraj-soerdjbali Yes - we're aware this also needs updating. Thank you. The changes should be public sometime this week. As you've seen, the Intune UI is getting some updates, and will continue to be updated in the next couple of release cycles. I suspect what we see now in Admin Templates will get more tweaks.

You don't need to ingest a separate ADMX file. In the admin template, expand **Computer Configuration** > **All settings** > search for **Use OneDrive Files On-Demand**. I suspect you didn't select **All settings**, which is easy to miss.

![image](https://user-images.githubusercontent.com/3229224/77965398-ec25d600-72ae-11ea-8535-39fbfbaf35fc.png)

Engineering definitely wants feedback on the search feature in these templates. For example, it'd be great if recursive search was used. If you have ideas, please create a [UserVoice](https://microsoftintune.uservoice.com/forums/291681-ideas). You'll get my vote.
