### ISSUE TITLE
Enable CMG in default client policy for token-based installs

### ISSUE THREAD

**Issue by beanska** [MicrosoftDocs/memdocs#540]
It might be important to note that token-based registration requires CMG to be enabled in the default client policy. Failure to do so leaves the client installation unable to fully communicate. Even after the policy has changed clients that were install previously will have to be reinstalled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60a7510b-10d9-e7e2-f848-d57d69d7fe10
* Version Independent ID: d4e9a557-ca23-3727-52b8-b81c6f767757
* Content: [Token-based authentication for CMG - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/deploy/deploy-clients-cmg-token)
* Content Source: [memdocs/configmgr/core/clients/deploy/deploy-clients-cmg-token.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/deploy/deploy-clients-cmg-token.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @beanska for the feedback. I'm making some changes to the CMG content that I hope to publish this week, so included a few lines about this. This issue will auto close when my pull request merges, and then the changes will go live on the next daily publishing cycle.
