### ISSUE TITLE
Info on Support Operating Systems

### ISSUE THREAD

**Issue by AdamGrossTX** [MicrosoftDocs/memdocs#545]
Can you add information about which client operating systems are supported? Tenant attach works for workstation and server OSs, but that's not obvious. Providing some details about any limitations on usage or on minimum supported OS would be great, in addition to promoting the fact that Tenant Attach is a great benefit for server management as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2eb4acb-7311-79d3-3daa-6f27ea42aee7
* Version Independent ID: 123f2a5c-04c1-8184-05a4-689d9c591981
* Content: [Microsoft Endpoint Manager tenant attach - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/tenant-attach/device-sync-actions)
* Content Source: [memdocs/configmgr/tenant-attach/device-sync-actions.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/tenant-attach/device-sync-actions.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @AdamGrossTX for the feedback. I think the answer here is to just point to the list of supported clients. We'll confirm that, but generally we don't like to maintain separate lists of supported configs, just point back to the central list. 😄
