### ISSUE TITLE
Information about the SensorFramework

### ISSUE THREAD

**Issue by AdamGrossTX** [MicrosoftDocs/memdocs#546]
Can you include information about the additional ConfigMgr client components that enable EA data collection? Specifically the SensorFramework - what is it, how does it work, where are the logs, troubleshooting, etc?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 059acdd9-38dd-5ffd-0b22-e4564e6cb3d2
* Version Independent ID: eade30a9-d535-1b47-a764-1294a3c52fc5
* Content: [Endpoint analytics data collection - Configuration Manager](https://docs.microsoft.com/en-us/mem/analytics/data-collection)
* Content Source: [memdocs/analytics/data-collection.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/analytics/data-collection.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @AdamGrossTX for the feedback. We've made a conscious decision to not do detailed docs on the sensors. In much the same way that we don't doc the gory details of the site server components or client agents.
