### ISSUE TITLE
There is no Company Portal (Offline) option in Intune

### ISSUE THREAD

**Issue by icelava** [MicrosoftDocs/memdocs#55]
The only Windows apps options in Intune are

Store app
+ Windows Phone 8.1 store app
+ Microsoft Store app (this one only makes app available in Company Portal; so making Company Portal available in Company Portal is silly)

Office 365 Suite
+ Windows 10

Microsoft Edge, version 77 and later
+ Windows 10

Other
+ Web link
+ Line-of-business app
+ Windows app (Win32)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42b3ccb0-592e-a0bf-aa4f-ab37e00e1195
* Version Independent ID: d0af9188-3489-0f15-ef25-5b6d83edb76c
* Content: [Add and assign the Windows 10 Company Portal app for Autopilot provisioned devices - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/store-apps-company-portal-autopilot#feedback)
* Content Source: [memdocs/intune/apps/store-apps-company-portal-autopilot.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/store-apps-company-portal-autopilot.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Flip88** [comment]
After following the steps in all the sections it showed up for me. Took about 2 - 3 hours, but it eventually appeared in the list.

**Comment by dougeby** [comment]
@icelava, Thanks for taking the time to share this with the Intune documentation team. If you still are not seeing the Company Portal (offline) option after going through the steps in the article, I want to make sure your question gets to the right people that can help. There are a couple of options available to provide the best level of support for this:  

- Post on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.  

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.  

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.  

I'm closing this issue as there's nothing actionable for docs at this time.
