### ISSUE TITLE
Misleading info on Intune licensing

### ISSUE THREAD

**Issue by MarkBratton** [MicrosoftDocs/memdocs#551]
The statement "Devices without user affinity require a device license." is not completely accurate. If all users of the device are licensed for Intune, a device license is not required. Suggest something like "Devices without user affinity require a device license if the device will be used by anyone not licensed for Intune." 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd130267-c54b-41e3-d534-831d4a86bae6
* Version Independent ID: bdfa7eca-a356-3dde-7643-9a759f952007
* Content: [Enroll iOS/iPadOS devices - Automated Device Enrollment - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-ios#distribute-devices)
* Content Source: [memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
7811876

**Comment by MandiOhlinger** [comment]
@MarkBratton Thank you. You're right. That text is confusing. We updated it. The changes should be live later today.

If you see other updates like this, it'd be great if you created a pull request (PR) with your recommended changes. We review every PR, and would love the help. 

Thanks again.
