### ISSUE TITLE
VPP is gone

### ISSUE THREAD

**Issue by josemocha** [MicrosoftDocs/memdocs#553]
Replace text and links for Volume Purchase Program for Business with https://business.apple.com
Replace text  for Volume Purchase Program for Business with "Apple Business Manager"
Replace text and links for Volume Purchase Program for Education with https://school.apple.com
Replace text  for Volume Purchase Program for Education with "Apple School Manager"
Replace word buy with acquire. Some licenses can be free.
The token is still a .vpptoken.

Recommended text:
"Manage volume-purchased books for iOS devices
You acquire licenses for iOS/iPadOS books through Apps and Books in Apple Business Manager or Apple School Manager, formerly the. Volume Purchase Program. This process involves setting up or logging into the Apple Business Manager or Apple School Manager.  In Settings, you can download the .vpptoken and upload it to Intune. You can then synchronize your apps and books information with Intune and track your content use."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c3ed198-0186-97ca-e364-017b3a2a2652
* Version Independent ID: d584d94d-6c4a-6f3d-93f8-5f921a50a92d
* Content: [Manage volume-purchased iOS/iPadOS eBooks - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/vpp-ebooks-ios?source=docs)
* Content Source: [memdocs/intune/apps/vpp-ebooks-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/vpp-ebooks-ios.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@josemocha - Thanks for the detailed feedback. I checked through all Intune docs and did find a few remaining changes to make. Appreciate it. Thanks
