### ISSUE TITLE
Typo in docs?

### ISSUE THREAD

**Issue by sn-michiyo** [MicrosoftDocs/memdocs#554]
>Make sure an Android app protection policy is deployed to the user's security and...

should this be

>Make sure an Android app protection policy is deployed to the user's security **group** and...

?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07ad00ff-9b23-6f32-6642-353ef8239471
* Version Independent ID: a891fc24-8477-9bb9-a175-aec32005f3bc
* Content: [Troubleshoot mobile application management - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/troubleshoot-mam)
* Content Source: [memdocs/intune/apps/troubleshoot-mam.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/troubleshoot-mam.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by jpcast88** [comment]
Thanks @sn-michiyo for catching that. I've made a private pull request to get this fixed.

In the future, you may consider making the change yourself! 😉 For more information, see [How to contribute to docs.](https://docs.microsoft.com/mem/configmgr/core/understand/use-docs#bkmk_contribute)
