### ISSUE TITLE
One of the example URL format (http://www.contoso.com/*;)  is incorrect. 

### ISSUE THREAD

**Issue by Satoshi-Mori** [MicrosoftDocs/memdocs#558]
[Enter feedback here]

URL formats for allowed and blocked site list
https://docs.microsoft.com/en-us/mem/intune/apps/manage-microsoft-edge#url-formats-for-allowed-and-blocked-site-list

The example URL format (http://www.contoso.com/*;) is incorrect. 
 
Correct: http://www.contoso.com/*
Incorrect: http://www.contoso.com/*;

If you type a semicolon according to the documentation, the URL match will not work as expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a31e5a24-4f06-9e36-eacb-689bed95cd59
* Version Independent ID: ede9248e-1114-3e1a-9e80-34e5fe547707
* Content: [Manage Edge for iOS and Android with Intune](https://docs.microsoft.com/en-us/mem/intune/apps/manage-microsoft-edge#specify-allowed-or-blocked-sites-list-for-microsoft-edge)
* Content Source: [memdocs/intune/apps/manage-microsoft-edge.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/manage-microsoft-edge.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@Satoshi-Mori - Thanks for the feedback. The update is being made now and should be published later today.

**Comment by Satoshi-Mori** [comment]
Hi Erik,
Thank you for your sincere response.
Satoshi Mori
