### ISSUE TITLE
Where are Custom Reports in new Intune portal

### ISSUE THREAD

**Issue by c016smith** [MicrosoftDocs/memdocs#560]
The instructions here are for the classic portal which is retired. Where can I get this functionality in the new portal? I go to "reports" and there's no option for Custom Reports. I see a banner advertising the ability to get custom reports in the new portal. but no option to do it. Where is that option? 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e5e8bfb-530f-5fae-7a02-bb494497bcea
* Version Independent ID: 5350b76e-4e1d-79da-2655-10829ef261c9
* Content: [View hardware and software inventory for Windows PCs - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/view-hardware-and-software-inventory-for-windows-pcs-in-microsoft-intune)
* Content Source: [memdocs/intune/fundamentals/view-hardware-and-software-inventory-for-windows-pcs-in-microsoft-intune.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/view-hardware-and-software-inventory-for-windows-pcs-in-microsoft-intune.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @dougeby
* Microsoft Alias: **dougeby**

**Comment by dougeby** [comment]
@c016smith Sorry for the delay! 

You can go to the Intune Data Warehouse documentation for information about creating custom reports here: https://docs.microsoft.com/en-us/mem/intune/developer/reports-nav-create-intune-reports. 

The general reporting article is here: https://docs.microsoft.com/en-us/mem/intune/fundamentals/reports. 

I hope this helps!
