### ISSUE TITLE
Error code not listed 0x87D13B92

### ISSUE THREAD

**Issue by tek-collab** [MicrosoftDocs/memdocs#561]
The error code: 0x87D13B92 is not listed in the documentation https://docs.microsoft.com/en-us/mem/intune/apps/app-install-error-codes and the solution is jut changing the licensing in the app, the error should be added ASAP

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 826eb5cf-dadc-a5a6-ff24-793f7e9fb371
* Version Independent ID: 92227d8c-1eb3-e5b7-8dc1-52aaa1eabfd4
* Content: [App installation error codes - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-install-error-codes)
* Content Source: [memdocs/intune/apps/app-install-error-codes.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-install-error-codes.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
We have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. I'm passing your information to the support team. If you have additional questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

Please use the above channels if you don't already have a solution.
