### ISSUE TITLE
Education profile is not listed?

### ISSUE THREAD

**Issue by kcurtis-dnusd** [MicrosoftDocs/memdocs#564]
I'm not sure if I am in the correct place but the instructions do not seem to match the Admin Center for Endpoint Manager or Intune for Edu. Specifically, when creating an iOS configuration profile, there is not an education profile type listed in the dropdown. I could create a "custom" PKCS certificate profile but that does not match the steps and I am wondering if I have something misconfigured.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bc0159d-5a5e-ea2c-042d-bd5ead842d0b
* Version Independent ID: 83266995-5234-3b09-784d-75bb1844e5f3
* Content: [Intune settings for the iOS/iPadOS Classroom app - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/education-settings-configure-ios)
* Content Source: [memdocs/intune/fundamentals/education-settings-configure-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/education-settings-configure-ios.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @kcurtis-dnusd, thanks for writing in. If you're trying to configure the Classroom app, Intune doesn't currently support doing that. It used to be supported (which is why you're finding this article). Now this article is only applicable for users with existing iOS/iPadOS education profiles in Intune.
