### ISSUE TITLE
Additional known issue with Content Cleanup Tool

### ISSUE THREAD

**Issue by Maymne** [MicrosoftDocs/memdocs#565]
https://configurationmanager.uservoice.com/forums/300492-ideas/suggestions/36670366-content-cleanup-tool-errors-out-on-nested-task-seq

As reported above, the Content Cleanup Tool will error out when there are nested Task Sequence segments as it, like the Content Library Explorer, believes that their state is pending. I believe the only workaround currently is to not to use any nested Task Sequences if you want to use the Content Cleanup Tool.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5902fbb-8ca5-6cfb-bb5e-fbbe4d68e712
* Version Independent ID: 51544ed6-18b7-d926-e45f-c817b8e26d69
* Content: [Content library cleanup tool - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/hierarchy/content-library-cleanup-tool)
* Content Source: [memdocs/configmgr/core/plan-design/hierarchy/content-library-cleanup-tool.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/hierarchy/content-library-cleanup-tool.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Maymne for the feedback. The engineering team is tracking this and other issues with the tool. When they update the tool, we'll doc accordingly.
(internal reference 4411374)
