### ISSUE TITLE
Documentation update recommendation

### ISSUE THREAD

**Issue by igorvt77** [MicrosoftDocs/memdocs#569]
Under the section "Managed Google Play private (LOB) app publishing using the Google Developer Console", I had trouble finding the "Privately target this app to a list of organizations" option mentioned in bullet 3. Eventually I was able to find the documentation from Google here: https://support.google.com/googleplay/android-developer/answer/6145139?hl=en (Look for the section Publish to your own organization). I would suggest either adding a few of the steps to this document or linking to this answer. Thank you.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5a2b8f0-f2a0-f4d6-94d9-06e6d9632f59
* Version Independent ID: 8c8d89cf-9ed7-bb02-2439-e7ce9bb03f0c
* Content: [Add and assign Managed Google Play apps to Android Enterprise devices - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-add-android-for-work)
* Content Source: [memdocs/intune/apps/apps-add-android-for-work.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/apps-add-android-for-work.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@igorvt77 - Thanks for the feedback. I updated the Intune docs based on your feedback.
