### ISSUE TITLE
clarity on data collection for MAM-WE scenario

### ISSUE THREAD

**Issue by WeiPinChai** [MicrosoftDocs/memdocs#57]
while the title of this page reads "Data collection in Intune", the first paragraph "When users enroll their corporate or personal devices using Intune....". my question is; wouldn't this applies to MAM-WE scenario, where devices are NOT enrolled?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92f5f6f5-e3f0-c28c-4789-894774b93ed2
* Version Independent ID: 02b9fe77-ed28-a366-16f7-413a72ddfeb9
* Content: [Data collection in Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/privacy-data-collect?source=docs#feedback)
* Content Source: [memdocs/intune/protect/privacy-data-collect.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/privacy-data-collect.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
(6943352)

**Comment by ErikjeMS** [comment]
@WeiPinChai The PM responded and tells me that this does not apply to MAM-WE. Thanks!
