### ISSUE TITLE
License Pre-requisite

### ISSUE THREAD

**Issue by vijaynikam** [MicrosoftDocs/memdocs#573]
Can we update this page with additional pre-requisite information especially relating to Licensing requirements.
Licensing requirement however is available on 
https://techcommunity.microsoft.com/t5/intune-customer-success/configuring-jamf-pro-and-intune-integration/ba-p/334613

The latest version of Jamf Pro
Microsoft Intune and Microsoft AAD Premium P1 licenses (recommended Microsoft Enterprise Mobility + Security license bundle)
A user with Microsoft Intune Integration privileges in Jamf Pro
The latest version of the Microsoft Intune Company Portal app
End user computers with macOS 10.11 or later

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54745d43-7151-b13a-57f6-7329856e5d2b
* Version Independent ID: 07d2ffd1-49b6-3046-cc07-a4aa35e4fe61
* Content: [Integrate Jamf Pro with Microsoft Intune for compliance - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/conditional-access-integrate-jamf)
* Content Source: [memdocs/intune/protect/conditional-access-integrate-jamf.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/conditional-access-integrate-jamf.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
Docs have been updated with the additional details and will be live later on 9/24/2020.
