### ISSUE TITLE
Scan Exclusions

### ISSUE THREAD

**Issue by johnjohnjohn87** [MicrosoftDocs/memdocs#574]
Hello,

I was wondering if there were any best practices for exclusions for MAC. It would be really helpful if there were some guidance in this area for all of us Windows admins :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44ae558b-798a-7d24-fed3-1b34dee61747
* Version Independent ID: 407b8efd-3351-8891-6b2b-09834c06e240
* Content: [macOS Antivirus policy settings for Microsoft Defender Antivirus for Intune](https://docs.microsoft.com/en-us/mem/intune/protect/antivirus-microsoft-defender-settings-macos)
* Content Source: [memdocs/intune/protect/antivirus-microsoft-defender-settings-macos.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/antivirus-microsoft-defender-settings-macos.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@johnjohnjohn87   Thanks for the question, but I regret that  best practice details for configuring Defender ATP for macOS isn't a subject that our Intune documentation can cover. Something like that would need to come from macOS experts, or the Defender ATP team which added the support. 

I did some digging around and found similar questions via techcommunity.microsoft.com, so your not alone. I think this following article from the Defender ATP team might be a good place to start, though it doesn't lay out best practices as I'd hope to see them: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-mac.
