### ISSUE TITLE
Useless

### ISSUE THREAD

**Issue by the50admiral** [MicrosoftDocs/memdocs#576]
The page is kind of useless if you have to sign up for a free Premium trail.  What am I supposed to do when the trial runs out?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adbfe90c-635e-5d23-f0b3-2d015565e311
* Version Independent ID: bcc85788-87a8-c3b5-1b60-a4938a09e541
* Content: [Quickstart - Set up automatic enrollment in Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/quickstart-setup-auto-enrollment)
* Content Source: [memdocs/intune/enrollment/quickstart-setup-auto-enrollment.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/quickstart-setup-auto-enrollment.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@the50admiral At the end of the free trial you'll be given an option to sign up for a paid subscription. Thanks!
