### ISSUE TITLE
Scenario #4's WMI method doesn't work on 1906

### ISSUE THREAD

**Issue by NathanHopkins6283** [MicrosoftDocs/memdocs#577]
Scenario 4: Machine-based pre-approved requests, the WMI method returns a 'Generic Failure':
Invoke-WmiMethod : Generic failure 
At line:2 char:5
+     Invoke-WmiMethod -ComputerName <ServerNameRedacted> -Path "SMS_ApplicationRequ ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Invoke-WmiMethod], ManagementException
    + FullyQualifiedErrorId : InvokeWMIManagementException,Microsoft.PowerShell.Commands.InvokeWmiMethod

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da2c2de6-cf86-436e-3902-f1a3aa991e1a
* Version Independent ID: cc00e4b1-43ac-d665-0567-a14689954199
* Content: [Application approval process - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/develop/apps/application-approval-process)
* Content Source: [memdocs/configmgr/develop/apps/application-approval-process.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/develop/apps/application-approval-process.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @NathanHopkins6283 for the feedback. We'll need to check with the engineer that authored this content.

**Comment by mestew** [comment]
Well, sorry it took a bit to get to this but.....closing since 1906 isn't a supported version anymore. Please file a frown in the CM console from the Applications node if this still occurs so it gets to the dev team.
