### ISSUE TITLE
Only option is "Rename"

### ISSUE THREAD

**Issue by rcmpgi** [MicrosoftDocs/memdocs#579]
When I sign in to the Company Portal website, the only option I get for a device is "Rename". Why, and can this page please link somewhere to tell me or an IT admin (I am an IT admin!) how to fix this?

**Comment by ChrisKibble** [comment]
@rcmpgi - You removed the metadata from the comment so I'm not sure which page you're referring to.  Do you recall what you were looking at that you wanted to provide this feedback on?

**Comment by rcmpgi** [comment]
Maybe referring to this one: https://portal.manage.microsoft.com/devices/ and/or maybe this one: https://docs.microsoft.com/en-us/mem/intune/apps/company-portal-app#customizing-user-self-service-actions-for-the-company-portal
But frankly this was so long ago now I have no idea what I was hoping to achieve! :-)
