### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by MatthewSteeples** [MicrosoftDocs/memdocs#58]
The only instructions I have are

`Something went wrong`
`Try again, or tap Cancel to set up your device later`

It's been like this for 2 days now, multiple resets, re-installs. No error details or anything

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fbb1036-7815-586b-f86c-89065a44cf9b
* Version Independent ID: f19e131c-88f4-73d6-5fdc-8faac18763ee
* Content: [Troubleshooting Windows device enrollment problems in Microsoft Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/troubleshoot-windows-enrollment-errors#feedback)
* Content Source: [memdocs/intune/enrollment/troubleshoot-windows-enrollment-errors.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/troubleshoot-windows-enrollment-errors.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@MatthewSteeples Thanks for taking the time to share this with the Intune documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a few options available to provide the best level of support for a specific issue like this:   
- Post on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.   
- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.   
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.   
I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by MatthewSteeples** [comment]
@ErikjeMS Thanks for that. And sorry about the rant :)

If there are any other places where information can be found (Event Logs to check, or Logs on the device itself) they would be useful to write about, but I'll see what I get back from forums/support.

**Comment by MatthewSteeples** [comment]
@milesgratz no I hadn't. Thanks for the pointer. Sadly neither Admin or Operational shows any messages when I try and join the device. They have some information logs, but they all seem to indicate that the device itself is happy
