### ISSUE TITLE
Spelling Error in Sample Code

### ISSUE THREAD

**Issue by KEJP1** [MicrosoftDocs/memdocs#581]
There is a spelling error on the sample code located here https://docs.microsoft.com/en-us/mem/configmgr/develop/core/understand/sqlviews/hardware-inventory-views-configuration-manager#sample-query

SBS.LatestGPDuration0 as 'Latest Group Ploci Duration', Should be "Policy" no?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 931870af-92b6-3bd3-1928-94fe3d0ece9a
* Version Independent ID: bfa95bdb-ed33-d8c3-8ca8-f3ac740abb5d
* Content: [Hardware inventory views - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/develop/core/understand/sqlviews/hardware-inventory-views-configuration-manager)
* Content Source: [memdocs/configmgr/develop/core/understand/sqlviews/hardware-inventory-views-configuration-manager.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/develop/core/understand/sqlviews/hardware-inventory-views-configuration-manager.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Yep, good catch @KEJP1. I'll fix that now. Might catch afternoon publishing, otherwise tomorrow morning for sure. Thanks!
