### ISSUE TITLE
Microsoft 365 F3?

### ISSUE THREAD

**Issue by djanny22** [MicrosoftDocs/memdocs#585]
Where stating licensing requirements, is Microsoft 365 F3 missing, as it was renamed this year?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f3023a8-ab6c-1d77-0111-77cc7583347c
* Version Independent ID: 26debf60-c3c1-caa6-7f78-a04a8b8e73af
* Content: [Product and licensing FAQ - Configuration Manager](https://docs.microsoft.com/en-gb/mem/configmgr/core/understand/product-and-licensing-faq#bkmk_mem)
* Content Source: [memdocs/configmgr/core/understand/product-and-licensing-faq.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/understand/product-and-licensing-faq.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Yeah, appears so. Thanks for letting me know, I was unaware of the change. I'll fix that now across our content set.
