### ISSUE TITLE
No docs for error 0x87D13B92

### ISSUE THREAD

**Issue by rooneytx** [MicrosoftDocs/memdocs#586]
Have opened a support ticket for this incomplete documentation [Case #:21059915] 

We are seeing an error for an iOS app that uses a VPP token. The error reported in the Intune App install blade is  “VPP App licensing pending user consent. Ensure the user has accepted the VPP management invite. (0x87D13B92)” but when I view the web site https://docs.microsoft.com/en-us/mem/intune/apps/app-install-error-codes#ios-and-ipados-app-installation-errors I am not seeing any documentation related to this error code. What are the troubleshooting steps for this error? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 826eb5cf-dadc-a5a6-ff24-793f7e9fb371
* Version Independent ID: 92227d8c-1eb3-e5b7-8dc1-52aaa1eabfd4
* Content: [App installation error codes - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-install-error-codes#feedback)
* Content Source: [memdocs/intune/apps/app-install-error-codes.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-install-error-codes.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
We have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. If you have continue to have questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

Please use the above channels if you don't already have a solution.
