### ISSUE TITLE
Resetting Device Profiles without Retiring Device

### ISSUE THREAD

**Issue by mslsac** [MicrosoftDocs/memdocs#59]
Instead of retiring a device and then re-enrolling a device to reset the policies that are applied to a computer that is managed by a less restrictive profile can you simply do the following:
Remove the following registry entry:
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PolicyManager\Providers\\{GUID}\default\Device\\{keys for entry}
then remove the entries that are located at:
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PolicyManager\default\\{Main settings applied you wish to remove}

and then let the device re-check configuration profiles, will this allow the new settings to take effect, even if its less restrictive than the previous settings?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14c045c9-2ccb-e24b-9eaa-bfd65b64a48c
* Version Independent ID: 355e928b-5ad8-ac1d-24d4-1d2e8f11cb4d
* Content: [Troubleshoot device profiles in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/device-profile-troubleshoot#feedback)
* Content Source: [memdocs/intune/configuration/device-profile-troubleshoot.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/device-profile-troubleshoot.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by mslsac** [comment]
The reason why I have had to go into these settings is because over time, organizations change over time. If an organization determines that a setting is too restrictive for their environment they need to revert that setting. There needs to be an easier way for administration to be able to change a setting and have the device check back in and apply the setting that is currently set for the device. NOT be the most restrictive setting that was ever applied to the device as those settings may no longer apply to the device for proper administration.

**Comment by MandiOhlinger** [comment]
@mslsac This is a great question for the [Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod), or to ask the [Intune support team](https://docs.microsoft.com/intune/get-support). We strongly encourage you to go that route.

**Comment by mslsac** [comment]
I have opened the following thread on the Intune Forums-
https://social.technet.microsoft.com/Forums/en-US/a93b2214-48da-4dbd-89cd-a6b5ef77369f/resetting-device-profiles-without-retiring-device?forum=microsoftintuneprod
