### ISSUE TITLE
Add tip to avoid unexpected interaction with Azure Security Center Standard

### ISSUE THREAD

**Issue by troyphil** [MicrosoftDocs/memdocs#590]
In step 5, there is already a tip "You can only have one Desktop Analytics workspace per Azure AD tenant". Please add another tip, along the lines of "it is recommended not to use Desktop Analytics with a workspace that contains servers and may be used with Azure Security Center Standard. If Azure Security Centre Standard is enabled on the Desktop Analytics workspace, then each Windows 10 device will be charged as a Virtual Machine node"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93b0864e-3fa3-54c2-a9cc-96cff884cc08
* Version Independent ID: 7a29f204-30d6-7482-47cb-98498899ea3b
* Content: [Set up Desktop Analytics - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/desktop-analytics/set-up)
* Content Source: [memdocs/configmgr/desktop-analytics/set-up.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/desktop-analytics/set-up.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @troyphil for the feedback. I have a conversation underway with support and several service PMs to sort this out. Stay tuned.

**Comment by aczechowski** [comment]
I'm actually adding a note to the prerequisites doc that already talks about cost of Log Analytics. This issue will auto close when the change merges, and then it will go live with the next daily publishing process (which right now should be later today around 4pm Pacific time).
