### ISSUE TITLE
Incorrect location of "Use custom web site" check box

### ISSUE THREAD

**Issue by BradPalmerKSE** [MicrosoftDocs/memdocs#592]
Doc says:
Although you can check or uncheck the box for using custom websites at a primary site at any time (the box is on the General tab of the site's Properties)

The location of the "Use custom web site" check box in CB 2002 is in the sites properties "Port" tab.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbfc4cf2-66c2-5bd6-e8ee-21f716c394bf
* Version Independent ID: 675e37a8-0e93-2a04-f645-6aa73ab385e9
* Content: [Websites for site systems - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/network/websites-for-site-system-servers)
* Content Source: [memdocs/configmgr/core/plan-design/network/websites-for-site-system-servers.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/network/websites-for-site-system-servers.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
Thanks @jpcast88 for fixing this one!
