### ISSUE TITLE
Rebuild indexes task description

### ISSUE THREAD

**Issue by Yupiter2005** [MicrosoftDocs/memdocs#599]
Hi!

Are we sure we actually **drop** and **create** the indexes as per
```
Creates indexes on database columns that are at least 50 percent unique
Drops indexes on columns that are less than 50 percent unique
Rebuilds all existing indexes that meet the data uniqueness criteria
```
?

As per our code (BOOL DBUtils::RecreateIndexes()) I see that we do REBUILD/REORGANIZE, but not DROP/CREATE.
Am I missing something?

Pavel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8964669d-7a44-83d9-ae6c-9765aabf221c
* Version Independent ID: fce0954c-706c-11a3-fc92-9b9a433da8a6
* Content: [Reference for maintenance tasks - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/manage/reference-for-maintenance-tasks#rebuild-indexes)
* Content Source: [memdocs/configmgr/core/servers/manage/reference-for-maintenance-tasks.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/manage/reference-for-maintenance-tasks.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by Yupiter2005** [comment]
+ documented here: https://techcommunity.microsoft.com/t5/configuration-manager-archive/configmgr-2012-rebuilding-indexes-criteria/ba-p/339921

**Comment by mestew** [comment]
@Yupiter2005 I'm seeing the same thing that Umair posted. Hit me up on Teams and I'll tell ya how to create an issue in the private docs repo if you need to discuss parts of code. 

Working on doc change now.
