### ISSUE TITLE
Clarify remote AADJ+Autopilot support (i.e. VPN)

### ISSUE THREAD

**Issue by joesuffceren** [MicrosoftDocs/memdocs#60]
This article calls out VPN as explicitly unsupported, but https://support.microsoft.com/en-us/help/4532441/cumulative-update-for-autopilot-in-windows-10-versions-1903-1909 says support was added. Can this article be updated to reflect support stance specifically with regards to that CU? Remote Autopilot AADJ is pretty important for orgs that have had to close all physical offices.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a94c428-95df-632b-46e8-4386ad551a03
* Version Independent ID: f23998f0-52ff-1203-1a0c-ff5c25b08c1c
* Content: [Enrollment for hybrid Azure AD-joined devices - Windows Autopilot](https://docs.microsoft.com/en-us/mem/intune/enrollment/windows-autopilot-hybrid#feedback)
* Content Source: [memdocs/intune/enrollment/windows-autopilot-hybrid.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/windows-autopilot-hybrid.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
(6735133)

**Comment by ErikjeMS** [comment]
@joesuffceren Here's the PM's response: "The December update added the Windows 10 client-side support needed for us to support VPN for Hybrid Azure AD Join. So the documentation is correct."
We'll update the docs when the service-side support is released. Keep an eye on the [In Development ](https://docs.microsoft.com/en-us/mem/intune/fundamentals/in-development)and [What's New](https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new) pages for news on that.
