### ISSUE TITLE
Explain offline version choice

### ISSUE THREAD

**Issue by AlwaysLearningTech** [MicrosoftDocs/memdocs#604]
Why use offline and not online version?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42b3ccb0-592e-a0bf-aa4f-ab37e00e1195
* Version Independent ID: d0af9188-3489-0f15-ef25-5b6d83edb76c
* Content: [Add and assign the Windows 10 Company Portal app for Autopilot provisioned devices - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/store-apps-company-portal-autopilot)
* Content Source: [memdocs/intune/apps/store-apps-company-portal-autopilot.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/store-apps-company-portal-autopilot.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
Thanks for the feedback. The docs have been updated:
Offline apps are managed by Intune, whereas online apps are managed by the store. Use offline apps when you need to install and maintain a specific app version.
