### ISSUE TITLE
Few changes

### ISSUE THREAD

**Issue by theg00d1** [MicrosoftDocs/memdocs#605]
[Enter feedback here]

Kindly change the intune portal to Endpoint Manager 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea4a659b-65d0-26ec-c36a-9a21a72a09a8
* Version Independent ID: bff44b73-9021-6659-e212-66349c759989
* Content: [Adding devices](https://docs.microsoft.com/en-us/mem/autopilot/add-devices)
* Content Source: [memdocs/autopilot/add-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/add-devices.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
@theg00d1 please clarify.  The term "intune portal" is not used in this article.

**Comment by theg00d1** [comment]
https://i.imgur.com/mBbZmkw.png

**Comment by greg-lindsay** [comment]
These are links to article, not to portals.  It is meant to be this way.

**Comment by theg00d1** [comment]
YEs i understand that Greg however i am sure you know that using Intune we cannot upload the hardware hash anymore & it got migrated.

**Comment by greg-lindsay** [comment]
I just checked this and I don't see any issues with uploading a .CSV with hardware hashes. Can you tell me what you believe has changed?

**Comment by greg-lindsay** [comment]
https://docs.microsoft.com/en-us/mem/autopilot/enrollment-autopilot#add-devices

**Comment by greg-lindsay** [comment]
I think I see where the confusing lies. MEM is a combination of Intune and SCCM.  Device enrollment is an Intune function, but when you do it, you use the MEM manager interface.  This is still Intune, however.  Maybe I can clarify that in the documentation.

**Comment by theg00d1** [comment]
Yup you are right :)

**Comment by greg-lindsay** [comment]
I've added a clarification in the doc it should publish later today. Thanks!
