### ISSUE TITLE
Insight into "client settings".

### ISSUE THREAD

**Issue by essentialexch** [MicrosoftDocs/memdocs#606]
It would be quite worthwhile to define where "client settings" are located. For a beginner, it's not obvious.

Secondly, it's not obvious that "Default Client Settings" apply even if they've never been deployed.  Therefore, if you've installed Software Updates - EVEN IF YOU HAVEN'T CONFIGURED THEM YET - the settings go out in the next client settings update, since "Enable software updates on clients" setting is enabled by default. I think this behavior is broken. Regardless of which, the behavior should be documented.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41d9647c-11a2-b092-6f37-2176a3f8562d
* Version Independent ID: 416a59b0-946c-48aa-a82b-95b74572334a
* Content: [Manage settings for software updates - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/sum/get-started/manage-settings-for-software-updates)
* Content Source: [memdocs/configmgr/sum/get-started/manage-settings-for-software-updates.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/sum/get-started/manage-settings-for-software-updates.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @essentialexch, thanks for the feedback, but I don't think in this context it requires additional information. There are links at the end of the section on client settings that refers to the two main articles on client settings, which go into more detail:

[How to configure client settings](https://docs.microsoft.com/mem/configmgr/core/clients/deploy/configure-client-settings)

[About client settings](https://docs.microsoft.com/mem/configmgr/core/clients/deploy/about-client-settings)
