### ISSUE TITLE
The screenshot for the Device Authority change is not correct

### ISSUE THREAD

**Issue by raoul84th** [MicrosoftDocs/memdocs#607]
[Image is misleading as it no longer appears this way in the portal... now it is something along the lines of "your account is o365 do you want to change it to Intune.....takes several refreshes of the browser to see it pop up too]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a76fc834-999b-2dea-10b7-984225b695dd
* Version Independent ID: 583b8b02-5c7b-aa08-ec28-07b89adbd994
* Content: [Set the mobile device management authority - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/mdm-authority-set)
* Content Source: [memdocs/intune/fundamentals/mdm-authority-set.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/mdm-authority-set.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@raoul84th The PM tells me the screenshot is still correct. Perhaps you've found a bug? Can you contact support and provide them with a screencap that you're seeing? Thanks! I'll close this issue as there's nothing for docs to do until support determines if there's a bug.
- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.
