### ISSUE TITLE
Token renewal after 90 days?

### ISSUE THREAD

**Issue by Maelito77** [MicrosoftDocs/memdocs#612]
How does the client renews the token after 90 days?
Can this be explained on the doc? 
Thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60a7510b-10d9-e7e2-f848-d57d69d7fe10
* Version Independent ID: d4e9a557-ca23-3727-52b8-b81c6f767757
* Content: [Token-based authentication for CMG - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/deploy/deploy-clients-cmg-token)
* Content Source: [memdocs/configmgr/core/clients/deploy/deploy-clients-cmg-token.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/deploy/deploy-clients-cmg-token.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @Maelito77, thanks for the question. Technically how the client renews the token is a level of detail that we generally don't include in our docs. However, I think what you're asking about is what happens after 90 days? The client tries to renew the token after 30 days, either on the internal network, or via CMG if it uses certificate authentication or Azure AD. If the client is truly offline for more than 90 days, then you will need to register it again with a new token.
One of our PMs is planning some revisions to this article soon, which should address this question. So I'm going to close this issue.

**Comment by Maelito77** [comment]
I’m sorry to come back to this Aaron but something is not clicking my side. 
If I need a token to register against the CMG that’s because the machine does not have certs to hybrid join (it’s only azure registered right now) so how can I requested a token renewal? Will the CMG be able to renew the token as the machine is now visible (after aí regtoken it and authenticated to the CMG? These machine will never ever go back to the office so that dunks the 90day limit...

**Comment by aczechowski** [comment]
Hi @Maelito77 sorry if I confused/mixed terminology. What I'm talking about is the the client's "self-prove" token, as described in the section [Register on the internal network](https://docs.microsoft.com/mem/configmgr/core/clients/deploy/deploy-clients-cmg-token#register-on-the-internal-network). If a client registers on the internal network, and then roams onto the internet, if it can't create a secure connection with an MP, that token will expire. That behavior has been the case for many years. So if you have AD-joined, workgroup, or AAD-registered clients, they'll need some way to establish that secure communication. Over CMG, it needs either PKI or AAD-join. Alternatively, if the clients have VPN, and they can talk with the on-prem MP (as they would if they were on the internal network), then they'll renew their self-prove token as normal. If none of those options apply, then you'll need to issue a bulk registration token (a different type of token) after 90 days to re-register those clients with the site. I hope that helps to clarify.
