### ISSUE TITLE
Missing error 0x87d10000

### ISSUE THREAD

**Issue by jimmyeao** [MicrosoftDocs/memdocs#613]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef65dde9-9a09-7783-54fd-d2048a7e5c8d
* Version Independent ID: 78f87124-42d7-746a-5a67-11cba073f3e4
* Content: [Error and status codes in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/fundamentals/troubleshoot-company-resource-access-problems)
* Content Source: [memdocs/intune/fundamentals/troubleshoot-company-resource-access-problems.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/troubleshoot-company-resource-access-problems.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@jimmyeao I followed up with the support team. It's possible this error code may no longer be relevant or used. If you’re seeing it in your environment, it'd be great if you created a pull request (PR) with some recommended doc changes. We review every PR, and it'll give our support team more information.

The steps to create a PR are at [https://github.com/MicrosoftDocs/memdocs](https://github.com/MicrosoftDocs/memdocs). Just scroll post the folder view.
