### ISSUE TITLE
"SMSMP=https://mp1.contoso.com" not showing in the example

### ISSUE THREAD

**Issue by ii-batman** [MicrosoftDocs/memdocs#614]
Previous examples in Step 5 included an entry for "SMSMP=https://mp1.contoso.com"
This is not present on the current version of the document.
Please confirm if this is a required entry, and if so is this my internal SCCM server address?
Cross check with this doc "https://docs.microsoft.com/en-us/mem/configmgr/core/clients/deploy/about-client-installation-properties" where it lists the SMSMP entry.
Thanks, M

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60a7510b-10d9-e7e2-f848-d57d69d7fe10
* Version Independent ID: d4e9a557-ca23-3727-52b8-b81c6f767757
* Content: [Token-based authentication for CMG - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/deploy/deploy-clients-cmg-token#create-a-bulk-registration-token)
* Content Source: [memdocs/configmgr/core/clients/deploy/deploy-clients-cmg-token.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/deploy/deploy-clients-cmg-token.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @ii-batman, it was removed on June 4 as part of an internal doc bug. For the full details, see [the commit](https://github.com/MicrosoftDocs/memdocs/commit/2506e21af2d4ab4e506f406b5a6ec70ed7a5c851). SMSMP may still a valid entry for your environment if the client will roam back onto the internal network. See the following line from the referenced article [Install and register the client using Azure AD identity](https://docs.microsoft.com/mem/configmgr/core/clients/deploy/deploy-clients-cmg-azure):

> The **SMSMP** property specifies the on-premises management point. It's not required. It's recommended for Azure AD-joined devices that roam onto the intranet, so they can find an on-premises management point.
