### ISSUE TITLE
Conditional Launch - Missing a feature setting

### ISSUE THREAD

**Issue by Pickell** [MicrosoftDocs/memdocs#616]
Can anyone advise what might be the reason I **_don't_** have the following setting available in my Application Protection Policy for Android?  I have all the other new settings (e.g. Min patch level, SafetyNet, Max threat level).  Note: we use App Protection Policies without enrollment.

**Disabled account** | There is no value to set for this setting. Actions include:
-Block access - When we have confirmed the user has been disabled in Azure Active Directory, the app blocks access to work or school data.
-Wipe data - When we have confirmed the user has been disabled in Azure Active Directory, the app will perform a selective wipe of the users' account and data.
-- | --

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 521e26fd-bb00-1174-b238-a1c445140cd6
* Version Independent ID: 21341639-85f8-2f94-1834-59cb778bd21b
* Content: [Android app protection policy settings - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policy-settings-android)
* Content Source: [memdocs/intune/apps/app-protection-policy-settings-android.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-protection-policy-settings-android.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
Thanks for the feedback. This feature likely appeared as part of a rolling implementation shortly after this GitHub issue was posted. I verified the option is available. 

If you have additional questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

We have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. Please use the above channels if you don't already have a solution.
