### ISSUE TITLE
Steps in new order now. 

### ISSUE THREAD

**Issue by CloudBeard** [MicrosoftDocs/memdocs#618]
Hello, 

Awesome and very useful guide! I notice while running through the setup that a few steps have moved in your order. 

Under the section Create the device configuration profile to onboard Windows devices step 3 now appeared for me after step 5.

This is also my first time submitting a change, if there is a guide on the best method to do this I will follow that from now on!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24fa182f-ace6-e7e2-ff98-91951be7d10e
* Version Independent ID: f1acb398-6d69-b91c-5ee0-3da3bbf7809f
* Content: [Configure Microsoft Defender ATP in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/advanced-threat-protection-configure)
* Content Source: [memdocs/intune/protect/advanced-threat-protection-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/advanced-threat-protection-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@CloudBeard  Thanks for the great feedback. You provided clear details that let me home in on just where the doc issue is at.  For this, it looks like the Device Configuration workflow in the UI has recently caught up to the more recent workflow design seen in other areas. However, this content was left behind. I've submitted a fix to get the steps in-line, which will be published live later today. 

In the future, you can go a step further if you wish to submit a direct contribution to the content. If interested, check out our _Contributors Guide_ for how to do so [[https://docs.microsoft.com/en-us/contribute/](https://docs.microsoft.com/contribute)].  Edits to the article you submit are reviewed and if necessary passed back to you for modification. We can also directly edit them to fix minor issues when needed.  Edit submissions are always reviewed by the docs team before they move to publication so you won't need worry about doing harm. ;).
