### ISSUE TITLE
-o switch

### ISSUE THREAD

**Issue by kniption** [MicrosoftDocs/memdocs#62]
-o should represent a path, not a file name. When using -o the file is created in the folder used in the parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54e4efd6-d1de-dba7-6ae5-a91c7a28b662
* Version Independent ID: f529438b-becd-3b8e-dc6c-02413af9854f
* Content: [How to add macOS line-of-business apps to Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/lob-apps-macos#feedback)
* Content Source: [memdocs/intune/apps/lob-apps-macos.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/lob-apps-macos.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@kniption - Thanks for the feedback. We're updating the docs now.
