### ISSUE TITLE
Delete deployed Wi-Fi Profile on Android Enterprise

### ISSUE THREAD

**Issue by Mela-SAG** [MicrosoftDocs/memdocs#625]
Hi, I want to "Delete deployed Wi-Fi Profile on Android Enterprise"
https://techcommunity.microsoft.com/t5/microsoft-intune/delete-deployed-wi-fi-profile-on-android-enterprise/m-p/1580233

As I figurate out, this need to be done manually "unfortunately", BUT according to Manual should be possible....?
https://docs.microsoft.com/en-us/mem/intune/configuration/device-profile-troubleshoot#what-happens-when-a-profile-is-deleted-or-no-longer-applicable
![image](https://user-images.githubusercontent.com/53521867/90234743-70bd5f00-de20-11ea-884c-81b2c692bb24.png)
Anyway, if not, this is written very confusable.....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14c045c9-2ccb-e24b-9eaa-bfd65b64a48c
* Version Independent ID: 355e928b-5ad8-ac1d-24d4-1d2e8f11cb4d
* Content: [Troubleshoot device profiles in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/device-profile-troubleshoot#what-happens-when-a-profile-is-deleted-or-no-longer-applicable)
* Content Source: [memdocs/intune/configuration/device-profile-troubleshoot.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/device-profile-troubleshoot.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@Mela-SAG On Android Enterprise devices, the Wi-Fi profiles _should_ be removed. If yours isn't being removed, we suggest working with [Microsoft Intune support](https://docs.microsoft.com/intune/get-support) to figure out why it isn't working. You can also post your question on [the user forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod) for ideas on things to check.

**Comment by Mela-SAG** [comment]
Thanks @MandiOhlinger , I will try to get Support from the Intune Teams.
