### ISSUE TITLE
Clarify Company Portal supportability for Non User Device Affinity devices

### ISSUE THREAD

**Issue by mattwailes** [MicrosoftDocs/memdocs#626]
I'm seeing a contradiction on the documentation [here](https://docs.microsoft.com/en-us/mem/intune/enrollment/ios-enroll#about-corporate-owned-managed-devices-with-no-user-affinity) discussing how the company portal should not be used for non-uda devices. _"Devices that are configured with no user affinity do not support the Company Portal and should not have the app installed."_

On a different page [here ](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-ios#create-an-apple-enrollment-profile)it discusses deploying the company portal with some modifications "_Enroll without User Affinity - Choose this option for device unaffiliated with a single user. Use this option for devices that don't access local user data. To enable an end user to sign in to the iOS Company Portal and establish themself as the primary user of the device, send the IntuneUDAUserlessDevice key to iOS Company Portal in an app configuration policy for managed devices. Note that only the first user signing in is established as the primary user. If the first user signs out and a second user signs in, the first user remains the primary user of the device. For more information, see Configure the Company Portal app to support iOS and iPadOS DEP devices."_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cc313c2-46f2-c985-5f4a-7b7dd6c2cab3
* Version Independent ID: 84fba899-da3c-80f5-fb82-62cd381bc650
* Content: [Enroll iOS/iPadOS devices in Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/ios-enroll)
* Content Source: [memdocs/intune/enrollment/ios-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/ios-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by MandiOhlinger** [comment]
@mattwailes You are correct. We didn't do a good job of explaining that. Both articles are updated, and explain the situation better. The changes should be live tomorrow sometime. Thanks for questioning.
