### ISSUE TITLE
License SKU list out of date.

### ISSUE THREAD

**Issue by jawboston** [MicrosoftDocs/memdocs#627]
This doc needs to be updated to reflect the fact that Business Prem includes defender ATP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d129246-93fe-04ec-0e49-8e9ac1c910a8
* Version Independent ID: 66d3e475-e2b9-1974-f04a-2ae8b31f96bd
* Content: [Use Microsoft Defender ATP in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/advanced-threat-protection)
* Content Source: [memdocs/intune/protect/advanced-threat-protection.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/advanced-threat-protection.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
Content updated to reflect Microsoft 365 Business Premium.
