### ISSUE TITLE
Minor tweak

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/memdocs#628]
This isn't a big deal, but the troubleshooting steps start with "To collect your Win32 app installation logs, first follow the steps provided in the section App troubleshooting details. Then, continue with the following steps:"

The linked page is 5 steps that boil down to "Select the device that you want to troubleshoot from the Devices list"

So if you add these two steps someone doesn't have to read through the linked article to get to the "Managed Apps" section of a specific device.
1. Click Users > pick a device
2. Select Managed Apps from selected device pane. (now proceed to the next step)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 652beaa2-6bc5-728b-dfca-2c34ed568b08
* Version Independent ID: 7a6b8bcb-dc6c-ffb0-00e6-d0bbcbb446a0
* Content: [Troubleshoot app installation issues - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/troubleshoot-app-install#win32-app-installation-troubleshooting)
* Content Source: [memdocs/intune/apps/troubleshoot-app-install.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/troubleshoot-app-install.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@jonwbstr - Thanks for the feedback. I looked this over. As the steps currently are, they provide the detail that new admins can benefit from, which is important for troubleshoot steps. Thank you.
