### ISSUE TITLE
Please clarify statement

### ISSUE THREAD

**Issue by matthewjlevy** [MicrosoftDocs/memdocs#63]
“Devices are blocked for Conditional Access with the exception of Windows 10 1803+”. What does that statement mean exactly?

Windows 10 devices &lt; 1803 enrolled into Intune using a DEM account will not be evaluated by any Conditional Access policies? Will access just be blocked to any cloud app regardless? What happens with non-Windows 10 devices enrolled using a DEM account with respect to Conditional Access Policies?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7786d9c0-55b0-9bff-fc0a-f4ee70ee0615
* Version Independent ID: cf0c17a0-fdc7-e0af-db82-913e36d2ec7c
* Content: [Enroll devices using a device enrollment manager account - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-manager-enroll?source=docs#feedback)
* Content Source: [memdocs/intune/enrollment/device-enrollment-manager-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/device-enrollment-manager-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
(6935722)

**Comment by ErikjeMS** [comment]
Repinged PM...

**Comment by ErikjeMS** [comment]
Repinged PM

**Comment by MandiOhlinger** [comment]
@matthewjlevy Hey - I think the that text is referring to bulk enrollment. I clarified the text. Changes should be live later today.

If you're not aware, the [Windows enrollment deployment guide](https://docs.microsoft.com/mem/intune/fundamentals/deployment-guide-enrollment-windows) may be a good read.
