### ISSUE TITLE
Should this profile be deployed to the User collection or device collection?

### ISSUE THREAD

**Issue by santoshseth** [MicrosoftDocs/memdocs#633]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5453486-e657-0e95-f0cf-73c06928ed40
* Version Independent ID: 7e9fe802-25b6-c3c1-2257-7f5003a4f3d7
* Content: [OneDrive for Business Profiles - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/compliance/deploy-use/onedrive-profile)
* Content Source: [memdocs/configmgr/compliance/deploy-use/onedrive-profile.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/compliance/deploy-use/onedrive-profile.md)
* Product: **configuration-manager**
* Technology: **configmgr-compliance**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @santoshseth, you can deploy a ODfB profile to either a user or a device collection.
