### ISSUE TITLE
App already installed?

### ISSUE THREAD

**Issue by OffColour** [MicrosoftDocs/memdocs#636]
If the App you want to install from Company Portal is already installed on the iPhone by the device owner (BYOD User enrollment), then it just takes them to the installed one rather than installing a separate copy for work.
Is this expected behaviour?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf5828d-2528-a52c-6526-f860f81fbf6c
* Version Independent ID: acbd3994-1978-6f7c-9e98-90c769ae5643
* Content: [Add iOS store apps to Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/store-apps-ios)
* Content Source: [memdocs/intune/apps/store-apps-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/store-apps-ios.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
We have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. If you have continue to have questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

Please use the above channels if you don't already have a solution.

**Comment by Erikre** [comment]
@OffColour - From our product team:
_Yes, that is expected behavior. Since the app is already installed on the device, and it's detected, there's no need to install it twice._
