### ISSUE TITLE
Microsoft Connected Cache is not supported on Cloud Distribution Point 

### ISSUE THREAD

**Issue by Navneet-Singh-Ghura** [MicrosoftDocs/memdocs#637]
Microsoft Connected Cache is not supported on Cloud Distribution Point. 
Should it be documented?

**Comment by aczechowski** [comment]
Hi @Navneet-Singh-Ghura, we don't document everything that's not supported, that would be a long list. 😉 The cloud DP is an Azure PaaS. The Connected Cache options are only available with the on-prem DPs.
