### ISSUE TITLE
Azure AD Join vs. Azure AD join

### ISSUE THREAD

**Issue by ATR-Master** [MicrosoftDocs/memdocs#638]
Sorry Ladys and Sir's
but what the hell is the difference between 
![grafik](https://user-images.githubusercontent.com/38193570/90413863-564ce500-e0af-11ea-98a9-a517aaccf1fe.png)
in Text:
Azure Active Directory Join and Azure Active Directory join
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0f572e0-1bc0-6f14-7f60-989eb67fb7e7
* Version Independent ID: e4ec5b25-d9a6-d260-6cf6-ff4f3eb3ecb8
* Content: [Windows Autopilot for white glove deployment](https://docs.microsoft.com/en-us/mem/autopilot/white-glove)
* Content Source: [memdocs/autopilot/white-glove.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/white-glove.md)
* Product: **w10**
* GitHub Login: @greg-lindsay

**Comment by ErikjeMS** [comment]
@ATR-Master One of those should say Hybrid. It's been fixed. Thanks!
