### ISSUE TITLE
Unable to use module on macOS

### ISSUE THREAD

**Issue by scheblein** [MicrosoftDocs/memdocs#640]
I've successfully installed powershell 7 on macOS Catalina 10.15.6 using homebrew - brew cask install powershell from https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-macos.

I'm successfully able to install the AzureAD module - using Install-Module -Name AzureAD.

I'm unable to import the AzureAD module in order to run these samples:

PS /Users/ascheble> Import-Module -Name AzureAD
Import-Module: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5e14127-3656-1554-7b19-6e6122e6ea0f
* Version Independent ID: 8f48f0a7-258d-9b45-c3b2-663269d32e31
* Content: [How to use Azure AD to access Intune APIs in Microsoft Graph - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/developer/intune-graph-apis)
* Content Source: [memdocs/intune/developer/intune-graph-apis.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/developer/intune-graph-apis.md)
* Service: **microsoft-intune**
* Sub-service: **developer**
* Technology: ****
* GitHub Login: @dougeby
* Microsoft Alias: **dougeby**

**Comment by MandiOhlinger** [comment]
@scheblein If you're still having this issue, we suggest posting to the [Microsoft Q&A](https://docs.microsoft.com/answers/products/enterprise-mobility-security) to see if others have this same issue. As always, you can open a [support request](https://docs.microsoft.com/intune/get-support).

If you resolved this issue, it'd be great if created a pull request with your resolution. We want and encourage community contributions.
