### ISSUE TITLE
Why are we referencing Server 2003 (v2) cert template in our docs for the CMG cert requirement?

### ISSUE THREAD

**Issue by CJRicard** [MicrosoftDocs/memdocs#642]
Why are we referencing Server 2003 (v2) cert template in our docs?  Shouldn't it now be Server 2008 (v3) with the advent of the CMG and the deprecation of the cloud dp?

**Comment by aczechowski** [comment]
Hi @CJRicard, two things:
- ConfigMgr support for v3 certs is in a separate article: [CNG certificates overview](https://docs.microsoft.com/mem/configmgr/core/plan-design/network/cng-certificates-overview)
- We have an internal work item to revamp our PKI articles (internal reference 2841906)
Thanks for the feedback.
