### ISSUE TITLE
Computer\HKEY_LOCAL\MACHINE\Software\WINRAR

### ISSUE THREAD

**Issue by aavdberg** [MicrosoftDocs/memdocs#648]
Computer\HKEY_LOCAL\MACHINE\Software\WINRAR in the not correct has to be \HKEY_LOCAL\MACHINE\Software\WINRAR

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de85c97e-b22f-1b7d-0fb2-18e2c2b1970d
* Version Independent ID: 0744e16d-47f6-f1f4-0fbd-41074136e110
* Content: [Add and assign Win32 apps to Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-win32-app-management)
* Content Source: [memdocs/intune/apps/apps-win32-app-management.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/apps-win32-app-management.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
I opened the Registry Editor in Windows 10 and confirmed that the path starts with "Computer\HKEY_LOCAL_MACHINE".

If you have continue to have questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

Please use the above channels if you don't already have a solution.
