### ISSUE TITLE
App selective wipe for hybrid Azure AD-joined devices

### ISSUE THREAD

**Issue by weyCC81** [MicrosoftDocs/memdocs#65]
Is this also possible for hybrid Azure AD-joined devices?
(I can not find the device on the assigned user)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e31bcb79-bae1-8398-9a3d-0559e4445e23
* Version Independent ID: ffb05284-00c1-a071-9683-402b1ce93e3c
* Content: [How to wipe only corporate data from apps - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-selective-wipe#feedback)
* Content Source: [memdocs/intune/apps/apps-selective-wipe.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/apps-selective-wipe.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
We have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. If you have continue to have questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

Please use the above channels if you don't already have a solution.
