### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by philhorn** [MicrosoftDocs/memdocs#654]
[Enter feedback here]
In the section called 
**Install the Intune Certificate Connector**
Step 4.b: you might add a blurb that the NDESConnectorSetup must "Run as administrator" or the installation will fail with an obscure error.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9107185-e6c7-b178-4e22-819797fe4880
* Version Independent ID: 1153b441-94f0-b471-52a2-3cf556c68581
* Content: [Configure infrastructure to support SCEP certificate profiles with Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/certificates-scep-configure#install-and-bind-certificates-on-the-server-that-hosts-ndes)
* Content Source: [memdocs/intune/protect/certificates-scep-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certificates-scep-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@philhorn   Thanks for the feedback. This was an easy clarification to add and will appear in the live content later today. Thanks!
