### ISSUE TITLE
Clarification - User Certificate

### ISSUE THREAD

**Issue by philhorn** [MicrosoftDocs/memdocs#655]
[Enter feedback here]
Hey -
In the section:
**Create the SCEP certificate template**
... to create a new custom template.
Copy an existing template (**_like the User template_**) and then update the copy to use as the NDES template.

It may be better to specify a different existing template - I had copied the User template as specified, but then I could not get the machine to request the cert, because it's a User cert and not a Machine cert.  When I went back and copied the Web Server template, I was able to request a proper cert from the wizard.  
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9107185-e6c7-b178-4e22-819797fe4880
* Version Independent ID: 1153b441-94f0-b471-52a2-3cf556c68581
* Content: [Configure infrastructure to support SCEP certificate profiles with Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/certificates-scep-configure#install-and-bind-certificates-on-the-server-that-hosts-ndes)
* Content Source: [memdocs/intune/protect/certificates-scep-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certificates-scep-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@philhorn   I can’t recall where the focus on the *User* template came from, though its been around for a long time. I've made this change and expect this suggestion will smooth things for others as well. You’ll see this change in content later today.
