### ISSUE TITLE
Typo on "VMWare WorkspaceONE"

### ISSUE THREAD

**Issue by brookspeppin** [MicrosoftDocs/memdocs#656]
Small typo on "VMWare WorkspaceONE UEM (previously known as AirWatch)". It should be 
**VMware Workspace ONE UEM** (previously known as AirWatch)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d16c28db-1e8e-31fa-6127-3050a2940422
* Version Independent ID: 4cf9a244-1ae5-1637-48f7-3f503d400da6
* Content: [What's new in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new#week-of-august-17-2020)
* Content Source: [memdocs/intune/fundamentals/whats-new.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/whats-new.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@brookspeppin Thanks! I'll fix it today.

**Comment by brookspeppin** [comment]
hi @ErikjeMS. I see you closed this 5 days ago but don't see the changes yet. When will that happen?

**Comment by ErikjeMS** [comment]
@brookspeppin I see the changes. Did you refresh the page?

**Comment by brookspeppin** [comment]
@ErikjeMS It's not changed here: https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new#set-device-compliance-state-from-third-party-mdm-providers

It is changed here though: https://docs.microsoft.com/en-us/mem/intune/protect/device-compliance-partners#supported-device-compliance-partners:

**Comment by ErikjeMS** [comment]
@brookspeppin If you are talking about the space between workspace ONE, it is fixed in the first link you provide. Have you tried clearing your cache?

**Comment by brookspeppin** [comment]
And the lowercase "w" - VM**w**are Workspace ONE UEM

**Comment by ErikjeMS** [comment]
@brookspeppin OK. I'll fix it. Thanks!
