### ISSUE TITLE
login.live.com opens up a lot of consumer services we'd otherwise block

### ISSUE THREAD

**Issue by AquinoN** [MicrosoftDocs/memdocs#658]
login.live.com is currently blocked by our firewall.  There's a discussion on why this URL is required because opening it will enable devices/users to get to consumer services that we do not wish them to access.
Why is this URL required and is there a way to keep Desktop Analytics working without it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55ba9622-311f-0c2c-bce3-f0510a4d2b79
* Version Independent ID: 49d1ca0a-b8b0-bfa9-c735-d45c7118ac9a
* Content: [Enable data sharing - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/desktop-analytics/enable-data-sharing)
* Content Source: [memdocs/configmgr/desktop-analytics/enable-data-sharing.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/desktop-analytics/enable-data-sharing.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @AquinoN for the feedback. What we currently have published is the best description we have. To explain in a different way: Windows diagnostic data leverages login.live.com endpoint to generate the device ID. Without a device ID we can’t reliably get diagnostic data or compute insights for that device so it’ll be dropped from the portal.
As the article says, you can use policy to disable the Microsoft Account functionality in Windows and still allow the endpoint. If you're still not comfortable with that, then unfortunately you shouldn't use Desktop Analytics on that device.
If you have further feedback about the requirement for this endpoint, I suggest filing [product feedback](https://docs.microsoft.com/mem/configmgr/core/understand/find-help#product-feedback).
