### ISSUE TITLE
Configuration conflict with device configuration endpoint protection

### ISSUE THREAD

**Issue by sveinungre** [MicrosoftDocs/memdocs#66]
How about adding some information about Intune configuration conflicts with device configuration endpoint protection if attack surface reduction rules aere configured there? If you enable the following settings in device configuration profile endpoint protection which is not available in security baseline you get conflict: Process creation from PSExec and WMI commands. Executables that don’t meet a prevalence, age, or trusted list criteria. Advanced ransomware protection.

Also could you make sure that the setting names are the same across security baselines and the device configuration profile endpoint protection?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f0f4d5d-fdd1-22e7-6372-9916b199209f
* Version Independent ID: caeb9f8b-30ad-7f02-4740-56522b2f9b1b
* Content: [Intune security baselines settings for Windows 10 MDM - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/security-baseline-settings-mdm-all?pivots=mdm-may-2019#feedback)
* Content Source: [memdocs/intune/protect/security-baseline-settings-mdm-all.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/security-baseline-settings-mdm-all.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@sveinungre    Thanks for this feedback.  This article is a reference article focused on providing the details about the available baseline settings as they appear in the UI, with a touch of extra detail to try to clarify them, when possible. For information about identifying or resolving settings conflicts for devices, see the following article:  
-	[Troubleshoot policies and profiles](https://docs.microsoft.com/mem/intune/configuration/troubleshoot-policies-in-microsoft-intune)
-	[Security Baselines](https://docs.microsoft.com/mem/intune/protect/security-baselines)
-	[Monitor your baselines](https://docs.microsoft.com/mem/intune/protect/security-baselines-monitor#troubleshoot-using-per-setting-status)

Currently, the first article is the most relevant as it applies broadly to Intune which has several different features and processes that can all configure the same settings on devices. The other articles have very light mention and will receive minor updates soon to make the connection to the troubleshooting guidance more clear.   

As to settings names, that is feedback I recommend you pass on directly to our engineering team through the [Intune User Voice](https://microsoftintune.uservoice.com/forums/291681-ideas) feedback system, (I've provided similar feedback myself).  As the engineering team updates settings across Intune, we should begin to see consistency and clarity in the setting names, information text, and options – regardless of where that setting lives (like Security baselines, Device Configuration, Device Compliance, etc.).
