### ISSUE TITLE
Not applying to group

### ISSUE THREAD

**Issue by TheDapperDevin** [MicrosoftDocs/memdocs#661]
Hello!

I set this up and have it applied to a custom group containing just my user profile and the test device in question. Our goal here is to block the default installed apps from running. I set it up to include things like Facebook and YouTube. So far, I have not even seen it apply to the device, as the device and user status are still empty, even after forcing a sync from the phone. Any idea what the issue could be?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0418958-151f-4b4c-814e-73684132a3c3
* Version Independent ID: 4d6178a6-61ab-6a0e-8f20-719932d67077
* Content: [Microsoft Intune policy to allow/block apps for Samsung Knox](https://docs.microsoft.com/en-us/mem/intune/configuration/samsung-knox-apps-allow-block)
* Content Source: [memdocs/intune/configuration/samsung-knox-apps-allow-block.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/samsung-knox-apps-allow-block.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@TheDapperDevin GitHub issues aren't monitored by the support teams or support community. We suggest posting your issue on the [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community and MVPs, who are very experienced, knowledgeable, and helpful.

Or, if you want help from Microsoft, you can open a support case. See [get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support).
