### ISSUE TITLE
Windows 10 Remote Lock

### ISSUE THREAD

**Issue by kktamang** [MicrosoftDocs/memdocs#666]
[Enter feedback here]
When Windows 10 Remote Lock option will come in Intune. It will really help Enterprise to check and counter unhealthy Windows 10 machine. Also, it will help to protect the device from data leakage from disgruntled employee or protect data in case of laptop is lost.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c79f5e46-0615-682c-0368-5a14cfa738e7
* Version Independent ID: 08094776-efc7-d7b1-0b82-0aee1dac5634
* Content: [Lock devices with Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/remote-actions/device-remote-lock?source=docs#feedback)
* Content Source: [memdocs/intune/remote-actions/device-remote-lock.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/remote-actions/device-remote-lock.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@kktamang To make feature requests, you can use [Microsoft Intune Feedback]( https://microsoftintune.uservoice.com/forums/291681-ideas). To see a list of upcoming features, you can check [Features in development](https://docs.microsoft.com/en-us/mem/intune/fundamentals/in-development).  I'm closing this issue as there's nothing actionable for docs at this time.
