### ISSUE TITLE
Grammatical error

### ISSUE THREAD

**Issue by fredskis** [MicrosoftDocs/memdocs#667]
In the **Create the profile** section, step 7, wrong use of "your" instead of "you're"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed9033d1-2230-25a0-39c2-4a6399baeb5c
* Version Independent ID: ac8d9122-d136-9e4d-4416-cd015a058662
* Content: [Delivery Optimization settings for Windows 10 in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/delivery-optimization-windows#feedback)
* Content Source: [memdocs/intune/configuration/delivery-optimization-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/delivery-optimization-windows.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@fredskis  Thanks, we've published a fix for that.
