### ISSUE TITLE
Missing/wrong information for prerequisites.

### ISSUE THREAD

**Issue by larsinus** [MicrosoftDocs/memdocs#668]
Requirement section should have another section that no custom ports can be used for SQL.
Or, if that is supported; how to type the connection string e.g. <server name>,12345

When we try starting CEViewer.exe from the site server with a user that's CM admin and a SQL admin we get this error message:
"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured for remote connections."
The SQL server is online.
We can remotely connect to it.
Using default instance, but custom port.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28e7af11-76d5-355f-c4a7-86ac19332150
* Version Independent ID: 74fd3c4e-4b64-55b9-110f-3d2d1b286b3f
* Content: [Collection Evaluation Viewer - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/support/ceviewer)
* Content Source: [memdocs/configmgr/core/support/ceviewer.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/support/ceviewer.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
@larsinus just checked with one of the dev. There isn't a way to do a custom SQL port for CEViewer. I'll add that to the requirements.
Good new, is that starting in 2103, CEViewer is built into the console.
