### ISSUE TITLE
This page is not accurate and needs a re-write

### ISSUE THREAD

**Issue by theprez1980** [MicrosoftDocs/memdocs#669]
The headers for Android MDM and Android MDM Enterprise are not correct.    The steps also do not exactly match the Knox KME portal.   I'd recommend someone obtain Knox KME access and re-author the article to match and include screenshots.

Selecting Microsoft Intune within KME, auto populates this APK:  https://play.google.com/managed/downloadManagingApp?identifier=setup

The steps call out a different APK, but the auto populated one with the matching JSON for the QR code works fine.    

Article is causing a lot of confusion as it currently is.   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91c6e4c4-96e2-14c6-8028-a2b947740e73
* Version Independent ID: 94bd0e7c-03c8-151d-6569-5d12985824e6
* Content: [Automatically enroll Android devices using Samsung's Knox Mobile Enrollment - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/android-samsung-knox-mobile-enroll)
* Content Source: [memdocs/intune/enrollment/android-samsung-knox-mobile-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/android-samsung-knox-mobile-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Updates to this article are in our work queue. Thanks!
