### ISSUE TITLE
MSI or .EXE for SCCM client deployment?

### ISSUE THREAD

**Issue by edlang** [MicrosoftDocs/memdocs#673]
re: the section on creating the SCCM app in the MEM console:

"For the App package file, browse to the location of the Configuration Manager file ccmsetup.msi, and then select Open > OK. For example, C:\Program Files\Microsoft Configuration Manager\bin\i386\ccmsetup.msi"

Has this been tested? I've used the <SITECODE>\Client\x64\client.msi file as there is no ccmsetup.msi, and I see this error on the clients:

"Product: Configuration Manager Client -- Error 25502. Setup was not launched from CcmSetup.exe. Please run CcmSetup.exe to install ConfigMgr Client."

If we need to use ccmsetup.exe, I assume this means we need to create an .intunewin package, which is a very different approach to packaging. Could you please confirm which method we should use?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d01fcdfb-06ea-51c1-890c-5ccf63ae8f36
* Version Independent ID: d7766b63-8462-c281-d74b-8e2c5fae6103
* Content: [Tutorial: Enable co-management for internet devices - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/comanage/tutorial-co-manage-new-devices)
* Content Source: [memdocs/configmgr/comanage/tutorial-co-manage-new-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/comanage/tutorial-co-manage-new-devices.md)
* Product: **configuration-manager**
* Technology: **configmgr-comanage**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @edlang, sorry you're having problems. You definitely need to use ccmsetup.msi. That file has been around for many years, as it was also for installing the client via group policy (which could only install MSI apps). The example file path that's given is the default installation directory for a Configuration Manager site. If your site uses the default path, then the file should be there on the site server. You do need to be an admin on the site server to access that folder.
