### ISSUE TITLE
Local lockscreen image

### ISSUE THREAD

**Issue by elang-bmrn** [MicrosoftDocs/memdocs#678]
The URI parameter for the lockscreen background in the device restrictions configuration profile does not permit file URIs, which would let us reference an image copied to the device.

Could you please add support for these local files? Alternatively, please update the documentation to support the supported URI 
schemes.

An example of a URL that should work (according to the underlying policy CSP documentation) is file:///C:/windows/web/Screen/img100.jpg.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7874ff8b-727f-b013-27f8-fd714ebb53a5
* Version Independent ID: 05674b42-613e-d54d-2895-1f2db41b613a
* Content: [Device restriction settings for Windows 10 in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-windows-10)
* Content Source: [memdocs/intune/configuration/device-restrictions-windows-10.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/device-restrictions-windows-10.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@elang-bmrn PM don't monitor GitHub issues. They do use and monitor [Uservoice](https://microsoftintune.uservoice.com/forums/291681-ideas) for feature improvements.

Are you referring to **Locked screen experience** > **Locked screen picture URL (desktop only)** setting?
