### ISSUE TITLE
Citrix Secure Mail is not available

### ISSUE THREAD

**Issue by new-kirte** [MicrosoftDocs/memdocs#68]
Citrix Secure Mail is not available in the list of Intune supported apps for MAM policies

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02165898-ec07-86e1-adc5-18f60bec9689
* Version Independent ID: 7b6c64c4-3304-42b0-079a-7dee609c5e4f
* Content: [Supported Microsoft Intune apps](https://docs.microsoft.com/en-us/mem/intune/apps/apps-supported-intune-apps#feedback)
* Content Source: [memdocs/intune/apps/apps-supported-intune-apps.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/apps-supported-intune-apps.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@new-kirte - I just checked. Please take a second look. This is where I looked:
https://docs.microsoft.com/mem/intune/apps/apps-supported-intune-apps

**Comment by new-kirte** [comment]
@Erikre, please go to Intune portal, create a new application protection policy аnd try to add Citrix Secure App. The documentation is confusing and does not match the product. I'm going to submit a new issue since you hastily closed this one.
