### ISSUE TITLE
How can we edit group tags after we upload a hash?

### ISSUE THREAD

**Issue by dbdmora** [MicrosoftDocs/memdocs#683]
When clicking on a device, I can enter a name for the group tag, I hit save but it does not save it.  Is there a work around to add group tags after a hash device has been uploaded?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97ce79c0-0014-f6f0-95f7-58574bfdefb3
* Version Independent ID: 40b3877e-a094-8d05-c95b-ca842c5ca8ce
* Content: [Enroll devices with Windows Autopilot - Microsoft Intune](https://docs.microsoft.com/en-us/mem/autopilot/enrollment-autopilot#add-devices)
* Content Source: [memdocs/autopilot/enrollment-autopilot.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/enrollment-autopilot.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@dbdmora Thanks for taking the time to share this with the Intune documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a few options available to provide the best level of support for this:   

  - Post on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.   

  - Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.    

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.   

I'm closing this issue as there's nothing actionable for docs at this time.
