### ISSUE TITLE
"Persist content in the client cache" should be more specific in regard of content instance/version

### ISSUE THREAD

**Issue by rrifonasmsft** [MicrosoftDocs/memdocs#684]
While the option "Persist content in the client cache" works as advertised, the content is persisted only if the app needs some action (install / repair / uninstall). 

If the app is already installed **OR** if the content is updated at any point (content id is changed), it won't be cached again and in case of content update, the actual content will be marked as "tombstoned" and deleted on schedule or if the customer clear the cache.

Some customers might expect that the content will be downloaded or updated when needed, which is not true. It would be good to document that only the specific instance of a content already executed will be stored in cache.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 791c915c-953e-a9a5-c85a-ec7e06098473
* Version Independent ID: d9e0b4fd-987d-2b12-a6be-3f2651ef214f
* Content: [Create applications - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/apps/deploy-use/create-applications)
* Content Source: [memdocs/configmgr/apps/deploy-use/create-applications.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/apps/deploy-use/create-applications.md)
* Product: **configuration-manager**
* Technology: **configmgr-app**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @rrifonasmsft for the feedback

**Comment by aczechowski** [comment]
I added a tip for this, thanks again. The change should publish live later today.
