### ISSUE TITLE
Starting in 1910

### ISSUE THREAD

**Issue by gflewis** [MicrosoftDocs/memdocs#690]
Computers did not exist in 1910.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0847f1f-4207-1380-4c05-0b9b9b4bf6c9
* Version Independent ID: 0dd578d7-5a6d-482d-04d6-cc2b29f5b9ec
* Content: [Microsoft Endpoint Configuration Manager FAQ - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/understand/microsoft-endpoint-manager-faq)
* Content Source: [memdocs/configmgr/core/understand/microsoft-endpoint-manager-faq.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/understand/microsoft-endpoint-manager-faq.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @gflewis I assume you're referring to the _year_ 1910? 😆 
Configuration Manager current branch _versions_ identify the year and month of that version's release (YYMM). For example, version 1511 identifies November 2015 (the month when Configuration Manager current branch was first released to manufacturing). Later updates have version names like 2002, which indicates an update that was created in February 2020.
