### ISSUE TITLE
Wrong error message for aad global admin without Intune license

### ISSUE THREAD

**Issue by jingjing-dot-com** [MicrosoftDocs/memdocs#691]
Hi

For link [Tutorial: Enable co-management for existing Configuration Manager clients](https://docs.microsoft.com/en-us/mem/configmgr/comanage/tutorial-co-manage-clients), the error message for AAD global admin without Intune license is incorrect.
It is misleading our customers. We have tested in both customer lab and internal lab, the error is  'An unanticipated error occurred. Your IT department may be able to help'. Please help to update the message.

**Permissions**
_Throughout this tutorial, use the following permissions to complete tasks:
    An account that is a domain admin on your on-premises infrastructure
    An account that is a full administrator for all scopes in Configuration Manager
    An account that is a global administrator in Azure Active Directory (Azure AD)
        Make sure you've assigned an Intune license to the account that you use to sign in to your tenant. Otherwise, sign in fails with the error message **"User not recognized"**._  <-- This message needs to be changed to 'An unanticipated error occurred. Your IT department may be able to help'.

Thanks,
Jingjing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b813a55b-0679-f80c-983f-782b394c748c
* Version Independent ID: ea738339-f10c-10f2-91ab-a2b87b342b12
* Content: [Tutorial: Enable co-management for existing clients - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/comanage/tutorial-co-manage-clients)
* Content Source: [memdocs/configmgr/comanage/tutorial-co-manage-clients.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/comanage/tutorial-co-manage-clients.md)
* Product: **configuration-manager**
* Technology: **configmgr-comanage**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @jingjing-dot-com for the feedback, I'm making this change, as well as to a similar reference in the main list of prerequisites.
