### ISSUE TITLE
SQL Query incorrect

### ISSUE THREAD

**Issue by koenraadrens** [MicrosoftDocs/memdocs#692]
v_LU_SoftwareList_Editable doesn't contain SoftwareCode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23fda686-e17b-01ca-1e3e-fdbbe7a5b0ac
* Version Independent ID: 8c0a9e98-1941-629d-9c10-e2586e8b0f9f
* Content: [Sample queries for asset intelligence - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/develop/core/understand/sqlviews/sample-queries-asset-intelligence-configuration-manager)
* Content Source: [memdocs/configmgr/develop/core/understand/sqlviews/sample-queries-asset-intelligence-configuration-manager.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/develop/core/understand/sqlviews/sample-queries-asset-intelligence-configuration-manager.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @koenraadrens for the feedback. Honestly, all of this SQL Views content was copied over mostly as-is from 2007 docs to preserve them. We'll have to do some deeper investigation to determine how to fix this. If you (or anyone else) has suggestions on how to fix this query, please let us know. You can also directly submit it by editing the file and making a contribution. For more information on how to do that, see [How to contribute to docs](https://docs.microsoft.com/mem/configmgr/core/understand/use-docs#bkmk_contribute).
