### ISSUE TITLE
"General NDES message" Issue

### ISSUE THREAD

**Issue by beanmachine-20** [MicrosoftDocs/memdocs#695]
After installing the Intune Connector, the NDES URL (https://FQDN/certsrv/mscep/mscep.dll) was still returning the "General NDES Message" instead of 403 message as described here - https://docs.microsoft.com/en-us/mem/intune/protect/troubleshoot-scep-certificate-device-to-ndes#general-ndes-message

Install logs indicated the Connector had installed successfully. Reinstallation gave same results. Server rebooted several times etc

What resolved the issue for me was to run an iisreset after installing the Connector. 403 message was then returned. Can this be added to recommended fixes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b578b342-2f38-2aba-13b3-1daa155d6f7b
* Version Independent ID: 4d6af3d7-c65e-0d38-9df2-8096ec36cc52
* Content: [Troubleshoot managed device to NDES communication in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/troubleshoot-scep-certificate-device-to-ndes#general-ndes-message)
* Content Source: [memdocs/intune/protect/troubleshoot-scep-certificate-device-to-ndes.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/troubleshoot-scep-certificate-device-to-ndes.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@beanmachine-20   Thanks for that feedback. We have IIS Reset in a few places in that article, so I can add that in as a possible step to try for that general message, should the other resolution not succeed.
