### ISSUE TITLE
RBAC documentation for Deploying ATP policies?

### ISSUE THREAD

**Issue by PotentEngineer** [MicrosoftDocs/memdocs#698]
Can information around required RBAC permissions be added for deploying policies to collections? Reference this [Twitter thread](https://twitter.com/PotentEngineer/status/1299420328511373315?s=20) please. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ea5be34-a969-e46b-4fc0-ccca775265bb
* Version Independent ID: 209b8abb-88f7-f3a0-385a-56a6a9fdce23
* Content: [Microsoft Defender Advanced Threat Protection - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/protect/deploy-use/defender-advanced-threat-protection?source=docs)
* Content Source: [memdocs/configmgr/protect/deploy-use/defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/protect/deploy-use/defender-advanced-threat-protection.md)
* Product: **configuration-manager**
* Technology: **configmgr-protect**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @PotentEngineer, thanks for filing this feedback. 😁  I checked with engineering:

> admin should have Endpoint Protection Manager Rbac role. 
> They seem to be lacking some collection permissions on their custom permissions. It's possible that "Deploy Configuration Items" needs to be turned on as well as Configuration Policy Create/Delete.

**Comment by aczechowski** [comment]
I'm going to add the bit about the role, but not anything about specific permissions. We generally don't get down into that level of detail (unfortunately, just don't have the resources for that sort of detailed effort)
