### ISSUE TITLE
Primary vs Enrolled

### ISSUE THREAD

**Issue by KingDrewcifer** [MicrosoftDocs/memdocs#7]
Does this mean that the Enrolled User can be removed from the directory without impacting device enrollment if the primary user is changed before hand? Currently a device becomes unmanaged if the user that is set as the Enrollment User is deleted or unlicensed. Or is this just the foundation for targeting Primary Users devices instead of just the user for deployments ala SCCM?  Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d40af25-83c1-4041-abde-19803c3352f1
* Version Independent ID: e089f511-d044-7511-e096-b23c7ac0cc18
* Content: [Find the primary user of a Microsoft Intune device.](https://docs.microsoft.com/en-us/mem/intune/remote-actions/find-primary-user#feedback)
* Content Source: [memdocs/intune/remote-actions/find-primary-user.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/remote-actions/find-primary-user.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
(6488377)

**Comment by TiganSan** [comment]
Any update on the previous questions?
Also, how can I use the Intune Primary user info for device affinity in SCCM?  All the documets so far say that it can be used but none of them talks about how to configure SCCM to use the primary user assignment from Intune!
Thx

**Comment by ErikjeMS** [comment]
Repinged PM...

**Comment by ErikjeMS** [comment]
@TiganSan Here's the response from the PM:
Removing a user who shows as the “Enrolledby” user does not impact the management state of the device. You can remove this user from the directory or remove their license at any point in time; either before changing the Primary User or after changing the Primary User. The Primary user is currently used to improve single-user device experiences such as Company Portal user experiences and the Troubleshooting blade in the MEM console.
