### ISSUE TITLE
Free trial has expired

### ISSUE THREAD

**Issue by henrypi73** [MicrosoftDocs/memdocs#70]
Hi , under sign in to Intune, I get this error has expired: Visit the Intune Sign-up page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c3f2675-9769-6b63-3ce8-3c7eb1c6c703
* Version Independent ID: bdd28d63-4fc5-6e2d-b54e-2225896ce493
* Content: [Sign up or sign in to Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/account-sign-up#feedback)
* Content Source: [memdocs/intune/fundamentals/account-sign-up.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/account-sign-up.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@henrypi73 Thanks for taking the time to share this with the Intune documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a few options available to provide the fastest level of support for this:   
- Post on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.   
- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.   
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.   
I'm closing this issue as there's nothing actionable for docs at this time.
