### ISSUE TITLE
Typo and explanation

### ISSUE THREAD

**Issue by MarcoCibis** [MicrosoftDocs/memdocs#703]
There is a typo in the last sentence of spelling configuraion instead of configuration.

Further I would like that we clarify a bit more that pressing 15 times the back button also needed to exit the managed home screen.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff4c5218-bbe4-110c-c74d-3eed1179ac61
* Version Independent ID: b7c148dc-574b-fbed-7637-29699f3eb97a
* Content: [Configure the Microsoft Managed Home Screen app - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-configuration-managed-home-screen-app)
* Content Source: [memdocs/intune/apps/app-configuration-managed-home-screen-app.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-configuration-managed-home-screen-app.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by ChrisKibble** [comment]
Fixed by @Erikre in 4ef2c653c5fe0e44205755e9966fe59b3e00be00.  Should be OK to close.

**Comment by Erikre** [comment]
I agree about accessing the debug screen. I will research, but will close this issue in the meantime.
