### ISSUE TITLE
Update Intune documentation for automatic clean-up rule at https://docs.microsoft.com/en-us/mem/intune 

### ISSUE THREAD

**Issue by DP30110698** [MicrosoftDocs/memdocs#704]
Hello,

With reference to **Microsoft Case #:21340354**, Thanks for confirming that the clean-up rules does not trigger any retire or wipe actions and it just removes the entry from Intune console (referring: article shared by you which is written by Intune engineering team at [https://techcommunity.microsoft.com/t5/device-management-in-microsoft/using-intune-device-cleanup-rules-160/ba-p/377272](https://techcommunity.microsoft.com/t5/device-management-in-microsoft/using-intune-device-cleanup-rules-160/ba-p/377272) ). 

There is one KB article in Microsoft documentation (refer: https://docs.microsoft.com/en-us/mem/intune/remote-actions/devices-wipe#automatically-delete-devices-with-cleanup-rules  ) which is currently not documented clearly explaining  this concept of clean-up rule and the reason behind it. 

Please update this online KB article [https://docs.microsoft.com/en-us/mem/intune/remote-actions/devices-wipe#automatically-delete-devices-with-cleanup-rules](https://docs.microsoft.com/en-us/mem/intune/remote-actions/devices-wipe#automatically-delete-devices-with-cleanup-rules) on Microsoft portal to reflect the actual behavior of clean-up rule as shown in below screenshot? Please include information from all 4 FAQs:  “**What happens behind the scene for Device Cleanup rules?**”, “**What device types get affected from this device cleanup?**”, “**Does this device cleanup rule perform device wipe or retire?**” and  “**Is it possible to have devices removed by  the device cleanup rule to come back in some scenarios?**”. 

![MS doc reference](https://user-images.githubusercontent.com/70588225/91863782-1bd96f80-ec8d-11ea-8f29-3cb9cd0dd760.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cdcc7fd-5bd9-1645-abf4-a73d3ea7adaa
* Version Independent ID: 5022b2ba-5fb0-18ce-9079-1b65ad0b2e17
* Content: [Retire or wipe devices using Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/remote-actions/devices-wipe#automatically-delete-devices-with-cleanup-rules)
* Content Source: [memdocs/intune/remote-actions/devices-wipe.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/remote-actions/devices-wipe.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by DP30110698** [comment]
Can you please share the TAT for this documentation update ?

**Comment by DP30110698** [comment]
@ErikjeMS - Can you please update the document KB and confirm back on this please ? It is open since 22 days !!

**Comment by ErikjeMS** [comment]
@DP30110698 Unfortuantely, due to resource constraints, we can't make any promises on how long it takes to triage, prioritize, research, approve, and publish any suggested changes.

**Comment by DP30110698** [comment]
> @DP30110698 Unfortunately, due to resource constraints, we can't make any promises on how long it takes to triage, prioritize, research, approve, and publish any suggested changes.

@ErikjeMS , could you please share at-least the tentative timelines to update this KB article ?

**Comment by ErikjeMS** [comment]
Investigating with PM... no ETA. I'll add a link to the techcommunity article in the meantime.
8732845

**Comment by ErikjeMS** [comment]
@DP30110698 I've updated the article with the new information. Thanks!
