### ISSUE TITLE
Omissions in the Subject alternative name section

### ISSUE THREAD

**Issue by LarryFluke** [MicrosoftDocs/memdocs#706]
The information in the Subject alternative name section is incomplete. It should explain the following:

1. User certs can also have DNS attributes.
2. User certs can also have values.
3. User cert values can be any variable. You should point to a list of the variables.
4. In "Device certificate type" you say the user has to **Add**, so it sounds like they have to click an Add button. There is a Delete button, but there is no Add button. this should be reworded.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30c444f9-5cc4-7276-6882-d6b32ee453ea
* Version Independent ID: f1ec96ac-c890-2ed1-ede4-179de4b4e4cc
* Content: [Use SCEP certificate profiles with Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/certificates-profile-scep)
* Content Source: [memdocs/intune/protect/certificates-profile-scep.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certificates-profile-scep.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@LarryFluke  Thanks for the PR submissions which fixes the issues you've noted. These updates will be live in the content later today.
