### ISSUE TITLE
Wording for requirements of conditional access

### ISSUE THREAD

**Issue by StereoRocker** [MicrosoftDocs/memdocs#707]
I refer to the following section:

"Conditional Access
Conditional Access is not available for Windows devices enrolled using bulk enrollment, with the exception of Windows 10 1803+."

This statement is confusing to me. Stating Conditional Access is not available for devices unrolled with bulk enrollment, then qualifying that actually it is if you're running 1803+ seems backwards. I think it could be worded differently:

"Conditional Access is available for Windows devices enrolled using bulk enrollment, running Windows 10 1803+."

or

"Conditional Access is available for Windows devices enrolled using bulk enrollment, but requires Windows 10 1803+."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84a280df-a5f1-1cc2-8e58-80e2db7110b9
* Version Independent ID: e263811d-a2f9-2ff9-24ff-0e2a2d58907a
* Content: [Bulk enrollment for Windows 10 - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/windows-bulk-enroll)
* Content Source: [memdocs/intune/enrollment/windows-bulk-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/windows-bulk-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@StereoRocker Thanks! I'll change this today.

**Comment by matthewjlevy** [comment]
What does "Conditional access is available for devices enrolled via bulk enrollment running Windows 11 or Windows 10, version 1803 and later." actually mean?
Is there some reference somewhere about target resource (bulk enrollment) that can be configured in a CA policy? Perhaps the reader should be directed to https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/concept-conditional-access-cloud-apps#user-actions
