### ISSUE TITLE
Rkendall75

### ISSUE THREAD

**Issue by Rkendall75** [MicrosoftDocs/memdocs#708]
[Enter feedback here]

The article claims that you can lock a Windows 10 PC my understand from other documentation this is not possible. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efa2b3a1-8393-c78b-0c73-ad0fe6350a61
* Version Independent ID: c1cac54e-811c-897e-dcaf-ffbd6f7e49c7
* Content: [Lock your device from the Company Portal](https://docs.microsoft.com/en-us/mem/intune/user-help/remote-lock-your-device-cpwebsite)
* Content Source: [memdocs/intune/user-help/remote-lock-your-device-cpwebsite.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/user-help/remote-lock-your-device-cpwebsite.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @Rkendall75, thank you for reaching out to the Intune docs team. You are correct--thanks for pointing this out. This article has been updated to remove Windows 10 PC from the list of devices.
