### ISSUE TITLE
Onboard the up-level devices

### ISSUE THREAD

**Issue by Blacksuit07** [MicrosoftDocs/memdocs#709]
In the documentation for Onboard the up-level devices it has the note on how to obtain the Workspace key and ID for SCCM v2002. However it does not specify the format it needs to be in. When I copy those entries into SCCM it gives me an error that the workspace key and workspace id does not meet the expected format. This format was copied exactly as shown from MS Defender ATP via securitycenter.windows.com>Settings>Onboarding, under Device management.

I was able to resolve the issue with Workspace key by removing the hyphens (-). I have not figured out how to resolve the format issue with the Workspace ID.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ea5be34-a969-e46b-4fc0-ccca775265bb
* Version Independent ID: 209b8abb-88f7-f3a0-385a-56a6a9fdce23
* Content: [Microsoft Defender Advanced Threat Protection - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/protect/deploy-use/defender-advanced-threat-protection?redirectedfrom=MSDN#bkmk_uplevel)
* Content Source: [memdocs/configmgr/protect/deploy-use/defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/protect/deploy-use/defender-advanced-threat-protection.md)
* Product: **configuration-manager**
* Technology: **configmgr-protect**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @Blacksuit07 for the feedback. I checked with engineering, and they are seeing different behavior (same as what we have doc'd). So can you please [file a frown](https://docs.microsoft.com/mem/configmgr/core/understand/find-help#product-feedback) in the Configuration Manager console? That action files a bug for the engineering team, and they can investigate further. When you do, if you can add a screenshot of your experience, to help them understand what might be different in your circumstance.

We may still add a tip to the article about the format. I'll let @mestew decide and followup

**Comment by mestew** [comment]
Decided we probably shouldn't add formatting tip. I suspect it's possible to introduce a formatting issue, especially with things like  hyphens or quotes if you paste into a Rich Text enabled editor then back into the admin center. Basically when using rich text it uses UTF-8 rather than ANSI.  I find this issue occasionally too when copying commands from Outlook to PowerShell.   #Please-close
