### ISSUE TITLE
Typos in the Azure Portal

### ISSUE THREAD

**Issue by Mlavieri** [MicrosoftDocs/memdocs#71]
There are two typos in the Azure portal related to the Intune Data warehouse under Microsoft Power BI Online section. 

3rd word also is spelt alse and custom on the second line is custome

![image](https://user-images.githubusercontent.com/1187519/78154237-a2013980-7401-11ea-8eb5-bb4fb1963b7d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65fe2aaf-92db-2355-58da-d713ff94bc1d
* Version Independent ID: a7f55b77-717d-62f0-1b4f-733539e6da02
* Content: [Connect to the Data Warehouse with Power BI - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/developer/reports-proc-get-a-link-powerbi)
* Content Source: [memdocs/intune/developer/reports-proc-get-a-link-powerbi.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/developer/reports-proc-get-a-link-powerbi.md)
* Service: **microsoft-intune**
* Sub-service: **developer**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@Mlavieri - Thanks for the feedback. I've passed this on to be fixed.
