### ISSUE TITLE
this section needs more clarity - "Configuring products for versions of Windows 10"

### ISSUE THREAD

**Issue by PaulKlerkx** [MicrosoftDocs/memdocs#710]
There are 17 possible products to choose just for the main Windows 10 build ( not including LTSB or S) then there are separate ones for the 1803, 1809 and 1903 builds for "servicing drivers, upgrade & servicing drivers or just the build, so in all there are around 25 possibilities and 15 for me on 1809 build.  It should be clearer on this page what to choose for each build.  at the moment, it is more of a best guess scenario.  
I would think for Windows 10 where we have just english, only the tick box for "windows 10, version 1809 and later" is required - does this include "upgrade and servicing drivers" or do I need to choose that one too? This page leaves doubts as to that choice.  
For example, are the GDR options still required if using config manager "Windows 10 Servicing". I believe all the anniversary , creators update and fall creators update options are for older builds, but that should be stated on this page.  

Maybe a Required Or Not table showing all the windows 10 product selection possible options down the left with build numbers across the top, then yes, no or if there is variability based on individual environments then  "if you have a config in your environment of ....xyz, then yes, otherwise no" or if it is too complex to include in the table, have a link to the information required to make the call.  

there is a product category of "Windows 10" does this include everything? it seems like it should so no other tickboxes required or does ticking this get Everything meaning ticking any of the other checkboxes is obsolete and if I have ticked the option for 1809 or later, does ticking the windows 10 option just add a tonne of extra stuff that I don't need because everything I need is covered by "1809 or later just looking for some clarity.  

![windows 10 products](https://user-images.githubusercontent.com/43360853/91924625-90a4bc00-ed16-11ea-82e7-6db69bdad34b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0150e043-d08d-bb83-e39a-7f27ba25198f
* Version Independent ID: fb88957c-9a3d-9cc8-c11a-c131c5137f56
* Content: [Configure classifications and products - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/sum/get-started/configure-classifications-and-products)
* Content Source: [memdocs/configmgr/sum/get-started/configure-classifications-and-products.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/sum/get-started/configure-classifications-and-products.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
@mestew made changes to the following articles that should address this feedback: 
- https://docs.microsoft.com/en-us/mem/configmgr/sum/get-started/configure-classifications-and-products#configuring-products-for-versions-of-windows-10
- https://docs.microsoft.com/en-us/mem/configmgr/sum/deploy-use/surface-drivers#bkmk_prod
