### ISSUE TITLE
Add required additional steps for the '5. Configure the Power BI Report Server' for an easier experience integrating Power BI 

### ISSUE THREAD

**Issue by ivaldesMSFT** [MicrosoftDocs/memdocs#713]
While configuring Power BI Report Server, and asides of the Encryption Keys restore operation, there are some steps that would be good to consider adding in this doc to avoid hiccups with the next '6. Add reporting services point role' step as:
- Add a note/reference on the new Report Server Instance (PBIRS) we need to configure
- Change Database step: need to change and select the existing ReportServer DB

And these 2 steps that will be needed in order to have the Add Role wizard successfully reading the new PBIRS Reporting Services server instance:
- Apply changes on the 'Web Service URL' and 'Web Portal URL', so that 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb13fff2-41ef-fa3d-4685-7b5b17c6b2a7
* Version Independent ID: 7e541e95-40de-b779-dd3e-b03f5fb5b911
* Content: [Integrate with Power BI Report Server - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/manage/powerbi-report-server#you-have-a-reporting-services-point)
* Content Source: [memdocs/configmgr/core/servers/manage/powerbi-report-server.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/manage/powerbi-report-server.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @ivaldesMSFT for the feedback. Let me check with the engineering team.

**Comment by aczechowski** [comment]
I added a tip based on our internal email. I basically referred to the existing verify steps from the [Configure reporting](https://docs.microsoft.com/mem/configmgr/core/servers/manage/configuring-reporting#verify-sql-server-reporting-services-installation) article.
This issue will auto close when my change merges, and then will go live with the next daily publishing cycle.
