### ISSUE TITLE
Intune in Azure Portal is no longer accessible

### ISSUE THREAD

**Issue by TommyKobber** [MicrosoftDocs/memdocs#714]
This page should be removed. Intune in the Azure portal was discontinued on July 31 2020

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 873ed0fb-9b09-fba1-ed4b-0a2a305634fc
* Version Independent ID: 2ead72fc-1bd7-7fd6-1632-7119815377d8
* Content: [Tutorial - Walkthrough Intune in the Azure portal - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/tutorial-walkthrough-intune-portal)
* Content Source: [memdocs/intune/fundamentals/tutorial-walkthrough-intune-portal.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/tutorial-walkthrough-intune-portal.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
We have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. Thanks for the feedback. The tutorial is now updated.
