### ISSUE TITLE
Intune and Company Portal apps on Full Managed android

### ISSUE THREAD

**Issue by cabastar** [MicrosoftDocs/memdocs#715]
Regarding this Note:
When an end user enrolls their Android Enterprise fully managed device, the Intune Company Portal app is automatically installed and the application icon may be visible to the end user. If the end user attempts to launch the Intune Company Portal app, the end user will be redirected to the Microsoft Intune app and the Company Portal app icon will be subsequently hidden.

I tested this on Android 9-  Samsung Note 20, and the Company Portal App icon will not subsequently be hidden.  In the first place I don't understand why there is a necessity to have 2 apps , can you just merge the functionality of both apps?  Please imagine how we are supporting our users, and telling them, please open Intune if you have a fully managed device.  Then saying open Company portal if you have a BYOD.  In the first place our users does not know even know the difference between the two.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5a2b8f0-f2a0-f4d6-94d9-06e6d9632f59
* Version Independent ID: 8c8d89cf-9ed7-bb02-2439-e7ce9bb03f0c
* Content: [Add and assign Managed Google Play apps to Android Enterprise devices - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-add-android-for-work)
* Content Source: [memdocs/intune/apps/apps-add-android-for-work.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/apps-add-android-for-work.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
We have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. If you have continue to have questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

Please use the above channels if you don't already have a solution.
