### ISSUE TITLE
Update on EJBCA Support for Intune

### ISSUE THREAD

**Issue by kombatminipig** [MicrosoftDocs/memdocs#716]
Hi there,

My name is Mike Agrenius Kushner, and I'm the product owner for EJBCA at PrimeKey Solutions. I just thought that I'd let you know that as of EJBCA 7.4.1, EJBCA Enterprise has built in support for enrollment through Intune. We've documented the instructions here: 

https://doc.primekey.com/ejbca/ejbca-integration/integrating-with-third-party-applications/microsoft-intune-device-certificate-enrollment

Cheers,
Mike Agrenius Kushner
Product Owner EJBCA
mike.kushner@primekey.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cda83a64-56ae-a632-dc81-dfd1a03984c1
* Version Independent ID: b93da48e-4097-4c3a-f6c8-02a5c4e0a616
* Content: [Use third-party certification authorities (CA) with SCEP in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/certificate-authority-add-scep-overview#set-up-third-party-ca-integration)
* Content Source: [memdocs/intune/protect/certificate-authority-add-scep-overview.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certificate-authority-add-scep-overview.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
You'll find a link in the article to the EJBCA document, along with links to our other Third-Party CA partners.
