### ISSUE TITLE
CommandLine options for setup missing DistributionPointInstallIIS

### ISSUE THREAD

**Issue by jeffotterpohl** [MicrosoftDocs/memdocs#717]
command-line-options-for-setup.md is missing DistributionPointInstallIIS

(admin edit: add metadata to link with article)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e974688b-b85e-3698-7b8e-6ed3396f0267
* Version Independent ID: f6853905-1140-5336-e469-a61c86b1e49e
* Content: [Setup command-line options - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/install/command-line-options-for-setup)
* Content Source: [memdocs/configmgr/core/servers/deploy/install/command-line-options-for-setup.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/deploy/install/command-line-options-for-setup.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
I ended up just completely redoing this article (and a few others). I actually split off the unattended answer file info into a separate article. I added a few other properties too. Thanks again for the feedback. 

The changes should publish live later today.
