### ISSUE TITLE
SMSTSPostAction Question

### ISSUE THREAD

**Issue by gwblok** [MicrosoftDocs/memdocs#719]
[Enter feedback here]

Is there any information about how SMSTSPostAction works?
Like... what actually triggers the command?
Is the TSManger Service Running?  Has the TS completely shutdown when the command is run?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d19a7bae-9409-05b3-96d1-409dd2cb0946
* Version Independent ID: 5dcc1789-cea0-fdba-bb36-2769730f8f78
* Content: [Task sequence variable reference - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/osd/understand/task-sequence-variables)
* Content Source: [memdocs/configmgr/osd/understand/task-sequence-variables.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/osd/understand/task-sequence-variables.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @gwblok, let me check 😉

**Comment by aczechowski** [comment]
Just before exiting the task sequence, the TSManager process spawns the specified post action. It doesn't wait or record any status, just exits after calling that command. That's probably some useful detail to add for this TS variable.

NOTE: not for doc, but FYI, there may be a couple of known issues with this variable. The following issues were reported, but I don't think we've yet tried to reproduce:
- Make sure to set the variable at the end of the task sequence. MVP Niall Brady reported a while back an instance where the task sequence was actually triggering the action right after the variable was set in the middle of the task sequence. 😱 
- There was an issue reported with version 1706 plus a support case in late 2018 where it launched two instances of the action.

**Comment by gwblok** [comment]
Thank you for that.
follow up question, is TSManager then dependent on the CM Client?
Here is my current issue... I have a Task Sequence, near the end I
uninstall the CM Client, the TS pretty much never recovers, and the Post
Action doesn't run.

My Goal is to build a VM (non-domain Joined), do lots of stuff in the
middle, at the end remove the CM Client completely and shutdown.
I've gotten my goal with some trickery and scheduled tasks, but was hoping
to not need a scheduled task and rely on the post action.

Gary

**Comment by aczechowski** [comment]
The task sequence in general is dependent upon the client. If you uninstall the client while the TS is running, then you're also removing (or trying to remove) the task sequence components itself. So bad things will likely occur. Other than the trick with the prepare client for capture step (noted in the other thread 😉), I think the only option would be to use a post action to uninstall the client. Or run a script that uninstalls the client and then does whatever other action you need. 

I'm making a change to add some wording as noted above. This issue will auto close when that change merges, and then will go live with the next regular publishing (twice each business day mid morning and afternoon).

**Comment by gwblok** [comment]
Thanks Aaron, I really appreciate the extra explanation on that.  I've been
diving deep into these steps for both a blog series, along with at Wells
Fargo as we try some "interesting" things in OSD for our Non-Peristent VDI
project.
