### ISSUE TITLE
Airprint IP Address Requirement

### ISSUE THREAD

**Issue by dbetlow** [MicrosoftDocs/memdocs#72]
Why must we use an IP address for the printer?  We use hostnames so that the IP address can change or so it can be accessed via an Edge server or round robin configuration.  An IP address restriction is a limitation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a7b8e75-3872-6bbd-4d9b-b26d1eb11f81
* Version Independent ID: 74769948-8c98-19de-df74-2fcf1d399387
* Content: [iOS/iPadOS device feature settings in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/ios-device-features-settings#feedback)
* Content Source: [memdocs/intune/configuration/ios-device-features-settings.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/ios-device-features-settings.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@dbetlow Apple requires the IP address [AirPlay.WhitelistItem](https://developer.apple.com/documentation/devicemanagement/airplay/whitelistitem). To send the payload successfully, Intune must also require it in the UI. It's also required in Apple's MDM profile manager:

![image](https://user-images.githubusercontent.com/3229224/78191021-2de78580-7443-11ea-9937-1b01043c9b3c.png)

FYI, for questions like this, we recommend use the [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod).
