### ISSUE TITLE
Document error/clarification

### ISSUE THREAD

**Issue by essentialexch** [MicrosoftDocs/memdocs#722]
When using a PowerShell script, the documentation repeatedly refers to writing to STDOUT, which is fine, but PowerShell doesn't really have STDOUT, although it has many ways of generating output. The documentation should emphasize using Write-Host instead (as Write-Output doesn't work).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de85c97e-b22f-1b7d-0fb2-18e2c2b1970d
* Version Independent ID: 0744e16d-47f6-f1f4-0fbd-41074136e110
* Content: [Add and assign Win32 apps to Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-win32-app-management)
* Content Source: [memdocs/intune/apps/apps-win32-app-management.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/apps-win32-app-management.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by ChrisKibble** [comment]
Don't see STDOUT referenced in this article.  Looked at the past several commits and didn't see any fixes, but might have been fixed by someone else?

**Comment by essentialexch** [comment]
The documentation has been rearranged since I filed that feedback.

Now, see https://docs.microsoft.com/en-us/mem/intune/apps/apps-win32-add and https://docs.microsoft.com/en-us/mem/intune/apps/apps-win32-troubleshoot

**Comment by Erikre** [comment]
We have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. If you have continue to have questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

Please use the above channels if you don't already have a solution.

**Comment by essentialexch** [comment]
Really?

The issue is that the documentation is wrong. I'm giving feedback to improve the documentation. Referring me to additional support for YOUR problem is ridiculous.

If you don't care about your documentation, I don't either. Sheesh.

**Comment by essentialexch** [comment]
Oh yeah, if you aren't going to take feedback - remove the buttons. smdh.

**Comment by Erikre** [comment]
@essentialexch - We're tracking this doc issue internally. I have an open doc issue on this one. Once I'm able to verify with the product team, I'll make the doc update. I'll see if I can get greater attention to this issue too. We do appreciate your feedback.

**Comment by essentialexch** [comment]
thanks.
