### ISSUE TITLE
TPM/Bitlocker info missing - BitLocker

### ISSUE THREAD

**Issue by wUEZRs** [MicrosoftDocs/memdocs#725]
TPM and Bitlocker information when resetting a PC must be included here as it's crucial in an IT environment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8411fd84-8a1d-28e6-1535-30143be7ede2
* Version Independent ID: 4e5ecbe1-aa9b-cfa0-7b67-1ac1dcb0c465
* Content: [Windows Autopilot Reset](https://docs.microsoft.com/en-us/mem/autopilot/windows-autopilot-reset)
* Content Source: [memdocs/autopilot/windows-autopilot-reset.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/windows-autopilot-reset.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jiorblommaert** [comment]
This information is important. Customers are asking questions what exactly happens with Bitlocker keys when performing a Autopilot Reset.

**Comment by frankroj** [comment]
Thank you for the feedback @wUEZRs  and @jordy-blommaert  I apologize for the time it took to get back to you regarding this feedback item. Nothing happens to either BitLocker or the TPM during an Autopilot Reset. The disk is encrypted and the keys live in the TPM. Neither of these two things are affected or changed during the Autopilot Reset. User data is wiped and the OS is reinstalled, but neither two of these affected the disk encryption or the TPM. This can all occur on top of the encrypted disk with nothing changing with either BitLocker or the TPM.

In general, we document what does occur during a certain action, not what doesn't occur. The list of actions that don't occur is infinite and would be impossible to try and document.

I'm closing this issue as there's nothing actionable for docs at this time.
