### ISSUE TITLE
Consider adding information on how clients use proxy servers

### ISSUE THREAD

**Issue by davidpaMSFT** [MicrosoftDocs/memdocs#728]
Since Configuration Manager client also connects to the Internet, consider adding information about client proxy selection behavior, e.g. does it use user proxy when user is signed in, does it use default WinHTTP proxy if configured, in what order it tries different proxies, does it fallback to direct connection if proxy server is not reachable etc.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7038be9-dfd9-c75b-1224-f54a06dcef1a
* Version Independent ID: b33009c7-4ed4-21ca-d786-43f746c4a638
* Content: [Proxy server support - Configuration Manager](https://docs.microsoft.com/en-ca/mem/configmgr/core/plan-design/network/proxy-server-support)
* Content Source: [memdocs/configmgr/core/plan-design/network/proxy-server-support.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/network/proxy-server-support.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
Marking this won't fix since some of the behavior can vary.
