### ISSUE TITLE
Updating LOB Apps

### ISSUE THREAD

**Issue by OffColour** [MicrosoftDocs/memdocs#73]
Does "The admin must manually upload and deploy updates of LOB apps" just mean changing the MSI in the existing deployment to a new version?
As opposed to the SCCM method creating a new deployment and retiring the old one?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 925b5dc0-9a45-5ac2-7132-80f8cc158d66
* Version Independent ID: ceb01ba2-5a90-1fda-ed25-36887099da71
* Content: [Windows 10 app deployment by using Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-windows-10-app-deploy)
* Content Source: [memdocs/intune/apps/apps-windows-10-app-deploy.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/apps-windows-10-app-deploy.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
We have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. If you have continue to have questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

Please use the above channels if you don't already have a solution.
