### ISSUE TITLE
Resizing VM instance of CMG

### ISSUE THREAD

**Issue by JeissonL** [MicrosoftDocs/memdocs#733]
It's possible to change the default size of de CMG instance (A2v2) after of deployment on Azure for example to B4ms?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07d4e4f7-68ed-e604-b577-2c18617d1c2e
* Version Independent ID: 1ce10bc0-2a6d-405a-a9ae-46adfaac8fe6
* Content: [Plan for cloud management gateway - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/plan-cloud-management-gateway)
* Content Source: [memdocs/configmgr/core/clients/manage/cmg/plan-cloud-management-gateway.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/cmg/plan-cloud-management-gateway.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @JeissonL, thanks for the question. The short answer is no, there's no supported way to change the size of the VM. After a quick glance, I don't see an existing UserVoice idea, so it might be worth adding one. For more information, see [Product feedback](https://docs.microsoft.com/mem/configmgr/core/understand/find-help#product-feedback).

This question is kind of related to this FAQ: [Do I need to maintain the Azure virtual machines?](https://docs.microsoft.com/mem/configmgr/core/clients/manage/cmg/cloud-management-gateway-faq#do-i-need-to-maintain-the-azure-virtual-machines).

The longer answer, is that I think it might be technically possible to go into Azure and change the VM size. However, anytime the CMG service is redeployed, it will reset to the default A2V2 as defined in its deployment template.
