### ISSUE TITLE
Needs an update

### ISSUE THREAD

**Issue by Mal-G** [MicrosoftDocs/memdocs#734]
[Enter feedback here]
I believe this page needs an update given it was last updated in Feb-2019 and since there have been a number of OS releases and device releases (e..g Samsung Knox devices). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f70a020-9214-3316-5419-ee35ba6ff91a
* Version Independent ID: 9cc74430-af54-a2ac-7e4f-5a70b415c66e
* Content: [Operating systems and browsers supported by Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/supported-devices-browsers)
* Content Source: [memdocs/intune/fundamentals/supported-devices-browsers.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/supported-devices-browsers.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by lightupdifire** [comment]
Hello,
Please update the doc for Intune supported operating systems.

**Comment by ErikjeMS** [comment]
Updating this doc is in our doc team work queue. Thanks!
