### ISSUE TITLE
Android LOB update procedure using Intune is wrong

### ISSUE THREAD

**Issue by talbenach** [MicrosoftDocs/memdocs#735]
The page describes a process that does not match the actual page in the portal. When accessing the LOB properties page and clicking edit next to App Information heading, the page expects to see a file name that can be selected for the update, but there is none. There is only a link to the application on the Managed Google Play Store, but it is not clear how to use the link.
![image](https://user-images.githubusercontent.com/26057074/92472693-84bb6d00-f1e2-11ea-93f4-887975d11f3f.png)

Trying to reach the Managed Google Play by going through the "Add" app process, selecting a new Managed Google Play app which opens the app store, and then reaching the LOB that I wish to update.
![image](https://user-images.githubusercontent.com/26057074/92472835-b5030b80-f1e2-11ea-8929-c8559fb836e2.png)

This process allows you to edit and update the APK file of the LOB app, but the update does not propagate to the Android phone.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e8cdcd4-7df9-24b7-c501-e79d48942ac5
* Version Independent ID: db7ecc4c-aa1c-b450-305a-397c6ae56a33
* Content: [Add an Android line-of-business app to Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/lob-apps-android)
* Content Source: [memdocs/intune/apps/lob-apps-android.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/lob-apps-android.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
We have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. If you have continue to have questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

Please use the above channels if you don't already have a solution.
