### ISSUE TITLE
RSS Feed.

### ISSUE THREAD

**Issue by win2000b** [MicrosoftDocs/memdocs#736]
Can you confirm the RSS feed url for this page please. As it only gives 2 links

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66f915d1-8486-44dc-a605-280f979d6f9b
* Version Independent ID: 23c6b2c3-64c1-2df3-ad51-d9be083871a1
* Content: [In development - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/in-development)
* Content Source: [memdocs/intune/fundamentals/in-development.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/in-development.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@win2000b Yes, the RSS link is correct. You should see many updates.
