### ISSUE TITLE
V2 Certificate type for SCEP certificate template

### ISSUE THREAD

**Issue by Pickell** [MicrosoftDocs/memdocs#738]
Regarding the section https://docs.microsoft.com/en-us/mem/intune/protect/certificates-scep-configure#create-the-scep-certificate-template :

Specifically, do we STILL have to use a V2 certificate for the SSL/web server certificate for SCEP?  My CA people are unhappy with having to use a cert template that uses SHA1.

If there are other certificate types that can be used can this doc be updated to include those types?  I'm sure our company isn't the only one that balks at using SHA1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9107185-e6c7-b178-4e22-819797fe4880
* Version Independent ID: 1153b441-94f0-b471-52a2-3cf556c68581
* Content: [Configure infrastructure to support SCEP certificate profiles with Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/certificates-scep-configure#create-the-scep-certificate-template)
* Content Source: [memdocs/intune/protect/certificates-scep-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certificates-scep-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@Pickell  I've been able to confirm with our engineering team that only the V2 certificate template has been tested and is supported at this time. This is however something the engineering team is now aware of, and are drafting plans to revisit this limitation, and investigate what else is possible or can be made possible. While there's no ETA for this work yet, we'd expect to announce any changes in [What's New](https://docs.microsoft.com/mem/intune/fundamentals/whats-new) if we're able to expand support.
