### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by haverland389** [MicrosoftDocs/memdocs#744]
There is an important note under the heading "Client push installation account" that isn't quite clear. Where should one not grant sign in locally? This is unclear because the client push account needs to be in Administrators group on the local machine which then grants it sign in locally.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08a113a9-a9e7-30b1-55d1-1a0ec3615f08
* Version Independent ID: 71d19b44-aea7-1f83-b697-f21443a800aa
* Content: [Accounts used - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/hierarchy/accounts#client-push-installation-account)
* Content Source: [memdocs/configmgr/core/plan-design/hierarchy/accounts.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/hierarchy/accounts.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @haverland389, we could certainly be more explicit. Use the Windows user rights assignment **Deny log on locally** to explicitly deny that account. That policy supersedes the **Allow log on locally** policy setting. You can configure that with local or domain group policy. I'll put in a change today to clarify.
