### ISSUE TITLE
Built in role identifier is missing: Company Resource Access Manager

### ISSUE THREAD

**Issue by ganeshkamath89** [MicrosoftDocs/memdocs#747]
In the Built in role list section, there are only 14 entries but in Endpoint Manager, I am seeing 15 Roles. the missing role in the list "Company Resource Access Manager" needs to be updated in the list

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5eb6f85-f198-9376-41f0-659fdedb744e
* Version Independent ID: 4ac9de95-cf78-41e6-4d8e-3ed22e2f798a
* Content: [SMS_Admin Class - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/develop/reference/core/servers/configure/sms_admin-server-wmi-class)
* Content Source: [memdocs/configmgr/develop/reference/core/servers/configure/sms_admin-server-wmi-class.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/develop/reference/core/servers/configure/sms_admin-server-wmi-class.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @ganeshkamath89 for the feedback and catching that. I'll make an update today to include it.
