### ISSUE TITLE
Windows Home Edition can be enrolled in Intune

### ISSUE THREAD

**Issue by velden** [MicrosoftDocs/memdocs#748]
The document cleary states: 
_"The computer is running Windows 10 **Home**. However, enrolling in Intune or joining Azure AD is only supported on Windows 10 Pro and higher editions."_

However this is not true but it is very confusing. I just managed to enroll a Windows Home laptop in Intune.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fbb1036-7815-586b-f86c-89065a44cf9b
* Version Independent ID: f19e131c-88f4-73d6-5fdc-8faac18763ee
* Content: [Troubleshooting Windows device enrollment problems in Microsoft Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/troubleshoot-windows-enrollment-errors)
* Content Source: [memdocs/intune/enrollment/troubleshoot-windows-enrollment-errors.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/troubleshoot-windows-enrollment-errors.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
8557917

**Comment by ErikjeMS** [comment]
The documentation team hasn’t been able to find an answer for this issue. If this is still an issue for you can try any of the following: 

- Open a support ticket by following the steps here: [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support). 

- Post on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.   

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.   

 I'm closing this issue as there's nothing actionable for docs at this time.
