### ISSUE TITLE
VPP Is now Apps & Books

### ISSUE THREAD

**Issue by josemocha** [MicrosoftDocs/memdocs#75]
This section needs to be retitled and terminology update to reflect Apps & Books and no longer referencing "Legacy VPP." While commonly referred to as VPP that program no longer exists. Tokens will work but need to be renewed in Apple School or Apple Business Manager. 

Upgrade to Apple Business Manager to continue using the Device Enrollment Program and Volume Purchase Program. Apple Deployment Programs are no longer available as of December 1, 2019.
https://support.apple.com/en-us/HT208817

Upgrade from Apple Deployment Programs
https://support.apple.com/en-us/HT209617

Migrate to Apps & Books
https://support.apple.com/en-us/HT208257

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5e0d6b8-b0ef-92af-59be-fbfeadc86503
* Version Independent ID: 4bc281e4-1b33-7513-3c75-48f38c378c04
* Content: [Manage volume-purchased apps and books with Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/vpp-apps#feedback)
* Content Source: [memdocs/intune/apps/vpp-apps.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/vpp-apps.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@josemocha - Thanks for the feedback. We have recently update the Intune content to note that Apple allows you purchase multiple licenses for an app that you want to use in your organization on iOS/iPadOS and macOS devices using Apple Business Manager or Apple School Manager. We're also updating the Table of Contents in the Intune docs. Thanks for your feedback.
