### ISSUE TITLE
Initial Paragraph requires clarification.

### ISSUE THREAD

**Issue by ImaBadCoder** [MicrosoftDocs/memdocs#750]
[Enter feedback here]
The description doesn't quite make sense.

/Snip

starting in version 1906, you can install a Microsoft Connected Cache server on your distribution points. By caching this content on-premises, your clients can benefit from the Delivery Optimization feature, but you can help to protect WAN links.

/end snip

Seems like the last part should say "that can help to protect WAN links.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f3bc546-10ba-d750-fc0c-a9fa4e3e1e8d
* Version Independent ID: 9a692485-d3fb-d8d4-57d2-611ff9692421
* Content: [Microsoft Connected Cache - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/hierarchy/microsoft-connected-cache)
* Content Source: [memdocs/configmgr/core/plan-design/hierarchy/microsoft-connected-cache.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/hierarchy/microsoft-connected-cache.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by jpcast88** [comment]
@ImaBadCoder Thanks for calling this one out. I've submitted a private pull request to get this fixed. For future reference, If you're interested and willing, you can also submit the change yourself.

https://docs.microsoft.com/en-us/mem/configmgr/core/understand/use-docs#bkmk_contribute

**Comment by ImaBadCoder** [comment]
Good to know.. Thanks for the information.

Larry
