### ISSUE TITLE
Is Wi-Fi Supported or not?

### ISSUE THREAD

**Issue by liskajoe** [MicrosoftDocs/memdocs#753]
The prerequisites state, "Wi-fi connectivity isn't supported because of the requirement to choose a language, locale, and keyboard to make that Wi-fi connection"

The user flow section states, "Connect to a network (if using Wi-Fi)."

Which is it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0f572e0-1bc0-6f14-7f60-989eb67fb7e7
* Version Independent ID: e4ec5b25-d9a6-d260-6cf6-ff4f3eb3ecb8
* Content: [Windows Autopilot for white glove deployment](https://docs.microsoft.com/en-us/mem/autopilot/white-glove)
* Content Source: [memdocs/autopilot/white-glove.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/white-glove.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
I suppose it's not made expressly clear, but the requirements section applies to pre-provisioning, i.e. the technician flow.  

At the very end of the white glove process the user gets the device and at that point they can connect to wi-fi or ethernet, it doesn't matter.  I'll try to make this clearer in the text.
