### ISSUE TITLE
Endpoint Analytics What's new page is out of date

### ISSUE THREAD

**Issue by kingad** [MicrosoftDocs/memdocs#756]
Endpoint analytics page is out of date and self-referential. 
The page "What is Endpoint Analytics" was last updated 8/12/2020.  To learn what's new, it references a page last updated 6/20/2020, which references itself for more information.

The what's new page should be updated or removed as a reference if there is nothing new, or its not being used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4310913-4a9f-5d18-d284-d49f543e59be
* Version Independent ID: 1a448a38-a5db-5249-9f6a-b68f7081f92a
* Content: [What's new in Endpoint analytics - Configuration Manager](https://docs.microsoft.com/en-us/mem/analytics/whats-new)
* Content Source: [memdocs/analytics/whats-new.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/analytics/whats-new.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
@kingad Totally agree. I highly suspect it *might* be removed within the next week or so.
#please-close
