### ISSUE TITLE
Company Portal and MFA

### ISSUE THREAD

**Issue by colin-small** [MicrosoftDocs/memdocs#758]
I think it would be very helpful to include guidance on not requiring MFA when using the Company Portal for enrollment. 

While many will prefer the Company Portal app for authentication, they do not want to force MFA during enrollment. Especially on ADE/DEP enrollment. The average person uses the device they are enrolling for MFA also. 

This makes it quite a challenge or problem during enrollment when they are promoted for MFA on a device they cannot use yet for SMS or the authenticator app etc.. 

Sure the person could go to their account and modify their MFA temporarily for enrollment but this isn't realistic when you talk about hundreds or thousands of people trying to enroll. 

The only real option here seems to be abandon the company portal for authentication and the benefits it offers or exclude the Microsoft Intune cloud app from the MFA conditional access policy. This is what I think most people end up doing to get around this.

Official guidance from Microsoft in this doc would be appreciated I'm sure as most people realize the nature of the problem after they are in the middle of it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e94556e6-69f3-5c56-f77d-01a810473e6a
* Version Independent ID: 8928627b-e085-2660-38dc-bf6a0ce9a6d8
* Content: [Tutorial - Use Apple Business Manager or the Device Enrollment Program to enroll iOS/iPadOS devices in Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/tutorial-use-device-enrollment-program-enroll-ios)
* Content Source: [memdocs/intune/enrollment/tutorial-use-device-enrollment-program-enroll-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/tutorial-use-device-enrollment-program-enroll-ios.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
8557974

**Comment by MandiOhlinger** [comment]
@colin-small This is great advice, and should be included in our guidance. We'd love for you to create a pull request (PR) with your recommended changes. We review every PR, and will make it publish-ready. Your text changes gives us an idea of what you're trying to say, if that makes sense. And, we'd love your input based on your experience.

To create a pull request:

1. Go to [Tutorial: Use Apple's Corporate Device Enrollment features...](https://docs.microsoft.com/mem/intune/enrollment/tutorial-use-device-enrollment-program-enroll-ios).

2. Select the **Edit** button:

    ![image](https://user-images.githubusercontent.com/3229224/102829128-6d307a80-43b4-11eb-97ea-1ed7400a8d9f.png)

3. Select the pencil icon, and make your changes. You will need to sign in with a GitHub account, and agree to the client license agreement (which is a one time thing).

    ![image](https://user-images.githubusercontent.com/3229224/102829237-a79a1780-43b4-11eb-9993-3ea2c3e0206c.png)

Thanks!
Mandi
