### ISSUE TITLE
Add -DomainName under Script usage

### ISSUE THREAD

**Issue by gaswange** [MicrosoftDocs/memdocs#759]
As fixed in the Microsoft Endpoint Configuration Manager 2002 release under PowerShell:

https://support.microsoft.com/en-us/help/4556203/summary-of-changes-in-microsoft-endpoint-configuration-manager-current

An addition to this page should include usage and example for -DomainName

-DomainName: Used in the instance of a disjointed AD domain space. For example -DomainName fabrikham. If the domain name is contoso.com but the domain netbios name is fabrikham.

I have recently just experienced this situation with a customer who had this exact scenario.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b28d3556-29c0-eaad-9855-8fdeb91bad84
* Version Independent ID: 84234954-f695-0c7d-ca04-7474550a455f
* Content: [Set up BitLocker portals - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/protect/deploy-use/bitlocker/setup-websites)
* Content Source: [memdocs/configmgr/protect/deploy-use/bitlocker/setup-websites.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/protect/deploy-use/bitlocker/setup-websites.md)
* Product: **configuration-manager**
* Technology: **configmgr-protect**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @gaswange, good catch! I'll make the edit.

(Hey Garrett! 😉 Blast from the past...)
