### ISSUE TITLE
VPP

### ISSUE THREAD

**Issue by josemocha** [MicrosoftDocs/memdocs#76]
While we still download a ".vpptoken" it is better to refer to it as the "Apps and books server token."
https://support.apple.com/en-us/HT202995

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6be83bf7-b364-60e3-1b4f-97bbde969ada
* Version Independent ID: 02a2bedd-1af7-3a14-7314-11e0853e4c98
* Content: [Manage Apple volume-purchased apps - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/vpp-apps-ios)
* Content Source: [memdocs/intune/apps/vpp-apps-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/vpp-apps-ios.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@josemocha - Thanks for the feedback. We have recently updated our doc:
- [Manage volume-purchased apps and books with Microsoft Intune](https://docs.microsoft.com/mem/intune/apps/vpp-apps)
- [Migrate from Volume Purchase Program (VPP) to Apps and Books](https://docs.microsoft.com/mem/intune/apps/vpp-apps-ios#migrate-from-volume-purchase-program-vpp-to-apps-and-books)

If you are still running into problems related to this issue, we want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
