### ISSUE TITLE
Follow on sentences seem to contradict each other

### ISSUE THREAD

**Issue by markoshea1212** [MicrosoftDocs/memdocs#761]
Under pre-requisites the following sentences seem to contradict each other or are talking about two separate things.

"Devices must be joined to Azure AD and auto-enrolled. The Intune management extension supports Azure AD joined, hybrid domain joined, group policy enrolled devices are supported."

The first sentence seems to suggest that it only supports AAD joined autoenrolled devices, but the next sentence then says that the IME supports AADJ, hybrid AADJ and group policy enrolled. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de85c97e-b22f-1b7d-0fb2-18e2c2b1970d
* Version Independent ID: 0744e16d-47f6-f1f4-0fbd-41074136e110
* Content: [Win32 app management in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-win32-app-management#prerequisites)
* Content Source: [memdocs/intune/apps/apps-win32-app-management.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/apps-win32-app-management.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
Thanks for the feedback. The docs have now been updated.
