### ISSUE TITLE
Text correction please - broken reference

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/memdocs#762]
The text on this page

- To use PKCS certificate profiles:

- [Install the PFX Certificate Connector for Microsoft Intune](certificates-imported-pfx-configure.

looks broken. Please review.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2320f32-f46c-c4a8-1c22-1a79b44f1075
* Version Independent ID: abd36170-7d28-8708-29d6-45260ef44df5
* Content: [Create certificates profile in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/certificates-configure)
* Content Source: [memdocs/intune/protect/certificates-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certificates-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@andrePKI  Thanks. A fix has been submitted and that link will be back in action later today.
