### ISSUE TITLE
Missed Task Sequence Variable

### ISSUE THREAD

**Issue by olegkngit** [MicrosoftDocs/memdocs#764]
Can't find any mention about OSDBitlockerPIN

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d19a7bae-9409-05b3-96d1-409dd2cb0946
* Version Independent ID: 5dcc1789-cea0-fdba-bb36-2769730f8f78
* Content: [Task sequence variable reference - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/osd/understand/task-sequence-variables#deprecated-variables)
* Content Source: [memdocs/configmgr/osd/understand/task-sequence-variables.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/osd/understand/task-sequence-variables.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @olegkngit for the feedback, good catch. We purposefully don't document all possible task sequence variables, as some are only for internal use. We do talk about this variable in a couple of other articles, though, so I'll add it.
