### ISSUE TITLE
Setup Windows & ConfigMgr Step

### ISSUE THREAD

**Issue by gwblok** [MicrosoftDocs/memdocs#768]
[Enter feedback here]

Hey Team, The Setup Windows & CM Step does a TON!  I get you can't add everything, but is there a variable that controls if DisableCMDRequest.TAG is created (which is created at the same time setupcomplete.cmd file is created in C:\Windows\Setup\Scripts.)  This prevents Shift-F10 during OOBE.

For Troubleshooting, I'd like to prevent that file from being created, I've tried a few things, but it causes the step to fail.  Is there already a mechanism in place (variable) that I can set that will prevent the Setup Win & CM step from creating that file?

Is this a UserVoice Request, or is this already available, and I just haven't figured out the variable? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8d2232b-5503-07b6-29fd-8afcdcea9a89
* Version Independent ID: 9621b35d-5928-2319-1048-eff6fa6a2e70
* Content: [Task sequence steps - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/osd/understand/task-sequence-steps#BKMK_RequestStateStore)
* Content Source: [memdocs/configmgr/osd/understand/task-sequence-steps.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/osd/understand/task-sequence-steps.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @gwblok, I checked with engineering, there's no variable to control this behavior. So filing a UserVoice item that describes the scenario would be best.

FYI, for in-place upgrade, you can use the [/DiagnosticPrompt option](https://docs.microsoft.com/windows-hardware/manufacture/desktop/windows-setup-command-line-options#diagnosticprompt) via the OSDSetupAdditionalUpgradeOptions TS variable.
