### ISSUE TITLE
Missing "What can your organization DO"

### ISSUE THREAD

**Issue by tomer-schles** [MicrosoftDocs/memdocs#77]
Missing "What can your organization DO"
It's super relevant

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb1f7fe9-6bae-6fc5-eb77-d456e08f8736
* Version Independent ID: b0d12a58-0a77-67dc-7006-49e98589ca7f
* Content: [What info can your company see when you enroll your device?](https://docs.microsoft.com/en-us/mem/intune/user-help/what-info-can-your-company-see-when-you-enroll-your-device-in-intune#feedback)
* Content Source: [memdocs/intune/user-help/what-info-can-your-company-see-when-you-enroll-your-device-in-intune.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/user-help/what-info-can-your-company-see-when-you-enroll-your-device-in-intune.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Thanks @tomer-schles for your suggestion. To clarify, are you wanting to know what actions the organization can directly take on your device? 

In case you're looking for much more detail, there is a documentation set dedicated to IT pros that describes how organizations can use Intune to manage devices. That doc set is here: https://docs.microsoft.com/en-us/mem/intune/

**Comment by lenewsad** [comment]
Hi @tomer-schles, thank you again for your suggestion. What an organization can/can't do varies between organizations and is based on the organization's own policies/terms of use. We've added your request for more information to our documentation backlog so that we can figure out if/how we can address this in the future in a clear, helpful manner. I'm closing this item as there are no plans to update this document right now. 

 Thank you!

**Comment by StingyJack** [comment]
> What an organization can/can't do varies between organizations and is based on the organization's own policies/terms of use

@lenewsad what an org can do depends on what this app allows them to do. That's a terribly important difference.

**Comment by lenewsad** [comment]
Thanks for your feedback @StingyJack. I will let the product team that we've received additional feedback that a "what your organization can do" section is important. Hopefully we can get support to write something in the future.
