### ISSUE TITLE
ADE enrollment profiles limit error

### ISSUE THREAD

**Issue by eljoe29** [MicrosoftDocs/memdocs#771]
[Please change the number of DEP profiles per token on the second paragraph that show only 100 instead of 1000. here is the error "There is a limit of 100 enrollment profiles per ADE token."]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd130267-c54b-41e3-d534-831d4a86bae6
* Version Independent ID: bdfa7eca-a356-3dde-7643-9a759f952007
* Content: [Enroll iOS/iPadOS devices - Automated Device Enrollment - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-ios)
* Content Source: [memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
![ADE profiles](https://user-images.githubusercontent.com/71354073/93272583-6671e600-f77b-11ea-919a-5cb06022d6ef.png)

* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@eljoe29 Thanks! I'll fix this today.
