### ISSUE TITLE
Page refers to intune protallll -       and original destinationnot present in endpoint manager portal

### ISSUE THREAD

**Issue by edbakermct** [MicrosoftDocs/memdocs#772]
[Enter feedback here]

This pages refers in several places to the Intune portalin Azure - this has gone away (sob) - also in the endpoint manager portal the WIP learning report is absent - is this going to be given back or has it gone for good?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db9e7f9d-a388-7689-a4e2-9c7f65cec382
* Version Independent ID: 88d065e0-17ee-32c7-4639-d95306e2a1cb
* Content: [Windows Information Protection (WIP) app protection policy - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/windows-information-protection-policy-create)
* Content Source: [memdocs/intune/apps/windows-information-protection-policy-create.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/windows-information-protection-policy-create.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
Thanks for feedback. This topic has been updated to point to Microsoft Endpoint Manager.
