### ISSUE TITLE
Sync button is not there for android device

### ISSUE THREAD

**Issue by ValBis** [MicrosoftDocs/memdocs#773]
Sign in to the Microsoft Endpoint Manager admin center.
Select Devices > All devices.
In the list of devices you manage, select a device to open its Overview pane, and then select Sync.

But sync button is not there for fully managed devices (Kiosk) Android. The Doc states that it should be there

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6cb3efe-0b30-d8e2-d81e-15e11b31cabe
* Version Independent ID: e9d478d0-9cb7-518d-cb47-023868caee0c
* Content: [Sync devices with Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/remote-actions/device-sync)
* Content Source: [memdocs/intune/remote-actions/device-sync.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/remote-actions/device-sync.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@ValBis Sync is not available for Android dedicated devices (Kiosk). Sync is only supported for Android Device administrator and Android for work devices.
