### ISSUE TITLE
Please explain

### ISSUE THREAD

**Issue by kennethvs** [MicrosoftDocs/memdocs#775]
[Enter feedback here]
Can you please further explain the following two statements:

Fencing isn't available.
Mobile Application Management (MAM) availability is conditional on those apps being available in People's Republic of China.

What is fencing? I haven't heard of this term before in this context
What does "Mobile Application Management (MAM) availability is conditional on those apps being available in People's Republic of China." mean exactly, can you define it a little bit more concrete? Like which apps are/aren't available and what can we do with those apps? (App Protection/App Configuration policies)

Thanks in advance,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d6b42fe-83df-0636-3293-9b0e4de5a73d
* Version Independent ID: b4cc15d1-a2d3-e27e-91d7-f12192a000fd
* Content: [Intune operated by 21Vianet in China](https://docs.microsoft.com/en-us/mem/intune/fundamentals/china)
* Content Source: [memdocs/intune/fundamentals/china.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/china.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by kennethvs** [comment]
It would also be nice if Microsoft can be a little bit more concrete on what exactly is supported for users in China, managed by Intune tenants hosted outside of China.

**Comment by kennethvs** [comment]
Any update on this?

**Comment by ErikjeMS** [comment]
The documentation team hasn’t been able to find an answer for this issue. If this is still an issue for you can try any of the following: 

- Open a support ticket by following the steps here: [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support). 

- Post on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.   

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.   

 I'm closing this issue as there's nothing actionable for docs at this time.
