### ISSUE TITLE
What role is required to upload Autopilot devices?

### ISSUE THREAD

**Issue by scheblein** [MicrosoftDocs/memdocs#777]
What role is required to upload Autopilot devices? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97ce79c0-0014-f6f0-95f7-58574bfdefb3
* Version Independent ID: 40b3877e-a094-8d05-c95b-ca842c5ca8ce
* Content: [Enroll devices with Windows Autopilot - Microsoft Intune](https://docs.microsoft.com/en-us/mem/autopilot/enrollment-autopilot)
* Content Source: [memdocs/autopilot/enrollment-autopilot.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/enrollment-autopilot.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@greg-lindsay Do you know the answer to this question?

**Comment by greg-lindsay** [comment]
Generally this is done by an Intune Administrator, but you can create a custom role that only includes the enrollment permissions. See https://oofhours.com/2019/08/13/creating-a-windows-autopilot-role-in-intune/

**Comment by greg-lindsay** [comment]
I'll add this detail to the topic.

**Comment by greg-lindsay** [comment]
Below is what I've added

Device enrollment can be done by an Intune Administrator or a Policy and Profile Manager. You can also create a custom Autopilot device manager role by using Role Based Access Control and creating this role. Autopilot device management only requires that you enable all permissions under Enrollment programs, with the exception of the four token management options.

**Comment by ErikjeMS** [comment]
Thanks, Greg!
@scheblein Looks like Greg has addressed your question, so I'm going to close this issue. Let us know if you need more info.
