### ISSUE TITLE
Wrong JSON key names to configure the Feed

### ISSUE THREAD

**Issue by Bruenu** [MicrosoftDocs/memdocs#778]
The JSON key names are wrong to configure the Feed:

com.microsoft.launcher.Feed.Enabled
com.microsoft.launcher.Feed.Enable.UserChangeAllowed

it only works with:
com.microsoft.launcher.Feed.Enabled
and
com.microsoft.launcher.Feed.Enable.UserChangeAllowed

as in the JSON sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8976417-16d9-58c1-8831-5c06aee65ad2
* Version Independent ID: b00e84d9-a244-9739-832a-9a02261112fb
* Content: [Configure Microsoft Launcher for Android Enterprise with Intune](https://docs.microsoft.com/en-us/mem/intune/apps/configure-microsoft-launcher)
* Content Source: [memdocs/intune/apps/configure-microsoft-launcher.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/configure-microsoft-launcher.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
The topic currently shows these values. If you have continue to have questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

Please use the above channels if you don't already have a solution.
