### ISSUE TITLE
typo in doc

### ISSUE THREAD

**Issue by soupman98** [MicrosoftDocs/memdocs#779]
Windows 10 version 1803 and above adds event log entries. You can use the **og** entries to see details related to the Autopilot profile settings and OOBE flow. These entries can be viewed using Event Viewer
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70ba3843-a7d3-3bce-9975-dd624c514fe1
* Version Independent ID: 65311f2a-a61d-b976-9bd6-a0fb43dcc198
* Content: [Troubleshooting Windows Autopilot](https://docs.microsoft.com/en-us/mem/autopilot/troubleshooting)
* Content Source: [memdocs/autopilot/troubleshooting.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/troubleshooting.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
fixed in https://github.com/MicrosoftDocs/memdocs-pr/pull/2131
