### ISSUE TITLE
"Device ownership" greyed out - cannot change

### ISSUE THREAD

**Issue by MichelZ** [MicrosoftDocs/memdocs#78]
I know this was previously possible, but doesn't seem to be anymore (Service Release 2003 installed)
Has something changed here and the Documentation wasn't updated?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcd313b3-e225-849a-def5-8a32a08a92e9
* Version Independent ID: 917b6190-a8bd-f55d-3e71-f403a395721f
* Content: [Add corporate identifiers to Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/corporate-identifiers-add#change-device-ownership)
* Content Source: [memdocs/intune/enrollment/corporate-identifiers-add.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/corporate-identifiers-add.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@MichelZ I just checked on my end and I can still use Device Ownership. You might have found a bug. :(  There are a few options available to provide the fastest level of support for this:   
- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.   
- Post on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.   
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.   
I'm closing this issue as there's nothing actionable for docs at this time.
