### ISSUE TITLE
Missing scope

### ISSUE THREAD

**Issue by CloudlinkAdmin** [MicrosoftDocs/memdocs#780]
All I get is missing scope. 
AADSTS900144: The request body **must** contain the following parameter: 'scope'.

It does say that this is optional, but I wont get anywhere even when adding a scope or disabling it again. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ae2a36c-2b94-a3c4-a20f-ef4ed3c226c7
* Version Independent ID: 0d83f965-49af-4443-2876-47590f5e694e
* Content: [Get data from the Data Warehouse API with a REST client - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/developer/reports-proc-data-rest)
* Content Source: [memdocs/intune/developer/reports-proc-data-rest.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/developer/reports-proc-data-rest.md)
* Service: **microsoft-intune**
* Sub-service: **developer**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
The issue appears that it may be related to an OAuth issue. If you have continue to have questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

Please use the above channels if you don't already have a solution.
