### ISSUE TITLE
August 2020 MDM Baseline needs to be added

### ISSUE THREAD

**Issue by Cosmo121** [MicrosoftDocs/memdocs#783]
Endpoint Manager is showing August 2020 as the latest MDM security baseline. This article says: 

> The most recent baseline version is MDM Security Baseline for May 2019

Looks like the August 2020 baseline changes need to be added, or at least linked.

Thanks,
Mike
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2fae9ac-8971-3c2d-533d-dbfb1cea912c
* Version Independent ID: 54f83d9b-0b25-4b9f-db5d-e148917dfb3a
* Content: [Intune security baselines settings for Windows 10 - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/security-baseline-settings-mdm#feedback)
* Content Source: [memdocs/intune/protect/security-baseline-settings-mdm.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/security-baseline-settings-mdm.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@Cosmo121   Looks like you've found your way to an older version of this article, that is soon to be retired (removed). The article you want is here: https://docs.microsoft.com/en-us/mem/intune/protect/security-baseline-settings-mdm-all?pivots=mdm-sept-2020   The difference is the addition of -all to the file name in the URL. 

The file change was implemented some time back, to test the contents ability to select between versions. As this was in a trial phase, a new article was created to ensure the technology for selecting was stable, before getting ride of this now outdated article. This article will soon be removed with an automatic redirection to the  correct on put in its place.

**Comment by Cosmo121** [comment]
Thanks @Brenduns! It looks like the link in the new baseline in Endpoint Manager, under _Learn about_ needs to be updated. It uses the short URL: https://aka.ms/AA3xja4

**Comment by Brenduns** [comment]
@Cosmo121 Thanks for Identifying that link. That's eluded me, and I thought we had all the fwlink and aka.ms links run down long ago.  NowTime to fix that.
