### ISSUE TITLE
Delete Threshold(%)

### ISSUE THREAD

**Issue by cert01** [MicrosoftDocs/memdocs#785]
The wording for **Start Delete threshold(%)** and  **Stop Delete threshold(%)** is unclear. 

It's potentially clearer to be:

**"When the percentage of disk space remaining available drops below the value you enter"**

vs.

**"When the total disk/storage space drops below the value you enter"**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe42a212-bb45-2823-80e7-584df7898e53
* Version Independent ID: 969f46bf-e963-fc1f-22b8-78c18df19098
* Content: [Windows 10 shared device settings - Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/shared-user-device-settings-windows)
* Content Source: [memdocs/intune/configuration/shared-user-device-settings-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/shared-user-device-settings-windows.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@cert01 Agreed. It looks like the change is already made in https://docs.microsoft.com/mem/intune/configuration/shared-user-device-settings-windows.

Thank you!
