### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by nkubenik** [MicrosoftDocs/memdocs#786]
In the "Settings applied based on user affinity" section, the "Window Hybrid Azure AD joined" enrollment type shows YES for Intune applies. This seems to be a typo as a HDAAJ device doesn't actually interact with Intune. Unless I am reading that wrong.

Also, the macOS Jamf/Intune integration enrollment type is missing from the options. The macOS options listed don't really apply to any of the listed items.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0e6e96c-331b-20e6-c646-45cb351e3fdf
* Version Independent ID: dacdefe3-7674-9083-e5be-c10a3b615e03
* Content: [Understand between Intune and Azure device limit restrictions](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-limit-intune-azure)
* Content Source: [memdocs/intune/enrollment/device-limit-intune-azure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/device-limit-intune-azure.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
8556673

**Comment by ErikjeMS** [comment]
The documentation team hasn’t been able to find an answer for this issue. If this is still an issue for you can try any of the following: 

- Open a support ticket by following the steps here: [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support). 

- Post on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.   

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.   

 I'm closing this issue as there's nothing actionable for docs at this time.
