### ISSUE TITLE
Delivery Optimization Report is not supported by Desktop Analytics

### ISSUE THREAD

**Issue by ra-ful** [MicrosoftDocs/memdocs#788]
This page shows reporting of Delivery Optimization is YES.

Reporting | Yes (using Desktop Analytics)

But, Delivery Optimization insights is not available now.

>Delivery Optimization insights
https://docs.microsoft.com/en-us/mem/configmgr/desktop-analytics/faq

Please check which is correct.

(admin edit: add article metadata for proper linking)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41018f34-d884-7a61-4b6a-6149968d0673
* Version Independent ID: c39f9160-7165-0654-0dc0-86ac90bebef0
* Content: [FAQ for Desktop Analytics - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/desktop-analytics/faq)
* Content Source: [memdocs/configmgr/desktop-analytics/faq.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/desktop-analytics/faq.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Oh, just noticed that it's a discrepancy between the DA FAQ and this article: https://docs.microsoft.com/en-us/mem/configmgr/sum/deploy-use/optimize-windows-10-update-delivery#peer-cache-comparison-chart

I'm investigating to figure out what's going on.
Thanks for the feedback!

**Comment by aczechowski** [comment]
Hi @ra-ful, I confirmed with a DA PM, there are no DO insights in DA. UC is still the home for that. I'll update the optimize article to align with the DA FAQ (which is correct).
