### ISSUE TITLE
Planning Endpoint Security

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/memdocs#789]
[Enter feedback here]
I don't see anything on this page about planning for endpoint security. Is there a reason that this is not included in the planning section?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7169a77-bebf-3ee5-4f8f-ade05986074c
* Version Independent ID: a8452d1d-4e33-2cb2-8cfb-3dee9c8cb6c2
* Content: [Intune onboarding process - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/planning-guide-onboarding)
* Content Source: [memdocs/intune/fundamentals/planning-guide-onboarding.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/planning-guide-onboarding.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @dougeby
* Microsoft Alias: **dougeby**

**Comment by MandiOhlinger** [comment]
@DeanGross Yeah - Those old guides needed some work. We rewrote and restructured them:

- [Planning guide](https://docs.microsoft.com/mem/intune/fundamentals/intune-planning-guide)
- [Intune setup deployment guide](https://docs.microsoft.com/mem/intune/fundamentals/deployment-guide-intune-setup)
- [Migrate your mobile device management from Basic Mobility and Security to Intune](https://docs.microsoft.com/mem/intune/fundamentals/migrate-to-intune)

If you see something that's missing, it'd be great if you created a pull request with your recommended changed. We want and encourage community contributions.
