### ISSUE TITLE
So many things wrong in Cause 6

### ISSUE THREAD

**Issue by nessts** [MicrosoftDocs/memdocs#79]
all of the /Library under step six of cause six need ~/Library
the next two lines should be one line
/Library/Saved Application
State/com.jamfsoftware.selfservice.mac.savedState

all of this in step 6 makes no sense 
com.microsoft.CompanyPortal
com.microsoft.CompanyPortal.HockeySDK
enterpriseregistration.windows.net
https://device.login.microsoftonline.com
https://device.login.microsoftonline.com/
Microsoft Session Transport Key (public AND private keys)
Microsoft Workplace Join Key (public AND private keys)

in step 7 you say don't remove the jamf keys so we don't break jamf enrollment, but hello we unenrolled in steps 2 and 3

what is the point of uninstalling company portal? you just have to install it again and since we removed all the plists for it there is really no use in reinstalling the app and even if you do remove it you never ask to reinstall it which is a bit problematic for re-enrolling in intune. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 953344ed-f631-a20b-c38a-9eb31c96b1e9
* Version Independent ID: 3937361d-d0b2-6619-521e-894acb94e6cf
* Content: [Troubleshooting Jamf Pro integration with Microsoft Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/troubleshoot-jamf#feedback)
* Content Source: [memdocs/intune/protect/troubleshoot-jamf.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/troubleshoot-jamf.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
Closing this issue without action.
We've not been able to get the engineering team to engage on this, (below their bar for ongoing work), and without their feedback on the necessity of the suggested changes, nor without further indication these entries are problematic as is, this falls below the content teams bar for taking action.

**Comment by Brenduns** [comment]
Closing this issue without action.
We've not been able to get the engineering team to engage on this, (below their bar for ongoing work), and without their feedback on the necessity of the suggested changes, nor without further indication these entries are problematic as is, this falls below the content teams bar for taking action.
