### ISSUE TITLE
No way to identify windows devices as corporate?

### ISSUE THREAD

**Issue by StuBeck32** [MicrosoftDocs/memdocs#791]
Per the table on the page, there is no way to identify Windows devices by serial number. Is this accurate?

Platform | IMEI numbers | Serial numbers
-- | -- | --
Windows | Not supported | Not supported

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcd313b3-e225-849a-def5-8a32a08a92e9
* Version Independent ID: 917b6190-a8bd-f55d-3e71-f403a395721f
* Content: [Add corporate identifiers to Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/corporate-identifiers-add)
* Content Source: [memdocs/intune/enrollment/corporate-identifiers-add.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/corporate-identifiers-add.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
8556580

**Comment by ErikjeMS** [comment]
The documentation team hasn’t been able to find an answer for this issue. If this is still an issue for you can try any of the following: 

- Open a support ticket by following the steps here: [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support). 

- Post on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.   

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.   

 I'm closing this issue as there's nothing actionable for docs at this time.
