### ISSUE TITLE
Intune education settings for shared iPad devices documentation is out of date

### ISSUE THREAD

**Issue by p0shkar** [MicrosoftDocs/memdocs#797]
It seems to me that a lot of this information is out of date and a complete overhaul is needed.

Some examples:
> 1. Sign in to Intune.

The URL points to the old Intune portal/URL.
> 2. On the Intune pane, choose Device configuration.

Device configuration is renamed.
> 3. On the Create profile pane, enter a Name and Description for the iOS/iPadOS education profile.

I'm in an EDU tenant, but I can't see no "education profile" to create.

Therefor, it seems to me that this whole doc needs to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46100a4f-7fea-329b-b2e5-a9c05515d07f
* Version Independent ID: 2794893b-6703-e35e-11e5-dd44dafe6ac6
* Content: [Intune shared device settings for the iOS/iPadOS Classroom app - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/education-settings-configure-ios-shared)
* Content Source: [memdocs/intune/fundamentals/education-settings-configure-ios-shared.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/education-settings-configure-ios-shared.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @p0shkar, thanks for your feedback throughout our docs--it's much appreciated. The same situation from #796 applies here, where we've left this article as-is to support people who had this feature before we deprecated it. 

I'm closing this issue as there aren't any updates to be made to this article at this time.
