### ISSUE TITLE
Error 0x80072193

### ISSUE THREAD

**Issue by GlennMillerNZ** [MicrosoftDocs/memdocs#8]
Edge Chromium using "Microsoft Edge (Windows 10) - preview" distribution is failing with the above error.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 826eb5cf-dadc-a5a6-ff24-793f7e9fb371
* Version Independent ID: 92227d8c-1eb3-e5b7-8dc1-52aaa1eabfd4
* Content: [App installation error codes - Microsoft Intune](https://docs.microsoft.com/en-au/mem/intune/apps/app-install-error-codes#feedback)
* Content Source: [memdocs/intune/apps/app-install-error-codes.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-install-error-codes.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@GlennMillerNZ - Thanks for the feedback. I've forwarded on these details to the product team and once I have additional information, I'll add it to the Intune documentation. f you are still running into problems related to this issue, we want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

This question is in our documentation feedback channel and it may be best to handle this question as a support request. For this reason, I'm closing this issue. Please use the above channels if you don't already have a solution.
