### ISSUE TITLE
more wrong with cause 6

### ISSUE THREAD

**Issue by nessts** [MicrosoftDocs/memdocs#80]
instead of deleting preference files should probably be doing 
defaults delete com.jamf.management.jamfAAD

defaults delete com.jamfsoftware.selfservice.mac

defaults delete com.microsoft.CompanyPortal

and probably could not have to reboot  if you do this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 953344ed-f631-a20b-c38a-9eb31c96b1e9
* Version Independent ID: 3937361d-d0b2-6619-521e-894acb94e6cf
* Content: [Troubleshooting Jamf Pro integration with Microsoft Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/troubleshoot-jamf#feedback)
* Content Source: [memdocs/intune/protect/troubleshoot-jamf.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/troubleshoot-jamf.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
Closing this issue without action.
We've not been able to get the engineering team to engage on this, (below their bar for ongoing work), and without their feedback on the necessity of the suggested changes, nor without further indication these entries are problematic as is, this falls below the content teams bar for taking action.
