### ISSUE TITLE
Clarification of terms

### ISSUE THREAD

**Issue by philhorn** [MicrosoftDocs/memdocs#801]
[Enter feedback here]
Hello,

There is some vague wording in the section:

Enabled: Accounts created by guests, and accounts in AD and Azure AD are automatically deleted. When a user signs off the device, or when system maintenance runs, these accounts are deleted.

This seems to imply that an AD or Azure AD account will be deleted, From AD? or From Azure?, when it should say that the account will be removed from the computer in question.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe42a212-bb45-2823-80e7-584df7898e53
* Version Independent ID: 969f46bf-e963-fc1f-22b8-78c18df19098
* Content: [Windows 10 shared device settings - Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/shared-user-device-settings-windows)
* Content Source: [memdocs/intune/configuration/shared-user-device-settings-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/shared-user-device-settings-windows.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@philhorn Good point. Thank you. The description is updated, and changes should be live later today. 

When you see fixes like this, it'd be great if you created a Pull Request (PR) with your recommended changes. Just something to consider for next time.

Thanks again!
