### ISSUE TITLE
Missing info

### ISSUE THREAD

**Issue by philhorn** [MicrosoftDocs/memdocs#803]
[Enter feedback here]
There is a setting at the bottom (last setting below Allow phone sign-in) for "Use security keys for sign-in", but there is nothing listed in this doc regarding that setting.
https://endpoint.microsoft.com/#blade/Microsoft_Intune_DeviceSettings/DevicesEnrollmentMenu/windowsEnrollment

Can you add some info regarding this section?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6d32682-0e4e-449b-6ad5-001c631735d2
* Version Independent ID: 66419be7-51dc-f5e1-cf18-1a55866e4193
* Content: [Integrate Windows Hello for Business with Microsoft Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/windows-hello)
* Content Source: [memdocs/intune/protect/windows-hello.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/windows-hello.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@philhorn   Thanks for the feedback. It does seem we're missing a setting. I'm submitting a fix that will add the missing details for this setting to the docs, which will appear later today.
