### ISSUE TITLE
Could use a bit... more details on ways to remove devices.

### ISSUE THREAD

**Issue by bramnet** [MicrosoftDocs/memdocs#804]
[Enter feedback here]

What if you've reached the maximum number of enrolled devices and the end user needs to remove one?
Just some screenshots for how to remotely remove a device as an end user would be nice (tech support technician thinking he needs to buy an android just to figure this out, here.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00ecc12c-2dd5-51aa-f582-c89713e72762
* Version Independent ID: fa7b5b06-042b-9f86-48f5-638a96bb076e
* Content: [How to remove your Android device from Intune](https://docs.microsoft.com/en-us/mem/intune/user-help/unenroll-your-device-from-intune-android)
* Content Source: [memdocs/intune/user-help/unenroll-your-device-from-intune-android.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/user-help/unenroll-your-device-from-intune-android.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @bramnet, thank your for the suggestion and I'll run your question by the product team to see if that scenario should be documented here.  I have a couple questions about your screenshot suggestion; do you want the screenshots that are currently shown to be updated, or are you asking for screenshots for another procedure on the page? Or something else?

Thanks so much for clarifying! :)

**Comment by bramnet** [comment]
Hi @lenewsad 
Sorry for the delay in response.
To be clear, I'm looking for uptodate screenshots of what the end user should be seeing so that we can guide them on how to remove their devices. Entry-level technicians at my company aren't given access to the admin web portal.

**Comment by lenewsad** [comment]
Thanks for clarifying @bramnet!

**Comment by lenewsad** [comment]
Hi again @bramnet, I just added those screenshots, which should be live on 1/26 after 10 am PST. Thanks for your patience! I'm closing this issue now.
