### ISSUE TITLE
Unclear whether MSI product code should include { }

### ISSUE THREAD

**Issue by webash** [MicrosoftDocs/memdocs#805]
Both in the UI of MEM/Intune and in this document, it is unclear whether the product code provided to MSI detection should include the curly braces `{` and `}` or not. MSI product codes always refer to them, but no validation is done on this field to determine whether Intune requires them or not, leaving it entirely to chance as to whether it needs it or not. Please clarify in the documentation at least.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca840cce-3b99-3009-c8fa-d5fab6ae37d0
* Version Independent ID: 928b9e37-626a-8d50-c6a1-ac0b5cad4be4
* Content: [Add and assign Win32 apps to Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-win32-add)
* Content Source: [memdocs/intune/apps/apps-win32-add.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/apps-win32-add.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by JeremyTBradshaw** [comment]
This is a perfect point.  I also feel as though there should be some very clear guidance as to whether or not to target devices or users for apps that install under the user rather than the system.  Bing Wallpaper is a simple example.  I've found it never detects and always claims to have failed to install, however always succeeds.  The detection stuff needs to real TLC.

**Comment by webash** [comment]
@Erikre Any comment here?

**Comment by webash** [comment]
Bump

**Comment by Erikre** [comment]
I've escalated this issue and I'm tracking this with an internal bug directed at the product team. 

We have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. If you have continue to have questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

Please use the above channels if you don't already have a solution. I will continue to ping the product team. Once I have more information, I will be updating the related topics.

**Comment by Erikre** [comment]
Closing this GitHub issue because we're tracking this issue as an internal work item.

**Comment by DanielWahlgren** [comment]
The documentation is still not clear on this, and the UI still have no validation to guide users. 
While I understand moving it to an internal work item, it's been years with seemingly no action.
