### ISSUE TITLE
Incorrect Start Menu Group Referenced (for newer builds)

### ISSUE THREAD

**Issue by Brachus12** [MicrosoftDocs/memdocs#808]
> After you install it, find the following items on the Start menu in the **Microsoft System Center** group:

In more recent versions of ConfigMgr, these items now appear under the Microsoft Endpoint Manager group
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9c165c0-acf3-96fd-0e25-963c0b4a28a0
* Version Independent ID: 5a6b4ca0-d281-f06d-ea7e-e78962c35d59
* Content: [Support Center - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/support/support-center)
* Content Source: [memdocs/configmgr/core/support/support-center.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/support/support-center.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @Brachus12 for catching this. We updated the path in a few other places, but obviously missed this one. I'll do a scrub of the whole content to look for others.

This issue will auto close when my change merges. It will then go live with the next daily publishing process, which should be later today.
