### ISSUE TITLE
Unknown Win32 Error code: 0x80180001

### ISSUE THREAD

**Issue by PaulEstevesAtPEX** [MicrosoftDocs/memdocs#81]
Auto MDM Enroll: Device Credential (0x1), Failed (Unknown Win32 Error code: 0x80180001)

**Comment by ErikjeMS** [comment]
@PaulEstevesAtPEX Are you getting this error somewhere? I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a few options available to provide the fastest level of support for this:   
- Post on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.   
- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.   
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.   
I'm closing this issue as there's nothing actionable for docs at this time.
