### ISSUE TITLE
Configuring iOS Safari Domain with Microsoft Tunnel

### ISSUE THREAD

**Issue by pmeuser** [MicrosoftDocs/memdocs#812]
Please, can you add guidance how to configure Safari domains for iOS, that allows to connect to internal websites with Safari browser? Thanks a lot! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4538f49d-8c19-9227-0acf-77bef7f8d4a8
* Version Independent ID: 1b1b2c40-1fd8-3909-37ae-05ab0d27efb5
* Content: [Install and configure the Microsoft Tunnel VPN solution for Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/microsoft-tunnel-configure)
* Content Source: [memdocs/intune/protect/microsoft-tunnel-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/microsoft-tunnel-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@pmeuser  Thanks for your feedback Peter, I've also commented on this  with your feedback from https://github.com/MicrosoftDocs/memdocs/issues/813. 
- While in preview, Safari domains aren't supported. Support for them is expected to be added in a future update.
