### ISSUE TITLE
Mention that blocking login.live.com will break autopilot

### ISSUE THREAD

**Issue by hpsin** [MicrosoftDocs/memdocs#816]
It often catches customers unaware that they must not block login.live.com for Autopilot to work.  Can we ensure that included in this page is the requirement that login.live.com also be unblocked, like login.microsoftonline.com? If there are concerns around opening the consumer login endpoint, I can provide additional security measure there soon. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82c5b872-c031-9ed9-c4cc-c8a1a8e93e0a
* Version Independent ID: ac837825-11e3-cf43-7516-0d94b496a59f
* Content: [Windows Autopilot networking requirements](https://docs.microsoft.com/en-us/mem/autopilot/networking-requirements)
* Content Source: [memdocs/autopilot/networking-requirements.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/networking-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
This URL is actually included in https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide which is a requirement, but I can add a specific mention of this URL to make it clear.

**Comment by frankroj** [comment]
Closing this issue since @greg-lindsay fixed it back in 2020.
