### ISSUE TITLE
Company portal not working on redmi note 6 pro

### ISSUE THREAD

**Issue by sandeepc001** [MicrosoftDocs/memdocs#82]
Hi Team, 

I am unable to complete the setup. Process of company portal app I'm redmi note 6 pro, unable to resolve 'Secure start up must be enabled for encryption'. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65b4168f-4a7b-9546-5287-cfc277b17458
* Version Independent ID: 0451fa59-1307-f432-57a4-ee97b96e4b2e
* Content: [Enroll Android device with Intune Company Portal](https://docs.microsoft.com/en-us/mem/intune/user-help/enroll-device-android-company-portal#feedback)
* Content Source: [memdocs/intune/user-help/enroll-device-android-company-portal.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/user-help/enroll-device-android-company-portal.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @sandeepc001, thanks for your question. Check out this article for the steps to enable secure start up on your device: [Encrypting your Android device](https://docs.microsoft.com/mem/intune/user-help/encrypt-your-device-android#enable-secure-startup
