### ISSUE TITLE
Wildcard needed for *.blob.core.windows.net?

### ISSUE THREAD

**Issue by maxbaldt** [MicrosoftDocs/memdocs#822]
Do we really need to allow *.blob.core.windows.net? Defender Docs do not recommend to exclude this whitecard-URL from network inspection and firewall block lists: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/configure-network-connections-microsoft-defender-antivirus#allow-connections-to-the-microsoft-defender-antivirus-cloud-service

The blob.core.windows.net domain is used not only directly from MSFT. Customers can have subdomains underneath and provide unsecure content from there. So setting a asterisk for this domain might be a additional security risk. It would be better to have a list of known endpoints to maintain instead of allowlisting the whole domain.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a9e88a5-bc7d-4982-4564-ceea80bde0e7
* Version Independent ID: 817824fe-5b44-ebeb-75c4-9eeb2dfa13ce
* Content: [Internet access requirements - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/network/internet-endpoints#bkmk_scp-updates)
* Content Source: [memdocs/configmgr/core/plan-design/network/internet-endpoints.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/network/internet-endpoints.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks again @maxbaldt for filing this feedback 😉 
I'm checking with engineering to see if we can get better detail especially for that endpoint instead of the wildcard.

**Comment by aczechowski** [comment]
I made a change to the article for this feedback. The issue will auto close when my change merges. The change will then go live with the daily publishing cycle (tomorrow morning Pacific most likely as this point)
