### ISSUE TITLE
Hi, requesting update documentation on WVD Multisession Win 10 support 

### ISSUE THREAD

**Issue by megaalc** [MicrosoftDocs/memdocs#825]
Hi, requesting update documentation on WVD Multisession Win 10 support 
Currently it is not clear whether we can use Intune to apply win OS patches to WVD Multisession Win 10 support  (2004 and 1909 in particular) 
Thank you 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62bdbb09-8341-1b8b-b0ba-cd5aaa3fa6f3
* Version Independent ID: dcb0a61c-2502-04f1-4744-97777496b57e
* Content: [Configure Windows Update for Business in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/windows-update-for-business-configure)
* Content Source: [memdocs/intune/protect/windows-update-for-business-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/windows-update-for-business-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@megaalc Thanks for the question. Intune doesn’t support management of _Windows 10 Enterprise multi-session_. So unfortunately, patching is right out.  

You can read about Intune support for WVD in [Using Windows Virtual Desktop with Intune](https://docs.microsoft.com/mem/intune/fundamentals/windows-virtual-desktop). The relevant statement for multi-session comes at the end in the section [Windows 10 Enterprise multi-session](https://docs.microsoft.com/mem/intune/fundamentals/windows-virtual-desktop#windows-10-enterprise-multi-session), which is a subsection of the _Limitations_ section. 

I'm led to believe that a future update is expected to add support for multi-session. When that support is added, we'll need to then evaluate or confirm if Windows Update for Business is supported for multi-session.
