### ISSUE TITLE
Redundant link in Prereqs

### ISSUE THREAD

**Issue by p0shkar** [MicrosoftDocs/memdocs#83]
In prereqs you have the same link twice:
"Apple Mobile Device Management (MDM) Push certificate"
"Apple MDM Push certificate"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c94c405-5fac-4890-281a-28a51831f290
* Version Independent ID: e50b3c20-8a95-1cae-1e70-f96f310ddb55
* Content: [Apple School Manager Program enrollment for iOS/iPadOS devices - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/apple-school-manager-set-up-ios)
* Content Source: [memdocs/intune/enrollment/apple-school-manager-set-up-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/apple-school-manager-set-up-ios.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@p0shkar Thanks! I'll fix this today.
