### ISSUE TITLE
Error on WGET cmdlet to download mst-readiness file

### ISSUE THREAD

**Issue by faatenci** [MicrosoftDocs/memdocs#835]
There is an issue with the cmdlet 
REPLACE THIS LINE
wget https://aka.ms/microsofttunnelready -o mst-readiness

WITH THIS LINE
wget --output-document=mst-readiness https://aka.ms/microsofttunnelready

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ebaa15c-1e00-c075-eff2-79d4c10ba6af
* Version Independent ID: c9dfee71-1c01-4318-725c-b4bb97052efb
* Content: [Use the Microsoft Tunnel VPN solution for Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/microsoft-tunnel-overview)
* Content Source: [memdocs/intune/protect/microsoft-tunnel-overview.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/microsoft-tunnel-overview.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@faatenci  Thanks for the feedback here. The content will update tonight with some minor changes, which include a correction to the _wget_ command that aligns to your suggestions, and to similar suggestions from another PR.
