### ISSUE TITLE
Missing/incorrect commands

### ISSUE THREAD

**Issue by jchri** [MicrosoftDocs/memdocs#836]
Two fixes in this section https://docs.microsoft.com/en-us/mem/intune/protect/microsoft-tunnel-overview#run-the-readiness-tool
1. This command is wrong.
wget https://aka.ms/microsofttunnelready -o mst-readiness
Replace with
wget --output-document=mst-readiness https://aka.ms/microsofttunnelready

2. Steps are missing to enable the script to be executable. Please add some descriptive text and the command below.

After downloading the script, it is necessary to make the file executable, by changing the file permissions, before running the script.
sudo chmod +x mst-readiness

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ebaa15c-1e00-c075-eff2-79d4c10ba6af
* Version Independent ID: c9dfee71-1c01-4318-725c-b4bb97052efb
* Content: [Use the Microsoft Tunnel VPN solution for Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/microsoft-tunnel-overview)
* Content Source: [memdocs/intune/protect/microsoft-tunnel-overview.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/microsoft-tunnel-overview.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@jchri   Thanks for the feedback here. The content will update tonight with some minor changes, which include a correction to the _wget_ command, that aligns to your suggestions (and that from another PR), as well as the use of _chmod_ to set the permissions for running the script, for which we've also received suggestion outside of GitHub issue feedback at about the same time.
