### ISSUE TITLE
Alternative SSO for macOS

### ISSUE THREAD

**Issue by mcmeeking** [MicrosoftDocs/memdocs#839]
There's a note about the state of Azure AD SSO app extension for macOS, but no indication of whether any of the other options can be used instead:

> The Microsoft Azure AD SSO extension is still being developed. It's listed in the Intune user interface, but doesn't work as expected. Don't use Microsoft Azure AD for the SSO app extension type.

It would be nice to get:
- Clarity on whether any of the alternatives perform a similar function for Microsoft apps while this is being worked on
- A link to the progress of this upcoming update if available
- _**An indication in the Intune UI that this is currently broken and shouldn't be used**_

It's frustrating having to have 10 docs.microsoft.com tabs open alongside Intune just to check whether things aren't working because of misconfiguration or because they are just broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b4d6112-d991-a27a-6515-e3c48d600d09
* Version Independent ID: 42f0eba4-d096-9447-446d-9580fc340210
* Content: [macOS device feature settings in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/macos-device-features-settings#single-sign-on-app-extension)
* Content Source: [memdocs/intune/configuration/macos-device-features-settings.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/macos-device-features-settings.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@mcmeeking The other options all work - Redirect, Credential, and Kerberos. So, you can try any of those. In the documentation, we **try** to avoid specific timeframes, as timelines change often.

When it's functioning, we'll announce in [What's New](https://docs.microsoft.com/mem/intune/fundamentals/whats-new).

**Comment by mcmeeking** [comment]
Thanks, but it might be helpful to explain *how* the others work for something like, say for instance, Microsoft apps for SSO with Azure AD creds from Company Portal - at least while the actual Azure AD SSO is broken.

That way people who visit this page looking for documentation on setting up SSO for the MS apps on Macs will actually have something to help them - rather than a note saying that what they're trying to do is possible.
