### ISSUE TITLE
Clarify what you mean with the recommendation of Supervised Mode

### ISSUE THREAD

**Issue by p0shkar** [MicrosoftDocs/memdocs#84]
"Microsoft recommends using ADE as the mechanism for enabling supervised mode, especially for organizations that are deploying large numbers of iOS/iPadOS devices."

I think it's unclear if you mean that Microsoft recommends setting the "Supervised" profile setting in Intune or if that is something which should be set elsewhere (DEP/BEM/ASM).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c94c405-5fac-4890-281a-28a51831f290
* Version Independent ID: e50b3c20-8a95-1cae-1e70-f96f310ddb55
* Content: [Apple School Manager Program enrollment for iOS/iPadOS devices - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/apple-school-manager-set-up-ios)
* Content Source: [memdocs/intune/enrollment/apple-school-manager-set-up-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/apple-school-manager-set-up-ios.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@p0shkar It means Intune's setting. I'll add that to the doc today. Thanks!
