### ISSUE TITLE
Typo in "Enable Win32 apps on S mode devices"

### ISSUE THREAD

**Issue by modzilla99** [MicrosoftDocs/memdocs#842]
In the document "Enable Win32 apps on S mode devices" there is a small typo in the second sentence! :)

"These devices include **a** a single Win 10S base policy, which locks the S mode device from running any Win32 apps on it. "

https://docs.microsoft.com/en-us/mem/intune/apps/apps-win32-s-mode

(admin edit: add meta data for proper link with article)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84fae477-b987-1e31-1dbf-7bfc236faf33
* Version Independent ID: c82f5ec1-8383-fca3-072c-1f9f642a4b25
* Content: [Enable Win32 apps on S mode devices - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-win32-s-mode)
* Content Source: [memdocs/intune/apps/apps-win32-s-mode.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/apps-win32-s-mode.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@modzilla99 - Thanks for the feedback. I fixed the typo and it should be published tomorrow. If you see any other issues, please let us know. Thanks
