### ISSUE TITLE
PROVISIONTS Property

### ISSUE THREAD

**Issue by jpoling1** [MicrosoftDocs/memdocs#843]
It is not clear in the doc whether the task sequence used for PROVISIONTS needs to be deployed as available or required.  

Additional clarity on that point would be really helpful.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3f3e45d-8f9d-aa5a-8b6a-d8c51c50d11e
* Version Independent ID: f5305fc4-894b-19dd-26c8-6f90901d4b1e
* Content: [Client installation parameters and properties - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/deploy/about-client-installation-properties)
* Content Source: [memdocs/configmgr/core/clients/deploy/about-client-installation-properties.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/deploy/about-client-installation-properties.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @jpoling1, thanks for the feedback, and good question. It actually doesn't matter, it can be either. Since you specify the deployment ID, you just have to deploy the TS to that collection. But still probably a good point to clarify to avoid confusion.

**Comment by aczechowski** [comment]
I'm adding a tip for this. The issue will auto close when the change merges. It will then go live with the next daily publishing process, which should be later today.

**Comment by jpoling1** [comment]
Awesome! Thank you

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
