### ISSUE TITLE
Android missing for some collected details

### ISSUE THREAD

**Issue by JiriHy** [MicrosoftDocs/memdocs#844]
[Enter feedback here]
Android is missing for some device details. The following items are collected on Android: Name, Intune Device ID, Serial number, OS, OS version, OS build. In the table we have only iOS and Windows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905c303e-4306-38ec-2a30-4852a8c1bc2b
* Version Independent ID: ceb7e815-e19a-386f-902c-6e6bf53d5766
* Content: [View device details with Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/remote-actions/device-inventory)
* Content Source: [memdocs/intune/remote-actions/device-inventory.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/remote-actions/device-inventory.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@JiriHy Thanks! I'll change this today.
