### ISSUE TITLE
Profile type additions

### ISSUE THREAD

**Issue by haakonwibe** [MicrosoftDocs/memdocs#846]
Device configuration profile type "Windows health monitoring" is missing from the list of various profile types.
Just noticed when I was doing documentation write-up on my side.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d8832b0-265d-5c37-9f9d-4adbaa8202de
* Version Independent ID: 48c4745d-166e-01a6-0f29-8bfc2a86d07a
* Content: [Create device profiles in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/device-profile-create)
* Content Source: [memdocs/intune/configuration/device-profile-create.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/device-profile-create.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@haakonwibe Thank you. The Windows Health Monitoring profile doc is included in the 2011 release. So, you should see it in the near future.
