### ISSUE TITLE
User side-loading apps not possible

### ISSUE THREAD

**Issue by toxarisswe** [MicrosoftDocs/memdocs#847]
Hello.
I was in contact with the support regarding allow Side-loading, this is actually not possible. 
My setup consisted a Fully Managed device that was configured with "Allow installation from unknown sources" set to "Allow". The user can install an APK-file transferred via USB, but a while later the app gets uninstalled (after MDM policy refesh or restart). So, the statement "It allows users to side-load apps on the device using means other than the Google Play Store" is incorrect.
https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-android-for-work#applications 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 900e72be-d42b-49ba-f304-602df23cbb04
* Version Independent ID: 2ce5c45d-15be-d316-1c57-92bea37358e0
* Content: [Android Enterprise device settings in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-android-for-work)
* Content Source: [memdocs/intune/configuration/device-restrictions-android-for-work.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/device-restrictions-android-for-work.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by toxarisswe** [comment]
This can be closed, saw later that it was already answered

**Comment by MandiOhlinger** [comment]
@toxarisswe Thank you. So what was the answer? Are any doc updates needed to clarify the setting description?

**Comment by toxarisswe** [comment]
Yes, its clearly stated in the section explaining access to "Allow access to all apps in Google Play store"

**Comment by MandiOhlinger** [comment]
@toxarisswe I gotcha. Thank you!
