### ISSUE TITLE
Clarify "Sync with Computer"

### ISSUE THREAD

**Issue by p0shkar** [MicrosoftDocs/memdocs#85]
This setting lacks a description on this page, and when creating a policy the information text "Specifies whether iOS devices can sync with computers." is equally inadequate.

Also see https://github.com/MicrosoftDocs/IntuneDocs/issues/2908 for similar request.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c94c405-5fac-4890-281a-28a51831f290
* Version Independent ID: e50b3c20-8a95-1cae-1e70-f96f310ddb55
* Content: [Apple School Manager Program enrollment for iOS/iPadOS devices - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/apple-school-manager-set-up-ios)
* Content Source: [memdocs/intune/enrollment/apple-school-manager-set-up-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/apple-school-manager-set-up-ios.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@p0shkar The UI information bubble explains that Sync with computers "Specifies whether iOS can sync with computers." We don't always repeat definitions from the UI in the docs to avoid repetition. Thanks!

**Comment by ErikjeMS** [comment]
Based on the other issue, I added a sentence stating Deny all means no sync to any data on any computer.
