### ISSUE TITLE
MSfBSyncWorker.log does not exist

### ISSUE THREAD

**Issue by MonsieurPec** [MicrosoftDocs/memdocs#850]
[Enter feedback here]
Hello,

It seems that the MSfBSyncWorker.log file was renamed to WsfbSyncWorker.log

Thank you.
PEC

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 123e9d7b-1759-cc47-e73f-25e17b791636
* Version Independent ID: 966dca6c-9688-8a43-65cb-0f795d0a646a
* Content: [Log file reference - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/hierarchy/log-files)
* Content Source: [memdocs/configmgr/core/plan-design/hierarchy/log-files.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/hierarchy/log-files.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @MonsieurPec for the feedback, you're correct. We had a couple of community contributions last year to correct some instances. I'll do a sweep of the content to make sure we get them all.

This issue will auto close when my change merges, and then will go live with the next daily publishing. At this point that should be later today.
