### ISSUE TITLE
The intune portal was not in Azure portal anymore

### ISSUE THREAD

**Issue by julienghithub** [MicrosoftDocs/memdocs#851]
[Enter feedback here]

The sentence "Wipe can't be done from the Company Portal. Wiping a device enrolled by a DEM user account can be done from the Intune in Azure portal." is not correct

Sould be "Wipe can't be done from the Company Portal. Wiping a device enrolled by a DEM user account can be done from the Intune portal or Endpoint Management portal."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7786d9c0-55b0-9bff-fc0a-f4ee70ee0615
* Version Independent ID: cf0c17a0-fdc7-e0af-db82-913e36d2ec7c
* Content: [Enroll devices using a device enrollment manager account - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-manager-enroll)
* Content Source: [memdocs/intune/enrollment/device-enrollment-manager-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/device-enrollment-manager-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@julienghithub Thanks! I'll change this today.
