### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/memdocs#853]
In the "Note" box at the top of the article it has a link ""Announcing the Power BI solution template for Configuration Manager". This goes to a page that doesn't link to anything to do with ConfigMgr.
I thought now the MEM portal can show ConfigMgr and Intune devices side-by-side I would be able to get software inventory from one place. If this isn't the case then this page should link to the best way to get this info from ConfigMgr.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a815b74-6234-4c1d-80ac-7375c58f8860
* Version Independent ID: fb3cdf86-f84b-b272-ea9f-311f2e7a7641
* Content: [Use the Intune Data Warehouse - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/developer/reports-nav-create-intune-reports)
* Content Source: [memdocs/intune/developer/reports-nav-create-intune-reports.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/developer/reports-nav-create-intune-reports.md)
* Service: **microsoft-intune**
* Sub-service: **developer**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
Thanks for the feedback. Updating this link to point to better information.
