### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by russrimm** [MicrosoftDocs/memdocs#854]
Is there going to be an RSS feed so customers can subscribe to see what's new in Endpoint Analytics?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4310913-4a9f-5d18-d284-d49f543e59be
* Version Independent ID: 1a448a38-a5db-5249-9f6a-b68f7081f92a
* Content: [What's new in Endpoint analytics - Configuration Manager](https://docs.microsoft.com/en-us/mem/analytics/whats-new)
* Content Source: [memdocs/analytics/whats-new.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/analytics/whats-new.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @russrimm, you can get an RSS feed for any doc. For more info, see [How to use the docs: Notifications](https://docs.microsoft.com/en-us/mem/configmgr/core/understand/use-docs#bkmk_notifications).

If you [search](https://docs.microsoft.com/en-us/search/?scope=ConfigMgr&terms=%22what%27s%20new%20in%20endpoint%20analytics%20-%20configuration%20manager%22) for `"what's new in endpoint analytics - configuration manager"` it will return a single result. Then select **RSS**, which in this example yields the following result: 
`https://docs.microsoft.com/api/search/rss?search=%22what%27s+new+in+endpoint+analytics+-+configuration+manager%22&locale=en-us&facet=&%24filter=scopes%2Fany%28t%3A+t+eq+%27ConfigMgr%27%29`
