### ISSUE TITLE
Is "WS-Trust 1.3 Username/Mixed endpoint" still a prereq?

### ISSUE THREAD

**Issue by p0shkar** [MicrosoftDocs/memdocs#86]
"If using ADFS, user affinity requires WS-Trust 1.3 Username/Mixed endpoint."

Is this still a prereq?

/adfs/services/trust/13/usernamemixed
Used for Exchange Online with Office clients older than Office 2013 May 2015 update. Later clients use the passive \adfs\ls endpoint.
 
/adfs/ls
Browser based authentication flows and current versions of Microsoft Office use this endpoint for Azure AD and Office 365 authentication

Surely this must now support /adfs/ls, now that Basic Auth is being disabled? (My reasoning is that usernamemixed seems to be username+password in cleartext: ClientCredentialType : Username-Password-Clear).

Also, in https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-ios#create-an-apple-enrollment-profile it only seems to be an issue when using Setup Assistant and ADFS, not if you use Company Portal. If it does still require usernamemixed, which is true? Only for Setup Assistant or both?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c94c405-5fac-4890-281a-28a51831f290
* Version Independent ID: e50b3c20-8a95-1cae-1e70-f96f310ddb55
* Content: [Apple School Manager Program enrollment for iOS/iPadOS devices - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/apple-school-manager-set-up-ios)
* Content Source: [memdocs/intune/enrollment/apple-school-manager-set-up-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/apple-school-manager-set-up-ios.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by p0shkar** [comment]
Or is this exactly the reason why Company Portal is required if using MFA, that Setup Assistant still uses Basic Auth? 

Will Setup Assistant not work if using Conditional Access to block Basic Auth?

**Comment by ErikjeMS** [comment]
Investigating with PM...
(6973948)

**Comment by p0shkar** [comment]
I found that the tutorial has a better explination regarding authenticating using Setup Assistant, even though it is a bit outdated (since the choices has been renamed in Intune). https://docs.microsoft.com/en-us/mem/intune/enrollment/tutorial-use-device-enrollment-program-enroll-ios

"If you would like to use Multi-Factor Authentication, allow users to change passwords upon first sign in, or prompt users to reset their expired passwords during enrollment, choose Yes under Authenticate with Company Portal instead of Apple Setup Assistant. If you are comfortable using Apple's provided basic HTTP authentication through Apple Setup Assistant, choose No."

Here it clearly states that basic HTTP auth is used for Apple Setup Assistant.
However, I would still like to know if this information is up to date. Otherwise, it would be really good if Microsoft could put some pressure on Apple to not use insecure authentication.

**Comment by ErikjeMS** [comment]
Repinged PM...

**Comment by ErikjeMS** [comment]
The documentation team hasn’t been able to find an answer for this issue. If this is still an issue for you can try any of the following: 
- Open a support ticket by following the steps here: [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support). 
- Post on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.   
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.   
 I'm closing this issue as there's nothing actionable for docs at this time.
