### ISSUE TITLE
Notes appear to be mixed up

### ISSUE THREAD

**Issue by ld0614** [MicrosoftDocs/memdocs#860]
The table [here](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/configs/site-size-performance-guidelines#general-sizing-guidelines) has Note 2 for SQL Server Memory, Note 3 for IOPS and Note 4 for Storage space.  

However the actual notes are:

[Note 2: IOPS: Inboxes and IOPS: SQL](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/configs/site-size-performance-guidelines#bkmk_note2)
[Note 3: SQL Server memory allocation](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/configs/site-size-performance-guidelines#bkmk_note3)
[Note 4: Storage space required](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/configs/site-size-performance-guidelines#bkmk_note4)

It looks like Notes 2 and 3 just need switching around, happy to create a PR if it would help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cda5d744-c604-5cf1-2174-44a82db01053
* Version Independent ID: fd18ea2a-485e-67b0-dcbf-efa9784e2d3e
* Content: [Site size and performance guidelines - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/configs/site-size-performance-guidelines#bkmk_note3)
* Content Source: [memdocs/configmgr/core/plan-design/configs/site-size-performance-guidelines.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/configs/site-size-performance-guidelines.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @ld0614, good catch. I just added the SQL Server memory note last week, and obviously messed up the numbering! If you want to put in a PR to fix it, I can quickly review and approve. Otherwise I'll take care of it later this week.
