### ISSUE TITLE
Overlapping Boundary Groups

### ISSUE THREAD

**Issue by johnjohnjohn87** [MicrosoftDocs/memdocs#861]
I thought this explanation from Jason Sandys really helped clarify some questions I had. I think it's worth adding to this page to really spell out what happens to clients when they are in multiple boundary groups. This explanation allowed me to confidently move forward with leveraging the new VPN boundary feature (which I love). https://www.reddit.com/r/SCCM/comments/ik7rbe/2006_vpn_boundary/g3j3ei4/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a2d3a58-d1b9-6f56-8f0c-dfdf2733b670
* Version Independent ID: 436c5f30-086a-5c8a-d9b3-98a017f9f55b
* Content: [Configure boundary groups - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/boundary-groups)
* Content Source: [memdocs/configmgr/core/servers/deploy/configure/boundary-groups.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/deploy/configure/boundary-groups.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @johnjohnjohn87 for the feedback. I'm checking with Jason if he wants to make the edit himself 😉

**Comment by mestew** [comment]
Jason was nice enough to edit the docs for overlapping boundaries. It should update in the next few days.
