### ISSUE TITLE
Conflicting information

### ISSUE THREAD

**Issue by jackster18** [MicrosoftDocs/memdocs#863]
This page states that on the compatibility tab of the template, Windows server 2003 should be used, yet when reviewing this page: https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/network/cng-certificates-overview, the compatibility tab is supposed to be "Certificate Authority must be Windows Server 2008 or later. (Windows Server 2012 is recommended.)"

Seems the information is in conflict. If it's set to Windows Server 2003, I cannot change the "Provider category" on the compatibility tab.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a41a19c-d822-1ee7-80a7-3672e1d47077
* Version Independent ID: 305cb6a2-adf1-87d5-212e-456e945cf5fd
* Content: [Example PKI certificate deployment - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/network/example-deployment-of-pki-certificates#BKMK_client2008_cm2012)
* Content Source: [memdocs/configmgr/core/plan-design/network/example-deployment-of-pki-certificates.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/network/example-deployment-of-pki-certificates.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @jackster18. This article (Example PKI deployment) is very old and hasn't been reviewed for a while. We have an internal tracking item to review it and the related PKI requirements article, just haven't yet been able to free resources to work on it. The CNG v3 article is newer, more recently reviewed, and more current.
I'm closing this issue as we have an internal item tracking rework on the older PKI article. Thanks for the feedback!
