### ISSUE TITLE
No proxy error

### ISSUE THREAD

**Issue by Honken77** [MicrosoftDocs/memdocs#864]
If I copy your configuration I get the error "Unrecognized element 'defaultProxy'" over and over, and no matter if I add the defaultProxy config or not, I am unable to connect my Intune Connector even though there is no proxy for this environment.

`<system.net>`
      `<defaultProxy>`
            `<defaultProxy enabled="False" />`
      `</defaultProxy>`
`</system.net>`

Further down on the page, the syntax instead seems to be only "proxy" and not "defaultProxy" but typing it like that didn't help either. Then I instead get an error on the attribute "enabled".

`<system.net>`
        `<defaultProxy>`
            `<proxy enabled="False" /> `
        `</defaultProxy>`
    `</system.net>`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1546e07f-4168-140d-508e-bf7fcb3661bb
* Version Independent ID: e1deb787-f2b9-b024-e921-68f6b0d5d4cb
* Content: [Configure proxy settings for the Intune Connector for Active Directory](https://docs.microsoft.com/en-us/mem/intune/enrollment/autopilot-hybrid-connector-proxy)
* Content Source: [memdocs/intune/enrollment/autopilot-hybrid-connector-proxy.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/autopilot-hybrid-connector-proxy.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @master11218
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
8556197

**Comment by ErikjeMS** [comment]
@Honken77 I haven't been able to find a solution with the PM. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a few options available to provide the fastest level of support for this:   
- Post on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.   
- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.   
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.   
I'm closing this issue as there's nothing actionable for docs at this time.
