### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by majdalsharif** [MicrosoftDocs/memdocs#866]
![1](https://user-images.githubusercontent.com/24624606/95788698-aed1e480-0ce4-11eb-8524-824b4ef03bce.jpg)

Link: https://docs.microsoft.com/en-us/mem/intune/protect/advanced-threat-protection-configure#enable-microsoft-defender-atp-in-intune

**Comment by ErikjeMS** [comment]
@majdalsharif Thanks! I'll fix it today.
