### ISSUE TITLE
Azure AD Cloud Sync works for User as well as Device collections

### ISSUE THREAD

**Issue by robinherbert** [MicrosoftDocs/memdocs#870]
In the section about synchronizing collection membership results to Azure Active Directory groups, is the sentence "You can synchronize device collections." plus other similar text. This implies you cannot sync user collections. However, this is not true. User collections can be sync'd.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e416191-9e1a-7779-46ad-3e138a6a38e5
* Version Independent ID: 825f7f36-6968-2592-e44f-9ffdac59a7b6
* Content: [Create collections - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/collections/create-collections)
* Content Source: [memdocs/configmgr/core/clients/manage/collections/create-collections.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/collections/create-collections.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @robinherbert, good catch. I'll get that fixed this morning.
