### ISSUE TITLE
Windows 10 feature updates remain in public preview, still the current status?

### ISSUE THREAD

**Issue by mattsmacblog** [MicrosoftDocs/memdocs#874]
Is this still live/happening, any ETA?  I have told devices to upgrade to 2004 but nothing is happening on devices running 1903 still...

"While Windows 10 feature updates remain in public preview, when co-managing devices with Configuration Manager and Intune, there is a limitation where feature update policies may not immediately take effect, causing devices to update to a later feature update than configured in Intune. This limitation will be removed with a future update to Configuration Manager."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62bdbb09-8341-1b8b-b0ba-cd5aaa3fa6f3
* Version Independent ID: dcb0a61c-2502-04f1-4744-97777496b57e
* Content: [Configure Windows Update for Business in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/windows-update-for-business-configure)
* Content Source: [memdocs/intune/protect/windows-update-for-business-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/windows-update-for-business-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@mattsmacblog   Thanks for the question. I’ve shared this with our engineering team and had them run down status for this fix. While there isn't a firm ETA yet, they are working to get it resolved by the end of the year.  I regret there isn’t more to share on this.
