### ISSUE TITLE
Microsoft Support _ Which Department was mentioned? 

### ISSUE THREAD

**Issue by BulletproofVan** [MicrosoftDocs/memdocs#875]
Please left the name of the Microsoft Department.  
Microsoft Support is split in several Departments, each has there own Support Area. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f3023a8-ab6c-1d77-0111-77cc7583347c
* Version Independent ID: 26debf60-c3c1-caa6-7f78-a04a8b8e73af
* Content: [Product and licensing FAQ - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/understand/product-and-licensing-faq)
* Content Source: [memdocs/configmgr/core/understand/product-and-licensing-faq.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/understand/product-and-licensing-faq.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @BulletproofVan, we've covered this topic pretty thoroughly in the past, see the following issues:
- MicrosoftDocs/SCCMdocs#2158
- MicrosoftDocs/SCCMdocs#493

I've talked with folks in support, and there's really not anything more we can do from a documentation perspective on this topic. Anyone in Microsoft Support can access the internal KB, it has instructions.
