### ISSUE TITLE
GPO Script: Time Issue

### ISSUE THREAD

**Issue by Kazzan** [MicrosoftDocs/memdocs#876]
Hi, the detection script for GPO and other throw errors if run.

Cannot bind parameter 'Start' to the target. Exception setting "Start": "Cannot convert null to type "System.DateTime"."

Seems that definition of $lastGPUpdateDate missing from script.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c319001-aa77-b53e-0975-4c55fbd7be87
* Version Independent ID: 35080234-188d-cb9a-fca9-8df7986b6a38
* Content: [PowerShell scripts for Proactive remediations - Configuration Manager](https://docs.microsoft.com/en-us/mem/analytics/powershell-scripts#bkmk_ps_scripts)
* Content Source: [memdocs/analytics/powershell-scripts.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/analytics/powershell-scripts.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @Kazzan for the feedback. The built-in script has changed, so we'll review and update the docs accordingly. You should be able to copy the latest script from the built-in.

**Comment by mestew** [comment]
Working on copying out script and getting it published. This issue will close automatically once the change is merged and staged for publish. The article changes might take a bit of time to be reflected in the live documentation.
