### ISSUE TITLE
Work profile - location

### ISSUE THREAD

**Issue by MarcoCibis** [MicrosoftDocs/memdocs#88]
Be aware - the location Android Device\Phone\Android\data\com.microsoft.windowsintune.companyportal\files\ is not accessible via USB when using a work profile. It will then redirect to the private area. The only way of accessing the logs yourself is using a file browser within your work profile.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 426365c8-4113-b445-7ecd-ab2117bcf52a
* Version Independent ID: cbec76e3-b29d-7fb6-b724-ca8b8b29a954
* Content: [Upload and email logs using a USB cable](https://docs.microsoft.com/en-us/mem/intune/user-help/send-logs-to-your-it-admin-using-cable-android)
* Content Source: [memdocs/intune/user-help/send-logs-to-your-it-admin-using-cable-android.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/user-help/send-logs-to-your-it-admin-using-cable-android.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @MarcoCibis Thank you for sharing your experience and feedback. Once I confirm this info with the product team, I'll update this article appropriately.

**Comment by lenewsad** [comment]
The documentation team hasn’t been able to find an answer for this issue. If this is still an issue for you, please try one of these support channels:

**Device users:**
* Reach out to the IT support person at your work or school for help.

**IT administrators:**

* Open a support ticket by following the steps here: [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support)  

* Post on [Microsoft Q & A](https://docs.microsoft.com/answers/products/?WT.mc_id=msdnredirect-web-msdn).

* Browse the old [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/home?forum=microsoftintuneprod). The site was recently replaced with Microsoft Q & A but still shows the old posts from our community MVPs who are very experienced, knowledgeable, and helpful.

* Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

**Comment by lenewsad** [comment]
I wanted to update this issue with an answer. The documentation team will update these docs with this information.

To access the logs from your work profile, you'll need to have access to a file viewer app in the work profile. 

1. Go to your work profile and open Company Portal.
2. Tap the menu > **Settings**.
3. Tap **COPY LOGS**.
4. Return to the work proile and open your file viewing app.
5. Tap the menu > **Show internal storage.** This step will vary from app to app, but the key here is to find the option that unhides your internal storage. 
6. Make sure you're viewing the internal storage for your device. If you don't see any folders appear, tap the app menu and then tap your device name to switch to your device's storage.  
6. When the folders appear, tap **Android** > **data** > **com.microsoft.windowsintune.companyportal\files\ > **files** to find the logs.
