### ISSUE TITLE
Per-App VPN Question

### ISSUE THREAD

**Issue by usvjosh** [MicrosoftDocs/memdocs#881]
Hello,

Can someone please explain the per-app vpn side of this to me? I'd like to know if we set this up with per-app vpn, that the specific app on the ios/android device will run through MS tunnel and all other apps will go out the wifi/cellular connection. Similar to split tunneling. 

We don't want to use per app and find out that all traffic starts to go through the VPN (for example background apps checking email). 

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ebaa15c-1e00-c075-eff2-79d4c10ba6af
* Version Independent ID: c9dfee71-1c01-4318-725c-b4bb97052efb
* Content: [Use the Microsoft Tunnel VPN solution for Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/microsoft-tunnel-overview)
* Content Source: [memdocs/intune/protect/microsoft-tunnel-overview.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/microsoft-tunnel-overview.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by sergiozygmunt** [comment]
I agree with the @usvjosh - How do we deploy per-app VPN using Microsoft Tunnel on iOS? The KB the Azure portal links to when you enable per-app VPN for Microsoft Tunnel in a new VPN configuration profile was last updated in May of 2020 despite Microsoft Tunnel being released for preview in September. Maybe there's an updated article that wasn't published?

**Comment by Brenduns** [comment]
@usvjosh   I checked with our engineering team and they agree that what your asking about is exactly what the per-app VPN does and you should be fine. 

- With per-app VPN, the specific app on the device will be directed through the tunnel. All other apps go out across other connections but not via the tunnel. 
- Split tunneling is more for the full device VPN where you can define some traffic going to the web, with the rest not going to the web.


@sergiozygmunt    For per-app VPN for Microsoft Tunnel on iOS, see [Configure Microsoft Tunnel]( https://docs.microsoft.com/mem/intune/protect/microsoft-tunnel-configure) for details.

**Comment by sergiozygmunt** [comment]
> @sergiozygmunt For per-app VPN for Microsoft Tunnel on iOS, see [Configure Microsoft Tunnel](https://docs.microsoft.com/mem/intune/protect/microsoft-tunnel-configure) for details.

@Brenduns The link you provided says (for iOS)
>To enable a per-app VPN, select Enable. Additional configuration steps are required for iOS per-app VPNs. When the per-app VPN is configured, your split tunneling rules are ignored by iOS.
For more information, see [Per-App VPN for iOS/iPadOS.](https://docs.microsoft.com/en-us/mem/intune/configuration/vpn-setting-configure-per-app)


but that second link doesn't have any information about setting up Per App VPN with Microsoft Tunnel as it was last updated in May. It only has information for setting up Per-App VPN with the VPNs supported prior to the release of Microsoft Tunnel.
