### ISSUE TITLE
Can you publish some documents on how to troubleshoot issues related to proactive remediation script deployment?

### ISSUE THREAD

**Issue by NagBibhash** [MicrosoftDocs/memdocs#883]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d35a1251-2323-4239-85d7-ca21f44cf93a
* Version Independent ID: d8bd22fc-6af5-075f-ecee-bb084483bbce
* Content: [Tutorial - Proactive remediations - Configuration Manager](https://docs.microsoft.com/en-us/mem/analytics/proactive-remediations)
* Content Source: [memdocs/analytics/proactive-remediations.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/analytics/proactive-remediations.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @NagBibhash, thanks for the feedback, but this is not something that we're going to be able to resource in the near future. We're not doing deep troubleshooting right now, just what you'll find in the [Troubleshoot](https://docs.microsoft.com/mem/analytics/troubleshoot) article.
