### ISSUE TITLE
Device Name Template

### ISSUE THREAD

**Issue by danbu** [MicrosoftDocs/memdocs#890]
Should be a note about that if you have a Enrollment profile (iOS) that uses a "Device Name Template" then the device will rename but then will revert to the Template name scheme upon next sync with Intune.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab62517e-47bd-a28d-5907-5fd3841f8504
* Version Independent ID: 765044bd-ef1c-1dc3-c48e-3bbdb602e1c7
* Content: [Rename a device with Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/remote-actions/device-rename)
* Content Source: [memdocs/intune/remote-actions/device-rename.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/remote-actions/device-rename.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
8663001
