### ISSUE TITLE
"What happens when a profile is deleted or no longer applicable" - the guidance for Windows is incorrect

### ISSUE THREAD

**Issue by rbalsleyMSFT** [MicrosoftDocs/memdocs#892]
In the section "What happens when a profile is deleted or no longer applicable", the guidance for Windows is incorrect. If a profile is deleted, Intune will delete a profile from a device. For example, if you apply a device restriction profile that blocks the Spotlight functionality to a user and delete that profile, Intune will delete it from the device. You can confirm this in the device management log in event viewer. 

It is possible, however, that certain profiles or policies may tattoo to the device, depending on how Intune and/or the CSP was implemented in Windows. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14c045c9-2ccb-e24b-9eaa-bfd65b64a48c
* Version Independent ID: 355e928b-5ad8-ac1d-24d4-1d2e8f11cb4d
* Content: [Troubleshoot device profiles in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/device-profile-troubleshoot#what-happens-when-a-profile-is-deleted-or-no-longer-applicable)
* Content Source: [memdocs/intune/configuration/device-profile-troubleshoot.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/device-profile-troubleshoot.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@rbalsleyMSFT [What happens when a profile is deleted or no longer applicable?](https://docs.microsoft.com/mem/intune/configuration/device-profile-troubleshoot#what-happens-when-a-profile-is-deleted-or-no-longer-applicable) now includes this information. Changes should be live later today.

Thank you!
