### ISSUE TITLE
.NET 4.7 is required

### ISSUE THREAD

**Issue by pedrr** [MicrosoftDocs/memdocs#895]
In the Setup Log we can see that the setup is installing .Net 4.7.  You may adjust the section requirements.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa43fc11-ff6b-20c8-5bfa-a89572295223
* Version Independent ID: ea0f43b6-5c74-6f9e-7e0c-ec86db3e4400
* Content: [Use imported PFX certificates in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/certificates-imported-pfx-configure#requirements)
* Content Source: [memdocs/intune/protect/certificates-imported-pfx-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certificates-imported-pfx-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@pedrr   Thanks for raising this to my attention. The newer connector versions, do require .NET 4.7.2, as noted in https://docs.microsoft.com/mem/intune/protect/certificate-connectors#pfx-certificate-connector-for-microsoft-intune.  Looks like this reference hadn't been updated. That will be fixed later today.
