### ISSUE TITLE
Cut, copy, and paste/ Data transfer restrictions and force PIN entry do not work properly

### ISSUE THREAD

**Issue by phuong-vo** [MicrosoftDocs/memdocs#896]
Hello all,
I create an Intune App Protection with properties as below screen captures
I used this policy for Cut, copy, and paste/ Data transfer restrictions and force PIN entry features for users and devices (this is MAM action, so my device does not need to be compliant, but I did test for both)
To test this, I added my users into the included groups (in my case it is BK iOS-Restrict Device group) and on device I used Microsoft Teams. I got results:
- For devices, these features do not work at all.
- For users (users already log into Microsoft Teams), these features only work when users log out and log back in.

![Screen Shot 2020-10-19 at 10 19 28 AM](https://user-images.githubusercontent.com/6592922/96492637-cdf6d780-11f8-11eb-9a55-a2f362b8de4c.png)

continue...
![Screen Shot 2020-10-19 at 10 20 07 AM](https://user-images.githubusercontent.com/6592922/96492734-eebf2d00-11f8-11eb-9722-6e3443dd816a.png)

continue...
![Screen Shot 2020-10-19 at 10 20 42 AM](https://user-images.githubusercontent.com/6592922/96492817-0d252880-11f9-11eb-93ef-84b0bda461cb.png)

Could you please help me to find out what I missed?
Thank you very much for your help,
Phuong

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cde34bc-bab0-d412-5971-cbc1f515a486
* Version Independent ID: ac355bba-5f6f-0168-49f3-67b7a2ddb2d4
* Content: [Create and deploy app protection policies - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policies?source=docs)
* Content Source: [memdocs/intune/apps/app-protection-policies.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-protection-policies.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
We have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. If you have continue to have questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

This question is in our documentation feedback channel and it may be best to handle this question as a support request. For this reason, I'm closing this issue. Please use the above channels if you don't already have a solution.
