### ISSUE TITLE
portal.azure.com

### ISSUE THREAD

**Issue by fox-on-the-run** [MicrosoftDocs/memdocs#9]
Would it not be better to refer to devicemanagement.microsoft.com instead of Azure portal at https://portal.azure.com.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3929b5a0-f852-ce35-4ecd-72d5b9b4a948
* Version Independent ID: 33b804a6-5bf9-75e6-13e0-f2a35e07ef8f
* Content: [Frequently asked questions about MAM and app protection](https://docs.microsoft.com/en-us/mem/intune/apps/mam-faq#app-experience-on-ios)
* Content Source: [memdocs/intune/apps/mam-faq.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/mam-faq.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@fox-on-the-run - Thanks for the feedback. We're updating the docs now.
