### ISSUE TITLE
Server 2008 era

### ISSUE THREAD

**Issue by russrimm** [MicrosoftDocs/memdocs#901]
This example page is pre CNG v3 template era, would you like for me to submit updates to it or is there already a plan to rework it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a41a19c-d822-1ee7-80a7-3672e1d47077
* Version Independent ID: 305cb6a2-adf1-87d5-212e-456e945cf5fd
* Content: [Example PKI certificate deployment - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/network/example-deployment-of-pki-certificates)
* Content Source: [memdocs/configmgr/core/plan-design/network/example-deployment-of-pki-certificates.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/network/example-deployment-of-pki-certificates.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @russrimm, we do have an internal item tracking rework to this article as well as the main PKI certs article. But it's been languishing for a while, trying to find resourcing for it. If you want to take a swing at changes to it, go ahead! I'm going to close this issue.
