### ISSUE TITLE
running the tool on an all in one MECM server

### ISSUE THREAD

**Issue by PaulKlerkx** [MicrosoftDocs/memdocs#905]
Can you perhaps make it clearer, the way I read this is a little vague, but it suggests to me that maybe, if you have a single primary Site server that also contains your DP, this tool is not able to assist with cleaning up the DP of invalid content.  Is that correct? Also, is there another option for this scenario? - I.E. "if you have this all in one setup, invalid content can only be cleaned up using the following process...(with link to whatever that process is maybe)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5902fbb-8ca5-6cfb-bb5e-fbbe4d68e712
* Version Independent ID: 51544ed6-18b7-d926-e45f-c817b8e26d69
* Content: [Content library cleanup tool - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/hierarchy/content-library-cleanup-tool)
* Content Source: [memdocs/configmgr/core/plan-design/hierarchy/content-library-cleanup-tool.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/hierarchy/content-library-cleanup-tool.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @PaulKlerkx for the feedback. You're right, we could clarify a bit. The tool doesn't support removing content from the site server. It has a single content library, whether or not the DP role is on the same server. So even if a package isn't targeted to the collocated DP role, it's still in the site server's content library.

**Comment by aczechowski** [comment]
Probably also worth explicitly mentioning that it doesn't support cloud-enabled CMG or CDP.

**Comment by aczechowski** [comment]
I made a change for this issue as part of the 2010 current branch release content. This issue will automatically close when my pull request merges. It won't go live until the 2010 content publishes.
