### ISSUE TITLE
Sample code doesn't work

### ISSUE THREAD

**Issue by larsa2000** [MicrosoftDocs/memdocs#910]
The sample code for Xamarin Forms just shows a white page. The documentation states "If you encounter a blank, white screen in your application on launch, then you may need to force the navigation calls to execute on the main thread.", which is very unclear. OnMAMCreate doesn't get called so the app isn't staring up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 123cb14f-5edf-1bdd-1f16-00ce32443583
* Version Independent ID: c41ef518-bc7a-d87e-b03c-31cba1de6d0a
* Content: [Microsoft Intune App SDK Xamarin Bindings](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-xamarin#support)
* Content Source: [memdocs/intune/developer/app-sdk-xamarin.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/developer/app-sdk-xamarin.md)
* Service: **microsoft-intune**
* Sub-service: **developer**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
Thanks for the feedback. Please see the following forum post: [White screen after application start](https://forums.xamarin.com/discussion/149109/white-screen-after-application-start), it looks helpful. 

If you have additional questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

This question is in our documentation feedback channel and it may be best to handle this question as a support request. For this reason, I'm closing this issue. Please use the above channels if you don't already have a solution.
