### ISSUE TITLE
Potential Missing step

### ISSUE THREAD

**Issue by Jlouden9** [MicrosoftDocs/memdocs#913]
Hi,

When on-boarding devices to Defender for Endpoint (MDATP), post setting up the policies and assigning them devices don't magically appear in MDATP. They require a user to logon to the device for the sensor to be installed. I believe this should be included either as a final step in the section "Create the device configuration profile to onboard Windows devices". 

Also I don't believe the step 2 listed in this section is valid\best pratice anymore. The ideal location would be to use Endpoint Security -> Endpoint detection and response.

The is overlap  between these two options. If a user was to create a policy in both area's it would result in a conflict error.

 I have had a few clients run foul of this missing information.

Regards
John

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24fa182f-ace6-e7e2-ff98-91951be7d10e
* Version Independent ID: f1acb398-6d69-b91c-5ee0-3da3bbf7809f
* Content: [Configure Microsoft Defender ATP in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/advanced-threat-protection-configure)
* Content Source: [memdocs/intune/protect/advanced-threat-protection-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/advanced-threat-protection-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@Jlouden9  Thanks for this issue. I'll be adding some clarifications to this content in the next day or so. To answer you directly:

- When the profile deploys to a user, that user must login before the device can install and onboard. However, when deploying to a device, the device will onboard without user involvement or login. (Some changes are pending to make it clear you can deploy to both users or devices). 
- Endpoint detection and response policy is newer, and while it doesn't _replace_ device configuration profiles as in this article, its a newer method to get the same end result. We'll be adding cross-links and mention of the newer policy and content.
