### ISSUE TITLE
When a CMG needs its Cert and / or API Secrete Key Renewed Section?

### ISSUE THREAD

**Issue by Chadwicksracing** [MicrosoftDocs/memdocs#916]
Add this reference to this page:
https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/azure-services-wizard#bkmk_renew

Perhaps instead of having it the settings part of the page (https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/modify-cloud-management-gateway#settings-tab)  maybe make it easier to see or a better call to action header?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12ab4165-870a-9fea-872a-35c03d2ba338
* Version Independent ID: b9015594-b05d-05dd-ef03-a99c3a4be225
* Content: [Modify a cloud management gateway - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/modify-cloud-management-gateway)
* Content Source: [memdocs/configmgr/core/clients/manage/cmg/modify-cloud-management-gateway.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/cmg/modify-cloud-management-gateway.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Chadwicksracing 😉

**Comment by aczechowski** [comment]
See original thread: https://twitter.com/brower_chad/status/1319345738724376578
