### ISSUE TITLE
Can't add new Users on Corporate-owned fully managed device.

### ISSUE THREAD

**Issue by Mela-SAG** [MicrosoftDocs/memdocs#918]
Hi everyone

 

We have a Android 10 Tablet that without Intune enrolled you have the Option to Add new Users.

We want to enroll this Device and use it as "Multi Users Device".

 

When we enroll this Device through "Corporate-owned fully managed device", this option disappear.

We have also check on the our Device Restrictions and set as per Guide (https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-android-for-work#users...) the Option to "Add new users" to "not configure", but the option still disappear.

 

Interesting is that if I search in to the Settings for "New Users", he give me a "link" to his point, but when click on it, bring you to the "Settings\Account and BackUp\Users" where principally this Option is, but it is not there :(

 

Who anyone have an Idea....?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 900e72be-d42b-49ba-f304-602df23cbb04
* Version Independent ID: 2ce5c45d-15be-d316-1c57-92bea37358e0
* Content: [Android Enterprise device settings in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-android-for-work#users-and-accounts)
* Content Source: [memdocs/intune/configuration/device-restrictions-android-for-work.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/device-restrictions-android-for-work.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@Mela-SAG Hi Mela - For technical help, it's best to post your question to the [Microsoft Intune forums](https://docs.microsoft.com/answers/products/mem). These are moderated by our community and MVPs, who are very experienced, knowledgeable, and helpful.

**Comment by Mela-SAG** [comment]
Thanks.
