### ISSUE TITLE
Core infrastructure documentation

### ISSUE THREAD

**Issue by gardmkdg** [MicrosoftDocs/memdocs#920]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4417335-de0a-6a49-b1b4-5551199d8643
* Version Independent ID: 761507d4-99d2-991a-8baf-e0010d962d35
* Content: [Publishing and the Active Directory schema - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/network/extend-the-active-directory-schema)
* Content Source: [memdocs/configmgr/core/plan-design/network/extend-the-active-directory-schema.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/network/extend-the-active-directory-schema.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by gardmkdg** [comment]
Core infrastructure documentation

**Comment by aczechowski** [comment]
Hi @gardmkdg this looks like a test or a accident, so I'm going to close it. If you have some specific feedback on this article, please add more detail and reopen the issue.
