### ISSUE TITLE
upload intune enrollment profiles to ADE

### ISSUE THREAD

**Issue by Driepma** [MicrosoftDocs/memdocs#921]
This article states the following:
 It also lets Intune upload enrollment profiles to Apple and to these profiles to devices.

I've linked Intune to ABM, set up all the tokens and such, works fine, but there's nothing in ABM that lets me link the enrollment profiles i've created in intune to devices in ABM?
It would be great to be able to assign devices there, so i can make a selection between a user-based enrollment or a kiosk-based enrollment before the device is shipped.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0319ece7-6b1f-d737-618c-778d3f196313
* Version Independent ID: 20b5b39e-56e2-d88e-e4b2-22a79b5d3ccb
* Content: [Enroll macOS devices - Apple Business Manager or Apple School Manager](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-macos)
* Content Source: [memdocs/intune/enrollment/device-enrollment-program-enroll-macos.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/device-enrollment-program-enroll-macos.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@Driepma Looks like the sentence you quoted is missing a word (which I'll fix). It should read: It also lets Intune upload enrollment profiles to Apple and assign these profiles to devices.

Assigning profiles to devices is done in Intune: https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-macos#assign-an-enrollment-profile-to-devices

Let me know if you have any more questions.
