### ISSUE TITLE
LOB is not equal to in-house

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/memdocs#923]
I have an issue with the way you describe Line of Business Windows apps as being developed "in house". This is confusing for people as most organisations do not have an in house development team and it is more likely they are installing software that is just purchased outside of the Windows App Store. E.g. if I wanted to deploy Adobe Reader then that clearly wasn't developed in house (it also is more of a productivity app than a Line of Business one).
I work for a Microsoft Partner consultancy and this confusion constantly comes up when discussing with my clients. I'd say on average only about 10% of software that a client uses is in the Microsoft Store, the rest is purchased direct from the vendor as and supplied as an MSI, not developed in house.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eda39475-7d32-b359-ed80-b1e3ed3aee70
* Version Independent ID: 4fe0e69a-fa68-1635-8c4c-6570032df2a7
* Content: [Add apps to Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-add#uninstall-an-app)
* Content Source: [memdocs/intune/apps/apps-add.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/apps-add.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
Thanks for the feedback. "Custom" app may make sense here. I'm reviewing, but plan to update the language of this doc to make it more clear.

**Comment by Erikre** [comment]
Updating the topic now. Thanks again for the feedback.
