### ISSUE TITLE
Mix-up in Page Disk encryption policy settings for endpoint security in Intune

### ISSUE THREAD

**Issue by 3deep5me** [MicrosoftDocs/memdocs#924]
Hello,

I think there is a mix-up. In Intune it says: 
Allow standard users to enable encryption during Autopilot
When set to Yes, during Azure Active Directory Join (AADJ) silent enable scenarios, users do not need to be local administrators to enable BitLocker. When set to not configured, the setting will be left as client default which is to require local admin access to enable BitLocker. For non-silent enablement/Autopilot scenarios, the user must be a local admin to complete the BitLocker setup wizard.

But in the documentary it says:
Allow standard users to enable encryption during Autopilot
CSP: AllowStandardUserEncryption

Not configured (default) – During Azure Active Directory Join (AADJ) silent enable scenarios, users don't need to be local administrators to enable BitLocker.
Yes - The setting is left as client default, which is to require local admin access to enable BitLocker.
For non-silent enablement and Autopilot scenarios, the user must be a local admin to complete the BitLocker setup wizard.

Which one is right?

**Comment by Brenduns** [comment]
@3deep5me   Thanks for submitting this, it appears that this settings details are reversed in the docs. I'm submitting a fix for this later today for https://docs.microsoft.com/mem/Intune/protect/endpoint-security-disk-encryption-profile-settings.

When the setting is set to Yes, disk encryption can occur when the logged on user is a standard user.  By default, that requires administrative access. 

As a general guide, should you cross other suspect settings details, fall back to reference the underlying CSP's from Windows. For this setting, that CSP is AllowStandardUserEncryption, and the UI link (also replicated in docs) goes to https://docs.microsoft.com/windows/client-management/mdm/bitlocker-csp#allowstandarduserencryption where the behavior as defined and managed by Windows is detailed.
