### ISSUE TITLE
DEM initiated via Company Portal

### ISSUE THREAD

**Issue by bleek00** [MicrosoftDocs/memdocs#931]
How can I enroll a windows 10 device with DEM using company portal?
In this article it just say “DEM initiated via Company Portal” but it has no link or more guidance on how to do it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7786d9c0-55b0-9bff-fc0a-f4ee70ee0615
* Version Independent ID: cf0c17a0-fdc7-e0af-db82-913e36d2ec7c
* Content: [Enroll devices using a device enrollment manager account - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-manager-enroll)
* Content Source: [memdocs/intune/enrollment/device-enrollment-manager-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/device-enrollment-manager-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@bleek00 You can learn more about Company Portal enrollment here: https://docs.microsoft.com/en-us/mem/intune/user-help/use-managed-devices-to-get-work-done
I'll update the doc with the link.
