### ISSUE TITLE
Needs Updating

### ISSUE THREAD

**Issue by Aegrum** [MicrosoftDocs/memdocs#932]
[Enter feedback here]
This page hasn't been updated in 2 years. It's missing a **substantial** amount of information related to remote management of devices. Please update this to include all the newer remote actions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 217e72bd-8597-5640-7000-37a3eb2d5f29
* Version Independent ID: 202cad01-13d1-37c1-c794-6d31621cdab2
* Content: [Manage devices with Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/remote-actions/device-management#available-device-actions)
* Content Source: [memdocs/intune/remote-actions/device-management.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/remote-actions/device-management.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
8760905

**Comment by MandiOhlinger** [comment]
@Aegrum Thank you for input. We added some extra info to state that not all device actions are listed in the article. Changes should be live later today.
