### ISSUE TITLE
PKCS and device certificate question

### ISSUE THREAD

**Issue by nhogarth86** [MicrosoftDocs/memdocs#938]
Regarding PKCS certificates it says "When deployed to a device that lacks a user affinity, the certificate isn’t provisioned.". 

In 2019 there was an Intune update "You can now use PKCS certificate profiles to issue certificates to devices that run Android for Work, iOS/iPadOS, and Windows, when associated with profiles like those for Wi-Fi and VPN" https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new-archive#use-pkcs-certificate-profiles-to-provision-devices-with-certificates

Is the original comment about a device that lacks user affinity still true?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2320f32-f46c-c4a8-1c22-1a79b44f1075
* Version Independent ID: abd36170-7d28-8708-29d6-45260ef44df5
* Content: [Learn about certificate types and profiles you use with Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/certificates-configure#which-certificate-profile-to-use)
* Content Source: [memdocs/intune/protect/certificates-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certificates-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@nhogarth86   Hello Nick, this took a crazy amount of time to run down, but in working with our PM for this feature area, we are able to identify and update and sent it to publication, going live later today. The original entry for PKCS certificate omitted some context regarding the certificate type used in the template. That's been added to the entry with a bit more detail. The update is a bit more structured, but aligns to the following: 

User affinity is required when you deploy a template with a certificate type of User.  User affinity isn't required when the certificate type is Device. If a Device type template targets a user, then any device the user logs into that has user affinity would get a device cert.
