### ISSUE TITLE
Either 

### ISSUE THREAD

**Issue by Anoni-Mouse** [MicrosoftDocs/memdocs#939]
When the documentation says:
Fixed data drive encryption: If you enable this setting, BitLocker requires users to put all fixed data drives under protection. It then encrypts the data drives. When you enable this policy, **either** enable auto-unlock **or** the settings for Fixed data drive password policy.

Does this mean I cannot have BOTH? Please elaborate
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d362145-5048-abf3-fad0-1b6c25f76447
* Version Independent ID: 988e83fa-54da-9bf6-ba19-98006f0043a2
* Content: [Deploy BitLocker management - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/protect/deploy-use/bitlocker/deploy-management-agent)
* Content Source: [memdocs/configmgr/protect/deploy-use/bitlocker/deploy-management-agent.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/protect/deploy-use/bitlocker/deploy-management-agent.md)
* Product: **configuration-manager**
* Technology: **configmgr-protect**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @Anoni-Mouse - it's one or the other, not both. If the drive automatically unlocks, it's still encrypted, but it wouldn't prompt for a password. Without auto-unlock, then it requires the user to provide a password. There's a little more explanation in the settings reference article, as linked just below the setting you reference:

> For more information on these and other settings on this page, see [Settings reference - Fixed drive](https://docs.microsoft.com/mem/configmgr/protect/tech-ref/bitlocker/settings#fixed-drive).
