### ISSUE TITLE
Auto MDM Enroll: Device Credential (0x1), Failed (Unknown Win32 Error code: 0x80180001)

### ISSUE THREAD

**Issue by PaulEstevesAtPEX** [MicrosoftDocs/memdocs#94]
When looking in the DeviceManagement-Enterprise-Diagnostics-Provider Admin event viewer logs I find Event ID 76:
Auto MDM Enroll: Device Credential (0x1), Failed (Unknown Win32 Error code: 0x80180001)

This is for a hybrid AD environment on a locally joined machine that does show the Azure Devices as 'Hybrid Azure AD joined'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fbb1036-7815-586b-f86c-89065a44cf9b
* Version Independent ID: f19e131c-88f4-73d6-5fdc-8faac18763ee
* Content: [Troubleshooting Windows device enrollment problems in Microsoft Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/troubleshoot-windows-enrollment-errors)
* Content Source: [memdocs/intune/enrollment/troubleshoot-windows-enrollment-errors.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/troubleshoot-windows-enrollment-errors.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@PaulEstevesAtPEX Thanks for taking the time to share this with the Intune documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a few options available to provide the best level of support for this:   
- Post on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.   
- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.   
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.   

  

I'm closing this issue as there's nothing actionable for docs at this time.
