### ISSUE TITLE
Allow access to Bitlocker-protected fixed data drives from earlier versions of Windows

### ISSUE THREAD

**Issue by Anoni-Mouse** [MicrosoftDocs/memdocs#941]
This option seen in Bitlocker policy from the SCCM console (2006), namely **Allow access to Bitlocker-protected fixed data drives from earlier versions of Windows** is not mentioned in the documentation. Please update the docs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92b32250-24be-03a2-1f56-13adadcad80c
* Version Independent ID: d6fbfb74-cc14-d27a-4c97-2aafd111d691
* Content: [BitLocker settings reference - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/protect/tech-ref/bitlocker/settings#setup)
* Content Source: [memdocs/configmgr/protect/tech-ref/bitlocker/settings.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/protect/tech-ref/bitlocker/settings.md)
* Product: **configuration-manager**
* Technology: **configmgr-protect**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @Anoni-Mouse, it's purposefully not included. We have a bug to remove it from the UI, as it doesn't apply anymore:

> **Allow access to BitLocker-protected fixed drives from earlier versions of Windows**
> Enable this policy so that fixed drives with the FAT file system can be unlocked and viewed on computers that are running Windows Server 2008, Windows Vista, Windows XP with SP3, or Windows XP with SP2.
