### ISSUE TITLE
Enormous Delay before applying

### ISSUE THREAD

**Issue by jonathan-gaudreau** [MicrosoftDocs/memdocs#942]
https://docs.microsoft.com/en-us/mem/intune/fundamentals/unlicensed-admins
I hit the button around 10 AM yesterday and by the end of the day it wasn't working and i Had to open a case because nowhere in the page it's written that It could take that much time.
Please update the information on this page to mention that it can take up to 24 hours.
That way, you'll probably prevent mobilizing the support time for an issue that isn't one.

(admin edit: add article metadata for proper linking)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04418415-45d5-1775-ece7-94da93d6ab2f
* Version Independent ID: 483b6c54-8ec4-2842-bee8-8610fe97b677
* Content: [Unlicensed admins in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/unlicensed-admins)
* Content Source: [memdocs/intune/fundamentals/unlicensed-admins.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/unlicensed-admins.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
8726781

**Comment by ErikjeMS** [comment]
repinged pm

**Comment by ErikjeMS** [comment]
The documentation team hasn’t been able to find an answer for this issue. If this is still an issue for you can try any of the following: 

- Open a support ticket by following the steps here: [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support). 

- Post on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.   

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.   

 I'm closing this issue as there's nothing actionable for docs at this time.
