### ISSUE TITLE
Stale link

### ISSUE THREAD

**Issue by p0shkar** [MicrosoftDocs/memdocs#95]
"For more information, see Microsoft Intune Co-existence with MDM for Office 365"

This links to stale/archived information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a76fc834-999b-2dea-10b7-984225b695dd
* Version Independent ID: 583b8b02-5c7b-aa08-ec28-07b89adbd994
* Content: [Set the mobile device management authority - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/mdm-authority-set)
* Content Source: [memdocs/intune/fundamentals/mdm-authority-set.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/mdm-authority-set.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
(6979767)

**Comment by ErikjeMS** [comment]
@p0shkar Unfortunately, we don't have a new blog post to link to. To avoid confusion, I'm deleting the link.
