### ISSUE TITLE
Confusion between our docs re: Intune licenses for admins (or not)

### ISSUE THREAD

**Issue by hilde-msft** [MicrosoftDocs/memdocs#953]
This doc says an admin must have an Intune license to administer Intune - yet this other doc that says that isn't true: https://docs.microsoft.com/en-us/mem/intune/fundamentals/unlicensed-admins

We need to align these three links so they all say the same thing re: administration/portal access for admins:
https://docs.microsoft.com/en-us/mem/configmgr/comanage/overview#prerequisites
https://docs.microsoft.com/en-us/mem/intune/fundamentals/licenses
https://docs.microsoft.com/en-us/mem/intune/fundamentals/unlicensed-admins
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73c7bea7-ccff-ca28-35e4-820494059bf6
* Version Independent ID: 42e6e56f-d5ca-4124-f409-7e34ca609a3a
* Content: [Licenses available for Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/licenses)
* Content Source: [memdocs/intune/fundamentals/licenses.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/licenses.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@aczechowski Do you want to add a note to your [CM article](https://docs.microsoft.com/en-us/mem/configmgr/comanage/overview#prerequisites) about the new [unlicensed admin feature](https://docs.microsoft.com/en-us/mem/intune/fundamentals/unlicensed-admins) in MEM?

**Comment by aczechowski** [comment]
Reference #949 
Taking offline with Erik to discuss

**Comment by ErikjeMS** [comment]
Added info to Licenses article.
