### ISSUE TITLE
NO_SMS_ON_DRIVE.SMS, PowerShell Automation and Logs to be monitored - can be added in docs

### ISSUE THREAD

**Issue by Sri-Boddupalli** [MicrosoftDocs/memdocs#954]
NO_SMS_ON_DRIVE.SMS step is missing in Install a distribution point section. If could mention that file and how to use that file to prevent installing DP content on unrelated Drive letters it can be very helpful 

PowerShell way of automating the installation of DP can be mentioned for advance administrators who don't want to spend lot of time on writing their own code

Logs to be monitored during the installation of distribution point and other remediation steps can be specified. It can be easier to follow this single place for those things 

(admin edit: adding article metadata for proper link and tracking)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47242ed6-ef2e-f497-6f04-61a790b9935b
* Version Independent ID: c1180f2a-0caa-1295-7b22-bc7897c56d4b
* Content: [Manage distribution points - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/install-and-configure-distribution-points#bkmk_install)
* Content Source: [memdocs/configmgr/core/servers/deploy/configure/install-and-configure-distribution-points.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/deploy/configure/install-and-configure-distribution-points.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Sri-Boddupalli for the feedback, good suggestions.
