### ISSUE TITLE
Link for "New tools to help IT empower employees securely in a remote work world"

### ISSUE THREAD

**Issue by AnnaAmelia** [MicrosoftDocs/memdocs#955]
The link for _"New tools to help IT empower employees securely in a remote work world"_ in the section _"What is endpoint analtics"_  is broken, it redirects to Page not found error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f003e4ec-77c1-80fd-1c19-51ee2c78595f
* Version Independent ID: 47b778f5-909a-7432-3da3-ee9afe24146b
* Content: [What is Endpoint analytics? - Configuration Manager](https://docs.microsoft.com/en-us/mem/analytics/overview)
* Content Source: [memdocs/analytics/overview.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/analytics/overview.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @AnnaAmelia, thanks for the feedback and sorry for the issue. I'm assuming it was a transient issue, it's opening ok for me. Please try again, and let us know if it's still not working.

**Comment by AnnaAmelia** [comment]
Hi @aczechowski still not working for me - it has something to do with language/location settings, as I get redirected to https://www.microsoft.com/de-de/microsoft-365/blog/2020/04/30/new-tools-help-it-empower-employees-securely-remote-work-world/  -so instead of "en-us" I get "de-de", which is wrong address...

**Comment by aczechowski** [comment]
Ah...if you manually switch the URL to en-us, does it work? https://www.microsoft.com/en-us/microsoft-365/blog/2020/04/30/new-tools-help-it-empower-employees-securely-remote-work-world/

If so, that's unfortunate, sorry about that. We almost always specify locale-neutral links. But if this blog is only available in US English, then I'll have to explicitly set it as such.

**Comment by aczechowski** [comment]
I put in a change to add the locale. This issue will auto-close when that change merges, and then will go live with the next daily publishing cycle. Right now that should be tomorrow (Thursday) morning around 10 AM Pacific. Thanks again for the feedback, and sorry for the difficulty (and en-us requirement 😞 )
