### ISSUE TITLE
"What happened to the Ready for Windows website?"

### ISSUE THREAD

**Issue by bubbletroubles** [MicrosoftDocs/memdocs#958]
Hi,

The page at https://docs.microsoft.com/en-us/mem/configmgr/desktop-analytics/ready-for-windows#what-happened-to-the-ready-for-windows-website

has a section titled "What happened to the Ready for Windows website?", but the question is not answered - e.g. the text below that heading doesn't actually say what happened to the website. From what I can see it no longer exists, but the page doesn't say that, nor does it say the date when it ceased to be available. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e52c79ee-df65-469d-2a3d-86f95992d547
* Version Independent ID: fac30b7a-46ee-7bc9-7ab7-b33c87f2bfe3
* Content: [Ready for Windows - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/desktop-analytics/ready-for-windows#what-happened-to-the-ready-for-windows-website)
* Content Source: [memdocs/configmgr/desktop-analytics/ready-for-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/desktop-analytics/ready-for-windows.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @bubbletroubles, I'll snip a response from the lead PM on an older issue with the same question:

> The readyforwindows.com site is no longer available. We've heard from IT admins they want these insights integrated with the tools they already use to plan their deployments. Use Desktop Analytics and Office 365 ProPlus readiness features in Configuration Manager to plan and manage your Windows 10 and Office 365 ProPlus upgrades

[Reference](https://github.com/MicrosoftDocs/SCCMdocs/issues/2040)

It's also implicit in that the URL redirects to this article.
