### ISSUE TITLE
command line "Server=[Servername FQDN]" missing from docs

### ISSUE THREAD

**Issue by scott-ip1** [MicrosoftDocs/memdocs#959]
There is a "Server=[FQDN]" option for the command line that is not documented to specify the system for the console to connect to when starting

Are there any others?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cef4bca8-634b-87a8-f479-d2e3da8a85c8
* Version Independent ID: ded2670d-c188-f6ef-6852-d41323c04fab
* Content: [Configuration Manager console - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/manage/admin-console)
* Content Source: [memdocs/configmgr/core/servers/manage/admin-console.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/manage/admin-console.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @scott-ip1 for the feedback.
