### ISSUE TITLE
Update documentation regarding choice of authentication

### ISSUE THREAD

**Issue by p0shkar** [MicrosoftDocs/memdocs#96]
"choose Yes under Authenticate with Company Portal instead of Apple Setup Assistant."

A dropdown containing "Setup Assistant" and "Company Portal" has replaced this option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e94556e6-69f3-5c56-f77d-01a810473e6a
* Version Independent ID: 8928627b-e085-2660-38dc-bf6a0ce9a6d8
* Content: [Tutorial - Use Apple Business Manager or the Device Enrollment Program to enroll iOS/iPadOS devices in Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/tutorial-use-device-enrollment-program-enroll-ios)
* Content Source: [memdocs/intune/enrollment/tutorial-use-device-enrollment-program-enroll-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/tutorial-use-device-enrollment-program-enroll-ios.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@p0shkar Thanks! I'll fix this today.
