### ISSUE TITLE
Information about App protection policies is not correct

### ISSUE THREAD

**Issue by JuGhithub** [MicrosoftDocs/memdocs#960]
[Enter feedback here]

Hi, 

There is a few page on docs.microsoft.com about Intune App protection policies that refer to portal.azure.com like "App protection policies can be created and deployed in the Intune console in the Azure portal. "

But Intune was not anymore available on portal.azure.com but only on Intune portal https://endpoint.microsoft.com

So, documentation needs to be updated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17955fd7-d652-8f0e-4446-00b8628d58cc
* Version Independent ID: 46755b3c-43a5-f5c9-0b74-ce2b7ede7d40
* Content: [App protection policies overview - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policy)
* Content Source: [memdocs/intune/apps/app-protection-policy.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-protection-policy.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@JuGhithub - Thanks for the feedback. Updating this content now. Thanks
