### ISSUE TITLE
Incorrectly showing Teams as a supported app!

### ISSUE THREAD

**Issue by StChrist-MSFT** [MicrosoftDocs/memdocs#961]
Hi there documentation maintainers,

Please update this page to reflect the actual apps that are supported. Teams is sadly not one of them right now.

Align with this page maybe?
https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/concept-conditional-access-grant#require-app-protection-policy

I have also validated internally in a test tenant and in customer environments.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d9a11b1-ff48-8c1e-9dbe-c48a7e4dc350
* Version Independent ID: 6bd15450-157a-e2e8-c636-e692c7ff6e81
* Content: [Data protection framework using app protection policies - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-framework)
* Content Source: [memdocs/intune/apps/app-protection-framework.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-protection-framework.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
I verified in Endpoint Manager and found that Teams is now supported. Closing this GitHub Issue.
