### ISSUE TITLE
"Quickstart: Set up automatic enrollment for Windows 10 devices" not accessible to roles listed on page

### ISSUE THREAD

**Issue by dfsaqwe** [MicrosoftDocs/memdocs#963]
Document states

Sign in to the Microsoft Endpoint Manager admin center as a Global Administrator or **an Intune Administrator.**

Note that Intune Administrator role **does not** have access to modify the settings provided on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adbfe90c-635e-5d23-f0b3-2d015565e311
* Version Independent ID: bcc85788-87a8-c3b5-1b60-a4938a09e541
* Content: [Quickstart - Set up automatic enrollment in Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/quickstart-setup-auto-enrollment)
* Content Source: [memdocs/intune/enrollment/quickstart-setup-auto-enrollment.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/quickstart-setup-auto-enrollment.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
8733199

**Comment by ErikjeMS** [comment]
Repinged pm...

**Comment by ErikjeMS** [comment]
The documentation team hasn’t been able to find an answer for this issue. If this is still an issue for you can try any of the following: 

- Open a support ticket by following the steps here: [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support). 

- Post on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.   

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.   

 I'm closing this issue as there's nothing actionable for docs at this time.
