### ISSUE TITLE
Please specify SQL Server Edition

### ISSUE THREAD

**Issue by joseluiscc** [MicrosoftDocs/memdocs#965]
[Enter feedback here]

Please specify SQL Server Edition, for Always On Availability Groups, Configuration Manager requires SQL Enterprise edition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f3023a8-ab6c-1d77-0111-77cc7583347c
* Version Independent ID: 26debf60-c3c1-caa6-7f78-a04a8b8e73af
* Content: [Product and licensing FAQ - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/understand/product-and-licensing-faq)
* Content Source: [memdocs/configmgr/core/understand/product-and-licensing-faq.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/understand/product-and-licensing-faq.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @joseluiscc, we made a decision earlier this year to specifically not include that topic in this article. For more information, see the following historical issues:

- MicrosoftDocs/SCCMdocs#1274
- MicrosoftDocs/SCCMdocs#464
