### ISSUE TITLE
It would be nice when this page would explain how this relates to the All Systems Collection.

### ISSUE THREAD

**Issue by koenraadrens** [MicrosoftDocs/memdocs#967]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80fd687b-ad5d-4e45-93bd-f5c0f938603b
* Version Independent ID: d6a1bb72-61d0-80a5-a5ce-45e8e46de891
* Content: [Collection evaluation - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/collections/collection-evaluation)
* Content Source: [memdocs/configmgr/core/clients/manage/collections/collection-evaluation.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/collections/collection-evaluation.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by koenraadrens** [comment]
Management Insights has a rule to not use All Systems as a limiting collection.
But when you follow Limiting Collections, you always will end up at the All Systems Collection.
So what's the role for All Systems in the evaluation of collections?
I could replace All Systems with another master collection, but currently don't see the benefit.

**Comment by aczechowski** [comment]
Hi @koenraadrens, thanks for the question. Here's the description of the management insight:

> **Collections limited to All Systems or All Users**: Review any collections that use the All Systems or All Users collections as the limiting collection. Configuration Manager updates the membership of these default collections with data from the Active Directory discovery methods. This data may not be valid information for Configuration Manager clients.

Also link through to the further description from Microsoft Premier on the Services Hub: https://docs.microsoft.com/services-hub/health/remediation-steps-configmgr#collections-limited-to-all-systems-or-all-users, and watch the video there, which helps explain this rule in more detail.

I wouldn't summarize it as "don't use All Systems as a limiting collection." As you mention, you'll need some that are limited on All Systems.

I think the change here is probably just some better links between the two articles to help tie together the full story. Thanks for the feedback.
