### ISSUE TITLE
VPP is a legacy term. 

### ISSUE THREAD

**Issue by josemocha** [MicrosoftDocs/memdocs#97]
This section needs to be retitled and terminology update to reflect Apps & Books and no longer referencing "Legacy VPP." While commonly referred to as VPP that program no longer exists. Tokens will work but need to be renewed in Apple School or Apple Business Manager.
Upgrade to Apple Business Manager to continue using the Device Enrollment Program and Volume Purchase Program. Apple Deployment Programs are no longer available as of December 1, 2019.
https://support.apple.com/en-us/HT208817
Upgrade from Apple Deployment Programs
https://support.apple.com/en-us/HT209617
Migrate to Apps & Books
https://support.apple.com/en-us/HT208257

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6be83bf7-b364-60e3-1b4f-97bbde969ada
* Version Independent ID: 02a2bedd-1af7-3a14-7314-11e0853e4c98
* Content: [Manage Apple volume-purchased apps - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/vpp-apps-ios#feedback)
* Content Source: [memdocs/intune/apps/vpp-apps-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/vpp-apps-ios.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@josemocha - Thanks for the feedback. We have updating several areas of the Intune docs, including the following section:
[Migrate from Volume Purchase Program (VPP) to Apps and Books](https://docs.microsoft.com/mem/intune/apps/vpp-apps-ios#migrate-from-volume-purchase-program-vpp-to-apps-and-books)

I'll also work to make sure the portal UI matches our docs. Again, thanks for the feedback.
