### ISSUE TITLE
Diagnostic Settings

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/memdocs#976]
This section should be updated
https://docs.microsoft.com/en-us/mem/intune/fundamentals/monitor-audit-logs#route-logs-to-azure-monitor

Sending logs to Monitor (Log Analytics) is now done from **Tenant Administration -> Diagnostics Settings**, not the Audit Logs blade.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e5b9d48-b76c-6d66-a4f3-48936c51216b
* Version Independent ID: 208f04ee-503d-c6e8-cedc-59fd720c71bf
* Content: [Audit changes and events in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/fundamentals/monitor-audit-logs)
* Content Source: [memdocs/intune/fundamentals/monitor-audit-logs.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/monitor-audit-logs.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @dougeby
* Microsoft Alias: **dougeby**

**Comment by MandiOhlinger** [comment]
@danmyhre Thank you! The doc changes should be live later today.
