### ISSUE TITLE
Allow users to see deployments for this...

### ISSUE THREAD

**Issue by ofortun** [MicrosoftDocs/memdocs#977]
There is an option in an Application's Supersedence tab that I cannot find documentation for. Is this documented somewhere? I've searched throughout https://docs.microsoft.com/en-us/search/?scope=ConfigMgr

If you open the Application and navigate to the tab, at the bottom there is a checkbox for:
- [x]  Allow users to see deployments for this application and all applications that it supersedes in Software Center. This may result in the user installing multiple applications on the same device, if requirements for these applications are met.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15f78008-e65f-25b5-dee8-e3d93d08bc44
* Version Independent ID: 588fa52b-956b-8142-a788-fa66dd37ebb8
* Content: [Revise and supersede applications - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/apps/deploy-use/revise-and-supersede-applications)
* Content Source: [memdocs/configmgr/apps/deploy-use/revise-and-supersede-applications.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/apps/deploy-use/revise-and-supersede-applications.md)
* Product: **configuration-manager**
* Technology: **configmgr-app**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @ofortun for the feedback. Great question, I don't see anything either. I'm checking with some folks to make sure I understand the scenario, and then will get something added.

**Comment by aczechowski** [comment]
I put in a fix for this issue with the 2010 current branch content. This issue will auto close when that pull request merges, but the change won't be live until we release 2010.
