### ISSUE TITLE
Missing documentation for language setting

### ISSUE THREAD

**Issue by Alam-Arias-LPS** [MicrosoftDocs/memdocs#978]
The JSON template speak of a language settings option
No documentation  of "enable_language_setting"
```
		{
			"key": "enable_language_setting",
			"valueBool": false
		}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff4c5218-bbe4-110c-c74d-3eed1179ac61
* Version Independent ID: b7c148dc-574b-fbed-7637-29699f3eb97a
* Content: [Configure the Microsoft Managed Home Screen app - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-configuration-managed-home-screen-app)
* Content Source: [memdocs/intune/apps/app-configuration-managed-home-screen-app.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-configuration-managed-home-screen-app.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
We have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. If you have continue to have questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

Please use the above channels if you don't already have a solution.
