### ISSUE TITLE
Online course

### ISSUE THREAD

**Issue by asdfg603** [MicrosoftDocs/memdocs#983]
Best Online Arabic Programs, Learn Islamic Sciences and the Holy Quran - Al-dirassa
Learn the Arabic language online easily and quickly, study Islamic sciences and memorize the Holy Quran by Skype with al-
dirassa center. Learn Arabic for All.

https://en.al-dirassa.com/
info@al-dirassa.com
Soffian

**Comment by aczechowski** [comment]
SPam, closing
