### ISSUE TITLE
"Deploy Software updates to MacOS devices" missing

### ISSUE THREAD

**Issue by UolSimon** [MicrosoftDocs/memdocs#984]
Hi.

Earlier last week there was a section called "Deploy Software updates to MacOS devices" that promised the ability to fdeploy critical updates:

![image](https://user-images.githubusercontent.com/52497301/98521894-f14afa80-226b-11eb-84bd-e2ac93c69623.png)

It seems to have suddenly disappeared. Was this by accident? Or has the feature either been completed or abandoned?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66f915d1-8486-44dc-a605-280f979d6f9b
* Version Independent ID: 23c6b2c3-64c1-2df3-ad51-d9be083871a1
* Content: [In development - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/in-development)
* Content Source: [memdocs/intune/fundamentals/in-development.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/in-development.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@uolsimon This feature has been postponed. It'll return to In Development when it's nearer to release. Thanks!
