### ISSUE TITLE
Guidance on Endpoint Protection Device Configuration vs. Endpoint Security

### ISSUE THREAD

**Issue by richardjgreen** [MicrosoftDocs/memdocs#985]
With the "new" Endpoint Security section in Intune focused on security-related settings, there is now an overlap between what can be achieved using existing Device Configuration Profiles vs. what can be achieved with Endpoint Security Policies.

There needs to be a note or guidance on both articles explaining the Pro's and Con's of using either method to apply security related settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6665726-449d-4b0f-bc89-5351cf67f1f8
* Version Independent ID: fdaecc11-5a6a-42a2-f2f1-2fd78a08e445
* Content: [Configure endpoint protection settings in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/endpoint-protection-configure)
* Content Source: [memdocs/intune/protect/endpoint-protection-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/endpoint-protection-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@richardjgreen    Thanks for this submission.  I’ve opened an internal tracking but so I can evaluate this more deeply in the future. Once we can scope this, if it continues to make sense, I’d track that through to a content update (new publications).  With this being tracked by the team and assigned to me via an internal doc bug, I’ll be closing this GitHub issue. I’ve recorded the GitHub issue link in the bug so when we are able to move forward, we should be able to drop an @ to you about that.  

With that said, I can’t provide an ETA for when we'll be able to devote dedicated time to this other than 'sometime after the start of the new year'.  This idea does however fit with a desire to provide better guidance  for why to use Intune in certain ways, and that definitely filters down to why you might use _this_ policy vs _that_, or a _policy_ vs a _security baseline_, and so on.  So yes, to me this ask makes sense.  

For now, I can only say that the initial intent of Endpoint security policies was described as a way to provide security administrators a way to focus on just that, security, without the kitchen sink of available non-security settings found in Device Configuration profiles getting in the way.
