### ISSUE TITLE
Clearify policy to object assignments

### ISSUE THREAD

**Issue by weyCC81** [MicrosoftDocs/memdocs#99]
How are computer policy assigned if there are just users in the assigned group?
How are user policy assigned if there are just computers in the assigned group?

- Always in the "loopback processing mode"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28c32cc0-8eac-5924-81c9-e084eae9bd0e
* Version Independent ID: e7913cc4-023e-b570-ce10-4ee90f785969
* Content: [Use templates for Windows 10 devices in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/administrative-templates-windows)
* Content Source: [memdocs/intune/configuration/administrative-templates-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/administrative-templates-windows.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@weyCC81 Configured ADMX settings assigned to users apply to any device that users enroll, and sign in to. Configured ADMX setting assigned to devices apply to the device, and any user that signs into that device. [User groups vs. device groups](https://docs.microsoft.com/mem/intune/configuration/device-profile-assign#user-groups-vs-device-groups) may be helpful. We updated the article to include this information. The changes should be live later today.

If you think of the total collection of targeted groups as an OU that can include computer and user objects, then you could say we kinda do "loopback processing mode". Hope that helps.
