### ISSUE TITLE
Interactive login description doesn't match actual behaviour

### ISSUE THREAD

**Issue by stefanflegg** [MicrosoftDocs/memdocs#990]
Under Interactive Login there is a setting called "Minutes of lock screen inactivity until screensaver activates". The description suggests that this setting controls how long the device will sit at the lock screen before the screensaver activates. The actual behaviour on my test device is that it will lock the screen after this many minutes of inactivity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f2a095c-452e-c494-a013-0626b9f3728d
* Version Independent ID: a4787d69-187f-fe55-d071-3a37b9b082e9
* Content: [Protection settings for Windows 10 devices in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/endpoint-protection-windows-10)
* Content Source: [memdocs/intune/protect/endpoint-protection-windows-10.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/endpoint-protection-windows-10.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@stefanflegg  Thanks for that feedback. The content reflects what's in our UI, but upon reading the underlying CSP found here: https://docs.microsoft.com/windows/client-management/mdm/policy-csp-localpoliciessecurityoptions#localpoliciessecurityoptions-interactivelogon-machineinactivitylimit I agree with your take on this. I'll update the content later today, but also alert our product team that this description needs to be reviewed.

**Comment by Brenduns** [comment]
@stefanflegg  Its confirmed that the wrong description was used. It should be more simply: **Minutes of inactivity until screensaver activates.**   Our engineering team will revise the text in the UI in a future update, and I'll submit a content edit for the documentation to fix this, which should believe today or tomorrow.
