### ISSUE TITLE
Policy delivery for ADE devices with user affinity

### ISSUE THREAD

**Issue by kevintaber** [MicrosoftDocs/memdocs#991]
Not sure I follow with this statement: "For the fastest policy delivery on ADE devices with user affinity, make sure the enrolling user is a member, prior to device setup, of an Azure AD user group."

I thought that the App Configuration Policy was applied at the device and not the user? The above statement says user.

Hence a Dynamic group using the enrollmentProfileName device attribute can be used to apply the App Config Policy... I assume. If not what's the best practice, or what am I not understanding?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd130267-c54b-41e3-d534-831d4a86bae6
* Version Independent ID: bdfa7eca-a356-3dde-7643-9a759f952007
* Content: [Enroll iOS/iPadOS devices - Automated Device Enrollment - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-ios)
* Content Source: [memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
8851574

**Comment by ErikjeMS** [comment]
Repinged pm...

**Comment by AnyaNovicheva1** [comment]
Hi, I think I may need some more detail around the question here. The statement that is referenced in this doc: https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-ios is separate from app configuration policies. If the question is around app config for the iOS CP, that is automatically applied to the Company Portal upon the creation of the enrollment profile with User Device Affinity. There is no manual app config policy needed for the iOS Company Portal with Automated Device Enrollment with UDA. Enrollment with user device affinity for ADE is done at a device level, that is correct. 

The statement in the documentation regarding dynamic groups in AAD is not related to app config for the CP or any other app. It is just saying that the quicker the user is assigned an AAD group, the faster Intune calculates what policies they need and then they will receive them. At the first check in of the device after ADE enrollment, Intune will know what group the user is in and they'll get their policies and apps, If you assign your users based on the enrollmentProfileName, there will be a slight delay in the device getting the policies. Does this help?

**Comment by ErikjeMS** [comment]
@kevintaber We haven't heard from you on Anya's questions so we're assuming you figured this out. I'll close this issue, but if you have more questions let us know.
