### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by tmachqy** [MicrosoftDocs/memdocs#992]
The link within this section of the article is broken: "Not today, but see the announcement from Microsoft Ignite 2019 on insights-driven device management" [https://myignite.techcommunity.microsoft.com/sessions/81690?source=sessions]. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41018f34-d884-7a61-4b6a-6149968d0673
* Version Independent ID: c39f9160-7165-0654-0dc0-86ac90bebef0
* Content: [FAQ for Desktop Analytics - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/desktop-analytics/faq#bkmk_intune)
* Content Source: [memdocs/configmgr/desktop-analytics/faq.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/desktop-analytics/faq.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @tmachqy for catching that. I found the current link in the archives: https://myignite.microsoft.com/archives/IG19-BRK3086

I'll update it now, the change will go live later today.
