### ISSUE TITLE
Conflicting wording for Min App Version

### ISSUE THREAD

**Issue by JWGrilli** [MicrosoftDocs/memdocs#994]
Under Conditional Launch section in Min App Version, it reads "Specify a value for the minimum _operating system_ value"
Shouldn't it read "application version" instead? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c81b9a99-a379-a3b6-0dde-8781da62d16a
* Version Independent ID: 33b4409f-9687-feb7-07ab-7d6bc0d8b9f5
* Content: [iOS/iPadOS app protection policy settings - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policy-settings-ios)
* Content Source: [memdocs/intune/apps/app-protection-policy-settings-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-protection-policy-settings-ios.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@JWGrilli - Thanks for the feedback. I'm fixing this now.
