### ISSUE TITLE
Unclear statement on when to apply App Configuration Policy for Company Portal

### ISSUE THREAD

**Issue by bryhall** [MicrosoftDocs/memdocs#998]
This [statement](https://docs.microsoft.com/en-us/mem/intune/apps/app-configuration-policies-use-ios#configure-the-company-portal-app-to-support-ios-and-ipados-dep-devices) is unclear:

> DEP (Apple's Device Enrollment Program) enrollments are not compatible with the app store version of the Company Portal app. However, you can configure the Company Portal app to support iOS/iPadOS DEP devices using the following steps.

- In the first sentence it states it DEP enrolled devices are NOT compatible with App Store versions of the Company Portal -- is this a blanket statement and means that it is NOT compatible under any circumstances?
- In the second sentence , it states that the Company Portal can be configured to support DEP devices -- is this referring to only App Store versions fo the Company Portal or VPP versions as well?

It is unclear to me when the prescribed XML app configuration needs to be applied. Does it need to be applied to any iOS/iPadOS device with any version of the Company Portal (regardless if it is from the Apple App Store or from VPP)?  Or is it ONLY needed when the device has a App Store version of the Company Portal.  It's also unclear as to the purpose of this setting

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee33d638-3024-87d5-1b02-c4568478d1ce
* Version Independent ID: fe0f2aa3-b2dc-486a-4883-9c25ee361fe8
* Content: [Add app configuration policies for managed iOS/iPadOS devices - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-configuration-policies-use-ios#configure-the-company-portal-app-to-support-ios-and-ipados-dep-devices)
* Content Source: [memdocs/intune/apps/app-configuration-policies-use-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-configuration-policies-use-ios.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
Thanks for the feedback. I updated the text to help make it more clear. You can use the Company Portal on a DEP device enrolled with or without user affinity be specifically adding a configuration policy and calling out the XML mentioned in step 3. If you have continue to have questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

Please use the above channels if you don't already have a solution.
